window.LIVRO_DATA = {
    nome: "Filemom",
    id: "filemom",
    testament: "NT",

    dados: {
        1: [
            "<span style='font-size: 15px;'><strong>VERSÍCULO: 1</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Paulo, prisioneiro de Jesus Cristo, e o irmão Timóteo, ao amado Filemom, nosso cooperador,<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Grego (Textus Receptus):</strong> Παῦλος δέσμιος Χριστοῦ Ἰησοῦ, καὶ Τιμόθεος ὁ ἀδελφός, Φιλήμονι τῷ ἀγαπητῷ καὶ συνεργῷ ἡμῶν,<br>",
            "🔤 <strong>Transliteração:</strong> Paulos desmios Christou Iēsou, kai Timotheos ho adelphos, Philēmoni tō agapētō kai synergō hēmōn,<br>",
            "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) Παῦλος δέσμιος Χριστοῦ Ἰησοῦ, καὶ Τιμόθεος ὁ ἀδελφός, Φιλήμονι τῷ ἀγαπητῷ καὶ συνεργῷ ἡμῶν,<br>",
            "🇻🇦 <strong>Vulgata:</strong> Paulus vinctus Christi Iesu et Timotheus frater Philemoni dilecto et adiutori nostro<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>δέσμιος</em> – 'prisioneiro' – acorrentado, prisioneiro por Cristo. <em>Χριστοῦ Ἰησοῦ</em> – 'de Jesus Cristo' – pertencente a Cristo, prisioneiro por causa de Cristo. <em>Τιμόθεος</em> – 'Timóteo' – companheiro de Paulo, co-enviado. <em>Φιλήμονι</em> – 'Filemom' – nome que significa 'amigável' ou 'amoroso'. <em>ἀγαπητῷ</em> – 'amado' – querido, amado. <em>συνεργῷ</em> – 'cooperador' – colaborador, companheiro de trabalho no evangelho.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Paulo se identifica como prisioneiro, não de Roma, mas de Cristo. A prisão física é uma oportunidade de serviço espiritual. Cristo é o Senhor que mesmo preso serve. Filemom é um exemplo de liderança cristã (cooperador) e amor (amado).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> A saudação de Paulo é pessoal e cheia de afeto. Ele se identifica como prisioneiro, não por crimes, mas por sua fé em Cristo. Timóteo é incluído na saudação, mostrando a comunhão dos santos.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Mesmo em prisões, podemos servir a Cristo. Valorizemos os cooperadores na obra de Deus.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 2</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> E à nossa amada Áfia, e a Arquipo, nosso companheiro de lutas, e à igreja que está em tua casa:<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Grego (Textus Receptus):</strong> καὶ Ἀπφίᾳ τῇ ἀγαπητῇ, καὶ Ἀρχίππῳ τῷ συστρατιώτῃ ἡμῶν, καὶ τῇ κατ᾽ οἶκόν σου ἐκκλησίᾳ·<br>",
            "🔤 <strong>Transliteração:</strong> kai Apphia tē agapētē, kai Archippō tō systratiōtē hēmōn, kai tē kat' oikon sou ekklēsia;<br>",
            "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) καὶ Ἀπφίᾳ τῇ ἀγαπητῇ, καὶ Ἀρχίππῳ τῷ συστρατιώτῃ ἡμῶν, καὶ τῇ κατ᾽ οἶκόν σου ἐκκλησίᾳ·<br>",
            "🇻🇦 <strong>Vulgata:</strong> et Appiae sorori carissimae et Archippo commilitoni nostro et ecclesiae quae in domo tua est<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>Ἀπφίᾳ</em> – 'Áfia' – provavelmente a esposa de Filemom, nome de origem frígia. <em>ἀγαπητῇ</em> – 'amada' – querida, amada no Senhor. <em>Ἀρχίππῳ</em> – 'Arquipo' – possivelmente filho de Filemom (Cl 4:17). <em>συστρατιώτῃ</em> – 'companheiro de lutas' – co-soldado, companheiro na batalha espiritual. <em>κατ᾽ οἶκόν</em> – 'em tua casa' – a igreja doméstica, reunida na casa de Filemom.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A igreja na casa de Filemom mostra o modelo de comunhão cristã primitiva. A família de Filemom é ativa na obra de Deus. Cristo é o Senhor da casa e da igreja. Arquipo é um soldado de Cristo, lutando ao lado de Paulo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Paulo inclui Áfia (esposa de Filemom) e Arquipo (provavelmente seu filho) na saudação, mostrando o envolvimento familiar na igreja.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> A igreja deve estar presente em nossas casas. A família deve ser ativa na obra de Deus.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 3</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Graça a vós e paz da parte de Deus nosso Pai e do Senhor Jesus Cristo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Grego (Textus Receptus):</strong> χάρις ὑμῖν καὶ εἰρήνη ἀπὸ Θεοῦ πατρὸς ἡμῶν καὶ Κυρίου Ἰησοῦ Χριστοῦ.<br>",
            "🔤 <strong>Transliteração:</strong> charis hymin kai eirēnē apo Theou patros hēmōn kai Kyriou Iēsou Christou.<br>",
            "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) χάρις ὑμῖν καὶ εἰρήνη ἀπὸ Θεοῦ πατρὸς ἡμῶν καὶ Κυρίου Ἰησοῦ Χριστοῦ.<br>",
            "🇻🇦 <strong>Vulgata:</strong> gratia vobis et pax a Deo Patre nostro et Domino Iesu Christo<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>χάρις</em> – 'graça' – favor imerecido, a base da salvação e da vida cristã. <em>εἰρήνη</em> – 'paz' – reconciliação com Deus e paz interior. <em>ἀπὸ</em> – 'da parte de' – a fonte da graça e da paz. <em>Θεοῦ πατρὸς</em> – 'Deus Pai' – o Pai como fonte de toda bênção. <em>Κυρίου Ἰησοῦ Χριστοῦ</em> – 'Senhor Jesus Cristo' – o mediador da graça e da paz.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A graça e a paz são os dons essenciais de Deus. Cristo é o canal da graça e da paz. A trindade está implícita na saudação (Pai, Filho e o Espírito implícito).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> A saudação paulina padrão é adaptada para incluir Filemom e sua família, mostrando a bênção sobre a igreja doméstica.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Vivamos na graça e na paz de Deus. Recebamos estes dons do Pai e de Cristo.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 4</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Sempre dou graças ao meu Deus, fazendo menção de ti nas minhas orações,<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Grego (Textus Receptus):</strong> Εὐχαριστῶ τῷ Θεῷ μου πάντοτε, μνείαν σου ποιούμενος ἐπὶ τῶν προσευχῶν μου,<br>",
            "🔤 <strong>Transliteração:</strong> Eucharistō tō Theō mou pantote, mneian sou poioumenos epi tōn proseuchōn mou,<br>",
            "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) Εὐχαριστῶ τῷ Θεῷ μου πάντοτε, μνείαν σου ποιούμενος ἐπὶ τῶν προσευχῶν μου,<br>",
            "🇻🇦 <strong>Vulgata:</strong> gratias ago Deo meo semper memoriam tui faciens in orationibus meis<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>Εὐχαριστῶ</em> – 'dou graças' – agradeço, expresso gratidão. <em>Θεῷ μου</em> – 'meu Deus' – relacionamento pessoal de Paulo com Deus. <em>μνείαν</em> – 'menção' – lembrança, recordação. <em>ποιούμενος</em> – 'fazendo' – fazendo menção, lembrando. <em>προσευχῶν</em> – 'orações' – orações, súplicas.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A oração intercessória é uma expressão de amor. Cristo intercede continuamente por nós (Hebreus 7:25). Paulo modela a vida de oração, lembrando-se dos irmãos com gratidão.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Paulo expressa sua gratidão a Deus por Filemom e o lembra em suas orações.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Lembremo-nos uns dos outros em oração com gratidão. A oração fortalece a comunhão.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 5</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Ouvindo do teu amor e da fé que tens para com o Senhor Jesus Cristo e para com todos os santos.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Grego (Textus Receptus):</strong> ἀκούων σου τὴν ἀγάπην καὶ τὴν πίστιν, ἣν ἔχεις πρὸς τὸν Κύριον Ἰησοῦν, καὶ εἰς πάντας τοὺς ἁγίους·<br>",
            "🔤 <strong>Transliteração:</strong> akouōn sou tēn agapēn kai tēn pistin, hēn echeis pros ton Kyrion Iēsoun, kai eis pantas tous hagious;<br>",
            "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) ἀκούων σου τὴν ἀγάπην καὶ τὴν πίστιν, ἣν ἔχεις πρὸς τὸν Κύριον Ἰησοῦν, καὶ εἰς πάντας τοὺς ἁγίους·<br>",
            "🇻🇦 <strong>Vulgata:</strong> audiens caritatem tuam et fidem quam habes in Domino Iesu et in omnes sanctos<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>ἀκούων</em> – 'Ouvindo' – ouvindo, tendo notícia. <em>ἀγάπην</em> – 'amor' – amor ágape, amor sacrificial. <em>πίστιν</em> – 'fé' – confiança, fé. <em>πρὸς</em> – 'para com' – em direção a, em relação a. <em>Κύριον Ἰησοῦν</em> – 'Senhor Jesus' – Cristo como Senhor. <em>ἁγίους</em> – 'santos' – os crentes, separados para Deus.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A fé e o amor andam juntos. A fé em Cristo se manifesta no amor pelos santos. Cristo é o objeto da fé e a fonte do amor. O amor pelos irmãos é evidência do amor a Cristo (1 João 4:20).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Paulo ouviu falar do amor e da fé de Filemom, que se manifestam tanto para com Cristo quanto para com os santos.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Nossa fé em Cristo deve ser acompanhada de amor pelos irmãos. Sejamos conhecidos por nosso amor.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 6</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Para que a comunicação da tua fé seja eficaz no conhecimento de todo o bem que em vós há por Cristo Jesus.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Grego (Textus Receptus):</strong> ὅπως ἡ κοινωνία τῆς πίστεώς σου ἐνεργὴς γένηται ἐν ἐπιγνώσει παντὸς ἀγαθοῦ τοῦ ἐν ὑμῖν εἰς Χριστὸν Ἰησοῦν.<br>",
            "🔤 <strong>Transliteração:</strong> hopōs hē koinōnia tēs pisteōs sou energēs genētai en epignōsei pantos agathou tou en hymin eis Christon Iēsoun.<br>",
            "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) ὅπως ἡ κοινωνία τῆς πίστεώς σου ἐνεργὴς γένηται ἐν ἐπιγνώσει παντὸς ἀγαθοῦ τοῦ ἐν ὑμῖν εἰς Χριστὸν Ἰησοῦν.<br>",
            "🇻🇦 <strong>Vulgata:</strong> ut communicatio fidei tuae evidens fiat in agnitione omnis operis boni quod est in vobis in Christo Iesu<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>κοινωνία</em> – 'comunicação' – comunhão, participação, compartilhamento. <em>ἐνεργὴς</em> – 'eficaz' – ativa, eficaz. <em>ἐπιγνώσει</em> – 'conhecimento' – pleno conhecimento, compreensão. <em>ἀγαθοῦ</em> – 'bem' – bom, benéfico, bondade. <em>ἐν ὑμῖν</em> – 'em vós' – em vocês, entre vocês. <em>εἰς Χριστὸν Ἰησοῦν</em> – 'por Cristo Jesus' – em direção a Cristo, para a glória de Cristo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A fé compartilhada produz fruto. Cristo é o centro de todo o bem que há nos crentes. A comunhão na fé leva ao conhecimento de toda boa obra em Cristo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Paulo ora para que a comunhão da fé de Filemom seja eficaz no pleno conhecimento de todo o bem que há em Cristo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Nossa fé deve ser compartilhada e eficaz. O conhecimento de Cristo produz boas obras.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 7</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Porque temos grande gozo e consolação do teu amor, porquanto as entranhas dos santos têm sido recreadas por ti, irmão.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Grego (Textus Receptus):</strong> χαρὰν γὰρ πολλὴν ἔσχομεν καὶ παράκλησιν ἐπὶ τῇ ἀγάπῃ σου, ὅτι τὰ σπλάγχνα τῶν ἁγίων ἀναπέπαυται διὰ σοῦ, ἀδελφέ.<br>",
            "🔤 <strong>Transliteração:</strong> charan gar pollēn eschomen kai paraklēsin epi tē agapē sou, hoti ta splanchna tōn hagiōn anapepautai dia sou, adelphe.<br>",
            "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) χαρὰν γὰρ πολλὴν ἔσχομεν καὶ παράκλησιν ἐπὶ τῇ ἀγάπῃ σου, ὅτι τὰ σπλάγχνα τῶν ἁγίων ἀναπέπαυται διὰ σοῦ, ἀδελφέ.<br>",
            "🇻🇦 <strong>Vulgata:</strong> gaudium enim magnum habui et consolationem in caritate tua quia viscera sanctorum requieverunt per te frater<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>χαρὰν</em> – 'gozo' – alegria, regozijo. <em>παράκλησιν</em> – 'consolação' – encorajamento, consolo. <em>σπλάγχνα</em> – 'entranhas' – sentimentos profundos, compaixão, amor íntimo. <em>ἀναπέπαυται</em> – 'têm sido recreadas' – foram revigoradas, descansaram, foram confortadas. <em>διὰ σοῦ</em> – 'por ti' – através de você, por sua causa. <em>ἀδελφέ</em> – 'irmão' – expressão de afeto fraternal.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> O amor de Filemom trouxe alegria e consolo a Paulo e aos santos. Cristo é a fonte do amor que recreia os corações. O amor prático é uma expressão do amor de Cristo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Paulo testemunha a alegria e o consolo que o amor de Filemom trouxe, especialmente por ter recreado os santos.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Nosso amor deve trazer alegria e consolo aos irmãos. Sejamos canais do amor de Cristo.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 8</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Pelo que, ainda que tenha em Cristo muita confiança para te mandar o que convém,<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Grego (Textus Receptus):</strong> Διό, πολλὴν ἐν Χριστῷ παρρησίαν ἔχων ἐπιτάσσειν σοι τὸ ἀνῆκον,<br>",
            "🔤 <strong>Transliteração:</strong> Dio, pollēn en Christō parrēsian echōn epitassein soi to anēkon,<br>",
            "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) Διό, πολλὴν ἐν Χριστῷ παρρησίαν ἔχων ἐπιτάσσειν σοι τὸ ἀνῆκον,<br>",
            "🇻🇦 <strong>Vulgata:</strong> propter quod multam fiduciam habens in Christo imperandi tibi quod oportet<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>παρρησίαν</em> – 'confiança' – ousadia, franqueza, confiança. <em>ἐπιτάσσειν</em> – 'mandar' – ordenar, dar ordem. <em>ἀνῆκον</em> – 'convém' – apropriado, conveniente, devido.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Paulo tem autoridade apostólica para mandar, mas escolhe apelar pelo amor. Cristo tem autoridade sobre todos, mas age com amor. A autoridade cristã é exercida com humildade.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Paulo reconhece sua autoridade apostólica, mas prefere não usá-la, optando por um apelo amoroso.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> A autoridade deve ser exercida com amor. A humildade é mais persuasiva que a imposição.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 9</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Contudo, peço-te antes por amor, sendo eu tal como sou, Paulo, já velho, e também agora prisioneiro de Jesus Cristo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Grego (Textus Receptus):</strong> διὰ τὴν ἀγάπην μᾶλλον παρακαλῶ, τοιοῦτος ὢν ὡς Παῦλος πρεσβύτης, νυνὶ δὲ καὶ δέσμιος Ἰησοῦ Χριστοῦ·<br>",
            "🔤 <strong>Transliteração:</strong> dia tēn agapēn mallon parakalō, toioutos ōn hōs Paulos presbytēs, nyni de kai desmios Iēsou Christou;<br>",
            "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) διὰ τὴν ἀγάπην μᾶλλον παρακαλῶ, τοιοῦτος ὢν ὡς Παῦλος πρεσβύτης, νυνὶ δὲ καὶ δέσμιος Ἰησοῦ Χριστοῦ·<br>",
            "🇻🇦 <strong>Vulgata:</strong> propter caritatem magis obsecro cum sis talis ut Paulus senex nunc autem et vinctus Iesu Christi<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>παρακαλῶ</em> – 'peço' – exorto, peço, suplico. <em>πρεσβύτης</em> – 'velho' – idoso, ancião (pode ser 'embaixador' em alguns manuscritos, mas a maioria traduz como 'velho'). <em>δέσμιος</em> – 'prisioneiro' – acorrentado, prisioneiro.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Paulo apela com base em sua idade e prisão. Cristo foi despojado de Sua glória para nos salvar (Filipenses 2:6-8). A humildade e o sofrimento são argumentos poderosos para o amor.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Paulo prefere apelar por amor, lembrando Filemom de sua idade e de sua condição de prisioneiro.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> O amor é mais poderoso que a autoridade. A humildade e o sofrimento podem tocar corações.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 10</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Peço-te por meu filho Onésimo, que gerei nas minhas prisões,<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Grego (Textus Receptus):</strong> παρακαλῶ σε περὶ τοῦ ἐμοῦ τέκνου, ὃν ἐγέννησα ἐν τοῖς δεσμοῖς μου, Ὀνήσιμον,<br>",
            "🔤 <strong>Transliteração:</strong> parakalō se peri tou emou teknou, hon egennēsa en tois desmois mou, Onēsimon,<br>",
            "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) παρακαλῶ σε περὶ τοῦ ἐμοῦ τέκνου, ὃν ἐγέννησα ἐν τοῖς δεσμοῖς μου, Ὀνήσιμον,<br>",
            "🇻🇦 <strong>Vulgata:</strong> obsecro te de meo filio quem genui in vinculis Onesimo<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>τέκνου</em> – 'filho' – filho espiritual, convertido por Paulo. <em>ἐγέννησα</em> – 'gerei' – dei à luz espiritualmente, converti. <em>δεσμοῖς</em> – 'prisões' – cadeias, correntes. <em>Ὀνήσιμον</em> – 'Onésimo' – nome que significa 'útil' ou 'proveitoso'.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Onésimo é filho espiritual de Paulo, nascido em prisão. Cristo gera filhos espirituais através da proclamação do evangelho (1 Coríntios 4:15). O nome Onésimo (útil) será contrastado com sua inutilidade passada.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Paulo apresenta Onésimo como seu filho na fé, gerado durante seu encarceramento.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> A obra de evangelismo pode acontecer em qualquer lugar, até mesmo na prisão. O evangelho gera filhos espirituais.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 11</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> O qual noutro tempo te foi inútil, mas agora a ti e a mim muito útil.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Grego (Textus Receptus):</strong> τόν ποτέ σοι ἄχρηστον, νυνὶ δὲ σοὶ καὶ ἐμοὶ εὔχρηστον,<br>",
            "🔤 <strong>Transliteração:</strong> ton pote soi achrēston, nyni de soi kai emoi euchrēston,<br>",
            "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) τόν ποτέ σοι ἄχρηστον, νυνὶ δὲ σοὶ καὶ ἐμοὶ εὔχρηστον,<br>",
            "🇻🇦 <strong>Vulgata:</strong> qui tibi aliquando inutilis est nunc autem et tibi et mihi utilis<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>ἄχρηστον</em> – 'inútil' – sem utilidade, inútil. <em>νυνὶ</em> – 'agora' – agora, no presente. <em>εὔχρηστον</em> – 'útil' – útil, proveitoso.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> O jogo de palavras com o nome de Onésimo (útil). Cristo transforma o inútil em útil. A graça de Deus transforma vidas (2 Coríntios 5:17). O que era inútil para o mundo se torna útil para o reino.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Paulo brinca com o nome de Onésimo, dizendo que antes era inútil, mas agora é útil tanto para Filemom quanto para ele.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> O evangelho transforma vidas inúteis em úteis. Nossa utilidade vem de Cristo.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 12</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> E eu to envio de volta; recebe-o, pois, como ao meu próprio coração.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Grego (Textus Receptus):</strong> ὃν ἀνέπεμψά σοι, αὐτὸν τοῦτ᾽ ἔστι τὰ ἐμὰ σπλάγχνα·<br>",
            "🔤 <strong>Transliteração:</strong> hon anepempsa soi, auton tout' esti ta ema splanchna;<br>",
            "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) ὃν ἀνέπεμψά σοι, αὐτὸν τοῦτ᾽ ἔστι τὰ ἐμὰ σπλάγχνα·<br>",
            "🇻🇦 <strong>Vulgata:</strong> quem remisi tibi tu autem illum id est viscera mea suscipe<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>ἀνέπεμψα</em> – 'envio de volta' – enviar de volta, restituir. <em>σπλάγχνα</em> – 'coração' – entranhas, sentimentos profundos, afeto íntimo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Onésimo é o coração de Paulo. Cristo nos recebe como membros de Seu corpo, como Seu próprio coração. A restituição de Onésimo é um ato de fé e amor.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Paulo envia Onésimo de volta a Filemom, pedindo que ele seja recebido como se fosse o próprio coração de Paulo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Recebamos os irmãos com amor profundo. Cada crente é precioso como o coração de Cristo.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 13</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Eu bem quisera retê-lo comigo, para que por ti me servisse nas prisões do evangelho;<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Grego (Textus Receptus):</strong> ὃν ἐγὼ ἐβουλόμην πρὸς ἐμαυτὸν κατέχειν, ἵνα ὑπὲρ σοῦ μοι διακονῇ ἐν τοῖς δεσμοῖς τοῦ εὐαγγελίου·<br>",
            "🔤 <strong>Transliteração:</strong> hon egō eboulomēn pros emauton katechein, hina hyper sou moi diakonē en tois desmois tou euangeliou;<br>",
            "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) ὃν ἐγὼ ἐβουλόμην πρὸς ἐμαυτὸν κατέχειν, ἵνα ὑπὲρ σοῦ μοι διακονῇ ἐν τοῖς δεσμοῖς τοῦ εὐαγγελίου·<br>",
            "🇻🇦 <strong>Vulgata:</strong> quem ego volueram mecum retinere ut pro te mihi ministraret in vinculis evangelii<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>ἐβουλόμην</em> – 'quisera' – queria, desejava. <em>κατέχειν</em> – 'retê-lo' – reter, guardar. <em>διακονῇ</em> – 'servisse' – servir, ministrar. <em>δεσμοῖς</em> – 'prisões' – cadeias, correntes. <em>εὐαγγελίου</em> – 'evangelho' – boas novas.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Paulo desejava que Onésimo o servisse na prisão. Cristo veio para servir e não para ser servido (Marcos 10:45). O serviço na prisão é visto como serviço ao evangelho.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Paulo queria reter Onésimo para que ele o servisse na prisão, representando Filemom.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> O serviço cristão pode ser realizado em qualquer lugar. Servir aos presos é servir a Cristo.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 14</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Mas nada quis fazer sem o teu parecer, para que o teu benefício não fosse como por força, mas, voluntariamente.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Grego (Textus Receptus):</strong> χωρὶς δὲ τῆς σῆς γνώμης οὐδὲν ἠθέλησα ποιῆσαι, ἵνα μὴ ὡς κατὰ ἀνάγκην τὸ ἀγαθόν σου ᾖ, ἀλλὰ κατὰ ἑκούσιον.<br>",
            "🔤 <strong>Transliteração:</strong> chōris de tēs sēs gnōmēs ouden ēthelēsa poiēsai, hina mē hōs kata anankēn to agathon sou ē, alla kata hekousion.<br>",
            "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) χωρὶς δὲ τῆς σῆς γνώμης οὐδὲν ἠθέλησα ποιῆσαι, ἵνα μὴ ὡς κατὰ ἀνάγκην τὸ ἀγαθόν σου ᾖ, ἀλλὰ κατὰ ἑκούσιον.<br>",
            "🇻🇦 <strong>Vulgata:</strong> sine consilio autem tuo nihil volui facere ut ne velut ex necessitate bonum tuum esset sed voluntarium<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>χωρὶς</em> – 'sem' – sem, à parte de. <em>γνώμης</em> – 'parecer' – opinião, consentimento. <em>ἀνάγκην</em> – 'por força' – necessidade, obrigação. <em>ἑκούσιον</em> – 'voluntariamente' – voluntário, espontâneo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Paulo valoriza a decisão voluntária de Filemom. Cristo nos chama a servi-Lo voluntariamente, não por obrigação (2 Coríntios 9:7). O amor é voluntário e não forçado.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Paulo não quis agir sem o consentimento de Filemom, para que seu ato de bondade fosse voluntário, não forçado.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Nossas boas obras devem ser voluntárias. O amor verdadeiro é dado livremente.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 15</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Porque bem pode ser que ele se tenha separado de ti por algum tempo, para que o recebesses para sempre,<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Grego (Textus Receptus):</strong> τάχα γὰρ διὰ τοῦτο ἐχωρίσθη πρὸς ὥραν, ἵνα αἰώνιον αὐτὸν ἀπέχῃς,<br>",
            "🔤 <strong>Transliteração:</strong> tacha gar dia touto echōristhē pros hōran, hina aiōnion auton apechēs,<br>",
            "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) τάχα γὰρ διὰ τοῦτο ἐχωρίσθη πρὸς ὥραν, ἵνα αἰώνιον αὐτὸν ἀπέχῃς,<br>",
            "🇻🇦 <strong>Vulgata:</strong> forsitan enim ideo discessit ad horam ut aeternum illum reciperes<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>τάχα</em> – 'bem pode ser' – talvez, provavelmente. <em>ἐχωρίσθη</em> – 'separado' – foi separado, se afastou. <em>πρὸς ὥραν</em> – 'por algum tempo' – por uma hora, por um breve período. <em>αἰώνιον</em> – 'para sempre' – eterno, para sempre. <em>ἀπέχῃς</em> – 'recebesses' – receber de volta, ter de volta.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A separação temporária pode ter um propósito eterno. Cristo se separou de nós por um tempo para nos reconciliar eternamente (Hebreus 9:12). A soberania de Deus usa até mesmo a separação para um bem maior.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Paulo sugere que a separação temporária de Onésimo pode ter sido providencial para que Filemom o recebesse para sempre.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Deus pode usar até mesmo situações dolorosas para um propósito eterno. Confiemos em Sua soberania.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 16</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Não já como servo, antes, mais do que servo, como irmão amado, particularmente de mim, e quanto mais de ti, assim na carne como no Senhor.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Grego (Textus Receptus):</strong> οὐκέτι ὡς δοῦλον, ἀλλ᾽ ὑπὲρ δοῦλον, ἀδελφὸν ἀγαπητόν, μάλιστα ἐμοί, πόσῳ δὲ μᾶλλον σοὶ, καὶ ἐν σαρκὶ καὶ ἐν Κυρίῳ.<br>",
            "🔤 <strong>Transliteração:</strong> ouketi hōs doulon, all' hyper doulon, adelphon agapēton, malista emoi, posō de mallon soi, kai en sarki kai en Kyriō.<br>",
            "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) οὐκέτι ὡς δοῦλον, ἀλλ᾽ ὑπὲρ δοῦλον, ἀδελφὸν ἀγαπητόν, μάλιστα ἐμοί, πόσῳ δὲ μᾶλλον σοὶ, καὶ ἐν σαρκὶ καὶ ἐν Κυρίῳ.<br>",
            "🇻🇦 <strong>Vulgata:</strong> iam non ut servum sed pro servo fratrem carissimum maxime mihi quanto autem magis tibi et in carne et in Domino<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>οὐκέτι</em> – 'Não já' – não mais, já não. <em>δοῦλον</em> – 'servo' – escravo, servo. <em>ὑπὲρ δοῦλον</em> – 'mais do que servo' – acima de servo, melhor que servo. <em>ἀδελφὸν</em> – 'irmão' – irmão em Cristo. <em>ἐν σαρκὶ</em> – 'na carne' – na vida física, como ser humano. <em>ἐν Κυρίῳ</em> – 'no Senhor' – na comunhão com Cristo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A nova relação em Cristo transcende as relações sociais. Cristo nos torna irmãos, independentemente de status social (Gálatas 3:28). Onésimo é irmão, não apenas servo, tanto na carne (como ser humano) quanto no Senhor (como cristão).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Onésimo não deve ser recebido apenas como servo, mas como irmão amado, tanto na carne quanto no Senhor.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Em Cristo, somos irmãos. As distinções sociais são superadas pelo amor fraternal.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 17</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Assim, pois, se me tens por companheiro, recebe-o como a mim mesmo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Grego (Textus Receptus):</strong> εἰ οὖν με ἔχεις κοινωνόν, προσλαβοῦ αὐτὸν ὡς ἐμέ.<br>",
            "🔤 <strong>Transliteração:</strong> ei oun me echeis koinōnon, proslabou auton hōs eme.<br>",
            "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) εἰ οὖν με ἔχεις κοινωνόν, προσλαβοῦ αὐτὸν ὡς ἐμέ.<br>",
            "🇻🇦 <strong>Vulgata:</strong> si ergo habes me socium suscipe illum sicut me<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>κοινωνόν</em> – 'companheiro' – parceiro, participante, sócio na fé. <em>προσλαβοῦ</em> – 'recebe' – receber, acolher. <em>ὡς ἐμέ</em> – 'como a mim' – como se fosse a mim mesmo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Receber Onésimo é receber o próprio Paulo. Cristo nos identifica com Ele (Mateus 25:40). A união com Cristo significa que somos representados uns pelos outros.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Paulo pede a Filemom que receba Onésimo como se fosse o próprio Paulo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Recebamos os irmãos como receberíamos a Cristo. A hospitalidade cristã é uma expressão de amor.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 18</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> E, se te fez algum dano ou te deve alguma coisa, põe isso na minha conta.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Grego (Textus Receptus):</strong> εἰ δέ τι ἠδίκησέ σε ἢ ὀφείλει, τοῦτο ἐμοὶ ἐλλόγα·<br>",
            "🔤 <strong>Transliteração:</strong> ei de ti ēdikēse se ē opheilei, touto emoi elloga;<br>",
            "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) εἰ δέ τι ἠδίκησέ σε ἢ ὀφείλει, τοῦτο ἐμοὶ ἐλλόγα·<br>",
            "🇻🇦 <strong>Vulgata:</strong> si autem aliquid nocuit tibi aut debet hoc mihi inputa<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>ἠδίκησε</em> – 'fez dano' – injustiçou, prejudicou. <em>ὀφείλει</em> – 'deve' – está em débito. <em>ἐλλόγα</em> – 'põe na minha conta' – cobrar de mim, imputar a mim.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Paulo se oferece para pagar a dívida de Onésimo. Cristo pagou nossa dívida de pecado (Colossenses 2:14). O princípio da substituição é central no evangelho.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Paulo assume a responsabilidade por qualquer dívida ou dano que Onésimo tenha causado.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> O amor cobre as dívidas dos outros. Cristo pagou nossa dívida e nos chama a perdoar.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 19</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Eu, Paulo, de minha própria mão o escrevo; eu o pagarei, para te não dizer que ainda a ti mesmo a ti te deves.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Grego (Textus Receptus):</strong> ἐγὼ Παῦλος ἔγραψα τῇ ἐμῇ χειρί, ἐγὼ ἀποτίσω· ἵνα μὴ λέγω σοι ὅτι καὶ σεαυτόν μοι προσοφείλεις.<br>",
            "🔤 <strong>Transliteração:</strong> egō Paulos egrapsa tē emē cheiri, egō apotisō; hina mē legō soi hoti kai seauton moi prosopheileis.<br>",
            "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) ἐγὼ Παῦλος ἔγραψα τῇ ἐμῇ χειρί, ἐγὼ ἀποτίσω· ἵνα μὴ λέγω σοι ὅτι καὶ σεαυτόν μοι προσοφείλεις.<br>",
            "🇻🇦 <strong>Vulgata:</strong> ego Paulus scripsi mea manu ego reddam ut non dicam tibi quod et te ipsum mihi debes<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>ἔγραψα</em> – 'escrevo' – escrevi (aoristo epistolar). <em>ἀποτίσω</em> – 'pagarei' – pagarei, reembolsarei. <em>προσοφείλεις</em> – 'deves' – está em débito, devedor.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Paulo assume a dívida com sua própria assinatura. Cristo selou nossa redenção com Seu próprio sangue (Hebreus 9:12). A promessa de Paulo é uma garantia pessoal.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Paulo escreve de próprio punho, prometendo pagar, lembrando Filemom que ele mesmo é devedor a Paulo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Nossas promessas devem ser cumpridas. A dívida do amor nunca pode ser totalmente paga.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 20</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Sim, irmão, eu me regozijarei de ti no Senhor; recreia as minhas entranhas no Senhor.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Grego (Textus Receptus):</strong> ναί, ἀδελφέ, ἐγώ σου ὀναίμην ἐν Κυρίῳ· ἀνάπαυσόν μου τὰ σπλάγχνα ἐν Κυρίῳ.<br>",
            "🔤 <strong>Transliteração:</strong> nai, adelphe, egō sou onaimēn en Kyriō; anapauson mou ta splanchna en Kyriō.<br>",
            "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) ναί, ἀδελφέ, ἐγώ σου ὀναίμην ἐν Κυρίῳ· ἀνάπαυσόν μου τὰ σπλάγχνα ἐν Κυρίῳ.<br>",
            "🇻🇦 <strong>Vulgata:</strong> ita frater ego te fruar in Domino refice viscera mea in Domino<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>ὀναίμην</em> – 'regozijarei' – que eu possa me alegrar, ter benefício. <em>ἀνάπαυσον</em> – 'recreia' – revigora, descansa. <em>σπλάγχνα</em> – 'entranhas' – sentimentos profundos, coração.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Paulo pede a Filemom que recreie seu coração no Senhor. Cristo é a fonte de todo consolo e alegria (2 Coríntios 1:3-4). A alegria no Senhor é o maior benefício.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Paulo expressa seu desejo de se alegrar no Senhor por causa da atitude de Filemom.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Nossas ações devem trazer alegria aos outros no Senhor. Sejamos fonte de consolo.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 21</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Escrevo-te confiado na tua obediência, sabendo que farás ainda mais do que digo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Grego (Textus Receptus):</strong> πεποιθὼς τῇ ὑπακοῇ σου ἔγραψά σοι, εἰδὼς ὅτι καὶ ὑπὲρ ἃ λέγω ποιήσεις.<br>",
            "🔤 <strong>Transliteração:</strong> pepoithōs tē hypakoē sou egrapsa soi, eidōs hoti kai hyper ha legō poiēseis.<br>",
            "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) πεποιθὼς τῇ ὑπακοῇ σου ἔγραψά σοι, εἰδὼς ὅτι καὶ ὑπὲρ ἃ λέγω ποιήσεις.<br>",
            "🇻🇦 <strong>Vulgata:</strong> confidens oboedientia tua scripsi tibi sciens quoniam et super id quod dico facies<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>πεποιθὼς</em> – 'confiado' – confiando, persuadido. <em>ὑπακοῇ</em> – 'obediência' – obediência, submissão. <em>ὑπὲρ</em> – 'mais do que' – além de, mais do que.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Paulo confia na obediência de Filemom. Cristo confia em nós para fazer mais do que pedimos (Efésios 3:20). A confiança motiva a ação generosa.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Paulo expressa confiança na obediência de Filemom, esperando que ele faça ainda mais do que lhe é pedido.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Sejamos obedientes e generosos. A confiança dos outros em nós deve nos motivar a ir além.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 22</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> E juntamente prepara-me também pousada, porque espero que pelas vossas orações vos hei de ser concedido.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Grego (Textus Receptus):</strong> ἅμα δὲ καὶ ἑτοίμαζέ μοι ξενίαν· ἐλπίζω γὰρ ὅτι διὰ τῶν προσευχῶν ὑμῶν χαρισθήσομαι ὑμῖν.<br>",
            "🔤 <strong>Transliteração:</strong> hama de kai hetoimaze moi xenian; elpizō gar hoti dia tōn proseuchōn hymōn charisthēsomai hymin.<br>",
            "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) ἅμα δὲ καὶ ἑτοίμαζέ μοι ξενίαν· ἐλπίζω γὰρ ὅτι διὰ τῶν προσευχῶν ὑμῶν χαρισθήσομαι ὑμῖν.<br>",
            "🇻🇦 <strong>Vulgata:</strong> simul autem et para mihi hospitium spero enim quia per orationes vestras donabor vobis<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>ἑτοίμαζε</em> – 'prepara' – preparar, aprontar. <em>ξενίαν</em> – 'pousada' – hospitalidade, hospedagem. <em>χαρισθήσομαι</em> – 'concedido' – serei concedido, presenteado.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Paulo espera ser libertado pela oração. Cristo prometeu que onde dois ou três estiverem reunidos em Seu nome, Ele estaria presente (Mateus 18:20). A oração da igreja pode abrir portas.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Paulo pede que Filemom prepare hospedagem, esperando ser libertado através das orações da igreja.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> A oração da igreja pode libertar. Preparemo-nos para receber os servos de Deus.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 23</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Saúdam-te Epafras, meu companheiro de prisão em Cristo Jesus,<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Grego (Textus Receptus):</strong> Ἀσπάζεταί σε Ἐπαφρᾶς, ὁ συναιχμάλωτός μου ἐν Χριστῷ Ἰησοῦ·<br>",
            "🔤 <strong>Transliteração:</strong> Aspazetai se Epaphras, ho synaichmalōtos mou en Christō Iēsou;<br>",
            "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) Ἀσπάζεταί σε Ἐπαφρᾶς, ὁ συναιχμάλωτός μου ἐν Χριστῷ Ἰησοῦ·<br>",
            "🇻🇦 <strong>Vulgata:</strong> salutat te Epaphras concaptivus meus in Christo Iesu<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>Ἐπαφρᾶς</em> – 'Epafras' – fundador da igreja de Colossos (Cl 1:7). <em>συναιχμάλωτός</em> – 'companheiro de prisão' – co-prisioneiro, companheiro de cativeiro. <em>ἐν Χριστῷ Ἰησοῦ</em> – 'em Cristo Jesus' – união com Cristo, a esfera da comunhão.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Epafras é co-prisioneiro de Paulo. Cristo é a prisão que liberta (Romanos 8:2). A comunhão no sofrimento une os servos de Deus.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Epafras envia saudações a Filemom, como companheiro de prisão de Paulo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> O sofrimento por Cristo cria laços profundos. Sejamos fiéis mesmo em meio às dificuldades.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 24</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Marcos, Aristarco, Demas e Lucas, meus cooperadores.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Grego (Textus Receptus):</strong> Μάρκος, Ἀρίσταρχος, Δημᾶς, Λουκᾶς, οἱ συνεργοί μου.<br>",
            "🔤 <strong>Transliteração:</strong> Markos, Aristarchos, Dēmas, Loukas, hoi synergoi mou.<br>",
            "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) Μάρκος, Ἀρίσταρχος, Δημᾶς, Λουκᾶς, οἱ συνεργοί μου.<br>",
            "🇻🇦 <strong>Vulgata:</strong> Marcus Aristarchus Demas Lucas adiutores mei<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>Μάρκος</em> – 'Marcos' – João Marcos, autor do evangelho de Marcos, primo de Barnabé. <em>Ἀρίσταρχος</em> – 'Aristarco' – companheiro de Paulo de Tessalônica. <em>Δημᾶς</em> – 'Demas' – que mais tarde abandonou Paulo (2Tm 4:10). <em>Λουκᾶς</em> – 'Lucas' – médico amado, autor do evangelho de Lucas e Atos. <em>συνεργοί</em> – 'cooperadores' – colaboradores na obra.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A diversidade de cooperadores mostra a unidade do corpo de Cristo. Cristo tem muitos colaboradores na obra do evangelho (1 Coríntios 3:9).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Paulo lista seus colaboradores que enviam saudações a Filemom.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Trabalhemos juntos no evangelho. Cada colaborador é importante na obra de Deus.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 25</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> A graça de nosso Senhor Jesus Cristo seja com o vosso espírito. Amém.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Grego (Textus Receptus):</strong> Ἡ χάρις τοῦ Κυρίου ἡμῶν Ἰησοῦ Χριστοῦ μετὰ τοῦ πνεύματος ὑμῶν. Ἀμήν.<br>",
            "🔤 <strong>Transliteração:</strong> Hē charis tou Kyriou hēmōn Iēsou Christou meta tou pneumatos hymōn. Amēn.<br>",
            "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) Ἡ χάρις τοῦ Κυρίου ἡμῶν Ἰησοῦ Χριστοῦ μετὰ τοῦ πνεύματος ὑμῶν. Ἀμήν.<br>",
            "🇻🇦 <strong>Vulgata:</strong> gratia Domini nostri Iesu Christi cum spiritu vestro amen<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>χάρις</em> – 'graça' – favor imerecido, o poder de Deus para viver. <em>πνεύματος</em> – 'espírito' – espírito humano, a vida interior. <em>ὑμῶν</em> – 'vosso' – de vocês (plural), incluindo Filemom e toda a igreja.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A graça de Cristo é a bênção final. Cristo é a graça que nos sustenta (2 Coríntios 12:9). A bênção é sobre o espírito, a parte mais profunda do ser.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> A carta termina com a bênção da graça de Cristo sobre o espírito dos destinatários.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> A graça de Cristo seja com nosso espírito. Vivamos na dependência da graça de Deus.<br>"
        ]
    }
};