window.LIVRO_DATA = {
    nome: "Obadias",
    id: "obadias",
    testament: "AT",
    
    dados: {
        1: [
            
            "<span style='font-size: 15px;'><b>VERSÍCULO: 1</b></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>TEXTO:</span></b> Visão de Obadias. Assim diz o Senhor Deus a respeito de Edom: Temos ouvido uma mensagem da parte do Senhor, e um mensageiro foi enviado entre as nações, dizendo: Levantai-vos, e levantemo-nos contra ela para a guerra.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ORIGINAL:</span></b><br>",
            "📜 <b>Hebraico:</b> חֲזוֹן עֹבַדְיָה כֹּה־אָמַר אֲדֹנָי יְהוִה לֶאֱדוֹם שְׁמוּעָה שָׁמַעְנוּ מֵאֵת יְהוָה וְצִיר בַּגּוֹיִם שֻׁלָּח קוּמוּ וְנָקוּמָה עָלֶיהָ לַמִּלְחָמָה<br>",
            "🔤 <b>Transliteração:</b> Chazon Ovadyah ko-amar Adonai YHWH l'Edom sh'mu'ah sham'nu me'et YHWH v'tzir bagoyim shulach kumu v'nakumah aleiha lamilchamah<br>",
            "🇬🇷 <b>Septuaginta:</b> Ὅρασις Ὀβδίου. Τάδε λέγει κύριος ὁ θεὸς τῇ Ἰδουμαίᾳ· ἀκοὴν ἤκουσα παρὰ κυρίου, καὶ περιοχὴν εἰς ἔθνη ἐξαπέστειλεν· ἀνάστητε καὶ ἐξαναστῶμεν ἐπ᾽ αὐτὴν εἰς πόλεμον<br>",
            "🇻🇦 <b>Vulgata:</b> Visio Abdiae. Haec dicit Dominus Deus ad Edom: Auditum audivimus a Domino, et legatus ad gentes missus est: Surgite, et consurgamus adversus eam in proelium.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></b> <em>חֲזוֹן</em> – 'Visão' – revelação profética, visão. <em>עֹבַדְיָה</em> – 'Obadias' – significa 'servo do Senhor'. <em>צִיר</em> – 'mensageiro' – emissário, enviado.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>SIMBOLISMO:</span></b> A visão de Obadias revela o juízo divino contra Edom, descendente de Esaú, que sempre esteve em conflito com Israel, descendente de Jacó. Cristo, o mensageiro final, veio trazer a mensagem de salvação e juízo. O chamado às nações para guerrear contra Edom prefigura a reunião das nações contra os inimigos de Deus (Apocalipse 16:14).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></b> Rashi: Obadias profetizou contra Edom por sua crueldade com Israel. Calvino: O juízo de Deus é anunciado às nações. Crisóstomo: Cristo é o mensageiro que traz a mensagem divina.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>APLICAÇÃO:</span></b> Deus envia mensageiros para anunciar Sua vontade. Estamos atentos à Sua voz?<br>",

            "<span style='font-size: 15px;'><b>VERSÍCULO: 2</b></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>TEXTO:</span></b> Eis que te farei pequeno entre as nações; serás muito desprezado.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ORIGINAL:</span></b><br>",
            "📜 <b>Hebraico:</b> הִנֵּה קָטֹן נְתַתִּיךָ בַּגּוֹיִם בָּזוּי אַתָּה מְאֹד<br>",
            "🔤 <b>Transliteração:</b> Hineh katon n'taticha bagoyim bazui atah m'od<br>",
            "🇬🇷 <b>Septuaginta:</b> ἰδοὺ μικρὸν δέδωκά σε ἐν τοῖς ἔθνεσιν, ἠτιμωμένος εἶ σφόδρα<br>",
            "🇻🇦 <b>Vulgata:</b> Ecce parvulum dedi te in gentibus; contemptibilis tu es valde.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></b> <em>קָטֹן</em> – <q>pequeno</q> – diminuto, insignificante. <em>נְתַתִּיךָ</em> – 'te farei' – te colocarei, te tornarei. <em>בָּזוּי</em> – 'desprezado' – desprezado, menosprezado.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>SIMBOLISMO:</span></b> O orgulho de Edom será humilhado, e a nação que se considerava grande será reduzida a nada. Cristo, que Se humilhou e foi desprezado, mostra o caminho da verdadeira grandeza: a humildade (Filipenses 2:5-8).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></b> Rashi: Edom será humilhado entre as nações. Calvino: O orgulho precede a queda. Crisóstomo: A humildade é o caminho para a exaltação.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>APLICAÇÃO:</span></b> O orgulho nos leva à queda. A humildade nos exalta em Cristo.<br>",

            "<span style='font-size: 15px;'><b>VERSÍCULO: 3</b></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>TEXTO:</span></b> A soberba do teu coração te enganou, tu que habitas nas fendas dos rochedos, cuja morada é elevada; que dizes no teu coração: Quem me derrubará em terra?<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ORIGINAL:</span></b><br>",
            "📜 <b>Hebraico:</b> זְדוֹן לִבְּךָ הִשִּׁיאֶךָ שֹׁכְנִי בְחַגְוֵי־סֶּלַע מְרוֹם שִׁבְתּוֹ אֹמֵר בְּלִבּוֹ מִי יוֹרִדֵנִי אָרֶץ<br>",
            "🔤 <b>Transliteração:</b> Z'don lib'cha hishi'echa shoch'ni v'chagvei-sela m'rom shivto omer b'libo mi yorideni aretz<br>",
            "🇬🇷 <b>Septuaginta:</b> ὑπερηφανία τῆς καρδίας σου ἐπῆρέν σε, κατασκηνῶν ἐν ταῖς ὀπαῖς τῶν πετρῶν, ὑψῶν κατοικίαν αὐτοῦ, λέγων ἐν καρδίᾳ αὐτοῦ· τίς κατάξει με ἐπὶ τὴν γῆν;<br>",
            "🇻🇦 <b>Vulgata:</b> Superbia cordis tui extulit te, habitantem in scissuris petrarum, exaltantem solium suum; qui dicis in corde tuo: Quis detrahet me in terram?<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></b> <em>זְדוֹן</em> – 'soberba' – arrogância, orgulho. <em>הִשִּׁיאֶךָ</em> – 'enganou' – enganou, iludiu. <em>חַגְוֵי</em> – 'fendas' – fendas, cavidades.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>SIMBOLISMO:</span></b> Edom habitava em uma região montanhosa, cheia de rochedos e fortalezas naturais, o que gerava grande orgulho. A pergunta 'Quem me derrubará?' reflete a autossuficiência humana. Cristo, o Rei que desceu do céu, nos ensina que a verdadeira segurança está em Deus e não em fortificações humanas (Mateus 6:19-21).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></b> Rashi: A soberba de Edom o cegou. Calvino: A confiança em fortificações é vã. Crisóstomo: A verdadeira segurança está em Cristo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>APLICAÇÃO:</span></b> Não confiemos em nossa própria força. Nossa segurança está em Deus.<br>",

            "<span style='font-size: 15px;'><b>VERSÍCULO: 4</b></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>TEXTO:</span></b> Ainda que te eleves como a águia, e ainda que ponhas o teu ninho entre as estrelas, dali te derrubarei, diz o Senhor.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ORIGINAL:</span></b><br>",
            "📜 <b>Hebraico:</b> אִם־תַּגְבִּיהַ כַּנֶּשֶׁר וְאִם־בֵּין כּוֹכָבִים שִׂים קִנֶּךָ מִשָּׁם אוֹרִידְךָ נְאֻם־יְהוָה<br>",
            "🔤 <b>Transliteração:</b> Im-tagbiha kanesher v'im-bein kochavim sim kinecha misham orid'cha n'um-YHWH<br>",
            "🇬🇷 <b>Septuaginta:</b> ἐὰν μετεωρισθῇς ὡς ἀετός, καὶ ἐὰν ἀνὰ μέσον ἄστρων θῇς νοσσιάν σου, ἐκεῖθεν κατάξω σε, λέγει κύριος<br>",
            "🇻🇦 <b>Vulgata:</b> Si exaltatus fueris ut aquila, et si inter sidera posueris nidum tuum, inde detraham te, dicit Dominus.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></b> <em>תַּגְבִּיהַ</em> – 'te eleves' – te eleves, te exaltes. <em>כַּנֶּשֶׁר</em> – 'como a águia' – como a águia, ave de rapina. <em>קִנֶּךָ</em> – 'teu ninho' – teu ninho, teu abrigo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>SIMBOLISMO:</span></b> A águia simboliza a altivez e o orgulho. Edom se considerava inatingível, mas Deus declara que de qualquer lugar, até mesmo entre as estrelas, Ele o derrubará. Cristo, que desceu das alturas do céu, humilhou-Se para exaltar os humildes (Efésios 4:9-10).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></b> Rashi: Nenhuma altura protege do juízo de Deus. Calvino: O orgulho humano é vão diante de Deus. Crisóstomo: Cristo desceu para nos elevar.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>APLICAÇÃO:</span></b> Não há lugar onde possamos nos esconder de Deus. Ele nos vê e nos julga.<br>",

            "<span style='font-size: 15px;'><b>VERSÍCULO: 5</b></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>TEXTO:</span></b> Se viessem a ti ladrões, ou assaltantes de noite (como estás destruído!), não furtariam apenas o que lhes bastasse? Se a ti viessem os vindimadores, não deixariam alguns rabiscos?<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ORIGINAL:</span></b><br>",
            "📜 <b>Hebraico:</b> אִם־גַּנָּבִים בָּאוּ לְךָ אִם־שׁוֹדְדֵי לַיְלָה אֵיךְ נִדְמֵיתָה הֲלוֹא יִגְנְבוּ דַּיָּם אִם־בֹּצְרִים בָּאוּ לָךְ הֲלוֹא יַשְׁאִירוּ עֹלֵלוֹת<br>",
            "🔤 <b>Transliteração:</b> Im-ganavim ba'u l'cha im-shod'dei laylah eich nidmeitah halo yign'vu dayam im-botz'rim ba'u lach halo yash'iru olelot<br>",
            "🇬🇷 <b>Septuaginta:</b> εἰ κλέπται εἰσῆλθον πρὸς σὲ ἢ λῃσταὶ νυκτός, πῶς ἂν παρεσιωπήθης; οὐκ ἂν ἔκλεψαν ἃ ἱκανὰ ἦν αὐτοῖς; καὶ εἰ τρυγῶντες εἰσῆλθον πρὸς σέ, οὐκ ἂν ὑπελίποντο ἐπιφυλλίδα<br>",
            "🇻🇦 <b>Vulgata:</b> Si fures introissent ad te, si latrones per noctem, quomodo conticuisses? Nonne furati essent sufficientia sibi? Si vindemiatores introissent ad te, nonne reliquissent racemos?<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></b> <em>גַּנָּבִים</em> – 'ladrões' – ladrões, salteadores. <em>שׁוֹדְדֵי</em> – 'assaltantes' – saqueadores, destruidores. <em>בֹּצְרִים</em> – 'vindimadores' – colhedores de uvas.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>SIMBOLISMO:</span></b> A pergunta retórica destaca que Edom será saqueado mais severamente do que ladrões ou vindimadores normalmente fariam. O juízo será completo e não deixará sobras. Cristo, que é o verdadeiro pão da vida, não deixa os Seus sem sustento (João 6:35).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></b> Rashi: A destruição de Edom será total. Calvino: O juízo de Deus é completo. Crisóstomo: Cristo provê abundantemente para os Seus.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>APLICAÇÃO:</span></b> O juízo de Deus é completo. Confiemos em Sua provisão.<br>",

            "<span style='font-size: 15px;'><b>VERSÍCULO: 6</b></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>TEXTO:</span></b> Como foram rebuscados os bens de Esaú! Como foram esquadrinhados os seus tesouros escondidos!<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ORIGINAL:</span></b><br>",
            "📜 <b>Hebraico:</b> אֵיךְ נֶחְפְּשׂוּ עֵשָׂו נִבְעוּ מַצְפֻּנָיו<br>",
            "🔤 <b>Transliteração:</b> Eich nechp'su Esav niv'u matzpunav<br>",
            "🇬🇷 <b>Septuaginta:</b> πῶς ἐξηρευνήθη ὁ Ἠσαῦ, καὶ κατελήφθη τὰ κεκρυμμένα αὐτοῦ;<br>",
            "🇻🇦 <b>Vulgata:</b> Quomodo scrutati sunt Esau, et investigaverunt abscondita eius!<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></b> <em>נֶחְפְּשׂוּ</em> – 'rebuscados' – examinados, vasculhados. <em>נִבְעוּ</em> – 'esquadrinhados' – explorados, investigados. <em>מַצְפֻּנָיו</em> – 'tesouros escondidos' – coisas ocultas, tesouros escondidos.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>SIMBOLISMO:</span></b> Os tesouros escondidos de Edom serão descobertos e saqueados, simbolizando a total exposição do pecado e a perda de tudo o que é precioso. Cristo, que busca e salva os perdidos, revela os segredos do coração (Lucas 19:10; Mateus 10:26).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></b> Rashi: Os tesouros de Edom serão saqueados. Calvino: Nada escapará do juízo de Deus. Crisóstomo: Cristo revela o que está oculto.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>APLICAÇÃO:</span></b> Não acumulemos tesouros na terra. Nosso tesouro está em Cristo.<br>",

            "<span style='font-size: 15px;'><b>VERSÍCULO: 7</b></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>TEXTO:</span></b> Todos os teus aliados te levaram até à fronteira; os que estavam em paz contigo te enganaram, e prevaleceram contra ti; os que comem o teu pão puseram armadilhas debaixo de ti; não há em ti entendimento.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ORIGINAL:</span></b><br>",
            "📜 <b>Hebraico:</b> עַד־הַגְּבוּל שִׁלְּחוּךָ כֹּל אַנְשֵׁי בְרִיתֶךָ הִשִּׁיאוּךָ יָכְלוּ לְךָ אַנְשֵׁי שְׁלֹמֶךָ לַחְמְךָ יָשִׂימוּ מָזוֹר תַּחְתֶּיךָ אֵין תְּבוּנָה בּוֹ<br>",
            "🔤 <b>Transliteração:</b> Ad-hagvul shil'chu cha kol anshei v'ritecha hishi'ucha yachlu l'cha anshei sh'lomecha lachm'cha yasimu mazor tachteicha ein t'vunah bo<br>",
            "🇬🇷 <b>Septuaginta:</b> ἕως τῶν ὁρίων ἐξαπέστειλάν σε πάντες οἱ ἄνδρες τῆς διαθήκης σου, ἀντέστησάν σοι, ἠδυνάσθησαν πρὸς σὲ ἄνδρες εἰρήνης σου, ἔθεντο ἔνεδρα ὑποκάτω σου, οὐκ ἔστιν σύνεσις αὐτῷ<br>",
            "🇻🇦 <b>Vulgata:</b> Usque ad terminum dimiserunt te omnes viri foederis tui; valuerunt adversum te, qui erant pacifici tui; qui comedebant tecum, posuerunt insidias subter te; non est prudentia in eo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></b> <em>בְרִיתֶךָ</em> – 'aliados' – seus aliados, da aliança. <em>הִשִּׁיאוּךָ</em> – 'enganaram' – enganaram, iludiram. <em>מָזוֹר</em> – 'armadilhas' – laços, armadilhas.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>SIMBOLISMO:</span></b> Edom confiou em alianças humanas e foi traído. A confiança em homens é vã. Cristo, o amigo fiel, nunca nos abandona (João 15:13-15). A falta de entendimento de Edom é a falta de sabedoria espiritual, que só é encontrada em Cristo (Provérbios 9:10).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></b> Rashi: Os aliados de Edom o traíram. Calvino: A confiança em alianças humanas é vã. Crisóstomo: Cristo é o amigo fiel.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>APLICAÇÃO:</span></b> Confiemos somente em Cristo, o amigo fiel. Ele nunca nos trai.<br>",

            "<span style='font-size: 15px;'><b>VERSÍCULO: 8</b></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>TEXTO:</span></b> Acaso não acontecerá naquele dia, diz o Senhor, que destruirei os sábios de Edom, e o entendimento do monte de Esaú?<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ORIGINAL:</span></b><br>",
            "📜 <b>Hebraico:</b> הֲלוֹא בַּיּוֹם הַהוּא נְאֻם־יְהוָה וְהַאֲבַדְתִּי חֲכָמִים מֵאֱדוֹם וּתְבוּנָה מֵהַר עֵשָׂו<br>",
            "🔤 <b>Transliteração:</b> Halo bayom hahu n'um-YHWH v'ha'avad'ti chachamim me'Edom ut'vunah mehar Esav<br>",
            "🇬🇷 <b>Septuaginta:</b> οὐκ ἐν τῇ ἡμέρᾳ ἐκείνῃ, λέγει κύριος, ἀπολῶ σοφοὺς ἐξ Ἰδουμαίας καὶ σύνεσιν ἐξ ὄρους Ἠσαῦ;<br>",
            "🇻🇦 <b>Vulgata:</b> Nonne in die illa, dicit Dominus, perdam sapientes de Edom, et prudentiam de monte Esau?<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></b> <em>חֲכָמִים</em> – 'sábios' – sábios, prudentes. <em>תְּבוּנָה</em> – 'entendimento' – discernimento, inteligência. <em>הַר עֵשָׂו</em> – 'monte de Esaú' – a região montanhosa de Edom.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>SIMBOLISMO:</span></b> A sabedoria humana e o entendimento de Edom serão destruídos. A verdadeira sabedoria vem do Senhor (Provérbios 2:6). Cristo é a sabedoria de Deus (1 Coríntios 1:24). A destruição da sabedoria de Edom prefigura a humilhação de toda altivez humana.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></b> Rashi: A sabedoria de Edom será inútil. Calvino: A sabedoria humana é vã diante de Deus. Crisóstomo: Cristo é a verdadeira sabedoria.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>APLICAÇÃO:</span></b> Busquemos a sabedoria que vem de Deus, a sabedoria de Cristo.<br>",

            "<span style='font-size: 15px;'><b>VERSÍCULO: 9</b></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>TEXTO:</span></b> E os teus valentes, ó Temã, ficarão atemorizados, para que do monte de Esaú seja cada um exterminado pela matança.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ORIGINAL:</span></b><br>",
            "📜 <b>Hebraico:</b> וְחַתּוּ גִבּוֹרֶיךָ תֵּימָן לְמַעַן יִכָּרֶת־אִישׁ מֵהַר עֵשָׂו מִקָּטֶל<br>",
            "🔤 <b>Transliteração:</b> V'chatu giboreicha Teiman l'ma'an yikaret-ish mehar Esav mikatel<br>",
            "🇬🇷 <b>Septuaginta:</b> καὶ πτοηθήσονται οἱ μαχηταί σου, οἱ ἐκ Θαιμάν, ὅπως ἐξαρθῇ ἄνθρωπος ἐξ ὄρους Ἠσαῦ<br>",
            "🇻🇦 <b>Vulgata:</b> Et timebunt fortes tui, o Theman, ut interficiatur de monte Esau vir unusquisque.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></b> <em>חַתּוּ</em> – 'atemorizados' – ficarão aterrorizados, desanimados. <em>גִּבּוֹרֶיךָ</em> – 'valentes' – heróis, guerreiros. <em>תֵּימָן</em> – 'Temã' – região de Edom famosa por seus guerreiros.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>SIMBOLISMO:</span></b> Os valentes de Edom, conhecidos por sua força, serão tomados pelo medo e exterminados. A força humana é fraca diante do poder de Deus. Cristo, o verdadeiro valente, venceu o inimigo e nos dá força (Efésios 6:10).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></b> Rashi: Os guerreiros de Temã serão derrotados. Calvino: A força humana não resiste ao juízo de Deus. Crisóstomo: Cristo é a nossa força.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>APLICAÇÃO:</span></b> Nossa força está em Cristo. Não confiemos na força humana.<br>",

            "<span style='font-size: 15px;'><b>VERSÍCULO: 10</b></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>TEXTO:</span></b> Por causa da violência feita a teu irmão Jacó, cobrir-te-á a vergonha, e serás exterminado para sempre.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ORIGINAL:</span></b><br>",
            "📜 <b>Hebraico:</b> מֵחֲמַס אָחִיךָ יַעֲקֹב תְּכַסְּךָ בוּשָׁה וְנִכְרַתָּ לְעוֹלָם<br>",
            "🔤 <b>Transliteração:</b> Mechamas achicha Ya'akov t'chas'cha bushah v'nichrata l'olam<br>",
            "🇬🇷 <b>Septuaginta:</b> διὰ τὴν σφαγὴν καὶ τὴν ἀσέβειαν ἀδελφοῦ σου Ἰακώβ, καλύψει σε αἰσχύνη, καὶ ἐξαρθήσῃ εἰς τὸν αἰῶνα<br>",
            "🇻🇦 <b>Vulgata:</b> Propter interfectionem et propter iniquitatem in fratrem tuum Iacob, operiet te confusio, et peribis in aeternum.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></b> <em>חֲמַס</em> – 'violência' – violência, injustiça. <em>תְּכַסְּךָ</em> – 'cobrir-te-á' – te cobrirá, envolverá. <em>וְנִכְרַתָּ</em> – 'serás exterminado' – serás cortado, destruído.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>SIMBOLISMO:</span></b> A violência contra Jacó (Israel) trouxe vergonha e destruição eterna a Edom. Cristo, que sofreu violência por nós, nos reconciliou com Deus (Colossenses 1:20). A vergonha de Edom é a justiça divina.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></b> Rashi: A violência contra Israel será punida. Calvino: A injustiça contra o povo de Deus é grave. Crisóstomo: Cristo nos reconciliou com Deus.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>APLICAÇÃO:</span></b> Deus defende Seu povo. Não toquemos nos ungidos do Senhor.<br>",

            "<span style='font-size: 15px;'><b>VERSÍCULO: 11</b></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>TEXTO:</span></b> No dia em que estiveste perante ele, no dia em que estranhos lhe levaram cativo o exército, e estrangeiros entraram pelas suas portas, e sobre Jerusalém lançaram sortes, tu também eras como um deles.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ORIGINAL:</span></b><br>",
            "📜 <b>Hebraico:</b> בְּיוֹם עֲמָדְךָ מִנֶּגֶד בְּיוֹם שְׁבוֹת זָרִים חֵילוֹ וְנָכְרִים בָּאוּ שְׁעָרָיו וְעַל־יְרוּשָׁלִַם יַדּוּ גוֹרָל גַּם־אַתָּה כְּאַחַד מֵהֶם<br>",
            "🔤 <b>Transliteração:</b> B'yom amod'cha mineged b'yom sh'vot zarim cheilo v'nachrim ba'u sha'arav v'al-Yerushalayim yadu goril gam-atah k'achad mehem<br>",
            "🇬🇷 <b>Septuaginta:</b> ἀφ᾽ ἡμέρας ἀντιστάσεώς σου, ἡμέρας αἰχμαλωσίας ἀλλοτρίων δύναμιν αὐτοῦ, καὶ ἀλλότριοι εἰσῆλθον εἰς τὰς πύλας αὐτοῦ, καὶ ἐπὶ Ἱερουσαλὴμ ἔβαλον κλήρους, καὶ σὺ ἦς ὡς εἷς ἐξ αὐτῶν<br>",
            "🇻🇦 <b>Vulgata:</b> In die cum stare ex adverso, in die quando alieni capiebant exercitum eius, et extranei ingrediebantur portas eius, et super Ierusalem mittebant sortem, tu quoque eras quasi unus ex eis.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></b> <em>עֲמָדְךָ</em> – 'estiveste' – ficaste, estiveste. <em>שְׁבוֹת</em> – 'levaram cativo' – levaram cativo. <em>יַדּוּ גוֹרָל</em> – 'lançaram sortes' – lançaram sortes.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>SIMBOLISMO:</span></b> Edom se aliou aos inimigos de Israel e participou da destruição de Jerusalém. A indiferença e a conivência com o mal são pecados graves. Cristo, que chorou por Jerusalém (Mateus 23:37), nos chama a compaixão.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></b> Rashi: Edom se alegrou com a queda de Jerusalém. Calvino: A indiferença ao sofrimento do próximo é pecado. Crisóstomo: Cristo chorou por Jerusalém.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>APLICAÇÃO:</span></b> Não sejamos indiferentes ao sofrimento do próximo. Tenhamos compaixão.<br>",

            "<span style='font-size: 15px;'><b>VERSÍCULO: 12</b></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>TEXTO:</span></b> Mas tu não devias ter olhado com satisfação para o dia de teu irmão, no dia do seu desterro; nem te devias ter alegrado sobre os filhos de Judá, no dia da sua ruína; nem ter falado arrogantemente, no dia da angústia.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ORIGINAL:</span></b><br>",
            "📜 <b>Hebraico:</b> וְאַל־תֵּרֶא בְיוֹם־אָחִיךָ בְּיוֹם נָכְרוֹ וְאַל־תִּשְׂמַח לִבְנֵי־יְהוּדָה בְּיוֹם אָבְדָם וְאַל־תַּגְדֵּל פִּיךָ בְּיוֹם צָרָה<br>",
            "🔤 <b>Transliteração:</b> V'al-tere v'yom-achicha b'yom nochro v'al-tismach liv'nei-Yehudah b'yom av'dam v'al-tagdel picha b'yom tzarah<br>",
            "🇬🇷 <b>Septuaginta:</b> καὶ μὴ ἐπίδῃς ἡμέραν ἀδελφοῦ σου, ἡμέραν ἀλλοτρίων, καὶ μὴ ἐπιχαρῇς ἐπὶ υἱοὺς Ἰούδα ἐν ἡμέρᾳ ἀπωλείας αὐτῶν, καὶ μὴ μεγαλορρημονήσῃς ἐν ἡμέρᾳ θλίψεως<br>",
            "🇻🇦 <b>Vulgata:</b> Et non videbis diem fratris tui, diem peregrinationis eius; et non laetaberis super filios Iuda in die perditionis eorum; et non magnificabis os tuum in die angustiae.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></b> <em>וְאַל־תֵּרֶא</em> – 'não devias ter olhado' – não olhar com satisfação. <em>תִּשְׂמַח</em> – 'alegrado' – se alegrar, regozijar. <em>תַּגְדֵּל</em> – 'falado arrogantemente' – falar com arrogância.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>SIMBOLISMO:</span></b> Edom é condenado por ter se alegrado com a desgraça de Israel e falado arrogantemente. A alegria pela queda do próximo é pecado. Cristo, que nos ensina a amar os inimigos (Mateus 5:44), nos chama a compaixão.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></b> Rashi: Edom não deveria ter se alegrado com a queda de Judá. Calvino: A alegria pelo mal é pecado. Crisóstomo: Cristo nos ensina a amar os inimigos.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>APLICAÇÃO:</span></b> Não nos alegremos com a desgraça do próximo. Tenhamos compaixão e amor.<br>",

            "<span style='font-size: 15px;'><b>VERSÍCULO: 13</b></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>TEXTO:</span></b> Não devias ter entrado pela porta do meu povo, no dia da sua calamidade; nem, ainda, ter olhado satisfeito para o seu mal, no dia da sua calamidade; nem ter lançado mão dos seus bens, no dia da sua calamidade.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ORIGINAL:</span></b><br>",
            "📜 <b>Hebraico:</b> אַל־תָּבוֹא בְשַׁעַר־עַמִּי בְּיוֹם אֵידָם אַל־תֵּרֶא גַם־אַתָּה בְּרָעָתוֹ בְּיוֹם אֵידוֹ וְאַל־תִּשְׁלַחְנָה בְחֵילוֹ בְּיוֹם אֵידוֹ<br>",
            "🔤 <b>Transliteração:</b> Al-tavo v'sha'ar-ami b'yom eidam al-tere gam-atah b'ra'ato b'yom eido v'al-tishlachnah b'cheilo b'yom eido<br>",
            "🇬🇷 <b>Septuaginta:</b> μὴ εἰσέλθῃς εἰς πύλας λαῶν μου ἐν ἡμέρᾳ πόνων αὐτῶν, μὴ ἐπίδῃς σὺ καὶ σὺ ἐν κακοῖς αὐτοῦ ἐν ἡμέρᾳ ὀλέθρου αὐτοῦ, μὴ συνέλθῃς ἐπὶ τὴν δύναμιν αὐτοῦ ἐν ἡμέρᾳ ἀπωλείας αὐτοῦ<br>",
            "🇻🇦 <b>Vulgata:</b> Ne ingrediaris portam populi mei in die ruinae eorum; ne despicias et tu in malis eius in die vastitatis eius; et ne mittas manum in substantia eius in die perditionis eius.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></b> <em>בְשַׁעַר</em> – 'pela porta' – pela porta, entrada. <em>אֵידָם</em> – 'calamidade' – desgraça, calamidade. <em>בְחֵילוֹ</em> – 'bens' – riquezas, exército.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>SIMBOLISMO:</span></b> Edom é condenado por entrar na cidade de Jerusalém para saquear e se alegrar com a calamidade. O saque e a exploração do sofrimento alheio são pecados graves. Cristo, que foi saqueado e humilhado, nos chama a proteger os vulneráveis.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></b> Rashi: Edom participou do saque de Jerusalém. Calvino: A exploração do sofrimento alheio é grave. Crisóstomo: Cristo protege os vulneráveis.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>APLICAÇÃO:</span></b> Não exploremos o sofrimento alheio. Protejamos os vulneráveis.<br>",

            "<span style='font-size: 15px;'><b>VERSÍCULO: 14</b></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>TEXTO:</span></b> Nem te devias ter postado nas encruzilhadas, para exterminares os que fugiam; nem ter entregue os que lhe restaram, no dia da angústia.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ORIGINAL:</span></b><br>",
            "📜 <b>Hebraico:</b> וְאַל־תַּעֲמֹד עַל־הַפֶּרֶק לְהַכְרִית אֶת־פְּלִיטָיו וְאַל־תַּסְגֵּר שְׂרִידָיו בְּיוֹם צָרָה<br>",
            "🔤 <b>Transliteração:</b> V'al-ta'amod al-haperek l'hachrit et-p'litav v'al-tasger s'ridav b'yom tzarah<br>",
            "🇬🇷 <b>Septuaginta:</b> μὴ στῇς ἐπὶ τὴν διέξοδον ἐκκόψαι τοὺς σωζομένους αὐτοῦ, μὴ παραδῷς τοὺς περιλειπομένους ἐν ἡμέρᾳ θλίψεως<br>",
            "🇻🇦 <b>Vulgata:</b> Neque stabis in exitibus, ut interficias eos qui fugerint; et non concludes reliquos eius in die tribulationis.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></b> <em>הַפֶּרֶק</em> – 'encruzilhadas' – encruzilhadas, bifurcações. <em>פְּלִיטָיו</em> – 'que fugiam' – fugitivos, sobreviventes. <em>תַּסְגֵּר</em> – 'entregue' – entregar, trair.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>SIMBOLISMO:</span></b> Edom é condenado por interceptar os sobreviventes e entregá-los aos inimigos. A falta de misericórdia com os que fogem é pecado. Cristo, que acolhe os que fogem para Ele (João 6:37), nos chama à misericórdia.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></b> Rashi: Edom impediu a fuga dos sobreviventes. Calvino: A falta de misericórdia é condenada. Crisóstomo: Cristo acolhe os que fogem para Ele.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>APLICAÇÃO:</span></b> Sejamos misericordiosos com os que fogem e buscam abrigo. Cristo nos acolhe.<br>",

            "<span style='font-size: 15px;'><b>VERSÍCULO: 15</b></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>TEXTO:</span></b> Porque o dia do Senhor está perto, sobre todas as nações; como fizeste, assim se fará contigo; a tua recompensa cairá sobre a tua cabeça.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ORIGINAL:</span></b><br>",
            "📜 <b>Hebraico:</b> כִּי־קָרוֹב יוֹם־יְהוָה עַל־כָּל־הַגּוֹיִם כַּאֲשֶׁר עָשִׂיתָ יֵעָשֶׂה לָּךְ גְּמֻלְךָ יָשׁוּב בְּרֹאשֶׁךָ<br>",
            "🔤 <b>Transliteração:</b> Ki-karov yom-YHWH al-kol-hagoyim ka'asher asita ye'aseh lach g'mul'cha yashuv b'roshecha<br>",
            "🇬🇷 <b>Septuaginta:</b> διότι ἐγγὺς ἡμέρα κυρίου ἐπὶ πάντα τὰ ἔθνη, ὃν τρόπον ἐποίησας, οὕτως ἔσται σοι, τὸ ἀνταπόδομά σου ἀνταποδοθήσεται εἰς κεφαλήν σου<br>",
            "🇻🇦 <b>Vulgata:</b> Quoniam iuxta est dies Domini super omnes gentes; sicut fecisti, fiet tibi; retributionem tuam convertet in caput tuum.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></b> <em>קָרוֹב</em> – 'perto' – próximo, iminente. <em>יוֹם־יְהוָה</em> – 'dia do Senhor' – o dia do juízo de Deus. <em>גְּמֻלְךָ</em> – 'recompensa' – retribuição, recompensa.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>SIMBOLISMO:</span></b> O dia do Senhor é um dia de juízo para todas as nações. A lei da retribuição divina: como você fez, assim será feito a você. Cristo, que sofreu a retribuição por nossos pecados, nos oferece graça em vez de juízo (Romanos 6:23).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></b> Rashi: O dia do Senhor virá sobre todas as nações. Calvino: A justiça divina é retributiva. Crisóstomo: Cristo nos oferece graça em vez de juízo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>APLICAÇÃO:</span></b> A justiça de Deus é certa. Confiemos em Sua graça em Cristo.<br>",

            "<span style='font-size: 15px;'><b>VERSÍCULO: 16</b></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>TEXTO:</span></b> Pois assim como vós bebestes no meu santo monte, assim beberão de contínuo todas as nações; beberão, e sorverão, e serão como se nunca tivessem sido.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ORIGINAL:</span></b><br>",
            "📜 <b>Hebraico:</b> כִּי כַּאֲשֶׁר שְׁתִיתֶם עַל־הַר קָדְשִׁי יִשְׁתּוּ כָל־הַגּוֹיִם תָּמִיד וְשָׁתוּ וְלָעוּ וְהָיוּ כְּלוֹא הָיוּ<br>",
            "🔤 <b>Transliteração:</b> Ki ka'asher sh'titem al-har kodshi yishtu chol-hagoyim tamid v'shatu v'la'u v'hayu k'lo hayu<br>",
            "🇬🇷 <b>Septuaginta:</b> διότι ὃν τρόπον ἔπιες ἐπὶ τὸ ὄρος τὸ ἅγιόν μου, πίονται πάντα τὰ ἔθνη οἶνον, πίονται καὶ καταβήσονται καὶ ἔσονται καθὼς οὐχ ὑπάρχοντες<br>",
            "🇻🇦 <b>Vulgata:</b> Quia sicut bibistis super montem sanctum meum, bibent omnes gentes iugiter; et bibent, et absorbebunt, et erunt quasi non sint.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></b> <em>שְׁתִיתֶם</em> – 'bebestes' – bebestes, beberam. <em>יִשְׁתּוּ</em> – 'beberão' – beberão, beberão. <em>וְלָעוּ</em> – 'sorverão' – sorverão, engolirão.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>SIMBOLISMO:</span></b> O beber no monte santo simboliza o juízo que também virá sobre as nações. O sorver e serem como se nunca tivessem existido aponta para a destruição completa. Cristo, que bebeu o cálice da ira por nós (Mateus 26:39), nos oferece o cálice da salvação.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></b> Rashi: As nações beberão o juízo de Deus. Calvino: O juízo divino é completo. Crisóstomo: Cristo bebeu o cálice da ira por nós.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>APLICAÇÃO:</span></b> Cristo bebeu o cálice da ira por nós. Agradeçamos por Sua graça.<br>",

            "<span style='font-size: 15px;'><b>VERSÍCULO: 17</b></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>TEXTO:</span></b> Mas no monte Sião haverá livramento, e o monte será santo; e a casa de Jacó possuirá as suas possessões.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ORIGINAL:</span></b><br>",
            "📜 <b>Hebraico:</b> וּבְהַר צִיּוֹן תִּהְיֶה פְלֵיטָה וְהָיָה קֹדֶשׁ וְיָרְשׁוּ בֵּית יַעֲקֹב אֵת מוֹרָשֵׁיהֶם<br>",
            "🔤 <b>Transliteração:</b> Uv'har Tzion tih'yeh p'leitah v'hayah kodesh v'yar'shu beit Ya'akov et morasheihem<br>",
            "🇬🇷 <b>Septuaginta:</b> ἐν δὲ τῷ ὄρει Σιὼν ἔσται σωτηρία, καὶ ἔσται ἅγιον, καὶ κατακληρονομήσουσιν οἱ υἱοὶ Ἰσραὴλ τὸ ὄρος αὐτῶν<br>",
            "🇻🇦 <b>Vulgata:</b> In monte autem Sion erit salvatio, et erit sanctus; et possidebit domus Iacob eos qui se possederant.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></b> <em>פְלֵיטָה</em> – 'livramento' – escape, salvação. <em>קֹדֶשׁ</em> – 'santo' – sagrado, separado. <em>מוֹרָשֵׁיהֶם</em> – 'possessões' – heranças, possessões.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>SIMBOLISMO:</span></b> O monte Sião é o lugar de livramento e santidade para o remanescente de Israel. Cristo, o Rei de Sião (João 12:15), é o nosso livramento. A casa de Jacó possuirá suas possessões, simbolizando a restauração e a herança eterna.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></b> Rashi: O monte Sião será um lugar de salvação. Calvino: A santidade de Sião é restaurada. Crisóstomo: Cristo é o Rei de Sião.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>APLICAÇÃO:</span></b> Em Cristo, encontramos livramento e santidade. Ele é a nossa herança.<br>",

            "<span style='font-size: 15px;'><b>VERSÍCULO: 18</b></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>TEXTO:</span></b> E a casa de Jacó será fogo, e a casa de José uma chama, e a casa de Esaú palha; e se acenderão contra eles, e os consumirão; e não haverá sobrevivente algum da casa de Esaú; porque o Senhor o disse.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ORIGINAL:</span></b><br>",
            "📜 <b>Hebraico:</b> וְהָיָה בֵית־יַעֲקֹב אֵשׁ וּבֵית יוֹסֵף לֶהָבָה וּבֵית עֵשָׂו לְקַשׁ וְדָלְקוּ בָהֶם וַאֲכָלוּם וְלֹא־יִהְיֶה שָׂרִיד לְבֵית עֵשָׂו כִּי יְהוָה דִּבֵּר<br>",
            "🔤 <b>Transliteração:</b> V'hayah beit-Ya'akov esh u'veit Yosef lehavah u'veit Esav l'kash v'dalku vahem va'achalum v'lo-yih'yeh sarid l'veit Esav ki YHWH diber<br>",
            "🇬🇷 <b>Septuaginta:</b> καὶ ἔσται ὁ οἶκος Ἰακὼβ πῦρ, ὁ δὲ οἶκος Ἰωσὴφ φλόξ, ὁ δὲ οἶκος Ἠσαῦ εἰς καλάμην, καὶ ἐκκαυθήσονται εἰς αὐτοὺς καὶ καταφάγονται αὐτούς, καὶ οὐκ ἔσται πυρφόρος τῷ οἴκῳ Ἠσαῦ, διότι κύριος ἐλάλησεν<br>",
            "🇻🇦 <b>Vulgata:</b> Et erit domus Iacob ignis, et domus Ioseph flamma, et domus Esau stipula; et succendentur et devorabunt eos, et non erunt reliquiae domus Esau, quia Dominus locutus est.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></b> <em>אֵשׁ</em> – 'fogo' – fogo. <em>לֶהָבָה</em> – 'chama' – chama, labareda. <em>לְקַשׁ</em> – 'palha' – palha, restolho.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>SIMBOLISMO:</span></b> Jacó e José (Israel) serão como fogo e chama, enquanto Edom será como palha, consumida completamente. Cristo, o fogo que purifica (Malaquias 3:2-3), nos chama a ser luz e sal (Mateus 5:13-14).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></b> Rashi: Israel consumirá Edom como fogo. Calvino: O juízo de Edom é certo. Crisóstomo: Cristo é o fogo que purifica.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>APLICAÇÃO:</span></b> Sejamos fogo e luz para o mundo. Cristo nos capacita a isso.<br>",

            "<span style='font-size: 15px;'><b>VERSÍCULO: 19</b></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>TEXTO:</span></b> E os do sul possuirão o monte de Esaú, e os da planície os filisteus; possuirão também os campos de Efraim, e os campos de Samária; e Benjamim possuirá Gileade.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ORIGINAL:</span></b><br>",
            "📜 <b>Hebraico:</b> וְיָרְשׁוּ הַנֶּגֶב אֶת־הַר עֵשָׂו וְהַשְּׁפֵלָה אֶת־פְּלִשְׁתִּים וְיָרְשׁוּ אֶת־שְׂדֵה אֶפְרַיִם וְאֵת שְׂדֵה שֹׁמְרוֹן וּבִנְיָמִן אֶת־הַגִּלְעָד<br>",
            "🔤 <b>Transliteração:</b> V'yar'shu hanegev et-har Esav v'hash'felah et-P'lishtim v'yar'shu et-s'deh Efrayim v'et-s'deh Shomron u'Vinyamin et-hagil'ad<br>",
            "🇬🇷 <b>Septuaginta:</b> καὶ κατακληρονομήσουσιν οἱ ἐν Ναγεβ τὸ ὄρος Ἠσαῦ, καὶ οἱ ἐν Σεφηλὰ τοὺς ἀλλοφύλους, καὶ κατακληρονομήσουσι τὸ ὄρος Ἐφραὶμ καὶ τὸ πεδίον Σαμαρείας, καὶ Βενιαμὶν ἐν Γαλαάδ<br>",
            "🇻🇦 <b>Vulgata:</b> Et possidebunt hi, qui ad austrum sunt, montem Esau, et qui in campestribus, Philisthaeos; et possidebunt regionem Ephraim et regionem Samariae, et Beniamin possidebit Galaad.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></b> <em>הַנֶּגֶב</em> – 'do sul' – a região sul. <em>הַשְּׁפֵלָה</em> – 'da planície' – a planície costeira. <em>הַגִּלְעָד</em> – 'Gileade' – região a leste do Jordão.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>SIMBOLISMO:</span></b> A restauração de Israel inclui a possessão de todas as terras ao redor, incluindo as de Edom, Filístia, Efraim, Samaria e Gileade. Cristo, que tem todas as nações como herança (Salmo 2:8), nos garante a herança eterna.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></b> Rashi: Israel possuirá as terras ao redor. Calvino: A restauração de Israel é completa. Crisóstomo: Cristo é a herança eterna.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>APLICAÇÃO:</span></b> Em Cristo, somos herdeiros de todas as promessas. Nossa herança é eterna.<br>",

            "<span style='font-size: 15px;'><b>VERSÍCULO: 20</b></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>TEXTO:</span></b> E os cativos deste exército dos filhos de Israel possuirão a terra dos cananeus até Sarepta; e os cativos de Jerusalém, que estão em Sefarade, possuirão as cidades do sul.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ORIGINAL:</span></b><br>",
            "📜 <b>Hebraico:</b> וְגָלֻת הַחֵל הַזֶּה לִבְנֵי יִשְׂרָאֵל אֲשֶׁר־כְּנַעֲנִים עַד־צָרְפַת וְגָלֻת יְרוּשָׁלִַם אֲשֶׁר בִּסְפָרַד יִרְשׁוּ אֵת עָרֵי הַנֶּגֶב<br>",
            "🔤 <b>Transliteração:</b> V'galut hachel hazeh liv'nei Yisra'el asher-K'na'anim ad-Tzarfat v'galut Yerushalayim asher biS'farad yir'shu et arei hanegev<br>",
            "🇬🇷 <b>Septuaginta:</b> καὶ τῆς μετοικεσίας τῶν υἱῶν Ἰσραὴλ ἣ τῶν Χαναναίων ἕως Σαρεπτῶν, καὶ μετοικεσία Ἱερουσαλὴμ ἕως Ἐφραθά, κληρονομήσουσι πόλεις τοῦ Ναγεβ<br>",
            "🇻🇦 <b>Vulgata:</b> Et transmigratio exercitus huius filiorum Israel, qui Chananaei sunt usque ad Saraptham; et transmigratio Ierusalem, quae in Bosphoro est, possidebit civitates australes.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></b> <em>גָּלֻת</em> – 'cativos' – exilados, cativos. <em>עַד־צָרְפַת</em> – 'até Sarepta' – até Sarepta, cidade fenícia. <em>סְפָרַד</em> – 'Sefarade' – local não identificado, possivelmente uma região de exílio.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>SIMBOLISMO:</span></b> Os exilados de Israel retornarão e possuirão as terras desde Sarepta até as cidades do sul. Cristo, que veio buscar os perdidos (Lucas 19:10), nos garante a restauração completa.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></b> Rashi: Os exilados retornarão e possuirão as terras. Calvino: A restauração de Israel é geográfica e espiritual. Crisóstomo: Cristo busca os perdidos.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>APLICAÇÃO:</span></b> Em Cristo, somos restaurados e recebemos a herança. Ele nos busca e nos salva.<br>",

            "<span style='font-size: 15px;'><b>VERSÍCULO: 21</b></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>TEXTO:</span></b> E subirão salvadores ao monte Sião, para julgarem o monte de Esaú; e o reino será do Senhor.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ORIGINAL:</span></b><br>",
            "📜 <b>Hebraico:</b> וְעָלוּ מוֹשִׁעִים בְּהַר צִיּוֹן לִשְׁפֹּט אֶת־הַר עֵשָׂו וְהָיְתָה לַיהוָה הַמְּלוּכָה<br>",
            "🔤 <b>Transliteração:</b> V'alu moshi'im b'har Tzion lishpot et-har Esav v'hay'tah laYHWH ham'luchah<br>",
            "🇬🇷 <b>Septuaginta:</b> καὶ ἀναβήσονται σωζόμενοι ἐξ ὄρους Σιών, τοῦ ἐκδικῆσαι τὸ ὄρος Ἠσαῦ, καὶ ἔσται τῷ κυρίῳ ἡ βασιλεία<br>",
            "🇻🇦 <b>Vulgata:</b> Et ascendent salvatores in montem Sion, ut iudicent montem Esau; et erit Domino regnum.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></b> <em>מוֹשִׁעִים</em> – 'salvadores' – libertadores, salvadores. <em>לִשְׁפֹּט</em> – 'julgarem' – julgar, governar. <em>הַמְּלוּכָה</em> – 'reino' – reinado, soberania.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>SIMBOLISMO:</span></b> Salvadoras subirão a Sião para julgar Edom, e o reino será do Senhor. Este é o clímax da profecia: o estabelecimento do reino de Deus. Cristo, o Salvador final, julgará as nações e estabelecerá Seu reino eterno (Apocalipse 11:15).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></b> Rashi: Os salvadores julgarão Edom. Calvino: O reino de Deus é estabelecido. Crisóstomo: Cristo reinará para sempre.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<b><span style='color: #d4af37;'>APLICAÇÃO:</span></b> O reino é do Senhor. Confiamos em Seu governo eterno. Maranata!<br>"
        ]
    }
};