window.LIVRO_DATA = {
  nome: "Joel Comentado",
  id: "joel",
  testament: "AT",
  
  dados: {
    
  1: [
    "<p style='font-size: 0.8rem; text-align: center;'><i><strong>A Praga de Gafanhotos: O Chamado ao Lamento e ao Arrependimento</strong></i></p>",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 1</strong></span>",
    "<strong>TEXTO:</strong> Palavra do Senhor que foi dirigida a Joel, filho de Petuel.",
    "<strong>COMENTÁRIO:</strong> 📖 'Joel' (Yo'el) – nome que significa 'Yahweh é Deus'. 'Filho de Petuel' – pouco se sabe sobre seu pai. Joel é um profeta do reino do sul (Judá), provavelmente ministrando em Jerusalém, próximo ao templo. Datação incerta: pode ser do século IX a.C. (reinado de Joás) ou pós-exílico. O princípio é que Deus chama pessoas comuns para mensagens extraordinárias. Aplicação: Deus ainda chama 'Joéis' hoje – pessoas que proclamam que 'Yahweh é Deus'. Reflexão: você tem proclamado que o Senhor é Deus em sua geração?",
    "📖 <strong>RESUMO:</strong> A palavra do Senhor veio a Joel, filho de Petuel.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Não foi por vontade humana que a profecia jamais foi trazida' (2 Pedro 1:21).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 2</strong></span>",
    "<strong>TEXTO:</strong> Ouvi isto, vós anciãos, e escutai, todos os moradores da terra. Aconteceu isto em vossos dias, ou nos dias de vossos pais?",
    "<strong>COMENTÁRIO:</strong> 👂 'Ouvi... escutai' – convocação universal para atenção. 'Anciãos... moradores da terra' – todas as camadas da sociedade. 'Aconteceu isto em vossos dias... ou nos dias de vossos pais?' – retórica: a calamidade atual é sem precedentes. O princípio é que certos eventos divinos são únicos e exigem atenção especial. Aplicação: esteja atento aos 'sinais dos tempos' que Deus envia à sua geração.",
    "📖 <strong>RESUMO:</strong> Joel convoca anciãos e moradores para ouvirem sobre uma calamidade sem precedentes.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Quando virdes todas estas coisas, sabei que está próximo' (Mateus 24:33).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 3</strong></span>",
    "<strong>TEXTO:</strong> Fazei disto uma narração a vossos filhos, e vossos filhos a seus filhos, e os filhos destes à geração seguinte.",
    "<strong>COMENTÁRIO:</strong> 📢 'Fazei disto uma narração' – transmitir a memória do juízo às futuras gerações. 'A vossos filhos... à geração seguinte' – quatro gerações de transmissão. O princípio é que a memória do juízo de Deus serve como advertência e instrução para as gerações futuras. Aplicação: temos a responsabilidade de ensinar às próximas gerações sobre os atos de Deus, tanto de juízo quanto de misericórdia.",
    "📖 <strong>RESUMO:</strong> Transmiti esta história a vossos filhos, e eles a seus filhos, por gerações.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Nós não as esconderemos de seus filhos; contaremos à geração seguinte' (Salmo 78:4).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 4</strong></span>",
    "<strong>TEXTO:</strong> O que a locusta deixou, o gafanhoto o comeu; e o que o gafanhoto deixou, a larva o comeu; e o que a larva deixou, o cortador o comeu.",
    "<strong>COMENTÁRIO:</strong> 🦗 'Locusta... gafanhoto... larva... cortador' – quatro termos para gafanhotos em diferentes estágios ou espécies (possivelmente: 'gazam', 'arbeh', 'yeleq', 'chasil'). Destruição progressiva e total. 'O que um deixou, o outro comeu' – nada restou. O princípio é que o juízo de Deus pode vir em ondas sucessivas, consumindo tudo. Aplicação: o pecado não poupa; ele consome completamente quando não há arrependimento.",
    "📖 <strong>RESUMO:</strong> Quatro tipos de gafanhotos destruíram completamente a terra: o que um deixou, o outro comeu.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'O ladrão vem somente para roubar, matar e destruir' (João 10:10).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 5</strong></span>",
    "<strong>TEXTO:</strong> Despertai, bêbados, e chorai; gemei, todos os que bebeis vinho, por causa do mosto, porque tirado é da vossa boca.",
    "<strong>COMENTÁRIO:</strong> 🍷 'Despertai, bêbados' – chamado irônico aos que vivem entorpecidos. 'Chorai... gemei' – resposta apropriada à calamidade. 'Mosto tirado da vossa boca' – a fonte de prazer foi removida. O princípio é que o juízo interrompe até mesmo os prazeres pecaminosos. Aplicação: acorde do torpor espiritual antes que o juízo remova até mesmo as ilusões de prazer.",
    "📖 <strong>RESUMO:</strong> Os bêbados devem despertar e chorar, pois o vinho foi tirado de suas bocas.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Não vos embriagueis com vinho, em que há contenda' (Efésios 5:18).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 6</strong></span>",
    "<strong>TEXTO:</strong> Porque um povo poderoso e inumerável subiu sobre a minha terra; os seus dentes são dentes de leão, e têm os queixais de uma leoa.",
    "<strong>COMENTÁRIO:</strong> 🦁 'Um povo poderoso e inumerável' – o exército de gafanhotos descrito como nação invasora. 'Subiu sobre a minha terra' – invasão da terra de Deus. 'Dentes de leão... queixais de leoa' – ferocidade destrutiva. O princípio é que Deus pode usar a criação para executar juízo. Aplicação: quando Deus envia disciplina, ela é poderosa e irresistível.",
    "📖 <strong>RESUMO:</strong> Um povo numeroso e poderoso, com dentes de leão, invadiu a terra.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'O diabo, vosso adversário, anda em derredor como leão' (1 Pedro 5:8).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 7</strong></span>",
    "<strong>TEXTO:</strong> Assolou a minha vide, e descascou a minha figueira; despiu-a toda, e a lançou por terra; os seus ramos se embranqueceram.",
    "<strong>COMENTÁRIO:</strong> 🌿 'Assolou a minha vide... figueira' – destruição das fontes de alimento e prosperidade. 'Despiu-a toda... lançou por terra... ramos embranqueceram' – imagem de devastação completa. Videira e figueira são símbolos de paz e prosperidade (1 Reis 4:25). O princípio é que o juízo remove os símbolos da bênção de Deus. Aplicação: valorize as bênçãos de Deus enquanto as tem; elas podem ser removidas.",
    "📖 <strong>RESUMO:</strong> A vide e a figueira foram destruídas, descascadas, e seus ramos embranquecidos.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Toda árvore que não dá bom fruto é cortada' (Mateus 7:19).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 8</strong></span>",
    "<strong>TEXTO:</strong> Lamenta como a virgem cingida de saco, pelo marido da sua mocidade.",
    "<strong>COMENTÁRIO:</strong> 💔 'Lamenta como a virgem' – imagem de dor profunda e pessoal. 'Cingida de saco' – vestes de luto. 'Marido da sua mocidade' – noivo ou marido jovem, perdido tragicamente. O princípio é que o luto pela perda da comunhão com Deus deve ser tão intenso quanto o luto pela perda de um ente querido. Aplicação: você lamenta a perda da presença de Deus em sua vida?",
    "📖 <strong>RESUMO:</strong> Lamentai como a virgem que perdeu o marido da sua mocidade.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Bem-aventurados os que choram, porque serão consolados' (Mateus 5:4).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 9</strong></span>",
    "<strong>TEXTO:</strong> Cortada está a oferta de alimentos e a libação da casa do Senhor; os sacerdotes, ministros do Senhor, estão entristecidos.",
    "<strong>COMENTÁRIO:</strong> 🏛️ 'Cortada está a oferta de alimentos e a libação' – cessação do culto no templo. 'Sacerdotes... estão entristecidos' – líderes espirituais afetados diretamente. O princípio é que o juízo afeta até mesmo a adoração a Deus. Aplicação: o pecado não apenas prejudica a sociedade, mas também interrompe a adoração verdadeira.",
    "📖 <strong>RESUMO:</strong> As ofertas e libações foram cortadas; os sacerdotes estão entristecidos.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Não deixemos de congregar-nos' (Hebreus 10:25).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 10</strong></span>",
    "<strong>TEXTO:</strong> O campo está assolado, e a terra chora; porque o trigo está destruído, o mosto se secou, o azeite falta.",
    "<strong>COMENTÁRIO:</strong> 🌾 'Campo assolado... terra chora' – personificação da criação que sofre. 'Trigo destruído... mosto seco... azeite falta' – as três principais colheitas de Israel destruídas. O princípio é que o pecado humano afeta toda a criação (Romanos 8:22). Aplicação: nossas escolhas têm impacto cósmico, não apenas pessoal.",
    "📖 <strong>RESUMO:</strong> O campo está assolado, a terra chora; trigo, mosto e azeite foram destruídos.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'A criação geme e suporta dores' (Romanos 8:22).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 11</strong></span>",
    "<strong>TEXTO:</strong> Envergonhai-vos, lavradores; gemei, vinhateiros, sobre o trigo e sobre a cevada; porque a colheita do campo pereceu.",
    "<strong>COMENTÁRIO:</strong> 👨‍🌾 'Envergonhai-vos... gemei' – chamado ao luto para os trabalhadores rurais. 'Trigo e cevada' – colheitas básicas. 'Colheita pereceu' – sustento destruído. O princípio é que todos são afetados pelo juízo, independentemente de sua posição social. Aplicação: o juízo de Deus é democrático; todos sofrem as consequências do pecado coletivo.",
    "📖 <strong>RESUMO:</strong> Lavradores e vinhateiros devem envergonhar-se e gemer, pois a colheita pereceu.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'A seara é grande, mas os trabalhadores são poucos' (Mateus 9:37).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 12</strong></span>",
    "<strong>TEXTO:</strong> A vide se secou, a figueira se murchou; a romeira também, e a palmeira, e a macieira; todas as árvores do campo se secaram; porque a alegria se secou entre os filhos dos homens.",
    "<strong>COMENTÁRIO:</strong> 🌳 'Vide... figueira... romeira... palmeira... macieira' – lista de árvores frutíferas, todas afetadas. 'Alegria se secou entre os filhos dos homens' – a devastação externa reflete a interna. O princípio é que a alegria verdadeira está ligada à bênção de Deus; quando Ele discipline, a alegria desaparece. Aplicação: busque alegria em Deus, não apenas nas bênçãos materiais.",
    "📖 <strong>RESUMO:</strong> Todas as árvores se secaram; a alegria dos homens também se secou.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'A alegria do Senhor é a vossa força' (Neemias 8:10).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 13</strong></span>",
    "<strong>TEXTO:</strong> Cingi-vos e lamentai-vos, sacerdotes; gemei, ministros do altar; entrai, passai a noite vestidos de saco, ministros do meu Deus; porque a oferta de alimentos e a libação estão impedidas da casa de vosso Deus.",
    "<strong>COMENTÁRIO:</strong> 🙏 'Cingi-vos... lamentai-vos... gemei... entrai... passai a noite vestidos de saco' – múltiplos chamados ao luto sacerdotal. 'Oferta e libação impedidas' – o culto está suspenso. O princípio é que os líderes espirituais devem liderar no arrependimento e no luto. Aplicação: líderes espirituais, chorem primeiro pelo pecado e pela perda da presença de Deus.",
    "📖 <strong>RESUMO:</strong> Sacerdotes, cingi-vos de saco, lamentai, passai a noite em luto, pois as ofertas estão impedidas.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Chorai com os que choram' (Romanos 12:15).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 14</strong></span>",
    "<strong>TEXTO:</strong> Santificai um jejum, convocai uma assembléia solene, congregai os anciãos e todos os moradores da terra na casa do Senhor vosso Deus, e clamai ao Senhor.",
    "<strong>COMENTÁRIO:</strong> 📯 'Santificai um jejum' – preparação espiritual para buscar a Deus. 'Convocai uma assembléia solene' – culto público de arrependimento. 'Congregai anciãos e todos os moradores' – inclusão de todos. 'Clamai ao Senhor' – o objetivo final: buscar a Deus. O princípio é que a resposta correta ao juízo é o arrependimento coletivo e a busca sincera por Deus. Aplicação: em tempos de crise, convoque a comunidade para buscar a Deus com jejum e clamor.",
    "📖 <strong>RESUMO:</strong> Santificai um jejum, convocai assembléia, congregai todos na casa do Senhor e clamai a Ele.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Estando reunidos, jejuaram e oraram' (Atos 13:3).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 15</strong></span>",
    "<strong>TEXTO:</strong> Ai do dia! Porque o dia do Senhor está perto, e virá como uma assolação do Todo-Poderoso.",
    "<strong>COMENTÁRIO:</strong> 🌑 'Ai do dia!' – exclamação de terror. 'Dia do Senhor (Yom YHWH)' – termo técnico para o dia do juízo divino. 'Perto' – iminente. 'Assolação do Todo-Poderoso (Shaddai)' – destruição vinda do Deus Todo-Poderoso. O princípio é que o 'Dia do Senhor' é um tema central em Joel: um dia de juízo e terror para os ímpios. Aplicação: esteja preparado para o Dia do Senhor; ele virá inesperadamente.",
    "📖 <strong>RESUMO:</strong> Ai! O dia do Senhor está perto; virá como destruição do Todo-Poderoso.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'O grande dia da sua ira é chegado' (Apocalipse 6:17).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 16</strong></span>",
    "<strong>TEXTO:</strong> Porventura não está cortado o mantimento diante dos nossos olhos? E a alegria e o regozijo da casa de nosso Deus?",
    "<strong>COMENTÁRIO:</strong> 🍞 'Mantimento cortado' – falta de alimento físico. 'Alegria e regozijo da casa de nosso Deus' – perda da adoração alegre. O princípio é que a crise física reflete a crise espiritual. Aplicação: quando o culto a Deus é interrompido, a alegria verdadeira também cessa.",
    "📖 <strong>RESUMO:</strong> O mantimento foi cortado, e a alegria da casa de Deus também.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Nem só de pão viverá o homem' (Mateus 4:4).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 17</strong></span>",
    "<strong>TEXTO:</strong> A semente apodreceu debaixo dos seus torrões; os celeiros estão assolados, os depósitos derrubados, porque o trigo se secou.",
    "<strong>COMENTÁRIO:</strong> 🌱 'Semente apodreceu' – não há esperança de colheita futura. 'Celeiros assolados... depósitos derrubados' – estoques destruídos. 'Trigo se secou' – causa da destruição. O princípio é que o juízo afeta não apenas o presente, mas também o futuro. Aplicação: o pecado não apenas destrói o agora, mas compromete o amanhã.",
    "📖 <strong>RESUMO:</strong> A semente apodreceu, os celeiros estão assolados, o trigo secou.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'O que semeia para a sua carne, da carne ceifará a corrupção' (Gálatas 6:8).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 18</strong></span>",
    "<strong>TEXTO:</strong> Como geme o animal! As manadas de gado estão perplexas, porque não têm pasto; também os rebanhos de ovelhas estão desolados.",
    "<strong>COMENTÁRIO:</strong> 🐄 'Como geme o animal' – criação sofre com o juízo. 'Manadas perplexas... rebanhos desolados' – animais sem pasto, confusos e famintos. O princípio é que o juízo de Deus afeta toda a ordem criada. Aplicação: cuidar da criação é também uma responsabilidade espiritual; o pecado ecológico tem consequências.",
    "📖 <strong>RESUMO:</strong> Os animais gemem; as manadas estão perplexas; os rebanhos estão desolados sem pasto.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'A criação aguarda a manifestação dos filhos de Deus' (Romanos 8:19).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 19</strong></span>",
    "<strong>TEXTO:</strong> A ti, ó Senhor, clamo; porque o fogo consumiu os pastos do deserto, e a chama abrasou todas as árvores do campo.",
    "<strong>COMENTÁRIO:</strong> 🔥 'A ti, ó Senhor, clamo' – Joel clama a Deus em meio à crise. 'Fogo consumiu os pastos... chama abrasou as árvores' – imagem de destruição total, possivelmente combinando praga de gafanhotos com seca e incêndios. O princípio é que a resposta correta à crise é clamar a Deus, não aos homens. Aplicação: em tempos de devastação, volte-se para Deus em oração.",
    "📖 <strong>RESUMO:</strong> Joel clama ao Senhor, pois o fogo consumiu pastos e árvores.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Clama a mim, e responder-te-ei' (Jeremias 33:3).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 20</strong></span>",
    "<strong>TEXTO:</strong> Também os animais do campo suspiram por ti; porque as correntes de água se secaram, e o fogo consumiu os pastos do deserto.",
    "<strong>COMENTÁRIO:</strong> 🦌 'Animais do campo suspiram por ti' – até a criação anseia por Deus. 'Correntes de água se secaram' – a fonte de vida foi removida. 'Fogo consumiu os pastos' – repetição para ênfase. O princípio é que a criação depende de Deus e sofre quando Ele retém Suas bênçãos. Aplicação: reconheça sua dependência completa de Deus para todas as coisas, inclusive para as necessidades básicas.",
    "📖 <strong>RESUMO:</strong> Os animais suspiram por Deus; as águas secaram; o fogo consumiu os pastos.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Os olhos de todos esperam em ti' (Salmo 145:15).",
    
    
    "<p style='font-size: 0.8rem; text-align: center;'><i><strong>Reflexão Final do Capítulo 1</strong></i></p>",
    "<p style='font-size: 0.6rem;'>Joel 1 descreve uma praga catastrófica de gafanhotos que devastou completamente a terra de Judá. Quatro tipos de gafanhotos consumiram tudo em ondas sucessivas. A videira, a figueira, as árvores frutíferas, o trigo, a cevada, o vinho e o azeite – tudo foi destruído. Até os animais sofrem. O culto no templo foi interrompido. O capítulo chama todos ao luto: bêbados, lavradores, sacerdotes, anciãos, toda a nação. O 'Dia do Senhor' é anunciado como iminente. O capítulo ensina que: 1) O juízo de Deus pode vir em ondas sucessivas e destruir completamente; 2) O pecado afeta não apenas os indivíduos, mas toda a sociedade, a adoração e a criação; 3) A resposta correta ao juízo é o arrependimento coletivo, jejum e clamor a Deus; 4) O 'Dia do Senhor' é um tema central que será desenvolvido nos capítulos seguintes.</p>"
  ],
  
  2: [
    "<p style='font-size: 0.8rem; text-align: center;'><i><strong>O Exército do Senhor e o Chamado ao Arrependimento: A Promessa do Espírito</strong></i></p>",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 1</strong></span>",
    "<strong>TEXTO:</strong> Tocai a trombeta em Sião, e davai alarme no meu santo monte; estremeçam todos os moradores da terra, porque o dia do Senhor vem, já está perto;",
    "<strong>COMENTÁRIO:</strong> 📯 'Tocai a trombeta em Sião' – alerta de guerra em Jerusalém. 'Dai alarme no meu santo monte' – Monte Sião, local do templo. 'Estremeçam todos os moradores' – chamado universal ao terror. 'O dia do Senhor vem, já está perto' – iminência do juízo divino. O princípio é que o Dia do Senhor é um evento terrível que exige alerta máximo. Aplicação: a trombeta do juízo ainda soará; esteja preparado. Reflexão: você responderia ao 'alarme' do Dia do Senhor com medo ou com esperança?",
    "📖 <strong>RESUMO:</strong> Toquem a trombeta em Sião e alarme no monte santo; o dia do Senhor está perto.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Num momento, num abrir e fechar de olhos, ante a última trombeta' (1 Coríntios 15:52).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 2</strong></span>",
    "<strong>TEXTO:</strong> Dia de trevas e de escuridão, dia de nuvens e de densas trevas; como a alva se estende sobre os montes; um povo grande e poderoso, qual nunca houve desde os tempos antigos, nem depois dele haverá pelos anos adiante de geração em geração.",
    "<strong>COMENTÁRIO:</strong> 🌑 'Dia de trevas e escuridão... nuvens e densas trevas' – descrição apocalíptica do Dia do Senhor. 'Como a alva se estende sobre os montes' – o exército invasor cobre a terra como a luz da manhã. 'Povo grande e poderoso, qual nunca houve... nem depois haverá' – um exército sem precedentes na história. O princípio é que o Dia do Senhor será um evento único e aterrorizante. Aplicação: a história caminha para um clímax divino; viva com essa expectativa.",
    "📖 <strong>RESUMO:</strong> O dia do Senhor é de trevas; um povo poderoso, sem precedentes na história, cobre a terra.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Porque então haverá grande tribulação, como nunca houve' (Mateus 24:21).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 3</strong></span>",
    "<strong>TEXTO:</strong> Diante dele um fogo consome, e atrás dele uma chama abrasa; a terra diante dele é como o jardim do Éden, mas atrás dele um desolado deserto; sim, nada escapa dele.",
    "<strong>COMENTÁRIO:</strong> 🔥 'Fogo consome... chama abrasa' – poder destrutivo do exército. 'Diante... como jardim do Éden' – beleza original. 'Atrás... desolado deserto' – devastação completa. 'Nada escapa dele' – juízo total. O princípio é que o juízo de Deus é terrivelmente eficaz; nenhum pecado escapa. Aplicação: a beleza do Éden pode se tornar deserto em um momento se Deus retirar Sua mão protetora.",
    "📖 <strong>RESUMO:</strong> Diante do exército é como o Éden; atrás, deserto devastado; nada escapa.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'O mundo passa, e a sua concupiscência' (1 João 2:17).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 4</strong></span>",
    "<strong>TEXTO:</strong> O seu aspecto é como o de cavalos, e como cavaleiros, assim correm.",
    "<strong>COMENTÁRIO:</strong> 🐎 'Aspecto como o de cavalos' – os gafanhotos descritos com imagens de guerra. 'Como cavaleiros, assim correm' – velocidade e ordem militar. O princípio é que a criação de Deus pode se tornar um exército para executar Seu juízo. Aplicação: Deus é soberano sobre todas as forças da natureza; elas obedecem à Sua vontade.",
    "📖 <strong>RESUMO:</strong> O aspecto do exército é como cavalos; correm como cavaleiros.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Os cavalos do inferno' (Apocalipse 9:7).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 5</strong></span>",
    "<strong>TEXTO:</strong> Como o estrondo de carros, saltam eles sobre os cumes dos montes; como o crepitar da chama de fogo que devora a palha, como um povo poderoso posto em ordem de batalha.",
    "<strong>COMENTÁRIO:</strong> 💥 'Estrondo de carros' – som ensurdecedor do exército. 'Crepitar da chama... que devora a palha' – destruição rápida e total. 'Povo poderoso em ordem de batalha' – disciplina militar. O princípio é que o exército de Deus é organizado e imparável. Aplicação: quando Deus age em juízo, nenhuma força humana pode resistir.",
    "📖 <strong>RESUMO:</strong> O exército avança com estrondo de carros e rapidez de fogo; está em ordem de batalha.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'O Senhor é homem de guerra' (Êxodo 15:3).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 6</strong></span>",
    "<strong>TEXTO:</strong> Diante dele os povos se contorcem; todos os rostos se tornam pálidos.",
    "<strong>COMENTÁRIO:</strong> 😨 'Povos se contorcem' – convulsões de terror. 'Rostos se tornam pálidos' – expressão universal de medo. O princípio é que o Dia do Senhor causa terror universal. Aplicação: o temor do Senhor é o princípio da sabedoria; quem não O teme agora, temerá no Seu dia.",
    "📖 <strong>RESUMO:</strong> Diante do exército, os povos se contorcem e os rostos empalidecem.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Os reis da terra... se esconderão nas cavernas' (Apocalipse 6:15).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 7</strong></span>",
    "<strong>TEXTO:</strong> Como valentes, correm; como homens de guerra, sobem os muros; e andam cada um no seu caminho, e não se desviam das suas fileiras.",
    "<strong>COMENTÁRIO:</strong> ⚔️ 'Como valentes correm... homens de guerra sobem muros' – coragem e habilidade militar. 'Cada um no seu caminho... não se desviam' – disciplina perfeita, sem desordem. O princípio é que o exército de Deus age com perfeita coordenação. Aplicação: a obediência a Deus deve ser precisa e inabalável, como a deste exército.",
    "📖 <strong>RESUMO:</strong> Corre como valente, sobe muros, mantém formação, não se desvia.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Bom soldado de Jesus Cristo' (2 Timóteo 2:3).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 8</strong></span>",
    "<strong>TEXTO:</strong> Nem um empurra o outro; cada um segue a sua carreira; arremetem contra as armas, mas não se quebram.",
    "<strong>COMENTÁRIO:</strong> 🛡️ 'Nem um empurra o outro' – ordem perfeita, sem confusão. 'Arremetem contra as armas, mas não se quebram' – não recuam diante de obstáculos; são imparáveis. O princípio é que o juízo de Deus é irresistível e ordenado. Aplicação: quando Deus decide agir, nada O detém e tudo está sob Seu controle soberano.",
    "📖 <strong>RESUMO:</strong> Ninguém empurra ninguém; cada um segue sua carreira; não se quebram diante das armas.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Ninguém pode arrebatá-las da mão de meu Pai' (João 10:29).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 9</strong></span>",
    "<strong>TEXTO:</strong> Correm pela cidade, sobem os muros, trepam pelas casas; entram pelas janelas como um ladrão.",
    "<strong>COMENTÁRIO:</strong> 🏠 'Correm pela cidade... sobem muros... trepam casas... entram pelas janelas' – invasão total, sem defesa possível. 'Como um ladrão' – inesperado e penetrante. O princípio é que o juízo de Deus penetra todas as defesas humanas. Aplicação: não confie em muros, cidades fortificadas ou sistemas de segurança; só Deus é verdadeira proteção.",
    "📖 <strong>RESUMO:</strong> Corre pela cidade, sobe muros, entra em casas e janelas como ladrão.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Se o dono da casa soubesse a que hora viria o ladrão, vigiaria' (Mateus 24:43).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 10</strong></span>",
    "<strong>TEXTO:</strong> Diante deles a terra treme, e os céus se abalam; o sol e a lua se escurecem, e as estrelas retiram o seu resplendor.",
    "<strong>COMENTÁRIO:</strong> 🌍 'Terra treme... céus se abalam' – comoção cósmica. 'Sol, lua, estrelas escurecem' – sinais cósmicos do Dia do Senhor (cf. Joel 2:31; Mateus 24:29). O princípio é que o Dia do Senhor afeta toda a ordem cósmica, não apenas a terra. Aplicação: a criação inteira responderá ao seu Criador no dia final.",
    "📖 <strong>RESUMO:</strong> Terra treme, céus se abalam, sol e lua escurecem, estrelas perdem o brilho.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'O sol se escurecerá, e a lua não dará o seu resplendor' (Mateus 24:29).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 11</strong></span>",
    "<strong>TEXTO:</strong> E o Senhor levanta a sua voz diante do seu exército; porque o seu acampamento é mui grande; porque é poderoso quem executa a sua palavra; porque grande é o dia do Senhor, e mui terrível; e quem o poderá suportar?",
    "<strong>COMENTÁRIO:</strong> 🗣️ 'O Senhor levanta a sua voz' – Deus comanda Seu exército. 'Seu acampamento é mui grande' – as forças divinas são incontáveis. 'Poderoso quem executa a sua palavra' – os executores do juízo são poderosos. 'Grande é o dia do Senhor... quem o poderá suportar?' – pergunta retórica: ninguém pode resistir ao juízo divino. O princípio é que o Dia do Senhor é irresistível e universal. Aplicação: faça as pazes com Deus agora, antes que o Dia chegue. Reflexão: você poderá suportar o Dia do Senhor?",
    "📖 <strong>RESUMO:</strong> O Senhor comanda Seu grande exército; Seu dia é terrível; quem pode suportá-lo?",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Quem poderá subsistir diante da sua ira?' (Apocalipse 6:17).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 12</strong></span>",
    "<strong>TEXTO:</strong> Portanto, agora ainda, diz o Senhor, convertei-vos a mim com todo o vosso coração, e com jejuns, e com choro, e com pranto.",
    "<strong>COMENTÁRIO:</strong> 💔 'Portanto, agora ainda' – graça: ainda há tempo. 'Convertei-vos a mim' – chamado ao arrependimento. 'Com todo o vosso coração' – arrependimento total, não superficial. 'Com jejuns, choro e pranto' – expressões externas de um coração quebrantado. O princípio é que o arrependimento genuíno envolve todo o ser e se expressa em ações concretas. Aplicação: Deus oferece oportunidade de arrependimento mesmo quando o juízo está próximo. Aproveite agora.",
    "📖 <strong>RESUMO:</strong> Ainda há tempo: convertei-vos a Deus com todo o coração, jejum, choro e pranto.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Arrependei-vos, pois, e convertei-vos' (Atos 3:19).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 13</strong></span>",
    "<strong>TEXTO:</strong> Rasgai o vosso coração, e não as vossas vestes, e convertei-vos ao Senhor vosso Deus; porque ele é misericordioso, e compassivo, e tardio em irar-se, e grande em benignidade, e se arrepende do mal.",
    "<strong>COMENTÁRIO:</strong> 💗 'Rasgai o vosso coração, e não as vossas vestes' – arrependimento interior, não apenas ritual externo. 'Porque ele é misericordioso... compassivo... tardio em irar-se... grande em benignidade... se arrepende do mal' – os atributos de Deus que dão esperança. Este é um dos versículos mais importantes sobre o caráter de Deus no Antigo Testamento (cf. Êxodo 34:6). O princípio é que o arrependimento genuíno é baseado no caráter misericordioso de Deus. Aplicação: Deus não quer rituais vazios; Ele quer corações transformados. Reflexão: seu coração tem sido 'rasgado' diante de Deus?",
    "📖 <strong>RESUMO:</strong> Rasgai o coração, não as vestes; convertei-vos, pois Deus é misericordioso e compassivo.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Deus resiste aos soberbos, mas dá graça aos humildes' (Tiago 4:6).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 14</strong></span>",
    "<strong>TEXTO:</strong> Quem sabe se ele não se voltará e se arrependerá, e deixará após si uma bênção, em oferta de alimentos e libação para o Senhor vosso Deus?",
    "<strong>COMENTÁRIO:</strong> ❓ 'Quem sabe se ele não se voltará?' – expressão de esperança condicional, não presunção. 'Se arrependerá' – linguagem antropomórfica para mudança de ação divina. 'Deixará após si uma bênção' – restauração da prosperidade. 'Oferta de alimentos e libação' – restauração do culto. O princípio é que nunca sabemos com certeza o quanto Deus pode se mover em resposta ao arrependimento; por isso, devemos sempre nos arrepender. Aplicação: não presuma da graça, mas também não duvide da misericórdia de Deus.",
    "📖 <strong>RESUMO:</strong> Quem sabe se Deus não se arrependerá e deixará uma bênção, restaurando ofertas e libações?",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'A misericórdia triunfa sobre o juízo' (Tiago 2:13).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 15</strong></span>",
    "<strong>TEXTO:</strong> Tocai a trombeta em Sião, santificai um jejum, convocai uma assembléia solene.",
    "<strong>COMENTÁRIO:</strong> 📯 'Tocai a trombeta' – novamente o chamado ao alerta, mas agora para convocar ao arrependimento. 'Santificai jejum... convocai assembléia' – repetição do chamado do capítulo 1, agora em contexto de esperança. O princípio é que o chamado ao arrependimento deve ser urgente e público. Aplicação: não se arrependa em particular apenas; a comunidade deve se unir em arrependimento coletivo.",
    "📖 <strong>RESUMO:</strong> Toquem a trombeta em Sião, santifiquem jejum, convoquem assembléia solene.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Confessai as vossas culpas uns aos outros' (Tiago 5:16).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 16</strong></span>",
    "<strong>TEXTO:</strong> Congregai o povo, santificai a congregação, ajuntai os anciãos, congregai os meninos e os que mamam; saia o noivo da sua recâmara, e a noiva do seu quarto.",
    "<strong>COMENTÁRIO:</strong> 👨‍👩‍👧‍👦 'Congregai o povo... santificai a congregação' – reunião universal. 'Anciãos... meninos... os que mamam' – todas as idades, do mais velho ao mais novo. 'Noivo... noiva' – até mesmo os recém-casados, que normalmente eram isentos de obrigações (Deuteronômio 24:5), devem participar. O princípio é que o arrependimento nacional inclui absolutamente todos. Aplicação: ninguém está isento do chamado ao arrependimento; todos precisam se humilhar diante de Deus.",
    "📖 <strong>RESUMO:</strong> Congregai todos: anciãos, crianças, lactentes, noivos e noivas – ninguém excluído.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Toda a alma se humilhe diante de Deus' (Tiago 4:10).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 17</strong></span>",
    "<strong>TEXTO:</strong> Chorem os sacerdotes, ministros do Senhor, entre o pórtico e o altar, e digam: Poupa o teu povo, ó Senhor, e não entregues a tua herança ao opróbrio, para que as nações o dominem; por que diriam entre os povos: Onde está o seu Deus?",
    "<strong>COMENTÁRIO:</strong> 🙏 'Chorem os sacerdotes entre o pórtico e o altar' – lugar específico no templo, entre o altar dos holocaustos e o pórtico. 'Poupa o teu povo... tua herança' – intercessão baseada no relacionamento de aliança. 'Para que as nações não digam: Onde está o seu Deus?' – preocupação com o nome de Deus entre os pagãos. O princípio é que a intercessão deve ser baseada na glória de Deus e em Seu caráter de aliança. Aplicação: orem não apenas por livramento, mas para que o nome de Deus seja glorificado entre as nações.",
    "📖 <strong>RESUMO:</strong> Os sacerdotes devem chorar e interceder: 'Poupa teu povo, para que as nações não escarneçam: Onde está o Deus deles?'",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Santificado seja o teu nome' (Mateus 6:9).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 18</strong></span>",
    "<strong>TEXTO:</strong> Então o Senhor se zelará pela sua terra, e se compadecerá do seu povo.",
    "<strong>COMENTÁRIO:</strong> 🔥 'Então' – resposta divina ao arrependimento. 'Zelará pela sua terra' – ciúme santo de Deus por Sua herança. 'Compadecerá do seu povo' – misericórdia em resposta ao arrependimento. O princípio é que Deus responde ao arrependimento sincero com zelo e compaixão. Aplicação: o arrependimento genuíno nunca é em vão; Deus sempre responde com misericórdia.",
    "📖 <strong>RESUMO:</strong> Então o Senhor terá zelo por Sua terra e compaixão de Seu povo.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Aproximai-vos de Deus, e ele se aproximará de vós' (Tiago 4:8).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 19</strong></span>",
    "<strong>TEXTO:</strong> E o Senhor responderá, e dirá ao seu povo: Eis que vos envio o trigo, e o vinho, e o azeite, e deles vos fartareis; e nunca mais vos porei por opróbrio entre as nações.",
    "<strong>COMENTÁRIO:</strong> 🌾 'Responderá... e dirá' – resposta divina em palavras e ações. 'Envio o trigo, vinho e azeite' – restauração das bênçãos materiais. 'Deles vos fartareis' – abundância, não apenas suficiência. 'Nunca mais vos porei por opróbrio' – restauração da honra nacional. O princípio é que a restauração de Deus é completa: material, espiritual e social. Aplicação: Deus não apenas perdoa, mas também restaura o que foi perdido.",
    "📖 <strong>RESUMO:</strong> Deus responde: enviarei trigo, vinho e azeite; vos fartareis; não sereis mais opróbrio.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Buscai primeiro o reino... todas estas coisas vos serão acrescentadas' (Mateus 6:33).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 20</strong></span>",
    "<strong>TEXTO:</strong> E afastarei para longe de vós o exército do norte, e o lançarei numa terra seca e deserta, a sua frente para o mar oriental, e a sua retaguarda para o mar ocidental; e o seu mau cheiro subirá, e a sua podridão exalará, porque fez grandes coisas.",
    "<strong>COMENTÁRIO:</strong> 🦗 'Exército do norte' – os gafanhotos (que geralmente vinham do norte/nordeste) ou exército invasor. 'Lançarei numa terra seca e deserta' – destruição do exército inimigo. 'Frente para o mar oriental (Mar Morto)... retaguarda para o mar ocidental (Mediterrâneo)' – dispersão completa. 'Mau cheiro... podridão' – decomposição dos cadáveres. O princípio é que Deus não apenas remove o juízo, mas também derrota completamente o inimigo. Aplicação: Deus é um libertador que não apenas retira a ameaça, mas a destrói completamente.",
    "📖 <strong>RESUMO:</strong> Deus afastará o exército do norte, lançando-o no deserto; seu mau cheiro subirá.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Onde está, ó morte, a tua vitória?' (1 Coríntios 15:55).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 21</strong></span>",
    "<strong>TEXTO:</strong> Não temas, ó terra; regozija-te e alegra-te, porque o Senhor fez grandes coisas.",
    "<strong>COMENTÁRIO:</strong> 🌍 'Não temas, ó terra' – reversão do lamento anterior. 'Regozija-te e alegra-te' – chamado à alegria. 'O Senhor fez grandes coisas' – a causa da alegria são os atos poderosos de Deus. O princípio é que a restauração divina transforma luto em alegria. Aplicação: Deus é poderoso para transformar sua situação de desespero em alegria.",
    "📖 <strong>RESUMO:</strong> Não temas, ó terra; alegra-te, porque o Senhor fez grandes coisas.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Alegrai-vos sempre no Senhor' (Filipenses 4:4).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 22</strong></span>",
    "<strong>TEXTO:</strong> Não temais, animais do campo; porque os pastos do deserto já reverdecem, porque a árvore dá o seu fruto, e a vide e a figueira dão a sua força.",
    "<strong>COMENTÁRIO:</strong> 🦌 'Não temais, animais do campo' – até a criação é consolada. 'Pastos reverdecem... árvore dá fruto... vide e figueira dão força' – restauração ecológica completa. O princípio é que a restauração da relação do homem com Deus traz restauração para toda a criação. Aplicação: a salvação de Deus é cósmica, não apenas pessoal.",
    "📖 <strong>RESUMO:</strong> Não temais, animais; os pastos reverdecem, as árvores dão fruto.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'A própria criação será libertada' (Romanos 8:21).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 23</strong></span>",
    "<strong>TEXTO:</strong> Alegrai-vos, pois, filhos de Sião, e regozijai-vos no Senhor vosso Deus; porque ele vos dará a chuva a seu tempo, e fará descer para vós a chuva temporã e a serôdia, no primeiro mês.",
    "<strong>COMENTÁRIO:</strong> ☔ 'Alegrai-vos... regozijai-vos no Senhor vosso Deus' – a alegria é em Deus, não apenas nas bênçãos. 'Chuva a seu tempo... temporã e serôdia' – restauração das chuvas: temporã (outono, para plantar) e serôdia (primavera, para colher). 'No primeiro mês' – tempo específico da restauração. O princípio é que Deus controla as estações e abençoa Seu povo com prosperidade agrícola. Aplicação: alegre-se em Deus, não apenas no que Ele dá, mas em quem Ele é.",
    "📖 <strong>RESUMO:</strong> Alegrai-vos no Senhor; Ele dará chuva temporã e serôdia.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Alegrai-vos no Senhor; outra vez digo, alegrai-vos' (Filipenses 4:4).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 24</strong></span>",
    "<strong>TEXTO:</strong> E as eiras se encherão de trigo, e os lagares transbordarão de vinho e de azeite.",
    "<strong>COMENTÁRIO:</strong> 🌾 'Eiras se encherão de trigo' – colheita abundante. 'Lagares transbordarão de vinho e azeite' – superabundância. O princípio é que a bênção de Deus é abundante, transbordante. Aplicação: Deus não apenas supre, mas transborda em generosidade para com Seus filhos.",
    "📖 <strong>RESUMO:</strong> As eiras se encherão de trigo; os lagares transbordarão de vinho e azeite.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Boa medida, recalcada, sacudida e transbordante' (Lucas 6:38).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 25</strong></span>",
    "<strong>TEXTO:</strong> E restituir-vos-ei os anos que foram consumidos pela locusta, pelo gafanhoto, e pela larva, e pelo cortador, o meu grande exército que enviei contra vós.",
    "<strong>COMENTÁRIO:</strong> ⏰ 'Restituir-vos-ei os anos consumidos' – promessa única e maravilhosa: Deus compensa o tempo perdido. 'Locusta, gafanhoto, larva, cortador' – os quatro agentes de destruição do capítulo 1. 'Meu grande exército' – confirmação de que a praga veio de Deus. O princípio é que Deus restaura não apenas o que foi perdido, mas compensa o tempo de sofrimento. Aplicação: Deus pode restaurar 'anos consumidos' – anos de pecado, sofrimento, perda. Nunca é tarde para a restauração divina. Reflexão: que 'anos consumidos' você precisa que Deus restaure?",
    "📖 <strong>RESUMO:</strong> Restituirei os anos consumidos pelas pragas, meu grande exército.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Todas as coisas cooperam para o bem' (Romanos 8:28).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 26</strong></span>",
    "<strong>TEXTO:</strong> E comereis abundantemente, e vos fartareis, e louvareis o nome do Senhor vosso Deus, que procedeu para convosco maravilhosamente; e o meu povo nunca mais será envergonhado.",
    "<strong>COMENTÁRIO:</strong> 🍽️ 'Comereis abundantemente... vos fartareis' – saciedade como bênção. 'Louvareis o nome do Senhor' – a resposta adequada à bênção é louvor. 'Procedeu maravilhosamente' – reconhecimento dos atos milagrosos de Deus. 'Nunca mais será envergonhado' – restauração permanente da honra. O princípio é que a bênção de Deus leva ao louvor e à restauração da dignidade. Aplicação: Deus nos abençoa para que O louvemos, não apenas para que sejamos felizes.",
    "📖 <strong>RESUMO:</strong> Comereis até fartar, louvareis a Deus, e nunca mais sereis envergonhados.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Aquele que começou a boa obra em vós a aperfeiçoará' (Filipenses 1:6).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 27</strong></span>",
    "<strong>TEXTO:</strong> E sabereis que eu estou no meio de Israel, e que eu sou o Senhor vosso Deus, e não há outro; e o meu povo nunca mais será envergonhado.",
    "<strong>COMENTÁRIO:</strong> 🤝 'Sabereis que eu estou no meio de Israel' – conhecimento experimental da presença de Deus. 'Eu sou o Senhor vosso Deus, e não há outro' – confirmação do monoteísmo e do relacionamento de aliança. 'Nunca mais será envergonhado' – repetição para ênfase. O princípio é que o propósito final das bênçãos de Deus é que Seu povo O conheça como único Deus e Senhor. Aplicação: o conhecimento de Deus é o maior prêmio; as bênçãos materiais são secundárias.",
    "📖 <strong>RESUMO:</strong> Sabereis que Deus está no meio de Israel, que Ele é o Senhor, e não há outro; nunca mais sereis envergonhados.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Esta é a vida eterna: que te conheçam' (João 17:3).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 28</strong></span>",
    "<strong>TEXTO:</strong> E há de ser que, depois derramarei o meu Espírito sobre toda a carne; e vossos filhos e vossas filhas profetizarão, os vossos velhos terão sonhos, e os vossos jovens terão visões;",
    "<strong>COMENTÁRIO:</strong> 💨 'Depois' – após o juízo e a restauração, um evento futuro maior. 'Derramarei o meu Espírito' – efusão do Espírito, não medida limitada. 'Sobre toda a carne' – universal: judeus e gentios, jovens e velhos, homens e mulheres. 'Filhos e filhas profetizarão... velhos sonhos... jovens visões' – democratização dos dons espirituais. Este versículo é central no Pentecostes (Atos 2). O princípio é que Deus derrama Seu Espírito sobre todos os Seus filhos na nova aliança. Aplicação: você já recebeu o derramamento do Espírito? O Espírito está disponível para toda a carne.",
    "📖 <strong>RESUMO:</strong> Depois disso, derramarei meu Espírito sobre toda carne; todos profetizarão, terão sonhos e visões.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Isto é o que foi dito pelo profeta Joel' (Atos 2:16-21).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 29</strong></span>",
    "<strong>TEXTO:</strong> E também sobre os servos e sobre as servas, naqueles dias, derramarei o meu Espírito.",
    "<strong>COMENTÁRIO:</strong> 👤 'Também sobre os servos e servas' – inclusão dos escravos e das classes mais baixas. 'Naqueles dias' – o tempo do derramamento. O princípio é que o Espírito de Deus ignora barreiras sociais e de classe. Aplicação: diante de Deus, não há escravo nem livre; todos são iguais para receber o Espírito.",
    "📖 <strong>RESUMO:</strong> Também sobre servos e servas derramarei meu Espírito naqueles dias.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Não há judeu nem grego, escravo nem livre' (Gálatas 3:28).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 30</strong></span>",
    "<strong>TEXTO:</strong> E mostrarei prodígios no céu e na terra; sangue, e fogo, e colunas de fumaça.",
    "<strong>COMENTÁRIO:</strong> 🌋 'Prodigios no céu e na terra' – sinais cósmicos que precedem o Dia do Senhor. 'Sangue, fogo, colunas de fumaça' – imagens de guerra e juízo. O princípio é que o Dia do Senhor será precedido por sinais sobrenaturais. Aplicação: os sinais nos lembram que a história está sob controle divino e caminha para um clímax.",
    "📖 <strong>RESUMO:</strong> Mostrarei prodígios no céu e na terra: sangue, fogo e colunas de fumaça.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Havereá sinais no sol, na lua e nas estrelas' (Lucas 21:25).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 31</strong></span>",
    "<strong>TEXTO:</strong> O sol se converterá em trevas, e a lua em sangue, antes que venha o grande e terrível dia do Senhor.",
    "<strong>COMENTÁRIO:</strong> 🌞 'Sol em trevas... lua em sangue' – escuridão cósmica como sinal do juízo. 'Antes que venha o grande e terrível dia do Senhor' – esses sinais precedem o Dia. O princípio é que o Dia do Senhor é um evento de magnitude cósmica, precedido por perturbações celestiais. Aplicação: o universo físico responderá ao seu Criador no final dos tempos.",
    "📖 <strong>RESUMO:</strong> O sol se tornará trevas, e a lua sangue, antes do grande e terrível dia do Senhor.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'O sol escurecerá e a lua não dará seu resplendor' (Mateus 24:29).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 32</strong></span>",
    "<strong>TEXTO:</strong> E acontecerá que todo aquele que invocar o nome do Senhor será salvo; porque no monte Sião e em Jerusalém haverá livramento, como disse o Senhor, e entre os sobreviventes aqueles que o Senhor chamar.",
    "<strong>COMENTÁRIO:</strong> 🙌 'Todo aquele que invocar o nome do Senhor será salvo' – a grande promessa de salvação para todos que se voltarem a Deus. 'No monte Sião e em Jerusalém haverá livramento' – o lugar da salvação. 'Sobreviventes... que o Senhor chamar' – o remanescente eleito. Paulo cita este versículo em Romanos 10:13 como a base para a salvação pela fé. O princípio é que a salvação está disponível para todos que invocarem o nome do Senhor. Aplicação: invoque o nome do Senhor hoje mesmo; a promessa de salvação ainda está de pé. Reflexão: você já invocou o nome do Senhor para salvação?",
    "📖 <strong>RESUMO:</strong> Todo aquele que invocar o nome do Senhor será salvo; haverá livramento em Sião para os chamados.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Todo aquele que invocar o nome do Senhor será salvo' (Romanos 10:13).",
    
    
    "<p style='font-size: 0.8rem; text-align: center;'><i><strong>Reflexão Final do Capítulo 2</strong></i></p>",
    "<p style='font-size: 0.6rem;'>Joel 2 é o coração teológico do livro. O capítulo descreve o 'Dia do Senhor' como um evento terrível de juízo, usando imagens de um exército invencível de gafanhotos. Mas o centro do capítulo é o chamado ao arrependimento (vs. 12-17): 'Rasgai o vosso coração, e não as vossas vestes'. Deus é descrito como 'misericordioso, compassivo, tardio em irar-se, grande em benignidade'. O arrependimento genuíno leva à restauração: Deus promete restaurar os 'anos consumidos' pelas pragas. O clímax do capítulo é a promessa do derramamento do Espírito sobre toda a carne (vs. 28-29), cumprida no Pentecostes (Atos 2). O capítulo ensina que: 1) O Dia do Senhor é terrível, mas há esperança no arrependimento; 2) Deus é misericordioso e responde ao arrependimento sincero; 3) A restauração de Deus é completa e compensa o tempo perdido; 4) O derramamento do Espírito é a grande promessa da nova aliança; 5) 'Todo aquele que invocar o nome do Senhor será salvo' é a promessa universal de salvação.</p>"
  ],
  
  3: [
    "<p style='font-size: 0.8rem; text-align: center;'><i><strong>O Julgamento das Nações: O Vale de Josafá e a Habitação Eterna de Deus em Sião</strong></i></p>",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 1</strong></span>",
    "<strong>TEXTO:</strong> Porque eis que naqueles dias, e naquele tempo, em que eu trouxer do cativeiro Judá e Jerusalém,",
    "<strong>COMENTÁRIO:</strong> ⏰ 'Naqueles dias, e naquele tempo' – refere-se aos 'últimos dias' mencionados no capítulo 2. 'Trouxer do cativeiro Judá e Jerusalém' – restauração do exílio (embora Joel possa estar pensando em um cativeiro mais imediato ou no escatológico). O princípio é que a restauração de Israel precede o juízo final das nações. Aplicação: Deus tem um plano para Israel que ainda se cumprirá plenamente.",
    "📖 <strong>RESUMO:</strong> Naqueles dias, quando Deus trouxer Judá e Jerusalém do cativeiro...",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Todo Israel será salvo' (Romanos 11:26).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 2</strong></span>",
    "<strong>TEXTO:</strong> Congregarei todas as nações, e as farei descer ao vale de Josafá; e ali com elas entrarei em juízo, por causa do meu povo, e da minha herança, Israel, a quem eles espalharam entre as nações, e repartiram a minha terra.",
    "<strong>COMENTÁRIO:</strong> ⚖️ 'Congregarei todas as nações' – julgamento universal. 'Vale de Josafá' – nome que significa 'Yahweh julga'. Localização incerta (possivelmente vale do Cedrom). 'Entrarei em juízo' – tribunal divino. 'Por causa do meu povo... minha herança' – Deus defende Seu povo. 'Espalharam... repartiram a minha terra' – acusação específica: dispersão e divisão da terra de Israel. O princípio é que Deus julgará as nações com base em como trataram Seu povo e Sua terra. Aplicação: como você trata o povo de Deus? Isso importa para Deus.",
    "📖 <strong>RESUMO:</strong> Deus congregará todas as nações no vale de Josafá e ali as julgará por maltratarem Israel.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Diante do trono do Filho do Homem serão reunidas todas as nações' (Mateus 25:32).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 3</strong></span>",
    "<strong>TEXTO:</strong> E lançaram sortes sobre o meu povo, e deram um menino por uma meretriz, e venderam uma menina por vinho, para beberem.",
    "<strong>COMENTÁRIO:</strong> 🎲 'Lançaram sortes sobre o meu povo' – tratando os israelitas como espólio de guerra. 'Deram menino por meretriz... menina por vinho' – tratamento desumano e degradante, trocando pessoas por prazeres imorais. O princípio é que Deus vê e condena a desumanização e exploração de Seu povo. Aplicação: Deus defende os vulneráveis; o tratamento dado aos fracos importa para Ele.",
    "📖 <strong>RESUMO:</strong> As nações lançaram sortes sobre Israel, trocando crianças por prostitutas e vinho.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Em verdade vos digo que, quando o fizestes a um destes meus pequeninos irmãos, a mim o fizestes' (Mateus 25:40).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 4</strong></span>",
    "<strong>TEXTO:</strong> E que tendes vós comigo, Tiro e Sidom, e todas as costas da Filístia? Quereis vós dar-me recompensa? Se me recompensardes, bem depressa e prontamente farei cair a vossa recompensa sobre a vossa cabeça.",
    "<strong>COMENTÁRIO:</strong> 🏛️ 'Tiro e Sidom... costas da Filístia' – nações vizinhas específicas (fenícias e filisteias) que se opuseram a Israel. 'Que tendes vós comigo?' – pergunta retórica: por que estão contra o meu povo? 'Quereis dar-me recompensa?' – se quiserem me pagar pelo que fizeram, receberão de volta. O princípio é que Deus retribuirá às nações que se opõem a Ele através de Seu povo. Aplicação: o que você faz contra o povo de Deus, Deus considera como feito contra Ele mesmo.",
    "📖 <strong>RESUMO:</strong> Tiro, Sidom e Filístia: se quiserem me recompensar, farei cair a recompensa sobre vossas cabeças.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Aquele que vos tocar toca na menina do seu olho' (Zacarias 2:8).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 5</strong></span>",
    "<strong>TEXTO:</strong> Visto que levastes a minha prata e o meu ouro, e as minhas coisas preciosas e agradáveis, e as trouxestes para os vossos templos;",
    "<strong>COMENTÁRIO:</strong> 💰 'Minha prata e meu ouro' – os tesouros do templo (que pertenciam a Deus). 'Coisas preciosas e agradáveis' – objetos sagrados. 'Trouxestes para os vossos templos' – saquearam o templo de Deus para adornar seus próprios templos pagãos. O princípio é que profanar as coisas sagradas de Deus traz juízo severo. Aplicação: honre as coisas de Deus; não as trate como comuns ou profanas.",
    "📖 <strong>RESUMO:</strong> As nações levaram a prata, o ouro e as coisas preciosas de Deus para seus templos pagãos.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Não sabeis que sois o templo de Deus?' (1 Coríntios 3:16).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 6</strong></span>",
    "<strong>TEXTO:</strong> E vendestes os filhos de Judá e os filhos de Jerusalém aos filhos dos gregos, para os afastar da sua terra.",
    "<strong>COMENTÁRIO:</strong> 🇬🇷 'Vendestes os filhos de Judá... aos gregos (Javanim)' – menção específica aos gregos como compradores de escravos judeus. 'Para os afastar da sua terra' – deportação e dispersão forçada. O princípio é que o tráfico humano e a deportação são pecados que Deus julga. Aplicação: Deus defende a justiça e condena a exploração de pessoas.",
    "📖 <strong>RESUMO:</strong> Venderam os filhos de Judá aos gregos, afastando-os de sua terra.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Lembrai-vos dos presos, como se estivésseis presos com eles' (Hebreus 13:3).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 7</strong></span>",
    "<strong>TEXTO:</strong> Eis que eu os suscitarei do lugar para onde os vendestes, e farei cair a vossa recompensa sobre a vossa cabeça.",
    "<strong>COMENTÁRIO:</strong> 🔄 'Eu os suscitarei do lugar para onde os vendestes' – Deus trará de volta os exilados. 'Farei cair a vossa recompensa sobre a vossa cabeça' – retribuição divina: o que fizeram a outros recairá sobre eles. O princípio é que Deus é o libertador de Seu povo e o vingador da injustiça. Aplicação: confie que Deus vê a injustiça e trará justiça no tempo certo.",
    "📖 <strong>RESUMO:</strong> Deus suscitará Seu povo do lugar onde foi vendido; a recompensa cairá sobre a cabeça das nações.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Não vos vingueis a vós mesmos... minha é a vingança, diz o Senhor' (Romanos 12:19).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 8</strong></span>",
    "<strong>TEXTO:</strong> E venderei vossos filhos e vossas filhas nas mãos dos filhos de Judá, e eles os venderão aos sabeus, a uma nação remota; porque o Senhor o disse.",
    "<strong>COMENTÁRIO:</strong> 🔄 'Venderei vossos filhos... nas mãos dos filhos de Judá' – retribuição na mesma moeda. 'Sabeus' – povo da Arábia do Sul (Sabá). 'Porque o Senhor o disse' – confirmação da certeza do juízo. O princípio é que a lei da retribuição (olho por olho) é um princípio divino de justiça. Aplicação: Deus é justo; Ele retribui a cada um segundo suas obras.",
    "📖 <strong>RESUMO:</strong> Deus venderá os filhos das nações aos judeus, que os venderão aos sabeus.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Com a medida com que medirdes, também vós sereis medidos' (Mateus 7:2).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 9</strong></span>",
    "<strong>TEXTO:</strong> Proclamai isto entre as nações: Preparai a guerra, despertai os valentes; cheguem-se todos os homens de guerra, subam eles.",
    "<strong>COMENTÁRIO:</strong> ⚔️ 'Proclamai isto entre as nações' – convocação irônica: as nações devem se preparar para a guerra contra Deus. 'Preparai a guerra... despertai os valentes' – ironia: Deus desafia as nações a se armarem, sabendo que serão derrotadas. O princípio é que a guerra contra Deus é insensata e fútil. Aplicação: não lute contra Deus; você não vencerá.",
    "📖 <strong>RESUMO:</strong> Proclamai às nações: preparai a guerra, vinde todos os valentes.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Por que se amotinam as nações... contra o Senhor?' (Salmo 2:1-2).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 10</strong></span>",
    "<strong>TEXTO:</strong> Forjai espadas das vossas enxadas, e lanças das vossas foices; diga o fraco: Eu sou forte.",
    "<strong>COMENTÁRIO:</strong> 🛠️ 'Forjai espadas das enxadas... lanças das foices' – inversão da imagem messiânica de paz (Isaías 2:4: 'forjarão espadas em arados'). Aqui é guerra, não paz. 'Diga o fraco: Eu sou forte' – convocação total: até os fracos devem se preparar. O princípio é que no juízo final, não há lugar para fraqueza; todos serão testados. Aplicação: a paz messiânica ainda virá; mas primeiro, o juízo.",
    "📖 <strong>RESUMO:</strong> Forjai espadas de enxadas e lanças de foices; até o fraco diga: sou forte.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Quando disserem: Paz e segurança, então lhes sobrevirá repentina destruição' (1 Tessalonicenses 5:3).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 11</strong></span>",
    "<strong>TEXTO:</strong> Apressai-vos, e vinde, todos os povos em redor, e ajuntai-vos; ali, ó Senhor, faze descer os teus valentes.",
    "<strong>COMENTÁRIO:</strong> 🏃 'Apressai-vos, e vinde, todos os povos... ajuntai-vos' – convocação irônica para as nações se reunirem para o julgamento. 'Ali, ó Senhor, faze descer os teus valentes' – os exércitos celestiais de Deus. O princípio é que as nações pensam que estão vindo para guerrear, mas na verdade estão vindo para o julgamento. Aplicação: Deus tem 'valentes' celestiais que executarão Seu juízo.",
    "📖 <strong>RESUMO:</strong> Apressai-vos, povos, ajuntai-vos; ali, Senhor, faze descer teus valentes.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'E vi os exércitos que estão no céu' (Apocalipse 19:14).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 12</strong></span>",
    "<strong>TEXTO:</strong> Despertem as nações, e subam ao vale de Josafá; porque ali me assentarei para julgar todas as nações em redor.",
    "<strong>COMENTÁRIO:</strong> ⚖️ 'Despertem as nações... subam ao vale de Josafá' – convocação final. 'Ali me assentarei para julgar' – Deus como Juiz universal no trono. 'Todas as nações em redor' – juízo universal. O princípio é que o vale de Josafá ('Yahweh julga') se torna a cena do julgamento final das nações. Aplicação: prepare-se para encontrar o Juiz de toda a terra.",
    "📖 <strong>RESUMO:</strong> As nações despertarão e subirão ao vale de Josafá, onde Deus se assentará para julgá-las.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Porque todos havemos de comparecer ante o tribunal de Cristo' (Romanos 14:10).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 13</strong></span>",
    "<strong>TEXTO:</strong> Lançai a foice, porque já está madura a sega; vinde, descei, porque o lagar está cheio, e os vasos dos lagares transbordam, porque a sua maldade é grande.",
    "<strong>COMENTÁRIO:</strong> 🌾 'Lançai a foice... madura a sega' – imagem da colheita do juízo (cf. Apocalipse 14:15). 'Lagarinho cheio... transbordam' – imagem da prensa do vinho (juízo). 'Sua maldade é grande' – a razão do juízo é a plenitude do pecado. O princípio é que o juízo vem quando o pecado atinge seu limite (cf. Gênesis 15:16). Aplicação: a paciência de Deus tem limites; o pecado será julgado quando sua medida encher.",
    "📖 <strong>RESUMO:</strong> Lançai a foice, a sega está madura; descei, o lagar transborda porque a maldade é grande.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Lançou a sua foice à terra, e a terra foi ceifada' (Apocalipse 14:19).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 14</strong></span>",
    "<strong>TEXTO:</strong> Multidões, multidões no vale da decisão; porque o dia do Senhor está perto, no vale da decisão.",
    "<strong>COMENTÁRIO:</strong> 📊 'Multidões, multidões (hamonim, hamonim)' – repetição para ênfase na imensidão das nações reunidas. 'Vale da decisão (emek hecharutz)' – 'vale da serra' ou 'vale do julgamento severo'. 'Dia do Senhor está perto' – repetição da iminência do juízo. O princípio é que o Dia do Senhor é o dia da decisão final para as nações. Aplicação: hoje é o dia da decisão para você: de que lado você estará no vale do julgamento?",
    "📖 <strong>RESUMO:</strong> Multidões no vale da decisão; o dia do Senhor está perto naquele vale.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Agora é o juízo deste mundo' (João 12:31).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 15</strong></span>",
    "<strong>TEXTO:</strong> O sol e a lua se escurecerão, e as estrelas retirarão o seu resplendor.",
    "<strong>COMENTÁRIO:</strong> 🌑 'Sol e lua se escurecerão... estrelas retirarão resplendor' – repetição dos sinais cósmicos do capítulo 2. O princípio é que o Dia do Senhor é cósmico, não apenas local. Aplicação: a criação inteira será afetada pelo juízo final.",
    "📖 <strong>RESUMO:</strong> Sol e lua escurecerão; as estrelas perderão seu resplendor.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'As estrelas cairão do céu' (Mateus 24:29).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 16</strong></span>",
    "<strong>TEXTO:</strong> E o Senhor bramará de Sião, e de Jerusalém fará ouvir a sua voz; os céus e a terra tremerão; mas o Senhor será o refúgio do seu povo, e a fortaleza dos filhos de Israel.",
    "<strong>COMENTÁRIO:</strong> 🦁 'Bramará de Sião' – Deus ruge como leão de Sião, Sua morada. 'Céus e terra tremerão' – comoção universal. 'Senhor será o refúgio do seu povo... fortaleza dos filhos de Israel' – contraste: para os ímpios, terror; para o povo de Deus, proteção. O princípio é que o mesmo Dia do Senhor é terror para os ímpios e refúgio para os justos. Aplicação: para aqueles que estão em Cristo, o Dia do Senhor não é medo, mas esperança.",
    "📖 <strong>RESUMO:</strong> O Senhor bramará de Sião; céus e terra tremerão; mas Ele será refúgio para Seu povo.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Nós, porém, esperamos novos céus e nova terra' (2 Pedro 3:13).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 17</strong></span>",
    "<strong>TEXTO:</strong> E vós sabereis que eu sou o Senhor vosso Deus, que habito em Sião, meu santo monte; e Jerusalém será santa, e estranhos não mais passarão por ela.",
    "<strong>COMENTÁRIO:</strong> 🏔️ 'Sabereis que eu sou o Senhor vosso Deus' – conhecimento experimental que leva à adoração. 'Habito em Sião... santo monte' – Deus estabelece Sua presença permanente. 'Jerusalém será santa' – separada para Deus. 'Estranhos não mais passarão por ela' – pureza e segurança perpétuas. O princípio é que o reinado de Deus em Sião trará santidade e segurança eternas. Aplicação: ansiemos pela Jerusalém celestial, onde Deus habitará com Seu povo para sempre.",
    "📖 <strong>RESUMO:</strong> Sabereis que eu sou o Senhor que habita em Sião; Jerusalém será santa; estranhos não passarão.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'E vi a santa cidade, a nova Jerusalém' (Apocalipse 21:2).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 18</strong></span>",
    "<strong>TEXTO:</strong> E há de ser que, naquele dia, os montes destilarão mosto, e os outeiros manarão leite, e todos os rios de Judá estarão cheios de águas; e sairá uma fonte da casa do Senhor, e regará o vale de Sitim.",
    "<strong>COMENTÁRIO:</strong> 🍯 'Montes destilarão mosto... outeiros manarão leite' – abundância agrícola sem precedentes. 'Rios de Judá cheios de águas' – restauração hídrica. 'Sairá uma fonte da casa do Senhor' – água viva do templo (cf. Ezequiel 47; Zacarias 14:8). 'Regará o vale de Sitim' – vale de acácias, possivelmente no lado oriental do Jordão. O princípio é que a restauração futura incluirá bênçãos materiais e uma fonte de água viva do templo. Aplicação: a água viva que jorra do trono de Deus está disponível para todos que têm sede (João 7:37-39).",
    "📖 <strong>RESUMO:</strong> Naquele dia, os montes destilarão mosto, os rios estarão cheios, e uma fonte sairá da casa do Senhor.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Aquele que crê em mim... rios de água viva correrão' (João 7:38).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 19</strong></span>",
    "<strong>TEXTO:</strong> O Egito se tornará uma desolação, e Edom se fará um deserto assolado, por causa da violência que fizeram aos filhos de Judá, em cuja terra derramaram sangue inocente.",
    "<strong>COMENTÁRIO:</strong> 🏜️ 'Egito... Edom' – inimigos tradicionais de Israel, exemplos de nações que serão julgadas. 'Desolação... deserto assolado' – juízo de esterilidade. 'Por causa da violência... sangue inocente' – a razão específica: violência contra Judá. O princípio é que Deus julga nações com base em como tratam Seu povo e na violência que praticam. Aplicação: Deus é o vingador do sangue inocente; a injustiça não ficará impune.",
    "📖 <strong>RESUMO:</strong> Egito e Edom se tornarão desolação por causa da violência e sangue inocente derramado sobre Judá.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Ai daquela cidade onde o sangue dos justos foi derramado' (Mateus 23:35).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 20</strong></span>",
    "<strong>TEXTO:</strong> Mas Judá será habitada para sempre, e Jerusalém, de geração em geração.",
    "<strong>COMENTÁRIO:</strong> 🏘️ 'Judá será habitada para sempre' – permanência eterna de Judá. 'Jerusalém, de geração em geração' – continuidade perpétua da cidade santa. O princípio é que, ao contrário dos inimigos que são destruídos, o povo de Deus tem uma herança eterna. Aplicação: nossa esperança não é temporal, mas eterna; temos uma cidade que permanece (Hebreus 13:14).",
    "📖 <strong>RESUMO:</strong> Judá será habitada para sempre; Jerusalém, de geração em geração.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'A Jerusalém que é de cima é livre' (Gálatas 4:26).",
    
    "<span style='font-size: 15px;'><strong>VERSÍCULO: 21</strong></span>",
    "<strong>TEXTO:</strong> E purificarei o sangue que eu não tinha purificado; porque o Senhor habitará em Sião.",
    "<strong>COMENTÁRIO:</strong> 💧 'Purificarei o sangue que eu não tinha purificado' – interpretação difícil: pode ser 'declararei inocente' ou 'vindicarei o sangue derramado'. 'Porque o Senhor habitará em Sião' – a razão final de toda a restauração: a presença permanente de Deus no meio de Seu povo. O princípio é que o propósito final de Deus é habitar com Seu povo. Aplicação: o clímax da história não é a prosperidade ou a vitória militar, mas a presença de Deus. Reflexão: você anseia pela habitação de Deus?",
    "📖 <strong>RESUMO:</strong> Deus purificará o sangue (ou vindicará) e habitará em Sião.",
    "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Eis aqui o tabernáculo de Deus com os homens, pois com eles habitará' (Apocalipse 21:3).",
    
    
    "<p style='font-size: 0.8rem; text-align: center;'><i><strong>Reflexão Final do Capítulo 3</strong></i></p>",
    "<p style='font-size: 0.6rem;'>Joel 3 (4 na numeração hebraica) apresenta o julgamento final das nações no 'vale de Josafá' ('Yahweh julga'). As nações são acusadas de espalhar Israel, dividir a terra, vender o povo como escravos, e saquear os tesouros do templo. Deus promete retribuição: 'farei cair a vossa recompensa sobre a vossa cabeça'. O capítulo usa imagens poderosas: a sega madura e o lagar transbordante para o juízo. Mas para o povo de Deus, o Dia do Senhor é refúgio e fortaleza. O capítulo termina com visões de restauração: montes destilando mosto, uma fonte saindo do templo, Judá habitada para sempre, e Deus habitando em Sião. O capítulo ensina que: 1) Deus julgará as nações com base em como trataram Seu povo; 2) O Dia do Senhor é terror para os ímpios, mas refúgio para os justos; 3) A retribuição divina é certa e proporcional; 4) O propósito final de Deus é habitar com Seu povo para sempre; 5) A restauração incluirá bênçãos materiais e espirituais, culminando na presença de Deus.</p>",

  "<p style='font-size: 1rem; text-align: center;'><i><strong>RESUMO FINAL DE JOEL</strong></i></p>",
  "<p style='font-size: 0.6rem;'>Joel profetiza sobre uma praga de gafanhotos como juízo de Deus, mas também como símbolo do dia do Senhor. Ele chama o povo ao arrependimento — com jejum, choro e luto — e promete a restauração.</p>",
  "<p style='font-size: 0.6rem;'>O ponto alto é a promessa do derramamento do Espírito sobre toda carne (2:28-32), cumprida em Atos 2 no Pentecostes.</p>",
  "<p style='font-size: 0.6rem;'>Joel nos lembra que o juízo pode ser evitado pelo arrependimento e que o Espírito Santo é a grande bênção da Nova Aliança.</p>",
  "<p style='font-size: 0.7rem;'><strong>LIÇÕES PRINCIPAIS:</strong></p>",
  "<ul style='font-size: 0.6rem;'>",
  "  <li><strong>O arrependimento precede a restauração:</strong> Rasgar o coração, não as vestes.</li>",
  "  <li><strong>O derramamento do Espírito é prometido:</strong> Cumprido no Pentecostes.</li>",
  "  <li><strong>O Dia do Senhor é grande e terrível:</strong> Mas há salvação para quem invocar o nome do Senhor.</li>",
  "  <li><strong>Deus restaura o que foi perdido:</strong> Os anos consumidos pelos gafanhotos serão compensados.</li>",
  "  <li><strong>Deus habita no meio do Seu povo:</strong> A presença divina é a maior bênção.</li>",
  "</ul>",
  "<p style='font-size: 0.6rem;'>Que possamos invocar o nome do Senhor, arrepender-nos e receber o derramamento do Espírito Santo.</p>"
  ]
}
};