window.LIVRO_DATA = {
  nome: "Rute Comentado",
  dados: {
    1: [
      "<p style='font-size: 0.8rem; text-align: center;'><i><strong>Fé e lealdade em meio à provação: Noemi e Rute retornam a Belém</strong></i></p>",
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 1</strong></span>",
      "<strong>TEXTO:</strong> E sucedeu, nos dias em que os juízes julgavam, que houve uma fome na terra; e um homem de Belém de Judá saiu a peregrinar na terra de Moabe, ele, e sua mulher, e seus dois filhos.",
      "<strong>COMENTÁRIO:</strong> 🔍 O período dos juízes foi marcado por anarquia espiritual: 'Cada um fazia o que parecia reto aos seus olhos' (Juízes 21:25). A fome em Belém ('casa do pão') é ironicamente contrastante. Moabe, descendente da relação incestuosa de Ló (Gênesis 19:30-38), era frequentemente hostil a Israel. A migração reflete descrença na aliança, pois Deus prometera abençoar a terra pela obediência (Deuteronômio 28:1-6).",
      "📖 <strong>RESUMO:</strong> Crise leva uma família de Belém a buscar sustento em Moabe, terra estrangeira.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Jesus, o 'pão da vida' (João 6:35), também veio para os carentes e marginalizados, invertendo a lógica da fome espiritual. Referência: Mateus 5:6.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 2</strong></span>",
      "<strong>TEXTO:</strong> O nome deste homem era Elimeleque, e o de sua mulher, Noemi, e os de seus dois filhos, Malom e Quiliom, efrateus, de Belém de Judá. E chegaram à terra de Moabe, e ficaram ali.",
      "<strong>COMENTÁRIO:</strong> 🔍 'Elimeleque' significa 'Meu Deus é Rei' - um nome teocrático que contrasta com sua decisão de deixar a terra prometida. 'Noemi' significa 'minha suavidade' ou 'minha doçura'. 'Malom' (doença) e 'Quiliom' (definhamento) - nomes proféticos que anunciam tragédia. 'Efrateus' refere-se a Efrata, antigo nome de Belém, região fértil. A permanência em Moabe, além do esperado, indica acomodação cultural.",
      "📖 <strong>RESUMO:</strong> Apresentação da família que migra e fixa residência em Moabe.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> O crente é peregrino neste mundo (1 Pedro 2:11); fixar-se onde Deus não ordena traz perigos. Referência: Tiago 4:4.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 3</strong></span>",
      "<strong>TEXTO:</strong> E faleceu Elimeleque, marido de Noemi; e ficou ela com os seus dois filhos.",
      "<strong>COMENTÁRIO:</strong> 💔 A morte de Elimeleque é o primeiro golpe. A ausência de registro de seu sepultamento sugere morte prematura ou desprezo por sepultar em terra pagã. Noemi torna-se viúva em terra estrangeira - situação de extrema vulnerabilidade no mundo antigo, sem direito à herança ou proteção social. O lamento implícito é que a busca por 'pão' resultou em morte.",
      "📖 <strong>RESUMO:</strong> Elimeleque morre, deixando Noemi viúva com dois filhos em Moabe.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> As aflições do mundo muitas vezes resultam de decisões fora da vontade de Deus, mas Ele pode redimi-las (Romanos 8:28).",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 4</strong></span>",
      "<strong>TEXTO:</strong> Os quais tomaram para si mulheres moabitas; o nome de uma era Orfa, e o da outra, Rute; e ficaram ali quase dez anos.",
      "<strong>COMENTÁRIO:</strong> 🔍 Casamentos com moabitas eram proibidos por Deuteronômio 23:3-6 devido à recusa de Moabe em ajudar Israel no êxodo e por sua prática de sedução com Balaão. No entanto, Rute se torna uma exceção pela fé (Mateus 1:5 inclui seu nome na genealogia de Jesus). 'Orfa' significa 'nuca' ou 'garça'; 'Rute' possivelmente 'amiga' ou 'beleza'. Dez anos de permanência indicam que a situação se tornou permanente.",
      "📖 <strong>RESUMO:</strong> Os filhos casam-se com moabitas, e a família permanece uma década em Moabe.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> A graça de Deus ultrapassa barreiras étnicas: Rute, gentia, torna-se ancestral do Messias. Referência: Gálatas 3:28.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 5</strong></span>",
      "<strong>TEXTO:</strong> E morreram também ambos, Malom e Quiliom, ficando assim a mulher desamparada de seus dois filhos e de seu marido.",
      "<strong>COMENTÁRIO:</strong> 💔 Tragédia total: Noemi perde marido e ambos os filhos sem descendência. No mundo antigo, viúva sem filhos estava à mercê da caridade pública, sem segurança e sem perpetuidade do nome familiar. O hebraico 'nish'ah' ('desamparada') sugere literalmente 'vazia' - um tema central do capítulo. A ironia: buscando encher o estômago, Noemi esvaziou a alma.",
      "📖 <strong>RESUMO:</strong> Morte dos dois filhos deixa Noemi completamente só e sem esperança natural.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Bem-aventurados os que choram, porque serão consolados' (Mateus 5:4) - Deus se aproxima dos desamparados. Referência: 2 Coríntios 1:3-4.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 6</strong></span>",
      "<strong>TEXTO:</strong> Então se levantou ela com as suas noras, para voltar da terra de Moabe, porquanto na terra de Moabe ouvira que o Senhor visitara o seu povo, dando-lhes pão.",
      "<strong>COMENTÁRIO:</strong> 🌾 A palavra 'visitara' (paqad) em hebraico denota intervenção divina atenta - pode ser para bênção ou juízo. Aqui é misericórdia: Deus 'lembrou' de Seu povo. A notícia da restauração agrícola em Judá contrasta com a fome inicial. O 'levantar-se' de Noemi simboliza movimento de fé, mesmo esgotada humanamente. A providência divina age mesmo quando não percebemos.",
      "📖 <strong>RESUMO:</strong> Noemi decide retornar a Judá ao ouvir que Deus acabou com a fome.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Deus visita Seu povo em Cristo (Lucas 1:68), trazendo o verdadeiro 'pão do céu'. Referência: João 6:33.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 7</strong></span>",
      "<strong>TEXTO:</strong> Pelo que saiu do lugar onde estava, e com ela as suas duas noras; e puseram-se a caminho para voltarem para a terra de Judá.",
      "<strong>COMENTÁRIO:</strong> 🚶‍♀️ A saída de Moabe é um movimento geográfico e espiritual. O termo 'colocaram-se a caminho' (telaknah baderekh) sugere decisão deliberada. A companhia das noras indica vínculo afetivo real, não apenas interesse. Judá é 'terra de promessa' novamente.",
      "📖 <strong>RESUMO:</strong> Noemi inicia a jornada de retorno com suas duas noras.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> A jornada da fé é um desligar-se do mundo (Egito/Moabe) para buscar a pátria celestial (Hebreus 11:13-16).",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 8</strong></span>",
      "<strong>TEXTO:</strong> E disse Noemi às suas duas noras: Ide, voltai cada uma à casa de sua mãe; e o Senhor use convosco de benevolência, como vós usastes com os falecidos e comigo.",
      "<strong>COMENTÁRIO:</strong> ❤️ O discurso de despedida revela a integridade de Noemi: ela não explora a lealdade das noras. 'Benevolência' (hesed) é o termo-chave do livro - amor leal da aliança, graça que vai além da obrigação. Noemi abençoa as noras com o nome do Senhor (Yahweh), não deuses moabitas, indicando que sua fé permaneceu viva.",
      "📖 <strong>RESUMO:</strong> Noemi, altruisticamente, incentiva as noras a retornarem às suas famílias em Moabe.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> O amor hesed é o modelo do amor ágape (1 Coríntios 13) - sacrificial e leal. Referência: Efésios 5:1-2.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 9</strong></span>",
      "<strong>TEXTO:</strong> O Senhor vos dê que acheis descanso cada uma em casa de seu marido. E beijou-as; porém levantaram a sua voz e choraram.",
      "<strong>COMENTÁRIO:</strong> 😢 'Descanso' (menuḥah) refere-se à segurança e estabilidade no casamento, incluindo provisão e proteção. O beijo como selo de afeto genuíno. O choro coletivo (literalmente 'levantaram a voz') expressa dor da separação iminente, mas também a força do vínculo formado ao longo de dez anos.",
      "📖 <strong>RESUMO:</strong> Noemi abençoa as noras com desejo de novo casamento; todas choram emocionadas.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> O descanso verdadeiro é encontrado em Cristo (Mateus 11:28-30) - não apenas matrimonial, mas espiritual.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 10</strong></span>",
      "<strong>TEXTO:</strong> E disseram-lhe: Certamente voltaremos contigo para o teu povo.",
      "<strong>COMENTÁRIO:</strong> 🤝 A resposta imediata mostra lealdade inesperada. Orfa e Rute oferecem o que nenhuma nora era obrigada a dar: deixar sua terra, deuses e família para seguir uma sogra empobrecida. A frase 'para o teu povo' reconhece que Israel é agora identificado como alvo de sua lealdade, mesmo sem compreensão plena.",
      "📖 <strong>RESUMO:</strong> As noras insistem em acompanhar Noemi para Judá.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Seguir a Cristo exige deixar laços terrenos e 'povo, pai e mãe' (Mateus 19:29) pela promessa de algo maior.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 11</strong></span>",
      "<strong>TEXTO:</strong> Porém Noemi disse: Voltai, minhas filhas; porque ireis comigo? Tenho eu ainda filhos no meu ventre, que vos possam ser maridos?",
      "<strong>COMENTÁRIO:</strong> Noemi argumenta com realismo doloroso. A referência a 'ter filhos no ventre' alude ao costume do levirato (Deuteronômio 25:5-10), onde o irmão do falecido deveria casar com a viúva. Noemi não tem outros filhos. Sua pergunta é retórica e cruelmente honesta: não há esperança de descendência por ela. O pragmatismo se choca com o amor das noras.",
      "📖 <strong>RESUMO:</strong> Noemi argumenta racionalmente: não pode oferecer novos maridos às noras.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Paulo também preferia o realismo da fé: 'seja honesto' (Efésios 4:25) - mas sem desencorajar o amor. Referência: 1 Coríntios 7:8-9.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 12</strong></span>",
      "<strong>TEXTO:</strong> Voltai, minhas filhas, ide-vos; porque já sou velha, para tomar marido. Ainda quando eu dissesse: Tenho esperança, e até esta noite tivesse marido, e ainda viesse a ter filhos,",
      "<strong>COMENTÁRIO:</strong> A intensificação do argumento: mesmo que Noemi casasse esta noite (impossível pela idade), seus filhos levariam anos para atingir maturidade para casamento. As noras seriam idosas quando os 'filhos' estivessem aptos. A lógica humana diz que elas devem partir. Noemi está protegendo-as da sua própria desgraça.",
      "📖 <strong>RESUMO:</strong> Noemi reforça: mesmo que casasse hoje e tivesse filhos, eles não seriam maridos adequados para as noras.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> O amor verdadeiro às vezes se expressa em 'empurrar' o amado para o melhor caminho, mesmo que custe solidão. Referência: Filipenses 2:4.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 13</strong></span>",
      "<strong>TEXTO:</strong> esperaríeis por eles até que viessem a ser grandes? Deter-vos-íeis por eles, sem tomar marido? Não, filhas minhas, porque mais amargo me é a vós, pois a mão do Senhor se descarregou contra mim.",
      "<strong>COMENTÁRIO:</strong> ☠️ 'Mais amargo me é a vós' (mar-lan meod) - Noemi sente que sua presença trará sofrimento às noras. Ela interpreta sua tragédia como 'mão do Senhor contra mim' - teologia da retribuição imediata (Deus pune o pecado com calamidade). Embora não totalmente correta (Jó mostra outra perspectiva), sua honestidade emocional é palpável. O nome 'Noemi' (doçura) agora contrasta com amargura.",
      "📖 <strong>RESUMO:</strong> Noemi lamenta a amargura que Deus lhe trouxe e não quer que as noras compartilhem sua sorte.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> A mão de Deus pode disciplinar (Hebreus 12:5-11), mas sempre em amor para restauração, não destruição final. Referência: Romanos 8:1.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 14</strong></span>",
      "<strong>TEXTO:</strong> Então levantaram a sua voz outra vez, e choraram; e Orfa beijou a sua sogra, porém Rute se apegou a ela.",
      "<strong>COMENTÁRIO:</strong> 💔 O contraste final: 'Orfa beijou' (beijo de despedida) vs. 'Rute se apegou' (dabaq - mesma raiz de Gênesis 2:24, 'apegar-se-á o homem à sua mulher'). Orfa faz o que é sensato e culturalmente esperado. Rute faz o que é extraordinário - adesão incondicional. O beijo de Orfa é respeitoso e afetuoso, mas não sobrepuja o medo do futuro. Rute escolhe a cruz.",
      "📖 <strong>RESUMO:</strong> Orfa se despede e retorna; Rute, ao contrário, se apega firmemente a Noemi.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Muitos seguem a Cristo até certo ponto, mas só os que 'se apegam' verdadeiramente recebem a vida eterna (João 6:66-68). Referência: Lucas 9:62.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 15</strong></span>",
      "<strong>TEXTO:</strong> E disse Noemi: Eis que tua cunhada voltou para o seu povo e para os seus deuses; volta também tu após a tua cunhada.",
      "<strong>COMENTÁRIO:</strong> Noemi libera Rute emocionalmente: Orfa voltou 'ao seu povo e seus deuses' (Quemos, o deus moabita). A implicação é que seguir Noemi significa adotar Yahweh como Deus. O teste de lealdade é também teológico. 'Volta após tua cunhada' - um último empurrão para o caminho fácil. Rute está sendo provada no fogo.",
      "📖 <strong>RESUMO:</strong> Noemi aponta que Orfa escolheu seus deuses e povo; sugere que Rute faça o mesmo.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Não se pode servir a dois senhores (Mateus 6:24). Toda decisão por Cristo exige rejeição dos 'deuses' deste mundo.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 16</strong></span>",
      "<strong>TEXTO:</strong> Disse, porém, Rute: Não me instes para que te deixe, e me obrigue a não seguir-te; porque aonde quer que tu fores, irei eu, e onde quer que pousares, ali pousarei eu; o teu povo é o meu povo, o teu Deus é o meu Deus.",
      "<strong>COMENTÁRIO:</strong> 🌟 A declaração mais linda do Antigo Testamento sobre lealdade da aliança. Rute usa verbos de movimento: 'seguir', 'ir', 'pousar'. Há uma progressão teológica: primeiro o local, depois o povo, finalmente o Deus (Yahweh). Ela não apenas decide ficar com Noemi, mas se converter ao Deus de Israel. Este versículo ecoa a aliança matrimonial (Gênesis 2:24) aplicada à comunidade de fé.",
      "📖 <strong>RESUMO:</strong> Rute faz uma profissão de fé e lealdade incondicional: onde Noemi for, ela irá; seu povo e Deus serão os seus.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Seguir a Cristo exige a mesma rendição total (Lucas 14:26-27). A igreja é nossa família, Cristo nosso Deus. Referência: João 14:6.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 17</strong></span>",
      "<strong>TEXTO:</strong> Onde quer que morreres, morrerei eu, e ali serei sepultada; assim me faça o Senhor, e outro tanto, se outra coisa que não seja a morte me separar de ti.",
      "<strong>COMENTÁRIO:</strong> ⚰️ A aliança é selada com juramento solene: 'Assim me faça o Senhor' é uma auto-maldição condicional (se eu quebrar, que Deus me puna). Rute vai além da vida - até a morte e sepultura serão compartilhadas. Ela abandona qualquer esperança de retorno. A frase ecoa o pacto davídico (1 Samuel 20:13) e o amor de Cristo (Romanos 8:38-39: nada pode separar).",
      "📖 <strong>RESUMO:</strong> Rute jura por Deus que somente a morte a separará de Noemi, incluindo o local de sepultamento.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> O amor de Deus em Cristo é irrevogável e eterno, assim como este juramento (Romanos 8:38-39).",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 18</strong></span>",
      "<strong>TEXTO:</strong> Vendo, pois, Noemi que ela estava firmemente resolvida a ir com ela, deixou de lhe falar.",
      "<strong>COMENTÁRIO:</strong> Noemi cessa de argumentar. O texto hebraico diz 'ela se fortaleceu' (hit'ametzah) - uma força interior. A rendição de Noemi não é derrota, mas reconhecimento de que a vontade de Rute é guiada por algo maior. A fé de Rute agora conduz ambas.",
      "📖 <strong>RESUMO:</strong> Noemi reconhece a determinação inabalável de Rute e desiste de persuadi-la a voltar.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> A fé obstinada é recompensada (Mateus 15:28 - a mulher cananeia). Deus honra a teimosia da graça.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 19</strong></span>",
      "<strong>TEXTO:</strong> Assim, pois, foram ambas, até que chegaram a Belém. E sucedeu que, entrando elas em Belém, toda a cidade se comoveu por causa delas; e as mulheres perguntavam: Não é esta Noemi?",
      "<strong>COMENTÁRIO:</strong> 🏙️ 'A cidade se comoveu' (tehom kol-ha'ir) - alvoroço total. A chegada de duas mulheres sem proteção masculina gera sensação. A pergunta 'Não é esta Noemi?' sugere que ela parecia irreconhecível - pelo sofrimento, pelo tempo, pela mudança de status. Belém agora é ironicamente a 'casa do pão' que antes não tinha pão.",
      "📖 <strong>RESUMO:</strong> Rute e Noemi chegam a Belém no momento da colheita; toda a cidade se alvoroça com a volta de Noemi.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Quando o povo de Deus retorna do exílio (figurativamente), há alvoroço no céu (Lucas 15:7 - alegria por um pecador que se arrepende).",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 20</strong></span>",
      "<strong>TEXTO:</strong> E ela lhes dizia: Não me chameis Noemi; chamai-me Mara; porque grande amargura me tem dado o Todo-Poderoso.",
      "<strong>COMENTÁRIO:</strong> 💧 'Noemi' (doçura) → 'Mara' (amargura). O nome Shaddai (Todo-Poderoso) é usado aqui, enfatizando o poder de Deus que ela sentiu como esmagador. A teologia da amargura de Noemi não nega a soberania divina, mas expressa dor genuína. Deus é tanto doce quanto amargo? Jó diria que recebemos o bem e o mal das mãos de Deus (Jó 2:10). O lamento é permitido nas Escrituras.",
      "📖 <strong>RESUMO:</strong> Noemi pede para ser chamada de Mara (amargura), pois crê que Deus a afligiu grandemente.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Jesus também clamou 'Deus meu, por que me desamparaste?' (Mateus 27:46) - a dor genuína é parte da fé. Referência: Salmo 34:18.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 21</strong></span>",
      "<strong>TEXTO:</strong> Cheia parti, porém vazia o Senhor me fez tornar; por que, pois, me chamareis Noemi, visto que o Senhor testemunhou contra mim, e o Todo-Poderoso me afligiu?",
      "<strong>COMENTÁRIO:</strong> ⚖️ 'Cheia parti': ironia - ela saiu com marido e dois filhos (plenitude), mas agora vazia (sem filhos, sem marido). 'Testemunhou contra mim' - linguagem forense: Deus agiu como testemunha de acusação. Noemi sente-se punida. Mas ela não sabe que Rute (a vazia?) trará plenitude novamente. A aflição (ra'ah) de Deus é real, mas não final.",
      "📖 <strong>RESUMO:</strong> Noemi explica que saiu cheia, mas voltou vazia, e Deus testemunhou contra ela em aflição.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Paulo aprendeu que 'quando sou fraco, então sou forte' (2 Coríntios 12:10). Deus esvazia para encher. Referência: Filipenses 2:7-9.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 22</strong></span>",
      "<strong>TEXTO:</strong> Assim Noemi voltou, e com ela Rute, a moabita, sua nora, que veio da terra de Moabe; e chegaram a Belém no princípio da colheita das cevadas.",
      "<strong>COMENTÁRIO:</strong> 🌾 O capítulo termina com um prenúncio de esperança: 'princípio da colheita das cevadas' (março/abril). O ciclo de morte e amargura começa a se inclinar para restauração. 'Rute, a moabita' - o narrador insiste em sua origem étnica, destacando que a graça de Deus inclui estrangeiros. A colheita é tempo de provisão, encontros e recomeços. O livro de Rute é uma história de redenção que começa na pobreza e termina na genealogia de Davi.",
      "📖 <strong>RESUMO:</strong> Noemi e sua nora moabita Rute chegam a Belém no início da colheita da cevada, abrindo possibilidades de provisão.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Jesus é as 'primícias' da ressurreição (1 Coríntios 15:20) - o início da colheita final. Assim como Rute, os gentios são enxertados na promessa (Romanos 11:17-24).",

      "<p style='font-size: 0.8rem; text-align: center;'><i><strong>Reflexão Final do Capítulo 1</strong></i></p><p style='font-size: 0.55rem;'>O capítulo 1 de Rute estabelece o cenário de perda e desolação que antecede a redenção. A fome em Belém ('casa do pão') e a migração para Moabe (terra inimiga) ilustram as consequências espirituais do período dos juízes. A morte de Elimeleque, Malom e Quiliom deixa Noemi, cujo nome ('doçura') se transforma em Mara ('amargura'), completamente vazia. No entanto, em meio à tragédia, o hesed (amor leal da aliança) de Rute, a nora moabita, brilha. Sua declaração de lealdade a Noemi e ao Deus de Israel ('o teu povo é o meu povo, o teu Deus é o meu Deus') é um dos mais belos compromissos de fé das Escrituras. Rute abandona sua terra, seus deuses e seu futuro por uma sogra empobrecida e um Deus desconhecido. O capítulo termina com um fio de esperança: a chegada a Belém no início da colheita da cevada. A mensagem central é que Deus não abandona os que confiam nele, mesmo quando as circunstâncias sugerem o contrário. A 'vazia' Noemi será preenchida, e a estrangeira Rute será incorporada à linhagem da redenção.</p>"
    ],
    
    2: [
      "<p style='font-size: 0.8rem; text-align: center;'><i><strong>Providência divina: Rute encontra favor no campo de Boaz</strong></i></p>",
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 1</strong></span>",
      "<strong>TEXTO:</strong> E tinha Noemi um parente de seu marido, homem poderoso e rico, da família de Elimeleque; e era o seu nome Boaz.",
      "<strong>COMENTÁRIO:</strong> 🌳 'Parente' (moda) indica laço familiar, não necessariamente próximo. 'Poderoso e rico' (gibbor hayil) - também pode ser traduzido como 'homem de valor', 'virtude' ou 'proeminente'. Boaz (literalmente 'Nele está a força') surge como possível redentor. A genealogia menciona Perez (4:18-22) e, por fim, Davi. A providência já está preparando o cenário.",
      "📖 <strong>RESUMO:</strong> Apresentação de Boaz, parente rico e influente de Elimeleque, figura central para a redenção.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Boaz é tipo de Cristo, nosso 'parente redentor' que possui riquezas para resgatar. Referência: Hebreus 2:11 - 'não se envergonha de chamá-los irmãos'.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 2</strong></span>",
      "<strong>TEXTO:</strong> E Rute, a moabita, disse a Noemi: Deixa-me ir ao campo, e apanharei espigas atrás daquele em cujos olhos eu achar graça. E ela lhe disse: Vai, minha filha.",
      "<strong>COMENTÁRIO:</strong> 🌾 A lei mosaica permitia que pobres e estrangeiros 'respigassem' (Levítico 19:9-10; 23:22; Deuteronômio 24:19-22). Rute toma iniciativa - traço de caráter notável. 'Achar graça' (matza hen) é linguagem de favor imerecido. Noemi permite, mas não dirige - o campo da providência está aberto.",
      "📖 <strong>RESUMO:</strong> Rute pede permissão para respigar em algum campo onde encontre favor; Noemi consente.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> A graça não pode ser comprada, mas encontrada - como a mulher siro-fenícia (Marcos 7:24-30). O trabalho digno é bênção. Referência: 2 Tessalonicenses 3:10.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 3</strong></span>",
      "<strong>TEXTO:</strong> Foi, pois, e chegou ao campo, e apanhava atrás dos ceifeiros; e caiu-lhe em sorte uma parte do campo de Boaz, que era da família de Elimeleque.",
      "<strong>COMENTÁRIO:</strong> 🎲 'Caiu-lhe em sorte' (vayyiqreh) - 'aconteceu', mas em hebraico sugere coincidência divinamente orquestrada. Não é acaso, mas providência. A mão de Deus guia Rute exatamente ao campo do parente. 'Atrás dos ceifeiros' era o lugar designado para pobres - humilde, mas digno.",
      "📖 <strong>RESUMO:</strong> Rute vai trabalhar e, por 'acaso', vai parar exatamente na parte do campo pertencente a Boaz.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> A providência de Deus opera no que parece coincidência: 'Todas as coisas cooperam para o bem' (Romanos 8:28).",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 4</strong></span>",
      "<strong>TEXTO:</strong> E eis que Boaz veio de Belém, e disse aos ceifeiros: O Senhor seja convosco. E eles responderam: O Senhor te abençoe.",
      "<strong>COMENTÁRIO:</strong> 🙏 Saudação teocêntrica genuína. No período dos juízes, tal piedade não era comum. Boaz cumprimenta seus trabalhadores com bênção do nome Yahweh, e eles respondem na mesma moeda. O ambiente de trabalho é marcado por temor a Deus e respeito mútuo. Boaz é um patrão justo.",
      "📖 <strong>RESUMO:</strong> Boaz chega ao campo e troca saudações piedosas com seus ceifeiros, abençoando-os em nome do Senhor.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Nossa fala deve edificar (Efésios 4:29). A saudação cristã deve carregar bênção. Referência: 3 João 2.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 5</strong></span>",
      "<strong>TEXTO:</strong> Então disse Boaz a seu moço que estava posto sobre os ceifeiros: De quem é esta moça?",
      "<strong>COMENTÁRIO:</strong> 👀 Boaz nota a moça estranha. O supervisor ('na'ar' - jovem servo) tinha autoridade sobre os ceifeiros. A pergunta 'de quem é?' é típica para identificar filiação/proteção familiar. Boaz percebe que ela não é uma das moças de sua propriedade. Curiosidade divinamente despertada.",
      "📖 <strong>RESUMO:</strong> Boaz pergunta ao supervisor sobre a identidade da moça que ele não reconhece.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Jesus também 'viu' os marginalizados que ninguém notava (Zaqueu, a mulher samaritana). Referência: Lucas 19:5.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 6</strong></span>",
      "<strong>TEXTO:</strong> E respondeu o moço que estava posto sobre os ceifeiros, e disse: Esta é a moça moabita que veio com Noemi da terra de Moabe;",
      "<strong>COMENTÁRIO:</strong> 🏷️ A identificação enfatiza 'moabita' - estrangeira, historicamente desprezada. O supervisor fornece informações precisas: ela veio com Noemi. A história de Rute já era conhecida? Provavelmente a chegada recente causara alvoroço (1:19).",
      "📖 <strong>RESUMO:</strong> O supervisor explica que ela é a moabita que veio com Noemi de volta de Moabe.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> A identidade de 'estrangeiro' é abolida em Cristo (Efésios 2:19) - somos concidadãos dos santos.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 7</strong></span>",
      "<strong>TEXTO:</strong> e disse-me: Deixa-me apanhar e ajuntar espigas entre os molhos após os ceifeiros. Assim veio, e desde pela manhã está aqui até agora; só há pouco se assentou em casa.",
      "<strong>COMENTÁRIO:</strong> 💪 Rute pediu permissão (demonstra humildade) e trabalhou incansavelmente 'desde a manhã até agora' (quase sem descanso). O supervisor nota seu esforço: 'só há pouco se assentou' - breve pausa. A ética de trabalho de Rute impressiona.",
      "📖 <strong>RESUMO:</strong> O supervisor relata que Rute pediu permissão para respigar e trabalhou desde cedo, descansando apenas brevemente.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Não se cansem de fazer o bem' (Gálatas 6:9). O trabalho diligente é testemunho. Referência: Colossenses 3:23.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 8</strong></span>",
      "<strong>TEXTO:</strong> Então Boaz disse a Rute: Ouve, filha minha, não vás a outro campo a colher, nem tampouco passes daqui; mas ajunta-te com as minhas moças.",
      "<strong>COMENTÁRIO:</strong> 🛡️ Boaz chama Rute de 'filha minha' - proteção paternal, mesmo sendo ela moabita. Ele restringe seu campo de ação ao seu território, onde pode garantir segurança. 'Ajuntar-se com minhas moças' oferece companhia feminina e proteção contra assédio (comum nos campos). Boaz age como guardião.",
      "📖 <strong>RESUMO:</strong> Boaz instrui Rute a ficar apenas em seu campo e acompanhar as moças que trabalham para ele.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Cristo nos diz: 'Permanecei em mim' (João 15:4). A proteção está na comunhão com Ele e com o Seu povo.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 9</strong></span>",
      "<strong>TEXTO:</strong> Os teus olhos estarão atentos no campo que eles ceifarem; e irás após elas; pois tenho ordenado aos moços que não te toquem. Também, quando tiveres sede, vai aos cântaros, e bebe do que os moços tirarem.",
      "<strong>COMENTÁRIO:</strong> 🚰 Boaz vai além: garante não apenas proteção ('não te toquem' - literalmente 'não te molestem' sexualmente), mas também provisão (água, recurso precioso). Ordenar aos moços que não toquem era autoridade sobre trabalhadores rudes. Rute recebe privilégio de acesso livre aos recursos normalmente restritos a empregados.",
      "📖 <strong>RESUMO:</strong> Boaz garante proteção contra assédio e oferece água dos cântaros dos trabalhadores.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Cristo é a água viva (João 4:10) e nosso protetor contra o maligno (João 17:15).",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 10</strong></span>",
      "<strong>TEXTO:</strong> Então ela se prostrou com o rosto em terra, e inclinou-se, e disse-lhe: Por que achei graça aos teus olhos, para que me conheças, sendo eu estrangeira?",
      "<strong>COMENTÁRIO:</strong> 🙇 Rute reage com humildade (prostração) e genuína surpresa. 'Por que achei graça?' - ela reconhece a gratuidade do favor. 'Conhecer' não é apenas reconhecer, mas tomar conhecimento e agir benevolamente. Sua identidade de 'estrangeira' (nokhriyyah) a tornava vulnerável à discriminação. A pergunta reflete teologia da graça.",
      "📖 <strong>RESUMO:</strong> Rute se curva agradecida e pergunta por que recebeu tal favor, sendo estrangeira.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> O crente pergunta: 'Por que eu, sendo pecador?' (Efésios 2:8-9) - a graça não tem explicação humana.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 11</strong></span>",
      "<strong>TEXTO:</strong> Respondeu Boaz, e disse-lhe: Bem se me contou tudo quanto fizeste à tua sogra, depois da morte de teu marido; e como deixaste a teu pai e a tua mãe, e a terra onde nasceste, e vieste para um povo que dantes não conheceste.",
      "<strong>COMENTÁRIO:</strong> 👂 Boaz ouviu a reputação de Rute. Ele a elogia por três atos: 1) lealdade à sogra; 2) abandonar laços familiares (ecoando Abraão em Gênesis 12:1); 3) vir a um povo desconhecido. Estes são atos de fé extraordinários. O 'bem se me contou' (hugged hugged) é ênfase hebraica.",
      "📖 <strong>RESUMO:</strong> Boaz explica que sabe de sua lealdade a Noemi e do sacrifício de deixar sua terra e família para seguir o povo de Deus.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> A fé é evidenciada por obras (Tiago 2:18). A reputação de Rute a precede como testemunho. Referência: 1 Timóteo 5:10.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 12</strong></span>",
      "<strong>TEXTO:</strong> O Senhor retribua o teu feito, e te seja concedido cumprido galardão da parte do Senhor Deus de Israel, sob cujas asas vieste te abrigar.",
      "<strong>COMENTÁRIO:</strong> 🕊️ 'Asas' (kanaf) é metáfora para proteção divina (Salmo 17:8; 36:7; 57:1; 91:4). Boaz reconhece que Rute buscou refúgio em Yahweh. 'Galardão cumprido' (maskoret shleimah) - recompensa total. A bênção de Boaz é profética, pois ele mesmo será instrumento de resposta de Deus. A linguagem do 'abrigo sob asas' antecipa o casamento (Rute 3:9 onde ela pede que ele estenda sua capa/kanaf).",
      "📖 <strong>RESUMO:</strong> Boaz abençoa Rute, pedindo que o Senhor a recompense plenamente por ter buscado abrigo sob Suas asas.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Jesus desejou ajuntar Jerusalém 'como a galinha ajunta seus pintinhos debaixo das asas' (Mateus 23:37).",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 13</strong></span>",
      "<strong>TEXTO:</strong> E disse ela: Ache eu graça aos teus olhos, senhor meu; porque me consolaste, e porque falaste bondosamente à tua serva, não sendo eu ainda como uma das tuas servas.",
      "<strong>COMENTÁRIO:</strong> 😊 Rute responde com humildade continuada: 'não sou como uma das tuas servas' - ela se vê em posição inferior. 'Consolaste' (niḥamta) - linguagem emocional, curando sua dor de rejeição. O tratamento bondoso (al libbah - literalmente 'falou ao coração') é restaurador.",
      "📖 <strong>RESUMO:</strong> Rute agradece a consolação e bondade, reconhecendo-se indigna diante das servas de Boaz.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> A graça nos consola em meio à dor (2 Coríntios 1:3-4). Somos 'servos inúteis' (Lucas 17:10).",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 14</strong></span>",
      "<strong>TEXTO:</strong> Disse-lhe mais Boaz: Hora é já de comeres; chega-te aqui, e come do pão, e molha o teu bocado no vinagre. Ela se assentou ao lado dos ceifeiros, e ele lhe deu do trigo torrado; e ela comeu e se fartou, e ainda lhe sobejou.",
      "<strong>COMENTÁRIO:</strong> 🍞 Boaz a convida à refeição comunitária, não isolada. 'Vinagre' (ḥometz) é vinho azedado diluído em água - bebida comum de trabalhadores. 'Trigo torrado' (qali) era iguaria. Rute come até fartar (sava) e ainda sobra - sinal de provisão abundante. A generosidade de Boaz é extravagante.",
      "📖 <strong>RESUMO:</strong> Boaz convida Rute para a refeição, dando-lhe comida em abundância; ela come até se fartar e ainda sobra.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Jesus multiplicou pães e todos se fartaram (João 6:12). A generosidade de Deus transborda.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 15</strong></span>",
      "<strong>TEXTO:</strong> Levantando-se ela para colher, Boaz deu ordem a seus moços, dizendo: Colha ela também entre os molhos, e não a afronteis.",
      "<strong>COMENTÁRIO:</strong> 📜 Boaz instrui que permitam Rute colher 'entre os molhos' - local proibido para respigadores (que deviam ficar atrás). 'Não a afronteis' (lo taklimu) - não a envergonhem ou repreendam. A provisão agora ultrapassa a letra da lei, entrando na misericórdia.",
      "📖 <strong>RESUMO:</strong> Boaz ordena que seus moços permitam Rute colher entre os molhos e não a repreendam.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> A graça supera a lei (Romanos 6:14). Cristo nos convida à intimidade, não apenas à periferia.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 16</strong></span>",
      "<strong>TEXTO:</strong> E tirai dos molhos algumas espigas, e deixai-as, para que as colha, e não a repreendais.",
      "<strong>COMENTÁRIO:</strong> 🎁 Boaz ordena que deliberadamente deixem cair espigas (shalal - 'tirar dos molhos') para Rute encontrar. Não é apenas permitir, mas providenciar ativamente. Instrução dupla: 'não a repreendais' (tov). A generosidade é intencional e secreta (para não humilhar a beneficiária).",
      "📖 <strong>RESUMO:</strong> Boaz manda que os ceifeiros deixem cair espigas propositadamente para que Rute as colha sem repreensão.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Quando deres esmola, não saiba a tua mão esquerda o que faz a direita' (Mateus 6:3). A discrição é parte do amor.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 17</strong></span>",
      "<strong>TEXTO:</strong> Assim colheu ela no campo até à tarde; e debulhou o que havia colhido, e foi quase um efa de cevada.",
      "<strong>COMENTÁRIO:</strong> ⚖️ Um efa = cerca de 22-30 litros, aproximadamente 13-18 kg de cevada. Era uma quantidade impressionante para um dia de respiga (normalmente se obtinha bem menos). O trabalho de Rute, somado à generosidade planejada de Boaz, resulta em provisão abundante. 'Até à tarde' indica jornada exaustiva.",
      "📖 <strong>RESUMO:</strong> Rute trabalha o dia todo, debulha a cevada e obtém quase um efa (cerca de 22-30 litros).",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> O trabalho fiel é recompensado por Deus (Colossenses 3:24). A abundância vem do Senhor.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 18</strong></span>",
      "<strong>TEXTO:</strong> E tomou-o, e foi à cidade; e viu sua sogra o que havia colhido; também tirou e deu-lhe o que lhe sobejara depois de fartar-se.",
      "<strong>COMENTÁRIO:</strong> 🏠 Rute compartilha a provisão com Noemi. 'O que sobejou' (hoter) - excedente da refeição que guardou. O coração generoso de Rute é visível: depois de trabalhar por comida, ela ainda divide. A cena mostra amor prático, não apenas palavras.",
      "📖 <strong>RESUMO:</strong> Rute leva a cevada para a cidade, mostra à sogra e ainda lhe dá o que sobejou da refeição.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> O amor se prova por ações, não palavras (1 João 3:18). Compartilhar com necessitados é adoração (Hebreus 13:16).",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 19</strong></span>",
      "<strong>TEXTO:</strong> Então disse-lhe sua sogra: Onde colheste hoje? e onde trabalhaste? bendito seja aquele que te conheceu! E ela contou à sua sogra com quem tinha trabalhado, e disse: O nome do homem com quem hoje trabalhei é Boaz.",
      "<strong>COMENTÁRIO:</strong> 🔍 A bênção de Noemi ('Bendito seja aquele que te conheceu') é intuitiva: ela percebe que alguém importante tratou Rute com favor extraordinário. Ao ouvir o nome Boaz, Noemi conecta os pontos: parente próximo, homem rico. O verbo 'conheceu' (nikkar) tem conotação de reconhecimento atencioso.",
      "📖 <strong>RESUMO:</strong> Noemi pergunta onde Rute trabalhou; ao saber que foi com Boaz, ela bendiz o nome dele.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Deus usa pessoas específicas para abençoar. A providência tem nomes e rostos. Referência: Romanos 16:12.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 20</strong></span>",
      "<strong>TEXTO:</strong> E Noemi disse a sua nora: Bendito seja ele do Senhor, que ainda não deixou a sua benevolência, nem para com os vivos, nem para com os mortos. Disse-lhe mais Noemi: Este homem é nosso parente chegado, e um dos nossos remidores.",
      "<strong>COMENTÁRIO:</strong> 🔗 'Benevolência' (ḥesed) - amor leal da aliança. Noemi vê a mão de Deus estendendo ḥesed a ela. 'Vivos' (Boaz, Rute) e 'mortos' (Elimeleque, Malom, Quiliom) são abençoados. 'Remidor' (go'el) é termo técnico: parente próximo que resgata terra, vinga sangue, casa com viúva do falecido para perpetuar nome (Levítico 25:25; Deuteronômio 25:5-10). A esperança renasce.",
      "📖 <strong>RESUMO:</strong> Noemi bendiz Boaz e reconhece-o como parente próximo, um dos remidores (go'el) da família.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Cristo é nosso Go'el definitivo (Jó 19:25) - nos resgata da escravidão do pecado. Referência: Gálatas 3:13.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 21</strong></span>",
      "<strong>TEXTO:</strong> Rute, a moabita, disse mais: Também me disse ele: Com os meus jovens te ajuntarás até que acabem toda a minha sega.",
      "<strong>COMENTÁRIO:</strong> 📅 O convite de Boaz para ficar durante toda a colheita (cevada e trigo - cerca de 2 meses) é extensão de proteção. Rute relata precisamente a oferta, mostrando transparência. A segurança de longo prazo é oferecida.",
      "📖 <strong>RESUMO:</strong> Rute acrescenta que Boaz a convidou a permanecer com seus trabalhadores durante toda a colheita.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> A segurança do crente é eterna: 'estarei convosco todos os dias' (Mateus 28:20).",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 22</strong></span>",
      "<strong>TEXTO:</strong> E Noemi disse a Rute, sua nora: Melhor é, minha filha, que saias com as suas moças, para que noutro campo não te encontrem.",
      "<strong>COMENTÁRIO:</strong> 👭 Noemi demonstra sabedoria prática: permanecer no campo de Boaz com as moças evita perigo em outros campos (onde os moços poderiam assediar). A orientação é protetora, não possessiva. O bom conselho de Noemi combina fé com prudência.",
      "📖 <strong>RESUMO:</strong> Noemi aconselha Rute a continuar com as moças de Boaz para evitar perigo em outros campos.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Sede prudentes como as serpentes' (Mateus 10:16). A fé não exclui o bom senso.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 23</strong></span>",
      "<strong>TEXTO:</strong> Assim se ajuntou com as moças de Boaz, para colher até o fim da colheita das cevadas e da colheita do trigo; e ficou com a sua sogra.",
      "<strong>COMENTÁRIO:</strong> 🏡 Rute obedece ao conselho e permanece no campo de Boaz por toda a temporada de colheita (c. abril a junho). O versículo finaliza o capítulo em harmonia: Rute fiel a Noemi, trabalhadora, protegida e presente. O palco está montado para o próximo ato - a ousada proposta de casamento por Noemi.",
      "📖 <strong>RESUMO:</strong> Rute trabalha com as moças de Boaz durante toda a colheita e continua morando com Noemi.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> A fidelidade nas pequenas coisas precede grandes bênçãos (Lucas 16:10). A colheita de Rute prepara o casamento.",

      "<p style='font-size: 0.8rem; text-align: center;'><i><strong>Reflexão Final do Capítulo 2</strong></i></p><p style='font-size: 0.55rem;'>O capítulo 2 demonstra a providência divina agindo nos bastidores. A 'coincidência' de Rute ir parar exatamente no campo de Boaz, parente de Elimeleque, é o dedo de Deus guiando os passos da fé. Boaz é apresentado como 'homem virtuoso' (gibbor hayil) – poderoso, rico, mas também piedoso e justo. Sua saudação aos ceifeiros ('O Senhor seja convosco') e a proteção imediata que oferece a Rute (proibindo os moços de molestá-la, oferecendo água e comida) revelam seu caráter. Rute, por sua vez, demonstra uma ética de trabalho notável e humildade.</p><p>A provisão abundante (um efa de cevada, aproximadamente 30 litros) e a generosidade planejada de Boaz (deixar cair espigas propositadamente) mostram que a lei do respigo (Levítico 19:9-10) é uma porta de entrada para a graça. Noemi, ao saber que o benfeitor é Boaz, reconhece a mão de Deus: 'bendito seja ele do Senhor, que ainda não deixou a sua benevolência'. O capítulo ensina que a fidelidade nas pequenas coisas (Rute respigando) e a generosidade dos que têm (Boaz) são instrumentos da provisão divina.</p>"
    ],
    
    3: [
      "<p style='font-size: 0.8rem; text-align: center;'><i><strong>Ousadia redentora: Rute reclama o direito de resgate na eira de Boaz</strong></i></p>",
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 1</strong></span>",
      "<strong>TEXTO:</strong> Depois lhe disse Noemi, sua sogra: Minha filha, não hei de buscar descanso para ti, para que fiques bem?",
      "<strong>COMENTÁRIO:</strong> 🏠 'Descanso' (manoach) ecoa 1:9 (menuḥah) - segurança no casamento. Noemi agora age ativamente como casamenteira, pois vê em Boaz o redentor. A pergunta retórica implica: 'É meu dever providenciar seu futuro'. Noemi muda de passiva (1:8-13) para proativa.",
      "📖 <strong>RESUMO:</strong> Noemi toma iniciativa de buscar 'descanso' (segurança matrimonial) para Rute, visando seu bem-estar.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Cristo busca 'descanso' para os seus (Mateus 11:28). A igreja é noiva que aguarda o descanso eterno.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 2</strong></span>",
      "<strong>TEXTO:</strong> Ora, pois, não é Boaz, com quem estiveste com as suas moças, de nossa parentela? Eis que ele esta noite alimpará a cevada na eira.",
      "<strong>COMENTÁRIO:</strong> 🌾 'Alimpará' (zoreh) - joeirar: jogar cevada ao vento para separar palha do grão. A eira (goren) era local de trabalho noturno quando soprava brisa. Também era lugar de celebração, onde os donos dormiam para proteger a colheita. Boaz estaria lá, vulnerável e acessível. Noemi usa informações práticas.",
      "📖 <strong>RESUMO:</strong> Noemi informa que Boaz, o parente próximo, estará joeirado cevada na eira à noite.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> João Batista disse que Cristo 'alimpará sua eira' (Mateus 3:12) - separando o joio do trigo.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 3</strong></span>",
      "<strong>TEXTO:</strong> Lava-te, pois, e unge-te, e veste os teus vestidos, e desce à eira; mas não te dês a conhecer ao homem, até que tenha acabado de comer e beber.",
      "<strong>COMENTÁRIO:</strong> 🧼 As instruções: 1) lavar (higiene ritual e preparação para encontro significativo); 2) ungir (perfume - sinal de festa e beleza); 3) vestir melhores roupas (não de luto ou trabalho). O objetivo era atrair Boaz, mas com decoro. 'Não te dês a conhecer' até ele terminar a refeição - esperar o momento adequado.",
      "📖 <strong>RESUMO:</strong> Noemi orienta Rute a se embelezar e ir à eira, mas esperar Boaz terminar de comer e beber.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> A igreja se prepara como noiva para Cristo (Apocalipse 19:7) - vestida de linho fino, que são as justiças dos santos.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 4</strong></span>",
      "<strong>TEXTO:</strong> E há de ser que, quando ele se deitar, notarás o lugar em que se deita; então entrarás, e descobrir-lhe-ás os pés, e te deitarás; e ele te dirá o que hás de fazer.",
      "<strong>COMENTÁRIO:</strong> 🦶 A ação de 'descobrir os pés' (gillah margelotav) é simbólica e culturalmente carregada. Não era ato sexual, mas gesto de reivindicar proteção (cf. Deuteronômio 25:9 onde descalçar sapato é sinal de renúncia). Descobrir os pés num sentido figurado pode significar vulnerabilidade e submissão. Rute pediria a Boaz que estendesse sua 'capa/asa' (3:9) sobre ela. Era ato ousado, mas não imoral - viúva reivindicava direito de levirato.",
      "📖 <strong>RESUMO:</strong> Rute deve observar onde Boaz se deita, descobrir seus pés e deitar-se ali, aguardando a orientação dele.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Maria Madalena foi ao túmulo 'de madrugada' (João 20:1) corajosamente. A ousadia santa é recompensada.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 5</strong></span>",
      "<strong>TEXTO:</strong> E ela lhe disse: Tudo quanto me disseres farei.",
      "<strong>COMENTÁRIO:</strong> Rute demonstra obediência total e confiança na sogra. Esta submissão não é cega, mas baseada no amor e sabedoria reconhecida. A mesma obediência que a levou a seguir Noemi a Belém agora a leva a um passo ousado.",
      "📖 <strong>RESUMO:</strong> Rute promete obedecer integralmente à orientação de Noemi.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Fazei tudo o que ele vos disser' (João 2:5) - as palavras de Maria em Caná. Obediência precede milagre.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 6</strong></span>",
      "<strong>TEXTO:</strong> Desceu, pois, à eira, e fez conforme tudo quanto sua sogra lhe ordenara.",
      "<strong>COMENTÁRIO:</strong> ✅ A obediência é executada sem hesitação. Rute não questiona o risco social: se fosse descoberta, seria considerada prostituta. A fé opera em meio à vulnerabilidade.",
      "📖 <strong>RESUMO:</strong> Rute desce à eira e cumpre exatamente o que Noemi ordenou.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Abraão obedeceu sem saber para onde ia (Hebreus 11:8). A fé age mesmo sem todos os detalhes.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 7</strong></span>",
      "<strong>TEXTO:</strong> Havendo, pois, Boaz comido e bebido, e já com o coração alegre, veio deitar-se ao pé do monte de cevada; então ela veio de mansinho, e descobriu-lhe os pés, e se deitou.",
      "<strong>COMENTÁRIO:</strong> 🌙 'Coração alegre' (yitav libo) - após refeição festiva, Boaz estava satisfeito, mas não embriagado (a Bíblia condena embriaguez, mas permite alegria moderada). Ele se deita ao pé do monte ('montão' - não montanha). Rute aproxima-se 'de mansinho' (bacharesh - sigilosamente) para não ser vista por outros trabalhadores. O 'descobrir os pés' e deitar-se era gesto simbólico de solicitação de casamento levirato.",
      "📖 <strong>RESUMO:</strong> Após a refeição festiva, Boaz se deita; Rute aproxima-se silenciosamente, descobre seus pés e se deita.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'A noite é escura, mas perto está o dia' (Romanos 13:12). A ousadia na escuridão precede a revelação da luz.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 8</strong></span>",
      "<strong>TEXTO:</strong> E sucedeu que, pela meia-noite, o homem estremeceu, e se voltou; e eis que uma mulher jazia a seus pés.",
      "<strong>COMENTÁRIO:</strong> 😲 'Estremeceu' (yeḥerad) - Boaz acorda sobressaltado, possivelmente sentindo frio ou percebendo algo incomum. Ao se voltar, descobre Rute. A cena é tensa: ele poderia ter reagido com raiva ou medo. A reação de Boaz será determinante.",
      "📖 <strong>RESUMO:</strong> À meia-noite, Boaz acorda assustado e encontra uma mulher deitada a seus pés.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> O susto de Boaz é como o tremor diante da presença divina (Jó 4:14). Deus opera em 'meia-noite' (Atos 16:25).",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 9</strong></span>",
      "<strong>TEXTO:</strong> E disse ele: Quem és tu? E ela respondeu: Sou Rute, tua serva; estende, pois, a tua capa sobre a tua serva, porque tu és remidor.",
      "<strong>COMENTÁRIO:</strong> 🧥 'Estende tua capa' (parasta kenafekha) - literalmente 'estende a borda/asa da tua capa'. Ecoa 2:12 ('sob cujas asas vieste te abrigar'). Pedir a capa é pedir proteção conjugal (Ezequiel 16:8 - Deus estende a orla sobre Jerusalém como símbolo de aliança de casamento). Rute declara Boaz como go'el (remidor). Coragem impressionante.",
      "📖 <strong>RESUMO:</strong> Rute se identifica e pede que Boaz estenda sua capa sobre ela como sinal de proteção e casamento, pois ele é remidor.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Cristo estende Sua 'capa' de justiça sobre nós (Isaías 61:10). O casamento místico com Cristo é o grande mistério (Efésios 5:32).",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 10</strong></span>",
      "<strong>TEXTO:</strong> E disse ele: Bendita sejas tu do Senhor, minha filha; porque melhor fizeste esta tua última benevolência do que a primeira, pois após nenhum mancebo foste, quer pobre quer rico.",
      "<strong>COMENTÁRIO:</strong> 🌟 Boaz abençoa Rute, não a repreende. 'Última benevolência' (hesed) - Rute demonstrou hesed ao buscar casamento com Boaz para perpetuar nome do falecido, em vez de buscar jovens ('mancebos') por atração pessoal. A virtude de Rute é confirmada: ela prioriza o dever do levirato sobre o romance. Boaz a elogia duplamente.",
      "📖 <strong>RESUMO:</strong> Boaz a abençoa, elogiando-a por buscar o remidor mais velho (ele) em vez de jovens, demonstrando lealdade especial.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> O amor ágape não busca o próprio interesse (1 Coríntios 13:5). Rute exemplifica devoção à aliança.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 11</strong></span>",
      "<strong>TEXTO:</strong> Agora, pois, minha filha, não temas; tudo quanto disseste te farei, pois toda a cidade do meu povo sabe que és mulher virtuosa.",
      "<strong>COMENTÁRIO:</strong> 💎 'Mulher virtuosa' ('eshet ḥayil) - mesma expressão usada para Boaz (gibbor ḥayil - homem virtuoso/poderoso) em 2:1. Rute tem reputação de excelência moral. 'Toda a cidade do meu povo sabe' - evidência pública. Boaz promete agir: 'não temas' dissipa o medo de rejeição. A integridade abre portas.",
      "📖 <strong>RESUMO:</strong> Boaz a tranquiliza, elogiando sua virtude (mulier virtuosa) reconhecida publicamente, e promete atendê-la.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> A mulher virtuosa de Provérbios 31 é celebrada. A reputação cristã deve ser imaculada (1 Timóteo 3:7).",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 12</strong></span>",
      "<strong>TEXTO:</strong> Agora é bem verdade que eu sou remidor; mas ainda outro remidor há mais chegado do que eu.",
      "<strong>COMENTÁRIO:</strong> 👥 Boaz revela um obstáculo: há um parente mais próximo (ha-go'el ha-rishon) com prioridade legal. O direito de resgate é sequencial (Levítico 25:25). Boaz não pode usurpar o direito de outrem. Sua honestidade é notável - ele poderia ignorar o parente, mas escolhe a retidão.",
      "📖 <strong>RESUMO:</strong> Boaz admite ser remidor, mas revela que há outro parente mais próximo com direito prioritário.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> A lei não pode ser quebrada nem por amor (Romanos 13:8-10). Cristo cumpriu a lei, não a violou.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 13</strong></span>",
      "<strong>TEXTO:</strong> Fica aqui esta noite, e será que pela manhã, se ele te resgatar, será bem; mas, se não te quiser resgatar, vivo é o Senhor, que eu te resgatarei; deita-te aqui até pela manhã.",
      "<strong>COMENTÁRIO:</strong> ⚖️ Boaz oferece solução: ele mesmo resolverá legalmente na porta da cidade pela manhã. Se o parente mais próximo assumir o resgate, 'bem será' (tov - aceitável para Rute? Não necessariamente emocional, mas legalmente correto) . Caso contrário, Boaz jura por Yahweh que resgatará. O juramento 'vivo é o Senhor' é solene. Boaz protege a reputação de Rute ao instruí-la a ficar até a manhã (evitando que saia à noite e seja vista).",
      "📖 <strong>RESUMO:</strong> Boaz diz que resolverá pela manhã: se o parente mais próximo quiser resgatar, bem; senão, ele próprio o fará.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Cristo é nosso 'Boaz' que se dispôs a nos resgatar quando nenhum outro (a lei, os profetas) pôde. Referência: Hebreus 7:19.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 14</strong></span>",
      "<strong>TEXTO:</strong> Ficou, pois, deitada a seus pés até pela manhã, e levantou-se antes que pudesse alguém conhecer a outrem; porque disse ele: Não se saiba que alguma mulher veio à eira.",
      "<strong>COMENTÁRIO:</strong> 🌅 Rute parte antes do amanhecer ('antes que pudesse alguém conhecer a outrem' - antes da meia-luz). Boaz zela pela reputação dela, evitando escândalo. O encontro noturno, se descoberto, arruinaria sua virtude. A discrição é ato de amor e proteção.",
      "📖 <strong>RESUMO:</strong> Rute passa a noite aos pés de Boaz e se levanta antes do amanhecer para não ser vista e evitar escândalo.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Todas as coisas vos sejam feitas com decência e ordem' (1 Coríntios 14:40). O zelo pela reputação alheia é cristão.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 15</strong></span>",
      "<strong>TEXTO:</strong> Disse mais: Dá aqui a capa com que te cobres, e segura-a. Segurou-a ele, e mediu seis medidas de cevada, e lhas pôs; então ela foi para a cidade.",
      "<strong>COMENTÁRIO:</strong> 🧺 Boaz dá a Rute 'seis medidas' (se'ah) - cerca de 50-60 litros! Era presente generoso, não paga. A capa (mitpaḥat - manta) serviu como saco. Este presente serve como prova para Noemi de que Boaz agiu favoravelmente, e também provisão prática. A generosidade confirma seu compromisso.",
      "📖 <strong>RESUMO:</strong> Boaz dá a Rute seis medidas de cevada envoltas em sua capa; ela volta à cidade carregando o presente.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> O Espírito Santo é o 'penhor' da herança (Efésios 1:14) - uma garantia do que está por vir.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 16</strong></span>",
      "<strong>TEXTO:</strong> E veio à sua sogra; e disse ela: És tu, minha filha? Então lhe contou tudo quanto aquele homem lhe fizera;",
      "<strong>COMENTÁRIO:</strong> 👂 A pergunta de Noemi ('És tu, minha filha?') pode indicar ansiedade: 'E então? Como foi?' O hebraico 'mi att' (literalmente 'quem és?') sugere que Noemi, na escuridão, mal podia vê-la, mas também pergunta sobre o desfecho. Rute relata 'tudo' - transparência total, sem omitir os detalhes.",
      "📖 <strong>RESUMO:</strong> Rute volta a Noemi e conta tudo o que Boaz lhe fez.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> A confissão mútua (Tiago 5:16) traz conselho sábio. A transparência no corpo de Cristo é saudável.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 17</strong></span>",
      "<strong>TEXTO:</strong> e disse: Estas seis medidas de cevada me deu, porque me disse: Não irás vazia para tua sogra.",
      "<strong>COMENTÁRIO:</strong> 🎁 O presente é acompanhado de palavras: 'Não irás vazia' (re'qam) - exatamente o oposto de Noemi em 1:21 ('vazia' - reqam). Deus está revertendo a maldição. Rute retorna com provisão e esperança.",
      "📖 <strong>RESUMO:</strong> Rute explica o significado do presente: Boaz não queria que ela voltasse de mãos vazias para a sogra.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Deus não nos deixa vazios (João 14:18). Cristo nos enche com o Espírito e a esperança. Referência: Romanos 15:13.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 18</strong></span>",
      "<strong>TEXTO:</strong> Então disse ela: Fica-te, minha filha, até que saibas como cairá o caso; porque aquele homem não descansará enquanto não tiver concluído este negócio hoje.",
      "<strong>COMENTÁRIO:</strong> ⏳ Noemi conhece o caráter de Boaz: ele é homem de ação, não procrastinador. 'Não descansará' (lo yishqot) - expressão de determinação. Noemi instrui Rute a esperar pacientemente. O capítulo termina com tensão resolvida: a questão será julgada na porta da cidade.",
      "📖 <strong>RESUMO:</strong> Noemi orienta Rute a esperar, pois Boaz resolverá a questão do resgate ainda naquele mesmo dia.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Espera no Senhor' (Salmo 27:14). Deus age no tempo certo. O descanso de Boaz prenuncia a obra consumada de Cristo.",

      "<p style='font-size: 0.8rem; text-align: center;'><i><strong>Reflexão Final do Capítulo 3</strong></i></p><p style='font-size: 0.55rem;'>O capítulo 3 é um ato de ousadia santa e fé arriscada. Noemi, agora proativa, instrui Rute a reivindicar o direito de resgate (go'el) na eira de Boaz. O gesto de descobrir os pés e deitar-se aos seus pés não é sedução, mas um ato simbólico de pedir proteção e casamento levirato, conforme o costume do Antigo Oriente Próximo. A resposta de Boaz é exemplar: ele não a rejeita, mas a abençoa, elogiando sua 'última benevolência' (hesed) – ela buscou o remidor mais velho para perpetuar o nome do falecido, em vez de um jovem por atração pessoal. A integridade de Boaz brilha quando ele menciona o parente mais próximo, cujo direito de resgate tem prioridade. Ele não toma atalhos, mas promete resolver legalmente pela manhã. A discrição de Boaz ao enviar Rute antes do amanhecer protege sua reputação. O presente generoso (seis medidas de cevada) é um penhor da promessa. O capítulo ensina que a fé pode ser ousada, mas deve operar dentro dos limites da lei e da integridade. A paciência é necessária: 'aquele homem não descansará enquanto não tiver concluído este negócio hoje'.</p>"
    ],
    
    4: [
      "<p style='font-size: 0.8rem; text-align: center;'><i><strong>Redenção plena: Casamento de Boaz e Rute, nascimento de Obede, linhagem de Davi</strong></i></p>",
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 1</strong></span>",
      "<strong>TEXTO:</strong> E Boaz subiu à porta, e assentou-se ali; e eis que o remidor de que Boaz falava passava; então disse: Fala, vem para aqui, assenta-te. E ele veio, e se assentou.",
      "<strong>COMENTÁRIO:</strong> 🏛️ 'Porta' (sha'ar) era o tribunal da cidade, onde anciãos se reuniam para julgar causas. Boaz toma iniciativa legal. O tal 'parente mais próximo' passa casualmente - providência: Deus o trouxe no momento exato. Boaz o chama pelo nome? A Bíblia não revela seu nome, talvez para não o envergonhar. O convite 'vem e assenta-te' é formal.",
      "📖 <strong>RESUMO:</strong> Boaz vai à porta da cidade (tribunal local) e convida o parente mais próximo a sentar-se para tratar do resgate.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Cristo, nosso Go'el, cumpriu a redenção legalmente, não por violência ou subterfúgio. Referência: Gálatas 4:4-5.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 2</strong></span>",
      "<strong>TEXTO:</strong> Então Boaz tomou dez homens dos anciãos da cidade, e disse: Assentai-vos aqui. E assentaram-se.",
      "<strong>COMENTÁRIO:</strong> ⚖️ Dez homens formavam um quórum legal para transações civis (cf. Rute 4:2; Números 35:24-25). Boaz convoca testemunhas idôneas. O processo é transparente e justo, garantindo validade jurídica ao resgate.",
      "📖 <strong>RESUMO:</strong> Boaz reúne dez anciãos como testemunhas oficiais.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> 'Toda questão se decidirá por duas ou três testemunhas' (Mateus 18:16). A justiça requer testemunho.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 3</strong></span>",
      "<strong>TEXTO:</strong> Depois disse ao remidor: Noemi, que voltou da terra de Moabe, vendeu uma parte das terras que pertencia a nosso irmão Elimeleque.",
      "<strong>COMENTÁRIO:</strong> 🧑‍🌾 Noemi, por ser viúva e não ter filhos, provavelmente precisou vender a terra de Elimeleque para sobreviver. A lei permitia que parentes resgatassem (Levítico 25:25). Boaz apresentaa questão de forma neutra, sem mencionar Rute ainda. A terra tinha valor econômico e simbólico (aliança).",
      "📖 <strong>RESUMO:</strong> Boaz informa que Noemi está vendendo uma porção de terra pertencente à família de Elimeleque.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Nossa herança celestial perdida pelo pecado foi resgatada por Cristo (Efésios 1:14). Referência: 1 Pedro 1:4.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 4</strong></span>",
      "<strong>TEXTO:</strong> E eu disse: Darei parte aos teus ouvidos, dizendo: Compra-a na presença dos que estão sentados aqui, e diante dos anciãos do meu povo. Se tu a queres resgatar, resgata-a; e se a não queres resgatar, declara-mo, para que eu o saiba; porque não há outro que a resgate senão tu, e eu depois de ti. Então disse ele: Eu a resgatarei.",
      "<strong>COMENTÁRIO:</strong> Boaz oferece a prioridade de resgate ao parente mais próximo. A resposta imediata: 'Eu a resgatarei' (ga'al) - o parente vê vantagem econômica na terra. Ele não sabe ainda do 'encargo' adicional (Rute). O direito de resgate era privilégio, não fardo.",
      "📖 <strong>RESUMO:</strong> Boaz expõe o direito de resgate, dando prioridade ao parente; ele concorda prontamente em resgatar a terra.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Muitos desejam as bênçãos terrenas de Deus (a terra), mas relutam quanto ao custo do discipulado (Rute). Referência: Lucas 14:28-30.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 5</strong></span>",
      "<strong>TEXTO:</strong> Disse, porém, Boaz: No dia em que comprares o campo da mão de Noemi, também a tomarás a Rute, a moabita, mulher do falecido, para que suscites o nome do falecido sobre a sua herança.",
      "<strong>COMENTÁRIO:</strong> ⚠️ Boaz revela a cláusula do levirato: o resgate da terra implica casamento com Rute para gerar descendência ao falecido (Malom). O parente agora enfrenta dilema: a terra seria herdada pelo filho gerado, não por seus próprios herdeiros. Isso poderia prejudicar sua herança pessoal. O pedido de Boaz é legalmente astuto e justo.",
      "📖 <strong>RESUMO:</strong> Boaz esclarece que o resgate inclui também o levirato: casar-se com Rute para suscitar descendência ao falecido.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> O discipulado tem custo: carregar a cruz (Mateus 16:24). Muitos desejam o céu sem abrir mão do mundo.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 6</strong></span>",
      "<strong>TEXTO:</strong> Então disse o remidor: Não poderei resgatá-lo para mim, para que não prejudique a minha própria herança; toma tu para ti o meu direito de remissão, porque eu não o posso resgatar.",
      "<strong>COMENTÁRIO:</strong> 💰 A justificativa: 'não prejudicar minha herança' - ele teme que a terra vá para o filho de Rute (que perpetuaria o nome de Malom) e não para seus herdeiros. Ele recusa, cedendo o direito a Boaz. A recusa é legal e honrosa, não maliciosa. Ele abre mão formalmente (o 'sapato' versículo 7).",
      "📖 <strong>RESUMO:</strong> O parente mais próximo recusa, alegando prejuízo à própria herança, e cede o direito a Boaz.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> A lei, personificada por este parente, não pode nos redimir completamente; Cristo (Boaz) faz o que a lei não pode (Romanos 8:3).",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 7</strong></span>",
      "<strong>TEXTO:</strong> Era, pois, este o costume antigo em Israel, quanto à remissão e à permuta, para confirmar todo o negócio; um homem descalçava o sapato, e o dava ao seu próximo; e isto era por testemunho em Israel.",
      "<strong>COMENTÁRIO:</strong> 👟 O ato de descalçar o sapato e entregar ao outro selava a renúncia do direito de compra (cf. Deuteronômio 25:9 - a viúva descalçava o sapato do cunhado que recusava levirato, mas aqui o próprio recusador tira o sapato e dá). O costume antigo garantia testemunho visual inesquecível. O autor explica a prática para leitores posteriores.",
      "📖 <strong>RESUMO:</strong> Explicação do costume: descalçar e entregar o sapato era sinal legal de renúncia ao direito de resgate.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> O batismo é um 'testemunho' visível da renúncia ao mundo e compromisso com Cristo. Referência: Atos 2:38.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 8</strong></span>",
      "<strong>TEXTO:</strong> Disse, pois, o remidor a Boaz: Toma-a para ti. E descalçou o sapato.",
      "<strong>COMENTÁRIO:</strong> A renúncia é formalizada. O parente anônimo desaparece da história. Boaz agora está legalmente autorizado a agir como go'el. A justiça foi cumprida.",
      "📖 <strong>RESUMO:</strong> O parente cede formalmente o direito a Boaz, descalçando o sapato como testemunho.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> João Batista disse: 'É necessário que ele cresça e que eu diminua' (João 3:30). O precursor cede lugar ao Cristo.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 9</strong></span>",
      "<strong>TEXTO:</strong> Então Boaz disse aos anciãos e a todo o povo: Vós sois hoje testemunhas de que comprei da mão de Noemi tudo quanto foi de Elimeleque, e tudo quanto foi de Quiliom, e de Malom;",
      "<strong>COMENTÁRIO:</strong> 🗣️ Boaz proclama publicamente a transação. Ele menciona 'tudo quanto foi' de Elimeleque e seus filhos, unificando a herança. As testemunhas confirmam a legalidade. A compra é legítima.",
      "📖 <strong>RESUMO:</strong> Boaz declara publicamente que comprou todas as propriedades da família de Elimeleque das mãos de Noemi.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> A redenção de Cristo é proclamada publicamente (1 Timóteo 2:5-6) diante de testemunhas celestiais e terrestres.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 10</strong></span>",
      "<strong>TEXTO:</strong> e também a Rute, a moabita, mulher de Malom, tomo por mulher, para suscitar o nome do falecido sobre a sua herança, para que o nome do falecido não se apague de entre seus irmãos e da porta do seu lugar; hoje sois testemunhas disso.",
      "<strong>COMENTÁRIO:</strong> 💍 Boaz toma Rute como esposa, mencionando explicitamente seu objetivo: perpetuar o nome de Malom (e por extensão de Elimeleque). A motivação não é paixão egoísta, mas obediência ao levirato e amor hesed. 'Não se apague o nome' - honra ao falecido. Boaz é modelo de altruísmo.",
      "📖 <strong>RESUMO:</strong> Boaz anuncia que toma Rute como esposa para suscitar descendência ao falecido Malom e perpetuar seu nome.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Cristo tomou a igreja (gentia, como Rute) para dar-lhe um nome e herança (Apocalipse 2:17; 3:12).",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 11</strong></span>",
      "<strong>TEXTO:</strong> E todo o povo que estava na porta, e os anciãos, disseram: Somos testemunhas; o Senhor faça a esta mulher, que entra na tua casa, como a Raquel e como a Lia, que edificaram ambas a casa de Israel; e porta-te valorosamente em Efrata, e faze-te nome afamado em Belém;",
      "<strong>COMENTÁRIO:</strong> 🏡 A bênção da comunidade invoca as matriarcas de Israel (Raquel e Lia). 'Edificar a casa de Israel' é linguagem de procriação abundante. 'Porta-te valorosamente' (aseh ḥayil) - mesma raiz de 'virtuoso'. 'Efrata' é o antigo nome de Belém (Miqueias 5:2). A comunidade abençoa Boaz e Rute com fecundidade e reputação.",
      "📖 <strong>RESUMO:</strong> Os anciãos e o povo abençoam Boaz e Rute, comparando Rute a Raquel e Lia e desejando prosperidade e fama a Boaz.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> A igreja é edificada sobre o fundamento dos apóstolos e profetas (Efésios 2:20). A bênção comunitária reflete o corpo de Cristo.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 12</strong></span>",
      "<strong>TEXTO:</strong> e seja a tua casa como a casa de Perez, que Tamar deu a Judá, da semente que o Senhor te der desta moça.",
      "<strong>COMENTÁRIO:</strong> 🌳 A referência a Pérez (filho de Judá com Tamar, nora) é notável: Tamar, como Rute, também era viúva que usou estratégia ousada para garantir descendência. A genealogia de Pérez é a linha messiânica (Mateus 1:3). A bênção aponta para algo maior: o Messias virá desta linhagem.",
      "📖 <strong>RESUMO:</strong> Desejam que a casa de Boaz seja como a casa de Pérez (filho de Judá com Tamar), abençoada e prolífica.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Jesus descende de Pérez (Mateus 1:3-6). A graça supera a irregularidade humana para trazer redenção.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 13</strong></span>",
      "<strong>TEXTO:</strong> Assim Boaz tomou a Rute, e ela lhe foi por mulher; e ele a possuiu, e o Senhor lhe deu concepção, e ela teve um filho.",
      "<strong>COMENTÁRIO:</strong> 👶 O casamento é consumado. A narrativa é econômica e sagrada: 'O Senhor lhe deu concepção' - o filho é dom divino, não apenas resultado biológico. A esterilidade de Rute (implícita por dez anos de casamento anterior sem filhos) é curada por Deus. O milagre aponta para a graça.",
      "📖 <strong>RESUMO:</strong> Boaz casa com Rute; Deus concede que ela conceba e dê à luz um filho.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Toda vida é dom de Deus. O nascimento de João Batista e Jesus foram também intervenções divinas. Referência: Lucas 1:13, 31.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 14</strong></span>",
      "<strong>TEXTO:</strong> Então as mulheres disseram a Noemi: Bendito seja o Senhor, que não te deixou hoje sem remidor, e seja o seu nome afamado em Israel.",
      "<strong>COMENTÁRIO:</strong> 🙌 As mulheres da vizinhança (as mesmas que antes se perguntaram 'Não é esta Noemi?') agora louvam a Deus. O 'remidor' (go'el) aqui refere-se ao neto Obede, que redimirá a velhice de Noemi. A linguagem ecoa 1:21 ('vazia') agora revertida. Deus não abandona Seu povo.",
      "📖 <strong>RESUMO:</strong> As mulheres bendizem ao Senhor por não ter deixado Noemi sem remidor (o neto Obede) e oram por sua fama em Israel.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Bendito seja Deus, que nos deu um Remidor em Cristo (Lucas 1:68 - 'Bendito o Senhor Deus de Israel, porque visitou e redimiu o seu povo').",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 15</strong></span>",
      "<strong>TEXTO:</strong> Ele será para ti restaurador da alma, e conservará a tua velhice; porque tua nora, que te ama, o teve; e ela é melhor para ti do que sete filhos.",
      "<strong>COMENTÁRIO:</strong> ❤️ 'Restaurador da alma' (meshiv nefesh) - aquele que renova a vida. O neto sustentará Noemi na velhice. 'Melhor do que sete filhos' - elogio máximo a Rute: uma nora fiel vale mais que muitos filhos. A comunidade reconhece o hesed de Rute. A amargura de Mara (1:20) transformou-se em doçura.",
      "📖 <strong>RESUMO:</strong> As mulheres profetizam que o filho restaurará a alma de Noemi e sustentará sua velhice, e exaltam Rute como melhor que sete filhos.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> O amor de Cristo é melhor que relações terrenas. 'Ninguém tem maior amor do que este' (João 15:13).",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 16</strong></span>",
      "<strong>TEXTO:</strong> E Noemi tomou o filho, e o pôs no seu regaço, e foi sua ama.",
      "<strong>COMENTÁRIO:</strong> 👵 Noemi atua como ama (o'menet) - provavelmente ama de leite ou cuidadora. O gesto de colocar no regaço simboliza adoção e nutrição. A velha viúva, que pensava estar vazia, agora tem um neto em seus braços. A restauração é completa.",
      "📖 <strong>RESUMO:</strong> Noemi toma o menino nos braços como ama, assumindo cuidado e afeto.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Simeão tomou Jesus nos braços (Lucas 2:28). Os idosos podem ainda abraçar a promessa de Deus.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 17</strong></span>",
      "<strong>TEXTO:</strong> E as vizinhas lhe deram nome, dizendo: A Noemi nasceu um filho; e chamaram o seu nome Obede. Este é o pai de Jessé, pai de Davi.",
      "<strong>COMENTÁRIO:</strong> 👑 'Obede' significa 'servo' ou 'adorador' - nome profético. 'A Noemi nasceu um filho' - o neto é considerado filho dela para efeito de perpetuação da linhagem (levirato). A ênfase final: Obede é avô de Davi. O livro conecta a história humilde de Rute à grande história da realeza de Israel. Uma moabita, marginalizada, torna-se ancestral do rei segundo o coração de Deus.",
      "📖 <strong>RESUMO:</strong> As vizinhas dão ao menino o nome de Obede; ele será pai de Jessé, pai do rei Davi.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Rute está na genealogia de Jesus (Mateus 1:5). A graça inclui estrangeiros e pecadores na linhagem do Salvador.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 18</strong></span>",
      "<strong>TEXTO:</strong> Estas são as gerações de Perez: Perez gerou a Hezrom;",
      "<strong>COMENTÁRIO:</strong> 📜 Início da genealogia de Perez a Davi (10 gerações). Perez (filho de Judá com Tamar) é o ponto de partida. As genealogias na Bíblia demonstram a fidelidade de Deus através das gerações, mesmo com irregularidades humanas.",
      "📖 <strong>RESUMO:</strong> Início da linhagem de Perez, incluindo Hezrom.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Mateus 1:3 também lista Perez na genealogia de Jesus, mostrando continuidade da promessa.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 19</strong></span>",
      "<strong>TEXTO:</strong> e Hezrom gerou a Rão; e Rão gerou a Aminadabe;",
      "<strong>COMENTÁRIO:</strong> Rão (ou Arã) e Aminadabe são antepassados de Davi. A genealogia salta gerações, selecionando os elos principais. O propósito não é histórico exaustivo, mas teológico.",
      "📖 <strong>RESUMO:</strong> Continuação genealógica: Hezrom gerou Rão, que gerou Aminadabe.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> A genealogia de Jesus (Lucas 3:33) inclui Aminadabe, confirmando a linhagem real.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 20</strong></span>",
      "<strong>TEXTO:</strong> e Aminadabe gerou a Naassom; e Naassom gerou a Salmom;",
      "<strong>COMENTÁRIO:</strong> Naassom foi líder da tribo de Judá no Êxodo (Números 1:7). Salmom é tradicionalmente identificado como o pai de Boaz (cf. Mateus 1:5). As ligações tecem a tapeçaria da redenção.",
      "📖 <strong>RESUMO:</strong> Naassom gerou Salmom, que dá sequência à linhagem.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> A fidelidade de Deus através do Êxodo até a monarquia é demonstrada.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 21</strong></span>",
      "<strong>TEXTO:</strong> e Salmom gerou a Boaz; e Boaz gerou a Obede;",
      "<strong>COMENTÁRIO:</strong> 🔗 Boaz é explicitamente ligado a Salmom. A linhagem chega ao nosso protagonista. Boaz gerou Obede, cumprindo o propósito do resgate. A história pessoal torna-se parte da história de salvação.",
      "📖 <strong>RESUMO:</strong> Salmom gerou Boaz; Boaz gerou Obede.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Boaz é antepassado de Jesus (Mateus 1:5). Seu hesed prefigura o hesed de Cristo.",
      
      "<span style='font-size: 15px;'><strong>VERSÍCULO: 22</strong></span>",
      "<strong>TEXTO:</strong> e Obede gerou a Jessé; e Jessé gerou a Davi.",
      "<strong>COMENTÁRIO:</strong> 👑 O clímax: Davi, o grande rei de Israel, o homem segundo o coração de Deus. O livro de Rute, que começou com fome, morte e amargura, termina com esperança messiânica. Pois Davi é tipo de Cristo, o Filho de Davi, o Redentor definitivo. A moabita Rute está na linhagem do Salvador. Assim, a graça triunfa sobre a maldição, o estrangeiro é acolhido, o vazio é preenchido, a amargura se torna doçura, e a história de uma família humilde se entrelaça com a história da redenção mundial.",
      "📖 <strong>RESUMO:</strong> Obede gerou Jessé; Jessé gerou Davi, o grande rei de Israel.",
      "✝️ <strong>CONEXÃO BÍBLICA:</strong> Jesus Cristo, o Filho de Davi (Mateus 1:1), é o último e maior Redentor, que resgata não apenas uma herança terrena, mas todo o Seu povo do pecado e da morte. A história de Rute aponta para a graça radical de Deus que acolhe os marginalizados e os insere na linhagem da salvação. ✝️",

      "<p style='font-size: 0.8rem; text-align: center;'><i><strong>Reflexão Final do Capítulo 4</strong></i></p><p style='font-size: 0.55rem;'>O capítulo 4 é a consumação da redenção. Boaz, agindo com justiça e transparência na porta da cidade (o tribunal de Israel), convoca o parente mais próximo e dez anciãos como testemunhas. O parente anônimo, disposto a resgatar a terra, recusa-se quando descobre que o resgate inclui casar-se com Rute e perpetuar o nome do falecido, temendo prejudicar sua própria herança. Boaz então assume o papel de go'el (remidor), casa-se com Rute, e Deus concede a ela um filho, Obede. A comunidade abençoa a união, comparando Rute a Raquel e Lia, e desejando que sua casa seja como a de Pérez (ancestral de Davi). O livro termina com uma genealogia que conecta Obede a Davi e, através de Mateus 1, a Jesus Cristo. A história que começou com uma viúva amargurada e uma estrangeira marginalizada termina com o nascimento do avô do maior rei de Israel, e prenuncia o nascimento do Rei dos reis. A mensagem final é a da graça radical de Deus: uma moabita (povo amaldiçoado) é incorporada à linhagem messiânica, o vazio é preenchido, a amargura se transforma em doçura. O hesed (amor leal) de Rute e Boaz é recompensado, e Deus demonstra que nenhum estrangeiro está fora dos seus planos de redenção. O livro de Rute é um prelúdio do evangelho: Cristo é nosso Boaz, que nos resgata da nossa condição de estrangeiros e nos traz para a família de Deus.</p>",

      "<p style='font-size: 1rem; text-align: center;'><i><strong>RESUMO FINAL DE RUTE</strong></i></p>",
      "<p style='font-size: 0.6rem;'>Rute é um belo relato de lealdade, amor e redenção. Uma moabita, viúva, escolhe acompanhar sua sogra Noemi até Belém, abandonando seus deuses e sua terra para servir ao Deus de Israel. Ela se casa com Boaz, um parente remidor, e torna-se bisavó do rei Davi.</p>",
      "<p style='font-size: 0.6rem;'>O livro mostra a graça de Deus acolhendo os gentios que se voltam para Ele, e a provisão divina por meio do casamento-redenção. Boaz é um tipo de Cristo, o Remidor que nos resgata.</p>",
      "<p style='font-size: 0.6rem;'>Rute é um farol de esperança em meio aos dias sombrios dos juízes.",
      "<p style='font-size: 0.7rem;'><strong>LIÇÕES PRINCIPAIS:</strong></p>",
      "<ul style='font-size: 0.6rem;'>",
      "  <li><strong>A lealdade e o amor são virtudes preciosas:</strong> Rute demonstra hesed (amor leal).</li>",
      "  <li><strong>Deus acolhe os que O buscam de coração:</strong> Rute, uma gentia, é incluída na linhagem de Davi e de Cristo.</li>",
      "  <li><strong>A redenção é um ato de amor e justiça:</strong> Boaz resgata Rute como parente remidor.</li>",
      "  <li><strong>Deus providencia nos momentos de dor:</strong> Noemi, que perdeu tudo, é restaurada.</li>",
      "  <li><strong>Cristo é nosso remidor:</strong> Assim como Boaz, Ele nos resgata da nossa condição de estrangeiros e órfãos.</li>",
      "</ul>",
      "<p style='font-size: 0.6rem;'>Que possamos, como Rute, abandonar tudo para seguir o Deus vivo, e descansar em Cristo, nosso divino Remidor.</p>"
    ]
  }
};