// volume/volume-90.js
window.LIVRO_DATA = {
    nome: "Volume XC",
    dados: [
        {
            termo: "01. Introdução: A Hospitalidade como Expressão do Amor de Cristo",
            definicao: "A hospitalidade (do grego philoxenia - 'amor ao estrangeiro') é uma virtude cristã fundamental. 'Não vos esqueçais da hospitalidade, porque por ela alguns, sem o saberem, hospedaram anjos' (Hebreus 13:2). 'Sendo hospitaleiros uns para com os outros, sem murmuração' (1 Pedro 4:9). 'Comunicai com os santos nas suas necessidades, segui a hospitalidade' (Romanos 12:13). A teologia reformada (Calvino, Kuyper) enfatiza a hospitalidade como expressão do amor de Cristo e como meio de edificação da igreja. Este volume explora: (1) A hospitalidade no Antigo e Novo Testamentos. (2) Cristo como modelo de hospitalidade. (3) Hospitalidade como evangelismo. (4) Hospitalidade e a igreja. (5) Hospitalidade e a família. (6) Desafios e práticas da hospitalidade. 'Abre a tua casa e o teu coração para o próximo' (Provérbios 3:27-28).",
            referencias: "Jó 31:32; Isaías 58:7; Mateus 25:35-40; Romanos 12:13; 1 Timóteo 3:2; Tito 1:8; Hebreus 13:2; 1 Pedro 4:9"
        },
        {
            termo: "02. Hospitalidade no Antigo Testamento - Abraão e Ló (Gênesis 18-19)",
            definicao: "O Antigo Testamento contém exemplos marcantes de hospitalidade. Abraão recebeu três visitantes (anjos) em sua tenda (Gênesis 18:1-15). 'E levantou os olhos, e olhou, e eis que três varões estavam em pé junto dele. E, vendo-os, correu da porta da tenda ao seu encontro, e inclinou-se à terra, e disse: Meu Senhor, se agora tenho achado graça aos teus olhos, rogo-te que não passes de teu servo' (Gênesis 18:2-3). Abraão ofereceu água, pão, bezerro, manteiga e leite. Ló também demonstrou hospitalidade em Sodoma (Gênesis 19:1-3). Exemplos adicionais: (1) Jó abria sua casa ao estrangeiro (Jó 31:32). (2) A sunamita hospedou Eliseu (2 Reis 4:8-10). (3) O estrangeiro era protegido pela lei (Levítico 19:33-34). (4) O amor ao estrangeiro era ordenado (Deuteronômio 10:18-19). (5) A hospitalidade era uma marca do justo. A teologia reformada (Calvino, Bavinck) vê na hospitalidade de Abraão um tipo da graça de Deus. 'Porque por ela alguns, sem o saberem, hospedaram anjos' (Hebreus 13:2).",
            referencias: "Gênesis 18:1-15; Gênesis 19:1-3; Jó 31:32; Isaías 58:7; 2 Reis 4:8-10; Levítico 19:33-34; Deuteronômio 10:18-19"
        },
        {
            termo: "03. Hospitalidade no Novo Testamento - Jesus e os Discípulos",
            definicao: "Jesus foi um exemplo de hospitalidade, acolhendo marginalizados, pecadores e estrangeiros. 'Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei' (Mateus 11:28). Ele comeu com publicanos e pecadores (Mateus 9:10-13). Ele recebeu crianças (Mateus 19:13-15). Ele acolheu a mulher samaritana (João 4:1-42). Ele recebeu Zaqueu em sua casa (Lucas 19:1-10). Ele lavou os pés dos discípulos (João 13:1-17). Ele prometeu lugar na casa do Pai (João 14:2-3). Os discípulos também praticaram hospitalidade: (1) Marta e Maria receberam Jesus (Lucas 10:38-42). (2) Lídia hospedou Paulo e seus companheiros (Atos 16:14-15,40). (3) Priscila e Áquila tinham igreja em sua casa (Romanos 16:3-5; 1 Coríndios 16:19). (4) Febe foi hospedeira de muitos (Romanos 16:1-2). (5) O bom samaritano foi um exemplo de hospitalidade (Lucas 10:30-37). (6) A viúva que hospedou Elias (1 Reis 17:8-24). A teologia reformada (Calvino, Bavinck) vê na hospitalidade de Jesus o modelo para a igreja. 'Como Cristo vos recebeu, recebei-vos uns aos outros' (Romanos 15:7).",
            referencias: "Mateus 9:10-13; Mateus 11:28; Lucas 10:38-42; Lucas 19:1-10; João 4:1-42; João 13:1-17; Atos 16:14-15; Romanos 15:7"
        },
        {
            termo: "04. Hospitalidade como Requisito para Líderes (1 Timóteo 3:2; Tito 1:8)",
            definicao: "A hospitalidade é um requisito para bispos (presbíteros) e diáconos. 'Convém, pois, que o bispo seja irrepreensível... dado à hospitalidade' (1 Timóteo 3:2). 'É necessário que o bispo seja... dado à hospitalidade' (Tito 1:7-8). A hospitalidade também é requisito para viúvas (1 Timóteo 5:10). Significados: (1) O líder deve ser hospitaleiro (abrir sua casa). (2) A hospitalidade é um sinal de maturidade espiritual. (3) A hospitalidade reflete o amor de Cristo. (4) A hospitalidade promove a comunhão. (5) A hospitalidade é um teste de caráter. (6) A hospitalidade é uma forma de ministério. (7) A hospitalidade edifica a igreja. (8) A hospitalidade é evangelismo. (9) A hospitalidade é um antídoto contra o egoísmo. (10) A hospitalidade é uma expressão do amor ao próximo. A teologia reformada (Calvino, Westminster) enfatiza a hospitalidade como qualificação essencial para líderes. 'Não deixando a nossa congregação, como é costume de alguns' (Hebreus 10:25).",
            referencias: "Atos 20:35; Romanos 12:13; 1 Timóteo 3:2; 1 Timóteo 5:10; Tito 1:7-8; Hebreus 13:16"
        },
        {
            termo: "05. Hospitalidade e Evangelismo - Abrindo o Lar para o Reino",
            definicao: "A hospitalidade é uma forma poderosa de evangelismo, abrindo o lar para o Reino. 'Sendo hospitaleiros uns para com os outros, sem murmuração' (1 Pedro 4:9). 'Comunicai com os santos nas suas necessidades, segui a hospitalidade' (Romanos 12:13). Como a hospitalidade evangeliza: (1) Mostra o amor de Cristo em ação. (2) Cria oportunidades para compartilhar o evangelho. (3) Demonstra a unidade da igreja. (4) Atrai os não-crentes. (5) Quebra barreiras culturais. (6) Cria amizades. (7) Oferece um ambiente seguro para perguntas. (8) Demonstra a alegria da salvação. (9) Mostra que os cristãos são diferentes. (10) Glorifica a Deus. Exemplos: (a) Lídia hospedou Paulo e sua equipe (Atos 16:14-15,40). (b) Priscila e Áquila hospedaram Apolo (Atos 18:26). (c) A mulher sunamita hospedou Eliseu (2 Reis 4:8-10). (d) Marta e Maria receberam Jesus (Lucas 10:38-42). (e) A igreja primitiva se reunia nas casas (Atos 2:46). (f) Paulo hospedou soldados e companheiros. Estratégias evangelísticas: (a) Jantares evangelísticos. (b) Estudos bíblicos em casa. (c) Grupos de oração. (d) Café e conversa. (e) Noites de jogos. (f) Churrascos. (g) Jantares temáticos. (h) Acolhimento de imigrantes. (i) Acolhimento de estudantes. (j) Acolhimento de pessoas em situação de rua. A teologia reformada (Kuyper, Schaeffer) incentiva a hospitalidade evangelística. 'Ide, ensinai todas as nações' (Mateus 28:19).",
            referencias: "Atos 2:46; Atos 16:14-15; Atos 18:26; Romanos 12:13; 1 Pedro 4:9; 3 João 1:5-8"
        },
        {
            termo: "06. Hospitalidade e a Igreja - Igreja em Casas (Atos 2:46; Romanos 16:5)",
            definicao: "A igreja primitiva se reunia em casas, praticando hospitalidade. 'E, perseverando unânimes todos os dias no templo, e partindo o pão em casa, comiam juntos com alegria e singeleza de coração' (Atos 2:46). 'Saúdai a igreja que está em sua casa' (Romanos 16:5). 'As igrejas da Ásia vos saúdam. Saúdam-vos afetuosamente no Senhor Áquila e Priscila, com a igreja que está em sua casa' (1 Coríndios 16:19). 'Saúdam-te os irmãos que estão em Laodiceia, e Ninfa, e a igreja que está em sua casa' (Colossenses 4:15). 'Saúda-te Epafras... e Marcos... e Lucas... e também a igreja que está em sua casa' (Filemom 1:23-24). A hospitalidade na igreja: (1) Pequenos grupos (células). (2) Cultos domésticos. (3) Estudos bíblicos em casa. (4) Grupos de oração. (5) Jantares de comunhão. (6) Acolhimento de visitantes. (7) Acolhimento de missionários. (8) Acolhimento de necessitados. (9) Acolhimento de novos membros. (10) Acolhimento de líderes. Benefícios: (a) Comunhão mais profunda. (b) Discipulado personalizado. (c) Evangelismo contextualizado. (d) Cuidado pastoral. (e) Unidade da igreja. (f) Crescimento espiritual. (g) Descentralização. (h) Acessibilidade. (i) Flexibilidade. (j) Intimidade. A teologia reformada (Calvino, Bavinck) valoriza a igreja em casa como complemento ao culto público. 'Não deixando a nossa congregação, como é costume de alguns' (Hebreus 10:25).",
            referencias: "Atos 2:46; Romanos 16:3-5; 1 Coríndios 16:19; Colossenses 4:15; Filemom 1:2; Hebreus 10:25"
        },
        {
            termo: "07. Hospitalidade e a Família - Abrindo o Lar para os Irmãos",
            definicao: "A família cristã deve ser uma casa aberta para a igreja e para os necessitados. 'A religião pura e imaculada para com Deus, o Pai, é esta: visitar os órfãos e as viúvas nas suas tribulações' (Tiago 1:27). 'E, quanto a vós, irmãos, rogo-vos que saudeis os irmãos com ósculo santo' (1 Tessalonicenses 5:26). A hospitalidade familiar: (1) Receber a família da igreja para refeições. (2) Hospedar missionários e pastores. (3) Acolher pessoas solitárias. (4) Cuidar de viúvas e órfãos. (5) Abrigar pessoas em crise (desemprego, doença). (6) Acolher imigrantes e refugiados. (7) Receber estudantes. (8) Acolher pessoas com deficiência. (9) Incluir pessoas excluídas. (10) Celebrar festas cristãs em família (Natal, Páscoa, Ação de Graças). Práticas: (a) Planejar refeições comunitárias. (b) Ter um quarto de hóspedes. (c) Ensinar os filhos a praticar hospitalidade. (d) Orar pelos convidados. (e) Compartilhar o evangelho naturalmente. (f) Ser sensível às necessidades. (g) Não se sobrecarregar (limites saudáveis). (h) Ser generoso, mas não desperdiçar. (i) Envolver a família toda. (j) Celebrar a diversidade. A teologia reformada (Kuyper, Bavinck) enfatiza a família como base da hospitalidade. 'Quanto a mim e à minha casa, serviremos ao Senhor' (Josué 24:15).",
            referencias: "Josué 24:15; Salmo 68:5-6; Isaías 58:7; Mateus 25:35-40; Tiago 1:27; 1 João 3:17-18"
        },
        {
            termo: "08. Hospitalidade e Missionários - Apoiando os Enviados (3 João 1:5-8)",
            definicao: "A hospitalidade aos missionários é uma forma de participar de sua obra. 'Amado, procedes fielmente em tudo o que fazes para com os irmãos, e para com os estranhos, os quais diante da igreja testificaram do teu amor; aos quais, se conduzires como é digno para com Deus, bem farás; porque por amor do Nome saíram, nada tomando dos gentios. Portanto, aos tais devemos receber, para que sejamos cooperadores da verdade' (3 João 1:5-8). Como hospedar missionários: (1) Oferecer hospedagem (quarto, refeições). (2) Oferecer transporte. (3) Oferecer apoio logístico (lavanderia, internet). (4) Oferecer encorajamento (oração, conversa). (5) Oferecer apoio financeiro (ofertas). (6) Oferecer descanso (férias missionárias). (7) Oferecer apoio médico (consultas, remédios). (8) Oferecer apoio educacional (escolas para filhos). (9) Oferecer apoio emocional (ouvir). (10) Oferecer apoio espiritual (oração, Bíblia). Benefícios: (a) Participar da obra missionária. (b) Receber bênçãos espirituais. (c) Fortalecer laços com missionários. (d) Aprender sobre missões. (e) Inspirar a família e a igreja. (f) Expandir o Reino de Deus. (g) Ser cooperador da verdade. A teologia reformada (Calvino, Kuyper) incentiva o apoio a missionários. 'Como, pois, invocarão aquele em quem não creram? e como crerão naquele de quem não ouviram? e como ouvirão, se não há quem pregue?' (Romanos 10:14).",
            referencias: "Romanos 10:14-15; 2 Coríndios 8:1-5; Filipenses 4:10-19; 3 João 1:5-8"
        },
        {
            termo: "09. Hospitalidade e Necessitados - Cuidando dos Pobres e Sofredores",
            definicao: "A hospitalidade aos pobres e necessitados é uma forma de servir a Cristo. 'Porque tive fome, e destes-me de comer; tive sede, e destes-me de beber; era estrangeiro, e recolhestes-me; estava nu, e vestistes-me; enfermo, e visitastes-me; preso, e fostes ver-me. Então os justos lhe responderão... Quando te vimos...? E, respondendo o Rei, lhes dirá: Em verdade vos digo que, quando o fizestes a um destes meus pequeninos irmãos, a mim o fizestes' (Mateus 25:35-40). Formas de hospitalidade aos necessitados: (1) Alimentar os famintos (comida, refeições). (2) Dar água aos sedentos. (3) Acolher estrangeiros (imigrantes, refugiados). (4) Vestir os nus (roupas). (5) Visitar os enfermos. (6) Visitar os presos. (7) Acolher órfãos e viúvas (Tiago 1:27). (8) Ajudar pessoas em situação de rua. (9) Ajudar pessoas com dependência química. (10) Ajudar vítimas de desastres. Princípios: (a) Agir com amor (1 Coríndios 13). (b) Agir com discrição (não humilhar). (c) Agir com sabedoria (não alimentar vícios). (d) Agir com generosidade (dar o melhor). (e) Agir com gratidão (servir a Cristo). (f) Agir com humildade (não se vangloriar). (g) Agir com oração. (h) Agir em parceria (igreja, organizações). (i) Agir com limites (não se sobrecarregar). (j) Agir com esperança (apontar para Cristo). A teologia reformada (Kuyper, Bavinck) enfatiza o cuidado aos pobres como dever cristão. 'Abre a tua mão ao teu irmão, ao teu necessitado' (Deuteronômio 15:11).",
            referencias: "Deuteronômio 15:11; Provérbios 19:17; Provérbios 22:9; Isaías 58:7; Mateus 25:31-46; Lucas 14:12-14; Tiago 1:27"
        },
        {
            termo: "10. Desafios da Hospitalidade - Limites, Recursos e Discernimento",
            definicao: "A hospitalidade enfrenta desafios práticos: falta de tempo, espaço, recursos financeiros, e discernimento para saber quem hospedar. 'Todas as coisas me são lícitas, mas nem todas as coisas convêm' (1 Coríndios 6:12). Desafios: (1) Falta de tempo (agenda lotada). (2) Falta de espaço (casa pequena). (3) Falta de recursos financeiros (dinheiro). (4) Falta de energia (cansaço). (5) Família resistente (cônjuges, filhos). (6) Convidados difíceis (exigentes, rudes). (7) Risco de abuso (aproveitadores). (8) Discernimento (quem hospedar). (9) Equilíbrio (não negligenciar a família). (10) Perfeccionismo (medo de não ser perfeito). Soluções: (a) Orar por discernimento (Tiago 1:5). (b) Estabelecer limites (não abrir mão da família). (c) Começar aos poucos (refeições simples). (d) Envolver a família. (e) Compartilhar tarefas (cada um contribui). (f) Planejar com antecedência. (g) Aceitar a imperfeição. (h) Buscar apoio da igreja. (i) Não se sobrecarregar (saber dizer não). (j) Confiar na providência de Deus (Filipenses 4:19). A teologia reformada (Calvino, Bavinck) incentiva a hospitalidade com sabedoria, não com imprudência. 'Sede, pois, prudentes como as serpentes e simples como as pombas' (Mateus 10:16).",
            referencias: "Provérbios 22:3; Mateus 10:16; 1 Coríndios 6:12; Gálatas 6:2; Efésios 5:15-16; Tiago 1:5; Filipenses 4:19"
        },
        {
            termo: "11. Hospitalidade e Discipulado - Formando Discípulos através da Mesa",
            definicao: "A hospitalidade é uma ferramenta poderosa para o discipulado. Jesus discipulou seus seguidores ao redor da mesa. 'E, estando à mesa com eles, tomou o pão, deu graças, partiu-o e deu-lho' (Lucas 24:30). 'E perseveravam na doutrina dos apóstolos, e na comunhão, e no partir do pão, e nas orações' (Atos 2:42). Como a mesa discipula: (1) Ensina amor ao próximo. (2) Ensina serviço (lavar pratos, servir). (3) Ensina generosidade. (4) Ensina paciência. (5) Ensina comunicação. (6) Ensina perdão. (7) Ensina humildade. (8) Ensina gratidão (orar antes das refeições). (9) Ensina comunhão. (10) Ensina evangelismo. Práticas discipuladoras: (a) Jantares com estudos bíblicos. (b) Almoços com discussões teológicas. (c) Cafés com oração. (d) Churrascos com comunhão. (e) Piqueniques com louvor. (f) Ceias com testemunhos. (g) Refeições com planejamento missionário. (h) Lanches com aconselhamento. (i) Brunch com discipulado de jovens. (j) Sobremesas com evangelismo. A teologia reformada (Kuyper, Bavinck) vê na mesa um lugar de formação de caráter. 'Tudo o que fizerdes, fazei-o de coração, como ao Senhor' (Colossenses 3:23).",
            referencias: "Atos 2:42; Lucas 24:30-31; Romanos 12:1-2; 1 Coríndios 10:31; Colossenses 3:23"
        },
        {
            termo: "12. A Promessa da Hospitalidade - Recompensa Eterna (Mateus 10:40-42)",
            definicao: "A hospitalidade será recompensada por Cristo. 'Quem vos recebe a vós, a mim me recebe; e quem me recebe a mim, recebe aquele que me enviou' (Mateus 10:40). 'E qualquer que tiver dado só que seja um copo de água fria a um destes pequeninos, em nome de discípulo, em verdade vos digo que não perderá o seu galardão' (Mateus 10:42). 'Então os justos lhe responderão... Quando te vimos...? E, respondendo o Rei, lhes dirá: Em verdade vos digo que, quando o fizestes a um destes meus pequeninos irmãos, a mim o fizestes' (Mateus 25:37-40). Promessas: (1) Receber a Cristo (Mateus 10:40). (2) Receber o Pai (Mateus 10:40). (3) Galardão (Mateus 10:41-42). (4) Herança do Reino (Mateus 25:34). (5) Bênção de Abraão (Gênesis 12:3). (6) Alegria eterna (Mateus 25:21). (7) Reconhecimento público (Mateus 25:31-46). (8) Tesouros no céu (Mateus 6:20). (9) Vida eterna (João 3:16). (10) Glória (Romanos 8:18). A teologia reformada (Calvino, Edwards) vê na hospitalidade um investimento eterno. 'Não ajunteis tesouros na terra... mas ajuntai tesouros no céu' (Mateus 6:19-20).",
            referencias: "Mateus 6:19-20; Mateus 10:40-42; Mateus 25:31-46; Lucas 6:38; 2 Coríndios 9:6-8; Gálatas 6:9-10"
        },
        {
            termo: "13. Síntese: Hospitalidade para a Glória de Cristo",
            definicao: "A hospitalidade cristã tem como objetivo final a glória de Cristo. 'Portanto, quer comais quer bebais, ou façais outra qualquer coisa, fazei tudo para glória de Deus' (1 Coríndios 10:31). Resumo da teologia da hospitalidade: (1) A hospitalidade é uma virtude cristã fundamental (Hebreus 13:2). (2) Abraão e Ló foram exemplos de hospitalidade (Gênesis 18-19). (3) Jesus foi o modelo de hospitalidade (Mateus 11:28). (4) A hospitalidade é requisito para líderes (1 Timóteo 3:2). (5) A hospitalidade evangeliza (Romanos 12:13). (6) A igreja se reunia em casas (Atos 2:46). (7) A família deve ser hospitaleira (Josué 24:15). (8) Os missionários devem ser acolhidos (3 João 1:5-8). (9) Os necessitados devem ser cuidados (Mateus 25:35-40). (10) A hospitalidade enfrenta desafios, mas deve ser praticada com sabedoria (Mateus 10:16). (11) A mesa discipula (Atos 2:42). (12) A hospitalidade será recompensada (Mateus 10:42). (13) Toda hospitalidade deve ser para a glória de Cristo (1 Coríndios 10:31). 'E tudo quanto fizerdes, por palavra ou por obra, fazei-o em nome do Senhor Jesus, dando por ele graças a Deus Pai' (Colossenses 3:17). Soli Deo Gloria!",
            referencias: "Romanos 11:36; 1 Coríndios 10:31; Colossenses 3:17; Hebreus 13:16; 1 Pedro 4:9-11"
        }
    ]
};