// volume/volume-69.js
window.LIVRO_DATA = {
    nome: "Volume LXIX",
    dados: [
        {
            termo: "01. Introdução: A História da Redenção Centrada em Cristo",
            definicao: "A história da redenção (Heilsgeschichte - 'história da salvação' em alemão) é a narrativa bíblica dos atos redentores de Deus, culminando em Jesus Cristo. A teologia reformada (Geerhardus Vos, Herman Ridderbos, Meredith Kline) enfatiza que a história não é um ciclo sem sentido, mas uma história teleológica (direcionada para um fim) centrada em Cristo. 'Havendo Deus antigamente falado muitas vezes e de muitas maneiras pelos profetas, a nós falou-nos nestes últimos dias pelo Filho' (Hebreus 1:1-2). 'E, quando chegou a plenitude do tempo, Deus enviou seu Filho' (Gálatas 4:4). 'Fazendo-nos conhecer o mistério da sua vontade, segundo o seu beneplácito, que propusera em si mesmo, de tornar a congregar em Cristo todas as coisas' (Efésios 1:9-10). Este volume explora a história da redenção desde a criação até a consumação, com Cristo como o centro. 'E, começando por Moisés e por todos os profetas, explicava-lhes o que dele se achava em todas as Escrituras' (Lucas 24:27).",
            referencias: "Gênesis 1-3; Lucas 24:27; Lucas 24:44; Gálatas 4:4; Efésios 1:9-10; Colossenses 1:15-20; Hebreus 1:1-2; 1 Pedro 1:10-12"
        },
        {
            termo: "02. A Criação - O Princípio da História (Gênesis 1-2)",
            definicao: "A história da redenção começa com a criação. Deus criou o universo 'no princípio' (Gênesis 1:1). Cristo é o Criador: 'Todas as coisas foram feitas por ele, e sem ele nada do que foi feito se fez' (João 1:3). 'Porque nele foram criadas todas as coisas que há nos céus e na terra' (Colossenses 1:16). A criação é a obra de Cristo e o palco da história da redenção. Aspectos da criação: (1) Criação do mundo (Gênesis 1:1-25). (2) Criação do homem à imagem de Deus (Gênesis 1:26-27). (3) O mandato de domínio (Gênesis 1:28). (4) O descanso de Deus (Gênesis 2:2-3). (5) A aliança da criação (Gênesis 2:15-17). (6) A criação da mulher (Gênesis 2:18-25). A criação é 'muito boa' (Gênesis 1:31) - tipo da nova criação em Cristo. A teologia reformada (Calvino, Kuyper) vê na criação o fundamento da redenção. 'Pela fé, entendemos que os mundos pela palavra de Deus foram criados; de maneira que aquilo que se vê não foi feito do que é aparente' (Hebreus 11:3).",
            referencias: "Gênesis 1-2; João 1:1-3; Colossenses 1:15-17; Hebreus 1:2-3; Hebreus 11:3; Apocalipse 4:11"
        },
        {
            termo: "03. A Queda - A Ruptura da História (Gênesis 3)",
            definicao: "A queda de Adão e Eva introduziu o pecado, a morte e a maldição na história. 'Pelo que, como por um homem entrou o pecado no mundo, e pelo pecado a morte, assim também a morte passou a todos os homens, por isso que todos pecaram' (Romanos 5:12). Consequências da queda: (1) Separação de Deus (Gênesis 3:8-10). (2) Morte espiritual (Efésios 2:1-3). (3) Morte física (Gênesis 3:19). (4) Maldição sobre a criação (Gênesis 3:17-19). (5) Inimizade entre a semente da mulher e a semente da serpente (Gênesis 3:15). (6) Expulsão do jardim (Gênesis 3:23-24). (7) A corrupção de toda a humanidade (Romanos 3:10-18). O proto-evangelho (Gênesis 3:15) é a primeira promessa da redenção. 'E porei inimizade entre ti e a mulher, e entre a tua semente e a sua semente; esta te ferirá a cabeça, e tu lhe ferirás o calcanhar' (Gênesis 3:15). A teologia reformada (Calvino, Bavinck) ensina que a queda tornou necessária a redenção em Cristo. 'Porque o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna em Cristo Jesus, nosso Senhor' (Romanos 6:23).",
            referencias: "Gênesis 3:1-24; Romanos 3:10-18; Romanos 5:12-21; Romanos 6:23; Efésios 2:1-3; Colossenses 2:13-15; 1 Coríndios 15:21-22"
        },
        {
            termo: "04. As Alianças - A Estrutura da História da Redenção",
            definicao: "Deus estabeleceu alianças (covenants) com seu povo como a estrutura da história da redenção. As principais alianças: (1) Aliança da Criação (Adão) - condicional (Gênesis 2:15-17). (2) Aliança com Noé - incondicional (Gênesis 9:8-17). (3) Aliança com Abraão - incondicional (Gênesis 12:1-3; 15:1-21; 17:1-27). (4) Aliança com Moisés (Sinai) - condicional (Êxodo 19-24). (5) Aliança com Davi - incondicional (2 Samuel 7:12-16). (6) Nova Aliança - inaugurada por Cristo (Jeremias 31:31-34; Lucas 22:20). A teologia reformada (Westminster, Kline) desenvolveu a teologia da aliança. 'Farei uma aliança de paz com eles, aliança eterna será com eles' (Ezequiel 37:26). 'Este é o meu sangue, o sangue do novo testamento, que por muitos é derramado para remissão dos pecados' (Mateus 26:28). 'Pelo que também ele é o Mediador de uma melhor aliança' (Hebreus 8:6).",
            referencias: "Gênesis 2:15-17; Gênesis 9:8-17; Gênesis 12:1-3; Gênesis 15:1-21; Gênesis 17:1-27; Êxodo 19-24; 2 Samuel 7:12-16; Jeremias 31:31-34; Mateus 26:28; Lucas 22:20; Hebreus 8:6-13; Hebreus 12:24"
        },
        {
            termo: "05. Adão e o Segundo Adão - O Cabeça da Humanidade (Romanos 5:12-21)",
            definicao: "Adão é o 'primeiro Adão' e Cristo é o 'segundo Adão' (ou 'último Adão'). 'Assim como por um homem entrou o pecado no mundo... assim também por um só homem, Jesus Cristo, a graça' (Romanos 5:15). 'Porque, assim como todos morrem em Adão, assim também todos serão vivificados em Cristo' (1 Coríndios 15:22). 'O primeiro homem, Adão, foi feito em alma vivente; o último Adão, em espírito vivificante' (1 Coríndios 15:45). O paralelo e contraste entre Adão e Cristo: (1) Adão trouxe pecado e morte; Cristo trouxe justiça e vida. (2) Adão desobedeceu na árvore; Cristo obedeceu na árvore da cruz. (3) Adão foi criado do pó; Cristo é o Senhor do céu. (4) Adão nos representou na queda; Cristo nos representa na redenção. A teologia reformada (Calvino, Owen) vê em Adão o 'cabeça federal' da humanidade caída, e em Cristo o 'cabeça federal' da nova criação. 'Pela desobediência de um só homem, muitos foram feitos pecadores, assim também pela obediência de um, muitos serão feitos justos' (Romanos 5:19).",
            referencias: "Gênesis 1:26-28; Gênesis 3:1-24; Romanos 5:12-21; 1 Coríndios 15:21-22; 1 Coríndios 15:45-49; Filipenses 2:5-11"
        },
        {
            termo: "06. Abraão - O Pai da Fé e a Semente Prometida (Gênesis 12-22)",
            definicao: "Abraão é o pai da fé, e a promessa feita a ele aponta para Cristo. 'Em ti serão benditas todas as famílias da terra' (Gênesis 12:3). 'Ora, as promessas foram feitas a Abraão e à sua semente. Não diz: E às sementes, como falando de muitos, mas como de um só: E à tua semente, que é Cristo' (Gálatas 3:16). 'Abraão, vosso pai, exultou por ver o meu dia, e viu-o, e alegrou-se' (João 8:56). A história de Abraão inclui: (1) O chamado (Gênesis 12:1-4). (2) A promessa de uma semente (Gênesis 15:1-6). (3) O nascimento de Isaque (Gênesis 21:1-7). (4) O sacrifício de Isaque (Gênesis 22:1-18) - tipo da morte de Cristo. (5) A intercessão por Sodoma (Gênesis 18:22-33) - tipo da intercessão de Cristo. A teologia reformada vê em Abraão o pai de todos os que creem em Cristo (Romanos 4:11-12). 'Abrão creu em Deus, e isso lhe foi imputado como justiça' (Gênesis 15:6; Romanos 4:3).",
            referencias: "Gênesis 12:1-3; Gênesis 15:1-6; Gênesis 22:1-18; João 8:56; Romanos 4:1-25; Gálatas 3:6-29; Hebreus 11:8-19"
        },
        {
            termo: "07. Moisés e o Êxodo - A Libertação e a Lei (Êxodo 1-24)",
            definicao: "O êxodo do Egito é o grande tipo da redenção em Cristo. Israel foi libertado da escravidão do Egito (tipo do pecado) pelo sangue do cordeiro pascal (tipo de Cristo). 'Cristo, nossa Páscoa, foi sacrificado por nós' (1 Coríndios 5:7). O êxodo inclui: (1) As pragas do Egito (Êxodo 7-12). (2) O cordeiro pascal (Êxodo 12:1-28). (3) A travessia do Mar Vermelho (Êxodo 14) - tipo do batismo (1 Coríndios 10:1-2). (4) O maná (Êxodo 16) - tipo de Cristo, o pão da vida (João 6:31-35). (5) A rocha ferida (Êxodo 17) - tipo de Cristo (1 Coríndios 10:4). (6) A lei no Sinai (Êxodo 19-24) - a lei é o pedagogo para Cristo (Gálatas 3:24). (7) O tabernáculo (Êxodo 25-40) - tipo do corpo de Cristo (João 2:19-21). A teologia reformada (Calvino) vê no êxodo o grande ato redentor do Antigo Testamento, prefigurando a redenção em Cristo. 'E Moisés disse ao povo: Lembrai-vos deste mesmo dia, em que saístes do Egito, da casa da servidão' (Êxodo 13:3).",
            referencias: "Êxodo 1-40; João 6:31-35; 1 Coríndios 5:7; 1 Coríndios 10:1-4; Gálatas 3:24; Colossenses 2:11-12; Hebreus 3:1-6"
        },
        {
            termo: "08. Davi e a Aliança Davídica - O Rei Eterno (2 Samuel 7)",
            definicao: "A aliança davídica promete um descendente de Davi que reinaria para sempre. 'Quando teus dias forem completos... então farei levantar depois de ti a tua posteridade... e estabelecerei o seu reino. Este edificará uma casa ao meu nome, e eu firmarei o trono do seu reino para sempre' (2 Samuel 7:12-13). Cumprimento em Cristo: 'O Senhor Deus lhe dará o trono de Davi, seu pai; e reinará para sempre na casa de Jacó, e o seu reino não terá fim' (Lucas 1:32-33). Jesus é o 'Filho de Davi' (Mateus 1:1). O reinado de Davi prefigura o reinado de Cristo: (1) Davi foi ungido rei; Cristo é o Ungido (Messias). (2) Davi derrotou Golias (tipo de Satanás); Cristo derrotou o pecado, a morte e o diabo. (3) Davi foi pastor; Cristo é o Bom Pastor. (4) Davi escreveu salmos messiânicos (Sl 22; 110). (5) Davi foi um rei guerreiro; Cristo é o Rei dos reis. A teologia reformada vê em Davi o tipo do rei messiânico, e em Cristo o cumprimento da aliança davídica. 'O Senhor jurou a Davi com verdade, e não se apartará dela: Do fruto do teu ventre assentarei sobre o teu trono' (Salmo 132:11).",
            referencias: "2 Samuel 7:12-16; 1 Crônicas 17:11-14; Salmo 2; Salmo 110; Salmo 132:11; Isaías 9:6-7; Jeremias 23:5-6; Lucas 1:32-33; Atos 2:30-31"
        },
        {
            termo: "09. O Exílio e o Retorno - O Julgamento e a Esperança (2 Reis 25; Esdras 1-6)",
            definicao: "O exílio babilônico (586 a.C.) foi o julgamento de Deus sobre Israel por seu pecado. O templo foi destruído, e o povo foi levado para a Babilônia. O retorno (538 a.C.) foi a restauração sob Ciro, Zorobabel, Esdras e Neemias. O exílio tipifica: (1) O julgamento de Deus sobre o pecado - Cristo sofreu o juízo em nosso lugar. (2) A separação de Deus - Cristo reconciliou o mundo com Deus. (3) A necessidade de arrependimento - Cristo chama ao arrependimento. (4) A esperança da restauração - Cristo restaura o relacionamento com Deus. O retorno tipifica: (1) A redenção de Cristo. (2) A reconstrução do templo - Cristo é o verdadeiro templo (João 2:19-21). (3) A restauração da adoração - Cristo é o mediador da verdadeira adoração. (4) A esperança escatológica - a nova Jerusalém. A teologia reformada vê no exílio o tipo do juízo que Cristo sofreu, e no retorno o tipo da redenção em Cristo. 'E vos levarei para a Babilônia, e ali vos livrarei' (Ezequiel 36:24).",
            referencias: "2 Reis 25:1-21; 2 Crônicas 36:17-23; Esdras 1-6; Neemias 1-13; Jeremias 25:8-14; Ezequiel 36:24-28; Isaías 40:1-5; Lucas 21:24; João 2:19-21"
        },
        {
            termo: "10. A Primeira Vinda de Cristo - O Centro da História",
            definicao: "A primeira vinda de Cristo (encarnação, vida, morte, ressurreição, ascensão) é o centro da história da redenção. 'Mas, vindo a plenitude dos tempos, Deus enviou seu Filho' (Gálatas 4:4). 'Havendo Deus antigamente falado muitas vezes e de muitas maneiras pelos profetas, a nós falou-nos nestes últimos dias pelo Filho' (Hebreus 1:1-2). Eventos da primeira vinda: (1) Encarnação (João 1:14). (2) Vida e ministério (Mateus 4-25). (3) Crucificação (Mateus 27). (4) Ressurreição (Mateus 28; 1 Coríndios 15). (5) Ascensão (Atos 1:9-11). (6) Derramamento do Espírito (Pentecostes, Atos 2). A primeira vinda inaugura o 'último dia' (João 6:39-40; 11:24). A teologia reformada (Ridderbos, Vos) enfatiza que a primeira vinda é o cumprimento das promessas do Antigo Testamento. 'E, quando ouvisseis que Cristo viria, creio que ele é aquele que há de vir? Sim, é ele mesmo, que há de vir? Jesus disse-lhe: Eu sou o que falo contigo' (João 4:25-26).",
            referencias: "Mateus 1-28; João 1:1-18; Gálatas 4:4-5; Efésios 1:3-14; Filipenses 2:5-11; Colossenses 1:15-20; 1 Timóteo 3:16; Tito 2:11-14; Hebreus 1:1-4; 1 Pedro 1:18-21; 1 João 4:9-10"
        },
        {
            termo: "11. A Era da Igreja - O Tempo entre as Vindas (Atos 1 - Apocalipse 19)",
            definicao: "Após a ascensão de Cristo, a igreja vive na era entre a primeira e a segunda vinda. Esta é a era do Espírito Santo, da pregação do evangelho, e da expansão do reino. 'E este evangelho do reino será pregado em todo o mundo, em testemunho a todas as nações, e então virá o fim' (Mateus 24:14). 'Eis que estou convosco todos os dias, até à consumação do século' (Mateus 28:20). Características da era da igreja: (1) O Espírito Santo é derramado (Atos 2:1-4). (2) O evangelho é pregado a todas as nações (Atos 1:8; Romanos 10:14-15). (3) A igreja é edificada (Efésios 4:11-16). (4) Os dons espirituais são dados (1 Coríndios 12:4-11). (5) O fruto do Espírito é produzido (Gálatas 5:22-23). (6) A igreja sofre perseguição (João 15:20; 2 Timóteo 3:12). (7) A igreja aguarda a volta de Cristo (Tito 2:13). A teologia reformada (Calvino, Bavinck) vê na era da igreja o tempo da colheita do evangelho. 'E eis que eu estou convosco todos os dias, até à consumação do século' (Mateus 28:20).",
            referencias: "Atos 1-28; Romanos 10:14-15; Efésios 4:11-16; Colossenses 1:28-29; 1 Tessalonicenses 4:13-18; 2 Pedro 3:8-13; Apocalipse 2-3"
        },
        {
            termo: "12. A Segunda Vinda de Cristo - A Consumação da História",
            definicao: "A segunda vinda de Cristo (parusia) é a consumação da história da redenção. 'Este Jesus... há de vir assim como para o céu o vistes ir' (Atos 1:11). 'Porque o Senhor mesmo descerá do céu com alarido, e com voz de arcanjo, e com a trombeta de Deus' (1 Tessalonicenses 4:16). Eventos da segunda vinda: (1) A ressurreição dos mortos (João 5:28-29; 1 Coríndios 15:20-23). (2) O juízo final (Mateus 25:31-46; Apocalipse 20:11-15). (3) A derrota final de Satanás (Apocalipse 20:10). (4) O fim da morte (1 Coríndios 15:26). (5) A nova criação (Apocalipse 21-22). (6) A entrega do reino ao Pai (1 Coríndios 15:24-28). (7) A consumação da salvação (Romanos 8:19-23). A teologia reformada (Calvino, Berkhof) vê na segunda vinda a esperança consumada da igreja. 'Aguardando a bem-aventurada esperança e o aparecimento da glória do grande Deus e nosso Salvador Jesus Cristo' (Tito 2:13). 'Ora vem, Senhor Jesus' (Apocalipse 22:20).",
            referencias: "Daniel 7:13-14; Zacarias 14:1-5; Mateus 24-25; Atos 1:11; Filipenses 3:20-21; 1 Tessalonicenses 4:13-18; 2 Tessalonicenses 1:5-10; Tito 2:13; Hebreus 9:28; 2 Pedro 3:10-13; Apocalipse 1:7; Apocalipse 19-22"
        },
        {
            termo: "13. Síntese: Cristo, o Alfa e o Ômega da História",
            definicao: "Cristo é o Alfa e o Ômega, o princípio e o fim da história da redenção. 'Eu sou o Alfa e o Ômega, o princípio e o fim, diz o Senhor, que é, e que era, e que há de vir, o Todo-Poderoso' (Apocalipse 1:8). 'Eu sou o primeiro e o último; e o que vivo e fui morto, mas eis aqui estou vivo para todo o sempre' (Apocalipse 1:17-18). Resumo da história da redenção: (1) Criação: Cristo é o Criador (João 1:3). (2) Queda: Cristo é prometido como Redentor (Gênesis 3:15). (3) Alianças: Cristo é o Mediador da nova aliança (Hebreus 8:6). (4) Abraão: Cristo é a semente prometida (Gálatas 3:16). (5) Moisés e o Êxodo: Cristo é o Cordeiro Pascal (1 Coríndios 5:7). (6) Davi: Cristo é o Filho de Davi (Mateus 1:1). (7) Exílio e retorno: Cristo é o Restaurador (Lucas 4:18-19). (8) Primeira vinda: Cristo é o centro da história (Gálatas 4:4). (9) Era da igreja: Cristo está com a igreja (Mateus 28:20). (10) Segunda vinda: Cristo consuma a história (Apocalipse 22:20). 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36). Soli Deo Gloria!",
            referencias: "Romanos 11:36; Gálatas 4:4; Efésios 1:9-10; Colossenses 1:15-20; Hebreus 1:1-4; Apocalipse 1:8; Apocalipse 1:17-18; Apocalipse 22:13; Apocalipse 22:20-21"
        }
    ]
};