// volume/volume-15.js
window.LIVRO_DATA = {
    nome: "Volume XV",
    dados: [
        {
            termo: "01. Introdução: A Cristologia como Fonte da Espiritualidade Cristã",
            definicao: "A espiritualidade cristã é a vida vivida em comunhão com Deus, por meio de Jesus Cristo, no poder do Espírito Santo. A teologia reformada enfatiza que a verdadeira espiritualidade não é escapista (mundo mau), nem legalista (obras para ganhar salvação), nem emocionalista (experiências subjetivas), mas cristocêntrica (centrada em Cristo). 'Porque para mim o viver é Cristo' (Filipenses 1:21). 'Já estou crucificado com Cristo; e vivo, não mais eu, mas Cristo vive em mim' (Gálatas 2:20). A espiritualidade cristocêntrica tem como fundamentos: (a) A união com Cristo (unio cum Christo) - os crentes estão 'em Cristo' (Romanos 8:1). (b) A imitação de Cristo (imitatio Christi) - os crentes andam como ele andou (1 João 2:6). (c) A conformação a Cristo (conformatio Christi) - os crentes são transformados à sua imagem (Romanos 8:29). (d) A presença de Cristo - Cristo prometeu estar com os seus (Mateus 28:20). Este volume explora a aplicação prática da cristologia na vida devocional: oração, leitura da Bíblia, santificação, cruz, esperança, etc.",
            referencias: "Mateus 11:28-30; João 14:6; João 15:1-5; Romanos 6:1-14; Romanos 8:1-4; Romanos 8:29; Gálatas 2:20; Efésios 1:3-14; Filipenses 1:21; Filipenses 3:7-14; Colossenses 3:1-4; 1 Pedro 2:21-25; 1 João 2:6"
        },
        {
            termo: "02. União com Cristo (Unio cum Christo)",
            definicao: "A união com Cristo (unio cum Christo) é a doutrina central da espiritualidade reformada. Os crentes estão 'em Cristo' (Romanos 8:1; 2 Coríntios 5:17; Efésios 1:3-14). Esta união é: (a) Mística (não física, não local, mas espiritual). (b) Real (não imaginária, não simbólica). (c) Pela fé (os crentes são unidos a Cristo pela fé). (d) Pelo Espírito Santo (o Espírito aplica a redenção e une os crentes a Cristo). (e) Indissolúvel (nada pode separar o crente do amor de Deus em Cristo, Romanos 8:38-39). Consequências da união com Cristo: (1) Justificação: os crentes são declarados justos por causa da justiça de Cristo imputada. (2) Santificação: os crentes são transformados à imagem de Cristo. (3) Adoção: os crentes tornam-se filhos de Deus em Cristo. (4) Vida eterna: os crentes têm a vida eterna em Cristo. (5) Glorificação: os crentes ressuscitarão com Cristo. A teologia reformada (Calvino, Westminster) enfatiza que a união com Cristo é a base de todos os benefícios da salvação. 'Aquele que se ajunta ao Senhor é um mesmo espírito' (1 Coríntios 6:17).",
            referencias: "João 14:20; João 15:1-5; Romanos 6:1-14; Romanos 8:1-4; Romanos 8:38-39; 1 Coríntios 6:17; 2 Coríntios 5:17; Gálatas 2:20; Efésios 1:3-14; Efésios 5:30; Colossenses 3:1-4; 1 Pedro 1:3-5; 1 João 4:13"
        },
        {
            termo: "03. Imitação de Cristo (Imitatio Christi)",
            definicao: "A imitação de Cristo (Imitatio Christi) é o chamado para seguir o exemplo de Jesus. 'Sede meus imitadores, como também eu sou de Cristo' (1 Coríntios 11:1). 'Porque para isto sois chamados, pois também Cristo padeceu por nós, deixando-nos o exemplo, para que sigais as suas pisadas' (1 Pedro 2:21). O que significa imitar Cristo? (1) Humildade: 'Aprendei de mim, que sou manso e humilde de coração' (Mateus 11:29). (2) Amor sacrificial: 'Como eu vos amei a vós, que também vós uns aos outros vos ameis' (João 13:34). (3) Perdão: 'Perdoai-vos uns aos outros, como também Deus vos perdoou em Cristo' (Efésios 4:32). (4) Obediência: 'Ele foi obediente até à morte' (Filipenses 2:8). (5) Paciência no sofrimento: 'Cristo padeceu por nós' (1 Pedro 2:21). (6) Serviço: 'O Filho do Homem não veio para ser servido, mas para servir' (Mateus 20:28). A imitação não é a causa da salvação (justificação), mas o fruto (santificação). 'A fé sem obras é morta' (Tiago 2:26). A obra clássica sobre o tema é 'Imitação de Cristo' (De Imitatione Christi) de Tomás de Kempis (c. 1380-1471 d.C.), valorizada pela tradição reformada (com ressalvas).",
            referencias: "Mateus 11:29; Mateus 20:28; João 13:34-35; Romanos 15:1-3; 1 Coríntios 11:1; Efésios 4:32; Efésios 5:1-2; Filipenses 2:5-8; Colossenses 3:12-14; 1 Tessalonicenses 1:6; 1 Pedro 2:21-25; 1 João 2:6; 1 João 3:16"
        },
        {
            termo: "04. A Oração Cristocêntrica",
            definicao: "A oração cristã é dirigida a Deus Pai, por meio de Jesus Cristo (o único Mediador), no Espírito Santo. 'Porque há um só Deus, e um só Mediador entre Deus e os homens, Jesus Cristo homem' (1 Timóteo 2:5). A oração deve ser feita 'em nome de Jesus' (João 14:13-14; 15:16; 16:23-24). Significa: (a) Orar com base nos méritos de Cristo (não nos nossos méritos). (b) Orar de acordo com a vontade de Cristo (revelada na Escritura). (c) Orar para a glória de Cristo. O exemplo de oração de Jesus: (1) O Pai Nosso (Mateus 6:9-13; Lucas 11:2-4) - o modelo de oração. (2) A oração sacerdotal (João 17:1-26) - Jesus ora por si mesmo, pelos discípulos e por todos os crentes. (3) A oração no Getsêmani (Mateus 26:36-46; Marcos 14:32-42; Lucas 22:39-46) - 'Pai, se queres, passa de mim este cálice; todavia não se faça a minha vontade, mas a tua'. A teologia reformada enfatiza que a oração é: (a) dirigida a Deus Pai; (b) por meio de Cristo; (c) no Espírito; (d) com confiança (Hebreus 4:16); (e) com perseverança (Lucas 18:1-8).",
            referencias: "Mateus 6:9-13; Lucas 11:2-4; João 14:13-14; João 15:16; João 16:23-24; João 17:1-26; Romanos 8:26-27; Romanos 8:34; Efésios 2:18; Efésios 3:12; Efésios 6:18; 1 Timóteo 2:5; Hebreus 4:14-16; Hebreus 7:25; 1 João 2:1-2"
        },
        {
            termo: "05. Leitura Cristocêntrica da Bíblia",
            definicao: "A Bíblia é o testemunho de Deus sobre Jesus Cristo. Jesus disse: 'Examinais as Escrituras... e são elas que de mim testificam' (João 5:39). Após sua ressurreição, Jesus explicou aos discípulos: 'E, começando por Moisés e por todos os profetas, explicava-lhes o que dele se achava em todas as Escrituras' (Lucas 24:27). 'São estas as palavras que vos disse, estando ainda convosco, que convinha que se cumprisse tudo o que de mim está escrito na lei de Moisés, e nos profetas e nos salmos' (Lucas 24:44). A leitura cristocêntrica da Bíblia significa: (1) Ver Cristo no Antigo Testamento (profecias, tipos, figuras). (2) Ver Cristo no Novo Testamento (evangelhos, epístolas, apocalipse). (3) Interpretar a Escritura à luz de Cristo (hermenêutica cristocêntrica). (4) Aplicar a Escritura à vida em Cristo. A teologia reformada (Calvino, Owen, Edwards) enfatiza a leitura cristocêntrica da Bíblia. 'Toda a Escritura é inspirada por Deus e útil para o ensino, para a repreensão, para a correção, para a instrução na justiça' (2 Timóteo 3:16-17).",
            referencias: "Lucas 24:27; Lucas 24:44-45; João 5:39; Atos 8:26-40; Atos 17:11; Romanos 15:4; 1 Coríntios 10:1-11; 2 Timóteo 3:14-17; Hebreus 4:12; 2 Pedro 1:19-21; 2 Pedro 3:15-16; Apocalipse 1:1-3"
        },
        {
            termo: "06. A Santificação e a Imagem de Cristo",
            definicao: "A santificação é o processo pelo qual os crentes são transformados à imagem de Cristo. 'Porque os que dantes conheceu, também os predestinou para serem conformes à imagem de seu Filho' (Romanos 8:29). 'E todos nós, com rosto descoberto, refletindo como um espelho a glória do Senhor, somos transformados de glória em glória na mesma imagem, como pelo Espírito do Senhor' (2 Coríntios 3:18). A santificação cristocêntrica significa: (1) A obra de Cristo é a base: Cristo morreu para nos santificar (Efésios 5:25-27). (2) O Espírito Santo aplica a santificação, unindo-nos a Cristo. (3) O crente participa ativamente: 'Operai a vossa salvação com temor e tremor; porque Deus é o que opera em vós tanto o querer como o executar, segundo a sua boa vontade' (Filipenses 2:12-13). (4) A santificação é progressiva, não perfeita nesta vida (o crente ainda luta contra o pecado, Romanos 7:14-25). (5) A santificação é completa na morte (alma) e na ressurreição (corpo). A teologia reformada enfatiza que a santificação é o fruto da justificação, não o meio. 'A fé sem obras é morta' (Tiago 2:26).",
            referencias: "Romanos 6:1-14; Romanos 7:14-25; Romanos 8:29; Romanos 12:1-2; 1 Coríntios 6:11; 2 Coríntios 3:18; Gálatas 5:22-25; Efésios 4:22-24; Efésios 5:25-27; Filipenses 2:12-13; Colossenses 3:1-10; Hebreus 12:14; 1 Pedro 1:13-16; 1 João 3:2-3"
        },
        {
            termo: "07. A Cruz como Caminho da Espiritualidade",
            definicao: "A teologia da cruz (theologia crucis) de Martinho Lutero afirma que o verdadeiro conhecimento de Deus é encontrado no sofrimento e humilhação de Cristo, não na glória e poder (theologia gloriae). 'A verdadeira teologia e conhecimento de Deus está em Cristo crucificado' (Heidelberg Disputation, 1518). Paulo escreveu: 'Longe esteja de mim gloriar-me, a não ser na cruz de nosso Senhor Jesus Cristo' (Gálatas 6:14). A espiritualidade da cruz significa: (1) Reconhecer que o sofrimento faz parte da vida cristã (2 Timóteo 3:12). (2) Aceitar as provações como disciplina de Deus (Hebreus 12:5-11). (3) Gloriar-se nas fraquezas, porque o poder de Cristo se aperfeiçoa na fraqueza (2 Coríntios 12:9-10). (4) Tomar a cruz diariamente: 'Se alguém quer vir após mim, negue-se a si mesmo, tome a sua cruz e siga-me' (Mateus 16:24). (5) Ter esperança na ressurreição: 'Porque para mim o viver é Cristo, e o morrer é ganho' (Filipenses 1:21).",
            referencias: "Mateus 10:38; Mateus 16:24; Lucas 9:23; Lucas 14:27; Romanos 5:3-5; 1 Coríntios 1:18-25; 2 Coríntios 4:7-12; 2 Coríntios 12:9-10; Gálatas 2:20; Gálatas 6:14; Filipenses 1:21; Filipenses 3:10; Colossenses 1:24; 2 Timóteo 3:12; 1 Pedro 4:12-19"
        },
        {
            termo: "08. A Eucaristia como Alimento Espiritual",
            definicao: "A Ceia do Senhor (Eucaristia) é um sacramento no qual os crentes participam do corpo e sangue de Cristo espiritualmente (presença espiritual, Calvino) ou oralmente (presença real, Lutero). Independentemente da posição, a Ceia é alimento espiritual para a alma. 'Tomei, comei; isto é o meu corpo' (Mateus 26:26). 'Bebei dele todos; porque isto é o meu sangue, o sangue do novo testamento' (Mateus 26:27-28). Significados: (1) Memorial: 'Fazei isto em memória de mim' (Lucas 22:19). (2) Comunhão com Cristo: 'O cálice de bênção que abençoamos, não é a comunhão do sangue de Cristo? O pão que partimos, não é a comunhão do corpo de Cristo?' (1 Coríntios 10:16). (3) Alimento espiritual: 'Quem come a minha carne e bebe o meu sangue permanece em mim, e eu nele' (João 6:56). (4) Unidade dos crentes: 'Nós, sendo muitos, somos um só pão e um só corpo' (1 Coríntios 10:17). (5) Antecipação da ceia celestial: 'Beberei convosco, novo, no reino de meu Pai' (Mateus 26:29). A teologia reformada (Calvino) enfatiza a presença espiritual: Cristo está verdadeiramente presente, mas espiritualmente (pelo Espírito Santo), não corporalmente.",
            referencias: "Mateus 26:26-29; Marcos 14:22-25; Lucas 22:19-20; João 6:51-58; 1 Coríntios 10:16-22; 1 Coríntios 11:23-34; Atos 2:42; Atos 20:7; Apocalipse 19:9"
        },
        {
            termo: "09. O Discipulado como Seguimento de Cristo",
            definicao: "Discipulado (mathetes) é o chamado para seguir a Cristo, aprender com ele e imitá-lo. 'Vinde após mim, e eu vos farei pescadores de homens' (Mateus 4:19). 'Se alguém quer vir após mim, negue-se a si mesmo, tome a sua cruz e siga-me' (Mateus 16:24). O discipulado envolve: (1) Arrependimento e fé: 'Arrependei-vos, e credes no evangelho' (Marcos 1:15). (2) Batismo: 'Portanto ide, ensinai todas as nações, batizando-as em nome do Pai, e do Filho, e do Espírito Santo' (Mateus 28:19). (3) Obediência aos mandamentos de Cristo: 'Se me amais, guardai os meus mandamentos' (João 14:15). (4) Crescimento espiritual: 'Crescei na graça e no conhecimento de nosso Senhor e Salvador Jesus Cristo' (2 Pedro 3:18). (5) Perseverança: 'Aquele que perseverar até ao fim será salvo' (Mateus 10:22). Dietrich Bonhoeffer, em 'O Custo do Discipulado' (1937), distingue 'fé barata' (sem obediência) de 'fé cara' (com obediência). A teologia reformada enfatiza que o discipulado é a resposta à justificação pela fé (santificação).",
            referencias: "Mateus 4:19; Mateus 10:38; Mateus 16:24; Mateus 28:18-20; Marcos 1:15; Lucas 9:23; Lucas 14:25-33; João 8:31-32; João 13:34-35; João 15:8; Atos 11:26; 2 Pedro 3:18; 1 João 2:6"
        },
        {
            termo: "10. A Esperança Escatológica como Âncora da Alma",
            definicao: "A esperança cristã é a expectativa da segunda vinda de Cristo (parusia), da ressurreição dos mortos e da nova criação. 'Aguardando a bem-aventurada esperança e o aparecimento da glória do grande Deus e nosso Salvador Jesus Cristo' (Tito 2:13). A esperança escatológica é uma 'âncora da alma' (Hebreus 6:19). Significados: (1) Consolação na tribulação: 'Porque a nossa leve e momentânea tribulação produz para nós um peso eterno de glória mui excelente' (2 Coríntios 4:17). (2) Motivação para a santificação: 'Todo aquele que nele tem esta esperança purifica-se a si mesmo, como também ele é puro' (1 João 3:3). (3) Motivação para o serviço: 'Portanto, meus amados irmãos, sede firmes e constantes, sempre abundantes na obra do Senhor' (1 Coríntios 15:58). (4) Consolação na morte: 'Porque, se cremos que Jesus morreu e ressuscitou, assim também aos que em Jesus dormem, Deus os tornará a trazer com ele' (1 Tessalonicenses 4:14). A teologia reformada enfatiza que a esperança não é mera ilusão, mas certeza baseada na ressurreição de Cristo.",
            referencias: "João 14:1-3; Romanos 8:18-25; 1 Coríntios 15:1-58; 2 Coríntios 4:16-18; 1 Tessalonicenses 4:13-18; Tito 2:11-14; Hebreus 6:19-20; 1 Pedro 1:3-9; 2 Pedro 3:10-13; 1 João 3:2-3; Apocalipse 21:1-8"
        },
        {
            termo: "11. A Devoção Pessoal a Cristo (Espiritualidade Cotidiana)",
            definicao: "A espiritualidade cristocêntrica não se limita à igreja (domingo), mas abrange toda a vida (todos os dias). 'Portanto, quer comais quer bebais, ou façais outra qualquer coisa, fazei tudo para glória de Deus' (1 Coríntios 10:31). 'E tudo quanto fizerdes, por palavra ou por obra, fazei-o em nome do Senhor Jesus, dando por ele graças a Deus Pai' (Colossenses 3:17). A devoção pessoal a Cristo inclui: (1) Leitura diária da Bíblia (com foco em Cristo). (2) Oração diária (em nome de Cristo). (3) Meditação em Cristo (Salmo 1:2; 119:97). (4) Ação de graças por Cristo (1 Tessalonicenses 5:18). (5) Serviço a Cristo (servir aos outros como a Cristo, Mateus 25:31-46). (6) Testemunho de Cristo (evangelismo). (7) Sofrimento por Cristo (2 Timóteo 3:12). A teologia reformada enfatiza que toda a vida é culto a Deus (coram Deo - 'diante de Deus'), e que Cristo é o centro de todas as atividades.",
            referencias: "Salmo 1:2; Salmo 119:97; Mateus 25:31-46; Lucas 9:23; João 15:1-8; Romanos 12:1-2; 1 Coríntios 10:31; Efésios 5:15-21; Filipenses 4:4-7; Colossenses 3:17; 1 Tessalonicenses 5:16-18; 2 Timóteo 3:12; Hebreus 13:15-16; 1 Pedro 2:9-12"
        },
        {
            termo: "12. A Comunhão dos Santos (Espiritualidade Comunitária)",
            definicao: "A espiritualidade cristã não é individualista (somente 'eu e Jesus'), mas comunitária (nós em Cristo). 'E perseveravam na doutrina dos apóstolos, e na comunhão, e no partir do pão, e nas orações' (Atos 2:42). A comunhão dos santos (koinōnia) inclui: (1) Unidade com Cristo (cabeça) e com os crentes (corpo). 'Porque, assim como o corpo é um e tem muitos membros, e todos os membros, sendo muitos, são um só corpo, assim é Cristo também' (1 Coríntios 12:12). (2) Partilha dos bens materiais (Atos 2:44-45; 4:32-35). (3) Partilha das alegrias e tristezas (Romanos 12:15). (4) Exortação mútua (Hebreus 10:24-25). (5) Perdão mútuo (Efésios 4:32). (6) Oração uns pelos outros (Tiago 5:16). A teologia reformada enfatiza que a igreja é o corpo de Cristo (Efésios 1:22-23; 4:15-16), e que a comunhão com os irmãos é expressão da comunhão com Cristo. 'Aquele que diz que está na luz e odeia a seu irmão, ainda está em trevas' (1 João 2:9-11).",
            referencias: "João 13:34-35; Atos 2:42-47; Romanos 12:4-5; Romanos 12:15; 1 Coríntios 10:16-17; 1 Coríntios 12:12-27; Efésios 4:1-6; Efésios 4:15-16; Efésios 4:32; Filipenses 2:1-4; Hebreus 10:24-25; 1 Pedro 4:8-11; 1 João 1:3-7; 1 João 3:14-18"
        },
        {
            termo: "13. Síntese: Viver para a Glória de Cristo",
            definicao: "A espiritualidade cristocêntrica reformada pode ser resumida como 'viver para a glória de Cristo' (Soli Deo Gloria). 'Portanto, quer comais quer bebais, ou façais outra qualquer coisa, fazei tudo para glória de Deus' (1 Coríntios 10:31). 'A fim de que, como está escrito: Quem se gloria, glorie-se no Senhor' (1 Coríntios 1:31). Significados: (1) Toda a vida é para a glória de Cristo (não para a glória própria). (2) A salvação é pela graça de Cristo (não por méritos humanos). (3) A fé em Cristo é o centro da vida (não as obras). (4) O amor a Cristo motiva o serviço (não o medo). (5) A esperança em Cristo consola nas tribulações. A teologia reformada resume a vida cristã em: (a) Coram Deo (diante de Deus). (b) In Christo (em Cristo). (c) Soli Deo Gloria (somente a Deus a glória). 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36). Que esta enciclopédia cristológica (15 volumes) sirva para a glória de Cristo e para a edificação da sua igreja.",
            referencias: "Romanos 11:36; 1 Coríntios 1:31; 1 Coríntios 10:31; 2 Coríntios 5:14-15; Gálatas 2:20; Efésios 1:3-14; Efésios 3:20-21; Filipenses 1:21; Filipenses 3:7-14; Colossenses 1:15-20; Apocalipse 5:12-14; Apocalipse 21:22-27"
        }
    ]
};