// volume/volume-8.js
window.LIVRO_DATA = {
    nome: "Volume VIII",
    dados: [
        {
            termo: "Adocionismo",
            definicao: "O Adocionismo (do latim adoptio - 'adoção') é uma heresia cristológica que surgiu nos primeiros séculos do cristianismo, ensinando que Jesus não era o Filho de Deus por natureza (divindade eterna), mas tornou-se Filho de Deus por adoção em algum momento de sua vida (geralmente no batismo, quando o Espírito Santo desceu sobre ele). Teve duas formas principais: (1) Adocionismo dinâmico (ou ebionita, século II): Jesus era um homem comum (nascido de José e Maria), que recebeu o Espírito Santo no batismo e foi 'adotado' como Filho de Deus. Os ebionitas (judeus-cristãos) rejeitavam a divindade de Cristo e a virgindade de Maria. (2) Adocionismo modalista (ou teopascita, século II-III): Jesus era Deus (o Pai) que assumiu a carne, mas foi 'adotado' como Filho? (confuso). A forma mais conhecida é o adocionismo de Félix de Urgel e Elipando de Toledo (século VIII), que ensinavam que Cristo, segundo sua humanidade, é Filho adotivo de Deus (embora segundo sua divindade seja Filho natural). Esta doutrina foi condenada pelo Concílio de Frankfurt (794 d.C.). A teologia reformada rejeita o adocionismo como heresia, afirmando que Cristo é o Filho eterno de Deus (João 1:1-14), gerado, não criado, consubstancial ao Pai (Nicéia, 325 d.C.). 'Antes que Abraão existisse, EU SOU' (João 8:58).",
            referencias: "Mateus 3:13-17; Marcos 1:9-11; Lucas 3:21-22; João 1:1-14; João 1:18; João 3:16; João 8:58; Romanos 1:3-4; Filipenses 2:5-11; Colossenses 1:15-20; Colossenses 2:9; Hebreus 1:1-4"
        },
        {
            termo: "Alfa e Ômega (Alpha and Omega)",
            definicao: "Alfa e Ômega são a primeira e a última letras do alfabeto grego. No Apocalipse, este título é aplicado tanto a Deus Pai (Apocalipse 1:8) quanto a Jesus Cristo (Apocalipse 22:12-13,16). 'Eu sou o Alfa e o Ômega, o primeiro e o último, o princípio e o fim.' Este título expressa a eternidade, a onipresença e a soberania de Cristo. Ele é o começo (Criador, João 1:3; Colossenses 1:16) e o fim (Consumador, Hebreus 12:2). Ele é o Senhor da história, que governa todas as coisas desde o princípio até a consumação. A teologia reformada vê neste título uma afirmação da divindade de Cristo, que compartilha os atributos divinos (eternidade, onipotência, onisciência) com o Pai e o Espírito Santo.",
            referencias: "Isaías 44:6; Isaías 48:12; Apocalipse 1:8; Apocalipse 1:17-18; Apocalipse 21:6; Apocalipse 22:12-13; Apocalipse 22:16"
        },
        {
            termo: "Analogia da Fé (Analogia Fidei)",
            definicao: "A analogia da fé (analogia fidei) é um princípio hermenêutico reformado que afirma que a Escritura interpreta a si mesma. Em outras palavras, nenhuma passagem da Escritura pode ser interpretada de modo a contradizer o claro ensinamento de outras passagens. A analogia da fé pressupõe a unidade e coerência da Escritura (que é inspirada por Deus, 2 Timóteo 3:16-17). Este princípio é particularmente importante para a cristologia: a divindade de Cristo é afirmada por muitas passagens (João 1:1-14; 20:28; Romanos 9:5; Tito 2:13; Filipenses 2:5-11; Colossenses 2:9; Hebreus 1:8-9), e passagens que parecem sugerir subordinação (João 14:28; 1 Coríntios 11:3) devem ser interpretadas em harmonia com as passagens que afirmam a divindade (subordinação funcional, não ontológica). A analogia da fé é também a base para o desenvolvimento do cânon e dos credos (Nicéia, Calcedônia), que são resumos da doutrina bíblica.",
            referencias: "Romanos 12:6; 2 Coríntios 13:1; 2 Timóteo 3:16-17; 2 Pedro 1:20-21; 2 Pedro 3:15-16"
        },
        {
            termo: "Anhypostasia (Anhypostasia)",
            definicao: "Anhypostasia (do grego an - 'sem' + hypostasis - 'substância/pessoa') é um termo técnico da cristologia que afirma que a natureza humana de Cristo não tem existência pessoal (hypostasis) independente. Em outras palavras, a natureza humana de Cristo não existiu como uma pessoa humana separada antes da encarnação; ela existe apenas na hipóstase (pessoa) do Verbo (Filho). Este conceito foi desenvolvido por Leôncio de Bizâncio (c. 485-543 d.C.) e pelos Pais Capadócios (Basílio, Gregório de Nazianzo, Gregório de Nissa) para refutar o nestorianismo (que separava as naturezas a ponto de duas pessoas). A anhypostasia é o correlato da enhypostasia (a natureza humana existe 'na' hipóstase do Verbo). A teologia reformada aceita a anhypostasia como uma formulação precisa da definição calcedoniana: 'uma pessoa em duas naturezas'.",
            referencias: "João 1:14; Romanos 1:3-4; Filipenses 2:5-11; Colossenses 2:9; Hebreus 2:14-18"
        },
        {
            termo: "Anátema (Anathema)",
            definicao: "Anátema (do grego anathema - 'coisa dedicada a Deus', geralmente para destruição) é uma fórmula de condenação eclesiástica. Nos concílios ecumênicos (Nicéia, Calcedônia, etc.), os hereges (Ário, Nestório, Eutiques) foram 'anatemizados' (condenados e excluídos da comunhão da igreja). O apóstolo Paulo usa o termo em Gálatas 1:8-9: 'Se alguém vos anunciar outro evangelho... seja anátema.' A teologia reformada mantém o princípio da disciplina eclesiástica (excomunhão) para os que negam a divindade de Cristo, a expiação vicária, ou a ressurreição. No entanto, a Reforma rejeitou o uso da força civil para punir hereges (Calvino foi ambivalente, pois consentiu na morte de Servet, 1553).",
            referencias: "Levítico 27:28-29; Deuteronômio 7:26; Josué 6:17; Romanos 9:3; 1 Coríntios 12:3; 1 Coríntios 16:22; Gálatas 1:8-9"
        },
        {
            termo: "Apocatástase (Apokatastasis)",
            definicao: "Apocatástase (do grego apokatastasis - 'restauração') é a doutrina de que todas as criaturas racionais (incluindo Satanás e os demônios) serão eventualmente salvas e restauradas à união com Deus. Foi ensinada por Orígenes (c. 184-253 d.C.) e por alguns Pais Gregos (Gregório de Nissa). A doutrina foi condenada pelo Concílio de Constantinopla (553 d.C.). A teologia reformada rejeita a apocatástase como contrária à Escritura, que ensina o juízo eterno para os ímpios (Mateus 25:46; Apocalipse 20:10,15). 'E estes irão para o tormento eterno, mas os justos para a vida eterna' (Mateus 25:46).",
            referencias: "Atos 3:21; Mateus 25:46; Apocalipse 20:10; Apocalipse 20:15; 2 Tessalonicenses 1:9; Judas 1:6-7"
        },
        {
            termo: "Apolinarianismo (Apollinarianism)",
            definicao: "O Apolinarianismo é uma heresia cristológica do século IV, atribuída a Apolinário de Laodiceia (c. 310-390 d.C.). Apolinário ensinava que o Logos (Verbo) substituiu a alma racional (nous) de Cristo, de modo que Cristo tinha corpo humano e alma animal (psique), mas não alma racional (espírito). Em outras palavras, Cristo não era plenamente humano. Esta doutrina foi condenada pelo Concílio de Constantinopla (381 d.C.). A resposta clássica foi dada por Gregório de Nazianzo: 'O que não foi assumido não foi curado' (o que não foi assumido por Cristo não foi redimido). A teologia reformada rejeita o apolinarianismo, afirmando que Cristo assumiu a natureza humana completa (corpo, alma e espírito), para redimir o homem completo (Hebreus 2:14-18; 4:15).",
            referencias: "João 1:14; Romanos 1:3; Gálatas 4:4; Filipenses 2:7; 1 Timóteo 2:5; Hebreus 2:14-18; Hebreus 4:15; 1 João 4:2-3"
        },
        {
            termo: "Arianismo (Arianism)",
            definicao: "O Arianismo é a heresia cristológica mais importante do século IV, atribuída a Ário (c. 256-336 d.C.), presbítero de Alexandria. Ário ensinava que o Filho de Deus não é co-eterno com o Pai, nem da mesma substância (homoousios). Suas fórmulas: 'Houve um tempo em que o Filho não existia' (ēn pote hote ouk ēn); 'O Filho foi criado do nada' (ex ouk ontōn); 'O Filho é uma criatura' (ktisma). O arianismo foi condenado pelo Concílio de Nicéia (325 d.C.), que afirmou o homoousios (da mesma substância). O arianismo moderno sobrevive nos unitaristas, testemunhas de Jeová (que traduzem João 1:1 como 'o Verbo era um deus') e mórmons (que veem Jesus como um espírito criado). A teologia reformada rejeita o arianismo como heresia, afirmando a divindade plena de Cristo (João 1:1,14; 20:28; Romanos 9:5; Tito 2:13; Filipenses 2:6).",
            referencias: "Provérbios 8:22-31; João 1:1-14; João 1:18; João 3:16; João 8:58; João 10:30; João 20:28; Romanos 9:5; Filipenses 2:5-6; Colossenses 1:15-17; Colossenses 2:9; Tito 2:13; Hebreus 1:1-4; Apocalipse 1:8"
        },
        {
            termo: "Ascensão de Cristo (Ascension of Christ)",
            definicao: "A ascensão de Cristo é o evento em que Jesus, quarenta dias após sua ressurreição, subiu corporalmente ao céu (Lucas 24:50-53; Atos 1:9-11). A ascensão marca o fim do ministério terreno de Cristo e o início de seu ministério celestial como sumo sacerdote e intercessor (Hebreus 4:14-16; 7:25; Romanos 8:34). Significados teológicos: (1) Exaltação de Cristo: após a humilhação (encarnação, sofrimento, morte), Cristo é exaltado à direita de Deus (Filipenses 2:9-11). (2) Preparação do lugar: 'Vou preparar-vos lugar' (João 14:2-3). (3) Envio do Espírito Santo: 'Se eu não for, o Consolador não virá' (João 16:7). (4) Intercessão: Cristo intercede por nós no céu (Hebreus 7:25). (5) Esperança da parusia: 'Este Jesus... há de vir assim como para o céu o vistes ir' (Atos 1:11). A teologia reformada afirma a ascensão corporal (Cristo está no céu em seu corpo glorificado, Atos 3:21), rejeitando a ubiquidade luterana (a presença corporal de Cristo em toda parte).",
            referencias: "Marcos 16:19; Lucas 24:50-53; João 14:2-3; João 16:7; Atos 1:1-3; Atos 1:9-11; Atos 2:33-36; Atos 3:21; Romanos 8:34; Efésios 1:20-23; Efésios 4:8-10; Filipenses 2:9-11; Colossenses 3:1; 1 Timóteo 3:16; Hebreus 1:3; Hebreus 4:14-16; Hebreus 7:25; 1 Pedro 3:22"
        },
        {
            termo: "Batismo de Jesus (Baptism of Jesus)",
            definicao: "O batismo de Jesus por João Batista no rio Jordão (Mateus 3:13-17; Marcos 1:9-11; Lucas 3:21-22; João 1:29-34) é um evento teológico de grande importância. Diferente do batismo de arrependimento (para remissão de pecados), Jesus não tinha pecados (Hebreus 4:15), mas foi batizado 'para cumprir toda a justiça' (Mateus 3:15). Significados: (1) Identificação de Jesus com os pecadores (embora sem pecado). (2) Inauguração de seu ministério público. (3) Manifestação da Trindade: o Pai fala do céu ('Este é o meu Filho amado'), o Filho é batizado, o Espírito desce como pomba. (4) Investidura messiânica: o Espírito desce sobre Jesus (Isaías 61:1; Atos 10:38). (5) Prefiguração do batismo cristão (Romanos 6:3-5). A teologia reformada vê no batismo de Jesus a confirmação de sua missão messiânica e a revelação trinitária.",
            referencias: "Isaías 42:1; Isaías 61:1; Mateus 3:13-17; Marcos 1:9-11; Lucas 3:21-22; Lucas 4:18-19; João 1:29-34; Atos 10:38; Romanos 6:3-5"
        },
        {
            termo: "Blasfêmia contra o Espírito Santo (Blasphemy against the Holy Spirit)",
            definicao: "A blasfêmia contra o Espírito Santo é um pecado mencionado por Jesus em Mateus 12:31-32; Marcos 3:28-30; Lucas 12:10. Jesus declarou que 'todo pecado e blasfêmia será perdoado aos homens; mas a blasfêmia contra o Espírito Santo não será perdoada'. O contexto: os fariseus atribuíram os milagres de Jesus (feitos pelo Espírito Santo) a Belzebu (príncipe dos demônios). A blasfêmia contra o Espírito Santo consiste em: (a) atribuir a obra do Espírito Santo (em Jesus) ao diabo; (b) rejeitar deliberadamente a evidência clara da verdade (a divindade de Cristo, os milagres); (c) endurecimento do coração a ponto de não haver mais arrependimento. A teologia reformada ensina que este pecado não é um ato isolado, mas uma rejeição final e obstinada de Cristo, que leva à impenitência. Não é que Deus não possa perdoar, mas o pecador não se arrepende (Hebreus 6:4-6; 10:26-31).",
            referencias: "Mateus 12:22-32; Marcos 3:22-30; Lucas 12:10; Hebreus 6:4-6; Hebreus 10:26-31; 1 João 5:16"
        },
        {
            termo: "Calcedônia, Definição de (Definition of Chalcedon)",
            definicao: "A Definição de Calcedônia (451 d.C.) é o mais importante documento cristológico da igreja antiga. Ela foi promulgada pelo Concílio de Calcedônia (quarto concílio ecumênico) em resposta às heresias do nestorianismo (separação das naturezas) e do monofisismo/eutiquianismo (confusão das naturezas). A definição afirma que Cristo é 'perfeito em divindade e perfeito em humanidade, verdadeiramente Deus e verdadeiramente homem... consubstancial ao Pai segundo a divindade e consubstancial a nós segundo a humanidade... em duas naturezas, sem confusão, sem mudança, sem divisão, sem separação'. A teologia reformada aceita Calcedônia como uma exposição fiel da Escritura e como a 'parede de pedra da ortodoxia'. Os quatro advérbios (sem confusão, sem mudança, sem divisão, sem separação) são essenciais para a cristologia reformada.",
            referencias: "João 1:1-14; João 1:18; João 10:30; Romanos 1:3-4; Romanos 9:5; Filipenses 2:5-11; Colossenses 1:15-20; Colossenses 2:9; 1 Timóteo 3:16; Tito 2:13; Hebreus 1:1-4; 1 João 4:2-3"
        },
        {
            termo: "Caminho, Verdade e Vida (Way, Truth and Life)",
            definicao: "'Eu sou o caminho, e a verdade, e a vida; ninguém vem ao Pai senão por mim' (João 14:6). Esta é uma das mais importantes declarações de Jesus sobre sua identidade exclusiva. (1) Caminho (hodos): Jesus é o único mediador entre Deus e os homens (1 Timóteo 2:5). Não há outro caminho para o Pai (Atos 4:12). (2) Verdade (alētheia): Jesus é a revelação definitiva de Deus (João 1:18; Colossenses 2:9). Ele não apenas fala a verdade, ele é a verdade. (3) Vida (zōē): Jesus é a fonte da vida eterna (João 3:16; 5:24; 10:10). 'Quem tem o Filho tem a vida' (1 João 5:11-12). A teologia reformada vê nesta declaração a unicidade de Cristo (exclusivismo), rejeitando o pluralismo religioso (Jesus é um caminho entre muitos).",
            referencias: "João 1:18; João 3:16; João 5:24; João 10:10; João 14:6; Atos 4:12; 1 Timóteo 2:5; 1 João 5:11-12; Apocalipse 1:18"
        },
        {
            termo: "Cabeça da Igreja (Head of the Church)",
            definicao: "Cristo é a 'cabeça da igreja' (Efésios 1:22; 4:15; 5:23; Colossenses 1:18). Esta metáfora orgânica (cabeça-corpo) expressa: (1) Autoridade de Cristo sobre a igreja: Ele governa, guia, protege e supre sua igreja. 'Ele é a cabeça do corpo, da igreja' (Colossenses 1:18). (2) Unidade entre Cristo e a igreja: a igreja é o corpo de Cristo (1 Coríntios 12:12-27). (3) Submissão da igreja a Cristo: assim como o corpo se submete à cabeça (Efésios 5:23-24). (4) Dependência da igreja: a igreja recebe vida, crescimento e dons de Cristo (Efésios 4:15-16). A teologia reformada enfatiza que Cristo é o único cabeça da igreja (contra o papado). 'Não reconhecemos outro cabeça na terra senão Cristo' (Confissão de Fé de Westminster, 25.6).",
            referencias: "1 Coríntios 11:3; 1 Coríntios 12:12-27; Efésios 1:22-23; Efésios 4:15-16; Efésios 5:23-24; Colossenses 1:18; Colossenses 2:19"
        },
        {
            termo: "Ceticismo Histórico (Historical Skepticism)",
            definicao: "O ceticismo histórico em relação a Jesus é a posição de que não podemos saber muito (ou nada) sobre o Jesus histórico, porque os evangelhos são tardios, tendenciosos e não confiáveis. Foi defendido por Rudolf Bultmann (desmitologização) e pelo 'Jesus Seminar' (século XX). A teologia reformada rejeita o ceticismo histórico, afirmando a confiabilidade histórica dos evangelhos (Lucas 1:1-4; João 20:30-31; 1 Coríntios 15:3-8). O Jesus da história é o Cristo da fé (Lucas 24:27,44-45).",
            referencias: "Lucas 1:1-4; Lucas 24:27; Lucas 24:44-45; João 20:30-31; Atos 1:1-3; 1 Coríntios 15:3-8; 2 Pedro 1:16-21; 1 João 1:1-4"
        },
        {
            termo: "Ciência de Cristo (Knowledge of Christ)",
            definicao: "A ciência de Cristo (conhecimento de Jesus) é uma questão debatida na teologia: Jesus, sendo verdadeiro Deus e verdadeiro homem, tinha conhecimento humano (limitado) e conhecimento divino (ilimitado). A teologia católica (Tomás de Aquino) distingue três tipos de conhecimento em Cristo: (1) Ciência beatífica (visão direta de Deus) - desde o momento da concepção, Cristo teve a visão beatífica (conhecia a Deus face a face). (2) Ciência infusa (conhecimento dado por Deus) - Cristo tinha todo o conhecimento que a alma humana pode receber por infusão divina. (3) Ciência adquirida (aprendizado empírico) - Cristo aprendeu algumas coisas por experiência (Lucas 2:52). A teologia reformada (Calvino) segue Tomás em linhas gerais, mas enfatiza que a humanidade de Cristo foi limitada (ele não sabia o dia da parusia, Marcos 13:32). O 'extra calvinisticum' (Logos opera também fora da carne) permite que Cristo soubesse coisas além de sua humanidade, mas não que sua humanidade fosse onisciente.",
            referencias: "Lucas 2:40; Lucas 2:52; Marcos 13:32; João 1:1-14; João 2:25; João 4:1-42; João 5:19-20; João 6:64; Colossenses 2:3; Apocalipse 1:1"
        },
        {
            termo: "Cordeiro de Deus (Lamb of God)",
            definicao: "Cordeiro de Deus (Amnos tou Theou) é um título cristológico dado por João Batista: 'Eis o Cordeiro de Deus, que tira o pecado do mundo' (João 1:29,36). O título tem raízes no Antigo Testamento: (1) O cordeiro pascal (Êxodo 12) - cujo sangue protegia da morte. (2) O cordeiro do sacrifício diário (tamid). (3) O cordeiro do Servo Sofredor (Isaías 53:7) - 'como cordeiro foi levado ao matadouro'. (4) O cordeiro de Deus no apocalipse (Apocalipse 5:6-14; 7:17; 21:22-23). Significados: (a) Sacrifício expiatório: Jesus morreu como o sacrifício perfeito pelos pecados (1 Coríntios 5:7; 1 Pedro 1:18-19). (b) Submissão voluntária: 'como cordeiro mudo perante o tosquiador, ele não abriu a boca' (Isaías 53:7). (c) Vitória: o Cordeiro é o Leão de Judá (Apocalipse 5:5-6). A teologia reformada vê no Cordeiro de Deus a expiação vicária (substituição penal): Jesus tomou sobre si os nossos pecados (Isaías 53:5-6; 2 Coríntios 5:21; 1 Pedro 2:24).",
            referencias: "Êxodo 12:1-28; Isaías 53:7; Jeremias 11:19; João 1:29; João 1:36; 1 Coríntios 5:7; 1 Pedro 1:18-19; Apocalipse 5:6-14; Apocalipse 7:17; Apocalipse 13:8; Apocalipse 17:14; Apocalipse 21:22-23; Apocalipse 22:3"
        },
        {
            termo: "Cristo (Christos)",
            definicao: "Cristo (do grego Christos - 'Ungido') é a tradução do hebraico Mashiach (Messias). O título 'Cristo' não é um sobrenome de Jesus, mas um título oficial que significa 'o Ungido'. No Antigo Testamento, eram ungidos: (1) Reis (1 Samuel 10:1; 16:13). (2) Sacerdotes (Êxodo 29:7). (3) Profetas (1 Reis 19:16). Jesus é o 'Ungido' em todos os três ofícios: profeta, sacerdote e rei (munus triplex). 'Cristo' se tornou o título principal de Jesus no Novo Testamento (Mateus 16:16; Marcos 8:29; Lucas 9:20). 'Pedro respondeu: Tu és o Cristo, o Filho do Deus vivo' (Mateus 16:16). A teologia reformada enfatiza que Jesus é o Messias prometido, que cumpriu todas as profecias do Antigo Testamento (Lucas 24:27,44-45).",
            referencias: "Êxodo 29:7; 1 Samuel 10:1; 1 Samuel 16:13; Salmo 2:2; Salmo 45:7; Isaías 61:1; Daniel 9:25-26; Mateus 16:16; Marcos 8:29; Lucas 2:11; Lucas 9:20; Lucas 24:27; Lucas 24:44-45; João 1:41; João 4:25; Atos 2:36; Atos 10:38"
        },
        {
            termo: "Cristo como Profeta, Sacerdote e Rei (Christ as Prophet, Priest, and King)",
            definicao: "Os três ofícios de Cristo (munus triplex) - profeta, sacerdote e rei - foram sistematicamente desenvolvidos por João Calvino (Institutas II.15). (1) Profeta: Cristo revela a vontade de Deus e nos ensina. 'O Senhor teu Deus levantará um profeta do meio de ti... a ele ouvireis' (Deuteronômio 18:15-19; Atos 3:22-23). Jesus cumpriu este ofício em seu ministério terreno (ensinando, pregando) e continua a ensinar por seu Espírito (João 14:26; 16:13). (2) Sacerdote: Cristo ofereceu a si mesmo em sacrifício pelos pecados e intercede por nós. 'Ele foi ferido por nossas transgressões... e pelas suas pisaduras fomos sarados' (Isaías 53:5). 'Ele é o sumo sacerdote... que sempre vive para interceder por nós' (Hebreus 4:14-16; 7:25). (3) Rei: Cristo governa a igreja e o universo. 'A ti foi dado domínio, honra e reino' (Daniel 7:14). 'Toda a autoridade me foi dada no céu e na terra' (Mateus 28:18). Cristo reina sobre os corações dos crentes (reino da graça) e voltará para julgar (reino da glória). A teologia reformada enfatiza que estes três ofícios são exercidos por Cristo simultaneamente, e os crentes participam deles (sacerdócio universal dos crentes, 1 Pedro 2:9).",
            referencias: "Deuteronômio 18:15-19; Salmo 2; Salmo 110; Isaías 9:6-7; Isaías 53; Daniel 7:13-14; Mateus 28:18; Lucas 4:18-21; João 14:6; Atos 3:22-23; Romanos 8:34; 1 Coríntios 1:30; Efésios 1:20-23; Filipenses 2:9-11; Colossenses 1:13-20; Hebreus 1:8-9; Hebreus 4:14-16; Hebreus 7:25; 1 Pedro 2:9; Apocalipse 17:14"
        },
        {
            termo: "Cristo, Homem (Christ as Man)",
            definicao: "A humanidade de Cristo é uma doutrina central da fé cristã: Jesus é verdadeiro homem, nascido da virgem Maria, com corpo, alma e espírito humanos. A Bíblia afirma: (1) Jesus nasceu de mulher (Gálatas 4:4). (2) Jesus tinha corpo humano: comeu (Lucas 24:42-43), bebeu (João 19:28), cansou-se (João 4:6), dormiu (Mateus 8:24), sofreu (Mateus 27:46), morreu (Marcos 15:37). (3) Jesus tinha alma/espírito humano: 'entregou o espírito' (Mateus 27:50), 'ficou maravilhado' (Mateus 8:10), 'compadeceu-se' (Mateus 9:36), 'angustiou-se' (Mateus 26:37-38). (4) Jesus foi tentado, mas sem pecado (Hebreus 4:15). A teologia reformada afirma a humanidade plena de Cristo (contra o docetismo e o apolinarianismo). 'O Verbo se fez carne' (João 1:14). 'O que não foi assumido não foi curado' (Gregório de Nazianzo).",
            referencias: "Isaías 7:14; Mateus 1:18-25; Lucas 1:26-38; Lucas 2:1-20; Lucas 2:40-52; João 1:14; João 4:6; João 11:35; João 19:28; Atos 2:22; Romanos 1:3; Romanos 5:15; Gálatas 4:4; Filipenses 2:7-8; 1 Timóteo 2:5; Hebreus 2:14-18; Hebreus 4:15; 1 João 4:2-3; 2 João 1:7"
        },
        {
            termo: "Cristo, Senhor (Christ as Lord)",
            definicao: "Senhor (Kyrios) é o título mais importante para Jesus no Novo Testamento, aplicando a ele o nome divino YHWH (o SENHOR) do Antigo Testamento. 'Se com a tua boca confessares ao Senhor Jesus, e em teu coração creres que Deus o ressuscitou dentre os mortos, serás salvo' (Romanos 10:9). Evidências de que Kyrios = YHWH: (1) Citação de Joel 2:32 ('todo aquele que invocar o nome do SENHOR será salvo') aplicada a Jesus em Romanos 10:9-13. (2) Citação de Isaías 45:23 ('todo joelho se dobrará') aplicada a Jesus em Filipenses 2:10-11. (3) Jesus é chamado de 'Senhor do sábado' (Marcos 2:28), atributo divino. (4) Tomé confessou: 'Senhor meu, e Deus meu!' (João 20:28). A teologia reformada vê no título 'Senhor' a afirmação da divindade de Cristo e seu senhorio sobre toda a criação. 'Confessar que Jesus Cristo é o Senhor' é o distintivo da fé cristã (1 Coríntios 12:3).",
            referencias: "Salmo 110:1; Isaías 45:23; Joel 2:32; Mateus 22:44; Marcos 2:28; Lucas 2:11; João 13:13; João 20:28; Atos 2:36; Atos 10:36; Romanos 10:9-13; 1 Coríntios 8:6; 1 Coríntios 12:3; Filipenses 2:9-11; Colossenses 2:6; 1 Pedro 3:15"
        },
        {
            termo: "Comunicação de Atributos (Communicatio Idiomatum)",
            definicao: "A comunicação de atributos (communicatio idiomatum) é um princípio cristológico que afirma que os atributos (propriedades) de cada natureza (divina e humana) podem ser atribuídos à pessoa de Cristo. Em outras palavras, o que é verdade sobre a natureza divina pode ser dito da pessoa (ex.: 'Deus morreu na cruz' - a pessoa do Filho, não a natureza divina). O que é verdade sobre a natureza humana pode ser dito da pessoa (ex.: 'Jesus criou o universo' - a pessoa do Verbo, que criou todas as coisas, João 1:3). A definição calcedoniana (451 d.C.) fornece a base: as duas naturezas são unidas 'sem confusão, sem mudança, sem divisão, sem separação'. A teologia reformada aceita a comunicação de atributos como um princípio bíblico (Atos 20:28; 1 Coríntios 2:8; Colossenses 1:15-17; 1 Pedro 3:18). Os luteranos (Fórmula de Concórdia, 1577) afirmam uma comunicação real (a humanidade de Cristo participa dos atributos divinos, como ubiquidade), enquanto os reformados (Calvino) afirmam uma comunicação verbal (os atributos são predicados da pessoa, mas a humanidade não se torna divina).",
            referencias: "João 1:1-3; João 3:13; Atos 20:28; 1 Coríntios 2:8; 1 Coríntios 15:47; Filipenses 2:5-11; Colossenses 1:15-17; 1 Pedro 3:18"
        },
        {
            termo: "Consubstancial (Homoousios)",
            definicao: "Consubstancial (do grego homoousios - 'da mesma substância/essência') é o termo teológico usado pelo Concílio de Nicéia (325 d.C.) para afirmar que o Filho (Jesus Cristo) é da mesma substância que o Pai, contra o arianismo (que ensinava que o Filho era de substância diferente, heteroousios, ou substância semelhante, homoiousios). O termo foi escolhido para excluir qualquer interpretação ariana. 'Cremos... em um só Senhor Jesus Cristo, o Filho de Deus... Deus de Deus, luz de luz, Deus verdadeiro de Deus verdadeiro; gerado, não criado; consubstancial ao Pai' (Credo Niceno). A teologia reformada aceita o homoousios como uma exposição fiel da Escritura (João 1:1; 10:30; 14:9; Filipenses 2:6; Colossenses 2:9).",
            referencias: "João 1:1; João 1:18; João 10:30; João 14:9; João 17:5; Filipenses 2:6; Colossenses 1:15; Colossenses 2:9; Hebreus 1:3"
        },
        {
            termo: "Cordeiro Pascal (Paschal Lamb)",
            definicao: "O Cordeiro Pascal é o cordeiro sacrificado na noite da Páscoa (Pessach) no Egito, cujo sangue foi colocado nos umbrais das portas dos israelitas para proteger suas casas do anjo da morte (Êxodo 12:1-28). O apóstolo Paulo identifica Cristo com o Cordeiro Pascal: 'Cristo, nossa Páscoa, foi sacrificado por nós' (1 Coríntios 5:7). João Batista também identifica Jesus como 'o Cordeiro de Deus, que tira o pecado do mundo' (João 1:29,36). Significados: (1) O sangue de Cristo nos protege da ira de Deus (Romanos 5:9). (2) Cristo é o sacrifício perfeito e definitivo (Hebreus 9:11-14; 10:1-18). (3) A libertação do Egito (escravidão do pecado) é tipificada pela libertação em Cristo. A teologia reformada vê no Cordeiro Pascal a expiação vicária (substituição penal).",
            referencias: "Êxodo 12:1-28; João 1:29; João 1:36; 1 Coríntios 5:7; 1 Pedro 1:18-19; Apocalipse 5:6-14; Apocalipse 13:8"
        },
        {
            termo: "Criação, Mediador da (Mediator of Creation)",
            definicao: "A Bíblia ensina que Jesus Cristo (o Verbo/Logos) foi o mediador da criação. 'Todas as coisas foram feitas por ele, e sem ele nada do que foi feito se fez' (João 1:3). 'Porque nele foram criadas todas as coisas que há nos céus e na terra, visíveis e invisíveis... tudo foi criado por ele e para ele' (Colossenses 1:16). 'O Filho... por quem fez também o mundo' (Hebreus 1:2). Isto significa que o Pai criou todas as coisas através do Filho (e no Espírito Santo). A teologia reformada vê na mediação da criação a pré-existência e divindade de Cristo. Ele não é uma criatura (como Ário ensinava), mas o Criador (João 1:10).",
            referencias: "João 1:1-3; João 1:10; 1 Coríntios 8:6; Colossenses 1:15-17; Hebreus 1:2-3; Hebreus 11:3"
        },
        {
            termo: "Cristologia de Cima / de Baixo (Christology from Above / from Below)",
            definicao: "A cristologia de cima (Christology from above) parte do Logos pré-existente (o Verbo eterno) e desce à encarnação. É característica de João (João 1:1-14), Paulo (Filipenses 2:5-11) e da cristologia calcedoniana. A cristologia de baixo (Christology from below) parte do Jesus histórico (homem, profeta, mestre) e ascende à confissão de divindade. É característica dos evangelhos sinóticos (Marcos, Mateus, Lucas) e da teologia moderna (Pannenberg, Moltmann). A teologia reformada rejeita a falsa dicotomia entre ambas: o Jesus da história é o Cristo da fé (Lucas 24:27,44-45). A cristologia deve começar com a Escritura como um todo, que testemunha tanto a divindade quanto a humanidade de Cristo.",
            referencias: "João 1:1-14; João 3:13; João 6:38; Romanos 1:3-4; Filipenses 2:5-11; Lucas 24:27; Lucas 24:44-45; 1 Pedro 1:10-12"
        },
        {
            termo: "Crucificação (Crucifixion)",
            definicao: "A crucificação de Jesus é o evento central da fé cristã: Jesus foi pregado na cruz sob Pôncio Pilatos (governador romano da Judeia, c. 26-36 d.C.), entre dois ladrões, e morreu depois de cerca de seis horas (Mateus 27:32-56; Marcos 15:21-41; Lucas 23:26-49; João 19:16-37). Significados teológicos: (1) Expiação vicária (substituição penal): 'Cristo morreu pelos nossos pecados' (1 Coríntios 15:3). 'Ele foi ferido por nossas transgressões' (Isaías 53:5). (2) Satisfação da justiça divina (Anselmo, Calvino). (3) Amor de Deus: 'Deus prova o seu amor para conosco, em que, sendo nós ainda pecadores, Cristo morreu por nós' (Romanos 5:8). (4) Reconciliação: 'Deus estava em Cristo reconciliando consigo o mundo' (2 Coríntios 5:19). (5) Vitória sobre o pecado e a morte (Colossenses 2:13-15). A teologia reformada enfatiza a expiação penal substitutiva como o coração do evangelho.",
            referencias: "Isaías 53:1-12; Mateus 27:32-56; Marcos 15:21-41; Lucas 23:26-49; João 19:16-37; Romanos 3:23-26; Romanos 5:8-11; 1 Coríntios 15:3; 2 Coríntios 5:18-21; Gálatas 3:13; Efésios 2:13-18; Colossenses 2:13-15; 1 Pedro 2:24; 1 Pedro 3:18"
        },
        {
            termo: "Deificação (Theosis)",
            definicao: "A deificação (theosis, do grego theos - 'Deus') é a doutrina de que o crente pode se tornar 'participante da natureza divina' (2 Pedro 1:4). Enfatizada na teologia oriental (Atanásio, Gregório de Nissa, Máximo, o Confessor) e no catolicismo, a theosis afirma que o homem pode se tornar 'deus por graça' (não por essência). Atanásio: 'O Verbo se fez homem para que nos tornássemos deuses' (De Incarnatione 54). A teologia reformada tem uma visão moderada da theosis: o crente é 'participante da natureza divina' no sentido de que recebe os frutos do Espírito (Gálatas 5:22-23) e é transformado à imagem de Cristo (Romanos 8:29; 2 Coríntios 3:18), mas não no sentido de se tornar 'deus' (essência divina), o que seria panteísmo. Calvino rejeitou a theosis no sentido oriental, mas afirmou a união com Cristo (unio cum Christo).",
            referencias: "João 10:34-36; João 17:21-23; Romanos 8:29; 2 Coríntios 3:18; Gálatas 2:20; Efésios 4:13; 2 Pedro 1:4; 1 João 3:2"
        },
        {
            termo: "Desmitologização (Demythologization)",
            definicao: "Desmitologização é o programa de Rudolf Bultmann (1884-1976) para interpretar o Novo Testamento removendo o 'mito' (cosmologia de três andares, milagres, anjos, demônios, céu, inferno) e extraindo o 'kerygma' (a mensagem existencial de salvação). Bultmann argumentava que o homem moderno (científico) não pode aceitar o mito. A teologia reformada rejeita a desmitologização como uma negação da ressurreição corporal, dos milagres e da divindade de Cristo. 'Se Cristo não ressuscitou, é vã a vossa fé' (1 Coríntios 15:17).",
            referencias: "1 Coríntios 15:1-8; 1 Coríntios 15:12-20; 2 Pedro 1:16-21; 1 João 1:1-4"
        },
        {
            termo: "Discipulado (Discipleship)",
            definicao: "Discipulado (do latim discipulus - 'aprendiz, seguidor') é o chamado de Jesus para segui-lo, aprender com ele e imitá-lo. 'Se alguém quer vir após mim, negue-se a si mesmo, tome a sua cruz e siga-me' (Mateus 16:24). O discipulado envolve: (a) arrependimento e fé; (b) obediência aos mandamentos de Cristo; (c) imitação de Cristo (1 Coríntios 11:1; 1 Pedro 2:21); (d) sofrimento (2 Timóteo 3:12). A teologia reformada (especialmente a puritana) enfatiza o discipulado como a resposta à justificação pela fé (a santificação). Dietrich Bonhoeffer, em 'O Custo do Discipulado' (1937), distingue 'fé barata' (sem obediência) de 'fé cara' (com obediência).",
            referencias: "Mateus 4:19; Mateus 8:22; Mateus 10:38; Mateus 16:24; Mateus 28:18-20; Lucas 9:23; Lucas 14:25-33; João 8:31; João 13:34-35; João 15:8; Atos 11:26; 1 Coríntios 11:1; 1 Pedro 2:21; 1 João 2:6"
        },
        {
            termo: "Docetismo (Docetism)",
            definicao: "O Docetismo (do grego dokeō - 'parecer, aparentar') é uma heresia cristológica dos primeiros séculos (século II-III) que ensinava que Jesus não tinha um corpo real, mas apenas 'parecia' ter corpo (era uma aparição, um fantasma). O docetismo foi combatido por Inácio de Antioquia (c. 35-108 d.C.) e pelos apóstolos João (1 João 4:2-3; 2 João 1:7). A teologia reformada rejeita o docetismo, afirmando a verdadeira humanidade de Cristo (João 1:14). 'Todo espírito que confessa que Jesus Cristo veio em carne é de Deus' (1 João 4:2).",
            referencias: "João 1:14; 1 João 4:2-3; 2 João 1:7; Lucas 24:36-43; João 20:24-29"
        },
        {
            termo: "Ego Eimi (Eu Sou)",
            definicao: "Ego eimi (grego para 'eu sou') é a expressão usada por Jesus no Evangelho de João para afirmar sua divindade, ecoando o nome divino de Êxodo 3:14 ('EU SOU O QUE SOU' - YHWH). Os sete 'Eu Sou' predicativos: (1) 'Eu sou o pão da vida' (João 6:35,48,51). (2) 'Eu sou a luz do mundo' (João 8:12; 9:5). (3) 'Eu sou a porta das ovelhas' (João 10:7,9). (4) 'Eu sou o bom pastor' (João 10:11,14). (5) 'Eu sou a ressurreição e a vida' (João 11:25). (6) 'Eu sou o caminho, a verdade e a vida' (João 14:6). (7) 'Eu sou a videira verdadeira' (João 15:1,5). Além destes, os 'Eu Sou' absolutos: 'Antes que Abraão existisse, EU SOU' (João 8:58); 'Eu o sou' (João 18:5-6). A teologia reformada vê nos 'Eu Sou' a afirmação inequívoca da divindade de Cristo.",
            referencias: "Êxodo 3:14; João 6:35; João 8:12; João 8:58; João 10:7; João 10:11; João 11:25; João 14:6; João 15:1; João 18:5-6"
        },
        {
            termo: "Encarnação (Incarnation)",
            definicao: "A encarnação (do latim incarnatio - 'tornar-se carne') é a doutrina de que o Verbo (Logos), a segunda pessoa da Trindade, assumiu a natureza humana (carne) e se tornou homem. 'E o Verbo se fez carne, e habitou entre nós' (João 1:14). 'O grande mistério da piedade: Deus se manifestou em carne' (1 Timóteo 3:16). A encarnação não significa que o Verbo deixou de ser Deus (ele continuou sendo Deus), mas que ele assumiu a natureza humana sem perder a divina. A definição calcedoniana (451 d.C.) afirma que as duas naturezas (divina e humana) estão unidas em uma pessoa, 'sem confusão, sem mudança, sem divisão, sem separação'. A teologia reformada afirma a encarnação como o centro da história da redenção. 'Deus se fez homem para que o homem se tornasse como Deus' (Atanásio).",
            referencias: "Isaías 7:14; Isaías 9:6; Mateus 1:23; João 1:1-14; João 1:18; Gálatas 4:4-5; Filipenses 2:5-8; 1 Timóteo 3:16; Hebreus 1:1-4; 1 João 4:2-3"
        },
        {
            termo: "Enhypostasia (Enhypostasis)",
            definicao: "Enhypostasia (do grego en - 'em' + hypostasis - 'substância/pessoa') é um termo técnico da cristologia que afirma que a natureza humana de Cristo existe 'na' hipóstase (pessoa) do Verbo. Em outras palavras, a natureza humana de Cristo não tem existência pessoal independente (anhypostasia), mas existe na pessoa do Verbo. Este conceito foi desenvolvido por Leôncio de Bizâncio (c. 485-543 d.C.) para refutar o nestorianismo (que separava as naturezas). A enhypostasia é o correlato da anhypostasia. A teologia reformada aceita a enhypostasia como uma formulação precisa da definição calcedoniana.",
            referencias: "João 1:14; Romanos 1:3-4; Filipenses 2:5-11; Colossenses 2:9; Hebreus 2:14-18"
        },
        {
            termo: "Eucaristia (Eucharist)",
            definicao: "A Eucaristia (do grego eucharistia - 'ação de graças'), também chamada Ceia do Senhor, é o sacramento instituído por Jesus na última ceia (Mateus 26:26-29; Marcos 14:22-25; Lucas 22:19-20; 1 Coríntios 11:23-26). As diferentes tradições cristãs têm visões diferentes sobre a presença de Cristo na Eucaristia: (a) Transubstanciação (católica): a substância do pão e do vinho se converte na substância do corpo e sangue de Cristo. (b) Consubstanciação / Presença real (luterana): o corpo e sangue de Cristo estão presentes 'com, sob e nas' formas do pão e do vinho. (c) Presença espiritual (calvinista/reformada): Cristo está verdadeiramente presente, mas espiritualmente (pelo Espírito Santo). (d) Memorialismo (zwingliano, batista): a Ceia é um memorial (símbolo) do corpo e sangue de Cristo. A teologia reformada (Calvino, Westminster) ensina a presença espiritual (os crentes recebem o corpo e sangue de Cristo pela fé, espiritualmente, não oralmente).",
            referencias: "Mateus 26:26-29; Marcos 14:22-25; Lucas 22:19-20; João 6:51-58; 1 Coríntios 10:16-22; 1 Coríntios 11:23-34; Atos 2:42; Atos 20:7"
        },
        {
            termo: "Exaltação de Cristo (Exaltation of Christ)",
            definicao: "A exaltação de Cristo é o estado de glória após sua humilhação (encarnação, sofrimento, morte). A exaltação inclui: (a) ressurreição (Atos 2:24-32); (b) ascensão (Atos 1:9-11); (c) sessão à direita de Deus (Marcos 16:19; Efésios 1:20); (d) juízo sobre o mundo (João 5:22; Atos 17:31); (e) parusia (segunda vinda). 'Pelo que também Deus o exaltou soberanamente, e lhe deu um nome que é sobre todo o nome' (Filipenses 2:9-11). A teologia reformada vê na exaltação o cumprimento das profecias do Antigo Testamento (Salmo 110:1; Daniel 7:13-14).",
            referencias: "Salmo 110:1; Daniel 7:13-14; Atos 2:32-36; Atos 5:31; Romanos 14:9; Efésios 1:20-23; Filipenses 2:9-11; Colossenses 3:1; Hebreus 1:3; Hebreus 12:2; 1 Pedro 3:22"
        },
        {
            termo: "Expiação (Atonement)",
            definicao: "A expiação (do latim expiatio - 'reparar, purificar') é a obra de Cristo pela qual ele reconciliou os pecadores com Deus, satisfazendo a justiça divina e removendo a culpa do pecado. Teorias da expiação: (a) Teoria do resgate (Orígenes): Cristo pagou um resgate ao diabo. (b) Teoria da satisfação (Anselmo): Cristo satisfez a honra divina. (c) Teoria da substituição penal (Reforma): Cristo sofreu a penalidade que nós merecíamos (Isaías 53:5-6; Romanos 3:23-26; 2 Coríntios 5:21; 1 Pedro 2:24). (d) Teoria da influência moral (Abelardo): a morte de Cristo demonstra o amor de Deus e inspira o arrependimento. (e) Teoria do exemplo (Socino): Cristo morreu como exemplo de fidelidade, não para satisfazer a justiça. A teologia reformada afirma a substituição penal como a doutrina bíblica da expiação.",
            referencias: "Isaías 53:5-6; Romanos 3:23-26; Romanos 5:8-11; 2 Coríntios 5:18-21; Gálatas 3:13; Efésios 2:13-18; Colossenses 1:19-22; Colossenses 2:13-15; 1 Timóteo 2:5-6; Tito 2:13-14; Hebreus 9:11-15; Hebreus 10:1-18; 1 Pedro 2:24; 1 Pedro 3:18; 1 João 2:2; 1 João 4:10"
        },
        {
            termo: "Extra Calvinisticum",
            definicao: "O 'extra calvinisticum' (expressão cunhada por teólogos luteranos para criticar Calvino) é a doutrina calvinista de que o Logos (Verbo) divino, mesmo durante a encarnação, opera também fora da carne assumida (extra carnem). Em outras palavras, a divindade de Cristo não está confinada à sua humanidade. 'O Filho de Deus desceu do céu de tal maneira que, embora tenha assumido a natureza humana, não deixou o céu vazio' (Calvino, Institutas II.13.4). Isto significa que Cristo, como Logos, continua onipresente (atributo divino), mesmo enquanto sua humanidade está no céu (Atos 3:21). A doutrina oposta (luterana) é a ubiquidade da humanidade de Cristo (a humanidade de Cristo participa da onipresença divina). A teologia reformada afirma o 'extra calvinisticum' como uma consequência da definição calcedoniana (as naturezas não se confundem).",
            referencias: "João 1:1-14; João 3:13; Atos 3:21; Filipenses 2:5-11; Colossenses 2:9; 1 Timóteo 3:16"
        },
        {
            termo: "Filho de Davi (Son of David)",
            definicao: "Filho de Davi (huios Dauid) é um título messiânico importante no Novo Testamento, especialmente nos evangelhos de Mateus (1:1; 9:27; 12:23; 15:22; 20:30-31; 21:9,15) e Lucas (1:32-33; 3:23-38). O título significa que Jesus é o descendente legítimo do rei Davi e, portanto, o herdeiro do trono de Israel (2 Samuel 7:12-16; Salmo 89:3-4,35-37). O título também tem conotações messiânicas (Salmo 132:11; Isaías 11:1-10; Jeremias 23:5-6; 33:14-16). A teologia reformada vê em 'Filho de Davi' o cumprimento da aliança davídica: Jesus é o Rei que reina para sempre (Lucas 1:32-33).",
            referencias: "2 Samuel 7:12-16; Salmo 89:3-4; Salmo 110:1; Salmo 132:11; Isaías 11:1-2; Jeremias 23:5-6; Jeremias 33:14-16; Ezequiel 34:23-24; Mateus 1:1-17; Mateus 9:27; Mateus 12:23; Mateus 15:22; Mateus 20:30-31; Mateus 21:9; Mateus 21:15; Lucas 1:32-33; Lucas 3:23-38; Romanos 1:3"
        },
        {
            termo: "Filho de Deus (Son of God)",
            definicao: "Filho de Deus (huios tou theou) é um título central para Jesus no Novo Testamento. Significados: (1) Filho eterno (João 1:1-2,18; 3:16; 17:5): Jesus é o Filho por natureza (não por adoção). (2) Messias (Mateus 16:16; Marcos 14:61-62; Lucas 4:41; João 1:34; 11:27). (3) Revelador do Pai (Mateus 11:27; João 1:18; 14:9-10). (4) Obediente (Filipenses 2:8; Hebreus 5:8). O título 'Filho de Deus' foi mal interpretado pelos arianos (que negavam a divindade do Filho) e pelos adocionistas (que diziam que Jesus se tornou Filho no batismo). A teologia reformada afirma que Jesus é o Filho eterno de Deus, consubstancial ao Pai (Nicéia, 325 d.C.).",
            referencias: "Salmo 2:7; Mateus 3:17; Mateus 16:16; Mateus 17:5; Mateus 27:54; Marcos 1:1; Marcos 1:11; Marcos 9:7; Marcos 14:61-62; Lucas 1:35; Lucas 4:41; Lucas 22:70; João 1:1-2; João 1:18; João 1:34; João 3:16-18; João 5:18; João 10:36; João 11:27; João 20:28; Atos 8:37; Atos 9:20; Romanos 1:4; Gálatas 2:20; Gálatas 4:4; Colossenses 1:13; Hebreus 1:2; 1 João 4:9-10"
        },
        {
            termo: "Filho do Homem (Son of Man)",
            definicao: "Filho do Homem (huios tou anthrōpou) é o título favorito de Jesus para si mesmo nos evangelhos (cerca de 80 vezes). O título deriva de Daniel 7:13-14: 'Eis que vinha nas nuvens do céu um como o filho do homem... e foi-lhe dado domínio, e honra, e reino'. Significados: (1) Humilhação: 'As raposas têm covis... mas o Filho do Homem não tem onde reclinar a cabeça' (Mateus 8:20). (2) Sofrimento: 'O Filho do Homem será entregue nas mãos dos homens, e matá-lo-ão' (Marcos 9:31). (3) Glória futura: 'Quando o Filho do Homem vier na sua glória... então se assentará no trono da sua glória' (Mateus 25:31). (4) Juízo: 'O Pai a ninguém julga, mas deu ao Filho todo o juízo' (João 5:22,27). A teologia reformada vê no título 'Filho do Homem' a afirmação da humanidade de Cristo e de sua identidade como o Messias celestial (Daniel 7).",
            referencias: "Daniel 7:13-14; Mateus 8:20; Mateus 9:6; Mateus 12:8; Mateus 12:40; Mateus 13:41; Mateus 16:13; Mateus 16:27; Mateus 17:22; Mateus 18:11; Mateus 19:28; Mateus 20:28; Mateus 24:30; Mateus 25:31; Mateus 26:64; Marcos 2:10; Marcos 8:31; Marcos 9:31; Marcos 10:45; Marcos 13:26; Marcos 14:62; Lucas 5:24; Lucas 6:5; Lucas 7:34; Lucas 9:22; Lucas 9:44; Lucas 9:58; Lucas 12:8; Lucas 18:31; Lucas 19:10; Lucas 21:27; Lucas 22:48; João 1:51; João 3:13-14; João 5:27; João 6:27; João 6:53; João 6:62; João 8:28; João 12:23; João 13:31; Atos 7:56; Apocalipse 1:13; Apocalipse 14:14"
        },
        {
            termo: "Fórmula de Concórdia (Formula of Concord)",
            definicao: "A Fórmula de Concórdia (Formula Concordiae, 1577 d.C.) é o documento confessional que unificou as igrejas luteranas após a morte de Lutero (1546), resolvendo controvérsias sobre a eucaristia, a ubiquidade da humanidade de Cristo e a comunicação de atributos. A Fórmula afirma: (1) A natureza humana de Cristo está onipresente (ubiquidade) por causa da união hipostática (comunicação real de atributos). (2) A presença real de Cristo na Ceia (consubstanciação). (3) A rejeição da transubstanciação (católica), da presença espiritual (calvinista) e do memorialismo (zwingliano). A teologia reformada rejeita a Fórmula de Concórdia, mantendo a ubiquidade apenas da divindade, não da humanidade de Cristo (extra calvinisticum).",
            referencias: "Mateus 26:26-29; João 1:14; João 6:51-58; Atos 3:21; Filipenses 2:5-11; Colossenses 2:9"
        },
        {
            termo: "Genealogia de Jesus (Genealogy of Jesus)",
            definicao: "Os evangelhos de Mateus (1:1-17) e Lucas (3:23-38) apresentam duas genealogias de Jesus. (1) Genealogia de Mateus: descendência de José (pai legal de Jesus) através de Davi e Salomão, indo de Abraão até Jesus. Mateus organiza a genealogia em três grupos de 14 gerações (total 42). Inclui mulheres (Tamar, Raabe, Rute, Bate-Seba) e reis pecadores, mostrando a graça de Deus. (2) Genealogia de Lucas: descendência de Maria (ou de José, segundo alguns) através de Davi e Natã, indo de Jesus até Adão (enfatizando a universalidade). As duas genealogias diferem entre Davi e José; a tradição explica que Mateus dá a linhagem de José (legal), Lucas a linhagem de Maria (biológica). A teologia reformada aceita as genealogias como historicamente confiáveis e teologicamente significativas: Jesus é o herdeiro legítimo do trono de Davi (Mateus) e o Salvador de todos os seres humanos (Lucas).",
            referencias: "Rute 4:18-22; 1 Crônicas 1-3; Esdras 7:1-5; Neemias 12:1-26; Mateus 1:1-17; Lucas 3:23-38"
        },
        {
            termo: "Geração Eterna do Filho (Eternal Generation of the Son)",
            definicao: "A geração eterna do Filho (generatio aeterna Filii) é a doutrina de que o Filho (Jesus Cristo) é gerado do Pai desde toda a eternidade (não no tempo). 'O Filho é gerado do Pai antes dos séculos' (Credo Niceno). A geração eterna não significa que o Filho é 'criado' (como Ário ensinava) nem que o Filho é 'inferior' ao Pai (subordinacionismo). Significa que o Filho procede do Pai (como fonte), mas é co-eterno e consubstancial (homoousios). A teologia reformada afirma a geração eterna como um mistério (não pode ser explicado racionalmente), baseado em textos como Salmo 2:7 ('Hoje eu te gerei' - entendido como eterno); João 1:1-2,18; 3:16; 17:5; Colossenses 1:15. A geração eterna distingue o Filho do Pai e do Espírito Santo (que procede do Pai e do Filho, Filioque).",
            referencias: "Salmo 2:7; João 1:1-2; João 1:14; João 1:18; João 3:16; João 5:26; João 8:58; João 17:5; Colossenses 1:15; Hebreus 1:1-2; Hebreus 1:5; 1 João 4:9"
        },
        {
            termo: "Graça Comum (Common Grace)",
            definicao: "Graça comum é a doutrina reformada de que Deus concede certos benefícios (não-salvíficos) a todos os seres humanos, independentemente de sua eleição. Estes benefícios incluem: (a) sustento da criação (Mateus 5:45); (b) restrição do pecado (Gênesis 20:6); (c) consciência moral (Romanos 2:14-15); (d) dons culturais e científicos (Êxodo 31:1-11). A graça comum é distinta da graça especial (salvífica), que é concedida apenas aos eleitos, através de Cristo. A teologia reformada (Calvino, Kuyper, Bavinck) desenvolveu a doutrina da graça comum para explicar como os não-crentes podem praticar o bem e como a sociedade pode ser ordenada. A graça comum está baseada na obra de Cristo como sustentador do universo (Colossenses 1:17; Hebreus 1:3).",
            referencias: "Gênesis 20:6; Êxodo 31:1-11; Jó 12:10; Salmo 36:6; Salmo 145:9; Mateus 5:45; Lucas 6:35-36; Romanos 2:14-15; 1 Timóteo 4:10; Hebreus 1:3"
        },

        {
            termo: "Graça de União (Grace of Union) - Continuação",
            definicao: "A graça de união é um conceito tomista e reformado que se refere à graça dada à humanidade de Cristo por sua união com o Verbo (Logos). Diferente da graça habitual (que santifica o crente), a graça de união é a graça de ser a própria humanidade do Verbo encarnado. Cristo, como homem, foi santificado pelo Espírito Santo desde o momento da concepção (Lucas 1:35), mas sua santidade não é apenas 'habitual' (como nos santos), mas 'hipostática' (por causa da união com o Verbo). A teologia reformada (Calvino, Tomás de Aquino) distingue: (a) graça de união: a união da humanidade de Cristo com o Verbo; (b) graça habitual: a plenitude da graça e santidade na alma humana de Cristo (João 1:14; Colossenses 2:9).",
            referencias: "Lucas 1:35; Lucas 4:1; Lucas 4:14; João 1:14; João 1:16; João 3:34; Atos 10:38; Colossenses 1:19; Colossenses 2:9; Hebreus 1:9; 1 João 5:20"
        },
        {
            termo: "Humilhação de Cristo (Humiliation of Christ)",
            definicao: "A humilhação de Cristo (status exinanitionis) é o estado de rebaixamento voluntário do Filho de Deus ao assumir a natureza humana e submeter-se às limitações e ao sofrimento, em contraste com sua exaltação posterior. A doutrina reformada identifica os seguintes aspectos da humilhação: (1) A encarnação: 'esvaziou-se a si mesmo, tomando a forma de servo' (Filipenses 2:7). (2) O nascimento humilde: nascido em uma manjedoura, de pais pobres (Lucas 2:7,24). (3) A sujeição à lei: 'nascido debaixo da lei' (Gálatas 4:4). (4) O sofrimento físico e emocional: fome (Mateus 4:2), sede (João 19:28), cansaço (João 4:6), tristeza (Mateus 26:38). (5) A tentação: foi tentado por Satanás (Mateus 4:1-11; Hebreus 4:15). (6) A perseguição e rejeição: 'veio para o que era seu, e os seus não o receberam' (João 1:11). (7) A morte na cruz: 'obediente até à morte, e morte de cruz' (Filipenses 2:8). (8) O sepultamento: 'feito um pouco menor que os anjos' (Hebreus 2:9). (9) A descida ao inferno (descensus ad inferos): interpretada pelos reformados como o estado de humilhação extrema (não como uma descida literal ao lugar dos mortos para pregar, mas como a experiência do abandono divino na cruz). 'Deus me desamparou' (Mateus 27:46). A teologia reformada enfatiza que a humilhação foi voluntária (João 10:18) e necessária para a expiação dos pecados.",
            referencias: "Mateus 4:1-11; Mateus 27:46; Lucas 2:7; Lucas 2:24; João 1:11; João 4:6; João 10:18; João 19:28; Gálatas 4:4; Filipenses 2:5-8; Hebreus 2:9; Hebreus 4:15"
        },
        {
            termo: "Hipóstase (Hypostasis)",
            definicao: "Hipóstase (do grego hypostasis - 'substância, subsistência, pessoa') é um termo técnico da teologia trinitária e cristológica. Na Trindade, há três hipóstases (Pai, Filho, Espírito Santo) em uma única essência (ousia). Na cristologia, a definição calcedoniana afirma que em Cristo há duas naturezas (divina e humana) em uma só hipóstase (pessoa). O termo foi usado pelos Pais Capadócios (Basílio, Gregório de Nazianzo, Gregório de Nissa) para distinguir as pessoas da Trindade sem cair no triteísmo (três deuses) ou no modalismo (uma pessoa com três modos). A teologia reformada aceita a distinção entre ousia (essência) e hypostasis (pessoa) como fundamental para a doutrina da Trindade e da cristologia. 'O Filho é a hypostasis do Pai' (Atanásio).",
            referencias: "Hebreus 1:3; Hebreus 3:14; João 1:1-2; João 10:30; 2 Coríntios 9:4; Colossenses 2:9"
        },
        {
            termo: "Iconografia de Cristo (Iconography of Christ)",
            definicao: "A iconografia de Cristo refere-se às representações visuais de Jesus na arte cristã. A teologia reformada (Calvino, Zwinglio, os puritanos) tem uma posição iconoclasta: rejeita a veneração de imagens de Cristo como violação do segundo mandamento (Êxodo 20:4-6). No entanto, a tradição reformada permite imagens de Cristo para fins pedagógicos (Bíblias ilustradas, livros didáticos) e estéticos (arte em museus), desde que não sejam adoradas. As principais representações incluem: (1) O Bom Pastor (arte paleocristã). (2) O Pantocrator (arte bizantina). (3) O Cristo em Majestade (arte românica). (4) O Cristo sofredor (arte gótica e barroca). (5) O Cristo homem perfeito (Renascimento). A teologia reformada alerta contra o perigo da idolatria: 'Não farás para ti imagem de escultura, nem alguma semelhança do que há em cima nos céus... não te encurvarás a elas nem as servirás' (Êxodo 20:4-5). Ver Volume XIII (Cristo na Arte, Literatura e Música) para uma análise detalhada.",
            referencias: "Êxodo 20:4-6; Deuteronômio 5:8-10; João 1:14; Atos 17:29; Romanos 1:23; 1 João 5:21"
        },
        {
            termo: "Imitação de Cristo (Imitatio Christi)",
            definicao: "A imitação de Cristo (Imitatio Christi) é o chamado para seguir o exemplo de Jesus em vida, caráter e ações. O apóstolo Paulo exorta: 'Sede meus imitadores, como também eu sou de Cristo' (1 Coríntios 11:1). E Pedro: 'Porque para isto sois chamados, pois também Cristo padeceu por nós, deixando-nos o exemplo, para que sigais as suas pisadas' (1 Pedro 2:21). A teologia reformada ensina que a imitação não é a causa da salvação (justificação), mas o fruto (santificação). 'A fé sem obras é morta' (Tiago 2:26). Aspectos da imitação: (1) Humildade: 'Tende em vós o mesmo sentimento que houve também em Cristo Jesus' (Filipenses 2:5-8). (2) Amor sacrificial: 'Como Cristo amou a igreja e a si mesmo se entregou por ela' (Efésios 5:25). (3) Perdão: 'Perdoai-vos uns aos outros, como também Deus vos perdoou em Cristo' (Efésios 4:32). (4) Obediência: 'Ele foi obediente até à morte' (Filipenses 2:8). (5) Paciência no sofrimento: 'Cristo padeceu por nós, deixando-nos o exemplo' (1 Pedro 2:21). A obra clássica 'Imitação de Cristo', de Tomás de Kempis (c. 1418), é amplamente utilizada na espiritualidade reformada, com ressalvas sobre o monasticismo excessivo.",
            referencias: "João 13:34-35; Romanos 15:1-3; 1 Coríntios 4:16; 1 Coríntios 11:1; Efésios 4:32; Efésias 5:1-2; Filipenses 2:5-8; Colossenses 3:12-14; 1 Tessalonicenses 1:6; 1 Pedro 2:21-25; 1 João 2:6; 1 João 3:16"
        },
        {
            termo: "Impecabilidade de Cristo (Impeccability of Christ)",
            definicao: "A impecabilidade de Cristo é a doutrina de que Jesus era não apenas sem pecado (anartēsia - 'sem pecado'), mas também incapaz de pecar (impeccantia). A Escritura afirma que Cristo 'não cometeu pecado, nem na sua boca se achou engano' (1 Pedro 2:22). 'Nele não há pecado' (1 João 3:5). 'Porque não temos um sumo sacerdote que não possa compadecer-se das nossas fraquezas; porém um que, como nós, em tudo foi tentado, mas sem pecado' (Hebreus 4:15). A teologia reformada distingue entre: (a) Anartēsia (ausência de pecado): Cristo nunca pecou. (b) Impeccantia (incapacidade de pecar): Cristo não podia pecar por causa da união hipostática (sua natureza humana estava hipostaticamente unida à natureza divina). Calvino ensina que Cristo foi tentado, mas sem pecado, e que sua vontade humana era perfeitamente conformada à vontade divina. A impecabilidade não nega a realidade da tentação (Cristo foi genuinamente tentado), mas afirma que ele não podia ceder ao pecado. 'O príncipe deste mundo vem, e nada tem em mim' (João 14:30).",
            referencias: "Mateus 4:1-11; Lucas 4:1-13; João 8:46; João 14:30; Romanos 8:3; 2 Coríntios 5:21; Hebreus 4:15; Hebreus 7:26; 1 Pedro 2:22; 1 João 3:5"
        },
        {
            termo: "Inerrância Bíblica (Biblical Inerrancy)",
            definicao: "A inerrância bíblica é a doutrina de que a Escritura, em seus manuscritos originais, é totalmente verdadeira e sem erro em tudo o que afirma, incluindo questões históricas, científicas e teológicas. A teologia reformada (Warfield, Hodge, Berkhof) afirma a inerrância como corolário da inspiração divina: 'Toda a Escritura é inspirada por Deus e útil para o ensino, para a repreensão, para a correção, para a instrução na justiça' (2 Timóteo 3:16). 'A tua palavra é a verdade' (João 17:17). Para a cristologia, a inerrância é fundamental, pois as afirmações dos evangelhos sobre a divindade, os milagres e a ressurreição de Cristo são históricas e verdadeiras. A Declaração de Chicago sobre a Inerrância Bíblica (1978) afirmou: 'A Escritura é inerrante, sendo livre de falsidade, engano ou erro.' A teologia reformada confessa a inerrância da Escritura, mas distingue entre os autógrafos originais (perdidos) e as cópias manuscritas (que podem conter erros textuais, mas não doutrinários).",
            referencias: "Salmo 12:6; Salmo 119:89; Salmo 119:105; João 10:35; João 17:17; Atos 24:14; 2 Timóteo 3:16-17; 2 Pedro 1:19-21"
        },
        {
            termo: "Intercessão de Cristo (Intercession of Christ)",
            definicao: "A intercessão de Cristo é o ministério celestial de Jesus como sumo sacerdote, no qual ele ora e intercede por seu povo diante de Deus Pai. 'Porque também Cristo não entrou num santuário feito por mãos, figura do verdadeiro, porém no mesmo céu, para agora comparecer por nós diante da face de Deus' (Hebreus 9:24). 'Cristo Jesus é o que morreu, ou antes, o que ressuscitou dentre os mortos, o qual está à direita de Deus, e também intercede por nós' (Romanos 8:34). 'Portanto, pode também salvar perfeitamente os que por ele se chegam a Deus, vivendo sempre para interceder por eles' (Hebreus 7:25). A intercessão de Cristo é: (a) Perfeita: ele conhece todas as nossas necessidades. (b) Contínua: 'vivendo sempre para interceder'. (c) Eficaz: o Pai sempre o ouve. (d) Baseada em seu sacrifício: ele intercede com base em sua morte expiatória. A teologia reformada enfatiza que a intercessão de Cristo é a fonte de nossa segurança e confiança na oração (Hebreus 4:14-16). 'Se alguém pecar, temos um Advogado para com o Pai, Jesus Cristo, o justo' (1 João 2:1).",
            referencias: "João 14:16; João 16:23-24; Romanos 8:34; Hebreus 4:14-16; Hebreus 7:25; Hebreus 9:24; 1 João 2:1-2"
        },
        {
            termo: "Jesus Histórico (Historical Jesus)",
            definicao: "O termo 'Jesus histórico' refere-se a Jesus de Nazaré como figura histórica, distinto do 'Cristo da fé' proclamado pela igreja. A 'busca pelo Jesus histórico' (Leben-Jesu-Forschung) foi um movimento acadêmico iniciado no século XVIII (Reimarus, Strauss, Renan) que tentou reconstruir a vida de Jesus usando métodos histórico-críticos. A teologia reformada afirma que o Jesus da história é o Cristo da fé (Lucas 24:27,44-45). Os evangelhos são testemunhos históricos confiáveis (Lucas 1:1-4; João 20:30-31; 1 Coríntios 15:3-8). A 'terceira busca' (desde 1980, representada por N.T. Wright, J.D.G. Dunn, E.P. Sanders) é mais respeitosa da historicidade dos evangelhos. A teologia reformada rejeita: (a) O ceticismo radical de Bultmann (pouco se pode saber sobre Jesus). (b) A separação entre Jesus histórico (humano) e Cristo da fé (divino). A confiabilidade histórica dos evangelhos é essencial para a fé cristã: 'Se Cristo não ressuscitou, é vã a vossa fé' (1 Coríntios 15:17).",
            referencias: "Lucas 1:1-4; Lucas 24:27; Lucas 24:44-45; João 20:30-31; Atos 1:1-3; 1 Coríntios 15:3-8; 2 Pedro 1:16-21; 1 João 1:1-4"
        },
        {
            termo: "Julgamento de Cristo (Judgment of Christ)",
            definicao: "O julgamento de Cristo refere-se tanto ao julgamento histórico de Jesus perante as autoridades judaicas e romanas, quanto ao julgamento escatológico que ele realizará na segunda vinda. (1) Julgamento histórico: Jesus foi julgado pelo Sinédrio (Mateus 26:57-68; Marcos 14:53-65; Lucas 22:54-71) e por Pôncio Pilatos (Mateus 27:11-26; Marcos 15:1-15; Lucas 23:1-25; João 18:28-19:16). Foi condenado à morte por crucificação. (2) Julgamento escatológico: Jesus é o juiz designado por Deus para julgar os vivos e os mortos. 'O Pai a ninguém julga, mas deu ao Filho todo o juízo' (João 5:22). 'Porque há um dia em que há de julgar o mundo com justiça, por meio do varão que para isso ordenou' (Atos 17:31). A teologia reformada ensina que o julgamento final será: (a) Universal: todos os seres humanos. (b) Baseado nas obras (como evidência da fé). (c) Justo: Cristo julgará com justiça perfeita. (d) Determinante: os justos irão para a vida eterna, os ímpios para o castigo eterno (Mateus 25:31-46).",
            referencias: "João 5:22-27; Atos 10:42; Atos 17:31; Romanos 2:16; Romanos 14:10-12; 2 Coríntios 5:10; 2 Timóteo 4:1; Apocalipse 20:11-15"
        },
        {
            termo: "Justificação pela Fé (Justification by Faith)",
            definicao: "A justificação pela fé é a doutrina central da Reforma Protestante, afirmando que o pecador é declarado justo diante de Deus somente pela fé em Jesus Cristo, não por obras da lei. 'Porque pensamos que o homem é justificado pela fé, sem as obras da lei' (Romanos 3:28). 'Sabendo que o homem não é justificado pelas obras da lei, senão pela fé em Jesus Cristo, temos também crido em Jesus Cristo, para sermos justificados pela fé em Cristo, e não pelas obras da lei' (Gálatas 2:16). A teologia reformada distingue entre: (a) Justificação (ato forense de Deus declarando o pecador justo com base na justiça imputada de Cristo). (b) Santificação (processo pelo qual Deus torna o crente mais santo). A justificação é pela fé somente (sola fide), mas a fé que justifica não está sozinha (é acompanhada por obras, como evidência). 'Porque somos feitura sua, criados em Cristo Jesus para as boas obras' (Efésios 2:10). A justificação é baseada na obediência ativa (cumprimento da lei) e passiva (morte) de Cristo, imputada ao crente.",
            referencias: "Isaías 53:11; Habacuque 2:4; João 3:16; Atos 13:38-39; Romanos 1:17; Romanos 3:21-28; Romanos 4:1-8; Romanos 5:1-2; 2 Coríntios 5:21; Gálatas 2:16; Gálatas 3:6-14; Efésios 2:8-10; Filipenses 3:9; Tito 3:5-7"
        },
        {
            termo: "Kenosis (Esvaziamento)",
            definicao: "Kenosis (do grego kenōsis - 'esvaziamento') é o termo usado em Filipenses 2:7: 'Mas esvaziou-se a si mesmo (ekenōsen), tomando a forma de servo, fazendo-se semelhante aos homens'. A doutrina da kenosis refere-se à humilhação voluntária de Cristo ao assumir a natureza humana. A teologia reformada (Calvino) ensina que a kenosis não significa que Cristo deixou de ser Deus (impossível), mas que ele: (a) Não usou egoistamente seus atributos divinos (não os exerceu para seu próprio benefício). (b) Assumiu as limitações da natureza humana (fome, sede, cansaço, dor, morte). (c) Ocultou sua glória divina (exceto na transfiguração). A kenosis não implica a perda de atributos divinos (onisciência, onipotência, onipresença), mas o não exercício independente deles. O 'extra calvinisticum' (Logos opera também fora da carne) preserva a onipresença de Cristo enquanto sua humanidade estava limitada. A teologia kenótica liberal (século XIX) ensinava que Cristo abandonou atributos divinos (heresia rejeitada).",
            referencias: "João 1:14; João 5:19; João 5:30; João 6:38; João 10:18; 2 Coríntios 8:9; Filipenses 2:5-8; Colossenses 2:9"
        },
        {
            termo: "Lei e Cristo (Law and Christ)",
            definicao: "A relação entre a lei (Torá) e Jesus Cristo é um tema central da teologia reformada. Jesus declarou: 'Não penseis que vim destruir a lei ou os profetas; não vim destruir, mas cumprir' (Mateus 5:17). O apóstolo Paulo escreveu: 'Porque o fim da lei é Cristo para justiça de todo aquele que crê' (Romanos 10:4). A teologia reformada (Calvino, Westminster) distingue três usos da lei: (1) Usus politicus (civil): refrear o pecado na sociedade. (2) Usus elenchticus (pedagógico): convencer o pecador de seu pecado e levá-lo a Cristo (Gálatas 3:24). (3) Usus didacticus (normativo): guiar o crente na santificação. Cristo cumpriu a lei de três maneiras: (a) Obediência ativa: cumpriu perfeitamente os mandamentos da lei. (b) Obediência passiva: sofreu a penalidade da lei por nós. (c) Interpretação: deu o verdadeiro sentido da lei (Sermão do Montanha). Os crentes não estão debaixo da lei como meio de justificação (Romanos 6:14), mas estão debaixo da lei como regra de vida (1 Coríntios 9:21). A lei moral (dez mandamentos) permanece obrigatória para o crente, pois reflete o caráter de Deus.",
            referencias: "Êxodo 20:1-17; Deuteronômio 5:6-21; Mateus 5:17-48; Romanos 3:19-20; Romanos 6:14-15; Romanos 7:1-25; Romanos 8:1-4; Romanos 10:4; 1 Coríntios 9:21; Gálatas 3:10-14; Gálatas 3:24-25; Efésios 2:15; Colossenses 2:14; 1 Timóteo 1:8-11"
        },
        {
            termo: "Leão de Judá (Lion of Judah)",
            definicao: "Leão de Judá é um título messiânico aplicado a Jesus Cristo no Apocalipse: 'Não chores; eis aqui o Leão da tribo de Judá, a Raiz de Davi, que venceu, para abrir o livro e desatar os seus sete selos' (Apocalipse 5:5). O título tem raízes no Antigo Testamento: Jacó profetizou sobre Judá: 'Judá é um leãozinho... o cetro não se arredará de Judá' (Gênesis 49:9-10). O título enfatiza: (1) A realeza de Cristo: ele é o Rei dos reis. (2) A força e poder de Cristo: o leão é o rei dos animais. (3) A vitória de Cristo: o Leão venceu (a morte, o pecado, Satanás). Paradoxalmente, no mesmo contexto (Apocalipse 5:6), o Leão também é o Cordeiro que foi morto. A teologia reformada vê no Leão de Judá a afirmação da realeza e da vitória de Cristo sobre todos os inimigos (1 Coríntios 15:24-28). 'Reinará para sempre' (Lucas 1:33).",
            referencias: "Gênesis 49:9-10; Números 24:9; Apocalipse 5:5-6; Apocalipse 19:11-16; Apocalipse 22:16"
        },
        {
            termo: "Logos (Verbo)",
            definicao: "Logos (do grego logos - 'palavra, razão, discurso') é o título usado por João para identificar Jesus como a Palavra eterna de Deus. 'No princípio era o Verbo, e o Verbo estava com Deus, e o Verbo era Deus' (João 1:1). 'E o Verbo se fez carne, e habitou entre nós, e vimos a sua glória, glória como do unigênito do Pai, cheio de graça e de verdade' (João 1:14). O conceito de Logos tem raízes: (1) No Antigo Testamento: a Palavra de Deus como agente da criação (Salmo 33:6) e da revelação (Isaías 55:11). (2) No judaísmo helenístico: Filão de Alexandria (20 a.C.-50 d.C.) identificou o Logos como o mediador da criação. (3) Na filosofia grega: o Logos como princípio racional do universo. O Evangelho de João cristianiza o conceito: o Logos não é um princípio impessoal, mas uma pessoa, o Filho eterno de Deus, que se encarnou. A teologia reformada vê no Logos a pré-existência e divindade de Cristo. 'Apocalipse 19:13 também identifica Cristo como 'o Verbo de Deus'.",
            referencias: "Gênesis 1:1-3; Salmo 33:6; Provérbios 8:22-31; João 1:1-18; Apocalipse 19:13"
        },
        {
            termo: "Lutero, Martinho (1483-1546) - Cristologia",
            definicao: "Martinho Lutero, reformador alemão, desenvolveu uma cristologia distinta, conhecida como 'teologia da cruz' (theologia crucis). Pontos principais: (1) Teologia da cruz: o verdadeiro conhecimento de Deus é encontrado no sofrimento e humilhação de Cristo, não na glória e poder (Heidelberg Disputation, 1518). (2) Ubiquidade (onipresença) da humanidade de Cristo: por causa da união hipostática, a natureza humana de Cristo participa da onipresença divina (necessário para sua doutrina da presença real na Ceia). (3) Presença real na Ceia: Cristo está verdadeiramente presente 'com, sob e nas' formas do pão e do vinho (consubstanciação). (4) Comunicação de atributos real: os atributos divinos são comunicados à humanidade de Cristo de modo real (a humanidade se torna onipresente). (5) Solus Christus: Cristo é o único mediador entre Deus e os homens. (6) Justificação pela fé na obra de Cristo. A teologia reformada (Calvino) rejeita a ubiquidade luterana (extra calvinisticum) e a presença real (presença espiritual). Ver Volume V (Cristologia da Reforma) e Volume XIV (Dicionário Biográfico).",
            referencias: "João 1:14; Atos 3:21; Romanos 3:23-26; 1 Coríntios 1:18-25; Filipenses 2:5-11; Gálatas 2:16; Gálatas 6:14; Colossenses 2:9"
        },
        {
            termo: "Mediador (Mediator)",
            definicao: "Mediador (do latim mediator - 'intermediário') é um título de Cristo que enfatiza seu papel como único intermediário entre Deus e os homens. 'Porque há um só Deus, e um só Mediador entre Deus e os homens, Jesus Cristo homem' (1 Timóteo 2:5). A mediação de Cristo envolve: (1) Sua pessoa: ele é Deus e homem, capaz de representar ambas as partes. (2) Sua obra: ele reconciliou Deus e os homens por meio de sua morte (Hebreus 9:15). (3) Sua intercessão: ele intercede continuamente por nós (Hebreus 7:25). (4) Sua revelação: ele revela o Pai a nós (João 1:18). A teologia reformada rejeita qualquer mediação de Maria, dos santos ou dos sacerdotes (catolicismo). 'Não há outro nome debaixo do céu dado entre os homens pelo qual devamos ser salvos' (Atos 4:12). A mediação de Cristo é exclusiva e suficiente (Hebreus 8:6; 9:15; 12:24).",
            referencias: "Jó 9:33; João 14:6; Atos 4:12; Romanos 8:34; Gálatas 3:19-20; 1 Timóteo 2:5; Hebreus 8:6; Hebreus 9:15; Hebreus 12:24; 1 João 2:1"
        },
        {
            termo: "Melquisedeque (Melchizedek)",
            definicao: "Melquisedeque, rei de Salém (paz) e sacerdote do Deus Altíssimo, é uma figura do Antigo Testamento que aparece em Gênesis 14:18-20, abençoando Abraão e recebendo dízimos dele. O Salmo 110:4 profetiza que o Messias seria 'sacerdote para sempre, segundo a ordem de Melquisedeque'. A Epístola aos Hebreus desenvolve este tipo (Hebreus 5:6,10; 6:20; 7:1-28). Paralelos entre Melquisedeque e Cristo: (1) 'Sem pai, sem mãe, sem genealogia' (Hebreus 7:3) - tipologicamente, seu sacerdócio não depende de linhagem. (2) 'Sacerdote para sempre' (Hebreus 7:3) - Cristo é sacerdote eterno. (3) 'Rei de justiça' (Melquisedeque) e 'Rei de paz' (rei de Salém) - Cristo é Rei de justiça e paz (Isaías 9:6-7). (4) Superioridade do sacerdócio de Melquisedeque sobre o levítico: Abraão (e portanto Levi) pagou dízimos a Melquisedeque (Hebreus 7:4-10). A teologia reformada vê em Melquisedeque um tipo claro do sacerdócio eterno de Cristo, que não depende de genealogia (não levítico) e é superior ao sacerdócio levítico (Hebreus 7:11-28).",
            referencias: "Gênesis 14:18-20; Salmo 110:4; Hebreus 5:6; Hebreus 5:10; Hebreus 6:20; Hebreus 7:1-28"
        },
        {
            termo: "Messias (Messiah)",
            definicao: "Messias (do hebraico Mashiach - 'Ungido') é o título equivalente ao grego Christos (Cristo). No Antigo Testamento, reis (1 Samuel 10:1), sacerdotes (Êxodo 29:7) e profetas (1 Reis 19:16) eram ungidos com óleo como sinal de consagração a Deus. O Messias prometido seria o Ungido por excelência, que cumpriria os três ofícios: profeta (Deuteronômio 18:15-19), sacerdote (Salmo 110:4) e rei (2 Samuel 7:12-16). Jesus é o Messias prometido. 'Pedro respondeu: Tu és o Cristo (Messias), o Filho do Deus vivo' (Mateus 16:16). 'André... encontrou primeiro a seu irmão Simão, e disse-lhe: Temos achado o Messias (que, traduzido, é o Cristo)' (João 1:41). 'A mulher disse: Eu sei que o Messias (que se chama o Cristo) vem; quando ele vier, nos anunciará tudo. Jesus disse: Eu o sou, eu que falo contigo' (João 4:25-26). A teologia reformada afirma que Jesus é o Messias prometido que cumpriu todas as profecias do Antigo Testamento (Lucas 24:27,44-45).",
            referencias: "1 Samuel 2:10; 2 Samuel 7:12-16; Salmo 2:2; Salmo 18:50; Isaías 61:1-3; Daniel 9:25-26; Mateus 1:1; Mateus 16:16; Lucas 2:11; Lucas 4:18-21; João 1:41; João 4:25-26; Atos 2:36; Atos 10:38"
        },
        {
            termo: "Milagres de Cristo (Miracles of Christ)",
            definicao: "Os milagres de Jesus são sinais (sēmeia) que demonstram sua divindade e a chegada do Reino de Deus. João escreve: 'Estes, porém, foram escritos para que creiais que Jesus é o Cristo, o Filho de Deus, e para que, crendo, tenhais vida em seu nome' (João 20:31). Categorias de milagres: (1) Curas: leprosos (Mateus 8:2-4), cegos (João 9:1-12), paralíticos (Mateus 9:1-8), coxos (Mateus 15:30-31), surdos-mudos (Marcos 7:31-37), enfermos (Mateus 8:14-15). (2) Expulsão de demônios: endemoninhado gadareno (Mateus 8:28-34), mudo (Mateus 9:32-34). (3) Ressurreição de mortos: filha de Jairo (Mateus 9:18-26), filho da viúva de Naim (Lucas 7:11-17), Lázaro (João 11:38-44). (4) Autoridade sobre a natureza: acalma a tempestade (Mateus 8:23-27), anda sobre o mar (Mateus 14:22-33), multiplicação dos pães (Mateus 14:13-21), água transformada em vinho (João 2:1-11). A teologia reformada vê os milagres como evidência da divindade de Cristo (Atos 2:22: 'Jesus Nazareno, varão aprovado por Deus entre vós com maravilhas, prodígios e sinais'). Os milagres não são violações das leis da natureza, mas a ação do Criador sobre sua criação. Ver Volume XXVIII (Apêndice - Tabela dos Milagres).",
            referencias: "Êxodo 4:21; Salmo 78:12-16; Isaías 35:5-6; Mateus 4:23-24; Mateus 8-9; Mateus 14-15; Marcos 1-8; Lucas 4-9; João 2; João 4-6; João 9; João 11; Atos 2:22; Atos 10:38"
        },
        {
            termo: "Missão de Cristo (Mission of Christ)",
            definicao: "A missão de Cristo é o propósito pelo qual o Filho de Deus foi enviado ao mundo pelo Pai. Jesus declarou: 'Porque o Filho do Homem veio buscar e salvar o que se havia perdido' (Lucas 19:10). 'Porque Deus enviou o seu Filho ao mundo, não para que condenasse o mundo, mas para que o mundo fosse salvo por ele' (João 3:17). A missão de Cristo inclui: (1) Revelar o Pai: 'Quem me vê a mim vê o Pai' (João 14:9). (2) Cumprir a lei e os profetas (Mateus 5:17). (3) Dar a sua vida em resgate por muitos (Mateus 20:28; Marcos 10:45). (4) Destruir as obras do diabo (1 João 3:8). (5) Chamar os pecadores ao arrependimento (Lucas 5:32). (6) Dar vida eterna aos que creem (João 10:10). (7) Estabelecer o Reino de Deus (Marcos 1:15). (8) Enviar o Espírito Santo (João 16:7). (9) Julgar o mundo (João 5:22). (10) Reconciliar todas as coisas consigo (Colossenses 1:20). A teologia reformada enfatiza que a missão de Cristo foi planejada desde a eternidade (Efésios 1:4-5; 1 Pedro 1:20) e é eficaz para os eleitos.",
            referencias: "Isaías 61:1-3; Mateus 9:13; Mateus 20:28; Marcos 10:45; Lucas 4:18-19; Lucas 19:10; João 3:16-17; João 5:30; João 6:38-40; João 10:10; João 12:47; 1 Timóteo 1:15; 1 João 3:8; 1 João 4:14"
        },
        {
            termo: "Monofisismo (Monophysitism)",
            definicao: "O Monofisismo (do grego monos - 'um só' + physis - 'natureza') é uma heresia cristológica do século V que ensinava que em Cristo há apenas uma natureza (a divina absorveu a humana). Foi ensinado por Eutiques (c. 378-454 d.C.), arquimandrita de Constantinopla, e condenado pelo Concílio de Calcedônia (451 d.C.). Os monofisitas (não calcedonianos) formaram as igrejas ortodoxas orientais: copta (Egito), siríaca (Síria), armênia, etíope, eritreia. A teologia reformada rejeita o monofisismo, afirmando a definição calcedoniana: 'duas naturezas, sem confusão, sem mudança, sem divisão, sem separação'. Cristo é verdadeiramente Deus e verdadeiramente homem, com duas naturezas distintas (mas não separadas) em uma pessoa. 'O Verbo se fez carne' (João 1:14) significa que o Verbo assumiu a natureza humana, não que a natureza humana foi absorvida pela divina.",
            referencias: "João 1:14; Romanos 1:3-4; Filipenses 2:5-11; Colossenses 2:9; 1 Timóteo 3:16; Tito 2:13; 1 João 4:2-3"
        },
        {
            termo: "Monotelismo (Monothelitism)",
            definicao: "O Monotelismo (do grego monos - 'um só' + thelēma - 'vontade') é uma heresia cristológica do século VII que ensinava que Cristo tem uma só vontade (divina) e uma só operação, embora duas naturezas. Surgiu como uma tentativa de reconciliar os monofisitas com a igreja calcedoniana. Foi condenado pelo Concílio de Constantinopla III (680-681 d.C.), que afirmou que Cristo tem duas vontades (divina e humana) e duas operações. A vontade humana de Cristo era impecável (não podia pecar) e sempre conformada à vontade divina. 'Desci do céu, não para fazer a minha vontade, mas a vontade daquele que me enviou' (João 6:38). 'Pai, se queres, passa de mim este cálice; todavia não se faça a minha vontade, mas a tua' (Lucas 22:42). A teologia reformada segue Constantinopla III, afirmando duas vontades em Cristo.",
            referencias: "João 4:34; João 5:30; João 6:38; Mateus 26:39; Mateus 26:42; Lucas 22:42; Filipenses 2:8; Hebreus 5:8; Hebreus 10:7; Hebreus 10:9"
        },
        {
            termo: "Munus Triplex (Três Ofícios)",
            definicao: "Munus triplex (do latim - 'três ofícios') é a doutrina de que Cristo exerce os ofícios de Profeta, Sacerdote e Rei. Foi sistematicamente desenvolvida por João Calvino (Institutas II.15). (1) Profeta: Cristo revela a vontade de Deus e nos ensina. 'O Senhor teu Deus levantará um profeta do meio de ti... a ele ouvireis' (Deuteronômio 18:15-19; Atos 3:22-23). (2) Sacerdote: Cristo ofereceu a si mesmo em sacrifício pelos pecados e intercede por nós. 'Ele é o sumo sacerdote... que sempre vive para interceder por nós' (Hebreus 4:14-16; 7:25). (3) Rei: Cristo governa a igreja e o universo. 'Toda a autoridade me foi dada no céu e na terra' (Mateus 28:18). 'Reinará para sempre' (Lucas 1:33). A teologia reformada enfatiza que estes três ofícios são exercidos por Cristo simultaneamente, e os crentes participam deles: profeticamente (testemunham), sacerdotalmente (oferecem sacrifícios espirituais, 1 Pedro 2:5,9) e realmente (reinam com Cristo, Apocalipse 22:5).",
            referencias: "Deuteronômio 18:15-19; Salmo 2; Salmo 110; Isaías 9:6-7; Isaías 61:1-3; Daniel 7:13-14; Mateus 28:18; Lucas 1:32-33; Lucas 4:18-21; Atos 3:22-23; Hebreus 4:14-16; Hebreus 7:25; 1 Pedro 2:5; 1 Pedro 2:9; Apocalipse 17:14; Apocalipse 22:5"
        }
    ]
};