// volume/volume-61.js
window.LIVRO_DATA = {
    nome: "Volume LXI",
    dados: [
        {
            termo: "01. Introdução: Cristo nos Salmos - A Chave Hermenêutica",
            definicao: "O livro dos Salmos (Tehilim) é o hinário do Antigo Testamento e uma das fontes mais ricas da cristologia. O próprio Jesus declarou que os Salmos testificam dele: 'E disse-lhes: Estas são as palavras que vos disse, estando ainda convosco, que convinha que se cumprisse tudo o que de mim está escrito na lei de Moisés, e nos profetas e nos salmos' (Lucas 24:44). Os Salmos messiânicos são aqueles que profetizam sobre a pessoa, o sofrimento, a morte, a ressurreição, a ascensão e o reinado de Jesus Cristo. A teologia reformada (Calvino, Spurgeon) sempre viu Cristo nos Salmos. 'E, começando por Moisés e por todos os profetas, explicava-lhes o que dele se achava em todas as Escrituras' (Lucas 24:27). Este volume explora os principais Salmos messiânicos: Salmos 2, 8, 16, 22, 23, 24, 31, 34, 40, 41, 45, 68, 69, 72, 89, 102, 110, 118, 132, e muitos outros. 'Examinais as Escrituras, porque vós cuidais ter nelas a vida eterna, e são elas que de mim testificam' (João 5:39).",
            referencias: "Lucas 24:27; Lucas 24:44-45; João 5:39; Atos 2:25-36; Atos 13:32-37; Hebreus 1:5-14; 1 Pedro 1:10-12"
        },
        {
            termo: "02. Salmo 1 - O Homem Bem-Aventurado e o Justo Perfeito",
            definicao: "Salmo 1 descreve o 'homem bem-aventurado' que não anda segundo o conselho dos ímpios, mas tem o seu prazer na lei do Senhor. Este homem é um tipo de Cristo, o único homem perfeitamente justo que cumpriu toda a lei. 'Bem-aventurado o varão que não anda segundo o conselho dos ímpios, nem se detém no caminho dos pecadores, nem se assenta na roda dos escarnecedores. Antes tem o seu prazer na lei do Senhor, e na sua lei medita de dia e de noite' (Salmo 1:1-2). Cumprimento em Cristo: (1) Jesus é o 'Justo' por excelência (Atos 3:14; 7:52; 22:14). (2) Jesus cumpriu a lei perfeitamente (Mateus 5:17). (3) Jesus meditava na Palavra (Lucas 2:46-47; 4:16-21). (4) A árvore plantada junto a ribeiros de águas (Salmo 1:3) tipifica Cristo como a videira verdadeira (João 15:1-8) e a fonte de água viva (João 4:10-14). (5) O ímpio será como a palha que o vento espalha (Salmo 1:4) - contraste com o juízo sobre os ímpios no fim (Mateus 13:41-42). A teologia reformada vê no Salmo 1 o retrato do homem perfeito que é Cristo e, por união com Ele, dos crentes que são justificados pela fé.",
            referencias: "Salmo 1:1-6; Mateus 5:17; Lucas 2:46-47; João 4:10-14; João 15:1-8; Atos 3:14; Romanos 8:1-4; Filipenses 3:9; Colossenses 1:22"
        },
        {
            termo: "03. Salmo 2 - O Rei Ungido e o Filho de Deus",
            definicao: "Salmo 2 é um dos mais importantes Salmos messiânicos, descrevendo a rebelião das nações contra o Senhor e o seu Ungido, e a vitória do Rei estabelecido por Deus. 'Por que se amotinam as nações, e os povos imaginam coisas vãs? Os reis da terra se levantam, e os príncipes juntamente consultam contra o Senhor e contra o seu ungido' (Salmo 2:1-2). 'Tu és meu Filho; eu hoje te gerei' (Salmo 2:7). 'Beijai o Filho, para que se não ire, e pereçais no caminho' (Salmo 2:12). Cumprimento em Cristo: (1) 'Ungido' (Messias) refere-se a Jesus (Atos 4:25-27; 13:33). (2) 'Tu és meu Filho, eu hoje te gerei' é aplicado à ressurreição de Cristo (Atos 13:33; Hebreus 1:5; 5:5). (3) A rebelião das nações cumpriu-se na crucificação (Atos 4:25-28). (4) 'Pedi-me, e eu te darei as nações por herança' (Salmo 2:8) - Cristo reina sobre todas as nações (Mateus 28:18; Apocalipse 2:26-27). (5) 'Beijai o Filho' é o chamado ao arrependimento e à fé em Cristo. (6) 'Quebrá-los-ás com uma vara de ferro' (Salmo 2:9) é aplicado a Cristo em Apocalipse 2:26-27; 12:5; 19:15. A teologia reformada vê no Salmo 2 a afirmação da divindade e realeza de Cristo.",
            referencias: "Salmo 2:1-12; Atos 4:25-28; Atos 13:33; Romanos 1:4; Hebreus 1:5; Hebreus 5:5; Apocalipse 2:26-27; Apocalipse 12:5; Apocalipse 19:15"
        },
        {
            termo: "04. Salmo 8 - A Glória de Cristo e a Encarnação",
            definicao: "Salmo 8 exalta a glória de Deus na criação e o lugar do homem na criação, mas é aplicado por Hebreus a Jesus Cristo. 'Ó Senhor, Senhor nosso, quão admirável é o teu nome em toda a terra!' (Salmo 8:1). 'Que é o homem, para que te lembres dele? e o filho do homem, para que o visites? Contudo, pouco menor que os anjos o fizeste, e de glória e de honra o coroaste' (Salmo 8:4-5). Cumprimento em Cristo: (1) O autor de Hebreus aplica este Salmo a Jesus: 'Mas alguém em certo lugar testificou, dizendo: Que é o homem, para que te lembres dele? ou o filho do homem, para que o visites? Tu o fizeste um pouco menor que os anjos; de glória e de honra o coroaste' (Hebreus 2:6-9). (2) 'Pouco menor que os anjos' refere-se à encarnação de Cristo (Filipenses 2:7-8). (3) 'De glória e de honra o coroaste' refere-se à exaltação de Cristo (Filipenses 2:9-11). (4) 'Todas as coisas sujeitaste debaixo de seus pés' (Hebreus 2:8; 1 Coríndios 15:27). (5) Jesus é o 'Filho do Homem' (Daniel 7:13-14) que veio para salvar. A teologia reformada vê no Salmo 8 a humilhação e exaltação de Cristo.",
            referencias: "Salmo 8:1-9; Hebreus 2:5-9; 1 Coríndios 15:27; Efésios 1:22; Filipenses 2:5-11; Daniel 7:13-14"
        },
        {
            termo: "05. Salmo 16 - A Ressurreição do Santo de Deus",
            definicao: "Salmo 16 é um Salmo messiânico que profetiza sobre a ressurreição de Cristo. 'Porque não deixarás a minha alma no inferno, nem permitirás que o teu Santo veja corrupção' (Salmo 16:10). Cumprimento em Cristo: (1) Pedro aplica este Salmo a Jesus em seu sermão de Pentecostes: 'Porque dele disse Davi: Sempre via diante de mim o Senhor... Porque não deixarás a minha alma no inferno, nem permitirás que o teu Santo veja corrupção' (Atos 2:25-31). (2) Paulo também aplica a ressurreição de Cristo (Atos 13:35-37). (3) Davi morreu e viu corrupção (seu corpo se decompôs); Jesus ressuscitou e não viu corrupção (Atos 2:29-32). (4) 'Tu me farás ver a vereda da vida; na tua presença há plenitude de alegria' (Salmo 16:11) - a vida eterna em Cristo. (5) O 'Santo de Deus' é Cristo (Marcos 1:24; Lucas 4:34). A teologia reformada vê no Salmo 16 a profecia da ressurreição de Cristo e da vida eterna.",
            referencias: "Salmo 16:1-11; Atos 2:25-32; Atos 13:35-37; Romanos 6:9; 1 Coríndios 15:4; 1 Pedro 1:3-4"
        },
        {
            termo: "06. Salmo 22 - A Crucificação do Messias",
            definicao: "Salmo 22 é o mais detalhado Salmo messiânico sobre a crucificação de Jesus, escrito séculos antes de Cristo. 'Deus meu, Deus meu, por que me desamparaste?' (Salmo 22:1). 'Todos os que me veem zombam de mim... Confiou no Senhor, que o livre' (Salmo 22:7-8). 'Porque muitos cães me têm rodeado; o ajuntamento de malfeitores me cercou; traspassaram as minhas mãos e os meus pés' (Salmo 22:16). 'Repartem entre si as minhas vestes, e lançam sortes sobre a minha túnica' (Salmo 22:18). Cumprimento em Cristo: (1) 'Deus meu, Deus meu, por que me desamparaste?' - as palavras de Jesus na cruz (Mateus 27:46; Marcos 15:34). (2) As zombarias (Mateus 27:39-44; Marcos 15:29-32). (3) 'Traspassaram as minhas mãos e os meus pés' - a crucificação (Lucas 23:33; João 20:25-27). (4) 'Repartem as minhas vestes... lançam sortes sobre a minha túnica' (Mateus 27:35; João 19:23-24). (5) 'Estou derramado como água... o meu coração é como cera, derreteu-se' (Salmo 22:14-15) - descrição da agonia na cruz. (6) 'A minha língua se apega ao meu paladar' - 'Tenho sede' (João 19:28). (7) 'Eles olham e me veem' - a multidão observava (Lucas 23:35). (8) 'O Senhor não o desprezou' (Salmo 22:24) - a ressurreição. (9) 'Todas as famílias das nações adorarão' (Salmo 22:27) - o evangelho aos gentios. A teologia reformada vê no Salmo 22 a descrição mais detalhada da crucificação de Cristo.",
            referencias: "Salmo 22:1-31; Mateus 27:35-46; Marcos 15:24-34; Lucas 23:33-49; João 19:18-30; Hebreus 2:11-12"
        },
        {
            termo: "07. Salmo 23 - O Bom Pastor",
            definicao: "Salmo 23 é o mais amado Salmo, descrevendo o Senhor como Pastor. 'O Senhor é o meu pastor; nada me faltará' (Salmo 23:1). 'Ainda que eu andasse pelo vale da sombra da morte, não temeria mal algum, porque tu estás comigo' (Salmo 23:4). Cumprimento em Cristo: (1) Jesus é o Bom Pastor (João 10:11-18). 'Eu sou o bom pastor; o bom pastor dá a sua vida pelas ovelhas' (João 10:11). (2) 'Nada me faltará' - Cristo supre todas as necessidades (Filipenses 4:19). (3) 'Deitar-me faz em verdes pastos' - Jesus alimenta as ovelhas com a Palavra (João 6:35). (4) 'Guia-me mansamente a águas tranquilas' - Jesus nos guia (João 10:3-4). (5) 'Refrigera a minha alma' - Jesus dá descanso (Mateus 11:28-30). (6) 'Guiar-me-á pelas veredas da justiça' - Cristo nos ensina a justiça. (7) 'Vale da sombra da morte' - a morte vencida por Cristo (Hebreus 2:14-15). (8) 'Preparas uma mesa perante mim' - a Ceia do Senhor. (9) 'O teu bordão e o teu cajado me consolam' - a disciplina e proteção de Cristo. (10) 'Unge a minha cabeça com óleo' - a unção do Espírito (1 João 2:20,27). (11) 'Habitarei na casa do Senhor por longos dias' - a vida eterna em Cristo. A teologia reformada vê no Salmo 23 a imagem de Cristo como o Bom Pastor.",
            referencias: "Salmo 23:1-6; João 10:11-18; Mateus 11:28-30; Filipenses 4:19; Hebreus 2:14-15; 1 Pedro 2:25; Apocalipse 7:17"
        },
        {
            termo: "08. Salmo 24 - O Rei da Glória",
            definicao: "Salmo 24 descreve o Rei da glória que entra no templo. 'Levantai, ó portas, as vossas cabeças; levantai-vos, ó portas eternas, para que entre o Rei da Glória. Quem é este Rei da Glória? O Senhor forte e poderoso, o Senhor poderoso na guerra' (Salmo 24:7-8). Cumprimento em Cristo: (1) 'Levantai, ó portas, as vossas cabeças' - frequentemente interpretado como a ascensão de Cristo ao céu. (2) 'Quem é este Rei da Glória?' - a resposta é Cristo, o Senhor dos exércitos (Apocalipse 19:16). (3) A ascensão de Cristo (Atos 1:9-11; Efésios 4:8-10) é o cumprimento desta entrada triunfal. (4) 'Quem subirá ao monte do Senhor? Aquele que é limpo de mãos e puro de coração' (Salmo 24:3-4) - Cristo é o único que subiu (João 3:13). (5) 'O Senhor é o Rei da Glória' (Salmo 24:10). A teologia reformada vê no Salmo 24 a ascensão e entronização de Cristo.",
            referencias: "Salmo 24:1-10; Atos 1:9-11; Efésios 4:8-10; 1 Timóteo 3:16; Apocalipse 19:16"
        },
        {
            termo: "09. Salmo 31 - A Oração de Cristo na Cruz",
            definicao: "Salmo 31 contém palavras que Jesus usou na cruz. 'Nas tuas mãos encomendo o meu espírito; tu me redimiste, Senhor, Deus da verdade' (Salmo 31:5). Cumprimento em Cristo: (1) 'Nas tuas mãos encomendo o meu espírito' foram as últimas palavras de Jesus na cruz (Lucas 23:46). (2) 'Tu me redimiste, Senhor, Deus da verdade' - Cristo é o Redentor (Efésios 1:7). (3) 'Os que me vêem lá fora fogem de mim' (Salmo 31:11) - os discípulos fugiram (Mateus 26:56). (4) 'Como um vaso quebrado' (Salmo 31:12) - o corpo de Cristo foi quebrado (1 Coríndios 11:24). (5) 'Ouvi a murmuração de muitos' (Salmo 31:13) - as murmurações dos líderes judeus. (6) 'Mas eu confiei em ti, Senhor' (Salmo 31:14) - a fé de Cristo na cruz (Hebreus 12:2). A teologia reformada vê no Salmo 31 a oração de Cristo na cruz.",
            referencias: "Salmo 31:1-24; Lucas 23:46; Atos 7:59; Efésios 1:7; 1 Pedro 2:23-24"
        },
        {
            termo: "10. Salmo 34 - O Justo Sofredor",
            definicao: "Salmo 34 descreve a proteção de Deus sobre o justo e a promessa de que nenhum osso do justo será quebrado. 'O Senhor está perto dos que têm o coração quebrantado' (Salmo 34:18). 'Ele guarda todos os seus ossos; nem um deles será quebrado' (Salmo 34:20). Cumprimento em Cristo: (1) 'Ele guarda todos os seus ossos; nem um deles será quebrado' é aplicado a Cristo em João 19:36. Na crucificação, os soldados não quebraram os ossos de Jesus (João 19:33-36). (2) 'O Senhor está perto dos que têm o coração quebrantado' - Jesus veio para os quebrantados de coração (Lucas 4:18). (3) 'Muitos são os males do justo, mas o Senhor o livra de todos' (Salmo 34:19) - a ressurreição de Cristo. (4) 'Provai e vede que o Senhor é bom' (Salmo 34:8) - convite à fé em Cristo (1 Pedro 2:3). A teologia reformada vê no Salmo 34 a proteção divina sobre o corpo de Cristo.",
            referencias: "Salmo 34:1-22; João 19:33-36; Êxodo 12:46; Números 9:12; Lucas 4:18; 1 Pedro 2:3"
        },
        {
            termo: "11. Salmo 40 - A Obediência de Cristo",
            definicao: "Salmo 40 descreve a vinda do Servo do Senhor e sua obediência. 'Sacrifício e oferta não quiseste; os meus ouvidos abriste; holocausto e expiação pelo pecado não reclamaste. Então disse: Eis aqui venho; no rolo do livro está escrito de mim. Deleito-me em fazer a tua vontade, ó Deus meu; sim, a tua lei está dentro do meu coração' (Salmo 40:6-8). Cumprimento em Cristo: (1) O autor de Hebreus aplica este Salmo a Jesus (Hebreus 10:5-10). 'Sacrifício e oferta não quiseste, mas um corpo me preparaste' (Hebreus 10:5). (2) 'Eis aqui venho' refere-se à encarnação de Cristo (João 1:14). (3) 'No rolo do livro está escrito de mim' - as Escrituras profetizavam sobre Cristo (Lucas 24:27,44). (4) 'Deleito-me em fazer a tua vontade, ó Deus meu' - a obediência de Cristo (João 4:34; 6:38). (5) 'Proclamei as boas novas de justiça' (Salmo 40:9) - a pregação de Cristo. A teologia reformada vê no Salmo 40 a obediência voluntária de Cristo na encarnação.",
            referencias: "Salmo 40:1-17; Hebreus 10:5-10; João 1:14; João 4:34; João 6:38; Lucas 24:27; Lucas 24:44"
        },
        {
            termo: "12. Salmo 41 - A Traição de um Amigo Íntimo",
            definicao: "Salmo 41 descreve a traição de um amigo íntimo, cumprida na traição de Judas Iscariotes. 'Até o meu amigo íntimo, em quem eu confiava, que comia do meu pão, levantou contra mim o calcanhar' (Salmo 41:9). Cumprimento em Cristo: (1) Jesus citou este versículo durante a Última Ceia, referindo-se a Judas: 'Não é para todos; eu vos escolhi a vós? Mas ainda assim um de vós é o diabo. Ora, ele falava de Judas Iscariotes, filho de Simão; porque este o havia de trair' (João 6:70-71). 'Não falo de todos vós; eu bem sei os que tenho escolhido; mas para que se cumpra a Escritura: O que come o pão comigo, levantou contra mim o calcanhar' (João 13:18). (2) 'O amigo íntimo... que comia do meu pão' - Judas compartilhou a mesa com Jesus (Mateus 26:23; Marcos 14:20). (3) 'Levantou contra mim o calcanhar' - a traição (Mateus 26:14-16; Lucas 22:3-6). (4) 'Senhor, tem misericórdia de mim, sara a minha alma' (Salmo 41:4) - a oração de Jesus. (5) 'O meu inimigo não triunfe sobre mim' (Salmo 41:11) - a ressurreição. A teologia reformada vê no Salmo 41 a profecia da traição de Judas.",
            referencias: "Salmo 41:1-13; João 6:70-71; João 13:18; Mateus 26:14-16; Marcos 14:20; Lucas 22:3-6; Atos 1:16-20"
        },
        {
            termo: "13. Salmo 45 - O Rei e a Noiva",
            definicao: "Salmo 45 é um Salmo nupcial que descreve um rei glorioso e sua noiva. É aplicado a Cristo e à igreja (sua noiva). 'O teu trono, ó Deus, é eterno e perpétuo; o cetro do teu reino é um cetro de equidade' (Salmo 45:6). 'Ouvindo, pois, ó filha, e vê, e inclina os teus ouvidos; esquece-te do teu povo e da casa de teu pai. E o rei se apaixonará da tua formosura' (Salmo 45:10-11). Cumprimento em Cristo: (1) O autor de Hebreus aplica Salmo 45:6-7 a Cristo: 'Mas do Filho, diz: Ó Deus, o teu trono subsiste pelos séculos dos séculos; cetro de equidade é o cetro do teu reino. Amaste a justiça e odiaste a iniquidade; por isso Deus, o teu Deus, te ungiu com óleo de alegria mais do que a teus companheiros' (Hebreus 1:8-9). (2) 'O teu trono, ó Deus, é eterno' - confirmação da divindade de Cristo. (3) O Rei é Cristo (Apocalipse 19:16). (4) A noiva é a igreja (Efésios 5:25-27; Apocalipse 19:7-9; 21:2). (5) 'Esquece-te do teu povo' - a igreja deixa o mundo para seguir a Cristo. (6) 'O rei se apaixonará da tua formosura' - o amor de Cristo pela igreja. A teologia reformada vê no Salmo 45 o casamento de Cristo com a igreja.",
            referencias: "Salmo 45:1-17; Hebreus 1:8-9; Efésios 5:25-27; Apocalipse 19:7-9; Apocalipse 21:2; Apocalipse 22:17"
        },
        {
            termo: "14. Salmo 68 - A Ascensão de Cristo",
            definicao: "Salmo 68 descreve a ascensão de Deus ao seu santuário e a recepção de dons. 'Subiste ao alto, levaste cativo o cativeiro, recebeste dons para os homens' (Salmo 68:18). Cumprimento em Cristo: (1) O apóstolo Paulo aplica este Salmo à ascensão de Cristo: 'Pelo que diz: Subindo ao alto, levou cativo o cativeiro, e deu dons aos homens. Ora, isto - ele subiu - que é, senão que também desceu às partes mais baixas da terra? Aquele que desceu é também o mesmo que subiu acima de todos os céus, para cumprir todas as coisas' (Efésios 4:8-10). (2) 'Subiste ao alto' - a ascensão de Cristo (Atos 1:9-11; Marcos 16:19). (3) 'Levaste cativo o cativeiro' - a vitória sobre o pecado, a morte e Satanás (Colossenses 2:15; Hebreus 2:14-15). (4) 'Recebeste dons para os homens' - o dom do Espírito Santo (Atos 2:33) e os dons ministeriais (Efésios 4:11). (5) 'Bendito seja o Senhor, que de dia em dia nos carrega de benefícios' (Salmo 68:19) - as bênçãos em Cristo. A teologia reformada vê no Salmo 68 a ascensão de Cristo e o derramamento do Espírito Santo.",
            referencias: "Salmo 68:1-35; Efésios 4:8-10; Atos 1:9-11; Atos 2:33; Colossenses 2:15; Hebreus 2:14-15; Apocalipse 5:11-12"
        },
        {
            termo: "15. Salmo 69 - O Sofrimento e a Sede de Cristo",
            definicao: "Salmo 69 é um dos Salmos messiânicos mais citados no Novo Testamento, descrevendo o sofrimento do Messias. 'Salva-me, ó Deus, porque as águas entraram até a minha alma... Inundaram-me as águas até o pescoço' (Salmo 69:1-2). 'O zelo da tua casa me devorou' (Salmo 69:9). 'Deram-me fel por mantimento, e na minha sede me deram vinagre' (Salmo 69:21). 'Põe-se a mesa diante deles para rede, e a prosperidade para laço' (Salmo 69:22). 'Seja o seu palácio assolado, e nas suas tendas não haja quem more' (Salmo 69:25). Cumprimento em Cristo: (1) 'O zelo da tua casa me devorou' foi aplicado a Jesus na purificação do templo (João 2:17). (2) 'Deram-me fel por mantimento, e na minha sede me deram vinagre' foi cumprido na crucificação: os soldados deram a Jesus vinagre para beber (Mateus 27:34,48; João 19:28-30). (3) 'Seja o seu palácio assolado' foi aplicado a Judas (Atos 1:20). (4) 'Eles me perseguiram e me feriram' (Salmo 69:26) - o sofrimento de Cristo. (5) 'As águas entraram até a minha alma' - a angústia de Cristo no Getsêmani e na cruz. (6) 'A minha garganta se resseca' - 'Tenho sede' (João 19:28). A teologia reformada vê no Salmo 69 o sofrimento do Messias e a sede na cruz.",
            referencias: "Salmo 69:1-36; João 2:17; Mateus 27:34; Mateus 27:48; João 19:28-30; Atos 1:20; Romanos 11:9-10"
        },
        {
            termo: "16. Salmo 72 - O Reinado do Messias",
            definicao: "Salmo 72 descreve o reinado do rei messiânico, com justiça, paz e domínio universal. 'Dai, ó Deus, os teus juízos ao rei, e a tua justiça ao filho do rei' (Salmo 72:1). 'Ele dominará de mar a mar, e desde o rio até às extremidades da terra' (Salmo 72:8). 'Todos os reis se prostrarão perante ele; todas as nações o servirão' (Salmo 72:11). 'O seu nome durará eternamente' (Salmo 72:17). Cumprimento em Cristo: (1) Este Salmo descreve o reinado de Cristo, o Filho de Davi (Mateus 1:1; Lucas 1:32-33). (2) 'Ele julgará o seu povo com justiça' - Cristo julgará o mundo com justiça (Atos 17:31). (3) 'Ele dominará de mar a mar' - a autoridade universal de Cristo (Mateus 28:18). (4) 'Todos os reis se prostrarão perante ele' - 'para que ao nome de Jesus se dobre todo joelho' (Filipenses 2:10-11). (5) 'O seu nome durará eternamente' - Cristo é eterno (Hebreus 13:8). (6) 'E nele serão benditas todas as nações' (Salmo 72:17) - cumprimento da promessa a Abraão (Gálatas 3:8). A teologia reformada vê no Salmo 72 o reinado universal de Cristo.",
            referencias: "Salmo 72:1-20; Mateus 1:1; Lucas 1:32-33; Mateus 28:18; Filipenses 2:10-11; Gálatas 3:8; Apocalipse 11:15; Apocalipse 22:5"
        },
        {
            termo: "17. Salmo 89 - A Aliança Davídica e o Filho de Davi",
            definicao: "Salmo 89 celebra a aliança de Deus com Davi, prometendo um descendente que reinaria para sempre. 'Fiz uma aliança com o meu escolhido; jurei a Davi, meu servo: Para sempre firmarei a tua descendência, e edificarei o teu trono de geração em geração' (Salmo 89:3-4). 'Ele me invocará, dizendo: Tu és meu Pai, meu Deus, e a rocha da minha salvação. Também lhe darei o direito de primogenitura, e o farei o mais alto dos reis da terra. Para sempre conservarei a minha benignidade para com ele' (Salmo 89:26-28). Cumprimento em Cristo: (1) Este Salmo é aplicado a Cristo, o descendente de Davi (Mateus 1:1; Lucas 1:32-33). (2) 'Firmarei a tua descendência para sempre' - Cristo é a descendência eterna de Davi (2 Samuel 7:12-16). (3) 'Tu és meu Pai' - a filiação de Cristo (Hebreus 1:5). (4) 'O farei o mais alto dos reis da terra' - Cristo é o Rei dos reis (Apocalipse 19:16). (5) 'Para sempre conservarei a minha benignidade' - a aliança eterna em Cristo (Hebreus 13:20). A teologia reformada vê no Salmo 89 a aliança davídica cumprida em Cristo.",
            referencias: "Salmo 89:1-52; 2 Samuel 7:12-16; Mateus 1:1; Lucas 1:32-33; Atos 2:30-31; Hebreus 1:5; Apocalipse 19:16"
        },
        {
            termo: "18. Salmo 102 - A Eternidade de Cristo",
            definicao: "Salmo 102 descreve a eternidade de Deus em contraste com a transitoriedade da criação. 'Tu, Senhor, permaneces para sempre... Desde a antiguidade fundaste a terra, e os céus são obra das tuas mãos. Eles perecerão, mas tu permanecerás; todos eles, como vestimenta, envelhecerão... Mas tu és o mesmo, e os teus anos não terão fim' (Salmo 102:12,25-27). Cumprimento em Cristo: (1) O autor de Hebreus aplica este Salmo a Cristo: 'E tu, Senhor, desde o princípio fundaste a terra, e os céus são obra de tuas mãos; eles perecerão, mas tu permanecerás; e todos eles, como roupa, envelhecerão... Mas tu és o mesmo, e os teus anos não acabarão' (Hebreus 1:10-12). (2) Aplicado a Cristo, confirma sua divindade e eternidade. (3) 'Tu, Senhor, permaneces para sempre' - Cristo é eterno (João 1:1; 8:58). (4) 'Os céus são obra das tuas mãos' - Cristo é o Criador (João 1:3; Colossenses 1:16). (5) 'Tu és o mesmo, e os teus anos não terão fim' - a imutabilidade de Cristo (Hebreus 13:8). A teologia reformada vê no Salmo 102 a afirmação da divindade e eternidade de Cristo.",
            referencias: "Salmo 102:1-28; Hebreus 1:10-12; João 1:1-3; João 8:58; Colossenses 1:16-17; Hebreus 13:8; Apocalipse 1:8"
        },
        {
            termo: "19. Salmo 110 - O Rei e Sacerdote Eterno",
            definicao: "Salmo 110 é o Salmo messiânico mais citado no Novo Testamento, descrevendo o Messias como Rei e Sacerdote eterno. 'Disse o Senhor ao meu Senhor: Assenta-te à minha direita, até que ponha os teus inimigos por escabelo dos teus pés' (Salmo 110:1). 'O Senhor jurou e não se arrependerá: Tu és sacerdote para sempre, segundo a ordem de Melquisedeque' (Salmo 110:4). Cumprimento em Cristo: (1) Jesus citou este Salmo para mostrar que o Messias é mais que filho de Davi - é seu Senhor (Mateus 22:41-46; Marcos 12:35-37; Lucas 20:41-44). (2) 'Assenta-te à minha direita' - aplicado à ascensão e exaltação de Cristo (Atos 2:33-35; Efésios 1:20; Colossenses 3:1; Hebreus 1:3; 8:1; 10:12; 12:2; 1 Pedro 3:22). (3) 'Tu és sacerdote para sempre, segundo a ordem de Melquisedeque' - aplicado ao sacerdócio eterno de Cristo (Hebreus 5:6; 6:20; 7:17,21). (4) 'Até que ponha os teus inimigos por escabelo dos teus pés' - a vitória final de Cristo (1 Coríndios 15:25-27; Hebreus 10:12-13). (5) 'O Senhor à tua direita ferirá os reis no dia da sua ira' - o juízo final (Apocalipse 19:11-16). A teologia reformada vê no Salmo 110 a dupla função de Cristo como Rei e Sacerdote.",
            referencias: "Salmo 110:1-7; Mateus 22:41-46; Marcos 12:35-37; Lucas 20:41-44; Atos 2:33-35; Hebros 1:3; Hebreus 5:6; Hebreus 6:20; Hebreus 7:17; Hebreus 7:21; 1 Coríndios 15:25-27"
        },
        {
            termo: "20. Salmo 118 - A Pedra Rejeitada e a Entrada Triunfal",
            definicao: "Salmo 118 é um Salmo messiânico que descreve a pedra rejeitada que se torna a cabeça da esquina e a entrada triunfal do Messias. 'A pedra que os edificadores rejeitaram tornou-se a cabeça da esquina. Isto foi do Senhor; é maravilhoso aos nossos olhos' (Salmo 118:22-23). 'Bendito o que vem em nome do Senhor' (Salmo 118:26). Cumprimento em Cristo: (1) 'A pedra que os edificadores rejeitaram' foi aplicado por Jesus a si mesmo (Mateus 21:42; Marcos 12:10-11; Lucas 20:17). Pedro também aplica a Cristo (Atos 4:11; 1 Pedro 2:7). (2) 'Tornou-se a cabeça da esquina' (pedra angular) - Cristo é o fundamento da igreja (Efésios 2:20). (3) 'Bendito o que vem em nome do Senhor' foi aclamação na entrada triunfal de Jesus em Jerusalém (Mateus 21:9; Marcos 11:9-10; Lucas 19:38; João 12:13). (4) 'Rendei graças ao Senhor, porque ele é bom; porque a sua misericórdia dura para sempre' (Salmo 118:1,29) - a misericórdia de Deus em Cristo. A teologia reformada vê no Salmo 118 a rejeição e exaltação de Cristo, e sua entrada triunfal.",
            referencias: "Salmo 118:1-29; Mateus 21:9; Mateus 21:42; Marcos 11:9-10; Lucas 19:38; Lucas 20:17; João 12:13; Atos 4:11; Efésios 2:20; 1 Pedro 2:7"
        },
        {
            termo: "21. Salmo 132 - O Trono de Davi e o Descendente Prometido",
            definicao: "Salmo 132 celebra a aliança de Deus com Davi e a promessa de um descendente que se assentaria em seu trono. 'O Senhor jurou a Davi com verdade, e não se apartará dela: Do fruto do teu ventre assentarei sobre o teu trono' (Salmo 132:11). 'Ali farei brotar a força de Davi; preparei uma lâmpada para o meu ungido' (Salmo 132:17). Cumprimento em Cristo: (1) O apóstolo Pedro aplica este Salmo a Cristo: 'Dizendo o Senhor ao meu Senhor: Assenta-te à minha direita, até que eu ponha os teus inimigos por escabelo dos teus pés' (Atos 2:34-35), e o contexto inclui a promessa a Davi. (2) 'Do fruto do teu ventre assentarei sobre o teu trono' - Cristo é o descendente de Davi (Mateus 1:1; Lucas 1:32-33; Romanos 1:3). (3) 'Preparei uma lâmpada para o meu ungido' - Cristo é a luz do mundo (João 8:12). (4) 'O ungido' (Messias) é Cristo (Lucas 2:11; João 1:41). (5) A aliança davídica (2 Samuel 7:12-16) encontra seu cumprimento final em Cristo. A teologia reformada vê no Salmo 132 a confirmação da aliança davídica em Cristo.",
            referencias: "Salmo 132:1-18; 2 Samuel 7:12-16; Mateus 1:1; Lucas 1:32-33; Romanos 1:3; Atos 2:30-31; João 8:12"
        },
        {
            termo: "22. Síntese: Cristo é o Centro de Todos os Salmos",
            definicao: "Os Salmos são cristocêntricos. Jesus, os apóstolos e os Pais da Igreja testificaram que os Salmos apontam para Cristo. Resumo dos Salmos messiânicos: (1) Salmo 1 - O Homem bem-aventurado (Cristo, o justo perfeito). (2) Salmo 2 - O Rei ungido, o Filho de Deus. (3) Salmo 8 - A encarnação e exaltação de Cristo. (4) Salmo 16 - A ressurreição do Santo de Deus. (5) Salmo 22 - A crucificação do Messias. (6) Salmo 23 - O Bom Pastor. (7) Salmo 24 - O Rei da Glória (ascensão). (8) Salmo 31 - A oração de Cristo na cruz. (9) Salmo 34 - O justo sofredor (ossos não quebrados). (10) Salmo 40 - A obediência de Cristo na encarnação. (11) Salmo 41 - A traição de um amigo íntimo (Judas). (12) Salmo 45 - O Rei e a noiva (Cristo e a igreja). (13) Salmo 68 - A ascensão de Cristo. (14) Salmo 69 - O sofrimento e a sede de Cristo. (15) Salmo 72 - O reinado universal do Messias. (16) Salmo 89 - A aliança davídica cumprida. (17) Salmo 102 - A eternidade de Cristo. (18) Salmo 110 - O Rei e Sacerdote eterno. (19) Salmo 118 - A pedra rejeitada e a entrada triunfal. (20) Salmo 132 - O descendente de Davi. Além destes, muitos outros Salmos têm aplicações cristológicas (Salmo 2, 22, 45, 69, 72, 89, 102, 110, 118, 132 são os principais). A teologia reformada (Calvino, Spurgeon) conclui: 'Os Salmos são um espelho de Cristo'. 'E disse-lhes: Estas são as palavras que vos disse, estando ainda convosco, que convinha que se cumprisse tudo o que de mim está escrito na lei de Moisés, e nos profetas e nos salmos' (Lucas 24:44). 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36). Soli Deo Gloria!",
            referencias: "Lucas 24:44-45; João 5:39; Atos 2:25-36; Romanos 11:36; Hebreus 1:5-14; 1 Pedro 1:10-12"
        }
    ]
};