// volume/volume-73.js
window.LIVRO_DATA = {
    nome: "Volume LXXIII",
    dados: [
        {
            termo: "01. Introdução: A Apologética Cristocêntrica e a Exegese Fiel",
            definicao: "A apologética (defesa da fé) e a exegese (interpretação das Escrituras) são fundamentais para a cristologia reformada. O apóstolo Pedro exorta: 'Antes, santificai ao Senhor Deus em vossos corações; e estai sempre preparados para responder com mansidão e temor a qualquer que vos pedir a razão da esperança que há em vós' (1 Pedro 3:15). A exegese fiel busca o sentido original do texto bíblico, enquanto a apologética defende a verdade do evangelho. 'Toda a Escritura é inspirada por Deus e útil para o ensino, para a repreensão, para a correção, para a instrução na justiça' (2 Timóteo 3:16). Este volume explora a relação entre apologética, exegese e cristologia: métodos de interpretação bíblica, a defesa da divindade de Cristo, a evidência da ressurreição, a confiabilidade dos evangelhos, o cumprimento das profecias, e a resposta a objeções comuns. 'Examinais as Escrituras, porque vós cuidais ter nelas a vida eterna, e são elas que de mim testificam' (João 5:39).",
            referencias: "João 5:39; Atos 17:11; Romanos 1:16; 1 Pedro 3:15; 2 Timóteo 3:16-17; 2 Pedro 1:19-21; Judas 1:3"
        },
        {
            termo: "02. Hermenêutica Cristocêntrica - Interpretando a Bíblia à Luz de Cristo",
            definicao: "A hermenêutica cristocêntrica é o método de interpretação que vê Cristo como a chave para toda a Escritura. Jesus declarou: 'São estas as palavras que vos disse, estando ainda convosco, que convinha que se cumprisse tudo o que de mim está escrito na lei de Moisés, e nos profetas e nos salmos' (Lucas 24:44). 'E, começando por Moisés e por todos os profetas, explicava-lhes o que dele se achava em todas as Escrituras' (Lucas 24:27). Princípios da hermenêutica cristocêntrica: (1) Cristo é o centro das Escrituras (João 5:39). (2) O Antigo Testamento aponta para Cristo (Lucas 24:27). (3) O Novo Testamento interpreta o Antigo Testamento à luz de Cristo. (4) A analogia da fé (analogia fidei): a Escritura interpreta a si mesma. (5) O sentido literal (gramático-histórico) é o sentido primário, mas deve ser entendido à luz do cumprimento em Cristo. Métodos hermenêuticos: (a) Exegese gramático-histórica: análise do texto em seu contexto original. (b) Análise literária: gênero, estrutura, figura de linguagem. (c) Análise teológica: relação com o restante da Escritura. (d) Aplicação cristocêntrica: como o texto aponta para Cristo. A teologia reformada (Calvino, Turretin) enfatiza a hermenêutica cristocêntrica. 'Toda a Escritura é uma manjedoura onde Cristo é deitado' (Calvino).",
            referencias: "Lucas 24:27; Lucas 24:44-45; João 5:39; Atos 8:26-40; Romanos 10:4; 2 Coríndios 1:20; Gálatas 3:24; Colossenses 2:17; Hebreus 8:5; Hebreus 10:1"
        },
        {
            termo: "03. A Divindade de Cristo - Evidências Bíblicas e Exegéticas",
            definicao: "A divindade de Cristo é central para a fé cristã. Evidências bíblicas exegéticas: (1) Jesus é chamado 'Deus' (Theos): 'No princípio era o Verbo, e o Verbo estava com Deus, e o Verbo era Deus' (João 1:1). 'Respondeu Tomé e disse-lhe: Senhor meu, e Deus meu!' (João 20:28). 'Cristo... é Deus sobre todos' (Romanos 9:5). 'Aguardando... o aparecimento da glória do grande Deus e nosso Salvador Jesus Cristo' (Tito 2:13). 'Do Filho, diz: O teu trono, ó Deus, é eterno' (Hebreus 1:8). (2) Jesus recebe adoração (proskynēsis): os magos (Mateus 2:2,11), os discípulos (Mateus 14:33; 28:9), Tomé (João 20:28), os anjos (Hebreus 1:6). (3) Jesus perdoa pecados (Marcos 2:5-12). (4) Jesus realiza ações divinas: cria (João 1:3; Colossenses 1:16), sustenta (Colossenses 1:17; Hebreus 1:3), julga (João 5:22-29). (5) Jesus tem atributos divinos: eternidade (João 1:1; 8:58), onipresença (Mateus 28:20), onipotência (Mateus 28:18), onisciência (João 21:17). A teologia reformada (Calvino, Warfield) vê nestas passagens a afirmação inequívoca da divindade de Cristo. 'Este é o verdadeiro Deus e a vida eterna' (1 João 5:20).",
            referencias: "João 1:1; João 1:14; João 8:58; João 20:28; Romanos 9:5; Filipenses 2:5-6; Colossenses 1:15-20; Colossenses 2:9; Tito 2:13; Hebreus 1:1-4; Hebreus 1:8-9; 2 Pedro 1:1; 1 João 5:20"
        },
        {
            termo: "04. A Humanidade de Cristo - Evidências Bíblicas e Exegéticas",
            definicao: "Jesus era verdadeiro homem. Evidências bíblicas exegéticas: (1) Nasceu de mulher (Gálatas 4:4). (2) Tinha corpo humano: comeu (Lucas 24:42-43), bebeu (João 19:28), cansou-se (João 4:6), dormiu (Mateus 8:24), sofreu (Mateus 27:46), morreu (Marcos 15:37). (3) Tinha alma humana: 'entregou o espírito' (Mateus 27:50); 'ficou maravilhado' (Mateus 8:10); 'compadeceu-se' (Mateus 9:36); 'angustiou-se' (Mateus 26:37-38). (4) Foi chamado 'homem' (João 8:40; Atos 2:22; 1 Timóteo 2:5). (5) Cresceu em estatura e sabedoria (Lucas 2:40,52). (6) Foi tentado, mas sem pecado (Hebreus 4:15). Evidências históricas extracanônicas: (a) Tácito (Anais 15.44, 116 d.C.): 'Cristo foi executado por Pôncio Pilatos'. (b) Flávio Josefo (Antiguidades 18.63-64, 94 d.C.): 'Jesus, homem sábio'. (c) Luciano de Samósata (c. 160 d.C.): 'Jesus foi crucificado'. (d) Celso (c. 177 d.C.): crítico que admite a existência de Jesus. A teologia reformada afirma a humanidade plena de Cristo (contra docetismo, apolinarianismo). 'O Verbo se fez carne' (João 1:14).",
            referencias: "Isaías 53:1-12; Mateus 1:18-25; Mateus 4:1-11; Lucas 2:40; Lucas 2:52; Lucas 24:42-43; João 1:14; João 4:6; João 19:28; Gálatas 4:4; 1 Timóteo 2:5; Hebreus 2:14-18; Hebreus 4:15; 1 João 4:2-3"
        },
        {
            termo: "05. A Ressurreição de Cristo - Evidências Históricas e Apologéticas",
            definicao: "A ressurreição de Cristo é a evidência central da fé cristã. 'E, se Cristo não ressuscitou, é vã a nossa pregação, e também é vã a vossa fé' (1 Coríndios 15:14). Evidências históricas: (1) O sepulcro vazio: as mulheres encontraram o túmulo vazio no domingo de manhã (Mateus 28:1-10; Marcos 16:1-8; Lucas 24:1-12; João 20:1-10). A teoria do roubo do corpo (Mateus 28:11-15) é implausível (os discípulos não teriam morrido por uma mentira). (2) As aparições de Jesus ressurreto: (a) a Maria Madalena (João 20:11-18); (b) às mulheres (Mateus 28:9-10); (c) a Pedro (Lucas 24:34; 1 Coríndios 15:5); (d) aos dois discípulos no caminho de Emaús (Lucas 24:13-35); (e) aos dez apóstolos (sem Tomé, João 20:19-23); (f) aos onze apóstolos (com Tomé, João 20:24-29); (g) a mais de 500 irmãos (1 Coríndios 15:6); (h) a Tiago (1 Coríndios 15:7); (i) a Paulo (Atos 9:1-9; 1 Coríndios 15:8). (3) A transformação dos discípulos: de medrosos (João 20:19) a corajosos (Atos 2:14-41), dispostos a morrer por sua fé. (4) A origem da fé cristã: começou em Jerusalém (onde Jesus foi crucificado), poucos anos após a crucificação. (5) O culto no domingo: os cristãos passaram a adorar no domingo (dia da ressurreição), não no sábado (Atos 20:7; 1 Coríndios 16:2; Apocalipse 1:10). A teologia reformada afirma a ressurreição como evento histórico, não mito ou símbolo. 'Cristo ressuscitou dos mortos' (1 Coríndios 15:20).",
            referencias: "Salmo 16:10; Isaías 53:10-12; Mateus 28:1-20; Marcos 16:1-20; Lucas 24:1-53; João 20:1-31; Atos 2:22-36; Atos 13:30-37; 1 Coríndios 15:1-8; 1 Coríndios 15:12-20; 1 Pedro 1:3; 1 Pedro 3:18"
        },
        {
            termo: "06. A Confiabilidade Histórica dos Evangelhos",
            definicao: "Os evangelhos são fontes históricas confiáveis sobre a vida de Jesus. Evidências: (1) Autoria: Mateus (apóstolo, testemunha ocular), Marcos (companheiro de Pedro), Lucas (companheiro de Paulo, entrevistou testemunhas), João (apóstolo, testemunha ocular). (2) Datação: evangelhos escritos no século I (poucos anos após a crucificação): Marcos c. 55-65 d.C., Mateus c. 55-65 d.C., Lucas c. 58-65 d.C., João c. 85-95 d.C. (3) Confirmação arqueológica: escavações confirmaram detalhes dos evangelhos (ex.: Piscina de Siloé, João 9:7; Pátio de Pilatos, João 18:28; Inscrição de Pôncio Pilatos descoberta em 1961). (4) Testemunho de fontes não cristãs: Tácito (Anais 15.44, 116 d.C.), Flávio Josefo (Antiguidades 18.63-64; 20.200, 94 d.C.), Plínio, o Jovem (Cartas 10.96, 112 d.C.), Luciano de Samósata (c. 160 d.C.). (5) Consistência interna: os evangelhos apresentam um retrato consistente de Jesus, apesar das diferentes ênfases. (6) Crítica textual: o Novo Testamento tem mais manuscritos (5.800 gregos) do que qualquer outra obra antiga. A teologia reformada afirma a confiabilidade histórica dos evangelhos (Lucas 1:1-4; João 20:30-31). 'Para que conheças a certeza das coisas de que já estás informado' (Lucas 1:4).",
            referencias: "Lucas 1:1-4; Lucas 3:1-2; João 19:35; João 20:30-31; João 21:24-25; Atos 1:1-3; 2 Pedro 1:16-21; 1 João 1:1-4"
        },
        {
            termo: "07. O Cumprimento das Profecias Messiânicas - Evidência Apologética",
            definicao: "Jesus cumpriu centenas de profecias do Antigo Testamento sobre o Messias. Exemplos principais: (1) Nascimento: (a) Nascido de uma virgem (Isaías 7:14; Mateus 1:22-23). (b) Nascido em Belém (Miqueias 5:2; Mateus 2:1-6). (c) Descendente de Abraão (Gênesis 12:3; Mateus 1:1). (d) Descendente de Davi (Isaías 11:1; Jeremias 23:5-6; Mateus 1:1). (2) Ministério: (a) Ungido pelo Espírito (Isaías 61:1-2; Lucas 4:18-21). (b) Faria milagres (Isaías 35:5-6; Mateus 11:2-6). (c) Entrada triunfal (Zacarias 9:9; Mateus 21:1-11). (3) Sofrimento e morte: (a) Traído por um amigo (Salmo 41:9; Mateus 26:14-16). (b) Vendido por 30 moedas de prata (Zacarias 11:12-13; Mateus 26:14-16). (c) Silencioso diante dos acusadores (Isaías 53:7; Mateus 27:12-14). (d) Crucificado com transgressores (Isaías 53:12; Marcos 15:27-28). (e) Mãos e pés traspassados (Salmo 22:16; Lucas 23:33). (f) Vestes repartidas (Salmo 22:18; Mateus 27:35). (g) Deram-lhe fel e vinagre (Salmo 69:21; Mateus 27:34; João 19:28-30). (h) Nenhum osso quebrado (Salmo 34:20; Êxodo 12:46; João 19:33-36). (i) Sepultado com os ricos (Isaías 53:9; Mateus 27:57-60). (4) Ressurreição: (a) Não verá corrupção (Salmo 16:10; Atos 2:25-32). (b) Ascensão (Salmo 68:18; Efésios 4:8-10). (c) Sessão à direita de Deus (Salmo 110:1; Marcos 16:19; Atos 2:33-35). A probabilidade de uma pessoa cumprir apenas 8 profecias é de 1 em 10^17. A teologia reformada vê no cumprimento das profecias evidência da divindade de Cristo.",
            referencias: "Gênesis 3:15; Gênesis 12:3; Gênesis 49:10; Números 24:17; Deuteronômio 18:15-19; 2 Samuel 7:12-16; Salmo 2; Salmo 16; Salmo 22; Salmo 69; Isaías 7:14; Isaías 9:6-7; Isaías 11:1-2; Isaías 35:5-6; Isaías 53:1-12; Jeremias 23:5-6; Daniel 9:24-27; Miqueias 5:2; Zacarias 9:9; Zacarias 11:12-13; Zacarias 12:10"
        },
        {
            termo: "08. Resposta ao Ateísmo - Argumentos Filosóficos e Teológicos",
            definicao: "O ateísmo afirma que Deus não existe. A teologia reformada argumenta que o ateísmo é irracional. Argumentos: (1) Argumento cosmológico: o universo teve um começo (Big Bang, c. 13,8 bilhões de anos). Algo não pode vir do nada (ex nihilo nihil fit). É necessário uma causa eterna e necessária (Deus). (2) Argumento teleológico (fine-tuning): as constantes fundamentais da física são precisamente ajustadas para permitir a vida. Probabilidade de acaso: 1 em 10^120. (3) Argumento moral: se não há Deus, não há fundamento objetivo para a moral (bem e mal). O ateísmo leva ao niilismo (tudo é relativo). (4) Argumento da consciência: a consciência (pensamentos, sentimentos, livre-arbítrio) não pode ser reduzida à matéria. (5) Argumento da ressurreição de Cristo: evidência histórica de um milagre (1 Coríndios 15:3-8). (6) Argumento da experiência religiosa: milhões de pessoas testemunham um encontro com Deus em Cristo. (7) Argumento pressuposicional (Van Til): o ateísmo pressupõe a existência de Deus (leis da lógica, uniformidade da natureza, moralidade) sem admitir. A teologia reformada rejeita o ateísmo como contrário à evidência (Romanos 1:18-25). 'O tolo disse no seu coração: Não há Deus' (Salmo 14:1; 53:1).",
            referencias: "Salmo 14:1; Salmo 53:1; Romanos 1:18-25; 1 Coríndios 1:18-25; 1 Coríndios 2:14; Efésios 2:12; Colossenses 2:8; Tito 1:15"
        },
        {
            termo: "09. Resposta ao Islamismo - Jesus no Alcorão vs. Jesus na Bíblia",
            definicao: "O Islã rejeita a divindade de Cristo, a crucificação e a ressurreição. Pontos de contraste: (1) Jesus no Alcorão: (a) É um profeta (como Maomé), não Deus. (b) Não foi crucificado (Alcorão 4:157: 'Não o mataram, nem o crucificaram, mas parecia-lhes que sim'). (c) Foi elevado ao céu vivo (não morreu). (d) É chamado 'Messias', 'Filho de Maria', 'Espírito de Deus', 'Verbo de Deus'. (2) Jesus na Bíblia: (a) É Deus (João 1:1,14; 20:28; Romanos 9:5; Tito 2:13). (b) Foi crucificado (Mateus 27:32-56; Marcos 15:21-41; Lucas 23:26-49; João 19:16-37). (c) Ressuscitou (1 Coríndios 15:3-8). (3) Evidências históricas da crucificação: (a) Fontes cristãs (evangelhos). (b) Fontes não cristãs (Tácito, Josefo, Luciano). (c) A aceitação universal da crucificação pelos historiadores (incluindo ateus). (4) A Bíblia é anterior ao Alcorão (NT: séc. I; Alcorão: séc. VII). (5) O Alcorão contradiz a evidência histórica. A teologia reformada rejeita o Islã como religião falsa (Gálatas 1:8-9), mas defende o diálogo respeitoso e o testemunho. 'Ainda que nós ou um anjo do céu vos anuncie outro evangelho... seja anátema' (Gálatas 1:8).",
            referencias: "Mateus 27:32-56; Marcos 15:21-41; Lucas 23:26-49; João 1:1-14; João 19:16-37; João 20:1-31; Atos 4:12; Romanos 9:5; 1 Coríndios 15:1-8; Gálatas 1:8-9; 1 Timóteo 2:5; Tito 2:13; 1 João 4:2-3"
        },
        {
            termo: "10. Resposta ao Judaísmo - Jesus é o Messias Prometido",
            definicao: "O judaísmo rabínico rejeita Jesus como o Messias. Pontos de diálogo: (1) O Messias no Antigo Testamento: (a) Descendente de Davi (2 Samuel 7:12-16). (b) Nasceria em Belém (Miqueias 5:2). (c) Seria Deus (Isaías 9:6-7: 'Deus Forte, Pai da Eternidade'). (d) Sofreria e morreria pelos pecados (Isaías 53:1-12). (e) Ressuscitaria (Salmo 16:10). (2) Jesus cumpriu as profecias: (a) Descendente de Davi (Mateus 1:1-17; Lucas 3:23-38). (b) Nascido em Belém (Mateus 2:1-6). (c) Divindade de Jesus (João 1:1-14). (d) Sofrimento e morte por pecados (Isaías 53:5-6; 1 Pedro 2:24). (e) Ressurreição (Atos 2:22-36). (3) Objeções judaicas: (a) 'O Messias traria paz mundial' (Isaías 2:4; 11:6-9) - respondida: a paz será na segunda vinda. (b) 'O Messias traria todos os judeus de volta a Israel' (Isaías 11:12) - respondida: cumprimento parcial (retorno de 1948) e completo na segunda vinda. (c) 'O Messias reconstruiria o Templo' (Ezequiel 40-48) - respondida: Jesus é o Templo (João 2:19-21). (d) 'Jesus não cumpriu as profecias messiânicas' - respondida: muitas profecias foram cumpridas na primeira vinda; as restantes serão cumpridas na segunda vinda. A teologia reformada afirma que Jesus é o Messias prometido (Romanos 10:1-4).",
            referencias: "Isaías 9:6-7; Isaías 53:1-12; Jeremias 23:5-6; Daniel 7:13-14; Miqueias 5:2; Zacarias 9:9; Salmo 2; Salmo 16; Salmo 22; Mateus 1:1-17; Lucas 1:32-33; Lucas 24:27; João 5:39; Atos 2:22-36; Romanos 9-11"
        },
        {
            termo: "11. Resposta ao Agnosticismo e Ceticismo Histórico",
            definicao: "O agnosticismo afirma que não podemos saber se Deus existe. O ceticismo histórico afirma que não podemos saber nada sobre o Jesus histórico. Resposta ao agnosticismo: (1) A Bíblia afirma que podemos conhecer a Deus (João 17:3: 'E a vida eterna é esta: que te conheçam... a Jesus Cristo'). (2) A criação revela Deus (Salmo 19:1-6; Romanos 1:20). (3) A consciência moral revela Deus (Romanos 2:14-15). (4) O agnosticismo é inconsistente: se não podemos saber se Deus existe, também não podemos saber se Ele não existe. Resposta ao ceticismo histórico: (1) Existem mais fontes sobre Jesus do que sobre qualquer outra figura antiga (ex.: Alexandre, o Grande; Júlio César). (2) Os evangelhos são fontes históricas confiáveis (autoria de testemunhas, datação precoce). (3) A arqueologia confirma os evangelhos (ex.: Piscina de Siloé, Pátio de Pilatos). (4) As fontes não cristãs confirmam a existência de Jesus (Tácito, Josefo). (5) O ceticismo radical (Jesus não existiu) é rejeitado pela maioria dos historiadores (ateus e cristãos). (6) A 'terceira busca' pelo Jesus histórico (N.T. Wright, James Dunn) é mais equilibrada. A teologia reformada afirma que podemos conhecer a Deus (até certo ponto) e que podemos conhecer o Jesus histórico (Lucas 1:1-4; João 20:30-31).",
            referencias: "Lucas 1:1-4; João 17:3; João 20:30-31; Romanos 1:18-25; Romanos 2:14-15; 1 Coríndios 15:1-8; 2 Pedro 1:16-21; 1 João 1:1-4"
        },
        {
            termo: "12. Apologética Reformada - Pressuposicionalismo (Cornelius Van Til)",
            definicao: "Cornelius Van Til (1895-1987), professor de apologética no Westminster Seminary, desenvolveu a 'apologética pressuposicional'. Princípios: (1) Todo pensamento humano é baseado em pressuposições (precompromissos). (2) O cristão deve ter pressuposições cristãs (a existência de Deus, a autoridade da Escritura, a divindade de Cristo). (3) O não-cristão tem pressuposições ateístas (o universo é autônomo, não há Deus). (4) A apologética deve expor as pressuposições do não-cristão e mostrar que o ateísmo é irracional (não pode explicar a lógica, a moral, a ciência). (5) A apologética não é neutra (todos têm pressuposições). (6) A Escritura é a autoridade final (não a razão autônoma). (7) O argumento transcendental: as pressuposições ateístas são autocontraditórias (ex.: o ateísmo pressupõe a existência de Deus para negar Deus). Críticas ao pressuposicionalismo: (a) Pode levar ao fideísmo (fé sem razão). (b) Pode ignorar as evidências históricas (ressurreição). (c) Pode ser circular (provar a Bíblia pela Bíblia). A teologia reformada divide-se entre pressuposicionalistas (Van Til, Bahnsen) e evidencialistas (Craig, Habermas). 'Examinais as Escrituras' (João 5:39).",
            referencias: "Provérbios 1:7; Provérbios 9:10; Atos 17:2-4; 2 Coríndios 10:3-5; Colossenses 2:8; 1 Pedro 3:15; 2 Pedro 1:19-21"
        },
        {
            termo: "13. Síntese: A Apologética e a Exegese a Serviço de Cristo",
            definicao: "A apologética cristã e a exegese bíblica têm como objetivo: (1) Defender a fé contra objeções (1 Pedro 3:15). (2) Remover obstáculos à fé (2 Coríndios 10:5). (3) Apresentar evidências da verdade do cristianismo (evidências históricas, profecias, ressurreição). (4) Interpretar corretamente as Escrituras (2 Timóteo 2:15). (5) Apontar para Cristo como a única esperança (João 14:6; Atos 4:12). (6) Glorificar a Cristo (Soli Deo Gloria). Métodos: (a) Evidencial: foco na ressurreição (Gary Habermas, Josh McDowell). (b) Clássico: argumentos filosóficos (cosmológico, teleológico, moral) + ressurreição (William Lane Craig). (c) Pressuposicional: expor pressuposições ateístas (Cornelius Van Til). (d) Reformado: combinação de pressuposições e evidências (Francis Schaeffer, Tim Keller). A teologia reformada recomenda uma abordagem equilibrada: (1) Pressuposições corretas (crença em Deus, na autoridade da Escritura, na divindade de Cristo). (2) Evidências históricas (ressurreição de Cristo, cumprimento de profecias, confiabilidade dos evangelhos). (3) Argumentos filosóficos (cosmológico, teleológico, moral). (4) Apelo à experiência (transformação pessoal, testemunho). (5) Mansidão e respeito (1 Pedro 3:15). O alvo final não é ganhar debates, mas ganhar almas para Cristo. 'Examinais as Escrituras... e são elas que de mim testificam' (João 5:39). Soli Deo Gloria!",
            referencias: "João 5:39; João 14:6; Atos 4:12; Romanos 1:16; 1 Coríndios 9:19-23; 2 Coríndios 5:18-21; 2 Coríndios 10:3-5; Colossenses 1:28-29; 2 Timóteo 2:15; 1 Pedro 3:15; Judas 1:22-23"
        }
    ]
};