// volume/volume-87.js
window.LIVRO_DATA = {
    nome: "Volume LXXXVII",
    dados: [
        {
            termo: "01. Introdução: O Corpo como Templo do Espírito Santo",
            definicao: "O corpo humano é criação de Deus e deve ser usado para sua glória. 'Não sabeis vós que o vosso corpo é o templo do Espírito Santo, que habita em vós, proveniente de Deus, e que não sois de vós mesmos?' (1 Coríndios 6:19). 'Portanto, quer comais quer bebais, ou façais outra qualquer coisa, fazei tudo para glória de Deus' (1 Coríndios 10:31). O esporte é uma atividade que envolve o corpo e pode ser usada para a glória de Deus, para o desenvolvimento de virtudes, e para o testemunho cristão. A teologia reformada (Calvino, Kuyper) valoriza o corpo como criação boa (Gênesis 1:31), rejeitando o dualismo gnóstico (que despreza o corpo). Este volume explora: (1) Cristo e o corpo humano. (2) A teologia do esporte. (3) Ética esportiva. (4) Esporte e evangelismo. (5) Esporte e juventude. (6) Esporte e santidade. 'Tudo o que fizerdes, fazei-o de coração, como ao Senhor' (Colossenses 3:23).",
            referencias: "Gênesis 1:26-27; Gênesis 1:31; 1 Coríndios 6:19-20; 1 Coríndios 9:24-27; 1 Coríndios 10:31; Colossenses 3:23"
        },
        {
            termo: "02. Cristo e o Corpo Humano - A Encarnação e a Ressurreição",
            definicao: "Cristo assumiu um corpo humano real na encarnação. 'E o Verbo se fez carne, e habitou entre nós' (João 1:14). Ele comeu, bebeu, cansou-se, sentiu dor, e morreu (Mateus 27:50). Ele ressuscitou corporalmente (Lucas 24:39-43). A ressurreição de Cristo é a garantia da ressurreição do nosso corpo (1 Coríndios 15:20-23). 'Transformará o nosso corpo vil, para ser conforme o seu corpo glorioso' (Filipenses 3:21). Implicações para o esporte: (1) O corpo é bom (criação de Deus). (2) O corpo deve ser cuidado (não negligenciado). (3) O corpo não deve ser idolatrado (culto ao corpo). (4) O corpo será ressuscitado (esperança). (5) O esporte pode ser uma forma de cuidar do corpo. (6) O esporte deve ser feito para a glória de Deus. A teologia reformada (Calvino, Bavinck) enfatiza a bondade do corpo e a esperança da ressurreição. 'Porque para mim o viver é Cristo, e o morrer é ganho' (Filipenses 1:21).",
            referencias: "João 1:14; Lucas 24:39-43; Romanos 8:11; 1 Coríndios 15:42-44; 2 Coríndios 5:1-4; Filipenses 3:20-21; 1 João 1:1"
        },
        {
            termo: "03. A Teologia do Esporte - Competição, Excelência e Humildade",
            definicao: "O esporte envolve competição, busca da excelência, e humildade na vitória e na derrota. 'Não sabeis vós que os que correm no estádio, todos, na verdade, correm, mas um só leva o prêmio? Correi de tal maneira que o alcanceis' (1 Coríndios 9:24). 'Pois exercita-te a ti mesmo em piedade; porque o exercício corporal para pouco é proveitoso, mas a piedade para tudo é proveitosa' (1 Timóteo 4:7-8). Princípios: (1) Excelência: buscar o melhor (Colossenses 3:23). (2) Disciplina: treinar com dedicação (1 Coríndios 9:25). (3) Humildade: não se orgulhar (Provérbios 16:18). (4) Respeito: respeitar adversários e árbitros. (5) Trabalho em equipe: cooperar (Eclesiastes 4:9-10). (6) Liderança: servir como exemplo (Mateus 20:26-28). (7) Perseverança: não desistir (Hebreus 12:1). (8) Alegria: celebrar com moderação (Filipenses 4:4). (9) Gratidão: agradecer a Deus pelos talentos. (10) Testemunho: refletir Cristo na competição. A teologia reformada (Kuyper, Plantinga) vê no esporte uma arena para o desenvolvimento de virtudes. 'E tudo quanto fizerdes, fazei-o de coração, como ao Senhor' (Colossenses 3:23).",
            referencias: "Provérbios 16:18; 1 Coríndios 9:24-27; Gálatas 5:22-23; Efésios 4:2-3; Colossenses 3:23; 1 Timóteo 4:7-8; Hebreus 12:1-2"
        },
        {
            termo: "04. Ética Esportiva - Fair Play, Doping e Integridade",
            definicao: "O esporte deve ser praticado com integridade, honestidade e respeito. 'O que é reto e honesto, nisso pensai' (Filipenses 4:8). Questões éticas: (1) Fair play (jogo limpo): respeitar as regras e adversários. (2) Doping: uso de substâncias proibidas é engano (Levítico 19:35). 'Não tenhais engano nas balanças, nem nos pesos' (Levítico 19:35). (3) Trapaça: mentir é pecado (Provérbios 12:22). (4) Violência: agredir intencionalmente é pecado (Mateus 5:21-22). (5) Corrupção: subornar árbitros é pecado (Êxodo 23:8). (6) Jogo excessivo: idolatria do esporte (Êxodo 20:3). (7) Apostas esportivas: jogos de azar (cuidado: avareza). (8) Abuso de crianças no esporte (Mateus 18:6). (9) Discriminação racial ou de gênero (Gálatas 3:28). (10) Exploração de atletas (Tiago 5:4). A teologia reformada (Calvino, Bavinck) enfatiza a integridade como fruto da santificação. 'O que furtava, não furte mais; antes trabalhe, fazendo com as mãos o que é bom' (Efésios 4:28).",
            referencias: "Êxodo 20:15; Levítico 19:35; Deuteronômio 25:13-16; Provérbios 11:1; Mateus 5:21-22; Filipenses 4:8; 1 Tessalonicenses 4:6"
        },
        {
            termo: "05. Esporte e Evangelismo - Testemunho de Atletas Cristãos",
            definicao: "Atletas cristãos podem usar o esporte como plataforma para testemunhar de Cristo. 'Antes, santificai ao Senhor Deus em vossos corações; e estai sempre preparados para responder com mansidão e temor a qualquer que vos pedir a razão da esperança que há em vós' (1 Pedro 3:15). Exemplos de atletas cristãos: (1) Tim Tebow (futebol americano) - orava no campo, testemunhava abertamente. (2) Eric Liddell (atletismo) - recusou correr no domingo, missionário na China. (3) Kaká (futebol) - camisa 'Eu pertenço a Jesus'. (4) Neymar (futebol) - cristão declarado (embora controverso). (5) David Luiz (futebol) - cristão. (6) Felipe Luis (futebol) - cristão. (7) Oscar Schmidt (basquete) - cristão. (8) André Agassi (tênis) - cristão (na juventude). (9) Maria Sharapova (tênis) - cristã. (10) Joel Osteen (não atleta) - pastor, mas muitos atletas mencionam sua influência. Como testemunhar no esporte: (a) Orar antes e depois dos jogos. (b) Agradecer a Deus pela vitória ou derrota. (c) Tratar adversários com respeito. (d) Ser humilde (não se gabar). (e) Compartilhar o evangelho com colegas. (f) Participar de missões esportivas. (g) Criar clubes cristãos (Atletas em Cristo). (h) Usar uniformes com versículos. (i) Dar entrevistas testemunhais. (j) Envolver-se em projetos sociais através do esporte. A teologia reformada (Schaeffer, Keller) incentiva o testemunho público da fé, com humildade. 'Portanto, ide, ensinai todas as nações' (Mateus 28:19).",
            referencias: "Mateus 28:19; Atos 1:8; Romanos 1:16; 1 Coríndios 10:31; 1 Pedro 3:15"
        },
        {
            termo: "06. Esporte e Juventude - Formação de Caráter e Discipulado",
            definicao: "O esporte é uma ferramenta poderosa para a formação de caráter e discipulado de jovens. 'Ensina o menino no caminho em que deve andar, e até quando envelhecer não se desviará dele' (Provérbios 22:6). Valores ensinados pelo esporte: (1) Disciplina (1 Coríndios 9:25). (2) Trabalho em equipe (Eclesiastes 4:9-10). (3) Respeito (1 Pedro 2:17). (4) Perseverança (Hebreus 12:1). (5) Humildade (Provérbios 15:33). (6) Excelência (Colossenses 3:23). (7) Lidar com vitórias e derrotas. (8) Controle emocional (Provérbios 16:32). (9) Saúde e cuidado do corpo (1 Coríndios 6:19-20). (10) Amizades saudáveis. Programas cristãos de esporte: (1) Escolinhas de futebol (através de igrejas). (2) Acampamentos esportivos (férias). (3) Ligas cristãs (campeonatos). (4) Clubes esportivos cristãos (Atletas em Cristo). (5) Missões esportivas (projetos sociais). (6) Escolas cristãs com ênfase esportiva. (7) Treinamento de líderes esportivos cristãos. (8) Mentoria de atletas jovens. A teologia reformada (Kuyper, Bavinck) valoriza o esporte como meio de educação integral. 'Fugi da prostituição. Todo o pecado que o homem comete é fora do corpo; mas o que comete prostituição peca contra o seu próprio corpo' (1 Coríndios 6:18).",
            referencias: "Provérbios 22:6; 1 Coríndios 6:19-20; 1 Coríndios 9:24-27; Gálatas 5:22-23; Efésios 4:2-3; 1 Timóteo 4:7-8; 2 Timóteo 2:5; Hebreus 12:11"
        },
        {
            termo: "07. Esporte e Santidade - Evitando os Exageros e a Idolatria",
            definicao: "O esporte pode se tornar idolatria quando é colocado acima de Deus. 'Não terás outros deuses diante de mim' (Êxodo 20:3). Sinais de idolatria esportiva: (1) Assistir esportes no lugar do culto dominical. (2) Gastar mais tempo com esportes do que com Deus. (3) Torcer com violência (ódio ao adversário). (4) Colocar o desempenho esportivo acima da família e da igreja. (5) Usar doping (trapaça). (6) Apostas esportivas (avareza). (7) Orgulho excessivo (Provérbios 16:18). (8) Violência no esporte (agressão). (9) Abuso de substâncias (álcool, drogas). (10) Obsessão por vitórias (perder a perspectiva). Como manter o equilíbrio: (a) Priorizar Deus (Mateus 6:33). (b) Descansar no domingo (Êxodo 20:8-11). (c) Praticar esporte para a glória de Deus (1 Coríndios 10:31). (d) Não apostar (1 Timóteo 6:10). (e) Não usar doping (Levítico 19:35). (f) Torcer com respeito (amor ao próximo). (g) Limitar o tempo de exposição (Efésios 5:15-16). (h) Envolver a família no esporte. (i) Usar o esporte como ferramenta evangelística. (j) Reconhecer que o esporte é temporário, mas Deus é eterno. A teologia reformada (Calvino, Edwards) alerta contra qualquer forma de idolatria. 'Filhinhos, guardai-vos dos ídolos' (1 João 5:21).",
            referencias: "Êxodo 20:3-5; Deuteronômio 5:7-9; Mateus 6:33; 1 Coríndios 10:14; 1 Coríndios 10:31; Gálatas 5:19-21; 1 João 5:21"
        },
        {
            termo: "08. O Sábado e o Esporte - Descanso e Adoração",
            definicao: "O domingo (Dia do Senhor) deve ser um dia de descanso e adoração. 'Lembra-te do dia do sábado, para o santificar' (Êxodo 20:8). 'O sábado foi feito por causa do homem, e não o homem por causa do sábado' (Marcos 2:27). Princípios: (1) O domingo é para adoração (Hebreus 10:25). (2) O domingo é para descanso (Êxodo 20:10). (3) Jogos no domingo? Depende: (a) Competições profissionais no domingo? Cristãos podem se recusar (Eric Liddell). (b) Jogos amadores? Pode ser feito após o culto, com moderação. (c) Assistir esportes no domingo? Pode tirar o foco da adoração. (d) Treinos no domingo? Evitar. (4) Crianças e esportes no domingo: priorizar a igreja. (5) Atletas cristãos: testemunhar recusando jogar no domingo (Eric Liddell). (6) Flexibilidade: em alguns contextos, não há opção (missionários). A teologia reformada (Calvino, Westminster) ensina que o domingo é o sábado cristão, um dia de descanso e adoração. 'Se desviares o teu pé do sábado, de fazeres a tua vontade no meu santo dia... então te deleitarás no Senhor' (Isaías 58:13-14).",
            referencias: "Êxodo 20:8-11; Deuteronômio 5:12-15; Isaías 58:13-14; Marcos 2:27-28; Hebreus 10:25"
        },
        {
            termo: "09. Atletas Cristãos na História - Testemunhas de Fé",
            definicao: "Muitos atletas ao longo da história usaram sua plataforma para testemunhar de Cristo. (1) Eric Liddell (1902-1945) - atleta olímpico (400m, 1924), recusou correr no domingo, missionário na China, morreu em campo de concentração japonês. (2) Tim Tebow (1987-) - jogador de futebol americano, testemunhou abertamente, orava no campo, usava versículos bíblicos. (3) Kaká (1982-) - jogador de futebol, camisa 'Eu pertenço a Jesus', testemunhou publicamente. (4) Neymar (1992-) - cristão declarado, mas vida pessoal controversa. (5) David Luiz (1987-) - cristão, testemunha publicamente. (6) Oscar Schmidt (1958-) - basquetebolista, cristão. (7) Felipe Luis (1985-) - cristão. (8) André Agassi (1970-) - cristão (na juventude). (9) Maria Sharapova (1987-) - cristã. (10) Stephen Curry (1988-) - basquetebolista, cristão. (11) LeBron James (1984-) - cristão (declarado). (12) Serena Williams (1981-) - cristã. (13) Usain Bolt (1986-) - cristão. (14) Michael Phelps (1985-) - cristão (convertido). (15) Tyson Fury (1988-) - boxeador, cristão. A teologia reformada (Calvino, Kuyper) celebra o testemunho público da fé, inclusive no esporte. 'Porque não me envergonho do evangelho de Cristo' (Romanos 1:16).",
            referencias: "Romanos 1:16; 1 Coríndios 9:24-27; Filipenses 3:14; 1 Pedro 3:15"
        },
        {
            termo: "10. Esporte e Missões - Evangelismo Através do Esporte",
            definicao: "O esporte pode ser uma ferramenta missionária eficaz, especialmente entre jovens e em países fechados. 'Fiz-me tudo para todos, para por todos os meios chegar a salvar alguns' (1 Coríndios 9:22). Estratégias missionárias: (1) Escolinhas de futebol em comunidades carentes. (2) Acampamentos esportivos (evangelismo). (3) Missões esportivas de curto prazo. (4) Parceria com organizações como 'Atletas em Cristo', 'Esporte para Todos', 'Missão Esportiva'. (5) Uso de atletas cristãos como embaixadores. (6) Evangelismo em estádios (eventos). (7) Clubes cristãos em países fechados (subterrâneo). (8) Distribuição de Bíblias em eventos esportivos. (9) Testemunho de atletas convertidos. (10) Plantação de igrejas através de projetos esportivos. Exemplos: (1) Missionários que usam futebol para alcançar crianças. (2) Igrejas que têm escolinhas de futebol como porta de entrada. (3) Acampamentos de férias com atividades esportivas. (4) Ligas esportivas entre igrejas. (5) Torneios de evangelismo. A teologia reformada (Kuyper, Bavinck) incentiva o uso criativo de meios para o evangelismo. 'Ide, ensinai todas as nações' (Mateus 28:19). 'Como, pois, invocarão aquele em quem não creram? e como crerão naquele de quem não ouviram?' (Romanos 10:14).",
            referencias: "Mateus 28:19-20; Atos 1:8; Romanos 10:13-15; 1 Coríndios 9:19-23; 2 Coríndios 5:18-20"
        },
        {
            termo: "11. Esporte e Saúde - Mordomia do Corpo",
            definicao: "O corpo é um dom de Deus e deve ser cuidado como mordomia. 'Não sabeis vós que o vosso corpo é o templo do Espírito Santo... e que não sois de vós mesmos? Porque fostes comprados por bom preço; glorificai, pois, a Deus no vosso corpo e no vosso espírito, os quais pertencem a Deus' (1 Coríndios 6:19-20). Práticas saudáveis: (1) Alimentação balanceada (não gluttonia). (2) Exercícios regulares (1 Timóteo 4:8). (3) Descanso adequado (Êxodo 20:8-11). (4) Evitar substâncias nocivas (álcool, drogas, tabaco). (5) Check-ups médicos regulares. (6) Saúde mental (orar, terapia). (7) Saúde espiritual (oração, Bíblia). (8) Evitar excessos (competição excessiva). (9) Evitar lesões (prudência). (10) Envelhecer com dignidade. A teologia reformada (Calvino, Bavinck) enfatiza a mordomia do corpo como parte da santificação. 'Tende cuidado de vós mesmos e de toda a igreja' (Atos 20:28). 'Ora, o Deus de paz vos santifique em tudo' (1 Tessalonicenses 5:23).",
            referencias: "Atos 20:28; 1 Coríndios 3:16-17; 1 Coríndios 6:19-20; 1 Timóteo 4:8; 1 Tessalonicenses 5:23"
        },
        {
            termo: "12. Esporte e Eternidade - O que Resta?",
            definicao: "O esporte é temporário, mas a glória de Deus é eterna. 'Aquele que luta, de tudo se abstém; eles o fazem para alcançar uma coroa corruptível, nós, porém, uma incorruptível' (1 Coríndios 9:25). 'Pois exercita-te a ti mesmo em piedade; porque o exercício corporal para pouco é proveitoso, mas a piedade para tudo é proveitosa' (1 Timóteo 4:7-8). O que resta do esporte: (1) As virtudes desenvolvidas (disciplina, perseverança). (2) As amizades formadas. (3) O testemunho deixado. (4) As almas alcançadas para Cristo. (5) O exemplo para as próximas gerações. (6) A glória de Deus refletida. O que não resta: (1) Títulos e medalhas (passageiros). (2) Recordes (serão quebrados). (3) Fama (efêmera). (4) Riquezas (Mateus 6:19-21). (5) Corpo (morrerá). A esperança cristã: a ressurreição do corpo e a nova criação. 'Porque para mim o viver é Cristo, e o morrer é ganho' (Filipenses 1:21). 'E Deus limpará de seus olhos toda lágrima; e não haverá mais morte, nem pranto, nem clamor, nem dor' (Apocalipse 21:4). A teologia reformada (Calvino, Edwards) nos chama a investir no que é eterno. 'Não ajunteis tesouros na terra... mas ajuntai tesouros no céu' (Mateus 6:19-20).",
            referencias: "Mateus 6:19-21; 1 Coríndios 9:24-27; 2 Coríndios 4:17-18; Filipenses 1:21; 1 Timóteo 4:7-8; 1 Pedro 1:24-25"
        },
        {
            termo: "13. Síntese: Esporte para a Glória de Cristo",
            definicao: "O esporte pode ser uma atividade que glorifica a Deus quando praticado com fé, amor, integridade e humildade. 'Portanto, quer comais quer bebais, ou façais outra qualquer coisa, fazei tudo para glória de Deus' (1 Coríndios 10:31). Resumo da teologia do esporte: (1) O corpo é criação boa de Deus (Gênesis 1:31). (2) Cristo assumiu um corpo humano (João 1:14) e ressuscitou corporalmente (Lucas 24:39-43). (3) O esporte desenvolve virtudes (disciplina, perseverança). (4) A ética esportiva exige integridade, fair play, e rejeição do doping (Levítico 19:35). (5) Atletas cristãos podem testemunhar de Cristo (1 Pedro 3:15). (6) O esporte forma o caráter de jovens (Provérbios 22:6). (7) Devemos evitar a idolatria esportiva (Êxodo 20:3). (8) O domingo deve ser um dia de descanso e adoração (Êxodo 20:8-11). (9) O esporte pode ser uma ferramenta missionária (1 Coríndios 9:22). (10) Devemos cuidar do corpo como mordomia (1 Coríndios 6:19-20). (11) O esporte é temporário, mas a glória de Deus é eterna (1 Coríndios 9:25). (12) A esperança cristã é a ressurreição do corpo (Filipenses 3:20-21). (13) Todo esporte deve ser para a glória de Cristo (1 Coríndios 10:31). 'E tudo quanto fizerdes, por palavra ou por obra, fazei-o em nome do Senhor Jesus, dando por ele graças a Deus Pai' (Colossenses 3:17). Soli Deo Gloria!",
            referencias: "Romanos 11:36; 1 Coríndios 10:31; Colossenses 3:17; 1 Pedro 4:10-11; Apocalipse 21:4"
        }
    ]
};