// volume/volume-22.js
window.LIVRO_DATA = {
    nome: "Volume XXII",
    dados: [
        {
            termo: "01. Introdução: Os Concílios Ecumênicos e a Definição da Ortodoxia Cristológica",
            definicao: "Os concílios ecumênicos (universais) foram assembléias de bispos de todo o Império Romano (e depois de toda a cristandade) que se reuniram para definir a doutrina cristã contra heresias e promover a unidade da igreja. A teologia reformada aceita os primeiros seis concílios ecumênicos (Nicéia I, Constantinopla I, Éfeso, Calcedônia, Constantinopla II, Constantinopla III) como exposições fiéis da Escritura, embora subordinados à autoridade final da Palavra de Deus (Sola Scriptura). O Concílio de Nicéia II (787 d.C.), que tratou da veneração de ícones, é rejeitado pela tradição reformada (violação do segundo mandamento). Este volume apresenta os documentos principais de cada concílio: credos, definições, cânones e anatematismos. 'Examinais as Escrituras... e são elas que de mim testificam' (João 5:39).",
            referencias: "João 5:39; Atos 15:1-29; Atos 16:4-5; Efésios 4:4-6; 1 Timóteo 3:15; Judas 1:3"
        },
        {
            termo: "02. Concílio de Nicéia I (325 d.C.) - Credo Niceno Original",
            definicao: "O Primeiro Concílio Ecumênico (Nicéia, 325 d.C.), convocado pelo imperador Constantino, condenou o arianismo (Ário) e definiu a divindade de Cristo com o termo homoousios ('da mesma substância'). Credo Niceno Original: 'Cremos em um só Deus, Pai Todo-poderoso, Criador de todas as coisas visíveis e invisíveis. E em um só Senhor Jesus Cristo, o Filho de Deus, unigênito, gerado do Pai, isto é, da substância do Pai; Deus de Deus, luz de luz, Deus verdadeiro de Deus verdadeiro; gerado, não criado; consubstancial (homoousios) ao Pai; por quem todas as coisas foram feitas, tanto as do céu como as da terra; que, por amor de nós homens e por nossa salvação, desceu, se encarnou, se fez homem, padeceu e ressuscitou ao terceiro dia, subiu aos céus, e há de vir para julgar os vivos e os mortos. E no Espírito Santo. E aos que dizem: 'Houve tempo em que ele não existia', e 'antes de ser gerado não existia', e 'ele foi criado do nada', ou 'ele é de outra substância ou essência', ou 'o Filho de Deus é criado, mutável ou variável', estes a igreja católica e apostólica anatematiza.' Comentário reformado: Nicéia I é o fundamento da ortodoxia trinitária e cristológica. O termo homoousios ('consubstancial') exclui o arianismo (Jesus é uma criatura). A teologia reformada aceita Nicéia como norma subordinada à Escritura.",
            referencias: "João 1:1-14; João 1:18; João 10:30; João 14:9; Filipenses 2:5-6; Colossenses 1:15-17; Colossenses 2:9; Hebreus 1:1-4"
        },
        {
            termo: "03. Concílio de Constantinopla I (381 d.C.) - Credo Niceno-Constantinopolitano",
            definicao: "O Primeiro Concílio de Constantinopla (381 d.C.), convocado pelo imperador Teodósio I, confirmou Nicéia, expandiu o Credo (seção sobre o Espírito Santo), e condenou o apolinarianismo (Apolinário de Laodiceia, que negava a alma racional de Cristo). Credo Niceno-Constantinopolitano (texto usado hoje): 'Creio em um só Deus, Pai Todo-poderoso, Criador do céu e da terra, de todas as coisas visíveis e invisíveis. E em um só Senhor Jesus Cristo, o Filho de Deus, unigênito, gerado do Pai antes de todos os séculos; Deus de Deus, luz de luz, Deus verdadeiro de Deus verdadeiro; gerado, não criado; consubstancial ao Pai; por quem todas as coisas foram feitas; que por nós homens e por nossa salvação desceu dos céus, e se encarnou pelo Espírito Santo no seio da virgem Maria, e se fez homem; foi crucificado por nós sob Pôncio Pilatos, padeceu e foi sepultado; e ao terceiro dia ressurgiu segundo as Escrituras; e subiu aos céus, e está assentado à direita do Pai; e de novo há de vir com glória para julgar os vivos e os mortos; o seu reino não terá fim.' Comentário reformado: Constantinopla I completa a doutrina da Trindade (divindade do Espírito Santo) e rejeita o apolinarianismo (Cristo tem alma humana). A teologia reformada aceita este credo como norma.",
            referencias: "João 1:1-14; João 14:16-17; Atos 2:33; Romanos 1:3-4; Filipenses 2:5-11; Colossenses 1:15-20; 1 Timóteo 3:16; Tito 2:13; Hebreus 4:15"
        },
        {
            termo: "04. Concílio de Éfeso (431 d.C.) - Condenação de Nestório",
            definicao: "O Terceiro Concílio Ecumênico (Éfeso, 431 d.C.), convocado pelo imperador Teodósio II, condenou o nestorianismo (Nestório, que separava as naturezas de Cristo a ponto de quase duas pessoas) e aprovou o título Theotokos ('Mãe de Deus') para Maria. Definição conciliar: 'O Verbo, unindo a si mesmo a carne animada por alma racional, se fez homem... a santa virgem é Theotokos, porque o Verbo de Deus se encarnou e se fez homem, e desde sua concepção uniu a si mesmo o templo que dela recebeu.' Anatematismos de Cirilo de Alexandria (12): (1) 'Se alguém não confessa que Emanuel é verdadeiramente Deus, e que a santa virgem é Theotokos... seja anátema.' (2) 'Se alguém não confessa que o Verbo de Deus foi unido à carne hipostaticamente... seja anátema.' (3) 'Se alguém confessa que Cristo é duas pessoas... seja anátema.' Comentário reformado: Éfeso rejeita o nestorianismo (separação das naturezas) e afirma a unidade da pessoa de Cristo. A teologia reformada aceita Theotokos como afirmação da encarnação (não como exaltação de Maria).",
            referencias: "Lucas 1:26-38; Lucas 1:43; João 1:14; Gálatas 4:4; Filipenses 2:5-11; 1 Timóteo 3:16; 1 João 4:2-3"
        },
        {
            termo: "05. Concílio de Calcedônia (451 d.C.) - Definição de Calcedônia",
            definicao: "O Quarto Concílio Ecumênico (Calcedônia, 451 d.C.), convocado pelo imperador Marciano, condenou o monofisismo (Eutiques, que confundia as naturezas) e produziu a Definição Calcedoniana, o documento cristológico mais importante da igreja antiga. Definição: 'Seguindo, pois, os santos padres, unanimemente ensinamos que devemos confessar um só e mesmo Filho, nosso Senhor Jesus Cristo, perfeito em divindade e perfeito em humanidade, verdadeiramente Deus e verdadeiramente homem, de alma racional e corpo; consubstancial (homoousios) ao Pai segundo a divindade, e consubstancial a nós segundo a humanidade, em tudo semelhante a nós, exceto no pecado; gerado do Pai antes dos séculos segundo a divindade, e nestes últimos dias, por nós e por nossa salvação, nascido de Maria, a virgem e Mãe de Deus (Theotokos), segundo a humanidade. (Confessamos) um só e mesmo Cristo, Senhor, Filho unigênito, em duas naturezas (en dyo physesin), sem confusão (asygchytōs), sem mudança (atreptōs), sem divisão (adiairetōs), sem separação (achōristōs). A diferença das naturezas não é de modo algum removida pela união; ao contrário, a propriedade de cada natureza é preservada e concorre para uma só pessoa (prosopon) e uma só hipóstase (hypostasis).' Comentário reformado: Calcedônia é a 'parede de pedra da ortodoxia'. Os quatro advérbios (sem confusão, sem mudança, sem divisão, sem separação) são essenciais para a cristologia reformada.",
            referencias: "João 1:14; Romanos 1:3-4; Romanos 9:5; Filipenses 2:5-11; Colossenses 1:15-20; Colossenses 2:9; 1 Timóteo 3:16; Tito 2:13; Hebreus 1:1-4"
        },
        {
            termo: "06. Concílio de Calcedônia - Cânones e Tomus de Leão",
            definicao: "Além da Definição, o Concílio de Calcedônia também aprovou 28 cânones (disciplinares) e confirmou o 'Tomus ad Flavianum' do papa Leão Magno (449 d.C.). Excerto do Tomus: 'Sem diminuir, pois, a propriedade de cada uma das naturezas, que se unem em uma só pessoa, a majestade assume a humildade, a fortaleza a fraqueza, a eternidade a mortalidade. Para pagar a dívida de nossa condição, a natureza impassível se uniu à natureza passível, e para satisfazer nossa cura, o verdadeiro Deus e o verdadeiro homem se fundiram em um só Senhor.' Comentário reformado: O Tomus de Leão é a base da Definição Calcedoniana. A teologia reformada valoriza o Tomus como uma exposição clara da cristologia ortodoxa.",
            referencias: "Hebreus 1:1-4; Hebreus 2:14-18; 1 Pedro 3:18"
        },
        {
            termo: "07. Concílio de Constantinopla II (553 d.C.) - Condenação dos Três Capítulos",
            definicao: "O Quinto Concílio Ecumênico (Constantinopla II, 553 d.C.), convocado pelo imperador Justiniano I, condenou os 'Três Capítulos' (Tria Capitula): (1) A pessoa e os escritos de Teodoro de Mopsuéstia (mestre de Nestório). (2) Os escritos de Teodoreto de Ciro contra Cirilo. (3) A carta de Ibas de Edessa a Maris (considerada nestoriana). O concílio reafirmou Calcedônia e condenou o nestorianismo. Definição: 'Se alguém não confessa que o nosso Senhor Jesus Cristo, que foi crucificado na carne, é verdadeiramente Deus e Senhor da glória... seja anátema.' Comentário reformado: Constantinopla II reafirma a ortodoxia calcedoniana. A teologia reformada aceita este concílio, embora tenha menos importância que Nicéia e Calcedônia.",
            referencias: "João 1:14; Filipenses 2:5-11; Colossenses 2:9; 1 Timóteo 3:16; Tito 2:13"
        },
        {
            termo: "08. Concílio de Constantinopla III (680-681 d.C.) - Contra o Monotelismo",
            definicao: "O Sexto Concílio Ecumênico (Constantinopla III, 680-681 d.C.), convocado pelo imperador Constantino IV, condenou o monotelismo (doutrina de que Cristo tem uma só vontade) e afirmou que Cristo tem duas vontades (divina e humana) e duas operações. Definição: 'Confessamos que nele [Cristo] há duas vontades naturais e duas operações naturais... a vontade humana segue a divina, não resistindo nem se opondo, mas submetendo-se.' O concílio também condenou o papa Honório I (625-638 d.C.), que havia aprovado o monotelismo. 'Se alguém não confessa que em Cristo há duas vontades e duas operações... seja anátema.' Comentário reformado: Constantinopla III é importante para a doutrina da impecabilidade de Cristo (sua vontade humana era perfeitamente conformada à divina). A teologia reformada aceita este concílio.",
            referencias: "João 4:34; João 5:30; João 6:38; Mateus 26:39; Mateus 26:42; Lucas 22:42; Filipenses 2:8; Hebreus 5:8"
        },
        {
            termo: "09. Concílio de Nicéia II (787 d.C.) - Veneração de Ícones (Rejeitado pela Reforma)",
            definicao: "O Sétimo Concílio Ecumênico (Nicéia II, 787 d.C.), convocado pela imperatriz Irene, tratou da controvérsia iconoclasta (destruição de imagens). O concílio afirmou a veneração (proskynēsis) de ícones (imagens) de Cristo, da virgem Maria e dos santos, mas não a adoração (latreia), que é devida somente a Deus. Definição: 'Aquele que venera um ícone venera a pessoa nele representada.' O concílio baseou-se na doutrina da encarnação: se Deus se fez carne (João 1:14), ele pode ser representado em imagem. A teologia reformada (Lutero, Calvino, Zwinglio) rejeitou Nicéia II, considerando a veneração de ícones como violação do segundo mandamento (Êxodo 20:4-6; Deuteronômio 5:8-10). Calvino e os reformados (exceto Lutero, que permitiu imagens em igrejas luteranas) foram iconoclastas (removeram imagens das igrejas). Comentário reformado: Nicéia II não é aceito pela tradição reformada. 'Não farás para ti imagem de escultura, nem alguma semelhança do que há em cima nos céus... não te encurvarás a elas nem as servirás' (Êxodo 20:4-5).",
            referencias: "Êxodo 20:4-6; Deuteronômio 5:8-10; João 1:14; Romanos 1:23; 1 João 5:21"
        },
        {
            termo: "10. Tabela Comparativa dos Concílios Cristológicos",
            definicao: "Tabela resumo dos concílios ecumênicos sobre cristologia (os sete primeiros, com observação sobre Nicéia II). (1) Nicéia I (325): condenou o arianismo; afirmou o homoousios (Filho consubstancial ao Pai). (2) Constantinopla I (381): condenou o apolinarianismo; afirmou a plena humanidade de Cristo (alma racional). (3) Éfeso (431): condenou o nestorianismo; afirmou a unidade da pessoa de Cristo; aprovou Theotokos. (4) Calcedônia (451): condenou o monofisismo/eutiquianismo; afirmou 'duas naturezas em uma pessoa' (sem confusão, sem mudança, sem divisão, sem separação). (5) Constantinopla II (553): condenou os 'Três Capítulos' (nestorianos); reafirmou Calcedônia. (6) Constantinopla III (680-681): condenou o monotelismo; afirmou duas vontades e duas operações em Cristo. (7) Nicéia II (787): afirmou a veneração de ícones (rejeitado pela Reforma). A teologia reformada aceita os concílios 1-6, rejeita o 7º.",
            referencias: "João 1:14; Filipenses 2:5-11; Colossenses 2:9; 1 Timóteo 3:16; Tito 2:13; Hebreus 1:1-4"
        },
        {
            termo: "11. O Credo dos Apóstolos e o Credo Atanasiano",
            definicao: "Embora não sejam produtos de concílios ecumênicos, o Credo dos Apóstolos (século II-VI) e o Credo Atanasiano (Símbolo Quicumque, século V-VI) são credos cristológicos importantes. Credo dos Apóstolos: 'Creio... em Jesus Cristo, seu único Filho, nosso Senhor; o qual foi concebido pelo Espírito Santo; nasceu da virgem Maria; padeceu sob o poder de Pôncio Pilatos; foi crucificado, morto e sepultado; desceu ao inferno; ao terceiro dia ressurgiu dos mortos; subiu ao céu; está assentado à direita de Deus Pai Todo-poderoso; donde há de vir a julgar os vivos e os mortos.' Credo Atanasiano (excerto cristológico): 'A fé verdadeira é que cremos e confessamos que nosso Senhor Jesus Cristo, o Filho de Deus, é Deus e homem; é Deus da substância do Pai, gerado antes dos séculos; e é homem da substância da mãe, nascido no mundo; perfeitamente Deus e perfeitamente homem... igual ao Pai quanto à divindade, menor que o Pai quanto à humanidade; o qual, embora seja Deus e homem, não são dois, mas um só Cristo.' Comentário reformado: A teologia reformada aceita ambos os credos como exposições fiéis da Escritura.",
            referencias: "Mateus 1:18-25; Lucas 1:26-38; João 1:14; João 14:28; Filipenses 2:5-11; 1 Timóteo 3:16; Tito 2:13"
        },
        {
            termo: "12. As Confissões Reformadas sobre Cristologia (Westminster, Heidelberg, Dort)",
            definicao: "As confissões reformadas (século XVI-XVII) resumiram a cristologia calcedoniana. (1) Catecismo de Heidelberg (1563): Pergunta 17: 'Por que ele precisa ser verdadeiro Deus e verdadeiro homem?' Resposta: 'Para que, como verdadeiro Deus, seu sacrifício e obediência fossem de valor infinito, e como verdadeiro homem, pudesse sofrer e morrer por nós.' (2) Confissão de Fé de Westminster (1647), Capítulo VIII: 'O Filho de Deus... assumiu a natureza humana... duas naturezas inteiras, perfeitas e distintas, inseparavelmente unidas em uma só pessoa, sem conversão, composição ou confusão.' (3) Cânones de Dort (1619): 'A morte do Filho de Deus é o único e mais perfeito sacrifício e satisfação pelos pecados; de valor infinito, abundantemente suficiente para expiar os pecados de todo o mundo.' Comentário reformado: As confissões reformadas estão em continuidade com os concílios ecumênicos (Nicéia, Calcedônia).",
            referencias: "João 1:14; Romanos 3:23-26; Filipenses 2:5-11; Colossenses 2:9; 1 Timóteo 2:5; Tito 2:13-14"
        },
        {
            termo: "13. Síntese: A Autoridade dos Concílios na Teologia Reformada",
            definicao: "A teologia reformada reconhece os concílios ecumênicos (Nicéia I, Constantinopla I, Éfeso, Calcedônia, Constantinopla II, Constantinopla III) como exposições fiéis da Escritura, mas não como infalíveis. 'Somente a Escritura é a regra infalível de fé' (Sola Scriptura). Os concílios podem errar (Nicéia II errou sobre ícones). O princípio reformado é: 'A igreja pode errar, a Escritura não pode errar.' Os credos e confissões são 'normas subordinadas' (norma normata), sujeitas à correção pela Escritura (norma normans). A cristologia reformada está em continuidade com a definição calcedoniana (duas naturezas em uma pessoa) e com a tradição nicena (homoousios). 'Examinais as Escrituras' (João 5:39).",
            referencias: "João 5:39; Atos 17:11; 2 Timóteo 3:16-17; 1 Pedro 4:11; 2 Pedro 1:19-21"
        }
    ]
};