// volume/volume-35.js
window.LIVRO_DATA = {
    nome: "Volume XXXV",
    dados: [
        {
            termo: "01. Introdução: A Adoração Cristocêntrica por meio dos Hinos",
            definicao: "A música e o canto são partes integrantes da adoração cristã desde os tempos bíblicos. O apóstolo Paulo exortou: 'Falando entre vós com salmos, e hinos, e cânticos espirituais; cantando e salmodiando ao Senhor no vosso coração' (Efésios 5:19). 'A palavra de Cristo habite em vós abundantemente, em toda a sabedoria, ensinando-vos e admoestando-vos uns aos outros, com salmos, hinos e cânticos espirituais, cantando com graça em vossos corações ao Senhor' (Colossenses 3:16). Os hinos cristocêntricos são aqueles que centram seu conteúdo na pessoa e obra de Jesus Cristo: sua pré-existência, encarnação, vida, morte, ressurreição, ascensão, intercessão, segunda vinda e reinado eterno. Este volume apresenta uma antologia dos principais hinos cristológicos da história da igreja, com análises teológicas e sugestões de uso litúrgico. A teologia reformada valoriza os hinos como meio de ensino doutrinário, adoração e edificação da igreja. 'Cantai ao Senhor um cântico novo, cantai ao Senhor, todas as terras' (Salmo 96:1).",
            referencias: "Salmo 96:1; Salmo 98:1; Efésios 5:19; Colossenses 3:16; Tiago 5:13; Apocalipse 5:9-10; Apocalipse 15:3-4"
        },
        {
            termo: "02. Hinos Cristológicos do Novo Testamento - Filipenses 2:5-11",
            definicao: "O hino de Filipenses 2:5-11 é o mais antigo e importante hino cristológico do Novo Testamento (provavelmente do século I). Texto: 'Tende em vós o mesmo sentimento que houve também em Cristo Jesus, que, sendo em forma de Deus, não considerou o ser igual a Deus como algo a que se apegar, mas esvaziou-se a si mesmo, tomando a forma de servo, fazendo-se semelhante aos homens; e, achado na forma de homem, humilhou-se a si mesmo, sendo obediente até à morte, e morte de cruz. Pelo que também Deus o exaltou soberanamente, e lhe deu um nome que é sobre todo o nome, para que ao nome de Jesus se dobre todo joelho dos que estão nos céus, e na terra, e debaixo da terra, e toda língua confesse que Jesus Cristo é o Senhor, para glória de Deus Pai.' Análise teológica: (1) A pré-existência de Cristo ('sendo em forma de Deus'). (2) A kenosis ('esvaziou-se a si mesmo'). (3) A encarnação ('tomando a forma de servo'). (4) A humilhação ('humilhou-se a si mesmo... até à morte, e morte de cruz'). (5) A exaltação ('Deus o exaltou soberanamente'). (6) O senhorio universal ('ao nome de Jesus se dobre todo joelho'). (7) A confissão cristológica ('toda língua confesse que Jesus Cristo é o Senhor'). Uso litúrgico: Pode ser cantado ou recitado no culto, especialmente na Quaresma (sofrimento) e Páscoa (exaltação).",
            referencias: "Filipenses 2:5-11; João 1:1-14; Atos 2:33; Romanos 10:9; 1 Timóteo 3:16"
        },
        {
            termo: "03. Hinos Cristológicos do Novo Testamento - Colossenses 1:15-20",
            definicao: "O hino de Colossenses 1:15-20 é o mais elevado hino cristológico sobre a supremacia cósmica de Cristo. Texto: 'Ele é a imagem do Deus invisível, o primogênito de toda a criação; porque nele foram criadas todas as coisas que há nos céus e na terra, visíveis e invisíveis, sejam tronos, sejam dominações, sejam principados, sejam potestades; tudo foi criado por ele e para ele. E ele é antes de todas as coisas, e todas as coisas subsistem por ele. E ele é a cabeça do corpo, da igreja; é o princípio e o primogênito dos mortos, para que em todas as coisas tenha a preeminência. Porque foi do agrado do Pai que toda a plenitude nele habitasse, e que, havendo por ele feito a paz pelo sangue da sua cruz, por meio dele reconciliasse consigo mesmo todas as coisas, tanto as que estão na terra como as que estão nos céus.' Análise teológica: (1) Cristo como imagem de Deus (eikōn). (2) Cristo como primogênito (prōtotokos) - primazia, não primeiro criado. (3) Cristo como Criador ('nele foram criadas todas as coisas'). (4) Cristo como Sustentador ('todas as coisas subsistem por ele'). (5) Cristo como Cabeça da igreja. (6) Cristo como primogênito dos mortos (ressurreição). (7) A plenitude (plērōma) de Deus em Cristo. (8) A reconciliação cósmica pelo sangue da cruz. Uso litúrgico: Ideal para o Pentecostes (ênfase na igreja) e Páscoa (ressurreição), ou para cultos de ação de graças.",
            referencias: "Colossenses 1:15-20; João 1:1-3; Romanos 8:19-22; Efésios 1:20-23; Hebreus 1:1-4"
        },
        {
            termo: "04. Hinos Cristológicos do Novo Testamento - João 1:1-18",
            definicao: "O Prólogo do Evangelho de João (João 1:1-18) é um dos mais ricos hinos cristológicos do Novo Testamento. Texto (excerto): 'No princípio era o Verbo, e o Verbo estava com Deus, e o Verbo era Deus. Ele estava no princípio com Deus. Todas as coisas foram feitas por ele, e sem ele nada do que foi feito se fez. Nele estava a vida, e a vida era a luz dos homens... E o Verbo se fez carne, e habitou entre nós, e vimos a sua glória, glória como do unigênito do Pai, cheio de graça e de verdade.' Análise teológica: (1) A pré-existência eterna do Verbo ('No princípio era o Verbo'). (2) A divindade do Verbo ('o Verbo era Deus'). (3) A criação pelo Verbo ('todas as coisas foram feitas por ele'). (4) A vida e a luz ('nele estava a vida, e a vida era a luz'). (5) A encarnação ('o Verbo se fez carne'). (6) A glória do Unigênito ('vimos a sua glória'). (7) A graça e verdade ('cheio de graça e de verdade'). Uso litúrgico: Excelente para o Natal (encarnação) e Epifania (manifestação).",
            referencias: "João 1:1-18; Gênesis 1:1; Provérbios 8:22-31; Colossenses 1:15-17; Hebreus 1:1-4"
        },
        {
            termo: "05. Hinos Cristológicos do Novo Testamento - 1 Timóteo 3:16 e Hebreus 1:1-4",
            definicao: "Outros hinos cristológicos do Novo Testamento incluem 1 Timóteo 3:16 e Hebreus 1:1-4. (1) 1 Timóteo 3:16: 'E, sem dúvida, grande é o mistério da piedade: Deus se manifestou em carne, foi justificado no Espírito, visto dos anjos, pregado aos gentios, crido no mundo, recebido acima na glória.' Análise: Seis declarações sobre a pessoa e obra de Cristo: encarnação, ressurreição/justificação, testemunho angelical, pregação aos gentios, fé no mundo, ascensão/glória. (2) Hebreus 1:1-4: 'Havendo Deus antigamente falado muitas vezes e de muitas maneiras pelos profetas, a nós falou-nos nestes últimos dias pelo Filho, a quem constituiu herdeiro de todas as coisas, por quem fez também o mundo. O qual, sendo o resplendor da sua glória e a expressa imagem da sua pessoa, e sustentando todas as coisas pela palavra do seu poder, havendo feito por si mesmo a purificação dos nossos pecados, assentou-se à destra da majestade nas alturas, feito tanto mais excelente do que os anjos, quanto herdou mais excelente nome do que eles.' Análise: (a) A revelação final do Filho. (b) O Filho como herdeiro de todas as coisas. (c) O Filho como mediador da criação. (d) O Filho como resplendor da glória de Deus. (e) O Filho como expressa imagem de Deus. (f) O Filho como sustentador do universo. (g) O Filho como purificador dos pecados. (h) O Filho exaltado à direita de Deus. Uso litúrgico: 1 Timóteo 3:16 pode ser usado no Natal (encarnação) e Ascensão; Hebreus 1:1-4 pode ser usado no Natal ou cultos de abertura do ano.",
            referencias: "1 Timóteo 3:16; Hebreus 1:1-4; Atos 2:33; Efésios 1:20-23"
        },
        {
            termo: "06. Hinos dos Pais da Igreja - Te Deum Laudamus (séc. IV-V)",
            definicao: "O 'Te Deum Laudamus' ('A Ti, ó Deus, louvamos') é um dos mais antigos e solenes hinos da igreja cristã, atribuído a Niceta de Remesiana (c. 335-414 d.C.) ou a Agostinho e Ambrósio (tradicionalmente associado ao batismo de Agostinho em 387 d.C.). Texto (parte cristológica): 'A ti, Deus, louvamos; a ti, Senhor, glorificamos... Tu és o Rei da glória, ó Cristo; tu és o Filho eterno do Pai. Tu, para libertares o homem, não desprezaste o ventre da virgem. Tu, vencido o aguilhão da morte, abriste aos crentes o reino dos céus. Tu estás à direita de Deus, na glória do Pai. Nós cremos que tu hás de vir como Juiz. Portanto, te rogamos, socorre os teus servos, que remiste com teu precioso sangue.' Análise teológica: (1) Cristo como Rei da glória. (2) Cristo como Filho eterno do Pai. (3) A encarnação ('não desprezaste o ventre da virgem'). (4) A vitória sobre a morte ('vencido o aguilhão da morte'). (5) A ascensão ('estás à direita de Deus'). (6) A segunda vinda ('hás de vir como Juiz'). (7) A redenção pelo sangue ('remiste com teu precioso sangue'). Uso litúrgico: Cantado em ocasiões solenes (Natal, Páscoa, Pentecostes, ordenações, dedicações).",
            referencias: "Salmo 145:1-21; Apocalipse 19:6; Filipenses 2:9-11; 1 Pedro 1:18-19; 1 Timóteo 2:5"
        },
        {
            termo: "07. Hinos da Reforma - Castelo Forte (Lutero) e outras",
            definicao: "Os reformadores produziram hinos cristocêntricos que se tornaram clássicos. (1) 'Castelo Forte é Nosso Deus' (Ein feste Burg ist unser Gott), de Martinho Lutero (1529). Texto (excerto): 'Castelo forte é nosso Deus, espada e bom escudo; com seu poder defende os seus, a Igreja em todo o mundo. O nosso grande opressor, com arte e com fúria, perturba o mundo inteiro. Não há no chão igual poder, nem força, nem valor. Não podemos, por nós, vencer, pois somos bem pequenos; mas Cristo luta por nós, é o Senhor dos senhores, Jesus Cristo, o Senhor, Deus forte e vencedor, que vencerá por nós.' Análise: O hino é cristocêntrico, centrado em Cristo como o guerreiro que luta por nós. (2) 'Ó divina Redentora' (Allein Gott in der Höh sei Ehr), de Nikolaus Decius (1523-1526) - paráfrase do Gloria in Excelsis. (3) 'Louvado seja o Senhor' (Nun lob, mein Seel, den Herren), de Johann Gramann (1530). (4) 'Ao Deus por nós, que vida nos dá' (Erhalt uns, Herr, bei deinem Wort), de Lutero (1542). Uso litúrgico: Cantados em cultos reformados e luteranos, especialmente 'Castelo Forte' (Domingos após Pentecostes, celebrações da Reforma).",
            referencias: "Salmo 46:1-11; Efésios 6:10-18; 1 João 4:4; Apocalipse 12:10-11"
        },
        {
            termo: "08. Hinos de Isaac Watts (1674-1748) - Cristo Crucificado e Glorificado",
            definicao: "Isaac Watts, o 'pai do hino inglês', escreveu centenas de hinos cristocêntricos. (1) 'Quando eu contemplo a cruz' (When I Survey the Wondrous Cross, 1707). Texto (excerto): 'Quando eu contemplo a cruz, onde meu Senhor morreu, tão grande a dor, tão vil a luz, perde o mundo o encanto seu. Maldita seja a minha glória, e o meu orgulho ante a cruz; renuncio ao meu viver ilusório, só pra viver, Senhor Jesus.' Análise: Contemplação da cruz, renúncia ao mundo, consagração a Cristo. (2) 'Amor insondável' (Amazing Love! How Can It Be? - baseado em 'And Can It Be That I Should Gain?', 1738, de Charles Wesley, muitas vezes atribuído a Watts). (3) 'Jesus, amado Salvador' (Jesus Shall Reign Where'er the Sun, 1719) - baseado no Salmo 72 sobre o reinado universal de Cristo. (4) 'Alegrai-vos, filhos do Rei' (Joy to the World, 1719) - baseado no Salmo 98, sobre a segunda vinda de Cristo. Análise de 'Jesus Shall Reign': 'Jesus reinará onde o sol passar, onde as nações, do nascer ao poente, lhe trouxerem louvor. Seu reino, Senhor, se estenderá, e todo o império que há de vir, e todo o mundo entoará: Em cada ser, em cada flor, se vê o teu amor, Senhor; e terra, céus e céu dos céus, proclamam que Jesus é Deus.' Uso litúrgico: Natal ('Joy to the World'), Páscoa ('When I Survey'), Missões ('Jesus Shall Reign'), Pentecostes.",
            referencias: "Gálatas 6:14; Salmo 72:1-20; Salmo 98:1-9; Romanos 5:8; Filipenses 2:5-11"
        },
        {
            termo: "09. Hinos de Charles Wesley (1707-1788) - Amor e Expiação",
            definicao: "Charles Wesley, irmão de John Wesley, escreveu mais de 6.500 hinos, muitos dos quais centrados em Cristo. (1) 'E quão sublime amor' (And Can It Be That I Should Gain? 1738). Texto (excerto): 'E quão sublime amor, Senhor, para comigo? O teu amor por mim morreu na cruz! É tão grande amor, tão insondável amor! Amor, amor por mim morreu na cruz!' Análise: Maravilha da expiação, o amor de Cristo que morreu por nós. (2) 'Cristo, o Senhor, ressurgiu hoje' (Christ the Lord Is Risen Today, 1739). Texto: 'Cristo, o Senhor, ressurgiu hoje, aleluia! Filhos dos homens, alegrai-vos, aleluia! Ele morreu, mas ressurgiu, aleluia! E para sempre ele vive, aleluia!' Análise: Hino pascal, celebração da ressurreição. (3) 'Ó amor que não me deixará' (Love Divine, All Loves Excelling, 1747). Texto (excerto): 'Ó amor que não me deixará, descansa em ti, Senhor; tu és a minha porção eterna, a minha glória e o meu Senhor. Termina, Senhor, a minha luta, concede-me o teu perdão; sê minha âncora, minha força, meu eterno galardão.' Análise: O amor de Deus em Cristo, a união com Cristo, a santificação. (4) 'Hark! The Herald Angels Sing' (1739) - hino natalino. (5) 'O For a Thousand Tongues to Sing' (1739) - louvor a Cristo. Uso litúrgico: Natal ('Hark! The Herald'), Páscoa ('Christ the Lord'), Cultos de adoração ('Love Divine'), Evangelismo ('And Can It Be').",
            referencias: "Gálatas 2:20; Romanos 5:5; 1 Coríntios 15:3-4; Romanos 8:35-39"
        },
        {
            termo: "10. Hinos de John Newton e William Cowper (1725-1807; 1731-1800)",
            definicao: "Newton e Cowper produziram hinos centrados na graça de Cristo. (1) 'Amazing Grace' (Graça Maravilhosa), de John Newton (1779). Texto: 'Graça maravilhosa, quão doce o som, que salvou um pecador como eu! Eu estava perdido, mas agora fui achado; cego, mas agora vejo. A graça me ensinou a temer, e a graça me livrou do temor; quão preciosa foi a graça na hora em que eu pela primeira vez creu! Através de muitos perigos, trabalhos e ciladas, já tenho chegado; a graça me trouxe até aqui, e a graça me levará para o lar.' Análise: A graça de Deus em Cristo, a salvação pela fé, a perseverança. (2) 'Os olhos do cego verão' (There Is a Fountain Filled with Blood), de William Cowper (1772). Texto (excerto): 'Há uma fonte cheia de sangue, jorrando da veia de Emanuel; pecadores imersos nesse sangue perdem as suas manchas de pecado. O ladrão moribundo alegrou-se em ver aquela fonte em seu último momento; e eu, embora vil como ele, também lavo minhas vestes neste sangue.' Análise: O sangue de Cristo como fonte de purificação. (3) 'Glorious Things of Thee Are Spoken', de Newton (1779) - sobre a igreja, o corpo de Cristo. (4) 'How Sweet the Name of Jesus Sounds', de Newton (1779) - sobre o nome de Jesus. Uso litúrgico: Cultos de evangelismo, ceia do Senhor ('There Is a Fountain'), testemunho pessoal ('Amazing Grace').",
            referencias: "1 Timóteo 1:15; Efésios 2:8-9; 1 João 1:7; Atos 4:12"
        },
        {
            termo: "11. Hinos de Fanny Crosby (1820-1915) - Jesus, o Amigo e Salvador",
            definicao: "Fanny Crosby, a 'rainha dos hinos gospel', escreveu mais de 8.000 hinos, muitos centrados em Jesus. (1) 'Blessed Assurance' (Bendita Certeza, 1873). Texto: 'Bendita certeza, Jesus é meu! Que herança gloriosa, promessa de Deus! Meu corpo e minha alma, meu ser e meu louvor, em êxtase de glória, pertencem ao Senhor. Esta é minha história, este é meu cântico: louvar ao meu Salvador, cantar sem cessar. Esta é minha história, este é meu cântico: louvar ao meu Salvador, cantar sem cessar.' Análise: A segurança da salvação em Cristo. (2) 'Draw Me Nearer' (1853) - um hino sobre a união com Cristo. (3) 'To God Be the Glory' (1875) - doxologia cristocêntrica. (4) 'Pass Me Not, O Gentle Savior' (1868) - súplica pela misericórdia de Cristo. (5) 'Rescue the Perishing' (1869) - hino missionário sobre o amor de Cristo pelos perdidos. (6) 'I Am Thine, O Lord' (1875) - consagração a Cristo. Análise de 'To God Be the Glory': 'A Deus seja a glória, pois fez grandes coisas; o mundo inteiro louve ao Senhor! Ele nos deu o seu Filho, a vitória ganhou; a Deus seja a glória, pois fez grandes coisas!' Uso litúrgico: Evangelismo ('Rescue the Perishing'), Adoração ('Blessed Assurance', 'To God Be the Glory'), Louvor pessoal ('I Am Thine, O Lord').",
            referencias: "Romanos 8:16; 1 Coríntios 6:20; Gálatas 6:14; Colossenses 3:16-17"
        },
        {
            termo: "12. Hinos Contemporâneos (séc. XX-XXI) - Louvor e Adoração",
            definicao: "O movimento de louvor e adoração contemporâneo produziu hinos cristocêntricos amplamente usados. (1) 'Shout to the Lord' (Darlene Zschech, 1993). Texto: 'Meu Jesus, meu Salvador, não há outro igual a ti; grande é o Senhor, digno de louvor; não há outro igual a ti. Diante de ti os céus se prostram, toda a terra canta hosanas ao Rei. Aleluia, aleluia, o Cordeiro venceu!' Análise: A centralidade de Jesus, sua exclusividade, sua vitória. (2) 'Reckless Love' (Cory Asbury, 2017). Texto (excerto): 'Ó amor insensato, que não desiste de mim; vai aonde eu for, me persegue até o fim; não há sombra que o esconda, não há altura que o impeça, não há fosso profundo onde este amor não me alcance. Eu me rendo, me rendo ao amor insensato de Deus.' Análise: O amor perseverante de Deus em Cristo. (3) 'Way Maker' (Sinach, 2015). Texto: 'Tu és o Deus que abre caminho, opera milagres; cumpre promessas, a luz nas trevas; meu Deus, és quem és! Meu Jesus, és quem és!' Análise: Jesus como o que abre caminho e opera milagres. (4) '10,000 Reasons (Bless the Lord)' (Matt Redman, 2011). (5) 'What a Beautiful Name' (Brooke Ligertwood/Ben Fielding, 2016). Uso litúrgico: Cultos contemporâneos, jovens, celebrações.",
            referencias: "Salmo 103:1-5; Salmo 150:1-6; Filipenses 2:9-11; Apocalipse 5:12-13"
        },
        {
            termo: "13. Síntese: O Hino como Confissão de Fé Cristocêntrica",
            definicao: "Os hinos cristocêntricos são 'teologia cantada' - expressões da fé da igreja na pessoa e obra de Jesus Cristo. Através dos hinos, a igreja confessa: (1) A divindade de Cristo - 'Tu és o Rei da glória, ó Cristo' (Te Deum). (2) A encarnação - 'O Verbo se fez carne' (João 1:14). (3) A expiação vicária - 'Quando eu contemplo a cruz onde meu Senhor morreu' (Isaac Watts). (4) A ressurreição - 'Cristo, o Senhor, ressurgiu hoje' (Charles Wesley). (5) A ascensão - 'Tu estás à direita de Deus' (Te Deum). (6) A segunda vinda - 'Nós cremos que tu hás de vir como Juiz' (Te Deum). (7) O senhorio universal - 'Jesus reinará onde o sol passar' (Isaac Watts). (8) A graça de Cristo - 'Graça maravilhosa, quão doce o som' (John Newton). (9) O amor de Cristo - 'Amor insondável, amor tão sublime' (Charles Wesley). (10) A união com Cristo - 'Já não sou eu quem vive, mas Cristo vive em mim' (Gálatas 2:20). A teologia reformada exorta: 'Cantai ao Senhor um cântico novo, cantai ao Senhor, todas as terras. Cantai ao Senhor, bendizei o seu nome; anunciai a sua salvação dia após dia' (Salmo 96:1-2). Que os hinos cristocêntricos encham nossos cultos, lares e corações, para a glória de Cristo. Soli Deo Gloria!",
            referencias: "Salmo 96:1-2; Salmo 98:1-4; Efésios 5:19; Colossenses 3:16; Apocalipse 5:9-14"
        }
    ]
};