// volume/volume-81.js
window.LIVRO_DATA = {
    nome: "Volume LXXX",
    dados: [
        {
            termo: "01. Introdução: A Missão como Participação na Missão de Cristo",
            definicao: "A missão da igreja é participação na missão de Cristo (Missio Dei). 'Assim como o Pai me enviou, também eu vos envio a vós' (João 20:21). 'Portanto, ide, ensinai todas as nações, batizando-as em nome do Pai, e do Filho, e do Espírito Santo' (Mateus 28:19). A teologia reformada (Calvino, Kuyper, Bavinck) enfatiza que a missão não é uma atividade opcional da igreja, mas a sua razão de ser. Este volume explora: (1) Evangelismo (proclamação do evangelho). (2) Discipulado (formação de seguidores de Cristo). (3) Plantação de igrejas (estabelecimento de comunidades cristãs). (4) Estratégias e métodos missionários. (5) O papel do Espírito Santo na missão. (6) O sofrimento missionário. (7) A esperança escatológica como motivação. 'Como, pois, invocarão aquele em quem não creram? e como crerão naquele de quem não ouviram? e como ouvirão, se não há quem pregue?' (Romanos 10:14).",
            referencias: "Mateus 28:18-20; Marcos 16:15; Lucas 24:46-48; João 20:21; Atos 1:8; Romanos 10:13-15; 2 Coríndios 5:18-20; Apocalipse 7:9-10"
        },
        {
            termo: "02. Evangelismo - A Proclamação do Evangelho de Cristo",
            definicao: "Evangelismo é a proclamação das boas novas (evangelho) de Jesus Cristo. 'Porque não me envergonho do evangelho de Cristo, pois é o poder de Deus para salvação de todo aquele que crê' (Romanos 1:16). 'Ide por todo o mundo, pregai o evangelho a toda criatura' (Marcos 16:15). Métodos de evangelismo: (1) Testemunho pessoal: compartilhar sua história de conversão (João 4:39-42). (2) Pregação pública: proclamação em praças, igrejas, meios de comunicação (Atos 2:14-41). (3) Evangelismo de amizade: construir relacionamentos antes de compartilhar (1 Tessalonicenses 2:7-8). (4) Evangelismo de massa: cruzadas, eventos (Atos 8:5-13). (5) Evangelismo digital: internet, redes sociais, aplicativos. (6) Evangelismo literário: folhetos, livros, Bíblias. (7) Evangelismo através de ações sociais: amor em ação (Tiago 1:27). (8) Evangelismo pessoal: um-a-um (Filipe e o eunuco, Atos 8:26-40). Conteúdo do evangelho: (1) Deus é santo (Isaías 6:3). (2) O homem é pecador (Romanos 3:23). (3) Cristo morreu pelos pecados (Romanos 5:8). (4) Cristo ressuscitou (1 Coríndios 15:3-4). (5) Arrependimento e fé são necessários (Atos 20:21). (6) Batismo é o sinal da fé (Mateus 28:19). A teologia reformada (Calvino, Edwards) enfatiza que o evangelismo deve ser feito com amor, respeito e dependência do Espírito Santo. 'Mas, em vossos corações, santificai a Cristo como Senhor; e estai sempre preparados para responder com mansidão e temor a qualquer que vos pedir a razão da esperança que há em vós' (1 Pedro 3:15).",
            referencias: "Isaías 6:1-5; Romanos 3:23; Romanos 5:8; Romanos 10:14-15; 1 Coríndios 15:3-4; 2 Coríndios 5:18-21; 1 Pedro 3:15; 1 João 1:9"
        },
        {
            termo: "03. Discipulado - Fazer Discípulos de Cristo (Mateus 28:19-20)",
            definicao: "Discipulado é o processo de ensinar os novos convertidos a seguir a Cristo. 'Ide, ensinai todas as nações... ensinando-as a guardar todas as coisas que eu vos tenho mandado' (Mateus 28:19-20). 'Até que todos cheguemos à unidade da fé... à medida da estatura completa de Cristo' (Efésios 4:13). Elementos do discipulado: (1) Ensino da doutrina bíblica (2 Timóteo 3:16-17). (2) Oração (1 Tessalonicenses 5:17). (3) Leitura da Bíblia (Salmo 119:105). (4) Comunhão com a igreja (Hebreus 10:24-25). (5) Serviço (Gálatas 5:13). (6) Evangelismo (fazer novos discípulos). (7) Obediência a Cristo (João 14:15). Métodos de discipulado: (a) Discipulado pessoal (um-a-um) (Paulo e Timóteo, 2 Timóteo 2:2). (b) Pequenos grupos (Atos 2:46). (c) Escola Dominical (Neemias 8:1-8). (d) Estudos bíblicos (Atos 17:11). (e) Retiros e acampamentos. (f) Discipulado online (YouTube, podcasts). (g) Mentoreamento (Tito 2:3-5). O discipulado é um processo contínuo, não um evento único. A teologia reformada (Calvino, Owen) enfatiza que o discipulado visa a conformação a Cristo. 'E todos nós, com rosto descoberto, refletindo como um espelho a glória do Senhor, somos transformados de glória em glória na mesma imagem' (2 Coríndios 3:18).",
            referencias: "Mateus 28:19-20; Atos 2:42; Romanos 8:29; 2 Coríndios 3:18; Gálatas 4:19; Efésios 4:11-16; Colossenses 1:28-29; 2 Timóteo 2:2; 2 Timóteo 3:16-17; 1 Pedro 2:2"
        },
        {
            termo: "04. Plantação de Igrejas - Estabelecendo Corpos Locais de Cristo",
            definicao: "Plantação de igrejas é o estabelecimento de novas congregações onde não há igreja evangélica. Paulo plantou igrejas em suas viagens missionárias (Atos 13-28). 'E, havendo em todas as igrejas estabelecido presbíteros' (Atos 14:23). 'Assim que, apascentai a igreja de Deus' (Atos 20:28). Razões para plantar igrejas: (1) Obediência à Grande Comissão (Mateus 28:19). (2) Alcançar povos não alcançados. (3) Crescimento do Reino de Deus. (4) Discipulado de novos convertidos. (5) Comunhão e apoio mútuo. (6) Celebração dos sacramentos (batismo, ceia). (7) Ensinamento da Palavra. Métodos de plantação: (a) Igreja-mãe envia uma equipe (Atos 13:1-4). (b) Igreja em casa (Atos 2:46). (c) Igreja em bairros carentes. (d) Igreja para grupos específicos (universitários, imigrantes). (e) Igreja digital (desafios). (f) Plantação em parceria com outras igrejas. (g) Plantação através de missões transculturais. Desafios: (i) Falta de recursos financeiros. (ii) Oposição espiritual e cultural. (iii) Falta de lideres treinados. (iv) Perseguição. A teologia reformada (Kuyper, Bavinck) incentiva a plantação de igrejas como cumprimento da Grande Comissão. 'Porque, onde estiverem dois ou três reunidos em meu nome, aí estou eu no meio deles' (Mateus 18:20).",
            referencias: "Mateus 18:20; Atos 2:42-47; Atos 13:1-4; Atos 14:23; Atos 20:28; 1 Coríndios 3:6-9; Tito 1:5"
        },
        {
            termo: "05. O Missionário - Chamado, Capacitação e Envio",
            definicao: "O missionário é um enviado (apóstolos, do grego apostolos - 'enviado') de Cristo. 'Assim como o Pai me enviou, também eu vos envio a vós' (João 20:21). 'Paulo, apóstolo (não da parte dos homens, nem por homem algum, mas por Jesus Cristo)' (Gálatas 1:1). Características do missionário: (1) Chamado por Deus (Atos 13:2). (2) Enviado pela igreja (Atos 13:3). (3) Capacitado pelo Espírito Santo (Atos 1:8). (4) Fiel à Palavra (2 Timóteo 4:2). (5) Amoroso (1 Coríndios 13). (6) Humilde (Mateus 11:29). (7) Corajoso (Atos 4:29). (8) Perseverante (Atos 14:22). (9) Disposto a sofrer (2 Coríndios 11:23-28). (10) Orador (Atos 17:22-31). (11) Estudioso da cultura (1 Coríndios 9:19-23). (12) Discipulador (Mateus 28:19). (13) Plantador de igrejas (Atos 14:23). O processo de envio: (a) Chamado interior (pelo Espírito). (b) Confirmação da igreja (Atos 13:1-3). (c) Treinamento (seminário, escola de missões). (d) Apoio (oração, financeiro). (e) Envio (Atos 13:3). (f) Acompanhamento. A teologia reformada (Calvino, Kuyper) enfatiza que o chamado missionário é um chamado especial para alguns, mas toda a igreja é chamada a apoiar missões. 'Rogai, pois, ao Senhor da seara que mande ceifeiros para a sua seara' (Mateus 9:38).",
            referencias: "Isaías 6:8; Mateus 9:38; Atos 1:8; Atos 13:1-3; Romanos 10:14-15; 1 Coríndios 9:19-23; 2 Coríndios 5:18-20; Efésios 6:19-20; 2 Timóteo 4:2"
        },
        {
            termo: "06. Oração e Missões - O Poder da Intercessão",
            definicao: "A oração é essencial para as missões. Jesus orou pelos discípulos e por todos os crentes (João 17:1-26). A igreja primitiva orava pelos missionários (Atos 12:5; 13:3). 'E, servindo eles ao Senhor e jejuando, disse o Espírito Santo: Separai-me a Barnabé e a Saulo para a obra a que os tenho chamado. Então, jejuando e orando, e pondo sobre eles as mãos, os despediram' (Atos 13:2-3). Modos de oração missionária: (1) Oração pelos missionários (proteção, saúde, sabedoria, fruto). (2) Oração pelos povos não alcançados. (3) Oração pelos perseguidores (Mateus 5:44). (4) Oração pelo envio de obreiros (Mateus 9:38). (5) Oração pela salvação de almas. (6) Oração pela abertura de portas (Colossenses 4:3). (7) Oração pelo poder do Espírito (Atos 4:29-31). Recursos de oração missionária: (a) Listas de oração (missionários específicos). (b) Agendas de oração (países, povos). (c) Grupos de oração (células missionárias). (d) Vigílias de oração. (e) Jejum e oração. A teologia reformada (Calvino, Edwards) enfatiza que a oração é o 'motor' das missões. 'Orai sem cessar' (1 Tessalonicenses 5:17). 'Perseverai na oração, vigiando com ações de graças' (Colossenses 4:2).",
            referencias: "Mateus 5:44; Mateus 9:38; Atos 4:29-31; Atos 12:5; Atos 13:2-3; Romanos 10:1; Efésios 6:18-20; Colossenses 4:2-4; 1 Tessalonicenses 5:17"
        },
        {
            termo: "07. Apoio Missionário - Parceiros na Missão de Cristo",
            definicao: "O apoio missionário (financeiro, oração, logístico) é uma parceria na missão de Cristo. Paulo recebia apoio de igrejas (Filipenses 4:15-18). 'E também vos foi muito útil, não somente a mim, mas também a todos os crentes' (Filipenses 1:7). Formas de apoio missionário: (1) Oração (intercessão). (2) Financeiro (dízimos, ofertas missionárias). (3) Logístico (transporte, moradia). (4) Comunicação (e-mails, cartas, redes sociais). (5) Visitação (quando possível). (6) Apoio emocional (encorajamento). (7) Apoio familiar (cuidar dos filhos). (8) Envio de equipes de curto prazo. (9) Doação de Bíblias e literatura. (10) Apoio médico. (11) Apoio educacional (escolas missionárias). (12) Apoio tecnológico (computadores, internet). A teologia reformada (Calvino, Kuyper) afirma que o apoio missionário é uma forma de participar da Grande Comissão. 'E assim os que repartem e os que são repartidos, me alegro com todos vós' (Filipenses 2:17). 'Vós também, como pedras vivas, sois edificados casa espiritual' (1 Pedro 2:5). 'Tendo por certo isto mesmo: que aquele que em vós começou a boa obra a aperfeiçoará até ao dia de Jesus Cristo' (Filipenses 1:6).",
            referencias: "Mateus 10:40-42; Lucas 10:7; Atos 18:3; Romanos 15:24; Filipenses 1:3-5; Filipenses 4:15-18; 3 João 1:5-8"
        },
        {
            termo: "08. Missões Transculturas - Alcançando Povos Não Alcançados",
            definicao: "Missões transculturais é o envio de missionários para povos de cultura diferente, especialmente os não alcançados pelo evangelho. 'Ide, ensinai todas as nações' (Mateus 28:19). 'E ser-me-eis testemunhas tanto em Jerusalém como em toda a Judeia e Samaria, e até aos confins da terra' (Atos 1:8). Povos não alcançados: (1) Aqueles que não têm igreja indígena evangelizadora. (2) Aqueles que não têm Bíblia em sua língua. (3) Aqueles que nunca ouviram o evangelho. Estratégias: (a) Plantação de igrejas transculturais. (b) Tradução da Bíblia (Wycliffe). (c) Missões médicas. (d) Educação (escolas, seminários). (e) Desenvolvimento comunitário (agricultura, água potável). (f) Rádio e TV. (g) Evangelismo digital. (h) Treinamento de líderes nacionais. (i) Missões de curto prazo. (j) Missões de ajuda humanitária. Desafios: (i) Barreira linguística. (ii) Barreira cultural. (iii) Perseguição. (iv) Doenças. (v) Solidão. (vi) Falta de recursos. (vii) Resistência local. (viii) Sincretismo. A teologia reformada (Kuyper, Bavinck) incentiva as missões transculturais como prioridade. 'Como, pois, invocarão aquele em quem não creram? e como crerão naquele de quem não ouviram? e como ouvirão, se não há quem pregue?' (Romanos 10:14).",
            referencias: "Isaías 6:8; Mateus 28:19; Atos 1:8; Romanos 10:13-15; 1 Coríndios 9:19-23; Apocalipse 5:9; Apocalipse 7:9"
        },
        {
            termo: "09. Sofrimento Missionário - Participação nas Aflições de Cristo",
            definicao: "As missões frequentemente envolvem sofrimento, perseguição e martírio. Paulo sofreu muito em suas viagens missionárias (2 Coríndios 11:23-28). 'Porque vos foi concedido, em relação a Cristo, não somente crer nele, como também padecer por ele' (Filipenses 1:29). 'E, se somos filhos, somos também herdeiros... se com ele padecemos, para que também com ele sejamos glorificados' (Romanos 8:17). Exemplos de sofrimento missionário: (1) Estêvão (martírio, Atos 7). (2) Tiago (martírio, Atos 12:2). (3) Paulo (prisões, naufrágios, açoites). (4) Pedro (crucificado de cabeça para baixo). (5) Missionários contemporâneos perseguidos (países fechados). (6) Martírio de missionários (Jim Elliot, Nate Saint, etc.). O sofrimento missionário é participação nas aflições de Cristo. 'Alegro-me nas minhas aflições por vós' (Colossenses 1:24). 'Mas, se padece por amor da justiça, bem-aventurado sois vós' (1 Pedro 3:14). 'Bem-aventurados os que são perseguidos por causa da justiça, porque deles é o reino dos céus' (Mateus 5:10). A teologia reformada (Calvino, Bonhoeffer) enfatiza que o sofrimento missionário é uma honra. 'E, tendo orado, moveu-se o lugar em que estavam reunidos; e todos foram cheios do Espírito Santo, e anunciavam com ousadia a palavra de Deus' (Atos 4:31).",
            referencias: "Mateus 5:10-12; Atos 5:41; Atos 7:54-60; Atos 12:2; Romanos 8:17-18; Filipenses 1:29; Colossenses 1:24; 2 Timóteo 3:12; 1 Pedro 4:12-16"
        },
        {
            termo: "10. Estratégias Missionárias - Métodos e Abordagens",
            definicao: "Diferentes estratégias missionárias têm sido usadas ao longo da história da igreja. Estratégias tradicionais: (1) Missões de plantação de igrejas (Paulo, Atos 13-28). (2) Missões médicas (hospitais, clínicas). (3) Missões educacionais (escolas, seminários). (4) Missões literárias (Bíblias, literatura cristã). (5) Missões de rádio e TV (transmissões). (6) Missões de ajuda humanitária (alimentos, água, abrigo). (7) Missões de desenvolvimento (agricultura, microcrédito). (8) Missões urbanas (cidades). (9) Missões entre povos não alcançados. Estratégias contemporâneas: (10) Missões digitais (internet, redes sociais, aplicativos). (11) Missões de negócios (empresas com propósito missionário). (12) Missões de esportes (eventos esportivos). (13) Missões de artes (música, teatro, cinema). (14) Missões de curto prazo (equipes de 1 semana a 2 anos). (15) Missões de estudo (intercâmbio cristão). (16) Missões de refugiados (acolhimento de imigrantes). (17) Missões de oração (grupos de intercessão). (18) Missões de pesquisa (mapeamento de povos). A teologia reformada (Calvino, Kuyper) incentiva a criatividade e adaptação de métodos, desde que o evangelho não seja comprometido. 'Fiz-me tudo para todos, para por todos os meios chegar a salvar alguns' (1 Coríndios 9:22).",
            referencias: "Atos 13-28; 1 Coríndios 9:19-23; 2 Coríndios 4:2; Efésios 6:19-20; Colossenses 4:3-4; 2 Timóteo 2:2; 2 Timóteo 4:2"
        },
        {
            termo: "11. Discipulado de Novos Convertidos - Fundamentos da Fé",
            definicao: "O discipulado de novos convertidos deve incluir os fundamentos da fé cristã. Conteúdo essencial do discipulado: (1) A Bíblia (inspiração, autoridade, interpretação) (2 Timóteo 3:16-17). (2) Deus (Trindade, atributos) (Mateus 28:19). (3) Jesus Cristo (divindade, humanidade, morte, ressurreição) (João 1:1-14; 1 Coríndios 15:3-4). (4) Espírito Santo (pessoa, obra, dons) (João 14:16-17; Atos 1:8). (5) Salvação (pecado, graça, fé, arrependimento) (Efésios 2:8-9). (6) Igreja (corpo de Cristo, membros, ordenanças) (Efésios 1:22-23; 4:11-16). (7) Oração (Pai Nosso, intercessão) (Mateus 6:9-13). (8) Santificação (vida santa, fruto do Espírito) (Gálatas 5:22-23). (9) Evangelismo (testemunho pessoal) (Mateus 28:19-20). (10) Escatologia (volta de Cristo, juízo, vida eterna) (Tito 2:13). Métodos de discipulado: (a) Discipulado pessoal. (b) Pequenos grupos. (c) Escola Dominical. (d) Catecismo. (e) Estudos bíblicos. (f) Mentoria. A teologia reformada (Calvino, Westminster) enfatiza o ensino sistemático da doutrina. 'Até que todos cheguemos à unidade da fé e ao conhecimento do Filho de Deus' (Efésios 4:13).",
            referencias: "Mateus 28:19-20; João 17:3; Atos 2:42; Romanos 6:1-14; Efésios 2:8-9; Efésios 4:11-16; Colossenses 2:6-7; 1 Pedro 2:2; 2 Pedro 3:18"
        },
        {
            termo: "12. Escatologia e Missões - O Cumprimento da Grande Comissão",
            definicao: "As missões são movidas pela esperança escatológica: a volta de Cristo e a salvação de todas as nações. 'E este evangelho do reino será pregado em todo o mundo, em testemunho a todas as nações, e então virá o fim' (Mateus 24:14). 'Depois destas coisas olhei, e eis aqui uma multidão... de todas as nações... que estavam diante do trono' (Apocalipse 7:9-10). Relação entre missões e escatologia: (1) A missão apressa a volta de Cristo (2 Pedro 3:12). (2) A missão é necessária porque ainda há povos não alcançados. (3) A missão é garantida de sucesso porque Cristo voltará. (4) A missão é movida pela esperança da nova criação. (5) O martírio missionário será recompensado (Apocalipse 6:9-11). A teologia reformada (John Piper) afirma: 'Missões existem porque a adoração não existe'. O objetivo final das missões é a glória de Cristo entre todas as nações. 'Porque dele e por ele, e para ele, são todas as coisas' (Romanos 11:36). 'Aguardando a bem-aventurada esperança e o aparecimento da glória do grande Deus e nosso Salvador Jesus Cristo' (Tito 2:13).",
            referencias: "Mateus 24:14; Romanos 11:36; 2 Pedro 3:10-13; Apocalipse 5:9-10; Apocalipse 7:9-10; Apocalipse 22:20-21"
        },
        {
            termo: "13. Síntese: Cristo, a Missão de Deus",
            definicao: "Cristo é o centro da Missio Dei (missão de Deus). 'Porque dele e por ele, e para ele, são todas as coisas' (Romanos 11:36). Resumo da missiologia cristocêntrica: (1) Evangelismo é proclamação de Cristo (Marcos 16:15). (2) Discipulado é formação de seguidores de Cristo (Mateus 28:19). (3) Plantação de igrejas é estabelecimento de corpos locais de Cristo (Atos 14:23). (4) O missionário é enviado por Cristo (João 20:21). (5) A oração sustenta as missões (Mateus 9:38). (6) O apoio missionário é parceria (Filipenses 4:15-18). (7) Missões transculturais alcançam povos não alcançados (Mateus 28:19). (8) O sofrimento missionário é participação nas aflições de Cristo (Filipenses 1:29). (9) Discipulado de novos convertidos fundamenta a fé (Efésios 4:13). (10) A escatologia motiva as missões (Mateus 24:14). (11) O objetivo final é a glória de Cristo entre todas as nações (Apocalipse 7:9-10). 'Portanto, ide... e eis que estou convosco todos os dias' (Mateus 28:19-20). 'Aquele que testifica estas coisas diz: Certamente cedo venho. Amém. Ora vem, Senhor Jesus. A graça de nosso Senhor Jesus Cristo seja com todos vós. Amém' (Apocalipse 22:20-21). Soli Deo Gloria!",
            referencias: "Romanos 11:36; Mateus 28:18-20; João 20:21; Atos 1:8; Apocalipse 7:9-10; Apocalipse 22:20-21"
        }
    ]
};