// volume/volume-92.js
window.LIVRO_DATA = {
    nome: "Volume XCII",
    dados: [
        {
            termo: "01. Introdução: A Esperança Cristã Centrada em Cristo",
            definicao: "A esperança cristã não é um otimismo ingênuo, mas uma certeza fundamentada na ressurreição de Cristo e na promessa de sua volta. 'Bendito o Deus... que, segundo a sua grande misericórdia, nos gerou de novo para uma viva esperança, pela ressurreição de Jesus Cristo dentre os mortos' (1 Pedro 1:3). 'Aguardando a bem-aventurada esperança e o aparecimento da glória do grande Deus e nosso Salvador Jesus Cristo' (Tito 2:13). A teologia reformada (Calvino, Bavinck) enfatiza que a esperança é uma âncora da alma (Hebreus 6:19). Este volume explora: (1) A esperança no Antigo Testamento. (2) A esperança na ressurreição de Cristo. (3) A esperança na segunda vinda. (4) A esperança na nova criação. (5) A esperança como virtude. (6) Esperança e sofrimento. (7) Esperança e missão. 'Porque pela esperança somos salvos' (Romanos 8:24).",
            referencias: "Romanos 8:24-25; 1 Coríndios 15:19; 2 Coríndios 4:17-18; Efésios 1:18; Colossenses 1:5; 1 Tessalonicenses 1:3; Tito 1:2; Tito 2:13; 1 Pedro 1:3-4; 1 João 3:2-3"
        },
        {
            termo: "02. A Esperança no Antigo Testamento - A Promessa do Messias",
            definicao: "O Antigo Testamento contém a esperança na vinda do Messias. 'E porei inimizade entre ti e a mulher, e entre a tua semente e a sua semente; esta te ferirá a cabeça, e tu lhe ferirás o calcanhar' (Gênesis 3:15). 'Eis que dias vêm, diz o Senhor, em que levantarei a Davi um Renovo justo' (Jeremias 23:5). 'Mas, para vós, os que temeis o meu nome, nascerá o sol da justiça' (Malaquias 4:2). A esperança do AT incluía: (1) A vinda de um profeta como Moisés (Deuteronômio 18:15-19). (2) O reinado eterno do Filho de Davi (2 Samuel 7:12-16). (3) O Servo Sofredor (Isaías 53). (4) A nova aliança (Jeremias 31:31-34). (5) A ressurreição dos mortos (Daniel 12:2). (6) O novo céu e nova terra (Isaías 65:17-25). (7) A vinda do Filho do Homem (Daniel 7:13-14). (8) O julgamento final (Daniel 12:2). (9) A salvação das nações (Isaías 49:6). (10) A habitação de Deus com seu povo (Ezequiel 37:27). A teologia reformada (Calvino, Bavinck) vê no AT a preparação para a esperança em Cristo. 'Estas coisas lhes aconteceram como figuras' (1 Coríndios 10:11).",
            referencias: "Gênesis 3:15; Gênesis 22:18; 2 Samuel 7:12-16; Jó 19:25-27; Salmo 16:9-11; Salmo 42:5; Isaías 9:6-7; Isaías 53; Daniel 12:2; Oséias 6:2; Zacarias 9:9; Malaquias 4:2"
        },
        {
            termo: "03. A Esperança na Ressurreição de Cristo - A Garantia",
            definicao: "A ressurreição de Cristo é a garantia da nossa esperança. 'Bendito o Deus... que nos gerou de novo para uma viva esperança, pela ressurreição de Jesus Cristo dentre os mortos' (1 Pedro 1:3). 'Cristo ressuscitou dos mortos, e foi feito as primícias dos que dormem' (1 Coríndios 15:20). Significados: (1) A ressurreição confirma a divindade de Cristo (Romanos 1:4). (2) Garante a nossa justificação (Romanos 4:25). (3) Garante a nossa ressurreição (1 Coríndios 15:20-23). (4) Garante a vitória sobre a morte (1 Coríndios 15:54-57). (5) Garante a nova criação (2 Pedro 3:13). (6) Garante a volta de Cristo (Atos 1:11). (7) Garante o juízo final (Atos 17:31). (8) Garante a vida eterna (João 11:25-26). (9) Garante a esperança (1 Pedro 1:3). (10) Garante a glória (Romanos 8:30). A teologia reformada (Calvino, Owen) vê na ressurreição de Cristo o fundamento de toda esperança. 'Se Cristo não ressuscitou, é vã a nossa fé' (1 Coríndios 15:14).",
            referencias: "João 11:25-26; Atos 2:24-32; Atos 17:31; Romanos 1:4; Romanos 4:25; 1 Coríndios 15:1-58; Filipenses 3:20-21; 1 Tessalonicenses 4:13-18; 1 Pedro 1:3"
        },
        {
            termo: "04. A Esperança na Segunda Vinda de Cristo (Parusia)",
            definicao: "A segunda vinda de Cristo (parusia) é a consumação da nossa esperança. 'Este Jesus... há de vir assim como para o céu o vistes ir' (Atos 1:11). 'Porque o Senhor mesmo descerá do céu com alarido, e com voz de arcanjo, e com a trombeta de Deus' (1 Tessalonicenses 4:16). 'Eis que vem com as nuvens, e todo olho o verá' (Apocalipse 1:7). Características da parusia: (1) Pessoal: o próprio Jesus virá (Atos 1:11). (2) Visível: 'todo olho o verá' (Apocalipse 1:7). (3) Gloriosa: 'com poder e grande glória' (Mateus 24:30). (4) Audível: 'com alarido... com voz de arcanjo' (1 Tessalonicenses 4:16). (5) Súbita: 'como um ladrão de noite' (1 Tessalonicenses 5:2). (6) Inesperada: 'daquele dia e hora ninguém sabe' (Mateus 24:36). (7) Para juízo: 'a fim de julgar os vivos e os mortos' (2 Timóteo 4:1). (8) Para consumação: 'novos céus e nova terra' (2 Pedro 3:13). A esperança na parusia transforma a vida presente: (a) Santificação (1 João 3:3). (b) Perseverança (Hebreus 10:23). (c) Consolação (1 Tessalonicenses 4:18). (d) Missão (Mateus 24:14). (e) Vigilância (Mateus 24:42). (f) Paciência (Tiago 5:7-8). (g) Oração (Apocalipse 22:20). (h) Alegria (1 Pedro 1:6-8). (i) Coragem (João 16:33). (j) Fidelidade (Apocalipse 2:10). A teologia reformada (Calvino, Berkhof) vê na parusia a esperança consumada. 'Aguardando a bem-aventurada esperança e o aparecimento da glória do grande Deus e nosso Salvador Jesus Cristo' (Tito 2:13).",
            referencias: "Daniel 7:13-14; Zacarias 14:1-5; Mateus 24-25; Atos 1:11; 1 Coríndios 15:23-24; Filipenses 3:20-21; 1 Tessalonicenses 4:13-18; 2 Tessalonicenses 1:7-10; Tito 2:13; 2 Pedro 3:10-13; Apocalipse 1:7; Apocalipse 22:20"
        },
        {
            termo: "05. A Esperança na Nova Criação - Novos Céus e Nova Terra",
            definicao: "A esperança final é a nova criação. 'E vi um novo céu e uma nova terra. Porque já o primeiro céu e a primeira terra passaram' (Apocalipse 21:1). 'Mas, segundo a sua promessa, nós aguardamos novos céus e nova terra, em que habita a justiça' (2 Pedro 3:13). 'Porque a ardente expectação da criatura espera a manifestação dos filhos de Deus' (Romanos 8:19). Características da nova criação: (1) Nova: não apenas reformada, mas nova criação (Apocalipse 21:1). (2) Habitação de Deus com seu povo (Apocalipse 21:3). (3) Ausência de sofrimento: 'não haverá mais morte, nem pranto, nem clamor, nem dor' (Apocalipse 21:4). (4) Ausência de pecado: 'não entrará nela coisa alguma que contamine' (Apocalipse 21:27). (5) Ausência de maldição: 'ali não haverá mais maldição' (Apocalipse 22:3). (6) Presença do Cordeiro: 'o Cordeiro é a sua lâmpada' (Apocalipse 21:23). (7) Árvore da vida (Apocalipse 22:2). (8) Rio da água da vida (Apocalipse 22:1). (9) Luz eterna: 'não necessitarão de luz de lâmpada nem de luz do sol' (Apocalipse 21:23). (10) Serviço a Deus: 'os seus servos o servirão' (Apocalipse 22:3). A esperança na nova criação transforma a vida presente: (a) Cuidado com a criação (mordomia). (b) Santidade (2 Pedro 3:11). (c) Paciência no sofrimento (2 Coríndios 4:17-18). (d) Alegria (Romanos 8:18). (e) Missão (Mateus 28:19). (f) Oração (Apocalipse 22:20). A teologia reformada (Calvino, Bavinck) vê na nova criação a consumação da redenção. 'E aquele que estava assentado sobre o trono disse: Eis que faço novas todas as coisas' (Apocalipse 21:5).",
            referencias: "Isaías 65:17-25; Isaías 66:22; Romanos 8:19-23; 2 Pedro 3:10-13; Apocalipse 21:1-27; Apocalipse 22:1-5"
        },
        {
            termo: "06. A Esperança como Virtude - Fé, Esperança e Amor",
            definicao: "A esperança é uma das três virtudes teologais, junto com a fé e o amor. 'Agora, pois, permanecem a fé, a esperança e o amor, estes três; mas o maior destes é o amor' (1 Coríndios 13:13). 'Tendo ouvido a vossa fé em Cristo Jesus e o vosso amor para com todos os santos, por causa da esperança que vos está reservada nos céus' (Colossenses 1:4-5). Características da esperança: (1) É certa (fundamentada na promessa de Deus). (2) É futura (aguarda a consumação). (3) É pessoal (relacionada a Cristo). (4) É comunitária (compartilhada com a igreja). (5) É ativa (motiva a santidade e a missão). (6) É paciente (aguarda o tempo de Deus). (7) É alegre (Romanos 12:12). (8) É perseverante (Hebreus 6:11-12). (9) É firme (âncora da alma). (10) É purificadora (1 João 3:3). A esperança se diferencia do otimismo: (a) Otimismo é baseado em circunstâncias; esperança é baseada em Deus. (b) Otimismo é incerto; esperança é certa. (c) Otimismo é humano; esperança é divina. (d) Otimismo é terreno; esperança é celestial. (e) Otimismo é temporário; esperança é eterna. A teologia reformada (Calvino, Edwards) enfatiza a esperança como fruto do Espírito. 'Ora, o Deus de esperança vos encha de todo o gozo e paz em crença, para que abundeis em esperança pelo poder do Espírito Santo' (Romanos 15:13).",
            referencias: "Romanos 5:2-5; Romanos 8:24-25; Romanos 12:12; Romanos 15:13; 1 Coríndios 13:13; Gálatas 5:5; Efésios 1:18; Colossenses 1:4-5; 1 Tessalonicenses 1:3; 1 Tessalonicenses 5:8; Tito 1:2; Tito 2:13; Hebreus 6:11-12; 1 Pedro 1:3; 1 João 3:2-3"
        },
        {
            termo: "07. Esperança e Sofrimento - Consolação nas Tribulações",
            definicao: "A esperança cristã consola os crentes no sofrimento. 'Porque a nossa leve e momentânea tribulação produz para nós um peso eterno de glória mui excelente' (2 Coríndios 4:17). 'Não quero, porém, irmãos, que ignoreis acerca dos que já dormem, para que não vos entristeçais, como os demais que não têm esperança' (1 Tessalonicenses 4:13). Como a esperança consola: (1) O sofrimento é temporário (Romanos 8:18). (2) O sofrimento produz glória (2 Coríndios 4:17). (3) O sofrimento é disciplinado por Deus (Hebreus 12:5-11). (4) O sofrimento nos aproxima de Cristo (Filipenses 3:10). (5) O sofrimento testifica nossa fé (1 Pedro 1:6-7). (6) O sofrimento nos ensina a confiar em Deus (2 Coríndios 1:8-10). (7) O sofrimento nos prepara para o céu (Romanos 5:3-5). (8) O sofrimento une-nos a Cristo (Romanos 8:17). (9) O sofrimento é vencido pela ressurreição (1 Coríndios 15:54-57). (10) O sofrimento terminará na nova criação (Apocalipse 21:4). A teologia reformada (Calvino, Bonhoeffer) vê no sofrimento uma escola de esperança. 'E sabemos que todas as coisas contribuem juntamente para o bem daqueles que amam a Deus' (Romanos 8:28).",
            referencias: "Romanos 5:3-5; Romanos 8:18; 2 Coríndios 1:3-7; 2 Coríndios 4:16-18; Filipenses 1:29; Colossenses 1:24; 1 Tessalonicenses 4:13-14; 2 Tessalonicenses 1:4-5; 1 Pedro 1:6-7; 1 Pedro 4:12-13"
        },
        {
            termo: "08. Esperança e Santidade - Purificando-se como Cristo",
            definicao: "A esperança da volta de Cristo motiva a santidade. 'E todo aquele que nele tem esta esperança purifica-se a si mesmo, como também ele é puro' (1 João 3:3). 'Portanto, rogo-vos, irmãos, pela compaixão de Deus, que apresenteis os vossos corpos em sacrifício vivo, santo e agradável a Deus' (Romanos 12:1). Como a esperança produz santidade: (1) A esperança nos lembra que veremos a Deus (Mateus 5:8). (2) A esperança nos lembra que seremos semelhantes a Cristo (1 João 3:2). (3) A esperança nos lembra que prestaremos contas (2 Coríndios 5:10). (4) A esperança nos lembra que o tempo é curto (Efésios 5:15-16). (5) A esperança nos lembra que o mundo passa (1 João 2:17). (6) A esperança nos motiva a abandonar o pecado (Romanos 6:11-14). (7) A esperança nos motiva a buscar a pureza (Filipenses 4:8). (8) A esperança nos motiva a perdoar (Efésios 4:32). (9) A esperança nos motiva a servir (Gálatas 5:13). (10) A esperança nos motiva a evangelizar (Mateus 28:19). A teologia reformada (Calvino, Owen) enfatiza que a esperança é um incentivo à santificação. 'Segui a paz com todos, e a santificação, sem a qual ninguém verá o Senhor' (Hebreus 12:14).",
            referencias: "Romanos 6:22; Romanos 12:1-2; 2 Coríndios 7:1; Efésios 4:22-24; Filipenses 1:10-11; Colossenses 1:22-23; 1 Tessalonicenses 3:13; 1 Tessalonicenses 5:23; 1 Pedro 1:13-16; 2 Pedro 3:11-14; 1 João 3:2-3"
        },
        {
            termo: "09. Esperança e Missão - Pregando a Esperança ao Mundo",
            definicao: "A esperança cristã é uma mensagem para o mundo. 'Antes, santificai ao Senhor Deus em vossos corações; e estai sempre preparados para responder com mansidão e temor a qualquer que vos pedir a razão da esperança que há em vós' (1 Pedro 3:15). 'Portanto, ide, ensinai todas as nações' (Mateus 28:19). Como compartilhar a esperança: (1) Com mansidão (1 Pedro 3:15). (2) Com temor (respeito). (3) Com amor (João 13:34-35). (4) Com clareza (Colossenses 4:4). (5) Com paciência (2 Timóteo 4:2). (6) Com oração (Colossenses 4:3). (7) Com testemunho (Atos 1:8). (8) Com alegria (Filipenses 4:4). (9) Com esperança (1 Pedro 3:15). (10) Com urgência (Romanos 13:11-12). A esperança na volta de Cristo motiva a missão: (a) A certeza da volta de Cristo nos urge a evangelizar (Mateus 24:14). (b) A esperança da nova criação nos motiva a cuidar da criação. (c) A esperança do juízo nos motiva a pregar o arrependimento (Atos 17:30-31). (d) A esperança da ressurreição nos motiva a pregar a vida eterna (João 3:16). (e) A esperança da glória nos motiva a suportar o sofrimento (2 Coríndios 4:17-18). (f) A esperança da volta de Cristo nos motiva a orar 'Maranata' (Apocalipse 22:20). A teologia reformada (Kuyper, Bavinck) vê na esperança o combustível da missão. 'Como, pois, invocarão aquele em quem não creram? e como crerão naquele de quem não ouviram? e como ouvirão, se não há quem pregue?' (Romanos 10:14).",
            referencias: "Isaías 49:6; Mateus 9:37-38; Mateus 24:14; Mateus 28:19-20; Atos 1:8; Romanos 10:13-15; 2 Coríndios 5:18-20; Efésios 6:19-20; Colossenses 4:3-6; 1 Pedro 3:15"
        },
        {
            termo: "10. Esperança e Perseverança - Aguardando com Paciência",
            definicao: "A esperança nos ensina a perseverar. 'E será que aquele que perseverar até ao fim será salvo' (Mateus 10:22). 'Tendo por certo isto mesmo: que aquele que em vós começou a boa obra a aperfeiçoará até ao dia de Jesus Cristo' (Filipenses 1:6). Como a esperança nos ajuda a perseverar: (1) A esperança nos lembra que o sofrimento é temporário (Romanos 8:18). (2) A esperança nos lembra que a recompensa é certa (Hebreus 11:6). (3) A esperança nos lembra que Deus é fiel (1 Coríndios 10:13). (4) A esperança nos lembra que Cristo voltará (Apocalipse 22:20). (5) A esperança nos lembra que não estamos sozinhos (Hebreus 13:5). (6) A esperança nos lembra que outros perseveraram (Hebreus 12:1). (7) A esperança nos lembra que Jesus perseverou (Hebreus 12:2-3). (8) A esperança nos dá força (Isaías 40:31). (9) A esperança nos dá alegria (Romanos 12:12). (10) A esperança nos dá paz (João 14:27). Exemplos de perseverança: (a) Jó (Tiago 5:11). (b) Abraão (Hebreus 6:15). (c) Moisés (Hebreus 11:27). (d) Paulo (2 Timóteo 4:7-8). (e) Jesus (Hebreus 12:2). A teologia reformada (Calvino, Edwards) vê na perseverança a marca da verdadeira fé. 'Perseverai na oração' (Colossenses 4:2).",
            referencias: "Mateus 10:22; João 8:31; Romanos 2:7; Romanos 12:12; Gálatas 6:9; Filipenses 1:6; Filipenses 3:12-14; Colossenses 1:11-12; 1 Tessalonicenses 5:14; 2 Tessalonicenses 3:13; Hebreus 6:11-12; Hebreus 10:36-39; Tiago 1:12; 2 Pedro 3:9; Apocalipse 2:10"
        },
        {
            termo: "11. A Oração da Esperança - Maranata (1 Coríndios 16:22; Apocalipse 22:20)",
            definicao: "'Maranata' (aramaico: Marana tha - 'Nosso Senhor, vem!') é a oração da igreja pela volta de Cristo. 'Se alguém não ama o Senhor Jesus Cristo, seja anátema. Maranata' (1 Coríndios 16:22). 'Aquele que testifica estas coisas diz: Certamente cedo venho. Amém. Ora vem, Senhor Jesus' (Apocalipse 22:20). Significados: (1) Confissão do senhorio de Cristo ('Nosso Senhor'). (2) Súplica pela volta de Cristo ('vem'). (3) Esperança na parusia (segunda vinda). (4) Oração pela justiça final. (5) Pedido por redenção completa. (6) Anseio pela nova criação. (7) Expressão de amor a Cristo. (8) Antecipação do encontro com Cristo. (9) Perseverança na esperança. (10) Unidade da igreja. A oração 'Maranata' deve caracterizar a igreja: (a) Deve ser feita com fé (Hebreus 11:6). (b) Deve ser feita com amor (1 Coríndios 16:22). (c) Deve ser feita com perseverança (Lucas 18:1-8). (d) Deve ser feita com pureza (1 João 3:3). (e) Deve ser feita com urgência (Romanos 13:11-12). (f) Deve ser feita com alegria (Filipenses 4:4). (g) Deve ser feita com expectativa (Tito 2:13). (h) Deve ser feita com santidade (1 Pedro 1:15-16). (i) Deve ser feita com missão (Mateus 28:19). (j) Deve ser feita com adoração (Apocalipse 22:20-21). A teologia reformada (Calvino, Bavinck) vê em 'Maranata' a oração central da igreja. 'Aquele que testifica estas coisas diz: Certamente cedo venho. Amém. Ora vem, Senhor Jesus. A graça de nosso Senhor Jesus Cristo seja com todos vós. Amém' (Apocalipse 22:20-21).",
            referencias: "1 Coríndios 16:22; Filipenses 3:20-21; Colossenses 3:4; 1 Tessalonicenses 4:17; Tito 2:13; Hebreus 9:28; 2 Pedro 3:12; Apocalipse 1:7; Apocalipse 22:20-21"
        },
        {
            termo: "12. A Esperança e o Juízo - A Consumação da Justiça",
            definicao: "A esperança cristã inclui o juízo final, onde Deus fará justiça. 'E estes irão para o tormento eterno, mas os justos para a vida eterna' (Mateus 25:46). 'Porque todos devemos comparecer ante o tribunal de Cristo' (2 Coríndios 5:10). O juízo não é temido pelo crente, pois Cristo é seu advogado (1 João 2:1). 'Portanto, agora nenhuma condenação há para os que estão em Cristo Jesus' (Romanos 8:1). A esperança no juízo: (1) Consola os oprimidos (Apocalipse 6:9-11). (2) Alerta os ímpios (2 Tessalonicenses 1:5-10). (3) Motiva a santidade (2 Pedro 3:11-14). (4) Recompensa os fiéis (Mateus 25:21,23). (5) Conforta os enlutados (1 Tessalonicenses 4:13-18). (6) Glorifica a Deus (Romanos 11:33-36). (7) Estabelece a justiça (Apocalipse 20:11-15). (8) Separa o bem do mal (Mateus 25:31-46). (9) Encerra a história (1 Coríndios 15:24-28). (10) Inaugura a nova criação (Apocalipse 21-22). A teologia reformada (Calvino, Berkhof) vê no juízo a consumação da justiça divina. 'E, como aos homens está ordenado morrerem uma vez, vindo depois o juízo, assim também Cristo, oferecendo-se uma vez para tirar os pecados de muitos, aparecerá segunda vez, sem pecado, aos que o esperam para salvação' (Hebreus 9:27-28).",
            referencias: "João 5:22-29; Atos 10:42; Atos 17:31; Romanos 2:5-11; 2 Coríndios 5:10; 2 Tessalonicenses 1:5-10; 2 Timóteo 4:1; Hebreus 9:27-28; 1 Pedro 4:5; 2 Pedro 2:9; 2 Pedro 3:7; Judas 1:14-15; Apocalipse 20:11-15"
        },
        {
            termo: "13. Síntese: Aguardando a Bem-Aventurada Esperança",
            definicao: "A esperança cristã é a âncora da alma, firme e segura (Hebreus 6:19). 'Aguardando a bem-aventurada esperança e o aparecimento da glória do grande Deus e nosso Salvador Jesus Cristo' (Tito 2:13). Resumo da teologia da esperança: (1) A esperança é fundamentada na ressurreição de Cristo (1 Pedro 1:3). (2) O Antigo Testamento aguardava o Messias (Gênesis 3:15). (3) A ressurreição de Cristo é a garantia da nossa esperança (1 Coríndios 15:20). (4) A segunda vinda é a consumação da esperança (Atos 1:11). (5) A nova criação é o destino da esperança (Apocalipse 21-22). (6) A esperança é uma virtude teologal (1 Coríndios 13:13). (7) A esperança consola no sofrimento (2 Coríndios 4:17-18). (8) A esperança motiva a santidade (1 João 3:3). (9) A esperança impulsiona a missão (Mateus 28:19). (10) A esperança ensina a perseverar (Filipenses 1:6). (11) A esperança ora 'Maranata' (Apocalipse 22:20). (12) A esperança aguarda o juízo final (Mateus 25:46). (13) Toda esperança é para a glória de Cristo (Romanos 11:36). 'Porque pela esperança somos salvos. Ora, a esperança que se vê não é esperança; porque o que alguém vê, como o espera? Mas, se esperamos o que não vemos, com paciência o esperamos' (Romanos 8:24-25). 'Aquele que testifica estas coisas diz: Certamente cedo venho. Amém. Ora vem, Senhor Jesus. A graça de nosso Senhor Jesus Cristo seja com todos vós. Amém' (Apocalipse 22:20-21). Soli Deo Gloria!",
            referencias: "Romanos 8:24-25; Romanos 11:36; 1 Coríndios 15:19-20; Gálatas 5:5; Efésios 1:18; Colossenses 1:5; 1 Tessalonicenses 1:3; 1 Tessalonicenses 5:8; Tito 2:13; Tito 3:7; Hebreus 6:19-20; 1 Pedro 1:3-4; 1 João 3:2-3; Apocalipse 22:20-21"
        }
    ]
};