// volume/volume-10.js
window.LIVRO_DATA = {
    nome: "Volume X",
    dados: [
        {
            termo: "01. Credo dos Apóstolos (Symbolum Apostolorum)",
            definicao: "O Credo dos Apóstolos é a mais antiga e difundida confissão de fé da igreja cristã ocidental. Embora não tenha sido escrito diretamente pelos apóstolos (tradição lendária), sua substância remonta ao século II. Forma final (século VI-VIII). Texto: 'Creio em Deus Pai Todo-poderoso, Criador do céu e da terra. E em Jesus Cristo, seu único Filho, nosso Senhor; o qual foi concebido pelo Espírito Santo; nasceu da virgem Maria; padeceu sob o poder de Pôncio Pilatos; foi crucificado, morto e sepultado; desceu ao inferno; ao terceiro dia ressurgiu dos mortos; subiu ao céu; está assentado à direita de Deus Pai Todo-poderoso; donde há de vir a julgar os vivos e os mortos. Creio no Espírito Santo; na santa igreja católica (universal); na comunhão dos santos; na remissão dos pecados; na ressurreição do corpo; na vida eterna. Amém.' Uso: utilizado em batismos, catequeses e liturgias. A teologia reformada aceita o Credo dos Apóstolos como uma exposição fiel da doutrina bíblica, incluindo sua cristologia (concebido pelo Espírito Santo, nascido da virgem Maria, crucificado, ressurreto, ascendido, juiz).",
            referencias: "Mateus 16:16; Mateus 28:19; João 20:28; Atos 8:37; Romanos 10:9-10; 1 Coríntios 15:3-4; 1 Pedro 3:18-22"
        },
        {
            termo: "02. Credo Niceno-Constantinopolitano (325/381 d.C.)",
            definicao: "O Credo Niceno-Constantinopolitano é o credo ecumênico por excelência, adotado pelo Concílio de Nicéia (325 d.C.) e expandido pelo Concílio de Constantinopla (381 d.C.). Texto: 'Creio em um só Deus, Pai Todo-poderoso, Criador do céu e da terra, de todas as coisas visíveis e invisíveis. E em um só Senhor Jesus Cristo, o Filho de Deus, unigênito, gerado do Pai antes de todos os séculos; Deus de Deus, luz de luz, Deus verdadeiro de Deus verdadeiro; gerado, não criado; consubstancial ao Pai; por quem todas as coisas foram feitas; que por nós homens e por nossa salvação desceu dos céus, e se encarnou pelo Espírito Santo no seio da virgem Maria, e se fez homem; foi crucificado por nós sob Pôncio Pilatos, padeceu e foi sepultado; e ao terceiro dia ressurgiu segundo as Escrituras; e subiu aos céus, e está assentado à direita do Pai; e de novo há de vir com glória para julgar os vivos e os mortos; o seu reino não terá fim. E no Espírito Santo, Senhor que dá vida, que procede do Pai (e do Filho - Filioque); que com o Pai e o Filho é adorado e glorificado; que falou pelos profetas. E na igreja una, santa, católica e apostólica. Confesso um só batismo para a remissão dos pecados. Aguardo a ressurreição dos mortos e a vida do século que há de vir. Amém.' A teologia reformada aceita o Credo Niceno-Constantinopolitano como padrão de ortodoxia trinitária e cristológica.",
            referencias: "João 1:1-14; João 10:30; João 14:16-17; Atos 2:33; Romanos 1:3-4; Filipenses 2:5-11; Colossenses 1:15-20; 1 Timóteo 3:16; Tito 2:13; Hebreus 1:1-4"
        },
        {
            termo: "03. Credo Atanasiano (Símbolo Quicumque)",
            definicao: "O Credo Atanasiano (Símbolo Quicumque) é um credo cristológico e trinitário, tradicionalmente atribuído a Atanásio de Alexandria (c. 296-373 d.C.), mas provavelmente originado na Gália (século V-VI). Seu nome vem da primeira palavra em latim: 'Quicumque vult salvus esse' ('Todo aquele que quer ser salvo'). Texto (parte cristológica): 'A fé verdadeira é que cremos e confessamos que nosso Senhor Jesus Cristo, o Filho de Deus, é Deus e homem; é Deus da substância do Pai, gerado antes dos séculos; e é homem da substância da mãe, nascido no mundo; perfeitamente Deus e perfeitamente homem, consistindo de alma racional e carne humana; igual ao Pai quanto à divindade, menor que o Pai quanto à humanidade; o qual, embora seja Deus e homem, não são dois, mas um só Cristo; um, não pela conversão da divindade em carne, mas pela assunção da humanidade em Deus; completamente um, não pela confusão da substância, mas pela unidade da pessoa. Porque assim como a alma racional e a carne são um só homem, assim Deus e homem são um só Cristo.' A teologia reformada aceita o Credo Atanasiano como uma exposição clássica da cristologia calcedoniana.",
            referencias: "João 1:1-14; João 1:18; João 10:30; João 14:28; Filipenses 2:5-11; Colossenses 2:9; 1 Timóteo 2:5; Tito 2:13; Hebreus 1:1-4; Hebreus 2:14-18"
        },
        {
            termo: "04. Definição de Calcedônia (451 d.C.)",
            definicao: "A Definição de Calcedônia (Símbolo de Calcedônia) é o documento mais importante da cristologia antiga, promulgado pelo Quarto Concílio Ecumênico (Calcedônia, 451 d.C.). Texto: 'Seguindo, pois, os santos padres, unanimemente ensinamos que devemos confessar um só e mesmo Filho, nosso Senhor Jesus Cristo, perfeito em divindade e perfeito em humanidade, verdadeiramente Deus e verdadeiramente homem, de alma racional e corpo; consubstancial (homoousios) ao Pai segundo a divindade, e consubstancial a nós segundo a humanidade, em tudo semelhante a nós, exceto no pecado; gerado do Pai antes dos séculos segundo a divindade, e nestes últimos dias, por nós e por nossa salvação, nascido de Maria, a virgem e Mãe de Deus (Theotokos), segundo a humanidade. (Confessamos) um só e mesmo Cristo, Senhor, Filho unigênito, em duas naturezas (en dyo physesin), sem confusão (asygchytōs), sem mudança (atreptōs), sem divisão (adiairetōs), sem separação (achōristōs). A diferença das naturezas não é de modo algum removida pela união; ao contrário, a propriedade de cada natureza é preservada e concorre para uma só pessoa (prosopon) e uma só hipóstase (hypostasis), não sendo Cristo partido ou dividido em duas pessoas, mas sendo um só e mesmo Filho, Unigênito, Deus Verbo, Senhor Jesus Cristo.' A teologia reformada aceita Calcedônia como a 'parede de pedra da ortodoxia'.",
            referencias: "João 1:14; Romanos 1:3-4; Filipenses 2:5-11; Colossenses 1:15-20; Colossenses 2:9; 1 Timóteo 3:16; Tito 2:13; Hebreus 1:1-4; 1 Pedro 3:18; 1 João 4:2-3"
        },
        {
            termo: "05. Símbolo de Leão Magno (Tomus ad Flavianum, 449 d.C.)",
            definicao: "O Tomus ad Flavianum ('Tombo a Flaviano') é uma carta dogmática do papa Leão Magno (c. 400-461 d.C.) ao patriarca Flaviano de Constantinopla, que se tornou a base da Definição de Calcedônia (451 d.C.). O documento refuta o eutiquianismo (confusão das naturezas) e afirma que em Cristo há duas naturezas (divina e humana), cada uma conservando suas propriedades. Texto (excerto): 'Sem diminuir, pois, a propriedade de cada uma das naturezas, que se unem em uma só pessoa, a majestade assume a humildade, a fortaleza a fraqueza, a eternidade a mortalidade. Para pagar a dívida de nossa condição, a natureza impassível se uniu à natureza passível, e para satisfazer nossa cura, o verdadeiro Deus e o verdadeiro homem se fundiram em um só Senhor.' A teologia reformada valoriza o Tomus de Leão como uma exposição clara da cristologia calcedoniana.",
            referencias: "João 1:14; Romanos 1:3-4; Filipenses 2:5-11; Colossenses 2:9; 1 Timóteo 3:16; Hebreus 2:14-18; 1 Pedro 3:18"
        },
        {
            termo: "06. Concílio de Nicéia (325 d.C.) - Credo Original e Anatematismos",
            definicao: "O Primeiro Concílio Ecumênico (Nicéia, 325 d.C.) foi convocado pelo imperador Constantino para resolver a controvérsia ariana. O Credo Niceno original (325 d.C.) e os anatematismos contra Ário são documentos fundamentais. Credo Niceno (325): 'Cremos em um só Deus, Pai Todo-poderoso, Criador de todas as coisas visíveis e invisíveis. E em um só Senhor Jesus Cristo, o Filho de Deus, gerado do Pai, o Unigênito, isto é, da substância do Pai; Deus de Deus, luz de luz, Deus verdadeiro de Deus verdadeiro; gerado, não criado; consubstancial (homoousios) ao Pai; por quem todas as coisas foram feitas...' Anatematismos: 'Aos que dizem: 'Houve tempo em que ele não existia', e 'antes de ser gerado não existia', e 'ele foi criado do nada', ou 'ele é de outra substância ou essência', ou 'o Filho de Deus é criado, mutável ou variável', estes a igreja católica e apostólica anatematiza.' A teologia reformada aceita Nicéia como a definição da divindade de Cristo.",
            referencias: "João 1:1-14; João 1:18; João 10:30; João 14:9; Filipenses 2:5-6; Colossenses 1:15-17; Colossenses 2:9; Hebreus 1:1-4"
        },
        {
            termo: "07. Concílio de Constantinopla I (381 d.C.) - Credo Expandido",
            definicao: "O Primeiro Concílio de Constantinopla (381 d.C.) confirmou o Credo Niceno, expandiu a seção sobre o Espírito Santo, e condenou o apolinarianismo. O Credo Niceno-Constantinopolitano resultante é o usado hoje nas liturgias. Texto (parte cristológica): 'Creio... em um só Senhor Jesus Cristo, o Filho de Deus, unigênito, gerado do Pai antes de todos os séculos; Deus de Deus, luz de luz, Deus verdadeiro de Deus verdadeiro; gerado, não criado; consubstancial ao Pai; por quem todas as coisas foram feitas; que por nós homens e por nossa salvação desceu dos céus, e se encarnou pelo Espírito Santo no seio da virgem Maria, e se fez homem; foi crucificado por nós sob Pôncio Pilatos, padeceu e foi sepultado; e ao terceiro dia ressurgiu segundo as Escrituras; e subiu aos céus, e está assentado à direita do Pai; e de novo há de vir com glória para julgar os vivos e os mortos; o seu reino não terá fim.' A teologia reformada aceita este credo como a norma da ortodoxia trinitária.",
            referencias: "João 1:1-14; Atos 2:33; Romanos 1:3-4; 1 Coríntios 15:3-8; Filipenses 2:5-11; Colossenses 1:15-20"
        },
        {
            termo: "08. Concílio de Éfeso (431 d.C.) - Condenação de Nestório e Theotokos",
            definicao: "O Terceiro Concílio Ecumênico (Éfeso, 431 d.C.) condenou o nestorianismo e aprovou o título Theotokos ('Mãe de Deus') para Maria. Documentos principais: (a) 12 Anatematismos de Cirilo de Alexandria contra Nestório. (b) Definição conciliar: 'O Verbo, unindo a si mesmo a carne animada por alma racional, se fez homem... a santa virgem é Theotokos, porque o Verbo de Deus se encarnou e se fez homem, e desde sua concepção uniu a si mesmo o templo que dela recebeu.' A teologia reformada aceita a condenação do nestorianismo e o título Theotokos (como afirmação da encarnação, não como mariologia exagerada).",
            referencias: "Lucas 1:26-38; Lucas 1:43; João 1:14; Gálatas 4:4; 1 Timóteo 3:16; 1 João 4:2-3"
        },
        {
            termo: "09. Concílio de Calcedônia (451 d.C.) - Definição completa",
            definicao: "O Quarto Concílio Ecumênico (Calcedônia, 451 d.C.) produziu a definição cristológica mais importante da igreja antiga. Documentos: (a) Definição de Calcedônia (já transcrita no verbete 04). (b) Cânones disciplinares. (c) Aprovação do Tomus ad Flavianum de Leão Magno. O concílio também condenou o monofisismo (Eutiques) e o nestorianismo. A teologia reformada aceita Calcedônia como a norma da cristologia ortodoxa.",
            referencias: "João 1:14; Romanos 1:3-4; Filipenses 2:5-11; Colossenses 2:9; 1 Timóteo 3:16; Tito 2:13; Hebreus 1:1-4"
        },
        {
            termo: "10. Concílio de Constantinopla II (553 d.C.) - Condenação dos Três Capítulos",
            definicao: "O Quinto Concílio Ecumênico (Constantinopla II, 553 d.C.), convocado pelo imperador Justiniano I, condenou os 'Três Capítulos' (Tria Capitula): escritos de Teodoro de Mopsuéstia, Teodoreto de Ciro e Ibas de Edessa (considerados nestorianos). O concílio reafirmou Calcedônia e condenou o nestorianismo. A teologia reformada aceita Constantinopla II como concílio ecumênico, embora com menos ênfase que Nicéia e Calcedônia.",
            referencias: "João 1:14; Filipenses 2:5-11; Colossenses 2:9; 1 Timóteo 3:16; 1 João 4:2-3"
        },
        {
            termo: "11. Concílio de Constantinopla III (680-681 d.C.) - Contra o Monotelismo",
            definicao: "O Sexto Concílio Ecumênico (Constantinopla III, 680-681 d.C.) condenou o monotelismo (doutrina de que Cristo tem uma só vontade) e afirmou que Cristo tem duas vontades (divina e humana) e duas operações. Definição: 'Confessamos que nele [Cristo] há duas vontades naturais e duas operações naturais... a vontade humana segue a divina, não resistindo nem se opondo, mas submetendo-se.' O concílio também condenou o papa Honório I (625-638 d.C.), que havia aprovado o monotelismo. A teologia reformada aceita Constantinopla III como concílio ecumênico, afirmando a dupla vontade de Cristo.",
            referencias: "João 4:34; João 5:30; João 6:38; Mateus 26:39; Mateus 26:42; Lucas 22:42; Filipenses 2:8; Hebreus 5:8"
        },
        {
            termo: "12. Concílio de Nicéia II (787 d.C.) - Veneração de Ícones",
            definicao: "O Sétimo Concílio Ecumênico (Nicéia II, 787 d.C.) tratou da controvérsia iconoclasta, afirmando a veneração (proskynēsis) de ícones (imagens) de Cristo, da virgem Maria e dos santos, mas não a adoração (latreia), que é devida somente a Deus. O concílio baseou-se na doutrina da encarnação: se Deus se fez carne (João 1:14), ele pode ser representado em imagem. A teologia reformada rejeita Nicéia II, considerando a veneração de ícones como violação do segundo mandamento (Êxodo 20:4-6; Deuteronômio 5:8-10). Calvino e os reformados iconoclastas rejeitaram imagens de Cristo (embora Lutero fosse mais tolerante).",
            referencias: "Êxodo 20:4-6; Deuteronômio 5:8-10; João 1:14; Romanos 1:23; 1 João 5:21"
        },
        {
            termo: "13. Confissão de Augsburgo (1530 d.C.) - Artigos Cristológicos",
            definicao: "A Confissão de Augsburgo (Confessio Augustana, 1530 d.C.) é a principal confissão luterana, apresentada ao imperador Carlos V. Artigos cristológicos: Artigo III: 'Os nossos ensinam que o Verbo, isto é, o Filho de Deus, assumiu a natureza humana no ventre da bem-aventurada virgem Maria, de modo que há duas naturezas, divina e humana, inseparavelmente unidas em uma só pessoa, um só Cristo, verdadeiro Deus e verdadeiro homem, que nasceu, padeceu, foi crucificado, morto e sepultado, para nos reconciliar com o Pai, e que ressuscitou ao terceiro dia, subiu ao céu, está assentado à direita do Pai, para governar e julgar vivos e mortos.' A teologia reformada (calvinista) aprecia a Confissão de Augsburgo, mas discorda da eucaristia luterana (Artigo X).",
            referencias: "João 1:14; Romanos 1:3-4; Filipenses 2:5-11; Colossenses 2:9; 1 Timóteo 3:16; Tito 2:13"
        },
        {
            termo: "14. Catecismo de Heidelberg (1563 d.C.) - Perguntas Cristológicas",
            definicao: "O Catecismo de Heidelberg (Heidelberger Katechismus, 1563 d.C.) é a confissão reformada mais querida, usada por igrejas reformadas (presbiterianas, congregacionais, batistas reformadas). Perguntas cristológicas: Pergunta 17: 'Por que ele precisa ser verdadeiro Deus e verdadeiro homem?' Resposta: 'Para que, como verdadeiro Deus, seu sacrifício e obediência fossem de valor infinito, e como verdadeiro homem, pudesse sofrer e morrer por nós.' Pergunta 31: 'Por que ele é chamado Cristo, isto é, Ungido?' Resposta: 'Porque ele foi ungido pelo Pai com o Espírito Santo para ser nosso sumo profeta, sacerdote e rei.' Pergunta 35: 'O que significa que ele foi concebido pelo Espírito Santo e nasceu da virgem Maria?' Resposta: 'Que ele é o verdadeiro Deus e verdadeiro homem.' A teologia reformada adota o Catecismo de Heidelberg como padrão doutrinário.",
            referencias: "Isaías 53:5-6; Mateus 1:18-25; Lucas 1:26-38; João 1:14; Romanos 3:23-26; 1 Coríntios 15:3; Gálatas 3:13; 1 Pedro 2:24; 1 João 2:2"
        },
        {
            termo: "15. Confissão de Fé de Westminster (1647 d.C.) - Capítulo VIII",
            definicao: "A Confissão de Fé de Westminster (Westminster Confession of Faith, 1647 d.C.) é o padrão doutrinário das igrejas presbiterianas e reformadas de língua inglesa. Capítulo VIII ('Do Mediador') é o resumo mais completo da cristologia reformada. Excertos: '§2. O Filho de Deus, sendo Deus de Deus, luz de luz, muito Deus de muito Deus, verdadeiro e eterno Deus, da mesma substância e igual com o Pai, assumiu a natureza humana... duas naturezas inteiras, perfeitas e distintas, inseparavelmente unidas em uma só pessoa, sem conversão, composição ou confusão.' '§3. O Senhor Jesus, em sua vida, suportou a ira de Deus e a morte amaldiçoada da cruz, para satisfazer a justiça de Deus, e para nos reconciliar com ele.' '§4. Ao Senhor Jesus foi dado o ofício de profeta, sacerdote e rei.' A teologia reformada adota Westminster como padrão confessional.",
            referencias: "João 1:1-14; Romanos 1:3-4; Romanos 3:23-26; Filipenses 2:5-11; Colossenses 1:13-20; Colossenses 2:9; 1 Timóteo 2:5; Tito 2:13-14; Hebreus 1:1-4; 1 Pedro 2:24"
        },
        {
            termo: "16. Cânones de Dort (1619 d.C.) - Expiação Limitada",
            definicao: "Os Cânones de Dort (Canons of Dort, 1619 d.C.) são a resposta reformada aos 'Cinco Artigos dos Remonstrantes' (arminianos). O Segundo Cabeça de Doutrina ('Da Morte de Cristo e da Redenção dos Homens por Ela') trata da expiação. Artigo 3: 'A morte do Filho de Deus é o único e mais perfeito sacrifício e satisfação pelos pecados; de valor infinito, abundantemente suficiente para expiar os pecados de todo o mundo. Mas, porque muitos a quem o evangelho é pregado não creem... isto procede de sua própria culpa. Mas todos os que verdadeiramente creem... alcançam a redenção.' Artigo 8: 'Porque foi da vontade de Deus que Cristo, pela sua morte na cruz, eficazmente redimisse... todos aqueles que o Pai lhe deu.' A teologia reformada (calvinista) aceita Dort como a exposição da expiação limitada (particularismo).",
            referencias: "João 10:11; João 10:15; João 17:9; Atos 20:28; Romanos 8:32-34; Efésios 5:25; Tito 2:14; 1 Pedro 3:18"
        },
        {
            termo: "17. Trinta e Nove Artigos da Igreja da Inglaterra (1571 d.C.)",
            definicao: "Os Trinta e Nove Artigos (Thirty-Nine Articles, 1571 d.C.) são a confissão da Igreja da Inglaterra (anglicana). Artigos cristológicos: Artigo II: 'O Verbo, o Filho de Deus, assumiu a natureza humana no ventre da bem-aventurada Virgem Maria... assim duas naturezas (divina e humana) estão unidas em uma só pessoa, nunca divididas, de modo que há um Cristo, verdadeiro Deus e verdadeiro homem.' Artigo XXVIII: 'A Ceia do Senhor... o corpo de Cristo é dado, tomado e comido na Ceia somente de maneira celestial e espiritual.' A teologia reformada aprecia os Artigos, especialmente a rejeição da transubstanciação (Artigo XXVIII).",
            referencias: "João 1:14; Romanos 1:3-4; Filipenses 2:5-11; Colossenses 2:9; 1 Timóteo 3:16; Tito 2:13"
        },
        {
            termo: "18. Fórmula de Concórdia (1577 d.C.) - Epítome e Declaração Sólida",
            definicao: "A Fórmula de Concórdia (Formula Concordiae, 1577 d.C.) é o documento confessional que unificou as igrejas luteranas. Os Artigos VII-VIII tratam da Ceia do Senhor e da pessoa de Cristo. Afirma a ubiquidade (onipresença) da humanidade de Cristo e a presença real na Ceia. 'A natureza humana de Cristo está onipresente, não localmente, mas sacramentalmente, por causa da união hipostática e da comunicação de atributos' (Epítome, Art.VII). A teologia reformada rejeita a Fórmula de Concórdia, mantendo a distinção calcedoniana (as naturezas não se confundem) e a localização celestial da humanidade de Cristo (Atos 3:21).",
            referencias: "Mateus 26:26-29; João 1:14; Atos 3:21; Filipenses 2:5-11; Colossenses 2:9; 1 Coríntios 11:23-26"
        },
        {
            termo: "19. Declaração de Lausanne (1974 d.C.) - Cristo e a Missão Integral",
            definicao: "O Pacto de Lausanne (Lausanne Covenant, 1974 d.C.) é um documento evangélico que afirma a missão integral da igreja: evangelismo (pregação do evangelho) e ação social (justiça, compaixão). Artigo 3 ('A Unicidade e Universalidade de Cristo'): 'Afirmamos que Jesus Cristo é o único Salvador e Senhor, o único mediador entre Deus e os homens, e que nenhum outro nome há debaixo do céu pelo qual devamos ser salvos. Cremos que o evangelho é o poder de Deus para a salvação de todo aquele que crê.' O documento rejeita o pluralismo religioso. A teologia reformada evangélica aceita a Declaração de Lausanne como uma expressão da missão cristã.",
            referencias: "João 14:6; Atos 4:12; Romanos 1:16; 1 Timóteo 2:5; Hebreus 7:25; 1 Pedro 3:15"
        },
        {
            termo: "20. Credo de Calcedônia em Grego e Latim (Texto Original)",
            definicao: "O texto original da Definição de Calcedônia em grego (língua do concílio) e latim (tradução oficial da igreja ocidental) é fornecido para referência acadêmica. Grego: 'Ἑπόμενοι τοίνυν τοῖς ἁγίοις πατράσιν ἕνα καὶ τὸν αὐτὸν ὁμολογεῖν Υἱὸν τὸν Κύριον ἡμῶν Ἰησοῦν Χριστὸν συμφώνως ἅπαντες ἐκδιδάσκομεν, τέλειον τὸν αὐτὸν ἐν θεότητι καὶ τέλειον τὸν αὐτὸν ἐν ἀνθρωπότητι, θεὸν ἀληθῶς καὶ ἄνθρωπον ἀληθῶς τὸν αὐτόν, ἐκ ψυχῆς λογικῆς καὶ σώματος, ὁμοούσιον τῷ Πατρὶ κατὰ τὴν θεότητα, καὶ ὁμοούσιον τὸν αὐτὸν ἡμῖν κατὰ τὴν ἀνθρωπότητα, κατὰ πάντα ὅμοιον ἡμῖν χωρὶς ἁμαρτίας... ἐν δύο φύσεσιν, ἀσυγχύτως, ἀτρέπτως, ἀδιαιρέτως, ἀχωρίστως γνωριζόμενον.' Latim: 'Seguentes igitur sanctos patres, unum eundemque confiteri Filium, Dominum nostrum Iesum Christum, consona omnes voce docemus, eundem perfectum in deitate, eundem perfectum in humanitate, Deum verum et hominem verum eundem, ex anima rationali et corpore, consubstantialem Patri secundum deitatem, consubstantialem nobis eundem secundum humanitatatem... in duabus naturis, inconfuse, immutabiliter, indivise, inseparabiliter agnoscendum.' A teologia reformada valoriza o texto original como base para a tradução e interpretação.",
            referencias: "João 1:14; Romanos 1:3-4; Filipenses 2:5-11; Colossenses 2:9; 1 Timóteo 3:16; Tito 2:13"
        },
        {
            termo: "21. Tabela Cronológica dos Concílios Ecumênicos",
            definicao: "Tabela dos concílios ecumênicos reconhecidos pela igreja antiga e pela teologia reformada (os primeiros quatro são ecumênicos; os três seguintes são aceitos pela teologia reformada; Nicéia II é rejeitado). (1) Nicéia I (325 d.C.): condenou o arianismo; afirmou o homoousios (Filho consubstancial ao Pai). (2) Constantinopla I (381 d.C.): afirmou a divindade do Espírito Santo; condenou o apolinarianismo; expandiu o Credo Niceno. (3) Éfeso (431 d.C.): condenou o nestorianismo; afirmou Theotokos. (4) Calcedônia (451 d.C.): definiu as duas naturezas de Cristo; condenou o monofisismo. (5) Constantinopla II (553 d.C.): condenou os 'Três Capítulos' (nestorianos). (6) Constantinopla III (680-681 d.C.): condenou o monotelismo; afirmou duas vontades em Cristo. (7) Nicéia II (787 d.C.): afirmou a veneração de ícones (rejeitado pela Reforma). A teologia reformada aceita os primeiros seis concílios (ou quatro, dependendo da tradição), mas rejeita Nicéia II.",
            referencias: "Atos 15:1-29; Efésios 4:4-6; 1 Timóteo 3:15; Judas 1:3"
        },
        {
            termo: "22. Tabela das Principais Heresias Cristológicas",
            definicao: "Tabela das principais heresias cristológicas condenadas pela igreja antiga e pela teologia reformada: (1) Ebionismo (século II): Jesus é apenas um homem, Filho adotivo (Adocionismo). (2) Docetismo (século II-III): Jesus apenas parecia humano (nega a encarnação real). (3) Arianismo (século IV): Jesus é uma criatura, não consubstancial ao Pai. (4) Apolinarianismo (século IV): Jesus não tem alma racional (Logos substitui a mente). (5) Nestorianismo (século V): separação das naturezas a ponto de duas pessoas. (6) Monofisismo/Eutiquianismo (século V): confusão das naturezas (uma só natureza). (7) Monotelismo (século VII): Cristo tem uma só vontade. (8) Adocionismo medieval (século VIII): Cristo, segundo sua humanidade, é Filho adotivo. A teologia reformada rejeita todas estas heresias como contrárias à Escritura e à definição calcedoniana.",
            referencias: "João 1:1-14; 1 Coríntios 15:3-8; Gálatas 1:6-9; Colossenses 2:8-10; 1 Timóteo 3:16; 1 João 4:2-3; 2 João 1:7"
        },
        {
            termo: "23. Glossário de Termos Gregos e Latinos",
            definicao: "Glossário dos principais termos cristológicos em grego e latim, com transliteração e definição. (1) Χριστός (Christos) - 'Cristo, o Ungido'. (2) Λόγος (Logos) - 'Verbo, Palavra'. (3) μονογενής (monogenēs) - 'unigênito'. (4) κένωσις (kenōsis) - 'esvaziamento' (Filipenses 2:7). (5) ὑπόστασις (hypostasis) - 'pessoa, subsistência'. (6) οὐσία (ousia) - 'substância, essência'. (7) φύσις (physis) - 'natureza'. (8) πρόσωπον (prosōpon) - 'pessoa, máscara'. (9) ὁμοούσιος (homoousios) - 'consubstancial, da mesma substância'. (10) θεοτόκος (Theotokos) - 'Mãe de Deus'. (11) ἐνυπόστατος (enhypostatos) - 'existindo na pessoa'. (12) ἀνυπόστατος (anhypostatos) - 'sem pessoa própria'. (13) μία φύσις (mia physis) - 'uma só natureza' (fórmula monofisita). (14) θέλημα (thelēma) - 'vontade'. (15) ἐνέργεια (energeia) - 'operação, energia'. Latim: (1) persona - 'pessoa'. (2) substantia - 'substância'. (3) natura - 'natureza'. (4) incarnatio - 'encarnação'. (5) satisfactio - 'satisfação'. (6) vicarius - 'substituto'. (7) communio idiomatum - 'comunicação de atributos'. (8) extra calvinisticum - 'extra calvinístico'. A teologia reformada utiliza esta terminologia em seus escritos técnicos.",
            referencias: "João 1:1-18; João 1:14; Filipenses 2:5-11; Colossenses 1:15-20; Colossenses 2:9; 1 Timóteo 3:16; Tito 2:13; Hebreus 1:1-4"
        },
        {
            termo: "24. Bibliografia Selecionada de Cristologia Reformada",
            definicao: "Bibliografia das principais obras de cristologia na tradição reformada e evangélica. (1) Obras clássicas: João Calvino, 'Institutas da Religião Cristã' (1536-1559, Livro II). Francisco Turretin, 'Institutas de Teologia Elênctica' (1679-1685, Locus XIII-XIV). Charles Hodge, 'Teologia Sistemática' (1872-1873, Volume II). Herman Bavinck, 'Teologia Reformada' (1895-1901, Volume III). Louis Berkhof, 'Teologia Sistemática' (1932, Parte III). (2) Obras contemporâneas: Karl Barth, 'Dogmática Eclesial' (KD IV, 1953-1967). Jürgen Moltmann, 'O Deus Crucificado' (1972). Wolfhart Pannenberg, 'Cristologia' (1964). N. T. Wright, 'A Ressurreição do Filho de Deus' (2003). John Stott, 'A Cruz de Cristo' (1986). J. I. Packer, 'O Conhecimento do Deus Santo' (1973). (3) Obras em português: Augustus Nicodemus, 'Cristologia: A Pessoa e a Obra de Jesus Cristo' (2020). Franklin Ferreira, 'Cristologia: Uma Introdução Bíblica, Histórica e Sistemática' (2015). A teologia reformada recomenda estas obras para estudo aprofundado.",
            referencias: "João 5:39; Lucas 24:27; Lucas 24:44-45; Atos 17:11; 2 Timóteo 2:15; 2 Timóteo 3:14-17"
        },
        {
            termo: "25. Índice Remissivo da Enciclopédia Cristológica (10 Volumes)",
            definicao: "Índice remissivo para os 10 volumes da Enciclopédia Cristológica, organizado por temas principais: (1) Antigo Testamento (Profecias, Tipos, Alianças). (2) Novo Testamento (Evangelhos, Paulo, Hebreus, Apocalipse). (3) Patrística (Pais, Concílios, Heresias). (4) Medieval (Anselmo, Tomás, Escoto). (5) Reforma (Lutero, Calvino, Zwinglio, Confissões). (6) Moderno (Iluminismo, Liberalismo, Barth). (7) Contemporâneo (Libertação, Negra, Feminista, Pluralista). (8) Termos Técnicos (A-Z, Volumes VIII-IX). (9) Documentos (Credos, Concílios, Confissões). O índice completo (cerca de 2.000 entradas) pode ser consultado na versão digital. A teologia reformada recomenda o uso do índice para navegação eficiente.",
            referencias: "Efésios 4:4-6; Colossenses 2:2-3; 2 Pedro 1:12-15; 2 Pedro 3:1-2"
        },
        {
            termo: "26. Conclusão e Exortação: Conhecendo a Cristo",
            definicao: "Esta Enciclopédia Cristológica (10 volumes) foi escrita para prover aos pastores, estudantes de teologia e leigos um recurso abrangente sobre a pessoa e obra de Jesus Cristo, dentro da perspectiva reformada confessional (Sola Scriptura, Solus Christus, Sola Fide, Sola Gratia, Soli Deo Gloria). O conhecimento sobre Cristo (notitia) deve levar à fé (fiducia) e à obediência (usus). Como escreveu o apóstolo Paulo: 'E conhecer a Cristo, e a virtude da sua ressurreição, e a comunicação de suas aflições, sendo feito conforme a sua morte' (Filipenses 3:10). Que esta obra seja usada para glória de Deus, edificação da igreja e expansão do evangelho. Soli Deo Gloria. 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36).",
            referencias: "João 17:3; Romanos 11:36; 1 Coríntios 2:2; Gálatas 2:20; Efésios 3:14-21; Filipenses 3:10; 2 Pedro 1:2-4; 2 Pedro 3:18"
        }
    ]
};