// volume/volume-34.js
window.LIVRO_DATA = {
    nome: "Volume XXXIV",
    dados: [
        {
            termo: "01. Introdução: A Profecia como Preparação para Cristo",
            definicao: "As profecias do Antigo Testamento são a preparação divina para a vinda do Messias, Jesus Cristo. O apóstolo Pedro escreveu: 'Desta salvação inquiriram e trataram diligentemente os profetas que profetizaram da graça que vos foi dada, indagando que tempo ou que ocasião de tempo o Espírito de Cristo, que estava neles, indicava, testificando antecipadamente os sofrimentos que a Cristo haviam de vir, e a glória que se lhes havia de seguir' (1 Pedro 1:10-11). As profecias messiânicas são numerosas (mais de 300 referências diretas no Antigo Testamento). Este volume explora as principais profecias do Antigo Testamento sobre o Messias e seu cumprimento em Jesus Cristo, organizadas por categoria: nascimento, ministério, sofrimento, morte, ressurreição, ascensão, reinado e segunda vinda. A teologia reformada vê no cumprimento das profecias a evidência da divindade de Cristo e da inspiração das Escrituras. 'Examinais as Escrituras, porque vós cuidais ter nelas a vida eterna, e são elas que de mim testificam' (João 5:39). 'E começando por Moisés e por todos os profetas, explicava-lhes o que dele se achava em todas as Escrituras' (Lucas 24:27).",
            referencias: "Lucas 24:27; Lucas 24:44-45; João 5:39; Atos 3:18; Atos 10:43; Atos 17:2-3; 1 Pedro 1:10-12; 2 Pedro 1:19-21"
        },
        {
            termo: "02. Profecias do Nascimento de Cristo",
            definicao: "As profecias sobre o nascimento do Messias são específicas e detalhadas: (1) Gênesis 3:15 - 'E porei inimizade entre ti e a mulher, e entre a tua semente e a sua semente; esta te ferirá a cabeça, e tu lhe ferirás o calcanhar.' - O proto-evangelho, primeira promessa de um Redentor. Cumprimento: Gálatas 4:4; Hebreus 2:14-15. (2) Gênesis 12:3 - 'Em ti serão benditas todas as famílias da terra.' - A semente de Abraão (Cristo) trará bênção a todas as nações. Cumprimento: Gálatas 3:16. (3) Gênesis 49:10 - 'O cetro não se arredará de Judá... até que venha Siló.' - O Messias viria da tribo de Judá. Cumprimento: Mateus 1:2; Lucas 3:33; Hebreus 7:14. (4) Números 24:17 - 'Uma estrela procederá de Jacó, e um cetro subirá de Israel.' - Profecia de Balaão sobre o Messias. Cumprimento: Mateus 2:2. (5) Isaías 7:14 - 'Eis que a virgem conceberá, e dará à luz um filho, e chamará o seu nome Emanuel.' - O nascimento virginal. Cumprimento: Mateus 1:22-23. (6) Isaías 9:6-7 - 'Porque um menino nos nasceu, um filho se nos deu... e será o seu nome: Maravilhoso, Conselheiro, Deus Forte, Pai da Eternidade, Príncipe da Paz.' - Títulos divinos aplicados ao Messias. Cumprimento: Lucas 2:11; Tito 2:13. (7) Miqueias 5:2 - 'E tu, Belém Efrata... de ti me sairá o que será Senhor em Israel, e cujas origens são desde os dias da eternidade.' - O Messias nasceria em Belém. Cumprimento: Mateus 2:1-6; Lucas 2:4-7. (8) Oséias 11:1 - 'Do Egito chamei o meu filho.' - A fuga para o Egito e o retorno. Cumprimento: Mateus 2:13-15. (9) Jeremias 31:15 - 'Ouviu-se uma voz em Ramá, lamentação e choro amargo; Raquel chora a seus filhos.' - A matança dos inocentes. Cumprimento: Mateus 2:17-18. A teologia reformada vê nestas profecias a fidelidade de Deus no cumprimento de suas promessas.",
            referencias: "Gênesis 3:15; Gênesis 12:3; Gênesis 49:10; Números 24:17; Isaías 7:14; Isaías 9:6-7; Jeremias 31:15; Oséias 11:1; Miqueias 5:2; Mateus 1:22-23; Mateus 2:1-6; Mateus 2:13-15; Mateus 2:17-18; Lucas 2:4-7; Lucas 2:11; Gálatas 3:16; Gálatas 4:4; Tito 2:13; Hebreus 2:14-15; Hebreus 7:14"
        },
        {
            termo: "03. Profecias da Genealogia e Linhagem do Messias",
            definicao: "As profecias sobre a genealogia do Messias estabelecem sua linhagem real e sua humanidade: (1) Gênesis 12:3; 22:18 - Descendente de Abraão. Cumprimento: Mateus 1:1; Gálatas 3:16. (2) Gênesis 49:10 - Descendente de Judá. Cumprimento: Mateus 1:2; Lucas 3:33. (3) Rute 4:18-22 - Descendente de Boaz e Rute (linhagem de Davi). Cumprimento: Mateus 1:5-6. (4) 2 Samuel 7:12-16 - Descendente de Davi, cujo trono seria eterno. Cumprimento: Mateus 1:1; Lucas 1:32-33; Atos 2:30-31. (5) Salmo 89:3-4,35-37 - A aliança com Davi confirmada. Cumprimento: Atos 13:22-23. (6) Isaías 11:1-2 - 'Porque brotará um rebento do tronco de Jessé.' - Descendente de Jessé (pai de Davi). Cumprimento: Mateus 1:6; Atos 13:22-23. (7) Jeremias 23:5-6; 33:14-16 - 'Levantarei a Davi um Renovo justo.' - Cumprimento: Lucas 1:32-33. A teologia reformada vê nestas profecias a garantia de que Jesus é o legítimo herdeiro do trono de Davi.",
            referencias: "Gênesis 12:3; Gênesis 22:18; Gênesis 49:10; Rute 4:18-22; 2 Samuel 7:12-16; Salmo 89:3-4; Isaías 11:1-2; Jeremias 23:5-6; Jeremias 33:14-16; Mateus 1:1-17; Lucas 1:32-33; Lucas 3:23-38; Atos 2:30-31; Atos 13:22-23; Gálatas 3:16"
        },
        {
            termo: "04. Profecias do Ministério e Precursor do Messias",
            definicao: "As profecias sobre o precursor e o ministério do Messias preparam o caminho para sua obra: (1) Isaías 40:3 - 'Voz do que clama no deserto: Preparai o caminho do Senhor.' - O precursor (João Batista). Cumprimento: Mateus 3:3; Marcos 1:3; Lucas 3:4-6; João 1:23. (2) Malaquias 3:1 - 'Eis que eu envio o meu anjo... e o Senhor, a quem vós buscais, virá de repente ao seu templo.' - Cumprimento: Mateus 11:10; Marcos 1:2; Lucas 1:76. (3) Malaquias 4:5-6 - 'Eis que eu vos enviarei o profeta Elias, antes que venha o grande e terrível dia do Senhor.' - João Batista veio no espírito de Elias. Cumprimento: Mateus 11:14; 17:10-13; Lucas 1:17. (4) Isaías 61:1-2 - 'O Espírito do Senhor Deus está sobre mim, porque o Senhor me ungiu para pregar boas novas aos pobres...' - A unção do Messias pelo Espírito. Cumprimento: Lucas 4:16-21; Atos 10:38. (5) Isaías 42:1-4 - 'Eis aqui o meu servo... porei sobre ele o meu Espírito.' - O Servo escolhido. Cumprimento: Mateus 12:18-21. (6) Isaías 11:1-2 - 'Repousará sobre ele o Espírito do Senhor.' - Os dons do Espírito sobre o Messias. Cumprimento: Mateus 3:16; João 1:32-33. (7) Isaías 35:5-6 - 'Então os olhos dos cegos serão abertos... o coxo saltará como cervo.' - Os milagres do Messias. Cumprimento: Mateus 11:2-6; João 9:1-12. (8) Isaías 9:1-2 - 'A terra de Zebulom e a terra de Naftali... o povo que andava em trevas viu uma grande luz.' - O ministério na Galileia. Cumprimento: Mateus 4:12-16. (9) Salmo 78:2 - 'Abrirei a minha boca numa parábola.' - Jesus falaria em parábolas. Cumprimento: Mateus 13:34-35. A teologia reformada vê nestas profecias a preparação divina para o ministério de Cristo.",
            referencias: "Isaías 9:1-2; Isaías 11:1-2; Isaías 35:5-6; Isaías 40:3; Isaías 42:1-4; Isaías 61:1-2; Salmo 78:2; Malaquias 3:1; Malaquias 4:5-6; Mateus 3:3; Mateus 3:16; Mateus 4:12-16; Mateus 11:2-6; Mateus 11:10; Mateus 11:14; Mateus 12:18-21; Mateus 13:34-35; Mateus 17:10-13; Marcos 1:2-3; Lucas 1:17; Lucas 1:76; Lucas 3:4-6; Lucas 4:16-21; João 1:23; João 1:32-33; Atos 10:38"
        },
        {
            termo: "05. Profecias da Entrada Triunfal e Rejeição do Messias",
            definicao: "As profecias sobre a entrada triunfal e a rejeição do Messias: (1) Zacarias 9:9 - 'Eis que o teu rei virá... justo e salvo, humilde, montado em um jumento.' - A entrada triunfal. Cumprimento: Mateus 21:1-11; Marcos 11:1-11; Lucas 19:28-44; João 12:12-19. (2) Salmo 118:26 - 'Bendito o que vem em nome do Senhor.' - A aclamação do povo. Cumprimento: Mateus 21:9. (3) Salmo 69:9 - 'O zelo da tua casa me devorou.' - A purificação do templo. Cumprimento: João 2:17. (4) Isaías 53:3 - 'Desprezado e o mais rejeitado entre os homens, homem de dores e que sabe o que é padecer.' - A rejeição do Messias. Cumprimento: João 1:11; João 5:43. (5) Salmo 118:22 - 'A pedra que os edificadores rejeitaram tornou-se a cabeça da esquina.' - A rejeição e exaltação. Cumprimento: Mateus 21:42; Atos 4:11; 1 Pedro 2:7. (6) Isaías 8:14 - 'Então ele será por santuário; mas por pedra de tropeço e por rocha de escândalo.' - O Messias como pedra de tropeço. Cumprimento: Romanos 9:33; 1 Pedro 2:8. A teologia reformada vê nestas profecias o contraste entre a rejeição de Cristo pelos homens e sua aceitação por Deus.",
            referencias: "Salmo 69:9; Salmo 118:22; Salmo 118:26; Isaías 8:14; Isaías 53:3; Zacarias 9:9; Mateus 21:1-11; Mateus 21:9; Mateus 21:42; Marcos 11:1-11; Lucas 19:28-44; João 1:11; João 2:17; João 5:43; João 12:12-19; Atos 4:11; Romanos 9:33; 1 Pedro 2:7-8"
        },
        {
            termo: "06. Profecias do Sofrimento e Agonia do Messias",
            definicao: "As profecias sobre o sofrimento e a agonia do Messias antes da crucificação: (1) Salmo 69:4 - 'Aqueles que me aborrecem sem causa são mais do que os cabelos da minha cabeça.' - Ódio sem causa. Cumprimento: João 15:24-25. (2) Salmo 69:20 - 'A vergonha quebrou o meu coração... esperei por quem tivesse compaixão, mas não houve; e por consoladores, mas não os achei.' - O abandono dos amigos. Cumprimento: Mateus 26:56; Marcos 14:50. (3) Salmo 35:11 - 'Falsas testemunhas se levantaram.' - Falsas acusações. Cumprimento: Mateus 26:59-61. (4) Isaías 50:6 - 'Ofereci as minhas costas aos que me feriam... não escondi o rosto da vergonha e da cuspida.' - O sofrimento físico e a vergonha. Cumprimento: Mateus 26:67; 27:26,30; Marcos 14:65. (5) Salmo 69:21 - 'Deram-me fel por mantimento, e na minha sede me deram vinagre.' - Na cruz. Cumprimento: Mateus 27:34,48; João 19:28-30. (6) Zacarias 12:10 - 'Olharão para mim, a quem traspassaram.' - A crucificação. Cumprimento: João 19:37. (7) Isaías 53:7 - 'Como cordeiro foi levado ao matadouro, e como ovelha muda perante os seus tosquiadores, ele não abriu a boca.' - Silêncio diante dos acusadores. Cumprimento: Mateus 27:12-14; Marcos 15:3-5. (8) Isaías 53:12 - 'E com os transgressores foi contado.' - Crucificado com ladrões. Cumprimento: Marcos 15:27-28; Lucas 23:33. A teologia reformada vê nestas profecias o sofrimento vicário de Cristo.",
            referencias: "Salmo 35:11; Salmo 69:4; Salmo 69:20-21; Isaías 50:6; Isaías 53:7; Isaías 53:12; Zacarias 12:10; Mateus 26:56-61; Mateus 26:67; Mateus 27:12-14; Mateus 27:26; Mateus 27:30; Mateus 27:34; Mateus 27:48; Marcos 14:50; Marcos 14:65; Marcos 15:3-5; Marcos 15:27-28; Lucas 23:33; João 15:24-25; João 19:28-30; João 19:37"
        },
        {
            termo: "07. Profecias da Crucificação e Morte do Messias",
            definicao: "As profecias mais detalhadas sobre a crucificação e morte do Messias estão no Salmo 22 e Isaías 53: (1) Salmo 22:1 - 'Deus meu, Deus meu, por que me desamparaste?' - As palavras de Jesus na cruz. Cumprimento: Mateus 27:46; Marcos 15:34. (2) Salmo 22:7-8 - 'Todos os que me veem zombam de mim... Confiou no Senhor, que o livre.' - As zombarias. Cumprimento: Mateus 27:39-43; Marcos 15:29-32. (3) Salmo 22:14-15 - 'Como água me derramei, e todos os meus ossos se desconjuntaram... a minha língua se apega ao meu paladar.' - O sofrimento físico da crucificação. Cumprimento: João 19:28. (4) Salmo 22:16 - 'Traspassaram as minhas mãos e os meus pés.' - A crucificação (mãos e pés traspassados). Cumprimento: Lucas 23:33; João 20:25-27. (5) Salmo 22:18 - 'Repartem entre si as minhas vestes, e sobre a minha túnica lançam sortes.' - As vestes de Jesus. Cumprimento: Mateus 27:35; João 19:23-24. (6) Êxodo 12:46 - 'Não lhe quebrareis osso nenhum.' - Nenhum osso quebrado. Cumprimento: João 19:33-36. (7) Salmo 34:20 - 'Ele guarda todos os seus ossos; nem um deles será quebrado.' - Cumprimento: João 19:36. (8) Zacarias 12:10 - 'Olharão para mim, a quem traspassaram.' - O lado traspassado. Cumprimento: João 19:34,37. (9) Isaías 53:9 - 'Com o rico na sua morte.' - Sepultado com os ricos. Cumprimento: Mateus 27:57-60. (10) Isaías 53:5 - 'Ele foi traspassado pelas nossas transgressões e moído pelas nossas iniquidades.' - A expiação vicária. Cumprimento: Romanos 4:25; 1 Pedro 2:24. (11) Isaías 53:10-12 - 'Foi cortado da terra dos viventes... levará sobre si o pecado de muitos.' - A morte expiatória. Cumprimento: 2 Coríntios 5:21. (12) Daniel 9:26 - 'O Messias será cortado, mas não para si mesmo.' - A morte do Messias. Cumprimento: Mateus 27:50. A teologia reformada vê nestas profecias a descrição mais precisa da crucificação, escrita séculos antes de Cristo.",
            referencias: "Êxodo 12:46; Salmo 22:1; Salmo 22:7-8; Salmo 22:14-18; Salmo 34:20; Isaías 53:5; Isaías 53:9-12; Daniel 9:26; Zacarias 12:10; Mateus 27:35; Mateus 27:39-43; Mateus 27:46; Mateus 27:50; Mateus 27:57-60; Marcos 15:29-34; Lucas 23:33; João 19:23-24; João 19:28; João 19:33-37; João 20:25-27; Romanos 4:25; 2 Coríntios 5:21; 1 Pedro 2:24"
        },
        {
            termo: "08. Profecias da Traição e Abandono do Messias",
            definicao: "As profecias sobre a traição e o abandono do Messias: (1) Salmo 41:9 - 'Até o meu amigo íntimo, em quem eu confiava, que comia do meu pão, levantou contra mim o calcanhar.' - A traição de um amigo (Judas). Cumprimento: Mateus 26:14-16; João 13:18. (2) Zacarias 11:12-13 - 'Pesaram o meu salário, trinta moedas de prata... e o atirei na casa do Senhor.' - As 30 moedas de prata. Cumprimento: Mateus 26:14-16; 27:3-10. (3) Zacarias 13:7 - 'Fere o pastor, e as ovelhas se dispersarão.' - O abandono dos discípulos. Cumprimento: Mateus 26:31; Marcos 14:27. (4) Salmo 69:20 - 'Esperei por quem tivesse compaixão, mas não houve; e por consoladores, mas não os achei.' - O abandono. Cumprimento: Mateus 26:56. (5) Salmo 69:4 - 'Os que me aborrecem sem causa são mais do que os cabelos da minha cabeça.' - Ódio sem causa. Cumprimento: João 15:25. A teologia reformada vê nestas profecias o cumprimento detalhado da traição de Judas.",
            referencias: "Salmo 41:9; Salmo 69:4; Salmo 69:20; Zacarias 11:12-13; Zacarias 13:7; Mateus 26:14-16; Mateus 26:31; Mateus 26:56; Mateus 27:3-10; Marcos 14:27; João 13:18; João 15:25"
        },
        {
            termo: "09. Profecias da Ressurreição do Messias",
            definicao: "As profecias sobre a ressurreição do Messias: (1) Salmo 16:10 - 'Não permitirás que o teu Santo veja corrupção.' - A ressurreição do Messias. Cumprimento: Atos 2:25-32; 13:34-37. (2) Isaías 53:10-11 - 'Verá a sua posteridade... prolongará os seus dias... verá o fruto do trabalho da sua alma.' - A ressurreição e vida pós-morte. Cumprimento: Atos 2:24; Romanos 6:9. (3) Salmo 30:3 - 'Senhor, fizeste subir a minha alma da sepultura; conservaste-me a vida para que não descesse à cova.' - Cumprimento: Mateus 28:1-10. (4) Jonas 1:17 - 'Jonas esteve três dias e três noites no ventre do peixe.' - Tipo da ressurreição. Cumprimento: Mateus 12:40. (5) Oséias 6:2 - 'Depois de dois dias nos dará a vida; ao terceiro dia nos ressuscitará.' - A ressurreição ao terceiro dia. Cumprimento: 1 Coríntios 15:4. (6) Isaías 55:3 - 'Darei-vos as santas e fiéis bênçãos de Davi.' - A vida eterna garantida pela ressurreição. Cumprimento: Atos 13:34. (7) Salmo 118:17 - 'Não morrerei, mas viverei; e contarei as obras do Senhor.' - Cumprimento: Apocalipse 1:18. A teologia reformada vê na ressurreição o cumprimento das profecias e a garantia da nossa ressurreição.",
            referencias: "Salmo 16:10; Salmo 30:3; Salmo 118:17; Isaías 53:10-11; Isaías 55:3; Oséias 6:2; Jonas 1:17; Mateus 12:40; Mateus 28:1-10; Atos 2:24-32; Atos 13:34-37; Romanos 6:9; 1 Coríntios 15:4; Apocalipse 1:18"
        },
        {
            termo: "10. Profecias da Ascensão, Exaltação e Reinado do Messias",
            definicao: "As profecias sobre a ascensão, exaltação e reinado do Messias: (1) Salmo 68:18 - 'Subiste ao alto, levaste cativo o cativeiro, recebeste dons para os homens.' - A ascensão de Cristo. Cumprimento: Atos 1:9-11; Efésios 4:8-10. (2) Salmo 110:1 - 'Assenta-te à minha direita, até que ponha os teus inimigos por escabelo dos teus pés.' - A sessão à direita de Deus. Cumprimento: Mateus 22:44; Marcos 16:19; Atos 2:33-35; Hebreus 1:3,13; 10:12-13. (3) Salmo 110:4 - 'Tu és sacerdote para sempre, segundo a ordem de Melquisedeque.' - O sacerdócio eterno de Cristo. Cumprimento: Hebreus 5:6; 6:20; 7:17,21. (4) Daniel 7:13-14 - 'Foi-lhe dado domínio, e honra, e reino... o seu reino não será destruído.' - O reinado universal de Cristo. Cumprimento: Mateus 28:18; Apocalipse 11:15. (5) Salmo 2:6-9 - 'Assentarei o meu rei sobre Sião... dar-te-ei os gentios por herança.' - O reinado de Cristo sobre as nações. Cumprimento: Apocalipse 2:26-27; 12:5; 19:15. (6) Isaías 9:6-7 - 'O seu reino não terá fim.' - O reino eterno. Cumprimento: Lucas 1:33; Apocalipse 22:5. (7) Zacarias 14:9 - 'O Senhor será rei sobre toda a terra.' - Cumprimento: Filipenses 2:9-11. (8) Salmo 45:6-7 - 'O teu trono, ó Deus, é eterno.' - A divindade e realeza de Cristo. Cumprimento: Hebreus 1:8-9. A teologia reformada vê nestas profecias a exaltação de Cristo à direita do Pai.",
            referencias: "Salmo 2:6-9; Salmo 45:6-7; Salmo 68:18; Salmo 110:1; Salmo 110:4; Isaías 9:6-7; Daniel 7:13-14; Zacarias 14:9; Mateus 22:44; Mateus 28:18; Marcos 16:19; Lucas 1:33; Atos 1:9-11; Atos 2:33-35; Efésios 4:8-10; Filipenses 2:9-11; Hebreus 1:3; Hebreus 1:8-9; Hebreus 1:13; Hebreus 5:6; Hebreus 6:20; Hebreus 7:17; Hebreus 7:21; Hebreus 10:12-13; Apocalipse 2:26-27; Apocalipse 11:15; Apocalipse 12:5; Apocalipse 19:15; Apocalipse 22:5"
        },
        {
            termo: "11. Profecias da Segunda Vinda e Juízo do Messias",
            definicao: "As profecias sobre a segunda vinda e o juízo do Messias: (1) Daniel 7:13-14 - 'Vindo nas nuvens do céu.' - A parusia (segunda vinda). Cumprimento: Mateus 24:30; 26:64; Atos 1:11; Apocalipse 1:7. (2) Zacarias 14:4-5 - 'E os seus pés estarão naquele dia sobre o monte das Oliveiras.' - A volta de Cristo ao monte das Oliveiras. Cumprimento: Atos 1:11-12. (3) Malaquias 3:1-3 - 'Virá de repente ao seu templo... mas quem suportará o dia da sua vinda?' - A segunda vinda como juízo. Cumprimento: 2 Tessalonicenses 1:7-10. (4) Isaías 66:15-16 - 'Porque eis que o Senhor virá com fogo... para executar o seu juízo.' - O juízo final. Cumprimento: 2 Pedro 3:7,10-12. (5) Salmo 96:13 - 'Virá a julgar a terra; julgará o mundo com justiça e os povos com a sua verdade.' - Cumprimento: Atos 17:31. (6) Joel 3:12-14 - 'Despertem as nações... porque ali estarei para julgar todas as nações.' - O vale do juízo. Cumprimento: Mateus 25:31-46. (7) Zacarias 12:10 - 'Olharão para mim, a quem traspassaram.' - A consumação. Cumprimento: Apocalipse 1:7. (8) Daniel 12:2 - 'Muitos dos que dormem no pó da terra ressuscitarão, uns para a vida eterna, e outros para vergonha e desprezo eterno.' - A ressurreição geral. Cumprimento: João 5:28-29. A teologia reformada vê nestas profecias a esperança da parusia e a certeza do juízo final.",
            referencias: "Salmo 96:13; Isaías 66:15-16; Daniel 7:13-14; Daniel 12:2; Joel 3:12-14; Zacarias 12:10; Zacarias 14:4-5; Malaquias 3:1-3; Mateus 24:30; Mateus 25:31-46; Mateus 26:64; Atos 1:11-12; Atos 17:31; 2 Tessalonicenses 1:7-10; 2 Pedro 3:7; 2 Pedro 3:10-12; Apocalipse 1:7"
        },
        {
            termo: "12. Profecias sobre a Salvação para os Gentios",
            definicao: "As profecias sobre a salvação dos gentios em Cristo: (1) Gênesis 12:3 - 'Em ti serão benditas todas as famílias da terra.' - Cumprimento: Gálatas 3:8. (2) Isaías 42:6 - 'Te darei como luz dos gentios.' - Cumprimento: Lucas 2:32; Atos 13:47. (3) Isaías 49:6 - 'Te darei como luz dos gentios, para que sejas a minha salvação até à extremidade da terra.' - Cumprimento: Atos 13:47. (4) Isaías 60:3 - 'As nações andarão à tua luz.' - Cumprimento: Apocalipse 21:24. (5) Salmo 22:27 - 'Todos os limites da terra se lembrarão e se converterão ao Senhor.' - Cumprimento: Romanos 15:9-12. (6) Amós 9:11-12 - 'Levantarei o tabernáculo de Davi... para que possuam o resto de Edom e todas as nações.' - Cumprimento: Atos 15:16-18. (7) Isaías 11:10 - 'Buscarão os gentios a raiz de Jessé.' - Cumprimento: Romanos 15:12. (8) Salmo 117:1 - 'Louvai ao Senhor, todas as nações.' - Cumprimento: Romanos 15:11. (9) Oséias 2:23 - 'Chamarei a meu povo ao que não era meu povo.' - Cumprimento: Romanos 9:25-26. A teologia reformada vê nestas profecias a inclusão dos gentios na aliança da graça.",
            referencias: "Gênesis 12:3; Salmo 22:27; Salmo 117:1; Isaías 11:10; Isaías 42:6; Isaías 49:6; Isaías 60:3; Oséias 2:23; Amós 9:11-12; Lucas 2:32; Atos 13:47; Atos 15:16-18; Romanos 9:25-26; Romanos 15:9-12; Gálatas 3:8; Apocalipse 21:24"
        },
        {
            termo: "13. Síntese: O Cumprimento das Profecias como Evidência da Divindade de Cristo",
            definicao: "O cumprimento das profecias do Antigo Testamento em Jesus Cristo é uma das evidências mais poderosas de sua divindade e da inspiração das Escrituras. As profecias não são vagas ou genéricas, mas específicas e detalhadas: nascimento em Belém (Miqueias 5:2), nascimento virginal (Isaías 7:14), descendência de Davi (2 Samuel 7:12-16), traição por 30 moedas de prata (Zacarias 11:12-13), crucificação com traspassamento de mãos e pés (Salmo 22:16), morte com os ímpios e sepultamento com os ricos (Isaías 53:9), ressurreição ao terceiro dia (Salmo 16:10; Oséias 6:2), ascensão à direita de Deus (Salmo 110:1), e muitas outras. A probabilidade matemática de uma pessoa cumprir todas estas profecias é astronomicamente pequena (estimada em 1 em 10^17 para apenas 8 profecias). A teologia reformada vê no cumprimento das profecias a prova de que Jesus é o Messias prometido, o Filho de Deus. 'E começando por Moisés e por todos os profetas, explicava-lhes o que dele se achava em todas as Escrituras' (Lucas 24:27). 'Examinais as Escrituras, porque vós cuidais ter nelas a vida eterna, e são elas que de mim testificam' (João 5:39). 'Toda a Escritura é inspirada por Deus e útil para o ensino, para a repreensão, para a correção, para a instrução na justiça' (2 Timóteo 3:16). Soli Deo Gloria!",
            referencias: "Lucas 24:27; Lucas 24:44-45; João 5:39; Atos 10:43; Romanos 1:1-4; 1 Coríntios 15:3-4; 2 Timóteo 3:16-17; 2 Pedro 1:19-21"
        }
    ]
};