// volume/volume-93.js
window.LIVRO_DATA = {
    nome: "Volume XCIII",
    dados: [
        {
            termo: "01. Introdução: A Glória de Deus Revelada em Cristo",
            definicao: "A glória de Deus (kabod YHWH, doxa Theou) é a manifestação da sua majestade, santidade, poder e amor. A glória de Deus é revelada plenamente em Jesus Cristo. 'E o Verbo se fez carne, e habitou entre nós, e vimos a sua glória, glória como do unigênito do Pai, cheio de graça e de verdade' (João 1:14). 'Porque Deus, que disse que das trevas resplandecesse a luz, é quem resplandeceu em nossos corações, para iluminação do conhecimento da glória de Deus, na face de Jesus Cristo' (2 Coríndios 4:6). A teologia reformada (Calvino, Edwards) enfatiza que o propósito final de todas as coisas é a glória de Deus (Soli Deo Gloria). Este volume explora: (1) A glória de Deus no Antigo Testamento. (2) A glória de Cristo na encarnação. (3) A glória de Cristo na transfiguração. (4) A glória de Cristo na cruz. (5) A glória de Cristo na ressurreição e ascensão. (6) A glória de Cristo na igreja. (7) A glória de Cristo na nova criação. 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36).",
            referencias: "Êxodo 33:18-23; Isaías 6:1-3; Ezequiel 1:28; João 1:14; João 17:5; Romanos 11:36; 2 Coríndios 4:6; Efésios 1:17-18; Hebreus 1:3; Apocalipse 21:23"
        },
        {
            termo: "02. A Glória de Deus no Antigo Testamento - A Shekinah",
            definicao: "No Antigo Testamento, a glória de Deus (Shekinah) se manifestava de várias formas: (1) A nuvem e o fogo no deserto (Êxodo 13:21-22). (2) A glória no monte Sinai (Êxodo 19:16-19; 24:16-17). (3) A glória no tabernáculo (Êxodo 40:34-35). (4) A glória no templo (1 Reis 8:10-11). (5) A visão de Isaías (Isaías 6:1-3). (6) A visão de Ezequiel (Ezequiel 1:28). (7) A glória que enche a terra (Números 14:21; Salmo 72:19). (8) A glória que retorna ao templo (Ezequiel 43:1-5). (9) A glória que será revelada a todas as nações (Isaías 40:5). (10) A glória que habitará com seu povo (Zacarias 2:5). A Shekinah era uma manifestação temporária e limitada. Apontava para a glória plena que seria revelada em Cristo. A teologia reformada (Calvino, Bavinck) vê na glória do AT uma antecipação da glória de Cristo. 'O Deus, que disse que das trevas resplandecesse a luz, é quem resplandeceu em nossos corações, para iluminação do conhecimento da glória de Deus, na face de Jesus Cristo' (2 Coríndios 4:6).",
            referencias: "Êxodo 13:21-22; Êxodo 16:10; Êxodo 24:16-17; Êxodo 33:18-23; Êxodo 40:34-35; 1 Reis 8:10-11; 2 Crônicas 5:13-14; Isaías 6:1-3; Ezequiel 1:28; Ezequiel 43:1-5; Ageu 2:7-9; Zacarias 2:5"
        },
        {
            termo: "03. A Glória de Cristo na Encarnação - O Verbo se Fez Carne",
            definicao: "A encarnação é a manifestação máxima da glória de Deus. 'E o Verbo se fez carne, e habitou entre nós, e vimos a sua glória, glória como do unigênito do Pai, cheio de graça e de verdade' (João 1:14). 'Nós vimos a sua glória' (João 1:14). Características da glória de Cristo na encarnação: (1) Glória oculta: a divindade estava oculta na humanidade (Filipenses 2:5-8). (2) Glória revelada: nos milagres (João 2:11). (3) Glória da graça: 'cheio de graça e de verdade' (João 1:14). (4) Glória da verdade: Jesus é a verdade (João 14:6). (5) Glória do amor: 'tendo amado os seus... amou-os até o fim' (João 13:1). (6) Glória da humildade: 'esvaziou-se a si mesmo' (Filipenses 2:7). (7) Glória da obediência: 'obediente até à morte' (Filipenses 2:8). (8) Glória da compaixão: curou os enfermos (Mateus 14:14). (9) Glória da santidade: 'sem pecado' (Hebreus 4:15). (10) Glória da ressurreição: 'declarado Filho de Deus com poder, pela ressurreição dos mortos' (Romanos 1:4). A teologia reformada (Calvino, Edwards) vê na encarnação a glória de Deus revelada em forma humana. 'Grande é o mistério da piedade: Deus se manifestou em carne' (1 Timóteo 3:16).",
            referencias: "João 1:14; João 1:18; João 2:11; João 11:4; João 12:23; João 13:31-32; João 17:1-5; Romanos 1:4; Filipenses 2:5-11; 1 Timóteo 3:16; Hebreus 1:3"
        },
        {
            termo: "04. A Transfiguração de Cristo - A Revelação da Glória Divina (Mateus 17:1-8)",
            definicao: "A transfiguração foi uma revelação antecipada da glória divina de Cristo. 'Seis dias depois, tomou Jesus consigo Pedro, Tiago e João, seu irmão, e os levou em particular a um alto monte. E foi transfigurado diante deles; o seu rosto resplandecia como o sol, e as suas vestes se tornaram brancas como a luz' (Mateus 17:1-2). Significados: (1) Confirmação da divindade de Cristo. (2) Antecipação da glória da ressurreição. (3) Testemunho da Lei (Moisés) e dos Profetas (Elias). (4) A voz do Pai: 'Este é o meu Filho amado, em quem me comprazo; escutai-o' (Mateus 17:5). (5) Preparação para a paixão (Lucas 9:31). (6) Garantia da glória futura dos crentes (2 Pedro 1:16-18). (7) Manifestação da glória que Jesus tinha antes da fundação do mundo (João 17:5). (8) Antecipação da segunda vinda (2 Pedro 1:16-18). A teologia reformada (Calvino, Owen) vê na transfiguração a glória de Cristo revelada aos discípulos. 'E sabemos que, quando ele se manifestar, seremos semelhantes a ele; porque assim como ele é, o veremos' (1 João 3:2).",
            referencias: "Mateus 17:1-8; Marcos 9:2-8; Lucas 9:28-36; 2 Pedro 1:16-18; Apocalipse 1:13-16; Apocalipse 10:1"
        },
        {
            termo: "05. A Glória de Cristo na Cruz - Glória na Humilhação",
            definicao: "A cruz, paradoxalmente, é a glória de Cristo. 'E, quando Judas saiu, disse Jesus: Agora é glorificado o Filho do Homem, e Deus é glorificado nele' (João 13:31). 'Pai, é chegada a hora; glorifica a teu Filho, para que também o teu Filho te glorifique a ti' (João 17:1). A cruz é glória porque: (1) Revela o amor de Deus (Romanos 5:8). (2) Revela a justiça de Deus (Romanos 3:25-26). (3) Revela a sabedoria de Deus (1 Coríndios 1:24). (4) Revela o poder de Deus (1 Coríndios 1:18,24). (5) Revela a obediência de Cristo (Filipenses 2:8). (6) Revela a vitória sobre o pecado (Romanos 6:6-7). (7) Revela a vitória sobre a morte (1 Coríndios 15:54-57). (8) Revela a vitória sobre Satanás (Colossenses 2:15). (9) Revela a reconciliação (2 Coríndios 5:18-21). (10) Revela a glória da graça (Efésios 1:6). A teologia reformada (Calvino, Owen) vê na cruz o lugar onde a glória de Deus brilha mais intensamente. 'Longe esteja de mim gloriar-me, a não ser na cruz de nosso Senhor Jesus Cristo' (Gálatas 6:14).",
            referencias: "João 12:23-28; João 13:31-32; João 17:1-5; Romanos 5:8; 1 Coríndios 1:18-25; Gálatas 6:14; Colossenses 1:19-20; Colossenses 2:13-15; Hebreus 2:9; Apocalipse 5:12"
        },
        {
            termo: "06. A Glória de Cristo na Ressurreição e Ascensão",
            definicao: "A ressurreição e a ascensão são a entrada de Cristo na glória plena. 'E foi declarado Filho de Deus com poder, segundo o Espírito de santificação, pela ressurreição dos mortos' (Romanos 1:4). 'Pelo que também Deus o exaltou soberanamente, e lhe deu um nome que é sobre todo o nome' (Filipenses 2:9). 'O qual, sendo o resplendor da sua glória e a expressa imagem da sua pessoa... assentou-se à destra da majestade nas alturas' (Hebreus 1:3). Características da glória pós-ressurreição: (1) Corpo glorificado (Lucas 24:39-43). (2) Autoridade universal (Mateus 28:18). (3) Nome sobre todo nome (Filipenses 2:9-11). (4) Sessão à direita de Deus (Atos 2:33-35; Efésios 1:20). (5) Intercessão pelos crentes (Romanos 8:34; Hebreus 7:25). (6) Cabeça da igreja (Efésios 1:22-23). (7) Senhor dos vivos e dos mortos (Romanos 14:9). (8) Juiz final (Atos 10:42; 17:31). (9) Fonte do Espírito Santo (Atos 2:33). (10) Garantia da nossa ressurreição (1 Coríndios 15:20-23). A teologia reformada (Calvino, Bavinck) vê na ascensão a entrada de Cristo na glória celestial. 'E nós todos, com rosto descoberto, refletindo como um espelho a glória do Senhor, somos transformados de glória em glória na mesma imagem' (2 Coríndios 3:18).",
            referencias: "Marcos 16:19; Lucas 24:50-53; Atos 1:9-11; Atos 2:33-36; Romanos 6:9-10; Efésios 1:20-23; Filipenses 2:9-11; Colossenses 3:1; 1 Timóteo 3:16; Hebreus 1:3-4; 1 Pedro 3:22"
        },
        {
            termo: "07. A Glória de Cristo na Igreja - O Corpo Glorificado",
            definicao: "A glória de Cristo se manifesta através da igreja, seu corpo. 'E pôs todas as coisas debaixo de seus pés, e para ser a cabeça sobre todas as coisas o deu à igreja, que é o seu corpo, a plenitude daquele que cumpre tudo em todos' (Efésios 1:22-23). 'Para que apresente a si mesmo igreja gloriosa' (Efésios 5:27). Como a glória de Cristo se manifesta na igreja: (1) Através da pregação da Palavra (Romanos 10:14-17). (2) Através dos sacramentos (batismo e ceia). (3) Através do amor fraternal (João 13:34-35). (4) Através da unidade (João 17:20-23). (5) Através da santidade (Efésios 5:27). (6) Através do serviço (Gálatas 5:13). (7) Através do sofrimento (2 Coríndios 4:10-11). (8) Através dos dons espirituais (1 Coríndios 12:4-7). (9) Através da oração (Atos 4:31). (10) Através do evangelismo (Mateus 28:19-20). A glória da igreja não é própria, mas refletida de Cristo. 'Porque dele e por ele, e para ele, são todas as coisas' (Romanos 11:36). A teologia reformada (Kuyper, Bavinck) vê na igreja o reflexo da glória de Cristo. 'E nós todos, com rosto descoberto, refletindo como um espelho a glória do Senhor, somos transformados de glória em glória na mesma imagem' (2 Coríndios 3:18).",
            referencias: "João 13:34-35; João 17:20-23; Romanos 9:23-24; Efésios 1:22-23; Efésios 3:10; Efésios 5:25-27; Colossenses 1:27; 2 Tessalonicenses 1:10-12; 1 Pedro 2:9; 1 Pedro 4:14"
        },
        {
            termo: "08. A Glória de Cristo nos Crentes - Transformados de Glória em Glória",
            definicao: "Os crentes são transformados à imagem da glória de Cristo. 'E nós todos, com rosto descoberto, refletindo como um espelho a glória do Senhor, somos transformados de glória em glória na mesma imagem, como pelo Espírito do Senhor' (2 Coríndios 3:18). 'Porque os que dantes conheceu, também os predestinou para serem conformes à imagem de seu Filho' (Romanos 8:29). Aspectos da glória nos crentes: (1) Glória da justificação (Romanos 3:23-24). (2) Glória da adoção (1 João 3:1). (3) Glória da santificação (2 Coríndios 3:18). (4) Glória da perseverança (Romanos 5:2-5). (5) Glória do testemunho (Mateus 5:16). (6) Glória do serviço (João 12:26). (7) Glória do sofrimento (Romanos 8:17). (8) Glória da oração (João 14:13). (9) Glória da comunhão (1 João 1:3). (10) Glória da esperança (Romanos 5:2). A transformação é progressiva: de glória em glória. A teologia reformada (Calvino, Edwards) enfatiza que a glória do crente é refletida, não inerente. 'Vós sois o sal da terra... vós sois a luz do mundo' (Mateus 5:13-14).",
            referencias: "Romanos 5:2; Romanos 8:17; Romanos 8:30; 1 Coríndios 15:43; 2 Coríndios 4:17; Colossenses 3:4; 1 Tessalonicenses 2:12; 2 Tessalonicenses 2:14; 2 Timóteo 2:10; 1 Pedro 5:10; 1 João 3:2"
        },
        {
            termo: "09. A Glória de Cristo na Nova Criação - A Consumação da Glória",
            definicao: "Na nova criação, a glória de Deus e do Cordeiro será plenamente manifestada. 'E a cidade não necessita de sol nem de lua, para que nela resplandeçam, porque a glória de Deus a tem iluminado, e o Cordeiro é a sua lâmpada' (Apocalipse 21:23). 'E vi um novo céu e uma nova terra' (Apocalipse 21:1). Características da glória na nova criação: (1) Ausência de sol e lua (a glória de Deus é a luz) (Apocalipse 21:23). (2) Ausência de templo (Deus e o Cordeiro são o templo) (Apocalipse 21:22). (3) Ausência de maldição (Apocalipse 22:3). (4) Ausência de morte, pranto, clamor, dor (Apocalipse 21:4). (5) Presença da árvore da vida (Apocalipse 22:2). (6) Presença do rio da água da vida (Apocalipse 22:1). (7) Serviço a Deus (Apocalipse 22:3). (8) Visão de Deus (Apocalipse 22:4). (9) Nome de Deus nas frontes (Apocalipse 22:4). (10) Reinado eterno (Apocalipse 22:5). A glória da nova criação é a consumação da oração de Cristo: 'Pai, quero que onde eu estou, também eles estejam comigo, para que vejam a minha glória' (João 17:24). A teologia reformada (Calvino, Bavinck) vê na nova criação o triunfo final da glória de Deus. 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36).",
            referencias: "Isaías 60:1-3; Isaías 60:19-20; Ezequiel 48:35; Romanos 8:18; 2 Coríndios 4:17; Filipenses 3:20-21; Colossenses 3:4; 2 Pedro 3:13; Apocalipse 21:1-27; Apocalipse 22:1-5"
        },
        {
            termo: "10. Soli Deo Gloria - Somente a Deus a Glória",
            definicao: "Soli Deo Gloria (somente a Deus a glória) é um dos cinco solas da Reforma Protestante. 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36). 'Não a nós, Senhor, não a nós, mas ao teu nome dá glória, por amor da tua misericórdia e da tua verdade' (Salmo 115:1). 'Portanto, quer comais quer bebais, ou façais outra qualquer coisa, fazei tudo para glória de Deus' (1 Coríndios 10:31). Implicações do Soli Deo Gloria: (1) A salvação é pela graça, não por obras (Efésios 2:8-9). (2) A vida cristã é para a glória de Deus (1 Coríndios 10:31). (3) A adoração é para a glória de Deus (Salmo 96:8-9). (4) O trabalho é para a glória de Deus (Colossenses 3:23). (5) A família é para a glória de Deus (Josué 24:15). (6) A igreja é para a glória de Deus (Efésios 3:21). (7) A criação é para a glória de Deus (Salmo 19:1). (8) A história é para a glória de Deus (Romanos 11:36). (9) O sofrimento pode ser para a glória de Deus (João 11:4). (10) A morte pode ser para a glória de Deus (João 21:19). A teologia reformada (Calvino, Edwards) enfatiza que a glória de Deus é o fim supremo de todas as coisas. 'A glória de Deus é o fim último da criação e da redenção' (Westminster Confession).",
            referencias: "Salmo 115:1; Isaías 42:8; Isaías 48:11; Mateus 5:16; João 15:8; Romanos 11:36; 1 Coríndios 10:31; Efésios 1:6; Efésios 1:12; Efésios 1:14; Efésios 3:21; 1 Pedro 4:11; Apocalipse 4:11"
        },
        {
            termo: "11. A Glória de Cristo na Teologia Reformada - Calvino e Edwards",
            definicao: "A teologia reformada enfatiza a glória de Deus como o centro de toda a teologia. João Calvino (1509-1564) escreveu: 'O fim da vida cristã é a glória de Deus'. Em suas 'Institutas', Calvino afirma que toda a criação existe para a glória de Deus. Jonathan Edwards (1703-1758), o maior teólogo americano, escreveu 'O Fim para o qual Deus Criou o Mundo', argumentando que a glória de Deus é o fim supremo da criação. 'A glória de Deus é a soma de todas as suas perfeições' (Edwards). Características da glória de Deus segundo Edwards: (1) Glória intrínseca: a beleza das perfeições divinas. (2) Glória emanada: a manifestação externa das perfeições divinas. (3) Glória comunicada: a participação dos crentes na glória divina. (4) Glória refletida: a criação reflete a glória de Deus. (5) Glória redentora: a cruz é a manifestação máxima da glória de Deus. (6) Glória escatológica: a nova criação será a plenitude da glória. A teologia reformada (Calvino, Edwards, Kuyper, Bavinck) celebra a glória de Deus como o centro da fé cristã. 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36).",
            referencias: "Romanos 11:36; 1 Coríndios 10:31; Efésios 1:6; Efésios 1:12; Efésios 1:14; Efésios 3:21; Filipenses 1:11; 1 Pedro 4:11; Apocalipse 4:11; Apocalipse 5:12-13"
        },
        {
            termo: "12. Vivendo para a Glória de Cristo - Aplicações Práticas",
            definicao: "A teologia da glória deve ser vivida na prática. 'Portanto, quer comais quer bebais, ou façais outra qualquer coisa, fazei tudo para glória de Deus' (1 Coríndios 10:31). Aplicações: (1) No trabalho: trabalhe para a glória de Deus (Colossenses 3:23). (2) Na família: eduque os filhos para a glória de Deus (Efésios 6:4). (3) Na igreja: adore para a glória de Deus (Salmo 96:8-9). (4) No estudo: estude para a glória de Deus (Provérbios 1:7). (5) No lazer: divirta-se para a glória de Deus (Filipenses 4:8). (6) Nas finanças: administre o dinheiro para a glória de Deus (Provérbios 3:9). (7) Na saúde: cuide do corpo para a glória de Deus (1 Coríndios 6:19-20). (8) Nos relacionamentos: ame para a glória de Deus (João 13:34-35). (9) No sofrimento: sofra para a glória de Deus (1 Pedro 4:16). (10) Na morte: morra para a glória de Deus (Filipenses 1:20-21). (11) No evangelismo: evangelize para a glória de Deus (Mateus 28:19). (12) Na missão: sirva para a glória de Deus (Atos 20:24). (13) Na adoração: adore para a glória de Deus (Apocalipse 4:11). (14) Na oração: ore para a glória de Deus (João 14:13). (15) Na esperança: espere para a glória de Deus (Tito 2:13). A teologia reformada (Kuyper, Schaeffer) nos chama a viver 'coram Deo' (diante de Deus) e para a glória de Deus. 'E tudo quanto fizerdes, por palavra ou por obra, fazei-o em nome do Senhor Jesus, dando por ele graças a Deus Pai' (Colossenses 3:17).",
            referencias: "Mateus 5:16; João 14:13; Romanos 15:5-6; 1 Coríndios 6:20; 1 Coríndios 10:31; 2 Coríndios 4:15; Efésios 1:12; Filipenses 1:11; Colossenses 3:17; 1 Tessalonicenses 2:12; 2 Tessalonicenses 1:10; 1 Pedro 2:12; 1 Pedro 4:11; Apocalipse 4:11"
        },
        {
            termo: "13. Síntese: Toda Glória a Cristo",
            definicao: "A teologia da glória culmina na adoração a Cristo. 'Digno é o Cordeiro, que foi morto, de receber o poder, e riquezas, e sabedoria, e força, e honra, e glória, e ações de graças' (Apocalipse 5:12). 'Ao que está assentado sobre o trono, e ao Cordeiro, seja o louvor, e a honra, e a glória, e o poder para todo o sempre' (Apocalipse 5:13). Resumo da teologia da glória: (1) A glória de Deus é revelada em Cristo (João 1:14). (2) A Shekinah no AT apontava para a glória de Cristo (Êxodo 40:34-35). (3) A encarnação é a glória oculta de Cristo (Filipenses 2:5-8). (4) A transfiguração revelou a glória divina de Cristo (Mateus 17:1-8). (5) A cruz é a glória paradoxal de Cristo (João 13:31). (6) A ressurreição e ascensão são a glória exaltada de Cristo (Filipenses 2:9-11). (7) A igreja reflete a glória de Cristo (Efésios 1:22-23). (8) Os crentes são transformados de glória em glória (2 Coríndios 3:18). (9) A nova criação será a plenitude da glória (Apocalipse 21:23). (10) Soli Deo Gloria é o princípio reformado (Romanos 11:36). (11) Toda a vida deve ser para a glória de Cristo (1 Coríndios 10:31). (12) A glória de Cristo é o fim de todas as coisas (Romanos 11:36). (13) Toda glória seja dada a Cristo (Apocalipse 5:12-14). 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36). 'Aquele que testifica estas coisas diz: Certamente cedo venho. Amém. Ora vem, Senhor Jesus. A graça de nosso Senhor Jesus Cristo seja com todos vós. Amém' (Apocalipse 22:20-21). Soli Deo Gloria!",
            referencias: "Romanos 11:36; 1 Coríndios 10:31; Efésios 3:20-21; Filipenses 2:9-11; 1 Timóteo 1:17; 1 Pedro 4:11; 2 Pedro 3:18; Judas 1:25; Apocalipse 1:6; Apocalipse 4:11; Apocalipse 5:12-14; Apocalipse 7:12; Apocalipse 19:1"
        }
    ]
};