// volume/volume-41.js
window.LIVRO_DATA = {
    nome: "Volume XLI",
    dados: [
        {
            termo: "01. Introdução: A Páscoa como Centro da Fé Cristã",
            definicao: "A Páscoa (Ressurreição de Cristo) é o evento central da fé cristã e a celebração mais importante do ano litúrgico. O apóstolo Paulo declarou: 'E, se Cristo não ressuscitou, é vã a nossa pregação, e também é vã a vossa fé' (1 Coríntios 15:14). 'Mas, agora, Cristo ressuscitou dentre os mortos, e foi feito as primícias dos que dormem' (1 Coríntios 15:20). A Páscoa não é apenas uma lembrança histórica, mas uma realidade presente que transforma a vida do crente. A teologia reformada enfatiza que a ressurreição é: (1) A confirmação da divindade de Cristo (Romanos 1:4). (2) A vitória sobre o pecado e a morte (Romanos 6:9; 1 Coríntios 15:54-57). (3) A garantia da nossa justificação (Romanos 4:25). (4) A garantia da nossa ressurreição (1 Coríntios 15:20-23). (5) A base da nossa nova vida em Cristo (Romanos 6:4). (6) A esperança da parusia (segunda vinda). Este volume explora a teologia da Páscoa, suas raízes no Antigo Testamento (Páscoa judaica), seu cumprimento em Cristo, e sua celebração na igreja. 'Cristo, nossa Páscoa, foi sacrificado por nós' (1 Coríntios 5:7).",
            referencias: "Êxodo 12:1-28; Levítico 23:4-8; Mateus 28:1-10; Marcos 16:1-8; Lucas 24:1-12; João 20:1-18; Atos 2:22-36; Romanos 1:4; Romanos 4:25; Romanos 6:4-5; 1 Coríntios 5:7; 1 Coríntios 15:1-58; 1 Pedro 1:3-5"
        },
        {
            termo: "02. A Páscoa Judaica (Pessach) - A Sombra do Cordeiro Pascal",
            definicao: "A Páscoa judaica (Pessach) foi instituída por Deus no Êxodo, quando Israel foi libertado da escravidão do Egito (Êxodo 12:1-28). Eventos principais: (1) O cordeiro sem defeito era sacrificado no dia 14 do mês de Nisan (Êxodo 12:3-6). (2) O sangue do cordeiro era aspergido nos umbrais das portas (Êxodo 12:7,22-23). (3) O anjo da morte 'passou por cima' (pasach) das casas protegidas pelo sangue (Êxodo 12:13,23). (4) O povo comia o cordeiro assado com pães asmos e ervas amargas (Êxodo 12:8). (5) A festa durava sete dias (Êxodo 12:15-20). Significados teológicos da Páscoa judaica: (a) Libertação do Egito (escravidão) - tipo da libertação do pecado. (b) O sangue do cordeiro como proteção - tipo do sangue de Cristo. (c) O cordeiro sem defeito - tipo de Cristo sem pecado. (d) A pressa em comer (Êxodo 12:11) - tipo da urgência da fé. (e) Os pães asmos (sem fermento) - tipo da pureza e santidade (1 Coríntios 5:7-8). A Páscoa judaica era uma 'sombra das coisas futuras' (Colossenses 2:17), cujo cumprimento é Cristo. Paulo escreve: 'Cristo, nossa Páscoa, foi sacrificado por nós' (1 Coríntios 5:7). A teologia reformada vê na Páscoa judaica o tipo da redenção em Cristo.",
            referencias: "Êxodo 12:1-28; Levítico 23:4-8; Números 9:1-14; Deuteronômio 16:1-8; Isaías 53:7; João 1:29; 1 Coríntios 5:7; 1 Pedro 1:18-19; Colossenses 2:17; Hebreus 8:5; Hebreus 10:1"
        },
        {
            termo: "03. A Última Ceia - Jesus Institui a Nova Páscoa",
            definicao: "Na noite anterior à sua morte, Jesus celebrou a Páscoa com seus discípulos (Mateus 26:17-30; Marcos 14:12-26; Lucas 22:7-23; João 13-17). Durante a ceia, Jesus transformou a Páscoa judaica na Ceia do Senhor (Eucaristia). Eventos: (1) Jesus tomou o pão, partiu-o e disse: 'Isto é o meu corpo, que por vós é dado; fazei isto em memória de mim' (Lucas 22:19). (2) Jesus tomou o cálice e disse: 'Este cálice é o novo testamento no meu sangue, que por vós é derramado' (Lucas 22:20). (3) Jesus lavou os pés dos discípulos (João 13:1-17) - exemplo de humildade. (4) Jesus anunciou a traição de Judas (Mateus 26:21-25; João 13:21-30). (5) Jesus instituiu o 'mandamento novo': 'Que vos ameis uns aos outros, como eu vos amei a vós' (João 13:34-35). (6) A Oração Sacerdotal (João 17:1-26). (7) O cântico de um hino (Mateus 26:30; Marcos 14:26). Significados teológicos: (a) Jesus é o verdadeiro Cordeiro Pascal (1 Coríntios 5:7). (b) A Ceia do Senhor substitui a Páscoa judaica como o memorial da redenção em Cristo. (c) O 'novo testamento' (aliança) é inaugurado em seu sangue (Jeremias 31:31-34; Hebreus 8:6-13). (d) A Ceia aponta para a volta de Cristo: 'Não beberei deste fruto da vide, até aquele dia em que o beba novo convosco no reino de meu Pai' (Mateus 26:29). A teologia reformada celebra a Ceia do Senhor como memorial e comunhão espiritual com Cristo.",
            referencias: "Êxodo 12:1-28; Jeremias 31:31-34; Mateus 26:17-30; Marcos 14:12-26; Lucas 22:7-23; João 13-17; 1 Coríntios 5:7; 1 Coríntios 11:23-34; Hebreus 8:6-13"
        },
        {
            termo: "04. A Crucificação - O Sacrifício do Cordeiro de Deus",
            definicao: "Jesus foi crucificado na sexta-feira, dia da preparação da Páscoa (João 19:14,31). Ele morreu como o Cordeiro de Deus que tira o pecado do mundo (João 1:29). Detalhes da crucificação: (1) Jesus foi condenado por Pilatos (Mateus 27:11-26; Marcos 15:1-15; Lucas 23:1-25; João 18:28-19:16). (2) Jesus foi açoitado, coroado de espinhos e humilhado (Mateus 27:27-31; João 19:1-5). (3) Jesus foi crucificado no Gólgota (Lugar da Caveira) entre dois ladrões (Mateus 27:33-38; Marcos 15:22-27; Lucas 23:32-33; João 19:17-18). (4) Suas últimas palavras (as 'sete palavras'): (a) 'Pai, perdoa-lhes, porque não sabem o que fazem' (Lucas 23:34). (b) 'Em verdade te digo que hoje estarás comigo no paraíso' (Lucas 23:43). (c) 'Mulher, eis aí o teu filho... Eis aí tua mãe' (João 19:26-27). (d) 'Deus meu, Deus meu, por que me desamparaste?' (Mateus 27:46; Marcos 15:34). (e) 'Tenho sede' (João 19:28). (f) 'Está consumado' (João 19:30). (g) 'Pai, nas tuas mãos entrego o meu espírito' (Lucas 23:46). (5) Jesus morreu ao entardecer (Mateus 27:50; Marcos 15:37; Lucas 23:46; João 19:30). (6) O véu do templo se rasgou (Mateus 27:51; Marcos 15:38; Lucas 23:45). (7) O terremoto e a escuridão (Mateus 27:45,51-54). (8) O centurião confessou: 'Verdadeiramente este homem era o Filho de Deus' (Marcos 15:39). Significados teológicos: (a) A morte de Cristo é o sacrifício definitivo pelos pecados (Hebreus 9:11-14; 10:10-14). (b) O sangue de Cristo purifica os pecados (1 João 1:7). (c) A morte de Cristo é a vitória sobre o pecado e a morte (Colossenses 2:13-15). (d) O véu rasgado simboliza o acesso direto a Deus por meio de Cristo (Hebreus 10:19-22). A teologia reformada enfatiza a expiação vicária (substituição penal): Cristo morreu em nosso lugar.",
            referencias: "Isaías 53:1-12; Salmo 22:1-31; Mateus 27:27-56; Marcos 15:16-41; Lucas 23:26-49; João 19:16-37; Romanos 3:23-26; 2 Coríntios 5:21; Gálatas 3:13; Colossenses 2:13-15; 1 Pedro 2:24; 1 João 1:7; Hebreus 10:19-22"
        },
        {
            termo: "05. O Sepultamento e o Sábado - O Descanso no Túmulo",
            definicao: "Após a morte de Jesus, seu corpo foi sepultado por José de Arimateia (um discípulo secreto) e Nicodemos (João 19:38-42). Detalhes: (1) José pediu o corpo de Jesus a Pilatos (Mateus 27:57-58; Marcos 15:42-43; Lucas 23:50-52; João 19:38). (2) José envolveu o corpo em um lençol limpo e o colocou em seu sepulcro novo, escavado na rocha (Mateus 27:59-60; Marcos 15:46; Lucas 23:53; João 19:40-42). (3) Uma grande pedra foi rolada para a entrada do sepulcro (Mateus 27:60; Marcos 15:46). (4) Maria Madalena e a outra Maria estavam sentadas em frente ao sepulcro (Mateus 27:61). (5) No sábado (dia seguinte), os líderes judeus pediram a Pilatos que guardasse o sepulcro para evitar que os discípulos roubassem o corpo (Mateus 27:62-66). O sepulcro foi selado e guardado por soldados romanos (Mateus 27:65-66). Significados teológicos: (a) O sepultamento confirma a realidade da morte de Jesus (Cristo realmente morreu). (b) O sábado foi um dia de descanso no túmulo (tipologicamente, o descanso de Deus após a criação - Gênesis 2:2-3). (c) O sepulcro vazio na manhã de domingo é a primeira evidência da ressurreição. A teologia reformada afirma a morte real de Cristo (não um desmaio, como em algumas teorias). 'Cristo morreu pelos nossos pecados, segundo as Escrituras, e que foi sepultado' (1 Coríntios 15:3-4).",
            referencias: "Gênesis 2:2-3; Isaías 53:9; Mateus 27:57-66; Marcos 15:42-47; Lucas 23:50-56; João 19:38-42; 1 Coríntios 15:3-4"
        },
        {
            termo: "06. A Ressurreição - A Vitória sobre a Morte (Domingo de Páscoa)",
            definicao: "No domingo de manhã (o terceiro dia após a crucificação), Jesus ressuscitou dos mortos. Eventos: (1) As mulheres (Maria Madalena, Maria mãe de Tiago, Salomé, Joana) foram ao sepulcro para ungir o corpo de Jesus (Mateus 28:1; Marcos 16:1-2; Lucas 24:1; João 20:1). (2) Houve um grande terremoto, e um anjo desceu do céu e removeu a pedra (Mateus 28:2-4). (3) O anjo disse às mulheres: 'Ele não está aqui, porque já ressuscitou, como havia dito' (Mateus 28:5-6). (4) Jesus apareceu a Maria Madalena (João 20:11-18). (5) Jesus apareceu às outras mulheres (Mateus 28:9-10). (6) Os guardas romanos fugiram e relataram o ocorrido (Mateus 28:11-15). (7) Jesus apareceu a Pedro (Lucas 24:34; 1 Coríntios 15:5). (8) Jesus apareceu aos dois discípulos no caminho de Emaús (Lucas 24:13-35). (9) Jesus apareceu aos discípulos reunidos (sem Tomé) no domingo à noite (João 20:19-23). (10) Jesus apareceu aos discípulos (com Tomé) oito dias depois (João 20:24-29). Significados teológicos da ressurreição: (1) Declaração de que Jesus é o Filho de Deus (Romanos 1:4). (2) Vitória sobre o pecado e a morte (Romanos 6:9; 1 Coríntios 15:54-57). (3) Garantia da nossa justificação (Romanos 4:25). (4) Garantia da nossa ressurreição (1 Coríntios 15:20-23). (5) Base da nossa nova vida (Romanos 6:4). (6) Esperança da parusia (Atos 1:11). A teologia reformada afirma a ressurreição corporal como evento histórico, não mito ou símbolo.",
            referencias: "Salmo 16:10; Isaías 53:10-12; Oséias 6:2; Mateus 28:1-20; Marcos 16:1-20; Lucas 24:1-53; João 20:1-29; Atos 1:1-3; Atos 2:22-36; Romanos 1:4; Romanos 4:25; Romanos 6:4-5; 1 Coríntios 15:1-58"
        },
        {
            termo: "07. As Aparições de Jesus Ressurreto (Evidências da Ressurreição)",
            definicao: "Jesus apareceu a muitas testemunhas após sua ressurreição, fornecendo evidências irrefutáveis. Lista completa das aparições (em ordem cronológica): (1) A Maria Madalena (João 20:11-18; Marcos 16:9). (2) Às outras mulheres (Mateus 28:9-10). (3) A Pedro (Lucas 24:34; 1 Coríntios 15:5). (4) Aos dois discípulos no caminho de Emaús (Lucas 24:13-35; Marcos 16:12-13). (5) Aos dez apóstolos (sem Tomé) (João 20:19-23; Lucas 24:36-49; Marcos 16:14). (6) Aos onze apóstolos (com Tomé) (João 20:24-29). (7) A mais de 500 irmãos (1 Coríntios 15:6). (8) A Tiago (1 Coríntios 15:7). (9) Aos apóstolos na Galileia (Mateus 28:16-20). (10) Aos discípulos na pesca milagrosa (João 21:1-25). (11) Na ascensão (Lucas 24:50-53; Atos 1:9-11). (12) A Estêvão (Atos 7:55-56). (13) A Paulo (Atos 9:1-9; 22:6-11; 26:12-18; 1 Coríntios 15:8). (14) A Ananias (Atos 9:10-17). (15) A João em Patmos (Apocalipse 1:12-20). Significados: (a) As aparições confirmam a ressurreição corporal (Jesus come, é tocado, etc.). (b) O número de testemunhas é grande (mais de 500). (c) Muitas testemunhas ainda estavam vivas quando Paulo escreveu (1 Coríntios 15:6), podendo ser consultadas. (d) A transformação dos discípulos (de medrosos a corajosos mártires) é evidência da ressurreição. A teologia reformada vê nas aparições a evidência histórica da ressurreição.",
            referencias: "Mateus 28:9-10; Mateus 28:16-20; Marcos 16:9-20; Lucas 24:13-53; João 20:11-29; João 21:1-25; Atos 1:3; Atos 1:9-11; Atos 7:55-56; Atos 9:1-19; 1 Coríntios 15:3-8; Apocalipse 1:12-20"
        },
        {
            termo: "08. O Significado Teológico da Ressurreição (Romanos 6, 1 Coríntios 15)",
            definicao: "O apóstolo Paulo desenvolve a teologia da ressurreição em Romanos 6 e 1 Coríntios 15. Principais pontos: (1) A ressurreição como fundamento da fé: 'Se Cristo não ressuscitou, é vã a nossa pregação, e também é vã a vossa fé' (1 Coríntios 15:14). (2) A ressurreição como vitória sobre o pecado e a morte: 'O último inimigo que há de ser aniquilado é a morte' (1 Coríntios 15:26). 'Onde está, ó morte, o teu aguilhão? Onde está, ó inferno, a tua vitória?' (1 Coríntios 15:55). (3) A ressurreição como garantia da nossa ressurreição: 'Cristo ressuscitou dos mortos, e foi feito as primícias dos que dormem' (1 Coríntios 15:20). (4) A nova vida em Cristo (Romanos 6:4): 'Assim andemos nós também em novidade de vida'. (5) O batismo como participação na morte e ressurreição de Cristo (Romanos 6:3-5). (6) A certeza da justificação: 'Que foi entregue por nossas ofensas, e ressuscitou para nossa justificação' (Romanos 4:25). (7) A esperança da parusia: 'Porque o Senhor mesmo descerá do céu... e os que morreram em Cristo ressuscitarão primeiro' (1 Tessalonicenses 4:16-17). A teologia reformada vê na ressurreição o centro da fé e da esperança cristã. 'Bendito o Deus e Pai de nosso Senhor Jesus Cristo, que, segundo a sua grande misericórdia, nos gerou de novo para uma viva esperança, pela ressurreição de Jesus Cristo dentre os mortos' (1 Pedro 1:3).",
            referencias: "Romanos 4:25; Romanos 6:1-14; 1 Coríntios 15:1-58; 1 Tessalonicenses 4:13-18; 1 Pedro 1:3-5; Apocalipse 20:11-15; Apocalipse 21:1-5"
        },
        {
            termo: "09. A Celebração da Páscoa na História da Igreja",
            definicao: "A celebração da Páscoa tem uma longa história na igreja cristã. Principais desenvolvimentos: (1) Páscoa no cristianismo primitivo (século I-II): Os cristãos celebravam a ressurreição semanalmente no domingo (Dia do Senhor) e anualmente na Páscoa. (2) Controvérsia sobre a data da Páscoa (século II): Os 'Quartodecimanos' (do grego tessareskaidekatitai - 'os catorze') celebravam a Páscoa no dia 14 de Nisan (a data judaica). A igreja romana celebrava no domingo seguinte. O Concílio de Nicéia (325 d.C.) decidiu que a Páscoa seria celebrada no primeiro domingo após a primeira lua cheia após o equinócio da primavera (hemisfério norte). (3) Páscoa na igreja medieval: Desenvolveu-se a Semana Santa, com liturgias para Domingo de Ramos, Quinta-feira Santa (Ceia do Senhor), Sexta-feira Santa (crucificação), Sábado Santo (sepultamento) e Domingo de Páscoa (ressurreição). (4) Páscoa na Reforma Protestante: Lutero, Calvino e Zwinglio mantiveram a celebração da Páscoa, mas rejeitaram os excessos católicos (relíquias, procissões, veneração da cruz). As igrejas reformadas enfatizaram a pregação da ressurreição e a Ceia do Senhor. (5) Páscoa no evangelicalismo contemporâneo: Cultos especiais no Domingo de Páscoa, com ênfase na ressurreição, cantos e mensagens evangelísticas. A teologia reformada valoriza a celebração da Páscoa como a festa principal do ano litúrgico.",
            referencias: "Atos 20:7; 1 Coríntios 16:2; Apocalipse 1:10; Colossenses 2:16-17; Romanos 14:5-6"
        },
        {
            termo: "10. Hinos e Cânticos da Páscoa",
            definicao: "A Páscoa inspirou alguns dos mais belos hinos da igreja cristã. Hinos tradicionais: (1) 'Cristo, o Senhor, ressurgiu hoje' (Christ the Lord Is Risen Today) - Charles Wesley (1739). Texto (excerto): 'Cristo, o Senhor, ressurgiu hoje, aleluia! Filhos dos homens, alegrai-vos, aleluia! Ele morreu, mas ressurgiu, aleluia! E para sempre ele vive, aleluia!' (2) 'Jesus Cristo ressurgiu' (Jesus Christ Is Risen Today) - tradução do latim 'Surrexit Christus hodie' (séc. XIV). (3) 'Aleluia, Aleluia! Cristo venceu a morte' (Alleluia! Alleluia! Hearts to Heaven) - Christopher Wordsworth (1862). (4) 'Viva! Viva! Jesus ressurgiu' (Low in the Grave He Lay) - Robert Lowry (1874). (5) 'Ele vive, eu sei' (He Lives) - Alfred H. Ackley (1933). Hinos contemporâneos: (1) 'In Christ Alone' (Somente em Cristo) - Keith Getty e Stuart Townend (2001). (2) 'Christ Is Risen' (Cristo Ressurgiu) - Matt Maher (2009). (3) 'Living Hope' (Viva Esperança) - Phil Wickham (2018). A teologia reformada valoriza os hinos pascais como meio de celebrar a ressurreição e ensinar a doutrina. 'Falando entre vós com salmos, e hinos, e cânticos espirituais' (Efésios 5:19). 'A palavra de Cristo habite em vós abundantemente... cantando com graça em vossos corações ao Senhor' (Colossenses 3:16).",
            referencias: "Êxodo 15:1-21; Salmo 118:1-29; Salmo 150:1-6; Efésios 5:19; Colossenses 3:16; Apocalipse 5:9-14; Apocalipse 19:1-8"
        },
        {
            termo: "11. Meditações e Sermões para a Páscoa",
            definicao: "A Páscoa é uma oportunidade para meditação e pregação sobre a ressurreição de Cristo. Esboços de sermões para o Domingo de Páscoa: (1) 'Ele não está aqui, porque já ressuscitou' (Mateus 28:6). Esboço: (a) O sepulcro vazio (evidência histórica). (b) As aparições (testemunho ocular). (c) A implicação para nós (esperança da ressurreição). (2) 'Cristo, nossa Páscoa, foi sacrificado por nós' (1 Coríntios 5:7). Esboço: (a) O cordeiro pascal (tipo). (b) O Cordeiro de Deus (cumprimento). (c) A nova vida em Cristo (aplicação). (3) 'Se Cristo não ressuscitou, é vã a nossa fé' (1 Coríntios 15:14-17). Esboço: (a) A centralidade da ressurreição. (b) As evidências históricas. (c) A esperança da nossa ressurreição. (4) 'Bendito o Deus... que nos gerou de novo para uma viva esperança, pela ressurreição de Jesus Cristo' (1 Pedro 1:3-4). Esboço: (a) A ressurreição como causa da nossa nova vida. (b) A esperança viva. (c) A herança incorruptível. Meditações diárias para a semana da Páscoa: Segunda-feira: O sepulcro vazio. Terça-feira: A aparição a Maria Madalena. Quarta-feira: O caminho de Emaús. Quinta-feira: A aparição aos discípulos. Sexta-feira: A fé de Tomé. Sábado: A ascensão. Domingo: A esperança da parusia. A teologia reformada incentiva a pregação cristocêntrica e a meditação na ressurreição.",
            referencias: "Mateus 28:1-20; Lucas 24:1-53; João 20:1-31; Atos 2:22-36; 1 Coríntios 15:1-58; 1 Pedro 1:3-5"
        },
        {
            termo: "12. A Páscoa e a Esperança Escatológica",
            definicao: "A Páscoa não é apenas uma celebração do passado, mas uma antecipação do futuro. A ressurreição de Cristo é a garantia da ressurreição geral e da nova criação. 'Porque, assim como todos morrem em Adão, assim também todos serão vivificados em Cristo. Cada um, porém, na sua ordem: Cristo as primícias; depois os que são de Cristo, na sua vinda' (1 Coríntios 15:22-23). Conexões escatológicas: (1) A parusia (segunda vinda): 'Porque o Senhor mesmo descerá do céu... e os que morreram em Cristo ressuscitarão primeiro' (1 Tessalonicenses 4:16-17). (2) O juízo final: 'Ele ordenou um dia em que há de julgar o mundo com justiça, por meio do varão que para isso ordenou, dando a todos a certeza disso, ressuscitando-o dos mortos' (Atos 17:31). (3) A nova criação: 'E vi um novo céu e uma nova terra' (Apocalipse 21:1). (4) A morte como inimigo vencido: 'O último inimigo que há de ser aniquilado é a morte' (1 Coríntios 15:26). (5) A vida eterna: 'Para que todo aquele que nele crê não pereça, mas tenha a vida eterna' (João 3:16). A esperança pascal transforma a vida do crente: (a) Não tememos a morte (Filipenses 1:21). (b) Vivemos em santidade (1 João 3:3). (c) Servimos ao Senhor com alegria (1 Coríntios 15:58). (d) Aguardamos a volta de Cristo (Tito 2:13). A teologia reformada enfatiza a esperança escatológica como âncora da alma (Hebreus 6:19). 'Aguardando a bem-aventurada esperança e o aparecimento da glória do grande Deus e nosso Salvador Jesus Cristo' (Tito 2:13).",
            referencias: "João 3:16; Atos 17:31; Romanos 8:18-25; 1 Coríntios 15:20-28; 1 Coríntios 15:50-58; 1 Tessalonicenses 4:13-18; Tito 2:13; Hebreus 6:19-20; 2 Pedro 3:10-13; 1 João 3:2-3; Apocalipse 21-22"
        },
        {
            termo: "13. Síntese: Cristo Vive! Aleluia!",
            definicao: "A Páscoa é a celebração da vitória de Cristo sobre o pecado, a morte e o inferno. 'Cristo ressuscitou dos mortos, e foi feito as primícias dos que dormem' (1 Coríntios 15:20). A ressurreição é: (1) A confirmação da divindade de Cristo (Romanos 1:4). (2) A vitória sobre o pecado e a morte (Romanos 6:9; 1 Coríntios 15:54-57). (3) A garantia da nossa justificação (Romanos 4:25). (4) A garantia da nossa ressurreição (1 Coríntios 15:20-23). (5) A base da nossa nova vida (Romanos 6:4). (6) A esperança da parusia (Atos 1:11). (7) A fonte da nossa alegria (João 16:22). (8) A razão da nossa adoração (Apocalipse 5:11-14). A teologia reformada celebra a Páscoa como a festa central do ano litúrgico. 'Cristo, nossa Páscoa, foi sacrificado por nós' (1 Coríntios 5:7). Que a igreja proclame: 'Cristo vive! Aleluia!' 'E, se Cristo não ressuscitou, é vã a vossa fé' (1 Coríntios 15:14). 'Mas, agora, Cristo ressuscitou dentre os mortos' (1 Coríntios 15:20). 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36). Soli Deo Gloria!",
            referencias: "Romanos 11:36; 1 Coríntios 15:1-58; Filipenses 3:10-11; Colossenses 3:1-4; 1 Pedro 1:3-5; Apocalipse 1:17-18; Apocalipse 5:11-14"
        }
    ]
};