// volume/volume-56.js
window.LIVRO_DATA = {
    nome: "Volume LVI",
    dados: [
        {
            termo: "01. Introdução: Cristo é o Senhor da Economia",
            definicao: "A economia (produção, distribuição e consumo de bens e serviços) não está fora do senhorio de Cristo. 'Porque dele e por ele, e para ele, são todas as coisas' (Romanos 11:36). 'Tudo o que fizerdes, por palavra ou por obra, fazei-o em nome do Senhor Jesus' (Colossenses 3:17). A teologia reformada afirma que o trabalho é uma ordem da criação (Gênesis 2:15), que a riqueza pode ser usada para o bem ou para o mal, que os pobres devem ser cuidados, e que o dízimo e as ofertas são expressões de gratidão a Cristo. Este volume explora a relação entre cristologia e economia: o trabalho, a pobreza, a riqueza, a mordomia, o dízimo, a justiça econômica, e a esperança escatológica (a nova criação). 'Não ajunteis tesouros na terra' (Mateus 6:19). 'Bem-aventurados vós, os pobres, porque vosso é o reino de Deus' (Lucas 6:20).",
            referencias: "Gênesis 2:15; Mateus 6:19-21; Lucas 6:20; Romanos 11:36; Colossenses 3:17; 1 Timóteo 6:6-10; 1 Timóteo 6:17-19"
        },
        {
            termo: "02. Cristo e o Trabalho - O Valor do Trabalho na Visão Cristã",
            definicao: "O trabalho foi instituído por Deus antes da queda (Gênesis 2:15). Após a queda, o trabalho tornou-se difícil (Gênesis 3:17-19), mas continua sendo uma ordem divina. O apóstolo Paulo ensina: 'Se alguém não quer trabalhar, também não coma' (2 Tessalonicenses 3:10). 'Aqueles que trabalham, fazendo com as mãos o que é bom, para que tenham que repartir com o que tiver necessidade' (Efésios 4:28). Jesus trabalhou como carpinteiro (Marcos 6:3). O trabalho tem valor em si mesmo, não apenas como meio de sustento. Princípios cristãos do trabalho: (1) O trabalho é uma ordem de Deus (Gênesis 2:15). (2) O trabalho é para a glória de Deus (1 Coríndios 10:31). (3) O trabalho deve ser feito com excelência (Colossenses 3:23). (4) O trabalho deve ser honesto (não enganar). (5) O trabalho deve ser para o bem comum (Efésios 4:28). (6) O descanso é ordenado (Êxodo 20:8-11; Marcos 2:27). (7) O trabalho não é um fim em si mesmo (não idolatria). A teologia reformada (Calvino, Kuyper) valoriza o trabalho como vocação (chamado de Deus). 'O que furtava, não furte mais; antes trabalhe' (Efésios 4:28). 'Tudo o que fizerdes, fazei-o de coração, como ao Senhor' (Colossenses 3:23).",
            referencias: "Gênesis 2:15; Gênesis 3:17-19; Êxodo 20:8-11; Marcos 6:3; Marcos 2:27; Efésios 4:28; 2 Tessalonicenses 3:10; Colossenses 3:23"
        },
        {
            termo: "03. A Pobreza na Bíblia - Os Pobres e o Cuidado de Deus",
            definicao: "A Bíblia mostra a preocupação de Deus com os pobres. 'Bem-aventurados vós, os pobres, porque vosso é o reino de Deus' (Lucas 6:20). 'A religião pura e imaculada para com Deus, o Pai, é esta: visitar os órfãos e as viúvas nas suas tribulações' (Tiago 1:27). Causas da pobreza: (1) Preguiça (Provérbios 6:6-11). (2) Injustiça social (Provérbios 13:23). (3) Catástrofes naturais. (4) Doença. (5) Exploração. (6) Desastres econômicos. (7) Pecado pessoal (Provérbios 21:17). A Bíblia condena a opressão dos pobres: 'Não oprimirás o teu próximo, nem o roubarás' (Levítico 19:13). A Bíblia ordena o cuidado dos pobres: 'Abre a tua mão ao teu irmão, ao teu necessitado' (Deuteronômio 15:11). A teologia reformada enfatiza a responsabilidade da igreja e do Estado para com os pobres. A pobreza não é virtude em si (os pobres também pecam), mas Deus tem compaixão dos pobres. 'O que oprime ao pobre insulta ao seu Criador' (Provérbios 14:31). 'Pois nunca faltará pobre na terra' (Deuteronômio 15:11).",
            referencias: "Levítico 19:9-10; Deuteronômio 15:7-11; Provérbios 6:6-11; Provérbios 14:31; Provérbios 21:17; Lucas 6:20; Tiago 1:27; Tiago 2:5-6"
        },
        {
            termo: "04. A Riqueza na Bíblia - Perigos e Bênçãos",
            definicao: "A riqueza em si não é pecado. Abraão era rico (Gênesis 13:2). Jó era rico (Jó 1:3). José de Arimateia era rico (Mateus 27:57). No entanto, a Bíblia alerta sobre os perigos da riqueza: (1) Amor ao dinheiro é raiz de todos os males (1 Timóteo 6:10). (2) A riqueza pode levar à confiança em si mesmo, não em Deus (Provérbios 18:11). (3) A riqueza pode levar à idolatria (Mateus 6:24). (4) A riqueza pode ser um obstáculo ao reino (Mateus 19:24). (5) A riqueza pode levar à injustiça (Tiago 5:1-6). Bênçãos da riqueza: (1) Pode ser usada para o bem (Provérbios 19:17). (2) Pode ser usada para a obra de Deus (Malaquias 3:8-10). (3) Pode ser usada para ajudar os pobres (Efésios 4:28). Princípios para os ricos: (a) Não confiar na riqueza (1 Timóteo 6:17). (b) Ser generoso (1 Timóteo 6:18). (c) Ser justo (não oprimir). (d) Honrar a Deus com os bens (Provérbios 3:9). (e) Reconhecer que tudo pertence a Deus (Salmo 24:1). A teologia reformada rejeita a teologia da prosperidade (riqueza como sinal de bênção divina) e o ascetismo (pobreza como virtude). 'Não vos conformeis com este mundo' (Romanos 12:2). 'Manda aos ricos deste mundo que não sejam altivos, nem ponham a esperança na incerteza das riquezas, mas em Deus' (1 Timóteo 6:17).",
            referencias: "Gênesis 13:2; Jó 1:3; Salmo 24:1; Provérbios 3:9; Provérbios 18:11; Provérbios 19:17; Mateus 6:24; Mateus 19:24; 1 Timóteo 6:6-10; 1 Timóteo 6:17-19; Tiago 5:1-6"
        },
        {
            termo: "05. Mordomia Cristã - Tudo Pertence a Cristo",
            definicao: "Mordomia (stewardship) é a administração dos bens de Deus. 'Ao Senhor pertence a terra e a sua plenitude, o mundo e aqueles que nele habitam' (Salmo 24:1). 'Tudo o que existe debaixo do céu é meu' (Jó 41:11). Princípios da mordomia cristã: (1) Deus é o proprietário de tudo. (2) Nós somos mordomos (administradores). (3) Devemos usar os recursos para a glória de Deus (1 Coríndios 10:31). (4) Devemos prestar contas a Deus (Mateus 25:14-30). (5) Devemos usar os recursos para o bem comum (Gálatas 6:10). (6) Devemos evitar o desperdício (João 6:12). (7) Devemos planejar o futuro (Provérbios 6:6-8). Aplicações da mordomia: (a) Finanças: orçamento, poupança, investimento ético. (b) Propriedade: cuidar da terra (mordomia ambiental). (c) Tempo: usar o tempo para Deus. (d) Talentos: usar dons para o Reino. (e) Relacionamentos: investir nas pessoas. 'Aquele que é fiel no mínimo também é fiel no muito' (Lucas 16:10). 'Sede, pois, imitadores de Deus' (Efésios 5:1).",
            referencias: "Salmo 24:1; Jó 41:11; Provérbios 6:6-8; Mateus 25:14-30; Lucas 16:10-13; 1 Coríndios 10:31; Gálatas 6:10; Efésios 5:1"
        },
        {
            termo: "06. O Dízimo e as Ofertas - Apoiando a Obra de Cristo",
            definicao: "O dízimo (décima parte) era exigido no Antigo Testamento (Levítico 27:30; Malaquias 3:8-10). O Novo Testamento não exige o dízimo (a lei cerimonial foi cumprida em Cristo), mas ensina a generosidade. 'Cada um dê segundo o propósito do seu coração; não com tristeza, ou por necessidade; porque Deus ama ao que dá com alegria' (2 Coríndios 9:7). 'Naquilo que, pois, tiveres, dá esmola' (Lucas 11:41). Princípios do dar cristão: (1) Dar generosamente (2 Coríndios 8:1-5). (2) Dar sacrificialmente (Marcos 12:41-44). (3) Dar alegremente (2 Coríndios 9:7). (4) Dar sistematicamente (1 Coríndios 16:2). (5) Dar em proporção da renda (1 Coríndios 16:2). (6) Dar para a obra do Senhor (missões, igreja, pobres). O dízimo é um bom ponto de partida (muitos cristãos dízimam como princípio de gratidão). Ofertas adicionais são encorajadas. A teologia reformada ensina que o dar é uma expressão de gratidão a Cristo, não uma forma de ganhar mérito. 'Honra ao Senhor com os teus bens, e com a primeira parte de todos os teus ganhos' (Provérbios 3:9). 'O que semeia pouco, pouco também ceifará; e o que semeia em abundância, em abundância também ceifará' (2 Coríndios 9:6).",
            referencias: "Levítico 27:30; Malaquias 3:8-10; Mateus 23:23; Marcos 12:41-44; Lucas 11:41; 1 Coríndios 16:1-2; 2 Coríndios 8:1-5; 2 Coríndios 9:6-7"
        },
        {
            termo: "07. Justiça Econômica - Salários Justos e Condições Dignas",
            definicao: "A Bíblia ensina a justiça econômica: salários justos, tratamento digno dos trabalhadores, e oposição à exploração. 'Não oprimirás o teu próximo, nem o roubarás; a paga do diarista não ficará contigo até pela manhã' (Levítico 19:13). 'Eis que o salário dos trabalhadores que ceifaram as vossas terras e que por vós foi diminuído clama' (Tiago 5:4). Princípios de justiça econômica: (1) Salário justo (o suficiente para viver com dignidade). (2) Condições de trabalho seguras. (3) Descanso semanal (Êxodo 20:8-11). (4) Direito dos trabalhadores de se organizar (sindicatos - princípio, não explícito). (5) Oposição à exploração (escravidão, trabalho infantil). (6) Responsabilidade do empregador (Provérbios 29:7). (7) Responsabilidade do trabalhador (trabalhar com diligência). A teologia reformada (Kuyper) desenvolveu a doutrina da 'soberania das esferas': empregadores e empregados têm direitos e responsabilidades distintos. 'O que trabalha com as próprias mãos, ganha o pão' (Provérbios 12:11). 'O trabalhador é digno do seu salário' (Lucas 10:7). 'Bem-aventurado o que atende ao pobre' (Provérbios 14:21).",
            referencias: "Êxodo 20:8-11; Levítico 19:13; Deuteronômio 24:14-15; Provérbios 12:11; Provérbios 14:21; Provérbios 29:7; Lucas 10:7; Tiago 5:1-4"
        },
        {
            termo: "08. A Igreja e os Pobres - Diaconia e Ação Social",
            definicao: "A igreja primitiva cuidava dos pobres (Atos 2:44-45; 4:32-35). Foram escolhidos diáconos para servir às mesas (Atos 6:1-6). Paulo coletou ofertas para os pobres de Jerusalém (Romanos 15:25-28; 1 Coríndios 16:1-4). Ministérios de diaconia: (1) Socorro emergencial (comida, roupas, abrigo). (2) Aconselhamento financeiro. (3) Auxílio médico. (4) Educação. (5) Capacitação profissional. (6) Microcrédito. (7) Parceria com organizações de caridade. A teologia reformada (Kuyper, Bavinck) enfatiza o cuidado dos pobres como parte da missão integral da igreja (evangelismo + ação social). A igreja não deve substituir o Estado, mas deve suplementar. 'A religião pura e imaculada... é esta: visitar os órfãos e as viúvas nas suas tribulações' (Tiago 1:27). 'Repartia com todos, segundo a necessidade de cada um' (Atos 2:45). 'Não sejamos vagarosos em cuidar dos necessitados' (Gálatas 6:10).",
            referencias: "Atos 2:44-45; Atos 4:32-35; Atos 6:1-6; Romanos 15:25-28; 1 Coríndios 16:1-4; Gálatas 6:10; Tiago 1:27"
        },
        {
            termo: "09. A Ética do Consumo - Simplicidade, Moderação, Gratidão",
            definicao: "A Bíblia ensina a moderação e a simplicidade, não o consumismo desenfreado. 'E disse-lhes: Acautelai-vos e guardai-vos da avareza; porque a vida de qualquer não consiste na abundância do que possui' (Lucas 12:15). 'Tendo, porém, sustento e com que nos cobrirmos, estejamos contentes' (1 Timóteo 6:8). Princípios de consumo cristão: (1) Necessidades vs. desejos (distinguir). (2) Evitar dívidas desnecessárias (Provérbios 22:7). (3) Consumir com moderação (Filipenses 4:5). (4) Evitar desperdício (João 6:12). (5) Consumir eticamente (evitar produtos de exploração). (6) Consumir com gratidão (1 Timóteo 4:4-5). (7) Consumir com generosidade (partilhar com os pobres). (8) Evitar a idolatria (coisas materiais como deuses). A teologia reformada rejeita tanto o ascetismo (negação da criação) quanto o consumismo (idolatria da criação). 'Todas as coisas me são lícitas, mas nem todas as coisas convêm' (1 Coríndios 6:12). 'Portanto, quer comais quer bebais... fazei tudo para glória de Deus' (1 Coríndios 10:31).",
            referencias: "Provérbios 22:7; João 6:12; Lucas 12:15; Filipenses 4:5; 1 Timóteo 4:4-5; 1 Timóteo 6:6-8; 1 Coríndios 6:12"
        },
        {
            termo: "10. A Economia e o Pecado - Avareza, Ganância, Corrupção",
            definicao: "O pecado afeta a economia: avareza, ganância, corrupção, exploração, fraude, roubo, sonegação de impostos. A Bíblia condena: (1) Avareza: 'a raiz de todos os males é o amor ao dinheiro' (1 Timóteo 6:10). (2) Ganância: 'Não defraudeis' (Levítico 19:13). (3) Corrupção: 'suborno não aceitarás' (Êxodo 23:8). (4) Exploração: 'Ai dos que ajuntam casa a casa' (Isaías 5:8). (5) Fraude: 'balança falsa é abominação ao Senhor' (Provérbios 11:1). (6) Roubo: 'Não furtarás' (Êxodo 20:15). (7) Sonegação de impostos: 'Dai a César o que é de César' (Mateus 22:21). A teologia reformada afirma que a redenção em Cristo transforma a relação do crente com o dinheiro: (a) Arrependimento da avareza. (b) Generosidade em Cristo. (c) Honestidade nos negócios. (d) Justiça nas relações econômicas. (e) Contentamento (Filipenses 4:11). 'Vós não podeis servir a Deus e a Mamom' (Mateus 6:24). 'O que furtava, não furte mais' (Efésios 4:28).",
            referencias: "Êxodo 20:15; Êxodo 23:8; Levítico 19:13; Provérbios 11:1; Isaías 5:8; Mateus 6:24; Mateus 22:21; Efésios 4:28; 1 Timóteo 6:10; Filipenses 4:11"
        },
        {
            termo: "11. Escatologia Econômica - A Nova Jerusalém e a Economia Redimida",
            definicao: "A nova criação (novos céus e nova terra) terá uma economia redimida. 'E não haverá mais fome' (Apocalipse 7:16). 'E trarão a glória e honra das nações para ela' (Apocalipse 21:26). Características da economia redimida: (1) Ausência de pobreza (Apocalipse 21:4). (2) Ausência de exploração (não haverá mais opressão). (3) Trabalho significativo (Apocalipse 22:3: 'os seus servos o servirão'). (4) Justiça perfeita. (5) Abundância (não escassez). (6) Comunhão (partilha). (7) Glória de Deus como centro. A esperança escatológica transforma a economia presente: (a) Não idolatramos a economia (passageira). (b) Usamos os recursos para o Reino, não para acumular (Mateus 6:19-21). (c) Trabalhamos para a glória de Deus, não para o lucro apenas. (d) Cuidamos dos pobres como antecipação da nova criação. (e) Buscamos justiça econômica como sinal do Reino. 'Porque a nossa leve e momentânea tribulação produz para nós um peso eterno de glória mui excelente' (2 Coríndios 4:17). 'Mas buscai primeiro o reino de Deus e a sua justiça' (Mateus 6:33).",
            referencias: "Isaías 65:17-25; Mateus 6:19-21; Mateus 6:33; Apocalipse 7:16; Apocalipse 21:1-4; Apocalipse 21:26; Apocalipse 22:3"
        },
        {
            termo: "12. Conselhos Práticos para a Vida Financeira Cristã",
            definicao: "Conselhos práticos para a vida financeira baseados na Bíblia: (1) Orçamento: planeje seus gastos (Provérbios 27:23-24). (2) Poupança: guarde para emergências (Provérbios 6:6-8). (3) Evite dívidas: 'o devedor é servo do credor' (Provérbios 22:7). (4) Viva dentro de suas posses: não gaste mais do que ganha. (5) Dízimo e ofertas: doe regularmente (1 Coríndios 16:2). (6) Ajuda aos pobres: reserve uma parte para caridade (Efésios 4:28). (7) Invista com sabedoria: diversifique, evite riscos excessivos. (8) Testamento: planeje a herança (Provérbios 13:22). (9) Seguro: proteja-se contra catástrofes. (10) Contentamento: 'aprendi a contentar-me com o que tenho' (Filipenses 4:11). (11) Oração: ore antes de decisões financeiras. (12) Aconselhamento: busque conselho sábio (Provérbios 15:22). (13) Generosidade: seja conhecido por dar (Atos 20:35). (14) Integridade: não engane nos negócios (Provérbios 20:10). 'O que ajunta no verão é filho prudente' (Provérbios 10:5). 'Melhor é o pouco com o temor do Senhor do que um grande tesouro com inquietação' (Provérbios 15:16).",
            referencias: "Provérbios 6:6-8; Provérbios 10:5; Provérbios 13:22; Provérbios 15:16; Provérbios 15:22; Provérbios 22:7; Provérbios 27:23-24; Atos 20:35; Filipenses 4:11"
        },
        {
            termo: "13. Síntese: Cristo, o Senhor da Economia",
            definicao: "Cristo é o Senhor da economia. 'Porque dele e por ele, e para ele, são todas as coisas' (Romanos 11:36). Resumo da economia cristocêntrica: (1) O trabalho é uma ordem de Deus (Gênesis 2:15). (2) O trabalho deve ser para a glória de Deus (1 Coríndios 10:31). (3) A pobreza deve ser aliviada (Tiago 1:27). (4) A riqueza pode ser usada para o bem (1 Timóteo 6:17-19). (5) A mordomia reconhece que tudo pertence a Deus (Salmo 24:1). (6) O dízimo e as ofertas sustentam a obra de Cristo. (7) A justiça econômica exige salários justos (Levítico 19:13). (8) A igreja deve cuidar dos pobres (Atos 6:1-6). (9) O consumo deve ser moderado e grato (1 Timóteo 6:6-8). (10) O pecado econômico (avareza, ganância) deve ser combatido (Mateus 6:24). (11) A esperança escatológica transforma a economia presente (Mateus 6:33). (12) A vida financeira cristã deve ser prudente e generosa. 'Não vos conformeis com este mundo, mas transformai-vos pela renovação do vosso entendimento' (Romanos 12:2). 'E tudo quanto fizerdes, por palavra ou por obra, fazei-o em nome do Senhor Jesus' (Colossenses 3:17). Soli Deo Gloria!",
            referencias: "Romanos 11:36; Romanos 12:2; 1 Coríndios 10:31; Colossenses 3:17; 1 Timóteo 6:6-10; 1 Timóteo 6:17-19; Tiago 1:27"
        }
    ]
};