// volume/volume-58.js
window.LIVRO_DATA = {
    nome: "Volume LVIII",
    dados: [
        {
            termo: "01. Introdução: A Unicidade de Cristo no Pluralismo Religioso",
            definicao: "O mundo contemporâneo é marcado pelo pluralismo religioso: múltiplas religiões coexistem (cristianismo, judaísmo, islamismo, hinduísmo, budismo, etc.). A teologia reformada afirma a unicidade e exclusividade de Jesus Cristo como o único Salvador. 'E em nenhum outro há salvação, porque também debaixo do céu nenhum outro nome há, dado entre os homens, pelo qual devamos ser salvos' (Atos 4:12). 'Eu sou o caminho, e a verdade, e a vida; ninguém vem ao Pai senão por mim' (João 14:6). Este volume explora o diálogo inter-religioso a partir de uma perspectiva cristocêntrica: (1) A posição exclusivista (só Cristo salva). (2) A posição inclusivista (Cristo salva, mas sem conhecimento explícito). (3) A posição pluralista (múltiplos caminhos). (4) Diálogo com o judaísmo (Jesus como Messias). (5) Diálogo com o islamismo (Jesus no Alcorão). (6) Diálogo com o hinduísmo (Cristo e os avatares). (7) Diálogo com o budismo (Cristo e o iluminismo). (8) Diálogo com religiões africanas e indígenas. A teologia reformada mantém o exclusivismo: somente Cristo salva, e a fé explícita em Cristo é necessária (Romanos 10:9-10). 'Porque a Escritura diz: Todo aquele que nele crer não será confundido' (Romanos 10:11).",
            referencias: "João 14:6; Atos 4:12; Romanos 10:9-13; 1 Timóteo 2:5; 1 João 2:23; 1 João 5:11-12"
        },
        {
            termo: "02. As Três Posições Teológicas - Exclusivismo, Inclusivismo, Pluralismo",
            definicao: "Três posições principais sobre o destino dos não-cristãos: (1) Exclusivismo (reformado): Somente aqueles que explicitamente creem em Cristo são salvos. 'Quem crê no Filho tem a vida eterna; quem não crê no Filho não verá a vida' (João 3:36). 'Se não crerdes que eu sou, morrereis em vossos pecados' (João 8:24). (2) Inclusivismo (católico, evangélico liberal): Cristo salva, mas a fé explícita pode não ser necessária (ex.: 'cristãos anônimos' de Karl Rahner). Base: 'Porque, quando os gentios, que não têm lei, fazem naturalmente as coisas que são da lei... estes são a lei para si mesmos' (Romanos 2:14-15). (3) Pluralismo (John Hick, Paul Knitter): Jesus é um caminho entre muitos. Base: 'Há muitas moradas na casa de meu Pai' (João 14:2) - interpretado erroneamente. A teologia reformada (Calvino, Turretin, Bavinck) defende o exclusivismo. 'Pela fé, Enoque foi trasladado' (Hebreus 11:5) - a fé é necessária. 'Sem fé é impossível agradar-lhe' (Hebreus 11:6). 'Quem tem o Filho tem a vida; quem não tem o Filho de Deus não tem a vida' (1 João 5:12).",
            referencias: "João 3:36; João 8:24; Romanos 2:14-15; 1 Coríndios 1:18; Gálatas 1:8-9; Hebreus 11:6; 1 João 5:11-12"
        },
        {
            termo: "03. Diálogo com o Judaísmo - Jesus é o Messias Prometido",
            definicao: "O judaísmo rabínico rejeita Jesus como o Messias. Pontos de diálogo: (1) Jesus cumpriu as profecias messiânicas (Isaías 7:14; 9:6-7; 53; Miqueias 5:2; Zacarias 9:9; Salmo 22; 110). (2) Jesus é descendente de Davi (Mateus 1:1-17; Lucas 3:23-38). (3) Jesus realizou milagres que confirmam sua messianidade (João 20:30-31). (4) Jesus ressuscitou dos mortos (1 Coríndios 15:3-8). (5) O judaísmo espera um Messias político; Jesus veio como Messias espiritual. (6) A nova aliança (Jeremias 31:31-34) foi inaugurada por Jesus (Lucas 22:20). Objeções judaicas e respostas: (a) 'O Messias traria paz mundial' (Isaías 2:4) - respondida: a paz será na segunda vinda. (b) 'O Messias reconstruiria o templo' (Ezequiel 40-48) - respondida: Jesus é o templo (João 2:19-21). (c) 'Jesus não cumpriu as profecias' - respondida: muitas foram cumpridas; as restantes serão cumpridas na parusia. A teologia reformada rejeita o judaísmo como religião que rejeita o Messias. 'Ele veio para o que era seu, e os seus não o receberam' (João 1:11). 'Agora, porém, sem a lei, se manifestou a justiça de Deus' (Romanos 3:21).",
            referencias: "Isaías 53; Jeremias 31:31-34; Zacarias 9:9; Malaquias 3:1; Mateus 1:1-17; Lucas 24:27; João 1:11; Romanos 9:30-33; Romanos 10:1-4; Romanos 11:1-36"
        },
        {
            termo: "04. Diálogo com o Islamismo - Jesus no Alcorão vs. Jesus na Bíblia",
            definicao: "O Islã (muçulmanos) rejeita a divindade de Cristo, a crucificação e a ressurreição. Jesus no Alcorão: (1) Jesus (Isa) é um profeta (como Maomé), não Deus. (2) Jesus não foi crucificado (Alcorão 4:157): 'Não o mataram, nem o crucificaram, mas parecia-lhes que sim'. (3) Jesus foi elevado ao céu vivo (não morreu). (4) Jesus é chamado 'Messias' (Al-Masih), 'Filho de Maria' (Ibn Maryam), 'Espírito de Deus' (Ruh Allah), 'Verbo de Deus' (Kalimat Allah). (5) Jesus voltará no fim dos tempos para matar o Anticristo (Dajjal) e converter o mundo ao Islã. Contradições com a Bíblia: (a) A Bíblia ensina que Jesus é Deus (João 1:1,14; 20:28; Romanos 9:5; Tito 2:13). (b) A Bíblia ensina que Jesus foi crucificado (Mateus 27:32-56; Marcos 15:21-41; Lucas 23:26-49; João 19:16-37). (c) A Bíblia ensina que Jesus ressuscitou (1 Coríndios 15:3-8). (d) A Bíblia é anterior ao Alcorão (NT: séc. I; Alcorão: séc. VII). (e) O Alcorão contradiz a evidência histórica (a crucificação é atestada por fontes cristãs e não cristãs, ex.: Tácito). A teologia reformada rejeita o Islã como religião falsa (Gálatas 1:8-9), mas defende o diálogo respeitoso e o testemunho. 'Ainda que nós ou um anjo do céu vos anuncie outro evangelho além do que já vos temos anunciado, seja anátema' (Gálatas 1:8).",
            referencias: "João 1:1-14; João 20:28; Atos 4:12; Romanos 9:5; Tito 2:13; Gálatas 1:8-9; 1 Timóteo 2:5; 1 João 4:2-3"
        },
        {
            termo: "05. Diálogo com o Hinduísmo - Cristo e os Avatares",
            definicao: "O hinduísmo é uma família de religiões originárias da Índia, com crenças como reencarnação (samsara), carma, e avatares (encarnações de deuses, especialmente Vishnu). Pontos de diálogo: (1) Avatares hindus (Krishna, Rama) são diferentes de Cristo: (a) Avatares são múltiplos; Cristo é único. (b) Avatares são manifestações de Vishnu; Cristo é o Filho de Deus, consubstancial ao Pai. (c) A encarnação de Cristo é uma vez por todas (Hebreus 9:28); avatares são múltiplos. (2) A salvação no hinduísmo é por obras (karma, reencarnação); no cristianismo é pela graça mediante a fé (Efésios 2:8-9). (3) A ressurreição de Cristo é única; a reencarnação é repetitiva. (4) Cristo é o único caminho (João 14:6); o hinduísmo é pluralista ('muitos caminhos'). (5) Cristãos hindus (convertidos) testemunham que Cristo é superior. A teologia reformada afirma: (a) O hinduísmo é uma religião falsa (não oferece salvação). (b) Cristo é o único Salvador (Atos 4:12). (c) O diálogo deve incluir testemunho claro do evangelho. (d) Respeito pelos hindus como pessoas, mas não pela religião. 'Aquele que crê no Filho tem a vida eterna; mas aquele que não crê no Filho não verá a vida' (João 3:36). 'Nem há salvação em nenhum outro' (Atos 4:12).",
            referencias: "João 1:14; João 14:6; Atos 4:12; Romanos 6:23; Efésios 2:8-9; Hebreus 9:27-28; 1 João 5:11-12"
        },
        {
            termo: "06. Diálogo com o Budismo - Cristo e o Nirvana",
            definicao: "O budismo (fundado por Sidarta Gautama, o Buda, c. 563-483 a.C.) ensina o caminho para o nirvana (extinção do desejo) através do Nobre Caminho Óctuplo. Não há Deus pessoal no budismo (embora algumas escolas tenham divindades). Pontos de diálogo: (1) Buda não é Deus; Cristo é Deus (João 1:1). (2) Buda é um modelo humano; Cristo é o Deus-homem. (3) O budismo ensina a aniquilação do ego; o cristianismo ensina a ressurreição do corpo e a vida eterna com Deus. (4) O budismo é uma religião sem salvação pela graça (é baseada em esforço humano). (5) O budismo não tem um Salvador que morre pelos pecados. (6) O nirvana é vago (extinção); o céu é comunhão com Deus. A teologia reformada afirma: (a) O budismo é uma religião falsa (não oferece salvação). (b) Cristo é o único Salvador (João 14:6; Atos 4:12). (c) O diálogo deve testemunhar de Cristo. (d) O cristianismo oferece esperança real (ressurreição), não aniquilação. 'E esta é a vida eterna: que te conheçam, a ti só, por único Deus verdadeiro, e a Jesus Cristo, a quem enviaste' (João 17:3). 'Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito' (João 3:16).",
            referencias: "João 1:1-14; João 3:16; João 14:6; João 17:3; Atos 4:12; Romanos 6:23; 1 Coríndios 15:1-58"
        },
        {
            termo: "07. Diálogo com Religiões Africanas e Indígenas",
            definicao: "Religiões africanas e indígenas são geralmente animistas (crença em espíritos, ancestrais, forças da natureza). Pontos de diálogo: (1) Cristianismo também reconhece o mundo espiritual (anjos, demônios, Deus). (2) O sacrifício de Cristo é superior aos sacrifícios animistas (Hebreus 9:11-14). (3) Cristo venceu os poderes espirituais do mal (Colossenses 2:15). (4) O evangelho pode ser contextualizado (inculturação) sem sincretismo. (5) Muitos missionários impuseram cultura ocidental junto com o evangelho (erro). (6) A Bíblia foi traduzida para muitas línguas indígenas. A teologia reformada afirma: (a) O animismo é uma religião falsa (não oferece salvação). (b) Cristo é o único Salvador (Atos 4:12). (c) O evangelho deve ser contextualizado (1 Coríndios 9:19-23). (d) Respeitar as culturas, mas rejeitar práticas contrárias à Bíblia (sacrifícios humanos, feitiçaria). (e) O testemunho deve ser feito com amor e respeito. 'Mas, como está escrito: Aqueles a quem não foi anunciado, o verão; e os que não ouviram, o entenderão' (Romanos 15:21). 'Ide, ensinai todas as nações' (Mateus 28:19).",
            referencias: "Mateus 28:19; Atos 4:12; Atos 17:22-31; Romanos 15:21; 1 Coríndios 9:19-23; Colossenses 2:15; Apocalipse 5:9"
        },
        {
            termo: "08. A Grande Comissão - Evangelismo como Imperativo (Mateus 28:18-20)",
            definicao: "A Grande Comissão é o mandamento de Cristo para evangelizar todas as nações. 'Ide, ensinai todas as nações, batizando-as em nome do Pai, e do Filho, e do Espírito Santo; ensinando-as a guardar todas as coisas que eu vos tenho mandado' (Mateus 28:19-20). Implicações: (1) O evangelho deve ser proclamado a todas as nações (incluindo muçulmanos, hindus, budistas). (2) A salvação é somente em Cristo (Atos 4:12). (3) O diálogo inter-religioso não substitui o evangelismo. (4) O testemunho deve ser com amor, respeito e mansidão (1 Pedro 3:15). (5) A conversão envolve arrependimento e fé. (6) O batismo é o sinal da nova aliança. (7) O discipulado é contínuo. A teologia reformada (Calvino, Kuyper, Bavinck) enfatiza a missão como mandamento de Cristo. 'Porque toda a autoridade me foi dada no céu e na terra' (Mateus 28:18). 'Como, pois, invocarão aquele em quem não creram? e como crerão naquele de quem não ouviram? e como ouvirão, se não há quem pregue?' (Romanos 10:14).",
            referencias: "Mateus 28:18-20; Marcos 16:15-16; Lucas 24:46-48; João 20:21; Atos 1:8; Romanos 10:13-15; 1 Pedro 3:15"
        },
        {
            termo: "09. Cristianismo e Sincretismo - O Perigo da Mistura",
            definicao: "Sincretismo é a mistura de crenças cristãs com elementos de outras religiões, resultando em uma fé corrompida. Exemplos: (1) Natal pagão (culto ao sol) + cristianismo. (2) Culto aos santos (sincretismo com religiões africanas no Brasil - umbanda, candomblé). (3) Teologia da prosperidade (sincretismo com capitalismo). (4) Jesus como avatar (sincretismo com hinduísmo). (5) Jesus como profeta (sincretismo com islamismo). A Bíblia condena o sincretismo: 'Não farás para ti imagem de escultura... não te encurvarás a elas' (Êxodo 20:4-5). 'Não podeis beber o cálice do Senhor e o cálice dos demônios' (1 Coríndios 10:21). A teologia reformada rejeita o sincretismo, mas aceita a contextualização (inculturação) que não compromete a verdade. 'Vede que ninguém vos faça presa sua, por meio de filosofias e vãs sutilezas' (Colossenses 2:8). 'Não vos conformeis com este mundo' (Romanos 12:2).",
            referencias: "Êxodo 20:4-6; Deuteronômio 12:30-32; 1 Reis 18:21; 2 Coríndios 6:14-18; Gálatas 1:6-9; Colossenses 2:8; Apocalipse 18:4"
        },
        {
            termo: "10. Testemunho em Contexto Pluralista - Estratégias e Cuidados",
            definicao: "Testemunhar de Cristo em contexto pluralista requer sabedoria. Estratégias: (1) Conheça a religião do seu interlocutor (estude). (2) Comece com pontos de contato (ex.: monoteísmo para muçulmanos; esperança para hindus). (3) Compartilhe sua experiência pessoal com Cristo. (4) Use a Bíblia, mas também mostre evidências históricas (ressurreição). (5) Responda objeções com mansidão (1 Pedro 3:15). (6) Ore pelo interlocutor. (7) Convide para um grupo de estudo bíblico. (8) Seja paciente (a conversão pode levar tempo). Cuidados: (a) Não insultar a religião do outro. (b) Não usar coerção. (c) Não prometer benefícios materiais (teologia da prosperidade). (d) Não comprometer a verdade (sincretismo). (e) Não debater agressivamente. (f) Respeitar a liberdade religiosa. 'A vossa palavra seja sempre agradável, temperada com sal, para que saibais como vos convém responder a cada um' (Colossenses 4:6). 'Antes, santificai ao Senhor Deus em vossos corações; e estai sempre preparados para responder com mansidão e temor a qualquer que vos pedir a razão da esperança que há em vós' (1 Pedro 3:15).",
            referencias: "Mateus 5:13-16; Atos 17:22-31; 1 Coríndios 9:19-23; Colossenses 4:6; 1 Pedro 3:15"
        },
        {
            termo: "11. Missões Transculturais - Paulo como Modelo",
            definicao: "O apóstolo Paulo é modelo de missionário transcultural (Atos 13-28). Ele se adaptava a diferentes culturas: 'Fiz-me como judeu para os judeus... como gentio para os gentios' (1 Coríndios 9:20-21). Exemplos: (1) Em Antioquia da Pisídia, pregou na sinagoga (Atos 13:16-41). (2) Em Atenas, usou o altar 'Ao Deus Desconhecido' e citou poetas gregos (Atos 17:22-31). (3) Em Éfeso, debateu na escola de Tirano (Atos 19:9-10). (4) Para os judeus, usou o Antigo Testamento; para os gentios, usou argumentos filosóficos. (5) Adaptou a mensagem, mas não comprometeu a verdade: 'Cristo crucificado' (1 Coríndios 2:2). A teologia reformada segue o modelo de Paulo: (a) Conheça a cultura do povo. (b) Encontre pontos de contato. (c) Use linguagem compreensível. (d) Não comprometa o evangelho. (e) Confie no poder do Espírito. 'Não me envergonho do evangelho, porque é o poder de Deus para salvação de todo aquele que crê' (Romanos 1:16).",
            referencias: "Atos 13-28; 1 Coríndios 1:22-24; 1 Coríndios 2:2; 1 Coríndios 9:19-23; Colossenses 1:28-29; 2 Timóteo 4:2"
        },
        {
            termo: "12. O Futuro do Diálogo Inter-Religioso - Desafios e Esperança",
            definicao: "O diálogo inter-religioso continuará a ser desafiador. Tendências futuras: (1) Crescimento do islamismo na Europa e América. (2) Crescimento do hinduísmo e budismo no Ocidente. (3) Secularismo e ateísmo crescentes. (4) Pluralismo religioso como ideologia dominante. (5) Perseguição a cristãos em muitos países. (6) Diálogo inter-religioso para a paz (evitar conflitos). (7) Evangelismo digital (alcançando pessoas de outras religiões online). Desafios: (a) Manter a unicidade de Cristo em meio ao pluralismo. (b) Resistir ao sincretismo. (c) Testemunhar com amor, mas sem compromisso. (d) Enfrentar a perseguição. (e) Alcançar a próxima geração. Esperança: (1) A Grande Comissão será cumprida (Mateus 24:14). (2) Multidões de todas as nações serão salvas (Apocalipse 7:9-10). (3) Cristo voltará e julgará (Apocalipse 19:11-16). (4) O testemunho da igreja é eficaz pelo poder do Espírito. 'E este evangelho do reino será pregado em todo o mundo, em testemunho a todas as nações, e então virá o fim' (Mateus 24:14). 'Depois destas coisas olhei, e eis aqui uma multidão... de todas as nações... que estavam diante do trono' (Apocalipse 7:9).",
            referencias: "Mateus 24:14; Atos 1:8; Romanos 1:16; Apocalipse 5:9; Apocalipse 7:9-10; Apocalipse 19:11-16"
        },
        {
            termo: "13. Síntese: Cristo, o Único Caminho em um Mundo Pluralista",
            definicao: "Em um mundo pluralista, os cristãos devem afirmar a unicidade de Cristo com amor e convicção. 'Eu sou o caminho, e a verdade, e a vida; ninguém vem ao Pai senão por mim' (João 14:6). Resumo do diálogo inter-religioso cristocêntrico: (1) Exclusivismo reformado: somente Cristo salva (Atos 4:12). (2) Judaísmo: Jesus é o Messias prometido (Lucas 24:27,44-45). (3) Islamismo: Jesus é Deus, crucificado e ressurreto (João 1:1; 20:28; 1 Coríndios 15:3-4). (4) Hinduísmo: Cristo é o único Salvador, não um avatar (João 14:6). (5) Budismo: Cristo oferece vida eterna, não aniquilação (João 17:3). (6) Religiões africanas/indígenas: Cristo vence os poderes espirituais (Colossenses 2:15). (7) A Grande Comissão é imperativa (Mateus 28:19). (8) O sincretismo é rejeitado (2 Coríndios 6:14-18). (9) O testemunho deve ser com mansidão (1 Pedro 3:15). (10) Paulo é modelo de missões transculturais (1 Coríndios 9:19-23). (11) A esperança é a volta de Cristo e a salvação de multidões (Apocalipse 7:9). 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36). 'Aquele que testifica estas coisas diz: Certamente cedo venho. Amém. Ora vem, Senhor Jesus. A graça de nosso Senhor Jesus Cristo seja com todos vós. Amém' (Apocalipse 22:20-21). Soli Deo Gloria!",
            referencias: "Romanos 11:36; 1 Coríndios 9:19-23; 1 Pedro 3:15; Apocalipse 7:9-10; Apocalipse 22:20-21"
        }
    ]
};