// volume/volume-59.js
window.LIVRO_DATA = {
    nome: "Volume LIX",
    dados: [
        {
            termo: "01. Introdução: A Missão de Deus (Missio Dei) Centrada em Cristo",
            definicao: "A missiologia é o estudo da missão de Deus no mundo. A teologia reformada afirma que a missão (missio Dei) é centrada em Cristo. O Pai enviou o Filho (João 3:16-17), o Filho enviou o Espírito (João 16:7), e o Espírito envia a igreja (Atos 13:2-4). 'Assim como tu me enviaste ao mundo, também eu os enviei ao mundo' (João 17:18). 'Ide, ensinai todas as nações' (Mateus 28:19). A missão não é invenção da igreja, mas participação na missão de Deus. Este volume explora a relação entre cristologia e missiologia: a Missio Dei, o evangelismo (testemunho pessoal), a plantação de igrejas, as missões transculturais, o discipulado, e a esperança escatológica. 'Porque para mim o viver é Cristo, e o morrer é ganho' (Filipenses 1:21). 'E nos reconciliou consigo mesmo por Jesus Cristo, e nos deu o ministério da reconciliação' (2 Coríndios 5:18).",
            referencias: "Mateus 28:18-20; João 3:16-17; João 17:18; João 20:21; Atos 1:8; Atos 13:2-4; 2 Coríndios 5:18-20; Apocalipse 7:9-10"
        },
        {
            termo: "02. A Missio Dei - A Missão do Pai, do Filho e do Espírito",
            definicao: "A Missio Dei (missão de Deus) é a obra trinitária de Deus para a salvação do mundo. (1) O Pai envia o Filho: 'Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito' (João 3:16). 'Deus enviou seu Filho' (Gálatas 4:4). (2) O Filho envia o Espírito: 'Se eu não for, o Consolador não virá; mas, quando eu for, vo-lo enviarei' (João 16:7). 'Recebereis a virtude do Espírito Santo... e ser-me-eis testemunhas' (Atos 1:8). (3) O Espírito envia a igreja: 'Separai-me a Barnabé e a Saulo para a obra a que os tenho chamado' (Atos 13:2). 'E ele mesmo deu uns para apóstolos... outros para evangelistas... para edificação do corpo de Cristo' (Efésios 4:11-12). Características da Missio Dei: (a) Origem em Deus (não na igreja). (b) Trinitária (Pai, Filho, Espírito). (c) Centrada em Cristo. (d) Universal (todas as nações). (e) Escatológica (consumação na volta de Cristo). A teologia reformada (Karl Barth, Lesslie Newbigin, David Bosch) desenvolveu o conceito de Missio Dei. 'Porque dele e por ele, e para ele, são todas as coisas' (Romanos 11:36).",
            referencias: "Mateus 28:19; João 3:16-17; João 16:7; João 20:21-22; Atos 1:8; Atos 13:2-4; Efésios 4:11-12; Gálatas 4:4"
        },
        {
            termo: "03. Cristo como o Enviado e o Enviador (João 17:18; 20:21)",
            definicao: "Jesus é tanto o Enviado do Pai quanto o Enviador da igreja. 'Assim como tu me enviaste ao mundo, também eu os enviei ao mundo' (João 17:18). 'Assim como o Pai me enviou, também eu vos envio a vós' (João 20:21). Implicações: (1) A missão da igreja é uma extensão da missão de Cristo. (2) A igreja deve imitar o exemplo de Cristo na missão: (a) Encarnação: contextualização. (b) Serviço: humildade. (c) Sacrifício: disposição para sofrer. (d) Amor: amor ao próximo. (e) Verdade: fidelidade à Palavra. (3) A autoridade da missão vem de Cristo (Mateus 28:18). (4) A missão é centrada na reconciliação (2 Coríndios 5:18-20). (5) A missão é acompanhada pelo Espírito Santo (Atos 1:8). 'Como o Pai me enviou, eu vos envio' é o fundamento da missão. 'Vós sois o sal da terra... vós sois a luz do mundo' (Mateus 5:13-14). 'Sede meus imitadores, como também eu sou de Cristo' (1 Coríndios 11:1).",
            referencias: "Mateus 5:13-16; Mateus 28:18-20; João 17:18; João 20:21-22; Atos 1:8; 2 Coríndios 5:18-20; 1 Pedro 2:21"
        },
        {
            termo: "04. Evangelismo - Testemunho Pessoal de Cristo",
            definicao: "Evangelismo é a proclamação do evangelho (boas novas) de Jesus Cristo. 'Ide por todo o mundo, pregai o evangelho a toda criatura' (Marcos 16:15). 'Como, pois, invocarão aquele em quem não creram? e como crerão naquele de quem não ouviram? e como ouvirão, se não há quem pregue?' (Romanos 10:14). Métodos de evangelismo: (1) Testemunho pessoal: compartilhar sua história de conversão. (2) Pregação: proclamação pública. (3) Evangelismo pessoal: um-a-um (Filipe e o eunuco, Atos 8:26-40). (4) Evangelismo de amizade: construir relacionamentos. (5) Evangelismo digital: internet, redes sociais. (6) Evangelismo literário: folhetos, livros. (7) Evangelismo de massa: cruzadas (Billy Graham). Conteúdo do evangelismo: (1) Deus é santo (Isaías 6:3). (2) O homem é pecador (Romanos 3:23). (3) Cristo morreu pelos pecados (Romanos 5:8). (4) Cristo ressuscitou (1 Coríndios 15:3-4). (5) Arrependimento e fé são necessários (Atos 20:21). (6) O batismo é o sinal da fé (Mateus 28:19). 'Mas, em vossos corações, santificai a Cristo como Senhor' (1 Pedro 3:15). 'O fruto do justo é árvore de vida, e o que ganha almas é sábio' (Provérbios 11:30).",
            referencias: "Provérbios 11:30; Mateus 28:19; Marcos 16:15; Lucas 24:46-48; Atos 1:8; Atos 8:26-40; Romanos 10:13-15; 1 Pedro 3:15"
        },
        {
            termo: "05. Discipulado - Fazer Discípulos de Cristo",
            definicao: "Discipulado é o processo de ensinar os novos convertidos a seguir a Cristo. 'Ide, ensinai todas as nações... ensinando-as a guardar todas as coisas que eu vos tenho mandado' (Mateus 28:19-20). 'Até que todos cheguemos à unidade da fé... à medida da estatura completa de Cristo' (Efésios 4:13). Elementos do discipulado: (1) Ensino da doutrina bíblica. (2) Oração. (3) Leitura da Bíblia. (4) Comunhão com a igreja. (5) Serviço. (6) Evangelismo (fazer novos discípulos). (7) Obediência a Cristo. Métodos de discipulado: (a) Discipulado pessoal (um-a-um). (b) Pequenos grupos. (c) Escola Dominical. (d) Estudos bíblicos. (e) Retiros e acampamentos. (f) Discipulado online. (g) Mentoreamento (Timóteo e Paulo). 'E o que de mim, entre muitas testemunhas, ouviste, confia-o a homens fiéis, que sejam idôneos para também ensinarem os outros' (2 Timóteo 2:2). 'Segundo aquele que vos chamou, que é santo, sede vós também santos em toda a vossa maneira de viver' (1 Pedro 1:15).",
            referencias: "Mateus 28:19-20; João 8:31-32; Efésios 4:11-16; Colossenses 1:28; 2 Timóteo 2:2; 2 Timóteo 3:16-17; 1 Pedro 2:21"
        },
        {
            termo: "06. Plantação de Igrejas - Estabelecendo Corpos Locais de Cristo",
            definicao: "Plantação de igrejas é o estabelecimento de novas congregações onde não há igreja evangélica. Paulo plantou igrejas em suas viagens missionárias (Atos 13-28). 'E, havendo em todas as igrejas estabelecido presbíteros' (Atos 14:23). 'Assim que, apascentai a igreja de Deus' (Atos 20:28). Razões para plantar igrejas: (1) Obediência à Grande Comissão (Mateus 28:19). (2) Alcançar povos não alcançados. (3) Crescimento do Reino de Deus. (4) Discipulado de novos convertidos. (5) Comunhão e apoio mútuo. (6) Celebração dos sacramentos (batismo, ceia). (7) Ensinamento da Palavra. (8) Evangelismo local. Métodos de plantação de igrejas: (a) Igreja-mãe envia uma equipe. (b) Igreja em casa (casa, escola, salão). (c) Igreja em bairros carentes. (d) Igreja para grupos específicos (universitários, profissionais, imigrantes). (e) Igreja digital (desafios). (f) Igreja transcultural (missões). 'Porque, onde estiverem dois ou três reunidos em meu nome, aí estou eu no meio deles' (Mateus 18:20). 'E acrescentava o Senhor cada dia à igreja aqueles que se haviam de salvar' (Atos 2:47).",
            referencias: "Mateus 18:20; Atos 2:42-47; Atos 13-28; Atos 14:23; Atos 20:28; 1 Coríndios 3:6-9; Tito 1:5"
        },
        {
            termo: "07. Missões Transculturais - Alcançando Povos Não Alcançados",
            definicao: "Missões transculturais é o envio de missionários para povos de cultura diferente, especialmente os não alcançados pelo evangelho. Paulo é o modelo de missionário transcultural (Atos 13-28). 'Seja feita a tua vontade, como na terra, assim no céu' (Mateus 6:10). 'Ide, ensinai todas as nações' (Mateus 28:19). Tipos de missionários: (1) Missionário plantador de igrejas (cria novas igrejas). (2) Missionário educador (escolas, seminários). (3) Missionário médico (hospitais, clínicas). (4) Missionário de desenvolvimento (agricultura, água potável). (5) Missionário de tradução da Bíblia (Wycliffe). (6) Missionário digital (internet). (7) Missionário de ajuda humanitária. Desafios das missões: (a) Barreira linguística. (b) Barreira cultural. (c) Perseguição. (d) Doenças. (e) Solidão. (f) Falta de recursos. (g) Resistência local. (h) Sincretismo. A teologia reformada (Kuyper, Bavinck) enfatiza a necessidade de missões transculturais para cumprir a Grande Comissão. 'Como, pois, invocarão aquele em quem não creram? e como crerão naquele de quem não ouviram? e como ouvirão, se não há quem pregue?' (Romanos 10:14). 'Eis-me aqui, envia-me a mim' (Isaías 6:8).",
            referencias: "Isaías 6:8; Mateus 28:19; Atos 1:8; Romanos 10:13-15; 1 Coríndios 9:19-23; Apocalipse 5:9; Apocalipse 7:9"
        },
        {
            termo: "08. O Missionário como Enviado de Cristo - Chamado e Capacitação",
            definicao: "O missionário é um enviado (apóstolos, do grego apostolos - 'enviado') de Cristo. 'Assim como o Pai me enviou, também eu vos envio a vós' (João 20:21). 'Paulo, apóstolo (não da parte dos homens, nem por homem algum, mas por Jesus Cristo)' (Gálatas 1:1). Características do missionário: (1) Chamado por Deus (Atos 13:2). (2) Enviado pela igreja (Atos 13:3). (3) Capacitado pelo Espírito Santo (Atos 1:8). (4) Fiel à Palavra (2 Timóteo 4:2). (5) Amoroso (1 Coríndios 13). (6) Humilde (Mateus 11:29). (7) Corajoso (Atos 4:29). (8) Perseverante (Atos 14:22). (9) Disposto a sofrer (2 Coríndios 11:23-28). (10) Orador (Atos 17:22-31). (11) Estudioso da cultura (1 Coríndios 9:19-23). (12) Discipulador (Mateus 28:19). (13) Plantador de igrejas (Atos 14:23). A teologia reformada (John Piper) enfatiza que o missionário é movido pelo prazer de Deus e pela glória de Cristo. 'Porque dele e por ele, e para ele, são todas as coisas' (Romanos 11:36). 'Portanto, ide... e eis que estou convosco todos os dias' (Mateus 28:19-20).",
            referencias: "Isaías 6:8; Mateus 11:29; Mateus 28:19-20; Atos 1:8; Atos 13:1-3; Atos 17:22-31; Romanos 10:14-15; 1 Coríndios 9:19-23; 2 Coríndios 5:18-20; Filipenses 2:5-8"
        },
        {
            termo: "09. Oração e Missões - O Poder da Intercessão",
            definicao: "A oração é essencial para as missões. Jesus orou pelos discípulos e por todos os crentes (João 17:1-26). A igreja primitiva orava pelos missionários (Atos 12:5; 13:3). 'E, servindo eles ao Senhor e jejuando, disse o Espírito Santo: Separai-me a Barnabé e a Saulo para a obra a que os tenho chamado. Então, jejuando e orando, e pondo sobre eles as mãos, os despediram' (Atos 13:2-3). Modos de oração missionária: (1) Oração pelos missionários (por proteção, saúde, sabedoria, fruto). (2) Oração pelos povos não alcançados. (3) Oração pelos perseguidores (Mateus 5:44). (4) Oração pelo envio de obreiros (Mateus 9:38). (5) Oração pela salvação de almas. (6) Oração pela abertura de portas (Colossenses 4:3). (7) Oração pelo poder do Espírito (Atos 4:29-31). A teologia reformada (John Piper) afirma que a oração é o 'motor' das missões. 'Pedi, pois, ao Senhor da seara que mande ceifeiros para a sua seara' (Mateus 9:38). 'Orai sem cessar' (1 Tessalonicenses 5:17). 'Não cesso de dar graças por vós, fazendo memória de vós nas minhas orações' (Efésios 1:16).",
            referencias: "Mateus 5:44; Mateus 9:38; João 17:1-26; Atos 4:29-31; Atos 12:5; Atos 13:2-3; Efésios 6:18-20; Colossenses 4:2-4; 1 Tessalonicenses 5:17"
        },
        {
            termo: "10. Apoio Missionário - Parceiros na Missão de Cristo",
            definicao: "O apoio missionário (financeiro, oração, logístico) é uma parceria na missão de Cristo. Paulo recebia apoio de igrejas (Filipenses 4:15-18). 'E também vos foi muito útil, não somente a mim, mas também a todos os crentes' (Filipenses 1:7). Formas de apoio missionário: (1) Oração (intercessão). (2) Financeiro (dízimos, ofertas). (3) Logístico (transporte, moradia). (4) Comunicação (e-mails, cartas). (5) Visitação (quando possível). (6) Apoio emocional (encorajamento). (7) Apoio familiar (cuidar dos filhos). (8) Envio de equipes de curto prazo. (9) Doação de Bíblias e literatura. (10) Apoio médico. A teologia reformada afirma que o apoio missionário é uma forma de participar da Grande Comissão. 'E assim os que repartem e os que são repartidos, me alegro com todos vós' (Filipenses 2:17). 'Vós também, como pedras vivas, sois edificados casa espiritual' (1 Pedro 2:5). 'Tendo por certo isto mesmo: que aquele que em vós começou a boa obra a aperfeiçoará até ao dia de Jesus Cristo' (Filipenses 1:6).",
            referencias: "Mateus 10:40-42; Lucas 10:7; Atos 18:3; Romanos 15:24; Filipenses 1:3-5; Filipenses 4:15-18; 3 João 1:5-8"
        },
        {
            termo: "11. Missões e Sofrimento - A Participação nas Aflições de Cristo",
            definicao: "As missões frequentemente envolvem sofrimento, perseguição e martírio. Paulo sofreu muito em suas viagens missionárias (2 Coríndios 11:23-28). 'Porque vos foi concedido, em relação a Cristo, não somente crer nele, como também padecer por ele' (Filipenses 1:29). 'E, se somos filhos, somos também herdeiros... se com ele padecemos, para que também com ele sejamos glorificados' (Romanos 8:17). Exemplos de sofrimento missionário: (1) Estêvão (martírio, Atos 7). (2) Tiago (martírio, Atos 12:2). (3) Paulo (prisões, naufrágios, açoites). (4) Missionários contemporâneos perseguidos (países fechados). (5) Martírio de missionários (Jim Elliot, Nate Saint, etc.). O sofrimento missionário é participação nas aflições de Cristo. 'Alegro-me nas minhas aflições por vós' (Colossenses 1:24). 'Mas, se padece por amor da justiça, bem-aventurado sois vós' (1 Pedro 3:14). 'Bem-aventurados os que são perseguidos por causa da justiça, porque deles é o reino dos céus' (Mateus 5:10).",
            referencias: "Mateus 5:10-12; Atos 5:41; Atos 7:54-60; Romanos 8:17-18; Filipenses 1:29; Colossenses 1:24; 2 Timóteo 3:12; 1 Pedro 4:12-16"
        },
        {
            termo: "12. Escatologia e Missões - O Cumprimento da Grande Comissão",
            definicao: "As missões são movidas pela esperança escatológica: a volta de Cristo e a salvação de todas as nações. 'E este evangelho do reino será pregado em todo o mundo, em testemunho a todas as nações, e então virá o fim' (Mateus 24:14). 'Depois destas coisas olhei, e eis aqui uma multidão... de todas as nações... que estavam diante do trono' (Apocalipse 7:9-10). Relação entre missões e escatologia: (1) A missão apressa a volta de Cristo (2 Pedro 3:12). (2) A missão é necessária porque ainda há povos não alcançados. (3) A missão é garantida de sucesso porque Cristo voltará. (4) A missão é movida pela esperança da nova criação. (5) O martírio missionário será recompensado (Apocalipse 6:9-11). A teologia reformada (John Piper) afirma: 'Missões existem porque a adoração não existe'. O objetivo final das missões é a glória de Cristo entre todas as nações. 'Porque dele e por ele, e para ele, são todas as coisas' (Romanos 11:36). 'Aguardando a bem-aventurada esperança e o aparecimento da glória do grande Deus e nosso Salvador Jesus Cristo' (Tito 2:13).",
            referencias: "Mateus 24:14; Romanos 11:36; 2 Pedro 3:10-13; Apocalipse 5:9-10; Apocalipse 7:9-10; Apocalipse 22:20-21"
        },
        {
            termo: "13. Síntese: Cristo, a Missão de Deus",
            definicao: "Cristo é o centro da Missio Dei (missão de Deus). 'Porque dele e por ele, e para ele, são todas as coisas' (Romanos 11:36). Resumo da missiologia cristocêntrica: (1) A Missio Dei é trinitária: Pai envia o Filho, Filho envia o Espírito, Espírito envia a igreja (João 20:21). (2) Cristo é o enviado e o enviador (João 17:18). (3) Evangelismo é proclamação de Cristo (Marcos 16:15). (4) Discipulado é formação de seguidores de Cristo (Mateus 28:19). (5) Plantação de igrejas é estabelecimento de corpos locais de Cristo (Atos 14:23). (6) Missões transculturais alcançam povos não alcançados (Mateus 28:19). (7) O missionário é enviado por Cristo (João 20:21). (8) A oração sustenta as missões (Mateus 9:38). (9) O apoio missionário é parceria (Filipenses 4:15-18). (10) O sofrimento missionário é participação nas aflições de Cristo (Filipenses 1:29). (11) A escatologia motiva as missões (Mateus 24:14). (12) O objetivo final é a glória de Cristo entre todas as nações (Apocalipse 7:9-10). 'Ide, ensinai todas as nações... e eis que estou convosco todos os dias' (Mateus 28:19-20). 'Aquele que testifica estas coisas diz: Certamente cedo venho. Amém. Ora vem, Senhor Jesus. A graça de nosso Senhor Jesus Cristo seja com todos vós. Amém' (Apocalipse 22:20-21). Soli Deo Gloria!",
            referencias: "Romanos 11:36; Mateus 28:18-20; João 17:18; João 20:21; Atos 1:8; Atos 13:2-4; 2 Coríndios 5:18-20; Apocalipse 7:9-10; Apocalipse 22:20-21"
        }
    ]
};