// volume/volume-67.js
window.LIVRO_DATA = {
    nome: "Volume LXVII",
    dados: [
        {
            termo: "01. Introdução: O Impacto Transformador de Cristo nos Discípulos",
            definicao: "A influência de Jesus Cristo sobre seus discípulos foi transformadora e duradoura. Homens simples, pescadores, coletores de impostos e homens comuns foram transformados em apóstolos, líderes da igreja primitiva e mártires. 'E, passando Jesus adiante, viu um homem chamado Mateus, sentado na recebedoria, e disse-lhe: Segue-me. E ele, levantando-se, o seguiu' (Mateus 9:9). 'E ele lhes disse: Vinde após mim, e eu vos farei pescadores de homens' (Mateus 4:19). Este volume explora a influência de Cristo sobre seus discípulos: o chamado, o discipulado, a transformação de caráter, o envio em missão, o martírio, e a herança deixada para as gerações futuras. A teologia reformada vê nos discípulos o modelo do verdadeiro discípulo de Cristo. 'E todos nós, com rosto descoberto, refletindo como um espelho a glória do Senhor, somos transformados de glória em glória na mesma imagem' (2 Coríndios 3:18). 'Porque para mim o viver é Cristo, e o morrer é ganho' (Filipenses 1:21).",
            referencias: "Mateus 4:18-22; Mateus 9:9; Marcos 1:16-20; Marcos 3:13-19; Lucas 5:1-11; Lucas 6:12-16; João 1:35-51"
        },
        {
            termo: "02. O Chamado dos Discípulos - Escolhidos por Cristo (João 15:16)",
            definicao: "Cristo escolheu seus discípulos; eles não o escolheram primeiro. 'Não me escolhestes vós a mim, mas eu vos escolhi a vós, e vos nomeei, para que vades e deis fruto' (João 15:16). O chamado dos doze apóstolos é registrado nos evangelhos sinóticos (Mateus 10:1-4; Marcos 3:13-19; Lucas 6:12-16). Características do chamado: (1) Iniciativa divina: Cristo os chamou (Marcos 3:13). (2) Propósito: 'para que estivessem com ele, e para os enviar a pregar' (Marcos 3:14). (3) Poder: 'e para que tivessem poder de curar as enfermidades e expulsar os demônios' (Marcos 3:15). (4) Nomes: Simão (Pedro), André, Tiago, João, Filipe, Bartolomeu, Mateus, Tomé, Tiago (filho de Alfeu), Tadeu, Simão (o Cananeu), Judas Iscariotes (Mateus 10:2-4). (5) A resposta: 'E eles, deixando tudo, o seguiram' (Lucas 5:11). A teologia reformada (Calvino) vê no chamado dos discípulos a eleição soberana de Deus. 'E ele foi ao monte a orar, e passou a noite em oração a Deus. E, quando já era dia, chamou a si os seus discípulos, e escolheu doze deles, a quem também deu o nome de apóstolos' (Lucas 6:12-13).",
            referencias: "Mateus 10:1-4; Marcos 3:13-19; Lucas 6:12-16; João 15:16; Efésios 1:4; 2 Timóteo 1:9"
        },
        {
            termo: "03. O Discipulado - Três Anos com Cristo (Marcos 3:14)",
            definicao: "Os discípulos passaram aproximadamente três anos com Cristo, aprendendo com ele, observando seus milagres, ouvindo seus ensinos, e testemunhando sua vida. 'Para que estivessem com ele' (Marcos 3:14). O que os discípulos aprenderam: (1) Ensinamentos: o Sermão do Monte (Mateus 5-7), as parábolas (Mateus 13), os discursos (Mateus 24-25). (2) Milagres: viram Jesus acalmar a tempestade (Mateus 8:23-27), multiplicar pães (Mateus 14:13-21), andar sobre o mar (Mateus 14:22-33), ressuscitar Lázaro (João 11:38-44). (3) Oração: viram Jesus orar (Lucas 11:1). (4) Caráter: testemunharam sua compaixão, humildade, paciência, amor. (5) Sofrimento: viram sua agonia no Getsêmani (Mateus 26:36-46). (6) Morte: testemunharam sua crucificação (Mateus 27:32-56). (7) Ressurreição: viram o Cristo ressurreto (João 20:19-29). A teologia reformada enfatiza que o discipulado envolve estar com Cristo, aprender de Cristo, e imitar a Cristo. 'Tomai sobre vós o meu jugo, e aprendei de mim, que sou manso e humilde de coração; e encontrareis descanso para as vossas almas' (Mateus 11:29).",
            referencias: "Mateus 5-7; Mateus 13; Mateus 24-25; Mateus 26:36-46; Mateus 27:32-56; João 20:19-29"
        },
        {
            termo: "04. A Transformação dos Discípulos - De Medrosos a Corajosos",
            definicao: "Antes da ressurreição e do Pentecostes, os discípulos eram medrosos e imperfeitos. Após a ressurreição e o derramamento do Espírito, foram transformados em testemunhas corajosas. Exemplos da transformação: (1) Pedro: negou Cristo três vezes (Mateus 26:69-75), mas depois pregou corajosamente no Pentecostes (Atos 2:14-41) e enfrentou o Sinédrio (Atos 4:8-12). (2) Tomé: duvidou da ressurreição (João 20:24-29), mas depois se tornou missionário na Índia (tradição). (3) João: um dos 'filhos do trovão' (Marcos 3:17), tornou-se o apóstolo do amor (1 João 4:7-21). (4) Tiago e João: queriam chamar fogo do céu (Lucas 9:54), mas depois se tornaram pacientes. (5) Todos os discípulos: fugiram na crucificação (Mateus 26:56), mas depois enfrentaram perseguição e martírio. A teologia reformada vê nessa transformação o poder do Espírito Santo e a influência de Cristo ressurreto. 'Mas recebereis a virtude do Espírito Santo, que há de vir sobre vós; e ser-me-eis testemunhas' (Atos 1:8). 'E, tendo orado, moveu-se o lugar em que estavam reunidos; e todos foram cheios do Espírito Santo, e anunciavam com ousadia a palavra de Deus' (Atos 4:31).",
            referencias: "Mateus 26:56; Mateus 26:69-75; Lucas 9:54; João 20:24-29; Atos 2:14-41; Atos 4:8-12; Atos 4:31; 1 João 4:7-21"
        },
        {
            termo: "05. A Missão dos Discípulos - Enviados por Cristo (João 20:21)",
            definicao: "Cristo enviou seus discípulos em missão, dando-lhes autoridade e poder. 'Assim como o Pai me enviou, também eu vos envio a vós' (João 20:21). 'Portanto, ide, ensinai todas as nações, batizando-as em nome do Pai, e do Filho, e do Espírito Santo' (Mateus 28:19). A primeira missão dos doze (Mateus 10:1-42) e dos setenta (Lucas 10:1-24) foram treinamentos para a Grande Comissão. A Grande Comissão inclui: (1) Autoridade: 'Toda a autoridade me foi dada' (Mateus 28:18). (2) Mandato: 'Ide, ensinai todas as nações' (Mateus 28:19). (3) Batismo: 'batizando-as em nome do Pai, e do Filho, e do Espírito Santo' (Mateus 28:19). (4) Ensino: 'ensinando-as a guardar todas as coisas que eu vos tenho mandado' (Mateus 28:20). (5) Promessa: 'E eis que estou convosco todos os dias, até à consumação do século' (Mateus 28:20). A teologia reformada vê na Grande Comissão o mandato contínuo da igreja. 'Como, pois, invocarão aquele em quem não creram? e como crerão naquele de quem não ouviram? e como ouvirão, se não há quem pregue?' (Romanos 10:14).",
            referencias: "Mateus 28:18-20; Marcos 16:15-16; Lucas 10:1-24; João 20:21-23; Atos 1:8; Romanos 10:13-15"
        },
        {
            termo: "06. O Martírio dos Apóstolos - Testemunhas até a Morte",
            definicao: "A maioria dos apóstolos morreu como mártires por causa de sua fé em Cristo. Martírios tradicionais: (1) Pedro: crucificado de cabeça para baixo em Roma (c. 64-68 d.C.). (2) Paulo: decapitado em Roma (c. 65-68 d.C.). (3) Tiago (filho de Zebedeu): decapitado por Herodes Agripa I (Atos 12:2). (4) André: crucificado em uma cruz em forma de X (Patras, Grécia). (5) Filipe: crucificado (Hierápolis, Frígia). (6) Tomé: traspassado com uma lança (Índia). (7) Bartolomeu: esfolado vivo e decapitado (Armênia). (8) Mateus: morto à espada (Etiópia). (9) Simão, o Zelote: crucificado (Pérsia). (10) Judas Tadeu: morto a machados (Pérsia). (11) Tiago (filho de Alfeu): apedrejado e morto a golpes de clava (Jerusalém). (12) Matias (substituto de Judas): apedrejado e decapitado (Jerusalém). (13) João: único apóstolo que morreu de morte natural (exilado em Patmos). A teologia reformada vê no martírio dos apóstolos a prova da veracidade da ressurreição (ninguém morreria por uma mentira). 'E perseguir-vos-ão, como a mim' (João 15:20). 'Bem-aventurados os que são perseguidos por causa da justiça, porque deles é o reino dos céus' (Mateus 5:10).",
            referencias: "Mateus 5:10; Atos 5:41; Atos 7:54-60; Atos 12:2; Atos 14:19; 2 Coríndios 11:23-28; Filipenses 1:29; 1 Pedro 4:12-16; Apocalipse 1:9"
        },
        {
            termo: "07. A Herança Doutrinária dos Discípulos - O Novo Testamento",
            definicao: "Os discípulos e apóstolos deixaram como herança o Novo Testamento, que contém o evangelho e a doutrina cristã. O Novo Testamento inclui: (1) Os Evangelhos (Mateus, Marcos, Lucas, João) - testemunho da vida de Cristo. (2) Atos dos Apóstolos - história da igreja primitiva. (3) Epístolas de Paulo (13-14) - doutrina e prática cristã. (4) Epístolas gerais (Tiago, 1-2 Pedro, 1-3 João, Judas) - exortações. (5) Apocalipse - esperança escatológica. 'Estes, porém, foram escritos para que creiais que Jesus é o Cristo, o Filho de Deus, e para que, crendo, tenhais vida em seu nome' (João 20:31). 'Toda a Escritura é inspirada por Deus e útil para o ensino, para a repreensão, para a correção, para a instrução na justiça' (2 Timóteo 3:16). A teologia reformada (Calvino, Westminster) afirma que o Novo Testamento é a Palavra de Deus inspirada e a regra final de fé e prática. 'Examinais as Escrituras, porque vós cuidais ter nelas a vida eterna, e são elas que de mim testificam' (João 5:39).",
            referencias: "João 5:39; João 20:30-31; Atos 1:1-3; 2 Timóteo 3:16-17; 2 Pedro 1:16-21; 2 Pedro 3:15-16; 1 João 1:1-4"
        },
        {
            termo: "08. A Herança Espiritual - O Espírito Santo e os Dons",
            definicao: "Cristo deixou o Espírito Santo como herança para seus discípulos e para a igreja. 'E eu rogarei ao Pai, e ele vos dará outro Consolador, para que fique convosco para sempre' (João 14:16). 'Mas recebereis a virtude do Espírito Santo, que há de vir sobre vós; e ser-me-eis testemunhas' (Atos 1:8). A herança do Espírito inclui: (1) Consolação (João 14:16). (2) Ensino (João 14:26). (3) Guia (João 16:13). (4) Convencimento do pecado (João 16:8). (5) Dons espirituais (1 Coríndios 12:4-11). (6) Fruto do Espírito (Gálatas 5:22-23). (7) Selo da redenção (Efésios 1:13-14). (8) Poder para testemunhar (Atos 1:8). A teologia reformada (Calvino, Owen) enfatiza que o Espírito Santo é o grande dom de Cristo à igreja. 'E foram todos cheios do Espírito Santo, e começaram a falar noutras línguas, conforme o Espírito Santo lhes concedia que falassem' (Atos 2:4). 'O amor de Deus está derramado em nossos corações pelo Espírito Santo que nos foi dado' (Romanos 5:5).",
            referencias: "João 14:16-17; João 14:26; João 16:8; João 16:13; Atos 1:8; Atos 2:1-4; Romanos 5:5; 1 Coríndios 12:4-11; Gálatas 5:22-23; Efésios 1:13-14"
        },
        {
            termo: "09. A Herança das Igrejas - Comunidades Fundadas pelos Apóstolos",
            definicao: "Os apóstolos fundaram igrejas em todo o mundo conhecido, que se tornaram a base do cristianismo. Igrejas fundadas pelos apóstolos: (1) Jerusalém (Atos 2). (2) Antioquia (Atos 11:19-26). (3) Corinto (Atos 18:1-11). (4) Éfeso (Atos 19:1-10). (5) Filipos (Atos 16:11-40). (6) Tessalônica (Atos 17:1-9). (7) Roma (tradicionalmente por Pedro e Paulo). (8) Alexandria (tradicionalmente por Marcos). (9) Antioquia da Pisídia (Atos 13:13-52). (10) Listra, Derbe, Icônio (Atos 14). (11) Creta (Tito 1:5). (12) Índia (tradicionalmente por Tomé). Essas igrejas se multiplicaram e se tornaram a igreja universal. A teologia reformada vê na plantação de igrejas o cumprimento da Grande Comissão. 'E eles, tendo partido, pregaram por todas as partes, cooperando com eles o Senhor, e confirmando a palavra com os sinais que se seguiram' (Marcos 16:20). 'E perseveravam na doutrina dos apóstolos, e na comunhão, e no partir do pão, e nas orações' (Atos 2:42).",
            referencias: "Atos 2:42; Atos 11:19-26; Atos 13-14; Atos 16-19; Marcos 16:20; Romanos 15:18-23; 1 Coríndios 3:6-9; Tito 1:5"
        },
        {
            termo: "10. Pedro - A Rocha e a Restauração (Mateus 16:18; João 21:15-19)",
            definicao: "Pedro (Simão) foi o líder dos apóstolos, mas também negou Cristo três vezes. Após a ressurreição, Cristo o restaurou. 'Tu és Pedro, e sobre esta pedra edificarei a minha igreja' (Mateus 16:18). A restauração de Pedro (João 21:15-19): (1) 'Simão, filho de Jonas, amas-me mais do que estes?' (v.15). 'Apascenta os meus cordeiros.' (2) 'Simão... amas-me?' (v.16). 'Apascenta as minhas ovelhas.' (3) 'Simão... amas-me?' (v.17). 'Apascenta as minhas ovelhas.' Pedro se tornou líder da igreja primitiva, pregou no Pentecostes (Atos 2), abriu a porta aos gentios (Atos 10), e escreveu 1 e 2 Pedro. Sua influência: (1) Sermão no Pentecostes (3.000 convertidos). (2) Cura do coxo (Atos 3). (3) Defesa diante do Sinédrio (Atos 4). (4) Visão dos gentios (Atos 10). (5) Martírio em Roma (c. 64-68 d.C.). A teologia reformada vê em Pedro um exemplo de arrependimento, restauração e liderança. 'Apascentai o rebanho de Deus que está entre vós' (1 Pedro 5:2).",
            referencias: "Mateus 16:13-20; Lucas 22:31-34; João 21:15-19; Atos 2:14-41; Atos 3:1-10; Atos 4:5-22; Atos 10:1-48; 1 Pedro 5:1-4"
        },
        {
            termo: "11. João - O Discípulo Amado e o Apóstolo do Amor (João 13:23; 19:26)",
            definicao: "João, filho de Zebedeu, era conhecido como 'o discípulo a quem Jesus amava' (João 13:23; 19:26; 20:2; 21:7,20). Ele foi testemunha ocular da transfiguração (Mateus 17:1-8), da ressurreição da filha de Jairo (Mateus 9:18-26), da agonia no Getsêmani (Mateus 26:36-46), e da crucificação (João 19:26-27). Após a ascensão, João se tornou líder da igreja em Éfeso. Sua herança: (1) Evangelho de João (a mais alta cristologia). (2) 1,2,3 João (ênfase no amor e na verdade). (3) Apocalipse (visão da consumação). Ele foi exilado em Patmos (Apocalipse 1:9). A tradição afirma que João morreu de morte natural em Éfeso, o único apóstolo que não foi martirizado. Sua ênfase: 'Deus é amor' (1 João 4:8). 'Nisto todos conhecerão que sois meus discípulos, se vos amardes uns aos outros' (João 13:35). A teologia reformada vê em João o exemplo do discípulo que descansa no peito de Cristo e que enfatiza o amor. 'Nós o amamos porque ele nos amou primeiro' (1 João 4:19).",
            referencias: "Mateus 17:1-8; João 13:23; João 19:26-27; João 20:2; João 21:7; João 21:20; 1 João 4:7-21; Apocalipse 1:9"
        },
        {
            termo: "12. Paulo - O Apóstolo dos Gentios e sua Transformação (Atos 9:1-22)",
            definicao: "Saulo de Tarso (Paulo) foi um perseguidor da igreja que se tornou o apóstolo dos gentios. Sua conversão (Atos 9:1-22): (1) Perseguidor: 'respirava ameaças e mortes contra os discípulos do Senhor' (Atos 9:1). (2) Encontro com Cristo: 'Saulo, Saulo, por que me persegues?' (Atos 9:4). (3) Cura: Ananias restaurou sua visão (Atos 9:17-18). (4) Batismo: 'levantou-se e foi batizado' (Atos 9:18). (5) Pregação: 'logo pregava nas sinagogas a Jesus' (Atos 9:20). Sua influência: (1) Três viagens missionárias (Atos 13-21). (2) 13 epístolas (Romanos a Filemom). (3) Plantação de igrejas. (4) Martírio em Roma (c. 65-68 d.C.). Sua teologia: (a) Justificação pela fé (Romanos 3:21-28). (b) União com Cristo (Gálatas 2:20). (c) A cruz como centro (1 Coríndios 2:2). (d) A ressurreição (1 Coríndios 15). A teologia reformada (Calvino) vê em Paulo o modelo da graça transformadora. 'Porque para mim o viver é Cristo, e o morrer é ganho' (Filipenses 1:21).",
            referencias: "Atos 7:58; Atos 8:1-3; Atos 9:1-22; Atos 13-28; Romanos 1:1; 1 Coríndios 2:2; Gálatas 2:20; Filipenses 1:21"
        },
        {
            termo: "13. Síntese: O Legado de Cristo nos Discípulos e na Igreja",
            definicao: "A influência de Cristo sobre seus discípulos produziu um legado que perdura até hoje. Resumo da herança: (1) O chamado: fomos chamados por Cristo para segui-lo. (2) O discipulado: aprendemos com Cristo através de sua Palavra. (3) A transformação: somos transformados à imagem de Cristo. (4) A missão: somos enviados para fazer discípulos. (5) O martírio: alguns são chamados a testemunhar com suas vidas. (6) O Novo Testamento: a doutrina deixada pelos apóstolos. (7) O Espírito Santo: o dom de Cristo à igreja. (8) As igrejas: comunidades fundadas pelos apóstolos. (9) Os líderes: Pedro, João, Paulo e outros deixaram exemplos. (10) A esperança: aguardamos a volta de Cristo. A teologia reformada celebra o legado dos discípulos e a influência contínua de Cristo. 'E ele mesmo deu uns para apóstolos, e outros para profetas, e outros para evangelistas, e outros para pastores e doutores, para aperfeiçoamento dos santos, para a obra do ministério, para edificação do corpo de Cristo' (Efésios 4:11-12). 'Lembrai-vos dos vossos pastores, que vos falaram a palavra de Deus; a fé dos quais imitai, considerando o fim da sua conversação' (Hebreus 13:7). 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36). Soli Deo Gloria!",
            referencias: "Mateus 28:18-20; João 15:16; Atos 1:8; Romanos 11:36; Efésios 4:11-12; Hebreus 13:7; Apocalipse 22:20-21"
        }
    ]
};