// volume/volume-40.js
window.LIVRO_DATA = {
    nome: "Volume XL",
    dados: [
        {
            termo: "01. Introdução: A Filosofia como Serva da Cristologia?",
            definicao: "A relação entre a filosofia e a cristologia tem sido complexa ao longo da história da igreja. Tertuliano perguntou: 'O que tem Atenas a ver com Jerusalém?' (De Praescriptione Haereticorum 7). No entanto, o Evangelho de João usa o termo filosófico Logos (Verbo) para identificar Jesus (João 1:1-14). Os Pais Apologistas (Justino Mártir, Atenágoras) usaram a filosofia grega para defender o cristianismo. A teologia reformada tem uma relação ambivalente com a filosofia: (a) A filosofia pode ser útil como 'serva da teologia' (ancilla theologiae) - fornecendo conceitos e categorias para articular a doutrina cristã (ex.: o termo homoousios do Concílio de Nicéia). (b) A filosofia pode ser perigosa quando se torna autônoma e contradiz a Escritura (Colossenses 2:8: 'Vede que ninguém vos faça presa sua, por meio de filosofias e vãs sutilezas'). Este volume explora o diálogo entre a cristologia e os principais filósofos: Platão, Aristóteles, Kant, Hegel, Kierkegaard, Nietzsche, Heidegger e outros. A teologia reformada subordina a filosofia à autoridade da Escritura (Sola Scriptura) e à centralidade de Cristo (Solus Christus).",
            referencias: "João 1:1-14; Colossenses 2:8; 1 Coríntios 1:18-25; 1 Coríntios 2:1-5; 2 Coríntios 10:5; Atos 17:22-31"
        },
        {
            termo: "02. Platão (c. 428-348 a.C.) - O Logos e o Mundo das Ideias",
            definicao: "Platão, discípulo de Sócrates, desenvolveu a teoria das Ideias (Formas), segundo a qual o mundo sensível é uma cópia imperfeita do mundo inteligível das Ideias eternas. O conceito de Logos (razão, palavra) em Platão influenciou a teologia cristã (especialmente o Prólogo de João). Pontos de contato: (1) O Logos em Platão: No 'Timeu', Platão fala do Demiurgo (Artífice) que cria o mundo usando as Ideias como modelo. (2) O conceito de transcendência: Deus é transcendente, além do mundo material. (3) A imortalidade da alma: Platão ensinava a imortalidade da alma, compatível com a ressurreição (embora diferente). (4) O bem supremo: A Ideia do Bem é o princípio supremo, análogo a Deus. Críticas reformadas: (1) O dualismo platônico (matéria é má, espírito é bom) é contrário à criação (Gênesis 1:31: 'muito bom'). (2) A alma é imortal por natureza (Platão), enquanto a Bíblia ensina que a imortalidade é um dom de Deus em Cristo (Romanos 2:7; 2 Timóteo 1:10). (3) O Logos platônico é impessoal; o Logos joanino é pessoal (João 1:1: 'o Verbo estava com Deus'). Agostinho e os Pais Capadócios usaram Platão (com cautela) para articular a doutrina da Trindade. A teologia reformada vê Platão como um preparador do caminho (como a lei para os judeus), mas rejeita o dualismo platônico.",
            referencias: "Gênesis 1:31; João 1:1-3; João 1:14; Romanos 2:7; 2 Timóteo 1:10; Atos 17:28; 1 Coríntios 15:35-58"
        },
        {
            termo: "03. Aristóteles (384-322 a.C.) - Substância e Natureza",
            definicao: "Aristóteles, discípulo de Platão, desenvolveu um sistema filosófico baseado na lógica, na metafísica (substância, acidente, ato, potência) e na ética (virtude). Sua influência na teologia cristã foi mediada por Tomás de Aquino (século XIII). Pontos de contato: (1) O conceito de substância (ousia) e acidente (symbebekos) - usado na definição calcedoniana (duas naturezas) e na transubstanciação (católica). (2) O conceito de ato e potência - usado para falar da encarnação (Cristo em ato, mas também em potência, etc.). (3) O conceito de causa primeira (motor imóvel) - argumento cosmológico para a existência de Deus. (4) A lógica aristotélica (silogismo) foi usada na escolástica. Críticas reformadas: (1) O motor imóvel de Aristóteles não é o Deus pessoal da Bíblia (não é amoroso, não é criador ex nihilo). (2) A transubstanciação (baseada na distinção substância/acidente) é rejeitada pelos reformados (presença espiritual). (3) A escolástica tardia (nominalismo, via moderna) foi criticada por Lutero e Calvino como especulação vazia. (4) A teologia reformada prefere a filosofia de Agostinho (platônica) à de Tomás (aristotélica), embora Calvino e Turretin tenham usado conceitos aristotélicos (com cautela). 'Vede que ninguém vos faça presa sua, por meio de filosofias e vãs sutilezas' (Colossenses 2:8).",
            referencias: "Colossenses 2:8; Romanos 1:18-20; Atos 17:24-28; 1 Coríntios 1:21-25; 1 Coríntios 2:6-16; Gálatas 4:3-9"
        },
        {
            termo: "04. Immanuel Kant (1724-1804) - Religião nos Limites da Simples Razão",
            definicao: "Immanuel Kant, filósofo alemão do Iluminismo, desenvolveu a 'filosofia crítica', que separa o fenômeno (como as coisas aparecem) do noumeno (a coisa em si). Na 'Religião nos Limites da Simples Razão' (1793), Kant reinterpreta o cristianismo em termos morais. Cristologia de Kant: (1) Jesus como arquétipo moral: 'Jesus é o ideal da humanidade moralmente agradável a Deus' (Religião). (2) Rejeição da divindade de Cristo: Kant nega que Jesus seja Deus (seria 'antropomorfismo'). (3) Rejeição da expiação vicária: 'A ideia de que Deus exigiu o sangue de seu Filho para satisfazer sua justiça é uma representação horrível' (Religião). (4) Rejeição da ressurreição corporal: A ressurreição é interpretada como um símbolo do triunfo da razão moral. (5) A religião é reduzida à moralidade: 'A religião não é nada mais do que o reconhecimento de nossos deveres como mandamentos divinos' (Crítica da Razão Prática). A teologia liberal do século XIX (Schleiermacher, Ritschl, Harnack) foi influenciada por Kant. Avaliação reformada: A teologia reformada rejeita a cristologia de Kant como uma negação da divindade de Cristo, da expiação vicária e da ressurreição corporal. 'Se Cristo não ressuscitou, é vã a nossa fé' (1 Coríntios 15:17). 'Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito' (João 3:16).",
            referencias: "João 1:1-14; João 3:16; Romanos 3:23-26; 1 Coríntios 15:12-20; Gálatas 2:16; Efésios 2:8-9"
        },
        {
            termo: "05. G.W.F. Hegel (1770-1831) - A Dialética e o Cristo Absoluto",
            definicao: "Georg Wilhelm Friedrich Hegel desenvolveu um sistema filosófico baseado na dialética: tese → antítese → síntese. O Espírito Absoluto (Geist) se realiza através da história. Cristologia de Hegel: (1) Cristo como o 'Espírito Absoluto' encarnado: A encarnação é o momento em que o Espírito Absoluto se torna autoconsciente na história. (2) A morte de Cristo é a 'morte da morte' - a superação da alienação. (3) A ressurreição é o símbolo da vitória do Espírito sobre a matéria. (4) A Trindade é reinterpretada como o processo dialético do Espírito: Pai (tese), Filho (antítese), Espírito Santo (síntese). (5) A religião cristã é a 'religião absoluta' porque expressa a verdade do Espírito Absoluto. A teologia liberal (David Strauss, Ferdinand Christian Baur) foi influenciada por Hegel. Avaliação reformada: A teologia reformada rejeita a cristologia de Hegel porque: (a) Panteísmo: Hegel identifica Deus com o processo histórico (panteísmo). (b) Cristo é apenas um símbolo, não uma pessoa real. (c) A ressurreição não é histórica. (d) A Trindade é reinterpretada como processo dialético, não como três pessoas eternas. 'Toda a Escritura é inspirada por Deus' (2 Timóteo 3:16). 'Jesus Cristo é o mesmo, ontem, hoje e eternamente' (Hebreus 13:8).",
            referencias: "João 1:1-14; João 8:58; 1 Coríntios 15:1-8; 2 Timóteo 3:16-17; Hebreus 13:8; Apocalipse 1:8"
        },
        {
            termo: "06. Søren Kierkegaard (1813-1855) - O Paradoxo Absoluto",
            definicao: "Søren Kierkegaard, filósofo dinamarquês, é considerado o 'pai do existencialismo'. Ele rejeitou o hegelianismo e enfatizou a fé individual, o paradoxo e o 'salto da fé'. Cristologia de Kierkegaard: (1) O paradoxo absoluto: A encarnação é o paradoxo absoluto - Deus eterno se tornando homem temporal. 'A contradição absoluta é que Deus, que é eterno, tenha se tornado homem no tempo' (Postscriptum). (2) A ofensa: A encarnação é uma ofensa à razão humana; a fé é um salto. (3) O instante (Øieblikket): A eternidade entra no tempo em Cristo. (4) A imitação de Cristo: 'O cristianismo não é uma doutrina, mas uma existência' - seguir a Cristo implica sofrimento. (5) 'O cavaleiro da fé': Abraão (Gênesis 22) é o exemplo de fé paradoxal. (6) Contra a cristandade nominal (Cristandade): A igreja da Dinamarca havia se tornado uma religião cultural; o verdadeiro cristianismo requer discipulado radical. Kierkegaard influenciou a teologia dialética (Barth, Bultmann) e o evangelicalismo (via Francis Schaeffer). Avaliação reformada: A teologia reformada aprecia a ênfase de Kierkegaard na fé individual, no paradoxo da encarnação, e na imitação de Cristo. No entanto, há críticas: (a) O 'salto da fé' pode ser irracionalista (enquanto a fé reformada é razoável, baseada em evidências históricas). (b) A ênfase no sofrimento pode minimizar a alegria da salvação. (c) A falta de ênfase na igreja (individualismo). Calvino também enfatizou o paradoxo (Deus oculto no sofrimento), mas manteve a racionalidade da fé. 'A fé é o firme fundamento das coisas que se esperam, e a prova das coisas que se não veem' (Hebreus 11:1).",
            referencias: "Gênesis 22:1-18; Mateus 16:24; Lucas 9:23; João 1:14; Romanos 4:1-25; 1 Coríntios 1:18-25; Hebreus 11:1; 1 Pedro 2:21-25"
        },
        {
            termo: "07. Friedrich Nietzsche (1844-1900) - O Anticristo",
            definicao: "Friedrich Nietzsche, filósofo alemão, foi um crítico feroz do cristianismo. Em 'O Anticristo' (1895), ele ataca a moral cristã, a teologia e a pessoa de Jesus. Cristologia de Nietzsche (crítica): (1) Jesus como 'idiota' (do grego idiotes - 'pessoa comum, simples'): 'O cristianismo é a religião do ressentimento dos fracos contra os fortes.' (2) Rejeição da divindade de Cristo: 'Deus está morto' - o cristianismo é uma ilusão. (3) Jesus como um rebelde mal interpretado: 'O verdadeiro Jesus queria abolir o Estado e a lei, mas seus seguidores o transformaram em um Deus.' (4) O 'super-homem' (Übermensch) é o antítese de Cristo: o super-homem afirma a vida, a vontade de poder, a auto-superação, enquanto Cristo prega a humildade e o sofrimento. (5) 'O cristianismo é a única grande maldição da humanidade' (O Anticristo). Avaliação reformada: Nietzsche é um adversário feroz da fé cristã. A teologia reformada responde: (a) A humildade de Cristo não é fraqueza, mas força (Filipenses 2:5-11). (b) O cristianismo não é 'ressentimento', mas amor ao próximo (João 13:34-35). (c) Deus não está morto; 'Ó profundidade das riquezas, tanto da sabedoria como da ciência de Deus!' (Romanos 11:33). (d) O super-homem de Nietzsche é uma ilusão; o verdadeiro homem é aquele que é transformado à imagem de Cristo (Romanos 8:29). Francis Schaeffer (1912-1984) respondeu a Nietzsche em 'A Morte da Razão' e 'O Deus que Se Revela'. A teologia reformada rejeita Nietzsche como um exemplo de humanismo autônomo e ateísmo militante.",
            referencias: "Romanos 11:33; Romanos 8:29; 1 Coríntios 1:18-25; Filipenses 2:5-11; Colossenses 2:8-10; 2 Pedro 1:16-21"
        },
        {
            termo: "08. Martin Heidegger (1889-1976) - Existência e Ser",
            definicao: "Martin Heidegger, filósofo alemão, desenvolveu uma 'ontologia fundamental' centrada na pergunta pelo Ser (Seinsfrage). Seu pensamento influenciou a teologia existencial de Rudolf Bultmann (desmitologização). Cristologia de Heidegger (relação indireta): (1) Dasein (ser-aí): O ser humano é um ser-no-mundo, caracterizado pela temporalidade, finitude e angústia. (2) Ser-para-a-morte: O homem autêntico se confronta com a morte e decide existir autenticamente. (3) A desmitologização de Bultmann: Bultmann usou Heidegger para reinterpretar o NT existencialmente: a ressurreição não é um evento histórico, mas um evento existencial (o crente experimenta uma nova vida). (4) Crítica à metafísica: Heidegger rejeita a teologia metafísica (Deus como 'causa primeira', 'ser supremo'). Avaliação reformada: A teologia reformada rejeita a desmitologização de Bultmann (negação da ressurreição histórica). 'Se Cristo não ressuscitou, é vã a nossa fé' (1 Coríntios 15:17). A teologia reformada afirma a historicidade da ressurreição (1 Coríntios 15:3-8). No entanto, a ênfase de Heidegger na autenticidade (viver autenticamente) pode ser útil quando subordinada à fé em Cristo. 'Já estou crucificado com Cristo; e vivo, não mais eu, mas Cristo vive em mim' (Gálatas 2:20). Francis Schaeffer respondeu a Heidegger em 'O Deus que Se Revela'.",
            referencias: "1 Coríntios 15:12-20; Gálatas 2:20; Filipenses 1:21; Filipenses 3:7-11; Colossenses 3:1-4; 2 Pedro 1:16-21; 1 João 1:1-4"
        },
        {
            termo: "09. Jean-Paul Sartre (1905-1980) - O Existencialismo Ateísta",
            definicao: "Jean-Paul Sartre, filósofo francês, desenvolveu um existencialismo ateísta. Em 'O Existencialismo é um Humanismo' (1946), ele afirma que 'o homem está condenado a ser livre' - não há Deus, não há natureza humana pré-definida. Cristologia de Sartre (crítica): (1) Ateísmo radical: 'Deus não existe'; o cristianismo é uma 'má fé' (auto-engano). (2) A liberdade absoluta: O homem é livre para criar seus próprios valores. (3) A angústia, o desamparo, o desespero: O homem está sozinho no universo. (4) 'O inferno são os outros' (Huis Clos). (5) A morte é o fim; não há esperança. Avaliação reformada: Sartre representa o ateísmo existencialista em sua forma mais radical. A teologia reformada responde: (a) Deus existe, e ele se revelou em Jesus Cristo (João 1:14,18). (b) O homem não é livre para criar seus próprios valores; os valores são dados por Deus (Êxodo 20:1-17). (c) Há esperança: a ressurreição de Cristo garante a vida eterna (1 Pedro 1:3-5). (d) O 'outro' não é o inferno; somos chamados a amar o próximo (João 13:34-35). (e) 'Aquele que crê no Filho tem a vida eterna' (João 3:36). Francis Schaeffer respondeu a Sartre em 'A Morte da Razão'.",
            referencias: "Êxodo 20:1-17; João 1:14; João 1:18; João 3:36; João 13:34-35; Romanos 1:18-25; 1 Pedro 1:3-5"
        },
        {
            termo: "10. Paul Ricoeur (1913-2005) - Hermenêutica e Símbolo",
            definicao: "Paul Ricoeur, filósofo francês, desenvolveu uma filosofia hermenêutica (interpretação) que dialoga com a teologia. Cristologia de Ricoeur: (1) O símbolo como revelação: 'O símbolo dá o que pensar' - os símbolos bíblicos (Reino de Deus, Filho de Deus, Cordeiro, etc.) revelam a realidade. (2) A hermenêutica da confissão: Interpretar os textos bíblicos como testemunho de fé. (3) O 'homem capaz': O ser humano é capaz de agir, falar, narrar, responder (em contraste com a angústia heideggeriana). (4) O mal e a culpa: Ricoeur escreveu 'O Simbolismo do Mal' (1960). (5) A ressurreição como símbolo: Ricoeur interpreta a ressurreição como símbolo da esperança (não como evento histórico). Avaliação reformada: A teologia reformada aprecia a ênfase de Ricoeur na interpretação e nos símbolos bíblicos. No entanto, rejeita sua interpretação simbólica da ressurreição (não histórica). A ressurreição é um evento histórico (1 Coríntios 15:3-8). A teologia reformada afirma que a Escritura não é apenas 'símbolo', mas 'história' (História da Salvação). 'Deus estava em Cristo reconciliando consigo o mundo' (2 Coríntios 5:19) é uma realidade histórica, não apenas um símbolo.",
            referencias: "Lucas 24:27; Lucas 24:44-45; João 5:39; Atos 2:22-36; 1 Coríntios 15:3-8; 2 Coríntios 5:18-21; 2 Pedro 1:16-21"
        },
        {
            termo: "11. A Filosofia Analítica (Russell, Wittgenstein) e a Cristologia",
            definicao: "A filosofia analítica (século XX) enfatiza a clareza lógica, a análise da linguagem e o empirismo. Principais representantes: Bertrand Russell (1872-1970) (ateu), Ludwig Wittgenstein (1889-1951) (cristão não-ortodoxo). Cristologia na filosofia analítica: (1) Bertrand Russell: Ateu, crítico do cristianismo. 'Por que não sou cristão' (1927): argumenta que a existência de Deus é improvável, que os milagres são improváveis, que a ressurreição não tem evidências suficientes. (2) Ludwig Wittgenstein: 'Onde não se pode falar, deve-se calar' (Tractatus Logico-Philosophicus). Posteriormente, desenvolveu a ideia de 'jogos de linguagem' - a linguagem religiosa é um jogo de linguagem distinto da linguagem científica. A fé não é uma questão de evidências, mas de 'forma de vida'. (3) Anthony Flew (1923-2010): 'A parábola do jardineiro invisível' - crítica ao fideísmo (fé sem evidências). Flew inicialmente foi ateu, mas no final da vida tornou-se deísta. (4) Alvin Plantinga (1932-): Desenvolveu a 'epistemologia reformada', argumentando que a crença em Deus é 'propriamente básica' (não requer evidências). Seu argumento contra o naturalismo evolutivo (EAN). (5) Richard Swinburne (1934-): Desenvolveu argumentos probabilísticos para a existência de Deus e para a ressurreição de Cristo. Avaliação reformada: A teologia reformada aprecia a filosofia analítica (Platinga, Swinburne) por seus argumentos rigorosos em defesa da fé cristã. Rejeita Russell (ateísmo) e Wittgenstein (fideísmo). A ressurreição tem evidências históricas (1 Coríntios 15:3-8). 'Examinais as Escrituras' (João 5:39).",
            referencias: "João 5:39; 1 Coríntios 15:3-8; 1 Pedro 3:15; 2 Pedro 1:16-21; 1 João 1:1-4"
        },
        {
            termo: "12. A Filosofia Pós-Moderna (Derrida, Foucault) e a Cristologia",
            definicao: "A pós-modernidade (desde c. 1960) questiona as metanarrativas (grandes relatos), a verdade objetiva, a razão universal, e as identidades fixas. Principais representantes: Jacques Derrida (1930-2004) (desconstrução), Michel Foucault (1926-1984) (poder/saber), Jean-François Lyotard (1924-1998) ('incredulidade em relação às metanarrativas'). Cristologia na pós-modernidade: (1) Desconstrução da cristologia tradicional: Derrida desconstruiria a 'metafísica da presença' na cristologia (a 'presença real' de Cristo). (2) O 'Cristo pós-moderno': Jesus como um 'outro' radical, um 'evento' em vez de uma 'pessoa'. (3) A verdade como construção social: Foucault argumentaria que a cristologia é uma construção de poder. (4) O 'evangelho emergente' (Brian McLaren, Rob Bell) é influenciado pela pós-modernidade: nega a exclusividade de Cristo (João 14:6), reinterpreta a expiação e a ressurreição simbolicamente. Avaliação reformada: A teologia reformada rejeita a pós-modernidade como um desvio da verdade objetiva. 'A tua palavra é a verdade' (João 17:17). Jesus é a verdade (João 14:6). A ressurreição é um evento histórico (1 Coríntios 15:3-8). No entanto, a teologia reformada pode dialogar com a pós-modernidade na apologética (reconhecendo as pressuposições, a contextualização). Francis Schaeffer respondeu à pós-modernidade em 'A Morte da Razão' e 'O Deus que Se Revela'. 'E conhecereis a verdade, e a verdade vos libertará' (João 8:32).",
            referencias: "João 8:32; João 14:6; João 17:17; 1 Coríntios 15:3-8; Gálatas 1:6-9; 2 Pedro 1:16-21"
        },
        {
            termo: "13. Síntese: A Filosofia sob o Senhorio de Cristo",
            definicao: "A filosofia (amor à sabedoria) pode ser útil ou perigosa para a cristologia, dependendo de sua subordinação à Escritura e à pessoa de Cristo. Princípios reformados para o diálogo entre cristologia e filosofia: (1) Sola Scriptura: A Escritura é a única regra infalível de fé (2 Timóteo 3:16-17). A filosofia deve ser subordinada à Escritura, não autônoma. (2) Solus Christus: Cristo é o centro de toda a verdade (João 14:6; Colossenses 2:2-3). A filosofia que nega a divindade de Cristo, a expiação vicária, ou a ressurreição deve ser rejeitada. (3) A filosofia pode ser 'serva da teologia' (ancilla theologiae) quando fornece conceitos e categorias para articular a doutrina cristã (ex.: homoousios). (4) A filosofia pode ser uma preparação para o evangelho (como a lei para os judeus, a filosofia para os gregos - Atos 17:22-31; Justino Mártir). (5) Deve-se evitar a 'filosofia vã' (Colossenses 2:8) que contradiz a Escritura ou torna a fé irracional. (6) A verdadeira sabedoria é encontrada em Cristo (1 Coríntios 1:24,30). 'Nele estão escondidos todos os tesouros da sabedoria e da ciência' (Colossenses 2:3). Que a filosofia seja usada para a glória de Cristo, não para sua negação. 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36). Soli Deo Gloria!",
            referencias: "Romanos 11:36; 1 Coríntios 1:24; 1 Coríndios 1:30; Colossenses 2:2-3; Colossenses 2:8; 2 Timóteo 3:16-17; Atos 17:22-31"
        }
    ]
};