// volume/volume-16.js
window.LIVRO_DATA = {
    nome: "Volume XVI",
    dados: [
        {
            termo: "01. Introdução: As Ciências Humanas sob o Senhorio de Cristo",
            definicao: "As ciências humanas (psicologia, sociologia, antropologia, história) estudam o comportamento, a cultura e a trajetória da humanidade. A cosmovisão cristocêntrica reformada afirma que 'não há um único centímetro quadrado de todo o domínio da existência humana sobre o qual Cristo, que é soberano sobre tudo, não clame: Meu!' (Abraham Kuyper). 'Porque dele e por ele, e para ele, são todas as coisas' (Romanos 11:36). As ciências humanas, quando praticadas dentro de uma cosmovisão cristã, podem: (a) descrever a realidade criada por Cristo; (b) compreender a natureza humana caída; (c) auxiliar no cuidado pastoral (psicologia); (d) promover justiça social (sociologia); (e) respeitar as culturas (antropologia); (f) aprender com o passado (história). No entanto, as ciências humanas secularizadas (naturalismo, behaviorismo, marxismo, freudismo) frequentemente negam a realidade espiritual, o pecado, a queda e a redenção em Cristo. A teologia reformada afirma a 'autonomia' limitada das ciências (cada esfera tem sua própria metodologia), mas rejeita a autonomia absoluta (as ciências não podem contradizer a Escritura).",
            referencias: "Gênesis 1:26-27; Salmo 8:4-8; Salmo 139:1-24; Romanos 1:18-25; Romanos 11:36; Colossenses 1:15-17; Colossenses 2:8-10; Hebreus 4:12-13; Tiago 3:9"
        },
        {
            termo: "02. Psicologia e Cristo: A Natureza da Alma Humana",
            definicao: "A psicologia (do grego psychē - 'alma' + logos - 'estudo') é o estudo da alma, mente e comportamento humanos. A cosmovisão cristã afirma que o ser humano foi criado por Cristo (João 1:3; Colossenses 1:16) à imagem de Deus (Gênesis 1:26-27). A psicologia cristã (ou psicologia reformada) se baseia em princípios: (1) O homem é uma unidade psicossomática (corpo e alma, Gênesis 2:7; 1 Tessalonicenses 5:23). (2) O homem caiu em pecado (Gênesis 3), resultando em corrupção da mente, vontade e emoções. (3) A redenção em Cristo restaura a imagem de Deus (Romanos 8:29; 2 Coríntios 3:18). (4) A saúde mental envolve: (a) arrependimento e fé; (b) perdão de Deus e dos outros; (c) renovação da mente pela Palavra (Romanos 12:2); (d) esperança em Cristo. Diálogo com a psicologia secular: (a) Freud (1856-1939): sua teoria é reducionista (tudo é sexual, inconsciente) e ateísta, rejeitada pela teologia reformada. (b) Jung (1875-1961): seus arquétipos e inconsciente coletivo têm paralelos com a teologia (Cristo como arquétipo do self), mas seu panteísmo é rejeitado. (c) Rogers (1902-1987): sua terapia centrada no cliente enfatiza a aceitação incondicional, que pode ser vista como expressão do amor de Cristo, mas sua visão do homem como inerentemente bom é contrária à Escritura. (d) Aconselhamento bíblico (nouthetic counseling, Jay Adams, 1923-2020): abordagem que rejeita a psicologia secular e baseia o aconselhamento exclusivamente na Bíblia (2 Timóteo 3:16-17). (e) Aconselhamento cristão integrativo (integração da psicologia com a teologia): usa insights psicológicos (desde que não contradigam a Escritura).",
            referencias: "Gênesis 2:7; Gênesis 3:1-24; Salmo 51:10; Provérbios 4:23; Jeremias 17:9; Marcos 7:21-23; Romanos 1:18-32; Romanos 7:14-25; Romanos 12:2; 1 Coríntios 2:14-16; 2 Coríntios 5:17; Gálatas 5:22-23; Efésios 4:22-24; Filipenses 4:8; Colossenses 3:1-10; 2 Timóteo 3:16-17; Hebreus 4:12; Tiago 1:14-15"
        },
        {
            termo: "03. A Personalidade de Jesus: Perspectiva Psicológica",
            definicao: "A personalidade de Jesus tem sido objeto de estudo psicológico. A teologia reformada afirma que Jesus era (a) verdadeiro homem (João 1:14), com uma personalidade humana completa; (b) sem pecado (Hebreus 4:15), portanto sua personalidade era perfeita; (c) simultaneamente verdadeiro Deus (João 1:1), transcendendo a compreensão psicológica humana. Tentativas de psicologizar Jesus: (1) 'Jesus Histórico' liberal (século XIX-XX): Jesus como um homem comum, com complexos, neuroses (ex.: 'Jesus, o homem', de Ernest Renan). Rejeitado pela teologia ortodoxa. (2) 'Jesus Psicoterapeuta' (século XX): Jesus como mestre da saúde mental (ex.: 'O Evangelho da Saúde Mental', de O. Hobart Mowrer). (3) 'Jesus e a psicanálise': abordagens freudianas (Jesus como neurótico) - rejeitadas. (4) 'Jesus e a psicologia humanista' (Carl Rogers): Jesus como 'pessoa que se realiza' - insuficiente. A teologia reformada afirma que a personalidade de Jesus é um mistério (união hipostática) que não pode ser totalmente explicado pela psicologia. 'Grande é o mistério da piedade: Deus se manifestou em carne' (1 Timóteo 3:16).",
            referencias: "Isaías 53:2-3; Mateus 4:1-11; Mateus 9:36; Mateus 11:29; Mateus 26:36-46; Marcos 3:5; Marcos 6:34; Lucas 2:40; Lucas 2:52; João 1:14; João 11:35; Hebreus 2:14-18; Hebreus 4:15; 1 Pedro 2:21-23"
        },
        {
            termo: "04. Cristo e a Cura da Alma (Aconselhamento Cristocêntrico)",
            definicao: "O aconselhamento cristão (ou aconselhamento bíblico) baseia-se na premissa de que a verdadeira cura da alma (psique) vem de Cristo. 'Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei' (Mateus 11:28). 'E conhecereis a verdade, e a verdade vos libertará' (João 8:32). Princípios: (1) O pecado é a raiz de muitos problemas psicológicos (depressão, ansiedade, raiva, medo). (2) O arrependimento e a fé em Cristo trazem perdão e cura. (3) A renovação da mente pela Palavra transforma o caráter (Romanos 12:2). (4) O Espírito Santo produz fruto (Gálatas 5:22-23). (5) A esperança escatológica alivia o sofrimento presente. Métodos: (a) Aconselhamento bíblico (nouthetic counseling, Jay Adams): confronto direto com o pecado, uso exclusivo da Bíblia. (b) Aconselhamento cristão integrativo: combina psicologia (insights seculares) com teologia, desde que a Escritura seja a autoridade final. (c) Aconselhamento pastoral (pastoral counseling): oferecido por pastores e líderes cristãos. A teologia reformada afirma que o aconselhamento deve ser cristocêntrico (foco em Cristo, não em técnicas).",
            referencias: "Salmo 34:18; Salmo 42:5; Salmo 119:50; Salmo 147:3; Provérbios 12:25; Isaías 40:1; Isaías 61:1-3; Mateus 11:28-30; João 8:32; João 14:27; Romanos 8:28; Romanos 12:2; 2 Coríntios 1:3-5; Filipenses 4:6-7; 1 Pedro 5:7"
        },
        {
            termo: "05. Sociologia e Cristo: A Igreja como Corpo de Cristo",
            definicao: "A sociologia (do latim socius - 'companheiro' + logos - 'estudo') é o estudo da sociedade, das relações sociais e das instituições. A cosmovisão cristã afirma que a sociedade foi criada por Cristo (João 1:3) e que a igreja é o corpo de Cristo (Efésios 1:22-23; 1 Coríntios 12:12-27). A sociologia cristã (ou reformada) se baseia em princípios: (1) A sociedade é ordenada por Deus (Gênesis 1-2). (2) O pecado causou desordem social (Gênesis 3-4; Romanos 1:18-32). (3) A redenção em Cristo restaura as relações sociais (Efésios 2:11-22; Gálatas 3:28). (4) A igreja é uma 'contra-sociedade' (uma comunidade alternativa que vive pelos valores do Reino). (5) Os cristãos devem ser 'sal da terra e luz do mundo' (Mateus 5:13-16), influenciando a sociedade para o bem. Diálogo com sociólogos seculares: (a) Karl Marx (1818-1883): sua análise da luta de classes (opressão dos pobres) é útil, mas sua solução (revolução, ateísmo) é rejeitada. A teologia da libertação (América Latina) usou Marx, mas foi criticada pelos reformados. (b) Émile Durkheim (1858-1917): via a religião como 'fator de coesão social' (função social), mas negava a realidade de Deus. (c) Max Weber (1864-1920): estudou a 'ética protestante' (Calvino) e sua influência no capitalismo. A teologia reformada afirma que a sociologia pode descrever a sociedade, mas não pode prescrever soluções sem Cristo.",
            referencias: "Gênesis 1:26-28; Gênesis 12:1-3; Êxodo 20:1-17; Levítico 19:18; Salmo 72; Isaías 65:17-25; Miqueias 6:8; Mateus 5:13-16; Atos 2:42-47; Romanos 12:9-21; 1 Coríntios 12:12-27; Gálatas 3:28; Efésios 2:11-22; Efésios 4:1-6; 1 Pedro 2:9-12"
        },
        {
            termo: "06. Cristo e a Justiça Social (Sociologia Cristã)",
            definicao: "A justiça social é um tema central na Bíblia. Deus ordena: 'Aprendei a fazer bem; procurai o que é justo; ajudai o oprimido; fazei justiça ao órfão; tratai da causa das viúvas' (Isaías 1:17). 'Ele te declarou, ó homem, o que é bom; e o que o Senhor pede de ti, senão que pratiques a justiça, e ames a misericórdia, e andes humildemente com o teu Deus?' (Miqueias 6:8). A teologia reformada (especialmente a tradição da 'missão integral', Lausanne 1974) afirma: (1) A igreja deve pregar o evangelho (evangelismo) e cuidar dos pobres (ação social). (2) A 'opção preferencial pelos pobres' é bíblica (Lucas 4:18-19; 6:20-23), mas não exclusiva (Deus também ama os ricos). (3) A justiça social não é o evangelho, mas uma consequência do evangelho. (4) A transformação social requer transformação individual (novo nascimento). (5) A igreja deve ser uma comunidade de justiça e amor. Diálogo com sociologia crítica (Frankfurt School, Herbert Marcuse, Jürgen Habermas): os reformados apreciam a ênfase na justiça, mas rejeitam o marxismo e o relativismo moral. A justiça social baseada em Cristo é superior à justiça secular.",
            referencias: "Levítico 19:9-10; Deuteronômio 15:7-11; Salmo 72:1-4; Salmo 82:3-4; Isaías 1:17; Isaías 58:6-7; Jeremias 22:3; Amós 5:24; Miqueias 6:8; Zacarias 7:9-10; Mateus 25:31-46; Lucas 4:18-19; Lucas 6:20-23; Lucas 14:12-14; Atos 6:1-7; Gálatas 2:10; Tiago 1:27; Tiago 2:14-26"
        },
        {
            termo: "07. Antropologia e Cristo: A Unidade e Diversidade das Culturas",
            definicao: "A antropologia (do grego anthrōpos - 'homem' + logos - 'estudo') é o estudo da humanidade em suas dimensões culturais, sociais e biológicas. A cosmovisão cristã afirma que: (1) Todas as culturas foram criadas por Cristo (João 1:3) e refletem a imagem de Deus (Gênesis 1:26-27). (2) O pecado afetou todas as culturas (pecados específicos de cada cultura). (3) A redenção em Cristo transcende as culturas: 'Nisto não há judeu nem grego; não há servo nem livre; não há macho nem fêmea; porque todos vós sois um em Cristo Jesus' (Gálatas 3:28). (4) A igreja é multicultural (Apocalipse 7:9), mas unida em Cristo. (5) O evangelho deve ser contextualizado (inculturação) em cada cultura (1 Coríntios 9:19-23), mas sem comprometer a verdade. A teologia reformada rejeita: (a) o etnocentrismo (minha cultura é superior); (b) o relativismo cultural (todas as culturas são igualmente boas); (c) o sincretismo (misturar o evangelho com práticas pagãs). A antropologia cristã enfatiza a dignidade de todas as culturas (criadas por Deus) e a necessidade de redenção de todas as culturas (afetadas pelo pecado).",
            referencias: "Gênesis 1:26-27; Gênesis 10:1-32; Gênesis 11:1-9; Atos 2:1-12; Atos 10:1-48; Atos 15:1-29; 1 Coríntios 9:19-23; Gálatas 3:28; Efésios 2:11-22; Colossenses 3:11; Apocalipse 7:9-10; Apocalipse 21:24-26"
        },
        {
            termo: "08. Missões e Contextualização (Antropologia Cristã)",
            definicao: "As missões cristãs envolvem a pregação do evangelho a todas as nações (Mateus 28:18-20). A contextualização é o processo de apresentar o evangelho em termos compreensíveis para cada cultura. Princípios: (1) O evangelho é transcultural (a verdade de Cristo é universal). (2) O evangelho deve ser encarnado em cada cultura (como Cristo se encarnou na cultura judaica, João 1:14). (3) A contextualização não deve comprometer a verdade (evangelho puro). (4) A contextualização deve respeitar as culturas (não impor costumes ocidentais). (5) O resultado é uma igreja indígena (liderada por nacionais). Exemplos bíblicos: (a) Paulo no Areópago (Atos 17:22-31): usou o altar 'Ao Deus Desconhecido' e citou poetas gregos para anunciar Cristo. (b) Paulo circuncidou Timóteo (Atos 16:1-3) para não ofender os judeus (contextualização). (c) Paulo não circuncidou Tito (Gálatas 2:3-5) para defender o evangelho da graça. A teologia reformada (missões) afirma a necessidade de contextualização (inculturação), mas rejeita o sincretismo (misturar o evangelho com religiões pagãs).",
            referencias: "Isaías 49:6; Isaías 66:18-21; Ezequiel 34:23-24; Daniel 7:13-14; Zacarias 8:20-23; Mateus 24:14; Mateus 28:18-20; Marcos 16:15; Lucas 24:47; Atos 1:8; Atos 17:22-31; Romanos 10:13-15; 1 Coríntios 9:19-23; Apocalipse 5:9-10; Apocalipse 7:9-10"
        },
        {
            termo: "09. História e Cristo: O Senhor da História",
            definicao: "A história (do grego historia - 'investigação, relato') é o estudo do passado humano. A cosmovisão cristã afirma que Cristo é o Senhor da história. 'Ele é antes de todas as coisas, e todas as coisas subsistem por ele' (Colossenses 1:17). 'Eu sou o Alfa e o Ômega, o primeiro e o último, o princípio e o fim' (Apocalipse 22:13). A história tem: (1) Origem: criada por Cristo (João 1:3). (2) Direção: governada por Cristo (Efésios 1:20-22). (3) Clímax: a primeira vinda de Cristo (encarnação, crucificação, ressurreição). (4) Fim: a segunda vinda de Cristo (parusia), juízo final, nova criação. A teologia reformada (Abraham Kuyper, Herman Dooyeweerd, Francis Schaeffer) desenvolveu uma filosofia da história cristã. Diálogo com historiadores seculares: (a) Hegel (1770-1831): via a história como evolução do Espírito (panteísmo). (b) Marx (1818-1883): via a história como luta de classes (materialismo). (c) Toynbee (1889-1975): via a história como ciclos de civilizações. (d) A 'história da redenção' (Heilsgeschichte) é a perspectiva cristã: Deus age na história para redimir seu povo. A teologia reformada afirma que a história não é sem sentido (niilismo), nem cíclica (eterno retorno), nem meramente progresso (otimismo ingênuo), mas teleológica (direcionada para o fim em Cristo).",
            referencias: "Deuteronômio 32:7; Salmo 145:4; Isaías 46:9-10; Daniel 2:21; Daniel 7:13-14; Habacuque 1:1-4; Atos 17:26; Romanos 13:1-7; 1 Coríntios 10:11; Efésios 1:9-10; Efésios 1:20-22; Colossenses 1:15-17; 1 Timóteo 2:1-4; Hebreus 1:1-2; Apocalipse 1:8; Apocalipse 21:1-5; Apocalipse 22:13"
        },
        {
            termo: "10. A Primeira Vinda de Cristo como Clímax da História",
            definicao: "A encarnação, vida, morte e ressurreição de Jesus Cristo são o clímax da história humana. 'Havendo Deus antigamente falado muitas vezes e de muitas maneiras pelos profetas, a nós falou-nos nestes últimos dias pelo Filho' (Hebreus 1:1-2). 'Mas, vindo a plenitude dos tempos, Deus enviou seu Filho' (Gálatas 4:4). Significados: (1) O tempo é linear (não cíclico), com um começo (criação), meio (Cristo) e fim (parusia). (2) A encarnação é o ponto central da história (Deus se fez homem). (3) A cruz é o julgamento da história (o pecado é condenado). (4) A ressurreição é a vitória da história (a morte é vencida). (5) A ascensão é a exaltação da história (Cristo reina). A teologia reformada rejeita: (a) o otimismo histórico (progresso automático sem Cristo); (b) o pessimismo histórico (a história não tem sentido); (c) a 'teologia da história' de Hegel e Marx (panteísta, ateísta). A história é 'sua história' (His story) - a história de Cristo.",
            referencias: "Isaías 9:6-7; Daniel 9:24-27; Miqueias 5:2; Zacarias 9:9; Lucas 1:30-33; Gálatas 4:4; Efésios 1:9-10; Hebreus 1:1-2; 1 Pedro 1:20; 1 João 4:9-10; Apocalipse 5:1-14"
        },
        {
            termo: "11. A Parusia como Consumação da História",
            definicao: "A segunda vinda de Cristo (parusia) é a consumação da história. 'Este Jesus... há de vir assim como para o céu o vistes ir' (Atos 1:11). 'Porque o Senhor mesmo descerá do céu' (1 Tessalonicenses 4:16). Eventos da parusia: (1) Ressurreição dos mortos (João 5:28-29; 1 Coríntios 15:20-23). (2) Juízo final (Mateus 25:31-46; Apocalipse 20:11-15). (3) Nova criação (Isaías 65:17; Apocalipse 21-22). (4) Derrota final da morte (1 Coríntios 15:26). (5) Reino eterno de Cristo (Apocalipse 22:1-5). A teologia reformada afirma: (a) A parusia é certa (Cristo virá). (b) A data é desconhecida (Mateus 24:36). (c) Os crentes devem estar vigilantes (Mateus 25:13). (d) A esperança escatológica motiva a missão (evangelismo) e a santificação (pureza). (e) A história não termina em tragédia, mas em vitória (Cristo reina).",
            referencias: "Daniel 7:13-14; Zacarias 14:3-5; Mateus 24:30-31; Mateus 25:31-46; João 5:28-29; Atos 1:9-11; 1 Coríntios 15:20-28; 1 Tessalonicenses 4:13-18; 2 Tessalonicenses 1:7-10; Tito 2:13; Hebreus 9:28; 2 Pedro 3:10-13; Apocalipse 1:7; Apocalipse 19:11-16; Apocalipse 20:11-15; Apocalipse 21-22"
        },
        {
            termo: "12. Cristo e a Filosofia da História (Hermenêutica Cristã)",
            definicao: "A filosofia da história pergunta: qual é o significado, direção e propósito da história? A resposta cristã é Cristoocêntrica: (1) A história foi criada por Cristo (João 1:3). (2) A história é governada por Cristo (Efésios 1:20-22). (3) A história é redimida por Cristo (Romanos 5:12-21). (4) A história é consumada em Cristo (Apocalipse 21-22). (5) A história é testemunha de Cristo (Atos 1:8). A teologia reformada rejeita: (a) O otimismo iluminista (progresso automático). (b) O pessimismo pós-moderno (a história não tem sentido). (c) O niilismo (a história é absurda). (d) O historicismo (a história é determinada por leis). (e) O relativismo (a verdade depende da história). Em vez disso, a teologia reformada afirma que a história é linear, teleológica (direcionada para um fim), e cristocêntrica (centrada em Cristo). 'Porque dele e por ele, e para ele, são todas as coisas' (Romanos 11:36).",
            referencias: "Romanos 11:36; 1 Coríntios 8:6; Colossenses 1:15-20; Hebreus 1:1-4; Apocalipse 1:8; Apocalipse 22:13; 2 Pedro 3:8-13"
        },
        {
            termo: "13. Síntese: As Ciências Humanas sob a Soberania de Cristo",
            definicao: "As ciências humanas (psicologia, sociologia, antropologia, história) são legítimas quando reconhecem que Cristo é o Criador e Redentor da humanidade. 'Porque dele e por ele, e para ele, são todas as coisas' (Romanos 11:36). A teologia reformada oferece uma estrutura para integrar as ciências humanas: (1) Reconhecer a criação (Cristo criou o ser humano, a sociedade, a cultura, a história). (2) Reconhecer a queda (o pecado afeta a psicologia, sociologia, antropologia, história). (3) Reconhecer a redenção (Cristo redime o ser humano, transforma a sociedade, renova a cultura, consuma a história). (4) Reconhecer a consumação (Cristo restaurará todas as coisas). As ciências humanas não são autônomas (não podem contradizer a Escritura), mas têm 'autonomia' limitada (cada esfera tem seu método). O alvo final é a glória de Cristo. 'A fim de que, como está escrito: Quem se gloria, glorie-se no Senhor' (1 Coríntios 1:31).",
            referencias: "Romanos 11:36; 1 Coríntios 1:31; 1 Coríntios 10:31; Colossenses 1:15-20; Colossenses 2:8-10; 2 Pedro 1:3-4; Apocalipse 21:1-5"
        }
    ]
};