// volume/volume-65.js
window.LIVRO_DATA = {
    nome: "Volume LXV",
    dados: [
        {
            termo: "01. Introdução: O Espírito Santo e o Filho na Trindade",
            definicao: "A relação entre o Filho (Jesus Cristo) e o Espírito Santo é um tema central da teologia trinitária e cristológica. O Espírito Santo é a terceira pessoa da Trindade, consubstancial (homoousios) ao Pai e ao Filho, e procede do Pai e do Filho (Filioque). 'E, quando vier o Consolador, que eu vos enviarei da parte do Pai, o Espírito da verdade, que procede do Pai, ele testificará de mim' (João 15:26). 'Tudo quanto o Pai tem é meu; por isso vos disse que há de receber do que é meu, e vo-lo há de anunciar' (João 16:15). A teologia reformada (Calvino, Turretin, Bavinck) afirma que o Espírito Santo procede do Pai e do Filho (Filioque), e que o Espírito glorifica a Cristo e aplica a redenção aos crentes. Este volume explora a relação entre o Filho e o Espírito: a processão do Espírito, a unção de Cristo pelo Espírito, a obra do Espírito na encarnação, a missão do Espírito enviada pelo Filho, e a obra do Espírito na aplicação da redenção. 'Porque não sois vós que falais, mas o Espírito de vosso Pai é que fala em vós' (Mateus 10:20). 'Mas recebereis a virtude do Espírito Santo, que há de vir sobre vós; e ser-me-eis testemunhas' (Atos 1:8).",
            referencias: "Mateus 3:16-17; João 14:16-17; João 14:26; João 15:26; João 16:7-15; Atos 1:8; Atos 2:33; Romanos 8:9-11; 1 Coríndios 2:10-13; 2 Coríndios 13:13; Efésios 1:13-14"
        },
        {
            termo: "02. A Divindade do Espírito Santo - Consubstancial com o Filho",
            definicao: "O Espírito Santo é verdadeiramente Deus, consubstancial ao Pai e ao Filho. A Bíblia afirma: (1) O Espírito Santo é chamado de Deus (Atos 5:3-4). (2) O Espírito Santo tem atributos divinos: eternidade (Hebreus 9:14), onipresença (Salmo 139:7-10), onisciência (1 Coríndios 2:10-11), onipotência (Lucas 1:35). (3) O Espírito Santo realiza obras divinas: criação (Gênesis 1:2), regeneração (João 3:5-8), ressurreição (Romanos 8:11). (4) O Espírito Santo é adorado juntamente com o Pai e o Filho (2 Coríndios 13:13; Mateus 28:19). (5) O Concílio de Constantinopla I (381 d.C.) afirmou a divindade do Espírito Santo: 'Cremos no Espírito Santo, Senhor que dá vida, que procede do Pai (e do Filho), e que com o Pai e o Filho é adorado e glorificado'. A teologia reformada aceita o Credo Niceno-Constantinopolitano e afirma a divindade plena do Espírito Santo. 'Não sabeis vós que sois o templo de Deus e que o Espírito de Deus habita em vós?' (1 Coríndios 3:16). 'Ora, o Senhor é o Espírito; e onde está o Espírito do Senhor, aí há liberdade' (2 Coríndios 3:17).",
            referencias: "Gênesis 1:2; Salmo 139:7-10; Mateus 28:19; Lucas 1:35; João 3:5-8; Atos 5:3-4; Romanos 8:11; 1 Coríndios 2:10-11; 1 Coríndios 3:16; 2 Coríndios 3:17; 2 Coríndios 13:13; Hebreus 9:14"
        },
        {
            termo: "03. A Processão do Espírito Santo - Filioque (João 15:26)",
            definicao: "A processão (ekporeusis, processio) do Espírito Santo é a relação eterna pela qual o Espírito procede (vem) do Pai e do Filho. Jesus declarou: 'Quando vier o Consolador, que eu vos enviarei da parte do Pai, o Espírito da verdade, que procede do Pai, ele testificará de mim' (João 15:26). A teologia ocidental (incluindo a reformada) afirma o Filioque ('e do Filho'), ou seja, que o Espírito procede do Pai e do Filho. A teologia oriental (ortodoxa) afirma apenas a processão do Pai. A teologia reformada (Calvino, Turretin) afirma o Filioque baseada em: (1) João 15:26 ('da parte do Pai' - inclui o Filho como enviador). (2) João 16:7 ('envio-vos o Consolador' - o Filho envia o Espírito). (3) João 20:22 ('recebei o Espírito Santo'). (4) Gálatas 4:6 ('Deus enviou o Espírito de seu Filho'). (5) Romanos 8:9 ('Espírito de Cristo'). (6) A processão eterna (não apenas temporal) é inferida destas passagens. O Filioque foi adotado pela Igreja Ocidental (incluindo a Reforma) no Credo Niceno-Constantinopolitano. 'Ele vos guiará em toda a verdade' (João 16:13). 'O Espírito de verdade, que procede do Pai' (João 15:26).",
            referencias: "João 14:26; João 15:26; João 16:7; João 16:13; João 20:22; Romanos 8:9; Gálatas 4:6; 1 Pedro 1:11"
        },
        {
            termo: "04. A Unção de Cristo pelo Espírito - O Messias Ungido",
            definicao: "Jesus é o Messias (Ungido) porque foi ungido pelo Espírito Santo. 'O Espírito do Senhor é sobre mim, porque me ungiu para evangelizar os pobres' (Lucas 4:18; Isaías 61:1). 'Como Deus ungiu a Jesus de Nazaré com o Espírito Santo e com virtude' (Atos 10:38). 'Vós ungistes a Cristo' (Hebreus 1:9). Eventos da unção: (1) A concepção de Jesus pelo Espírito (Mateus 1:18,20; Lucas 1:35). (2) O batismo de Jesus: o Espírito desceu como pomba (Mateus 3:16; Marcos 1:10; Lucas 3:22; João 1:32-33). (3) A tentação no deserto: Jesus foi conduzido pelo Espírito (Mateus 4:1; Lucas 4:1). (4) O ministério de Jesus: realizou milagres pelo poder do Espírito (Mateus 12:28; Atos 10:38). (5) A ressurreição: Cristo foi 'vivificado pelo Espírito' (1 Pedro 3:18; Romanos 1:4). A unção do Espírito capacitou Cristo para seu ministério messiânico. A teologia reformada (Calvino) vê a unção como evidência da divindade e humanidade de Cristo. 'O Espírito do Senhor repousará sobre ele' (Isaías 11:2).",
            referencias: "Isaías 11:2; Isaías 42:1; Isaías 61:1; Mateus 1:18; Mateus 3:16; Mateus 4:1; Mateus 12:28; Lucas 1:35; Lucas 4:1; Lucas 4:18; João 1:32-33; Atos 10:38; Romanos 1:4; 1 Pedro 3:18"
        },
        {
            termo: "05. O Espírito Santo na Encarnação - Concebido pelo Espírito",
            definicao: "O Espírito Santo foi ativo na encarnação de Cristo. O anjo Gabriel anunciou a Maria: 'O Espírito Santo virá sobre ti, e a virtude do Altíssimo te cobrirá com a sua sombra; pelo que também o Santo, que de ti há de nascer, será chamado Filho de Deus' (Lucas 1:35). José foi informado: 'O que nela está gerado é do Espírito Santo' (Mateus 1:20). Significados teológicos: (1) A encarnação não foi por geração humana, mas por obra do Espírito Santo. (2) O nascimento virginal é a prova da divindade de Cristo (ele não tem pai humano). (3) O Espírito Santo santificou a natureza humana de Cristo, preservando-a do pecado. (4) Cristo é verdadeiramente homem (nascido de Maria) e verdadeiramente Deus (concebido pelo Espírito). (5) A obra do Espírito na encarnação é a base para a obra do Espírito na regeneração (João 3:5-8). A teologia reformada (Calvino, Westminster) afirma o nascimento virginal como doutrina essencial. 'E o Verbo se fez carne, e habitou entre nós' (João 1:14).",
            referencias: "Mateus 1:18; Mateus 1:20; Lucas 1:35; João 1:14; João 3:5-8; Gálatas 4:4"
        },
        {
            termo: "06. O Batismo de Jesus - A Descida do Espírito e a Voz do Pai",
            definicao: "No batismo de Jesus, o Espírito Santo desceu sobre ele como uma pomba, e a voz do Pai declarou: 'Este é o meu Filho amado, em quem me comprazo' (Mateus 3:16-17; Marcos 1:10-11; Lucas 3:22; João 1:32-34). Significados teológicos: (1) A manifestação da Trindade: Pai (voz), Filho (batizado), Espírito (pomba). (2) A unção de Cristo para o ministério (Atos 10:38). (3) A confirmação da filiação de Cristo. (4) O início do ministério público de Jesus. (5) A identificação de Jesus com os pecadores (embora sem pecado, Mateus 3:15). (6) O modelo para o batismo cristão (Romanos 6:3-5). A teologia reformada (Calvino) vê no batismo de Jesus a confirmação de sua missão messiânica e a revelação trinitária. 'Este é o meu Filho amado, em quem me comprazo; escutai-o' (Mateus 17:5).",
            referencias: "Mateus 3:13-17; Marcos 1:9-11; Lucas 3:21-22; João 1:29-34; Atos 10:38; Romanos 6:3-5"
        },
        {
            termo: "07. Cristo Envia o Espírito Santo - O Dom do Pai e do Filho (João 14:16; 16:7)",
            definicao: "Cristo prometeu enviar o Espírito Santo após sua ascensão. 'E eu rogarei ao Pai, e ele vos dará outro Consolador, para que fique convosco para sempre' (João 14:16). 'E, quando eu for, vo-lo enviarei' (João 16:7). 'Se eu não for, o Consolador não virá; mas, quando eu for, vo-lo enviarei' (João 16:7). O envio do Espírito ocorreu no Pentecostes (Atos 2:1-13). Significados teológicos: (1) O Espírito é enviado pelo Pai e pelo Filho (João 15:26). (2) O Espírito é 'outro Consolador' (paraklētos) - igual a Cristo. (3) A vinda do Espírito depende da glorificação de Cristo (João 7:39). (4) O Espírito aplica a redenção comprada por Cristo. (5) O Espírito glorifica a Cristo (João 16:14). A teologia reformada (Calvino) enfatiza que o Espírito Santo é o 'selo' da redenção (Efésios 1:13-14). 'Recebereis a virtude do Espírito Santo... e ser-me-eis testemunhas' (Atos 1:8). 'E foram todos cheios do Espírito Santo' (Atos 2:4).",
            referencias: "João 7:39; João 14:16-17; João 14:26; João 15:26; João 16:7; João 16:13-15; Atos 1:8; Atos 2:1-4; Atos 2:33; Efésios 1:13-14"
        },
        {
            termo: "08. O Espírito Santo Glorifica a Cristo (João 16:14)",
            definicao: "Uma das principais obras do Espírito Santo é glorificar a Cristo. Jesus declarou: 'Ele me glorificará, porque há de receber do que é meu, e vo-lo há de anunciar' (João 16:14). 'Mas, quando vier aquele Espírito da verdade, ele vos guiará em toda a verdade' (João 16:13). O Espírito glorifica a Cristo ao: (1) Testemunhar de Cristo (João 15:26). (2) Convencer o mundo do pecado, da justiça e do juízo (João 16:8-11). (3) Aplicar a redenção aos crentes (Romanos 8:9-11). (4) Produzir o fruto do Espírito (Gálatas 5:22-23). (5) Distribuir dons espirituais (1 Coríndios 12:4-11). (6) Interpretar as Escrituras (1 Coríndios 2:10-14). (7) Unir os crentes a Cristo (Efésios 4:3-6). A teologia reformada (Calvino) enfatiza que o Espírito não fala de si mesmo, mas revela a Cristo. 'Ninguém pode dizer que Jesus é o Senhor, senão pelo Espírito Santo' (1 Coríndios 12:3). 'O amor de Deus está derramado em nossos corações pelo Espírito Santo que nos foi dado' (Romanos 5:5).",
            referencias: "João 15:26; João 16:8-15; Romanos 5:5; 1 Coríndios 2:10-14; 1 Coríndios 12:3; 1 Coríndios 12:4-11; 2 Coríndios 3:17-18; Gálatas 5:22-23; Efésios 4:3-6"
        },
        {
            termo: "09. O Espírito Santo na Obra de Cristo - Cruz e Ressurreição",
            definicao: "O Espírito Santo atuou na obra redentora de Cristo. (1) Na cruz: 'Cristo, pelo Espírito eterno, se ofereceu a si mesmo imaculado a Deus' (Hebreus 9:14). (2) Na ressurreição: 'Cristo foi mortificado na carne, mas vivificado pelo Espírito' (1 Pedro 3:18). 'Que foi declarado Filho de Deus com poder, segundo o Espírito de santificação, pela ressurreição dos mortos' (Romanos 1:4). (3) Na ascensão e exaltação: 'Subiu ao alto... e deu dons aos homens' (Efésios 4:8; Salmo 68:18). Significados teológicos: (1) O Espírito capacitou Cristo a se oferecer na cruz. (2) O Espírito ressuscitou Cristo dos mortos (Romanos 8:11). (3) O Espírito é o poder da exaltação de Cristo. (4) O Espírito aplica os benefícios da cruz e da ressurreição aos crentes. A teologia reformada (Owen) enfatiza a obra do Espírito na morte e ressurreição de Cristo. 'Se o Espírito daquele que dos mortos ressuscitou a Jesus habita em vós, aquele que dos mortos ressuscitou a Cristo Jesus também vivificará os vossos corpos mortais' (Romanos 8:11).",
            referencias: "Romanos 1:4; Romanos 8:11; 1 Coríndios 6:14; Efésios 4:8; Hebreus 9:14; 1 Pedro 3:18"
        },
        {
            termo: "10. O Espírito Santo e a Igreja - O Corpo de Cristo",
            definicao: "O Espírito Santo edifica a igreja como o corpo de Cristo. 'Porque todos fomos batizados em um Espírito, formando um corpo' (1 Coríndios 12:13). 'Vós sois o corpo de Cristo, e individualmente seus membros' (1 Coríndios 12:27). O Espírito na igreja: (1) Convence do pecado, da justiça e do juízo (João 16:8-11). (2) Regenera e batiza os crentes (João 3:5-8). (3) Distribui dons espirituais (1 Coríndios 12:4-11). (4) Produz o fruto do Espírito (Gálatas 5:22-23). (5) Guia a igreja (Atos 13:2; 16:6-7). (6) Intercede pelos crentes (Romanos 8:26-27). (7) Sela os crentes para o dia da redenção (Efésios 1:13-14). A teologia reformada (Calvino) enfatiza que o Espírito é o vínculo da união entre Cristo e a igreja. 'Ele mesmo deu uns para apóstolos... para aperfeiçoamento dos santos, para a obra do ministério, para edificação do corpo de Cristo' (Efésios 4:11-12).",
            referencias: "João 3:5-8; João 16:8-11; Atos 13:2; Romanos 8:26-27; 1 Coríndios 12:4-13; 1 Coríndios 12:27; Gálatas 5:22-23; Efésios 1:13-14; Efésios 4:11-12"
        },
        {
            termo: "11. O Espírito Santo e o Crente - União com Cristo",
            definicao: "O Espírito Santo une o crente a Cristo. 'Aquele que se ajunta ao Senhor é um mesmo espírito' (1 Coríndios 6:17). 'Deus vos ungiu... e nos selou e deu o penhor do Espírito em nossos corações' (2 Coríndios 1:21-22). O Espírito aplica a redenção: (1) Regeneração (João 3:5-8). (2) Fé (Efésios 2:8). (3) Santificação (Romanos 8:13). (4) Adoção (Romanos 8:15-16). (5) Oração (Romanos 8:26-27). (6) Segurança da salvação (Efésios 1:13-14). (7) Fruto do Espírito (Gálatas 5:22-23). A teologia reformada (Calvino, Owen) enfatiza a união mística com Cristo operada pelo Espírito. 'Cristo em vós, esperança da glória' (Colossenses 1:27). 'E estou certo de que aquele que em vós começou a boa obra a aperfeiçoará até ao dia de Jesus Cristo' (Filipenses 1:6).",
            referencias: "João 3:5-8; Romanos 8:13; Romanos 8:15-16; Romanos 8:26-27; 1 Coríndios 6:17; 2 Coríndios 1:21-22; Gálatas 5:22-23; Efésios 1:13-14; Efésios 2:8; Filipenses 1:6; Colossenses 1:27"
        },
        {
            termo: "12. A Blasfêmia contra o Espírito Santo - Pecado Imperdoável",
            definicao: "A blasfêmia contra o Espírito Santo é o pecado imperdoável (Mateus 12:31-32; Marcos 3:28-30; Lucas 12:10). O contexto: os fariseus atribuíram os milagres de Jesus (feitos pelo Espírito Santo) a Belzebu (príncipe dos demônios). A blasfêmia consiste em: (1) Atribuir a obra do Espírito Santo (em Jesus) ao diabo. (2) Rejeitar deliberadamente a evidência clara da verdade (a divindade de Cristo, os milagres). (3) Endurecimento do coração a ponto de não haver mais arrependimento. A teologia reformada ensina que este pecado não é um ato isolado, mas uma rejeição final e obstinada de Cristo, que leva à impenitência. Não é que Deus não possa perdoar, mas o pecador não se arrepende (Hebreus 6:4-6; 10:26-31). 'Portanto, eu vos digo: Todo pecado e blasfêmia será perdoado aos homens; mas a blasfêmia contra o Espírito não será perdoada' (Mateus 12:31). 'Porque o amor ao dinheiro é raiz de todos os males' (1 Timóteo 6:10).",
            referencias: "Mateus 12:22-32; Marcos 3:22-30; Lucas 12:10; Hebreus 6:4-6; Hebreus 10:26-31; 1 João 5:16"
        },
        {
            termo: "13. Síntese: A Relação entre o Filho e o Espírito Santo",
            definicao: "A relação entre o Filho (Jesus Cristo) e o Espírito Santo é uma relação de amor, missão e glorificação. Resumo: (1) O Espírito Santo é Deus, consubstancial com o Filho. (2) O Espírito procede do Pai e do Filho (Filioque). (3) O Espírito ungiu a Cristo para seu ministério messiânico. (4) O Espírito atuou na encarnação (concepção virginal). (5) O Espírito desceu sobre Cristo no batismo. (6) Cristo enviou o Espírito na ascensão (Pentecostes). (7) O Espírito glorifica a Cristo. (8) O Espírito atuou na cruz e na ressurreição de Cristo. (9) O Espírito edifica a igreja como corpo de Cristo. (10) O Espírito une os crentes a Cristo. (11) A blasfêmia contra o Espírito é imperdoável. 'A graça do Senhor Jesus Cristo, e o amor de Deus, e a comunhão do Espírito Santo seja com todos vós. Amém' (2 Coríndios 13:13). 'E não entristeçais o Espírito Santo de Deus, no qual estais selados para o dia da redenção' (Efésios 4:30). Soli Deo Gloria!",
            referencias: "Mateus 28:19; João 14:16-17; João 15:26; João 16:13-15; Atos 2:33; Romanos 8:9-11; 2 Coríndios 13:13; Efésios 4:30; 1 Pedro 1:2"
        }
    ]
};