// volume/volume-64.js
window.LIVRO_DATA = {
    nome: "Volume LXIV",
    dados: [
        {
            termo: "01. Introdução: O Propósito Eterno de Deus em Cristo",
            definicao: "O propósito eterno de Deus para o Filho é o centro da história da redenção. O apóstolo Paulo escreve: 'Bendito o Deus... que nos abençoou com todas as bênçãos espirituais... em Cristo, como também nos elegeu nele antes da fundação do mundo... nos predestinou para filhos de adoção por Jesus Cristo' (Efésios 1:3-5). 'Fazendo-nos conhecer o mistério da sua vontade, segundo o seu beneplácito, que propusera em si mesmo, de tornar a congregar em Cristo todas as coisas' (Efésios 1:9-10). O propósito de Deus é reconciliar a humanidade caída consigo mesmo por meio de seu Filho, restaurando o relacionamento rompido pelo pecado. 'Deus estava em Cristo reconciliando consigo o mundo' (2 Coríndios 5:19). Este volume explora o propósito de Deus para o Filho: a redenção, a reconciliação, a justificação, a adoção, a santificação e a glorificação. 'Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna' (João 3:16).",
            referencias: "João 3:16-17; Romanos 5:10-11; 2 Coríndios 5:18-21; Efésios 1:3-14; Colossenses 1:19-22"
        },
        {
            termo: "02. O Relacionamento Original - Criação e Queda (Gênesis 1-3)",
            definicao: "Deus criou o homem à sua imagem (Gênesis 1:26-27) para ter comunhão com Ele. Adão e Eva andavam com Deus no jardim (Gênesis 3:8). No entanto, o pecado rompeu esse relacionamento. 'Assim como por um homem entrou o pecado no mundo, e pelo pecado a morte' (Romanos 5:12). Consequências da queda: (1) Separação de Deus (Gênesis 3:8-10). (2) Morte espiritual (Efésios 2:1-3). (3) Morte física (Gênesis 3:19). (4) Maldição sobre a criação (Gênesis 3:17-19). (5) Inimizade entre a semente da mulher e a semente da serpente (Gênesis 3:15). O propósito de Deus para o Filho é restaurar o que foi perdido na queda. 'Porque, assim como todos morrem em Adão, assim também todos serão vivificados em Cristo' (1 Coríndios 15:22). A teologia reformada (Calvino, Bavinck) ensina que o pecado original afetou toda a humanidade, tornando necessária a redenção em Cristo.",
            referencias: "Gênesis 1:26-27; Gênesis 3:1-24; Romanos 5:12-21; Efésios 2:1-3; 1 Coríndios 15:21-22"
        },
        {
            termo: "03. O Propósito da Encarnação - Deus se Fez Homem (João 1:14)",
            definicao: "O propósito da encarnação é a redenção da humanidade caída. 'O Verbo se fez carne, e habitou entre nós' (João 1:14). 'E, visto como os filhos participam da carne e do sangue, também ele participou das mesmas coisas' (Hebreus 2:14). 'Porque Deus enviou o seu Filho ao mundo, não para que condenasse o mundo, mas para que o mundo fosse salvo por ele' (João 3:17). Propósitos da encarnação: (1) Revelar o Pai (João 1:18; 14:9). (2) Cumprir a lei (Mateus 5:17). (3) Servir e dar a vida em resgate (Marcos 10:45). (4) Destruir as obras do diabo (1 João 3:8). (5) Tornar-se sumo sacerdote compassivo (Hebreus 4:15). (6) Morrer pelos pecados (1 Pedro 3:18). (7) Ressuscitar para nossa justificação (Romanos 4:25). A encarnação é a base para o resgate do relacionamento do homem com Deus. 'Porque não temos um sumo sacerdote que não possa compadecer-se das nossas fraquezas; porém um que, como nós, em tudo foi tentado, mas sem pecado' (Hebreus 4:15).",
            referencias: "João 1:14; João 3:17; João 14:9; Romanos 8:3; Gálatas 4:4-5; Filipenses 2:5-8; 1 Timóteo 3:16; Hebreus 2:14-18; 1 João 3:8"
        },
        {
            termo: "04. A Redenção - O Resgate do Pecado (Romanos 3:24; Efésios 1:7)",
            definicao: "Redenção (apolytrōsis) significa 'libertação mediante o pagamento de um resgate'. Cristo pagou o preço de nossa redenção com seu sangue. 'Em quem temos a redenção pelo seu sangue, a remissão das ofensas' (Efésios 1:7). 'Fostes comprados por preço' (1 Coríndios 6:20). Aspectos da redenção: (1) Redenção da culpa do pecado (justificação). (2) Redenção do poder do pecado (santificação). (3) Redenção da presença do pecado (glorificação). (4) Redenção da maldição da lei (Gálatas 3:13). (5) Redenção da escravidão de Satanás (Hebreus 2:14-15). (6) Redenção da morte (1 Coríndios 15:54-57). O propósito de Deus é nos redimir para si mesmo. 'Ele se deu a si mesmo por nós para nos remir de toda iniquidade' (Tito 2:14). 'Vós não sois de vós mesmos... fostes comprados por bom preço' (1 Coríndios 6:19-20).",
            referencias: "Romanos 3:24; 1 Coríndios 6:20; Gálatas 3:13; Efésios 1:7; Colossenses 1:14; Tito 2:14; Hebreus 2:14-15; 1 Pedro 1:18-19"
        },
        {
            termo: "05. A Propiciação - A Satisfação da Justiça Divina (Romanos 3:25; 1 João 2:2)",
            definicao: "Propiciação (hilasmos, hilastērion) significa 'satisfazer a ira de Deus contra o pecado'. Cristo é a propiciação pelos nossos pecados. 'A quem Deus propôs para propiciação pela fé no seu sangue' (Romanos 3:25). 'Ele é a propiciação pelos nossos pecados' (1 João 2:2). 'Nisto está o amor, não em que nós tenhamos amado a Deus, mas em que ele nos amou a nós, e enviou seu Filho para propiciação pelos nossos pecados' (1 João 4:10). A propiciação é necessária porque Deus é santo e justo. O pecado exige punição. Cristo tomou sobre si a punição que merecíamos. 'O castigo que nos traz a paz estava sobre ele' (Isaías 53:5). A teologia reformada (Calvino, Owen) enfatiza que a propiciação é objetiva (satisfaz a justiça de Deus) e subjetiva (aplica-se ao crente). 'Cristo nos resgatou da maldição da lei, fazendo-se maldição por nós' (Gálatas 3:13).",
            referencias: "Isaías 53:5; Romanos 3:25; Gálatas 3:13; 1 João 2:2; 1 João 4:10; Hebreus 2:17"
        },
        {
            termo: "06. A Reconciliação - A Restauração do Relacionamento (2 Coríndios 5:18-21; Romanos 5:10-11)",
            definicao: "Reconciliação (katallagē) significa 'restaurar o relacionamento entre Deus e o homem'. Éramos inimigos de Deus por causa do pecado, mas fomos reconciliados pela morte de Cristo. 'Sendo inimigos, fomos reconciliados com Deus pela morte de seu Filho' (Romanos 5:10). 'Deus estava em Cristo reconciliando consigo o mundo, não lhes imputando os seus pecados' (2 Coríndios 5:19). 'E nos reconciliou consigo mesmo por Jesus Cristo' (2 Coríndios 5:18). Aspectos da reconciliação: (1) Deus tomou a iniciativa (Romanos 5:8). (2) O pecado é o problema (Isaías 59:2). (3) A cruz é o meio (Efésios 2:16). (4) O resultado é a paz com Deus (Romanos 5:1). (5) A reconciliação é universal em oferta, mas eficaz apenas para os que creem. O propósito de Deus é restaurar o relacionamento rompido. 'Sendo justificados pela fé, temos paz com Deus por nosso Senhor Jesus Cristo' (Romanos 5:1). 'Pelo qual também temos acesso pela fé a esta graça, na qual estamos firmes' (Romanos 5:2).",
            referencias: "Romanos 5:1; Romanos 5:8-11; 2 Coríndios 5:18-21; Efésios 2:16-18; Colossenses 1:20-22; Hebreus 2:17"
        },
        {
            termo: "07. A Justificação - Declarado Justo Diante de Deus (Romanos 3:21-28; 4:1-8)",
            definicao: "Justificação é o ato judicial de Deus pelo qual ele declara o pecador justo por causa da justiça de Cristo imputada (creditada) mediante a fé. 'Sendo justificados gratuitamente pela sua graça, pela redenção que há em Cristo Jesus' (Romanos 3:24). 'E àquele que não trabalha, mas crê naquele que justifica o ímpio, a sua fé lhe é imputada como justiça' (Romanos 4:5). 'Porque pensamos que o homem é justificado pela fé, sem as obras da lei' (Romanos 3:28). Aspectos da justificação: (1) É um ato forense (legal, declarativo). (2) É baseada na justiça de Cristo (Romanos 5:19). (3) É imputada (creditada) ao crente. (4) É recebida pela fé (sola fide). (5) É pela graça (sola gratia). (6) Exclui as obras (Romanos 3:28). O propósito de Deus é justificar os ímpios pela fé em Cristo, restaurando o relacionamento legal com Ele. 'Aquele que crê no Filho tem a vida eterna' (João 3:36).",
            referencias: "Romanos 3:21-28; Romanos 4:1-8; Romanos 5:1; Gálatas 2:16; Gálatas 3:6-14; Filipenses 3:9"
        },
        {
            termo: "08. A Adoção - Tornados Filhos de Deus (Romanos 8:14-17; Gálatas 4:4-7)",
            definicao: "Adoção (huiothesia) é o ato de Deus pelo qual ele nos recebe como filhos em sua família, por meio de Cristo. 'Mas, vindo a plenitude dos tempos, Deus enviou seu Filho... para remir os que estavam debaixo da lei, a fim de recebermos a adoção de filhos' (Gálatas 4:4-5). 'Recebestes o espírito de adoção de filhos, pelo qual clamamos: Aba, Pai' (Romanos 8:15). 'E, se nós somos filhos, somos também herdeiros, herdeiros de Deus e co-herdeiros de Cristo' (Romanos 8:17). 'Vede quão grande caridade nos tem concedido o Pai: que fôssemos chamados filhos de Deus!' (1 João 3:1). Aspectos da adoção: (1) Somos filhos por adoção, não por natureza. (2) Somos herdeiros com Cristo. (3) Temos acesso a Deus como Pai. (4) Somos disciplinados por Ele (Hebreus 12:5-11). (5) Somos glorificados com Ele. O propósito de Deus é nos tornar filhos amados. 'Portanto, já não és servo, mas filho' (Gálatas 4:7).",
            referencias: "Romanos 8:14-17; Gálatas 4:4-7; Efésios 1:5; 1 João 3:1-3; Hebreus 12:5-11"
        },
        {
            termo: "09. A Santificação - Conformados à Imagem de Cristo (Romanos 8:29; 2 Coríndios 3:18)",
            definicao: "Santificação (hagiasmos) é o processo pelo qual Deus nos torna mais semelhantes a Cristo. 'Porque os que dantes conheceu, também os predestinou para serem conformes à imagem de seu Filho' (Romanos 8:29). 'E todos nós, com rosto descoberto, refletindo como um espelho a glória do Senhor, somos transformados de glória em glória na mesma imagem' (2 Coríndios 3:18). 'Esta é a vontade de Deus, a vossa santificação' (1 Tessalonicenses 4:3). Aspectos da santificação: (1) É obra de Deus (Fp 1:6). (2) É obra do crente (Fp 2:12-13). (3) É progressiva (não instantânea). (4) É pela Palavra (João 17:17). (5) É pelo Espírito (Romanos 8:13). (6) É para toda a vida. O propósito de Deus é nos tornar semelhantes a Cristo. 'Sede santos, porque eu sou santo' (1 Pedro 1:16).",
            referencias: "Romanos 6:19-22; Romanos 8:29; 2 Coríndios 3:18; Gálatas 5:22-23; Efésios 4:22-24; Filipenses 2:12-13; 1 Tessalonicenses 4:3; João 17:17"
        },
        {
            termo: "10. A Glorificação - A Consumação (Romanos 8:30; Filipenses 3:20-21)",
            definicao: "Glorificação (doxazō) é o ato final da salvação, quando seremos totalmente conformados a Cristo em corpo e alma. 'E aos que predestinou, a esses também chamou; e aos que chamou, a esses também justificou; e aos que justificou, a esses também glorificou' (Romanos 8:30). 'O nosso Senhor Jesus Cristo... transformará o nosso corpo vil, para ser conforme o seu corpo glorioso' (Filipenses 3:20-21). 'E sabemos que, quando ele se manifestar, seremos semelhantes a ele' (1 João 3:2). Aspectos da glorificação: (1) Resurreição do corpo (1 Coríndios 15). (2) Corpo glorificado (sem pecado, incorruptível). (3) Plena santificação (sem pecado). (4) Visão de Deus (Mateus 5:8). (5) Vida eterna com Deus. O propósito de Deus é nos glorificar com Cristo. 'Para que onde eu estou, estejais vós também' (João 14:3).",
            referencias: "João 17:24; Romanos 8:17-18; 1 Coríndios 15:35-58; Filipenses 3:20-21; 1 João 3:2; Apocalipse 21-22"
        },
        {
            termo: "11. A União com Cristo - O Coração da Salvação (João 15:1-5; Romanos 6:1-11)",
            definicao: "A união com Cristo (unio cum Christo) é a base de todos os benefícios da salvação. Estamos 'em Cristo' (Romanos 8:1; 2 Coríndios 5:17; Efésios 1:3-14). 'Estou crucificado com Cristo; e vivo, não mais eu, mas Cristo vive em mim' (Gálatas 2:20). 'Permanecei em mim, e eu permanecerei em vós' (João 15:4). Aspectos da união com Cristo: (1) Mística (não física). (2) Real (não imaginária). (3) Pela fé (Efésios 3:17). (4) Pelo Espírito (1 Coríndios 6:17). (5) Indissolúvel (Romanos 8:38-39). (6) Fonte da vida espiritual. O propósito de Deus é nos unir a Cristo, para que participemos de todos os seus benefícios. 'Aquele que se ajunta ao Senhor é um mesmo espírito' (1 Coríndios 6:17).",
            referencias: "João 15:1-5; Romanos 6:1-11; 1 Coríndios 6:17; 2 Coríndios 5:17; Gálatas 2:20; Efésios 1:3-14; Efésios 3:17; Colossenses 3:1-4"
        },
        {
            termo: "12. O Propósito Final - A Nova Criação (Apocalipse 21-22)",
            definicao: "O propósito final de Deus é a nova criação, onde Deus habitará com seu povo para sempre. 'E vi um novo céu e uma nova terra' (Apocalipse 21:1). 'Eis aqui o tabernáculo de Deus com os homens, pois com eles habitará, e eles serão o seu povo, e o mesmo Deus estará com eles, e será o seu Deus. E Deus limpará de seus olhos toda lágrima; e não haverá mais morte, nem pranto, nem clamor, nem dor' (Apocalipse 21:3-4). 'E não haverá mais maldição' (Apocalipse 22:3). 'O trono de Deus e do Cordeiro estará nela' (Apocalipse 22:3). Aspectos da nova criação: (1) Novo céu e nova terra. (2) Presença de Deus com seu povo. (3) Ausência de pecado, sofrimento, morte. (4) Adoração eterna. (5) Plenitude de alegria. O propósito de Deus é restaurar o relacionamento perfeito do homem com Deus, como no Éden, mas glorificado. 'Porque dele e por ele, e para ele, são todas as coisas' (Romanos 11:36).",
            referencias: "Isaías 65:17-25; 2 Pedro 3:13; Apocalipse 21:1-27; Apocalipse 22:1-5"
        },
        {
            termo: "13. Síntese: O Resgate do Relacionamento com Deus Pai",
            definicao: "O propósito eterno de Deus para o Filho é resgatar o relacionamento do homem com Deus Pai. Resumo: (1) O relacionamento original foi rompido pela queda (Gênesis 3). (2) A encarnação é o meio de redenção (João 1:14). (3) A redenção nos liberta do pecado (Efésios 1:7). (4) A propiciação satisfaz a justiça divina (Romanos 3:25). (5) A reconciliação restaura o relacionamento (2 Coríndios 5:18-21). (6) A justificação nos declara justos (Romanos 3:24). (7) A adoção nos torna filhos de Deus (Gálatas 4:4-7). (8) A santificação nos conforma a Cristo (Romanos 8:29). (9) A glorificação nos aperfeiçoa (Romanos 8:30). (10) A união com Cristo é o coração de tudo (João 15:4). (11) A nova criação é a consumação (Apocalipse 21-22). 'Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna' (João 3:16). 'Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei' (Mateus 11:28). 'Eis que estou à porta e bato; se alguém ouvir a minha voz e abrir a porta, entrarei em sua casa e com ele cearei, e ele comigo' (Apocalipse 3:20). Soli Deo Gloria!",
            referencias: "João 3:16; Romanos 5:1; 2 Coríndios 5:18-21; Gálatas 4:4-7; Efésios 1:3-14; Apocalipse 3:20; Apocalipse 21-22"
        }
    ]
};