// volume/volume-91.js
window.LIVRO_DATA = {
    nome: "Volume XCI",
    dados: [
        {
            termo: "01. Introdução: O Perdão como Coração do Evangelho",
            definicao: "O perdão é o coração do evangelho. Deus, em Cristo, perdoou os nossos pecados. 'Em quem temos a redenção pelo seu sangue, a remissão das ofensas, segundo as riquezas da sua graça' (Efésios 1:7). 'Se confessarmos os nossos pecados, ele é fiel e justo para nos perdoar os pecados e nos purificar de toda injustiça' (1 João 1:9). A teologia reformada (Calvino, Owen, Edwards) enfatiza que o perdão divino é a base para o perdão humano. 'Perdoai-vos uns aos outros, como também Deus vos perdoou em Cristo' (Efésios 4:32). Este volume explora: (1) O perdão de Deus em Cristo. (2) O perdão como mandamento. (3) O perdão como processo. (4) Os limites do perdão. (5) Perdão e reconciliação. (6) Perdão e justiça. (7) Perdão e cura. 'Senhor, até quantas vezes pecará meu irmão contra mim, e eu lhe perdoarei? Até sete?' (Mateus 18:21). Jesus respondeu: 'Não te digo que até sete, mas até setenta vezes sete' (Mateus 18:22).",
            referencias: "Salmo 32:1-2; Isaías 1:18; Mateus 6:12; Mateus 18:21-35; Efésios 1:7; Efésios 4:32; Colossenses 3:13; 1 João 1:9"
        },
        {
            termo: "02. O Perdão de Deus em Cristo - A Base do Perdão Humano",
            definicao: "O perdão humano é baseado no perdão divino que recebemos em Cristo. 'Antes sede uns para com os outros benignos, misericordiosos, perdoando-vos uns aos outros, como também Deus vos perdoou em Cristo' (Efésios 4:32). 'Perdoai-vos uns aos outros, se alguém tem queixa contra outro; assim como Cristo vos perdoou, assim fazei vós também' (Colossenses 3:13). Características do perdão divino: (1) Gracioso: não merecido (Romanos 3:24). (2) Pleno: todos os pecados (Salmo 103:3). (3) Eterno: para sempre (Jeremias 31:34). (4) Baseado no sacrifício de Cristo (Efésios 1:7). (5) Incondicional: oferecido a todos (João 3:16). (6) Transformador: leva ao arrependimento (Romanos 2:4). (7) Esquece o pecado: 'não me lembrarei mais' (Hebreus 8:12). (8) Justo: satisfez a justiça divina (Romanos 3:25-26). (9) Amoroso: motivado pelo amor (João 3:16). (10) Pacificador: reconcilia (2 Coríndios 5:18-21). A teologia reformada (Calvino, Owen) enfatiza que o perdão divino é a fonte e o modelo do perdão humano. 'Perdoai, e sereis perdoados' (Lucas 6:37).",
            referencias: "Salmo 103:8-12; Isaías 43:25; Jeremias 31:34; Miqueias 7:18-19; Romanos 3:23-26; 2 Coríndios 5:18-21; Efésios 1:7; Colossenses 2:13-14"
        },
        {
            termo: "03. A Parábola do Credor Incompassivo (Mateus 18:21-35)",
            definicao: "A parábola do credor incompassivo é o ensino central de Jesus sobre o perdão. Um rei perdoou uma dívida de dez mil talentos (impossível de pagar) ao seu servo. Este mesmo servo, porém, não perdoou uma dívida de cem denários de um conservo. O rei, ao saber, lançou o servo na prisão. 'Assim vos fará também meu Pai celestial, se do coração não perdoardes, cada um a seu irmão, as suas ofensas' (Mateus 18:35). Lições da parábola: (1) Devemos perdoar porque fomos perdoados (v.32-33). (2) Nossa dívida com Deus é infinita (dez mil talentos). (3) A dívida do próximo é pequena (cem denários). (4) O perdão deve ser do coração (não fingido). (5) O perdão deve ser ilimitado (setenta vezes sete). (6) A falta de perdão resulta em juízo (v.34-35). (7) O perdão é um requisito para receber o perdão de Deus (Mateus 6:14-15). (8) O perdão reflete a natureza de Deus. (9) O perdão quebra o ciclo da vingança. (10) O perdão liberta o ofensor e o ofendido. A teologia reformada (Calvino, Edwards) vê nesta parábola a urgência do perdão. 'Porque, se perdoardes aos homens as suas ofensas, também vosso Pai celestial vos perdoará a vós; se, porém, não perdoardes aos homens as suas ofensas, também vosso Pai vos não perdoará as vossas ofensas' (Mateus 6:14-15).",
            referencias: "Mateus 6:14-15; Mateus 18:21-35; Lucas 17:3-4; Efésios 4:32; Colossenses 3:13"
        },
        {
            termo: "04. O Perdão na Cruz - 'Pai, Perdoa-lhes' (Lucas 23:34)",
            definicao: "Na cruz, Jesus orou pelo perdão de seus algozes. 'Pai, perdoa-lhes, porque não sabem o que fazem' (Lucas 23:34). Este é o maior exemplo de perdão da história. Significados: (1) Perdão incondicional: Jesus perdoou sem que os algozes pedissem. (2) Perdão vicário: Jesus intercedeu por eles. (3) Perdão enquanto sofria: no auge da dor, Jesus perdoou. (4) Perdão para os pecadores: os algozes eram pecadores como nós. (5) Perdão baseado na ignorância: 'não sabem o que fazem' (Atos 3:17). (6) Perdão que abre caminho para a salvação: muitos daqueles que crucificaram se converteram (Atos 2:36-41). (7) Perdão como modelo para nós: 'perdoai-vos uns aos outros' (Efésios 4:32). (8) Perdão que quebra o ciclo da vingança: Jesus não revidou (1 Pedro 2:23). (9) Perdão que demonstra o amor de Deus (João 3:16). (10) Perdão que nos chama ao arrependimento. A teologia reformada (Calvino, Bonhoeffer) vê na oração de Jesus na cruz o supremo exemplo de perdão. 'Quando o injuriavam, não injuriava; quando padecia, não ameaçava, mas entregava-se àquele que julga justamente' (1 Pedro 2:23).",
            referencias: "Atos 3:17; Atos 7:60; Romanos 5:8; 1 Pedro 2:21-23; 1 João 2:2; Lucas 23:34"
        },
        {
            termo: "05. O Perdão de Estêvão - 'Senhor, não lhes imputes este pecado' (Atos 7:60)",
            definicao: "Estêvão, o primeiro mártir cristão, imitou o exemplo de Cristo ao perdoar seus assassinos. 'E apedrejavam Estêvão, que em oração dizia: Senhor Jesus, recebe o meu espírito. E, pondo-se de joelhos, clamou com grande voz: Senhor, não lhes imputes este pecado. E, tendo dito isto, adormeceu' (Atos 7:59-60). Significados: (1) Estêvão imitou Cristo ('Pai, perdoa-lhes'). (2) O perdão é um ato de fé (confiança em Deus). (3) O perdão é um ato de amor (amor aos inimigos). (4) O perdão é um ato de martírio (testemunho). (5) O perdão é um ato de intercessão (orar pelos perseguidores). (6) O perdão é um ato de esperança (esperar a justiça de Deus). (7) O perdão é um ato de libertação (não guardar rancor). (8) O perdão é um ato de poder (poder do Espírito Santo). (9) O perdão é um ato de evangelismo (Saulo, que se tornaria Paulo, testemunhou). (10) O perdão é um ato de santidade (seguir a Cristo). A teologia reformada (Calvino, Bonhoeffer) vê em Estêvão um exemplo de como perdoar. 'Abençoai aos que vos perseguem; abençoai e não amaldiçoeis' (Romanos 12:14).",
            referencias: "Mateus 5:44; Lucas 23:34; Romanos 12:14; 1 Coríndios 4:12; 1 Pedro 2:23; Atos 7:54-60"
        },
        {
            termo: "06. Perdão e Arrependimento - A Condição para o Perdão?",
            definicao: "O perdão divino é oferecido a todos, mas é recebido mediante arrependimento e fé. 'Arrependei-vos, pois, e convertei-vos, para que sejam apagados os vossos pecados' (Atos 3:19). O perdão humano, entretanto, deve ser oferecido mesmo sem arrependimento? Jesus nos ensina a perdoar sempre (Mateus 18:21-22). Distinções: (1) Perdão incondicional: devemos perdoar ofensas mesmo sem pedido de perdão (Marcos 11:25). (2) Perdão condicional: a reconciliação plena requer arrependimento (Lucas 17:3-4). (3) Perdão interior: devemos liberar o ofensor do nosso coração (Efésios 4:32). (4) Perdão relacional: a restauração do relacionamento depende do arrependimento. (5) Perdão e justiça: o perdão não elimina a necessidade de justiça (Romanos 13:4). (6) Perdão e confiança: perdoar não significa confiar novamente automaticamente. (7) Perdão e esquecimento: perdoar não significa esquecer (mas não usar o passado como arma). (8) Perdão e emoções: perdoar não significa não sentir dor. (9) Perdão e tempo: o perdão pode ser um processo. (10) Perdão e graça: o perdão é um ato de graça, não de mérito. A teologia reformada (Calvino, Owen) enfatiza que devemos perdoar como fomos perdoados: graciosamente, sem esperar merecimento. 'Perdoai-vos uns aos outros, como também Deus vos perdoou em Cristo' (Efésios 4:32).",
            referencias: "Mateus 6:14-15; Mateus 18:21-22; Marcos 11:25; Lucas 17:3-4; Atos 3:19; Efésios 4:32"
        },
        {
            termo: "07. Perdão e Reconciliação - Restaurando Relacionamentos",
            definicao: "Perdão e reconciliação são distintos, embora relacionados. O perdão é unilateral (oferecido independentemente da resposta do ofensor). A reconciliação é bilateral (requer arrependimento e restauração). 'Portanto, se trouxeres a tua oferta ao altar e aí te lembrares de que teu irmão tem alguma coisa contra ti, deixa ali a tua oferta... vai primeiro reconciliar-te com teu irmão' (Mateus 5:23-24). 'Se teu irmão pecar contra ti, vai e repreende-o entre ti e ele só; se te ouvir, ganhaste a teu irmão' (Mateus 18:15). Passos para a reconciliação: (1) Ore pelo relacionamento. (2) Examine seu coração (Salmo 139:23-24). (3) Aborde o ofensor com humildade (Mateus 18:15). (4) Confesse seu pecado (se houver). (5) Ofereça perdão (Efésios 4:32). (6) Busque restauração. (7) Estabeleça limites saudáveis (se necessário). (8) Busque mediação (Mateus 18:16). (9) Envolva a igreja (Mateus 18:17). (10) Ore juntos. A teologia reformada (Calvino, Bavinck) enfatiza a reconciliação como fruto do perdão. 'Deus estava em Cristo reconciliando consigo o mundo' (2 Coríndios 5:19).",
            referencias: "Mateus 5:23-24; Mateus 18:15-17; Romanos 12:18; 2 Coríndios 5:18-20; Efésios 4:32; Colossenses 3:13"
        },
        {
            termo: "08. Perdão e Justiça - O Dilema entre Misericórdia e Justiça",
            definicao: "O perdão não anula a necessidade de justiça. Deus é justo e misericordioso. A cruz conciliou justiça e misericórdia. 'A quem Deus propôs para propiciação pela fé no seu sangue, para manifestar a sua justiça' (Romanos 3:25). Princípios: (1) O perdão não significa ignorar o mal (Provérbios 17:15). (2) O perdão não significa não buscar justiça (Romanos 13:4). (3) O perdão não significa não proteger os vulneráveis (Mateus 18:6). (4) O perdão não significa não aplicar consequências. (5) O perdão não significa restaurar a confiança automaticamente. (6) O perdão não significa não envolver autoridades (Romanos 13:1-4). (7) O perdão não significa não buscar restituição (Lucas 19:8). (8) O perdão não significa minimizar o pecado. (9) O perdão não significa não pedir desculpas. (10) O perdão significa liberar o ofensor do nosso coração, mas não necessariamente da justiça. Exemplos bíblicos: (a) Deus perdoou Davi, mas ele sofreu consequências (2 Samuel 12:13-14). (b) Paulo perdoou, mas alertou sobre as consequências do pecado (Gálatas 6:7-8). (c) Jesus perdoou a mulher adúltera, mas disse: 'Vai e não peques mais' (João 8:11). A teologia reformada (Calvino, Bavinck) enfatiza que a justiça e a misericórdia se encontram na cruz. 'Misericórdia e verdade se encontraram; a justiça e a paz se beijaram' (Salmo 85:10).",
            referencias: "Salmo 85:10; Provérbios 17:15; Isaías 1:17; Mateus 18:6; Romanos 3:25-26; Romanos 13:1-4; 2 Tessalonicenses 1:6-9"
        },
        {
            termo: "09. Perdão e Cura - Libertando o Coração do Rancor",
            definicao: "A falta de perdão causa danos emocionais, espirituais e até físicos. O perdão traz cura. 'O coração alegre é bom remédio, mas o espírito abatido seca os ossos' (Provérbios 17:22). Efeitos da falta de perdão: (1) Amargura (Hebreus 12:15). (2) Raiva (Efésios 4:26-27). (3) Depressão. (4) Ansiedade. (5) Insônia. (6) Pressão alta. (7) Problemas cardíacos. (8) Isolamento social. (9) Espiritualidade fraca. (10) Relacionamentos rompidos. Efeitos do perdão: (a) Paz interior (Filipenses 4:7). (b) Liberdade (João 8:36). (c) Cura emocional (Salmo 147:3). (d) Restauração de relacionamentos. (e) Crescimento espiritual. (f) Alegria (Salmo 51:12). (g) Saúde física. (h) Sono tranquilo. (i) Testemunho eficaz. (j) Glória a Deus. Passos para perdoar: (1) Reconheça a mágoa. (2) Ore pela pessoa que te ofendeu (Mateus 5:44). (3) Decida perdoar (escolha). (4) Confesse seu pecado de amargura (1 João 1:9). (5) Libere a pessoa do seu coração. (6) Peça a Deus para curar suas feridas. (7) Busque reconciliar-se, se possível (Romanos 12:18). (8) Estabeleça limites saudáveis. (9) Pratique o perdão diariamente. (10) Celebre a liberdade. A teologia reformada (Edwards, Bonhoeffer) vê o perdão como chave para a cura espiritual. 'E sede uns para com os outros benignos, misericordiosos, perdoando-vos uns aos outros, como também Deus vos perdoou em Cristo' (Efésios 4:32).",
            referencias: "Salmo 51:10-12; Salmo 147:3; Provérbios 14:30; Mateus 5:44; Romanos 12:18; Efésios 4:31-32; Hebreus 12:15"
        },
        {
            termo: "10. Perdão e Amor aos Inimigos (Mateus 5:43-48)",
            definicao: "Jesus ordenou amar os inimigos e orar pelos que nos perseguem. 'Ouvistes que foi dito: Amarás o teu próximo e odiarás o teu inimigo. Eu, porém, vos digo: Amai a vossos inimigos, bendizei os que vos maldizem, fazei bem aos que vos odeiam, e orai pelos que vos maltratam e vos perseguem' (Mateus 5:43-44). Razões para amar os inimigos: (1) Para serdes filhos do Pai (v.45). (2) Deus é bondoso com os ingratos (v.45). (3) Para serdes perfeitos como o Pai (v.48). (4) Para vencer o mal com o bem (Romanos 12:21). (5) Para acumular brasas sobre a cabeça do inimigo (Romanos 12:20). (6) Para testemunhar de Cristo. (7) Para libertar o coração do ódio. (8) Para quebrar o ciclo da vingança. (9) Para glorificar a Deus. (10) Para imitar a Cristo. Como amar os inimigos: (a) Orar por eles (Mateus 5:44). (b) Fazer o bem a eles (Romanos 12:20). (c) Abençoá-los (Romanos 12:14). (d) Não revidar (Romanos 12:17). (e) Perdoá-los (Efésios 4:32). (f) Buscar a paz (Romanos 12:18). (g) Confiar a justiça a Deus (Romanos 12:19). (h) Ser bondoso (Provérbios 25:21-22). (i) Ser humilde (Filipenses 2:3). (j) Ser paciente (Efésios 4:2). A teologia reformada (Calvino, Bonhoeffer) vê no amor aos inimigos a marca do verdadeiro cristão. 'Se for possível, quanto estiver em vós, tende paz com todos os homens' (Romanos 12:18).",
            referencias: "Provérbios 25:21-22; Mateus 5:43-48; Lucas 6:27-36; Romanos 12:14-21; 1 Pedro 3:8-9"
        },
        {
            termo: "11. Perdão e Disciplina Eclesiástica - O Papel da Igreja",
            definicao: "A igreja tem um papel no processo de perdão e reconciliação. Mateus 18:15-17 descreve os passos da disciplina eclesiástica: (1) Advertência privada (v.15). (2) Advertência com testemunhas (v.16). (3) Advertência à igreja (v.17). (4) Excomunhão (tratar como gentio e publicano) (v.17). O objetivo é a restauração, não a punição. 'Irmãos, se um homem chegar a ser surpreendido nalguma ofensa, vós, que sois espirituais, encaminhai o tal com espírito de mansidão; olhando por ti mesmo, para que também tu não sejas tentado' (Gálatas 6:1). A disciplina deve ser: (1) Amorosa (Hebreus 12:6). (2) Justa (não severa demais). (3) Restauradora (visar a correção). (4) Confidencial (não expor desnecessariamente). (5) Gradual (seguir os passos). (6) Comunitária (envolver a igreja). (7) Oracional. (8) Perdoadora (após arrependimento). (9) Reconciliadora (2 Coríndios 2:6-8). (10) Edificante. A teologia reformada (Calvino, Westminster) enfatiza a disciplina como expressão de amor. 'A disciplina parece, na verdade, no presente, não ser motivo de alegria, mas de tristeza, mas depois produz um fruto pacífico de justiça nos que por ela têm sido exercitados' (Hebreus 12:11).",
            referencias: "Mateus 18:15-20; 1 Coríndios 5:1-13; Gálatas 6:1; 2 Tessalonicenses 3:14-15; 1 Timóteo 5:20; Tito 3:10-11; Hebreus 12:5-11"
        },
        {
            termo: "12. Perdão e Esquecimento - Deus se Lembra? (Hebreus 8:12)",
            definicao: "Deus promete: 'Pois perdoarei a sua maldade, e não me lembrarei mais dos seus pecados' (Hebreus 8:12). 'Eu, eu mesmo, sou o que apago as tuas transgressões por amor de mim, e dos teus pecados não me lembro' (Isaías 43:25). Deus não se esquece no sentido humano (ele é onisciente), mas não usa o pecado passado contra nós. O perdão humano também deve envolver não trazer o passado à tona repetidamente. 'Não guarda rancor' (1 Coríndios 13:5). Princípios: (1) Perdoar significa não trazer o pecado à tona novamente. (2) Perdoar significa não usar o passado como arma. (3) Perdoar significa não fofocar sobre o pecado. (4) Perdoar significa não ruminar a ofensa. (5) Perdoar significa não exigir punição contínua. (6) Perdoar significa não rebaixar a pessoa. (7) Perdoar significa não bloquear o relacionamento (se possível). (8) Perdoar significa tratar a pessoa como se o pecado não tivesse acontecido (dentro dos limites da sabedoria). (9) Perdoar significa liberar a pessoa do nosso coração. (10) Perdoar significa escolher não se lembrar (não alimentar a mágoa). A teologia reformada (Calvino, Edwards) enfatiza que o perdão inclui o esquecimento funcional (não usar o pecado contra a pessoa). 'O amor... não guarda rancor' (1 Coríndios 13:5).",
            referencias: "Isaías 43:25; Jeremias 31:34; Miqueias 7:19; 1 Coríndios 13:5; Hebreus 8:12; Hebreus 10:17"
        },
        {
            termo: "13. Síntese: Perdoando como Cristo Perdoou",
            definicao: "O perdão cristão tem como modelo o perdão de Cristo na cruz. 'Perdoai-vos uns aos outros, como também Deus vos perdoou em Cristo' (Efésios 4:32). Resumo da teologia do perdão: (1) O perdão é o coração do evangelho (Efésios 1:7). (2) O perdão divino é a base do perdão humano (Colossenses 3:13). (3) A parábola do credor incompassivo ensina o perdão ilimitado (Mateus 18:21-35). (4) Jesus perdoou na cruz (Lucas 23:34). (5) Estêvão imitou Cristo (Atos 7:60). (6) O perdão deve ser oferecido mesmo sem arrependimento (Mateus 6:14-15). (7) A reconciliação é o objetivo do perdão (Mateus 5:23-24). (8) O perdão não anula a justiça (Romanos 13:4). (9) O perdão traz cura (Provérbios 17:22). (10) Devemos amar os inimigos (Mateus 5:44). (11) A igreja deve exercer disciplina restaurativa (Mateus 18:15-17). (12) O perdão envolve não guardar rancor (1 Coríndios 13:5). (13) Todo perdão deve ser para a glória de Cristo (1 Coríndios 10:31). 'E sede uns para com os outros benignos, misericordiosos, perdoando-vos uns aos outros, como também Deus vos perdoou em Cristo' (Efésios 4:32). Soli Deo Gloria!",
            referencias: "Romanos 11:36; 1 Coríndios 10:31; Efésios 4:32; Colossenses 3:13; 1 Pedro 2:21-25"
        }
    ]
};