// volume/volume-79.js
window.LIVRO_DATA = {
    nome: "Volume LXXIX",
    dados: [
        {
            termo: "01. Introdução: A Mulher à Luz de Cristo",
            definicao: "A mulher ocupa um lugar de honra e dignidade na criação e na redenção. 'E criou Deus o homem à sua imagem; à imagem de Deus o criou; macho e fêmea os criou' (Gênesis 1:27). 'Não há judeu nem grego; não há servo nem livre; não há macho nem fêmea; porque todos vós sois um em Cristo Jesus' (Gálatas 3:28). A teologia reformada (Calvino, Bavinck) ensina que homens e mulheres são iguais em dignidade e valor, mas têm papéis distintos na família e na igreja. A mulher é chamada a ser 'auxiliadora idônea' do homem (Gênesis 2:18), a se submeter ao marido como a igreja se submete a Cristo (Efésios 5:22-24), e a exercer poder e influência significativos na família. Este volume explora: (1) A obediência e submissão da mulher à luz de Cristo. (2) O poder e a influência da mulher na família. (3) A mulher virtuosa (Provérbios 31). (4) Exemplos bíblicos de mulheres influentes. (5) Aplicações práticas para a esposa e mãe cristã. 'A mulher virtuosa é a coroa do seu marido' (Provérbios 12:4).",
            referencias: "Gênesis 1:26-27; Gênesis 2:18-25; Provérbios 12:4; Provérbios 31:10-31; Gálatas 3:28; Efésios 5:22-33; Colossenses 3:18; 1 Pedro 3:1-7"
        },
        {
            termo: "02. A Obediência e Submissão da Mulher - Reflexo da Submissão a Cristo",
            definicao: "A submissão da mulher ao marido é um reflexo da submissão da igreja a Cristo. 'Vós, mulheres, estai sujeitas a vossos próprios maridos, como ao Senhor. Porque o marido é a cabeça da mulher, como também Cristo é a cabeça da igreja' (Efésios 5:22-23). 'Como a igreja está sujeita a Cristo, assim também as mulheres sejam em tudo sujeitas a seus maridos' (Efésios 5:24). A submissão não é: (a) Inferioridade (a igreja não é inferior a Cristo). (b) Escravidão (é voluntária). (c) Silêncio absoluto (a mulher pode falar e opinar). (d) Obediência cega (não quando contradiz a Deus - Atos 5:29). Características da submissão cristã: (1) Voluntária: não forçada. (2) Amorosa: motivada pelo amor a Deus e ao marido. (3) Respeitosa: 'a mulher reverencie o marido' (Efésios 5:33). (4) Confiante: confia na liderança do marido. (5) Alegre: não forçada. (6) Edificante: visa a glória de Deus. (7) Testemunhal: para que o marido incrédulo seja ganho (1 Pedro 3:1-2). 'Como Sara obedecia a Abraão, chamando-lhe senhor' (1 Pedro 3:6). A teologia reformada (Calvino, Piper) enfatiza que a submissão da esposa é um ato de fé e obediência a Deus. 'A vossa ornamentação não seja a exterior... mas seja o homem interior do coração' (1 Pedro 3:3-4).",
            referencias: "Atos 5:29; 1 Coríndios 14:34-35; Efésios 5:22-24; Colossenses 3:18; 1 Pedro 3:1-6; Tito 2:4-5"
        },
        {
            termo: "03. O Poder da Mulher na Família - Influência Silenciosa e Transformadora",
            definicao: "A mulher exerce um poder significativo na família, mesmo sem ocupar posições de autoridade formal. 'A mulher virtuosa é a coroa do seu marido' (Provérbios 12:4). 'A sua virtude é altura de preço' (Provérbios 31:10). Formas de poder e influência da mulher: (1) Influência moral: seu caráter piedoso influencia o marido e os filhos. (2) Influência espiritual: sua fé e oração transformam o lar. (3) Influência educacional: ensina os filhos (Provérbios 1:8; 6:20). (4) Influência emocional: seu amor e cuidado criam um ambiente seguro. (5) Influência prática: administra o lar (Provérbios 31:27). (6) Influência evangelística: pode ganhar o marido incrédulo (1 Pedro 3:1-2). (7) Influência econômica: contribui para o sustento da família (Provérbios 31:16-24). (8) Influência social: sua hospitalidade abençoa outros. Exemplos bíblicos: (1) Ester: influenciou o rei Assuero para salvar seu povo (Ester 4-8). (2) Rute: sua lealdade e caráter a tornaram ancestral de Davi e de Cristo (Rute 1-4). (3) Ana: sua oração influenciou a história de Israel (1 Samuel 1-2). (4) Eunice e Lóide: influenciaram Timóteo na fé (2 Timóteo 1:5; 3:14-15). A teologia reformada (Calvino, Bavinck) reconhece o poder transformador da mulher piedosa. 'A sabedoria edificará a sua casa' (Provérbios 14:1).",
            referencias: "Rute 1-4; 1 Samuel 1-2; Ester 4-8; Provérbios 14:1; Provérbios 31:10-31; 2 Timóteo 1:5; 2 Timóteo 3:14-15; 1 Pedro 3:1-2"
        },
        {
            termo: "04. A Mulher como Auxiliadora Idônea - Parceria e Complementaridade (Gênesis 2:18)",
            definicao: "A mulher foi criada como 'auxiliadora idônea' para o homem. 'E disse o Senhor Deus: Não é bom que o homem esteja só; far-lhe-ei uma auxiliadora idônea' (Gênesis 2:18). 'E chamou Adão o nome da sua mulher, Eva, porquanto ela era a mãe de todos os viventes' (Gênesis 3:20). Significados de 'auxiliadora idônea': (1) Auxiliadora: a mulher ajuda o homem em sua missão (dominar a terra, multiplicar-se). (2) Idônea: adequada, correspondente, complementar. (3) Parceira: não é inferior, mas igual em dignidade. (4) Corpo: 'osso dos meus ossos e carne da minha carne' (Gênesis 2:23). (5) Mãe: geradora de vida (Gênesis 3:20). (6) Administradora: cuida do lar (Provérbios 31:27). (7) Conselheira: oferece sabedoria (Provérbios 31:26). A mulher não é um 'assistente' inferior, mas uma parceira essencial. A teologia reformada (Calvino, Bavinck) enfatiza a complementaridade entre homem e mulher. 'E Deus os abençoou... frutificai, multiplicai-vos, enchei a terra, e sujeitai-a' (Gênesis 1:28).",
            referencias: "Gênesis 1:28; Gênesis 2:18-25; Gênesis 3:20; Provérbios 31:10-31; 1 Coríndios 11:7-12; Efésios 5:28-29"
        },
        {
            termo: "05. A Mulher Virtuosa de Provérbios 31 - O Modelo da Esposa Ideal",
            definicao: "Provérbios 31:10-31 descreve a mulher virtuosa (eshet chayil), o modelo da esposa ideal. Características: (1) Digna de confiança: 'o coração do seu marido confia nela' (v.11). (2) Trabalhadora: 'busca lã e linho, e trabalha de boa vontade com as mãos' (v.13). (3) Provedora: 'como os navios mercantes, ela traz de longe o seu pão' (v.14). (4) Madrugadora: 'levanta-se ainda de noite, e dá comida à sua casa' (v.15). (5) Empreendedora: 'examina uma propriedade e adquire-a; planta uma vinha com o fruto de suas mãos' (v.16). (6) Forte: 'cinge os lombos de força, e fortalece os braços' (v.17). (7) Generosa: 'abre a mão aos pobres, e estende as mãos aos necessitados' (v.20). (8) Sábia: 'abre a boca com sabedoria, e a lei da beneficência está na sua língua' (v.26). (9) Cuidadora: 'olha pela economia da sua casa, e não come o pão da preguiça' (v.27). (10) Temerosa de Deus: 'a mulher que teme ao Senhor, essa será louvada' (v.30). A teologia reformada (Calvino, Puritanos) vê em Provérbios 31 o modelo da esposa cristã. 'Muitas filhas agiram virtuosamente, mas tu a todas sobrepujaste' (Provérbios 31:29).",
            referencias: "Provérbrios 12:4; Provérbios 18:22; Provérbios 19:14; Provérbios 31:10-31; 1 Timóteo 2:9-10; 1 Pedro 3:3-4"
        },
        {
            termo: "06. A Mulher como Educadora dos Filhos - Transmissão da Fé",
            definicao: "A mãe tem um papel fundamental na educação espiritual dos filhos. 'Lembra-te do teu Criador nos dias da tua mocidade' (Eclesiastes 12:1). 'Desde criança sabes as sagradas letras, que podem fazer-te sábio para a salvação, pela fé que há em Cristo Jesus' (2 Timóteo 3:15). Exemplos bíblicos: (1) Joquebede (mãe de Moisés): ensinou Moisés sobre o Deus de Israel (Êxodo 2:1-10; Hebreus 11:23). (2) Ana (mãe de Samuel): dedicou Samuel ao Senhor (1 Samuel 1-2). (3) Eunice e Lóide (mãe e avó de Timóteo): transmitiram a fé a Timóteo (2 Timóteo 1:5; 3:14-15). (4) Maria (mãe de Jesus): criou Jesus na fé (Lucas 2:51-52). Responsabilidades da mãe: (1) Ensinar a Bíblia aos filhos. (2) Orar pelos filhos diariamente. (3) Levar os filhos à igreja. (4) Ser exemplo de fé. (5) Discipular os filhos. (6) Corrigir com amor. (7) Preparar os filhos para a vida adulta. A teologia reformada (Calvino, Puritanos) enfatiza o papel da mãe na educação cristã. 'Ensina o menino no caminho em que deve andar, e até quando envelhecer não se desviará dele' (Provérbios 22:6).",
            referencias: "Êxodo 2:1-10; 1 Samuel 1-2; Provérbios 1:8; Provérbios 6:20; Lucas 2:51-52; 2 Timóteo 1:5; 2 Timóteo 3:14-15; Hebreus 11:23"
        },
        {
            termo: "07. A Mulher como Administradora do Lar - Mordomia Doméstica",
            definicao: "A mulher tem a responsabilidade de administrar o lar (economia doméstica). 'Olha pela economia da sua casa, e não come o pão da preguiça' (Provérbios 31:27). 'Que sejam moderadas... que ensinem as mulheres novas a serem prudentes, a amarem seus maridos, a amarem seus filhos, a serem moderadas, castas, boas donas de casa' (Tito 2:4-5). Aspectos da administração doméstica: (1) Planejamento financeiro (orçamento familiar). (2) Organização da rotina diária. (3) Cuidado com a alimentação (cozinhar, comprar). (4) Cuidado com a limpeza e manutenção da casa. (5) Cuidado com as roupas (costurar, lavar). (6) Cuidado com os filhos (educação, saúde). (7) Hospitalidade (receber visitas). (8) Mordomia dos recursos de Deus (não desperdiçar). A mulher virtuosa de Provérbios 31 é um exemplo de boa administradora. A teologia reformada (Calvino, Puritanos) valoriza o trabalho doméstico como vocação sagrada. 'Portanto, quer comais quer bebais, ou façais outra qualquer coisa, fazei tudo para glória de Deus' (1 Coríndios 10:31).",
            referencias: "Provérbios 14:1; Provérbios 24:27; Provérbios 31:27; Romanos 12:11; 1 Coríndios 10:31; Tito 2:4-5"
        },
        {
            termo: "08. A Mulher como Conselheira e Aconselhadora - Sabedoria no Lar",
            definicao: "A mulher exerce influência através de seu conselho sábio. 'Abre a boca com sabedoria, e a lei da beneficência está na sua língua' (Provérbios 31:26). 'O coração do seu marido confia nela' (Provérbios 31:11). Exemplos bíblicos: (1) Abigail: com sabedoria impediu Davi de cometer vingança (1 Samuel 25). (2) Ester: aconselhou o rei Assuero (Ester 4-8). (3) Priscila: junto com Áquila, explicou o caminho de Deus a Apolo (Atos 18:26). (4) A mulher sunamita: aconselhou seu marido a hospedar Eliseu (2 Reis 4:8-10). Características do conselho sábio: (a) Baseado na Palavra de Deus. (b) Amoroso (não manipulador). (c) Respeitoso (não desautoriza o marido). (d) Oportuno (no momento certo). (e) Humilde (não arrogante). (f) Busca o bem da família. A teologia reformada (Calvino, Puritanos) valoriza a sabedoria da mulher piedosa. 'A boca do justo profere sabedoria' (Salmo 37:30).",
            referencias: "1 Samuel 25; Ester 4-8; 2 Reis 4:8-10; Provérbios 15:1; Provérbios 31:26; Atos 18:26"
        },
        {
            termo: "09. Mulheres de Influência no Antigo Testamento - Exemplos de Fé e Coragem",
            definicao: "O Antigo Testamento apresenta muitas mulheres de grande influência. (1) Sara: 'pela fé, também a mesma Sara recebeu a virtude de conceber' (Hebreus 11:11). (2) Rebeca: mãe de Jacó e Esaú, participou do plano de Deus (Gênesis 24-27). (3) Raquel e Lia: mães das tribos de Israel (Gênesis 29-30). (4) Miriã: profetisa, liderou o louvor após o êxodo (Êxodo 15:20-21). (5) Débora: profetisa e juíza em Israel (Juízes 4-5). (6) Jael: matou Sísera, o inimigo de Israel (Juízes 4:17-22; 5:24-27). (7) Ana: mãe de Samuel, modelo de oração e dedicação (1 Samuel 1-2). (8) Ester: rainha que salvou seu povo (Ester 4-8). (9) Rute: ancestral de Davi e de Cristo (Rute 1-4). (10) Hulda: profetisa consultada pelo rei Josias (2 Reis 22:14-20). A teologia reformada (Calvino, Bavinck) vê nessas mulheres exemplos de fé, coragem e obediência a Deus. 'Bem-aventurados os que ouvem a palavra de Deus e a guardam' (Lucas 11:28).",
            referencias: "Gênesis 24-27; Gênesis 29-30; Êxodo 15:20-21; Rute 1-4; 1 Samuel 1-2; 2 Reis 22:14-20; Ester 4-8; Hebreus 11:11"
        },
        {
            termo: "10. Mulheres de Influência no Novo Testamento - Discípulas e Servas de Cristo",
            definicao: "O Novo Testamento apresenta muitas mulheres que serviram a Cristo. (1) Maria, mãe de Jesus: 'Eis aqui a serva do Senhor' (Lucas 1:38). (2) Isabel: mãe de João Batista, cheia do Espírito Santo (Lucas 1:41-45). (3) Ana: profetisa que testemunhou o menino Jesus (Lucas 2:36-38). (4) Maria Madalena: primeira testemunha da ressurreição (João 20:11-18). (5) Marta e Maria de Betânia: amigas de Jesus (Lucas 10:38-42; João 11:1-44). (6) Joana, Suzana e outras mulheres que auxiliavam Jesus (Lucas 8:1-3). (7) Priscila: ensinadora ao lado de Áquila (Atos 18:26). (8) Lídia: primeira convertida na Europa, hospedeira da igreja (Atos 16:14-15,40). (9) Febe: diaconisa da igreja de Cencreia (Romanos 16:1-2). (10) Trifena, Trifosa, Pérside: trabalhadoras no Senhor (Romanos 16:12). (11) A mãe de Rufo: a quem Paulo chama de sua mãe (Romanos 16:13). (12) As quatro filhas de Filipe: profetizas (Atos 21:9). A teologia reformada (Calvino, Bavinck) celebra o papel ativo das mulheres no ministério de Jesus e na igreja primitiva. 'Não há judeu nem grego; não há servo nem livre; não há macho nem fêmea; porque todos vós sois um em Cristo Jesus' (Gálatas 3:28).",
            referencias: "Lucas 1:26-56; Lucas 2:36-38; Lucas 8:1-3; Lucas 10:38-42; João 11:1-44; João 20:11-18; Atos 16:14-15; Atos 16:40; Atos 18:26; Atos 21:9; Romanos 16:1-2; Romanos 16:12-13; Gálatas 3:28"
        },
        {
            termo: "11. A Oração da Mulher - Intercessão pela Família",
            definicao: "A oração é uma das formas mais poderosas de influência da mulher na família. 'Orai sem cessar' (1 Tessalonicenses 5:17). 'A oração fervorosa do justo pode muito em seus efeitos' (Tiago 5:16). Exemplos bíblicos: (1) Ana: orou fervorosamente por um filho (1 Samuel 1:10-18). (2) Ester: pediu orações e jejuou antes de se apresentar ao rei (Ester 4:16). (3) Maria, mãe de Jesus: perseverou em oração após a ascensão (Atos 1:14). (4) As mulheres na igreja primitiva: dedicavam-se à oração (Atos 12:12). Áreas de intercessão da mulher: (a) Pelo marido: para que seja um líder sábio e piedoso. (b) Pelos filhos: para que cresçam na fé, sejam protegidos do mal. (c) Pela família: para que haja paz, amor e unidade. (d) Por outras famílias: hospitalidade e intercessão. (e) Pela igreja: pastores, missionários, membros. (f) Pela nação: autoridades e justiça. A teologia reformada (Calvino, Puritanos) incentiva a oração como arma poderosa da mulher piedosa. 'Antes de tudo, pois, exorto que se façam deprecações, orações, intercessões e ações de graças por todos os homens' (1 Timóteo 2:1).",
            referencias: "1 Samuel 1:10-18; Ester 4:16; Atos 1:14; Atos 12:12; 1 Timóteo 2:1-2; Tiago 5:16; 1 Pedro 3:12"
        },
        {
            termo: "12. A Hospitalidade da Mulher - Abrindo o Lar para o Reino",
            definicao: "A hospitalidade é uma forma importante de influência da mulher. 'Sendo hospitaleiros uns para com os outros, sem murmuração' (1 Pedro 4:9). 'Exercendo a hospitalidade' (Romanos 12:13). Exemplos bíblicos: (1) A mulher sunamita: hospedou Eliseu (2 Reis 4:8-10). (2) Lídia: abriu sua casa para Paulo e seus companheiros (Atos 16:14-15,40). (3) Priscila e Áquila: tinham uma igreja em sua casa (Romanos 16:3-5; 1 Coríndios 16:19). (4) Febe: provavelmente hospedava a igreja (Romanos 16:1-2). (5) Maria, mãe de João Marcos: tinha uma igreja em sua casa (Atos 12:12). Aspectos da hospitalidade: (a) Abrir o lar para a igreja (cultos domésticos). (b) Receber missionários e viajantes. (c) Alimentar os necessitados. (d) Acolher os solitários. (e) Oferecer descanso para os cansados. (f) Criar um ambiente acolhedor. (g) Usar os dons culinários para o Reino. A teologia reformada (Calvino, Puritanos) valoriza a hospitalidade como expressão do amor cristão. 'Não vos esqueçais da hospitalidade, porque por ela alguns, sem o saberem, hospedaram anjos' (Hebreus 13:2).",
            referencias: "2 Reis 4:8-10; Atos 12:12; Atos 16:14-15; Atos 16:40; Romanos 12:13; Romanos 16:1-2; Romanos 16:3-5; 1 Coríndios 16:19; 1 Pedro 4:9; Hebreus 13:2"
        },
        {
            termo: "13. Síntese: A Mulher Virtuosa como Reflexo da Igreja, Noiva de Cristo",
            definicao: "A mulher virtuosa é um reflexo da igreja como noiva de Cristo. 'A mulher que teme ao Senhor, essa será louvada' (Provérbios 31:30). 'Porque zelo por vós com zelo de Deus; porque vos tenho preparado para vos apresentar como uma virgem pura a um só marido, que é Cristo' (2 Coríndios 11:2). Paralelos entre a mulher virtuosa e a igreja: (1) Submissão voluntária: a igreja se submete a Cristo; a esposa se submete ao marido. (2) Amor sacrificial: Cristo amou a igreja; a esposa ama o marido. (3) Fidelidade: Cristo é fiel à igreja; a esposa é fiel ao marido. (4) Frutificação: a igreja produz fruto; a esposa gera filhos. (5) Administração: a igreja administra os dons de Deus; a esposa administra o lar. (6) Testemunho: a igreja testemunha ao mundo; a esposa testemunha ao marido. (7) Beleza interior: a igreja é adornada com santidade; a esposa é adornada com mansidão (1 Pedro 3:3-4). A teologia reformada (Calvino, Bavinck) celebra a mulher piedosa como imagem da igreja fiel a Cristo. 'Muitas filhas agiram virtuosamente, mas tu a todas sobrepujaste' (Provérbios 31:29). 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36). Soli Deo Gloria!",
            referencias: "Romanos 11:36; 2 Coríndios 11:2; Efésios 5:25-32; Provérbios 31:10-31; 1 Pedro 3:3-4; Apocalipse 19:7-9; Apocalipse 21:2"
        }
    ]
};