// volume/volume-66.js
window.LIVRO_DATA = {
    nome: "Volume LXVI",
    dados: [
        {
            termo: "01. Introdução: A Igreja como Corpo de Cristo",
            definicao: "A igreja é o corpo de Cristo, e Cristo é a cabeça do corpo. O apóstolo Paulo escreve: 'E ele é a cabeça do corpo, da igreja' (Colossenses 1:18). 'E pôs todas as coisas debaixo de seus pés, e para ser a cabeça sobre todas as coisas o deu à igreja, que é o seu corpo, a plenitude daquele que cumpre tudo em todos' (Efésios 1:22-23). 'Porque, assim como o corpo é um e tem muitos membros, e todos os membros, sendo muitos, são um só corpo, assim é Cristo também' (1 Coríndios 12:12). A teologia reformada (Calvino, Bavinck, Berkhof) enfatiza que a igreja não é uma instituição meramente humana, mas o corpo de Cristo, onde Ele vive e age através do Espírito Santo. Este volume explora a relação entre Cristo e a igreja: a igreja como corpo de Cristo, Cristo como cabeça, as marcas da igreja verdadeira, os sacramentos, a disciplina, e a missão da igreja. 'E vos congreguemos todos em unidade, na comunhão do corpo de Cristo' (Efésios 4:13).",
            referencias: "Efésios 1:22-23; 1 Coríndios 12:12-27; Colossenses 1:18; Colossenses 2:19; Efésios 4:15-16; Romanos 12:4-5"
        },
        {
            termo: "02. Cristo como Cabeça da Igreja - Autoridade e Governo",
            definicao: "Cristo é a cabeça da igreja, o que significa que Ele tem autoridade suprema sobre ela. 'Porque o marido é a cabeça da mulher, como também Cristo é a cabeça da igreja' (Efésios 5:23). 'Não reconhecemos outro cabeça na terra senão Cristo' (Confissão de Fé de Westminster, 25.6). Implicações da cabeça de Cristo: (1) Autoridade suprema: Cristo governa sua igreja (Mateus 28:18). (2) Fonte de vida: a igreja recebe vida de Cristo (João 15:4-5). (3) Unidade: a igreja é unida sob uma cabeça (Efésios 4:4-6). (4) Crescimento: o corpo cresce quando unido à cabeça (Efésios 4:15-16). (5) Proteção: Cristo protege sua igreja (Mateus 16:18). (6) Direção: Cristo guia sua igreja (João 10:27). (7) Julgamento: Cristo julgará sua igreja (1 Pedro 4:17). A teologia reformada rejeita o papado (primado de Pedro como cabeça da igreja) e afirma que somente Cristo é a cabeça. 'Porque um é o vosso Mestre, o Cristo, e todos vós sois irmãos' (Mateus 23:8).",
            referencias: "Mateus 16:18; Mateus 23:8; João 15:4-5; Efésios 4:4-6; Efésios 4:15-16; Efésios 5:23; Colossenses 2:19; 1 Pedro 4:17"
        },
        {
            termo: "03. A Igreja como Corpo de Cristo - Unidade e Diversidade",
            definicao: "A igreja é o corpo de Cristo, composto de muitos membros com diferentes dons. 'Porque, assim como em um corpo temos muitos membros, nem todos os membros têm a mesma operação, assim nós, que somos muitos, somos um só corpo em Cristo' (Romanos 12:4-5). 'Porque todos fomos batizados em um Espírito, formando um corpo' (1 Coríndios 12:13). Características do corpo: (1) Unidade: um só corpo, um só Espírito, um só Senhor (Efésios 4:4-5). (2) Diversidade: muitos membros com diferentes funções (1 Coríndios 12:14-20). (3) Interdependência: os membros precisam uns dos outros (1 Coríndios 12:21-25). (4) Cuidado mútuo: 'se um membro padece, todos os membros padecem com ele' (1 Coríndios 12:26). (5) Cristo é a cabeça (Colossenses 1:18). (6) A igreja é a plenitude de Cristo (Efésios 1:23). A teologia reformada enfatiza que todos os crentes são membros do corpo de Cristo, independentemente de sua posição social, raça ou gênero (Gálatas 3:28). 'De sorte que, se um membro padece, todos os membros padecem com ele; e, se um membro é honrado, todos os membros se regozijam com ele' (1 Coríndios 12:26).",
            referencias: "Romanos 12:4-5; 1 Coríndios 10:17; 1 Coríndios 12:12-27; Efésios 1:23; Efésios 4:4-6; Efésios 4:15-16; Colossenses 2:19; Gálatas 3:28"
        },
        {
            termo: "04. As Marcas da Verdadeira Igreja - Pregação, Sacramentos, Disciplina",
            definicao: "As marcas da verdadeira igreja (notae ecclesiae) são os sinais que identificam onde está a igreja verdadeira. A teologia reformada (Calvino, Westminster) identifica três marcas: (1) A pregação pura da Palavra de Deus (João 8:31-32; 2 Timóteo 4:2). (2) A administração correta dos sacramentos (batismo e ceia) conforme instituídos por Cristo (Mateus 28:19; 1 Coríndios 11:23-26). (3) O exercício da disciplina eclesiástica (Mateus 18:15-20; 1 Coríndios 5:1-13). 'Onde quer que a Palavra de Deus é pregada puramente e os sacramentos são administrados conforme a instituição de Cristo, aí está a verdadeira igreja' (Calvino, Institutas IV.1.9). A Confissão de Fé de Westminster (25.3) afirma: 'A igreja católica ou universal... consiste no número total dos eleitos... e é a noiva e o corpo de Cristo'. A teologia reformada distingue entre a igreja visível (professos) e invisível (eleitos). 'Pelo que, se alguém se purificar destas coisas, será vaso para honra, santificado e idôneo para uso do Senhor' (2 Timóteo 2:21).",
            referencias: "Mateus 28:19-20; João 8:31-32; 1 Coríndios 11:23-26; Efésios 4:11-16; 2 Timóteo 4:2; Tito 1:5-9; Apocalipse 2-3"
        },
        {
            termo: "05. Os Sacramentos - Batismo e Ceia do Senhor",
            definicao: "Os sacramentos são sinais e selos da graça de Deus em Cristo. A teologia reformada (Calvino, Westminster) reconhece dois sacramentos: (1) Batismo: sinal da purificação pelo sangue de Cristo e da regeneração pelo Espírito. 'Portanto, ide, ensinai todas as nações, batizando-as em nome do Pai, e do Filho, e do Espírito Santo' (Mateus 28:19). 'Ou não sabeis que todos quantos fomos batizados em Jesus Cristo fomos batizados na sua morte?' (Romanos 6:3). (2) Ceia do Senhor (Eucaristia): sinal e selo da comunhão com Cristo crucificado e ressurreto. 'E, tomando o pão, tendo dado graças, o partiu e deu-lhes, dizendo: Isto é o meu corpo, que por vós é dado; fazei isto em memória de mim' (Lucas 22:19). 'Porque todas as vezes que comerdes este pão e beberdes este cálice anunciais a morte do Senhor, até que venha' (1 Coríndios 11:26). A teologia reformada (Calvino) ensina a presença espiritual de Cristo na Ceia (não transubstanciação, nem mero memorial). 'O cálice de bênção que abençoamos, não é a comunhão do sangue de Cristo? O pão que partimos, não é a comunhão do corpo de Cristo?' (1 Coríndios 10:16).",
            referencias: "Mateus 28:19; Lucas 22:19-20; Romanos 6:3-4; 1 Coríndios 10:16-17; 1 Coríndios 11:23-26; Gálatas 3:27; Colossenses 2:11-12; 1 Pedro 3:21"
        },
        {
            termo: "06. A Disciplina Eclesiástica - A Chaves do Reino (Mateus 18:15-20)",
            definicao: "A disciplina eclesiástica é o exercício das chaves do Reino para manter a pureza da igreja e restaurar os pecadores. 'Em verdade vos digo que tudo o que ligardes na terra será ligado no céu, e tudo o que desligardes na terra será desligado no céu' (Mateus 18:18). As chaves do Reino foram dadas a Pedro (Mateus 16:19) e à igreja (Mateus 18:18). A disciplina inclui: (1) Advertência privada (Mateus 18:15). (2) Advertência com testemunhas (Mateus 18:16). (3) Advertência à igreja (Mateus 18:17). (4) Excomunhão (Mateus 18:17; 1 Coríndios 5:1-5). (5) Restauração (2 Coríndios 2:6-8). Propósitos da disciplina: (a) Glória de Deus (1 Coríndios 5:6-8). (b) Pureza da igreja (1 Coríndios 5:6-8). (c) Restauração do pecador (Gálatas 6:1). (d) Advertência a outros (1 Timóteo 5:20). (e) Testemunho ao mundo (1 Pedro 2:12). A teologia reformada (Calvino, Westminster) enfatiza que a disciplina é essencial para a igreja verdadeira. 'Se teu irmão pecar contra ti, vai e repreende-o entre ti e ele só' (Mateus 18:15).",
            referencias: "Mateus 16:19; Mateus 18:15-20; 1 Coríndios 5:1-13; 2 Coríndios 2:5-11; Gálatas 6:1; 1 Timóteo 5:19-20; Tito 3:10-11"
        },
        {
            termo: "07. Os Dons do Espírito para a Edificação do Corpo (1 Coríndios 12-14)",
            definicao: "O Espírito Santo distribui dons espirituais (charismata) para a edificação do corpo de Cristo. 'Porque a manifestação do Espírito é dada a cada um, para o que for útil' (1 Coríndios 12:7). Listas de dons: (1) 1 Coríndios 12:8-10: palavra da sabedoria, palavra da ciência, fé, dons de curar, operação de milagres, profecia, discernimento de espíritos, variedade de línguas, interpretação de línguas. (2) Romanos 12:6-8: profecia, ministério, ensino, exortação, contribuição, presidência, misericórdia. (3) Efésios 4:11: apóstolos, profetas, evangelistas, pastores e doutores. (4) 1 Pedro 4:10-11: falar, servir. A teologia reformada (Calvino, Warfield) distingue entre dons extraordinários (apostolado, profecia, línguas, milagres) que cessaram com a conclusão do cânon, e dons ordinários (ensino, exortação, liderança, misericórdia) que continuam. 'Segui o amor, e procurai com zelo os dons espirituais' (1 Coríndios 14:1). 'Todas as coisas, porém, sejam feitas com decência e ordem' (1 Coríndios 14:40).",
            referencias: "Romanos 12:4-8; 1 Coríndios 12:1-31; 1 Coríndios 14:1-40; Efésios 4:11-13; 1 Pedro 4:10-11"
        },
        {
            termo: "08. A Igreja como Noiva de Cristo (Efésios 5:25-32; Apocalipse 19:7-9)",
            definicao: "A igreja é a noiva de Cristo, e Cristo é o noivo. 'Vós, maridos, amai vossas mulheres, como também Cristo amou a igreja e a si mesmo se entregou por ela' (Efésios 5:25). 'Este mistério é grande; digo-o, porém, a respeito de Cristo e da igreja' (Efésios 5:32). No Apocalipse, a noiva é apresentada: 'Regozijemo-nos... porque são chegadas as bodas do Cordeiro, e já a sua noiva se preparou' (Apocalipse 19:7). 'E eu, João, vi a santa cidade, a nova Jerusalém, que de Deus descia do céu, adereçada como uma esposa ataviada para o seu marido' (Apocalipse 21:2). Características da noiva: (1) Amada por Cristo (Efésios 5:25). (2) Purificada por Cristo (Efésios 5:26-27). (3) Apresentada a Cristo (Efésios 5:27). (4) Sujeita a Cristo (Efésios 5:24). (5) Prepara-se para as bodas (Apocalipse 19:7). (6) Aguarda o noivo (Mateus 25:1-13). (7) Vive em santidade (2 Coríndios 11:2). A teologia reformada vê no relacionamento noivo-noiva a expressão do amor de Cristo pela igreja. 'Porque zelo por vós com zelo de Deus; porque vos tenho preparado para vos apresentar como uma virgem pura a um só marido, que é Cristo' (2 Coríndios 11:2).",
            referencias: "Mateus 25:1-13; João 3:29; 2 Coríndios 11:2; Efésios 5:22-33; Apocalipse 19:7-9; Apocalipse 21:2; Apocalipse 21:9"
        },
        {
            termo: "09. A Igreja como Templo de Deus (1 Coríndios 3:16-17; Efésios 2:19-22)",
            definicao: "A igreja é o templo de Deus, onde o Espírito Santo habita. 'Não sabeis vós que sois o templo de Deus e que o Espírito de Deus habita em vós?' (1 Coríndios 3:16). 'Edificados sobre o fundamento dos apóstolos e dos profetas, de que Jesus Cristo é a principal pedra da esquina; no qual todo o edifício, bem ajustado, cresce para templo santo no Senhor' (Efésios 2:20-21). Características do templo: (1) Fundamento: apóstolos e profetas, com Cristo como pedra angular (Efésios 2:20). (2) Edificação: todo o edifício cresce (Efésios 2:21). (3) Habitação: Deus habita na igreja (Efésios 2:22). (4) Santidade: templo santo (1 Coríndios 3:17). (5) Sacrifícios espirituais: oferecidos pelos crentes (1 Pedro 2:5). (6) Adoração: a igreja adora a Deus (João 4:23-24). (7) Oração: casa de oração (Mateus 21:13). A teologia reformada enfatiza que a igreja é o lugar da presença de Deus na terra. 'Vós também, como pedras vivas, sois edificados casa espiritual e sacerdócio santo, para oferecer sacrifícios espirituais agradáveis a Deus por Jesus Cristo' (1 Pedro 2:5).",
            referencias: "1 Coríndios 3:16-17; 2 Coríndios 6:16; Efésios 2:19-22; 1 Pedro 2:4-5; Apocalipse 21:22"
        },
        {
            termo: "10. A Igreja como Família de Deus (Efésios 2:19; 1 Timóteo 3:15)",
            definicao: "A igreja é a família de Deus. 'Assim que já não sois estrangeiros, nem forasteiros, mas concidadãos dos santos e da família de Deus' (Efésios 2:19). 'Para que saibas como convém andar na casa de Deus, que é a igreja do Deus vivo, coluna e firmeza da verdade' (1 Timóteo 3:15). Características da família: (1) Pai: Deus é o Pai (Mateus 6:9). (2) Irmãos: os crentes são irmãos (Mateus 23:8). (3) Filhos: somos filhos de Deus (Romanos 8:14-17). (4) Herança: somos herdeiros de Deus (Romanos 8:17). (5) Amor fraternal: amai-vos uns aos outros (João 13:34-35). (6) Cuidado mútuo: levai as cargas uns dos outros (Gálatas 6:2). (7) Disciplina: o Pai disciplina seus filhos (Hebreus 12:5-11). A teologia reformada enfatiza que a igreja é uma família espiritual, não apenas uma instituição. 'E sede uns para com os outros benignos, misericordiosos, perdoando-vos uns aos outros, como também Deus vos perdoou em Cristo' (Efésios 4:32). 'Portanto, enquanto temos tempo, façamos bem a todos, mas principalmente aos domésticos da fé' (Gálatas 6:10).",
            referencias: "Mateus 6:9; João 13:34-35; Romanos 8:14-17; Efésios 2:19; 1 Timóteo 3:15; Hebreus 12:5-11; 1 Pedro 1:22; 1 João 3:1-2"
        },
        {
            termo: "11. O Governo da Igreja - Presbíteros e Diáconos (1 Timóteo 3:1-13)",
            definicao: "Cristo estabeleceu ofícios na igreja para seu governo e serviço. Os ofícios bíblicos: (1) Presbíteros (anciãos, bispos, pastores): governam, ensinam e pastoreiam a igreja. 'Apascentai o rebanho de Deus que está entre vós' (1 Pedro 5:2). Qualificações: irrepreensível, esposo de uma só mulher, moderado, hospitaleiro, apto para ensinar (1 Timóteo 3:2-7). (2) Diáconos: servem às mesas (Atos 6:1-6), cuidam dos pobres e necessitados. Qualificações: honestos, não de língua dobre, não dados a muito vinho, não cobiçosos (1 Timóteo 3:8-13). (3) A igreja (assembleia) elege os oficiais (Atos 6:3-6; 14:23). A teologia reformada (Calvino, Westminster) adota o presbiterianismo (governo por presbíteros), rejeitando o episcopado (bispos) e o congregacionalismo radical. 'E ele mesmo deu uns para apóstolos, e outros para profetas, e outros para evangelistas, e outros para pastores e doutores, para aperfeiçoamento dos santos' (Efésios 4:11-12).",
            referencias: "Atos 6:1-6; Atos 14:23; 1 Timóteo 3:1-13; Tito 1:5-9; 1 Pedro 5:1-4; Efésios 4:11-12"
        },
        {
            termo: "12. A Missão da Igreja - Evangelismo e Ação Social (Mateus 28:18-20)",
            definicao: "A missão da igreja é fazer discípulos de todas as nações. 'Ide, ensinai todas as nações, batizando-as em nome do Pai, e do Filho, e do Espírito Santo; ensinando-as a guardar todas as coisas que eu vos tenho mandado' (Mateus 28:19-20). Componentes da missão: (1) Evangelismo: proclamação do evangelho (Romanos 10:14-15). (2) Discipulado: ensino da Palavra (Mateus 28:20). (3) Batismo: incorporação na igreja (Mateus 28:19). (4) Ação social: cuidado dos pobres e necessitados (Gálatas 2:10; Tiago 1:27). (5) Missões transculturais: alcançar todas as nações (Atos 1:8). (6) Justiça social: defender o oprimido (Isaías 1:17). (7) Criação de novas igrejas (plantação de igrejas). A teologia reformada (Lausanne, 1974) afirma a 'missão integral' (evangelismo + ação social). 'Portanto, ide... e eis que estou convosco todos os dias, até à consumação do século' (Mateus 28:19-20). 'Como, pois, invocarão aquele em quem não creram? e como crerão naquele de quem não ouviram? e como ouvirão, se não há quem pregue?' (Romanos 10:14).",
            referencias: "Mateus 28:18-20; Marcos 16:15; Lucas 24:46-48; Atos 1:8; Romanos 10:13-15; Gálatas 2:10; Tiago 1:27"
        },
        {
            termo: "13. Síntese: Cristo e a Igreja - Uma União Inseparável",
            definicao: "Cristo e a igreja estão unidos em uma união inseparável. Ele é a cabeça; ela é o corpo. Ele é o noivo; ela é a noiva. Ele é a videira; ela é os ramos. Ele é o fundamento; ela é o edifício. 'Porque somos membros do seu corpo, da sua carne e dos seus ossos' (Efésios 5:30). Resumo da relação entre Cristo e a igreja: (1) Cristo é a cabeça; a igreja é o corpo (Efésios 1:22-23). (2) Cristo é o noivo; a igreja é a noiva (Efésios 5:25-32). (3) Cristo é a videira; a igreja é os ramos (João 15:1-5). (4) Cristo é a pedra angular; a igreja é o templo (Efésios 2:20-22). (5) Cristo é o Pai; a igreja é a família (Efésios 2:19). (6) Cristo é o Senhor; a igreja é a serva (Lucas 1:38). (7) Cristo é o Salvador; a igreja é a salva (Efésios 5:23). A teologia reformada celebra a união de Cristo com sua igreja. 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36). 'Aquele que testifica estas coisas diz: Certamente cedo venho. Amém. Ora vem, Senhor Jesus. A graça de nosso Senhor Jesus Cristo seja com todos vós. Amém' (Apocalipse 22:20-21). Soli Deo Gloria!",
            referencias: "João 15:1-5; Romanos 11:36; Efésios 1:22-23; Efésios 5:22-33; Colossenses 1:18; Apocalipse 19:7-9; Apocalipse 21-22"
        }
    ]
};