// volume/volume-74.js
window.LIVRO_DATA = {
    nome: "Volume LXXIV",
    dados: [
        {
            termo: "01. Introdução: A Vida Devocional Centrada em Cristo",
            definicao: "A vida devocional cristã é a prática de comunhão com Deus por meio de Jesus Cristo. 'Porque para mim o viver é Cristo, e o morrer é ganho' (Filipenses 1:21). 'Já estou crucificado com Cristo; e vivo, não mais eu, mas Cristo vive em mim' (Gálatas 2:20). A teologia reformada enfatiza que a vida devocional não é legalista (obras para ganhar salvação), nem emocionalista (experiências subjetivas), mas cristocêntrica (centrada em Cristo). A vida devocional inclui: (1) Oração (em nome de Jesus). (2) Leitura da Bíblia (Cristo em todas as Escrituras). (3) Meditação (reflexão na pessoa e obra de Cristo). (4) Louvor (adoração a Cristo). (5) Ação de graças (gratidão a Cristo). (6) Confissão de pecados (perdão em Cristo). (7) Consagração (dedicação a Cristo). Este volume explora a aplicação prática da cristologia na vida devocional diária. 'Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei' (Mateus 11:28). 'E tudo quanto fizerdes, por palavra ou por obra, fazei-o em nome do Senhor Jesus' (Colossenses 3:17).",
            referencias: "Mateus 11:28-30; João 15:1-5; Romanos 12:1-2; Gálatas 2:20; Filipenses 1:21; Colossenses 3:17; 1 Pedro 2:21"
        },
        {
            termo: "02. A Oração Cristocêntrica - Orando em Nome de Jesus",
            definicao: "A oração cristã é dirigida a Deus Pai, por meio de Jesus Cristo (o único Mediador), no Espírito Santo. 'Porque há um só Deus, e um só Mediador entre Deus e os homens, Jesus Cristo homem' (1 Timóteo 2:5). 'E tudo quanto pedirdes em meu nome, isso farei, para que o Pai seja glorificado no Filho' (João 14:13). 'Se pedirdes alguma coisa em meu nome, eu o farei' (João 14:14). O significado de orar 'em nome de Jesus': (1) Reconhecer que Jesus é o único Mediador. (2) Basear a oração nos méritos de Cristo, não nos nossos méritos. (3) Orar de acordo com a vontade de Cristo (revelada na Escritura). (4) Orar para a glória de Cristo. (5) Orar com fé na pessoa e obra de Cristo. (6) Orar em comunhão com Cristo ('se vós estiverdes em mim'). (7) Orar com a Palavra de Cristo habitando em nós ('as minhas palavras estiverem em vós'). O modelo de oração: o Pai Nosso (Mateus 6:9-13). A oração de Jesus (João 17) é o modelo de intercessão. A teologia reformada (Calvino, Owen) enfatiza que a oração é o exercício da fé em Cristo. 'Orai sem cessar' (1 Tessalonicenses 5:17). 'Perseverai na oração' (Colossenses 4:2).",
            referencias: "Mateus 6:9-13; João 14:13-14; João 15:7; João 16:23-24; João 17:1-26; Romanos 8:34; 1 Timóteo 2:5; Hebreus 4:14-16; Hebreus 7:25; 1 João 2:1-2; 1 João 5:14-15"
        },
        {
            termo: "03. O Pai Nosso - Modelo de Oração Cristocêntrica (Mateus 6:9-13)",
            definicao: "O Pai Nosso é o modelo de oração que Jesus ensinou aos seus discípulos. Análise cristocêntrica: (1) 'Pai nosso, que estás nos céus' - Somos filhos de Deus por meio de Cristo (Romanos 8:15; Gálatas 4:4-7). (2) 'Santificado seja o teu nome' - O nome de Deus é santificado em Cristo (João 12:28). (3) 'Venha o teu reino' - O reino de Deus veio em Cristo (Marcos 1:15) e será consumado na parusia (Apocalipse 11:15). (4) 'Seja feita a tua vontade, assim na terra como no céu' - Cristo fez a vontade do Pai (João 4:34; 6:38). (5) 'O pão nosso de cada dia dá-nos hoje' - Cristo é o pão da vida (João 6:35). (6) 'Perdoa-nos as nossas dívidas, assim como nós perdoamos aos nossos devedores' - O perdão é em Cristo (Efésios 4:32; Colossenses 3:13). (7) 'Não nos induzas à tentação' - Cristo foi tentado, mas venceu (Hebreus 4:15). (8) 'Livra-nos do mal' - Cristo venceu o maligno (Hebreus 2:14-15). (9) 'Porque teu é o reino, e o poder, e a glória, para sempre. Amém' - Cristo reina e a glória é sua (Filipenses 2:9-11). A teologia reformada recomenda a oração do Pai Nosso diariamente, meditando em cada petição. 'Vós orareis assim' (Mateus 6:9).",
            referencias: "Mateus 6:9-13; Lucas 11:2-4; João 4:34; João 6:35; João 12:28; Romanos 8:15; Efésios 4:32; Colossenses 3:13; Hebreus 2:14-15; Hebreus 4:15; Filipenses 2:9-11"
        },
        {
            termo: "04. A Oração de Jesus - Modelo de Intercessão (João 17)",
            definicao: "A Oração Sacerdotal de Jesus (João 17) é o modelo de intercessão. Estrutura: (1) Jesus ora por si mesmo (João 17:1-5): 'Pai, é chegada a hora; glorifica a teu Filho, para que também o teu Filho te glorifique a ti... E a vida eterna é esta: que te conheçam, a ti só, por único Deus verdadeiro, e a Jesus Cristo, a quem enviaste.' (2) Jesus ora pelos discípulos (João 17:6-19): 'Rogo por eles; não rogo pelo mundo, mas por aqueles que me deste... Pai santo, guarda-os em teu nome... Santifica-os na verdade; a tua palavra é a verdade.' (3) Jesus ora por todos os crentes (João 17:20-26): 'Não rogo somente por estes, mas também por aqueles que pela sua palavra hão de crer em mim; para que todos sejam um... para que o mundo creia que tu me enviaste.' Aplicações para a oração cristã: (a) Ore pela glória de Deus. (b) Ore pelos discípulos (crentes). (c) Ore pela unidade da igreja. (d) Ore pela santificação dos crentes. (e) Ore pela proteção contra o mal. (f) Ore pela perseverança. (g) Ore pela glorificação final. A teologia reformada vê na Oração de Jesus o modelo de intercessão pastoral. 'Orai uns pelos outros' (Tiago 5:16).",
            referencias: "João 17:1-26; Romanos 8:34; Efésios 6:18; 1 Timóteo 2:1-2; Hebreus 7:25; Tiago 5:16; 1 João 2:1"
        },
        {
            termo: "05. A Leitura Cristocêntrica da Bíblia - Encontrando Cristo nas Escrituras",
            definicao: "A leitura da Bíblia deve ser cristocêntrica, pois as Escrituras testificam de Cristo. 'Examinais as Escrituras, porque vós cuidais ter nelas a vida eterna, e são elas que de mim testificam' (João 5:39). 'E, começando por Moisés e por todos os profetas, explicava-lhes o que dele se achava em todas as Escrituras' (Lucas 24:27). 'São estas as palavras que vos disse, estando ainda convosco, que convinha que se cumprisse tudo o que de mim está escrito na lei de Moisés, e nos profetas e nos salmos' (Lucas 24:44). Práticas devocionais: (1) Leitura diária da Bíblia (um capítulo por dia). (2) Leitura de um livro inteiro de uma só vez (para contexto). (3) Uso de um plano de leitura bíblica. (4) Leitura em voz alta (para melhor compreensão). (5) Anotar versículos que apontam para Cristo. (6) Perguntar: 'Como este texto revela Cristo?' (7) Memorização de versículos sobre Cristo. (8) Estudo da Bíblia em comunidade (pequenos grupos). (9) Uso de comentários bíblicos (Calvino, Spurgeon, etc.). (10) Uso de dicionários bíblicos e concordâncias. A teologia reformada (Calvino, Spurgeon) enfatiza a leitura cristocêntrica da Bíblia. 'Lâmpada para os meus pés é a tua palavra, e luz para o meu caminho' (Salmo 119:105).",
            referencias: "Salmo 1:1-3; Salmo 119:9-16; Josué 1:8; Lucas 24:27; Lucas 24:44-45; João 5:39; Atos 17:11; 2 Timóteo 3:14-17; 2 Pedro 1:19-21"
        },
        {
            termo: "06. A Lectio Divina Reformada - Leitura, Meditação, Oração, Contemplação",
            definicao: "A Lectio Divina (leitura divina) é uma prática espiritual antiga, adaptada pela tradição reformada. Método em 4 passos: (1) Lectio (Leitura): Leia um texto bíblico lentamente, em voz alta se possível. Observe palavras ou frases que se destacam. (2) Meditatio (Meditação): Reflita sobre o texto. O que ele diz sobre Deus? Sobre Cristo? Sobre mim? O que Deus está me ensinando? (3) Oratio (Oração): Ore o texto. Agradeça, confesse, peça, interceda. Transforme as palavras da Escritura em oração. (4) Contemplatio (Contemplação): Descanse na presença de Deus. Silencie sua mente e abra seu coração para Deus. Não esforce, apenas descanse. A teologia reformada adiciona um quinto passo: (5) Actio (Ação): Aplique o texto à sua vida. O que Deus quer que você faça hoje em resposta à Palavra? Prática sugerida: 15-30 minutos diários. Escolha um evangelho (Mateus, Marcos, Lucas, João) ou uma epístola. Leia um capítulo por dia. Use um caderno para anotar insights e orações. 'Bem-aventurado o varão que... na sua lei medita de dia e de noite' (Salmo 1:1-2).",
            referencias: "Josué 1:8; Salmo 1:1-3; Salmo 63:6; Salmo 77:12; Salmo 119:97-105; Lucas 24:27; Lucas 24:44-45; Filipenses 4:8"
        },
        {
            termo: "07. Meditação em Cristo - Refletindo na Pessoa e Obra de Jesus",
            definicao: "A meditação cristã é a reflexão consciente na pessoa e obra de Jesus Cristo. Diferente da meditação oriental (esvaziamento da mente), a meditação cristã é o preenchimento da mente com Cristo. Objetos de meditação: (1) A divindade de Cristo (João 1:1-18). (2) A humanidade de Cristo (João 1:14). (3) A encarnação (Mateus 1:18-25; Lucas 1:26-38). (4) A vida e ministério de Cristo (evangelhos). (5) Os milagres de Cristo (sinais do Reino). (6) Os ensinos de Cristo (Sermão do Monte, parábolas). (7) A paixão de Cristo (Mateus 26-27; Marcos 14-15; Lucas 22-23; João 18-19). (8) A ressurreição de Cristo (Mateus 28; Marcos 16; Lucas 24; João 20-21). (9) A ascensão de Cristo (Atos 1:9-11). (10) A intercessão de Cristo (Romanos 8:34; Hebreus 7:25). (11) A segunda vinda de Cristo (1 Tessalonicenses 4:13-18; Apocalipse 19-22). Métodos de meditação: (a) Escolha um texto sobre Cristo. (b) Leia devagar. (c) Visualize a cena (se for narrativa). (d) Pergunte: 'O que este texto revela sobre Cristo?' (e) Pergunte: 'Como posso responder a Cristo?' (f) Ore sobre o texto. (g) Agradeça a Cristo. 'Em tudo, pela oração e súplica, com ação de graças, sejam conhecidas as vossas petições diante de Deus' (Filipenses 4:6).",
            referencias: "Salmo 104:34; Salmo 119:15; Salmo 119:23; Salmo 119:48; Filipenses 4:8; Colossenses 3:1-4; 1 Timóteo 4:15"
        },
        {
            termo: "08. Oração e Jejum - Disciplinas Espirituais Cristocêntricas",
            definicao: "A oração e o jejum são disciplinas espirituais que nos aproximam de Cristo. O jejum não é um meio de ganhar mérito (justificação), mas um meio de focar em Cristo (santificação). Jesus jejuou 40 dias (Mateus 4:2). Ele ensinou sobre o jejum: 'Quando jejuares, não te mostres contristado... mas unge a tua cabeça... para não pareceres aos homens que jejuas, mas a teu Pai' (Mateus 6:16-18). Propósitos do jejum: (1) Humilhação diante de Deus (Esdras 8:21). (2) Arrependimento (Joel 2:12). (3) Busca da vontade de Deus (Atos 13:2-3). (4) Libertação de opressões (Isaías 58:6). (5) Foco na oração (Neemias 1:4). (6) Crescimento espiritual. Tipos de jejum: (a) Jejum normal (abstenção de alimentos sólidos, mas líquidos permitidos). (b) Jejum total (abstenção de alimentos e líquidos - curto período). (c) Jejum parcial (abstenção de certos alimentos). (d) Jejum de Daniel (vegetais e água - Daniel 1:12). Cuidados: (a) Não jejuar por razões médicas sem orientação. (b) Não jejuar para impressionar os outros. (c) Jejum não substitui a oração (deve acompanhá-la). A teologia reformada (Calvino, Edwards) valoriza o jejum como disciplina espiritual. 'Este gênero não se expulsa senão pela oração e pelo jejum' (Mateus 17:21 - Textus Receptus).",
            referencias: "Esdras 8:21; Neemias 1:4; Isaías 58:6-7; Joel 2:12; Mateus 4:2; Mateus 6:16-18; Mateus 17:21 (TR); Atos 13:2-3; 2 Coríndios 11:27"
        },
        {
            termo: "09. O Louvor e a Adoração a Cristo - Cânticos e Hinos",
            definicao: "O louvor e a adoração são respostas a Cristo. 'Falando entre vós com salmos, e hinos, e cânticos espirituais; cantando e salmodiando ao Senhor no vosso coração' (Efésios 5:19). 'A palavra de Cristo habite em vós abundantemente, em toda a sabedoria, ensinando-vos e admoestando-vos uns aos outros, com salmos, hinos e cânticos espirituais, cantando com graça em vossos corações ao Senhor' (Colossenses 3:16). Hinos cristocêntricos: (1) Hinos do Novo Testamento (Filipenses 2:5-11; Colossenses 1:15-20; 1 Timóteo 3:16). (2) Hinos tradicionais: 'Castelo Forte' (Lutero), 'Quando eu contemplo a cruz' (Watts), 'Cristo, o Senhor, ressurgiu hoje' (Wesley), 'Graça Maravilhosa' (Newton). (3) Hinos contemporâneos: 'Shout to the Lord', 'In Christ Alone', 'Way Maker'. Práticas devocionais: (a) Cantar hinos diariamente (no culto doméstico). (b) Ouvir música cristã durante o trabalho ou deslocamento. (c) Memorizar hinos (aprender doutrina cantando). (d) Tocar instrumentos para glória de Cristo. (e) Compor hinos (se tiver o dom). A teologia reformada valoriza o louvor cristocêntrico como meio de adoração e ensino. 'Cantai ao Senhor um cântico novo, cantai ao Senhor, todas as terras' (Salmo 96:1).",
            referencias: "Salmo 96:1-4; Salmo 100:1-5; Efésios 5:19-20; Colossenses 3:16; Filipenses 2:5-11; Colossenses 1:15-20; Apocalipse 5:9-14"
        },
        {
            termo: "10. A Confissão de Pecados e o Perdão em Cristo",
            definicao: "A confissão de pecados é essencial para a vida devocional, baseada no perdão em Cristo. 'Se confessarmos os nossos pecados, ele é fiel e justo para nos perdoar os pecados e nos purificar de toda injustiça' (1 João 1:9). 'O sangue de Jesus Cristo, seu Filho, nos purifica de todo o pecado' (1 João 1:7). Práticas de confissão: (1) Confissão diária de pecados (no momento em que pecamos). (2) Exame de consciência ao final do dia (revisão dos pecados cometidos). (3) Confissão específica (não genérica). (4) Confissão com arrependimento (mudança de atitude). (5) Confissão com fé no perdão em Cristo. (6) Confissão uns aos outros (Tiago 5:16). A teologia reformada (Calvino, Owen) enfatiza que a confissão não é para obter perdão (já temos em Cristo), mas para restaurar a comunhão com Deus e com os irmãos. 'Se dissermos que não temos pecado, enganamo-nos a nós mesmos, e não há verdade em nós' (1 João 1:8). 'O que encobre as suas transgressões nunca prosperará, mas o que as confessa e deixa, alcançará misericórdia' (Provérbios 28:13).",
            referencias: "Provérbios 28:13; Romanos 3:23; Romanos 6:23; 1 João 1:7-9; 1 João 2:1-2; Tiago 5:16"
        },
        {
            termo: "11. A Ação de Graças a Cristo - Gratidão Diária",
            definicao: "A ação de graças é a resposta do crente às bênçãos de Deus em Cristo. 'Em tudo dai graças, porque esta é a vontade de Deus em Cristo Jesus para convosco' (1 Tessalonicenses 5:18). 'Dando sempre graças por tudo a nosso Deus e Pai, em nome de nosso Senhor Jesus Cristo' (Efésios 5:20). Práticas de ação de graças: (1) Agradecer diariamente pela salvação em Cristo. (2) Agradecer pelas bênçãos materiais (pão, saúde, família). (3) Agradecer nas tribulações (porque Deus as usa para o nosso bem - Romanos 8:28). (4) Manter um diário de gratidão (anotar bênçãos diárias). (5) Agradecer em oração antes das refeições. (6) Agradecer em comunidade (culto de ação de graças). A teologia reformada (Calvino, Edwards) enfatiza a gratidão como a resposta natural à graça de Deus em Cristo. 'Bendize, ó minha alma, ao Senhor, e tudo o que há em mim bendiga o seu santo nome' (Salmo 103:1). 'Portanto, quer comais quer bebais, ou façais outra qualquer coisa, fazei tudo para glória de Deus' (1 Coríndios 10:31).",
            referencias: "Salmo 103:1-5; Salmo 136:1-26; Romanos 8:28; Efésios 5:20; Filipenses 4:6; Colossenses 3:15; 1 Tessalonicenses 5:18"
        },
        {
            termo: "12. A Consagração a Cristo - Oferecendo-se a Deus",
            definicao: "A consagração é o ato de dedicar toda a vida a Cristo. 'Rogo-vos, pois, irmãos, pela compaixão de Deus, que apresenteis os vossos corpos em sacrifício vivo, santo e agradável a Deus, que é o vosso culto racional' (Romanos 12:1). 'E vós estais em Cristo Jesus' (1 Coríndios 1:30). Aspectos da consagração: (1) Corpo: usar o corpo para a glória de Deus (1 Coríndios 6:19-20). (2) Alma: amar a Deus de todo o coração (Mateus 22:37). (3) Mente: renovar a mente pela Palavra (Romanos 12:2). (4) Vontade: submeter-se à vontade de Deus (Mateus 26:39). (5) Bens: usar os recursos para o Reino (Mateus 6:19-21). (6) Tempo: usar o tempo para Deus (Efésios 5:15-16). (7) Talentos: usar os dons para servir (1 Pedro 4:10-11). (8) Relacionamentos: amar os outros como Cristo amou (João 13:34-35). Práticas de consagração: (a) Oração de consagração diária. (b) Oferecimento do trabalho a Deus. (c) Serviço na igreja. (d) Evangelismo. (e) Mordomia financeira. 'Portanto, quer comais quer bebais, ou façais outra qualquer coisa, fazei tudo para glória de Deus' (1 Coríndios 10:31).",
            referencias: "Mateus 22:37; Romanos 6:13-19; Romanos 12:1-2; 1 Coríndios 6:19-20; 2 Coríndios 8:5; Efésios 5:15-16; Colossenses 3:23-24; 1 Pedro 4:10-11"
        },
        {
            termo: "13. Síntese: Vivendo para a Glória de Cristo",
            definicao: "A vida devocional cristocêntrica pode ser resumida como 'viver para a glória de Cristo' (Soli Deo Gloria). 'Portanto, quer comais quer bebais, ou façais outra qualquer coisa, fazei tudo para glória de Deus' (1 Coríndios 10:31). 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36). Resumo da vida devocional cristocêntrica: (1) Ore em nome de Jesus (com base em seus méritos). (2) Leia a Bíblia para encontrar Cristo em todas as Escrituras. (3) Medite na pessoa e obra de Cristo. (4) Jejum como foco em Cristo (não como mérito). (5) Louve a Cristo com hinos e cânticos espirituais. (6) Confesse seus pecados, confiando no perdão em Cristo. (7) Agradeça a Deus por todas as bênçãos em Cristo. (8) Consagre toda a sua vida a Cristo. (9) Sirva a Cristo no seu trabalho, família e igreja. (10) Espere a volta de Cristo. 'Porque para mim o viver é Cristo, e o morrer é ganho' (Filipenses 1:21). 'E tudo quanto fizerdes, por palavra ou por obra, fazei-o em nome do Senhor Jesus, dando por ele graças a Deus Pai' (Colossenses 3:17). Soli Deo Gloria!",
            referencias: "Romanos 11:36; 1 Coríndios 10:31; Filipenses 1:21; Filipenses 4:4-7; Colossenses 3:17; 1 Tessalonicenses 5:16-18; 1 Pedro 4:10-11; Apocalipse 22:20-21"
        }
    ]
};