// volume/volume-98.js
window.LIVRO_DATA = {
    nome: "Volume XCVIII",
    dados: [
        {
            termo: "01. Introdução: Cristo, o Vencedor sobre o Diabo",
            definicao: "A demonologia cristã estuda a realidade dos demônios, Satanás e o juízo final sob a luz de Cristo. Cristo é aquele que veio para destruir as obras do diabo. 'Para isto o Filho de Deus se manifestou: para desfazer as obras do diabo' (1 João 3:8). Diferente de visões pagãs ou dualistas (que igualam bem e mal), a teologia reformada afirma que Satanás é uma criatura caída, limitada e já derrotada por Cristo na cruz. Características da demonologia reformada: (1) Satanás é real, não apenas um símbolo do mal (Mateus 4:1-11). (2) Satanás é uma criatura, não um deus igual a Deus (Colossenses 1:16). (3) Satanás já foi derrotado por Cristo na cruz (Colossenses 2:15). (4) Satanás ainda age, mas com poder limitado (Apocalipse 12:12). (5) Satanás não pode possuir um verdadeiro crente (1 João 5:18). (6) Satanás será lançado no lago de fogo eternamente (Apocalipse 20:10). (7) O julgamento de Satanás e seus demônios é terrível e certo (Mateus 25:41). (8) Os crentes têm autoridade em Cristo para resistir ao diabo (Tiago 4:7). (9) A armadura de Deus protege contra as astutas ciladas (Efésios 6:10-18). (10) Cristo é o Senhor sobre todos os principados e potestades (Colossenses 2:10). A teologia reformada (Calvino, Turretin, Edwards, Lloyd-Jones) ensina uma visão equilibrada: nem ignorar o diabo, nem dar-lhe atenção excessiva. 'Sede sóbrios e vigiai, porque o diabo vosso adversário anda em derredor, bramando como leão, buscando a quem possa tragar' (1 Pedro 5:8).",
            referencias: "Gênesis 3:1-15; Jó 1:6-12; Isaías 14:12-15; Ezequiel 28:11-19; Zacarias 3:1-2; Mateus 4:1-11; Mateus 12:22-29; Mateus 25:41; Lucas 10:17-20; Lucas 22:31-32; João 8:44; João 12:31; João 14:30; João 16:11; Atos 26:18; Romanos 16:20; 2 Coríntios 2:11; 2 Coríntios 4:4; 2 Coríntios 11:14; Efésios 2:2; Efésios 4:27; Efésios 6:10-18; Colossenses 2:10-15; Colossenses 2:15; 1 Tessalonicenses 2:18; 2 Tessalonicenses 2:9-10; 1 Timóteo 3:6-7; 2 Timóteo 2:26; Tiago 4:7; 1 Pedro 5:8; 1 João 2:13; 1 João 3:8; 1 João 4:4; 1 João 5:18-19; Judas 1:9; Apocalipse 12:7-12; Apocalipse 20:1-3; Apocalipse 20:7-10"
        },
        {
            termo: "02. A Origem do Mal: A Queda de Satanás",
            definicao: "Satanás e os demônios são anjos criados por Deus que caíram em pecado por sua própria vontade. 'Porque Deus não poupou os anjos que pecaram, mas lançou-os no inferno' (2 Pedro 2:4). A queda de Satanás: (1) Anjos foram criados bons e santos (Gênesis 1:31; Colossenses 1:16). (2) Alguns anjos pecaram voluntariamente, não por criação má (Ezequiel 28:15). (3) O pecado original de Satanás foi o orgulho: 'subirei ao céu, exaltarei o meu trono' (Isaías 14:13-14). (4) Satanás quis ser semelhante ao Altíssimo (Isaías 14:14). (5) Ele foi lançado do céu à terra (Lucas 10:18; Apocalipse 12:9). (6) Muitos anjos o seguiram na rebelião (Mateus 25:41; Apocalipse 12:4). (7) Esses anjos caídos são chamados de demônios, espíritos imundos (Mateus 10:1). (8) Eles estão reservados para o julgamento do grande dia (Judas 1:6). (9) Satanás tornou-se o deus deste século (2 Coríntios 4:4). (10) Ele é o príncipe das potestades do ar (Efésios 2:2). A teologia reformada (Calvino, Turretin, Hodge, Berkhof) rejeita qualquer visão dualista (bem e mal como coeternos) ou a ideia de que Deus criou anjos maus. Deus criou anjos bons; o pecado originou-se da livre vontade deles, não de Deus. 'Longe de Deus o praticar a maldade, e do Todo-Poderoso o cometer a injustiça' (Jó 34:10).",
            referencias: "Deuteronômio 32:4; Jó 34:10; Salmo 5:4; Isaías 14:12-15; Ezequiel 28:12-19; Mateus 25:41; Lucas 10:18; João 8:44; 2 Coríntios 4:4; Efésios 2:2; Colossenses 1:16; 1 Timóteo 3:6; 2 Pedro 2:4; Judas 1:6; Apocalipse 12:3-4; Apocalipse 12:7-9"
        },
        {
            termo: "03. A Queda do Homem: Satanás como Tentador",
            definicao: "Satanás tentou Adão e Eva no Éden, levando a humanidade ao pecado e à condenação. 'E a serpente era mais astuta que todas as alimárias do campo' (Gênesis 3:1). Estratégias de Satanás na tentação: (1) Questionou a Palavra de Deus: 'É assim que Deus disse?' (Gênesis 3:1). (2) Negou a verdade: 'Não morrereis' (Gênesis 3:4). (3) Distorceu o caráter de Deus: Deus como avarento e cruel (Gênesis 3:5). (4) Prometeu divindade: 'Sereis como Deus' (Gênesis 3:5). (5) Apelou aos desejos: boa para comer, agradável aos olhos, desejável para dar entendimento (Gênesis 3:6). Consequências da queda: (a) Morte espiritual (separação de Deus) (Gênesis 3:8-10). (b) Morte física (Gênesis 3:19; Romanos 5:12). (c) Maldição sobre a criação (Gênesis 3:17-18). (d) Inimizade entre a semente da serpente e a semente da mulher (Gênesis 3:15). (e) Escravidão ao pecado (Romanos 6:20). (f) Escravidão a Satanás (Efésios 2:2). (g) Condenação eterna (Romanos 5:18). O protoevangelho (Gênesis 3:15) é a primeira promessa da vitória de Cristo sobre Satanás: 'Ela te ferirá a cabeça, e tu lhe ferirás o calcanhar'. A teologia reformada (Calvino, Owen, Murray) vê a queda como histórica e real, não alegórica, e Satanás como agente real da tentação. 'Pelo que, como por um homem entrou o pecado no mundo, e pelo pecado a morte' (Romanos 5:12).",
            referencias: "Gênesis 3:1-24; Salmo 51:5; Isaías 43:27; Romanos 5:12-21; Romanos 6:20-23; Romanos 7:7-25; 1 Coríntios 15:21-22; 2 Coríntios 11:3; 2 Coríntios 11:14; 1 Timóteo 2:14; Apocalipse 12:9; Apocalipse 20:2"
        },
        {
            termo: "04. Os Nomes e Títulos de Satanás - Revelação de seu Caráter",
            definicao: "A Escritura revela o caráter e a obra de Satanás através de seus nomes e títulos. Cada nome descreve um aspecto de sua natureza maligna: (1) Satanás (adversário): opositor de Deus e dos homens (Jó 1:6; Zacarias 3:1). (2) Diabo (caluniador, acusador): acusa os irmãos dia e noite (Apocalipse 12:10). (3) Dragão: ser monstruoso, poderoso e cruel (Apocalipse 12:3,7,9). (4) Serpente antiga: o tentador no Éden, enganador astuto (Gênesis 3:1; Apocalipse 12:9; 20:2). (5) Príncipe deste mundo: exerce domínio sobre o mundo caído (João 12:31; 14:30; 16:11). (6) Príncipe das potestades do ar: governa os poderes demoníacos (Efésios 2:2). (7) Deus deste século: cega os entendimentos dos incrédulos (2 Coríntios 4:4). (8) Maligno: personificação do mal (Mateus 6:13; 13:19; 1 João 2:13-14; 5:18-19). (9) Tentador: tenta os homens a pecar (Mateus 4:3; 1 Tessalonicenses 3:5). (10) Acusador dos irmãos: acusa os eleitos diante de Deus (Apocalipse 12:10). (11) Leão que ruge: busca devorar os crentes (1 Pedro 5:8). (12) Anjo de luz: disfarça-se como mensageiro da verdade (2 Coríntios 11:14). (13) Belzebu: príncipe dos demônios (Mateus 12:24). (14) Belial: inutilidade, maldade (2 Coríntios 6:15). (15) Apoliom (destruidor): traz destruição (Apocalipse 9:11). A teologia reformada (Calvino, Owen, Lloyd-Jones) usa esses nomes para compreender a natureza multifacetada do inimigo espiritual, a fim de resistir-lhe com a armadura de Deus. 'Não ignoramos os seus desígnios' (2 Coríntios 2:11).",
            referencias: "Gênesis 3:1; Jó 1:6-12; Zacarias 3:1-2; Mateus 4:3; Mateus 6:13; Mateus 12:24; Mateus 13:19; Lucas 10:18; Lucas 22:31; João 8:44; João 12:31; João 14:30; João 16:11; 2 Coríntios 2:11; 2 Coríntios 4:4; 2 Coríntios 6:15; 2 Coríntios 11:14; Efésios 2:2; 1 Tessalonicenses 3:5; 2 Tessalonicenses 2:9; 1 Pedro 5:8; 1 João 2:13-14; 1 João 3:8; 1 João 5:18-19; Judas 1:9; Apocalipse 9:11; Apocalipse 12:3; Apocalipse 12:7-10; Apocalipse 20:2"
        },
        {
            termo: "05. A Demoniacal Possessão e Atividade Demoníaca",
            definicao: "Os demônios são espíritos imundos que podem afligir, oprimir e possuir pessoas não salvas. Eles também influenciam o mundo, as culturas e as falsas religiões. Atividades demoníacas na Escritura: (1) Possessão demoníaca: habitação de um demônio em uma pessoa não salva, controlando-a (Mateus 8:28-34; 9:32-33; 12:22; 17:14-18; Marcos 5:1-20; Lucas 8:26-39). (2) Opressão: ataques externos, enfermidades, sofrimentos (Lucas 13:11-16; Atos 10:38). (3) Tentação: incitação ao pecado (1 Coríntios 7:5; Efésios 4:27). (4) Engano: falsas doutrinas, falsos profetas, heresias (1 Timóteo 4:1; 1 João 4:1-3). (5) Falsos sinais e milagres: enganam os incrédulos (2 Tessalonicenses 2:9-10; Apocalipse 16:14). (6) Idolatria: demônios estão por trás dos ídolos (1 Coríntios 10:20; Deuteronômio 32:17). (7) Mentira: Satanás é o pai da mentira (João 8:44). (8) Acusação: acusa os crentes (Apocalipse 12:10). (9) Morte: tem o poder da morte, já vencido por Cristo (Hebreus 2:14-15). A teologia reformada (Calvino, Turretin, Hodge) distingue entre: (a) Possessão demoníaca (mais comum no NT como sinal do reino de Cristo). (b) Opressão (pode ocorrer com crentes, como no caso de Jó). (c) Influência (todos os incrédulos estão sob o poder do maligno - Efésios 2:2). Crentes verdadeiros não podem ser possuídos, pois o Espírito Santo habita neles (1 João 4:4; 1 Coríntios 6:19). 'Maior é o que está em vós do que o que está no mundo' (1 João 4:4).",
            referencias: "Levítico 20:27; Deuteronômio 18:9-14; Deuteronômio 32:17; 1 Samuel 16:14; Salmo 106:36-37; Zacarias 13:2; Mateus 4:24; Mateus 8:16; Mateus 8:28-34; Mateus 9:32-34; Mateus 10:1; Mateus 12:22-29; Mateus 12:43-45; Mateus 17:14-18; Marcos 1:23-27; Marcos 5:1-20; Marcos 7:24-30; Marcos 9:14-29; Lucas 4:33-36; Lucas 8:26-39; Lucas 9:37-43; Lucas 10:17-20; Lucas 11:14-26; Lucas 13:11-16; Atos 5:3; Atos 8:9-24; Atos 10:38; Atos 13:6-12; Atos 16:16-18; Atos 19:11-20; Romanos 8:38-39; 1 Coríntios 10:20-21; 2 Coríndios 2:11; 2 Coríndios 4:4; Efésios 6:12; 1 Timóteo 4:1-3; 2 Timóteo 2:26; Hebreus 2:14; Tiago 2:19; 1 Pedro 5:8; 1 João 3:8; 1 João 4:1-4; Apocalipse 2:13; Apocalipse 9:1-11; Apocalipse 12:9; Apocalipse 16:13-14; Apocalipse 18:2"
        },
        {
            termo: "06. A Vitória de Cristo sobre Satanás na Cruz",
            definicao: "A cruz de Cristo é a derrota decisiva e completa de Satanás e todas as hostes demoníacas. 'E, despojando os principados e potestades, os expôs publicamente e deles triunfou em si mesmo' (Colossenses 2:15). Dimensões da vitória de Cristo: (1) O Calvário esmagou a cabeça da serpente (Gênesis 3:15). (2) Cristo desfez as obras do diabo (1 João 3:8). (3) Satanás foi julgado e condenado na cruz (João 16:11). (4) O príncipe deste mundo foi expulso (João 12:31). (5) Cristo destruiu aquele que tem o poder da morte (Hebreus 2:14-15). (6) As acusações contra os eleitos foram canceladas (Colossenses 2:14). (7) Cristo levou os pecados que davam poder a Satanás (1 Pedro 2:24). (8) Os principados e potestades foram despojados e humilhados (Colossenses 2:15). (9) Satanás perdeu suas armas (Lucas 11:21-22). (10) A ressurreição confirmou a vitória (Romanos 1:4; 1 Coríntios 15:54-57). A vitória é: (a) Decisiva: já foi conquistada de uma vez por todas. (b) Real: não é meramente simbólica. (c) Progressiva: será plenamente manifestada na consumação. (d) Aplicada: os crentes participam dela pela fé. A teologia reformada (Calvino, Owen, Murray, Lloyd-Jones) celebra a cruz como o centro da vitória sobre Satanás. 'Cristo nos resgatou da maldição da lei, fazendo-se maldição por nós' (Gálatas 3:13).",
            referencias: "Gênesis 3:15; Isaías 53:10-12; Mateus 12:29; Lucas 10:18; Lucas 11:21-22; João 12:31; João 14:30; João 16:11; Romanos 6:9-10; 1 Coríntios 15:54-57; Gálatas 3:13; Colossenses 2:14-15; Hebreus 2:14-15; 1 Pedro 3:18-22; 1 João 3:8; Apocalipse 1:18; Apocalipse 5:5; Apocalipse 12:9-11"
        },
        {
            termo: "07. A Armadura de Deus - Resistindo ao Diabo",
            definicao: "Deus provê os crentes com a armadura espiritual para resistir aos ataques de Satanás. 'Revesti-vos de toda a armadura de Deus, para que possais estar firmes contra as astutas ciladas do diabo' (Efésios 6:11). A armadura de Deus (Efésios 6:14-18): (1) Cinto da verdade: viver em integridade e conhecimento da verdade revelada (João 17:17). (2) Couraça da justiça: a justiça imputada de Cristo (Romanos 3:22) e a justiça prática da santidade (Romanos 6:13). (3) Calçado da preparação do evangelho da paz: prontidão para proclamar e viver o evangelho (Isaías 52:7; Romanos 10:15). (4) Escudo da fé: confiança em Deus e em suas promessas, que apaga os dardos inflamados do maligno (1 Pedro 5:8-9). (5) Capacete da salvação: certeza da salvação e da esperança futura (1 Tessalonicenses 5:8). (6) Espada do Espírito: a Palavra de Deus, a única arma ofensiva (Mateus 4:1-11; Hebreus 4:12). (7) Oração em todo tempo: comunicação com Deus como fundamento de tudo (Lucas 18:1; 1 Tessalonicenses 5:17). Estratégias de resistência: (a) Submeter-se a Deus (Tiago 4:7). (b) Resistir ao diabo (Tiago 4:7). (c) Vigiar e orar (Mateus 26:41). (d) Ser sóbrio e vigilante (1 Pedro 5:8). (e) Não dar lugar ao diabo (Efésios 4:27). (f) Humilhar-se diante de Deus (1 Pedro 5:6). (g) Usar a Palavra de Deus como Jesus fez (Mateus 4:1-11). A teologia reformada (Calvino, Gurnall, Lloyd-Jones, Sproul) exorta os crentes a conhecerem o inimigo, mas a confiarem no poder de Deus. 'Sede sóbrios, vigiai' (1 Pedro 5:8).",
            referencias: "Jó 1:9-12; Salmo 91:11-12; Isaías 59:17; Mateus 4:1-11; Lucas 22:31-32; João 17:15-17; Romanos 6:13; Romanos 13:12; 2 Coríntios 10:3-5; Efésios 4:27; Efésios 6:10-18; 1 Tessalonicenses 5:8; 2 Timóteo 2:3-4; Tiago 4:7; 1 Pedro 5:6-9; 1 João 2:14; 1 João 4:4; 1 João 5:18"
        },
        {
            termo: "08. A Libertação e o Exorcismo na Igreja Primitiva",
            definicao: "No Novo Testamento, Jesus e os apóstolos expulsaram demônios como sinal da chegada do reino de Deus. 'Se eu expulso demônios pelo Espírito de Deus, logo é chegado a vós o reino de Deus' (Mateus 12:28). O exorcismo no NT: (1) Jesus expulsou muitos demônios (Marcos 1:34; 1:39; 3:11-12; Lucas 4:41). (2) Jesus deu autoridade aos discípulos sobre os demônios (Mateus 10:1; Marcos 6:7; Lucas 9:1). (3) Os setenta voltaram alegres porque os demônios se sujeitavam (Lucas 10:17-20). (4) Em nome de Jesus, os apóstolos expulsavam demônios (Atos 5:16; 8:7; 16:18; 19:11-12). (5) O nome de Jesus é poderoso (Atos 19:13-17). Distinções importantes: (a) O exorcismo no NT era um sinal apostólico (Marcos 16:17). (b) O foco não era o ritual, mas o nome e a autoridade de Jesus. (c) A libertação verdadeira vem pela fé em Cristo (João 8:36). (d) A igreja deve discernir entre possessão demoníaca genuína e doenças mentais (Mateus 4:24 distingue entre endemoninhados e lunáticos). (e) O poder está em Cristo, não em fórmulas ou objetos. (f) O crescimento na santidade é proteção contra opressão (Efésios 4:27). A teologia reformada (Calvino, Bavinck, Berkhof, MacArthur) ensina que o dom de exorcismo como sinal apostólico cessou, mas a autoridade sobre demônios continua na igreja através da pregação do evangelho, oração e autoridade espiritual. 'Se o Filho vos libertar, verdadeiramente sereis livres' (João 8:36).",
            referencias: "Mateus 10:1; Mateus 12:28; Marcos 1:34; Marcos 1:39; Marcos 3:15; Marcos 6:7; Marcos 9:38-40; Marcos 16:17; Lucas 9:1; Lucas 9:49-50; Lucas 10:17-20; Atos 5:16; Atos 8:6-7; Atos 16:16-18; Atos 19:11-17; Romanos 8:31-39; 1 Coríntios 12:28-30; Efésios 1:20-23; Efésios 6:10-18; Colossenses 2:10; 1 João 4:1-4"
        },
        {
            termo: "09. O Julgamento de Satanás e dos Demônios - O Terrível Fim",
            definicao: "O julgamento de Satanás e seus demônios é certo, eterno e terrível. Eles serão lançados no lago de fogo e enxofre para sempre. 'Apartai-vos de mim, malditos, para o fogo eterno, preparado para o diabo e seus anjos' (Mateus 25:41). A progressão do julgamento: (1) Primeiro julgamento: quando Satanás e os anjos caíram, foram lançados no tártaro (2 Pedro 2:4; Judas 1:6) - um estado de prisão aguardando o juízo final. (2) Julgamento na cruz: Satanás foi condenado e derrotado (João 16:11; Colossenses 2:15). (3) Expulsão do céu: Satanás foi lançado à terra (Apocalipse 12:7-12). (4) Aprisionamento por mil anos: Satanás é preso no abismo durante o milênio (Apocalipse 20:1-3). (5) Soltura final: após o milênio, Satanás é solto e engana as nações (Apocalipse 20:7-8). (6) Derrota final: Satanás é lançado no lago de fogo (Apocalipse 20:9-10). (7) Julgamento eterno: o lago de fogo é o tormento eterno para o diabo, a besta, o falso profeta e todos os ímpios (Apocalipse 20:10, 15; 21:8). Características do julgamento final: (a) Eterno: 'para todo o sempre' (Apocalipse 20:10). (b) Consciente: tormento dia e noite (Apocalipse 20:10). (c) Justo: Deus é justo ao julgar (Romanos 3:5-6). (d) Terrível: horrenda é a expectação do juízo (Hebreus 10:27). (e) Sem apelação: não há segunda chance (Hebreus 9:27). A teologia reformada (Calvino, Turretin, Shedd, Sproul) afirma a realidade do castigo eterno para Satanás e seus demônios como manifestação da justiça divina e advertência para os ímpios. 'Horrível coisa é cair nas mãos do Deus vivo' (Hebreus 10:31).",
            referencias: "Isaías 24:21-22; Ezequiel 28:16-19; Mateus 8:29; Mateus 25:41; Lucas 8:31; Lucas 10:18; João 12:31; João 16:11; Romanos 16:20; 1 Coríntios 6:3; 2 Pedro 2:4; Judas 1:6; Apocalipse 12:7-12; Apocalipse 20:1-3; Apocalipse 20:7-10; Apocalipse 20:14-15; Apocalipse 21:8"
        },
        {
            termo: "10. O Julgamento do Mundo e dos Ímpios - Terrível Expectação",
            definicao: "Assim como Satanás, os ímpios que rejeitam a Cristo também enfrentarão o terrível julgamento de Deus. 'E estes irão para o tormento eterno, mas os justos para a vida eterna' (Mateus 25:46). O julgamento final: (1) O Juiz: Jesus Cristo (João 5:22-27; Atos 17:31). (2) Os julgados: todos os que rejeitaram o evangelho (Apocalipse 20:12-15). (3) O critério: obras como evidência da fé ou incredulidade (Mateus 25:31-46; Apocalipse 20:12-13). (4) A base da condenação: rejeição de Cristo (João 3:18; 3:36). (5) O destino: lago de fogo, a segunda morte (Apocalipse 21:8). (6) A duração: eterna (Mateus 25:46; 2 Tessalonicenses 1:9). (7) A intensidade: choro e ranger de dentes (Mateus 8:12; 13:42; 22:13; 24:51; 25:30). (8) A natureza: separação eterna da presença de Deus (2 Tessalonicenses 1:9). (9) A consciência: o rico em Lucas 16:23-24 estava consciente. (10) A justiça: Deus é absolutamente justo (Romanos 3:5-6). Negando heresias: (a) Não é aniquilação (os ímpios continuam existindo em tormento). (b) Não é universalismo (nem todos serão salvos). (c) Não é purgatório (não há saída). (d) Não é segundo chance (Hebreus 9:27). O propósito do ensino sobre o juízo: (a) Levar os pecadores ao arrependimento (Atos 17:30-31). (b) Motivar a evangelização (2 Coríntios 5:10-11). (c) Consolar os justos que sofrem (2 Tessalonicenses 1:5-7). (d) Glorificar a justiça de Deus (Romanos 3:5-6). A teologia reformada (Calvino, Turretin, Hodge, Shedd, Sproul) afirma a realidade terrível do juízo eterno. 'E o pó volte à terra, como o era, e o espírito volte a Deus, que o deu' (Eclesiastes 12:7; mas o destino final é eterno).",
            referencias: "Daniel 12:2; Mateus 10:15; Mateus 11:22-24; Mateus 12:36-37; Mateus 13:41-42; Mateus 13:49-50; Mateus 22:13; Mateus 24:51; Mateus 25:30; Mateus 25:31-46; Marcos 9:43-48; Lucas 12:4-5; Lucas 16:19-31; João 5:22-29; Atos 10:42; Atos 17:31; Romanos 2:5-11; Romanos 14:10-12; 1 Coríntios 4:5; 2 Coríntios 5:10-11; 2 Tessalonicenses 1:5-10; Hebreus 6:2; Hebreus 9:27; Hebreus 10:26-31; 2 Pedro 2:9; 2 Pedro 3:7; Judas 1:6-7; Judas 1:14-15; Apocalipse 14:9-11; Apocalipse 20:11-15; Apocalipse 21:8; Apocalipse 22:15"
        },
        {
            termo: "11. A Proteção do Crente contra o Maligno",
            definicao: "Deus protege seus filhos dos ataques de Satanás, e nenhum verdadeiro crente pode ser possuído ou finalmente enganado pelo maligno. 'Sabemos que todo aquele que é nascido de Deus não peca; mas o que de Deus foi gerado conserva-se a si mesmo, e o maligno não lhe toca' (1 João 5:18). Promessas de proteção: (1) O Senhor é quem nos guarda do maligno (2 Tessalonicenses 3:3). (2) Jesus orou por Pedro para que sua fé não desfalecesse (Lucas 22:31-32). (3) O escudo da fé apaga os dardos inflamados (Efésios 6:16). (4) Maior é o que está em nós do que o que está no mundo (1 João 4:4). (5) Cristo nos livrará de toda obra má (2 Timóteo 4:18). (6) A fidelidade de Deus é a proteção contra a tentação (1 Coríntios 10:13). (7) O nome do Senhor é torre forte (Provérbios 18:10). (8) O anjo do Senhor acampa-se ao redor dos que o temem (Salmo 34:7). (9) A oração é proteção (Mateus 6:13; 26:41). (10) A Palavra de Deus é arma ofensiva (Mateus 4:1-11). O crente pode ser: (a) Tentado pelo diabo (Efésios 4:27). (b) Afligido (Jó 1-2). (c) Acusado (Apocalipse 12:10). (d) Oprimido (Atos 10:38). Mas nunca: (a) Possuído (o Espírito Santo habita no crente - 1 Coríntios 6:19). (b) Finalmente enganado (Mateus 24:24). (c) Arrancado da mão de Cristo (João 10:28-29). A teologia reformada (Calvino, Owen, Boston) ensina a segurança eterna do crente contra o poder final do maligno. 'Quem nos separará do amor de Cristo?' (Romanos 8:35).",
            referencias: "Jó 1:9-12; Salmo 34:7; Salmo 91:9-12; Provérbios 18:10; Mateus 6:13; Lucas 22:31-32; João 10:28-29; João 17:15; Romanos 8:31-39; 1 Coríntios 10:13; 2 Coríntios 12:7-10; Efésios 6:10-18; Colossenses 1:13; 2 Tessalonicenses 3:3; 2 Timóteo 4:18; Tiago 4:7; 1 Pedro 1:5; 1 Pedro 5:8-9; 1 João 2:13-14; 1 João 3:8-9; 1 João 4:4; 1 João 5:18; Judas 1:24-25"
        },
        {
            termo: "12. Síntese: Cristo, o Vencedor - Esperança no Terrível Julgamento",
            definicao: "A demonologia reformada é cristocêntrica: Cristo derrotou Satanás na cruz e voltará para julgar o mundo com justiça. Resumo final: (1) Satanás é real, uma criatura caída, não um deus igual a Deus. (2) Ele caiu por orgulho e foi lançado do céu. (3) Ele tentou Adão e Eva, trazendo o pecado à humanidade. (4) Seus nomes revelam seu caráter: adversário, acusador, tentador, enganador. (5) Demônios podem possuir e oprimir, mas crentes estão protegidos. (6) Cristo conquistou vitória decisiva sobre Satanás na cruz. (7) Os crentes devem usar a armadura de Deus para resistir. (8) O exorcismo no NT era sinal do reino; hoje a autoridade está na Palavra. (9) Satanás e seus demônios serão lançados no lago de fogo eternamente. (10) Os ímpios que rejeitam Cristo enfrentarão o mesmo terrível julgamento. (11) Os crentes estão protegidos pelo poder de Deus e nada os separará de Cristo. (12) A certeza do julgamento deve levar os pecadores ao arrependimento. (13) A vitória final é de Cristo, que voltará como Rei e Juiz. 'E aquele que estava assentado sobre o trono disse: Eis que faço novas todas as coisas. E disse-me: Escreve; porque estas palavras são fiéis e verdadeiras' (Apocalipse 21:5). A teologia reformada (Calvino, Turretin, Edwards, Lloyd-Jones, Sproul) chama a igreja a não temer o diabo, mas a temer a Deus, que pode lançar no inferno (Mateus 10:28). 'Não temas, porque eu sou contigo; não te assombres, porque eu sou teu Deus; eu te fortaleço, e te ajudo, e te sustento com a minha destra fiel' (Isaías 41:10). Soli Deo Gloria! Maranata!",
            referencias: "Gênesis 3:15; Salmo 2:1-12; Isaías 41:10; Mateus 10:28; Mateus 25:31-46; Lucas 10:19; João 12:31; Romanos 8:31-39; 1 Coríntios 15:24-26; 1 Coríntios 15:54-57; Colossenses 2:15; Hebreus 2:14-15; Tiago 4:7; 1 Pedro 5:6-9; 1 João 3:8; 1 João 4:4; Apocalipse 1:17-18; Apocalipse 5:5; Apocalipse 12:10-11; Apocalipse 20:10; Apocalipse 20:14-15; Apocalipse 21:5-8; Apocalipse 22:20-21"
        }
    ]
};