// volume/volume-55.js
window.LIVRO_DATA = {
    nome: "Volume LV",
    dados: [
        {
            termo: "01. Introdução: Cristo é o Rei dos reis",
            definicao: "A teologia política cristã afirma que Jesus Cristo é o 'Rei dos reis e Senhor dos senhores' (Apocalipse 19:16). 'Toda a autoridade me foi dada no céu e na terra' (Mateus 28:18). O Estado (governo civil) foi instituído por Deus para promover a justiça e punir o mal (Romanos 13:1-7). No entanto, o Estado não é absoluto; está sujeito a Cristo e à sua lei. Este volume explora a relação entre cristologia e política: o papel do Estado, a obediência ao governo, a resistência à tirania, a liberdade religiosa, a separação entre igreja e Estado, a justiça social, e a esperança escatológica (o reino de Cristo). 'Dai, pois, a César o que é de César, e a Deus o que é de Deus' (Mateus 22:21). 'Porque não temos aqui cidade permanente, mas buscamos a futura' (Hebreus 13:14).",
            referencias: "Mateus 22:21; Mateus 28:18; Romanos 13:1-7; Hebreus 13:14; Apocalipse 19:16; Apocalipse 22:5"
        },
        {
            termo: "02. A Instituição do Estado - Romanos 13:1-7",
            definicao: "O apóstolo Paulo ensina que o Estado foi instituído por Deus para promover o bem e punir o mal. 'Toda alma esteja sujeita às autoridades superiores; porque não há autoridade que não venha de Deus; e as que existem foram ordenadas por Deus' (Romanos 13:1). 'Porque é ministro de Deus para teu bem. Mas, se fizeres o mal, teme, pois não traz debalde a espada; porque é ministro de Deus, e vingador para castigar o que faz o mal' (Romanos 13:4). Características do Estado segundo Romanos 13: (1) Autoridade vem de Deus (não do povo, em última instância). (2) O Estado é 'ministro de Deus' (servo de Deus). (3) A 'espada' simboliza o poder coercitivo (polícia, exército, punição). (4) Os cristãos devem pagar impostos (Romanos 13:6-7). (5) A desobediência ao Estado é desobediência a Deus (exceto quando o Estado ordena algo contra Deus). A teologia reformada (Calvino, Turretin, Bavinck) ensina que o Estado é uma ordem da criação (não resultado da queda), mas é afetado pelo pecado. 'Fazei, pois, toda a obra como para o Senhor' (Colossenses 3:23). 'Pedi a paz de Jerusalém' (Salmo 122:6).",
            referencias: "Salmo 122:6; Colossenses 3:23; 1 Timóteo 2:1-2; Tito 3:1; 1 Pedro 2:13-17"
        },
        {
            termo: "03. Cristo e a Autoridade Política - A Submissão ao Governo",
            definicao: "Cristo ensinou a submissão ao governo: 'Dai, pois, a César o que é de César, e a Deus o que é de Deus' (Mateus 22:21). Ele pagou o imposto do templo (Mateus 17:24-27). Ele não resistiu às autoridades romanas (João 19:11). O apóstolo Pedro escreveu: 'Sujeitai-vos, pois, a toda ordenação humana por amor do Senhor; quer ao rei, como superior; quer aos governadores' (1 Pedro 2:13-14). Paulo também exortou: 'Admoesto-vos, pois, antes de tudo, que se façam deprecações, orações, intercessões e ações de graças por todos os homens; pelos reis, e por todos os que estão em eminência' (1 Timóteo 2:1-2). Razões para a submissão: (1) Por amor do Senhor. (2) Para não dar ocasião ao inimigo. (3) Para viver em paz. (4) Para promover a justiça. (5) Para testemunhar a Cristo. A teologia reformada afirma a submissão ao governo como regra geral, com exceções quando o governo ordena algo contra Deus. 'Antes importa obedecer a Deus do que aos homens' (Atos 5:29). 'Se é justo diante de Deus ouvir-vos mais a vós do que a Deus, julgai vós' (Atos 4:19).",
            referencias: "Mateus 17:24-27; Mateus 22:21; Atos 4:19; Atos 5:29; Romanos 13:1-7; 1 Timóteo 2:1-2; 1 Pedro 2:13-17"
        },
        {
            termo: "04. Resistência à Tirania - Quando Desobedecer ao Governo",
            definicao: "A Bíblia ensina que devemos obedecer ao governo, exceto quando o governo ordena algo contra a vontade de Deus. Exemplos bíblicos de resistência: (1) As parteiras hebreias desobedeceram ao faraó (Êxodo 1:15-21). (2) Sansão lutou contra os filisteus (Juízes 13-16). (3) Daniel orou a Deus apesar do decreto (Daniel 6). (4) Os três jovens na fornalha (Sadraque, Mesaque, Abednego) desobedeceram a Nabucodonosor (Daniel 3). (5) Os apóstolos desobedeceram ao Sinédrio: 'É necessário obedecer a Deus antes que aos homens' (Atos 5:29). (6) A igreja primitiva resistiu à perseguição romana. Teorias de resistência: (1) Resistência passiva (desobediência civil, não violenta). (2) Resistência ativa (revolução). A teologia reformada (Calvino, Turretin, Beza) desenvolveu a doutrina da resistência aos governantes tiranos. Calvino ensinou que magistrados inferiores podem resistir a um tirano. A Confissão de Fé de Westminster (1647) afirma: 'Os magistrados inferiores podem resistir aos superiores quando estes ordenam algo contra Deus.' Princípios: (a) Esgote todos os meios legais primeiro. (b) A resistência deve ser proporcional. (c) Busque a paz e a justiça. (d) Esteja disposto a sofrer pela causa justa (1 Pedro 2:19-20). 'Bem-aventurados os que são perseguidos por causa da justiça' (Mateus 5:10).",
            referencias: "Êxodo 1:15-21; Daniel 3; Daniel 6; Atos 4:19-20; Atos 5:29; 1 Pedro 2:19-20"
        },
        {
            termo: "05. O Exemplo de Cristo - Submissão, não Revolução",
            definicao: "Cristo não veio para estabelecer um reino político terreno. 'O meu reino não é deste mundo' (João 18:36). Ele recusou ser feito rei pela força (João 6:15). Ele pagou impostos (Mateus 17:24-27). Ele se submeteu a Pilatos (João 19:11). Ele não resistiu à crucificação (Mateus 26:52-54). No entanto, Cristo confrontou as autoridades quando necessário (Mateus 23:13-36). Contraste: (1) Jesus vs. os zelotes (revolucionários judeus): Jesus rejeitou a violência política. (2) Jesus vs. os fariseus: confrontou a hipocrisia religiosa, mas não incitou revolta. (3) Jesus vs. Pilatos: reconheceu a autoridade de Pilatos, mas afirmou que esta vinha de Deus (João 19:11). A teologia reformada segue o exemplo de Cristo: (a) Submissão ao governo, exceto quando ordena algo contra Deus. (b) Engajamento político (votar, servir, orar). (c) Não violência (exceto em casos de autodefesa ou guerra justa). (d) Evangelismo como prioridade, não revolução. 'Porque para isso fostes chamados, pois também Cristo padeceu por nós, deixando-nos o exemplo, para que sigais as suas pisadas' (1 Pedro 2:21). 'Aprendam os nossos também a aplicar-se às boas obras, para suprir as necessidades urgentes' (Tito 3:14).",
            referencias: "Mateus 17:24-27; Mateus 23:13-36; João 6:15; João 18:36; João 19:11; Romanos 12:18; 1 Pedro 2:21"
        },
        {
            termo: "06. Liberdade Religiosa - O Direito de Adorar a Cristo",
            definicao: "A liberdade religiosa é o direito de adorar a Deus segundo a própria consciência, sem coerção do Estado. A Bíblia ensina: (1) A fé não pode ser imposta pela força (Deuteronômio 30:19: 'escolhe, pois, a vida'). (2) Deus quer adoração voluntária, não forçada (Salmo 110:3: 'o teu povo se apresentará voluntariamente'). (3) Os apóstolos continuaram a pregar mesmo quando proibidos (Atos 4:18-20; 5:27-29). (4) A perseguição é esperada (2 Timóteo 3:12). A teologia reformada (Calvino, Turretin, a Confissão de Fé de Westminster) defende a liberdade de consciência. 'A consciência não está sujeita a leis humanas' (Westminster Confession, 20.2). 'Os cristãos não devem ser forçados a crer, mas devem ser persuadidos pela Palavra' (Calvino). Limites da liberdade religiosa: (a) Não pode violar a lei de Deus (ex.: sacrifício humano). (b) Não pode promover violência. (c) Não pode impor crenças a outros. Aplicações: (a) Ore pelos governantes (1 Timóteo 2:1-2). (b) Testemunhe com amor, não com coerção. (c) Resista pacificamente à perseguição. (d) Acolha refugiados religiosos. (e) Promova a liberdade religiosa para todos (não apenas para cristãos). 'Se o Filho vos libertar, verdadeiramente sereis livres' (João 8:36). 'Estai, pois, firmes na liberdade com que Cristo nos libertou' (Gálatas 5:1).",
            referencias: "Deuteronômio 30:19; Salmo 110:3; João 8:36; Atos 4:18-20; Atos 5:27-29; Gálatas 5:1; 2 Timóteo 3:12"
        },
        {
            termo: "07. Separação entre Igreja e Estado - Duas Esferas",
            definicao: "A doutrina das duas esferas (ou duas espadas) afirma que a igreja e o Estado são instituições distintas, com funções diferentes, ambas sob o senhorio de Cristo. Jesus disse: 'Dai, pois, a César o que é de César, e a Deus o que é de Deus' (Mateus 22:21). Funções da igreja: (1) Pregação do evangelho (Mateus 28:19). (2) Administração dos sacramentos (batismo, ceia). (3) Disciplina eclesiástica (Mateus 18:15-20). (4) Culto a Deus. Funções do Estado: (1) Promover a justiça (Romanos 13:4). (2) Punir o mal (Romanos 13:4). (3) Proteger a vida e a propriedade. (4) Manter a ordem pública. (5) Liberdade religiosa (proteger a igreja). A teologia reformada (Calvino, Kuyper) desenvolveu a doutrina da 'soberania das esferas': cada esfera (igreja, Estado, família, educação) tem sua própria autoridade sob Deus. A igreja não deve controlar o Estado (teocracia), nem o Estado deve controlar a igreja (césaropapismo, erastianismo). 'O meu reino não é deste mundo' (João 18:36). 'Porque não temos aqui cidade permanente, mas buscamos a futura' (Hebreus 13:14).",
            referencias: "Mateus 22:21; João 18:36; Romanos 13:1-7; Hebreus 13:14; 1 Pedro 2:13-17"
        },
        {
            termo: "08. Justiça Social - A Igreja e os Pobres",
            definicao: "A Bíblia ordena a justiça social: 'Aprendei a fazer bem; procurai o que é justo; ajudai o oprimido; fazei justiça ao órfão; tratai da causa das viúvas' (Isaías 1:17). 'Ele te declarou, ó homem, o que é bom; e o que o Senhor pede de ti, senão que pratiques a justiça, e ames a misericórdia, e andes humildemente com o teu Deus?' (Miqueias 6:8). Jesus leu Isaías 61:1-2 na sinagoga: 'O Espírito do Senhor é sobre mim, porque me ungiu para evangelizar os pobres... para apregoar liberdade aos cativos' (Lucas 4:18-19). A teologia reformada (especialmente na tradição da 'missão integral', Lausanne 1974) afirma que a igreja deve se envolver em justiça social. Princípios: (a) A igreja deve pregar o evangelho (evangelismo). (b) A igreja deve cuidar dos pobres (ação social). (c) A justiça social não é o evangelho, mas uma consequência do evangelho. (d) A transformação social requer transformação individual (novo nascimento). (e) A igreja deve ser uma comunidade de justiça e amor. (f) A igreja pode advogar por políticas justas, mas não deve se aliar a partidos políticos. 'A religião pura e imaculada para com Deus, o Pai, é esta: visitar os órfãos e as viúvas nas suas tribulações' (Tiago 1:27). 'Não sejamos vagarosos em cuidar dos necessitados' (Gálatas 6:10).",
            referencias: "Isaías 1:17; Miqueias 6:8; Lucas 4:18-19; Gálatas 6:10; Tiago 1:27; Tiago 2:14-17"
        },
        {
            termo: "09. Guerra e Paz - A Doutrina da Guerra Justa",
            definicao: "A Bíblia contém exemplos de guerra (Josué, Davi) e exemplos de paz (Sermão do Monte). A teologia reformada desenvolveu a 'doutrina da guerra justa' (just war theory). Condições para a guerra justa (Tomás de Aquino, Calvino, Turretin): (1) Autoridade legítima: declarada por governante legítimo (não por grupos privados). (2) Causa justa: autodefesa contra agressão, não conquista. (3) Intenção justa: paz e justiça, não vingança. (4) Último recurso: todas as alternativas pacíficas esgotadas. (5) Proporcionalidade: os benefícios superam os danos. (6) Discriminação: não alvejar civis (distinção entre combatentes e não-combatentes). (7) Probabilidade de sucesso: não guerrear se é certo perder. Jesus ensinou a não-resistência ao mal (Mateus 5:39), mas isso se aplica ao indivíduo, não ao Estado (Romanos 13:4 dá a espada ao Estado). O pacifismo cristão (menonitas, quakers) rejeita qualquer guerra, baseado no Sermão do Monte. A teologia reformada (Calvino) permitiu a guerra justa, mas com tristeza. 'Bem-aventurados os pacificadores' (Mateus 5:9). 'Se for possível, quanto estiver em vós, tende paz com todos os homens' (Romanos 12:18).",
            referencias: "Mateus 5:9; Mateus 5:38-48; Romanos 12:18-21; Romanos 13:4; 1 Pedro 2:13-14"
        },
        {
            termo: "10. O Engajamento Político do Cristão - Voto, Serviço, Advocacia",
            definicao: "O cristão deve se envolver na política? A Bíblia não ordena explicitamente o voto ou a participação partidária, mas oferece princípios. Evidências bíblicas: (1) José serviu no governo egípcio (Gênesis 41:39-45). (2) Daniel serviu no governo babilônico e persa (Daniel 1-6). (3) Neemias foi governador de Judá (Neemias 1-13). (4) Ester foi rainha (Ester 1-10). (5) Cornélio era centurião romano (Atos 10). (6) Paulo apelou a César (Atos 25:11). O cristão pode: (a) Votar (escolher líderes). (b) Servir no governo (funcionário público, juiz, legislador). (c) Advocacia (defender políticas justas). (d) Ser político (senador, deputado, prefeito, presidente). Cuidados: (1) Não idolatrar partidos políticos. (2) Não comprometer a fé por poder. (3) Não odiar os adversários políticos. (4) Lembrar que o reino de Cristo não é deste mundo (João 18:36). (5) Colocar Cristo acima da pátria. (6) Ser sal e luz (Mateus 5:13-16). 'O justo considera a causa dos pobres' (Provérbios 29:7). 'Bem-aventurada é a nação cujo Deus é o Senhor' (Salmo 33:12). 'O que governa os homens deve ser justo' (2 Samuel 23:3).",
            referencias: "Êxodo 18:21; 2 Samuel 23:3; Salmo 33:12; Provérbios 29:7; Daniel 1-6; Mateus 5:13-16; Atos 10; Romanos 13:1-7"
        },
        {
            termo: "11. O Reino de Cristo vs. Reinos Terrenos - Escatologia Política",
            definicao: "O reino de Cristo (o Reino de Deus) não é um reino político terreno. 'O meu reino não é deste mundo' (João 18:36). 'Pois o reino de Deus não é comida nem bebida, mas justiça, e paz, e alegria no Espírito Santo' (Romanos 14:17). O reino de Deus: (1) Já veio: em Cristo (Marcos 1:15). (2) Ainda virá: na parusia (Apocalipse 11:15). (3) É espiritual: nos corações dos crentes (Lucas 17:21). (4) É ético: justiça, paz, alegria. (5) É escatológico: a nova criação. A teologia reformada rejeita: (a) Teocracia (Estado controlado pela igreja). (b) Dominionismo (cristãos devem dominar todas as áreas, incluindo governo, para estabelecer o reino). (c) Cristianismo político (identificar o reino de Deus com um partido). (d) Dispensacionalismo (reino terreno de mil anos). A esperança cristã não é um reino político na terra, mas a nova criação (Apocalipse 21-22). 'Porque a nossa pátria está nos céus' (Filipenses 3:20). 'Buscai primeiro o reino de Deus e a sua justiça' (Mateus 6:33).",
            referencias: "Mateus 6:33; Marcos 1:15; Lucas 17:21; João 18:36; Romanos 14:17; Filipenses 3:20; Colossenses 1:13; Apocalipse 11:15; Apocalipse 21-22"
        },
        {
            termo: "12. Cristianismo e Democracia - Compatibilidade",
            definicao: "A democracia é um sistema político onde o poder emana do povo (governo do povo, pelo povo, para o povo). A Bíblia não prescreve uma forma de governo (monarquia, democracia, república), mas estabelece princípios. Princípios bíblicos compatíveis com a democracia: (1) Dignidade humana (imagem de Deus - Gênesis 1:26-27). (2) Participação (Êxodo 18:21-22: escolha de líderes). (3) Justiça (igualdade perante a lei). (4) Liberdade (Gálatas 5:1). (5) Prestação de contas (os líderes devem prestar contas). A teologia reformada (Kuyper, Dooyeweerd) geralmente apoia a democracia como forma de governo que respeita a liberdade de consciência e a separação entre igreja e Estado. No entanto, a democracia também tem riscos: (1) Tirania da maioria. (2) Populismo (promessas irrealistas). (3) Secularismo (exclusão da religião). (4) Relativismo moral (maioria decide o que é certo). O cristão deve: (a) Participar da democracia (votar, engajar-se). (b) Defender a liberdade religiosa. (c) Promover a justiça para todos. (d) Resistir à tirania. (e) Orar pelos líderes (1 Timóteo 2:1-2). 'Onde há justiça e equidade, aí está a bênção de Deus' (Provérbios 29:4). 'A nação que se esquece de Deus será lançada no inferno' (Salmo 9:17).",
            referencias: "Gênesis 1:26-27; Êxodo 18:21-22; Levítico 19:15; Deuteronômio 16:18-20; Salmo 9:17; Provérbios 29:4; Gálatas 5:1; 1 Timóteo 2:1-2"
        },
        {
            termo: "13. Síntese: Cristo, o Rei que Governa sobre Todas as Nações",
            definicao: "Cristo é o Rei dos reis e Senhor dos senhores (Apocalipse 19:16). Ele governa sobre todas as nações (Salmo 2:8). No entanto, seu reino não é deste mundo (João 18:36). A teologia política cristã reformada afirma: (1) O Estado foi instituído por Deus para promover a justiça (Romanos 13:1-7). (2) Os cristãos devem obedecer ao governo, exceto quando ordena algo contra Deus (Atos 5:29). (3) A resistência à tirania é permitida em certas circunstâncias (magistrados inferiores). (4) Cristo é o modelo de submissão e confronto profético. (5) A liberdade religiosa é um direito humano fundamental. (6) Igreja e Estado são esferas distintas (duas espadas). (7) A justiça social é uma responsabilidade da igreja (Tiago 1:27). (8) A guerra é justificada apenas em condições restritas (guerra justa). (9) Os cristãos devem se engajar na política (votar, servir). (10) O reino de Cristo não é político, mas espiritual e escatológico. 'Ele julgará entre as nações e corrigirá muitos povos' (Isaías 2:4). 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36). 'Aquele que testifica estas coisas diz: Certamente cedo venho. Amém. Ora vem, Senhor Jesus. A graça de nosso Senhor Jesus Cristo seja com todos vós. Amém' (Apocalipse 22:20-21). Soli Deo Gloria!",
            referencias: "Salmo 2:8; Isaías 2:4; Mateus 28:18; João 18:36; Romanos 11:36; Apocalipse 19:16; Apocalipse 22:20-21"
        }
    ]
};