// volume/volume-19.js
window.LIVRO_DATA = {
    nome: "Volume XIX",
    dados: [
        {
            termo: "01. Introdução: Cristo em Todas as Escrituras",
            definicao: "O Antigo Testamento é cristocêntrico: aponta para Jesus Cristo em profecias, tipos, figuras e teofanias. O próprio Jesus declarou: 'Examinais as Escrituras, porque vós cuidais ter nelas a vida eterna, e são elas que de mim testificam' (João 5:39). Após sua ressurreição, 'começando por Moisés e por todos os profetas, explicava-lhes o que dele se achava em todas as Escrituras' (Lucas 24:27). 'São estas as palavras que vos disse, estando ainda convosco, que convinha que se cumprisse tudo o que de mim está escrito na lei de Moisés, e nos profetas e nos salmos' (Lucas 24:44). Este volume expande o tratamento do Antigo Testamento iniciado no Volume II (Cristologia Bíblica), oferecendo uma análise detalhada de cada profecia messiânica, cada tipo cristológico e cada teofania do Antigo Testamento. A teologia reformada afirma que o Antigo Testamento não é apenas preparação para o Novo, mas é parte integrante da revelação de Cristo. 'Toda a Escritura é inspirada por Deus e útil para o ensino' (2 Timóteo 3:16).",
            referencias: "Lucas 24:27; Lucas 24:44-45; João 5:39; Atos 3:18; Atos 8:26-40; Atos 17:2-3; Romanos 1:1-4; 1 Coríntios 15:3-4; 2 Timóteo 3:16-17; 1 Pedro 1:10-12"
        },
        {
            termo: "02. Gênesis 3:15 - O Proto-Evangelho (Primeiro Evangelho)",
            definicao: "Gênesis 3:15 é chamado de 'proto-evangelho' (primeiro evangelho) porque contém a primeira promessa de um Redentor. 'E porei inimizade entre ti e a mulher, e entre a tua semente e a sua semente; esta te ferirá a cabeça, e tu lhe ferirás o calcanhar' (Gênesis 3:15). Análise detalhada: (1) Contexto: após a queda de Adão e Eva (Gênesis 3:1-13), Deus amaldiçoa a serpente (Satanás). (2) 'A semente da mulher' (zera ha'ishah): refere-se a um descendente de Eva (Cristo). Normalmente a genealogia é pelo pai (Gênesis 5:1-32), mas aqui é pela mulher, apontando para o nascimento virginal (Isaías 7:14; Mateus 1:18-25). (3) 'Ferirá a cabeça' (esmagará a cabeça): vitória decisiva sobre Satanás (Romanos 16:20; Hebreus 2:14-15). (4) 'Tu lhe ferirás o calcanhar': o sofrimento de Cristo (cruz, morte), mas não fatal (ressurreição). Interpretação messiânica: (a) A Targum (tradução aramaica) interpreta como referência ao Messias. (b) Os Pais da Igreja (Irineu, Tertuliano, Agostinho) viram Cristo aqui. (c) A teologia reformada vê Gênesis 3:15 como a primeira promessa do evangelho. 'E, se algum homem está em Cristo, nova criatura é' (2 Coríntios 5:17). A inimizade entre a semente da serpente (descrentes) e a semente da mulher (crentes) continua até a consumação (Apocalipse 20:1-10).",
            referencias: "Gênesis 3:1-24; Isaías 7:14; Mateus 1:18-25; Romanos 16:20; 1 Coríntios 15:20-28; Gálatas 4:4; Colossenses 2:13-15; Hebreus 2:14-15; 1 João 3:8; Apocalipse 12:1-17; Apocalipse 20:1-10"
        },
        {
            termo: "03. Gênesis 12:1-3 - A Promessa a Abraão (Bênção para as Nações)",
            definicao: "Deus prometeu a Abraão: 'E far-te-ei uma grande nação, e abençoar-te-ei, e engrandecerei o teu nome; e tu serás uma bênção. E abençoarei os que te abençoarem, e amaldiçoarei os que te amaldiçoarem; e em ti serão benditas todas as famílias da terra' (Gênesis 12:2-3). Análise detalhada: (1) Contexto: Deus chama Abrão (depois Abraão) para deixar sua terra e ir para Canaã (Gênesis 12:1). (2) 'Em ti serão benditas todas as famílias da terra': a promessa se cumpre em Cristo, a 'semente' (descendente) de Abraão. O apóstolo Paulo escreve: 'Ora, as promessas foram feitas a Abraão e à sua semente. Não diz: E às sementes, como falando de muitos, mas como de um só: E à tua semente, que é Cristo' (Gálatas 3:16). (3) A bênção de Abraão vem sobre os gentios pela fé em Cristo: 'a fim de que a bênção de Abraão chegasse aos gentios por Jesus Cristo, e para que pela fé recebêssemos a promessa do Espírito' (Gálatas 3:14). (4) Os crentes são filhos de Abraão pela fé (Romanos 4:11-12; Gálatas 3:7-9). A teologia reformada vê na promessa a Abraão a inclusão dos gentios na aliança da graça, cumprida em Cristo.",
            referencias: "Gênesis 12:1-3; Gênesis 15:1-21; Gênesis 17:1-27; Gênesis 22:15-18; Atos 3:25-26; Romanos 4:1-25; Gálatas 3:6-29; Efésios 2:11-22; Hebreus 6:13-15"
        },
        {
            termo: "04. Gênesis 14:18-20 - Melquisedeque, Tipo do Sacerdócio de Cristo",
            definicao: "Melquisedeque, rei de Salém (paz) e sacerdote do Deus Altíssimo, abençoou Abraão e recebeu dízimos dele (Gênesis 14:18-20). O Salmo 110:4 profetiza que o Messias seria 'sacerdote para sempre, segundo a ordem de Melquisedeque'. A Epístola aos Hebreus desenvolve este tipo (Hebreus 5:6,10; 6:20; 7:1-28). Análise detalhada: (1) Quem era Melquisedeque? (a) Rei de Salém (Jerusalém). (b) Sacerdote do Deus Altíssimo (Elyon). (c) Abençoou Abraão (o maior abençoa o menor, Hebreus 7:7). (d) Recebeu dízimos de Abraão (Hebreus 7:4-6). (2) Tipos de Melquisedeque em relação a Cristo: (a) 'Sem pai, sem mãe, sem genealogia' (Hebreus 7:3) - não no sentido literal, mas tipológico: seu sacerdócio não depende de linhagem levítica. (b) 'Sacerdote para sempre' (Hebreus 7:3) - Cristo é sacerdote eterno. (c) 'Rei de justiça' (Melquisedeque) e 'Rei de paz' (rei de Salém) - Cristo é Rei de justiça e paz (Isaías 9:6-7). (3) Superioridade do sacerdócio de Cristo sobre o levítico: (a) Levítico (descendente de Abraão) pagou dízimos a Melquisedeque (em Abraão, Hebreus 7:9-10). (b) O sacerdócio levítico era temporário; o de Melquisedeque é eterno. (c) Cristo é sacerdote 'segundo a ordem de Melquisedeque' (Hebreus 5:6,10). A teologia reformada vê em Melquisedeque um tipo claro do sacerdócio eterno de Cristo, que não depende de genealogia e é superior ao sacerdócio levítico.",
            referencias: "Gênesis 14:18-20; Salmo 110:4; Hebreus 5:6; Hebreus 5:10; Hebreus 6:20; Hebreus 7:1-28"
        },
        {
            termo: "05. Gênesis 22:1-18 - O Sacrifício de Isaque (Tipo da Morte de Cristo)",
            definicao: "Deus ordenou a Abraão que oferecesse seu filho Isaque em holocausto no monte Moriá (Gênesis 22:2). Abraão obedeceu, mas no último momento Deus proveu um carneiro em lugar de Isaque (Gênesis 22:13). Este evento é um tipo da morte de Cristo. Análise detalhada: (1) Paralelos entre Isaque e Cristo: (a) 'Toma teu filho, o teu único filho, Isaque' (Gênesis 22:2) - Jesus é o Filho único de Deus (João 3:16). (b) 'Oferece-o em holocausto' (Gênesis 22:2) - Jesus foi oferecido em sacrifício (Efésios 5:2). (c) Isaque carregou a lenha (Gênesis 22:6) - Jesus carregou a cruz (João 19:17). (d) 'Deus proverá para si o cordeiro' (Gênesis 22:8) - Deus proveu o Cordeiro (Cristo, João 1:29). (e) Isaque foi libertado no terceiro dia (tipologicamente) - Cristo ressuscitou ao terceiro dia (1 Coríntios 15:4). (2) O monte Moriá: tradicionalmente identificado com o monte do templo em Jerusalém, onde Jesus foi crucificado (2 Crônicas 3:1). (3) O carneiro (Gênesis 22:13): substituiu Isaque, apontando para Cristo como nosso substituto (expiação vicária, 2 Coríntios 5:21). (4) A promessa: 'Em tua semente serão benditas todas as nações' (Gênesis 22:18) - cumprida em Cristo (Gálatas 3:16). A teologia reformada vê no sacrifício de Isaque um tipo claro da morte substitutiva de Cristo.",
            referencias: "Gênesis 22:1-18; 2 Crônicas 3:1; João 1:29; João 3:16; João 19:17; Romanos 8:32; 2 Coríntios 5:21; Gálatas 3:16; Efésios 5:2; Hebreus 11:17-19; Tiago 2:21-23"
        },
        {
            termo: "06. Êxodo 12:1-28 - O Cordeiro Pascal (Tipo da Morte de Cristo)",
            definicao: "O cordeiro pascal foi sacrificado na noite da Páscoa (Pessach) no Egito, e seu sangue foi colocado nos umbrais das portas para proteger os israelitas da morte (Êxodo 12:1-28). O apóstolo Paulo identifica Cristo com o Cordeiro Pascal: 'Cristo, nossa Páscoa, foi sacrificado por nós' (1 Coríntios 5:7). João Batista também identifica Jesus como 'o Cordeiro de Deus, que tira o pecado do mundo' (João 1:29). Análise detalhada: (1) Paralelos entre o cordeiro pascal e Cristo: (a) 'um cordeiro sem defeito' (Êxodo 12:5) - Cristo sem pecado (Hebreus 4:15; 1 Pedro 1:19). (b) 'sacrificado... ao anoitecer' (Êxodo 12:6) - Cristo morreu na cruz ao entardecer (Mateus 27:45-50). (c) 'o sangue... nos umbrais' (Êxodo 12:7) - o sangue de Cristo nos protege da ira de Deus (Romanos 5:9). (d) 'comerei a carne... assada no fogo' (Êxodo 12:8-9) - Cristo é alimento espiritual (João 6:51-58). (e) 'nenhum osso lhe quebrareis' (Êxodo 12:46) - nenhum osso de Cristo foi quebrado na cruz (João 19:33-36). (f) 'Festa dos Pães Asmos' (Êxodo 12:15-20) - Cristo, o pão sem fermento (purificação do pecado). (2) A libertação do Egito (escravidão) é tipo da libertação do pecado (Romanos 6:6-7, 17-18). (3) A Páscoa cristã é a Ceia do Senhor (Lucas 22:19-20). A teologia reformada vê no cordeiro pascal o tipo mais claro da expiação vicária de Cristo.",
            referencias: "Êxodo 12:1-28; Levítico 23:5; Números 9:1-14; Deuteronômio 16:1-8; João 1:29; João 1:36; João 19:33-36; Romanos 5:9; 1 Coríntios 5:7; 1 Pedro 1:18-19; Apocalipse 5:6-14"
        },
        {
            termo: "07. Êxodo 16:1-36 - O Maná (Tipo do Pão da Vida)",
            definicao: "Deus deu o maná (pão do céu) para alimentar os israelitas no deserto (Êxodo 16:1-36). Jesus se identificou como o 'verdadeiro pão do céu': 'Eu sou o pão da vida; aquele que vem a mim não terá fome; e quem crê em mim nunca terá sede' (João 6:35). 'Eu sou o pão vivo que desceu do céu; se alguém comer deste pão, viverá para sempre; e o pão que eu darei é a minha carne, que eu darei pela vida do mundo' (João 6:51). Análise detalhada: (1) Paralelos entre o maná e Cristo: (a) Desceu do céu (Êxodo 16:4; João 6:33,38,50). (b) Era dom gratuito (Êxodo 16:15 - 'que é isto?', maná) - Cristo é dom gratuito de Deus (Romanos 6:23). (c) Devia ser colhido diariamente (Êxodo 16:4) - devemos buscar a Cristo diariamente. (d) Sustentava a vida (Êxodo 16:35) - Cristo é a vida (João 11:25). (e) O maná foi dado no deserto (peregrinação) - Cristo nos sustenta na peregrinação terrena. (2) O maná era um 'tipo' (figura) da Ceia do Senhor (Eucaristia): 'Nossos pais comeram o maná no deserto... eu sou o pão da vida' (João 6:49-51). (3) O maná foi cessado quando Israel entrou em Canaã (Josué 5:12) - o tipo encontra seu cumprimento em Cristo. A teologia reformada vê no maná o tipo do alimento espiritual que é Cristo (a Palavra, a Ceia).",
            referencias: "Êxodo 16:1-36; Números 11:4-9; Deuteronômio 8:3; Neemias 9:15; Salmo 78:23-25; João 6:31-58; 1 Coríntios 10:3; Apocalipse 2:17"
        },
        {
            termo: "08. Êxodo 17:1-7 - A Rocha Ferida (Tipo de Cristo Ferido)",
            definicao: "Em Meribá, Moisés feriu a rocha com sua vara, e dela jorrou água para o povo (Êxodo 17:1-7; Números 20:7-13). O apóstolo Paulo identifica a rocha com Cristo: 'E beberam todos da mesma bebida espiritual, porque bebiam da pedra espiritual que os seguia; e a pedra era Cristo' (1 Coríntios 10:4). Análise detalhada: (1) Paralelos entre a rocha e Cristo: (a) A rocha foi ferida (Êxodo 17:6) - Cristo foi ferido (Isaías 53:5). (b) A rocha ferida produziu água (Êxodo 17:6) - Cristo ferido produz água viva (João 4:10-14; 7:37-39). (c) A água saciou a sede do povo - Cristo sacia a sede espiritual. (d) A rocha seguia o povo (tradição rabínica) - Cristo está sempre conosco (Mateus 28:20). (2) O pecado de Moisés: em Números 20:7-13, Moisés feriu a rocha duas vezes (em vez de falar com ela), tipologicamente, Cristo foi ferido uma só vez (Hebreus 9:28). (3) A água da rocha é tipo do Espírito Santo (João 7:37-39). A teologia reformada vê na rocha ferida um tipo da expiação de Cristo e do dom do Espírito Santo.",
            referencias: "Êxodo 17:1-7; Números 20:7-13; Salmo 78:15-16; Salmo 105:41; Isaías 48:21; João 4:10-14; João 7:37-39; 1 Coríntios 10:4; Hebreus 9:28"
        },
        {
            termo: "09. Números 21:4-9 - A Serpente de Bronze (Tipo da Crucificação)",
            definicao: "Israel pecou contra Deus, e Deus enviou serpentes abrasadoras que mataram muitos. Moisés, a mando de Deus, fez uma serpente de bronze e a colocou sobre uma haste; quem olhasse para ela viveria (Números 21:4-9). Jesus se identificou com a serpente de bronze: 'E, como Moisés levantou a serpente no deserto, assim importa que o Filho do Homem seja levantado; para que todo aquele que nele crê não pereça, mas tenha a vida eterna' (João 3:14-15). Análise detalhada: (1) Paralelos entre a serpente de bronze e Cristo: (a) A serpente foi 'levantada' (Números 21:8-9) - Cristo foi 'levantado' na cruz (João 12:32-33). (b) A serpente tinha forma de serpente (mas não era venenosa) - Cristo 'foi feito pecado por nós' (2 Coríntios 5:21), mas não tinha pecado. (c) Quem olhava para a serpente vivia - quem crê em Cristo tem vida eterna (João 3:16). (d) O veneno das serpentes (pecado) causa morte; a serpente de bronze (Cristo) cura. (2) A serpente é um símbolo de maldição (Gênesis 3:14), mas Cristo se fez maldição por nós (Gálatas 3:13). (3) O 'levantamento' na cruz é a exaltação de Cristo (João 12:32-33). A teologia reformada vê na serpente de bronze um tipo claro da expiação vicária: Cristo assumiu a forma de pecado (sem pecado) para que os que creem nele tenham vida.",
            referencias: "Números 21:4-9; 2 Reis 18:4; Isaías 45:22; João 3:14-15; João 12:32-33; 2 Coríntios 5:21; Gálatas 3:13"
        },
        {
            termo: "10. Deuteronômio 18:15-19 - O Profeta como Moisés",
            definicao: "Moisés profetizou: 'O Senhor teu Deus te levantará um profeta do meio de ti, de teus irmãos, como eu; a ele ouvireis' (Deuteronômio 18:15). Pedro identifica Jesus como este profeta: 'Porque Moisés disse... Um profeta o Senhor vosso Deus vos levantará dentre vossos irmãos, como eu; a ele ouvireis em todas as coisas em que vos falar' (Atos 3:22-23). Estêvão também fez a mesma identificação (Atos 7:37). Análise detalhada: (1) Paralelos entre Moisés e Cristo: (a) Moisés foi libertador do Egito (escravidão) - Cristo é libertador do pecado (Romanos 6:18). (b) Moisés foi mediador da antiga aliança (Êxodo 19-24) - Cristo é mediador da nova aliança (Hebreus 8:6). (c) Moisés deu a lei - Cristo dá a graça (João 1:17). (d) Moisés conduziu o povo a Canaã - Cristo nos conduz à nova criação. (2) 'Profeta como Moisés' (Deuteronômio 34:10-12): Moisés foi o maior profeta do AT, mas Jesus é maior (Hebreus 3:1-6). (3) 'A ele ouvireis': a autoridade de Cristo é superior à de Moisés (Mateus 17:5). (4) Jesus cumpriu este ofício como Profeta (ensinou, pregou, revelou o Pai). A teologia reformada vê em Deuteronômio 18:15-19 uma profecia clara do ministério profético de Cristo (João 6:14; 7:40; Atos 3:22-23).",
            referencias: "Deuteronômio 18:15-19; Deuteronômio 34:10-12; João 1:17; João 6:14; João 7:40; Atos 3:22-23; Atos 7:37; Hebreus 3:1-6; Hebreus 8:6"
        },
        {
            termo: "11. 2 Samuel 7:12-16 - A Aliança Davídica (O Filho de Davi)",
            definicao: "Deus prometeu a Davi: 'Quando teus dias forem completos e descansares com teus pais, então farei levantar depois de ti a tua posteridade, que procederá de ti, e estabelecerei o seu reino. Este edificará uma casa ao meu nome, e eu firmarei o trono do seu reino para sempre' (2 Samuel 7:12-13). A aliança davídica promete um descendente (filho) de Davi que reinaria para sempre. Jesus é o 'Filho de Davi' (Mateus 1:1; Lucas 1:32-33; Romanos 1:3). Análise detalhada: (1) A promessa: (a) Uma 'casa' (dinastia). (b) Um 'trono' (reino). (c) 'Para sempre' (eternidade). (2) Cumprimento em Cristo: (a) Jesus é descendente de Davi (Mateus 1:1-17; Lucas 3:23-38). (b) O anjo Gabriel anunciou: 'O Senhor Deus lhe dará o trono de Davi, seu pai; e reinará para sempre na casa de Jacó, e o seu reino não terá fim' (Lucas 1:32-33). (c) Jesus reinou na cruz ('Rei dos judeus', João 19:19), reina agora (à direita do Pai), e reinará eternamente. (3) O 'Filho' de Deus: 'Eu lhe serei por pai, e ele me será por filho' (2 Samuel 7:14) - aplicado a Cristo (Hebreus 1:5). (4) A aliança davídica é incondicional (Deus prometeu); Cristo a cumpriu. A teologia reformada vê em 2 Samuel 7:12-16 a promessa do reinado eterno de Cristo (Apocalipse 11:15).",
            referencias: "2 Samuel 7:12-16; 1 Crônicas 17:11-14; Salmo 89:3-4; Salmo 89:35-37; Salmo 132:11-12; Isaías 9:6-7; Isaías 11:1-2; Jeremias 23:5-6; Jeremias 33:14-16; Ezequiel 34:23-24; Ezequiel 37:24-25; Lucas 1:32-33; Romanos 1:3; Hebreus 1:5"
        },
        {
            termo: "12. O Livro de Isaías: O Evangelho do Antigo Testamento",
            definicao: "O livro de Isaías tem sido chamado de 'o quinto evangelho' ou 'o evangelho do Antigo Testamento', por suas muitas profecias messiânicas. Análise detalhada das principais: (1) Isaías 7:14 - 'Eis que a virgem conceberá, e dará à luz um filho, e chamará o seu nome Emanuel' (cumprida em Mateus 1:22-23). (2) Isaías 9:6-7 - 'Porque um menino nos nasceu, um filho se nos deu... e será o seu nome: Maravilhoso, Conselheiro, Deus Forte, Pai da Eternidade, Príncipe da Paz' (títulos divinos aplicados a Cristo). (3) Isaías 11:1-2 - 'Porque brotará um rebento do tronco de Jessé, e das suas raízes um renovo frutificará. E repousará sobre ele o Espírito do Senhor' (cumprida em Jesus batizado, Mateus 3:16). (4) Isaías 35:5-6 - 'Então os olhos dos cegos serão abertos... o coxo saltará como cervo' (cumprida nos milagres de Jesus, Mateus 11:2-6). (5) Isaías 42:1-4 - 'Eis aqui o meu servo... porei sobre ele o meu Espírito' (Cristo, o servo sofredor). (6) Isaías 49:6 - 'Pouco é que sejas meu servo... também te darei como luz dos gentios' (Cristo, luz para as nações). (7) Isaías 50:4-11 - 'O Senhor Deus me abriu os ouvidos, e eu não fui rebelde' (Cristo, servo obediente). (8) Isaías 52:13-53:12 - O capítulo mais importante sobre o Servo Sofredor: (a) 'Desprezado e o mais rejeitado entre os homens' (52:3). (b) 'Ele foi traspassado pelas nossas transgressões e moído pelas nossas iniquidades' (53:5). (c) 'Pelas suas pisaduras fomos sarados' (53:5). (d) 'O Senhor fez cair sobre ele a iniquidade de todos nós' (53:6). (e) 'Levou sobre si o pecado de muitos e intercedeu pelos transgressores' (53:12). (9) Isaías 61:1-3 - 'O Espírito do Senhor Deus está sobre mim' (Jesus leu este texto na sinagoga de Nazaré e disse: 'Hoje se cumpriu esta Escritura', Lucas 4:18-21). A teologia reformada vê em Isaías a mais rica cristologia do Antigo Testamento.",
            referencias: "Isaías 7:14; Isaías 9:6-7; Isaías 11:1-2; Isaías 35:5-6; Isaías 42:1-4; Isaías 49:6; Isaías 50:4-11; Isaías 52:13-53:12; Isaías 61:1-3; Mateus 1:22-23; Mateus 3:16; Mateus 11:2-6; Lucas 4:16-21; João 1:29; Atos 8:26-40; 1 Pedro 2:22-25"
        },
        {
            termo: "13. Síntese: Cristo, o Cumprimento do Antigo Testamento",
            definicao: "O Antigo Testamento não é um livro isolado, mas uma preparação, prefiguração e promessa que encontra seu cumprimento (telos) em Jesus Cristo. 'Porque todas quantas promessas há de Deus, são nele sim, e por ele amém, para glória de Deus por nós' (2 Coríntios 1:20). A hermenêutica reformada afirma que o Antigo Testamento deve ser lido à luz de Cristo (Lucas 24:27,44-45). Os tipos (Adão, Melquisedeque, Isaque, José, Moisés, Josué, Davi, Jonas) apontam para Cristo. As profecias (Isaías 53; Salmo 22; Miqueias 5:2; Zacarias 9:9; etc.) se cumpriram em Cristo. As teofanias (aparições do Anjo do Senhor) são manifestações do Verbo pré-encarnado. A Lei (cerimonial) aponta para o sacrifício de Cristo. O sacerdócio aponta para Cristo como Sumo Sacerdote. O templo aponta para Cristo como a habitação de Deus. O sábado aponta para o descanso em Cristo. As festas (Páscoa, Pentecostes, Tabernáculos) apontam para a obra redentora de Cristo. 'Não penseis que vim destruir a lei ou os profetas; não vim destruir, mas cumprir' (Mateus 5:17). A teologia reformada conclui que o Antigo Testamento é cristocêntrico e que Cristo é a chave hermenêutica para toda a Escritura.",
            referencias: "Mateus 5:17; Lucas 24:27; Lucas 24:44-45; João 5:39; Atos 10:43; Romanos 10:4; 2 Coríntios 1:20; Gálatas 3:24; Colossenses 2:17; Hebreus 8:5; Hebreus 10:1; 1 Pedro 1:10-12"
        }
    ]
};