// volume/volume-86.js
window.LIVRO_DATA = {
    nome: "Volume LXXXVI",
    dados: [
        {
            termo: "01. Introdução: Cristo, a Palavra Viva e a Comunicação",
            definicao: "Cristo é a Palavra (Logos) de Deus, a comunicação divina por excelência. 'No princípio era o Verbo, e o Verbo estava com Deus, e o Verbo era Deus' (João 1:1). 'E o Verbo se fez carne, e habitou entre nós' (João 1:14). Deus se comunicou conosco através de seu Filho, a Palavra encarnada. A teologia reformada (Calvino, Kuyper) enfatiza que a comunicação é um dom de Deus e deve ser usada para sua glória. Este volume explora: (1) Cristo como a Palavra. (2) A comunicação cristã na mídia tradicional (rádio, TV, imprensa). (3) Redes sociais e cristianismo (Facebook, Instagram, WhatsApp, YouTube, TikTok). (4) Evangelismo digital. (5) Ética da comunicação cristã. (6) Discernimento digital. (7) O futuro da comunicação cristã. 'Toda a Escritura é inspirada por Deus e útil para o ensino' (2 Timóteo 3:16). 'Falando entre vós com salmos, e hinos, e cânticos espirituais' (Efésios 5:19).",
            referencias: "João 1:1-14; João 14:6; Atos 2:1-11; 1 Coríndios 14:6-12; Efésios 4:15; Efésios 5:19; Colossenses 4:6; 2 Timóteo 3:16-17"
        },
        {
            termo: "02. Cristo como a Palavra (Logos) - A Comunicação Suprema de Deus",
            definicao: "Cristo é a Palavra de Deus, a comunicação definitiva do Pai à humanidade. 'Havendo Deus antigamente falado muitas vezes e de muitas maneiras pelos profetas, a nós falou-nos nestes últimos dias pelo Filho' (Hebreus 1:1-2). 'Quem me vê a mim vê o Pai' (João 14:9). A comunicação de Cristo é: (1) Encarnada: Deus se fez carne (João 1:14). (2) Clara: Jesus falou de forma compreensível (Mateus 13:10-17). (3) Verdadeira: 'Eu sou a verdade' (João 14:6). (4) Amorosa: 'Deus amou o mundo' (João 3:16). (5) Salvífica: 'as palavras que eu vos disse são espírito e são vida' (João 6:63). (6) Poderosa: 'a palavra de Deus é viva e eficaz' (Hebreus 4:12). (7) Universal: 'Ide, ensinai todas as nações' (Mateus 28:19). A comunicação cristã deve imitar a comunicação de Cristo: encarnada (contextualizada), clara, verdadeira, amorosa, salvífica, poderosa e universal. 'A vossa palavra seja sempre agradável, temperada com sal, para que saibais como vos convém responder a cada um' (Colossenses 4:6).",
            referencias: "João 1:1-18; João 6:63; João 14:6; João 14:9; Atos 20:27; Hebreus 1:1-2; Hebreus 4:12"
        },
        {
            termo: "03. Mídia Cristã - Rádio, TV e Imprensa",
            definicao: "Os meios de comunicação tradicionais (rádio, televisão, jornais, revistas, livros) têm sido usados para a propagação do evangelho. História: (1) Rádio: primeiras transmissões cristãs nos anos 1920. Redes como Rádio Trans Mundial (Rádio HCJB, Equador), Rádio Bíblica. (2) Televisão: programas evangélicos nos anos 1950-1960 (Billy Graham, Rex Humbard). Redes como TV Canção Nova (católica), TV Novo Tempo (adventista), TV Boas Novas, TV Evangelizar. (3) Imprensa: Bíblias, livros, revistas (A Bíblia Sagrada, a revista 'Cristianismo Hoje', 'Ultimato', 'Fiel'). Vantagens: (a) Alcance de massa. (b) Penetração em áreas remotas. (c) Baixo custo por pessoa. (d) Possibilidade de evangelismo em países fechados. Desafios: (a) Conteúdo superficial (pouco tempo). (b) Falta de discipulado (somente informação). (c) Riscos de heresias (falta de supervisão). (d) Custos elevados. (e) Concorrência com mídia secular. A teologia reformada (Calvino, Kuyper) incentiva o uso da mídia para o Reino, com responsabilidade. 'Pregai a palavra, instes a tempo e fora de tempo' (2 Timóteo 4:2). 'E como ouvirão, se não há quem pregue?' (Romanos 10:14).",
            referencias: "Atos 8:4; Atos 13:47; Romanos 10:14-15; 2 Timóteo 4:2; Tito 1:3; 1 Pedro 3:15"
        },
        {
            termo: "04. Redes Sociais - Oportunidades e Riscos para o Evangelismo",
            definicao: "As redes sociais (Facebook, Instagram, WhatsApp, YouTube, TikTok, Twitter/X, Telegram) transformaram a comunicação. Oportunidades: (1) Evangelismo: compartilhar o evangelho com milhões. (2) Discipulado: grupos de estudo bíblico online (WhatsApp, Telegram). (3) Transmissão de cultos: alcançar pessoas impossibilitadas de ir à igreja. (4) Comunhão: manter contato com irmãos distantes. (5) Arrecadação: campanhas missionárias (online). (6) Apoio pastoral: aconselhamento online (cautela). (7) Testemunho pessoal: compartilhar a fé (1 Pedro 3:15). (8) Evangelismo criativo: memes, vídeos curtos (TikTok, Reels). (9) Lives e podcasts: conteúdo aprofundado. (10) Anúncios pagos: segmentação de público. Riscos: (a) Comparação social: inveja, depressão. (b) Fofoca digital: difamação. (c) Isolamento: substituição da comunhão presencial. (d) Vício: perda de tempo (Efésios 5:15-16). (e) Conteúdo inadequado: pornografia, violência. (f) Fake news: desinformação. (g) Cancelamento: perseguição digital. (h) Discurso de ódio: falta de amor (João 13:34-35). (i) Polarização: divisão na igreja. (j) Heresias: falsos mestres online (2 Pedro 2:1-3). (k) Falta de profundidade: conteúdo superficial. (l) Riscos de segurança: privacidade. (m) Algoritmos: bolhas de informação. A teologia reformada (Schaeffer, Keller) incentiva o uso sábio das redes sociais. 'Vede, pois, irmãos, como andeis cuidadosamente, não como néscios, mas como sábios' (Efésios 5:15).",
            referencias: "Mateus 5:13-16; João 13:34-35; Gálatas 5:22-23; Efésios 4:29; Efésios 5:15-16; Filipenses 4:8; Colossenses 4:6; 1 Pedro 3:15"
        },
        {
            termo: "05. Evangelismo Digital - Estratégias e Ferramentas",
            definicao: "O evangelismo digital usa ferramentas online para proclamar o evangelho. Estratégias: (1) Websites e blogs (conteúdo apologético, estudos bíblicos). (2) Redes sociais (posts, stories, reels). (3) YouTube (vídeos, séries, documentários). (4) Podcasts (áudio, entrevistas). (5) Aplicativos (Bíblia App, YouVersion, apps de oração). (6) E-mail marketing (newsletters). (7) Chatbots (respostas automáticas). (8) Inteligência artificial (conteúdo personalizado). (9) Realidade virtual (experiências imersivas). (10) Gamificação (jogos cristãos). (11) Lives (transmissões ao vivo). (12) Anúncios pagos (Google Ads, Facebook Ads). (13) SEO (otimização para mecanismos de busca). (14) Inbound marketing (atrair pessoas com conteúdo útil). (15) Retargeting (anúncios personalizados). Ferramentas: (1) WordPress (blogs). (2) Canva (design gráfico). (3) Hootsuite (gerenciamento de redes sociais). (4) Mailchimp (e-mail marketing). (5) Zoom (reuniões online). (6) WhatsApp Business (comunicação). (7) Google Analytics (análise de tráfego). (8) ChatGPT (IA para conteúdo). (9) Bible Gateway (ferramentas bíblicas). (10) Blue Letter Bible (estudo bíblico). Desafios: (a) Falta de discipulado. (b) Falta de relacionamento pessoal. (c) Anonimato. (d) Conteúdo superficial. (e) Concorrência com conteúdo secular. (f) Custos. (g) Algoritmos. (h) Censura. (i) Fake news. (j) Heresias. A teologia reformada (John Piper, Tim Keller) incentiva o evangelismo digital como complemento ao evangelismo presencial. 'Como, pois, invocarão aquele em quem não creram? e como crerão naquele de quem não ouviram? e como ouvirão, se não há quem pregue?' (Romanos 10:14).",
            referencias: "Mateus 28:19-20; Marcos 16:15; Atos 1:8; Atos 8:4; Romanos 10:13-15; 2 Timóteo 4:2"
        },
        {
            termo: "06. A Igreja Online - Cultos Virtuais e Comunidade Digital",
            definicao: "A pandemia de COVID-19 (2020-2022) forçou muitas igrejas a migrar para o online. Questões teológicas: (1) A igreja online é 'igreja'? A igreja é o corpo de Cristo (1 Coríndios 12:12-27), uma comunidade que se reúne presencialmente (Hebreus 10:25). (2) Os sacramentos podem ser realizados online? Batismo requer água; Ceia do Senhor requer pão e vinho. (3) A disciplina eclesiástica pode ser aplicada online? Difícil. (4) O pastoreio online substitui o presencial? Não totalmente. (5) A comunhão online é comunhão real? Parcial. Práticas online: (1) Transmissão de cultos (ao vivo ou gravado). (2) Pequenos grupos online (Zoom, Google Meet). (3) Aconselhamento pastoral online (cautela). (4) Discipulado online (estudos bíblicos). (5) Oração online (grupos de intercessão). (6) Escola Dominical online (crianças, jovens). (7) Retiros online (acampamentos virtuais). (8) Missões online (evangelismo digital). (9) Treinamento online (seminários, cursos). (10) Administração online (sistemas de gestão). A teologia reformada afirma: (a) A igreja online pode complementar, mas não substituir, a igreja presencial. (b) O culto online é válido para quem não pode comparecer presencialmente (doentes, idosos, distantes). (c) O batismo e a Ceia devem ser presenciais. (d) A disciplina eclesiástica requer presença. (e) A comunhão plena requer presença. (f) A igreja online não deve ser usada como desculpa para evitar o ajuntamento (Hebreus 10:25). 'Não deixando a nossa congregação, como é costume de alguns' (Hebreus 10:25). 'E perseveravam na doutrina dos apóstolos, e na comunhão, e no partir do pão, e nas orações' (Atos 2:42).",
            referencias: "Atos 2:42; 1 Coríndios 11:23-34; Hebreus 10:24-25; 1 Pedro 5:2-4"
        },
        {
            termo: "07. Ética da Comunicação Cristã - Verdade, Amor e Discernimento",
            definicao: "A comunicação cristã deve ser guiada pela verdade, pelo amor e pelo discernimento. 'Antes, seguindo a verdade em amor, cresçamos em tudo naquele que é a cabeça, Cristo' (Efésios 4:15). Princípios: (1) Verdade: não mentir (Êxodo 20:16). 'Por isso, deixando a mentira, fale cada um a verdade com o seu próximo' (Efésios 4:25). (2) Amor: falar com amor (1 Coríndios 13:1). 'Toda a vossa palavra seja com graça' (Colossenses 4:6). (3) Discernimento: saber o que falar e quando (Eclesiastes 3:7). (4) Edificação: 'Não saia da vossa boca nenhuma palavra torpe, mas só a que for boa para promover a edificação' (Efésios 4:29). (5) Pureza: evitar palavras obscenas (Efésios 5:4). (6) Mansidão: responder com brandura (Provérbios 15:1). (7) Paciência: ouvir antes de falar (Tiago 1:19). (8) Humildade: não se vangloriar (Provérbios 27:2). (9) Coragem: falar a verdade mesmo quando difícil (Atos 4:29). (10) Oração: pedir sabedoria (Tiago 1:5). (11) Discernimento: testar os espíritos (1 João 4:1). (12) Contextualização: adaptar a mensagem (1 Coríndios 9:22). A teologia reformada (Calvino, Edwards) enfatiza a ética da comunicação como parte da santificação. 'A boca do justo profere sabedoria' (Salmo 37:30).",
            referencias: "Provérbios 15:1; Eclesiastes 3:7; Mateus 12:34-37; Efésios 4:15; Efésios 4:25; Efésios 4:29; Colossenses 4:6; Tiago 1:19; Tiago 3:2-12"
        },
        {
            termo: "08. Discernimento Digital - Combatendo Fake News e Heresias Online",
            definicao: "A era digital está cheia de fake news, desinformação e heresias. 'Acautelai-vos, porém, dos falsos profetas, que vêm até vós vestidos como ovelhas, mas interiormente são lobos devoradores' (Mateus 7:15). 'Porque surgirão falsos cristos e falsos profetas, e farão tão grandes sinais e prodígios que, se possível fora, enganariam até os eleitos' (Mateus 24:24). Como discernir: (1) Verificar a fonte: quem escreveu? (2) Comparar com a Bíblia: 'Examinais as Escrituras' (João 5:39). (3) Verificar outros sites (fact-checking). (4) Consultar líderes cristãos confiáveis. (5) Orar por discernimento (Tiago 1:5). (6) Não compartilhar sem verificar. (7) Denunciar fake news. (8) Educar outros sobre discernimento digital. (9) Usar ferramentas de verificação (Snopes, Aos Fatos, Lupa). (10) Evitar algoritmos que promovem sensacionalismo. (11) Seguir fontes confiáveis (ligas teológicas, seminários). (12) Desconfiar de conteúdo sensacionalista. (13) Verificar contexto (citação fora de contexto). (14) Verificar data (notícia antiga sendo reutilizada). (15) Verificar se é sátira (The Onion, Sensacionalista). A teologia reformada (Van Til, Schaeffer) enfatiza o discernimento como parte da vida cristã. 'Não creiais em todo o espírito, mas provai se os espíritos são de Deus' (1 João 4:1). 'Examinai tudo, retende o bem' (1 Tessalonicenses 5:21).",
            referencias: "Mateus 7:15; Mateus 24:24; João 5:39; Atos 17:11; 1 Tessalonicenses 5:21-22; 1 João 4:1; 2 João 1:7-11"
        },
        {
            termo: "09. O Testemunho Cristão nas Redes Sociais - Sal e Luz Online",
            definicao: "Os cristãos devem ser 'sal da terra' e 'luz do mundo' também nas redes sociais. 'Vós sois o sal da terra... vós sois a luz do mundo' (Mateus 5:13-14). 'Assim resplandeça a vossa luz diante dos homens, para que vejam as vossas boas obras e glorifiquem a vosso Pai, que está nos céus' (Mateus 5:16). Práticas para um bom testemunho online: (1) Compartilhar conteúdo edificante (Filipenses 4:8). (2) Evitar fofocas e calúnias (Efésios 4:29). (3) Não responder com raiva (Provérbios 15:1). (4) Ser humilde (não se gabar). (5) Orar antes de postar. (6) Compartilhar o evangelho (Romanos 1:16). (7) Mostrar amor (João 13:34-35). (8) Evitar polêmicas desnecessárias. (9) Ser consistente (vida offline e online). (10) Não se deixar levar por algoritmos. (11) Usar as redes para o Reino. (12) Ser autêntico (não fingir). (13) Evitar comparação social (inveja). (14) Limitar o tempo nas redes (Efésios 5:15-16). (15) Descansar nas redes (sábado digital). A teologia reformada (Keller, Piper) incentiva os cristãos a usarem as redes sociais para a glória de Deus. 'Portanto, quer comais quer bebais, ou façais outra qualquer coisa, fazei tudo para glória de Deus' (1 Coríndios 10:31).",
            referencias: "Mateus 5:13-16; João 13:34-35; Filipenses 4:8; 1 Pedro 3:15-16; 1 João 2:15-17"
        },
        {
            termo: "10. Cuidados com a Saúde Mental Digital - Vício, Ansiedade e Depressão",
            definicao: "O uso excessivo das redes sociais pode levar a problemas de saúde mental: vício, ansiedade, depressão, solidão, comparação social, FOMO (fear of missing out). 'Sede sóbrios e vigiai' (1 Pedro 5:8). 'Não vos conformeis com este mundo' (Romanos 12:2). Sintomas: (1) Verificar o celular constantemente. (2) Ansiedade quando sem acesso. (3) Comparação com vidas perfeitas (Instagram). (4) Depressão devido à baixa autoestima. (5) Isolamento social. (6) Falta de sono (usar celular à noite). (7) Procrastinação (adiar tarefas importantes). (8) Dificuldade de concentração. (9) Irritabilidade. (10) Queda no desempenho acadêmico/profissional. (11) Perda de interesse em atividades offline. (12) Uso como fuga de problemas. Estratégias de cuidado: (a) Limitar o tempo nas redes (aplicativos de controle). (b) Desativar notificações. (c) Fazer 'detox digital' (dias sem redes). (d) Priorizar relacionamentos offline. (e) Praticar esportes e hobbies. (f) Dormir bem (não usar celular na cama). (g) Buscar ajuda profissional (psicólogo, psiquiatra). (h) Orar e ler a Bíblia. (i) Confessar o vício como pecado. (j) Encontrar um parceiro de responsabilidade. (k) Jejum digital (Tempo com Deus). (l) Buscar contentamento em Cristo (Filipenses 4:11). A teologia reformada (Edwards, Bonhoeffer) enfatiza a importância do autocontrole (domínio próprio) como fruto do Espírito (Gálatas 5:23). 'Tudo me é lícito, mas nem tudo me convém' (1 Coríndios 6:12).",
            referencias: "Mateus 6:25-34; Romanos 12:2; 1 Coríndios 6:12; Gálatas 5:22-23; Filipenses 4:11-13; 1 Pedro 5:8"
        },
        {
            termo: "11. O Futuro da Comunicação Cristã - IA, Realidade Virtual e Metaverso",
            definicao: "A inteligência artificial (IA), a realidade virtual (RV) e o metaverso estão transformando a comunicação. Tendências futuras: (1) IA para tradução da Bíblia (acelerar processos). (2) Chatbots para aconselhamento pastoral (cautela). (3) Sermões gerados por IA? (risco). (4) Realidade virtual para simulações bíblicas (visitar a Jerusalém antiga). (5) Metaverso: igrejas em mundos virtuais (ex.: Second Life, Horizon Worlds). (6) Avatares cristãos para evangelismo. (7) Análise de dados para segmentação de público. (8) Personalização de conteúdo (recomendações de sermões). (9) Realidade aumentada (sobrepor versículos na vida real). (10) NFTs cristãos (arte digital para missões). Desafios éticos: (a) A IA pode substituir o pastor? (b) A RV pode substituir o culto presencial? (c) O metaverso pode criar uma 'igreja virtual' sem comunhão real? (d) A privacidade dos dados dos membros. (e) O viés algorítmico. (f) Deepfakes (falsificação de líderes cristãos). (g) Dependência tecnológica. (h) Exclusão digital (acesso desigual). A teologia reformada (Kuyper, Schaeffer) nos chama a usar a tecnologia com discernimento, sempre subordinada a Cristo. 'Nele estão escondidos todos os tesouros da sabedoria e da ciência' (Colossenses 2:3). 'Todas as coisas são vossas... e vós sois de Cristo, e Cristo de Deus' (1 Coríndios 3:21-23).",
            referencias: "Colossenses 2:3; 1 Coríndios 3:21-23; 1 Tessalonicenses 5:21; 1 Pedro 3:15"
        },
        {
            termo: "12. A Comunicação na Família - Diálogo, Disciplina e Amor",
            definicao: "A comunicação na família é fundamental para a educação cristã. 'Pais, não provoqueis vossos filhos à ira, mas criai-os na disciplina e admoestação do Senhor' (Efésios 6:4). 'Vós, pais, não irriteis vossos filhos, para que não percam o ânimo' (Colossenses 3:21). Princípios de comunicação familiar: (1) Diálogo aberto (ouvir os filhos). (2) Palavras de afirmação (encorajamento). (3) Disciplina com amor (Hebreus 12:5-11). (4) Ensino da Palavra (Deuteronômio 6:6-9). (5) Oração em família (1 Tessalonicenses 5:17). (6) Perdão (Efésios 4:32). (7) Tempo de qualidade (Eclesiastes 3:1). (8) Exemplo dos pais (1 Timóteo 4:12). (9) Limites no uso da tecnologia (Efésios 5:15-16). (10) Evitar gritos e insultos (Efésios 4:29). (11) Resolver conflitos (Mateus 18:15-17). (12) Celebrar conquistas. (13) Lamentar perdas juntos. (14) Planejar o futuro juntos. (15) Culto doméstico (Atos 2:46). A teologia reformada (Puritanos) enfatiza a comunicação familiar como essencial para a transmissão da fé. 'Ensina-as a teus filhos e delas fala assentado em tua casa, e andando pelo caminho, e deitando-te e levantando-te' (Deuteronômio 6:7).",
            referencias: "Deuteronômio 6:4-9; Efésios 4:29; Efésios 6:4; Colossenses 3:21; 1 Timóteo 4:12; 2 Timóteo 1:5; 2 Timóteo 3:14-15"
        },
        {
            termo: "13. Síntese: Comunicando Cristo na Era Digital",
            definicao: "A comunicação cristã na era digital deve ser centrada em Cristo, baseada na verdade, motivada pelo amor, e guiada pelo discernimento. 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36). Resumo da teologia da comunicação: (1) Cristo é a Palavra (Logos), a comunicação suprema de Deus (João 1:1-14). (2) A comunicação cristã deve imitar a comunicação de Cristo (encarnada, clara, verdadeira, amorosa). (3) A mídia tradicional (rádio, TV, imprensa) pode ser usada para o Reino. (4) As redes sociais oferecem oportunidades e riscos (Efésios 5:15-16). (5) O evangelismo digital é uma ferramenta poderosa (Romanos 10:14). (6) A igreja online complementa, mas não substitui, a igreja presencial (Hebreus 10:25). (7) A ética da comunicação cristã exige verdade, amor e discernimento (Efésios 4:15). (8) Devemos ter discernimento digital, combatendo fake news e heresias (1 João 4:1). (9) O testemunho cristão nas redes sociais deve ser sal e luz (Mateus 5:13-16). (10) Devemos cuidar da saúde mental digital (vício, ansiedade). (11) O futuro da comunicação cristã inclui IA, RV e metaverso (Colossenses 2:3). (12) A comunicação na família é fundamental para a educação cristã (Deuteronômio 6:6-9). (13) Toda comunicação deve ser para a glória de Cristo (1 Coríndios 10:31). 'E tudo quanto fizerdes, por palavra ou por obra, fazei-o em nome do Senhor Jesus, dando por ele graças a Deus Pai' (Colossenses 3:17). Soli Deo Gloria!",
            referencias: "Romanos 11:36; 1 Coríndios 10:31; Colossenses 3:17; Efésios 4:15; Efésios 5:15-16; Colossenses 4:6; 1 Pedro 3:15"
        }
    ]
};