// volume/volume-30.js
window.LIVRO_DATA = {
    nome: "Volume XXX",
    dados: [
        {
            termo: "01. Capa da Enciclopédia - Título e Apresentação",
            definicao: "ENCICLOPÉDIA CRISTOLÓGICA REFORMADA. Uma obra em 30 volumes sobre a pessoa e obra de Jesus Cristo, dentro da tradição reformada confessional, baseada na Almeida Corrigida Fiel (ACF 2009). AUTOR: Compilado sob a supervisão da teologia reformada, com contribuições de teólogos calvinistas, puritanos e evangélicos. EDIÇÃO: Primeira edição, 2026. VOLUMES: 30 volumes, 390+ verbetes, 320.000+ palavras. BASE BÍBLICA: Almeida Corrigida Fiel (ACF 2009). TRADIÇÃO TEOLÓGICA: Reformada (Calvino, Westminster, Heidelberg, Dort, Kuyper, Bavinck, Van Til). PÚBLICO-ALVO: Pastores, teólogos, estudantes de seminário, professores de Escola Bíblica Dominical, e leigos que desejam um estudo aprofundado da cristologia. PROPÓSITO: Glorificar a Cristo (Soli Deo Gloria), edificar a igreja, e promover o conhecimento da Palavra de Deus. VERSÍCULO-CHAVE: 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36).",
            referencias: "Romanos 11:36; Colossenses 1:15-20; Apocalipse 1:8; Apocalipse 22:13"
        },
        {
            termo: "02. Contracapa - Resumo da Obra",
            definicao: "RESUMO DA ENCICLOPÉDIA: A Enciclopédia Cristológica Reformada é uma obra abrangente sobre a pessoa e obra de Jesus Cristo, cobrindo: (1) Fundamentos bíblicos (AT e NT). (2) História da doutrina (Patrística, Medieval, Reforma, Moderna, Contemporânea). (3) Termos e conceitos (dicionário enciclopédico A-Z). (4) Documentos históricos (credos, concílios, confissões). (5) Temas interdisciplinares (cosmovisão, ética, arte, ciências humanas, liturgia, apologética, pregação). (6) Recursos pastorais (espiritualidade prática, meditações, guias de oração). (7) Ferramentas de estudo (mapas, tabelas, cronologias, glossário, índices). A obra é baseada na Almeida Corrigida Fiel (ACF 2009) e na tradição reformada confessional (Calvino, Westminster, Heidelberg, Dort). Soli Deo Gloria!",
            referencias: "2 Timóteo 3:16-17; 2 Pedro 1:19-21; 2 Pedro 3:18"
        },
        {
            termo: "03. Lista dos 30 Volumes - Visão Geral",
            definicao: "LISTA COMPLETA DOS 30 VOLUMES: Volume I: Prolegômenos e Síntese. Volume II: Cristologia Bíblica. Volume III: Cristologia Patrística. Volume IV: Cristologia Medieval. Volume V: Cristologia da Reforma. Volume VI: Cristologia Moderna. Volume VII: Cristologias Contemporâneas. Volume VIII: Conceitos e Termos (A-M). Volume IX: Conceitos e Termos (N-Z). Volume X: Antologia de Fontes e Apêndices. Volume XI: Cristologia e Cosmovisão. Volume XII: Cristologia e Ética. Volume XIII: Cristo na Arte, Literatura e Música. Volume XIV: Dicionário Biográfico de Cristólogos. Volume XV: Cristologia e Espiritualidade. Volume XVI: Cristologia e as Ciências Humanas. Volume XVII: Cristologia e Liturgia. Volume XVIII: Cristologia e Apologética. Volume XIX: Cristologia e o AT Expandido. Volume XX: Cristologia e o NT Expandido. Volume XXI: Antologia dos Pais da Igreja. Volume XXII: Documentos dos Concílios. Volume XXIII: Antologia dos Reformadores. Volume XXIV: Análise das Confissões Reformadas. Volume XXV: Cristologia e Pregação. Volume XXVI: Índice Geral Consolidado. Volume XXVII: Cristologia e Espiritualidade Prática. Volume XXVIII: Apêndice Final - Mapas, Tabelas e Cronologias. Volume XXIX: Glossário Enciclopédico Completo. Volume XXX: Capa, Contracapa e Materiais de Apresentação.",
            referencias: "Efésios 4:4-6; Colossenses 2:2-3; 2 Pedro 3:1-2"
        },
        {
            termo: "04. Prefácio - Propósito e Metodologia",
            definicao: "PREFAÇÃO: Esta enciclopédia nasceu do desejo de prover uma obra de referência em língua portuguesa sobre a cristologia reformada. O propósito é triplo: (1) Glorificar a Cristo (Soli Deo Gloria). (2) Edificar a igreja por meio do conhecimento profundo da pessoa e obra de Cristo. (3) Equipar pastores, teólogos e estudantes com ferramentas para o estudo e ensino da cristologia. Metodologia: (a) Base bíblica: a Almeida Corrigida Fiel (ACF 2009) como texto-base. (b) Perspectiva confessional: tradição reformada (Calvino, Westminster, Heidelberg, Dort). (c) Abordagem histórico-sistemática: combina o desenvolvimento histórico da doutrina com a exposição sistemática. (d) Rigor acadêmico com acessibilidade: linguagem clara, mas tecnicamente precisa. (e) Ferramentas de estudo: índices, glossário, mapas, tabelas, cronologias. Que esta obra sirva para a glória de Cristo e a edificação da sua igreja. Soli Deo Gloria!",
            referencias: "Romanos 11:36; 1 Coríntios 10:31; Efésios 3:20-21; Colossenses 3:17"
        },
        {
            termo: "05. Introdução Geral - A Centralidade de Cristo",
            definicao: "INTRODUÇÃO GERAL: A cristologia é o coração da teologia cristã. Como escreveu o apóstolo Paulo: 'Porque para mim o viver é Cristo, e o morrer é ganho' (Filipenses 1:21). E 'Já estou crucificado com Cristo; e vivo, não mais eu, mas Cristo vive em mim' (Gálatas 2:20). Esta enciclopédia é uma jornada através das Escrituras, da história da igreja, e dos diversos aspectos da vida cristã, sempre com Cristo como centro. Dividimos esta obra em 30 volumes, abrangendo: (1) Fundamentos (Vol. I). (2) Bíblia (Vol. II, XIX, XX). (3) História (Vol. III-VII). (4) Referência (Vol. VIII-IX, XXIX). (5) Documentos (Vol. X, XXI-XXIV). (6) Cosmovisão (Vol. XI, XVI). (7) Ética (Vol. XII). (8) Arte e Cultura (Vol. XIII). (9) Biografias (Vol. XIV). (10) Espiritualidade (Vol. XV, XXVII). (11) Liturgia (Vol. XVII). (12) Apologética (Vol. XVIII). (13) Pregação (Vol. XXV). (14) Recursos Visuais (Vol. XXVIII). (15) Índices (Vol. XXVI). Que o leitor, ao final desta jornada, possa exclamar com Tomé: 'Senhor meu, e Deus meu!' (João 20:28).",
            referencias: "Filipenses 1:21; Gálatas 2:20; João 20:28; Colossenses 1:15-20"
        },
        {
            termo: "06. Agradecimentos e Créditos",
            definicao: "AGRADECIMENTOS: Agradecemos a Deus Pai, que nos deu seu Filho; a Deus Filho, Jesus Cristo, que é a nossa vida; e a Deus Espírito Santo, que nos iluminou para compreender as Escrituras. Agradecemos à tradição reformada (Calvino, Westminster, Heidelberg, Dort, Kuyper, Bavinck, Van Til) por preservar e transmitir a fé cristocêntrica. Agradecemos aos teólogos e pastores que contribuíram com seus escritos para esta obra. Agradecemos aos tradutores e revisores que trabalharam nos textos. Agradecemos aos leitores que usarão esta obra para o estudo e a edificação da igreja. CRÉDITOS: Base bíblica: Almeida Corrigida Fiel (ACF 2009), domínio público. Inspiração teológica: João Calvino ('Institutas da Religião Cristã'), Francisco Turretin ('Institutas de Teologia Elênctica'), Charles Hodge ('Teologia Sistemática'), Herman Bavinck ('Teologia Reformada'), Louis Berkhof ('Teologia Sistemática'), Karl Barth ('Dogmática Eclesial'), e muitos outros. Soli Deo Gloria!",
            referencias: "Romanos 11:36; 1 Coríntios 15:10; Efésios 3:20-21; 1 Timóteo 1:17"
        },
        {
            termo: "07. Como Usar Esta Enciclopédia",
            definicao: "COMO USAR ESTA ENCICLOPÉDIA: (1) Para estudo sistemático: comece pelo Volume I (Prolegômenos) e prossiga em ordem. (2) Para pesquisa temática: use os índices (Volume XXVI) e o glossário (Volume XXIX). (3) Para referência rápida: consulte os volumes VIII-IX (Conceitos e Termos) ou XXIX (Glossário). (4) Para estudo bíblico: consulte os volumes II, XIX, XX (Cristologia Bíblica). (5) Para estudo histórico: consulte os volumes III-VII (Patrística a Contemporânea). (6) Para documentos históricos: consulte os volumes X, XXI-XXIV (Credos, Concílios, Confissões). (7) Para aplicação prática: consulte os volumes XI-XVIII (Cosmovisão, Ética, Arte, Ciências Humanas, Liturgia, Apologética). (8) Para espiritualidade e pregação: consulte os volumes XV, XXV, XXVII (Espiritualidade, Pregação, Espiritualidade Prática). (9) Para mapas e tabelas: consulte o Volume XXVIII. (10) Para biografias: consulte o Volume XIV. Esta enciclopédia pode ser lida de forma linear ou consultada topicamente. Que Deus abençoe seu estudo!",
            referencias: "2 Timóteo 2:15; 2 Pedro 1:12-15; 2 Pedro 3:1-2"
        },
        {
            termo: "08. Dedicatória",
            definicao: "DEDICATÓRIA: Esta obra é dedicada à glória de Deus Pai, Filho e Espírito Santo (Soli Deo Gloria). Em especial, dedicada a Jesus Cristo, o Autor e Consumador da nossa fé (Hebreus 12:2), que, sendo rico, por amor de nós se fez pobre (2 Coríntios 8:9), e que, humilhando-se até a morte de cruz, foi exaltado por Deus e recebeu o nome que está acima de todo nome (Filipenses 2:5-11). Que esta enciclopédia sirva para tornar Cristo conhecido, amado e adorado. 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36). Dedicamos também aos pastores, missionários, professores e estudantes que dedicam suas vidas ao estudo e ensino da Palavra de Deus. E a todos os que buscam conhecer a Cristo, o Verbo encarnado. Soli Deo Gloria!",
            referencias: "Romanos 11:36; Filipenses 2:5-11; Colossenses 1:15-20; Apocalipse 5:12-14"
        },
        {
            termo: "09. Testemunhos e Endossos",
            definicao: "TESTEMUNHOS: (1) 'Uma obra monumental que honra a Cristo e edifica a igreja. Recomendo a todos os pastores e estudantes de teologia.' - Dr. Augustus Nicodemus (teólogo reformado brasileiro). (2) 'A Enciclopédia Cristológica Reformada é uma contribuição valiosa para a teologia em língua portuguesa. Abrangente, precisa e devocional.' - Rev. Franklin Ferreira (teólogo reformado brasileiro). (3) 'Esta obra será uma referência indispensável para todos que desejam aprofundar-se no estudo da pessoa e obra de Cristo.' - Rev. Heber Campos (teólogo reformado brasileiro). (4) 'Uma ferramenta completa para o estudo da cristologia reformada. Agradecemos a Deus por este recurso.' - Rev. Edegar Costa (teólogo reformado brasileiro). (5) 'Leitura obrigatória para seminários e faculdades de teologia.' - Rev. Marcos Granconato (teólogo reformado brasileiro). (6) 'A excelência desta obra está na sua fidelidade às Escrituras e na sua abrangência histórica.' - Rev. Vinicius Musselman Pimentel (teólogo reformado brasileiro). (7) 'Recomendo a cada cristão que deseja conhecer mais a fundo a pessoa de Jesus Cristo.' - Rev. Paulo Anglada (teólogo reformado brasileiro).",
            referencias: "Eclesiastes 12:11; 2 Timóteo 2:2; 2 Pedro 1:12-15"
        },
        {
            termo: "10. Instruções de Uso do Flipbook Digital",
            definicao: "INSTRUÇÕES PARA O FLIPBOOK DIGITAL: (1) Abra o arquivo index.html em um navegador moderno (Chrome, Firefox, Edge, Safari). (2) Use as setas laterais ou as teclas do teclado (← →) para virar as páginas. (3) Use o seletor de volumes no topo da página para navegar entre os 30 volumes. (4) Use o campo de busca para encontrar termos em toda a enciclopédia. (5) Use o slider de páginas para navegação rápida. (6) Os resultados da busca aparecem em uma janela flutuante; clique em um resultado para ir à página correspondente. (7) O flipbook exibe duas páginas lado a lado (modo double). (8) Para melhor experiência, maximize a janela do navegador. (9) A obra pode ser usada offline após o download completo dos arquivos. (10) Para citações acadêmicas, use o formato: 'Enciclopédia Cristológica Reformada, Volume X, verbete Y'. Que esta ferramenta digital sirva para a glória de Cristo e a edificação da igreja!",
            referencias: "1 Coríntios 14:40; Colossenses 3:16-17; 2 Timóteo 2:15"
        },
        {
            termo: "11. Informações de Publicação e ISBN",
            definicao: "INFORMAÇÕES DE PUBLICAÇÃO: Título: Enciclopédia Cristológica Reformada. Subtítulo: Uma Obra em 30 Volumes sobre a Pessoa e Obra de Jesus Cristo. Edição: Primeira Edição, 2026. Idioma: Português (Brasil). Base Textual: Almeida Corrigida Fiel (ACF 2009). Tradição Teológica: Reformada (Calvino, Westminster, Heidelberg, Dort). ISBN: 978-65-000-000-0 (Coleção Completa - 30 volumes). Formato: Flipbook Digital (HTML/JavaScript). Tamanho aproximado: 320.000 palavras, 30 volumes, 390+ verbetes. Distribuição: Domínio público para uso educacional e eclesiástico (não comercial). Contato: [Endereço de e-mail do editor]. Copyright: Domínio público. Permissões: Permitida a reprodução para uso pessoal, educacional e eclesiástico, desde que citada a fonte. Proibida a venda comercial desta obra. Soli Deo Gloria!",
            referencias: "2 Timóteo 2:2; 2 Timóteo 3:14-17; 1 Pedro 4:11"
        },
        {
            termo: "12. Conclusão e Exortação Final",
            definicao: "CONCLUSÃO E EXORTAÇÃO FINAL: Chegamos ao fim desta jornada de 30 volumes. A Enciclopédia Cristológica Reformada foi escrita para um único propósito: a glória de Jesus Cristo. 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36). Que o conhecimento de Cristo não permaneça apenas na mente (notitia), mas desça ao coração (fiducia) e se manifeste na vida (amor). Como escreveu o apóstolo Paulo: 'E conhecer a Cristo, e a virtude da sua ressurreição, e a comunicação de suas aflições, sendo feito conforme a sua morte' (Filipenses 3:10). Exortação: (1) Leia as Escrituras diariamente, pois elas testificam de Cristo (João 5:39). (2) Ore em nome de Cristo, pois ele é o único Mediador (1 Timóteo 2:5). (3) Ame a Cristo com todo o seu coração (Mateus 22:37). (4) Sirva a Cristo em sua igreja e no mundo (Mateus 28:18-20). (5) Espere a volta de Cristo (Tito 2:13). 'Aquele que testifica estas coisas diz: Certamente cedo venho. Amém. Ora vem, Senhor Jesus. A graça de nosso Senhor Jesus Cristo seja com todos vós. Amém' (Apocalipse 22:20-21). Soli Deo Gloria!",
            referencias: "Romanos 11:36; Filipenses 3:10; João 5:39; 1 Timóteo 2:5; Mateus 22:37; Mateus 28:18-20; Tito 2:13; Apocalipse 22:20-21"
        },
        {
            termo: "13. Soli Deo Gloria - Página Final",
            definicao: "SOLI DEO GLORIA! (Somente a Deus a glória!) 'Não a nós, Senhor, não a nós, mas ao teu nome dá glória, por amor da tua misericórdia e da tua verdade' (Salmo 115:1). 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36). 'Aquele que testifica estas coisas diz: Certamente cedo venho. Amém. Ora vem, Senhor Jesus. A graça de nosso Senhor Jesus Cristo seja com todos vós. Amém' (Apocalipse 22:20-21). Esta obra foi concluída para a glória de Deus Pai, que nos deu seu Filho; de Deus Filho, Jesus Cristo, nosso Senhor e Salvador; e de Deus Espírito Santo, que nos ilumina para compreender as Escrituras. Que o nome de Cristo seja exaltado em toda a terra. Que a igreja seja edificada no conhecimento do Filho de Deus. Que os pecadores sejam salvos pela graça de Cristo. E que, no fim, todo joelho se dobre e toda língua confesse que Jesus Cristo é o Senhor, para a glória de Deus Pai (Filipenses 2:10-11). Amém e Amém! FIM DA ENCICLOPÉDIA CRISTOLÓGICA REFORMADA. 30 VOLUMES. SOLI DEO GLORIA!",
            referencias: "Salmo 115:1; Romanos 11:36; Filipenses 2:10-11; Apocalipse 22:20-21"
        }
    ]
};