// volume/volume-31.js
window.LIVRO_DATA = {
    nome: "Volume XXXI",
    dados: [
        {
            termo: "01. Gênesis - Cristo como a Semente da Mulher e o Criador",
            definicao: "O livro de Gênesis (Bereshit - 'No princípio') é o livro dos começos: criação, queda, promessa de redenção. A cristologia em Gênesis é rica e tipológica. (1) Cristo como Criador: 'No princípio criou Deus os céus e a terra' (Gênesis 1:1). João identifica Jesus como o Verbo criador: 'Todas as coisas foram feitas por ele' (João 1:3). Paulo confirma: 'Porque nele foram criadas todas as coisas' (Colossenses 1:16). (2) Gênesis 3:15 - O Proto-Evangelho: 'E porei inimizade entre ti e a mulher, e entre a tua semente e a sua semente; esta te ferirá a cabeça, e tu lhe ferirás o calcanhar.' Esta é a primeira promessa do Redentor (proto-evangelho). A 'semente da mulher' é Cristo, que esmagaria a cabeça de Satanás. (3) Cristo como o segundo Adão (tipológico): Adão é 'figura daquele que havia de vir' (Romanos 5:14). O primeiro Adão trouxe pecado e morte; o último Adão (Cristo) trouxe justiça e vida (1 Coríntios 15:45-49). (4) Melquisedeque (Gênesis 14:18-20): rei de Salém e sacerdote do Deus Altíssimo, tipo do sacerdócio eterno de Cristo (Salmo 110:4; Hebreus 5:6,10; 6:20; 7:1-28). (5) Isaque, tipo de Cristo: filho amado, oferecido em sacrifício no monte Moriá (Gênesis 22:1-14). Abraão disse: 'Deus proverá para si o cordeiro' (Gênesis 22:8), cumprido em Cristo, o Cordeiro de Deus. (6) José, tipo de Cristo: amado pelo pai, odiado pelos irmãos, vendido por prata, injustamente acusado, depois exaltado para governar e salvar sua família. (7) A escada de Jacó (Gênesis 28:12): Jesus se identifica como a escada que liga o céu e a terra (João 1:51). (8) Judá e o cetro (Gênesis 49:10): 'O cetro não se arredará de Judá... até que venha Siló' - referência messiânica a Cristo, o Leão da tribo de Judá (Apocalipse 5:5).",
            referencias: "Gênesis 1:1; Gênesis 3:15; Gênesis 14:18-20; Gênesis 22:1-14; Gênesis 28:12; Gênesis 37-50; Gênesis 49:10; João 1:1-3; João 1:51; Romanos 5:12-21; 1 Coríntios 15:45-49; Colossenses 1:15-17; Hebreus 5:6; Hebreus 7:1-28; Apocalipse 5:5"
        },
        {
            termo: "02. Êxodo - Cristo como o Cordeiro Pascal e o Libertador",
            definicao: "O livro de Êxodo (Shemot - 'Nomes') narra a libertação de Israel da escravidão do Egito, tipificando a libertação do pecado por Cristo. (1) Cristo como o Cordeiro Pascal (Êxodo 12:1-28): O cordeiro sem defeito, cujo sangue nos umbrais das portas protegia da morte. Paulo identifica Cristo como 'nossa Páscoa' (1 Coríntios 5:7). João Batista declarou: 'Eis o Cordeiro de Deus, que tira o pecado do mundo' (João 1:29). (2) Cristo como o Libertador: Moisés, tipo de Cristo, libertou Israel do Egito (escravidão). Cristo nos liberta do pecado e da escravidão de Satanás (João 8:36; Romanos 6:18). (3) Cristo como o Pão do Céu (Maná, Êxodo 16:1-36): Jesus disse: 'Eu sou o pão da vida' (João 6:35). O maná era um tipo do verdadeiro pão celestial. (4) Cristo como a Rocha Ferida (Êxodo 17:1-7): Moisés feriu a rocha, e dela jorrou água. Paulo identifica a rocha com Cristo: 'E a pedra era Cristo' (1 Coríntios 10:4). Cristo foi ferido (Isaías 53:5), e dele flui água viva (João 7:37-39). (5) Cristo no Tabernáculo (Êxodo 25-40): (a) O propiciatório (hilastērion) - a tampa da arca onde o sangue era aspergido, tipo de Cristo como propiciação (Romanos 3:25). (b) O véu do templo que se rasgou na morte de Cristo (Mateus 27:51), simbolizando o acesso direto a Deus (Hebreus 10:19-22). (c) O altar, o candelabro, a mesa dos pães da proposição - todos apontam para Cristo. (6) A teofania do Anjo do Senhor (Êxodo 3:2-6; 23:20-23; 33:14): interpretado pelos reformados como uma pré-encarnação de Cristo.",
            referencias: "Êxodo 3:2-6; Êxodo 12:1-28; Êxodo 16:1-36; Êxodo 17:1-7; Êxodo 25-40; João 1:29; João 6:35; João 8:36; João 7:37-39; Romanos 3:25; 1 Coríntios 5:7; 1 Coríntios 10:4; Hebreus 10:19-22; 1 Pedro 1:18-19"
        },
        {
            termo: "03. Levítico - Cristo como o Sumo Sacerdote e o Sacrifício Perfeito",
            definicao: "O livro de Levítico (Vayikra - 'E chamou') contém as leis sacrificiais e sacerdotais que tipificam a obra de Cristo. (1) Cristo como o Sumo Sacerdote: O sumo sacerdote do AT entrava no Santo dos Santos uma vez por ano com sangue de animais. Cristo é o Sumo Sacerdote perfeito que entrou no céu com seu próprio sangue (Hebreus 4:14-16; 7:26-28; 9:11-12). (2) Cristo como o Sacrifício Perfeito: Os sacrifícios de animais (holocausto, oferta pelo pecado, oferta pela culpa) apontavam para o sacrifício definitivo de Cristo. 'Porque com uma só oblação aperfeiçoou para sempre os que são santificados' (Hebreus 10:14). (3) O Dia da Expiação (Yom Kippur, Levítico 16): Dois bodes - um sacrificado (tipo da morte de Cristo) e o outro (Azazel) enviado ao deserto (tipo da remoção dos pecados). (4) O Cordeiro de Deus: Os cordeiros sacrificados diariamente (tamid) apontavam para o Cordeiro de Deus que tira o pecado do mundo (João 1:29). (5) O Ano do Jubileu (Levítico 25): Tipo da libertação em Cristo. Jesus leu Isaías 61:1-2 (ano aceitável do Senhor) e disse: 'Hoje se cumpriu esta Escritura' (Lucas 4:16-21). (6) Leis de pureza: A lepra (Levítico 13-14) tipifica o pecado, e a purificação aponta para Cristo que purifica os pecadores. A teologia reformada vê em Levítico a sombra das realidades celestiais encontradas em Cristo (Hebreus 8:5).",
            referencias: "Levítico 1-7; Levítico 13-14; Levítico 16; Levítico 25; João 1:29; Romanos 3:25; Lucas 4:16-21; Hebreus 4:14-16; Hebreus 7:26-28; Hebreus 8:5; Hebreus 9:11-28; Hebreus 10:1-18"
        },
        {
            termo: "04. Números - Cristo como a Serpente Levantada e a Rocha que Segue",
            definicao: "O livro de Números (Bemidbar - 'No deserto') narra a peregrinação de Israel no deserto, cheia de tipos cristológicos. (1) A Serpente de Bronze (Números 21:4-9): Deus enviou serpentes abrasadoras para punir o pecado de Israel. Moisés fez uma serpente de bronze e a colocou sobre uma haste; quem olhasse para ela viveria. Jesus aplica este tipo a si mesmo: 'E, como Moisés levantou a serpente no deserto, assim importa que o Filho do Homem seja levantado; para que todo aquele que nele crê não pereça, mas tenha a vida eterna' (João 3:14-15). A serpente de bronze tinha forma de serpente (mas não tinha veneno), assim como Cristo foi feito pecado (2 Coríntios 5:21), mas não tinha pecado. (2) A Rocha que Seguia Israel (Números 20:7-13): Paulo identifica a rocha com Cristo: 'E beberam todos da mesma bebida espiritual, porque bebiam da pedra espiritual que os seguia; e a pedra era Cristo' (1 Coríntios 10:4). Cristo é a rocha que foi ferida (Isaías 53:5). (3) A Vara de Arão que floresceu (Números 17:1-11): Tipo da ressurreição de Cristo. A vara morta floresceu, apontando para a vitória de Cristo sobre a morte. (4) A Estrela e o Cetro de Jacó (Números 24:17): 'Uma estrela procederá de Jacó, e um cetro subirá de Israel' - profecia messiânica de Balaão, cumprida em Cristo, a Estrela da manhã (Apocalipse 22:16). (5) A Água da Purificação (Números 19): A cinza da novilha vermelha, misturada com água, purificava os impuros. Tipo da purificação pelo sangue de Cristo (Hebreus 9:13-14).",
            referencias: "Números 17:1-11; Números 19; Números 20:7-13; Números 21:4-9; Números 24:17; João 3:14-15; 2 Coríntios 5:21; 1 Coríntios 10:4; Hebreus 9:13-14; Apocalipse 22:16"
        },
        {
            termo: "05. Deuteronômio - Cristo como o Profeta como Moisés",
            definicao: "O livro de Deuteronômio (Devarim - 'Palavras') é o discurso de despedida de Moisés, contendo profecias messiânicas. (1) O Profeta como Moisés (Deuteronômio 18:15-19): 'O Senhor teu Deus te levantará um profeta do meio de ti, de teus irmãos, como eu; a ele ouvireis.' Pedro identifica Jesus como este profeta (Atos 3:22-23). Estêvão também fez a mesma identificação (Atos 7:37). Jesus é o Profeta maior que Moisés (Hebreus 3:1-6). (2) A Maldição do Pendurado no Madeiro (Deuteronômio 21:22-23): 'Maldito aquele que for pendurado no madeiro.' Paulo aplica este texto a Cristo: 'Cristo nos resgatou da maldição da lei, fazendo-se maldição por nós; porque está escrito: Maldito todo aquele que for pendurado no madeiro' (Gálatas 3:13). (3) A Rocha (Deuteronômio 32:4,15,18,30-31): Deus é chamado de 'Rocha', tipificando Cristo (1 Coríntios 10:4). (4) A Promessa de um Rei (Deuteronômio 17:14-20): As instruções para o rei, cumpridas em Cristo, o Rei perfeito. (5) O Perdão e a Restauração (Deuteronômio 30:1-10): Tipo do arrependimento e da restauração em Cristo. A circuncisão do coração (Deuteronômio 30:6) aponta para a regeneração em Cristo (Colossenses 2:11).",
            referencias: "Deuteronômio 17:14-20; Deuteronômio 18:15-19; Deuteronômio 21:22-23; Deuteronômio 30:1-10; Deuteronômio 32:4; Atos 3:22-23; Atos 7:37; Gálatas 3:13; Colossenses 2:11; Hebreus 3:1-6"
        },
        {
            termo: "06. Josué - Cristo como o Capitão do Exército do Senhor",
            definicao: "O livro de Josué (Yehoshua - 'O SENHOR é salvação') narra a conquista de Canaã sob a liderança de Josué (Yeshua), cujo nome é a forma hebraica de Jesus. (1) Josué como tipo de Cristo: Josué conduziu Israel à terra prometida (Canaã), assim como Cristo nos conduz à nova criação (descanso celestial). 'Porque, se Josué lhes houvesse dado descanso, não falaria depois disso de outro dia' (Hebreus 4:8). (2) O Capitão do Exército do Senhor (Josué 5:13-15): Um homem com uma espada desembainhada se apresenta como 'Príncipe do exército do SENHOR'. Josué se prostra e adora. A tradição reformada vê nesta teofania uma aparição do Verbo pré-encarnado (Cristo). (3) A Queda de Jericó (Josué 6): A marcha ao redor da cidade e o toque das trombetas tipificam a vitória de Cristo sobre as forças do mal. (4) Raabe, a prostituta (Josué 2; 6): Incluída na genealogia de Cristo (Mateus 1:5), mostrando a graça de Deus para os pecadores. (5) As cidades de refúgio (Josué 20): Tipificam Cristo como nosso refúgio do pecado e da morte (Hebreus 6:18). A teologia reformada vê em Josué (Yeshua) um tipo claro de Jesus, o verdadeiro Salvador que conduz seu povo à salvação.",
            referencias: "Josué 1-24; Josué 5:13-15; Josué 6; Josué 20; Mateus 1:5; Hebreus 4:8; Hebreus 6:18"
        },
        {
            termo: "07. Juízes - Cristo como o Juiz e Libertador",
            definicao: "O livro de Juízes (Shoftim) narra o ciclo de pecado, opressão, clamor e libertação através dos juízes, que tipificam Cristo como Juiz e Libertador. (1) Os juízes como tipos de Cristo: (a) Otniel (Juízes 3:7-11) - o Espírito do SENHOR veio sobre ele. (b) Eúde (Juízes 3:12-30) - libertador de Israel. (c) Débora e Baraque (Juízes 4-5) - liderança profética. (d) Gideão (Juízes 6-8) - libertador que derrotou os midianitas. (e) Jefté (Juízes 10-12) - libertador apesar de sua origem humilde. (f) Sansão (Juízes 13-16) - tipo de Cristo em seu nascimento milagroso (anunciado por anjo), sua força, sua morte sacrificial ('morreram mais os que matou na sua morte do que os que matara na sua vida', Juízes 16:30). (2) A teofania do Anjo do SENHOR (Juízes 2:1-5; 6:11-24; 13:3-22): O Anjo do SENHOR é identificado como divino, recebendo adoração. Interpretado como o Verbo pré-encarnado. (3) A falta de um rei (Juízes 17:6; 21:25): 'Naqueles dias não havia rei em Israel; cada um fazia o que parecia direito aos seus olhos.' Cristo é o Rei que Israel precisava. A teologia reformada vê nos juízes tipos imperfeitos de Cristo, o Libertador perfeito que julga com justiça e salva seu povo.",
            referencias: "Juízes 2:1-5; Juízes 3-16; Juízes 6:11-24; Juízes 13:3-22; Juízes 17:6; Juízes 21:25; Atos 10:38; Romanos 2:16; 2 Timóteo 4:8"
        },
        {
            termo: "08. Rute - Cristo como o Remidor (Goel)",
            definicao: "O livro de Rute (Rut) narra a história de uma moabita que se torna ancestral de Davi e de Cristo. (1) Boaz como tipo de Cristo: Boaz é o 'remidor' (goel) que resgata Rute (a estrangeira) e a casa de Elimeleque. Cristo é o nosso Remidor (Goel) que nos resgata do pecado e da morte. 'Porque o Filho do Homem veio buscar e salvar o que se havia perdido' (Lucas 19:10). (2) O direito de remir (Rute 4:1-12): Boaz age como parente remidor, tipificando Cristo que, como nosso 'parente' (assumiu a natureza humana), tem o direito de nos redimir (Hebreus 2:14-18). (3) Rute, a gentia: Incluída na linhagem de Cristo (Mateus 1:5), mostrando que a salvação é para todos os povos (Gálatas 3:28). (4) A genealogia de Davi (Rute 4:18-22): Rute é bisavó de Davi, e Davi é ancestral de Jesus (Mateus 1:5-6). A teologia reformada vê em Boaz um tipo de Cristo, o Remidor que nos resgata da pobreza espiritual e nos torna herdeiros das promessas.",
            referencias: "Rute 1-4; Rute 4:1-12; Rute 4:18-22; Mateus 1:5-6; Lucas 19:10; Gálatas 3:28; Hebreus 2:14-18"
        },
        {
            termo: "09. 1 e 2 Samuel - Cristo como o Ungido (Messias) e o Filho de Davi",
            definicao: "Os livros de Samuel (Shemuel) narram a transição de Israel dos juízes para a monarquia, estabelecendo a dinastia davídica, que aponta para Cristo. (1) Davi como tipo de Cristo: Davi, o rei ungido, pastor do povo, guerreiro que derrotou Golias (tipo de Satanás). Jesus é o 'Filho de Davi' (Mateus 1:1), o Rei ungido, o Bom Pastor (João 10:11), que derrotou Satanás (Hebreus 2:14). (2) A Aliança Davídica (2 Samuel 7:12-16): Deus promete um descendente de Davi que reinaria para sempre. Cumprida em Cristo (Lucas 1:32-33; Atos 2:30-31). (3) Cristo como a Estrela da Manhã: 2 Samuel 23:4 fala do 'rei que reina sobre os homens... será como a luz da manhã'. (4) O Profeta Samuel como tipo de Cristo: Samuel foi profeta, sacerdote e juiz; Cristo é o Profeta, Sacerdote e Rei supremo. (5) A teofania da Arca: A Arca da Aliança (1 Samuel 4-6) tipifica Cristo como a presença de Deus. (6) O Filho de Davi: Jesus é chamado 'Filho de Davi' (Mateus 1:1; 9:27; 12:23; 15:22; 20:30-31; 21:9,15). A teologia reformada vê em Davi o tipo do Rei messiânico, e em Cristo o cumprimento perfeito da aliança davídica.",
            referencias: "1 Samuel 1-31; 2 Samuel 1-24; 2 Samuel 7:12-16; 2 Samuel 23:4; Mateus 1:1; Mateus 9:27; Mateus 21:9; Lucas 1:32-33; João 10:11; Atos 2:30-31; Atos 13:22-23; Romanos 1:3; Hebreus 1:5; Hebreus 2:14"
        },
        {
            termo: "10. 1 e 2 Reis - Cristo como o Rei da Paz e o Templo Verdadeiro",
            definicao: "Os livros de Reis (Melachim) narram a história dos reis de Israel e Judá, a construção do templo, o cativeiro. (1) Salomão como tipo de Cristo: Salomão, rei de paz (seu nome significa 'paz'), construtor do templo, conhecido por sua sabedoria. Jesus é maior que Salomão: 'Eis que está aqui quem é maior do que Salomão' (Mateus 12:42). (2) O Templo como tipo de Cristo: O templo de Salomão (1 Reis 5-8) era a habitação de Deus. Jesus é o verdadeiro templo: 'Destruí este templo, e em três dias o levantarei' (João 2:19-21). (3) O profeta Elias como tipo de João Batista: Elias confrontou Acabe e Jezabel; João Batista veio no 'espírito e poder de Elias' (Lucas 1:17). (4) O profeta Eliseu como tipo de Cristo: Eliseu realizou milagres (multiplicação de azeite, ressurreição do filho da sunamita, cura de Naamã), prefigurando os milagres de Cristo. (5) A teofania do Anjo do SENHOR (1 Reis 19:5-7). (6) A Rainha de Sabá (1 Reis 10:1-13): Ela veio ouvir a sabedoria de Salomão. Jesus disse: 'A rainha do sul se levantará no juízo com esta geração, e a condenará; porque veio dos confins da terra para ouvir a sabedoria de Salomão; e eis que está aqui quem é maior do que Salomão' (Mateus 12:42). A teologia reformada vê em Salomão um tipo imperfeito de Cristo, o verdadeiro Rei da Paz e o verdadeiro Templo.",
            referencias: "1 Reis 1-22; 2 Reis 1-25; 1 Reis 5-8; 1 Reis 10:1-13; Mateus 12:42; Lucas 1:17; Lucas 11:31; João 2:19-21; Atos 7:48-50; Colossenses 2:9; 1 Pedro 2:4-8"
        },
        {
            termo: "11. 1 e 2 Crônicas - Cristo como o Rei do Trono Eterno",
            definicao: "Os livros das Crônicas (Divrei HaYamim) recontam a história de Israel com ênfase no templo e na linhagem davídica, apontando para Cristo. (1) A genealogia de Adão a Davi (1 Crônicas 1-9): Mateus e Lucas usam genealogias para mostrar a descendência de Cristo. (2) Davi e a Arca (1 Crônicas 13-16): A arca trazida a Jerusalém tipifica a presença de Deus em Cristo. (3) A Aliança Davídica (1 Crônicas 17:11-14): 'Farei levantar a tua semente depois de ti... estabelecerei o seu reino para sempre' - cumprida em Cristo (Lucas 1:32-33). (4) Salomão e o Templo (2 Crônicas 1-7): O templo dedicado com oração e sacrifícios, tipo de Cristo. (5) O Rei Josias (2 Crônicas 34-35): Reforma e celebração da Páscoa, tipo da reforma espiritual em Cristo. (6) O fim do cativeiro e o decreto de Ciro (2 Crônicas 36:22-23): O retorno do exílio prefigura a redenção em Cristo. A teologia reformada vê nas Crônicas a fidelidade de Deus às suas promessas messiânicas, culminando em Cristo, o Filho de Davi.",
            referencias: "1 Crônicas 1-9; 1 Crônicas 13-17; 1 Crônicas 17:11-14; 2 Crônicas 1-7; 2 Crônicas 34-35; 2 Crônicas 36:22-23; Lucas 1:32-33; Atos 2:29-36"
        },
        {
            termo: "12. Esdras, Neemias e Ester - Cristo como o Restaurador e Protetor",
            definicao: "Esdras e Neemias narram o retorno do exílio e a reconstrução de Jerusalém; Ester narra a proteção divina dos judeus na Pérsia. (1) Cristo como o Restaurador: Zorobabel (descendente de Davi) liderou o retorno do exílio, tipo de Cristo que nos restaura do cativeiro do pecado. (2) A reconstrução do templo (Esdras 3-6): Tipo da restauração da adoração em Cristo. (3) Esdras, o escriba (Esdras 7-10): Tipo de Cristo como o mestre que ensina a lei. (4) Neemias e os muros de Jerusalém (Neemias 1-7): Tipo da proteção de Deus em Cristo. (5) A leitura da lei (Neemias 8): Tipo da pregação do evangelho. (6) Ester e a proteção dos judeus: Ester intercede pelo seu povo diante do rei Assuero, tipo de Cristo que intercede por nós diante do Pai (Romanos 8:34; Hebreus 7:25). (7) Mardoqueu, tipo de Cristo: exaltado depois da humilhação (Ester 6-10), prefigurando a exaltação de Cristo (Filipenses 2:9-11). (8) O jejum e a oração (Ester 4): Tipo da intercessão. A teologia reformada vê nestes livros a fidelidade de Deus ao seu povo, prefigurando a redenção em Cristo.",
            referencias: "Esdras 1-10; Neemias 1-13; Ester 1-10; Romanos 8:34; Filipenses 2:9-11; Hebreus 7:25; Hebreus 12:2"
        },
        {
            termo: "13. Jó - Cristo como o Redentor Vivo",
            definicao: "O livro de Jó (Iyov) trata do sofrimento do justo e aponta para Cristo, o Justo Sofredor. (1) A confissão de Jó (Jó 19:25-27): 'Eu sei que o meu Redentor vive, e que por fim se levantará sobre a terra.' Jó expressa a esperança na ressurreição e em um Redentor vindouro (Cristo). (2) Jó como tipo de Cristo: Jó era 'perfeito e reto, temente a Deus e que se desviava do mal' (Jó 1:1). Ele sofreu injustamente, foi despojado de tudo, e foi vindicado por Deus. Cristo é o Justo perfeito que sofreu injustamente e foi vindicado pela ressurreição. (3) O sofrimento redentor: Jó não sabia a razão de seu sofrimento; Cristo sofreu conscientemente pelos nossos pecados. (4) A teofania do Anjo do SENHOR (Jó 33:23-24): 'Se com ele houver um anjo, um intérprete... então terá compaixão dele, e dirá: Livra-o, para que não desça à cova; já tenho achado expiação.' Interpretado como referência a Cristo, o Mediador. (5) A restauração de Jó: No final, Deus restaurou a sorte de Jó (Jó 42:10-17), prefigurando a exaltação de Cristo e a restauração dos crentes. A teologia reformada vê em Jó um tipo do justo sofredor e em Cristo o cumprimento perfeito.",
            referencias: "Jó 1:1; Jó 19:25-27; Jó 33:23-24; Jó 42:10-17; Isaías 53; Mateus 27:46; 1 Pedro 2:21-25; 1 Pedro 3:18"
        },
        {
            termo: "14. Salmos - Cristo como o Rei, o Sacerdote e o Sofredor",
            definicao: "O livro de Salmos (Tehilim) é o hinário do AT, repleto de profecias messiânicas. Salmos messiânicos principais: (1) Salmo 2: 'Tu és meu Filho, hoje te gerei' - A realeza messiânica de Cristo. Citado em Atos 13:33; Hebreus 1:5; 5:5. (2) Salmo 8: 'Que é o homem, que dele te lembres?' - A humilhação e exaltação de Cristo. Citado em Hebreus 2:6-8. (3) Salmo 16: 'Não permitirás que o teu Santo veja corrupção' - A ressurreição de Cristo. Citado em Atos 2:25-28; 13:35. (4) Salmo 22: 'Deus meu, Deus meu, por que me desamparaste?' - A crucificação de Cristo. Citado em Mateus 27:35-46; Marcos 15:34; João 19:23-24. (5) Salmo 31:5: 'Nas tuas mãos encomendo o meu espírito' - As últimas palavras de Cristo na cruz (Lucas 23:46). (6) Salmo 34:20: 'Nem um osso seu será quebrado' - A morte de Cristo (João 19:36). (7) Salmo 40:6-8: 'Sacrifício e oferta não quiseste... então disse: Eis aqui venho' - A obediência de Cristo (Hebreus 10:5-10). (8) Salmo 41:9: 'Até o meu amigo íntimo... levantou contra mim o calcanhar' - A traição de Judas (João 13:18). (9) Salmo 45:6-7: 'O teu trono, ó Deus, é eterno' - A divindade de Cristo (Hebreus 1:8-9). (10) Salmo 68:18: 'Subiste ao alto, levaste cativo o cativeiro' - A ascensão de Cristo (Efésios 4:8). (11) Salmo 69:9: 'O zelo da tua casa me devorou' - O zelo de Cristo (João 2:17). (12) Salmo 69:21: 'Deram-me fel por mantimento, e na minha sede me deram vinagre' - O sofrimento de Cristo na cruz (Mateus 27:34,48). (13) Salmo 72: 'Dar-lhe-á domínio de mar a mar' - O reinado universal de Cristo. (14) Salmo 110: 'Assenta-te à minha direita' - A exaltação de Cristo como Rei e Sacerdote segundo Melquisedeque (Mateus 22:44; Atos 2:34-35; Hebreus 5:6; 7:17,21). (15) Salmo 118:22: 'A pedra que os edificadores rejeitaram' - Cristo, a pedra angular (Mateus 21:42; Atos 4:11; 1 Pedro 2:7). (16) Salmo 118:26: 'Bendito o que vem em nome do SENHOR' - A entrada triunfal (Mateus 21:9). A teologia reformada vê nos Salmos a cristologia mais rica do AT.",
            referencias: "Salmos 2; 8; 16; 22; 31; 34; 40; 41; 45; 68; 69; 72; 110; 118; Mateus 21:9; Mateus 21:42; Mateus 22:44; Mateus 27:34-46; Lucas 23:46; João 2:17; João 13:18; João 19:23-24; João 19:36; Atos 2:25-28; Atos 2:34-35; Atos 4:11; Atos 13:33; Romanos 15:3; Efésios 4:8; Hebreus 1:5; Hebreus 1:8-9; Hebreus 2:6-8; Hebreus 5:5-6; Hebreus 7:17; Hebreus 10:5-10; 1 Pedro 2:7"
        },
        {
            termo: "15. Provérbios, Eclesiastes e Cantares - Cristo como a Sabedoria",
            definicao: "Os livros sapienciais (Provérbios, Eclesiastes, Cantares) apresentam a Sabedoria personificada, identificada com Cristo. (1) Cristo como a Sabedoria (Provérbios 8:22-31): 'O SENHOR me possuía no princípio de seus caminhos... quando ele preparava os céus, aí estava eu.' Paulo identifica Cristo como a Sabedoria de Deus (1 Coríntios 1:24,30). (2) Provérbios 30:4: 'Qual é o seu nome, e qual é o nome de seu filho?' - Uma referência misteriosa ao Filho de Deus. (3) Cristo como o Eclesiastes (O Pregador): A busca pelo sentido da vida (Eclesiastes 1-12) encontra resposta em Cristo, 'o Caminho, a Verdade e a Vida' (João 14:6). (4) Cristo como o Amado (Cantares 1-8): O livro de Cantares (Shir HaShirim) é interpretado tipologicamente como o amor entre Cristo (o Amado) e a igreja (a amada). 'O meu amado é meu e eu sou dele' (Cantares 2:16). A teologia reformada vê em Cantares a união de Cristo com a igreja (Efésios 5:25-32). (5) Cristo como o Leão de Judá (Provérbios 28:1; 30:30). (6) A mulher virtuosa (Provérbios 31:10-31): Tipo da igreja, a noiva de Cristo. A teologia reformada valoriza a interpretação cristocêntrica dos livros sapienciais.",
            referencias: "Provérbios 1-31; Provérbios 8:22-31; Provérbios 30:4; Eclesiastes 1-12; Cantares 1-8; Cantares 2:16; João 14:6; 1 Coríntios 1:24; 1 Coríntios 1:30; Efésios 5:25-32; Colossenses 2:2-3"
        },
        {
            termo: "16. Isaías - O Evangelho do Antigo Testamento",
            definicao: "O livro de Isaías (Yeshayahu) é chamado de 'o quinto evangelho' por suas numerosas profecias messiânicas. (1) Isaías 7:14 - O Nascimento Virginal: 'Eis que a virgem conceberá, e dará à luz um filho, e chamará o seu nome Emanuel' (Mateus 1:22-23). (2) Isaías 9:6-7 - O Filho dado: 'Porque um menino nos nasceu, um filho se nos deu... e será o seu nome: Maravilhoso, Conselheiro, Deus Forte, Pai da Eternidade, Príncipe da Paz.' Títulos divinos aplicados a Cristo. (3) Isaías 11:1-2 - O Rebento de Jessé: 'Porque brotará um rebento do tronco de Jessé, e das suas raízes um renovo frutificará. E repousará sobre ele o Espírito do Senhor.' (4) Isaías 35:5-6 - Os Milagres do Messias: 'Então os olhos dos cegos serão abertos... o coxo saltará como cervo.' Citado por Jesus (Mateus 11:2-6). (5) Isaías 40:3 - A Voz do que clama no deserto: 'Preparai o caminho do Senhor' - João Batista (Mateus 3:3; Marcos 1:3; Lucas 3:4-6). (6) Isaías 42:1-4 - O Servo Escolhido: 'Eis aqui o meu servo... porei sobre ele o meu Espírito.' Aplicado a Cristo em Mateus 12:18-21. (7) Isaías 49:6 - Luz para os Gentios: 'Também te darei como luz dos gentios, para que sejas a minha salvação até à extremidade da terra.' (8) Isaías 50:4-11 - O Servo Obediente: 'O Senhor Deus me abriu os ouvidos, e eu não fui rebelde.' (9) Isaías 52:13-53:12 - O Servo Sofredor (o mais importante capítulo messiânico): (a) 'Ele foi traspassado pelas nossas transgressões e moído pelas nossas iniquidades' (53:5). (b) 'Pelas suas pisaduras fomos sarados' (53:5). (c) 'O Senhor fez cair sobre ele a iniquidade de todos nós' (53:6). (d) 'Como cordeiro foi levado ao matadouro' (53:7). (e) 'Levou sobre si o pecado de muitos e intercedeu pelos transgressores' (53:12). Este capítulo é citado em Mateus 8:17; Lucas 22:37; João 12:38; Atos 8:32-33; Romanos 10:16; 1 Pedro 2:22-25. (10) Isaías 61:1-3 - A Unção do Espírito: 'O Espírito do Senhor Deus está sobre mim, porque o Senhor me ungiu para pregar boas novas aos pobres...' Jesus leu este texto na sinagoga de Nazaré e disse: 'Hoje se cumpriu esta Escritura' (Lucas 4:16-21). A teologia reformada vê em Isaías a mais rica cristologia do AT.",
            referencias: "Isaías 1-66; Isaías 7:14; Isaías 9:6-7; Isaías 11:1-2; Isaías 35:5-6; Isaías 40:3; Isaías 42:1-4; Isaías 49:6; Isaías 50:4-11; Isaías 52:13-53:12; Isaías 61:1-3; Mateus 1:22-23; Mateus 3:3; Mateus 8:17; Mateus 11:2-6; Mateus 12:18-21; Lucas 4:16-21; Lucas 22:37; João 12:38; Atos 8:32-33; Romanos 10:16; 1 Pedro 2:22-25"
        },
        {
            termo: "17. Jeremias, Lamentações e Ezequiel - Cristo como a Nova Aliança e o Pastor",
            definicao: "Jeremias, Lamentações e Ezequiel são profetas do exílio, que apontam para a restauração em Cristo. (1) Jeremias 23:5-6 - O Renovo Justo: 'Eis que dias vêm... em que levantarei a Davi um Renovo justo... e este será o seu nome: O SENHOR JUSTIÇA NOSSA.' (2) Jeremias 31:31-34 - A Nova Aliança: 'Eis que dias vêm... em que farei uma nova aliança com a casa de Israel... Porei a minha lei no seu interior... porque perdoarei a sua maldade.' Jesus instituiu a nova aliança na ceia (Lucas 22:20; 1 Coríntios 11:25). (3) Jeremias 33:14-16 - O Renovo de Justiça. (4) Lamentações 3:22-23 - As misericórdias do Senhor: 'As misericórdias do Senhor são a causa de não sermos consumidos... renovam-se cada manhã.' Cumpridas em Cristo. (5) Ezequiel 34:11-24 - O Bom Pastor: 'Eis que eu mesmo procurarei as minhas ovelhas... levantarei sobre elas um só pastor, o meu servo Davi.' Jesus é o Bom Pastor (João 10:11-18). (6) Ezequiel 36:24-28 - O Coração Novo: 'Dar-vos-ei um coração novo... porei dentro de vós o meu Espírito.' Cumprido em Cristo (2 Coríntios 3:3; 5:17). (7) Ezequiel 37:1-14 - O Vale de Ossos Secos: A ressurreição espiritual, cumprida em Cristo (Efésios 2:1-10). (8) Ezequiel 40-48 - O Templo Ideal: Tipo da presença de Deus em Cristo e da nova Jerusalém (Apocalipse 21-22). A teologia reformada vê em Jeremias e Ezequiel as promessas da nova aliança cumpridas em Cristo.",
            referencias: "Jeremias 23:5-6; Jeremias 31:31-34; Jeremias 33:14-16; Lamentações 3:22-23; Ezequiel 34:11-24; Ezequiel 36:24-28; Ezequiel 37:1-14; Ezequiel 40-48; Lucas 22:20; João 10:11-18; 1 Coríntios 11:25; 2 Coríntios 3:3; 2 Coríntios 5:17; Efésios 2:1-10; Apocalipse 21-22"
        },
        {
            termo: "18. Daniel - Cristo como o Filho do Homem e a Pedra que Destrói",
            definicao: "O livro de Daniel (Daniyyel) contém visões proféticas do Messias. (1) Daniel 2:31-45 - A Pedra que Destrói os Reinos: A estátua dos reinos mundiais é destruída por uma pedra 'cortada sem mãos'. A pedra é Cristo, que estabelecerá um reino eterno. (2) Daniel 7:13-14 - O Filho do Homem: 'Eis que vinha nas nuvens do céu um como o filho do homem... e foi-lhe dado domínio, e honra, e reino.' Jesus usou este título para si mesmo (Mateus 26:64; Marcos 14:62; Lucas 22:69). (3) Daniel 9:24-27 - As Setenta Semanas (70 semanas de anos): Profecia do tempo da vinda do Messias. 'Saberás e entenderás... que o Messias virá.' O Messias seria 'cortado' (morto). (4) Daniel 10-12 - A visão do homem glorioso: Interpretado como uma teofania de Cristo. (5) Os três jovens na fornalha (Daniel 3): 'Eis que vejo quatro homens soltos... e o aspecto do quarto é semelhante ao filho de Deus.' (6) Daniel na cova dos leões (Daniel 6): Tipo da ressurreição de Cristo. A teologia reformada vê em Daniel a visão do Filho do Homem (Cristo) recebendo domínio eterno.",
            referencias: "Daniel 2:31-45; Daniel 3; Daniel 6; Daniel 7:13-14; Daniel 9:24-27; Daniel 10-12; Mateus 24:30; Mateus 26:64; Marcos 14:62; Lucas 22:69; Atos 7:55-56; Apocalipse 1:7; Apocalipse 14:14"
        },
        {
            termo: "19. Oseias, Joel, Amós, Obadias, Jonas, Miqueias, Naum, Habacuque, Sofonias, Ageu, Zacarias, Malaquias - Os Profetas Menores",
            definicao: "Os profetas menores (doze livros) contêm numerosas profecias messiânicas e tipos de Cristo. (1) Oseias 11:1: 'Do Egito chamei o meu filho' - aplicado a Cristo em Mateus 2:15. Oseias 3:5: 'Buscarão ao Senhor seu Deus, e a Davi, seu rei' (Cristo). (2) Joel 2:28-32: 'Derramarei o meu Espírito sobre toda a carne' - cumprido em Pentecostes (Atos 2:16-21). (3) Amós 9:11-12: 'Levantarei o tabernáculo de Davi' - aplicado à inclusão dos gentios em Cristo (Atos 15:16-18). (4) Obadias 21: 'E o reino será do Senhor' - Cristo reinará. (5) Jonas 1:17: 'Jonas esteve três dias e três noites no ventre do peixe' - Jesus aplica a si mesmo: 'Assim como Jonas esteve três dias... assim estará o Filho do Homem três dias...' (Mateus 12:40). (6) Miqueias 5:2: 'E tu, Belém Efrata... de ti me sairá o que será Senhor em Israel, e cujas origens são desde os dias da eternidade' - O nascimento de Cristo em Belém (Mateus 2:6; João 7:42). (7) Naum 1:15: 'Eis sobre os montes os pés do que traz as boas novas' - Referência à pregação do evangelho (Romanos 10:15). (8) Habacuque 2:4: 'O justo viverá pela sua fé' - Citado por Paulo (Romanos 1:17; Gálatas 3:11) e por Hebreus (Hebreus 10:38). (9) Sofonias 3:14-17: 'O Senhor teu Deus está no meio de ti, poderoso para te salvar' - Cristo habita no meio do seu povo. (10) Ageu 2:6-7: 'Virei a todas as nações... e encherei esta casa de glória' - Cristo é a glória do segundo templo (Lucas 2:32). (11) Zacarias 3:8-9: 'Eis que eu farei vir o meu servo, o Renovo' (Cristo). Zacarias 6:12-13: 'Eis o homem cujo nome é Renovo' (Cristo). Zacarias 9:9: 'Eis que o teu rei virá... justo e salvo, humilde, montado em um jumento' - A entrada triunfal (Mateus 21:4-5; João 12:14-15). Zacarias 11:12-13: 'Pesaram o meu salário, trinta moedas de prata' - A traição de Judas (Mateus 26:15; 27:9-10). Zacarias 12:10: 'Olharão para mim, a quem traspassaram' - A crucificação (João 19:37). Zacarias 13:7: 'Fere o pastor, e as ovelhas se dispersarão' - A morte de Cristo (Mateus 26:31). Zacarias 14:4-5: 'Seus pés estarão naquele dia sobre o monte das Oliveiras' - A segunda vinda de Cristo. (12) Malaquias 3:1: 'Eis que eu envio o meu anjo... e o Senhor, a quem vós buscais, virá de repente ao seu templo' - Referência a João Batista e a Cristo (Mateus 11:10; Marcos 1:2; Lucas 1:76). Malaquias 4:2: 'Para vós, os que temeis o meu nome, nascerá o sol da justiça' - Cristo é a luz do mundo. A teologia reformada vê nos profetas menores a preparação para a vinda de Cristo.",
            referencias: "Oseias 1-14; Joel 1-3; Amós 1-9; Obadias 1; Jonas 1-4; Miqueias 1-7; Naum 1-3; Habacuque 1-3; Sofonias 1-3; Ageu 1-2; Zacarias 1-14; Malaquias 1-4; Mateus 2:6; Mateus 2:15; Mateus 11:10; Mateus 12:40; Mateus 21:4-5; Mateus 26:15; Mateus 26:31; Mateus 27:9-10; Lucas 1:76; Lucas 2:32; João 7:42; João 12:14-15; João 19:37; Atos 2:16-21; Atos 15:16-18; Romanos 1:17; Romanos 10:15; Gálatas 3:11; Hebreus 10:38"
        },
        {
            termo: "20. Mateus - Cristo como o Messias-Rei e o Novo Moisés",
            definicao: "O Evangelho de Mateus apresenta Jesus como o Messias prometido, o Filho de Davi, o novo Moisés e Emanuel ('Deus conosco'). (1) Genealogia de Jesus (Mateus 1:1-17): Jesus é o Filho de Davi e Filho de Abraão. (2) Nascimento virginal (Mateus 1:18-25): Cumprimento de Isaías 7:14. (3) A adoração dos magos (Mateus 2:1-12): Os gentios adoram o Rei dos judeus. (4) O Sermão do Monte (Mateus 5-7): Jesus como o novo Moisés, que dá a lei no monte. 'Bem-aventurados os pobres de espírito...' (5) Os milagres (Mateus 8-9): Demonstram a autoridade de Cristo. (6) A confissão de Pedro (Mateus 16:13-20): 'Tu és o Cristo, o Filho do Deus vivo.' (7) A transfiguração (Mateus 17:1-8): Revela a glória divina de Cristo. (8) A grande comissão (Mateus 28:18-20): 'Toda a autoridade me foi dada... ide, ensinai todas as nações... e eis que estou convosco todos os dias.' A teologia reformada vê em Mateus o evangelho do Rei.",
            referencias: "Mateus 1-28; Mateus 1:1-17; Mateus 1:18-25; Mateus 2:1-12; Mateus 5-7; Mateus 8-9; Mateus 16:13-20; Mateus 17:1-8; Mateus 28:18-20"
        },
        {
            termo: "21. Marcos - Cristo como o Servo Sofredor e o Filho de Deus",
            definicao: "O Evangelho de Marcos apresenta Jesus como o Servo Sofredor, o Filho de Deus poderoso em obras. (1) 'Princípio do evangelho de Jesus Cristo, Filho de Deus' (Marcos 1:1). (2) O batismo de Jesus (Marcos 1:9-11): A voz do Pai: 'Tu és meu Filho amado.' (3) A tentação (Marcos 1:12-13): Jesus vence Satanás. (4) Milagres: cura de endemoninhado (1:21-28), paralítico (2:1-12), leproso (1:40-45), tempestade acalmada (4:35-41), endemoninhado gadareno (5:1-20). (5) A confissão de Pedro (Marcos 8:27-30): 'Tu és o Cristo.' (6) O primeiro anúncio da paixão (Marcos 8:31-33). (7) A transfiguração (Marcos 9:2-8). (8) O segundo anúncio da paixão (Marcos 9:30-32). (9) O terceiro anúncio da paixão (Marcos 10:32-34). (10) 'O Filho do Homem não veio para ser servido, mas para servir, e para dar a sua vida em resgate de muitos' (Marcos 10:45). (11) A crucificação (Marcos 15:21-41): 'Verdadeiramente este homem era o Filho de Deus' (Marcos 15:39). (12) A ressurreição (Marcos 16:1-8). A teologia reformada vê em Marcos o evangelho da ação e do sofrimento de Cristo.",
            referencias: "Marcos 1-16; Marcos 1:1; Marcos 1:9-11; Marcos 1:12-13; Marcos 8:27-33; Marcos 9:2-8; Marcos 10:45; Marcos 15:21-41; Marcos 16:1-8"
        },
        {
            termo: "22. Lucas - Cristo como o Salvador Universal e o Homem Perfeito",
            definicao: "O Evangelho de Lucas apresenta Jesus como o Salvador universal (para judeus e gentios, pobres e ricos, homens e mulheres) e o Homem perfeito (compassivo, orante, justo). (1) Narrativas da infância (Lucas 1-2): Anunciação, Magnificat, nascimento em Belém, anjos, pastores, Simeão, Ana. (2) Genealogia de Jesus até Adão (Lucas 3:23-38): Ênfase na universalidade. (3) O sermão na sinagoga de Nazaré (Lucas 4:16-21): Jesus lê Isaías 61:1-2 e diz: 'Hoje se cumpriu esta Escritura.' (4) Parábolas exclusivas de Lucas: Bom Samaritano (10:25-37), Filho Pródigo (15:11-32), Rico e Lázaro (16:19-31), Fariseu e Publicano (18:9-14). (5) Ênfase nos marginalizados: pobres (4:18; 6:20-23), mulheres (7:36-50; 8:1-3; 10:38-42), publicanos (5:27-32; 19:1-10), samaritanos (10:30-37; 17:11-19). (6) A oração de Jesus: Lucas enfatiza a oração de Jesus (3:21; 5:16; 6:12; 9:18,28; 11:1; 22:31-32,39-46). (7) A entrada triunfal (Lucas 19:28-44). (8) A crucificação (Lucas 23:26-49): 'Pai, perdoa-lhes, porque não sabem o que fazem' (23:34); 'Hoje estarás comigo no paraíso' (23:43); 'Pai, nas tuas mãos entrego o meu espírito' (23:46). (9) O caminho de Emaús (Lucas 24:13-35): 'Começando por Moisés e por todos os profetas, explicava-lhes o que dele se achava em todas as Escrituras' (24:27). (10) A ascensão (Lucas 24:50-53). A teologia reformada vê em Lucas o evangelho da compaixão e da universalidade da salvação.",
            referencias: "Lucas 1-24; Lucas 1-2; Lucas 3:23-38; Lucas 4:16-21; Lucas 10:25-37; Lucas 15:11-32; Lucas 16:19-31; Lucas 18:9-14; Lucas 19:28-44; Lucas 23:26-49; Lucas 24:13-35; Lucas 24:50-53"
        },
        {
            termo: "23. João - Cristo como o Verbo Encarnado e o Filho de Deus",
            definicao: "O Evangelho de João apresenta a cristologia mais elevada do NT: Jesus é o Logos (Verbo) eterno, o Filho de Deus, a Luz do Mundo, o Pão da Vida, o Bom Pastor, a Ressurreição e a Vida, o Caminho, a Verdade e a Vida. (1) O Prólogo (João 1:1-18): 'No princípio era o Verbo... o Verbo era Deus... o Verbo se fez carne.' (2) Os sete sinais (semeia): (a) Água transformada em vinho (2:1-11). (b) Cura do filho do oficial (4:46-54). (c) Cura do paralítico (5:1-15). (d) Multiplicação dos pães (6:1-14). (e) Jesus anda sobre o mar (6:16-21). (f) Cura do cego (9:1-12). (g) Ressurreição de Lázaro (11:1-44). (3) Os sete 'Eu Sou': (a) 'Eu sou o pão da vida' (6:35). (b) 'Eu sou a luz do mundo' (8:12). (c) 'Eu sou a porta das ovelhas' (10:7,9). (d) 'Eu sou o bom pastor' (10:11,14). (e) 'Eu sou a ressurreição e a vida' (11:25). (f) 'Eu sou o caminho, a verdade e a vida' (14:6). (g) 'Eu sou a videira verdadeira' (15:1,5). (4) O 'Eu Sou' absoluto: 'Antes que Abraão existisse, EU SOU' (João 8:58). (5) A oração sacerdotal (João 17): Jesus ora por si mesmo, pelos discípulos e por todos os crentes. (6) A paixão e ressurreição (João 18-21). (7) Tomé confessa: 'Senhor meu, e Deus meu!' (João 20:28). (8) O propósito do evangelho: 'Estes, porém, foram escritos para que creiais que Jesus é o Cristo, o Filho de Deus, e para que, crendo, tenhais vida em seu nome' (João 20:31). A teologia reformada vê em João a mais alta afirmação da divindade de Cristo.",
            referencias: "João 1-21; João 1:1-18; João 2:1-11; João 4:46-54; João 5:1-15; João 6:1-14; João 6:16-21; João 6:35; João 8:12; João 8:58; João 9:1-12; João 10:7-18; João 11:1-44; João 11:25; João 14:6; João 15:1-5; João 17:1-26; João 18-21; João 20:28; João 20:31"
        },
        {
            termo: "24. Atos dos Apóstolos - Cristo como o Senhor Ressurreto e o Espírito Derramado",
            definicao: "O livro de Atos (Atos dos Apóstolos) narra a ascensão de Cristo, o derramamento do Espírito Santo e a expansão da igreja. (1) A ascensão (Atos 1:9-11): 'Este Jesus... há de vir assim como para o céu o vistes ir.' (2) A promessa do Espírito (Atos 1:4-5,8): 'Recebereis a virtude do Espírito Santo... e ser-me-eis testemunhas.' (3) Pentecostes (Atos 2:1-13): O Espírito é derramado. (4) O primeiro sermão de Pedro (Atos 2:14-41): 'A este Jesus, Deus o ressuscitou... ele foi feito Senhor e Cristo.' (5) A cura do coxo (Atos 3:1-10): 'Em nome de Jesus Cristo, o Nazareno, levanta-te e anda.' (6) A pregação da ressurreição: 'Vós matastes o Autor da vida, mas Deus o ressuscitou' (Atos 3:15). (7) Estêvão (Atos 6-7): 'Vejo os céus abertos, e o Filho do Homem em pé à direita de Deus' (Atos 7:55-56). (8) A conversão de Saulo (Atos 9:1-9): 'Eu sou Jesus, a quem tu persegues.' (9) A pregação de Paulo (Atos 13-28): 'A fé em Cristo' (Atos 20:21). A teologia reformada vê em Atos a continuação da obra de Cristo através do Espírito.",
            referencias: "Atos 1-28; Atos 1:4-5; Atos 1:8; Atos 1:9-11; Atos 2:1-13; Atos 2:14-41; Atos 3:1-10; Atos 3:15; Atos 7:55-56; Atos 9:1-9; Atos 20:21"
        },
        {
            termo: "25. Romanos - Cristo como a Justiça de Deus e o Segundo Adão",
            definicao: "A Epístola aos Romanos é a mais sistemática exposição do evangelho de Paulo. (1) Cristo na introdução (Romanos 1:1-4): 'Acerca de seu Filho... que foi feito da semente de Davi segundo a carne... declarado Filho de Deus com poder... pela ressurreição dos mortos.' (2) A justificação pela fé em Cristo (Romanos 3:21-31): 'Justificados gratuitamente pela sua graça, pela redenção que há em Cristo Jesus.' (3) A propiciação (Romanos 3:25): 'A quem Deus propôs para propiciação pela fé no seu sangue.' (4) Cristo como o segundo Adão (Romanos 5:12-21): 'Assim como por um só homem entrou o pecado... assim também por um só homem, a justiça.' (5) União com Cristo (Romanos 6:1-14): 'Batizados em Jesus Cristo, fomos batizados na sua morte.' (6) A lei e o pecado (Romanos 7:1-25): 'Graças a Deus por Jesus Cristo nosso Senhor.' (7) A vida no Espírito (Romanos 8:1-17): 'Nenhuma condenação há para os que estão em Cristo Jesus.' (8) A intercessão de Cristo (Romanos 8:34): 'Está à direita de Deus, e também intercede por nós.' (9) A eleição em Cristo (Romanos 8:29-30; 9-11). (10) A confissão de Jesus como Senhor (Romanos 10:9-10). (11) A doxologia final (Romanos 11:33-36): 'Porque dele e por ele, e para ele, são todas as coisas.' (12) Exortações (Romanos 12-15): 'Sede meus imitadores, como também eu sou de Cristo' (1 Coríntios 11:1). A teologia reformada vê em Romanos o coração da doutrina da justificação pela fé em Cristo.",
            referencias: "Romanos 1-16; Romanos 1:1-4; Romanos 3:21-31; Romanos 3:25; Romanos 5:12-21; Romanos 6:1-14; Romanos 8:1-17; Romanos 8:34; Romanos 10:9-10; Romanos 11:33-36"
        },
        {
            termo: "26. 1 e 2 Coríntios - Cristo como a Sabedoria de Deus e a Cabeça",
            definicao: "As epístolas aos Coríntios tratam de problemas na igreja e afirmam a centralidade de Cristo. (1) 1 Coríntios 1:22-24: 'Cristo, poder de Deus e sabedoria de Deus.' (2) 1 Coríntios 1:30: 'Ele nos foi feito por Deus sabedoria, e justiça, e santificação, e redenção.' (3) 1 Coríntios 2:2: 'Porque não me propus saber coisa alguma entre vós, senão a Jesus Cristo, e este crucificado.' (4) Cristo como fundamento (1 Coríntios 3:11): 'Ninguém pode pôr outro fundamento, além do que já está posto, o qual é Jesus Cristo.' (5) Cristo como a Páscoa (1 Coríntios 5:7): 'Cristo, nossa Páscoa, foi sacrificado por nós.' (6) A Ceia do Senhor (1 Coríntios 11:23-26). (7) O corpo de Cristo (1 Coríntios 12:12-27). (8) O capítulo do amor (1 Coríntios 13): Cristo é o amor encarnado. (9) A ressurreição de Cristo (1 Coríntios 15:1-58): 'Se Cristo não ressuscitou, é vã a nossa pregação.' (10) 2 Coríntios 3:18: 'Somos transformados na mesma imagem de Cristo.' (11) A reconciliação (2 Coríntios 5:18-21): 'Deus estava em Cristo reconciliando consigo o mundo.' (12) A graça de Cristo (2 Coríntios 8:9): 'Sendo rico, por amor de vós se fez pobre.' (13) A suficiência da graça de Cristo (2 Coríntios 12:9): 'A minha graça te basta.' A teologia reformada vê nas epístolas aos Coríntios a centralidade da cruz e da ressurreição.",
            referencias: "1 Coríntios 1-16; 2 Coríntios 1-13; 1 Coríntios 1:22-24; 1 Coríntios 1:30; 1 Coríntios 2:2; 1 Coríntios 3:11; 1 Coríntios 5:7; 1 Coríntios 11:23-26; 1 Coríntios 12:12-27; 1 Coríntios 15:1-58; 2 Coríntios 3:18; 2 Coríntios 5:18-21; 2 Coríntios 8:9; 2 Coríntios 12:9"
        },
        {
            termo: "27. Gálatas, Efésios, Filipenses, Colossenses - Cristo como Liberdade, Cabeça, Exemplo e Supremo",
            definicao: "As epístolas da prisão (Efésios, Filipenses, Colossenses) e Gálatas contêm alta cristologia. (1) Gálatas 2:20: 'Já estou crucificado com Cristo; e vivo, não mais eu, mas Cristo vive em mim.' (2) Gálatas 3:13: 'Cristo nos resgatou da maldição da lei, fazendo-se maldição por nós.' (3) Gálatas 3:16: 'A semente... que é Cristo.' (4) Gálatas 4:4-5: 'Veio a plenitude dos tempos... Deus enviou seu Filho.' (5) Efésios 1:3-14: 'Toda bênção espiritual em Cristo.' (6) Efésios 1:20-23: 'Cristo assentado à sua direita... cabeça da igreja.' (7) Efésios 2:13-18: 'Em Cristo Jesus, vós, que antes estáveis longe, já perto estais.' (8) Efésios 4:15-16: 'Crescimento no corpo, que é Cristo.' (9) Efésios 5:22-33: O casamento como tipo de Cristo e a igreja. (10) Filipenses 1:21: 'Para mim o viver é Cristo, e o morrer é ganho.' (11) Filipenses 2:5-11: O hino da kenosis (esvaziamento). (12) Filipenses 3:7-11: 'Conhecer a Cristo... a virtude da sua ressurreição.' (13) Colossenses 1:15-20: O hino da supremacia de Cristo. (14) Colossenses 2:9: 'Nele habita corporalmente toda a plenitude da divindade.' A teologia reformada vê nestas epístolas a mais alta cristologia paulina.",
            referencias: "Gálatas 1-6; Efésios 1-6; Filipenses 1-4; Colossenses 1-4; Gálatas 2:20; Gálatas 3:13; Gálatas 3:16; Gálatas 4:4-5; Efésios 1:3-14; Efésios 1:20-23; Efésios 2:13-18; Efésios 4:15-16; Efésios 5:22-33; Filipenses 1:21; Filipenses 2:5-11; Filipenses 3:7-11; Colossenses 1:15-20; Colossenses 2:9"
        },
        {
            termo: "28. Tessalonicenses, Timóteo, Tito, Filemom - Cristo como o Senhor que Vem e o Mediador",
            definicao: "As epístolas pastorais (1-2 Timóteo, Tito) e as epístolas a Tessalônica e a Filemom tratam da segunda vinda e da ordem da igreja. (1) 1 Tessalonicenses 1:9-10: 'Servir ao Deus vivo... e esperar dos céus a seu Filho Jesus.' (2) 1 Tessalonicenses 4:16-17: A parusia (segunda vinda). (3) 2 Tessalonicenses 1:7-10: A vinda de Cristo com seus anjos. (4) 1 Timóteo 2:5: 'Há um só Deus, e um só Mediador... Jesus Cristo.' (5) 1 Timóteo 3:16: 'Grande é o mistério da piedade: Deus se manifestou em carne.' (6) 2 Timóteo 1:9-10: 'Graça... em Cristo Jesus... que manifestou a vida e a imortalidade pelo evangelho.' (7) 2 Timóteo 2:8: 'Lembra-te de que Jesus Cristo... ressuscitou dentre os mortos.' (8) Tito 2:11-14: 'A graça de Deus se manifestou... aguardando a bem-aventurada esperança.' (9) Tito 2:13: 'O grande Deus e nosso Salvador Jesus Cristo.' (10) Filemom 1:6: 'A fé que temos em comum com Cristo Jesus.' A teologia reformada vê nestas epístolas a esperança da parusia e a ordem da igreja centrada em Cristo.",
            referencias: "1 Tessalonicenses 1-5; 2 Tessalonicenses 1-3; 1 Timóteo 1-6; 2 Timóteo 1-4; Tito 1-3; Filemom 1; 1 Tessalonicenses 1:9-10; 1 Tessalonicenses 4:16-17; 2 Tessalonicenses 1:7-10; 1 Timóteo 2:5; 1 Timóteo 3:16; 2 Timóteo 1:9-10; 2 Timóteo 2:8; Tito 2:11-14; Tito 2:13"
        },
        {
            termo: "29. Hebreus, Tiago, Pedro, João, Judas - Cristo como Sumo Sacerdote e Senhor",
            definicao: "As epístolas gerais (Hebreus, Tiago, 1-2 Pedro, 1-3 João, Judas) apresentam Cristo como o Sumo Sacerdote, o exemplo, o amor encarnado. (1) Hebreus 1:1-4: Cristo superior aos profetas e aos anjos. (2) Hebreus 4:14-16: 'Temos um grande sumo sacerdote, Jesus, Filho de Deus.' (3) Hebreus 5:5-10: Cristo sacerdote segundo a ordem de Melquisedeque. (4) Hebreus 7:1-28: A superioridade do sacerdócio de Cristo. (5) Hebreus 9:11-28: Cristo entrou no santuário celestial com seu próprio sangue. (6) Hebreus 10:1-18: O sacrifício perfeito de Cristo. (7) Tiago 2:1: 'A fé em nosso Senhor Jesus Cristo, Senhor da glória.' (8) 1 Pedro 2:21-25: 'Cristo padeceu por nós, deixando-nos o exemplo.' (9) 1 Pedro 3:18: 'Cristo morreu uma vez pelos pecados, o justo pelos injustos.' (10) 2 Pedro 1:1: 'Justiça do nosso Deus e Salvador Jesus Cristo.' (11) 1 João 1:1-4: 'O Verbo da vida' (João testemunha ocular). (12) 1 João 2:1-2: 'Temos um Advogado para com o Pai, Jesus Cristo, o justo. Ele é a propiciação pelos nossos pecados.' (13) 1 João 4:2-3: 'Confessar que Jesus Cristo veio em carne.' (14) 1 João 5:20: 'Este é o verdadeiro Deus e a vida eterna.' (15) 2 João 1:7: 'Os que não confessam que Jesus Cristo veio em carne.' (16) Judas 1:4: 'Negam a Deus, único dominador e Senhor nosso, Jesus Cristo.' A teologia reformada vê nestas epístolas a cristologia da experiência e da conduta.",
            referencias: "Hebreus 1-13; Tiago 1-5; 1 Pedro 1-5; 2 Pedro 1-3; 1 João 1-5; 2 João 1; 3 João 1; Judas 1; Hebreus 1:1-4; Hebreus 4:14-16; Hebreus 7:1-28; Hebreus 9:11-28; Hebreus 10:1-18; Tiago 2:1; 1 Pedro 2:21-25; 1 Pedro 3:18; 2 Pedro 1:1; 1 João 1:1-4; 1 João 2:1-2; 1 João 4:2-3; 1 João 5:20; 2 João 1:7; Judas 1:4"
        },
        {
            termo: "30. Apocalipse - Cristo como o Cordeiro, o Leão e o Rei dos Reis",
            definicao: "O Apocalipse (Revelação) apresenta a visão gloriosa de Cristo como o Cordeiro que foi morto, o Leão de Judá, o Rei dos reis e Senhor dos senhores. (1) Apocalipse 1:5-6: 'Da parte de Jesus Cristo... o primogênito dos mortos.' (2) Apocalipse 1:8: 'Eu sou o Alfa e o Ômega.' (3) Apocalipse 1:12-18: A visão do Cristo glorificado: 'Eu sou o primeiro e o último; e o que vivo e fui morto.' (4) Apocalipse 3:14: 'O Amém, a testemunha fiel e verdadeira, o princípio da criação de Deus.' (5) Apocalipse 5:5-6: O Leão de Judá (o Cordeiro). (6) Apocalipse 5:9-14: 'Digno é o Cordeiro, que foi morto, de receber o poder, e riquezas, e sabedoria, e força, e honra, e glória, e ações de graças.' (7) Apocalipse 7:9-17: A multidão vestida de branco lavada no sangue do Cordeiro. (8) Apocalipse 11:15: 'O reino do mundo passou a ser de nosso Senhor e do seu Cristo.' (9) Apocalipse 12:11: 'Venceram pelo sangue do Cordeiro.' (10) Apocalipse 17:14: 'O Cordeiro os vencerá, porque é o Senhor dos senhores e o Rei dos reis.' (11) Apocalipse 19:11-16: A visão de Cristo voltando em um cavalo branco: 'REI DOS REIS, E SENHOR DOS SENHORES.' (12) Apocalipse 21:22-23: 'O seu templo é o Senhor Deus Todo-poderoso, e o Cordeiro. A lâmpada é o Cordeiro.' (13) Apocalipse 22:12-13: 'Eis que cedo venho... Eu sou o Alfa e o Ômega.' (14) Apocalipse 22:16: 'Eu, Jesus... sou a raiz e a geração de Davi, a resplandecente estrela da manhã.' (15) Apocalipse 22:20-21: 'Aquele que testifica estas coisas diz: Certamente cedo venho. Amém. Ora vem, Senhor Jesus.' A teologia reformada vê no Apocalipse a consumação do reinado de Cristo e a esperança da sua igreja.",
            referencias: "Apocalipse 1-22; Apocalipse 1:5-6; Apocalipse 1:8; Apocalipse 1:12-18; Apocalipse 3:14; Apocalipse 5:5-6; Apocalipse 5:9-14; Apocalipse 7:9-17; Apocalipse 11:15; Apocalipse 12:11; Apocalipse 17:14; Apocalipse 19:11-16; Apocalipse 21:22-23; Apocalipse 22:12-13; Apocalipse 22:16; Apocalipse 22:20-21"
        }
    ]
};