// volume/volume-75.js
window.LIVRO_DATA = {
    nome: "Volume LXXV",
    dados: [
        {
            termo: "01. Introdução: A Teologia do Pacto Centrada em Cristo",
            definicao: "A teologia do pacto (covenant theology) é a estrutura bíblica que organiza a história da redenção em torno das alianças (pactos) de Deus com seu povo. O centro de todas as alianças é Jesus Cristo, o Mediador da nova aliança. 'Eis que dias vêm, diz o Senhor, em que farei uma nova aliança com a casa de Israel e com a casa de Judá' (Jeremias 31:31). 'Este é o meu sangue, o sangue do novo testamento, que por muitos é derramado para remissão dos pecados' (Mateus 26:28). A teologia reformada (Calvino, Cocceius, Witsius, Westminster) desenvolveu a teologia do pacto como a estrutura central da Escritura. Este volume explora as alianças de Deus: (1) Aliança da Criação (Adão). (2) Aliança da Redenção (Pai, Filho, Espírito). (3) Aliança com Noé. (4) Aliança com Abraão. (5) Aliança com Moisés. (6) Aliança com Davi. (7) Nova Aliança em Cristo. 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36).",
            referencias: "Gênesis 2:15-17; Gênesis 9:8-17; Gênesis 12:1-3; Gênesis 15:1-21; Gênesis 17:1-27; Êxodo 19-24; 2 Samuel 7:12-16; Jeremias 31:31-34; Mateus 26:28; Lucas 22:20; 1 Coríndios 11:25; Hebreus 8:6-13; Hebreus 9:15; Hebreus 12:24"
        },
        {
            termo: "02. A Aliança da Criação (Adão) - A Primeira Aliança (Gênesis 2:15-17)",
            definicao: "A aliança da criação (também chamada aliança das obras ou aliança com Adão) foi estabelecida por Deus com Adão no Jardim do Éden. Elementos da aliança: (1) Partes: Deus (Soberano) e Adão (representante da humanidade). (2) Condição: obediência perfeita (não comer da árvore do conhecimento do bem e do mal). (3) Promessa: vida eterna (representada pela árvore da vida). (4) Penalidade: morte (Gênesis 2:17: 'no dia em que dele comeres, certamente morrerás'). (5) Sinal: a árvore da vida (Gênesis 2:9; 3:22-24). Adão falhou, trazendo pecado e morte a toda a humanidade (Romanos 5:12-21). Cristo, o segundo Adão, cumpriu a aliança das obras perfeitamente (Romanos 5:19; Filipenses 2:8). A teologia reformada (Westminster, Turretin) ensina que a aliança das obras foi uma aliança de vida condicional, quebrada por Adão, mas cumprida por Cristo. 'Porque, assim como a desobediência de um só homem muitos foram feitos pecadores, assim também a obediência de um muitos serão feitos justos' (Romanos 5:19).",
            referencias: "Gênesis 2:9; Gênesis 2:15-17; Gênesis 3:1-24; Romanos 5:12-21; 1 Coríndios 15:21-22; 1 Coríndios 15:45-49; Filipenses 2:8; Hebreus 2:14-18"
        },
        {
            termo: "03. A Aliança da Redenção - O Pacto Eterno entre o Pai e o Filho",
            definicao: "A aliança da redenção (pactum salutis) é o pacto eterno entre o Pai, o Filho e o Espírito Santo antes da fundação do mundo para a salvação dos eleitos. O Pai: (1) Elegeu os eleitos (Efésios 1:3-4). (2) Enviou o Filho (João 3:16). (3) Deu os eleitos ao Filho (João 17:2,6,9,24). (4) Prometeu glória ao Filho após sua obra (Filipenses 2:9-11). O Filho: (1) Concordou em se tornar homem (Filipenses 2:5-8). (2) Cumpriu a lei (Mateus 5:17). (3) Morreu pelos pecados dos eleitos (João 10:11,15). (4) Intercede pelos eleitos (Romanos 8:34; Hebreus 7:25). O Espírito Santo: (1) Aplica a redenção aos eleitos (João 3:5-8). (2) Sela os eleitos (Efésios 1:13-14). (3) Produz o fruto do Espírito (Gálatas 5:22-23). (4) Ressuscitou Cristo (Romanos 8:11). A teologia reformada (Calvino, Owen, Westminster) afirma o pactum salutis como a base da redenção. 'Como também nos elegeu nele antes da fundação do mundo' (Efésios 1:4). 'E a vida eterna é esta: que te conheçam, a ti só, por único Deus verdadeiro, e a Jesus Cristo, a quem enviaste' (João 17:3).",
            referencias: "João 3:16; João 17:1-26; Romanos 8:28-30; Efésios 1:3-14; 2 Tessalonicenses 2:13-14; 2 Timóteo 1:9; Tito 1:2; 1 Pedro 1:2; 1 Pedro 1:18-21"
        },
        {
            termo: "04. A Aliança com Noé - A Preservação da Criação (Gênesis 9:8-17)",
            definicao: "A aliança com Noé foi estabelecida por Deus após o dilúvio. Elementos da aliança: (1) Partes: Deus e Noé (e toda a humanidade). (2) Promessa: Deus não destruirá mais a terra com dilúvio (Gênesis 9:11). (3) Sinal: o arco-íris (Gênesis 9:12-17). Esta aliança é incondicional e universal (aplica-se a toda a humanidade). Significado teológico: (1) A graça comum de Deus preserva a criação. (2) A estabilidade das estações (Gênesis 8:22). (3) A promessa de que a história continuará até a consumação. (4) A aliança com Noé aponta para a nova aliança em Cristo (a promessa de salvação). (5) O arco-íris é um símbolo da misericórdia de Deus. A teologia reformada (Calvino, Bavinck) vê na aliança com Noé a base para a missão da igreja (a história continua para que o evangelho seja pregado). 'Enquanto a terra durar, sementeira e sega, e frio e calor, e verão e inverno, e dia e noite, não cessarão' (Gênesis 8:22).",
            referencias: "Gênesis 6:18; Gênesis 8:20-22; Gênesis 9:8-17; Isaías 54:9-10; 2 Pedro 2:5; 2 Pedro 3:6-7"
        },
        {
            termo: "05. A Aliança com Abraão - A Promessa da Semente (Gênesis 12:1-3; 15:1-21; 17:1-27)",
            definicao: "A aliança com Abraão é uma aliança de graça, incondicional (baseada na promessa de Deus). Elementos: (1) Partes: Deus e Abraão (e sua descendência). (2) Promessas: (a) Terra: Canaã (Gênesis 12:7; 13:14-17). (b) Descendência: uma grande nação (Gênesis 12:2; 15:5). (c) Bênção: 'em ti serão benditas todas as famílias da terra' (Gênesis 12:3). (d) Relacionamento: 'Eu serei o seu Deus' (Gênesis 17:7-8). (3) Sinal: a circuncisão (Gênesis 17:9-14). (4) Condição: fé (Gênesis 15:6). Cumprimento em Cristo: (1) A 'semente' de Abraão é Cristo (Gálatas 3:16). (2) A bênção de Abraão vem aos gentios pela fé em Cristo (Gálatas 3:14). (3) A terra prometida aponta para a nova criação (Hebreus 11:10,16). (4) A circuncisão aponta para o batismo (Colossenses 2:11-12). A teologia reformada (Westminster, Berkhof) vê na aliança com Abraão a mesma aliança da graça que continua na nova aliança. 'Abraão creu em Deus, e isso lhe foi imputado como justiça' (Romanos 4:3).",
            referencias: "Gênesis 12:1-3; Gênesis 15:1-21; Gênesis 17:1-27; Gênesis 22:15-18; Romanos 4:1-25; Gálatas 3:6-29; Hebreus 11:8-16"
        },
        {
            termo: "06. A Aliança com Moisés (Sinai) - A Lei e o Sacrifício (Êxodo 19-24)",
            definicao: "A aliança com Moisés (aliança do Sinai) é uma aliança nacional entre Deus e Israel, com elementos condicionais. Elementos: (1) Partes: Deus e Israel. (2) Lei: os dez mandamentos e as leis cerimoniais (Êxodo 20-23). (3) Promessa: bênçãos para obediência (Deuteronômio 28:1-14). (4) Penalidade: maldições para desobediência (Deuteronômio 28:15-68). (5) Sacrifícios: para expiação temporária do pecado (Levítico 1-7). (6) Sinal: o sábado (Êxodo 31:12-17). A aliança mosaica era uma 'pedagogia para Cristo' (Gálatas 3:24), apontando para a necessidade de um Salvador. Cristo cumpriu a lei (Mateus 5:17) e foi o sacrifício definitivo (Hebreus 9:11-14; 10:1-18). A teologia reformada (Calvino, Westminster) distingue entre a lei moral (permanente), a lei cerimonial (cumprida em Cristo), e a lei civil (temporária). 'Porque o fim da lei é Cristo para justiça de todo aquele que crê' (Romanos 10:4).",
            referencias: "Êxodo 19-24; Êxodo 31:12-17; Levítico 1-7; Deuteronômio 4:1-14; Deuteronômio 28:1-68; Jeremias 31:31-34; Mateus 5:17; Romanos 3:19-20; Romanos 10:4; Gálatas 3:10-14; Gálatas 3:24-25; Hebreus 8-10"
        },
        {
            termo: "07. A Aliança com Davi - O Rei Eterno (2 Samuel 7:12-16)",
            definicao: "A aliança com Davi promete um descendente de Davi que reinaria para sempre. Elementos: (1) Partes: Deus e Davi (e sua descendência). (2) Promessa: (a) Um descendente reinará para sempre (2 Samuel 7:12-13). (b) O trono será estabelecido para sempre (2 Samuel 7:16). (c) Deus será Pai, e ele será filho (2 Samuel 7:14). (3) Sinal: o templo (1 Reis 5-8). (4) Condição: obediência dos reis (1 Reis 9:4-5), mas a aliança é incondicional (Deus a manterá mesmo com o pecado dos reis). Cumprimento em Cristo: (1) Jesus é o descendente de Davi (Mateus 1:1; Lucas 1:32-33). (2) Jesus é o Filho de Deus (Hebreus 1:5). (3) O trono de Cristo é eterno (Lucas 1:33). (4) Cristo reina à direita de Deus (Atos 2:33-35). A teologia reformada (Calvino, Bavinck) vê na aliança davídica a promessa do reinado de Cristo. 'O Senhor Deus lhe dará o trono de Davi, seu pai; e reinará para sempre na casa de Jacó, e o seu reino não terá fim' (Lucas 1:32-33).",
            referencias: "2 Samuel 7:12-16; 1 Crônicas 17:11-14; Salmo 2:7; Salmo 89:3-4; Salmo 89:35-37; Salmo 110:1; Isaías 9:6-7; Isaías 11:1-2; Jeremias 23:5-6; Lucas 1:32-33; Atos 2:30-36; Hebreus 1:5"
        },
        {
            termo: "08. A Nova Aliança - A Aliança Eterna em Cristo (Jeremias 31:31-34; Lucas 22:20)",
            definicao: "A nova aliança (nova aliança) é a aliança prometida por Jeremias e inaugurada por Cristo. 'Eis que dias vêm, diz o Senhor, em que farei uma nova aliança com a casa de Israel e com a casa de Judá' (Jeremias 31:31). 'Este é o meu sangue, o sangue do novo testamento, que por muitos é derramado para remissão dos pecados' (Mateus 26:28). Características da nova aliança: (1) Lei escrita no coração (Jeremias 31:33). (2) Relacionamento pessoal com Deus: 'Todos me conhecerão' (Jeremias 31:34). (3) Perdão completo dos pecados: 'Pois perdoarei a sua maldade, e não me lembrarei mais dos seus pecados' (Jeremias 31:34). (4) Mediador: Jesus Cristo (Hebreus 8:6; 9:15; 12:24). (5) Sacrifício: o sangue de Cristo (Hebreus 9:11-14). (6) Participantes: judeus e gentios (Efésios 2:11-22). (7) Eterna: 'aliança eterna' (Hebreus 13:20). A teologia reformada (Calvino, Westminster) vê na nova aliança a mesma aliança da graça que foi feita com Abraão, agora cumprida em Cristo. 'Porque todas quantas promessas há de Deus, são nele sim, e por ele amém, para glória de Deus por nós' (2 Coríndios 1:20).",
            referencias: "Isaías 42:6; Isaías 49:8; Isaías 54:10; Isaías 55:3; Isaías 59:21; Isaías 61:8; Jeremias 31:31-34; Jeremias 32:40; Ezequiel 34:25; Ezequiel 36:26-27; Ezequiel 37:26; Mateus 26:28; Lucas 22:20; 1 Coríndios 11:25; 2 Coríndios 3:6-18; Hebreus 8:6-13; Hebreus 9:15; Hebreus 10:16-17; Hebreus 12:24; Hebreus 13:20"
        },
        {
            termo: "09. A Unidade das Alianças - A Aliança da Graça",
            definicao: "A teologia reformada ensina que as alianças do Antigo Testamento (com Abraão, Moisés, Davi) são uma mesma aliança da graça, administrada de formas diferentes, mas com o mesmo conteúdo: salvação pela fé em Cristo. 'E as Escrituras, prevendo que Deus havia de justificar os gentios pela fé, anunciaram primeiro o evangelho a Abraão, dizendo: Todas as nações serão benditas em ti' (Gálatas 3:8). A aliança da graça é: (1) Uma: uma só aliança da graça, desde Abraão até Cristo. (2) Progressiva: revelada em etapas (Adão, Noé, Abraão, Moisés, Davi, Cristo). (3) Incondicional: baseada na promessa de Deus, não nas obras do homem. (4) Centrada em Cristo: Cristo é o mediador da aliança. (5) Selada por sinais: circuncisão (AT) e batismo (NT). A teologia reformada (Westminster, Berkhof) rejeita o dispensacionalismo (que vê as alianças como planos de salvação diferentes). 'Há um só corpo e um só Espírito... um só Senhor, uma só fé, um só batismo' (Efésios 4:4-5).",
            referencias: "Gênesis 3:15; Gênesis 12:3; Gênesis 15:1-6; Gênesis 17:7; Romanos 4:11-12; Gálatas 3:6-9; Gálatas 3:14; Gálatas 3:16-18; Efésios 2:12-13; Hebreus 11:39-40"
        },
        {
            termo: "10. Os Sinais e Selos da Aliança - Circuncisão e Batismo",
            definicao: "Os sinais da aliança são a circuncisão (AT) e o batismo (NT). Circuncisão: (1) Sinal da aliança com Abraão (Gênesis 17:9-14). (2) Simbolizava a purificação do coração (Deuteronômio 10:16; 30:6). (3) Era aplicada a crianças (Gênesis 17:12). Batismo: (1) Sinal da nova aliança (Mateus 28:19). (2) Simboliza a morte e ressurreição com Cristo (Romanos 6:3-4). (3) Aplica-se a crentes e a seus filhos (Atos 2:38-39). A teologia reformada (Calvino, Westminster) ensina o pedobatismo (batismo de crianças) como continuidade da aliança (a circuncisão foi substituída pelo batismo). Os credobatistas (batistas) ensinam o batismo apenas de crentes. A teologia reformada (presbiteriana, congregacional) afirma o batismo de crianças como sinal da aliança da graça. 'Porque a promessa vos diz respeito a vós, a vossos filhos, e a todos os que estão longe' (Atos 2:39).",
            referencias: "Gênesis 17:9-14; Êxodo 12:48; Deuteronômio 10:16; Deuteronômio 30:6; Jeremias 4:4; Jeremias 9:25-26; Romanos 2:28-29; Romanos 4:11; Colossenses 2:11-12"
        },
        {
            termo: "11. A Ceia do Senhor - O Sacramento da Nova Aliança",
            definicao: "A Ceia do Senhor é o sacramento da nova aliança, instituído por Cristo na última ceia. 'E, tomando o pão, tendo dado graças, o partiu e deu-lhes, dizendo: Isto é o meu corpo, que por vós é dado; fazei isto em memória de mim. Semelhantemente também, depois de cear, tomou o cálice, dizendo: Este cálice é o novo testamento no meu sangue, que por vós é derramado' (Lucas 22:19-20). Significados: (1) Memorial da morte de Cristo (1 Coríndios 11:24-25). (2) Comunhão com Cristo (1 Coríndios 10:16). (3) Comunhão dos crentes (1 Coríndios 10:17). (4) Antecipação da volta de Cristo (1 Coríndios 11:26). A teologia reformada (Calvino) ensina a presença espiritual de Cristo na Ceia (não transubstanciação católica, nem consubstanciação luterana, nem mero memorial zwingliano). 'O cálice de bênção que abençoamos, não é a comunhão do sangue de Cristo? O pão que partimos, não é a comunhão do corpo de Cristo?' (1 Coríndios 10:16).",
            referencias: "Mateus 26:26-29; Marcos 14:22-25; Lucas 22:19-20; João 6:51-58; 1 Coríndios 10:16-22; 1 Coríndios 11:23-34; Hebreus 9:15-22"
        },
        {
            termo: "12. A Nova Aliança e a Lei - A Lei Escrita no Coração",
            definicao: "A nova aliança traz a promessa da lei escrita no coração. 'Porei a minha lei no seu interior, e a escreverei no seu coração' (Jeremias 31:33). 'E vos darei um coração novo, e porei dentro de vós um espírito novo... e porei o meu Espírito dentro de vós, e farei que andeis nos meus estatutos' (Ezequiel 36:26-27). A lei moral (os dez mandamentos) não é abolida, mas escrita no coração do crente pelo Espírito Santo. 'Não estamos debaixo da lei, mas debaixo da graça' (Romanos 6:14) significa que a lei não nos condena (justificação), mas ainda nos guia (santificação). A teologia reformada (Calvino, Westminster) afirma o terceiro uso da lei (normativo) para o crente. 'Tendo, pois, ó amados, tais promessas, purifiquemo-nos de toda imundícia da carne e do espírito, aperfeiçoando a santificação no temor de Deus' (2 Coríndios 7:1).",
            referencias: "Jeremias 31:31-34; Ezequiel 11:19-20; Ezequiel 36:26-27; Romanos 3:31; Romanos 6:14; Romanos 7:12; Romanos 8:1-4; 1 Coríndios 9:21; Gálatas 5:18; Hebreus 8:10; Hebreus 10:16"
        },
        {
            termo: "13. Síntese: Cristo, o Mediador da Nova Aliança",
            definicao: "Cristo é o mediador da nova aliança (Hebreus 8:6; 9:15; 12:24). 'E, por isso, é Mediador de um novo testamento, para que, intervindo a morte para remissão das transgressões que havia debaixo do primeiro testamento, os chamados recebam a promessa da herança eterna' (Hebreus 9:15). Resumo da teologia do pacto: (1) Aliança da Criação (Adão): condicional, quebrada por Adão, cumprida por Cristo. (2) Aliança da Redenção (Pactum Salutis): pacto eterno entre Pai, Filho e Espírito. (3) Aliança com Noé: incondicional, preservação da criação. (4) Aliança com Abraão: incondicional, promessa da semente (Cristo). (5) Aliança com Moisés: condicional, pedagogia para Cristo. (6) Aliança com Davi: incondicional, promessa do Rei eterno (Cristo). (7) Nova Aliança: inaugurada por Cristo, lei escrita no coração, perdão dos pecados, vida eterna. A teologia reformada celebra a unidade das alianças em Cristo. 'Porque todas quantas promessas há de Deus, são nele sim, e por ele amém, para glória de Deus por nós' (2 Coríndios 1:20). 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36). Soli Deo Gloria!",
            referencias: "Romanos 11:36; 2 Coríndios 1:20; Gálatas 3:16-17; Efésios 2:12-13; Colossenses 2:11-12; Hebreus 8:6-13; Hebreus 9:15; Hebreus 12:24; 1 Pedro 1:10-12"
        }
    ]
};