// volume/volume-72.js
window.LIVRO_DATA = {
    nome: "Volume LXXII",
    dados: [
        {
            termo: "01. Introdução: A Cristologia da Igreja Apostólica",
            definicao: "A igreja primitiva (séculos I-III) herdou dos apóstolos a fé em Jesus Cristo como o Senhor, o Filho de Deus, o Salvador crucificado e ressurreto. Os Atos dos Apóstolos registram a pregação cristológica da igreja primitiva: 'E em nenhum outro há salvação, porque também debaixo do céu nenhum outro nome há, dado entre os homens, pelo qual devamos ser salvos' (Atos 4:12). 'Porque para mim o viver é Cristo, e o morrer é ganho' (Filipenses 1:21). A cristologia da igreja primitiva era: (1) Centrada na ressurreição: 'Deus o ressuscitou' (Atos 2:24). (2) Centrada na cruz: 'Cristo morreu pelos nossos pecados' (1 Coríndios 15:3). (3) Centrada na divindade de Cristo: 'Senhor meu, e Deus meu!' (João 20:28). (4) Centrada na humanidade de Cristo: 'O Verbo se fez carne' (João 1:14). Este volume explora a cristologia na igreja primitiva: a pregação dos apóstolos em Atos, as epístolas do Novo Testamento, a fé dos primeiros cristãos, a adoração a Cristo, o martírio dos primeiros santos, e a formação do cânon. 'E perseveravam na doutrina dos apóstolos, e na comunhão, e no partir do pão, e nas orações' (Atos 2:42).",
            referencias: "Atos 2:22-36; Atos 4:8-12; Atos 10:34-43; Atos 13:16-41; Romanos 1:1-4; 1 Coríndios 15:1-8; Filipenses 2:5-11; 1 Timóteo 3:16; 1 Pedro 3:18-22; 1 João 1:1-4; Apocalipse 1:5-8"
        },
        {
            termo: "02. A Pregação de Pedro no Pentecostes (Atos 2:14-41)",
            definicao: "O primeiro sermão da igreja primitiva foi pregado por Pedro no dia de Pentecostes (Atos 2). A cristologia deste sermão: (1) Jesus é o Messias prometido: 'A este Jesus, Deus o ressuscitou, do que todos nós somos testemunhas. Exaltado, pois, à destra de Deus... a Cristo, o Senhor o fez Senhor e Cristo' (Atos 2:32-36). (2) A crucificação foi pelo 'determinado conselho e presciência de Deus' (v.23) - soberania divina e responsabilidade humana. (3) A ressurreição é atestada por testemunhas oculares (v.32). (4) A exaltação de Cristo à direita de Deus (v.33-35). (5) O chamado ao arrependimento: 'Arrependei-vos, e cada um de vós seja batizado em nome de Jesus Cristo, para perdão dos pecados' (v.38). (6) A promessa do Espírito Santo (v.38-39). O resultado: cerca de 3.000 almas foram salvas (v.41). A teologia reformada vê neste sermão o modelo da pregação cristocêntrica. 'E com muitas outras palavras isto testificava, e os exortava, dizendo: Salvai-vos desta geração perversa' (Atos 2:40).",
            referencias: "Salmo 16:8-11; Salmo 110:1; Joel 2:28-32; Atos 2:14-41; Romanos 10:9-13"
        },
        {
            termo: "03. A Pregação de Pedro no Pórtico de Salomão (Atos 3:12-26)",
            definicao: "Após a cura do coxo de nascença, Pedro pregou no pórtico de Salomão. A cristologia deste sermão: (1) Jesus é o 'Santo e Justo' (Atos 3:14). (2) O 'Autor da vida' foi morto, mas Deus o ressuscitou (v.15). (3) A cura do coxo foi em nome de Jesus (v.16). (4) O cumprimento das profecias: 'Deus cumpriu assim o que antes anunciara pela boca de todos os seus profetas: que o Cristo havia de padecer' (v.18). (5) O chamado ao arrependimento: 'Arrependei-vos, pois, e convertei-vos, para que sejam apagados os vossos pecados' (v.19). (6) A promessa da segunda vinda: 'Para que venham os tempos do refrigério pela presença do Senhor, e envie ele a Jesus Cristo, que já dantes vos foi pregado' (v.20). (7) Jesus é o profeta como Moisés (v.22-23; Deuteronômio 18:15-19). (8) Jesus é a 'semente' de Abraão (v.25; Gênesis 12:3; 22:18). A teologia reformada vê neste sermão a pregação do arrependimento e da restauração em Cristo. 'E Deus suscitou a seu Filho Jesus, que a vós primeiramente vos enviou, para vos abençoar, na conversão de cada um dos vossos pecados' (Atos 3:26).",
            referencias: "Deuteronômio 18:15-19; Gênesis 12:3; Gênesis 22:18; Atos 3:12-26; 1 Pedro 2:21-25"
        },
        {
            termo: "04. A Pregação de Pedro perante o Sinédrio (Atos 4:8-12)",
            definicao: "Pedro e João foram presos e levados perante o Sinédrio. A cristologia de Pedro neste interrogatório: (1) A cura foi realizada 'em nome de Jesus Cristo, o Nazareno' (Atos 4:10). (2) 'A pedra que foi desprezada por vós, os edificadores, foi posta como cabeça da esquina' (v.11) - citação do Salmo 118:22, aplicada a Cristo. (3) 'E em nenhum outro há salvação, porque também debaixo do céu nenhum outro nome há, dado entre os homens, pelo qual devamos ser salvos' (v.12) - a exclusividade de Cristo. A teologia reformada vê neste texto a afirmação do Solus Christus (somente Cristo). 'Não podemos deixar de falar do que temos visto e ouvido' (Atos 4:20). A coragem dos apóstolos diante do Sinédrio é um testemunho da ressurreição. 'E conhecendo que eram homens iletrados e indoutos, maravilharam-se; e tinham conhecimento de que eles haviam estado com Jesus' (Atos 4:13).",
            referencias: "Salmo 118:22-23; Isaías 28:16; Mateus 21:42; Atos 4:8-12; 1 Pedro 2:6-8"
        },
        {
            termo: "05. A Pregação de Estêvão (Atos 7:1-60)",
            definicao: "Estêvão, o primeiro mártir cristão, pregou um longo sermão diante do Sinédrio antes de ser apedrejado. A cristologia de Estêvão: (1) Uma visão de Cristo glorificado: 'Vejo os céus abertos, e o Filho do Homem em pé à direita de Deus' (Atos 7:55-56). (2) Jesus é o 'Justo' (v.52). (3) Os profetas anunciaram a vinda do Justo (v.52). (4) A acusação contra os líderes judeus: 'Vós sois os que resistis ao Espírito Santo' (v.51). A visão de Estêvão é significativa: Jesus está 'em pé' (não assentado) - talvez para receber seu mártir. O martírio de Estêvão (Atos 7:57-60): (1) Apedrejado (v.58-59). (2) Suas últimas palavras: 'Senhor Jesus, recebe o meu espírito' (v.59) - ecoando Lucas 23:46. (3) 'Senhor, não lhes imputes este pecado' (v.60) - ecoando Lucas 23:34. A teologia reformada vê em Estêvão o exemplo do mártir cristão que segue os passos de Cristo. 'E Saulo consentiu na sua morte' (Atos 8:1) - a conversão de Paulo começou com o martírio de Estêvão.",
            referencias: "Atos 6:8-15; Atos 7:1-60; Lucas 23:34; Lucas 23:46; Apocalipse 1:13-18"
        },
        {
            termo: "06. A Pregação de Filipe ao Eunuco (Atos 8:26-40)",
            definicao: "Filipe, o evangelista, pregou ao eunuco etíope no caminho de Jerusalém a Gaza. A cristologia de Filipe: (1) Filipe começou com Isaías 53:7-8, que descreve o Servo Sofredor (Atos 8:32-33). (2) 'E, começando por esta Escritura, lhe anunciou a Jesus' (Atos 8:35). (3) O eunuco creu e foi batizado (v.36-38). (4) Filipe foi arrebatado pelo Espírito (v.39). Este episódio é um exemplo de evangelismo pessoal baseado na Escritura. A teologia reformada vê na pregação de Filipe o modelo de pregação cristocêntrica a partir do Antigo Testamento. 'Que impede que seja batizado?' (Atos 8:36). 'E disse: Creio que Jesus Cristo é o Filho de Deus' (Atos 8:37 - Textus Receptus).",
            referencias: "Isaías 53:7-8; Isaías 56:3-5; Atos 8:26-40; Romanos 10:13-15"
        },
        {
            termo: "07. A Pregação de Paulo em Antioquia da Pisídia (Atos 13:16-41)",
            definicao: "Paulo pregou na sinagoga de Antioquia da Pisídia. A cristologia deste sermão: (1) Deus levantou a Davi como rei (v.22). (2) Da descendência de Davi, Deus levantou Jesus, o Salvador (v.23). (3) João Batista preparou o caminho (v.24-25). (4) Os líderes judeus não reconheceram Jesus e o condenaram (v.27-28). (5) Deus o ressuscitou dos mortos (v.30). (6) Testemunhas da ressurreição: 'ele foi visto por muitos' (v.31). (7) O cumprimento das profecias: Salmo 2:7 ('Tu és meu Filho'), Isaías 55:3 ('as santas e fiéis bênçãos de Davi'), Salmo 16:10 ('não permitirás que o teu Santo veja corrupção') (v.33-37). (8) A justificação pela fé em Cristo: 'Por meio deste se vos anuncia a remissão dos pecados... justificado todo aquele que crê' (v.38-39). A teologia reformada vê neste sermão o resumo do evangelho de Paulo. 'Vede, pois, que não venha sobre vós o que está dito nos profetas' (Atos 13:40).",
            referencias: "Salmo 2:7; Salmo 16:10; Isaías 55:3; Atos 13:16-41; Romanos 1:1-4; Romanos 3:21-26"
        },
        {
            termo: "08. A Pregação de Paulo em Atenas (Atos 17:22-31)",
            definicao: "Paulo pregou no Areópago de Atenas, em diálogo com a filosofia grega. A cristologia deste sermão: (1) Deus é o Criador do céu e da terra (v.24). (2) Deus não habita em templos feitos por mãos (v.24). (3) Deus não precisa de nada dos homens (v.25). (4) Deus fez de um só sangue toda a humanidade (v.26). (5) 'Nele vivemos, e nos movemos, e existimos' (v.28) - citação de poetas gregos (Epimênides, Arato, Cleantes). (6) 'Somos também sua geração' (v.29). (7) Deus ordena o arrependimento (v.30). (8) Deus estabeleceu um dia para julgar o mundo com justiça, por meio de Jesus Cristo (v.31). (9) A ressurreição de Cristo é a garantia do juízo (v.31). A reação: alguns zombaram, outros creram (Dionísio, Damaris) (v.32-34). A teologia reformada vê neste sermão o modelo de contextualização (inculturação) do evangelho. 'Eu não sabia que era o Areópago' (Atos 17:19).",
            referencias: "Atos 17:16-34; 1 Coríndios 9:19-23; Colossenses 1:16-17; Tito 1:12"
        },
        {
            termo: "09. A Fé dos Primeiros Cristãos - O Credo dos Apóstolos",
            definicao: "O Credo dos Apóstolos (Symbolum Apostolorum) é a mais antiga confissão de fé da igreja primitiva, resumindo a fé em Cristo. Texto cristológico: 'Creio... em Jesus Cristo, seu único Filho, nosso Senhor; o qual foi concebido pelo Espírito Santo; nasceu da virgem Maria; padeceu sob o poder de Pôncio Pilatos; foi crucificado, morto e sepultado; desceu ao inferno; ao terceiro dia ressurgiu dos mortos; subiu ao céu; está assentado à direita de Deus Pai Todo-poderoso; donde há de vir a julgar os vivos e os mortos.' O Credo dos Apóstolos resume os eventos principais da vida de Cristo: (1) Encarnação (concebido pelo Espírito, nascido da virgem). (2) Paixão (padeceu sob Pilatos, crucificado, morto, sepultado). (3) Descida ao inferno (descensus ad inferos). (4) Ressurreição (ao terceiro dia). (5) Ascensão (subiu ao céu). (6) Exaltação (assentado à direita de Deus). (7) Segunda vinda (vir a julgar). A teologia reformada (Calvino, Westminster) aceita o Credo dos Apóstolos como exposição fiel da doutrina bíblica. 'Se com a tua boca confessares ao Senhor Jesus, e em teu coração creres que Deus o ressuscitou dentre os mortos, serás salvo' (Romanos 10:9).",
            referencias: "Mateus 1:18-25; Mateus 27:11-26; Mateus 28:1-10; Lucas 1:26-38; Lucas 24:50-53; Atos 1:9-11; Romanos 10:9-10; 1 Coríndios 15:3-4; Filipenses 2:9-11"
        },
        {
            termo: "10. A Adoração a Cristo na Igreja Primitiva",
            definicao: "A igreja primitiva adorava a Cristo como Deus. Evidências: (1) Oração a Cristo: 'Senhor Jesus, recebe o meu espírito' (Atos 7:59). 'Maranata' (1 Coríndios 16:22) - 'Nosso Senhor, vem!' (2) Invocação do nome de Cristo: 'Todos os que em toda parte invocam o nome de nosso Senhor Jesus Cristo' (1 Coríndios 1:2). (3) Louvor a Cristo: hinos cristológicos (Filipenses 2:5-11; Colossenses 1:15-20; 1 Timóteo 3:16). (4) Batismo em nome de Cristo: 'batizando-as em nome do Pai, e do Filho, e do Espírito Santo' (Mateus 28:19). (5) Ceia do Senhor: 'em memória de mim' (Lucas 22:19). (6) A fé em Cristo como Deus: Tomé confessou: 'Senhor meu, e Deus meu!' (João 20:28). (7) O testemunho de Plínio, o Jovem (c. 112 d.C.): os cristãos cantavam um hino a Cristo 'como a um deus'. A teologia reformada (Calvino) vê na adoração primitiva a Cristo a evidência da divindade de Cristo. 'Porque todos quantos foram batizados em Jesus Cristo já vos revestistes de Cristo' (Gálatas 3:27).",
            referencias: "Mateus 28:19; João 20:28; Atos 7:59; 1 Coríndios 1:2; 1 Coríndios 16:22; Filipenses 2:9-11; Colossenses 3:16; 1 Pedro 3:15"
        },
        {
            termo: "11. O Martírio dos Primeiros Cristãos - Testemunhas de Cristo",
            definicao: "Os primeiros cristãos enfrentaram perseguição e martírio por sua fé em Cristo. Exemplos: (1) Estêvão (Atos 7:54-60). (2) Tiago, filho de Zebedeu (Atos 12:2). (3) Pedro e Paulo (tradição, c. 64-68 d.C.). (4) Inácio de Antioquia (c. 108 d.C.). (5) Policarpo de Esmirna (c. 155 d.C.). (6) Justino Mártir (c. 165 d.C.). (7) Perpétua e Felicidade (c. 203 d.C.). (8) Cipriano de Cartago (c. 258 d.C.). Os mártires testemunharam: (1) A ressurreição de Cristo. (2) A divindade de Cristo. (3) A esperança da vida eterna. (4) O perdão dos inimigos. O testemunho dos mártires é uma evidência da veracidade da fé cristã (ninguém morreria por uma mentira). A teologia reformada (Calvino) vê no martírio dos santos a glória de Deus e o poder do Espírito Santo. 'Bem-aventurados os que são perseguidos por causa da justiça, porque deles é o reino dos céus' (Mateus 5:10). 'Eles o venceram pelo sangue do Cordeiro e pela palavra do seu testemunho' (Apocalipse 12:11).",
            referencias: "Mateus 5:10-12; Atos 7:54-60; Atos 12:2; 2 Coríndios 11:23-28; Filipenses 1:29; 1 Pedro 4:12-16; Apocalipse 2:10; Apocalipse 12:11"
        },
        {
            termo: "12. O Cânon do Novo Testamento - A Herança Apostólica",
            definicao: "A igreja primitiva reconheceu o cânon do Novo Testamento (27 livros) como Palavra de Deus inspirada. Critérios de canonicidade: (1) Apostolicidade: escrito por um apóstolo ou associado próximo (Marcos com Pedro, Lucas com Paulo). (2) Ortodoxia: conformidade com a regra da fé (a doutrina apostólica). (3) Antiguidade: datação precoce (século I). (4) Uso generalizado: aceito pela maioria das igrejas. Os principais testemunhos do cânon: (1) Cânon de Muratori (c. 170 d.C.). (2) Irineu de Lyon (c. 180 d.C.). (3) Clemente de Alexandria (c. 200 d.C.). (4) Tertuliano (c. 200 d.C.). (5) Orígenes (c. 250 d.C.). (6) Eusébio de Cesareia (c. 325 d.C.). (7) Atanásio de Alexandria (367 d.C.) - lista os 27 livros do NT. O cânon foi reconhecido, não criado, pela igreja. A teologia reformada (Calvino, Westminster) afirma que o cânon do NT é a Palavra de Deus inspirada. 'Toda a Escritura é inspirada por Deus e útil para o ensino, para a repreensão, para a correção, para a instrução na justiça' (2 Timóteo 3:16).",
            referencias: "Lucas 1:1-4; João 20:30-31; Atos 1:1-3; 1 Coríndios 14:37; Gálatas 1:11-12; 1 Tessalonicenses 2:13; 2 Pedro 1:16-21; 2 Pedro 3:15-16; 1 João 1:1-4"
        },
        {
            termo: "13. Síntese: A Cristologia dos Primeiros Cristãos",
            definicao: "A igreja primitiva herdou dos apóstolos uma cristologia rica e profunda. Resumo da cristologia na igreja primitiva: (1) Jesus é o Senhor (Kyrios), equivalente a YHWH (Atos 2:36; Romanos 10:9; Filipenses 2:11). (2) Jesus é o Cristo (Messias), o Ungido de Deus (Atos 2:36; 3:20; 10:38). (3) Jesus é o Filho de Deus (Atos 8:37; Romanos 1:4; 1 João 4:15). (4) Jesus é o Salvador (Atos 4:12; 5:31; 13:23). (5) Jesus é o Cordeiro de Deus (João 1:29; 1 Pedro 1:19; Apocalipse 5:6). (6) Jesus é o Sumo Sacerdote (Hebreus 4:14; 7:26-28). (7) Jesus é o Juiz (Atos 10:42; 17:31; 2 Timóteo 4:1). (8) Jesus é o Rei (Apocalipse 1:5; 17:14; 19:16). (9) Jesus é o Verbo (Logos) (João 1:1-14). (10) Jesus é verdadeiramente Deus e verdadeiramente homem (João 1:14; 20:28; Romanos 1:3-4; 1 Timóteo 3:16). A teologia reformada celebra a fé dos primeiros cristãos e sua herança apostólica. 'E perseveravam na doutrina dos apóstolos, e na comunhão, e no partir do pão, e nas orações' (Atos 2:42). 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36). Soli Deo Gloria!",
            referencias: "Atos 2:42; Romanos 11:36; Filipenses 2:5-11; 1 Timóteo 3:16; Tito 2:13; 1 Pedro 1:18-21; 1 João 4:2-3; Apocalipse 1:5-8"
        }
    ]
};