// volume/volume-46.js
window.LIVRO_DATA = {
    nome: "Volume XLVI",
    dados: [
        {
            termo: "Atos 1:9-11 - A Ascensão de Cristo",
            definicao: "Texto: 'E, quando dizia isto, vendo-o eles, foi elevado às alturas, e uma nuvem o recebeu, ocultando-o aos seus olhos. E, estando com os olhos fitos no céu, enquanto ele subia, eis que dois varões vestidos de branco se puseram junto deles, e disseram: Varões galileus, por que estais olhando para o céu? Esse Jesus, que dentre vós foi recebido em cima no céu, há de vir assim como para o céu o vistes ir.' Significados teológicos: (1) A ascensão marca o fim do ministério terreno de Cristo e o início de seu ministério celestial (Hebreus 4:14-16; 7:25). (2) Cristo está assentado à direita de Deus (Marcos 16:19; Efésios 1:20; Colossenses 3:1; Hebreus 1:3). (3) A ascensão é a garantia da segunda vinda (parusia): 'há de vir assim como para o céu o vistes ir'. (4) A ascensão abriu caminho para o envio do Espírito Santo (João 16:7). A teologia reformada afirma a ascensão corporal de Cristo e sua sessão à direita de Deus.",
            referencias: "Marcos 16:19; Lucas 24:50-53; João 14:2-3; João 16:7; Atos 1:9-11; Efésios 1:20-23; Colossenses 3:1; Hebreus 1:3; Hebreus 4:14-16; Hebreus 7:25"
        },
        {
            termo: "Atos 2:22-36 - Pedro e a Ressurreição",
            definicao: "Texto: 'Varões israelitas, ouvi estas palavras: A Jesus Nazareno, varão aprovado por Deus entre vós... a este, entregue pelo determinado conselho e presciência de Deus, tomando-o vós, o crucificastes e matastes... ao qual Deus ressuscitou, soltas as dores da morte... este Jesus, Deus o ressuscitou, do que todos nós somos testemunhas. Exaltado, pois, à destra de Deus... a Cristo, o Senhor o fez Senhor e Cristo.' Significados teológicos: (1) A crucificação foi pelo 'determinado conselho e presciência de Deus' (soberania divina) e pela ação dos homens (responsabilidade humana). (2) A ressurreição é atestada por testemunhas oculares ('do que todos nós somos testemunhas'). (3) Cristo é exaltado à direita de Deus. (4) 'Senhor e Cristo' - títulos messiânicos e divinos. (5) Citação do Salmo 16:10 (ressurreição) e Salmo 110:1 (sessão à direita). A teologia reformada vê neste texto a pregação apostólica central: Jesus crucificado, ressurreto e exaltado.",
            referencias: "Salmo 16:8-11; Salmo 110:1; Atos 2:22-36; Romanos 1:4; 1 Coríntios 15:3-8; Filipenses 2:9-11"
        },
        {
            termo: "Atos 4:11-12 - A Pedra Angular e a Exclusividade de Cristo",
            definicao: "Texto: 'Esta pedra, que foi desprezada por vós, os edificadores, foi posta como cabeça da esquina. E em nenhum outro há salvação, porque também debaixo do céu nenhum outro nome há, dado entre os homens, pelo qual devamos ser salvos.' Significados teológicos: (1) A 'pedra que foi desprezada' (Salmo 118:22) é Cristo, rejeitado pelos líderes judeus, mas exaltado por Deus. (2) 'Cabeça da esquina' (pedra angular) - Cristo é o fundamento e a pedra de esquina da igreja (Efésios 2:20; 1 Pedro 2:6-8). (3) 'Em nenhum outro há salvação' - a unicidade e exclusividade de Cristo como Salvador. (4) 'Nenhum outro nome... pelo qual devamos ser salvos' - rejeição do pluralismo religioso. A teologia reformada vê neste texto a afirmação do Solus Christus (somente Cristo) e da unicidade da salvação.",
            referencias: "Salmo 118:22-23; Isaías 28:16; Mateus 21:42; Marcos 12:10-11; Lucas 20:17; Atos 4:11-12; Efésios 2:20; 1 Pedro 2:6-8"
        },
        {
            termo: "Colossenses 1:15-20 - O Hino da Supremacia de Cristo",
            definicao: "Texto: 'Ele é a imagem do Deus invisível, o primogênito de toda a criação; porque nele foram criadas todas as coisas que há nos céus e na terra, visíveis e invisíveis, sejam tronos, sejam dominações, sejam principados, sejam potestades; tudo foi criado por ele e para ele. E ele é antes de todas as coisas, e todas as coisas subsistem por ele. E ele é a cabeça do corpo, da igreja; é o princípio e o primogênito dos mortos, para que em todas as coisas tenha a preeminência. Porque foi do agrado do Pai que toda a plenitude nele habitasse, e que, havendo por ele feito a paz pelo sangue da sua cruz, por meio dele reconciliasse consigo mesmo todas as coisas, tanto as que estão na terra como as que estão nos céus.' Significados teológicos: (1) 'Imagem do Deus invisível' (eikōn) - Cristo é a representação exata de Deus (João 1:18; 14:9; Hebreus 1:3). (2) 'Primogênito de toda a criação' - primazia, não primeiro criado (contra o arianismo). (3) 'Nele foram criadas todas as coisas' - Cristo é o Criador (João 1:3). (4) 'Todas as coisas subsistem por ele' - Cristo é o Sustentador (Hebreus 1:3). (5) 'Cabeça do corpo, da igreja' - Cristo é a cabeça da igreja (Efésios 1:22-23). (6) 'Primogênito dos mortos' - a ressurreição de Cristo é a primícia (1 Coríntios 15:20). (7) 'Toda a plenitude nele habitasse' - a plenitude da divindade em Cristo (Colossenses 2:9). (8) 'Paz pelo sangue da sua cruz' - a expiação vicária. A teologia reformada vê neste texto a cristologia cósmica mais elevada do Novo Testamento.",
            referencias: "João 1:1-3; João 1:18; João 14:9; Romanos 11:36; 1 Coríntios 8:6; 1 Coríndios 15:20; Efésios 1:22-23; Filipenses 2:6-11; Colossenses 2:9; Hebreus 1:1-3; Hebreus 1:8"
        },
        {
            termo: "Colossenses 2:9-15 - A Plenitude da Divindade em Cristo",
            definicao: "Texto: 'Porque nele habita corporalmente toda a plenitude da divindade. E estais perfeitos nele... no qual também estais circuncidados... sepultados com ele no batismo... vivificados juntamente com ele... e, tendo despojado os principados e as potestades, os exibiu publicamente, triunfando deles na cruz.' Significados teológicos: (1) 'Nele habita corporalmente toda a plenitude da divindade' - a humanidade de Cristo é o templo da divindade (João 1:14; Colossenses 1:19). (2) 'Estais perfeitos nele' - os crentes são completos em Cristo. (3) A circuncisão espiritual (Colossenses 2:11) - o batismo como sepultamento com Cristo (Romanos 6:4). (4) 'Vivificados juntamente com ele' - a ressurreição espiritual (Efésios 2:1-10). (5) 'Despojado os principados e as potestades' - a vitória sobre os poderes do mal na cruz (Efésios 1:20-23). (6) 'Triunfando deles na cruz' - a cruz é a vitória de Cristo. A teologia reformada vê neste texto a plenitude da divindade de Cristo e a vitória da cruz.",
            referencias: "Romanos 6:3-4; Efésios 1:20-23; Efésios 2:1-10; Colossenses 1:19; Colossenses 2:9-15; 1 Pedro 3:22"
        },
        {
            termo: "1 Coríntios 1:22-24 - Cristo, Poder e Sabedoria de Deus",
            definicao: "Texto: 'Porque os judeus pedem sinal, e os gregos buscam sabedoria; mas nós pregamos a Cristo crucificado, que é escândalo para os judeus e loucura para os gregos. Mas para os que são chamados, tanto judeus como gregos, lhes pregamos a Cristo, poder de Deus e sabedoria de Deus.' Significados teológicos: (1) 'Cristo crucificado' - o centro da pregação de Paulo (1 Coríntios 2:2). (2) 'Escândalo para os judeus' - a cruz era ofensiva para os judeus que esperavam um Messias político. (3) 'Loucur para os gregos' - a ideia de um Deus crucificado era irracional para a filosofia grega. (4) 'Cristo, poder de Deus' - a cruz é o poder de Deus para salvação (Romanos 1:16). (5) 'Sabedoria de Deus' - a cruz é a sabedoria suprema de Deus (1 Coríntios 1:25). (6) 'Para os que são chamados' - a eficácia da pregação para os eleitos. A teologia reformada vê neste texto a centralidade da cruz e a eleição divina.",
            referencias: "Isaías 29:14; Romanos 1:16; 1 Coríntios 1:18-25; 1 Coríndios 1:30; Gálatas 3:1; Gálatas 6:14"
        },
        {
            termo: "1 Coríntios 5:7 - Cristo, Nossa Páscoa",
            definicao: "Texto: 'Alimpai-vos, pois, do fermento velho, para que sejais uma nova massa, assim como estais sem fermento. Porque Cristo, nossa Páscoa, foi sacrificado por nós.' Significados teológicos: (1) 'Cristo, nossa Páscoa' - Jesus é o cumprimento do cordeiro pascal (Êxodo 12). (2) 'Foi sacrificado por nós' - a morte vicária de Cristo (Isaías 53:5-6; 1 Pedro 2:24). (3) 'Alimpai-vos do fermento velho' - a purificação do pecado (santificação). (4) 'Nova massa' - a nova vida em Cristo (2 Coríntios 5:17). (5) 'Pães asmos' - sinceridade e verdade (Êxodo 12:15-20). (6) 'Assim como estais sem fermento' - a posição do crente em Cristo (justificado). A teologia reformada vê neste texto a identificação de Cristo com o cordeiro pascal e o chamado à santidade.",
            referencias: "Êxodo 12:1-28; Isaías 53:5-6; 2 Coríntios 5:17; 1 Pedro 1:18-19; 1 Pedro 2:24"
        },
        {
            termo: "1 Coríntios 8:6 - Um só Senhor, Jesus Cristo",
            definicao: "Texto: 'Todavia para nós há um só Deus, o Pai, de quem é tudo e para quem nós vivemos; e um só Senhor, Jesus Cristo, pelo qual são todas as coisas, e nós por ele.' Significados teológicos: (1) 'Um só Deus, o Pai' - monoteísmo bíblico (Deuteronômio 6:4). (2) 'Um só Senhor, Jesus Cristo' - Jesus é Senhor (Kyrios), título equivalente a YHWH (Filipenses 2:9-11). (3) 'Pelo qual são todas as coisas' - Cristo é o Criador (João 1:3; Colossenses 1:16). (4) 'Nós por ele' - Cristo é o mediador da salvação (1 Timóteo 2:5). (5) A fórmula 'um só Deus' e 'um só Senhor' ecoa o Shema (Deuteronômio 6:4), incluindo Cristo na identidade divina. A teologia reformada vê neste texto a afirmação da divindade de Cristo e sua distinção do Pai.",
            referencias: "Deuteronômio 6:4; Salmo 110:1; João 1:3; Romanos 11:36; 1 Coríntios 8:6; Colossenses 1:16; 1 Timóteo 2:5"
        },
        {
            termo: "1 Coríntios 11:23-26 - A Ceia do Senhor",
            definicao: "Texto: 'Porque eu recebi do Senhor o que também vos ensinei: que o Senhor Jesus, na noite em que foi traído, tomou pão; e, tendo dado graças, o partiu e disse: Tomai, comei; isto é o meu corpo, que é partido por vós; fazei isto em memória de mim. Semelhantemente também, depois de cear, tomou o cálice, dizendo: Este cálice é o novo testamento no meu sangue; fazei isto, todas as vezes que beberdes, em memória de mim. Porque todas as vezes que comerdes este pão e beberdes este cálice anunciais a morte do Senhor, até que venha.' Significados teológicos: (1) A instituição da Ceia do Senhor (Eucaristia). (2) 'Isto é o meu corpo' - a presença de Cristo na Ceia (debate: transubstanciação católica, consubstanciação luterana, presença espiritual calvinista, memorialismo zwingliano). (3) 'O novo testamento no meu sangue' - a nova aliança inaugurada por Cristo (Jeremias 31:31-34; Hebreus 8:6-13). (4) 'Fazei isto em memória de mim' - a Ceia como memorial. (5) 'Anunciais a morte do Senhor, até que venha' - a Ceia aponta para a primeira vinda (cruz) e para a segunda vinda (parusia). A teologia reformada (Calvino) ensina a presença espiritual (praesentia spiritualis).",
            referencias: "Mateus 26:26-29; Marcos 14:22-25; Lucas 22:19-20; João 6:51-58; 1 Coríntios 10:16-22; 1 Coríndios 11:23-26; Hebreus 8:6-13"
        },
        {
            termo: "1 Coríntios 15:3-8 - O Evangelho da Ressurreição",
            definicao: "Texto: 'Que Cristo morreu pelos nossos pecados, segundo as Escrituras, e que foi sepultado, e que ressuscitou ao terceiro dia, segundo as Escrituras, e que foi visto por Cefas, e depois pelos doze. Depois foi visto por mais de quinhentos irmãos de uma vez... depois foi visto por Tiago, depois por todos os apóstolos. E por derradeiro de todos, como a um abortivo, me apareceu também a mim.' Significados teológicos: (1) 'Cristo morreu pelos nossos pecados' - a morte vicária (Isaías 53:5-6; 1 Pedro 2:24). (2) 'Segundo as Escrituras' - o cumprimento das profecias (Salmo 22; Isaías 53). (3) 'Foi sepultado' - a realidade da morte. (4) 'Ressuscitou ao terceiro dia' - a vitória sobre a morte. (5) 'Foi visto por...' - as aparições como evidência histórica. (6) 'Mais de quinhentos irmãos de uma vez' - grande número de testemunhas. (7) 'Apareceu também a mim' - a aparição a Paulo (Atos 9:1-9). A teologia reformada vê neste texto a evidência histórica da ressurreição e o cerne do evangelho.",
            referencias: "Salmo 16:10; Isaías 53:5-6; Oséias 6:2; Mateus 28:1-10; Lucas 24:1-12; Lucas 24:13-35; João 20:1-18; Atos 1:3; Atos 9:1-9; 1 Coríntios 15:3-8"
        },
        {
            termo: "1 Coríntios 15:20-28 - Cristo, as Primícias e o Fim",
            definicao: "Texto: 'Mas, agora, Cristo ressuscitou dos mortos, e foi feito as primícias dos que dormem. Porque, assim como a morte veio por um homem, também a ressurreição dos mortos veio por um homem. Porque, assim como todos morrem em Adão, assim também todos serão vivificados em Cristo. Cada um, porém, na sua ordem: Cristo as primícias; depois os que são de Cristo, na sua vinda. Depois virá o fim, quando tiver entregue o reino a Deus, o Pai... para que Deus seja tudo em todos.' Significados teológicos: (1) 'Primícias dos que dormem' - a ressurreição de Cristo é a garantia da nossa ressurreição (Romanos 8:11). (2) 'Assim como todos morrem em Adão' - o pecado original e a morte universal (Romanos 5:12). (3) 'Assim também todos serão vivificados em Cristo' - a ressurreição universal (dos justos e dos ímpios? - João 5:28-29). (4) 'Cada um na sua ordem' - a ordem: Cristo, depois os crentes na parusia. (5) 'Entregue o reino a Deus, o Pai' - a submissão do Filho ao Pai (1 Coríntios 11:3). (6) 'Para que Deus seja tudo em todos' - a consumação final. A teologia reformada vê neste texto a escatologia cristocêntrica.",
            referencias: "Romanos 5:12-21; 1 Coríntios 11:3; 1 Coríndios 15:20-28; Filipenses 3:20-21; 1 Tessalonicenses 4:13-18; Apocalipse 21-22"
        },
        {
            termo: "2 Coríntios 5:18-21 - A Reconciliação em Cristo",
            definicao: "Texto: 'E tudo provém de Deus, que nos reconciliou consigo mesmo por Jesus Cristo, e nos deu o ministério da reconciliação; isto é, Deus estava em Cristo reconciliando consigo o mundo, não lhes imputando os seus pecados; e pôs em nós a palavra da reconciliação. De sorte que somos embaixadores da parte de Cristo... Rogamo-vos, pois, da parte de Cristo, que vos reconcilieis com Deus. Àquele que não conheceu pecado, o fez pecado por nós; para que nele fôssemos feitos justiça de Deus.' Significados teológicos: (1) 'Deus estava em Cristo reconciliando consigo o mundo' - Deus é o autor da reconciliação. (2) 'Não lhes imputando os seus pecados' - o perdão dos pecados em Cristo. (3) 'O fez pecado por nós' - Cristo foi feito pecado (portador do pecado, não pecador) (Isaías 53:6; 1 Pedro 2:24). (4) 'Para que nele fôssemos feitos justiça de Deus' - a imputação da justiça de Cristo (Romanos 4:5-8). (5) 'Ministério da reconciliação' - o evangelismo. (6) 'Embaixadores da parte de Cristo' - os crentes como representantes de Cristo. A teologia reformada vê neste texto a doutrina da expiação vicária (substituição penal) e da imputação.",
            referencias: "Isaías 53:4-6; Isaías 53:11-12; Romanos 3:21-26; Romanos 4:5-8; Romanos 5:10-11; 2 Coríntios 5:18-21; Efésios 2:13-18; 1 Pedro 2:24"
        },
        {
            termo: "Efésios 1:3-14 - Toda Bênção Espiritual em Cristo",
            definicao: "Texto: 'Bendito o Deus e Pai de nosso Senhor Jesus Cristo, o qual nos abençoou com todas as bênçãos espirituais nos lugares celestiais em Cristo; como também nos elegeu nele antes da fundação do mundo... nos predestinou para filhos de adoção por Jesus Cristo... nos fez agradáveis a si no Amado, em quem temos a redenção pelo seu sangue, a remissão das ofensas... nos predestinou... para louvor da sua glória... em quem também vós, depois que ouvistes a palavra da verdade, o evangelho da vossa salvação... crestes e fostes selados com o Espírito Santo da promessa.' Significados teológicos: (1) 'Todas as bênçãos espirituais em Cristo' - a centralidade de Cristo para a salvação. (2) 'Nos elegeu nele antes da fundação do mundo' - a eleição em Cristo (Romanos 8:29-30; 2 Timóteo 1:9). (3) 'Predestinou para filhos de adoção' - a adoção em Cristo (Romanos 8:15; Gálatas 4:5). (4) 'Redenção pelo seu sangue' - a expiação vicária (Efésios 1:7; Colossenses 1:14). (5) 'Fostes selados com o Espírito Santo' - o selo do Espírito como garantia (2 Coríntios 1:22; Efésios 4:30). (6) 'Para louvor da sua glória' - Soli Deo Gloria. A teologia reformada vê neste texto a doutrina da eleição e da redenção em Cristo.",
            referencias: "Romanos 8:15; Romanos 8:29-30; Gálatas 4:5; Efésios 1:3-14; Colossenses 1:14; 2 Timóteo 1:9; 2 Coríndios 1:22; Efésios 4:30"
        },
        {
            termo: "Efésios 1:20-23 - Cristo, a Cabeça da Igreja",
            definicao: "Texto: 'Que operou em Cristo, ressuscitando-o dos mortos e pondo-o à sua direita nos céus, acima de todo principado, e poder, e potestade, e domínio, e de todo o nome que se nomeia, não só neste século, mas também no vindouro; e sujeitou todas as coisas debaixo de seus pés, e para ser a cabeça sobre todas as coisas o deu à igreja, que é o seu corpo, a plenitude daquele que cumpre tudo em todos.' Significados teológicos: (1) 'Ressuscitando-o dos mortos' - a ressurreição de Cristo. (2) 'Pondo-o à sua direita' - a exaltação de Cristo (Salmo 110:1; Atos 2:33-35). (3) 'Acima de todo principado, e poder, e potestade' - a autoridade universal de Cristo (Colossenses 2:10,15). (4) 'Sujeitou todas as coisas debaixo de seus pés' - o senhorio cósmico de Cristo (1 Coríntios 15:27). (5) 'Cabeça sobre todas as coisas' - Cristo é a cabeça da igreja. (6) 'O seu corpo, a plenitude daquele que cumpre tudo em todos' - a igreja como o corpo de Cristo (1 Coríndios 12:12-27; Colossenses 1:18). A teologia reformada vê neste texto a supremacia de Cristo sobre todas as coisas e sua relação com a igreja.",
            referencias: "Salmo 110:1; Atos 2:33-35; 1 Coríntios 12:12-27; 1 Coríndios 15:27; Efésios 1:20-23; Colossenses 1:18; Colossenses 2:10; Colossenses 2:15"
        },
        {
            termo: "Filipenses 2:5-11 - O Hino da Kenosis",
            definicao: "Texto: 'Tende em vós o mesmo sentimento que houve também em Cristo Jesus, que, sendo em forma de Deus, não considerou o ser igual a Deus como algo a que se apegar, mas esvaziou-se a si mesmo, tomando a forma de servo, fazendo-se semelhante aos homens; e, achado na forma de homem, humilhou-se a si mesmo, sendo obediente até à morte, e morte de cruz. Pelo que também Deus o exaltou soberanamente, e lhe deu um nome que é sobre todo o nome, para que ao nome de Jesus se dobre todo joelho dos que estão nos céus, e na terra, e debaixo da terra, e toda língua confesse que Jesus Cristo é o Senhor, para glória de Deus Pai.' Significados teológicos: (1) 'Sendo em forma de Deus' - a divindade de Cristo (João 1:1). (2) 'Não considerou o ser igual a Deus como algo a que se apegar' - Cristo não usou egoistamente seus atributos divinos. (3) 'Esvaziou-se a si mesmo' (ekenōsen) - a kenosis: humilhação voluntária, não perda da divindade. (4) 'Tomando a forma de servo' - a encarnação (João 1:14). (5) 'Obediente até à morte, e morte de cruz' - a obediência máxima (Hebreus 5:8). (6) 'Deus o exaltou soberanamente' - a exaltação (Atos 2:33; Efésios 1:20-21). (7) 'Um nome que é sobre todo o nome' - Kyrios (Senhor), equivalente a YHWH. (8) 'Ao nome de Jesus se dobre todo joelho' - citação de Isaías 45:23 (aplicado a YHWH). (9) 'Confesse que Jesus Cristo é o Senhor' - a confissão universal da divindade de Cristo. A teologia reformada vê neste texto o mais importante hino cristológico sobre a kenosis e a exaltação de Cristo.",
            referencias: "Isaías 45:23; João 1:1-14; Atos 2:33; Romanos 10:9; Efésios 1:20-21; Filipenses 2:5-11; Colossenses 2:9; Hebreus 1:3; Hebreus 5:8"
        },
        {
            termo: "Filipenses 3:7-11 - Conhecer a Cristo",
            definicao: "Texto: 'Mas o que para mim era ganho, reputei-o perda por Cristo. E, na verdade, tenho também por perda todas as coisas, pela excelência do conhecimento de Cristo Jesus, meu Senhor; pelo qual sofri a perda de todas estas coisas, e as considero como escória, para que possa ganhar a Cristo, e seja achado nele, não tendo a minha justiça que vem da lei, mas a que vem pela fé em Cristo, a saber, a justiça que vem de Deus pela fé; para conhecê-lo, e à virtude da sua ressurreição, e à comunicação de suas aflições, sendo feito conforme a sua morte; para ver se de alguma maneira posso chegar à ressurreição dos mortos.' Significados teológicos: (1) 'Conhecimento de Cristo' - o conhecimento supremo (João 17:3). (2) 'Perda de todas as coisas' - a renúncia por Cristo (Mateus 13:44-46). (3) 'Justiça que vem de Deus pela fé' - a justificação pela fé (Romanos 3:21-26). (4) 'Conhecê-lo, e à virtude da sua ressurreição' - a experiência do poder da ressurreição. (5) 'Comunicação de suas aflições' - participação no sofrimento de Cristo (2 Coríntios 1:5; 4:10-11). (6) 'Sendo feito conforme a sua morte' - a morte para o pecado (Romanos 6:5-8). (7) 'Ressurreição dos mortos' - a esperança escatológica. A teologia reformada vê neste texto o anseio do crente por conhecer Cristo em sua vida, morte e ressurreição.",
            referencias: "Mateus 13:44-46; João 17:3; Romanos 3:21-26; Romanos 6:5-8; 2 Coríntios 1:5; 2 Coríntios 4:10-11; Filipenses 3:7-11"
        },
        {
            termo: "Gálatas 2:20 - Cristo Vive em Mim",
            definicao: "Texto: 'Já estou crucificado com Cristo; e vivo, não mais eu, mas Cristo vive em mim; e a vida que agora vivo na carne, vivo-a pela fé do Filho de Deus, o qual me amou e se entregou a si mesmo por mim.' Significados teológicos: (1) 'Já estou crucificado com Cristo' - a identificação do crente com a morte de Cristo (Romanos 6:4-6). (2) 'Vivo, não mais eu, mas Cristo vive em mim' - a união mística com Cristo (unio cum Christo) (João 14:20; 15:4-5). (3) 'Vivo-a pela fé do Filho de Deus' - a fé em Cristo como princípio da vida cristã. (4) 'O qual me amou e se entregou a si mesmo por mim' - o amor de Cristo e sua morte vicária (Efésios 5:2,25; Tito 2:14). (5) A substituição (Cristo vive em mim) e a identificação (crucificado com Cristo). A teologia reformada vê neste texto a expressão clássica da união com Cristo e da vida cristã em Cristo.",
            referencias: "João 14:20; João 15:4-5; Romanos 6:4-6; Gálatas 2:20; Efésios 5:2; Efésios 5:25; Tito 2:14"
        },
        {
            termo: "Gálatas 3:13 - Cristo Redimiu-nos da Maldição da Lei",
            definicao: "Texto: 'Cristo nos resgatou da maldição da lei, fazendo-se maldição por nós; porque está escrito: Maldito todo aquele que for pendurado no madeiro.' Significados teológicos: (1) 'Cristo nos resgatou da maldição da lei' - a redenção (apolytrōsis) (Romanos 3:24). (2) 'Fazendo-se maldição por nós' - a substituição penal (2 Coríntios 5:21; 1 Pedro 2:24). (3) 'Maldito todo aquele que for pendurado no madeiro' - citação de Deuteronômio 21:23 (a maldição da crucificação). (4) 'Pendurado no madeiro' - a cruz (Atos 5:30; 10:39; 13:29). (5) Cristo levou sobre si a maldição da lei para que os crentes fossem libertos. A teologia reformada vê neste texto a doutrina da expiação vicária (substituição penal).",
            referencias: "Deuteronômio 21:23; Romanos 3:24; 2 Coríntios 5:21; Gálatas 3:13; 1 Pedro 2:24; Atos 5:30; Atos 10:39; Atos 13:29"
        },
        {
            termo: "Gálatas 3:16 - A Semente de Abraão",
            definicao: "Texto: 'Ora, as promessas foram feitas a Abraão e à sua semente. Não diz: E às sementes, como falando de muitos, mas como de um só: E à tua semente, que é Cristo.' Significados teológicos: (1) As promessas a Abraão (Gênesis 12:3; 22:18) foram feitas a 'uma semente', singular. (2) 'Não diz: E às sementes' - a interpretação paulina da promessa como referindo-se a Cristo. (3) 'Que é Cristo' - Cristo é a semente de Abraão (Mateus 1:1). (4) A bênção de Abraão vem aos gentios por meio de Cristo (Gálatas 3:14). (5) Os crentes são filhos de Abraão pela fé em Cristo (Gálatas 3:7-9). A teologia reformada vê neste texto o cumprimento das promessas abraâmicas em Cristo.",
            referencias: "Gênesis 12:3; Gênesis 22:18; Mateus 1:1; Gálatas 3:6-29; Romanos 4:13-17"
        },
        {
            termo: "Hebreus 1:1-4 - O Filho, o Resplendor da Glória",
            definicao: "Texto: 'Havendo Deus antigamente falado muitas vezes e de muitas maneiras pelos profetas, a nós falou-nos nestes últimos dias pelo Filho, a quem constituiu herdeiro de todas as coisas, por quem fez também o mundo. O qual, sendo o resplendor da sua glória e a expressa imagem da sua pessoa, e sustentando todas as coisas pela palavra do seu poder, havendo feito por si mesmo a purificação dos nossos pecados, assentou-se à destra da majestade nas alturas, feito tanto mais excelente do que os anjos, quanto herdou mais excelente nome do que eles.' Significados teológicos: (1) 'Nestes últimos dias falou-nos pelo Filho' - a revelação final em Cristo. (2) 'Herdeiro de todas as coisas' - Cristo como herdeiro universal (Salmo 2:8). (3) 'Por quem fez também o mundo' - Cristo como Criador (João 1:3; Colossenses 1:16). (4) 'Resplendor da sua glória' (apaugasma) - a irradiação da glória divina. (5) 'Expressa imagem da sua pessoa' (charaktēr) - a impressão exata da natureza de Deus (João 1:18; 14:9). (6) 'Sustentando todas as coisas pela palavra do seu poder' - Cristo como Sustentador (Colossenses 1:17). (7) 'Purificação dos nossos pecados' - a expiação (Hebreus 9:14). (8) 'Assentou-se à destra da majestade' - a exaltação (Salmo 110:1). A teologia reformada vê neste texto a mais alta afirmação da divindade de Cristo no prólogo de Hebreus.",
            referencias: "Salmo 2:8; Salmo 110:1; João 1:1-3; João 1:18; João 14:9; Colossenses 1:16-17; Hebreus 1:1-4; Hebreus 9:14"
        },
        {
            termo: "Hebreus 2:14-18 - Cristo, o Irmão na Humanidade",
            definicao: "Texto: 'E, visto como os filhos participam da carne e do sangue, também ele participou das mesmas coisas, para que pela morte aniquilasse o que tinha o império da morte, isto é, o diabo; e livrasse todos os que, com medo da morte, estavam por toda a vida sujeitos à servidão... Porque convinha que aquele, para quem são todas as coisas... trouxesse muitos filhos à glória... E, visto como os filhos são participantes da carne e do sangue, também ele participou das mesmas coisas... Porque, naquilo que ele mesmo padeceu, sendo tentado, pode socorrer aos que são tentados.' Significados teológicos: (1) 'Participou da carne e do sangue' - a verdadeira humanidade de Cristo (João 1:14). (2) 'Para que pela morte aniquilasse o diabo' - a vitória sobre Satanás (Colossenses 2:15; 1 João 3:8). (3) 'Livrasse os que estavam sujeitos à servidão' - a libertação do medo da morte. (4) 'Não toma os anjos, mas a semente de Abraão' - a encarnação é pela humanidade, não pelos anjos. (5) 'Semelhante aos irmãos' - a solidariedade de Cristo com a humanidade. (6) 'Misericordioso e fiel sumo sacerdote' - Cristo como Sumo Sacerdote (Hebreus 4:14-16). (7) 'Pode socorrer aos que são tentados' - a compaixão de Cristo (Hebreus 4:15). A teologia reformada vê neste texto a humanidade de Cristo e sua vitória sobre o diabo.",
            referencias: "João 1:14; Colossenses 2:15; 1 João 3:8; Hebreus 2:14-18; Hebreus 4:14-16; 1 Pedro 3:18"
        },
        {
            termo: "Hebreus 4:14-16 - O Sumo Sacerdote Compassivo",
            definicao: "Texto: 'Visto que temos um grande sumo sacerdote, Jesus, Filho de Deus, que penetrou nos céus, retenhamos firmemente a nossa confissão. Porque não temos um sumo sacerdote que não possa compadecer-se das nossas fraquezas; porém um que, como nós, em tudo foi tentado, mas sem pecado. Cheguemo-nos, pois, confiadamente ao trono da graça, para que possamos alcançar misericórdia e achar graça, a fim de sermos ajudados em tempo oportuno.' Significados teológicos: (1) 'Grande sumo sacerdote' - Jesus é o Sumo Sacerdote perfeito (Hebreus 5:5-10; 7:1-28). (2) 'Penetrou nos céus' - a ascensão e entrada no santuário celestial (Hebreus 9:11-12,24). (3) 'Retenhamos firmemente a nossa confissão' - a perseverança na fé. (4) 'Em tudo foi tentado, mas sem pecado' - a impecabilidade de Cristo (Hebreus 2:18). (5) 'Cheguemo-nos confiadamente ao trono da graça' - o acesso a Deus por meio de Cristo (Efésios 2:18; 3:12). (6) 'Alcançar misericórdia e achar graça' - a graça disponível em Cristo. A teologia reformada vê neste texto a base da confiança do crente na oração.",
            referencias: "Romanos 8:34; Efésios 2:18; Efésios 3:12; Hebreus 2:18; Hebreus 4:14-16; Hebreus 5:5-10; Hebreus 7:1-28; Hebreus 9:11-12; Hebreus 9:24"
        },
        {
            termo: "Hebreus 7:1-28 - Cristo, Sacerdote segundo Melquisedeque",
            definicao: "Texto (excerto): 'Porque este Melquisedeque... primeiro se interpreta Rei de justiça, e depois também Rei de Salém, que é Rei de paz; sem pai, sem mãe, sem genealogia, não tendo princípio de dias nem fim de vida, mas feito semelhante ao Filho de Deus... porque este, de quem se dizem estas coisas, é de outra tribo, da qual ninguém serviu ao altar. Porque é notório que o nosso Senhor procedeu de Judá... E ainda muito mais manifesto é, que à semelhança de Melquisedeque se levanta outro sacerdote... que não é feito segundo a lei do mandamento carnal, mas segundo o poder da vida indissolúvel... porque ele permanece para sempre... salva perfeitamente os que por ele se chegam a Deus... que é santo, inocente, imaculado, separado dos pecadores e feito mais sublime do que os céus.' Significados teológicos: (1) Melquisedeque como tipo de Cristo: 'sem pai, sem mãe, sem genealogia' - tipologicamente, seu sacerdócio não depende de linhagem. (2) 'Rei de justiça' e 'Rei de paz' - Cristo é o Rei de justiça e paz (Isaías 9:6-7). (3) 'Sacerdote para sempre' - o sacerdócio eterno de Cristo. (4) 'Segundo o poder da vida indissolúvel' - o sacerdócio de Cristo baseado na ressurreição. (5) 'Salva perfeitamente' - a suficiência do sacerdócio de Cristo. (6) 'Santo, inocente, imaculado, separado dos pecadores' - a pureza de Cristo. A teologia reformada vê neste texto a superioridade do sacerdócio de Cristo sobre o levítico.",
            referencias: "Gênesis 14:18-20; Salmo 110:4; Isaías 9:6-7; Hebreus 5:6; Hebreus 5:10; Hebreus 6:20; Hebreus 7:1-28"
        },
        {
            termo: "Hebreus 9:11-28 - O Sacrifício Perfeito de Cristo",
            definicao: "Texto: 'Mas Cristo, vindo como sumo sacerdote dos bens futuros... não por sangue de bodes e bezerros, mas por seu próprio sangue, entrou uma vez no santuário, havendo efetuado uma eterna redenção... porque o sangue de Cristo... purificará a vossa consciência das obras mortas... Porque Cristo não entrou num santuário feito por mãos... mas no mesmo céu... para agora comparecer por nós diante da face de Deus... Assim também Cristo, oferecendo-se uma vez para tirar os pecados de muitos, aparecerá segunda vez... aos que o esperam para salvação.' Significados teológicos: (1) 'Por seu próprio sangue' - a expiação vicária (Efésios 1:7; 1 Pedro 1:18-19). (2) 'Entrou uma vez no santuário' - a entrada de Cristo no céu (Hebreus 4:14). (3) 'Eterna redenção' - a suficiência do sacrifício de Cristo (Hebreus 10:10-14). (4) 'Purificará a vossa consciência' - a purificação interior (1 João 1:7,9). (5) 'Comparecer por nós diante da face de Deus' - a intercessão de Cristo (Romanos 8:34; 1 João 2:1). (6) 'Oferecendo-se uma vez' - a unicidade do sacrifício (Hebreus 7:27; 10:10). (7) 'Aparecerá segunda vez' - a parusia (segunda vinda). A teologia reformada vê neste texto a suficiência e unicidade do sacrifício de Cristo.",
            referencias: "Romanos 8:34; Efésios 1:7; Hebreus 4:14; Hebreus 7:27; Hebreus 9:11-28; Hebreus 10:10-14; 1 Pedro 1:18-19; 1 João 1:7; 1 João 1:9; 1 João 2:1"
        },
        {
            termo: "João 1:1-18 - O Prólogo do Evangelho",
            definicao: "Texto: 'No princípio era o Verbo, e o Verbo estava com Deus, e o Verbo era Deus. Ele estava no princípio com Deus. Todas as coisas foram feitas por ele, e sem ele nada do que foi feito se fez. Nele estava a vida, e a vida era a luz dos homens... E o Verbo se fez carne, e habitou entre nós, e vimos a sua glória, glória como do unigênito do Pai, cheio de graça e de verdade... Deus nunca foi visto por alguém; o Filho unigênito, que está no seio do Pai, esse o revelou.' Significados teológicos: (1) 'No princípio era o Verbo' - a pré-existência eterna de Cristo (Gênesis 1:1). (2) 'O Verbo estava com Deus' - a distinção pessoal do Filho em relação ao Pai. (3) 'O Verbo era Deus' - a divindade de Cristo. (4) 'Todas as coisas foram feitas por ele' - Cristo como Criador (Colossenses 1:16). (5) 'Nele estava a vida' - Cristo como fonte da vida (João 5:26; 11:25). (6) 'O Verbo se fez carne' - a encarnação (João 1:14). (7) 'Habitou entre nós' - 'tabernaculou' (João 1:14). (8) 'Cheio de graça e de verdade' - a plenitude de Cristo (Colossenses 2:9). (9) 'O Filho unigênito... o revelou' - Cristo como Revelador do Pai (Mateus 11:27). A teologia reformada vê neste texto o mais importante resumo da cristologia joanina.",
            referencias: "Gênesis 1:1; Mateus 11:27; João 1:1-18; João 5:26; João 11:25; Colossenses 1:16; Colossenses 2:9"
        },
        {
            termo: "João 1:29 - O Cordeiro de Deus",
            definicao: "Texto: 'Eis o Cordeiro de Deus, que tira o pecado do mundo.' Significados teológicos: (1) 'Cordeiro de Deus' - Jesus como o sacrifício expiatório (Isaías 53:7; 1 Pedro 1:19). (2) 'Tira o pecado do mundo' - a expiação vicária (João 1:36; 1 João 2:2). (3) 'Do mundo' - a universalidade da oferta (embora eficaz apenas para os crentes). (4) O cumprimento do cordeiro pascal (Êxodo 12) e do Servo Sofredor (Isaías 53). (5) João Batista identifica Jesus como o Cordeiro. A teologia reformada vê neste texto a identificação de Cristo como o sacrifício expiatório.",
            referencias: "Êxodo 12:1-28; Isaías 53:7; João 1:29; João 1:36; 1 Pedro 1:18-19; 1 João 2:2; Apocalipse 5:6-14"
        },
        {
            termo: "João 1:51 - A Escada de Jacó",
            definicao: "Texto: 'Na verdade, na verdade vos digo que vereis o céu aberto, e os anjos de Deus subindo e descendo sobre o Filho do Homem.' Significados teológicos: (1) 'O Filho do Homem' - o título favorito de Jesus para si mesmo. (2) Referência à escada de Jacó (Gênesis 28:12). (3) Jesus é a escada que liga o céu e a terra - o único mediador entre Deus e os homens (1 Timóteo 2:5). (4) 'Anjos de Deus subindo e descendo' - a mediação angelical serve a Cristo. (5) O céu é aberto por meio de Cristo (Hebreus 10:19-22). A teologia reformada vê neste texto a mediação exclusiva de Cristo.",
            referencias: "Gênesis 28:12; João 1:51; 1 Timóteo 2:5; Hebreus 10:19-22"
        },
        {
            termo: "João 3:14-15 - A Serpente de Bronze",
            definicao: "Texto: 'E, como Moisés levantou a serpente no deserto, assim importa que o Filho do Homem seja levantado; para que todo aquele que nele crê não pereça, mas tenha a vida eterna.' Significados teológicos: (1) Referência à serpente de bronze (Números 21:4-9). (2) 'Assim importa que o Filho do Homem seja levantado' - a crucificação de Cristo (João 12:32-33). (3) A serpente de bronze tinha forma de serpente (mas não venenosa); Cristo foi feito pecado (2 Coríntios 5:21), mas não tinha pecado. (4) 'Todo aquele que nele crê' - a universalidade da oferta. (5) 'Não pereça, mas tenha a vida eterna' - a salvação pela fé. (6) O levantamento na cruz é exaltação e humilhação simultaneamente. A teologia reformada vê neste texto a expiação vicária e a salvação pela fé.",
            referencias: "Números 21:4-9; João 3:14-15; João 12:32-33; 2 Coríntios 5:21"
        },
        {
            termo: "João 3:16 - O Amor de Deus Manifestado",
            definicao: "Texto: 'Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna.' Significados teológicos: (1) 'Deus amou o mundo' - a motivação da salvação é o amor de Deus (1 João 4:9-10). (2) 'Deu o seu Filho unigênito' - o dom de Cristo (Romanos 8:32). (3) 'Todo aquele que nele crê' - a condição da salvação é a fé (João 1:12; Romanos 10:9). (4) 'Não pereça, mas tenha a vida eterna' - o resultado da fé é a vida eterna (João 5:24). (5) O versículo mais conhecido da Bíblia, resumindo o evangelho. A teologia reformada vê neste texto o amor de Deus como causa da expiação (não a expiação como causa do amor).",
            referencias: "João 1:12; João 5:24; Romanos 8:32; Romanos 10:9; 1 João 4:9-10"
        },
        {
            termo: "João 8:58 - O Eu Sou",
            definicao: "Texto: 'Disse-lhes Jesus: Em verdade, em verdade vos digo que antes que Abraão existisse, EU SOU.' Significados teológicos: (1) 'EU SOU' (Ego Eimi) - a auto-designação divina de Jesus, ecoando Êxodo 3:14 ('EU SOU O QUE SOU' - YHWH). (2) 'Antes que Abraão existisse' - Jesus afirma sua pré-existência (João 1:1). (3) Os judeus pegaram pedras para apedrejá-lo (João 8:59), reconhecendo a afirmação de divindade como blasfêmia (Levítico 24:16). (4) O uso do presente ('EU SOU') em vez do passado ('eu era') indica eternidade. (5) Este é um dos textos mais fortes sobre a divindade de Cristo. A teologia reformada vê neste texto a afirmação inequívoca da divindade de Cristo.",
            referencias: "Êxodo 3:14; Isaías 43:10; João 1:1; João 8:58"
        },
        {
            termo: "João 10:11 - O Bom Pastor",
            definicao: "Texto: 'Eu sou o bom pastor; o bom pastor dá a sua vida pelas ovelhas.' Significados teológicos: (1) 'Eu sou o bom pastor' - Jesus como o Pastor (Ezequiel 34:11-24; Salmo 23). (2) 'Dá a sua vida pelas ovelhas' - a morte vicária de Cristo (João 10:15,17-18). (3) Contraste com o mercenário (João 10:12-13) - Jesus não foge do perigo. (4) 'Conheço as minhas ovelhas, e elas me conhecem' (João 10:14) - o conhecimento mútuo entre Cristo e os crentes. (5) 'Tenho outras ovelhas que não são deste aprisco' (João 10:16) - os gentios. (6) 'Dou a minha vida para tornar a tomá-la' (João 10:17-18) - a ressurreição. A teologia reformada vê neste texto o cuidado pastoral de Cristo e sua morte vicária.",
            referencias: "Salmo 23; Ezequiel 34:11-24; João 10:11-18; 1 Pedro 2:25"
        },
        {
            termo: "João 14:6 - O Caminho, a Verdade e a Vida",
            definicao: "Texto: 'Eu sou o caminho, e a verdade, e a vida; ninguém vem ao Pai senão por mim.' Significados teológicos: (1) 'Eu sou o caminho' - Jesus é o único mediador (1 Timóteo 2:5). (2) 'A verdade' - Jesus é a revelação definitiva de Deus (João 1:18; 14:9). (3) 'A vida' - Jesus é a fonte da vida eterna (João 11:25; 1 João 5:11-12). (4) 'Ninguém vem ao Pai senão por mim' - a exclusividade de Cristo (Atos 4:12). (5) Rejeição do pluralismo religioso (outros caminhos). A teologia reformada vê neste texto a afirmação do Solus Christus (somente Cristo).",
            referencias: "João 1:18; João 11:25; João 14:9; Atos 4:12; 1 Timóteo 2:5; 1 João 5:11-12"
        },
        {
            termo: "João 17:1-26 - A Oração Sacerdotal",
            definicao: "Texto: 'Pai, é chegada a hora; glorifica a teu Filho, para que também o teu Filho te glorifique a ti... A vida eterna é esta: que te conheçam, a ti só, por único Deus verdadeiro, e a Jesus Cristo, a quem enviaste... Eu te glorifiquei na terra, tendo consumado a obra que me deste para fazer. E agora glorifica-me tu, ó Pai, junto de ti mesmo, com aquela glória que eu tinha contigo antes que o mundo existisse.' Significados teológicos: (1) 'Glorifica a teu Filho' - a glória da cruz. (2) 'A vida eterna é esta: que te conheçam' - o conhecimento de Deus em Cristo. (3) 'Tendo consumado a obra' - a obra redentora de Cristo (João 19:30). (4) 'A glória que eu tinha contigo antes que o mundo existisse' - a pré-existência e a glória eterna de Cristo. (5) Jesus ora pelos discípulos e por todos os crentes (João 17:20-26). (6) 'Para que todos sejam um' - a unidade da igreja. A teologia reformada vê neste texto a intercessão de Cristo e sua glória eterna.",
            referencias: "João 17:1-26; João 19:30; Romanos 8:34; Hebreus 7:25; 1 João 2:1"
        },
        {
            termo: "João 20:28 - Senhor Meu e Deus Meu",
            definicao: "Texto: 'Tomé respondeu e disse-lhe: Senhor meu, e Deus meu!' Significados teológicos: (1) A confissão de Tomé é a mais explícita declaração da divindade de Cristo no Novo Testamento. (2) 'Senhor meu' (Kyrios) - título equivalente a YHWH (Filipenses 2:9-11). (3) 'Deus meu' (Theos) - aplicado diretamente a Jesus (João 1:1; Tito 2:13; Romanos 9:5). (4) A confissão de Tomé ocorre após ver as marcas da crucificação (João 20:24-29). (5) Jesus aceita a adoração de Tomé (contraste com Atos 10:25-26; 14:13-15). (6) Jesus diz: 'Bem-aventurados os que não viram e creram' (João 20:29). A teologia reformada vê neste texto a mais clara confissão da divindade de Cristo.",
            referencias: "Salmo 35:23; João 1:1; João 20:28; Romanos 9:5; Filipenses 2:9-11; Tito 2:13; Atos 10:25-26; Atos 14:13-15"
        },
        {
            termo: "Romanos 1:1-4 - O Evangelho acerca de seu Filho",
            definicao: "Texto: 'Paulo, servo de Jesus Cristo, chamado para apóstolo, separado para o evangelho de Deus, o qual antes prometeu pelos seus profetas nas santas Escrituras, acerca de seu Filho, que foi feito da semente de Davi segundo a carne, e declarado Filho de Deus com poder, segundo o Espírito de santificação, pela ressurreição dos mortos, Jesus Cristo nosso Senhor.' Significados teológicos: (1) 'Acerca de seu Filho' - o conteúdo do evangelho é Cristo. (2) 'Feito da semente de Davi segundo a carne' - a humanidade de Cristo (descendente de Davi) (2 Timóteo 2:8). (3) 'Declarado Filho de Deus com poder... pela ressurreição dos mortos' - a divindade de Cristo confirmada pela ressurreição (Atos 2:36; Romanos 1:4). (4) 'Jesus Cristo nosso Senhor' - o título Kyrios (Senhor). (5) A dupla natureza de Cristo (humana e divina). A teologia reformada vê neste texto a cristologia paulina em resumo.",
            referencias: "2 Samuel 7:12-16; Salmo 2:7; Atos 2:36; Romanos 1:1-4; Romanos 9:5; 2 Timóteo 2:8"
        },
        {
            termo: "Romanos 3:21-26 - A Justificação pela Fé em Cristo",
            definicao: "Texto: 'Mas, agora, sem a lei, se manifestou a justiça de Deus... a justiça de Deus pela fé em Jesus Cristo para todos e sobre todos os que creem... sendo justificados gratuitamente pela sua graça, pela redenção que há em Cristo Jesus, a quem Deus propôs para propiciação pela fé no seu sangue... para manifestação da sua justiça... para que ele seja justo e justificador daquele que tem fé em Jesus.' Significados teológicos: (1) 'Justiça de Deus' - a justiça que Deus imputa ao crente. (2) 'Pela fé em Jesus Cristo' - a justificação é pela fé, não pelas obras (Gálatas 2:16). (3) 'Redenção que há em Cristo Jesus' - a libertação pelo sangue de Cristo (Efésios 1:7). (4) 'Propiciação' (hilastērion) - a satisfação da justiça divina (1 João 2:2; 4:10). (5) 'Pela fé no seu sangue' - a fé na obra expiatória de Cristo. (6) 'Para que ele seja justo e justificador' - a justiça e a misericórdia de Deus conciliadas na cruz. A teologia reformada vê neste texto o coração da doutrina da justificação.",
            referencias: "Isaías 53:11; Romanos 3:21-26; Gálatas 2:16; Efésios 1:7; 1 João 2:2; 1 João 4:10"
        },
        {
            termo: "Romanos 5:12-21 - O Segundo Adão",
            definicao: "Texto: 'Portanto, como por um homem entrou o pecado no mundo, e pelo pecado a morte, assim também a morte passou a todos os homens, por isso que todos pecaram... Mas não é assim o dom gratuito como a ofensa... A condenação veio por uma só ofensa, mas o dom gratuito veio de muitas ofensas para justificação... Assim como pela desobediência de um só homem, muitos foram feitos pecadores, assim também pela obediência de um, muitos serão feitos justos.' Significados teológicos: (1) 'Por um homem entrou o pecado' - Adão como o cabeça federal da humanidade (pecado original). (2) 'A morte passou a todos os homens' - a morte universal (1 Coríntios 15:21-22). (3) 'Adão... que é a figura daquele que havia de vir' - Adão como tipo de Cristo. (4) 'Pela obediência de um, muitos serão feitos justos' - a obediência ativa de Cristo (Filipenses 2:8). (5) 'A graça reinasse pela justiça para a vida eterna' - o contraste entre Adão e Cristo. A teologia reformada vê neste texto a doutrina do pecado original e da justificação pela obediência de Cristo.",
            referencias: "Gênesis 3:1-24; Romanos 5:12-21; 1 Coríntios 15:21-22; 1 Coríndios 15:45-49; Filipenses 2:8"
        },
        {
            termo: "Romanos 10:9-10 - Confessar o Senhor Jesus",
            definicao: "Texto: 'Se com a tua boca confessares ao Senhor Jesus, e em teu coração creres que Deus o ressuscitou dentre os mortos, serás salvo. Porque com o coração se crê para a justiça, e com a boca se faz confissão para a salvação.' Significados teológicos: (1) 'Confessares ao Senhor Jesus' - confessar Jesus como Kyrios (Senhor), equivalente a YHWH (Filipenses 2:11). (2) 'Creres que Deus o ressuscitou dentre os mortos' - a fé na ressurreição como essencial. (3) 'Serás salvo' - a promessa da salvação. (4) Citação de Joel 2:32: 'Todo aquele que invocar o nome do Senhor será salvo' (Romanos 10:13). (5) O nome 'Senhor' (Kyrios) aplicado a Jesus é o nome de YHWH. A teologia reformada vê neste texto a confissão de fé essencial para a salvação.",
            referencias: "Joel 2:32; Romanos 10:9-13; Filipenses 2:11"
        },
        {
            termo: "Romanos 11:36 - A Glória de Cristo",
            definicao: "Texto: 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém.' Significados teológicos: (1) 'Dele e por ele, e para ele' - a origem, o meio e o fim de todas as coisas é Deus (e Cristo). (2) 'Soli Deo Gloria' - somente a Deus a glória. (3) Este versículo é uma doxologia que glorifica a Deus em Cristo. (4) Encerra a seção sobre a soberania de Deus (Romanos 9-11). A teologia reformada vê neste texto o princípio do Soli Deo Gloria (somente a Deus a glória).",
            referencias: "Romanos 11:36; 1 Coríntios 8:6; Colossenses 1:16; Hebreus 2:10"
        },
        {
            termo: "Tito 2:13 - O Grande Deus e Salvador",
            definicao: "Texto: 'Aguardando a bem-aventurada esperança e o aparecimento da glória do grande Deus e nosso Salvador Jesus Cristo.' Significados teológicos: (1) 'Grande Deus e nosso Salvador Jesus Cristo' - uma das mais claras afirmações da divindade de Cristo no Novo Testamento. (2) A gramática grega (regra de Granville Sharp) indica que 'grande Deus' e 'Salvador' referem-se à mesma pessoa, Jesus Cristo. (3) 'Aguardando a bem-aventurada esperança' - a parusia (segunda vinda). (4) 'Aparecimento da glória' - a manifestação gloriosa de Cristo na segunda vinda. (5) Jesus é chamado de 'grande Deus' (contraste com o arianismo). A teologia reformada vê neste texto uma afirmação inequívoca da divindade de Cristo.",
            referencias: "Isaías 9:6; João 20:28; Romanos 9:5; Tito 2:13; 2 Pedro 1:1"
        },
        {
            termo: "1 Pedro 2:21-25 - O Exemplo e o Substituto",
            definicao: "Texto: 'Porque para isto sois chamados, pois também Cristo padeceu por nós, deixando-nos o exemplo, para que sigais as suas pisadas. Ele não cometeu pecado, nem na sua boca se achou engano... Levando ele mesmo os nossos pecados em seu corpo sobre o madeiro, para que, mortos para os pecados, vivêssemos para a justiça; e pelas suas pisaduras fostes sarados. Porque éreis como ovelhas desgarradas... mas agora tendes voltado ao Pastor e Bispo das vossas almas.' Significados teológicos: (1) 'Cristo padeceu por nós' - a morte vicária. (2) 'Deixando-nos o exemplo' - a imitação de Cristo (Imitatio Christi). (3) 'Ele não cometeu pecado' - a impecabilidade de Cristo (Isaías 53:9; Hebreus 4:15). (4) 'Levando ele mesmo os nossos pecados' - a expiação vicária (Isaías 53:4-6,12). (5) 'Pelas suas pisaduras fostes sarados' - citação de Isaías 53:5. (6) 'Pastor e Bispo das vossas almas' - Cristo como Pastor (João 10:11) e Guardião. A teologia reformada vê neste texto tanto a expiação vicária quanto o exemplo de Cristo.",
            referencias: "Isaías 53:4-6; Isaías 53:9; Isaías 53:11-12; Mateus 16:24; João 10:11; 1 Pedro 2:21-25; 1 João 2:6"
        },
        {
            termo: "1 João 1:7 - O Sangue de Jesus Purifica",
            definicao: "Texto: 'Mas, se andarmos na luz, como ele na luz está, temos comunhão uns com os outros, e o sangue de Jesus Cristo, seu Filho, nos purifica de todo o pecado.' Significados teológicos: (1) 'O sangue de Jesus Cristo' - a morte expiatória de Cristo (Efésios 1:7; Colossenses 1:14). (2) 'Nos purifica de todo o pecado' - a purificação contínua (1 João 1:9). (3) 'Andarmos na luz' - a vida em comunhão com Deus. (4) 'Temos comunhão uns com os outros' - a comunhão dos santos. (5) O sangue de Cristo é o meio de purificação. A teologia reformada vê neste texto a obra contínua de purificação pelo sangue de Cristo.",
            referencias: "Efésios 1:7; Colossenses 1:14; 1 João 1:7; 1 João 1:9; Apocalipse 1:5"
        },
        {
            termo: "Apocalipse 1:8 - O Alfa e o Ômega",
            definicao: "Texto: 'Eu sou o Alfa e o Ômega, o princípio e o fim, diz o Senhor, que é, e que era, e que há de vir, o Todo-Poderoso.' Significados teológicos: (1) 'Alfa e Ômega' - primeira e última letras do alfabeto grego, significando eternidade e totalidade. (2) 'O princípio e o fim' - Cristo é o começo e o fim de todas as coisas. (3) 'Que é, e que era, e que há de vir' - a eternidade de Cristo. (4) 'O Todo-Poderoso' (Pantokrator) - um título divino (Apocalipse 4:8; 11:17; 15:3; 16:7,14; 19:6,15). (5) Este versículo ecoa Êxodo 3:14 ('EU SOU'). A teologia reformada vê neste texto a afirmação da divindade de Cristo e seu senhorio eterno.",
            referencias: "Êxodo 3:14; Isaías 41:4; Isaías 44:6; Apocalipse 1:8; Apocalipse 21:6; Apocalipse 22:13"
        },
        {
            termo: "Apocalipse 5:6-14 - O Cordeiro Digno",
            definicao: "Texto: 'E olhei, e eis que estava no meio do trono... um Cordeiro como havendo sido morto... E veio, e tomou o livro... E cantavam um novo cântico, dizendo: Digno és de tomar o livro e de abrir os seus selos, porque foste morto e com o teu sangue compraste para Deus homens de toda tribo, língua, povo e nação... Digno é o Cordeiro, que foi morto, de receber o poder, e riquezas, e sabedoria, e força, e honra, e glória, e ações de graças. E toda criatura... ouvi dizer: Ao que está assentado sobre o trono, e ao Cordeiro, seja o louvor, e a honra, e a glória, e o poder para todo o sempre.' Significados teológicos: (1) 'Cordeiro como havendo sido morto' - Cristo como o Cordeiro sacrificial (João 1:29). (2) 'Digno és... porque foste morto' - a dignidade de Cristo baseada em seu sacrifício. (3) 'Com o teu sangue compraste' - a redenção pelo sangue (Efésios 1:7). (4) 'Homens de toda tribo, língua, povo e nação' - a universalidade da redenção. (5) Adoração ao Cordeiro juntamente com Deus Pai. (6) O Cordeiro é digno de receber poder, riquezas, sabedoria, força, honra, glória e ações de graças. A teologia reformada vê neste texto a adoração celestial a Cristo, o Cordeiro.",
            referencias: "João 1:29; Efésios 1:7; Apocalipse 5:6-14; Apocalipse 7:9-17; Apocalipse 13:8; Apocalipse 21:22-23"
        },
        {
            termo: "Apocalipse 19:11-16 - O Rei dos Reis",
            definicao: "Texto: 'E vi o céu aberto, e eis um cavalo branco... e o que estava assentado sobre ele chama-se Fiel e Verdadeiro... Seus olhos eram como chama de fogo... e tinha um nome escrito, que ninguém sabia senão ele mesmo... e o nome pelo qual se chama é a Palavra de Deus... e ele mesmo é o que pisa o lagar do vinho do furor e da ira do Deus Todo-Poderoso. E no seu vestido e na sua coxa tem escrito este nome: REI DOS REIS, E SENHOR DOS SENHORES.' Significados teológicos: (1) 'Cavalo branco' - símbolo de vitória e conquista. (2) 'Fiel e Verdadeiro' - a fidelidade de Cristo. (3) 'Olhos como chama de fogo' - o juízo penetrante. (4) 'Palavra de Deus' (Logos) - título joanino (João 1:1; 1 João 5:7; Apocalipse 19:13). (5) 'Rei dos reis e Senhor dos senhores' - a soberania universal de Cristo (1 Timóteo 6:15; Apocalipse 17:14). (6) Cristo como juiz e guerreiro. A teologia reformada vê neste texto a segunda vinda de Cristo como Rei e Juiz.",
            referencias: "João 1:1; 1 Timóteo 6:15; Apocalipse 17:14; Apocalipse 19:11-16; Apocalipse 22:13"
        },
        {
            termo: "Apocalipse 22:20-21 - A Vinda de Cristo",
            definicao: "Texto: 'Aquele que testifica estas coisas diz: Certamente cedo venho. Amém. Ora vem, Senhor Jesus. A graça de nosso Senhor Jesus Cristo seja com todos vós. Amém.' Significados teológicos: (1) 'Cedo venho' - a promessa da segunda vinda (parusia). (2) 'Ora vem, Senhor Jesus' (Marana tha) - a resposta da igreja (1 Coríntios 16:22). (3) 'A graça de nosso Senhor Jesus Cristo' - a bênção final. (4) 'Amém' - a afirmação de fé. (5) O Novo Testamento termina com a esperança da vinda de Cristo. A teologia reformada vê neste texto a esperança escatológica da igreja: a vinda do Senhor Jesus.",
            referencias: "1 Coríntios 16:22; Apocalipse 1:7; Apocalipse 22:12; Apocalipse 22:20-21"
        }
    ]
};