// volume/volume-57.js
window.LIVRO_DATA = {
    nome: "Volume LVII",
    dados: [
        {
            termo: "01. Introdução: Cristo, o Criador e Redentor da Criação",
            definicao: "A ecologia (cuidado da criação) é uma preocupação cristã, porque a criação pertence a Cristo. 'Porque nele foram criadas todas as coisas que há nos céus e na terra... tudo foi criado por ele e para ele' (Colossenses 1:16). 'Ao Senhor pertence a terra e a sua plenitude' (Salmo 24:1). A teologia reformada afirma que o cuidado da criação é parte da mordomia cristã. Este volume explora a relação entre cristologia e ecologia: a criação como obra de Cristo, o mandato de domínio (Gênesis 1:28) vs. dominação destrutiva, a queda e a corrupção da criação (Romanos 8:20-22), a redenção da criação (Romanos 8:19-23), a nova criação (Apocalipse 21-22), e a responsabilidade cristã diante da crise ambiental (mudança climática, poluição, desmatamento, extinção de espécies). 'Os céus declaram a glória de Deus, e o firmamento anuncia a obra das suas mãos' (Salmo 19:1). 'E Deus viu tudo quanto tinha feito, e eis que era muito bom' (Gênesis 1:31).",
            referencias: "Gênesis 1:31; Salmo 19:1; Salmo 24:1; Romanos 8:19-23; Colossenses 1:15-20; Apocalipse 21-22"
        },
        {
            termo: "02. A Criação como Obra de Cristo - O Valor Intrínseco da Natureza",
            definicao: "A criação não é uma ilusão (gnosticismo), nem um deus (panteísmo), nem apenas um recurso a ser explorado (materialismo). A criação é obra de Cristo e tem valor intrínseco porque foi criada por Ele. 'Todas as coisas foram feitas por ele, e sem ele nada do que foi feito se fez' (João 1:3). 'Ele é a imagem do Deus invisível, o primogênito de toda a criação' (Colossenses 1:15). A criação reflete a glória de Cristo. 'Os céus declaram a glória de Deus' (Salmo 19:1). 'Porque as suas coisas invisíveis, desde a criação do mundo, tanto o seu eterno poder como a sua divindade, se entendem e claramente se veem pelas coisas que estão criadas' (Romanos 1:20). Implicações: (1) A natureza não deve ser adorada (panteísmo), mas respeitada. (2) A natureza não deve ser explorada sem limites (materialismo). (3) A natureza tem valor além de sua utilidade para o homem. (4) A natureza é um meio para conhecer a glória de Cristo. 'Louvai ao Senhor desde os céus... louvai-o, sol e lua; louvai-o, todas as estrelas luzentes' (Salmo 148:1,3).",
            referencias: "Salmo 148:1-14; Romanos 1:20; João 1:1-3; Colossenses 1:15-20; Romanos 1:20; Hebreus 1:1-3"
        },
        {
            termo: "03. O Mandato de Domínio - Cultivar e Guardar (Gênesis 1:28; 2:15)",
            definicao: "Deus deu ao homem o mandato de 'dominar' sobre a criação (Gênesis 1:28). No entanto, este domínio não é dominação destrutiva, mas cuidado responsável. 'E tomou o Senhor Deus o homem, e o pôs no jardim do Éden para o lavrar e o guardar' (Gênesis 2:15). 'Cultivar' (abad) e 'guardar' (shamar) implicam cuidado, proteção, preservação. Interpretações errôneas do domínio: (1) Exploração ilimitada (justificativa para destruição ambiental). (2) Abandono (não intervir). (3) Adoração da natureza (panteísmo). Interpretação correta (reformada): (a) Domínio como mordomia (stewardship). (b) O homem é administrador, não proprietário. (c) A criação deve ser usada para o bem humano, mas não abusada. (d) A criação deve ser preservada para as futuras gerações. (e) O cuidado da criação é um ato de adoração a Deus. 'O justo cuida da vida dos seus animais' (Provérbios 12:10). 'Pois a terra é do Senhor' (1 Coríndios 10:26).",
            referencias: "Gênesis 1:26-28; Gênesis 2:15; Levítico 25:1-7; Provérbios 12:10; 1 Coríndios 10:26; Colossenses 1:16-17"
        },
        {
            termo: "04. A Queda e a Corrupção da Criação - Romanos 8:20-22",
            definicao: "O pecado de Adão afetou não apenas a humanidade, mas toda a criação. 'Porque a criação ficou sujeita à vaidade, não por sua vontade, mas por causa daquele que a sujeitou' (Romanos 8:20). 'Porque sabemos que toda a criação geme e está com dores de parto até agora' (Romanos 8:22). Consequências da queda na criação: (1) Maldição sobre a terra (Gênesis 3:17-19). (2) Espinhos e cardos (Gênesis 3:18). (3) Fadiga no trabalho (Gênesis 3:19). (4) Desastres naturais (terremotos, tempestades). (5) Extinção de espécies (consequência indireta). (6) Mudança climática (agravada pelo pecado humano). (7) Poluição. (8) Desmatamento. A criação não é má em si (contra o gnosticismo), mas está corrompida pelo pecado. A redenção em Cristo inclui a redenção da criação. 'E a ardente expectação da criatura espera a manifestação dos filhos de Deus' (Romanos 8:19).",
            referencias: "Gênesis 3:17-19; Romanos 5:12; Romanos 8:19-22; 2 Pedro 3:5-7"
        },
        {
            termo: "05. A Redenção da Criação - Romanos 8:19-23; Colossenses 1:20",
            definicao: "A redenção em Cristo não é apenas espiritual, mas também cósmica. 'Porque foi do agrado do Pai que toda a plenitude nele habitasse, e que, havendo por ele feito a paz pelo sangue da sua cruz, por meio dele reconciliasse consigo mesmo todas as coisas, tanto as que estão na terra como as que estão nos céus' (Colossenses 1:19-20). 'Também a mesma criatura será libertada da servidão da corrupção, para a liberdade da glória dos filhos de Deus' (Romanos 8:21). Implicações: (1) A criação será redimida, não aniquilada. (2) A nova criação (novos céus e nova terra) é uma transformação, não uma substituição (2 Pedro 3:10-13). (3) A esperança da redenção da criação motiva o cuidado ambiental presente. (4) O sofrimento da criação (mudança climática, poluição) é um sinal da necessidade de redenção. (5) Os crentes são agentes de redenção na criação (co-criadores com Deus). 'E aquele que estava assentado sobre o trono disse: Eis que faço novas todas as coisas' (Apocalipse 21:5).",
            referencias: "Romanos 8:19-23; 2 Coríndios 5:17; Colossenses 1:19-20; 2 Pedro 3:10-13; Apocalipse 21:1-5"
        },
        {
            termo: "06. A Nova Criação - Novos Céus e Nova Terra (Apocalipse 21-22)",
            definicao: "A consumação da redenção é a nova criação (novos céus e nova terra). 'E vi um novo céu e uma nova terra. Porque já o primeiro céu e a primeira terra passaram' (Apocalipse 21:1). 'E ouvi uma grande voz do céu que dizia: Eis aqui o tabernáculo de Deus com os homens... Deus limpará de seus olhos toda lágrima; e não haverá mais morte, nem pranto, nem clamor, nem dor' (Apocalipse 21:3-4). Características da nova criação: (1) Redimida, não aniquilada (a mesma criação transformada). (2) Sem pecado, morte, maldição. (3) Habitação de Deus com seu povo. (4) Cidade-jardim (Nova Jerusalém). (5) Árvore da vida (Apocalipse 22:2). (6) Rio da água da vida (Apocalipse 22:1). (7) Luz de Deus e do Cordeiro (Apocalipse 21:23). A esperança da nova criação transforma nossa relação com a criação atual: (a) Cuidamos da criação como antecipação da nova criação. (b) Não nos desesperamos com a destruição ambiental. (c) Trabalhamos pela restauração ecológica como sinal do Reino. 'Porque eis que eu crio novos céus e nova terra; e não haverá mais lembrança das coisas passadas' (Isaías 65:17).",
            referencias: "Isaías 65:17-25; 2 Pedro 3:13; Apocalipse 21:1-27; Apocalipse 22:1-5"
        },
        {
            termo: "07. A Crise Ambiental - Mudança Climática, Poluição, Desmatamento",
            definicao: "A crise ambiental (mudança climática, poluição, desmatamento, extinção de espécies) é em grande parte causada pelo pecado humano (ganância, negligência, exploração). 'Destruem a terra' (Apocalipse 11:18). 'A terra pranteia e se murcha' (Isaías 24:4). Evidências da crise: (1) Aquecimento global (emissão de gases de efeito estufa). (2) Derretimento das calotas polares. (3) Aumento do nível do mar. (4) Eventos climáticos extremos (furacões, secas, inundações). (5) Poluição do ar, água, solo. (6) Desmatamento da Amazônia e outras florestas. (7) Extinção de espécies. (8) Escassez de água. (9) Desertificação. (10) Acidificação dos oceanos. A teologia reformada afirma: (a) A crise ambiental é uma consequência do pecado humano (ganância, falta de mordomia). (b) Os cristãos devem liderar o cuidado ambiental (não seguir o mundo). (c) A solução final é a nova criação, mas devemos mitigar os danos agora. (d) A esperança escatológica não é desculpa para negligência (2 Pedro 3:10-13 não é licença para poluir). 'O justo considera a casa do pobre' (Provérbios 29:7) - aplicado à terra. 'Não destrua a árvore' (Deuteronômio 20:19).",
            referencias: "Deuteronômio 20:19; Isaías 24:4-6; Apocalipse 11:18; Romanos 8:22; Colossenses 1:16-17; 2 Pedro 3:10-13"
        },
        {
            termo: "08. A Responsabilidade Cristã - Cuidado Ambiental como Mordomia",
            definicao: "Os cristãos têm a responsabilidade de cuidar da criação como mordomos de Cristo. 'Fazei tudo para glória de Deus' (1 Coríndios 10:31) inclui o cuidado ambiental. Ações práticas para cristãos: (1) Reduzir o consumo de energia (apagar luzes, usar lâmpadas LED, eficiência energética). (2) Reduzir o consumo de água (consertar vazamentos, uso consciente). (3) Reciclar lixo (plástico, papel, vidro, metal). (4) Reduzir o uso de plásticos descartáveis. (5) Plantar árvores (reflorestamento). (6) Usar transporte sustentável (bicicleta, transporte público, carro elétrico). (7) Evitar desperdício de alimentos (João 6:12). (8) Comprar produtos sustentáveis (orgânicos, comércio justo). (9) Apoiar políticas ambientais (votar em candidatos que se importam com o meio ambiente). (10) Educar outros sobre o cuidado ambiental. (11) Envolver a igreja em projetos ambientais (mutirões de limpeza, plantio de árvores). (12) Reduzir o consumo de carne (pecuária é uma das maiores emissoras de gases de efeito estufa). (13) Evitar produtos de empresas que destroem florestas. 'Quanto a mim, eu andaria na minha integridade' (Salmo 26:11). 'Ensina-nos a contar os nossos dias' (Salmo 90:12).",
            referencias: "Gênesis 2:15; Salmo 90:12; João 6:12; 1 Coríndios 10:31; 2 Coríndios 5:17-18; Colossenses 3:23"
        },
        {
            termo: "09. Teologia e Ecologia - Diálogo com o Ambientalismo Secular",
            definicao: "O ambientalismo secular muitas vezes baseia-se em pressupostos ateístas ou panteístas (ex.: Gaia - a Terra como deusa). A teologia cristã oferece uma base melhor para o cuidado ambiental: (1) A criação é obra de Cristo, não do acaso. (2) A criação tem valor intrínseco, não apenas instrumental. (3) O ser humano é mordomo, não dono. (4) A esperança cristã é a nova criação, não a destruição do planeta (como alguns ambientalistas radicais). (5) A redenção inclui a criação. Pontos de diálogo: (a) Concordância: a crise ambiental é real e urgente. (b) Discordância: a solução não é o panteísmo (adorar a natureza) nem o Malthusianismo (redução populacional forçada). (c) Contribuição cristã: motivação (amor a Deus e ao próximo), esperança (nova criação), poder do Espírito (transformação). 'Porque nele foram criadas todas as coisas' (Colossenses 1:16). 'A terra é do Senhor' (1 Coríndios 10:26).",
            referencias: "Salmo 24:1; Romanos 1:18-25; 1 Coríndios 10:26; Colossenses 1:16-17; 1 Timóteo 4:4"
        },
        {
            termo: "10. Espécies em Extinção - Protegendo a Biodiversidade",
            definicao: "A Bíblia mostra que Deus se importa com todas as criaturas. 'Deus... lembra-se deles' (Salmo 136:25). 'Ele dá aos animais o seu sustento' (Salmo 147:9). 'O justo cuida da vida dos seus animais' (Provérbios 12:10). A extinção de espécies é consequência do pecado humano (caça predatória, destruição de habitat, poluição). A teologia reformada afirma: (1) As espécies são criação de Deus e devem ser preservadas. (2) Cada espécie tem valor intrínseco (reflete a criatividade de Deus). (3) A extinção de espécies reduz a glória de Deus manifestada na criação. (4) Os cristãos devem proteger a biodiversidade (áreas de preservação, combate à caça ilegal). (5) A arca de Noé (Gênesis 6-9) é um tipo de preservação das espécies. 'E de todo o animal, de toda a carne, dois de cada espécie, farás entrar na arca' (Gênesis 6:19). 'Louve ao Senhor... animais de toda sorte' (Salmo 148:7,10).",
            referencias: "Gênesis 1:20-25; Gênesis 6:19-20; Gênesis 9:9-10; Salmo 104:24-30; Salmo 147:9; Salmo 148:7-10; Provérbios 12:10; Jó 38:39-41"
        },
        {
            termo: "11. Justiça Ambiental - Os Pobres e a Degradação Ambiental",
            definicao: "A degradação ambiental afeta desproporcionalmente os pobres. (1) Pobres vivem em áreas mais poluídas. (2) Pobres dependem mais de recursos naturais (agricultura, pesca). (3) Pobres têm menos recursos para se adaptar às mudanças climáticas. (4) Pobres sofrem mais com desastres naturais (moradias precárias). A Bíblia ordena a justiça para os pobres. 'Aprendei a fazer bem; procurai o que é justo; ajudai o oprimido' (Isaías 1:17). 'O que oprime ao pobre insulta ao seu Criador' (Provérbios 14:31). A teologia reformada afirma: (a) A justiça ambiental é parte da justiça social. (b) Os cristãos devem defender políticas que protejam os pobres dos danos ambientais. (c) As soluções ambientais não devem onerar excessivamente os pobres. (d) A transição para energias limpas deve ser justa (não aumentar a pobreza). 'Não se faça injustiça no juízo' (Levítico 19:15). 'Pobre e rico se encontram; a todos faz o Senhor' (Provérbios 22:2).",
            referencias: "Levítico 19:15; Isaías 1:17; Provérbios 14:31; Provérbios 22:2; Amós 5:24; Tiago 2:5-6"
        },
        {
            termo: "12. Esperança Ecológica - A Nova Criação e a Ação Presente",
            definicao: "A esperança da nova criação não nos leva a negligenciar a criação atual, mas a cuidar dela como antecipação da redenção final. 'Mas, segundo a sua promessa, nós aguardamos novos céus e nova terra, em que habita a justiça' (2 Pedro 3:13). Porque aguardamos a nova criação: (1) Trabalhamos pela restauração ecológica agora. (2) Não nos desesperamos com a destruição (há esperança). (3) Não idolatramos a criação (a criação não é eterna). (4) Usamos recursos com moderação (não acumulamos tesouros na terra). (5) Plantamos árvores, limpamos rios, reciclamos, reduzimos emissões. (6) Testemunhamos da esperança cristã através do cuidado ambiental. 'Portanto, meus amados irmãos, sede firmes e constantes, sempre abundantes na obra do Senhor' (1 Coríndios 15:58). 'Mas buscai primeiro o reino de Deus e a sua justiça' (Mateus 6:33).",
            referencias: "Mateus 6:33; 1 Coríndios 15:58; 2 Coríndios 5:17; 2 Pedro 3:13; Apocalipse 21:1-5"
        },
        {
            termo: "13. Síntese: Cristo, o Redentor da Criação",
            definicao: "Cristo é o Criador, Sustentador e Redentor da criação. 'Porque nele foram criadas todas as coisas... e ele é antes de todas as coisas, e todas as coisas subsistem por ele' (Colossenses 1:16-17). 'Por meio dele reconciliasse consigo mesmo todas as coisas' (Colossenses 1:20). Resumo da ecologia cristocêntrica: (1) A criação foi criada por Cristo e é boa (Gênesis 1:31). (2) O homem recebeu o mandato de 'cultivar e guardar' (mordomia). (3) A queda corrompeu a criação, mas não a destruiu (Romanos 8:20-22). (4) A redenção em Cristo inclui a redenção da criação (Romanos 8:19-23). (5) A nova criação é a consumação (Apocalipse 21-22). (6) A crise ambiental é consequência do pecado humano. (7) Os cristãos devem liderar o cuidado ambiental como mordomos de Cristo. (8) A justiça ambiental protege os pobres dos danos ecológicos. (9) A esperança na nova criação motiva a ação presente. (10) Cristo é o Rei de toda a criação, incluindo o meio ambiente. 'Louvai ao Senhor desde os céus... louvai-o, sol e lua; louvai-o, todas as estrelas luzentes' (Salmo 148:1,3). 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36). Soli Deo Gloria!",
            referencias: "Romanos 11:36; Colossenses 1:15-20; Romanos 8:19-23; 2 Pedro 3:13; Apocalipse 21-22"
        }
    ]
};