// volume/volume-12.js
window.LIVRO_DATA = {
    nome: "Volume XII",
    dados: [
        {
            termo: "01. Introdução: A Ética Cristocêntrica",
            definicao: "A ética é o estudo do que é moralmente certo e errado, bom e mau, virtuoso e vicioso. A ética cristã reformada é radicalmente cristocêntrica: não se baseia em princípios abstratos (utilitarismo, deontologia), nem em leis sem graça, mas na pessoa e obra de Jesus Cristo. Cristo não é apenas o exemplo moral supremo, mas também o fundamento, o conteúdo e o fim de toda ética. 'Sede meus imitadores, como também eu sou de Cristo' (1 Coríntios 11:1). 'Porque para mim o viver é Cristo' (Filipenses 1:21). A ética cristocêntrica tem várias fontes: (a) Os mandamentos de Cristo (Sermão do Monte, João 13:34-35). (b) A imitação de Cristo (Imitatio Christi). (c) A união com Cristo (unio cum Christo) - os crentes são participante da natureza de Cristo. (d) A lei de Deus (os dez mandamentos) interpretada por Cristo. (e) A obra redentora de Cristo (a cruz como padrão de amor sacrificial). A teologia reformada enfatiza que a ética não é meio de salvação (justificação), mas fruto da salvação (santificação). 'Porque somos feitura sua, criados em Cristo Jesus para as boas obras' (Efésios 2:10).",
            referencias: "Mateus 5-7; João 13:34-35; Romanos 6:1-14; Romanos 12:1-2; 1 Coríntios 11:1; Gálatas 5:22-25; Efésios 2:10; Efésios 5:1-2; Filipenses 1:21; Filipenses 2:5-8; Colossenses 3:1-17; 1 Pedro 2:21; 1 João 2:6"
        },
        {
            termo: "02. O Sermão da Montanha: A Ética do Reino",
            definicao: "O Sermão da Montanha (Mateus 5-7) é a exposição mais completa da ética de Jesus. Ele descreve o caráter (bem-aventuranças), as boas obras (sal da terra, luz do mundo), a justiça superior (cumprimento da lei), a oração (Pai Nosso), a confiança em Deus (não andeis ansiosos) e o julgamento (não julgueis). Características: (1) A ética do Reino: é para os discípulos de Cristo (os que creem). (2) A justiça superior: 'Se a vossa justiça não exceder a dos escribas e fariseus' (Mateus 5:20). Não apenas ações exteriores, mas atitudes interiores (ira, luxúria, perdão). (3) O amor aos inimigos: 'Amai a vossos inimigos, bendizei os que vos maldizem, fazei bem aos que vos odeiam' (Mateus 5:44). (4) A não-resistência ao mal: 'Não resistais ao mal; mas se qualquer te bater na face direita, oferece-lhe também a outra' (Mateus 5:39). (5) A perfeição: 'Sede vós pois perfeitos, como é perfeito o vosso Pai que está nos céus' (Mateus 5:48). A teologia reformada interpreta o Sermão da Montanha como (a) lei para o crente (norma da santificação), não como meio de justificação; (b) impossível de cumprir na carne, mas possível pelo Espírito; (c) aplicável ao crente individual, não diretamente ao Estado (duas esferas).",
            referencias: "Mateus 5:1-48; Mateus 6:1-34; Mateus 7:1-29; Lucas 6:20-49; Romanos 12:14-21; 1 Tessalonicenses 5:15; 1 Pedro 3:9; 1 Pedro 3:13-17"
        },
        {
            termo: "03. O Mandamento do Amor: Amar a Deus e ao Próximo",
            definicao: "Jesus resumiu toda a lei em dois mandamentos: 'Amarás o Senhor teu Deus de todo o teu coração, e de toda a tua alma, e de todo o teu pensamento. Este é o primeiro e grande mandamento. E o segundo, semelhante a este, é: Amarás o teu próximo como a ti mesmo' (Mateus 22:37-39). Na última ceia, Jesus deu um 'mandamento novo': 'Que vos ameis uns aos outros; como eu vos amei a vós, que também vós uns aos outros vos ameis' (João 13:34). O amor de Cristo é o padrão: amor sacrificial (ele deu a vida), amor incondicional (amou-nos sendo ainda pecadores, Romanos 5:8), amor ativo (não apenas palavras, mas ações). A teologia reformada enfatiza que o amor (ágape) é o fruto do Espírito (Gálatas 5:22) e a marca dos verdadeiros discípulos (João 13:35). O amor não anula a justiça (a justiça é expressão do amor), mas a transcende.",
            referencias: "Levítico 19:18; Deuteronômio 6:4-5; Mateus 22:34-40; Marcos 12:28-34; Lucas 10:25-28; João 13:34-35; João 14:15; João 14:21; João 15:9-14; Romanos 5:5; Romanos 5:8; Romanos 13:8-10; 1 Coríntios 13:1-13; Gálatas 5:6; Gálatas 5:22; Efésios 3:17-19; Efésios 5:2; 1 João 3:16-18; 1 João 4:7-12; 1 João 4:19-21"
        },
        {
            termo: "04. Imitação de Cristo (Imitatio Christi)",
            definicao: "A imitação de Cristo (Imitatio Christi) é um tema central da ética cristã. O apóstolo Paulo exorta: 'Sede meus imitadores, como também eu sou de Cristo' (1 Coríntios 11:1). Pedro escreve: 'Porque para isto sois chamados, pois também Cristo padeceu por nós, deixando-nos o exemplo, para que sigais as suas pisadas' (1 Pedro 2:21). O que significa imitar Cristo? (1) Humildade: 'Tende em vós o mesmo sentimento que houve também em Cristo Jesus' (Filipenses 2:5-8). (2) Obediência: 'Ele foi obediente até à morte' (Filipenses 2:8). (3) Amor sacrificial: 'Como Cristo amou a igreja e a si mesmo se entregou por ela' (Efésios 5:25). (4) Perdão: 'Perdoai-vos uns aos outros, como também Deus vos perdoou em Cristo' (Efésios 4:32). (5) Santidade: 'Aquele que diz que está nele, também deve andar como ele andou' (1 João 2:6). A teologia reformada enfatiza que a imitação não é a causa da salvação (justificação), mas o fruto (santificação). Imitamos Cristo porque já somos salvos, não para sermos salvos.",
            referencias: "Mateus 11:29; João 13:14-15; Romanos 15:3; 1 Coríntios 4:16; 1 Coríntios 11:1; Efésios 4:32; Efésios 5:1-2; Filipenses 2:5-8; Colossenses 3:12-14; 1 Tessalonicenses 1:6; 2 Tessalonicenses 3:7-9; Hebreus 12:1-4; 1 Pedro 2:21-25; 1 João 2:6; 1 João 3:16"
        },
        {
            termo: "05. Cristo e a Lei: Cumprimento e Liberdade",
            definicao: "Qual é a relação entre Cristo e a lei moral (os dez mandamentos)? Jesus declarou: 'Não cuideis que vim destruir a lei ou os profetas; não vim destruir, mas cumprir' (Mateus 5:17). 'Até que o céu e a terra passem, nem um jota ou um til se omitirá da lei, sem que tudo seja cumprido' (Mateus 5:18). Significados: (1) Cristo cumpriu a lei perfeitamente (obediência ativa), merecendo a vida eterna para os eleitos. (2) Cristo sofreu a penalidade da lei (obediência passiva), satisfazendo a justiça divina. (3) Cristo libertou os crentes da maldição da lei (Gálatas 3:13) e da obrigação cerimonial (circuncisão, sacrifícios). (4) A lei moral (dez mandamentos) permanece como regra de vida (norma da santificação) para o crente, mas não como meio de justificação. 'Não estamos debaixo da lei, mas debaixo da graça' (Romanos 6:14) significa que a lei não nos condena (justificação), mas ainda nos guia (santificação). A teologia reformada (Calvino, Westminster) distingue três usos da lei: (1) Usus politicus (civil): refrear o pecado na sociedade. (2) Usus elenchticus (pedagógico): convencer do pecado e levar a Cristo (Gálatas 3:24). (3) Usus didacticus (normativo): guiar o crente na santificação.",
            referencias: "Êxodo 20:1-17; Deuteronômio 5:6-21; Salmo 19:7-11; Salmo 119; Mateus 5:17-20; Romanos 3:19-20; Romanos 3:31; Romanos 6:14-15; Romanos 7:1-25; Romanos 8:1-4; Romanos 13:8-10; Gálatas 3:10-14; Gálatas 3:24; Gálatas 5:14; Efésios 2:15; Colossenses 2:14; 1 Timóteo 1:8-11; Tiago 1:25; Tiago 2:8-12"
        },
        {
            termo: "06. Cristo e a Bioética (Início e Fim da Vida)",
            definicao: "A bioética trata das questões éticas relacionadas à vida humana: aborto, eutanásia, reprodução assistida, clonagem, engenharia genética, etc. A cosmovisão cristocêntrica oferece princípios: (1) A vida humana é sagrada porque o homem foi criado à imagem de Deus (imago Dei, Gênesis 1:26-27) e Cristo morreu por nós (Romanos 5:8). (2) O aborto: a vida começa na concepção (Salmo 139:13-16; Jeremias 1:5; Lucas 1:41-44). O aborto é a morte de um ser humano inocente, violando o sexto mandamento (Êxodo 20:13). (3) A eutanásia: a morte deve ser aceita, não provocada ativamente. O sofrimento pode ser aliviado (cuidados paliativos), mas a morte não deve ser antecipada. 'O Senhor o dá, e o Senhor o tira' (Jó 1:21). (4) Reprodução assistida: a fertilização in vitro (FIV) é permitida se envolver apenas o casal (espermatozoide e óvulo do marido e da esposa), sem destruição de embriões (embriões congelados são vidas humanas). (5) Clonagem: clonagem reprodutiva é proibida (viola a dignidade humana, cria um 'gêmeo' do doador). (6) Engenharia genética (CRISPR): permitida para curar doenças, mas não para 'design de bebês' (eugenia). A teologia reformada afirma que toda vida humana é preciosa porque Cristo morreu por todos.",
            referencias: "Gênesis 1:26-27; Êxodo 20:13; Jó 1:21; Jó 14:5; Salmo 139:13-16; Jeremias 1:5; Lucas 1:41-44; Atos 17:26-28; Romanos 5:8; 1 Coríntios 6:19-20; 1 Coríntios 15:26; 2 Coríntios 5:1-10; Efésios 2:10; 1 Pedro 1:18-19"
        },
        {
            termo: "07. Cristo e a Sexualidade (Casamento, Família, Pureza)",
            definicao: "A ética cristã da sexualidade é baseada na criação (Gênesis 1-2) e no ensino de Jesus (Mateus 19:1-12). Princípios: (1) A sexualidade é um dom de Deus (não é má). (2) A expressão sexual é ordenada para o casamento (heterossexual, monogâmico, vitalício). 'Portanto deixará o homem seu pai e sua mãe, e unir-se-á a sua mulher, e serão dois numa carne' (Gênesis 2:24; Mateus 19:5). (3) O divórcio: Jesus permitiu apenas por causa de fornicação (Mateus 19:9) e Paulo adicionou abandono por incrédulo (1 Coríntios 7:15). O divórcio é uma concessão por causa da dureza do coração (Mateus 19:8). (4) Homossexualidade: a Bíblia considera as práticas homossexuais como pecado (Levítico 18:22; 20:13; Romanos 1:26-27; 1 Coríntios 6:9-10; 1 Timóteo 1:9-10). A teologia reformada afirma que a pessoa com atração pelo mesmo sexo deve ser tratada com compaixão, mas a prática homossexual é pecado. (5) Pureza sexual: 'Fugi da prostituição' (1 Coríntios 6:18); 'Não toqueis em mulher durante a menstruação' (Levítico 18:19); 'Não vos enganeis: nem os devassos, nem os idólatras, nem os adúlteros, nem os efeminados, nem os sodomitas... herdarão o reino de Deus' (1 Coríntios 6:9-10). (6) Casamento como tipo de Cristo e a igreja: 'Este mistério é grande; digo-o, porém, a respeito de Cristo e da igreja' (Efésios 5:32). O casamento cristão deve refletir o amor sacrificial de Cristo pela igreja.",
            referencias: "Gênesis 1:26-28; Gênesis 2:18-25; Levítico 18:22; Levítico 20:13; Deuteronômio 22:5; Mateus 5:27-32; Mateus 19:1-12; Romanos 1:18-32; 1 Coríntios 5:1-13; 1 Coríntios 6:9-20; 1 Coríntios 7:1-40; Gálatas 5:19-21; Efésios 5:22-33; 1 Timóteo 1:9-11; Hebreus 13:4; 1 Pedro 3:1-7"
        },
        {
            termo: "08. Cristo e a Justiça Social (Pobres, Marginalizados, Imigrantes)",
            definicao: "A Bíblia repetidamente exorta a igreja a cuidar dos pobres, dos órfãos, das viúvas, dos estrangeiros e dos marginalizados. Jesus exemplificou isso em seu ministério: 'O Espírito do Senhor é sobre mim... ungiu-me para evangelizar os pobres' (Lucas 4:18-19). Jesus comeu com publicanos e pecadores (Mateus 9:10-13), tocou leprosos (Mateus 8:2-3), defendeu a mulher adúltera (João 8:1-11). Princípios éticos: (1) Opção preferencial pelos pobres (não exclusiva, mas preferencial). 'Bem-aventurados vós, os pobres, porque vosso é o reino de Deus' (Lucas 6:20). (2) Justiça para os marginalizados: 'Aprendei a fazer bem; procurai o que é justo; ajudai o oprimido; fazei justiça ao órfão; tratai da causa das viúvas' (Isaías 1:17). (3) Amor aos imigrantes: 'Amarás o estrangeiro como a ti mesmo' (Levítico 19:34). (4) Ação social: 'A fé, se não tiver obras, é morta em si mesma' (Tiago 2:17). A teologia reformada (especialmente na tradição da 'missão integral', Lausanne 1974) afirma que a igreja deve pregar o evangelho (evangelismo) e cuidar dos pobres (ação social). 'A fé sem obras é morta' (Tiago 2:26).",
            referencias: "Levítico 19:9-10; Levítico 19:33-34; Deuteronômio 15:7-11; Salmo 68:5-6; Salmo 72:1-4; Salmo 82:3-4; Isaías 1:17; Isaías 58:6-7; Jeremias 22:3; Amós 5:24; Miqueias 6:8; Zacarias 7:9-10; Mateus 25:31-46; Lucas 4:18-19; Lucas 6:20-23; Lucas 14:12-14; Atos 6:1-7; Gálatas 2:10; Tiago 1:27; Tiago 2:14-26"
        },
        {
            termo: "09. Cristo e a Ética Política (Estado, Resistência, Não-Violência)",
            definicao: "Qual é a relação entre o cristão e o Estado? Jesus ensinou: 'Dai, pois, a César o que é de César, e a Deus o que é de Deus' (Mateus 22:21). Paulo exortou: 'Toda alma esteja sujeita às autoridades superiores' (Romanos 13:1). Pedro acrescentou: 'Antes importa obedecer a Deus do que aos homens' (Atos 5:29). Princípios: (1) O Estado é ordenado por Deus (Romanos 13:1-7) para punir o mal e promover o bem. (2) O cristão deve obedecer ao Estado, exceto quando o Estado ordena algo contra Deus (obediência civil). (3) Resistência: quando o Estado se torna tirânico (ex.: nazismo), os cristãos podem resistir (Bonhoeffer). (4) Não-violência: Jesus ensinou a não-resistência ao mal (Mateus 5:39), mas isso se aplica ao crente individual, não necessariamente ao Estado (que tem a espada, Romanos 13:4). (5) Guerra justa: a tradição reformada (Calvino, Turretin) defende a guerra justa em defesa própria (contra agressão), mas com restrições (último recurso, autoridade legítima, proporcionalidade, discriminação). (6) Separação igreja-Estado: Cristo é o rei da igreja, mas o Estado tem sua própria esfera (doutrina das duas esferas, Kuyper). A teologia reformada rejeita tanto o teocracia (Estado controla igreja) quanto o secularismo radical (igreja excluída da esfera pública).",
            referencias: "Êxodo 20:13; Deuteronômio 20:1-20; 2 Samuel 11:1-27; Salmo 2; Salmo 72; Isaías 9:6-7; Mateus 5:38-48; Mateus 22:15-22; Atos 4:18-20; Atos 5:29; Romanos 12:18-21; Romanos 13:1-7; 1 Timóteo 2:1-4; Tito 3:1; 1 Pedro 2:13-17; Apocalipse 13:1-18"
        },
        {
            termo: "10. Cristo e a Ética Econômica (Riqueza, Pobreza, Mordomia)",
            definicao: "O que a Bíblia ensina sobre riqueza, pobreza, trabalho e mordomia? Jesus ensinou: 'Não ajunteis tesouros na terra' (Mateus 6:19). 'Não podeis servir a Deus e a Mamom' (Mateus 6:24). Paulo ensinou: 'O amor ao dinheiro é a raiz de toda espécie de males' (1 Timóteo 6:10). Princípios: (1) A riqueza em si não é pecado (Abraão, Jó, José de Arimateia eram ricos), mas o amor ao dinheiro (avareza) é pecado. (2) Os ricos devem ser generosos: 'Manda aos ricos deste mundo... que pratiquem o bem, que sejam ricos em boas obras, generosos em dar' (1 Timóteo 6:17-18). (3) A pobreza não é virtude em si (a Bíblia condena a preguiça, Provérbios 6:6-11), mas Deus tem compaixão dos pobres. (4) Mordomia: tudo o que temos pertence a Deus (Salmo 24:1). Somos mordomos (administradores) dos recursos de Deus. (5) Trabalho: o trabalho é ordenado por Deus (Gênesis 2:15; Efésios 4:28). O ócio é pecado (2 Tessalonicenses 3:10). (6) Dízimo e ofertas: 'Cada um dê segundo o propósito do seu coração' (2 Coríntios 9:7). A teologia reformada (Kuyper, Bavinck) enfatiza a 'mordomia cristã' (stewardship): devemos usar nossos recursos para glória de Deus e para ajudar os necessitados.",
            referencias: "Deuteronômio 8:18; Provérbios 6:6-11; Provérbios 11:24-25; Provérbios 22:7; Eclesiastes 5:10; Malaquias 3:8-10; Mateus 6:19-24; Mateus 19:16-30; Lucas 12:13-21; Lucas 16:1-13; Atos 2:44-45; Atos 4:32-37; 2 Coríntios 8:1-9; 2 Coríntios 9:1-15; Efésios 4:28; 1 Timóteo 6:6-10; 1 Timóteo 6:17-19; Tiago 5:1-6"
        },
        {
            termo: "11. Cristo e a Ética Ambiental (Cuidado da Criação)",
            definicao: "O que a Bíblia ensina sobre o cuidado da criação (meio ambiente)? Deus criou o mundo e o declarou 'muito bom' (Gênesis 1:31). Deus deu ao homem domínio sobre a criação (Gênesis 1:28), mas não dominação destrutiva. O homem deve 'cultivar e guardar' o jardim (Gênesis 2:15). Princípios: (1) A criação é de Deus (Salmo 24:1). (2) O homem é mordomo (administrador), não proprietário. (3) O pecado afetou a criação (Gênesis 3:17-19; Romanos 8:20-22). (4) A criação geme aguardando a redenção (Romanos 8:19-22). (5) Os crentes devem cuidar da criação (não poluir, não desperdiçar, preservar a biodiversidade). (6) A esperança cristã é a nova criação (Apocalipse 21-22), não a destruição do planeta. A teologia reformada (especialmente na tradição de Kuyper, Bavinck, Schaeffer) enfatiza a 'mordomia ambiental' (environmental stewardship). A igreja deve liderar o cuidado da criação (não apenas o governo).",
            referencias: "Gênesis 1:26-31; Gênesis 2:15; Êxodo 23:10-11; Levítico 25:1-7; Salmo 24:1-2; Salmo 104:1-35; Salmo 148:1-14; Romanos 8:19-22; Colossenses 1:15-20; Hebreus 1:2-3; 2 Pedro 3:10-13; Apocalipse 11:18; Apocalipse 21:1-5"
        },
        {
            termo: "12. Cristo e a Ética da Virtude (As Virtudes de Cristo)",
            definicao: "A ética da virtude (virtue ethics) foca no caráter do agente moral, não apenas em ações ou deveres. A Bíblia apresenta Cristo como o modelo de virtude (exemplo perfeito). As virtudes de Cristo incluem: (1) Humildade: 'Tomai sobre vós o meu jugo, e aprendei de mim, que sou manso e humilde de coração' (Mateus 11:29). (2) Amor sacrificial: 'Como Cristo amou a igreja e a si mesmo se entregou por ela' (Efésios 5:25). (3) Paciência: 'Suportou a cruz' (Hebreus 12:2). (4) Perdão: 'Pai, perdoa-lhes, porque não sabem o que fazem' (Lucas 23:34). (5) Obediência: 'Ele foi obediente até à morte' (Filipenses 2:8). (6) Mansidão: 'Não bradará, nem levantará a voz' (Isaías 42:2; Mateus 12:19). (7) Justiça: 'Amaste a justiça e odiaste a iniquidade' (Hebreus 1:9). (8) Fidelidade: 'Fiel e verdadeiro' (Apocalipse 19:11). (9) Coragem: Jesus enfrentou a cruz sem recuar (Lucas 9:51). (10) Esperança: 'Pelo gozo que lhe estava proposto, suportou a cruz' (Hebreus 12:2). A teologia reformada enfatiza que as virtudes são fruto do Espírito (Gálatas 5:22-23) e são cultivadas pela união com Cristo (unio cum Christo).",
            referencias: "Isaías 11:2-5; Isaías 42:1-4; Zacarias 9:9; Mateus 5:3-12; Mateus 11:29; Mateus 21:5; João 13:1-17; Romanos 5:3-5; 1 Coríntios 13:1-13; Gálatas 5:22-23; Efésios 4:1-3; Filipenses 2:5-8; Colossenses 3:12-14; 1 Timóteo 6:11; 2 Timóteo 2:22; 2 Pedro 1:5-7"
        },
        {
            termo: "13. Síntese da Ética Cristocêntrica: Viver para Cristo",
            definicao: "A ética cristã reformada pode ser resumida como 'viver para Cristo' (Philippians 1:21: 'para mim o viver é Cristo'). Isto significa: (1) Fé em Cristo: a justificação é pela fé, não pelas obras (Efésios 2:8-9). (2) União com Cristo: os crentes estão 'em Cristo' (Romanos 8:1). (3) Imitação de Cristo: andar como ele andou (1 João 2:6). (4) Obediência a Cristo: 'Se me amais, guardai os meus mandamentos' (João 14:15). (5) Amor a Cristo: 'Aquele que não ama, não conhece a Deus' (1 João 4:8). (6) Serviço a Cristo: 'Em que me servistes' (Mateus 25:40). (7) Glorificar a Cristo: 'Fazei tudo para glória de Deus' (1 Coríntios 10:31). (8) Esperar por Cristo: 'Aguardando a bem-aventurada esperança e o aparecimento da glória do grande Deus e nosso Salvador Jesus Cristo' (Tito 2:13). A ética cristocêntrica não é legalismo (obras para ganhar salvação), nem antinomianismo (negar a lei), mas 'fé que opera por amor' (Gálatas 5:6). 'Porque o amor de Cristo nos constrange' (2 Coríntios 5:14).",
            referencias: "João 14:15; João 14:21; Romanos 8:1; Romanos 12:1-2; 1 Coríntios 10:31; 2 Coríntios 5:14-15; Gálatas 2:20; Gálatas 5:6; Efésios 2:8-10; Filipenses 1:21; Filipenses 3:7-14; Colossenses 3:1-4; Tito 2:11-14; 1 João 2:6; 1 João 3:16-18; 1 João 4:19"
        }
    ]
};