// volume/volume-43.js
window.LIVRO_DATA = {
    nome: "Volume XLIII",
    dados: [
        {
            termo: "01. Introdução: A Quaresma como Preparação para a Páscoa",
            definicao: "A Quaresma (do latim quadragesima - 'quadragésimo') é o período de 40 dias (excluindo os domingos) que antecede a Páscoa, começando na Quarta-feira de Cinzas e terminando no Sábado Santo. É um tempo de arrependimento, jejum, oração e meditação na paixão de Cristo. A teologia reformada tem uma relação ambivalente com a Quaresma: (a) Valor: É um tempo para focar no sofrimento de Cristo e preparar o coração para a Páscoa. (b) Risco: Pode levar ao legalismo (obras para ganhar mérito) ou ao ritualismo vazio. A teologia reformada enfatiza que a Quaresma não é um meio de salvação (justificação), mas uma disciplina espiritual para crescimento na santificação. 'Arrependei-vos, pois, e convertei-vos, para que sejam apagados os vossos pecados' (Atos 3:19). Este volume oferece meditações diárias para os 40 dias da Quaresma (incluindo a Semana Santa), focando na pessoa e obra de Jesus Cristo. 'Porque para mim o viver é Cristo, e o morrer é ganho' (Filipenses 1:21).",
            referencias: "Joel 2:12-13; Mateus 4:1-11; Atos 3:19; Romanos 12:1-2; 1 Coríntios 11:23-26; 2 Coríntios 5:14-15; Gálatas 2:20; Filipenses 1:21; 1 Pedro 2:21-25"
        },
        {
            termo: "02. Quarta-feira de Cinzas - Pó Tu és, e ao Pó Tornarás",
            definicao: "A Quarta-feira de Cinzas marca o início da Quaresma. As cinzas (feitas dos ramos do Domingo de Ramos do ano anterior) são impostas na testa dos fiéis, com as palavras: 'Lembra-te que és pó e ao pó voltarás' (Gênesis 3:19). Meditação: 'Com o suor do teu rosto comerás o teu pão, até que te tornes à terra; porque dela foste tomado, porquanto és pó e ao pó tornarás' (Gênesis 3:19). O pecado trouxe a morte (Romanos 5:12; 6:23). Mas Cristo morreu para nos dar vida eterna. 'Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna' (João 3:16). Oração: Senhor Jesus, lembra-me da minha mortalidade, mas também da tua ressurreição. Arrependo-me dos meus pecados e confio em ti para a vida eterna. Amém.",
            referencias: "Gênesis 3:19; Jó 34:15; Salmo 90:3; Salmo 103:14-16; Eclesiastes 3:20; Romanos 5:12; Romanos 6:23; João 3:16"
        },
        {
            termo: "03. Semana 1 - A Tentação de Jesus no Deserto (Mateus 4:1-11)",
            definicao: "Meditação para a primeira semana da Quaresma: A tentação de Jesus no deserto. Texto: 'Então foi conduzido Jesus pelo Espírito ao deserto, para ser tentado pelo diabo. E, tendo jejuado quarenta dias e quarenta noites, depois teve fome' (Mateus 4:1-2). As três tentações: (1) Transformar pedras em pão (satisfação física) - Jesus responde: 'Nem só de pão viverá o homem, mas de toda a palavra que sai da boca de Deus' (Deuteronômio 8:3). (2) Lançar-se do pináculo do templo (testar a Deus) - Jesus responde: 'Não tentarás o Senhor teu Deus' (Deuteronômio 6:16). (3) Adorar o diabo em troca de todos os reinos do mundo - Jesus responde: 'Ao Senhor teu Deus adorarás, e só a ele servirás' (Deuteronômio 6:13). Aplicação: (a) Jesus foi tentado como nós, mas sem pecado (Hebreus 4:15). (b) Jesus usou a Palavra de Deus para vencer o diabo. (c) Nós também podemos vencer a tentação pela Palavra de Deus e pelo Espírito. Oração: Senhor Jesus, tu venceste a tentação por nós. Dá-me força para resistir ao diabo e viver pela tua Palavra. Amém.",
            referencias: "Deuteronômio 6:13; Deuteronômio 6:16; Deuteronômio 8:3; Salmo 119:11; Mateus 4:1-11; Marcos 1:12-13; Lucas 4:1-13; Hebreus 2:18; Hebreus 4:15; 1 Coríntios 10:13"
        },
        {
            termo: "04. Semana 2 - A Transfiguração de Jesus (Mateus 17:1-8)",
            definicao: "Meditação para a segunda semana da Quaresma: A transfiguração de Jesus. Texto: 'Seis dias depois, tomou Jesus consigo Pedro, Tiago e João, seu irmão, e os levou em particular a um alto monte. E foi transfigurado diante deles; o seu rosto resplandecia como o sol, e as suas vestes se tornaram brancas como a luz' (Mateus 17:1-2). Moisés e Elias apareceram (representando a Lei e os Profetas), falando da partida de Jesus (Lucas 9:31). A voz do Pai: 'Este é o meu Filho amado, em quem me comprazo; escutai-o' (Mateus 17:5). Significados: (1) A transfiguração revela a glória divina de Cristo (que foi ocultada na encarnação). (2) Moisés e Elias testemunham que Jesus é o cumprimento da Lei e dos Profetas. (3) O Pai confirma a filiação de Jesus. (4) A transfiguração aponta para a ressurreição e a glória futura dos crentes (2 Pedro 1:16-18). Aplicação: (a) Jesus é o Filho amado de Deus - ouçamos sua voz. (b) A glória de Jesus será vista por todos na segunda vinda. (c) Somos transformados à imagem de Cristo (2 Coríntios 3:18). Oração: Senhor Jesus, revela a tua glória em minha vida. Transforma-me à tua imagem. Amém.",
            referencias: "Salmo 2:7; Daniel 7:13-14; Mateus 17:1-8; Marcos 9:2-8; Lucas 9:28-36; 2 Pedro 1:16-18; 2 Coríntios 3:18; 1 João 3:2"
        },
        {
            termo: "05. Semana 3 - A Ressurreição de Lázaro (João 11:1-44)",
            definicao: "Meditação para a terceira semana da Quaresma: A ressurreição de Lázaro. Texto: 'Eu sou a ressurreição e a vida; quem crê em mim, ainda que esteja morto, viverá; e todo aquele que vive e crê em mim nunca morrerá' (João 11:25-26). Significados: (1) Jesus chora com os que choram (João 11:35 - 'Jesus chorou'). (2) Jesus tem poder sobre a morte. (3) A ressurreição de Lázaro é um sinal (semeion) que aponta para a ressurreição de Cristo (e para a nossa). (4) A fé em Jesus é a chave para a vida eterna. Aplicação: (a) Jesus se compadece do nosso sofrimento. (b) A morte não tem a última palavra; Cristo venceu a morte. (c) Creia em Jesus e viverá eternamente. Oração: Senhor Jesus, tu és a ressurreição e a vida. Ajuda-me a crer em ti e a ter esperança mesmo na morte. Amém.",
            referencias: "Jó 19:25-27; Salmo 23:4; Isaías 25:8; Oséias 13:14; João 11:1-44; Romanos 6:23; 1 Coríntios 15:20-23; 1 Coríntios 15:54-57"
        },
        {
            termo: "06. Semana 4 - A Unção em Betânia (Mateus 26:6-13; João 12:1-8)",
            definicao: "Meditação para a quarta semana da Quaresma: A unção de Jesus em Betânia. Texto: 'Maria, tomando um vaso de unguento de nardo puro, de muito preço, ungiu os pés de Jesus e enxugou-os com os seus cabelos' (João 12:3). Significados: (1) Maria unge Jesus para a sua morte (preparação para o sepultamento). (2) O ato de adoração extravagante de Maria (unguento de muito preço). (3) A crítica de Judas (falso discípulo) - preocupação com dinheiro, não com Jesus. (4) Jesus defende Maria: 'Onde for pregado este evangelho, será também contado o que ela fez' (Mateus 26:13). Aplicação: (a) Adorar a Jesus com extravagância e amor. (b) Não criticar quem adora a Jesus de forma diferente. (c) Tudo o que temos é para a glória de Cristo. Oração: Senhor Jesus, ensina-me a adorar-te com todo o meu coração, como Maria. Que tudo o que eu faça seja para a tua glória. Amém.",
            referencias: "Cânticos 1:12; Mateus 26:6-13; Marcos 14:3-9; João 12:1-8; 2 Coríntios 9:7; Filipenses 3:8"
        },
        {
            termo: "07. Semana 5 - A Oração no Getsêmani (Mateus 26:36-46)",
            definicao: "Meditação para a quinta semana da Quaresma: A oração de Jesus no Getsêmani. Texto: 'Então foi com eles a um lugar chamado Getsêmani... começou a entristecer-se e a angustiar-se... caiu sobre o seu rosto, orando e dizendo: Pai meu, se é possível, passa de mim este cálice; todavia, não seja como eu quero, mas como tu queres' (Mateus 26:36-39). Significados: (1) A agonia de Cristo ('triste até a morte'). (2) O 'cálice' da ira de Deus (Isaías 51:17; Jeremias 25:15; Apocalipse 14:10). (3) A submissão à vontade do Pai ('não seja como eu quero, mas como tu queres'). (4) A fraqueza dos discípulos (não vigiaram). (5) A perseverança de Jesus (orou três vezes). Aplicação: (a) Jesus sofreu angústia por nós. (b) Devemos nos submeter à vontade de Deus, mesmo quando é difícil. (c) Vigiai e orai, para não cair em tentação. Oração: Senhor Jesus, tu sofrestes angústia por mim. Ajuda-me a submeter-me à vontade do Pai, assim como tu te submeteste. Amém.",
            referencias: "Salmo 22:1-2; Salmo 69:1-3; Isaías 53:3; Isaías 53:10; Mateus 26:36-46; Marcos 14:32-42; Lucas 22:39-46; João 18:1; Hebreus 5:7-8"
        },
        {
            termo: "08. Domingo de Ramos - A Entrada Triunfal (Mateus 21:1-11)",
            definicao: "O Domingo de Ramos celebra a entrada triunfal de Jesus em Jerusalém. Texto: 'E a maior parte da multidão estendia as suas vestes pelo caminho, e outros cortavam ramos das árvores e os espalhavam pelo caminho. E a multidão, que ia adiante e que seguia, clamava, dizendo: Hosana ao Filho de Davi; bendito o que vem em nome do Senhor. Hosana nas alturas!' (Mateus 21:8-9). Significados: (1) Jesus entra como Rei humilde, montado em um jumento (Zacarias 9:9). (2) A multidão O aclama como Messias ('Filho de Davi', 'Hosana'). (3) A mesma multidão O crucificará na sexta-feira (contraste). (4) Os ramos de palmeira simbolizam vitória e alegria. Aplicação: (a) Jesus é o Rei humilde que veio para servir. (b) Devemos aclamar Jesus como Rei de nossas vidas. (c) A mesma multidão que O aclamou O rejeitou - examine seu coração. Oração: Senhor Jesus, tu és o Rei dos reis. Hosana nas alturas! Que eu te aclame com alegria e te siga com fidelidade. Amém.",
            referencias: "Zacarias 9:9; Mateus 21:1-11; Marcos 11:1-11; Lucas 19:28-44; João 12:12-19; Apocalipse 7:9-10; Apocalipse 19:16"
        },
        {
            termo: "09. Segunda-feira Santa - A Purificação do Templo (Mateus 21:12-17)",
            definicao: "Meditação para a Segunda-feira Santa: A purificação do templo. Texto: 'E entrou Jesus no templo de Deus, e expulsou todos os que vendiam e compravam no templo, e derrubou as mesas dos cambistas e as cadeiras dos que vendiam pombas; e disse-lhes: Está escrito: A minha casa será chamada casa de oração; mas vós a tendes convertido em covil de ladrões' (Mateus 21:12-13). Significados: (1) O zelo de Jesus pela casa de Deus (Salmo 69:9). (2) A corrupção religiosa (comércio no templo). (3) O templo deve ser casa de oração para todas as nações (Isaías 56:7). (4) Jesus tem autoridade sobre o templo (ele é o verdadeiro templo, João 2:19-21). Aplicação: (a) Nosso corpo é templo do Espírito Santo (1 Coríntios 6:19-20). (b) Devemos purificar nosso coração de toda impureza. (c) Jesus purifica seu povo. Oração: Senhor Jesus, purifica o teu templo - o meu coração. Expulsa tudo o que é contrário à tua vontade. Amém.",
            referencias: "Isaías 56:7; Jeremias 7:11; Salmo 69:9; Mateus 21:12-17; Marcos 11:15-19; Lucas 19:45-48; João 2:13-22; 1 Coríntios 6:19-20"
        },
        {
            termo: "10. Terça-feira Santa - O Discurso Escatológico (Mateus 24-25)",
            definicao: "Meditação para a Terça-feira Santa: O discurso escatológico de Jesus no Monte das Oliveiras (Mateus 24-25; Marcos 13; Lucas 21). Texto: 'Porque se levantará nação contra nação, e reino contra reino, e haverá fomes, e pestes, e terremotos em vários lugares. Mas todas estas coisas são o princípio das dores' (Mateus 24:7-8). Parábolas: (a) A figueira (Mateus 24:32-35). (b) O servo fiel e o mau servo (Mateus 24:45-51). (c) As dez virgens (Mateus 25:1-13). (d) Os talentos (Mateus 25:14-30). (e) O juízo das nações (Mateus 25:31-46). Significados: (1) A segunda vinda de Cristo é certa, mas a data é desconhecida (Mateus 24:36). (2) Devemos estar vigilantes e preparados. (3) Servir a Cristo é investir os talentos que Ele nos deu. (4) O amor ao próximo é evidência do amor a Cristo. Aplicação: (a) Viva cada dia preparado para a volta de Cristo. (b) Use seus dons para a glória de Deus. (c) Ame o próximo como a si mesmo. Oração: Senhor Jesus, ajuda-me a viver vigilante, esperando a tua volta. Que eu use os meus talentos para a tua glória. Amém.",
            referencias: "Daniel 12:1-4; Zacarias 14:1-5; Mateus 24-25; Marcos 13; Lucas 21; 1 Tessalonicenses 4:13-18; 2 Pedro 3:10-13; Apocalipse 1:7"
        },
        {
            termo: "11. Quarta-feira Santa - A Traição de Judas (Mateus 26:14-16)",
            definicao: "Meditação para a Quarta-feira Santa: A traição de Judas. Texto: 'Então um dos doze, chamado Judas Iscariotes, foi ter com os príncipes dos sacerdotes, e disse: Que quereis dar-me, e eu vo-lo entregarei? E eles lhe pesaram trinta moedas de prata' (Mateus 26:14-15). Significados: (1) A traição por um amigo íntimo (Salmo 41:9). (2) Trinta moedas de prata (Zacarias 11:12-13). (3) O amor ao dinheiro é a raiz do mal (1 Timóteo 6:10). (4) A liberdade de escolha de Judas (responsabilidade humana) e a soberania de Deus (Atos 2:23). Aplicação: (a) Examine seu coração: há alguma 'traição' a Cristo? (b) O amor ao dinheiro pode levar à ruína espiritual. (c) Arrependa-se enquanto há tempo. Oração: Senhor Jesus, examina o meu coração. Liberta-me do amor ao dinheiro e de qualquer traição. Que eu seja fiel a ti até o fim. Amém.",
            referencias: "Salmo 41:9; Salmo 55:12-14; Zacarias 11:12-13; Mateus 26:14-16; Mateus 27:3-10; Marcos 14:10-11; Lucas 22:1-6; João 13:2; João 13:27; 1 Timóteo 6:10"
        },
        {
            termo: "12. Quinta-feira Santa (Cinco Meditações)",
            definicao: "A Quinta-feira Santa (também chamada Quinta-feira de Endoenças) celebra a Última Ceia de Jesus com seus discípulos. Cinco meditações: (1) A Ceia do Senhor (Mateus 26:17-30): Jesus institui a Ceia do Senhor (Eucaristia). 'Isto é o meu corpo... este é o meu sangue... fazei isto em memória de mim' (Lucas 22:19-20). (2) O Lava-pés (João 13:1-17): Jesus lava os pés dos discípulos como exemplo de humildade e serviço. 'Se eu, Senhor e Mestre, vos lavei os pés, também vós deveis lavar os pés uns dos outros' (João 13:14). (3) O Mandamento Novo (João 13:34-35): 'Que vos ameis uns aos outros, como eu vos amei a vós.' (4) A Oração Sacerdotal (João 17:1-26): Jesus ora por si mesmo, pelos discípulos e por todos os crentes. (5) A traição de Judas (João 13:21-30): Jesus anuncia que um dos doze o trairá. Aplicação: (a) Participe da Ceia do Senhor com reverência e fé. (b) Sirva os outros com humildade, como Jesus serviu. (c) Ame os irmãos como Cristo amou. Oração: Senhor Jesus, obrigado pela Ceia, pelo exemplo de serviço e pelo mandamento do amor. Ajuda-me a amar como tu amaste. Amém.",
            referencias: "Êxodo 12:1-28; Salmo 113-118; Mateus 26:17-30; Marcos 14:12-26; Lucas 22:7-23; João 13-17; 1 Coríntios 11:23-26"
        },
        {
            termo: "13. Sexta-feira Santa (Cinco Meditações)",
            definicao: "A Sexta-feira Santa celebra a crucificação e morte de Jesus. Cinco meditações: (1) O Julgamento (Mateus 27:11-26; Lucas 23:1-25; João 18:28-19:16): Jesus é condenado por Pilatos, apesar de sua inocência. 'Nenhuma culpa acho neste homem' (Lucas 23:4). (2) A Crucificação (Mateus 27:27-44; Marcos 15:16-32; Lucas 23:26-43; João 19:16-27): Jesus é crucificado entre dois ladrões. 'Pai, perdoa-lhes, porque não sabem o que fazem' (Lucas 23:34). (3) As Sete Palavras na Cruz: (a) 'Pai, perdoa-lhes' (Lucas 23:34). (b) 'Hoje estarás comigo no paraíso' (Lucas 23:43). (c) 'Mulher, eis aí o teu filho' (João 19:26-27). (d) 'Deus meu, Deus meu, por que me desamparaste?' (Mateus 27:46). (e) 'Tenho sede' (João 19:28). (f) 'Está consumado' (João 19:30). (g) 'Pai, nas tuas mãos entrego o meu espírito' (Lucas 23:46). (4) A Morte de Jesus (Mateus 27:45-56; Marcos 15:33-41; Lucas 23:44-49; João 19:28-30): O véu do templo se rasgou, houve terremoto, escuridão. (5) O Sepultamento (Mateus 27:57-61; Marcos 15:42-47; Lucas 23:50-56; João 19:38-42): José de Arimateia sepulta Jesus. Aplicação: (a) Medite no sofrimento de Cristo por seus pecados. (b) Agradeça pelo perdão e salvação. (c) Consagre sua vida a Cristo. Oração: Senhor Jesus, obrigado por morrer em meu lugar. Perdoa os meus pecados e dá-me vida eterna. Amém.",
            referencias: "Isaías 53:1-12; Salmo 22:1-31; Salmo 69:1-21; Mateus 27:11-66; Marcos 15:1-47; Lucas 23:1-56; João 18:28-19:42"
        },
        {
            termo: "14. Sábado Santo - O Descanso no Sepulcro",
            definicao: "O Sábado Santo é o dia entre a crucificação e a ressurreição. O corpo de Jesus descansou no sepulcro. Meditação: 'E, sendo já tarde, porque era a preparação, isto é, a véspera do sábado, José de Arimateia... foi ousadamente ter com Pilatos, e pediu o corpo de Jesus. E ele lho concedeu' (Marcos 15:42-45). Significados: (1) Jesus realmente morreu (não um desmaio). (2) O sábado foi um dia de silêncio e espera. (3) O descanso no sepulcro antecipa o descanso eterno em Cristo (Hebreus 4:9-11). (4) A esperança da ressurreição. A teologia reformada enfatiza que Cristo desceu ao inferno (descensus ad inferos) no sentido de sofrer a ira de Deus (não uma descida literal ao lugar dos mortos para pregar). O Credo dos Apóstolos: 'Desceu ao inferno; ao terceiro dia ressurgiu dos mortos.' Aplicação: (a) Espere em Deus, mesmo no silêncio. (b) A morte não tem a última palavra; a ressurreição virá. (c) Descanse em Cristo. Oração: Senhor Jesus, no silêncio do Sábado Santo, ensina-me a esperar em ti. Ajuda-me a descansar na tua obra consumada. Amém.",
            referencias: "Salmo 16:9-11; Mateus 27:57-66; Marcos 15:42-47; Lucas 23:50-56; João 19:38-42; Atos 2:27; 1 Pedro 3:18-20; Hebreus 4:9-11"
        },
        {
            termo: "15. Síntese: Da Cruz à Glória",
            definicao: "A Quaresma e a Semana Santa nos conduzem da cruz à glória da ressurreição. 'Cristo morreu pelos nossos pecados, segundo as Escrituras, e que foi sepultado, e que ressuscitou ao terceiro dia, segundo as Escrituras' (1 Coríntios 15:3-4). A teologia reformada enfatiza que: (1) A cruz não é o fim; a ressurreição é a vitória. (2) O sofrimento de Cristo foi vicário (em nosso lugar). (3) A Quaresma não é um fim em si mesma, mas uma preparação para a celebração da Páscoa. 'Temos, pois, irmãos, ousadia para entrar no santuário, pelo sangue de Jesus... aproximemo-nos com verdadeiro coração, em inteira certeza de fé' (Hebreus 10:19-22). Que a Quaresma nos leve ao arrependimento, à fé e à alegria da ressurreição. 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36). Soli Deo Gloria!",
            referencias: "Romanos 11:36; 1 Coríntios 15:1-58; 2 Coríntios 5:14-15; Gálatas 2:20; Efésios 2:1-10; Colossenses 2:13-15; Hebreus 10:19-22; 1 Pedro 2:21-25; 1 Pedro 3:18"
        }
    ]
};