// volume/volume-76.js
window.LIVRO_DATA = {
    nome: "Volume LXXVI",
    dados: [
        {
            termo: "01. Introdução: A História como Revelação de Cristo",
            definicao: "A teologia da história é o estudo do significado e propósito da história humana à luz da revelação de Deus em Cristo. A história não é um ciclo sem sentido (paganismo), nem um processo de evolução automática (progressismo secular), mas uma narrativa teleológica (direcionada para um fim) centrada em Jesus Cristo. 'Havendo Deus antigamente falado muitas vezes e de muitas maneiras pelos profetas, a nós falou-nos nestes últimos dias pelo Filho' (Hebreus 1:1-2). 'E, quando chegou a plenitude do tempo, Deus enviou seu Filho' (Gálatas 4:4). A história é 'His story' (a história de Deus, a história de Cristo). Este volume explora a teologia da história: a criação como o início da história, a queda como a ruptura, a redenção como o centro, a consumação como o fim, e Cristo como o Senhor da história. 'Porque dele e por ele, e para ele, são todas as coisas' (Romanos 11:36). 'Eu sou o Alfa e o Ômega, o princípio e o fim, diz o Senhor, que é, e que era, e que há de vir, o Todo-Poderoso' (Apocalipse 1:8).",
            referencias: "Romanos 11:36; Gálatas 4:4; Efésios 1:9-10; Colossenses 1:15-20; Hebreus 1:1-2; Apocalipse 1:8; Apocalipse 22:13"
        },
        {
            termo: "02. A Criação - O Início da História (Gênesis 1-2)",
            definicao: "A história começou com a criação. 'No princípio criou Deus os céus e a terra' (Gênesis 1:1). A criação não é eterna (contra o panteísmo), nem resultado do acaso (contra o ateísmo), mas obra de Deus através de Cristo. 'Todas as coisas foram feitas por ele, e sem ele nada do que foi feito se fez' (João 1:3). 'Porque nele foram criadas todas as coisas que há nos céus e na terra... tudo foi criado por ele e para ele' (Colossenses 1:16). A criação como início da história: (1) O tempo começa com a criação (não há tempo antes da criação). (2) A história tem um propósito: a glória de Deus (Romanos 11:36). (3) A criação é 'muito boa' (Gênesis 1:31) - não é má (contra o gnosticismo). (4) O homem foi criado à imagem de Deus (Gênesis 1:26-27) - dignidade humana. (5) O mandato cultural: 'dominai sobre a terra' (Gênesis 1:28) - responsabilidade humana. A teologia reformada (Kuyper, Bavinck) vê na criação o fundamento da história e da cultura. 'Os céus declaram a glória de Deus, e o firmamento anuncia a obra das suas mãos' (Salmo 19:1).",
            referencias: "Gênesis 1-2; Salmo 19:1-6; João 1:1-3; Romanos 11:36; Colossenses 1:15-17; Hebreus 1:2-3; Hebreus 11:3"
        },
        {
            termo: "03. A Queda - A Ruptura da História (Gênesis 3)",
            definicao: "A queda de Adão e Eva introduziu o pecado, a morte e a maldição na história. 'Pelo que, como por um homem entrou o pecado no mundo, e pelo pecado a morte, assim também a morte passou a todos os homens, por isso que todos pecaram' (Romanos 5:12). Consequências da queda na história: (1) Separação de Deus (Gênesis 3:8-10). (2) Morte espiritual e física (Gênesis 3:19; Efésios 2:1-3). (3) Maldição sobre a criação (Gênesis 3:17-19; Romanos 8:20-22). (4) Inimizade entre os homens (Gênesis 4:1-16). (5) A história se torna uma história de pecado, guerra, sofrimento e morte. (6) A necessidade de redenção. No entanto, Deus não abandonou a história. O proto-evangelho (Gênesis 3:15) é a primeira promessa de redenção: 'E porei inimizade entre ti e a mulher, e entre a tua semente e a sua semente; esta te ferirá a cabeça, e tu lhe ferirás o calcanhar.' A teologia reformada (Calvino, Bavinck) vê na queda a ruptura que torna necessária a redenção em Cristo. 'Onde o pecado abundou, superabundou a graça' (Romanos 5:20).",
            referencias: "Gênesis 3:1-24; Romanos 5:12-21; Romanos 8:20-22; Efésios 2:1-3; 1 Coríndios 15:21-22; Apocalipse 12:9"
        },
        {
            termo: "04. A Redenção - O Centro da História (Cristo)",
            definicao: "A primeira vinda de Cristo é o centro da história. 'Mas, vindo a plenitude dos tempos, Deus enviou seu Filho' (Gálatas 4:4). 'Havendo Deus... a nós falou-nos nestes últimos dias pelo Filho' (Hebreus 1:1-2). O centro da história é: (1) A encarnação: Deus se fez homem (João 1:14). (2) A vida de Cristo: cumpriu a lei (Mateus 5:17). (3) A morte de Cristo: expiação pelos pecados (Romanos 3:23-26). (4) A ressurreição de Cristo: vitória sobre a morte (1 Coríndios 15:3-8). (5) A ascensão de Cristo: entronização à direita de Deus (Atos 2:33-35). (6) O derramamento do Espírito: Pentecostes (Atos 2:1-4). (7) A formação da igreja: o corpo de Cristo (Efésios 1:22-23). A história antes de Cristo aponta para Ele (preparação). A história depois de Cristo testemunha Dele (expansão do evangelho). A teologia reformada (Vos, Ridderbos) vê a primeira vinda de Cristo como o clímax da história da redenção. 'Porque todas quantas promessas há de Deus, são nele sim, e por ele amém' (2 Coríndios 1:20).",
            referencias: "Mateus 1:18-25; Lucas 2:1-20; João 1:14; Gálatas 4:4-5; Efésios 1:3-14; Filipenses 2:5-11; Colossenses 1:15-20; 1 Timóteo 3:16; Tito 2:11-14; Hebreus 1:1-4; 1 Pedro 1:18-21"
        },
        {
            termo: "05. A Era da Igreja - O Tempo entre as Vindas (Atos 1 - Apocalipse 19)",
            definicao: "A era da igreja é o período entre a primeira e a segunda vinda de Cristo. Esta era é caracterizada por: (1) A pregação do evangelho a todas as nações (Mateus 24:14; Atos 1:8). (2) A expansão da igreja (Atos 2:47). (3) O sofrimento e perseguição (João 15:20; 2 Timóteo 3:12). (4) A presença do Espírito Santo (João 14:16-17; Atos 2:1-4). (5) Os dons espirituais (1 Coríndios 12:4-11). (6) O crescimento do Reino de Deus. (7) A esperança da volta de Cristo (Tito 2:13). Esta era não é sem sentido; é o tempo da colheita do evangelho. A teologia reformada (Calvino, Kuyper) vê a história da igreja como a progressão do Reino de Cristo. 'E este evangelho do reino será pregado em todo o mundo, em testemunho a todas as nações, e então virá o fim' (Mateus 24:14). 'E eis que estou convosco todos os dias, até à consumação do século' (Mateus 28:20).",
            referencias: "Mateus 13:31-33; Mateus 24:14; Mateus 28:18-20; Atos 1:8; Atos 2:1-47; Romanos 10:14-15; Efésios 4:11-16; Apocalipse 2-3"
        },
        {
            termo: "06. A Segunda Vinda de Cristo - A Consumação da História (Apocalipse 19-22)",
            definicao: "A segunda vinda de Cristo (parusia) é a consumação da história. 'Este Jesus... há de vir assim como para o céu o vistes ir' (Atos 1:11). 'Porque o Senhor mesmo descerá do céu com alarido, e com voz de arcanjo, e com a trombeta de Deus' (1 Tessalonicenses 4:16). Eventos da consumação: (1) A ressurreição dos mortos (João 5:28-29; 1 Coríndios 15:20-23). (2) O juízo final (Mateus 25:31-46; Apocalipse 20:11-15). (3) A derrota final de Satanás (Apocalipse 20:10). (4) A nova criação (Apocalipse 21-22). (5) A vida eterna com Deus. A história não termina em tragédia, mas em vitória (Cristo reina). A teologia reformada (Calvino, Berkhof) vê na segunda vinda a esperança consumada da igreja. 'Aguardando a bem-aventurada esperança e o aparecimento da glória do grande Deus e nosso Salvador Jesus Cristo' (Tito 2:13). 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36).",
            referencias: "Daniel 7:13-14; Zacarias 14:1-5; Mateus 24-25; Atos 1:11; Filipenses 3:20-21; 1 Tessalonicenses 4:13-18; 2 Tessalonicenses 1:5-10; Tito 2:13; 2 Pedro 3:10-13; Apocalipse 1:7; Apocalipse 19-22"
        },
        {
            termo: "07. Cristo como Senhor da História - A Soberania de Deus",
            definicao: "Cristo é o Senhor da história. Ele governa todas as nações e todos os eventos. 'Toda a autoridade me foi dada no céu e na terra' (Mateus 28:18). 'O coração do rei está na mão do Senhor; a tudo quanto quer, o inclina' (Provérbios 21:1). A soberania de Cristo sobre a história significa: (1) Deus está no controle (nada acontece fora do seu plano). (2) A história tem um propósito (a glória de Deus). (3) O mal não é final (Cristo vencerá). (4) Os crentes podem ter esperança, mesmo em meio ao caos. (5) A oração é eficaz (Deus age na história). (6) A missão da igreja é garantida de sucesso (Mateus 24:14). A teologia reformada (Calvino, Kuyper) enfatiza a soberania de Cristo sobre todas as áreas da vida (incluindo política, economia, cultura). 'Bem-aventurada é a nação cujo Deus é o Senhor' (Salmo 33:12). 'Porque dele e por ele, e para ele, são todas as coisas' (Romanos 11:36).",
            referencias: "Salmo 2:1-12; Salmo 33:10-11; Salmo 103:19; Daniel 2:21; Daniel 4:34-35; Mateus 28:18; Atos 17:26-28; Romanos 11:36; Efésios 1:20-23; Colossenses 1:16-17"
        },
        {
            termo: "08. A Filosofia da História Cristã - Agostinho, Kuyper, Dooyeweerd",
            definicao: "Grandes pensadores cristãos desenvolveram filosofias da história. (1) Agostinho (354-430 d.C.): 'A Cidade de Deus' contrasta a cidade de Deus (os eleitos) com a cidade dos homens (os ímpios). A história é o conflito entre as duas cidades, culminando na vitória da cidade de Deus. (2) Abraham Kuyper (1837-1920): 'Antirevolucionário' - a história é a luta entre a soberania de Deus e a autonomia humana. Kuyper desenvolveu a doutrina da 'soberania das esferas' (igreja, Estado, família, educação são distintas, mas todas sob Cristo). (3) Herman Dooyeweerd (1894-1977): desenvolveu uma 'filosofia da ideia da lei' (Wijsbegeerte der Wetsidee), afirmando que a criação é ordenada por leis divinas (modos: numérico, espacial, físico, biótico, sensitivo, lógico, histórico, lingüístico, social, econômico, estético, jurídico, ético, pístico). Cristo é o centro da criação. (4) Francis Schaeffer (1912-1984): 'A Morte da Razão' - a história da filosofia ocidental é a história do afastamento de Deus. Schaeffer chamou a igreja a voltar à cosmovisão cristã. A teologia reformada (Kuyper, Dooyeweerd, Schaeffer) afirma que Cristo é o Rei sobre todas as áreas da vida. 'Não há um centímetro quadrado do universo sobre o qual Cristo não clame: Meu!' (Kuyper).",
            referencias: "Salmo 24:1; Salmo 47:2; Daniel 2:21; Romanos 13:1-7; Colossenses 1:15-20; Hebreus 1:1-4; Apocalipse 11:15"
        },
        {
            termo: "09. O Significado do Tempo - Cronos e Kairós",
            definicao: "A Bíblia distingue entre dois tipos de tempo: (1) Cronos (chronos): tempo cronológico, sequencial, mensurável (dias, meses, anos). (2) Kairós (kairos): tempo qualitativo, momento oportuno, tempo decisivo. O Novo Testamento usa 'kairós' para descrever a vinda de Cristo. 'Mas, vindo a plenitude do tempo (kairós), Deus enviou seu Filho' (Gálatas 4:4). 'O tempo está cumprido, e o reino de Deus está próximo' (Marcos 1:15). O kairós é o momento decisivo na história da salvação: (a) A encarnação de Cristo. (b) A morte e ressurreição de Cristo. (c) O Pentecostes. (d) A volta de Cristo. O kairós também se aplica à vida do crente: o momento da conversão é um kairós. A teologia reformada (Vos, Ridderbos) enfatiza que o 'kairós' é o momento em que Deus age decisivamente na história. 'Eis que agora é o tempo aceitável, eis que agora é o dia da salvação' (2 Coríndios 6:2).",
            referencias: "Eclesiastes 3:1-8; Daniel 2:21; Marcos 1:15; Gálatas 4:4; Efésios 5:16; Colossenses 4:5; 2 Coríndios 6:2; 1 Pedro 1:5"
        },
        {
            termo: "10. A História como Preparação para Cristo - A Pedagogia de Deus",
            definicao: "O Antigo Testamento é a preparação para Cristo. 'E, começando por Moisés e por todos os profetas, explicava-lhes o que dele se achava em todas as Escrituras' (Lucas 24:27). A história do Antigo Testamento é uma pedagogia divina que prepara o caminho para Cristo. Preparações: (1) Profecias: Isaías 53; Salmo 22; Miqueias 5:2; Zacarias 9:9, etc. (2) Tipos: Adão (Romanos 5:14), Melquisedeque (Hebreus 7:1-28), Isaque (Gênesis 22), José (Gênesis 37-50), Moisés (Deuteronômio 18:15-19), Josué (Yeshua), Davi (2 Samuel 7:12-16), Salomão (Mateus 12:42), Jonas (Mateus 12:40). (3) Instituições: tabernáculo, templo, sacerdócio, sacrifícios, festas (Páscoa, Pentecostes, Tabernáculos). (4) Eventos: êxodo, travessia do Jordão, queda de Jericó, exílio e retorno. (5) Pessoas: Abraão, Isaque, Jacó, José, Moisés, Josué, Davi, Salomão, Elias, Eliseu, Isaías, Jeremias, Ezequiel, Daniel. A teologia reformada (Calvino, Owen) vê toda a história do Antigo Testamento como preparação para Cristo. 'Porque todas quantas promessas há de Deus, são nele sim, e por ele amém' (2 Coríndios 1:20).",
            referencias: "Lucas 24:27; Lucas 24:44-45; João 5:39; Atos 3:18; Atos 10:43; Romanos 1:1-4; 1 Coríndios 10:11; Gálatas 3:24; Colossenses 2:17; Hebreus 8:5; Hebreus 10:1; 1 Pedro 1:10-12"
        },
        {
            termo: "11. A História como Testemunho de Cristo - A Expansão do Evangelho",
            definicao: "Após a primeira vinda de Cristo, a história se tornou o testemunho de Cristo através da igreja. 'Mas recebereis a virtude do Espírito Santo, que há de vir sobre vós; e ser-me-eis testemunhas, tanto em Jerusalém como em toda a Judeia e Samaria, e até aos confins da terra' (Atos 1:8). Marcos na história: (1) A igreja primitiva (Atos 2-12). (2) As viagens missionárias de Paulo (Atos 13-28). (3) A expansão do evangelho no Império Romano (séculos I-V). (4) As missões na Idade Média (séculos V-XV). (5) A Reforma Protestante (século XVI). (6) O Despertamento Evangélico (séculos XVIII-XIX). (7) As missões modernas (séculos XIX-XX). (8) A igreja global hoje (África, Ásia, América Latina). A teologia reformada (Kuyper, Bavinck) vê na história da igreja a progressão do Reino de Cristo. 'E este evangelho do reino será pregado em todo o mundo, em testemunho a todas as nações, e então virá o fim' (Mateus 24:14).",
            referencias: "Mateus 24:14; Atos 1:8; Romanos 10:14-18; Romanos 15:18-24; Colossenses 1:6; Colossenses 1:23; Apocalipse 5:9; Apocalipse 7:9"
        },
        {
            termo: "12. A História e a Esperança Escatológica - O Fim como Consumação",
            definicao: "A história não é sem sentido; ela se dirige para um fim: a consumação do reino de Cristo. 'E, quando todas as coisas lhe estiverem sujeitas, então também o próprio Filho se sujeitará àquele que todas as coisas lhe sujeitou, para que Deus seja tudo em todos' (1 Coríndios 15:28). A esperança escatológica transforma a visão da história: (1) A história não é eterna (terá um fim). (2) O sofrimento presente é temporário (2 Coríndios 4:17). (3) A injustiça será julgada (Mateus 25:31-46). (4) A morte será vencida (1 Coríndios 15:54-57). (5) A nova criação é a esperança (Apocalipse 21-22). (6) Os crentes devem viver em santidade e serviço (2 Pedro 3:11-14). A teologia reformada (Calvino, Berkhof) vê na esperança escatológica a motivação para a missão e a santidade. 'Portanto, meus amados irmãos, sede firmes e constantes, sempre abundantes na obra do Senhor, sabendo que o vosso trabalho não é vão no Senhor' (1 Coríndios 15:58).",
            referencias: "Romanos 8:18-25; 1 Coríndios 15:20-28; 2 Coríndios 4:17-18; Filipenses 3:20-21; 2 Pedro 3:10-13; Apocalipse 21-22"
        },
        {
            termo: "13. Síntese: Cristo, o Senhor da História",
            definicao: "Cristo é o Senhor da história. 'Porque dele e por ele, e para ele, são todas as coisas' (Romanos 11:36). Resumo da teologia da história: (1) A criação é o início da história (Gênesis 1-2). (2) A queda é a ruptura da história (Gênesis 3). (3) A redenção é o centro da história (Cristo). (4) A era da igreja é o tempo entre as vindas (Atos 1 - Apocalipse 19). (5) A segunda vinda é a consumação da história (Apocalipse 19-22). (6) Cristo é o Senhor da história (Mateus 28:18). (7) A história é a preparação para Cristo (Antigo Testamento). (8) A história é o testemunho de Cristo (igreja). (9) A esperança escatológica transforma a história. (10) O fim da história é a glória de Cristo. 'Aquele que testifica estas coisas diz: Certamente cedo venho. Amém. Ora vem, Senhor Jesus. A graça de nosso Senhor Jesus Cristo seja com todos vós. Amém' (Apocalipse 22:20-21). Soli Deo Gloria!",
            referencias: "Romanos 11:36; 1 Coríndios 10:31; Colossenses 1:15-20; Hebreus 1:1-4; Apocalipse 1:8; Apocalipse 22:20-21"
        }
    ]
};