// volume/volume-89.js
window.LIVRO_DATA = {
    nome: "Volume LXXXIX",
    dados: [
        {
            termo: "01. Introdução: O Descanso como Dom de Deus",
            definicao: "O descanso é um dom de Deus, não uma mera ausência de trabalho. Deus mesmo descansou no sétimo dia após a criação (Gênesis 2:2-3). 'E abençoou Deus o sétimo dia e o santificou; porque nele descansou de toda a sua obra' (Gênesis 2:3). O descanso não é apenas físico, mas também espiritual: descansar em Deus, confiar em sua providência, cessar de nossas próprias obras para depender de Cristo. 'Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei' (Mateus 11:28). 'Tomai sobre vós o meu jugo... e encontrareis descanso para as vossas almas' (Mateus 11:29-30). A teologia reformada (Calvino, Bavinck) enfatiza que o descanso sabático aponta para o descanso eterno em Cristo (Hebreus 4:9-11). Este volume explora: (1) O sábado como descanso semanal. (2) Férias e lazer como descanso prolongado. (3) Descanso espiritual em Cristo. (4) Equilíbrio entre trabalho e descanso. (5) Descanso na eternidade. 'Portanto, resta ainda um repouso para o povo de Deus' (Hebreus 4:9).",
            referencias: "Gênesis 2:2-3; Êxodo 20:8-11; Mateus 11:28-30; Hebreus 4:1-11; Apocalipse 14:13"
        },
        {
            termo: "02. O Sábado na Criação e na Lei - O Descanso Semanal (Êxodo 20:8-11)",
            definicao: "O sábado (descanso semanal) foi instituído na criação (Gênesis 2:2-3) e codificado no Decálogo (Êxodo 20:8-11). 'Lembra-te do dia do sábado, para o santificar. Seis dias trabalharás, e farás toda a tua obra. Mas o sétimo dia é o sábado do Senhor teu Deus; não farás nenhuma obra' (Êxodo 20:8-10). Propósitos do sábado: (1) Descanso físico: corpo precisa de descanso (Salmo 127:2). (2) Descanso espiritual: adoração a Deus. (3) Lembrança da criação: Deus descansou no sétimo dia. (4) Lembrança da redenção: Israel foi libertado do Egito (Deuteronômio 5:15). (5) Sinal da aliança (Êxodo 31:13,17). (6) Antecipação do descanso eterno. O sábado no Antigo Testamento: (a) Proibição de trabalho (Êxodo 20:10). (b) Proibição de acender fogo (Êxodo 35:3). (c) Proibição de colher lenha (Números 15:32-36). (d) Proibição de carregar carga (Jeremias 17:21-22). (e) Culto sagrado (Levítico 23:3). (f) Descanso para servos e animais (Êxodo 20:10). (g) Ano sabático (Levítico 25:1-7). A teologia reformada (Calvino, Westminster) ensina que o sábado cerimonial foi cumprido em Cristo, mas o princípio do descanso permanece. 'O sábado foi feito por causa do homem, e não o homem por causa do sábado' (Marcos 2:27).",
            referencias: "Gênesis 2:2-3; Êxodo 20:8-11; Deuteronômio 5:12-15; Neemias 13:15-22; Isaías 58:13-14; Jeremias 17:21-22; Marcos 2:27-28"
        },
        {
            termo: "03. Jesus e o Sábado - O Senhor do Sábado (Mateus 12:1-14)",
            definicao: "Jesus declarou ser o Senhor do sábado. 'Porque o Filho do Homem é Senhor até do sábado' (Mateus 12:8). Ele curou no sábado (Mateus 12:9-14; João 5:1-18; 9:1-14), mostrando que a misericórdia está acima do ritual. 'O sábado foi feito por causa do homem, e não o homem por causa do sábado' (Marcos 2:27). Jesus reinterpretou o sábado: (1) O sábado foi feito para o bem do homem, não para oprimir. (2) Atos de misericórdia são permitidos no sábado (Mateus 12:11-12). (3) O descanso espiritual em Cristo é superior ao descanso físico. (4) Jesus é o verdadeiro descanso (Mateus 11:28-30). (5) O sábado aponta para Cristo (Colossenses 2:16-17). A teologia reformada (Calvino, Westminster) ensina que o sábado cerimonial foi abolido, mas o princípio do descanso (um dia em sete) permanece, aplicado ao domingo (Dia do Senhor). 'Portanto, ninguém vos julgue pelo comer, ou pelo beber, ou por causa dos dias de festa, ou da lua nova, ou dos sábados, que são sombras das coisas futuras, mas o corpo é de Cristo' (Colossenses 2:16-17).",
            referencias: "Mateus 11:28-30; Mateus 12:1-14; Marcos 2:23-28; Marcos 3:1-6; Lucas 6:1-11; João 5:1-18; João 9:1-14; Colossenses 2:16-17"
        },
        {
            termo: "04. O Domingo - O Dia do Senhor (Dies Domini)",
            definicao: "Os cristãos passaram a se reunir no domingo (primeiro dia da semana) em comemoração à ressurreição de Cristo. 'E, no primeiro dia da semana, ajuntando-se os discípulos para partir o pão, Paulo lhes pregava' (Atos 20:7). 'No primeiro dia da semana, cada um de vós ponha de parte o que puder ajuntar' (1 Coríndios 16:2). 'Eu fui arrebatado em espírito no dia do Senhor' (Apocalipse 1:10). O domingo é chamado 'Dia do Senhor' (Dies Domini). A teologia reformada (Calvino, Westminster) ensina que o domingo é o sábado cristão, um dia de descanso e adoração. 'Lembra-te do dia do sábado, para o santificar' (Êxodo 20:8) aplicado ao domingo. Práticas no domingo: (1) Culto público (Hebreus 10:25). (2) Descanso das atividades cotidianas. (3) Obras de misericórdia. (4) Leitura da Bíblia e oração em família. (5) Descanso físico. (6) Celebração da Ceia do Senhor. (7) Louvor e adoração. A teologia reformada (Puritanos) enfatizou o 'descanso sabático' (não trabalhar, não fazer compras, não recreação), enquanto outros reformados são menos rigorosos. 'Se desviares o teu pé do sábado, de fazeres a tua vontade no meu santo dia... então te deleitarás no Senhor' (Isaías 58:13-14).",
            referencias: "Atos 20:7; 1 Coríndios 16:2; Apocalipse 1:10; Apocalipse 10; Isaías 58:13-14; Hebreus 10:25"
        },
        {
            termo: "05. Descanso Espiritual em Cristo - O Verdadeiro Descanso (Mateus 11:28-30)",
            definicao: "O descanso espiritual em Cristo é superior ao descanso físico do sábado. 'Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei. Tomai sobre vós o meu jugo, e aprendei de mim, que sou manso e humilde de coração; e encontrareis descanso para as vossas almas' (Mateus 11:28-30). Este descanso é: (1) Da culpa do pecado (justificação). (2) Do poder do pecado (santificação). (3) Da ansiedade e preocupação (Filipenses 4:6-7). (4) Do trabalho para a salvação (Gálatas 2:16). (5) Do legalismo (Romanos 6:14). (6) Do medo da morte (Hebreus 2:14-15). (7) Da luta contra o mal (Romanos 8:37). (8) Da busca por significado (Eclesiastes 12:13). (9) Da comparação social (Gálatas 6:4). (10) Da autossuficiência (Filipenses 4:13). A teologia reformada (Calvino, Owen) enfatiza que o descanso em Cristo é a base do verdadeiro sábado. 'Vinde a mim' é o convite de Cristo. 'Tomai sobre vós o meu jugo' é o chamado ao discipulado. 'Aprendei de mim' é o discipulado. 'Encontrareis descanso para as vossas almas' é a promessa. 'Descansai no Senhor, e espera nele' (Salmo 37:7).",
            referencias: "Salmo 37:7; Isaías 30:15; Jeremias 6:16; Mateus 11:28-30; Hebreus 3:7-4:11; 1 Pedro 5:7"
        },
        {
            termo: "06. Férias e Lazer - Descanso Prolongado e Recreação",
            definicao: "Férias (descanso prolongado) e lazer (recreação) são dons de Deus para renovar corpo e mente. 'Deus descansou no sétimo dia' (Gênesis 2:2-3) é o modelo para descansos regulares. 'Férias' não são mencionadas na Bíblia, mas o princípio do descanso se aplica. Princípios para férias: (1) Planejamento: férias devem ser planejadas (Provérbios 21:5). (2) Descanso: férias são para descanso (Marcos 6:31). (3) Família: férias são oportunidades para fortalecer laços familiares. (4) Adoração: férias não devem ser desculpa para negligenciar o culto dominical (Hebreus 10:25). (5) Mordomia: gastar recursos com sabedoria (Provérbios 21:20). (6) Santidade: evitar práticas pecaminosas nas férias (1 Tessalonicenses 4:3-5). (7) Evitar excessos: não transformar férias em idolatria. (8) Trabalho: não negligenciar responsabilidades (2 Tessalonicenses 3:10). (9) Oração: orar durante as férias (1 Tessalonicenses 5:17). (10) Ação de graças: agradecer a Deus pelas férias (1 Tessalonicenses 5:18). Lazer (recreação): (1) Atividades recreativas são permitidas (Eclesiastes 3:1-8). (2) Evitar pecados (bebedeira, orgias, etc.) (Gálatas 5:19-21). (3) Moderar o tempo (Efésios 5:15-16). (4) Incluir atividades saudáveis (1 Timóteo 4:8). (5) Usar para relacionamentos (família, amigos). (6) Glorificar a Deus (1 Coríndios 10:31). A teologia reformada (Calvino, Kuyper) valoriza o lazer como parte da boa criação de Deus. 'Tudo o que é verdadeiro... nisso pensai' (Filipenses 4:8).",
            referencias: "Gênesis 2:2-3; Êxodo 20:8-11; Eclesiastes 3:1-8; Marcos 6:31; 1 Coríndios 10:31; 1 Timóteo 4:8; Filipenses 4:8"
        },
        {
            termo: "07. Equilíbrio entre Trabalho e Descanso - Sabedoria Prática",
            definicao: "A Bíblia ensina o equilíbrio entre trabalho e descanso. 'Seis dias trabalharás, e farás toda a tua obra' (Êxodo 20:9). 'O pão suado é melhor que o pão mendigado' (Provérbios 12:11). 'O sono do trabalhador é doce' (Eclesiastes 5:12). Sinais de desequilíbrio: (1) Workaholic (vício em trabalho): descanso insuficiente. (2) Preguiça: descanso excessivo (Provérbios 6:6-11). (3) Ansiedade: preocupação excessiva (Mateus 6:25-34). (4) Estresse: falta de descanso espiritual. (5) Burnout (esgotamento): trabalho excessivo sem descanso. (6) Idolatria do trabalho: trabalho em primeiro lugar (Êxodo 20:3). (7) Idolatria do descanso: lazer em primeiro lugar. Estratégias de equilíbrio: (a) Trabalhar com diligência (Colossenses 3:23). (b) Descansar no sábado/domingo (Êxodo 20:8-11). (c) Tirar férias regulares. (d) Dormir adequadamente (Salmo 127:2). (e) Orar e confiar em Deus (Filipenses 4:6-7). (f) Delegar tarefas (Êxodo 18:17-23). (g) Estabelecer limites (não trabalhar após certo horário). (h) Priorizar família (1 Timóteo 5:8). (i) Priorizar Deus (Mateus 6:33). (j) Descansar em Cristo (Mateus 11:28-30). A teologia reformada (Calvino, Kuyper) enfatiza o equilíbrio como sabedoria prática. 'Há tempo para tudo' (Eclesiastes 3:1).",
            referencias: "Êxodo 20:8-11; Provérbios 6:6-11; Eclesiastes 3:1-8; Eclesiastes 5:12; Mateus 6:33; Mateus 11:28-30; Colossenses 3:23; 1 Tessalonicenses 5:17"
        },
        {
            termo: "08. Descanso na Natureza - Contemplação da Criação",
            definicao: "O descanso na natureza é uma forma de contemplar a criação de Deus e renovar as forças. 'Os céus declaram a glória de Deus, e o firmamento anuncia a obra das suas mãos' (Salmo 19:1). 'Ele faz-me deitar em pastos verdejantes; guia-me mansamente a águas tranquilas' (Salmo 23:2). Benefícios do descanso na natureza: (1) Contemplação da glória de Deus (Salmo 8:3-4). (2) Renovação das forças (Isaías 40:31). (3) Paz interior (Salmo 23:2). (4) Conexão com a criação (Gênesis 2:15). (5) Alívio do estresse (Mateus 11:28-30). (6) Oportunidade para meditação (Salmo 1:2). (7) Oração ao ar livre. (8) Tempo em família. (9) Exercício físico (1 Timóteo 4:8). (10) Cuidado com o meio ambiente (Gênesis 2:15). Práticas: (a) Caminhadas na natureza. (b) Acampamentos. (c) Visitas a parques e praias. (d) Observação de aves e animais. (e) Jardinagem. (f) Pesca (sustento). (g) Piqueniques. (h) Fotografia da natureza. (i) Estudos bíblicos ao ar livre. (j) Cultos ao ar livre. A teologia reformada (Kuyper, Bavinck) valoriza a natureza como revelação de Deus. 'As suas coisas invisíveis, desde a criação do mundo, tanto o seu eterno poder como a sua divindade, se entendem e claramente se veem pelas coisas que estão criadas' (Romanos 1:20).",
            referencias: "Gênesis 2:15; Salmo 8:3-4; Salmo 19:1-6; Salmo 23:2; Isaías 40:31; Romanos 1:20; Romanos 8:19-22"
        },
        {
            termo: "09. Descanso na Velhice - Aposentadoria e Envelhecimento",
            definicao: "A velhice é um tempo de descanso das labutas da vida, mas não de inatividade. 'Na velhice ainda darão frutos' (Salmo 92:14). 'Os justos florescerão como a palmeira; crescerão como o cedro no Líbano' (Salmo 92:12). Características da velhice segundo a Bíblia: (1) Sabedoria (Provérbios 16:31). (2) Experiência (Jó 12:12). (3) Frutificação espiritual (Salmo 92:14). (4) Ensinamento aos jovens (Tito 2:2-5). (5) Oração e intercessão. (6) Discipulado. (7) Testemunho. (8) Serviço (voluntariado). (9) Descanso (aposentadoria do trabalho pesado). (10) Preparação para a morte (2 Timóteo 4:6-8). Aposentadoria: (a) Planejar financeiramente (Provérbios 6:6-8). (b) Não desperdiçar tempo (Efésios 5:15-16). (c) Servir a Deus (Colossenses 3:23). (d) Ensinar jovens (Tito 2:2-5). (e) Orar pela igreja. (f) Aconselhar (sabedoria). (g) Escrever (legado). (h) Cuidar da saúde (1 Coríndios 6:19-20). (i) Descansar adequadamente. (j) Preparar herança espiritual (2 Timóteo 1:5). A teologia reformada (Calvino, Bavinck) valoriza a velhice como tempo de colheita espiritual. 'O justo florescerá como a palmeira' (Salmo 92:12).",
            referencias: "Jó 12:12; Salmo 71:9; Salmo 71:18; Salmo 92:12-15; Provérbios 16:31; Eclesiastes 12:1-7; Tito 2:2-5; 2 Timóteo 4:6-8"
        },
        {
            termo: "10. Descanso e Morte - O Descanso dos Santos (Apocalipse 14:13)",
            definicao: "A morte para o crente é um descanso das labutas terrenas. 'Bem-aventurados os mortos que desde agora morrem no Senhor... para que descansem das suas labutas' (Apocalipse 14:13). 'Porque para mim o viver é Cristo, e o morrer é ganho' (Filipenses 1:21). 'E, tendo o desejo de partir e estar com Cristo, porque isto é ainda muito melhor' (Filipenses 1:23). Características do descanso na morte: (1) Ausência de dor e sofrimento (Apocalipse 21:4). (2) Ausência de pecado (Hebreus 12:23). (3) Presença com Cristo (2 Coríndios 5:8). (4) Comunhão com os santos (Hebreus 12:23). (5) Ausência de fadiga (Apocalipse 14:13). (6) Descanso das labutas terrenas. (7) Esperança da ressurreição (1 Coríndios 15:20-23). (8) Glorificação (Romanos 8:30). (9) Visão de Deus (1 João 3:2). (10) Vida eterna (João 3:16). A teologia reformada (Calvino, Bavinck) vê a morte como entrada no descanso eterno. 'Portanto, resta ainda um repouso para o povo de Deus' (Hebreus 4:9). 'E Deus limpará de seus olhos toda lágrima; e não haverá mais morte, nem pranto, nem clamor, nem dor' (Apocalipse 21:4).",
            referencias: "João 11:25-26; 2 Coríndios 5:1-8; Filipenses 1:21-23; 1 Tessalonicenses 4:13-18; Hebreus 4:9-11; Apocalipse 14:13; Apocalipse 21:4"
        },
        {
            termo: "11. Descanso na Nova Criação - O Descanso Eterno",
            definicao: "O descanso final do crente é na nova criação (novos céus e nova terra). 'E vi um novo céu e uma nova terra' (Apocalipse 21:1). 'E Deus limpará de seus olhos toda lágrima; e não haverá mais morte, nem pranto, nem clamor, nem dor' (Apocalipse 21:4). Características do descanso eterno: (1) Ausência de pecado (Apocalipse 21:27). (2) Ausência de sofrimento (Apocalipse 21:4). (3) Ausência de morte (Apocalipse 21:4). (4) Presença de Deus (Apocalipse 21:3). (5) Visão de Deus (Apocalipse 22:4). (6) Serviço a Deus (Apocalipse 22:3). (7) Comunhão com os santos (Hebreus 12:23). (8) Árvore da vida (Apocalipse 22:2). (9) Rio da água da vida (Apocalipse 22:1). (10) Luz de Deus (Apocalipse 21:23). (11) Ausência de noite (Apocalipse 21:25). (12) Ausência de templo (Deus e o Cordeiro são o templo) (Apocalipse 21:22). (13) Plenitude de alegria (Salmo 16:11). (14) Descanso eterno (Hebreus 4:9). A teologia reformada (Calvino, Bavinck) vê a nova criação como a consumação do descanso. 'E aquele que estava assentado sobre o trono disse: Eis que faço novas todas as coisas' (Apocalipse 21:5). 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36).",
            referencias: "Romanos 11:36; Filipenses 3:20-21; Hebreus 4:9-11; 2 Pedro 3:13; Apocalipse 21:1-27; Apocalipse 22:1-5"
        },
        {
            termo: "12. Descanso e Santidade - Evitando a Preguiça e a Ociosidade",
            definicao: "O descanso não deve se tornar preguiça ou ociosidade. 'Vai ter com a formiga, ó preguiçoso; olha para os seus caminhos e sábio sê' (Provérbios 6:6). 'Se alguém não quer trabalhar, também não coma' (2 Tessalonicenses 3:10). Distinção entre descanso e preguiça: (1) Descanso: cessar o trabalho para renovar forças (Marcos 6:31). (2) Preguiça: evitar o trabalho por falta de vontade (Provérbios 13:4). (3) Descanso é planejado; preguiça é procrastinação. (4) Descanso é temporário; preguiça é hábito. (5) Descanso glorifica a Deus; preguiça desonra a Deus. (6) Descanso é ordenado; preguiça é condenada. (7) Descanso é produtivo; preguiça é improdutiva. (8) Descanso é bíblico; preguiça é pecado. (9) Descanso é necessário; preguiça é destrutiva. (10) Descanso é sabedoria; preguiça é tolice. Sinais de preguiça: (a) Procrastinação (adiar tarefas). (b) Desculpas (justificativas). (c) Desorganização. (d) Falta de disciplina. (e) Desperdício de tempo. (f) Falta de zelo (Apocalipse 3:15-16). (g) Negligência de deveres. (h) Dependência dos outros. (i) Falta de iniciativa. (j) Excesso de sono (Provérbios 20:13). A teologia reformada (Calvino, Puritanos) enfatiza a diligência como virtude cristã. 'Tudo o que fizerdes, fazei-o de coração, como ao Senhor' (Colossenses 3:23).",
            referencias: "Provérbios 6:6-11; Provérbios 10:4-5; Provérbios 12:11; Provérbios 13:4; Romanos 12:11; 2 Tessalonicenses 3:10-12; Colossenses 3:23"
        },
        {
            termo: "13. Síntese: Descansando para a Glória de Cristo",
            definicao: "O descanso cristão tem como objetivo final a glória de Cristo. 'Portanto, quer comais quer bebais, ou façais outra qualquer coisa, fazei tudo para glória de Deus' (1 Coríndios 10:31). Resumo da teologia do descanso: (1) O descanso é um dom de Deus (Gênesis 2:2-3). (2) O sábado é um dia de descanso e adoração (Êxodo 20:8-11). (3) Jesus é o Senhor do sábado (Mateus 12:8). (4) O domingo é o Dia do Senhor (Atos 20:7; Apocalipse 1:10). (5) O descanso espiritual em Cristo é essencial (Mateus 11:28-30). (6) Férias e lazer são dons de Deus (Eclesiastes 3:1-8). (7) Equilíbrio entre trabalho e descanso é sabedoria (Eclesiastes 3:1). (8) Descanso na natureza contempla a criação (Salmo 19:1). (9) A velhice é tempo de descanso e frutificação (Salmo 92:14). (10) A morte é descanso das labutas (Apocalipse 14:13). (11) A nova criação é o descanso eterno (Apocalipse 21-22). (12) O descanso não deve ser preguiça (Provérbios 6:6). (13) Todo descanso deve ser para a glória de Cristo (1 Coríndios 10:31). 'E tudo quanto fizerdes, por palavra ou por obra, fazei-o em nome do Senhor Jesus, dando por ele graças a Deus Pai' (Colossenses 3:17). Soli Deo Gloria!",
            referencias: "Romanos 11:36; 1 Coríndios 10:31; Colossenses 3:17; Apocalipse 21-22; Apocalipse 22:20-21"
        }
    ]
};