// volume/volume-37.js
window.LIVRO_DATA = {
    nome: "Volume XXXVII",
    dados: [
        {
            termo: "01. Introdução: O que são os Evangelhos Apócrifos?",
            definicao: "Os evangelhos apócrifos (do grego apokryphos - 'oculto, escondido') são escritos do cristianismo primitivo que não foram incluídos no cânon do Novo Testamento. Eles datam principalmente dos séculos II a IV d.C. (alguns podem ser mais antigos). A palavra 'apócrifo' não significa necessariamente 'falso' ou 'herético', mas 'não canônico' (não aceito como Escritura inspirada). A igreja primitiva estabeleceu o cânon do Novo Testamento baseada em critérios: (a) Apostolicidade (escrito por um apóstolo ou associado próximo). (b) Ortodoxia (conformidade com a regra da fé). (c) Uso generalizado na igreja. (d) Antiguidade (datação precoce). Os evangelhos canônicos (Mateus, Marcos, Lucas, João) são aceitos como inspirados (2 Timóteo 3:16). Os apócrifos, embora contenham alguns ditos interessantes, são rejeitados por: (a) Datação tardia (século II em diante). (b) Autoria falsa (pseudepígrafos). (c) Conteúdo herético (docetismo, gnosticismo, ebionismo, etc.). (d) Falta de uso generalizado. A teologia reformada segue a tradição da igreja primitiva e da Reforma, aceitando apenas os 27 livros do Novo Testamento como canônicos. 'Toda a Escritura é inspirada por Deus e útil para o ensino, para a repreensão, para a correção, para a instrução na justiça' (2 Timóteo 3:16). Este volume analisa os principais evangelhos apócrifos, contrastando sua cristologia com a dos evangelhos canônicos.",
            referencias: "2 Timóteo 3:16-17; 2 Pedro 1:19-21; Apocalipse 22:18-19; Gálatas 1:8-9"
        },
        {
            termo: "02. Classificação dos Evangelhos Apócrifos",
            definicao: "Os evangelhos apócrifos podem ser classificados em várias categorias principais: (1) Evangelhos Gnósticos: Enfatizam o conhecimento secreto (gnosis) como meio de salvação, negam a encarnação real (docetismo), e distinguem o Jesus terreno do Cristo celestial. Exemplos: Evangelho de Tomé, Evangelho de Filipe, Evangelho da Verdade, Evangelho de Maria, Evangelho de Judas. (2) Evangelhos Judaizantes (Ebionitas): Enfatizam a observância da lei judaica, negam a divindade de Cristo (adocionismo), e rejeitam o nascimento virginal. Exemplos: Evangelho dos Ebionitas, Evangelho dos Nazarenos, Evangelho dos Hebreus. (3) Evangelhos de Infância: Narram milagres da infância de Jesus (não mencionados nos canônicos), muitas vezes fantasiosos e lendários. Exemplos: Proto-Evangelho de Tiago, Evangelho do Pseudo-Mateus, Evangelho de Tomé (Infância), História de José o Carpinteiro. (4) Evangelhos de Paixão e Ressurreição: Ampliam os relatos da paixão e ressurreição com detalhes lendários. Exemplos: Evangelho de Pedro, Evangelho de Nicodemos (Atos de Pilatos), Questões de Bartolomeu. (5) Fragmentos e Citações: Evangelhos perdidos conhecidos apenas por citações de Pais da Igreja. Exemplos: Evangelho dos Egípcios, Evangelho de Matias, Evangelho de Cerinto. A teologia reformada rejeita todos estes escritos como não canônicos e, na maioria dos casos, heréticos.",
            referencias: "Gálatas 1:6-9; 1 João 4:1-3; 2 João 1:7-11; Judas 1:3-4"
        },
        {
            termo: "03. Evangelho de Tomé (Códice de Nag Hammadi, c. 140-180 d.C.)",
            definicao: "O Evangelho de Tomé (Evangelho Copta de Tomé) foi descoberto em Nag Hammadi (Egito, 1945). Contém 114 ditos (logia) atribuídos a Jesus, sem narrativa. Data: provavelmente século II (140-180 d.C.), embora alguns argumentem por uma data mais precoce (c. 60-100 d.C.). Cristologia do Evangelho de Tomé: (1) Dito 1: 'Quem quer que encontre a interpretação dessas palavras não provará a morte.' - Ênfase gnóstica no conhecimento secreto. (2) Dito 3: 'O reino de Deus está dentro de vós e fora de vós... quando vos conhecerdes a vós mesmos, sereis conhecidos.' - Ênfase no autoconhecimento gnóstico, não na fé em Cristo. (3) Dito 13: 'Jesus disse a Tomé: Eu não sou o teu mestre. Porque tu te embriagaste e te tornaste bêbado na fonte borbulhante que eu mesmo medi.' - Jesus nega ser mestre de Tomé. (4) Dito 28: 'Eu me pus no meio do mundo, e em carne me manifestei a eles.' - Possível encarnação, mas ambígua. (5) Dito 29: 'Se a carne veio a existir por causa do espírito, é uma maravilha. Mas se o espírito veio a existir por causa do corpo, é maravilha das maravilhas.' - Desprezo pelo corpo (gnóstico). (6) Dito 30: 'Onde há três deuses, eles são deuses. Onde há dois ou um, eu estou com ele.' - Possível triteísmo ou modalismo. (7) Dito 77: 'Eu sou a luz que está sobre todas as coisas. Eu sou o Todo. O Todo saiu de mim e o Todo voltou para mim.' - Visão panteísta/gnóstica. (8) Dito 114: 'Jesus disse: Eis que eu a guiarei de modo a fazê-la homem, para que também ela se torne um espírito vivo, semelhante a vós, homens.' - Misoginia gnóstica (mulher deve tornar-se homem). Contraste com os canônicos: (a) Tomé enfatiza conhecimento secreto (gnosis); canônicos enfatizam fé pública (pistis). (b) Tomé não tem narrativa da paixão e ressurreição; canônicos enfatizam a cruz. (c) Tomé é docético (nega a humanidade real de Jesus). (d) Tomé rejeita o corpo como mau (gnóstico). A teologia reformada rejeita o Evangelho de Tomé como herético (docetismo, gnosticismo).",
            referencias: "João 1:1-14; 1 João 4:2-3; 2 João 1:7; Gálatas 1:6-9"
        },
        {
            termo: "04. Evangelho de Pedro (séc. II - descoberto em 1886)",
            definicao: "O Evangelho de Pedro (Evangelho de Pedro) foi descoberto em 1886 em um túmulo em Akhmim (Egito). Data: provavelmente século II (c. 150-180 d.C.). É um evangelho fragmentário que cobre a paixão e ressurreição de Jesus (não tem nascimento nem ministério). Cristologia do Evangelho de Pedro: (1) Docetismo explícito: 'E ele [Jesus] estava em silêncio, como se não sentisse dor' (cap. 4). 'E eles o tiraram e o penduraram... E eles o penduraram, e o amarraram. E eles o pregaram... e ele estava em silêncio, como se não sentisse dor' (cap. 5-6). (2) Na cruz: 'E eles trouxeram dois malfeitores e o crucificaram no meio deles... E o Senhor clamou: 'Poder meu, poder meu, tu me abandonaste!'... E depois de dizer isso, foi elevado' (cap. 5). Nota: 'Poder meu, poder meu' (não 'Deus meu, Deus meu'). (3) Ressurreição: Dois anjos descem do céu, entram no sepulcro, e saem com um terceiro (Jesus), cuja cabeça ultrapassava os céus (cap. 10). (4) Negação da humanidade de Jesus: 'Ele foi elevado' (docetismo). Contraste com os canônicos: (a) Pedro é docético (nega o sofrimento real de Jesus); canônicos afirmam a humanidade real (João 1:14; Hebreus 4:15). (b) Pedro modifica a palavra de Jesus na cruz ('Poder meu' em vez de 'Deus meu'). (c) Pedro tem uma visão extravagante da ressurreição (cabeça de Jesus ultrapassando os céus). (d) Pedro não tem narrativa do nascimento ou ministério. A teologia reformada rejeita o Evangelho de Pedro como herético (docetismo).",
            referencias: "João 1:14; João 19:28-30; Mateus 27:46; Hebreus 2:14-18; Hebreus 4:15; 1 João 4:2-3"
        },
        {
            termo: "05. Evangelho de Judas (séc. II - descoberto na década de 1970)",
            definicao: "O Evangelho de Judas foi descoberto na década de 1970 no Egito e traduzido em 2006. Data: provavelmente século II (c. 130-170 d.C.). É um texto gnóstico que retrata Judas Iscariotes como o único discípulo que entendeu verdadeiramente Jesus. Cristologia do Evangelho de Judas: (1) Jesus aparece aos discípulos em forma humana, mas ri de sua oração (p. 34). (2) Jesus ensina a Judas sobre o 'deus do bem' (verdadeiro Deus) e o 'deus do mal' (demiurgo) - dualismo gnóstico. (3) Judas é separado dos outros discípulos e recebe revelação secreta. (4) A morte de Jesus é interpretada como a libertação do espírito do corpo (docetismo). (5) Jesus diz a Judas: 'Tu sacrificarás o homem que me serve de vestimenta' - o corpo humano de Jesus é apenas uma vestimenta. (6) Judas é elogiado, não condenado. Contraste com os canônicos: (a) Judas retrata Judas Iscariotes como herói; canônicos o retratam como traidor (Mateus 26:14-16; 27:3-5; João 13:27). (b) Judas tem dualismo gnóstico (deus bom vs. deus mau); canônicos afirmam um só Deus (Deuteronômio 6:4; Isaías 45:5-7). (c) Judas é docético (nega a encarnação real); canônicos afirmam a encarnação (João 1:14; 1 João 4:2-3). A teologia reformada rejeita o Evangelho de Judas como herético (gnosticismo, docetismo).",
            referencias: "Mateus 26:14-16; Mateus 27:3-5; Lucas 22:3-6; João 13:27; Atos 1:16-20; 1 João 4:2-3"
        },
        {
            termo: "06. Evangelho de Maria (Magdalena) (séc. II - descoberto em 1896)",
            definicao: "O Evangelho de Maria (Evangelho de Maria Madalena) foi descoberto em 1896 no Cairo. Data: provavelmente século II (c. 120-180 d.C.). É um texto gnóstico que apresenta Maria Madalena como a discípula favorita de Jesus e receptora de revelação secreta. Cristologia do Evangelho de Maria: (1) Após a ressurreição, Jesus ensina os discípulos sobre a natureza do pecado e a salvação através do conhecimento (gnosis). (2) Jesus diz: 'Não há pecado, mas vós é que pecais quando fazeis as coisas que são da natureza do pecado' (p. 7) - negação do pecado objetivo. (3) A matéria é vista como má: 'Toda natureza, toda forma, toda criatura existe umas nas outras e serão dissolvidas em sua própria raiz' (p. 7). (4) Maria Madalena recebe revelação sobre a ascensão da alma através das potestades celestiais. (5) Os discípulos (Pedro, André) duvidam de Maria porque ela é mulher, mas Levi a defende. Contraste com os canônicos: (a) Maria é gnóstico (salvação pelo conhecimento); canônicos ensinam salvação pela fé em Cristo (Romanos 10:9-10; Efésios 2:8-9). (b) Maria nega a realidade do pecado; canônicos afirmam que todos pecaram (Romanos 3:23; 1 João 1:8-10). (c) Maria despreza a matéria; canônicos afirmam que a criação é boa (Gênesis 1:31). A teologia reformada rejeita o Evangelho de Maria como herético (gnosticismo).",
            referencias: "Romanos 3:23; Romanos 10:9-10; Efésios 2:8-9; 1 João 1:8-10; Gênesis 1:31"
        },
        {
            termo: "07. Evangelho de Filipe (séc. III - Nag Hammadi)",
            definicao: "O Evangelho de Filipe foi descoberto em Nag Hammadi (1945). Data: provavelmente século III (c. 200-250 d.C.). É um texto gnóstico que discute sacramentos, relações entre homens e mulheres, e a natureza de Cristo. Cristologia do Evangelho de Filipe: (1) 'O Senhor fez todas as coisas através de um mistério. No batismo, na unção, na eucaristia, na redenção e na câmara nupcial' (p. 67). (2) 'O Senhor ressuscitou dos mortos. Ele se tornou como era, mas seu corpo era perfeitamente espiritual' (p. 11) - docetismo. (3) 'Jesus enganou a todos. Pois ele não apareceu como era, mas apareceu de modo a não ser visto por aqueles que o viam' (p. 57). (4) 'O Cristo veio para redimir alguns: os judeus, os gentios e os discípulos' (p. 53). (5) 'A verdade não veio ao mundo nua, mas veio em tipos e imagens' (p. 67). Contraste com os canônicos: (a) Filipe enfatiza rituais secretos (câmara nupcial); canônicos enfatizam fé em Cristo (Romanos 10:9). (b) Filipe tem docetismo (Jesus não apareceu como era); canônicos afirmam a verdadeira humanidade (João 1:14; Lucas 24:39-43). (c) Filipe tem visão gnóstica da verdade; canônicos afirmam que Cristo é a verdade (João 14:6). A teologia reformada rejeita o Evangelho de Filipe como herético (gnosticismo, docetismo).",
            referencias: "João 1:14; João 14:6; Lucas 24:39-43; Romanos 10:9; 1 João 1:1-4"
        },
        {
            termo: "08. Evangelho da Verdade (séc. II - Nag Hammadi)",
            definicao: "O Evangelho da Verdade foi descoberto em Nag Hammadi (1945). Data: provavelmente século II (c. 140-180 d.C.). Atribuído a Valentino, um líder gnóstico. É um tratado homilético sobre a salvação através do conhecimento (gnosis). Cristologia do Evangelho da Verdade: (1) 'O evangelho da verdade é uma alegria para aqueles que receberam a graça de conhecer o Pai através da palavra que veio do Pleroma' (p. 16). (2) 'A palavra veio ao mundo por causa daqueles que estavam em erro' (p. 22). (3) 'Ele foi pregado na cruz, tornando-se um fruto do conhecimento do Pai' (p. 18) - a cruz é apenas um símbolo do conhecimento. (4) 'Ele os tirou do erro ao dar-lhes o conhecimento' (p. 22). Contraste com os canônicos: (a) Verdade enfatiza conhecimento secreto (gnosis) como salvação; canônicos enfatizam fé na morte e ressurreição de Cristo (1 Coríntios 15:3-4). (b) Verdade minimiza a cruz; canônicos enfatizam a cruz como central (1 Coríntios 1:18-25). (c) Verdade é alegórica e mística; canônicos são históricos e confessionais. A teologia reformada rejeita o Evangelho da Verdade como herético (gnosticismo).",
            referencias: "1 Coríntios 1:18-25; 1 Coríntios 15:3-4; Gálatas 6:14; Colossenses 2:13-15"
        },
        {
            termo: "09. Evangelho dos Ebionitas (séc. II - conhecido por citações)",
            definicao: "O Evangelho dos Ebionitas é conhecido apenas por citações de Pais da Igreja (Epifânio, Jerônimo). Data: provavelmente século II (c. 130-160 d.C.). Foi usado pelos ebionitas (judeus-cristãos). Cristologia do Evangelho dos Ebionitas: (1) Adocionismo: Jesus tornou-se Filho de Deus no batismo. (2) Rejeição do nascimento virginal: Jesus era filho de José e Maria. (3) Rejeição da divindade de Cristo: Jesus era apenas um homem justo. (4) Ênfase na observância da lei judaica (circuncisão, sábado, dieta). Contraste com os canônicos: (a) Ebionitas negam a divindade de Cristo; canônicos afirmam (João 1:1,14; 20:28; Romanos 9:5; Tito 2:13). (b) Ebionitas negam o nascimento virginal; canônicos afirmam (Mateus 1:18-25; Lucas 1:26-38). (c) Ebionitas enfatizam a lei; canônicos enfatizam a graça (Gálatas 2:16; 3:10-14). A teologia reformada rejeita o Evangelho dos Ebionitas como herético (adocionismo, judaísmo).",
            referencias: "João 1:1; João 1:14; João 20:28; Mateus 1:18-25; Lucas 1:26-38; Romanos 9:5; Tito 2:13; Gálatas 2:16; Gálatas 3:10-14"
        },
        {
            termo: "10. Proto-Evangelho de Tiago (séc. II - c. 145 d.C.)",
            definicao: "O Proto-Evangelho de Tiago (também chamado Evangelho da Infância de Tiago) é um dos apócrifos mais antigos e populares. Data: c. 145 d.C. Narra a história da infância de Maria (seus pais Joaquim e Ana), o nascimento de Jesus, e a infância de Jesus. Cristologia do Proto-Evangelho: (1) Enfatiza a virgindade perpétua de Maria (antes, durante e depois do parto). (2) Maria é apresentada como uma figura sem pecado, santificada desde o ventre (precursor da Imaculada Conceição). (3) José é apresentado como um homem idoso, viúvo com filhos (os 'irmãos' de Jesus seriam filhos de José de casamento anterior). (4) O nascimento de Jesus é milagroso: uma luz brilhou, e Jesus nasceu sem dor. (5) A parteira Salomé testa a virgindade de Maria e sua mão seca é curada ao tocar o menino. Contraste com os canônicos: (a) Proto-Evangelho adiciona detalhes lendários não encontrados nos canônicos (Maria criada no templo, etc.). (b) Proto-Evangelho exalta Maria além do que as Escrituras ensinam (tendência mariológica). (c) A tradição dos 'irmãos de Jesus' como filhos de José de casamento anterior é uma tentativa de harmonizar os evangelhos, mas não é bíblica. A teologia reformada rejeita o Proto-Evangelho como não canônico e rejeita sua mariologia excessiva (virgindade perpétua, santidade imaculada de Maria).",
            referencias: "Mateus 1:18-25; Mateus 13:55-56; Lucas 1:26-38; Lucas 2:1-20; Gálatas 1:19; Judas 1:1"
        },
        {
            termo: "11. Evangelho de Nicodemos (Atos de Pilatos) (séc. IV-V)",
            definicao: "O Evangelho de Nicodemos (também chamado Atos de Pilatos) é um texto tardio (séc. IV-V) que narra a paixão, morte, ressurreição e descida de Cristo ao inferno (descensus ad inferos). Divide-se em duas partes: Atos de Pilatos (cap. 1-16) e Descida de Cristo ao Inferno (cap. 17-27). Cristologia do Evangelho de Nicodemos: (1) Pilatos testemunha a inocência de Jesus. (2) Os soldados romanos testemunham a ressurreição. (3) Descrição detalhada da descida de Cristo ao inferno: Cristo quebra as portas do inferno, liberta os patriarcas do Antigo Testamento (Adão, Abraão, Davi, etc.), e amarra Satanás. (4) Cristo é apresentado como Rei da glória que vence a morte e o inferno. Contraste com os canônicos: (a) Nicodemos adiciona detalhes lendários não encontrados nos canônicos (descrição extensa do inferno, diálogos com Satanás). (b) A teologia reformada aceita a descida ao inferno (descensus) como parte do Credo dos Apóstolos, mas interpreta como o estado de humilhação extrema (sofrimento da ira de Deus), não como uma descida literal ao inferno para pregar. (c) Calvino rejeitou a interpretação literal da descida ao inferno. A teologia reformada valoriza o Evangelho de Nicodemos como literatura cristã primitiva, mas não como Escritura canônica.",
            referencias: "Mateus 27:11-26; Lucas 23:1-25; João 18:28-19:16; Atos 2:27; Romanos 10:6-7; Efésios 4:8-10; 1 Pedro 3:18-20"
        },
        {
            termo: "12. Evangelho de Tomé (Infância) (séc. II - c. 150 d.C.)",
            definicao: "O Evangelho de Tomé (Infância) é diferente do Evangelho de Tomé (ditos). Narra milagres fantásticos de Jesus entre os 5 e 12 anos de idade. Data: c. 150 d.C. (provavelmente originário da Síria). Cristologia do Evangelho de Tomé (Infância): (1) Jesus faz pássaros de barro e os anima (cap. 2). (2) Jesus amaldiçoa uma criança que o irrita, e a criança morre (cap. 3). (3) Jesus amaldiçoa um professor que o repreende, e o professor morre (cap. 14). (4) Jesus ressuscita uma criança que caiu de um telhado (cap. 9). (5) Jesus cura o pé de um lenhador que o feriu (cap. 10). (6) Jesus é retratado como temperamental, vingativo e mágico (não compassivo). Contraste com os canônicos: (a) O Jesus do Evangelho da Infância é temperamental e vingativo; o Jesus canônico é compassivo, manso e humilde (Mateus 11:29). (b) Os milagres são fantásticos e sem propósito redentor; os milagres canônicos têm propósito (sinais do Reino). (c) O Jesus canônico nunca usou seus poderes para vingança (Lucas 9:51-56). A teologia reformada rejeita o Evangelho da Infância como lendário e herético (apresenta um Jesus incompatível com os canônicos).",
            referencias: "Mateus 11:29; Lucas 2:40-52; Lucas 9:51-56; João 2:1-11; João 20:30-31"
        },
        {
            termo: "13. Síntese: Por que a Igreja Rejeitou os Evangelhos Apócrifos",
            definicao: "A igreja primitiva rejeitou os evangelhos apócrifos do cânon do Novo Testamento por várias razões teológicas e históricas. Razões principais: (1) Datação tardia: Os apócrifos são do século II em diante, enquanto os canônicos são do século I (c. 50-95 d.C.). (2) Autoria falsa (pseudepígrafos): Os apócrifos são atribuídos falsamente a apóstolos (Pedro, Tomé, Filipe, Judas, etc.). Os canônicos têm autoria genuína ou associação apostólica (Marcos com Pedro, Lucas com Paulo). (3) Conteúdo herético: (a) Docetismo (negação da encarnação real) - Evangelho de Pedro, Tomé, Judas. (b) Gnosticismo (salvação pelo conhecimento secreto) - Tomé, Filipe, Maria, Judas, Verdade. (c) Adocionismo (negação da divindade de Cristo) - Ebionitas. (d) Dualismo gnóstico (matéria é má) - Tomé, Filipe, Maria. (e) Mariologia excessiva - Proto-Evangelho de Tiago. (4) Falta de uso generalizado: Os apócrifos não eram lidos nas igrejas primitivas; os canônicos eram lidos em todo o mundo cristão. (5) Contradições com os canônicos: Os apócrifos contradizem os evangelhos canônicos em doutrinas fundamentais (divindade de Cristo, encarnação, morte expiatória, ressurreição corporal). A teologia reformada conclui que os evangelhos canônicos são a Palavra de Deus inspirada (2 Timóteo 3:16), e os apócrifos são rejeitados como não canônicos e, em muitos casos, heréticos. 'Ainda que nós ou um anjo do céu vos anuncie outro evangelho além do que já vos temos anunciado, seja anátema' (Gálatas 1:8). Soli Deo Gloria!",
            referencias: "Lucas 1:1-4; João 20:30-31; Atos 1:1-3; Gálatas 1:8-9; 2 Timóteo 3:16-17; 2 Pedro 1:16-21; 1 João 1:1-4; 2 João 1:7-11"
        }
    ]
};