// volume/volume-33.js
window.LIVRO_DATA = {
    nome: "Volume XXXIII",
    dados: [
        {
            termo: "01. Introdução: A Tipologia de Eventos - Acontecimentos que Prefiguram Cristo",
            definicao: "A tipologia (do grego týpos - 'modelo, padrão, figura') aplica-se não apenas a pessoas e instituições, mas também a eventos históricos que servem como prefigurações divinamente ordenadas de realidades maiores que se cumprem em Cristo. O apóstolo Paulo declara que os eventos do êxodo no deserto 'aconteceram-lhes como figuras (týpoi), e estão escritos para aviso nosso, para quem já são chegados os fins dos séculos' (1 Coríntios 10:11). Assim como as pessoas do Antigo Testamento tipificavam Cristo, certos acontecimentos históricos (criação, queda, dilúvio, êxodo, etc.) prefiguram aspectos da pessoa e obra de Jesus Cristo. Este volume explora dezenas de acontecimentos bíblicos que servem como tipos (prefigurações) ou sombras de Cristo. A teologia reformada enfatiza que os eventos não são meras coincidências, mas são divinamente ordenados por Deus (1 Pedro 1:10-12). 'Porque todas essas coisas lhes aconteciam como figuras (týpoi)' (1 Coríntios 10:11). 'Ora, isso foi dito por figura (alegoroumena) (Gálatas 4:24).",
            referencias: "1 Coríntios 10:6; 1 Coríntios 10:11; Gálatas 4:24; Colossenses 2:17; Hebreus 8:5; Hebreus 10:1; 1 Pedro 1:10-12"
        },
        {
            termo: "02. A Criação - O Princípio e o Novo Princípio em Cristo",
            definicao: "O evento da criação (Gênesis 1:1-2:3) é o primeiro grande acontecimento que aponta para Cristo. João identifica Jesus como o Verbo criador: 'Todas as coisas foram feitas por ele, e sem ele nada do que foi feito se fez' (João 1:3). Paulo confirma: 'Porque nele foram criadas todas as coisas que há nos céus e na terra' (Colossenses 1:16). A criação também prefigura a nova criação em Cristo: 'Assim que, se alguém está em Cristo, nova criatura é; as coisas velhas já passaram; eis que tudo se fez novo' (2 Coríntios 5:17). Paralelos: (1) A criação foi 'muito boa' (Gênesis 1:31); a nova criação é perfeita em Cristo. (2) Deus descansou no sétimo dia (Gênesis 2:2-3); Cristo é o descanso do crente (Mateus 11:28-30; Hebreus 4:1-11). (3) A luz foi criada no primeiro dia (Gênesis 1:3); Cristo é a luz do mundo (João 8:12). (4) A separação das águas (Gênesis 1:6-8); Cristo separa os crentes do mundo. (5) A criação do homem à imagem de Deus (Gênesis 1:26-27); Cristo é a imagem perfeita de Deus (Colossenses 1:15). A teologia reformada vê na criação o protótipo da nova criação em Cristo.",
            referencias: "Gênesis 1:1-2:3; João 1:1-3; João 8:12; 2 Coríntios 5:17; Colossenses 1:15-17; Hebreus 4:1-11"
        },
        {
            termo: "03. A Queda - O Pecado que Exigiu o Redentor",
            definicao: "A queda de Adão e Eva no Jardim do Éden (Gênesis 3:1-24) é o evento que tornou necessária a vinda do Redentor. O proto-evangelho (Gênesis 3:15) é a primeira promessa de Cristo. Paralelos e contrastes: (1) Adão desobedeceu na árvore (Gênesis 3:6); Cristo obedeceu na árvore da cruz (Filipenses 2:8). (2) Adão e Eva se esconderam de Deus (Gênesis 3:8); Cristo se entregou voluntariamente (João 10:18). (3) As folhas de figueira não cobriram o pecado (Gênesis 3:7); o sangue de Cristo cobre o pecado (1 Pedro 1:18-19). (4) Deus fez túnicas de pele (sacrifício de animais) para Adão e Eva (Gênesis 3:21); Cristo é o Cordeiro de Deus que tira o pecado do mundo (João 1:29). (5) A maldição da terra (Gênesis 3:17-19); Cristo redime a criação (Romanos 8:19-22). (6) A expulsão do Jardim (Gênesis 3:23-24); Cristo nos restaura ao paraíso (Lucas 23:43; Apocalipse 22:1-5). A teologia reformada vê na queda o problema que somente Cristo pode resolver.",
            referencias: "Gênesis 3:1-24; João 1:29; Romanos 5:12-21; 1 Coríntios 15:21-22; Filipenses 2:8; 1 Pedro 1:18-19; Apocalipse 22:1-5"
        },
        {
            termo: "04. O Dilúvio - Juízo e Salvação pela Arca (Tipo de Cristo)",
            definicao: "O dilúvio nos dias de Noé (Gênesis 6-9) é um evento que prefigura o juízo final e a salvação somente em Cristo. Jesus relacionou o dilúvio com sua segunda vinda: 'Assim como nos dias de Noé... assim será também a vinda do Filho do Homem' (Mateus 24:37-39). Paralelos: (1) A arca é um tipo de Cristo: quem entra na arca é salvo; quem está fora perece (João 14:6; Atos 4:12). (2) A arca foi construída segundo a especificação de Deus; Cristo é o único caminho de salvação. (3) O dilúvio foi juízo sobre o pecado (Gênesis 6:5-7); a cruz foi juízo sobre o pecado (Romanos 3:25-26). (4) A arca flutuou sobre as águas do juízo; Cristo venceu o juízo de Deus. (5) A arca levou Noé e sua família à nova criação (após o dilúvio); Cristo leva seu povo à nova criação (Apocalipse 21-22). (6) O arco-íris (aliança) apareceu após o dilúvio (Gênesis 9:12-17); Cristo é o mediador da nova aliança (Hebreus 8:6). (7) A pomba que retornou com o ramo de oliveira (Gênesis 8:11) é tipo do Espírito Santo e da paz em Cristo. (8) Pedro compara o batismo com a salvação pela arca (1 Pedro 3:20-21). A teologia reformada vê no dilúvio e na arca o tipo do juízo e da salvação somente em Cristo.",
            referencias: "Gênesis 6-9; Mateus 24:37-39; Lucas 17:26-27; João 14:6; Atos 4:12; Romanos 3:25-26; 1 Pedro 3:20-21; 2 Pedro 2:5; 2 Pedro 3:6-7"
        },
        {
            termo: "05. A Torre de Babel - A Confusão das Línguas e o Pentecostes",
            definicao: "O evento da Torre de Babel (Gênesis 11:1-9), onde Deus confundiu as línguas dos construtores, prefigura o Pentecostes (Atos 2:1-13), onde o Espírito Santo capacitou os apóstolos a falar em outras línguas. Paralelos e contrastes: (1) Em Babel, os homens queriam fazer um nome para si mesmos (Gênesis 11:4); no Pentecostes, os apóstolos proclamaram o nome de Cristo (Atos 2:14-36). (2) Em Babel, Deus confundiu as línguas (Gênesis 11:7); no Pentecostes, Deus uniu as línguas na compreensão do evangelho (Atos 2:5-11). (3) Babel foi o início da dispersão dos povos (Gênesis 11:8-9); o Pentecostes foi o início da unificação dos povos em Cristo (Efésios 2:11-22). (4) Babel representa o orgulho humano; o Pentecostes representa a graça divina. (5) A queda de Babel prefigura a queda da Babilônia (Apocalipse 18); a nova Jerusalém é a cidade onde Deus habita com seu povo (Apocalipse 21-22). A teologia reformada vê em Babel o tipo da dispersão do pecado e no Pentecostes o tipo da unidade em Cristo.",
            referencias: "Gênesis 11:1-9; Atos 2:1-13; Efésios 2:11-22; Apocalipse 18; Apocalipse 21-22"
        },
        {
            termo: "06. A Chamada de Abraão - A Peregrinação da Fé",
            definicao: "A chamada de Abraão para deixar sua terra e ir para Canaã (Gênesis 12:1-4) é um evento que prefigura o chamado de Deus em Cristo para deixar o mundo e seguir a Cristo. Paralelos: (1) Abraão deixou sua terra e parentela (Gênesis 12:1); os crentes deixam o mundo para seguir a Cristo (2 Coríntios 6:17). (2) Abraão peregrinou em Canaã (Gênesis 12:4-9); os crentes são peregrinos na terra (Hebreus 11:13-16). (3) A promessa de uma terra (Canaã) aponta para a herança celestial em Cristo (Hebreus 11:8-10). (4) Abraão viveu em tendas (Gênesis 12:8; 13:3,18); os crentes habitam temporariamente neste mundo (1 Pedro 2:11). (5) A peregrinação de Abraão prefigura a jornada da fé em Cristo. A teologia reformada vê na chamada de Abraão o tipo do chamado evangélico para seguir a Cristo.",
            referencias: "Gênesis 12:1-9; Gênesis 13:1-18; Hebreus 11:8-16; 1 Pedro 2:11; 2 Coríntios 6:17"
        },
        {
            termo: "07. O Sacrifício de Isaque - A Morte Substitutiva e a Ressurreição",
            definicao: "O evento do sacrifício de Isaque no monte Moriá (Gênesis 22:1-18) é o mais claro tipo da morte substitutiva e ressurreição de Cristo. Paralelos: (1) Isaque era o 'filho único' e 'amado' de Abraão (Gênesis 22:2); Cristo é o Filho unigênito e amado do Pai (João 3:16; Mateus 3:17). (2) Isaque carregou a lenha para o seu próprio sacrifício (Gênesis 22:6); Cristo carregou a sua cruz (João 19:17). (3) O sacrifício ocorreu no monte Moriá (Gênesis 22:2), o mesmo local onde o templo foi construído e onde Cristo foi crucificado (2 Crônicas 3:1). (4) Isaque foi oferecido e depois libertado (Hebreus 11:19 diz que Abraão 'considerou que Deus era poderoso até para o ressuscitar dos mortos'); Cristo morreu e ressuscitou. (5) Deus proveu um cordeiro (carneiro) em lugar de Isaque (Gênesis 22:13); Deus proveu o Cordeiro (Cristo) em lugar dos pecadores (João 1:29). (6) O nome 'Moriá' significa 'Deus proverá' (Gênesis 22:14); Deus proveu a salvação em Cristo. A teologia reformada vê no sacrifício de Isaque o tipo mais claro da expiação vicária e da ressurreição.",
            referencias: "Gênesis 22:1-18; 2 Crônicas 3:1; João 1:29; João 3:16; João 19:17; Hebreus 11:17-19"
        },
        {
            termo: "08. O Casamento de Isaque e Rebeca - O Amor do Noivo pela Noiva",
            definicao: "O evento do casamento de Isaque com Rebeca (Gênesis 24) prefigura o casamento de Cristo (o Noivo) com a igreja (a noiva). Paralelos: (1) Abraão enviou seu servo (Eliézer) para buscar uma noiva para Isaque (Gênesis 24:2-4); Deus Pai enviou o Espírito Santo para buscar a igreja para Cristo (João 14:16-17,26; 16:7). (2) O servo pediu um sinal (Gênesis 24:12-14); o Espírito Santo convence o mundo do pecado, da justiça e do juízo (João 16:8-11). (3) Rebeca estava em seu poço (Gênesis 24:15-20); a igreja é encontrada no mundo. (4) Rebeca foi convidada a ir com o servo (Gênesis 24:57-58); a igreja é convidada a vir para Cristo (Mateus 11:28). (5) Rebeca deixou sua família e sua terra (Gênesis 24:58); os crentes deixam o mundo para seguir a Cristo (Lucas 14:26). (6) Rebeca viajou com o servo (Gênesis 24:61); a igreja é guiada pelo Espírito. (7) Isaque saiu ao campo para encontrar Rebeca (Gênesis 24:62-65); Cristo virá buscar sua noiva na parusia (1 Tessalonicenses 4:16-17). (8) Isaque amava Rebeca e foi consolado (Gênesis 24:67); Cristo ama a igreja (Efésios 5:25-27). A teologia reformada vê neste casamento o tipo do amor de Cristo pela igreja.",
            referencias: "Gênesis 24:1-67; Mateus 11:28; Lucas 14:26; João 14:16-17; João 16:7-11; 1 Tessalonicenses 4:16-17; Efésios 5:25-27"
        },
        {
            termo: "09. A Escada de Jacó - A Conexão entre o Céu e a Terra",
            definicao: "O evento da escada de Jacó em Betel (Gênesis 28:10-22) prefigura Cristo como o único mediador entre o céu e a terra. Jesus aplicou este tipo a si mesmo: 'Na verdade, na verdade vos digo que vereis o céu aberto, e os anjos de Deus subindo e descendo sobre o Filho do Homem' (João 1:51). Paralelos: (1) Jacó viu uma escada que ligava a terra ao céu (Gênesis 28:12); Cristo é a escada que liga o céu e a terra (João 1:51). (2) Os anjos subiam e desciam pela escada (Gênesis 28:12); os anjos servem a Cristo (Hebreus 1:6,14). (3) O SENHOR estava no topo da escada (Gênesis 28:13); Deus Pai está em Cristo. (4) Deus fez promessas a Jacó (Gênesis 28:13-15); todas as promessas são 'sim' em Cristo (2 Coríntios 1:20). (5) Jacó ungiu a pedra (Gênesis 28:18); Cristo é a pedra angular (Efésios 2:20). (6) Jacó chamou o lugar de Betel ('casa de Deus', Gênesis 28:19); Cristo é a casa de Deus (João 2:19-21). A teologia reformada vê na escada de Jacó o tipo da mediação exclusiva de Cristo.",
            referencias: "Gênesis 28:10-22; João 1:51; 2 Coríntios 1:20; Efésios 2:20; Hebreus 1:14"
        },
        {
            termo: "10. A Luta de Jacó com o Anjo - A Oração Agonizante e a Vitória",
            definicao: "O evento da luta de Jacó com o Anjo do SENHOR em Peniel (Gênesis 32:24-32) prefigura a oração agonizante de Cristo no Getsêmani e sua vitória sobre as forças do mal. Paralelos: (1) Jacó lutou sozinho com o Anjo (Gênesis 32:24); Cristo orou sozinho no Getsêmani (Mateus 26:36-46). (2) A luta durou a noite toda (Gênesis 32:24); a agonia de Cristo foi durante a noite (Lucas 22:39-46). (3) O Anjo tocou o quadril de Jacó, ferindo-o (Gênesis 32:25); Cristo foi ferido na cruz (Isaías 53:5). (4) Jacó disse: 'Não te deixarei ir, se me não abençoares' (Gênesis 32:26); Cristo perseverou na oração (Mateus 26:44). (5) O nome de Jacó foi mudado para Israel ('aquele que luta com Deus', Gênesis 32:28); os crentes recebem um novo nome em Cristo (Apocalipse 2:17). (6) Jacó viu a Deus face a face e sobreviveu (Gênesis 32:30); os crentes verão a Deus face a face em Cristo (1 Coríntios 13:12; 1 João 3:2). A teologia reformada vê nesta luta o tipo da oração, perseverança e vitória em Cristo.",
            referencias: "Gênesis 32:24-32; Isaías 53:5; Mateus 26:36-46; Lucas 22:39-46; 1 Coríntios 13:12; 1 João 3:2; Apocalipse 2:17"
        },
        {
            termo: "11. A Venda de José - O Sofrimento que Resultou em Salvação",
            definicao: "O evento da venda de José pelos seus irmãos (Gênesis 37:12-36) é um dos mais claros tipos da rejeição e traição de Cristo, que resultou em salvação para muitos. Paralelos: (1) José foi odiado por seus irmãos (Gênesis 37:4-5); Cristo foi odiado por seus irmãos judeus (João 15:24-25). (2) José foi enviado por seu pai aos seus irmãos (Gênesis 37:13-14); Cristo foi enviado pelo Pai ao mundo (João 3:16). (3) José foi despido de sua túnica (Gênesis 37:23); Cristo foi despido de suas vestes (Mateus 27:28). (4) José foi vendido por 20 moedas de prata (Gênesis 37:28); Cristo foi vendido por 30 moedas de prata (Mateus 26:14-16). (5) José foi lançado na cisterna (Gênesis 37:24); Cristo foi lançado na morte. (6) A túnica de José foi mergulhada em sangue (Gênesis 37:31); o sangue de Cristo foi derramado. (7) José foi injustamente acusado e preso (Gênesis 39:7-20); Cristo foi injustamente acusado e preso (Mateus 26:59-61). (8) José foi exaltado depois do sofrimento (Gênesis 41:14-44); Cristo foi exaltado depois da ressurreição (Filipenses 2:9-11). (9) José salvou seu povo da fome (Gênesis 45:5-11); Cristo salva seu povo do pecado e da morte (Mateus 1:21). (10) José perdoou seus irmãos (Gênesis 45:4-8; 50:15-21); Cristo perdoa seus algozes (Lucas 23:34). A teologia reformada vê na venda de José o tipo do sofrimento redentor.",
            referencias: "Gênesis 37:12-36; Gênesis 39:7-20; Gênesis 45:4-11; Mateus 1:21; Mateus 26:14-16; Mateus 26:59-61; Lucas 23:34; João 15:24-25; Filipenses 2:9-11"
        },
        {
            termo: "12. O Êxodo do Egito - A Libertação da Escravidão",
            definicao: "O evento do êxodo (Êxodo 3-15), a libertação de Israel da escravidão do Egito, é o grande tipo da libertação do pecado por Cristo. Paulo aplica este tipo à experiência cristã: 'Nossos pais... foram todos batizados em Moisés, na nuvem e no mar' (1 Coríntios 10:1-2). Paralelos: (1) Israel estava escravizado no Egito (Êxodo 1:8-14); a humanidade está escravizada pelo pecado (João 8:34; Romanos 6:16-18). (2) Deus enviou Moisés como libertador (Êxodo 3:7-10); Deus enviou Cristo como Libertador (João 8:36; Gálatas 5:1). (3) As pragas do Egito foram juízos sobre os deuses egípcios (Êxodo 7-12); a cruz foi juízo sobre o pecado (Romanos 3:25-26). (4) O sangue do cordeiro pascal protegeu Israel da morte (Êxodo 12:1-13); o sangue de Cristo nos protege da ira de Deus (Romanos 5:9). (5) A travessia do Mar Vermelho (Êxodo 14) prefigura o batismo (1 Coríntios 10:1-2; 1 Pedro 3:20-21). (6) A libertação do Egito prefigura a libertação do pecado. A teologia reformada vê no êxodo o grande tipo da redenção em Cristo.",
            referencias: "Êxodo 1-15; Êxodo 3:7-10; Êxodo 7-12; Êxodo 12:1-13; Êxodo 14; João 8:34; Romanos 5:9; Romanos 6:16-18; 1 Coríntios 10:1-2; Gálatas 5:1; 1 Pedro 3:20-21"
        },
        {
            termo: "13. O Maná no Deserto - O Pão do Céu",
            definicao: "O evento do maná (Êxodo 16:1-36) prefigura Cristo como o verdadeiro pão do céu. Jesus aplicou este tipo a si mesmo: 'Eu sou o pão da vida; aquele que vem a mim não terá fome; e quem crê em mim nunca terá sede' (João 6:35). 'Vossos pais comeram o maná no deserto e morreram... Eu sou o pão vivo que desceu do céu' (João 6:49-51). Paralelos: (1) O maná desceu do céu (Êxodo 16:4); Cristo desceu do céu (João 6:33,38,50). (2) O maná era dom gratuito de Deus (Êxodo 16:15); Cristo é o dom gratuito de Deus (Romanos 6:23). (3) O maná devia ser colhido diariamente (Êxodo 16:4); devemos buscar a Cristo diariamente. (4) O maná sustentava a vida física (Êxodo 16:35); Cristo sustenta a vida eterna (João 6:51). (5) Aquele que comia o maná podia morrer (João 6:49); aquele que come o pão da vida viverá para sempre (João 6:51). A teologia reformada vê no maná o tipo do alimento espiritual que é Cristo.",
            referencias: "Êxodo 16:1-36; João 6:31-58; Romanos 6:23"
        },
        {
            termo: "14. A Rocha Ferida - A Água da Vida",
            definicao: "O evento da rocha ferida em Meribá (Êxodo 17:1-7; Números 20:7-13) prefigura Cristo como a rocha ferida de onde flui água viva. Paulo identifica a rocha com Cristo: 'E beberam todos da mesma bebida espiritual, porque bebiam da pedra espiritual que os seguia; e a pedra era Cristo' (1 Coríntios 10:4). Paralelos: (1) A rocha foi ferida por Moisés (Êxodo 17:6); Cristo foi ferido por Deus (Isaías 53:5). (2) Da rocha ferida jorrou água (Êxodo 17:6); de Cristo ferido flui água viva (João 4:10-14; 7:37-39). (3) A água saciou a sede do povo; Cristo sacia a sede espiritual. (4) A rocha seguia o povo (tradição rabínica); Cristo está sempre conosco (Mateus 28:20). (5) Moisés feriu a rocha duas vezes (Números 20:11), tipologicamente errado; Cristo foi ferido uma só vez (Hebreus 9:28). A teologia reformada vê na rocha ferida o tipo da água viva que flui de Cristo.",
            referencias: "Êxodo 17:1-7; Números 20:7-13; Isaías 53:5; João 4:10-14; João 7:37-39; 1 Coríntios 10:4; Hebreus 9:28"
        },
        {
            termo: "15. O Tabernáculo e o Templo - A Habitação de Deus com os Homens",
            definicao: "O evento da construção do tabernáculo (Êxodo 25-40) e do templo (1 Reis 5-8) prefigura Cristo como a verdadeira habitação de Deus com os homens. João diz que 'o Verbo se fez carne, e habitou (tabernaculou) entre nós' (João 1:14). Jesus disse: 'Destruí este templo, e em três dias o levantarei' (João 2:19-21). Paralelos: (1) O tabernáculo era o lugar onde Deus habitava (Êxodo 25:8); Cristo é Emanuel, 'Deus conosco' (Mateus 1:23). (2) O Santo dos Santos era onde a glória de Deus habitava; Cristo é a glória de Deus (Hebreus 1:3). (3) O véu do templo separava o homem de Deus (Êxodo 26:31-33); o véu se rasgou na morte de Cristo (Mateus 27:51), abrindo o acesso a Deus (Hebreus 10:19-22). (4) O propiciatório (tampa da arca) era onde o sangue era aspergido (Levítico 16); Cristo é a propiciação pelos nossos pecados (Romanos 3:25; 1 João 2:2). (5) O altar de holocausto era onde os sacrifícios eram oferecidos; Cristo se ofereceu na cruz (Hebreus 9:14). (6) O candelabro (menorá) fornecia luz; Cristo é a luz do mundo (João 8:12). (7) A mesa dos pães da proposição tinha pães; Cristo é o pão da vida (João 6:35). A teologia reformada vê no tabernáculo e no templo o tipo da habitação de Deus em Cristo.",
            referencias: "Êxodo 25-40; 1 Reis 5-8; Mateus 1:23; Mateus 27:51; João 1:14; João 2:19-21; João 6:35; João 8:12; Romanos 3:25; 2 Coríntios 5:19; Hebreus 1:3; Hebreus 9:14; Hebreus 10:19-22"
        },
        {
            termo: "16. A Serpente de Bronze - O Levantamento de Cristo na Cruz",
            definicao: "O evento da serpente de bronze (Números 21:4-9) prefigura o levantamento de Cristo na cruz. Jesus aplicou este tipo a si mesmo: 'E, como Moisés levantou a serpente no deserto, assim importa que o Filho do Homem seja levantado; para que todo aquele que nele crê não pereça, mas tenha a vida eterna' (João 3:14-15). Paralelos: (1) O pecado de Israel foi punido com serpentes abrasadoras (Números 21:6); o pecado da humanidade foi punido na cruz. (2) Deus ordenou que Moisés fizesse uma serpente de bronze (Números 21:8); Deus enviou seu Filho em semelhança de carne pecaminosa (Romanos 8:3). (3) A serpente foi levantada em um poste (Números 21:8-9); Cristo foi levantado na cruz (João 12:32-33). (4) Quem olhasse para a serpente vivia (Números 21:9); quem crê em Cristo tem vida eterna (João 3:15-16). (5) A serpente de bronze tinha forma de serpente (mas não era venenosa); Cristo foi feito pecado (2 Coríntios 5:21), mas não tinha pecado. A teologia reformada vê na serpente de bronze o tipo da expiação vicária.",
            referencias: "Números 21:4-9; João 3:14-15; João 12:32-33; Romanos 8:3; 2 Coríntios 5:21"
        },
        {
            termo: "17. O Bezerro de Ouro - A Idolatria e a Intercessão de Moisés",
            definicao: "O evento do bezerro de ouro (Êxodo 32:1-35) prefigura o pecado de idolatria e a necessidade de um mediador. Moisés intercedeu por Israel, prefigurando a intercessão de Cristo. Paralelos: (1) Israel pecou ao fazer o bezerro de ouro (Êxodo 32:1-6); a humanidade pecou contra Deus (Romanos 3:23). (2) Deus se irou contra Israel (Êxodo 32:9-10); a ira de Deus está sobre o pecado (Romanos 1:18). (3) Moisés intercedeu por Israel (Êxodo 32:11-14,30-32); Cristo intercede por nós (Romanos 8:34; Hebreus 7:25). (4) Moisés disse: 'Perdoa o seu pecado; se não, risca-me do teu livro' (Êxodo 32:32); Cristo ofereceu a si mesmo em nosso lugar (Isaías 53:5-6). (5) O bezerro de ouro foi queimado e moído (Êxodo 32:20); o pecado foi julgado na cruz. A teologia reformada vê neste evento o tipo do pecado humano e da necessidade de intercessão em Cristo.",
            referencias: "Êxodo 32:1-35; Isaías 53:5-6; Romanos 1:18; Romanos 3:23; Romanos 8:34; Hebreus 7:25"
        },
        {
            termo: "18. O Dia da Expiação (Yom Kippur) - O Sacrifício Definitivo",
            definicao: "O evento anual do Dia da Expiação (Yom Kippur, Levítico 16) prefigura o sacrifício definitivo de Cristo. A Epístola aos Hebreus desenvolve este tipo extensivamente (Hebreus 9-10). Paralelos: (1) O sumo sacerdote entrava no Santo dos Santos uma vez por ano com sangue de animais (Levítico 16:2-3); Cristo entrou no céu uma vez por todas com seu próprio sangue (Hebreus 9:11-12). (2) O sumo sacerdote oferecia sacrifícios por seus próprios pecados e pelos pecados do povo (Levítico 16:6); Cristo não tinha pecados próprios (Hebreus 7:26-27). (3) Dois bodes: um sacrificado (tipo da morte de Cristo) e o outro (Azazel) enviado ao deserto (tipo da remoção dos pecados) (Levítico 16:7-10,20-22). (4) O sangue era aspergido sobre o propiciatório (Levítico 16:14-15); o sangue de Cristo foi derramado (Romanos 3:25). (5) O sacrifício era repetido anualmente (Levítico 16:34); o sacrifício de Cristo foi único e definitivo (Hebreus 9:25-28; 10:10-14). (6) O sumo sacerdote saía e abençoava o povo (Levítico 16:23-25); Cristo ascendeu e abençoa seu povo (Lucas 24:50-51). A teologia reformada vê no Dia da Expiação o tipo mais claro do sacrifício de Cristo.",
            referencias: "Levítico 16:1-34; Levítico 23:26-32; Números 29:7-11; Romanos 3:25; Hebreus 7:26-27; Hebreus 9:1-28; Hebreus 10:1-18"
        },
        {
            termo: "19. A Travessia do Jordão - A Morte e a Entrada na Terra Prometida",
            definicao: "O evento da travessia do rio Jordão (Josué 3-4) prefigura a morte e a entrada na terra prometida (a nova criação) em Cristo. Paralelos: (1) O Jordão separava o deserto da terra prometida; a morte separa esta vida da nova criação. (2) Josué (Yeshua) conduziu o povo através do Jordão (Josué 3:1-17); Jesus (Yeshua) nos conduz através da morte para a vida eterna (João 14:1-3). (3) As águas do Jordão foram separadas (Josué 3:13-16); a morte foi vencida por Cristo (1 Coríntios 15:54-57). (4) As doze pedras foram colocadas no Jordão como memorial (Josué 4:1-9); o batismo é um memorial da morte e ressurreição de Cristo (Romanos 6:3-4). (5) O povo entrou na terra prometida (Josué 4:10-18); os crentes entrarão na nova criação (Apocalipse 21-22). A teologia reformada vê na travessia do Jordão o tipo da morte e ressurreição em Cristo.",
            referencias: "Josué 3-4; João 14:1-3; Romanos 6:3-4; 1 Coríntios 15:54-57; Apocalipse 21-22"
        },
        {
            termo: "20. A Queda de Jericó - A Vitória pela Fé",
            definicao: "O evento da queda de Jericó (Josué 6:1-27) prefigura a vitória de Cristo sobre os inimigos espirituais (pecado, morte, Satanás). Paralelos: (1) Jericó era uma cidade fortificada (Josué 6:1); o pecado e a morte são inimigos poderosos (Romanos 5:12; 1 Coríntios 15:26). (2) Deus deu instruções específicas (Josué 6:2-5); Deus nos dá vitória em Cristo (1 Coríntios 15:57). (3) O povo marchou ao redor da cidade por sete dias (Josué 6:3-5); a vitória veio pela obediência à palavra de Deus. (4) As trombetas de chifre de carneiro (Josué 6:4-5); o evangelho é a trombeta de Deus (1 Coríntios 14:8). (5) Os muros de Jericó caíram pela fé (Josué 6:20; Hebreus 11:30); a vitória sobre o pecado é pela fé em Cristo (1 João 5:4). (6) Raabe e sua família foram salvos (Josué 6:22-25); os gentios são salvos pela fé em Cristo (Efésios 2:11-13). A teologia reformada vê na queda de Jericó o tipo da vitória da fé em Cristo.",
            referencias: "Josué 6:1-27; Romanos 5:12; 1 Coríntios 15:26-27; 1 Coríntios 15:57; Efésios 2:11-13; Hebreus 11:30; 1 João 5:4"
        },
        {
            termo: "21. A Unção de Davi - A Escolha do Rei",
            definicao: "O evento da unção de Davi por Samuel (1 Samuel 16:1-13) prefigura a unção de Cristo como Rei. Cristo é o 'Ungido' (Messias). Paralelos: (1) Davi era pastor de ovelhas (1 Samuel 16:11); Cristo é o Bom Pastor (João 10:11). (2) Davi foi escolhido por Deus, não pelos homens (1 Samuel 16:7); Cristo foi enviado pelo Pai (João 3:16). (3) O Espírito do SENHOR veio sobre Davi (1 Samuel 16:13); o Espírito desceu sobre Cristo (Mateus 3:16). (4) Davi foi ungido rei; Cristo foi ungido Profeta, Sacerdote e Rei. A teologia reformada vê na unção de Davi o tipo da unção messiânica de Cristo.",
            referencias: "1 Samuel 16:1-13; Mateus 3:16; João 3:16; João 10:11"
        },
        {
            termo: "22. Davi e Golias - A Vitória do Pequeno Guerreiro",
            definicao: "O evento da batalha de Davi contra Golias (1 Samuel 17) prefigura a vitória de Cristo sobre Satanás. Paralelos: (1) Golias era um gigante (1 Samuel 17:4-7); Satanás é um inimigo poderoso (1 Pedro 5:8). (2) Davi era um jovem pastor (1 Samuel 17:33); Cristo é o Bom Pastor que venceu o inimigo (João 10:11). (3) Davi foi armado com sua funda e cinco pedras (1 Samuel 17:40); Cristo venceu pela Palavra de Deus (Mateus 4:1-11). (4) Davi derrubou Golias com uma pedra na testa (1 Samuel 17:49); Cristo derrotou Satanás pela cruz (Colossenses 2:15). (5) A vitória de Davi trouxe libertação para Israel; a vitória de Cristo trouxe libertação para a humanidade (Gálatas 5:1). A teologia reformada vê em Davi e Golias o tipo da vitória de Cristo sobre o inimigo.",
            referencias: "1 Samuel 17:1-58; Mateus 4:1-11; João 10:11; Colossenses 2:15; Gálatas 5:1; 1 Pedro 5:8"
        },
        {
            termo: "23. O Templo de Salomão - A Casa de Deus",
            definicao: "O evento da construção e dedicação do templo de Salomão (1 Reis 5-8; 2 Crônicas 2-7) prefigura Cristo como o verdadeiro templo. Paralelos: (1) O templo era a habitação de Deus (1 Reis 8:10-13); Cristo é Emanuel (Mateus 1:23). (2) A glória de Deus encheu o templo (1 Reis 8:10-11); a glória de Deus habita em Cristo (João 1:14; 2 Coríntios 4:6). (3) Salomão dedicou o templo com oração e sacrifício (1 Reis 8:22-61); Cristo se dedicou ao Pai (João 17:1-26). (4) O templo foi destruído pelos babilônios (2 Reis 25:9); Cristo disse: 'Destruí este templo, e em três dias o levantarei' (João 2:19). (5) O templo foi reconstruído após o exílio (Esdras 3-6); a igreja é o templo de Deus (1 Coríntios 3:16). A teologia reformada vê no templo de Salomão o tipo do corpo de Cristo e da igreja.",
            referencias: "1 Reis 5-8; 2 Crônicas 2-7; Esdras 3-6; Mateus 1:23; João 1:14; João 2:19; 1 Coríntios 3:16; 2 Coríntios 4:6; João 17:1-26"
        },
        {
            termo: "24. A Rainha de Sabá - A Busca pela Sabedoria de Salomão",
            definicao: "O evento da visita da rainha de Sabá a Salomão (1 Reis 10:1-13; 2 Crônicas 9:1-12) prefigura a busca dos gentios por Cristo. Jesus aplicou este tipo a si mesmo: 'A rainha do sul se levantará no juízo com esta geração, e a condenará; porque veio dos confins da terra para ouvir a sabedoria de Salomão; e eis que está aqui quem é maior do que Salomão' (Mateus 12:42). Paralelos: (1) A rainha de Sabá ouviu a fama de Salomão (1 Reis 10:1); os gentios ouvem o evangelho de Cristo (Romanos 10:17-18). (2) A rainha viajou de longe para ver Salomão (1 Reis 10:2); os gentios vêm de todas as nações a Cristo (Atos 2:5-11). (3) A rainha trouxe presentes (1 Reis 10:2); os gentios trazem ofertas a Cristo (Romanos 15:16). (4) Salomão respondeu a todas as suas perguntas (1 Reis 10:3); Cristo responde às perguntas dos que o buscam (Mateus 11:28). (5) A rainha glorificou a Deus (1 Reis 10:9); os gentios glorificam a Deus por sua misericórdia (Romanos 15:9). A teologia reformada vê na rainha de Sabá o tipo dos gentios que buscam a sabedoria de Cristo.",
            referencias: "1 Reis 10:1-13; 2 Crônicas 9:1-12; Mateus 12:42; Lucas 11:31; Atos 2:5-11; Romanos 10:17-18; Romanos 15:9; Romanos 15:16"
        },
        {
            termo: "25. A Rainha Ester - A Intercessora pelo Seu Povo",
            definicao: "O evento de Ester intercedendo pelo seu povo diante do rei Assuero (Ester 4-8) prefigura a intercessão de Cristo por seu povo diante do Pai. Paralelos: (1) O povo judeu estava condenado à morte (Ester 3:8-15); a humanidade está condenada ao pecado e à morte (Romanos 6:23). (2) Ester arriscou sua vida para interceder (Ester 4:10-16); Cristo deu sua vida para nos salvar (João 10:11). (3) Ester disse: 'Se eu perecer, pereci' (Ester 4:16); Cristo disse: 'Pai, se queres, passa de mim este cálice' (Lucas 22:42). (4) O rei estendeu o cetro a Ester (Ester 5:2); o Pai recebe a intercessão de Cristo (Romanos 8:34). (5) Hamã foi enforcado (Ester 7:9-10); Satanás será derrotado (Apocalipse 20:10). (6) O povo foi salvo (Ester 8:9-17); o povo de Deus é salvo em Cristo (Atos 4:12). A teologia reformada vê em Ester o tipo da intercessão de Cristo.",
            referencias: "Ester 3-8; João 10:11; Lucas 22:42; Romanos 6:23; Romanos 8:34; Atos 4:12; Apocalipse 20:10"
        },
        {
            termo: "26. O Livramento de Daniel na Cova dos Leões - A Proteção Divina",
            definicao: "O evento de Daniel na cova dos leões (Daniel 6) prefigura a ressurreição de Cristo e sua vitória sobre a morte. Paralelos: (1) Daniel foi lançado na cova dos leões (Daniel 6:16); Cristo foi lançado na morte (sepultura). (2) Uma pedra foi colocada na entrada da cova (Daniel 6:17); uma pedra foi colocada na entrada do sepulcro (Mateus 27:60). (3) Deus enviou seu anjo para fechar a boca dos leões (Daniel 6:22); Deus ressuscitou Cristo da morte (Atos 2:24). (4) Daniel foi tirado da cova sem ferimento (Daniel 6:23); Cristo ressuscitou com corpo glorificado (Lucas 24:39-40). (5) Os acusadores de Daniel foram lançados na cova e devorados (Daniel 6:24); os inimigos de Cristo serão julgados (Apocalipse 20:11-15). A teologia reformada vê no livramento de Daniel o tipo da ressurreição de Cristo.",
            referencias: "Daniel 6:1-28; Mateus 27:60; Lucas 24:39-40; Atos 2:24; Apocalipse 20:11-15"
        },
        {
            termo: "27. Os Três Jovens na Fornalha - O Quarto Homem",
            definicao: "O evento de Sadraque, Mesaque e Abednego na fornalha de fogo ardente (Daniel 3:1-30) prefigura a presença de Cristo com seu povo no sofrimento. Paralelos: (1) Os três jovens foram lançados na fornalha por não adorarem a imagem de ouro (Daniel 3:13-20); os crentes são perseguidos por não adorarem ao mundo (João 15:18-21). (2) A fornalha estava aquecida sete vezes mais (Daniel 3:19); o sofrimento dos crentes pode ser intenso (1 Pedro 4:12-13). (3) O quarto homem apareceu na fornalha, 'semelhante ao Filho de Deus' (Daniel 3:25); Cristo está presente com seu povo no sofrimento (Mateus 28:20; Hebreus 13:5). (4) Os três jovens não foram queimados (Daniel 3:27); os crentes são preservados em meio às provações (1 Coríntios 10:13). (5) Nabucodonosor louvou a Deus (Daniel 3:28-29); os poderes mundanos reconhecem a Deus. A teologia reformada vê nos três jovens o tipo da proteção divina em Cristo.",
            referencias: "Daniel 3:1-30; Mateus 28:20; João 15:18-21; 1 Coríntios 10:13; 1 Pedro 4:12-13; Hebreus 13:5"
        },
        {
            termo: "28. A Visão de Daniel do Filho do Homem - O Reinado do Messias",
            definicao: "O evento da visão de Daniel do Filho do Homem (Daniel 7:13-14) prefigura o reinado celestial de Cristo. Jesus aplicou este tipo a si mesmo (Mateus 26:64; Marcos 14:62; Lucas 22:69). Paralelos: (1) Daniel viu 'um como o filho do homem vindo nas nuvens do céu' (Daniel 7:13); Cristo ascendeu às nuvens (Atos 1:9) e voltará nas nuvens (Apocalipse 1:7). (2) 'Foi-lhe dado domínio, e honra, e reino' (Daniel 7:14); Cristo recebeu toda a autoridade (Mateus 28:18). (3) 'Todos os povos, nações e línguas o servem' (Daniel 7:14); todo joelho se dobrará a Cristo (Filipenses 2:10-11). (4) 'O seu reino não será destruído' (Daniel 7:14); o reino de Cristo é eterno (Lucas 1:33). A teologia reformada vê nesta visão o tipo do reinado universal de Cristo.",
            referencias: "Daniel 7:13-14; Mateus 26:64; Mateus 28:18; Lucas 1:33; Atos 1:9; Filipenses 2:10-11; Apocalipse 1:7"
        },
        {
            termo: "29. O Livramento de Jonas - A Ressurreição após Três Dias",
            definicao: "O evento de Jonas sendo engolido por um grande peixe e vomitado após três dias (Jonas 1:17) prefigura a morte e ressurreição de Cristo. Jesus aplicou este tipo a si mesmo: 'Porque assim como Jonas esteve três dias e três noites no ventre do peixe, assim estará o Filho do Homem três dias e três noites no seio da terra' (Mateus 12:40). Paralelos: (1) Jonas foi engolido pelo peixe (Jonas 1:17); Cristo foi engolido pela morte (sepultura). (2) Jonas ficou três dias no ventre do peixe (Jonas 1:17); Cristo ficou três dias na sepultura (Mateus 12:40). (3) Jonas foi vomitado pelo peixe (Jonas 2:10); Cristo ressuscitou da morte (1 Coríntios 15:4). (4) Jonas pregou a Nínive (Jonas 3); o evangelho é pregado a todos (Mateus 28:19-20). A teologia reformada vê no livramento de Jonas o tipo mais claro da ressurreição de Cristo.",
            referencias: "Jonas 1-3; Mateus 12:39-41; Mateus 28:19-20; 1 Coríntios 15:4"
        },
        {
            termo: "30. Síntese: Cristo como o Cumprimento de Todos os Acontecimentos",
            definicao: "Todos os eventos do Antigo Testamento - a criação, a queda, o dilúvio, Babel, a chamada de Abraão, o sacrifício de Isaque, o êxodo, o maná, a rocha ferida, o tabernáculo, a serpente de bronze, o Jordão, Jericó, Davi e Golias, Ester, Daniel, Jonas, e muitos outros - apontam para a pessoa e obra de Jesus Cristo. 'Porque todas essas coisas lhes aconteciam como figuras (týpoi), e estão escritas para aviso nosso' (1 Coríntios 10:11). Cristo é o 'Amém' de todas as promessas de Deus (2 Coríntios 1:20). Ele é o 'Cordeiro de Deus que tira o pecado do mundo' (João 1:29). Ele é 'o caminho, e a verdade, e a vida' (João 14:6). A teologia reformada vê em toda a Escritura uma preparação para a vinda de Cristo, o cumprimento de todos os tipos e sombras. 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36).",
            referencias: "Romanos 11:36; 1 Coríntios 10:6; 1 Coríntios 10:11; 2 Coríntios 1:20; Gálatas 4:24; Colossenses 2:17; Hebreus 8:5; 2 Pedro 1:19-21"
        }
    ]
};