// volume/volume-83.js
window.LIVRO_DATA = {
    nome: "Volume LXXXIII",
    dados: [
        {
            termo: "01. Introdução: O Trabalho como Vocação e Mordomia",
            definicao: "O trabalho é uma ordenança divina estabelecida antes da queda. 'E tomou o Senhor Deus o homem, e o pôs no jardim do Éden para o lavrar e o guardar' (Gênesis 2:15). O trabalho não é uma maldição, mas uma vocação (chamado) de Deus. Após a queda, o trabalho tornou-se difícil (Gênesis 3:17-19), mas continua sendo uma ordenança divina. A teologia reformada (Calvino, Kuyper, Bavinck) enfatiza que todo trabalho honesto é uma vocação sagrada. 'Portanto, quer comais quer bebais, ou façais outra qualquer coisa, fazei tudo para glória de Deus' (1 Coríndios 10:31). 'Tudo o que fizerdes, fazei-o de coração, como ao Senhor' (Colossenses 3:23). Este volume explora: (1) Cristo como trabalhador. (2) O trabalho como vocação. (3) A ética do trabalho. (4) Trabalho e descanso. (5) Trabalho e família. (6) Trabalho e economia. (7) Trabalho e escatologia. 'Se alguém não quer trabalhar, também não coma' (2 Tessalonicenses 3:10).",
            referencias: "Gênesis 2:15; Gênesis 3:17-19; Êxodo 20:8-11; Provérbios 6:6-11; Efésios 4:28; 2 Tessalonicenses 3:10-12; 1 Timóteo 5:8; Colossenses 3:23-24"
        },
        {
            termo: "02. Cristo como Trabalhador - O Carpinteiro da Galileia",
            definicao: "Jesus Cristo trabalhou como carpinteiro antes de iniciar seu ministério público. 'Não é este o carpinteiro, filho de Maria, e irmão de Tiago, e de José, e de Judas e de Simão?' (Marcos 6:3). 'Não é este o filho do carpinteiro? e sua mãe não se chama Maria?' (Mateus 13:55). Significados do trabalho de Cristo: (1) Santificação do trabalho manual: Cristo, sendo Deus, trabalhou com as mãos, santificando assim todo trabalho honesto. (2) Dignidade do trabalho: o trabalho não é inferior à pregação ou ao ministério espiritual. (3) Exemplo para trabalhadores: Cristo foi obediente, diligente e honesto em seu trabalho. (4) Identificação com os trabalhadores: Cristo se identifica com todos os que trabalham. (5) Preparação para o ministério: o trabalho de carpinteiro preparou Jesus para entender as necessidades humanas. (6) Humildade: o Filho de Deus não se envergonhou do trabalho manual. A teologia reformada (Calvino, Kuyper) celebra o trabalho de Cristo como santificação de todas as ocupações honestas. 'E crescia Jesus em sabedoria, e em estatura, e em graça para com Deus e os homens' (Lucas 2:52). 'Trabalhando com as próprias mãos para sustento' (Atos 20:34).",
            referencias: "Mateus 13:55; Marcos 6:3; Lucas 2:51-52; João 5:17; Atos 18:3; 1 Tessalonicenses 2:9; 2 Tessalonicenses 3:8"
        },
        {
            termo: "03. O Trabalho como Vocação (Calling) - Servindo a Cristo no Trabalho",
            definicao: "O trabalho é uma vocação (chamado) de Deus. A teologia reformada (Lutero, Calvino, Kuyper) desenvolveu a doutrina da vocação: todo trabalho honesto é um chamado de Deus, não apenas o ministério eclesiástico. 'Porque somos feitura sua, criados em Cristo Jesus para as boas obras, as quais Deus preparou para que andássemos nelas' (Efésios 2:10). Aspectos da vocação: (1) Chamado universal: todo cristão é chamado a trabalhar. (2) Chamado específico: Deus chama cada um para uma ocupação específica (1 Coríndios 7:20). (3) Serviço a Deus: o trabalho é uma forma de servir a Deus. (4) Serviço ao próximo: o trabalho beneficia a sociedade. (5) Mordomia: usamos os dons de Deus no trabalho. (6) Glória de Deus: o trabalho deve ser para glória de Deus (1 Coríndios 10:31). (7) Contentamento: devemos estar contentes com nossa vocação (Filipenses 4:11). A teologia reformada (Kuyper) afirmou: 'Não há um centímetro quadrado do universo sobre o qual Cristo não clame: Meu!' - incluindo o local de trabalho. 'Cada um permaneça na vocação em que foi chamado' (1 Coríndios 7:20).",
            referencias: "1 Coríndios 7:17-24; Efésios 2:10; Colossenses 3:17; 1 Tessalonicenses 4:11-12; 2 Tessalonicenses 3:10-12; 1 Timóteo 5:8; Tito 3:14"
        },
        {
            termo: "04. A Ética do Trabalho - Honestidade, Diligência e Excelência",
            definicao: "A Bíblia ensina princípios éticos para o trabalho: (1) Honestidade: 'Não furtarás' (Êxodo 20:15). 'Não tenhais engano nas balanças, nem nos pesos' (Levítico 19:35). (2) Diligência: 'O que trabalha com as próprias mãos, ganha o pão' (Provérbios 12:11). 'Vai ter com a formiga, ó preguiçoso; olha para os seus caminhos e sábio sê' (Provérbios 6:6). (3) Excelência: 'Tudo o que fizerdes, fazei-o de coração, como ao Senhor' (Colossenses 3:23). (4) Integridade: 'O que anda em sinceridade, anda seguro' (Provérbios 10:9). (5) Justiça: 'Não oprimas o teu próximo, nem o roubes' (Levítico 19:13). (6) Generosidade: 'Trabalhando com as próprias mãos, tenha que repartir com o que tiver necessidade' (Efésios 4:28). (7) Descanso: o trabalho não deve ser idolatria (Êxodo 20:8-11). (8) Respeito ao empregado: 'A paga do diarista não ficará contigo até pela manhã' (Levítico 19:13). (9) Submissão aos superiores: 'Servos, obedecei a vossos senhores segundo a carne' (Efésios 6:5). (10) Liderança justa: 'Senhores, fazei o que é justo e igual aos servos' (Colossenses 4:1). A teologia reformada (Calvino, Puritanos) enfatiza a ética protestante do trabalho (Weber). 'O que furtava, não furte mais; antes trabalhe, fazendo com as mãos o que é bom' (Efésios 4:28).",
            referencias: "Êxodo 20:15; Levítico 19:13; Provérbios 6:6; Provérbios 10:4; Provérbios 12:11; Efésios 4:28; Colossenses 3:23; 1 Timóteo 6:1-2; Tito 2:9-10"
        },
        {
            termo: "05. Trabalho e Descanso - O Sábado e o Descanso em Cristo",
            definicao: "O trabalho deve ser equilibrado com o descanso. O sábado (descanso semanal) foi instituído por Deus (Gênesis 2:2-3; Êxodo 20:8-11). Jesus é o Senhor do sábado (Mateus 12:8). 'Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei. Tomai sobre vós o meu jugo... e encontrareis descanso para as vossas almas' (Mateus 11:28-30). Aspectos do descanso: (1) Descanso físico: necessário para a saúde (Salmo 127:2). (2) Descanso espiritual: descansar em Cristo (Hebreus 4:9-11). (3) Descanso sabático: um dia por semana para descanso e adoração (Êxodo 20:8-11). (4) Descanso escatológico: o descanso eterno na nova criação (Hebreus 4:9-11). (5) Equilíbrio: não ser workaholic (idolatria do trabalho). (6) Férias: períodos de descanso prolongado. (7) Lazer: atividades recreativas para renovação. A teologia reformada (Calvino, Westminster) afirma o sábado cristão (domingo) como dia de descanso e adoração. 'Lembra-te do dia do sábado, para o santificar' (Êxodo 20:8). 'O sábado foi feito por causa do homem, e não o homem por causa do sábado' (Marcos 2:27).",
            referencias: "Gênesis 2:2-3; Êxodo 20:8-11; Deuteronômio 5:12-15; Mateus 11:28-30; Marcos 2:27-28; Hebreus 4:1-11; Apocalipse 14:13"
        },
        {
            termo: "06. Trabalho e Família - Equilibrando Trabalho e Lar",
            definicao: "O cristão deve equilibrar trabalho e família, não negligenciando nenhum dos dois. 'Se alguém não cuida dos seus, e especialmente dos domésticos, negou a fé e é pior do que o infiel' (1 Timóteo 5:8). Princípios de equilíbrio: (1) Prioridade da família: a família vem antes do trabalho. (2) Tempo de qualidade: dedicar tempo à família. (3) Trabalho como sustento: não como ídolo. (4) Envolvimento na vida dos filhos: educação, lazer, oração. (5) Apoio à esposa: ajudar nas tarefas domésticas. (6) Liderança espiritual: liderar o culto doméstico. (7) Não negligenciar o cônjuge: tempo a sós com o cônjuge. (8) Férias em família: momentos de descanso juntos. (9) Trabalho em casa (home office): mais tempo com a família (quando possível). (10) Comunicação: conversar sobre o trabalho em família. A teologia reformada (Calvino, Puritanos) enfatiza que a família é a primeira instituição de Deus. 'E vós, pais, não irriteis a vossos filhos, mas criai-os na doutrina e admoestação do Senhor' (Efésios 6:4). 'Maridos, amai vossas mulheres' (Efésios 5:25).",
            referencias: "Provérbios 31:10-31; Efésios 5:22-33; Efésios 6:4; Colossenses 3:18-21; 1 Timóteo 5:8; 1 Pedro 3:7"
        },
        {
            termo: "07. Trabalho e Economia - Mordomia Financeira",
            definicao: "O trabalho deve ser acompanhado de mordomia financeira sábia. 'Honra ao Senhor com os teus bens, e com a primeira parte de todos os teus ganhos' (Provérbios 3:9). 'O que furtava, não furte mais; antes trabalhe, fazendo com as mãos o que é bom, para que tenha que repartir com o que tiver necessidade' (Efésios 4:28). Princípios financeiros: (1) Dízimo: devolver a Deus a décima parte (Malaquias 3:8-10; 1 Coríndios 16:2). (2) Ofertas: contribuir além do dízimo (2 Coríndios 9:6-7). (3) Poupança: guardar para emergências (Provérbios 6:6-8). (4) Evitar dívidas: 'o devedor é servo do credor' (Provérbios 22:7). (5) Generosidade: ajudar os pobres (Efésios 4:28). (6) Orçamento: planejar os gastos (Provérbios 27:23-24). (7) Investimento: fazer o dinheiro trabalhar (Mateus 25:14-30). (8) Testamento: planejar herança (Provérbios 13:22). (9) Seguro: proteger contra imprevistos. (10) Contentamento: 'tendo, porém, sustento e com que nos cobrirmos, estejamos contentes' (1 Timóteo 6:8). A teologia reformada (Calvino, Kuyper) valoriza a mordomia financeira. 'Não ajunteis tesouros na terra' (Mateus 6:19).",
            referencias: "Provérbios 3:9-10; Provérbios 6:6-8; Malaquias 3:8-10; Mateus 25:14-30; 1 Coríndios 16:1-2; 2 Coríndios 9:6-7; Efésios 4:28; 1 Timóteo 6:6-10; 1 Timóteo 6:17-19"
        },
        {
            termo: "08. Trabalho e Testemunho - Evangelismo no Local de Trabalho",
            definicao: "O local de trabalho é um campo missionário. 'Vós sois o sal da terra... vós sois a luz do mundo' (Mateus 5:13-14). 'Assim resplandeça a vossa luz diante dos homens, para que vejam as vossas boas obras e glorifiquem a vosso Pai, que está nos céus' (Mateus 5:16). Como testemunhar no trabalho: (1) Excelência no trabalho: trabalhe como para o Senhor (Colossenses 3:23). (2) Honestidade: não enganar (Levítico 19:35). (3) Integridade: ser confiável. (4) Amor aos colegas: ajudar os necessitados (Gálatas 6:10). (5) Paciência: suportar as dificuldades (Romanos 12:12). (6) Perdão: perdoar ofensas (Efésios 4:32). (7) Conversa edificante: evitar fofocas (Efésios 4:29). (8) Oração: orar pelos colegas (1 Timóteo 2:1). (9) Compartilhar o evangelho: quando apropriado (1 Pedro 3:15). (10) Grupos de estudo bíblico no trabalho. (11) Aconselhamento: oferecer ajuda pastoral. (12) Liderança cristã: liderar com justiça. A teologia reformada (Kuyper, Schaeffer) enfatiza que o trabalho é um campo de testemunho. 'Estai sempre preparados para responder com mansidão e temor a qualquer que vos pedir a razão da esperança que há em vós' (1 Pedro 3:15).",
            referencias: "Mateus 5:13-16; Mateus 25:31-46; Gálatas 6:10; Efésios 4:28; Colossenses 3:17; 1 Pedro 3:15"
        },
        {
            termo: "09. Trabalho e Sofrimento - Trabalhando em Meio à Adversidade",
            definicao: "O trabalho pode envolver sofrimento: desemprego, exploração, assédio, injustiça, dificuldades financeiras. A Bíblia oferece esperança. 'Bem-aventurados os que são perseguidos por causa da justiça, porque deles é o reino dos céus' (Mateus 5:10). 'Tudo posso naquele que me fortalece' (Filipenses 4:13). Conselhos para enfrentar adversidades no trabalho: (1) Confiar em Deus: 'Lançando sobre ele toda a vossa ansiedade' (1 Pedro 5:7). (2) Orar: 'Orai sem cessar' (1 Tessalonicenses 5:17). (3) Buscar ajuda: igreja, família, conselheiros. (4) Não desistir: 'Bem-aventurado o homem que persevera' (Tiago 1:12). (5) Buscar novo emprego: se necessário. (6) Aconselhamento jurídico: em casos de injustiça. (7) Apoio da igreja: diaconia. (8) Desenvolvimento profissional: cursos, capacitação. (9) Trabalho voluntário: enquanto procura emprego. (10) Esperança: 'Porque a nossa leve e momentânea tribulação produz para nós um peso eterno de glória mui excelente' (2 Coríndios 4:17). A teologia reformada (Calvino, Bonhoeffer) enfatiza que o sofrimento faz parte da vida cristã. 'No mundo tereis aflições, mas tende bom ânimo; eu venci o mundo' (João 16:33).",
            referencias: "Mateus 5:10-12; João 16:33; Romanos 8:28; 2 Coríndios 4:17; Filipenses 4:13; 1 Pedro 5:7; Apocalipse 21:4"
        },
        {
            termo: "10. Trabalho e Liderança - Servindo como Cristo",
            definicao: "A liderança no trabalho deve refletir a liderança de Cristo: servidora, humilde, justa. 'O Filho do Homem não veio para ser servido, mas para servir, e para dar a sua vida em resgate de muitos' (Mateus 20:28). 'Quem quiser tornar-se grande entre vós, seja o que vos serve' (Mateus 20:26). Princípios da liderança cristocêntrica: (1) Serviço: líder serve sua equipe. (2) Humildade: reconhecer limitações (Mateus 11:29). (3) Justiça: tratar todos com igualdade (Levítico 19:15). (4) Integridade: ser honesto (Provérbios 11:3). (5) Sabedoria: tomar decisões sábias (Tiago 1:5). (6) Paciência: suportar dificuldades (Romanos 12:12). (7) Generosidade: reconhecer o trabalho dos funcionários (Colossenses 4:1). (8) Desenvolvimento: capacitar a equipe (2 Timóteo 2:2). (9) Exemplo: liderar pelo exemplo (1 Timóteo 4:12). (10) Oração: orar pela equipe. A teologia reformada (Calvino, Kuyper) afirma que a liderança cristã é uma forma de serviço. 'Vós, senhores, fazei o que é justo e igual a vossos servos' (Colossenses 4:1).",
            referencias: "Mateus 20:25-28; João 13:12-17; Romanos 12:3-8; Filipenses 2:3-4; Colossenses 3:22-4:1; 1 Pedro 5:2-3"
        },
        {
            termo: "11. Trabalho e Escatologia - O Trabalho na Nova Criação",
            definicao: "O trabalho continuará na nova criação, mas sem cansaço, sem frustração, sem pecado. 'E ali não haverá mais maldição; e o trono de Deus e do Cordeiro estará nela, e os seus servos o servirão' (Apocalipse 22:3). 'E os seus servos o servirão' (Apocalipse 22:3). Características do trabalho na nova criação: (1) Sem cansaço (Apocalipse 21:4). (2) Sem frustração (Romanos 8:21). (3) Sem pecado (Apocalipse 21:27). (4) Significativo (serviço a Deus). (5) Criativo (nova criação). (6) Comunitário (serviço conjunto). (7) Doxológico (para glória de Deus). (8) Eterno (sem fim). (9) Alegre (plenitude de alegria). (10) Redimido (sem maldição). A esperança do trabalho redimido motiva o trabalho presente: (a) Trabalhamos para a glória de Deus agora. (b) Trabalhamos com alegria, sabendo que o trabalho será aperfeiçoado. (c) Não idolatramos o trabalho (é passageiro). (d) Descansamos em Cristo (Hebreus 4:9-11). (e) Esperamos a nova criação. A teologia reformada (Kuyper, Bavinck) vê o trabalho como parte da cultura redimida na nova criação. 'Portanto, meus amados irmãos, sede firmes e constantes, sempre abundantes na obra do Senhor' (1 Coríndios 15:58).",
            referencias: "Isaías 65:17-25; Romanos 8:19-23; 1 Coríndios 15:58; 2 Pedro 3:13; Apocalipse 21:1-5; Apocalipse 22:3-5"
        },
        {
            termo: "12. Trabalho e Aposentadoria - Servindo a Cristo em Todas as Idades",
            definicao: "A aposentadoria não significa o fim do serviço a Cristo. Os idosos continuam a servir de várias formas. 'Na velhice ainda darão frutos' (Salmo 92:14). 'Honra ao Senhor com os teus bens' (Provérbios 3:9) - incluindo na aposentadoria. Serviços para idosos: (1) Voluntariado em igrejas. (2) Aconselhamento (sabedoria da idade). (3) Ensino (Escola Dominical). (4) Oração (intercessão). (5) Apoio a famílias (cuidar de netos). (6) Missões (curto prazo). (7) Diaconia (ajudar os pobres). (8) Hospitalidade (abrir o lar). (9) Discipulado (mentorear jovens). (10) Trabalho remunerado (se desejar). (11) Estudo (cursos, seminários). (12) Escrita (livros, artigos). (13) Liderança (conselhos, comitês). (14) Música (corais, instrumentos). (15) Artes (pintura, artesanato para o Reino). Planejamento para a aposentadoria: (a) Economizar para a aposentadoria (Provérbios 6:6-8). (b) Planejar o trabalho voluntário. (c) Manter-se saudável. (d) Envolver-se na igreja. (e) Preparar herança espiritual. A teologia reformada (Calvino, Puritanos) valoriza o serviço contínuo dos idosos. 'Ensina-nos a contar os nossos dias, de tal maneira que alcancemos coração sábio' (Salmo 90:12).",
            referencias: "Salmo 71:9; Salmo 71:18; Salmo 92:12-15; Provérbios 16:31; Isaías 46:4; Tito 2:2-5; Filemom 1:9"
        },
        {
            termo: "13. Síntese: Trabalhando para a Glória de Cristo",
            definicao: "O trabalho cristão tem como objetivo final a glória de Cristo. 'Portanto, quer comais quer bebais, ou façais outra qualquer coisa, fazei tudo para glória de Deus' (1 Coríndios 10:31). 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36). Resumo da teologia do trabalho: (1) O trabalho é uma ordenança divina (Gênesis 2:15). (2) Cristo trabalhou como carpinteiro, santificando o trabalho manual (Marcos 6:3). (3) O trabalho é uma vocação (chamado) de Deus (Efésios 2:10). (4) A ética do trabalho inclui honestidade, diligência e excelência (Colossenses 3:23). (5) Trabalho e descanso devem ser equilibrados (Êxodo 20:8-11). (6) Trabalho e família devem ser equilibrados (1 Timóteo 5:8). (7) Mordomia financeira é parte do trabalho (Provérbios 3:9). (8) O local de trabalho é um campo missionário (Mateus 5:16). (9) O trabalho pode envolver sofrimento, mas Deus é fiel (João 16:33). (10) A liderança no trabalho deve ser servidora (Mateus 20:28). (11) O trabalho continuará na nova criação, redimido (Apocalipse 22:3). (12) A aposentadoria é oportunidade para novo serviço (Salmo 92:14). (13) Todo trabalho deve ser para a glória de Cristo (1 Coríndios 10:31). 'Tudo o que fizerdes, por palavra ou por obra, fazei-o em nome do Senhor Jesus, dando por ele graças a Deus Pai' (Colossenses 3:17). Soli Deo Gloria!",
            referencias: "Romanos 11:36; 1 Coríndios 10:31; Colossenses 3:17; 1 Pedro 4:10-11; Apocalipse 22:3"
        }
    ]
};