// volume/volume-68.js
window.LIVRO_DATA = {
    nome: "Volume LXVIII",
    dados: [
        {
            termo: "01. Introdução: Os Profetas como Precursores de Cristo",
            definicao: "Os profetas do Antigo Testamento foram as vozes de Deus que anunciaram a vinda do Messias. O apóstolo Pedro escreve: 'Desta salvação inquiriram e trataram diligentemente os profetas que profetizaram da graça que vos foi dada, indagando que tempo ou que ocasião de tempo o Espírito de Cristo, que estava neles, indicava, testificando antecipadamente os sofrimentos que a Cristo haviam de vir, e a glória que se lhes havia de seguir' (1 Pedro 1:10-11). Os profetas são 'precursores' do Messias, preparando o caminho para sua vinda. Jesus declarou: 'Porque, se vós crêsseis em Moisés, certamente me creríeis a mim, porque de mim escreveu ele' (João 5:46). 'E, começando por Moisés e por todos os profetas, explicava-lhes o que dele se achava em todas as Escrituras' (Lucas 24:27). Este volume explora os principais profetas do Antigo Testamento e suas profecias messiânicas: Moisés, Samuel, Natã, Isaías, Jeremias, Ezequiel, Daniel, Oseias, Joel, Amós, Jonas, Miqueias, Naum, Habacuque, Sofonias, Ageu, Zacarias, Malaquias, e outros. 'Porque a profecia nunca foi produzida por vontade de homem algum, mas os homens santos de Deus falaram inspirados pelo Espírito Santo' (2 Pedro 1:21).",
            referencias: "Isaías 1:1; Jeremias 1:1-10; Ezequiel 1:1-3; Daniel 1:1-21; Oséias 1:1; Amós 1:1; Miqueias 1:1; Zacarias 1:1-6; Lucas 24:27; Lucas 24:44; João 5:46; Atos 3:18; 1 Pedro 1:10-12; 2 Pedro 1:21"
        },
        {
            termo: "02. Moisés - O Profeta como Moisés (Deuteronômio 18:15-19)",
            definicao: "Moisés é o maior profeta do Antigo Testamento, e ele profetizou sobre um profeta semelhante a ele que viria. 'O Senhor teu Deus te levantará um profeta do meio de ti, de teus irmãos, como eu; a ele ouvireis' (Deuteronômio 18:15). 'Eis que levantarei um profeta do meio de seus irmãos, como tu, e porei as minhas palavras na sua boca, e ele lhes falará tudo o que eu lhe ordenar' (Deuteronômio 18:18). Cumprimento em Cristo: (1) Jesus é o profeta como Moisés (Atos 3:22-23; 7:37). (2) Moisés libertou Israel do Egito; Cristo nos liberta do pecado (João 8:36). (3) Moisés mediou a antiga aliança; Cristo mediou a nova aliança (Hebreus 8:6). (4) Moisés deu a lei; Cristo deu a graça e a verdade (João 1:17). (5) Moisés foi fiel como servo; Cristo como Filho (Hebreus 3:1-6). (6) A face de Moisés brilhou (Êxodo 34:29-35); Cristo foi transfigurado (Mateus 17:2). A teologia reformada (Calvino) vê em Moisés o tipo do profeta maior que é Cristo. 'Aquele profeta, pois, que Moisés disse que o Senhor Deus levantaria de entre seus irmãos, como ele, a ele ouvireis em todas as coisas em que vos falar' (Atos 3:22).",
            referencias: "Êxodo 3:1-22; Deuteronômio 18:15-19; Deuteronômio 34:10-12; Atos 3:22-23; Atos 7:37; João 1:17; João 8:36; 2 Coríndios 3:7-18; Hebreus 3:1-6; Hebreus 8:6"
        },
        {
            termo: "03. Samuel - O Profeta que Ungiu o Rei",
            definicao: "Samuel foi o último juiz e o primeiro profeta após Moisés. Ele ungiu os primeiros reis de Israel (Saul e Davi). Sua vida e ministério apontam para Cristo. (1) Samuel foi dedicado a Deus desde o ventre (1 Samuel 1:11) - tipo da consagração de Cristo. (2) O Senhor falava com Samuel (1 Samuel 3:1-21) - tipo da revelação divina em Cristo. (3) Samuel ungiu Davi como rei (1 Samuel 16:13) - tipo da unção de Cristo como Rei. (4) Samuel intercedeu por Israel (1 Samuel 7:5-9; 12:19-25) - tipo da intercessão de Cristo (Hebreus 7:25). (5) Samuel foi um profeta fiel (1 Samuel 3:19-20) - tipo da fidelidade de Cristo. (6) A aliança davídica (2 Samuel 7:12-16) foi anunciada através de Natã, mas Samuel preparou o caminho. A teologia reformada vê em Samuel o tipo do profeta que unge o Rei (Cristo) e intercede pelo povo. 'E conhecereis que o Senhor tem suscitado para si um profeta fiel' (1 Samuel 3:20). 'E falou Samuel a todo o Israel' (1 Samuel 4:1).",
            referencias: "1 Samuel 1-16; 1 Samuel 3:1-21; 1 Samuel 7:5-9; 1 Samuel 12:19-25; 1 Samuel 16:13; Atos 3:24; Atos 13:20"
        },
        {
            termo: "04. Natã - A Aliança Davídica e o Descendente Prometido (2 Samuel 7:12-16)",
            definicao: "Natã foi o profeta que anunciou a aliança davídica a Davi. 'E quando teus dias forem completos e descansares com teus pais, então farei levantar depois de ti a tua posteridade, que procederá de ti, e estabelecerei o seu reino. Este edificará uma casa ao meu nome, e eu firmarei o trono do seu reino para sempre. Eu lhe serei por pai, e ele me será por filho' (2 Samuel 7:12-14). Cumprimento em Cristo: (1) O descendente de Davi é Cristo (Mateus 1:1; Lucas 1:32-33; Romanos 1:3). (2) O trono eterno é de Cristo (Lucas 1:32-33). (3) 'Eu lhe serei por pai, e ele me será por filho' é aplicado a Cristo (Hebreus 1:5). (4) Natã também confrontou Davi por seu pecado com Bate-Seba (2 Samuel 12:1-15) - tipo do confronto profético de Cristo com os pecadores (João 8:1-11). (5) Natã foi fiel em repreender o rei - tipo da fidelidade de Cristo. A teologia reformada vê em Natã o profeta que anuncia a aliança messiânica e confronta o pecado. 'Assim diz o Senhor Deus de Israel: Eu te ungi rei sobre Israel' (2 Samuel 12:7).",
            referencias: "2 Samuel 7:12-16; 2 Samuel 12:1-15; 1 Crônicas 17:11-14; Salmo 89:3-4; Salmo 89:35-37; Isaías 9:6-7; Jeremias 23:5-6; Lucas 1:32-33; Atos 2:30; Hebreus 1:5"
        },
        {
            termo: "05. Isaías - O Profeta do Emanuel e do Servo Sofredor",
            definicao: "Isaías (Yeshayahu - 'Salvação do SENHOR') é o maior profeta messiânico do Antigo Testamento. Suas principais profecias sobre Cristo: (1) Isaías 7:14 - O nascimento virginal: 'Eis que a virgem conceberá, e dará à luz um filho, e chamará o seu nome Emanuel' (Mateus 1:22-23). (2) Isaías 9:6-7 - O Filho dado: 'Porque um menino nos nasceu, um filho se nos deu... e será o seu nome: Maravilhoso, Conselheiro, Deus Forte, Pai da Eternidade, Príncipe da Paz' (Lucas 2:11). (3) Isaías 11:1-2 - O Rebento de Jessé: 'Porque brotará um rebento do tronco de Jessé, e das suas raízes um renovo frutificará. E repousará sobre ele o Espírito do Senhor' (Mateus 3:16; Romanos 15:12). (4) Isaías 35:5-6 - Os milagres do Messias: 'Então os olhos dos cegos serão abertos... o coxo saltará como cervo' (Mateus 11:2-6). (5) Isaías 40:3 - O precursor: 'Voz do que clama no deserto: Preparai o caminho do Senhor' (Mateus 3:3). (6) Isaías 42:1-4 - O Servo Escolhido: 'Eis aqui o meu servo... porei sobre ele o meu Espírito' (Mateus 12:18-21). (7) Isaías 49:6 - Luz para os gentios: 'Te darei como luz dos gentios' (Atos 13:47). (8) Isaías 50:4-11 - O Servo obediente (Mateus 26:67). (9) Isaías 52:13-53:12 - O Servo Sofredor (Atos 8:32-35; 1 Pedro 2:22-25). (10) Isaías 61:1-3 - A unção do Messias (Lucas 4:16-21). A teologia reformada (Calvino) vê em Isaías o evangelista do Antigo Testamento. 'E disse o Senhor: Ide, e dizei a este povo: Ouvi, ouvi, e não entendei; vede, vede, e não percebais' (Isaías 6:9).",
            referencias: "Isaías 1-66; Isaías 6:1-13; Isaías 7:14; Isaías 9:6-7; Isaías 11:1-2; Isaías 35:5-6; Isaías 40:3; Isaías 42:1-4; Isaías 49:6; Isaías 50:4-11; Isaías 52:13-53:12; Isaías 61:1-3; Mateus 1:22-23; Mateus 3:3; Mateus 8:17; Mateus 12:18-21; Lucas 4:16-21; Atos 8:32-35; 1 Pedro 2:22-25"
        },
        {
            termo: "06. Jeremias - O Profeta da Nova Aliança (Jeremias 31:31-34)",
            definicao: "Jeremias (Yirmeyahu - 'O SENHOR exalta') profetizou sobre a nova aliança que seria estabelecida por Cristo. 'Eis que dias vêm, diz o Senhor, em que farei uma nova aliança com a casa de Israel e com a casa de Judá... porei a minha lei no seu interior, e a escreverei no seu coração... porque perdoarei a sua maldade, e não me lembrarei mais dos seus pecados' (Jeremias 31:31-34). Cumprimento em Cristo: (1) Jesus instituiu a nova aliança na ceia (Lucas 22:20; 1 Coríndios 11:25). (2) O perdão dos pecados é em Cristo (Hebreus 8:8-12; 10:16-17). (3) A lei escrita no coração é obra do Espírito (2 Coríndios 3:3). (4) O 'Renovo justo' (Jeremias 23:5-6; 33:14-16) é Cristo. (5) Jeremias foi o profeta sofredor (Lamentações) - tipo de Cristo. (6) Jeremias chorou sobre Jerusalém (Lamentações) - Cristo chorou sobre Jerusalém (Lucas 19:41-44). A teologia reformada vê em Jeremias o profeta da nova aliança e do coração renovado. 'Ele está assentado solitário, e em silêncio' (Lamentações 3:28). 'As misericórdias do Senhor são a causa de não sermos consumidos' (Lamentações 3:22).",
            referencias: "Jeremias 1-52; Lamentações 1-5; Jeremias 23:5-6; Jeremias 31:31-34; Jeremias 33:14-16; Lucas 19:41-44; Lucas 22:20; 1 Coríndios 11:25; 2 Coríndios 3:3; Hebreus 8:8-12; Hebreus 10:16-17"
        },
        {
            termo: "07. Ezequiel - O Profeta do Bom Pastor e do Templo",
            definicao: "Ezequiel (Yechezqel - 'Deus fortalece') profetizou sobre o Bom Pastor e o templo ideal. (1) O Bom Pastor (Ezequiel 34:11-24): 'Eis que eu mesmo procurarei as minhas ovelhas... levantarei sobre elas um só pastor, o meu servo Davi' (v.11,23). Cumprimento: Jesus é o Bom Pastor (João 10:11-18). (2) O coração novo (Ezequiel 36:24-28): 'Dar-vos-ei um coração novo... porei dentro de vós o meu Espírito' (v.26-27). Cumprimento: regeneração em Cristo (João 3:5-8). (3) O vale de ossos secos (Ezequiel 37:1-14): tipo da ressurreição espiritual e física. (4) O templo ideal (Ezequiel 40-48): tipo da presença de Deus em Cristo e na nova Jerusalém. (5) A glória do Senhor (Ezequiel 1:4-28; 43:1-5) - tipo da glória de Cristo. (6) O rio que flui do templo (Ezequiel 47:1-12) - tipo da água viva de Cristo (João 7:37-39). Ezequiel foi chamado de 'filho do homem' (cerca de 90 vezes) - título também usado por Cristo (Mateus 8:20). A teologia reformada vê em Ezequiel o profeta do Espírito e do pastor. 'Assim diz o Senhor Deus: Eis que eu estou contra os pastores, e das suas mãos requererei as minhas ovelhas' (Ezequiel 34:10).",
            referencias: "Ezequiel 1-48; Ezequiel 1:4-28; Ezequiel 34:11-24; Ezequiel 36:24-28; Ezequiel 37:1-14; Ezequiel 40-48; Ezequiel 43:1-5; Ezequiel 47:1-12; João 3:5-8; João 7:37-39; João 10:11-18; 2 Coríndios 3:3"
        },
        {
            termo: "08. Daniel - O Profeta do Filho do Homem e da Pedra",
            definicao: "Daniel (Daniyyel - 'Deus é meu juiz') profetizou sobre o Filho do Homem e o reino messiânico. (1) O Filho do Homem (Daniel 7:13-14): 'Eis que vinha nas nuvens do céu um como o filho do homem... e foi-lhe dado domínio, e honra, e reino' (v.13-14). Cumprimento: Jesus é o Filho do Homem (Mateus 26:64; Marcos 14:62; Lucas 22:69; Apocalipse 1:13). (2) A pedra cortada sem mãos (Daniel 2:34-35,44-45): a pedra que destrói os reinos e se torna um grande monte - tipo do reino de Cristo. (3) As setenta semanas (Daniel 9:24-27): 'Saberás e entenderás... que o Messias virá' (v.25). O Messias seria 'cortado' (morto) (v.26). Cumprimento: a primeira vinda de Cristo. (4) A visão do homem glorioso (Daniel 10-12): teofania de Cristo. (5) Os três jovens na fornalha (Daniel 3): o quarto homem é 'semelhante ao filho de Deus'. (6) Daniel na cova dos leões (Daniel 6): tipo da ressurreição de Cristo. A teologia reformada vê em Daniel o profeta do Filho do Homem e do reino messiânico. 'Tu, ó rei, és rei de reis... tu és a cabeça de ouro' (Daniel 2:37-38).",
            referencias: "Daniel 1-12; Daniel 2:31-45; Daniel 3:1-30; Daniel 6:1-28; Daniel 7:13-14; Daniel 9:24-27; Daniel 10-12; Mateus 24:30; Mateus 26:64; Marcos 14:62; Lucas 22:69; Apocalipse 1:13; Apocalipse 14:14"
        },
        {
            termo: "09. Os Profetas Menores - Oseias, Joel, Amós, Obadias, Jonas, Miqueias",
            definicao: "Os profetas menores (12 livros) também contêm profecias messiânicas. (1) Oseias 11:1 - 'Do Egito chamei o meu filho' (Mateus 2:15). Oseias 3:5 - 'Buscarão ao Senhor seu Deus, e a Davi, seu rei' (Cristo). (2) Joel 2:28-32 - 'Derramarei o meu Espírito sobre toda a carne' (Atos 2:16-21; Pentecostes). (3) Amós 9:11-12 - 'Levantarei o tabernáculo de Davi' (Atos 15:16-18; a inclusão dos gentios). (4) Obadias 21 - 'E o reino será do Senhor' (Cristo reinará). (5) Jonas 1:17 - 'Jonas esteve três dias e três noites no ventre do peixe' (Mateus 12:40; tipo da ressurreição de Cristo). Jonas 3 - a pregação a Nínive (tipo da pregação do evangelho aos gentios). (6) Miqueias 5:2 - 'E tu, Belém Efrata... de ti me sairá o que será Senhor em Israel' (Mateus 2:6; João 7:42). Miqueias 4:1-5 - 'O monte da casa do Senhor será estabelecido' (o reino de Cristo). Miqueias 7:18-20 - 'Quem é Deus semelhante a ti, que perdoa a iniquidade?' (perdão em Cristo). A teologia reformada vê nos profetas menores a preparação para a vinda de Cristo. 'Eis que o Senhor sairá do seu lugar... as montanhas se derreterão debaixo dele' (Miqueias 1:3-4).",
            referencias: "Oseias 1-14; Joel 1-3; Amós 1-9; Obadias 1; Jonas 1-4; Miqueias 1-7; Oseias 11:1; Joel 2:28-32; Amós 9:11-12; Miqueias 5:2; Mateus 2:6; Mateus 12:40; Atos 2:16-21; Atos 15:16-18; Romanos 9:25-26; 1 Pedro 2:10"
        },
        {
            termo: "10. Naum, Habacuque, Sofonias, Ageu, Zacarias, Malaquias",
            definicao: "Continuação dos profetas menores. (1) Naum 1:15 - 'Eis sobre os montes os pés do que traz as boas novas' (Romanos 10:15; a pregação do evangelho). (2) Habacuque 2:4 - 'O justo viverá pela sua fé' (Romanos 1:17; Gálatas 3:11; Hebreus 10:38). (3) Sofonias 3:14-17 - 'O Senhor teu Deus está no meio de ti, poderoso para te salvar' (Cristo habita no meio do seu povo). (4) Ageu 2:6-7 - 'Virei a todas as nações... e encherei esta casa de glória' (Cristo é a glória do segundo templo - Lucas 2:32). (5) Zacarias - o profeta mais messiânico entre os menores: (a) Zacarias 3:8-9 - 'Eis que eu farei vir o meu servo, o Renovo' (Cristo). (b) Zacarias 6:12-13 - 'Eis o homem cujo nome é Renovo' (Cristo). (c) Zacarias 9:9 - 'Eis que o teu rei virá... justo e salvo, humilde, montado em um jumento' (Mateus 21:4-5; João 12:14-15). (d) Zacarias 11:12-13 - 'Pesaram o meu salário, trinta moedas de prata' (Mateus 26:14-16; 27:9-10). (e) Zacarias 12:10 - 'Olharão para mim, a quem traspassaram' (João 19:37). (f) Zacarias 13:7 - 'Fere o pastor, e as ovelhas se dispersarão' (Mateus 26:31). (g) Zacarias 14:4-5 - 'Seus pés estarão naquele dia sobre o monte das Oliveiras' (a segunda vinda). (6) Malaquias 3:1 - 'Eis que eu envio o meu anjo... e o Senhor... virá de repente ao seu templo' (João Batista e Cristo). Malaquias 4:2 - 'Para vós, os que temeis o meu nome, nascerá o sol da justiça' (Cristo é a luz do mundo - João 8:12). A teologia reformada vê nestes profetas a culminação da profecia messiânica. 'Eis que eu envio o meu mensageiro, e ele preparará o caminho diante de mim' (Malaquias 3:1).",
            referencias: "Naum 1-3; Habacuque 1-3; Sofonias 1-3; Ageu 1-2; Zacarias 1-14; Malaquias 1-4; Zacarias 9:9; Zacarias 11:12-13; Zacarias 12:10; Zacarias 13:7; Zacarias 14:4-5; Malaquias 3:1; Malaquias 4:2; Mateus 21:4-5; Mateus 26:14-16; Mateus 26:31; Mateus 27:9-10; João 8:12; João 12:14-15; João 19:37; Romanos 1:17; Gálatas 3:11; Hebreus 10:38"
        },
        {
            termo: "11. A Profecia como Revelação de Cristo - O Espírito de Cristo nos Profetas",
            definicao: "O Espírito de Cristo estava nos profetas do Antigo Testamento, inspirando-os a profetizar sobre sua vinda. 'Indagando que tempo ou que ocasião de tempo o Espírito de Cristo, que estava neles, indicava, testificando antecipadamente os sofrimentos que a Cristo haviam de vir, e a glória que se lhes havia de seguir' (1 Pedro 1:11). Os profetas não entendiam completamente o que profetizavam, mas serviam às gerações futuras. 'Aos quais foi revelado que, não para si mesmos, mas para nós, eles ministravam estas coisas' (1 Pedro 1:12). A teologia reformada (Calvino) enfatiza que os profetas foram instrumentos do Espírito de Cristo. 'E a palavra do Senhor veio a mim, dizendo: Antes que te formasse no ventre, te conheci; e antes que saísses da madre, te santifiquei; às nações te dei por profeta' (Jeremias 1:4-5). 'Quem mediu as águas na concha da sua mão... quem ensinou ao Espírito do Senhor?' (Isaías 40:12-14).",
            referencias: "Isaías 40:12-14; Jeremias 1:4-5; Amós 3:7; 1 Pedro 1:10-12; 2 Pedro 1:21; Apocalipse 19:10"
        },
        {
            termo: "12. João Batista - O Último e o Maior dos Profetas (Mateus 11:11)",
            definicao: "João Batista é o último profeta do Antigo Testamento e o precursor imediato do Messias. Jesus disse: 'Em verdade vos digo que, entre os que de mulher têm nascido, não apareceu alguém maior do que João Batista' (Mateus 11:11). 'Este é aquele de quem está escrito: Eis que envio o meu anjo diante da tua face, que preparará o teu caminho diante de ti' (Mateus 11:10). As profecias sobre João Batista: (1) Isaías 40:3 - 'Voz do que clama no deserto: Preparai o caminho do Senhor' (Mateus 3:3). (2) Malaquias 3:1 - 'Eis que eu envio o meu anjo, e ele preparará o caminho diante de mim' (Mateus 11:10). (3) Malaquias 4:5-6 - 'Eis que eu vos enviarei o profeta Elias, antes que venha o grande e terrível dia do Senhor' (Mateus 11:14; Lucas 1:17). Características de João Batista: (1) 'Não sou eu o Cristo' (João 1:20). (2) 'É necessário que ele cresça e que eu diminua' (João 3:30). (3) 'Eis o Cordeiro de Deus, que tira o pecado do mundo' (João 1:29). (4) Batizou com água; Cristo batiza com o Espírito (Mateus 3:11). (5) Morreu decapitado (Mateus 14:1-12). A teologia reformada vê em João Batista o modelo do precursor que aponta para Cristo. 'E ele irá adiante dele no espírito e poder de Elias' (Lucas 1:17).",
            referencias: "Isaías 40:3; Malaquias 3:1; Malaquias 4:5-6; Mateus 3:1-12; Mateus 11:2-19; Mateus 14:1-12; Marcos 1:1-8; Lucas 1:5-25; Lucas 1:57-80; Lucas 3:1-20; João 1:19-34; João 3:22-36"
        },
        {
            termo: "13. Síntese: Cristo, o Cumprimento de Todas as Profecias",
            definicao: "Jesus Cristo é o cumprimento de todas as profecias do Antigo Testamento. 'E começando por Moisés e por todos os profetas, explicava-lhes o que dele se achava em todas as Escrituras' (Lucas 24:27). 'São estas as palavras que vos disse, estando ainda convosco, que convinha que se cumprisse tudo o que de mim está escrito na lei de Moisés, e nos profetas e nos salmos' (Lucas 24:44). Resumo dos profetas e suas profecias sobre Cristo: (1) Moisés: o profeta como Moisés (Dt 18:15-19). (2) Samuel: unção do Rei. (3) Natã: aliança davídica (2 Sm 7:12-16). (4) Isaías: Emanuel (7:14), Servo Sofredor (53). (5) Jeremias: nova aliança (31:31-34). (6) Ezequiel: Bom Pastor (34:23-24). (7) Daniel: Filho do Homem (7:13-14), as setenta semanas (9:24-27). (8) Oseias: 'Do Egito chamei o meu filho' (11:1). (9) Joel: derramamento do Espírito (2:28-32). (10) Amós: tabernáculo de Davi (9:11-12). (11) Jonas: três dias no peixe (1:17) - tipo da ressurreição. (12) Miqueias: nascimento em Belém (5:2). (13) Naum: boas novas (1:15). (14) Habacuque: o justo viverá pela fé (2:4). (15) Sofonias: o Senhor no meio do povo (3:14-17). (16) Ageu: glória do segundo templo (2:6-7). (17) Zacarias: entrada triunfal (9:9), traspassado (12:10), pastor ferido (13:7). (18) Malaquias: o mensageiro (3:1), o sol da justiça (4:2). (19) João Batista: o precursor. 'Porque todas quantas promessas há de Deus, são nele sim, e por ele amém, para glória de Deus por nós' (2 Coríndios 1:20). 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36). Soli Deo Gloria!",
            referencias: "Lucas 24:27; Lucas 24:44; Atos 3:18; Atos 10:43; Romanos 1:1-4; Romanos 11:36; 2 Coríndios 1:20; Apocalipse 1:7; Apocalipse 22:20-21"
        }
    ]
};