// volume/volume-47.js
window.LIVRO_DATA = {
    nome: "Volume XLVII",
    dados: [
        {
            termo: "01. Introdução: A Escatologia Cristocêntrica",
            definicao: "A escatologia (doutrina das últimas coisas) é a consumação da obra redentora de Cristo. A teologia reformada enfatiza que a escatologia é cristocêntrica: tudo culmina em Cristo e para a glória de Cristo. O apóstolo Paulo escreve: 'Porque ele (Cristo) deve reinar até que haja posto todos os inimigos debaixo de seus pés' (1 Coríntios 15:25). 'E, quando todas as coisas lhe estiverem sujeitas, então também o próprio Filho se sujeitará àquele que todas as coisas lhe sujeitou, para que Deus seja tudo em todos' (1 Coríntios 15:28). Este volume explora a escatologia bíblica: a segunda vinda de Cristo (parusia), a ressurreição dos mortos, o juízo final, o estado eterno (novos céus e nova terra) e o inferno. A teologia reformada rejeita tanto o pós-milenismo otimista (reino terreno de mil anos antes da parusia) quanto o pré-milenismo dispensacionalista (arrebatamento secreto), preferindo o amilenismo (o milênio é simbólico e já começou com a ascensão de Cristo). 'Ora, o Deus de esperança vos encha de todo o gozo e paz em crença, para que abundeis em esperança pelo poder do Espírito Santo' (Romanos 15:13).",
            referencias: "Daniel 7:13-14; Zacarias 14:1-9; Mateus 24-25; Atos 1:6-11; Romanos 8:18-25; 1 Coríntios 15:1-58; 1 Tessalonicenses 4:13-18; 2 Pedro 3:1-13; Apocalipse 19-22"
        },
        {
            termo: "02. A Segunda Vinda de Cristo (Parusia) - Visão Geral",
            definicao: "A segunda vinda de Cristo (parusia - 'presença, vinda') é a volta visível e gloriosa de Jesus para julgar os vivos e os mortos e consumar o seu reino. Textos principais: 'Este Jesus... há de vir assim como para o céu o vistes ir' (Atos 1:11). 'Porque o Senhor mesmo descerá do céu com alarido, e com voz de arcanjo, e com a trombeta de Deus' (1 Tessalonicenses 4:16). 'Eis que vem com as nuvens, e todo olho o verá' (Apocalipse 1:7). Características da segunda vinda: (1) Pessoal: o próprio Jesus virá, não um representante (Atos 1:11). (2) Visível: 'todo olho o verá' (Apocalipse 1:7). (3) Gloriosa: virá 'nas nuvens do céu, com poder e grande glória' (Mateus 24:30). (4) Audível: 'com alarido... com voz de arcanjo, e com a trombeta de Deus' (1 Tessalonicenses 4:16). (5) Súbita: 'como um ladrão de noite' (1 Tessalonicenses 5:2; 2 Pedro 3:10). (6) Inesperada: 'daquele dia e hora ninguém sabe' (Mateus 24:36). (7) Para juízo: 'a fim de julgar os vivos e os mortos' (2 Timóteo 4:1). (8) Para consumação: 'novos céus e nova terra' (2 Pedro 3:13). A teologia reformada rejeita o 'arrebatamento secreto' pré-tribulacionista (dispensacionalismo), ensinando que a parusia é única, visível e gloriosa. 'Ora, o Senhor, que é a esperança, vos encha de gozo e paz' (Romanos 15:13).",
            referencias: "Daniel 7:13-14; Zacarias 14:1-5; Mateus 24:1-51; Atos 1:6-11; 1 Tessalonicenses 4:13-18; 2 Tessalonicenses 1:5-10; 2 Pedro 3:1-13; Apocalipse 1:7; Apocalipse 19:11-16; Apocalipse 22:12-13,20-21"
        },
        {
            termo: "03. O Milênio (Apocalipse 20) - As Três Principais Visões",
            definicao: "O milênio (do latim mille - 'mil') é o período de mil anos mencionado em Apocalipse 20:1-6. Três visões principais: (1) Pré-milenismo: Cristo voltará antes do milênio para estabelecer um reino terreno literal de mil anos. (2) Pós-milenismo: Cristo voltará depois do milênio (um período de paz e justiça na terra antes da parusia). (3) Amilenismo: o milênio é simbólico, representando o período entre a primeira e a segunda vinda de Cristo (a era da igreja). A teologia reformada (Calvino, Westminster) adota o amilenismo: (a) O milênio de Apocalipse 20 é simbólico, não literal. (b) Satanás foi amarrado na primeira vinda de Cristo (Mateus 12:29; Colossenses 2:15). (c) Os crentes reinam com Cristo agora espiritualmente (Efésios 2:6; Colossenses 3:1-4). (d) A ressurreição dos mártires em Apocalipse 20:4-5 é espiritual (regeneração), não física. (e) O fim dos mil anos é a segunda vinda de Cristo. (f) Apocalipse 20:7-10 descreve a rebelião final (Gogue e Magogue) antes da parusia. Texto-chave: 'Bem-aventurado e santo aquele que tem parte na primeira ressurreição; sobre estes não tem poder a segunda morte; mas serão sacerdotes de Deus e de Cristo, e reinarão com ele mil anos' (Apocalipse 20:6). A teologia reformada interpreta 'primeira ressurreição' como regeneração (João 5:24-25; Efésios 2:1-10).",
            referencias: "Mateus 12:29; João 5:24-25; Colossenses 2:15; Efésios 2:1-10; Apocalipse 20:1-15"
        },
        {
            termo: "04. A Ressurreição dos Mortos (1 Coríntios 15)",
            definicao: "A ressurreição dos mortos é a doutrina de que os corpos dos mortos serão levantados no último dia. Paulo escreve: 'Porque assim como a morte veio por um homem, também a ressurreição dos mortos veio por um homem. Porque, assim como todos morrem em Adão, assim também todos serão vivificados em Cristo' (1 Coríntios 15:21-22). 'Num momento, num abrir e fechar de olhos, ante a última trombeta; porque a trombeta soará, e os mortos ressuscitarão incorruptíveis, e nós seremos transformados' (1 Coríntios 15:52). Características da ressurreição: (1) Universal: 'todos os que estão nos sepulcros ouvirão a sua voz e sairão' (João 5:28-29). (2) Distinta: 'os que fizeram o bem para a ressurreição da vida, e os que fizeram o mal para a ressurreição da condenação' (João 5:29). (3) Corporal: não é apenas espiritual; o mesmo corpo será transformado (1 Coríntios 15:35-44). (4) Glorificada: o corpo será 'semeado em corrupção, ressuscitará em incorrupção... semeado em fraqueza, ressuscitará em glória' (1 Coríntios 15:42-43). (5) Semelhante ao corpo de Cristo: 'transformará o nosso corpo vil, para ser conforme o seu corpo glorioso' (Filipenses 3:21). (6) A ordem: 'Cristo as primícias; depois os que são de Cristo, na sua vinda' (1 Coríntios 15:23). A teologia reformada afirma a ressurreição corporal como artigo de fé (Credo dos Apóstolos: 'a ressurreição do corpo'). 'Porque sabemos que, se a nossa casa terrestre deste tabernáculo se desfizer, temos de Deus um edifício, uma casa não feita por mãos, eterna, nos céus' (2 Coríntios 5:1).",
            referencias: "Jó 19:25-27; Isaías 26:19; Daniel 12:2; João 5:28-29; 2 Coríntios 5:1; Filipenses 3:21; 1 Tessalonicenses 4:13-18; 1 Coríntios 15:1-58"
        },
        {
            termo: "05. O Julgamento Final (Mateus 25:31-46; Apocalipse 20:11-15)",
            definicao: "O juízo final é o evento no qual Cristo, o Juiz, separará os justos dos ímpios para a vida eterna ou para a condenação eterna. Texto principal (Mateus 25:31-46): 'E, quando o Filho do Homem vier em sua glória, e todos os santos anjos com ele, então se assentará no trono da sua glória; e todas as nações serão reunidas diante dele, e apartará uns dos outros, como o pastor aparta dos bodes as ovelhas... Então dirá o Rei aos que estiverem à sua direita: Vinde, benditos de meu Pai, possuí por herança o reino que vos está preparado desde a fundação do mundo... Então dirá também aos que estiverem à sua esquerda: Apartai-vos de mim, malditos, para o fogo eterno, preparado para o diabo e seus anjos... E estes irão para o tormento eterno, mas os justos para a vida eterna.' Outros textos: 'E vi os mortos, grandes e pequenos, diante de Deus... e os mortos foram julgados pelas coisas que estavam escritas nos livros, segundo as suas obras' (Apocalipse 20:12). 'Porque todos devemos comparecer ante o tribunal de Cristo' (2 Coríntios 5:10). Características do juízo final: (1) Presidido por Cristo: 'O Pai a ninguém julga, mas deu ao Filho todo o juízo' (João 5:22). (2) Universal: 'todos os que estão nos sepulcros' (João 5:28). (3) Justo: 'julgará o mundo com justiça' (Atos 17:31). (4) Baseado nas obras (como evidência da fé): 'as suas obras' (Apocalipse 20:12). (5) Determinante: separação entre justos e ímpios. A teologia reformada enfatiza que o juízo é baseado nas obras, mas a justificação é pela fé (Romanos 3:28); as obras são a evidência da fé genuína (Tiago 2:14-26). 'Porque todos havemos de comparecer ante o tribunal de Cristo, para que cada um receba o que fez por meio do corpo, segundo o que praticou, o bem ou o mal' (2 Coríntios 5:10).",
            referencias: "João 5:22-29; Atos 17:31; Romanos 2:5-11; 2 Coríntios 5:10; 2 Tessalonicenses 1:5-10; Mateus 25:31-46; Apocalipse 20:11-15"
        },
        {
            termo: "06. O Juiz - Jesus Cristo (João 5:22-29; Atos 17:31)",
            definicao: "Cristo é o Juiz designado por Deus para julgar os vivos e os mortos. Textos: 'O Pai a ninguém julga, mas deu ao Filho todo o juízo, para que todos honrem o Filho como honram o Pai' (João 5:22-23). 'Porque há um dia em que há de julgar o mundo com justiça, por meio do varão que para isso ordenou, dando a todos a certeza disso, ressuscitando-o dos mortos' (Atos 17:31). 'Paulo... perante Deus e Cristo Jesus, que há de julgar os vivos e os mortos' (2 Timóteo 4:1). Características do juízo de Cristo: (1) Exclusivo: todo o juízo foi dado ao Filho. (2) Justo: julgará com justiça (Isaías 11:2-5). (3) Baseado na relação com Cristo: 'Quem crê no Filho tem a vida eterna; quem não crê no Filho não verá a vida' (João 3:36). (4) Universal: 'julgar os vivos e os mortos' (2 Timóteo 4:1). (5) Determinante: 'os que fizeram o bem para a ressurreição da vida, e os que fizeram o mal para a ressurreição da condenação' (João 5:29). A teologia reformada enfatiza que o juízo de Cristo será: (a) Com base na fé (justificação) - os crentes são aceitos pela justiça de Cristo imputada. (b) Com base nas obras (como evidência da fé) - as obras demonstram a realidade da fé. (c) Os crentes comparecerão diante de Cristo para receber recompensas, não para condenação (Romanos 8:1: 'nenhuma condenação há para os que estão em Cristo Jesus'). 'Portanto, também agora se manifestou uma vez, no fim dos séculos, para aniquilar o pecado pelo seu sacrifício. E, como aos homens está ordenado morrerem uma vez, vindo depois o juízo, assim também Cristo, oferecendo-se uma vez para tirar os pecados de muitos, aparecerá segunda vez, sem pecado, aos que o esperam para salvação' (Hebreus 9:26-28).",
            referencias: "Isaías 11:2-5; Joel 3:12; João 5:22-29; Atos 10:42; Atos 17:31; Romanos 2:16; 2 Timóteo 4:1; Hebreus 9:27-28; 1 Pedro 4:5"
        },
        {
            termo: "07. O Estado Eterno: Novos Céus e Nova Terra (Apocalipse 21-22)",
            definicao: "Após o juízo final, Deus criará novos céus e nova terra, onde os justos habitarão eternamente com Deus. Texto principal (Apocalipse 21-22): 'E vi um novo céu e uma nova terra. Porque já o primeiro céu e a primeira terra passaram, e o mar já não existe... E ouvi uma grande voz do céu que dizia: Eis aqui o tabernáculo de Deus com os homens, pois com eles habitará, e eles serão o seu povo, e o mesmo Deus estará com eles, e será o seu Deus. E Deus limpará de seus olhos toda lágrima; e não haverá mais morte, nem pranto, nem clamor, nem dor; porque já as primeiras coisas são passadas' (Apocalipse 21:1-4). 'E não vi templo nela, porque o seu templo é o Senhor Deus Todo-poderoso, e o Cordeiro. E a cidade não necessita de sol nem de lua, para que nela resplandeçam, porque a glória de Deus a tem iluminado, e o Cordeiro é a sua lâmpada' (Apocalipse 21:22-23). Características dos novos céus e nova terra: (1) Nova criação: não apenas uma reforma da antiga, mas uma nova criação (Isaías 65:17; 2 Pedro 3:13). (2) Habitação de Deus com seu povo: 'o tabernáculo de Deus com os homens' (Apocalipse 21:3). (3) Ausência de sofrimento: 'não haverá mais morte, nem pranto, nem clamor, nem dor' (Apocalipse 21:4). (4) Ausência de maldição: 'ali não haverá mais maldição' (Apocalipse 22:3). (5) Cristo como luz: 'o Cordeiro é a sua lâmpada' (Apocalipse 21:23). (6) Vida abundante: 'o rio da água da vida... a árvore da vida' (Apocalipse 22:1-2). (7) Serviço a Deus: 'os seus servos o servirão' (Apocalipse 22:3). (8) Visão de Deus: 'verão o seu rosto' (Apocalipse 22:4). A teologia reformada vê nos novos céus e nova terra a consumação da redenção - não um paraíso espiritual desencarnado, mas uma nova criação física e espiritual.",
            referencias: "Isaías 65:17-25; Isaías 66:22; Romanos 8:19-23; 2 Pedro 3:10-13; Apocalipse 21:1-27; Apocalipse 22:1-5"
        },
        {
            termo: "08. O Inferno - O Castigo Eterno",
            definicao: "O inferno é o lugar de castigo eterno para Satanás, seus anjos e todos os que rejeitaram a Cristo. Textos principais: 'Então dirá também aos que estiverem à sua esquerda: Apartai-vos de mim, malditos, para o fogo eterno, preparado para o diabo e seus anjos' (Mateus 25:41). 'E estes irão para o tormento eterno, mas os justos para a vida eterna' (Mateus 25:46). 'E o diabo... foi lançado no lago de fogo e enxofre... e serão atormentados dia e noite para todo o sempre' (Apocalipse 20:10). 'E aquele que não foi achado escrito no livro da vida foi lançado no lago de fogo' (Apocalipse 20:15). Características do inferno: (1) Eternidade: 'fogo eterno', 'tormento eterno', 'para todo o sempre' (Mateus 25:41,46; Apocalipse 20:10). (2) Consciência: os condenados estão cientes de seu sofrimento (Lucas 16:23-24). (3) Separação de Deus: 'Apartai-vos de mim' (Mateus 25:41). (4) Preparado para o diabo e seus anjos: não originalmente para os homens, mas para aqueles que rejeitam a Deus. (5) Justiça divina: o castigo é proporcional (Lucas 12:47-48). A teologia reformada rejeita: (a) O universalismo (apocatástase - todos serão salvos) (Orígenes). (b) O aniquilacionismo (os ímpios deixarão de existir). (c) O purgatório (católico). (d) A segunda chance após a morte. 'E, como aos homens está ordenado morrerem uma vez, vindo depois o juízo' (Hebreus 9:27). 'Aquele que crê no Filho tem a vida eterna; mas aquele que não crê no Filho não verá a vida, mas a ira de Deus sobre ele permanece' (João 3:36).",
            referencias: "Isaías 66:24; Daniel 12:2; Mateus 5:22; Mateus 10:28; Mateus 13:41-42; Mateus 18:8; Mateus 25:41-46; Marcos 9:43-48; Lucas 16:19-31; 2 Tessalonicenses 1:8-9; Judas 1:7; Apocalipse 14:9-11; Apocalipse 20:10-15; Apocalipse 21:8"
        },
        {
            termo: "09. O Céu - A Vida Eterna com Cristo",
            definicao: "O céu é o lugar da bem-aventurança eterna para os redimidos, onde desfrutarão da presença de Deus e de Cristo para sempre. Textos principais: 'Na casa de meu Pai há muitas moradas... vou preparar-vos lugar... para que onde eu estiver estejais vós também' (João 14:2-3). 'E assim estaremos sempre com o Senhor' (1 Tessalonicenses 4:17). 'Bem-aventurados os limpos de coração, porque eles verão a Deus' (Mateus 5:8). 'Como está escrito: As coisas que o olho não viu, e o ouvido não ouviu, e não subiram ao coração do homem, são as que Deus preparou para os que o amam' (1 Coríntios 2:9). Características do céu: (1) Presença de Deus e de Cristo: 'verão o seu rosto' (Apocalipse 22:4). (2) Alegria eterna: 'entrará no gozo do teu senhor' (Mateus 25:21,23). (3) Descanso: 'descansem das suas labutas' (Apocalipse 14:13). (4) Sem pecado, sofrimento ou morte (Apocalipse 21:4). (5) Relacionamentos aperfeiçoados (não matrimônio, pois 'nem casam, nem dão-se em casamento' - Mateus 22:30). (6) Serviço a Deus: 'os seus servos o servirão' (Apocalipse 22:3). (7) Conhecimento perfeito: 'conhecerei como também sou conhecido' (1 Coríntios 13:12). (8) Glorificação: o corpo será glorificado (Filipenses 3:21). A teologia reformada enfatiza que o céu não é um lugar de tédio (harpa, nuvens), mas de alegria ativa na presença de Deus. 'Alegrem-se os céus, e regozije-se a terra' (Salmo 96:11). 'Fiel é Deus, pelo qual fostes chamados para a comunhão de seu Filho Jesus Cristo, nosso Senhor' (1 Coríntios 1:9).",
            referencias: "Salmo 16:11; Salmo 17:15; Mateus 5:8; João 14:1-3; João 17:24; Romanos 8:18-25; 1 Coríntios 13:12; Filipenses 1:23; Filipenses 3:20-21; 1 Tessalonicenses 4:13-18; Apocalipse 7:9-17; Apocalipse 21:1-27; Apocalipse 22:1-5"
        },
        {
            termo: "10. A Nova Jerusalém - A Cidade de Deus (Apocalipse 21:9-27)",
            definicao: "A Nova Jerusalém é a descrição simbólica da morada eterna de Deus com seu povo. Texto (Apocalipse 21:9-27): 'Vem, mostrar-te-ei a esposa, a mulher do Cordeiro... E a cidade era puro ouro, semelhante a vidro resplandecente. E o muro da cidade tinha doze fundamentos... a cidade estava posta em quadrado... Media doze mil estádios... Ouro puro, semelhante a vidro resplandecente. Os fundamentos do muro da cidade estavam adornados de toda a pedra preciosa... As doze portas eram doze pérolas... A glória de Deus a tem iluminado, e o Cordeiro é a sua lâmpada.' Significados simbólicos: (1) 'Esposa, a mulher do Cordeiro' - a igreja glorificada (Efésios 5:25-27). (2) 'Doze portas' - as doze tribos de Israel (a continuidade com o AT). (3) 'Doze fundamentos' - os doze apóstolos (a fundação da igreja). (4) 'Ouro puro' - a pureza e a glória. (5) 'Pedras preciosas' - a beleza da salvação. (6) 'Pérolas' - o preço da redenção (Mateus 13:45-46). (7) 'Sem templo' - Deus e o Cordeiro são o templo (Apocalipse 21:22). (8) 'Sem necessidade de sol ou lua' - a glória de Deus ilumina tudo. (9) 'Somente nela entrarão os que estão escritos no livro da vida' - a exclusividade da salvação. A teologia reformada vê na Nova Jerusalém a consumação da aliança de Deus com seu povo. 'E a cidade não necessita de sol nem de lua, para que nela resplandeçam, porque a glória de Deus a tem iluminado, e o Cordeiro é a sua lâmpada' (Apocalipse 21:23).",
            referencias: "Isaías 60:1-22; Ezequiel 40-48; Gálatas 4:26; Hebreus 11:10; Hebreus 12:22; Apocalipse 3:12; Apocalipse 21:2; Apocalipse 21:9-27"
        },
        {
            termo: "11. O Fim da História e a Entrega do Reino (1 Coríntios 15:24-28)",
            definicao: "Paulo descreve o fim escatológico: 'Depois virá o fim, quando tiver entregue o reino a Deus, o Pai, quando houver aniquilado todo o principado, e toda a potestade e todo o poder. Porque convém que ele reine até que haja posto todos os inimigos debaixo de seus pés. Ora, o último inimigo que há de ser aniquilado é a morte... E, quando todas as coisas lhe estiverem sujeitas, então também o próprio Filho se sujeitará àquele que todas as coisas lhe sujeitou, para que Deus seja tudo em todos' (1 Coríntios 15:24-28). Significados teológicos: (1) 'Entregue o reino a Deus, o Pai' - Cristo, como mediador, entrega o reino consumado ao Pai. (2) 'Aniquilado todo principado' - a derrota completa de todos os poderes malignos. (3) 'Reine até que haja posto todos os inimigos debaixo de seus pés' - o reinado mediador de Cristo (Salmo 110:1). (4) 'O último inimigo... é a morte' - a morte será vencida (Isaías 25:8; Apocalipse 20:14). (5) 'O próprio Filho se sujeitará' - não negação da divindade (subordinação funcional, não ontológica). (6) 'Para que Deus seja tudo em todos' - a consumação final. A teologia reformada entende que a submissão do Filho é econômica (na economia da salvação), não ontológica (o Filho é igual ao Pai em essência). 'Ele é antes de todas as coisas, e todas as coisas subsistem por ele' (Colossenses 1:17).",
            referencias: "Salmo 8:6; Salmo 110:1; Isaías 25:8; Ezequiel 37:25-28; Daniel 2:44; Daniel 7:14; 1 Coríntios 15:24-28; Colossenses 2:15; Apocalipse 20:14"
        },
        {
            termo: "12. A Maranata - A Esperança da Igreja (1 Coríntios 16:22; Apocalipse 22:20)",
            definicao: "'Maranata' (aramaico: Marana tha - 'Nosso Senhor, vem!') é a súplica da igreja primitiva pela vinda de Cristo. Textos: 'Se alguém não ama o Senhor Jesus Cristo, seja anátema. Maranata' (1 Coríntios 16:22). 'Aquele que testifica estas coisas diz: Certamente cedo venho. Amém. Ora vem, Senhor Jesus' (Apocalipse 22:20). Significados: (1) A expectativa da parusia (segunda vinda). (2) A súplica por justiça e redenção final. (3) A afirmação do senhorio de Cristo ('Nosso Senhor, vem!'). (4) A esperança que sustenta a igreja. (5) A oração final da Bíblia: 'Ora vem, Senhor Jesus'. A teologia reformada incentiva a esperança ativa na vinda de Cristo. 'Aguardando a bem-aventurada esperança e o aparecimento da glória do grande Deus e nosso Salvador Jesus Cristo' (Tito 2:13). 'E aquele que testifica estas coisas diz: Certamente cedo venho. Amém. Ora vem, Senhor Jesus. A graça de nosso Senhor Jesus Cristo seja com todos vós. Amém' (Apocalipse 22:20-21).",
            referencias: "1 Coríntios 16:22; Tito 2:13; Apocalipse 1:7; Apocalipse 22:20-21"
        },
        {
            termo: "13. Síntese: A Consumação do Reino de Cristo",
            definicao: "A escatologia cristã é a consumação do reino de Cristo. 'Ora, o Deus de esperança vos encha de todo o gozo e paz em crença, para que abundeis em esperança pelo poder do Espírito Santo' (Romanos 15:13). Resumo da escatologia cristocêntrica: (1) A segunda vinda de Cristo (parusia) será pessoal, visível e gloriosa. (2) A ressurreição dos mortos será universal, corporal e glorificada. (3) O juízo final será presidido por Cristo, separando os justos dos ímpios. (4) Os justos herdarão a vida eterna nos novos céus e nova terra. (5) Os ímpios sofrerão o castigo eterno no inferno. (6) Deus será 'tudo em todos' (1 Coríntios 15:28). (7) A igreja anseia: 'Maranata - Ora vem, Senhor Jesus!' (Apocalipse 22:20). A teologia reformada vive na tensão entre o 'já' (o reino já veio em Cristo) e o 'ainda não' (o reino ainda não está consumado). 'Porque a nossa leve e momentânea tribulação produz para nós um peso eterno de glória mui excelente; não atentando nós nas coisas que se veem, mas nas que se não veem; porque as que se veem são temporais, e as que se não veem são eternas' (2 Coríntios 4:17-18). 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36). Soli Deo Gloria!",
            referencias: "Romanos 15:13; 2 Coríntios 4:17-18; 1 Tessalonicenses 4:13-18; 2 Pedro 3:10-13; Apocalypse 1:7; Apocalipse 22:20-21"
        }
    ]
};