// volume/volume-62.js
window.LIVRO_DATA = {
    nome: "Volume LXII",
    dados: [
        {
            termo: "01. Introdução: A Cruz como o Coração da Escritura",
            definicao: "A mensagem da cruz é o coração de toda a Escritura, desde Gênesis até Apocalipse. O apóstolo Paulo declarou: 'Porque não me propus saber coisa alguma entre vós, senão a Jesus Cristo, e este crucificado' (1 Coríntios 2:2). 'Longe esteja de mim gloriar-me, a não ser na cruz de nosso Senhor Jesus Cristo' (Gálatas 6:14). A cruz não é um evento isolado, mas o centro da história da redenção. O Antigo Testamento prefigura a cruz em tipos, sombras e profecias. O Novo Testamento proclama a cruz como o evento central da salvação. A teologia reformada (Calvino, Owen, Edwards) enfatiza que a cruz é o lugar onde a justiça e a misericórdia de Deus se encontram. 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36). Este volume explora a mensagem da cruz em toda a Bíblia: Gênesis a Apocalipse, tipos e sombras, profecias, o significado teológico da cruz, e a aplicação da cruz à vida do crente. 'E ele disse a todos: Se alguém quer vir após mim, negue-se a si mesmo, tome a sua cruz e siga-me' (Lucas 9:23).",
            referencias: "Lucas 9:23; João 12:32-33; 1 Coríndios 1:18-25; 1 Coríndios 2:2; Gálatas 6:14; Colossenses 2:13-15; Hebreus 12:2"
        },
        {
            termo: "02. Gênesis - O Proto-Evangelho e as Sombras da Cruz",
            definicao: "O livro de Gênesis contém as primeiras sombras e prefigurações da cruz. (1) Gênesis 3:15 - O Proto-Evangelho: 'E porei inimizade entre ti e a mulher, e entre a tua semente e a sua semente; esta te ferirá a cabeça, e tu lhe ferirás o calcanhar.' A semente da mulher (Cristo) seria ferida no calcanhar (a cruz), mas esmagaria a cabeça da serpente (vitória sobre Satanás). (2) A expulsão do Jardim do Éden (Gênesis 3:23-24) - o pecado separou o homem de Deus; a cruz reconcilia (Romanos 5:10). (3) A promessa a Abraão (Gênesis 12:3; 22:18) - 'Em ti serão benditas todas as famílias da terra' - a bênção vem pela semente de Abraão (Cristo) e sua obra na cruz (Gálatas 3:13-14). (4) O sacrifício de Isaque (Gênesis 22:1-18) - tipo da morte substitutiva de Cristo. (5) José, vendido por seus irmãos, depois exaltado - tipo do sofrimento redentor de Cristo. (6) A escada de Jacó (Gênesis 28:12) - tipo da mediação de Cristo (João 1:51). A teologia reformada vê em Gênesis a primeira promessa do Redentor que seria ferido na cruz.",
            referencias: "Gênesis 3:15; Gênesis 12:3; Gênesis 22:1-18; Gênesis 28:12; Gênesis 37-50; Gálatas 3:13-14; Romanos 5:10; Romanos 16:20; Hebreus 2:14-15"
        },
        {
            termo: "03. Êxodo - O Cordeiro Pascal e a Libertação pelo Sangue",
            definicao: "O livro de Êxodo apresenta o Cordeiro Pascal, cujo sangue protegeu Israel da morte (Êxodo 12:1-28). (1) O Cordeiro Pascal: 'Tomar-vos-eis um cordeiro sem defeito... e o imolareis ao crepúsculo... e poreis o sangue nas ombreiras e na porta superior' (Êxodo 12:3,6-7). Paulo identifica Cristo com o Cordeiro Pascal: 'Cristo, nossa Páscoa, foi sacrificado por nós' (1 Coríndios 5:7). (2) O sangue nos umbrais das portas protegia da morte; o sangue de Cristo nos protege da ira de Deus (Romanos 5:9). (3) A Rocha Ferida (Êxodo 17:1-7): Moisés feriu a rocha, e dela jorrou água. Paulo identifica a rocha com Cristo: 'E a pedra era Cristo' (1 Coríndios 10:4). Cristo foi ferido (Isaías 53:5), e dele flui água viva (João 7:37-39). (4) O Tabernáculo (Êxodo 25-40): os sacrifícios, o altar, o propiciatório (hilastērion) - todos apontam para o sacrifício de Cristo (Romanos 3:25). (5) O véu do templo que se rasgou na morte de Cristo (Mateus 27:51) é prefigurado no véu do tabernáculo (Êxodo 26:31-33). A teologia reformada vê em Êxodo o tipo da libertação pela sangue do Cordeiro.",
            referencias: "Êxodo 12:1-28; Êxodo 17:1-7; Êxodo 25-40; Isaías 53:5; Mateus 27:51; João 1:29; João 7:37-39; Romanos 3:25; Romanos 5:9; 1 Coríndios 5:7; 1 Coríndios 10:4; 1 Pedro 1:18-19"
        },
        {
            termo: "04. Levítico - O Sacrifício pelo Pecado e o Dia da Expiação",
            definicao: "O livro de Levítico é o manual de sacrifícios do Antigo Testamento, todo ele apontando para o sacrifício de Cristo na cruz. (1) Os sacrifícios: holocausto, oferta pelo pecado, oferta pela culpa, oferta pacífica - todos apontam para o sacrifício de Cristo (Hebreus 9:11-14; 10:1-18). (2) O Dia da Expiação (Yom Kippur, Levítico 16): O sumo sacerdote entrava no Santo dos Santos uma vez por ano com sangue de animais. Cristo entrou no céu uma vez por todas com seu próprio sangue (Hebreus 9:11-12). (3) O bode emissário (Azazel) levava os pecados para o deserto (Levítico 16:20-22) - Cristo levou nossos pecados sobre si (Isaías 53:6; 1 Pedro 2:24). (4) O cordeiro sem defeito (Levítico 1:3,10) - Cristo sem pecado (Hebreus 4:15; 1 Pedro 1:19). (5) A imposição de mãos (Levítico 1:4) - transferência simbólica do pecado para o animal; Cristo se identificou com nossos pecados (2 Coríndios 5:21). (6) O sangue aspergido sobre o propiciatório (Levítico 16:14-15) - Cristo é a propiciação pelos nossos pecados (Romanos 3:25; 1 João 2:2). (7) O véu do templo se rasgou (Mateus 27:51) - simbolizando o acesso a Deus por meio da morte de Cristo (Hebreus 10:19-22). A teologia reformada vê em Levítico a sombra do sacrifício perfeito de Cristo.",
            referencias: "Levítico 1-7; Levítico 16:1-34; Isaías 53:4-6; Mateus 27:51; Romanos 3:25; 2 Coríndios 5:21; Hebreus 4:15; Hebreus 9:11-14; Hebreus 10:1-18; Hebreus 10:19-22; 1 Pedro 1:19; 1 Pedro 2:24; 1 João 2:2"
        },
        {
            termo: "05. Números - A Serpente de Bronze e a Rocha Ferida",
            definicao: "O livro de Números contém dois tipos importantes da cruz. (1) A Serpente de Bronze (Números 21:4-9): O povo pecou, e Deus enviou serpentes abrasadoras. Moisés fez uma serpente de bronze e a colocou sobre uma haste; quem olhasse para ela viveria. Jesus aplicou este tipo a si mesmo: 'E, como Moisés levantou a serpente no deserto, assim importa que o Filho do Homem seja levantado; para que todo aquele que nele crê não pereça, mas tenha a vida eterna' (João 3:14-15). (2) A Rocha Ferida (Números 20:7-13): Moisés feriu a rocha duas vezes, e dela jorrou água. A rocha é Cristo (1 Coríndios 10:4). A água é o Espírito Santo (João 7:37-39). (3) A Vara de Arão que floresceu (Números 17:1-11) - tipo da ressurreição de Cristo. (4) A Novilha Vermelha (Números 19) - tipo da purificação pelo sangue de Cristo (Hebreus 9:13-14). A teologia reformada vê na serpente de bronze o tipo mais claro de Cristo levantado na cruz.",
            referencias: "Números 17:1-11; Números 19; Números 20:7-13; Números 21:4-9; João 3:14-15; João 7:37-39; 1 Coríndios 10:4; 2 Coríndios 5:21; Hebreus 9:13-14"
        },
        {
            termo: "06. Deuteronômio - A Maldição do Pendurado no Madeiro",
            definicao: "O livro de Deuteronômio contém a profecia sobre o Crucificado como amaldiçoado. (1) A Maldição do Pendurado no Madeiro (Deuteronômio 21:22-23): 'Quando alguém tiver cometido pecado digno de morte, e for morto, e o pendurares num madeiro... o que for pendurado é maldito de Deus.' Paulo aplica este texto a Cristo: 'Cristo nos resgatou da maldição da lei, fazendo-se maldição por nós; porque está escrito: Maldito todo aquele que for pendurado no madeiro' (Gálatas 3:13). (2) O Profeta como Moisés (Deuteronômio 18:15-19) - Jesus é o Profeta que foi crucificado (Atos 3:22-23). (3) As promessas de restauração (Deuteronômio 30) - tipo da redenção pela cruz. (4) A circuncisão do coração (Deuteronômio 30:6) - tipo da regeneração pela obra da cruz (Colossenses 2:11). A teologia reformada vê em Deuteronômio 21:22-23 a profecia da maldição que Cristo sofreu em nosso lugar.",
            referencias: "Deuteronômio 18:15-19; Deuteronômio 21:22-23; Deuteronômio 30:1-10; Atos 3:22-23; Gálatas 3:10-14; Colossenses 2:11-12"
        },
        {
            termo: "07. Josué, Juízes, Rute - A Cruz nas Conquistas e na Redenção",
            definicao: "Josué, Juízes e Rute contêm tipos da cruz. Josué: (1) O nome Josué (Yeshua) é a forma hebraica de 'Jesus'. Ele conduziu o povo à terra prometida; Cristo nos conduz à nova criação (Hebreus 4:8-11). (2) A travessia do Jordão (Josué 3-4) - tipo do batismo na morte de Cristo (Romanos 6:3-5). (3) A queda de Jericó (Josué 6) - tipo da vitória da cruz sobre os inimigos espirituais (Colossenses 2:15). (4) O Capitão do exército do Senhor (Josué 5:13-15) - teofania de Cristo. Juízes: (1) Sansão: sua morte sacrificial (Juízes 16:28-30) - tipo da morte de Cristo. 'Morreram mais os que matou na sua morte do que os que matara na sua vida' (Juízes 16:30) - Cristo venceu na morte. (2) O sacrifício de Jefté (Juízes 11) - tipo de sacrifício vicário (embora problemático). Rute: (1) Boaz como remidor (goel) (Rute 2-4) - tipo de Cristo que nos remiu pelo sangue da cruz (Efésios 1:7). (2) O casamento de Boaz com Rute (gentia) - tipo da inclusão dos gentios pela cruz (Efésios 2:11-22). A teologia reformada vê nestes livros a atuação redentora de Deus prefigurando a cruz.",
            referencias: "Josué 3-4; Josué 5:13-15; Josué 6; Juízes 13-16; Rute 2-4; Mateus 1:5; Romanos 6:3-5; Efésios 1:7; Efésios 2:11-22; Colossenses 2:15; Hebreus 4:8-11"
        },
        {
            termo: "08. 1 e 2 Samuel - Davi e Golias e a Aliança Davídica",
            definicao: "Os livros de Samuel contêm tipos da cruz. (1) Davi e Golias (1 Samuel 17): Davi, o pastor, derrotou o gigante Golias com uma pedra. Cristo, o Bom Pastor, derrotou Satanás na cruz (Hebreus 2:14-15). (2) O sofrimento de Davi (Salmo 22) - profecia da crucificação. (3) A aliança davídica (2 Samuel 7:12-16) - promessa de um descendente que reinaria para sempre, cujo trono seria estabelecido pela cruz (Lucas 1:32-33). (4) O pecado de Davi com Bate-Seba e Urias (2 Samuel 11) - mostra a necessidade do perdão que vem pela cruz. (5) A arca da aliança (1 Samuel 4-6) - tipo da presença de Deus, que se tornou acessível pelo sangue de Cristo (Hebreus 9:1-5). (6) O arrependimento de Davi (Salmo 51) - aponta para o perdão que vem pela cruz. A teologia reformada vê em Davi o tipo do rei que sofre e vence, prefigurando Cristo crucificado.",
            referencias: "1 Samuel 4-6; 1 Samuel 17; 2 Samuel 7:12-16; 2 Samuel 11; Salmo 22; Salmo 51; Lucas 1:32-33; Hebreus 2:14-15"
        },
        {
            termo: "09. 1 e 2 Reis - O Templo e o Sacrifício de Salomão",
            definicao: "Os livros de Reis contêm tipos da cruz. (1) O Templo de Salomão (1 Reis 5-8): o lugar onde os sacrifícios eram oferecidos. Jesus é o verdadeiro templo (João 2:19-21). (2) A dedicação do templo com sacrifícios (1 Reis 8:62-64) - tipo do sacrifício de Cristo. (3) O profeta Elias e o sacrifício no Monte Carmelo (1 Reis 18:16-40) - o fogo desceu e consumiu o sacrifício, tipo do juízo de Deus sobre o pecado, cumprido na cruz. (4) A sombra da cruz no sofrimento dos profetas. (5) O rei Josias e a celebração da Páscoa (2 Reis 22-23) - tipo da reforma espiritual que olha para a cruz. (6) A destruição do templo pelos babilônios (2 Reis 25) - tipo do juízo de Deus sobre o pecado, que Cristo sofreu em nosso lugar. A teologia reformada vê nos sacrifícios do templo a sombra do sacrifício de Cristo.",
            referencias: "1 Reis 5-8; 1 Reis 18:16-40; 2 Reis 22-23; 2 Reis 25; João 2:19-21; Hebreus 8:1-5; Hebreus 9:1-14; Hebreus 10:1-4"
        },
        {
            termo: "10. Isaías - O Servo Sofredor (Isaías 52:13-53:12)",
            definicao: "O livro de Isaías contém a mais rica profecia da cruz no Antigo Testamento: o Servo Sofredor (Isaías 52:13-53:12). 'Ele foi traspassado pelas nossas transgressões e moído pelas nossas iniquidades; o castigo que nos traz a paz estava sobre ele, e pelas suas pisaduras fomos sarados. Todos nós andávamos desgarrados como ovelhas... mas o Senhor fez cair sobre ele a iniquidade de todos nós' (Isaías 53:5-6). 'Foi cortado da terra dos viventes; pela transgressão do meu povo ele foi atingido' (Isaías 53:8). 'Ele verá o fruto do trabalho da sua alma, e ficará satisfeito; com o seu conhecimento o meu servo justo justificará a muitos, porque as iniquidades deles levará sobre si' (Isaías 53:11). Cumprimento em Cristo: (1) O Servo Sofredor é Jesus (Mateus 8:17; Lucas 22:37; Atos 8:32-35; Romanos 10:16; 1 Pedro 2:22-25). (2) 'Traspassado' (João 19:34,37). (3) 'Com os transgressores foi contado' (Marcos 15:27-28). (4) 'Sepultado com os ricos' (Mateus 27:57-60). (5) 'Pelas suas pisaduras fomos sarados' (1 Pedro 2:24). Outras profecias da cruz em Isaías: (1) Isaías 42:1-4 - o Servo manso, que não quebrará a cana quebrada (Mateus 12:17-21). (2) Isaías 50:4-11 - o Servo que oferece o dorso aos que ferem (Mateus 26:67; 27:26). (3) Isaías 61:1-3 - ungido para pregar boas novas (Lucas 4:16-21). A teologia reformada vê em Isaías 53 a descrição mais clara da expiação vicária de Cristo na cruz.",
            referencias: "Isaías 42:1-4; Isaías 50:4-11; Isaías 52:13-53:12; Isaías 61:1-3; Mateus 8:17; Mateus 12:17-21; Lucas 4:16-21; Lucas 22:37; João 19:34; João 19:37; Atos 8:32-35; Romanos 10:16; 1 Pedro 2:22-25"
        },
        {
            termo: "11. Jeremias, Ezequiel, Daniel - A Nova Aliança e o Ungido Morto",
            definicao: "Jeremias, Ezequiel e Daniel contêm profecias da cruz. Jeremias: (1) A Nova Aliança (Jeremias 31:31-34) - inaugurada pelo sangue de Cristo na cruz (Lucas 22:20; Hebreus 8:6-13; 10:16-17). (2) O 'Renovo Justo' (Jeremias 23:5-6; 33:14-16) - Cristo crucificado como Rei justo. (3) Jeremias, o profeta sofredor - tipo de Cristo. Ezequiel: (1) O Bom Pastor que morre pelas ovelhas (Ezequiel 34:23-24) - Cristo (João 10:11-18). (2) A visão do vale de ossos secos (Ezequiel 37:1-14) - tipo da ressurreição pela cruz. (3) A água que flui do templo (Ezequiel 47:1-12) - tipo da água viva que flui do lado de Cristo (João 7:37-39). Daniel: (1) O Messias será cortado (Daniel 9:26) - a morte do Ungido. (2) A pedra cortada sem mãos (Daniel 2:34-35,44-45) - tipo da cruz que destrói os reinos. (3) O Filho do Homem (Daniel 7:13-14) - Cristo crucificado e exaltado. A teologia reformada vê nestes profetas a promessa da nova aliança e do Messias que morreria.",
            referencias: "Jeremias 23:5-6; Jeremias 31:31-34; Jeremias 33:14-16; Ezequiel 34:23-24; Ezequiel 37:1-14; Ezequiel 47:1-12; Daniel 2:34-35; Daniel 7:13-14; Daniel 9:24-27; Lucas 22:20; João 10:11-18; João 7:37-39; Hebreus 8:6-13; Hebreus 10:16-17"
        },
        {
            termo: "12. Zacarias e Malaquias - O Traspassado e o Sol da Justiça",
            definicao: "Zacarias e Malaquias contêm profecias da paixão de Cristo. Zacarias: (1) 'Olharão para mim, a quem traspassaram' (Zacarias 12:10) - cumprido na crucificação (João 19:37). (2) 'Fere o pastor, e as ovelhas se dispersarão' (Zacarias 13:7) - a prisão de Jesus e a fuga dos discípulos (Mateus 26:31). (3) A entrada triunfal em Jerusalém (Zacarias 9:9) - o Rei humilde montado em um jumento (Mateus 21:1-11). (4) As trinta moedas de prata (Zacarias 11:12-13) - a traição de Judas (Mateus 26:14-16; 27:3-10). (5) A fonte para purificação (Zacarias 13:1) - o sangue de Cristo que purifica (1 João 1:7). (6) O dia do Senhor (Zacarias 14) - a segunda vinda. Malaquias: (1) 'O Sol da justiça nascerá' (Malaquias 4:2) - Cristo, a luz do mundo (João 8:12). (2) 'Eis que eu envio o meu anjo' (Malaquias 3:1) - João Batista, precursor de Cristo. (3) 'O Senhor... virá de repente ao seu templo' (Malaquias 3:1) - a purificação do templo por Jesus (Mateus 21:12-13). A teologia reformada vê em Zacarias a profecia mais detalhada da paixão de Cristo.",
            referencias: "Zacarias 9:9; Zacarias 11:12-13; Zacarias 12:10; Zacarias 13:1; Zacarias 13:7; Zacarias 14; Malaquias 3:1; Malaquias 4:2; Mateus 21:1-11; Mateus 21:12-13; Mateus 26:14-16; Mateus 26:31; Mateus 27:3-10; João 8:12; João 19:37; 1 João 1:7"
        },
        {
            termo: "13. Os Salmos Messiânicos da Cruz",
            definicao: "Os Salmos contêm as mais detalhadas profecias da crucificação. (1) Salmo 22 - as palavras de Jesus na cruz ('Deus meu, Deus meu, por que me desamparaste?'), as mãos e pés traspassados, a repartição das vestes (Mateus 27:35-46). (2) Salmo 69 - o vinagre dado para beber, o zelo pela casa de Deus (João 2:17; 19:28-30). (3) Salmo 31 - 'Nas tuas mãos encomendo o meu espírito' (Lucas 23:46). (4) Salmo 34 - nenhum osso quebrado (João 19:36). (5) Salmo 41 - a traição de um amigo íntimo (João 13:18). (6) Salmo 38 - a descrição do sofrimento do justo. (7) Salmo 40 - a obediência de Cristo (Hebreus 10:5-10). (8) Salmo 16 - a ressurreição (Atos 2:25-32). (9) Salmo 118 - a pedra rejeitada (Mateus 21:42) e a entrada triunfal (Mateus 21:9). (10) Salmo 110 - o sacerdote segundo Melquisedeque (Hebreus 5:6; 6:20; 7:17). A teologia reformada vê nos Salmos a paixão e a glória de Cristo.",
            referencias: "Salmo 16; Salmo 22; Salmo 31; Salmo 34; Salmo 38; Salmo 40; Salmo 41; Salmo 69; Salmo 110; Salmo 118; Mateus 27:35-46; Lucas 23:46; João 2:17; João 13:18; João 19:28-30; João 19:36; Atos 2:25-32; Atos 13:35-37; Romanos 15:3; Gálatas 3:13; Hebreus 10:5-10"
        },
        {
            termo: "14. Os Evangelhos - A Narrativa da Crucificação",
            definicao: "Os quatro evangelhos descrevem a crucificação de Jesus com detalhes. Mateus 27:32-56 - a crucificação, as zombarias, a escuridão, o véu rasgado. Marcos 15:21-41 - a crucificação, o centurião que confessa. Lucas 23:26-49 - as palavras de Jesus na cruz: 'Pai, perdoa-lhes' (v.34), 'Hoje estarás comigo no paraíso' (v.43), 'Pai, nas tuas mãos entrego o meu espírito' (v.46). João 19:16-37 - os detalhes da crucificação: a inscrição 'Jesus Nazareno, Rei dos Judeus', a túnica sem costura, 'Tenho sede', 'Está consumado', a lança no lado. (1) O significado da cruz nos evangelhos: (a) Expiação vicária (Mateus 20:28; Marcos 10:45). (b) O Cordeiro de Deus (João 1:29). (c) O juízo sobre o pecado (Mateus 27:45 - escuridão). (d) O acesso a Deus (Mateus 27:51 - véu rasgado). (e) O perdão (Lucas 23:34). (f) A consumação da obra (João 19:30). A teologia reformada vê nos evangelhos a narrativa histórica da crucificação, central para a fé cristã.",
            referencias: "Mateus 20:28; Mateus 27:32-56; Marcos 10:45; Marcos 15:21-41; Lucas 23:26-49; João 1:29; João 19:16-37; João 19:30; Atos 2:23; Romanos 5:8; 2 Coríndios 5:21; Gálatas 3:13; 1 Pedro 2:24"
        },
        {
            termo: "15. As Epístolas de Paulo - A Teologia da Cruz",
            definicao: "O apóstolo Paulo desenvolve a teologia da cruz. (1) Romanos 3:23-26 - a propiciação pelo sangue de Cristo. (2) Romanos 5:8-10 - Cristo morreu por nós quando éramos pecadores. (3) 2 Coríndios 5:18-21 - a reconciliação; Cristo foi feito pecado por nós. (4) Gálatas 3:13 - Cristo nos redimiu da maldição da lei. (5) Efésios 2:13-18 - a paz pelo sangue de Cristo. (6) Colossenses 2:13-15 - a cruz como vitória sobre os principados e potestades. (7) Filipenses 2:5-11 - o esvaziamento (kenosis) e a morte de cruz. (8) 1 Coríndios 1:18-25 - a cruz como loucura para os gregos, mas poder de Deus. (9) Gálatas 6:14 - gloriar-se na cruz. (10) 1 Coríndios 15:3-4 - o evangelho: Cristo morreu pelos pecados. A teologia reformada vê em Paulo o mais profundo expositor da teologia da cruz.",
            referencias: "Romanos 3:23-26; Romanos 5:8-10; 1 Coríndios 1:18-25; 1 Coríndios 15:3-4; 2 Coríndios 5:18-21; Gálatas 3:13; Gálatas 6:14; Efésios 2:13-18; Filipenses 2:5-8; Colossenses 1:19-22; Colossenses 2:13-15; 1 Pedro 2:24"
        },
        {
            termo: "16. Hebreus - O Sacrifício Perfeito e o Sumo Sacerdote",
            definicao: "A Epístola aos Hebreus apresenta Cristo como o Sumo Sacerdote que ofereceu seu próprio sangue no santuário celestial. (1) Hebreus 7:26-28 - Cristo, sumo sacerdote santo, inocente, imaculado. (2) Hebreus 9:11-14 - Cristo entrou no santuário celestial com seu próprio sangue. (3) Hebreus 9:22 - sem derramamento de sangue não há remissão. (4) Hebreus 10:1-18 - o sacrifício de Cristo é único e definitivo. 'Porque com uma só oblação aperfeiçoou para sempre os que são santificados' (Hebreus 10:14). (5) Hebreus 10:19-22 - o acesso ao santuário pelo sangue de Jesus. (6) Hebreus 12:2 - Jesus, o autor e consumador da fé, que pelo gozo que lhe estava proposto suportou a cruz. (7) Hebreus 13:11-13 - Jesus padeceu fora da porta. (8) Hebreus 9:15-28 - o mediador da nova aliança. A teologia reformada vê em Hebreus a interpretação do significado do sacrifício de Cristo.",
            referencias: "Hebreus 7:26-28; Hebreus 9:11-28; Hebreus 10:1-22; Hebreus 12:2; Hebreus 13:11-13; Levítico 16; Êxodo 24:8; Jeremias 31:31-34"
        },
        {
            termo: "17. 1 Pedro e 1 João - O Cordeiro e a Propiciação",
            definicao: "Pedro e João escrevem sobre a cruz. 1 Pedro: (1) 1 Pedro 1:18-19 - redimidos pelo sangue precioso de Cristo, como de um cordeiro sem defeito. (2) 1 Pedro 2:21-25 - Cristo padeceu por nós, deixando-nos o exemplo; levou os nossos pecados em seu corpo sobre o madeiro. (3) 1 Pedro 3:18 - Cristo morreu uma vez pelos pecados, o justo pelos injustos. 1 João: (1) 1 João 1:7 - o sangue de Jesus Cristo nos purifica de todo pecado. (2) 1 João 2:2 - ele é a propiciação pelos nossos pecados. (3) 1 João 3:16 - conhecemos o amor de Cristo porque ele deu a sua vida por nós. (4) 1 João 4:9-10 - Deus enviou seu Filho para propiciação pelos nossos pecados. (5) 1 João 5:6 - Cristo veio por água e sangue (batismo e cruz). (6) Apocalipse 5:6-14 - o Cordeiro que foi morto é digno. A teologia reformada vê em Pedro e João a aplicação da cruz à vida do crente.",
            referencias: "1 Pedro 1:18-19; 1 Pedro 2:21-25; 1 Pedro 3:18; 1 João 1:7; 1 João 2:2; 1 João 3:16; 1 João 4:9-10; 1 João 5:6; Apocalipse 5:6-14; Apocalipse 7:9-17"
        },
        {
            termo: "18. Apocalipse - O Cordeiro que foi Morto",
            definicao: "O Apocalipse apresenta Cristo como o Cordeiro que foi morto, adorado no céu. (1) Apocalipse 5:6-14 - 'Digno é o Cordeiro, que foi morto, de receber o poder...' (v.12). (2) Apocalipse 7:9-17 - a multidão que lavou suas vestes no sangue do Cordeiro. (3) Apocalipse 12:11 - 'Eles o venceram pelo sangue do Cordeiro.' (4) Apocalipse 13:8 - o Cordeiro que foi morto desde a fundação do mundo. (5) Apocalipse 21:22-23 - o Cordeiro é a lâmpada da nova Jerusalém. (6) Apocalipse 22:1-3 - o trono de Deus e do Cordeiro. A cruz é o centro da adoração celestial. A teologia reformada vê no Apocalipse a consumação da obra da cruz: o Cordeiro reina porque foi morto.",
            referencias: "Apocalipse 5:6-14; Apocalipse 7:9-17; Apocalipse 12:11; Apocalipse 13:8; Apocalipse 21:22-23; Apocalipse 22:1-3; Apocalipse 22:16"
        },
        {
            termo: "19. O Significado Teológico da Cruz",
            definicao: "A teologia da cruz abrange vários aspectos: (1) Expiação vicária (substituição penal) - Cristo morreu em nosso lugar (Isaías 53:5-6; 2 Coríndios 5:21; 1 Pedro 2:24). (2) Propiciação - Cristo satisfez a ira de Deus (Romanos 3:25; 1 João 2:2). (3) Redenção - Cristo nos comprou do pecado (Romanos 3:24; Efésios 1:7). (4) Reconciliação - Cristo restaurou nosso relacionamento com Deus (Romanos 5:10-11; 2 Coríndios 5:18-21). (5) Vitória sobre Satanás - Cristo despojou os principados e potestades (Colossenses 2:15; Hebreus 2:14-15). (6) Exemplo - Cristo nos deixou exemplo de humildade e amor (1 Pedro 2:21; Filipenses 2:5-8). (7) Julgamento do pecado - Deus condenou o pecado na carne de Cristo (Romanos 8:3). (8) Justificação - somos declarados justos pela fé na obra de Cristo (Romanos 3:21-26; 5:9). (9) Santificação - a cruz nos liberta do poder do pecado (Romanos 6:6-7). (10) Esperança da ressurreição - a cruz venceu a morte (1 Coríndios 15:54-57). A teologia reformada (Calvino, Owen, Edwards) enfatiza a substituição penal como o coração da expiação.",
            referencias: "Isaías 53:5-6; Romanos 3:21-26; Romanos 5:8-11; Romanos 6:6-7; Romanos 8:3; 1 Coríndios 15:54-57; 2 Coríndios 5:18-21; Gálatas 3:13; Efésios 1:7; Colossenses 2:15; 1 Pedro 2:21-24; 1 João 2:2"
        },
        {
            termo: "20. Aplicações da Cruz na Vida do Crente",
            definicao: "A cruz não é apenas um evento histórico, mas tem aplicações práticas. (1) Arrependimento e fé - a cruz chama ao arrependimento (Atos 2:36-38). (2) Perdão dos pecados - a cruz é a base do perdão (Efésios 1:7). (3) Liberdade do pecado - a cruz nos liberta do poder do pecado (Romanos 6:6-7). (4) Identificação com Cristo - 'já estou crucificado com Cristo' (Gálatas 2:20). (5) Tomar a cruz diariamente - 'tome a sua cruz e siga-me' (Lucas 9:23). (6) Gloriar-se na cruz - 'longe esteja de mim gloriar-me, a não ser na cruz' (Gálatas 6:14). (7) Amar como Cristo amou - 'como Cristo amou a igreja e a si mesmo se entregou por ela' (Efésios 5:25). (8) Servir com humildade - o exemplo de Cristo (Filipenses 2:5-8). (9) Perseverar no sofrimento - 'tomai a vossa cruz' (Mateus 16:24). (10) Esperança na ressurreição - a cruz não é o fim; a ressurreição é a vitória (1 Coríndios 15:54-57). A teologia reformada (Bonhoeffer) enfatiza o 'custo do discipulado' (seguir a Cristo envolve tomar a cruz). 'Porque para mim o viver é Cristo, e o morrer é ganho' (Filipenses 1:21).",
            referencias: "Mateus 16:24; Lucas 9:23; Atos 2:36-38; Romanos 6:6-7; Gálatas 2:20; Gálatas 6:14; Efésios 1:7; Efésios 5:25; Filipenses 1:21; Filipenses 2:5-8; Colossenses 2:20-23; 1 Pedro 2:21"
        },
        {
            termo: "21. Síntese: A Cruz como o Centro da Escritura",
            definicao: "A mensagem da cruz está em toda a Bíblia, desde Gênesis até Apocalipse. Resumo da mensagem da cruz: (1) Gênesis: o proto-evangelho (3:15), o sacrifício de Isaque (22). (2) Êxodo: o Cordeiro Pascal (12), a Rocha Ferida (17). (3) Levítico: os sacrifícios e o Dia da Expiação (16). (4) Números: a Serpente de Bronze (21). (5) Deuteronômio: o pendurado no madeiro (21:22-23). (6) Josué, Juízes, Rute: tipos da redenção. (7) Samuel: Davi e Golias; a aliança davídica. (8) Reis: o templo e os sacrifícios. (9) Isaías: o Servo Sofredor (53). (10) Jeremias, Ezequiel, Daniel: a nova aliança, o Messias cortado. (11) Zacarias: o traspassado (12:10), o pastor ferido (13:7). (12) Salmos: Salmo 22, 69, 31, 34, etc. (13) Evangelhos: a narrativa da crucificação. (14) Epístolas: a teologia da cruz. (15) Apocalipse: o Cordeiro que foi morto. 'Porque a palavra da cruz é loucura para os que perecem, mas para nós, que somos salvos, é o poder de Deus' (1 Coríndios 1:18). 'Mas nós pregamos a Cristo crucificado' (1 Coríndios 1:23). 'Porque para mim o viver é Cristo, e o morrer é ganho' (Filipenses 1:21). Soli Deo Gloria!",
            referencias: "1 Coríndios 1:18-25; 1 Coríndios 2:2; Gálatas 6:14; Romanos 11:36; Apocalipse 22:20-21"
        }
    ]
};