// volume/volume-50.js
window.LIVRO_DATA = {
    nome: "Volume L",
    dados: [
        {
            termo: "01. Introdução: Cristo como Cabeça da Família",
            definicao: "A família cristã é fundamentada em Cristo como sua cabeça. O apóstolo Paulo escreve: 'Porque o marido é a cabeça da mulher, como também Cristo é a cabeça da igreja' (Efésios 5:23). 'Cristo é a cabeça de todo o homem' (1 Coríntios 11:3). Assim como Cristo é a cabeça da igreja, o marido deve ser a cabeça da família (não como tirano, mas como servo-líder, imitando a Cristo). Este volume explora a aplicação da cristologia às relações familiares: casamento, criação de filhos, relações entre pais e filhos, entre irmãos, e a família como igreja doméstica. A teologia reformada enfatiza que o casamento é um tipo (símbolo) da união entre Cristo e a igreja (Efésios 5:22-33). 'Vós, maridos, amai vossas mulheres, como também Cristo amou a igreja e a si mesmo se entregou por ela' (Efésios 5:25). 'E vós, pais, não irriteis a vossos filhos, mas criai-os na doutrina e admoestação do Senhor' (Efésios 6:4). 'E vós, servos, obedecei a vossos senhores segundo a carne... como a Cristo' (Efésios 6:5).",
            referencias: "1 Coríndios 11:3; Efésios 5:22-33; Efésios 6:1-4; Colossenses 3:18-21; 1 Pedro 3:1-7"
        },
        {
            termo: "02. O Casamento como Tipo da União de Cristo com a Igreja",
            definicao: "O casamento é um tipo (símbolo) da união entre Cristo e a igreja. Paulo escreve: 'Este mistério é grande; digo-o, porém, a respeito de Cristo e da igreja' (Efésios 5:32). Analogias: (1) Cristo é o noivo, a igreja é a noiva (Apocalipse 21:2,9; 22:17). (2) Cristo amou a igreja e se entregou por ela (Efésios 5:25). (3) Cristo santifica a igreja (Efésios 5:26-27). (4) Cristo é a cabeça da igreja (Efésios 5:23). (5) A igreja está sujeita a Cristo (Efésios 5:24). (6) O casamento é uma aliança perante Deus (Malaquias 2:14). (7) O amor de Cristo pela igreja é sacrificial, purificador, eterno. Aplicações: (a) O marido deve amar a esposa como Cristo amou a igreja (sacrificialmente). (b) A esposa deve respeitar o marido como a igreja respeita a Cristo. (c) O casamento cristão deve refletir o evangelho ao mundo. (d) O divórcio é uma ruptura deste tipo (Mateus 19:6). A teologia reformada vê no casamento um dos mais belos tipos de Cristo e da igreja. 'Porque o marido é a cabeça da mulher, como também Cristo é a cabeça da igreja, sendo ele próprio o salvador do corpo' (Efésios 5:23). 'Vós, maridos, amai vossas mulheres, como também Cristo amou a igreja e a si mesmo se entregou por ela' (Efésios 5:25).",
            referencias: "Gênesis 2:18-25; Mateus 19:4-6; Efésios 5:22-33; Apocalipse 19:7-9; Apocalipse 21:2; Apocalipse 21:9; Apocalipse 22:17"
        },
        {
            termo: "03. O Amor do Marido - Imitando o Amor Sacrificial de Cristo",
            definicao: "O apóstolo Paulo exorta os maridos: 'Vós, maridos, amai vossas mulheres, como também Cristo amou a igreja e a si mesmo se entregou por ela' (Efésios 5:25). 'Assim devem os maridos amar as suas próprias mulheres, como a seus próprios corpos' (Efésios 5:28). Características do amor de Cristo pela igreja: (1) Sacrificial: 'se entregou por ela' (Efésios 5:25). (2) Purificador: 'para a santificar... purificando-a com a lavagem da água pela palavra' (Efésios 5:26). (3) Glorificador: 'para apresentá-la a si mesmo igreja gloriosa' (Efésios 5:27). (4) Incondicional: amou a igreja enquanto ainda pecadora (Romanos 5:8). (5) Eterno: o amor de Cristo nunca falha (1 Coríntios 13:8). (6) Ação: não apenas palavras, mas ações (1 João 3:18). Aplicações para o marido: (a) Ame a esposa sacrificialmente (colocando suas necessidades acima das suas). (b) Sacrifique-se por ela (tempo, energia, recursos). (c) Busque a santificação dela (ore por ela, ensine a Palavra). (d) Trate-a com respeito e dignidade. (e) Seja fiel (aliança). (f) Expresse amor em palavras e ações. (g) Perdoe como Cristo perdoou (Efésios 4:32). 'Vós, maridos, amai vossas mulheres, e não vos irriteis contra elas' (Colossenses 3:19). 'Igualmente vós, maridos, coabitai com elas com entendimento, dando honra à mulher, como vaso mais fraco' (1 Pedro 3:7).",
            referencias: "Romanos 5:8; Efésios 4:32; Efésios 5:25-33; Colossenses 3:19; 1 Pedro 3:7; 1 João 3:18"
        },
        {
            termo: "04. A Submissão da Esposa - Refletindo a Submissão da Igreja a Cristo",
            definicao: "Paulo exorta as esposas: 'Vós, mulheres, estai sujeitas a vossos próprios maridos, como ao Senhor' (Efésios 5:22). 'Como a igreja está sujeita a Cristo, assim também as mulheres sejam em tudo sujeitas a seus maridos' (Efésios 5:24). Características da submissão da igreja a Cristo: (1) Voluntária: a igreja se submete voluntariamente a Cristo. (2) Amorosa: motivada pelo amor. (3) Respeitosa: 'a mulher reverencie o marido' (Efésios 5:33). (4) Total: 'em tudo' (Efésios 5:24) - exceto quando contradiz a Deus (Atos 5:29). (5) Confiante: confia na liderança de Cristo. (6) Alegre: não forçada. (7) Edificante: visa a glória de Deus. Aplicações para a esposa: (a) Submeta-se voluntariamente ao marido, como ao Senhor. (b) Respeite o marido (não o despreze ou ridicularize). (c) Apoie a liderança do marido. (d) Não usurpe a autoridade (1 Timóteo 2:12). (e) Confie na liderança do marido. (f) Seja uma ajudadora (Gênesis 2:18). (g) Submeta-se mesmo quando o marido não é crente (1 Pedro 3:1-2). 'Vós, mulheres, estai sujeitas a vossos próprios maridos, como é conveniente no Senhor' (Colossenses 3:18). 'Semelhantemente, vós, mulheres, sede sujeitas a vossos maridos, para que também, se alguns não obedecem à palavra, sejam ganhos sem palavra pela conversa de suas mulheres' (1 Pedro 3:1).",
            referencias: "Gênesis 2:18; Efésios 5:22-24; Efésios 5:33; Colossenses 3:18; 1 Timóteo 2:11-12; 1 Pedro 3:1-6"
        },
        {
            termo: "05. A Pureza Sexual no Casamento - Cristo como Exemplo de Fidelidade",
            definicao: "Cristo é o exemplo de pureza sexual e fidelidade. Ele ensinou que o adultério começa no coração (Mateus 5:27-28). O casamento deve ser honrado por todos, e o leito conjugal sem mácula (Hebreus 13:4). Características da pureza cristocêntrica: (1) Fidelidade: o marido deve ser fiel à esposa (Malaquias 2:15-16). (2) Exclusividade: a relação sexual é exclusiva do casamento (Provérbios 5:15-20). (3) Pureza de coração: não cobiçar (Mateus 5:28). (4) Evitar a pornografia: 'Tudo o que é verdadeiro... nisso pensai' (Filipenses 4:8). (5) Negação do adultério: 'Não cometerás adultério' (Êxodo 20:14). (6) Perdão após a queda: como Cristo perdoa (João 8:1-11). Aplicações para o casal: (a) Sejam fiéis um ao outro. (b) Evitem a pornografia e a cobiça. (c) Cultivem a intimidade sexual no casamento (1 Coríndios 7:3-5). (d) Busquem perdão e restauração após a queda. (e) Ensinem pureza aos filhos. (f) Reconheçam que o corpo pertence ao cônjuge (1 Coríndios 7:4). (g) Não privem um ao outro, exceto por consentimento mútuo (1 Coríndios 7:5). 'Fugi da prostituição. Todo o pecado que o homem comete é fora do corpo; mas o que comete prostituição peca contra o seu próprio corpo' (1 Coríndios 6:18). 'Honrado seja entre todos o matrimônio e o leito sem mácula; porém aos que se dão à prostituição e aos adúlteros Deus os julgará' (Hebreus 13:4).",
            referencias: "Êxodo 20:14; Provérbios 5:15-20; Mateus 5:27-28; João 8:1-11; 1 Coríndios 6:18; 1 Coríndios 7:2-5; 1 Coríndios 7:9; Gálatas 5:19-21; Efésios 5:3; 1 Tessalonicenses 4:3-5; Hebreus 13:4"
        },
        {
            termo: "06. A Criação dos Filhos - Disciplina e Admoestação do Senhor",
            definicao: "Paulo exorta os pais: 'E vós, pais, não irriteis a vossos filhos, mas criai-os na doutrina e admoestação do Senhor' (Efésios 6:4). 'Vós, pais, não irriteis vossos filhos, para que não percam o ânimo' (Colossenses 3:21). Características da criação cristocêntrica: (1) Disciplina do Senhor: 'Porque o Senhor corrige o que ama' (Hebreus 12:6). (2) Admoestação: ensinar a verdade bíblica. (3) Não provocar à ira: não abusar, não humilhar, não ser excessivamente crítico. (4) Exemplo: os pais devem modelar o caráter cristão. (5) Amor incondicional: como Deus ama seus filhos (Romanos 5:8). (6) Instrução na Palavra: 'Estas palavras... as ensinarás a teus filhos' (Deuteronômio 6:6-7). (7) Oração pelos filhos. Aplicações para os pais: (a) Ensine a Palavra de Deus aos filhos (Deuteronômio 6:6-9). (b) Discipline com amor, não com ira (Provérbios 13:24). (c) Não provoque os filhos à ira (não seja excessivamente crítico, não compare com outros). (d) Ore diariamente pelos filhos. (e) Seja um exemplo de vida cristã. (f) Estabeleça limites claros com amor. (g) Perdoe e peça perdão quando errar. 'Pais, não provoqueis vossos filhos à ira, mas criai-os na disciplina e admoestação do Senhor' (Efésios 6:4). 'Porque o Senhor corrige o que ama, e açoita a qualquer que recebe por filho' (Hebreus 12:6). 'Instrui o menino no caminho em que deve andar, e até quando envelhecer não se desviará dele' (Provérbios 22:6).",
            referencias: "Deuteronômio 6:6-9; Provérbios 13:24; Provérbios 22:6; Efésios 6:4; Colossenses 3:21; Hebreus 12:5-11"
        },
        {
            termo: "07. A Obediência dos Filhos - Imitando a Obediência de Cristo",
            definicao: "Paulo exorta os filhos: 'Vós, filhos, obedecei a vossos pais no Senhor, porque isto é justo. Honra a teu pai e a tua mãe (que é o primeiro mandamento com promessa), para que te vá bem, e vivas muito tempo sobre a terra' (Efésios 6:1-3). 'Vós, filhos, obedecei em tudo a vossos pais, porque isto é agradável ao Senhor' (Colossenses 3:20). Características da obediência cristocêntrica: (1) 'No Senhor' - obediência que não contradiz a Deus (Atos 5:29). (2) 'Honra' - respeito, apreço, gratidão. (3) 'Em tudo' - obediência geral (exceto quando contradiz a Deus). (4) Promessa: 'para que te vá bem, e vivas muito tempo' (Efésios 6:3). (5) Agradável ao Senhor. (6) Cristo como exemplo: 'Ele foi obediente até à morte' (Filipenses 2:8). Aplicações para os filhos: (a) Obedeça aos pais, a menos que peçam algo contra a vontade de Deus. (b) Honre os pais (mesmo quando não concordar). (c) Agradeça aos pais pelo cuidado e amor. (d) Ajude em casa sem ser obrigado. (e) Respeite a autoridade dos pais. (f) Peça perdão quando desobedecer. (g) Ore pelos pais. 'Filhos, obedecei a vossos pais em tudo, porque isto é agradável ao Senhor' (Colossenses 3:20). 'Honra a teu pai e a tua mãe, que é o primeiro mandamento com promessa, para que te vá bem, e vivas muito tempo sobre a terra' (Efésios 6:2-3).",
            referencias: "Êxodo 20:12; Deuteronômio 5:16; Atos 5:29; Efésios 6:1-3; Colossenses 3:20; Filipenses 2:8"
        },
        {
            termo: "08. Solteirice e Viuvez - A Centralidade de Cristo",
            definicao: "O apóstolo Paulo ensina que o solteirismo pode ser uma vocação (1 Coríntios 7:7-9,25-38), desde que seja vivido em santidade. Cristo foi solteiro (não se casou). Características do solteirismo cristocêntrico: (1) Cristo como o suficiente: 'Basta-te a minha graça' (2 Coríndios 12:9). (2) Serviço integral ao Senhor: 'O solteiro cuida das coisas do Senhor' (1 Coríndios 7:32-34). (3) Pureza sexual: abster-se de relações sexuais fora do casamento (1 Coríndios 6:18). (4) Comunidade: a igreja como família (Marcos 10:29-30). (5) Contentamento: 'Aprendi a contentar-me com o que tenho' (Filipenses 4:11). (6) Esperança: a ressurreição e a nova criação (Apocalipse 21-22). (7) Cristo como o noivo (para a igreja). Aplicações para os solteiros: (a) Sirva a Cristo com dedicação integral. (b) Mantenha-se puro sexualmente. (c) Envolva-se na igreja (família de Deus). (d) Não idolatre o casamento. (e) Cultive amizades profundas. (f) Use o tempo e recursos para o Reino. (g) Não desanime; Cristo é suficiente. Aplicações para os viúvos: (a) Lute contra o pecado (não se entregue à amargura). (b) Sirva a Cristo com dedicação. (c) Permaneça na igreja. (d) Pode casar novamente 'somente no Senhor' (1 Coríndios 7:39). (e) Lembre-se da esperança da ressurreição (1 Tessalonicenses 4:13-18). 'Digo, porém, aos solteiros e às viúvas, que lhes é bom se ficarem como eu; mas, se não podem conter-se, casem-se. Porque é melhor casar do que abrasar-se' (1 Coríndios 7:8-9). 'A mulher casada está ligada pela lei todo o tempo que o seu marido vive; mas, se falecer o marido, fica livre para casar com quem quiser, contanto que seja no Senhor' (1 Coríndios 7:39).",
            referencias: "Mateus 19:12; 1 Coríndios 7:1-40; 2 Coríndios 12:9; Filipenses 4:11; 1 Tessalonicenses 4:3-5; 1 Tessalonicenses 4:13-18"
        },
        {
            termo: "09. Relações entre Irmãos - Amor Fraternal como Cristo Amou",
            definicao: "Cristo nos ensina a amar uns aos outros como ele nos amou: 'Um novo mandamento vos dou: Que vos ameis uns aos outros; como eu vos amei a vós, que também vós uns aos outros vos ameis' (João 13:34). Aplicações para irmãos (família biológica e igreja): (1) Amor sacrificial: como Cristo amou (Efésios 5:2). (2) Perdão: perdoar como Cristo perdoou (Efésios 4:32). (3) Serviço: servir uns aos outros (Gálatas 5:13). (4) Humildade: considerar o outro superior (Filipenses 2:3). (5) Reconciliação: buscar a paz (Mateus 5:23-24). (6) Não julgar: não julgar os irmãos (Mateus 7:1-5). (7) Encorajamento: edificar uns aos outros (1 Tessalonicenses 5:11). Aplicações específicas para irmãos biológicos: (a) Evitar ciúmes e rivalidades (como José e seus irmãos, Gênesis 37). (b) Ajudar-se mutuamente. (c) Perdoar ofensas. (d) Honrar os pais juntos. (e) Cuidar dos irmãos mais novos. (f) Ser exemplo para os mais novos. 'Nisto todos conhecerão que sois meus discípulos, se vos amardes uns aos outros' (João 13:35). 'Amai-vos ardentemente uns aos outros com amor puro' (1 Pedro 1:22). 'Sede todos sujeitos uns aos outros, e vestidos de humildade' (1 Pedro 5:5).",
            referencias: "Mateus 5:23-24; Mateus 7:1-5; João 13:34-35; Gálatas 5:13; Efésios 4:32; Filipenses 2:3; 1 Tessalonicenses 5:11; 1 Pedro 1:22; 1 Pedro 5:5"
        },
        {
            termo: "10. A Igreja como Família de Deus - Irmãos em Cristo",
            definicao: "Os crentes são chamados de 'família de Deus' (Efésios 2:19) e 'irmãos' (Mateus 23:8). Jesus disse: 'Qualquer que fizer a vontade de meu Pai que está nos céus, este é meu irmão, e irmã, e mãe' (Mateus 12:50). Características da família de Deus: (1) Adoção: 'Recebestes o espírito de adoção de filhos' (Romanos 8:15). (2) Herança: 'Somos herdeiros de Deus e co-herdeiros de Cristo' (Romanos 8:17). (3) Amor fraternal: 'Amai-vos cordialmente uns aos outros com amor fraternal' (Romanos 12:10). (4) Cuidado: 'Se um membro padece, todos os membros padecem com ele' (1 Coríndios 12:26). (5) Disciplina: disciplina fraternal (Mateus 18:15-17). (6) Apoio mútuo: 'Levai as cargas uns dos outros' (Gálatas 6:2). (7) Unidade: 'Um só corpo, um só Espírito' (Efésios 4:4). Aplicações para a igreja: (a) Trate os irmãos como família. (b) Cuide dos necessitados (Tiago 1:27). (c) Visite os enfermos. (d) Ore uns pelos outros. (e) Perdoe as ofensas. (f) Não fofoque. (g) Esteja presente nos cultos e encontros. 'Portanto, enquanto temos tempo, façamos bem a todos, mas principalmente aos domésticos da fé' (Gálatas 6:10). 'Amai-vos uns aos outros com amor fraternal, preferindo-vos em honra uns aos outros' (Romanos 12:10).",
            referencias: "Mateus 12:50; Romanos 8:15-17; Romanos 12:10; 1 Coríndios 12:26; Gálatas 6:2; Gálatas 6:10; Efésios 2:19; Efésios 4:4; Tiago 1:27"
        },
        {
            termo: "11. A Família como Igreja Doméstica - Culto Doméstico",
            definicao: "A família cristã deve ser uma 'igreja doméstica' (igreja em casa). Paulo saúda 'a igreja que está em sua casa' (Romanos 16:5; 1 Coríndios 16:19; Colossenses 4:15; Filemom 1:2). Práticas da igreja doméstica: (1) Leitura da Escritura em família (Deuteronômio 6:6-9). (2) Oração em família (Mateus 18:19-20). (3) Louvor (cânticos espirituais) (Efésios 5:19; Colossenses 3:16). (4) Ensino dos pais aos filhos (Provérbios 22:6). (5) Exemplo dos pais (1 Timóteo 4:12). (6) Ceia do Senhor em casa (Atos 2:46). (7) Hospitalidade (Romanos 12:13). Aplicações: (a) Estabeleça um tempo diário de culto doméstico (pode ser curto: leitura, oração, cântico). (b) Envolva toda a família (marido, esposa, filhos). (c) Ore pelas necessidades da família e da igreja. (d) Cante hinos e cânticos espirituais. (e) Ensine a Bíblia aos filhos. (f) Seja um exemplo de vida cristã. (g) Convide outros crentes para sua casa. 'Ensina-as [estas palavras] a teus filhos e delas fala assentado em tua casa, e andando pelo caminho, e deitando-te e levantando-te' (Deuteronômio 6:7). 'E, perseverando unânimes todos os dias no templo, e partindo o pão em casa, comiam juntos com alegria e singeleza de coração' (Atos 2:46).",
            referencias: "Deuteronômio 6:6-9; Provérbios 22:6; Mateus 18:19-20; Atos 2:46; Romanos 12:13; Romanos 16:5; 1 Coríndios 16:19; Efésios 5:19; Colossenses 3:16; 1 Timóteo 4:12; Filemom 1:2"
        },
        {
            termo: "12. Resolução de Conflitos na Família - O Modelo de Cristo",
            definicao: "Cristo ensinou a resolução de conflitos com base no perdão e na reconciliação (Mateus 5:23-24; 18:15-17). Características da resolução cristocêntrica: (1) Iniciativa: 'Se teu irmão pecar contra ti, vai e repreende-o entre ti e ele só' (Mateus 18:15). (2) Perdão: setentas vezes sete (Mateus 18:21-22). (3) Humildade: 'Aquele que está sem pecado atire a primeira pedra' (João 8:7). (4) Reconciliação: 'Deixa ali a tua oferta... reconcilia-te' (Mateus 5:24). (5) Testemunhas: se não ouvir, toma contigo mais um ou dois (Mateus 18:16). (6) Igreja: se não ouvir, dize à igreja (Mateus 18:17). (7) Amor: 'Acima de tudo, porém, tende amor' (1 Pedro 4:8). Aplicações para a família: (a) Não deixe o sol se pôr sobre a vossa ira (Efésios 4:26). (b) Busque reconciliação rapidamente. (c) Não guarde rancor. (d) Peça perdão quando errar. (e) Perdoe de coração. (f) Evite a fofoca (falar do problema para outros, não para a pessoa). (g) Ore juntos pelos conflitos. 'E sede uns para com os outros benignos, misericordiosos, perdoando-vos uns aos outros, como também Deus vos perdoou em Cristo' (Efésios 4:32). 'Assim como Cristo vos perdoou, assim fazei vós também' (Colossenses 3:13). 'Portanto, se trouxeres a tua oferta ao altar e aí te lembrares de que teu irmão tem alguma coisa contra ti, deixa ali a tua oferta... vai primeiro reconciliar-te com teu irmão' (Mateus 5:23-24).",
            referencias: "Mateus 5:23-24; Mateus 18:15-22; João 8:1-11; Efésios 4:26; Efésios 4:32; Colossenses 3:13; 1 Pedro 4:8"
        },
        {
            termo: "13. Síntese: Cristo, o Fundamento e Modelo da Família Cristã",
            definicao: "Cristo é o fundamento e o modelo da família cristã. 'E tudo quanto fizerdes, por palavra ou por obra, fazei-o em nome do Senhor Jesus' (Colossenses 3:17). Resumo da família cristocêntrica: (1) O casamento é um tipo da união de Cristo com a igreja. (2) O marido deve amar a esposa como Cristo amou a igreja (sacrificialmente). (3) A esposa deve se submeter ao marido como a igreja se submete a Cristo. (4) Os pais devem criar os filhos na disciplina e admoestação do Senhor. (5) Os filhos devem obedecer e honrar os pais. (6) Os solteiros e viúvos encontram sua identidade e satisfação em Cristo. (7) Os irmãos devem amar-se como Cristo amou. (8) A igreja é a família de Deus. (9) A família deve ser uma igreja doméstica (culto doméstico). (10) Os conflitos devem ser resolvidos à luz do perdão de Cristo. 'Porque, assim como o corpo é um e tem muitos membros, e todos os membros, sendo muitos, são um só corpo, assim é Cristo também' (1 Coríndios 12:12). 'E sede agradecidos' (Colossenses 3:15). 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36). Soli Deo Gloria!",
            referencias: "Romanos 11:36; 1 Coríndios 12:12; Efésios 5:22-33; Colossenses 3:12-17"
        }
    ]
};