// volume/volume-100.js
window.LIVRO_DATA = {
    nome: "Volume C",
    dados: [
        {
            termo: "01. Introdução: Cristo, o Noivo Celestial, e Sua Noiva, a Igreja",
            definicao: "A teologia do noivado divino revela que Cristo é o Noivo celestial e a igreja é a Sua amada Noiva, chamada a entrar no Santo dos Santos pela Sua obra redentora. 'Porque eu vos tenho preparado para vos apresentar como uma virgem pura a um só marido, que é Cristo' (2 Coríndios 11:2). O relacionamento entre Cristo e a igreja é o ápice da história da salvação: um amor eterno, um pacto indissolúvel e uma comunhão perfeita. Diferente de qualquer relacionamento humano, este noivado é santo, eterno e glorioso. Características da Noiva de Cristo: (1) Escolhida antes da fundação do mundo (Efésios 1:4). (2) Redimida pelo sangue do Noivo (Atos 20:28). (3) Purificada pela água da Palavra (Efésios 5:26-27). (4) Vestida com as vestes da justiça de Cristo (Isaías 61:10; Apocalipse 19:8). (5) Chamada a ser santa e sem mácula (Efésios 5:27). (6) Aguarda o encontro final com o Noivo (Apocalipse 19:7-9). (7) Entra no Santo dos Santos pelo sangue de Cristo (Hebreus 10:19-20). (8) Une-se a Cristo na eternidade (Apocalipse 21:2-3). (9) Adora ao Deus três vezes santo (Apocalipse 4:8). (10) Proclama 'Santo, Santo, Santo' juntamente com os anjos. A teologia reformada (Calvino, Owen, Edwards, Boston) vê o casamento entre Cristo e a igreja como o mistério supremo da fé. 'Grande é este mistério; digo-o, porém, a respeito de Cristo e da igreja' (Efésios 5:32).",
            referencias: "Cântico dos Cânticos 2:16; Cântico dos Cânticos 6:3; Isaías 54:5-8; Isaías 61:10; Jeremias 2:2; Ezequiel 16:8-14; Oséias 2:19-20; Mateus 9:15; Mateus 22:2-14; Mateus 25:1-13; João 3:29; Romanos 7:4; 2 Coríndios 11:2; Efésios 5:22-33; Apocalipse 19:7-9; Apocalipse 21:2; Apocalipse 21:9-11; Apocalipse 22:17"
        },
        {
            termo: "02. A Noiva no Antigo Testamento - Israel como Esposa de Deus",
            definicao: "No Antigo Testamento, Deus apresenta-se como o esposo de Israel, e Israel como Sua esposa infiel, que será purificada e restaurada. 'Porque o teu Criador é o teu marido; o Senhor dos Exércitos é o seu nome' (Isaías 54:5). O casamento divino com Israel: (1) Deus escolheu Israel como Sua propriedade especial (Deuteronômio 7:6-8). (2) No Sinai, Deus fez um pacto de casamento com Israel (Êxodo 19:5-8; 24:7-8). (3) Israel, porém, foi infiel, cometendo adultério espiritual com ídolos (Ezequiel 16; Oséias 1-3). (4) Deus a disciplina, mas promete restaurá-la (Oséias 2:14-23). (5) A restauração inclui um novo coração e um novo pacto (Ezequiel 36:25-28; Jeremias 31:31-34). (6) No futuro, Israel será chamada 'Hefzibá' (meu prazer está nela) e a terra 'Beulá' (casada) (Isaías 62:4-5). (7) O casamento de Deus com Israel aponta para Cristo e a igreja. O Santo dos Santos no AT: (a) Era o lugar mais sagrado, onde a arca da aliança estava (Êxodo 26:31-34). (b) Somente o sumo sacerdote entrava uma vez por ano (Levítico 16). (c) Simbolizava a presença de Deus e a necessidade de expiação. (d) O véu separava Deus do povo (Êxodo 26:33). (e) Apontava para Cristo, que abriria o caminho. A teologia reformada (Calvino, Bavinck, Robertson, Clowney) vê o casamento de Deus com Israel como tipo do casamento de Cristo com a igreja. 'Desposar-te-ei comigo para sempre' (Oséias 2:19).",
            referencias: "Êxodo 19:5-8; Êxodo 24:7-8; Levítico 16; Deuteronômio 7:6-8; Salmo 45; Isaías 50:1; Isaías 54:5-8; Isaías 62:4-5; Jeremias 2:2; Jeremias 3:1-14; Jeremias 31:31-34; Ezequiel 16:1-63; Ezequiel 23; Ezequiel 36:25-28; Oséias 1-3; Oséias 2:19-20; Malaquias 2:11"
        },
        {
            termo: "03. Cristo, o Noivo Celestial - O Amor Eterno",
            definicao: "Cristo é o Noivo celestial que amou a igreja e se entregou por ela, para a santificar e purificar. 'Vós, maridos, amai vossa mulher, como também Cristo amou a igreja e a si mesmo se entregou por ela' (Efésios 5:25). O amor de Cristo pela Noiva: (1) Amor eterno: escolheu a Noiva antes da fundação do mundo (Efésios 1:4-5). (2) Amor redentor: deu Sua vida por ela (Efésios 5:25; João 10:11). (3) Amor santificador: purifica a Noiva pela Palavra (Efésios 5:26). (4) Amor glorificador: apresentará a Noiva sem mácula (Efésios 5:27). (5) Amor providente: cuida da Noiva como de Seu próprio corpo (Efésios 5:29). (6) Amor sacrificial: humilhou-se até a morte de cruz (Filipenses 2:5-8). (7) Amor fiel: nunca abandona Sua Noiva (Hebreus 13:5). (8) Amor eterno: a união é para sempre (João 10:28-29). (9) Amor nupcial: a igreja é Sua única Noiva (2 Coríndios 11:2). (10) Amor consumado: na eternidade, o casamento será completo (Apocalipse 19:7-9). A teologia reformada (Calvino, Owen, Boston, Edwards) contempla o amor de Cristo pela igreja como o modelo e fundamento de todo amor. 'Nós amamos a ele porque ele nos amou primeiro' (1 João 4:19).",
            referencias: "Isaías 54:5; Mateus 9:15; Mateus 22:2; Mateus 25:1; João 3:29; João 10:11; João 10:28-29; Romanos 5:5-8; Romanos 8:35-39; 2 Coríndios 11:2; Gálatas 2:20; Efésios 1:4-5; Efésios 5:25-32; Filipenses 2:5-8; Colossenses 1:13-14; Tito 2:14; Hebreus 9:14; Hebreus 13:5; 1 Pedro 1:18-19; 1 João 3:16; 1 João 4:10; Apocalipse 1:5-6"
        },
        {
            termo: "04. A Noiva no Novo Testamento - A Igreja, Corpo e Noiva",
            definicao: "O Novo Testamento revela que a igreja é tanto o corpo de Cristo quanto a Noiva de Cristo. 'Porque somos membros do seu corpo, da sua carne e dos seus ossos' (Efésios 5:30). A igreja como Noiva: (1) É apresentada como virgem pura a Cristo (2 Coríndios 11:2). (2) É a amada do Noivo (Efésios 5:28-29). (3) É lavada e purificada (Tito 3:5-6; 1 Coríndios 6:11). (4) É vestida com vestes brancas (Apocalipse 19:8). (5) Aguarda a vinda do Noivo (Mateus 25:1-13). (6) Participa das bodas do Cordeiro (Apocalipse 19:7-9). (7) Desce do céu como cidade adornada (Apocalipse 21:2). (8) É chamada de 'Jerusalém celestial' (Gálatas 4:26; Hebreus 12:22). (9) É composta de judeus e gentios em um só corpo (Efésios 2:14-18). (10) Tem acesso direto ao Santo dos Santos pelo sangue de Cristo (Hebreus 10:19-22). Diferente do AT, onde apenas o sumo sacerdote entrava no Santo dos Santos, agora todo crente tem acesso direto a Deus. O véu do templo se rasgou (Mateus 27:51), e Cristo, nosso Sumo Sacerdote, nos introduz na presença de Deus. 'Tendo, pois, irmãos, ousadia para entrar no Santuário, pelo sangue de Jesus' (Hebreus 10:19). A teologia reformada (Calvino, Bavinck, Berkhof, Ridderbos) enfatiza a união mística entre Cristo e a igreja como fundamento de todos os benefícios da salvação. 'Aquele que se une ao Senhor é um mesmo espírito' (1 Coríndios 6:17).",
            referencias: "Mateus 9:15; Mateus 25:1-13; João 3:29; Atos 20:28; Romanos 7:4; 1 Coríndios 6:15-17; 1 Coríndios 12:12-27; 2 Coríndios 11:2; Gálatas 3:26-29; Efésios 1:22-23; Efésios 2:14-22; Efésios 4:15-16; Efésios 5:22-33; Colossenses 1:18; Colossenses 1:24; Hebreus 10:19-22; 1 Pedro 2:4-10; Apocalipse 19:7-9; Apocalipse 21:2; Apocalipse 21:9-11"
        },
        {
            termo: "05. A Entrada no Santo dos Santos - Pelo Sangue de Cristo",
            definicao: "A obra redentora de Cristo abriu o caminho para que os crentes, a Noiva, entrem no Santo dos Santos, a própria presença de Deus. 'Tendo, pois, irmãos, ousadia para entrar no Santuário, pelo sangue de Jesus, pelo novo e vivo caminho que ele nos consagrou, pelo véu, isto é, pela sua carne' (Hebreus 10:19-20). O Santo dos Santos no AT: (a) Era o lugar mais sagrado, medindo 10x10x10 côvados (1 Reis 6:20). (b) Continha a arca da aliança, o propiciatório e os querubins (Êxodo 25:10-22). (c) Somente o sumo sacerdote entrava, uma vez por ano, no Dia da Expiação (Levítico 16). (d) O véu impedia a entrada do povo (Êxodo 26:31-33). (e) Simbolizava a separação entre Deus santo e o povo pecador. A entrada no Santo dos Santos pelo sangue de Cristo: (1) Cristo é o Sumo Sacerdote perfeito (Hebreus 4:14-16; 7:26-28). (2) Cristo ofereceu Seu próprio sangue, não sangue de animais (Hebreus 9:12). (3) O véu se rasgou na morte de Cristo (Mateus 27:51; Marcos 15:38; Lucas 23:45). (4) Agora todo crente tem acesso direto a Deus (Efésios 2:18; 3:12). (5) Não precisamos mais de mediadores humanos (1 Timóteo 2:5). (6) Podemos nos aproximar com confiança (Hebreus 4:16). (7) Somos feitos sacerdotes reais (1 Pedro 2:5,9). (8) A Noiva está na presença do Noivo. A teologia reformada (Calvino, Owen, Murray, Sproul) celebra o acesso direto a Deus como privilégio inefável da Noiva de Cristo. 'Cheguemo-nos, pois, com confiança ao trono da graça' (Hebreus 4:16).",
            referencias: "Êxodo 25:10-22; Êxodo 26:31-34; Levítico 16:1-34; 1 Reis 6:16-20; 2 Crônicas 3:8-14; Mateus 27:51; Marcos 15:38; Lucas 23:45; João 14:6; Romanos 5:1-2; Efésios 2:18; Efésios 3:12; Colossenses 1:21-22; Hebreus 4:14-16; Hebreus 6:19-20; Hebreus 7:26-28; Hebreus 9:1-28; Hebreus 10:19-22; 1 Pedro 2:5; 1 Pedro 2:9"
        },
        {
            termo: "06. A Santificação da Noiva - Purificada para o Noivo",
            definicao: "A Noiva de Cristo é purificada e santificada para ser apresentada ao Noivo como gloriosa, sem mácula nem ruga. 'Para a santificar, purificando-a com a lavagem da água, pela palavra, para a apresentar a si mesmo igreja gloriosa, sem mácula, nem ruga, nem coisa semelhante' (Efésios 5:26-27). O processo de santificação: (1) Justificação: declarada justa pela fé em Cristo (Romanos 3:24-26). (2) Regeneração: nascida de novo pelo Espírito (João 3:3-5; Tito 3:5). (3) Santificação progressiva: transformada à imagem de Cristo (Romanos 12:2; 2 Coríndios 3:18). (4) Purificação pela Palavra: a Escritura santifica (João 17:17). (5) Purificação pelo sangue: Cristo nos purifica (1 João 1:7). (6) Purificação pelo Espírito: o Espírito produz fruto (Gálatas 5:22-23). (7) Purificação pela disciplina: Deus nos disciplina como filhos (Hebreus 12:5-11). A Noiva é vestida: (a) Com a justiça imputada de Cristo (Romanos 3:22; Filipenses 3:9). (b) Com a justiça prática da santidade (Apocalipse 19:8 - 'as vestes de linho fino são as justiças dos santos'). (c) Com vestes brancas (Apocalipse 7:14 - 'lavaram suas vestes e as branquearam no sangue do Cordeiro'). A teologia reformada (Calvino, Owen, Boston, Bonar) enfatiza que a santificação é obra de Deus e responsabilidade do crente. 'Segui a paz com todos e a santificação, sem a qual ninguém verá o Senhor' (Hebreus 12:14).",
            referencias: "João 15:3; João 17:17; Romanos 6:1-23; Romanos 8:29-30; Romanos 12:1-2; 1 Coríndios 1:30; 1 Coríndios 6:11; 2 Coríndios 3:18; 2 Coríndios 7:1; Gálatas 5:22-25; Efésios 4:22-24; Efésios 5:26-27; Filipenses 3:12-14; Colossenses 3:5-17; 1 Tessalonicenses 4:3-8; Tito 2:11-14; Tito 3:5; Hebreus 12:5-14; 1 Pedro 1:15-16; 2 Pedro 3:14; 1 João 1:7; 1 João 3:2-3; Apocalipse 7:14; Apocalipse 19:8"
        },
        {
            termo: "07. A Adoração no Santo dos Santos - Santo, Santo, Santo!",
            definicao: "A Noiva de Cristo entra no Santo dos Santos não apenas para estar na presença de Deus, mas para adorá-Lo com o eterno cântico: 'Santo, Santo, Santo é o Senhor Deus, o Todo-Poderoso, que era, e é, e há de vir' (Apocalipse 4:8). A adoração tríplice 'Santo, Santo, Santo': (1) A primeira proclamação: os serafins no céu (Isaías 6:3). (2) A repetição eterna: os quatro seres viventes (Apocalipse 4:8). (3) A participação da igreja: todos os remidos se unem (Apocalipse 5:9-14; 7:9-12). Significado do 'Santo, Santo, Santo': (a) A santidade de Deus Pai: o Criador santo (Isaías 6:3; Apocalipse 4:8). (b) A santidade de Deus Filho: o Cordeiro santo (Apocalipse 5:9-10). (c) A santidade de Deus Espírito Santo: o Espírito santo (Mateus 28:19). (d) A Trindade santa: três pessoas, um só Deus santo. (e) A intensidade da santidade: repetição tríplice indica perfeição e ênfase. (f) A resposta da Noiva: 'Amém' e 'Aleluia' (Apocalipse 5:14; 19:1-4). A Noiva adora com os anjos: (1) Os querubins e serafins (Ezequiel 10; Isaías 6). (2) Os quatro seres viventes (Apocalipse 4:6-8). (3) Os vinte e quatro anciãos (Apocalipse 4:4,10-11). (4) Multidão de anjos (Hebreus 12:22; Apocalipse 5:11). (5) Toda a criação (Apocalipse 5:13). A teologia reformada (Calvino, Owen, Edwards, Tozer) chama a igreja a adorar a Deus em espírito e em verdade, reconhecendo Sua santidade absoluta. 'Exaltai ao Senhor nosso Deus, e prostrai-vos ante o escabelo de seus pés, porque ele é santo' (Salmo 99:5).",
            referencias: "Êxodo 15:11; 1 Samuel 2:2; Salmo 22:3; Salmo 29:2; Salmo 47:8; Salmo 96:9; Salmo 99:3; Salmo 99:5; Salmo 99:9; Isaías 6:1-3; Isaías 57:15; Ezequiel 1:4-28; Ezequiel 3:12; Daniel 7:9-10; Miqueias 4:2; Zacarias 14:5; Mateus 6:9; Lucas 1:49; Lucas 2:14; Atos 3:14; Romanos 1:4; 1 Coríndios 3:17; 1 Pedro 1:15-16; Apocalipse 3:7; Apocalipse 4:8-11; Apocalipse 5:8-14; Apocalipse 7:11-12; Apocalipse 11:15-18; Apocalipse 15:3-4; Apocalipse 19:1-8"
        },
        {
            termo: "08. A União Mística com Cristo - Um Só Espírito",
            definicao: "A entrada no Santo dos Santos não é apenas acesso à presença de Deus, mas união mística com Cristo, o Noivo. 'Aquele que se une ao Senhor é um mesmo espírito' (1 Coríndios 6:17). A união mística: (1) É real: não é meramente simbólica ou legal. (2) É espiritual: realizada pelo Espírito Santo (1 Coríndios 12:13). (3) É orgânica: como o corpo e a cabeça (Efésios 1:22-23; 5:29-30). (4) É vital: Cristo é a videira, nós somos os ramos (João 15:1-8). (5) É nupcial: como marido e mulher (Efésios 5:31-32). (6) É eterna: nada pode separar (Romanos 8:38-39). (7) É participativa: participamos da natureza divina (2 Pedro 1:4). (8) É transformadora: somos transformados à Sua imagem (2 Coríndios 3:18). Frutos da união: (a) Vida eterna (João 17:3). (b) Fruto do Espírito (Gálatas 5:22-23). (c) Santificação (Romanos 6:1-14). (d) Conhecimento de Deus (João 17:3). (e) Amor fraternal (1 João 4:7-12). (f) Ousadia no dia do juízo (1 João 4:17). A teologia reformada (Calvino, Owen, Murray, Berkhof) considera a união mística como o fundamento de todos os benefícios da salvação. 'Já não sou eu quem vive, mas Cristo vive em mim' (Gálatas 2:20).",
            referencias: "João 14:20; João 15:1-8; João 17:21-23; Romanos 6:3-8; Romanos 7:4; Romanos 8:9-11; 1 Coríndios 6:15-17; 1 Coríndios 12:12-13; 2 Coríndios 5:17; Gálatas 2:20; Gálatas 3:27-28; Efésios 1:22-23; Efésios 5:30-32; Colossenses 1:27; Colossenses 3:3-4; 2 Pedro 1:4; 1 João 3:24; 1 João 4:13-16"
        },
        {
            termo: "09. A Esperança da Noiva - As Bodas do Cordeiro",
            definicao: "A Noiva aguarda com esperança a consumação final: as bodas do Cordeiro, quando será eternamente unida ao Noivo. 'Regozijemo-nos, e alegremo-nos, e demos-lhe glória; porque vindas são as bodas do Cordeiro, e já a sua esposa se aprontou' (Apocalipse 19:7). As bodas do Cordeiro: (1) O banquete escatológico: festa de alegria perfeita (Isaías 25:6-8; Mateus 22:2-14; 25:1-13; Lucas 22:16). (2) O encontro final: a Noiva será apresentada ao Noivo (Efésios 5:27). (3) A união eterna: não mais separação (Apocalipse 21:3-4). (4) A festa eterna: alegria sem fim (Apocalipse 19:9). (5) A Noiva vestida: linho fino, justiças dos santos (Apocalipse 19:8). (6) O convite universal: 'Vinde, porque tudo já está preparado' (Mateus 22:4; Apocalipse 22:17). A preparação da Noiva: (a) Arrependimento e fé (Marcos 1:15). (b) Santificação e pureza (1 João 3:3). (c) Vigilância e oração (Mateus 25:13; 26:41). (d) Boas obras e amor (Apocalipse 19:8). (e) Perseverança até o fim (Mateus 24:13). A ansiosa expectativa: (1) O Espírito e a Noiva dizem: 'Vem!' (Apocalipse 22:17). (2) A oração da igreja: 'Maranata! Ora, vem, Senhor Jesus!' (1 Coríndios 16:22; Apocalipse 22:20). (3) A certeza da esperança: 'Aquele que testifica estas coisas diz: Certamente cedo venho' (Apocalipse 22:20). A teologia reformada (Calvino, Owen, Hoekema, Ridderbos) aguarda com esperança a consumação do casamento celestial. 'Bem-aventurados aqueles que são chamados à ceia das bodas do Cordeiro' (Apocalipse 19:9).",
            referencias: "Isaías 25:6-8; Isaías 61:10; Jeremias 33:11; Mateus 8:11; Mateus 22:2-14; Mateus 25:1-13; Lucas 12:35-37; Lucas 22:16; João 14:2-3; Romanos 8:18-25; 1 Coríndios 15:51-54; 2 Coríndios 5:1-5; Efésios 5:27; Filipenses 3:20-21; Colossenses 3:4; 1 Tessalonicenses 4:16-17; Tito 2:13; Hebreus 9:28; 1 Pedro 1:3-5; 1 João 3:2-3; Apocalipse 19:7-9; Apocalipse 21:2-4; Apocalipse 22:17; Apocalipse 22:20"
        },
        {
            termo: "10. A Noiva Adoradora - Santo, Santo, Santo na Eternidade",
            definicao: "Na eternidade, a Noiva de Cristo entrará plenamente no Santo dos Santos celestial e proclamará eternamente 'Santo, Santo, Santo' juntamente com todos os anjos e santos. 'E não vi templo algum nela, porque o seu templo é o Senhor Deus Todo-Poderoso, e o Cordeiro' (Apocalipse 21:22). O Santo dos Santos celestial: (1) Não há templo físico: Deus mesmo é o templo (Apocalipse 21:22). (2) A presença plena de Deus: verei a Deus face a face (1 Coríndios 13:12; 1 João 3:2). (3) O trono de Deus e do Cordeiro: um só trono (Apocalipse 22:1,3). (4) O rio e a árvore da vida (Apocalipse 22:1-2). (5) A luz de Deus: o Cordeiro é a lâmpada (Apocalipse 21:23). A adoração eterna: (a) Sem cessar: dia e noite (Apocalipse 4:8). (b) Com alegria: não mais lágrimas (Apocalipse 21:4). (c) Com todos os redimidos: multidão incontável (Apocalipse 7:9). (d) Com os anjos: todos os exércitos celestiais (Apocalipse 5:11-12). (e) Com o cântico de Moisés e do Cordeiro (Apocalipse 15:3-4). (f) Com o cântico novo (Apocalipse 5:9-10). (g) Proclamando 'Santo, Santo, Santo' (Apocalipse 4:8). (h) Proclamando 'Digno é o Cordeiro' (Apocalipse 5:12). (i) Proclamando 'Aleluia' (Apocalipse 19:1-6). A Noiva consumada: (1) Sem pecado: perfeita santidade (Hebreus 12:23). (2) Sem sofrimento: Deus enxuga as lágrimas (Apocalipse 21:4). (3) Sem morte: vida eterna (1 Coríndios 15:54-55). (4) Unida a Cristo: para sempre com o Senhor (1 Tessalonicenses 4:17). A teologia reformada (Calvino, Bavinck, Hoekema, Sproul) anseia por essa adoração eterna, onde a Noiva finalmente verá o Noivo face a face. 'Quanto a mim, verei a tua face com justiça; eu me satisfarei quando acordar à tua semelhança' (Salmo 17:15).",
            referencias: "Salmo 16:11; Salmo 17:15; Salmo 42:1-2; Isaías 6:3; Ezequiel 48:35; Mateus 5:8; 1 Coríndios 13:12; 2 Coríndios 5:1-8; Filipenses 1:23; 1 Tessalonicenses 4:17; 1 João 3:2; Apocalipse 4:8-11; Apocalipse 5:9-14; Apocalipse 7:9-17; Apocalipse 11:15-18; Apocalipse 14:1-5; Apocalipse 15:3-4; Apocalipse 19:1-8; Apocalipse 21:1-27; Apocalipse 22:1-5"
        },
        {
            termo: "11. Exortação à Noiva - Santidade e Preparação",
            definicao: "Enquanto aguarda as bodas do Cordeiro, a Noiva deve viver em santidade, vigilância e amor, preparando-se para o encontro com o Noivo. 'E todo aquele que nele tem esta esperança purifica-se a si mesmo, como também ele é puro' (1 João 3:3). Exortações à Noiva: (1) Santidade: sede santos, porque Eu sou santo (1 Pedro 1:16). (2) Vigilância: vigiai, porque não sabeis o dia nem a hora (Mateus 25:13). (3) Oração: orai sem cessar (1 Tessalonicenses 5:17). (4) Amor fraternal: amai-vos uns aos outros (João 13:34-35). (5) Fidelidade: sede fiéis até à morte (Apocalipse 2:10). (6) Humildade: Deus resiste aos soberbos (Tiago 4:6). (7) Perseverança: aquele que perseverar até ao fim será salvo (Mateus 24:13). (8) Missão: ide e fazei discípulos (Mateus 28:19-20). (9) Adoração: adorai ao Senhor em espírito e em verdade (João 4:24). (10) Esperança: aguardai a bem-aventurada esperança (Tito 2:13). O que a Noiva deve evitar: (a) Adultério espiritual: idolatria e mundanismo (Tiago 4:4; 1 João 2:15-17). (b) Frieza espiritual: deixar o primeiro amor (Apocalipse 2:4). (c) Obras mortas: justiça própria (Apocalipse 3:1). (d) Divisões e contendas (1 Coríndios 1:10). (e) Falsos mestres que enganam (Mateus 24:24). A teologia reformada (Calvino, Owen, Boston, Bonhoeffer) chama a igreja a uma vida de santidade e preparação, com os olhos fixos em Cristo. 'Corramos com paciência a carreira que nos está proposta, olhando para Jesus, autor e consumador da fé' (Hebreus 12:1-2).",
            referencias: "Mateus 5:13-16; Mateus 24:42-44; Mateus 25:1-13; João 13:34-35; Atos 1:8; Romanos 12:1-2; 1 Coríndios 15:58; Gálatas 5:22-25; Efésios 4:1-3; Efésios 5:8-10; Filipenses 2:14-16; Colossenses 3:1-4; 1 Tessalonicenses 3:12-13; 1 Tessalonicenses 4:1-8; 1 Tessalonicenses 5:5-11; Tito 2:11-14; Hebreus 12:1-2; Tiago 4:4-10; 1 Pedro 1:13-16; 1 Pedro 4:7-11; 2 Pedro 3:11-14; 1 João 2:15-17; 1 João 3:2-3; Judas 1:20-21; Apocalipse 2:4-5; Apocalipse 3:2-3; Apocalipse 19:7-8"
        },
        {
            termo: "12. Síntese: A Noiva no Santo dos Santos - Santo, Santo, Santo, para Sempre!",
            definicao: "A teologia da Noiva de Cristo revela o propósito eterno de Deus: uma igreja santa, redimida, unida a Cristo e adorando-O eternamente no Santo dos Santos celestial. Resumo final: (1) Cristo é o Noivo celestial que amou e escolheu a igreja antes da fundação do mundo. (2) Israel no AT foi a esposa infiel, que apontava para a Noiva perfeita do NT. (3) A igreja é a Noiva, o corpo e a amada de Cristo. (4) Pelo sangue de Cristo, a Noiva tem acesso direto ao Santo dos Santos. (5) A Noiva é purificada e santificada pela Palavra, pelo sangue e pelo Espírito. (6) No Santo dos Santos, a Noiva adora a Deus com o cântico eterno: 'Santo, Santo, Santo'. (7) A união mística com Cristo é a realidade central da experiência cristã. (8) A Noiva aguarda as bodas do Cordeiro, a consumação final. (9) Na eternidade, a Noiva verá Deus face a face e O adorará para sempre. (10) Enquanto aguarda, a Noiva deve viver em santidade, vigilância e missão. (11) O chamado final é: 'Vem, Senhor Jesus!' (Apocalipse 22:20). (12) Toda a história da salvação caminha para a união perfeita entre Cristo e a igreja. (13) A adoração eterna é 'Santo, Santo, Santo é o Senhor Deus, o Todo-Poderoso, que era, e é, e há de vir' (Apocalipse 4:8). A teologia reformada (Calvino, Owen, Boston, Edwards, Spurgeon, Lloyd-Jones, Sproul) chama a igreja a viver como Noiva que se prepara para o encontro com o Noivo, com lâmpadas acesas, vestes brancas e coração puro. 'Eis que estou à porta e bato; se alguém ouvir a minha voz e abrir a porta, entrarei em sua casa e com ele cearei, e ele comigo' (Apocalipse 3:20). Maranata! Ora, vem, Senhor Jesus! Soli Deo Gloria! Santo, Santo, Santo!",
            referencias: "Salmo 95:6; Salmo 96:7-9; Isaías 6:3; Isaías 35:10; Isaías 51:11; Zacarias 14:20-21; Mateus 22:2; Mateus 25:6; Lucas 2:14; João 4:24; Romanos 11:36; 1 Coríndios 6:17; 2 Coríndios 11:2; Efésios 1:4-5; Efésios 5:25-27; Filipenses 3:20-21; Colossenses 1:21-22; 1 Tessalonicenses 4:17; Tito 2:13; Hebreus 4:16; Hebreus 10:19-22; Hebreus 12:22-24; 1 Pedro 1:3-5; 1 Pedro 2:9; 1 João 3:2-3; Apocalipse 1:5-6; Apocalipse 3:20; Apocalipse 4:8-11; Apocalipse 5:9-14; Apocalipse 7:9-12; Apocalipse 19:1-8; Apocalipse 21:1-4; Apocalipse 22:1-5; Apocalipse 22:17; Apocalipse 22:20"
        }
    ]
};