// volume/volume-25.js
window.LIVRO_DATA = {
    nome: "Volume XXV",
    dados: [
        {
            termo: "01. Introdução: A Pregação Cristocêntrica como Ato de Adoração",
            definicao: "A pregação cristã é a proclamação (kerygma) da pessoa e obra de Jesus Cristo como o centro de toda a Escritura. A teologia reformada enfatiza que a pregação deve ser cristocêntrica, não apenas moralista, nem psicológica, nem política. O apóstolo Paulo declarou: 'Porque não me propus saber coisa alguma entre vós, senão a Jesus Cristo, e este crucificado' (1 Coríntios 2:2). A pregação cristocêntrica significa: (1) Pregar Cristo a partir de todo o Antigo Testamento (Lucas 24:27,44-45). (2) Pregar Cristo a partir de todo o Novo Testamento (João 5:39). (3) Pregar Cristo como o único Salvador (Atos 4:12). (4) Pregar Cristo crucificado (expiação vicária) e ressurreto (vitória sobre a morte). (5) Pregar Cristo para a fé, o arrependimento e a santificação. Este volume oferece orientações práticas para a pregação cristocêntrica, com exemplos e esboços de sermões. 'Examinais as Escrituras, porque vós cuidais ter nelas a vida eterna, e são elas que de mim testificam' (João 5:39).",
            referencias: "Lucas 24:27; Lucas 24:44-45; João 5:39; Atos 2:14-41; Atos 4:12; Romanos 10:13-17; 1 Coríntios 1:18-25; 1 Coríntios 2:1-5; 2 Coríntios 4:5; 2 Timóteo 4:1-5"
        },
        {
            termo: "02. A Hermenêutica Cristocêntrica (Cristo em Todas as Escrituras)",
            definicao: "A hermenêutica é a arte da interpretação bíblica. A hermenêutica cristocêntrica afirma que Cristo é a chave para interpretar toda a Escritura. Princípios: (1) O Antigo Testamento aponta para Cristo em profecias, tipos, figuras e teofanias. (2) O Novo Testamento interpreta o Antigo Testamento à luz de Cristo. (3) Cristo é o cumprimento (telos) da Lei (Romanos 10:4). (4) Cristo é o 'Amém' de todas as promessas de Deus (2 Coríntios 1:20). (5) A Escritura deve ser lida com a 'analogia da fé' (analogia fidei): a Escritura interpreta a si mesma, e Cristo é o centro. Métodos para pregar Cristo no Antigo Testamento: (a) Profecias messiânicas diretas (Isaías 53; Salmo 22; Miqueias 5:2). (b) Tipos (Adão, Melquisedeque, Isaque, José, Moisés, Josué, Davi, Jonas). (c) Eventos históricos (Páscoa, Êxodo, travessia do Mar Vermelho, maná, rocha ferida, serpente de bronze). (d) Instituições (tabernáculo, templo, sacerdócio, sacrifícios, festas). (e) Teofanias (aparições do Anjo do Senhor). A teologia reformada segue a hermenêutica de Calvino e dos puritanos: 'A Escritura é uma manjedoura onde Cristo é deitado' (Calvino).",
            referencias: "Lucas 24:27; Lucas 24:44-45; João 5:39; Atos 8:26-40; Atos 17:2-3; Romanos 10:4; 2 Coríntios 1:20; Gálatas 3:24; Colossenses 2:17; Hebreus 8:5; Hebreus 10:1"
        },
        {
            termo: "03. Pregando Cristo a partir do Antigo Testamento (Exemplos)",
            definicao: "Exemplos de como pregar Cristo a partir de passagens específicas do Antigo Testamento: (1) Gênesis 3:15 (proto-evangelho): Pregar a promessa de um Redentor que esmagaria a cabeça da serpente. Esboço: (a) A queda: o pecado trouxe a maldição. (b) A promessa: Deus promete um Redentor. (c) O cumprimento: Cristo é a semente da mulher. (2) Êxodo 12:1-28 (Cordeiro pascal): Pregar a libertação do pecado pelo sangue de Cristo. Esboço: (a) A escravidão do Egito (pecado). (b) O cordeiro sem defeito (Cristo sem pecado). (c) O sangue nos umbrais (a expiação). (d) A libertação (salvação em Cristo). (3) Isaías 53:1-12 (Servo Sofredor): Pregar a expiação vicária. Esboço: (a) O servo desprezado (Cristo rejeitado). (b) O servo ferido por nossas transgressões (substituição). (c) O servo ressurreto (vitória). A teologia reformada enfatiza que o Antigo Testamento não é apenas história ou moral, mas preparação para Cristo.",
            referencias: "Gênesis 3:15; Êxodo 12:1-28; Levítico 16:1-34; Números 21:4-9; Deuteronômio 18:15-19; Salmo 22; Isaías 53:1-12; Isaías 61:1-3; Jeremias 23:5-6; Ezequiel 34:23-24; Daniel 7:13-14; Miqueias 5:2; Zacarias 9:9; Zacarias 12:10"
        },
        {
            termo: "04. Pregando Cristo a partir dos Evangelhos",
            definicao: "Os evangelhos (Mateus, Marcos, Lucas, João) são testemunhos da vida, morte e ressurreição de Jesus. Para pregar Cristo a partir dos evangelhos: (1) Enfatize a identidade de Jesus (Quem ele é: Filho de Deus, Messias, Senhor). (2) Enfatize a obra de Jesus (O que ele fez: ensinou, curou, morreu, ressuscitou). (3) Enfatize o chamado de Jesus (O que ele exige: arrependimento, fé, discipulado). Exemplos: (a) Mateus 1:1-17 (Genealogia): A fidelidade de Deus em cumprir suas promessas. Esboço: Cristo é o Filho de Abraão e Davi. (b) Mateus 5-7 (Sermão do Montanha): A justiça superior do Reino. Esboço: a justiça de Cristo imputada e a santidade exigida. (c) João 1:1-18 (Prólogo): A divindade e encarnação de Cristo. Esboço: (i) O Verbo eterno (divindade); (ii) O Verbo encarnado (humanidade); (iii) O Verbo revelado (graça e verdade). (d) João 11:1-44 (Ressurreição de Lázaro): Jesus é a ressurreição e a vida. Esboço: (i) O sofrimento e a morte; (ii) A esperança na ressurreição; (iii) Jesus é a ressurreição. A teologia reformada enfatiza a pregação expositiva (versículo por versículo) dos evangelhos.",
            referencias: "Mateus 1:1-17; Mateus 5-7; Marcos 1:1; Lucas 1:1-4; Lucas 24:13-35; João 1:1-18; João 3:1-21; João 4:1-42; João 11:1-44; João 20:1-31"
        },
        {
            termo: "05. Pregando Cristo a partir das Epístolas de Paulo",
            definicao: "As epístolas de Paulo (Romanos, Coríntios, Gálatas, Efésios, Filipenses, Colossenses, etc.) são exposições teológicas da obra de Cristo. Para pregar Cristo a partir de Paulo: (1) Mostre que a justificação é pela fé em Cristo (Romanos 3:21-26). (2) Mostre que a santificação é a conformação a Cristo (Romanos 8:29; 2 Coríntios 3:18). (3) Mostre que a união com Cristo é a base da vida cristã (Gálatas 2:20; Efésios 1:3-14). Exemplos: (a) Romanos 5:12-21 (Segundo Adão): Esboço: (i) O pecado de Adão trouxe condenação; (ii) A obediência de Cristo trouxe justificação; (iii) A graça superabunda sobre o pecado. (b) Filipenses 2:5-11 (Kenosis): Esboço: (i) A humilhação de Cristo (esvaziamento, servo, cruz); (ii) A exaltação de Cristo (Senhor, nome sobre todo nome); (iii) A imitação de Cristo (tende em vós o mesmo sentimento). (c) Colossenses 1:15-20 (Supremacia de Cristo): Esboço: (i) Cristo é o Criador (primogênito de toda criação); (ii) Cristo é o Sustentador (todas as coisas subsistem por ele); (iii) Cristo é o Redentor (reconciliou todas as coisas). A teologia reformada valoriza a pregação das epístolas paulinas como o coração do evangelho.",
            referencias: "Romanos 1:1-4; Romanos 3:21-26; Romanos 5:12-21; Romanos 8:1-4; Romanos 8:29; 1 Coríntios 15:1-8; 2 Coríntios 5:18-21; Gálatas 2:20; Gálatas 3:10-14; Efésios 1:3-14; Filipenses 2:5-11; Colossenses 1:15-20"
        },
        {
            termo: "06. Pregando Cristo a partir de Hebreus e Apocalipse",
            definicao: "A Epístola aos Hebreus e o Apocalipse têm ênfases cristológicas únicas. Para pregar Cristo a partir de Hebreus: (1) Cristo é superior aos anjos, a Moisés e aos sacerdotes (Hebreus 1-7). (2) Cristo é o Sumo Sacerdote perfeito (Hebreus 4:14-5:10; 7:1-28). (3) Cristo ofereceu o sacrifício definitivo (Hebreus 9-10). Exemplo: Hebreus 4:14-16 (Sumo Sacerdote compassivo): Esboço: (i) Temos um grande Sumo Sacerdote (Jesus); (ii) Ele foi tentado em tudo, mas sem pecado; (iii) Aproximemo-nos com confiança ao trono da graça. Para pregar Cristo a partir do Apocalipse: (1) Cristo é o Cordeiro que foi morto (Apocalipse 5:6-14). (2) Cristo é o Leão de Judá (Apocalipse 5:5). (3) Cristo é o Rei dos reis e Senhor dos senhores (Apocalipse 19:16). (4) Cristo é o Alfa e o Ômega (Apocalipse 1:8; 22:13). Exemplo: Apocalipse 5:1-14 (O Cordeiro digno): Esboço: (i) O livro selado (o plano de Deus); (ii) O Cordeiro que foi morto (Cristo); (iii) A adoração universal (digno é o Cordeiro). A teologia reformada enfatiza a pregação escatológica (esperança da segunda vinda) a partir do Apocalipse.",
            referencias: "Hebreus 1:1-4; Hebreus 4:14-16; Hebreus 7:1-28; Hebreus 9:11-28; Hebreus 10:1-18; Hebreus 12:1-4; Apocalipse 1:1-20; Apocalipse 5:1-14; Apocalipse 19:11-16; Apocalipse 21:1-27; Apocalipse 22:1-21"
        },
        {
            termo: "07. Esboços de Sermões Cristocêntricos (Antigo Testamento)",
            definicao: "Esboços prontos para sermões cristocêntricos a partir do Antigo Testamento: (1) Gênesis 22:1-18 (O Sacrifício de Isaque). Título: 'Deus Proverá o Cordeiro'. Esboço: (a) A prova de Abraão (sacrifício do filho). (b) O cordeiro provido por Deus (o carneiro). (c) O cumprimento em Cristo (o verdadeiro Cordeiro). (2) Êxodo 16:1-36 (O Maná). Título: 'O Pão do Céu'. Esboço: (a) A fome no deserto (necessidade espiritual). (b) O maná do céu (Deus provê). (c) Jesus é o verdadeiro pão da vida (João 6:35). (3) Números 21:4-9 (A Serpente de Bronze). Título: 'Olhai e Vivei'. Esboço: (a) O pecado de Israel (mordido pelas serpentes). (b) A serpente de bronze (levantada no deserto). (c) Cristo levantado na cruz (João 3:14-15). (4) 2 Samuel 7:12-16 (Aliança Davídica). Título: 'O Filho de Davi'. Esboço: (a) A promessa a Davi (um descendente reinará para sempre). (b) O cumprimento em Cristo (Lucas 1:32-33). (c) O Reino eterno de Cristo. (5) Isaías 53:1-12 (O Servo Sofredor). Título: 'Ele foi Ferido por Nós'. Esboço: (a) O servo desprezado (Cristo rejeitado). (b) O servo ferido (substituição penal). (c) O servo ressurreto (vitória).",
            referencias: "Gênesis 22:1-18; Êxodo 16:1-36; Números 21:4-9; 2 Samuel 7:12-16; Isaías 53:1-12; João 3:14-15; João 6:35; Lucas 1:32-33"
        },
        {
            termo: "08. Esboços de Sermões Cristocêntricos (Novo Testamento)",
            definicao: "Esboços prontos para sermões cristocêntricos a partir do Novo Testamento: (1) João 1:1-18 (O Prólogo). Título: 'O Verbo se Fez Carne'. Esboço: (a) O Verbo eterno (divindade de Cristo). (b) O Verbo encarnado (humanidade de Cristo). (c) O Verbo revelador (graça e verdade). (2) Romanos 3:21-26 (Justificação). Título: 'Justificados pela Fé em Cristo'. Esboço: (a) O problema: todos pecaram. (b) A solução: a propiciação em Cristo. (c) A resposta: justificação pela fé. (3) Filipenses 2:5-11 (Kenosis). Título: 'O Esvaziamento de Cristo'. Esboço: (a) A humilhação de Cristo (servo, cruz). (b) A exaltação de Cristo (Senhor, nome sobre todo nome). (c) A imitação de Cristo (tende em vós o mesmo sentimento). (4) Colossenses 1:15-20 (Supremacia). Título: 'Cristo é Tudo'. Esboço: (a) Cristo é o Criador. (b) Cristo é o Sustentador. (c) Cristo é o Redentor. (5) Hebreus 4:14-16 (Sumo Sacerdote). Título: 'Aproximemo-nos do Trono da Graça'. Esboço: (a) Temos um grande Sumo Sacerdote (Jesus). (b) Ele foi tentado como nós (compassivo). (c) Aproximemo-nos com confiança (graça). (6) Apocalipse 5:1-14 (O Cordeiro). Título: 'Digno é o Cordeiro'. Esboço: (a) O livro selado (o plano de Deus). (b) O Cordeiro que foi morto (Cristo). (c) A adoração universal (digno é o Cordeiro).",
            referencias: "João 1:1-18; Romanos 3:21-26; Filipenses 2:5-11; Colossenses 1:15-20; Hebreus 4:14-16; Apocalipse 5:1-14"
        },
        {
            termo: "09. A Pregação Expositiva Cristocêntrica (Método)",
            definicao: "A pregação expositiva é a pregação que expõe um texto bíblico em seu contexto, mostrando seu significado original e sua aplicação a Cristo. Método: (1) Ler o texto em seu contexto (histórico, literário, redacional). (2) Analisar a estrutura e os termos-chave (grego/hebraico). (3) Determinar a ideia central do texto. (4) Mostrar como o texto aponta para Cristo (profecias, tipos, cumprimento). (5) Aplicar o texto aos ouvintes (fé, arrependimento, santificação). (6) Concluir com o evangelho (Cristo crucificado e ressurreto). Exemplo prático: Lucas 24:13-35 (O Caminho de Emaús). Esboço expositivo: (1) O contexto: discípulos desanimados após a crucificação. (2) A aparição de Jesus (reconhecimento na partida do pão). (3) A explicação das Escrituras (Cristo em Moisés e nos profetas). (4) Aplicação: Cristo está presente na Palavra e na Ceia. A teologia reformada valoriza a pregação expositiva (Calvino, Lloyd-Jones, Stott).",
            referencias: "Lucas 24:13-35; Atos 8:26-40; Neemias 8:1-12; 1 Timóteo 4:13; 2 Timóteo 4:1-5"
        },
        {
            termo: "10. Evitando Erros na Pregação Cristocêntrica",
            definicao: "Erros comuns na pregação cristocêntrica: (1) Alegorização excessiva: forçar Cristo em cada detalhe do texto (ex.: a cor do tapete do tabernáculo). (2) Tipologia forçada: criar tipos que não estão no texto. (3) Moralismo: pregar lições morais sem Cristo (ex.: 'seja corajoso como Davi'). (4) Psicologização: pregar autoajuda sem Cristo. (5) Politização: pregar ativismo político sem o evangelho. (6) Legalismo: pregar obras para justificação (em vez de graça). Como evitar: (1) Baseie-se no texto (exegese sólida). (2) Mostre o cumprimento em Cristo a partir do Novo Testamento. (3) Pregue a justificação pela fé (não pelas obras). (4) Aplique o evangelho (Cristo crucificado e ressurreto). (5) Mostre a necessidade do arrependimento e da fé. A teologia reformada enfatiza a fidelidade ao texto e a centralidade de Cristo.",
            referencias: "2 Coríntios 4:2; Gálatas 1:6-9; Colossenses 2:8; 1 Timóteo 4:7; 2 Timóteo 2:15; Tito 1:14; 2 Pedro 3:16"
        },
        {
            termo: "11. A Pregação e a Ceia do Senhor (Cristo nos Sacramentos)",
            definicao: "A pregação cristocêntrica está intimamente ligada aos sacramentos (batismo e Ceia do Senhor). A Ceia do Senhor é uma 'palavra visível' que proclama a morte de Cristo até que ele venha (1 Coríntios 11:26). A pregação deve preparar os fiéis para a Ceia: (1) Explicar o significado da Ceia (memorial, comunhão, presença de Cristo). (2) Exortar ao exame próprio (1 Coríntios 11:28). (3) Proclamar o perdão dos pecados em Cristo. (4) Celebrar a unidade do corpo de Cristo (1 Coríntios 10:17). O batismo é a incorporação em Cristo (Romanos 6:3-4). A pregação deve explicar o batismo como sinal e selo da graça de Deus em Cristo. A teologia reformada (Calvino) enfatiza que os sacramentos são meios de graça que confirmam a promessa do evangelho.",
            referencias: "Romanos 6:3-4; 1 Coríntios 10:16-17; 1 Coríntios 11:23-34; Gálatas 3:27; Colossenses 2:11-12; 1 Pedro 3:21"
        },
        {
            termo: "12. A Unção do Espírito Santo para a Pregação",
            definicao: "A pregação cristocêntrica eficaz depende não apenas da habilidade humana, mas da unção do Espírito Santo. Jesus prometeu: 'Mas recebereis a virtude do Espírito Santo, que há de vir sobre vós; e ser-me-eis testemunhas' (Atos 1:8). O Espírito Santo: (1) Ilumina o pregador para entender a Escritura (João 16:13). (2) Dá poder à pregação (1 Coríntios 2:4-5). (3) Convence os ouvintes do pecado, da justiça e do juízo (João 16:8). (4) Aplica a salvação aos corações. O pregador deve buscar a unção do Espírito mediante: (a) Oração (Atos 6:4). (b) Estudo da Palavra (2 Timóteo 2:15). (c) Santidade de vida (1 Timóteo 4:12). (d) Humildade (1 Pedro 5:5-6). A teologia reformada enfatiza que a pregação é um meio de graça pelo qual o Espírito Santo opera a salvação (Romanos 10:17).",
            referencias: "Isaías 61:1-3; Joel 2:28-32; Atos 1:8; Atos 2:1-4; Romanos 10:17; 1 Coríntios 2:1-5; Efésios 6:18-20; 1 Tessalonicenses 1:5"
        },
        {
            termo: "13. Síntese: Pregar Cristo para a Glória de Deus",
            definicao: "A pregação cristocêntrica tem como alvo final a glória de Deus (Soli Deo Gloria). 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36). O pregador deve ter como objetivo: (1) Glorificar a Cristo (João 16:14). (2) Edificar a igreja (Efésios 4:11-16). (3) Converter os pecadores (Romanos 10:13-15). (4) Anunciar a segunda vinda de Cristo (Tito 2:13). Que todo pregador siga o exemplo de Paulo: 'Porque não me propus saber coisa alguma entre vós, senão a Jesus Cristo, e este crucificado' (1 Coríntios 2:2). 'E tudo quanto fizerdes, por palavra ou por obra, fazei-o em nome do Senhor Jesus, dando por ele graças a Deus Pai' (Colossenses 3:17). Que esta enciclopédia cristológica (25 volumes) sirva para a glória de Cristo e para a edificação da sua igreja. 'Aquele que testifica estas coisas diz: Certamente cedo venho. Amém. Ora vem, Senhor Jesus. A graça de nosso Senhor Jesus Cristo seja com todos vós. Amém' (Apocalipse 22:20-21).",
            referencias: "Romanos 11:36; 1 Coríntios 2:2; 1 Coríntios 10:31; Efésios 3:20-21; Colossenses 3:17; 2 Timóteo 4:1-5; Tito 2:13; Hebreus 13:20-21; Apocalipse 22:20-21"
        }
    ]
};