// volume/volume-97.js
window.LIVRO_DATA = {
    nome: "Volume XCVII",
    dados: [
        {
            termo: "01. Introdução: Cristo, a Nossa Esperança",
            definicao: "A teologia da esperança estuda a consumação final do plano redentor de Deus em Cristo. Cristo é a nossa esperança certa. 'Esperança viva pela ressurreição de Jesus Cristo dentre os mortos' (1 Pedro 1:3). Diferente da esperança secular (incerta e ilusória), a esperança cristã é uma certeza baseada nas promessas de Deus e na obra consumada de Cristo. Características da esperança cristã: (1) É certa: baseada na fidelidade de Deus (Hebreus 10:23). (2) É cristocêntrica: Cristo é o conteúdo e a garantia (Colossenses 1:27). (3) É escatológica: aponta para o fim da história (Tito 2:13). (4) É pessoal: envolve a ressurreição do corpo (Filipenses 3:20-21). (5) É cósmica: inclui a restauração de toda a criação (Romanos 8:19-22). (6) É ética: produz santificação (1 João 3:3). (7) É consoladora: alivia o sofrimento (1 Tessalonicenses 4:18). (8) É missionária: motiva o evangelismo (2 Pedro 3:11-12). (9) É doxológica: glorifica a Deus (Romanos 15:13). (10) É triunfante: certa da vitória final (1 Coríntios 15:57). A teologia reformada (Calvino, Vos, Ridderbos, Hoekema, Berkouwer) enfatiza a esperança como virtude teologal, juntamente com a fé e o amor. 'A esperança não confunde' (Romanos 5:5).",
            referencias: "Jó 19:25-27; Salmo 42:5; Salmo 71:5; Romanos 5:2-5; Romanos 8:24-25; Romanos 15:13; 1 Coríntios 15:19; 2 Coríntios 4:16-18; Efésios 1:18; Colossenses 1:27; Tito 1:2; Tito 2:13; Hebreus 6:18-20; 1 Pedro 1:3-4; 1 Pedro 1:13; 1 João 3:2-3"
        },
        {
            termo: "02. A Escatologia do Antigo Testamento - A Esperança de Israel",
            definicao: "O Antigo Testamento está repleto de esperança escatológica, centrada nas promessas de Deus a Abraão, Davi e aos profetas. 'Eu sei que o meu Redentor vive' (Jó 19:25). Elementos da esperança no AT: (1) O Dia do Senhor (Yom YHWH): dia de juízo e salvação (Joel 2:1-11; Amós 5:18-20). (2) O Messias: rei descendente de Davi que trará justiça e paz (Isaías 9:6-7; 11:1-9). (3) O Servo Sofredor: aquele que padece pelos pecados do povo (Isaías 52:13-53:12). (4) O novo pacto: perdão e coração renovado (Jeremias 31:31-34; Ezequiel 36:26-27). (5) A restauração de Israel: retorno do exílio e restauração da nação (Ezequiel 37; Amós 9:11-15). (6) A ressurreição dos mortos: esperança de vida além da morte (Daniel 12:2; Isaías 26:19). (7) O novo céu e nova terra: a criação renovada (Isaías 65:17; 66:22). (8) O reinado universal de Deus: todos os povos adorarão ao Senhor (Salmo 2; Isaías 2:2-4; Miqueias 4:1-4). (9) O banquete messiânico: festa de alegria e abundância (Isaías 25:6-8). (10) A cidade de Deus: Jerusalém celestial (Isaías 60; Ezequiel 40-48). A teologia reformada (Vos, Robertson, Waltke) enfatiza que a escatologia do AT é protológica e tipológica, apontando para o cumprimento em Cristo. 'Todas as promessas de Deus são nele sim e amém' (2 Coríntios 1:20).",
            referencias: "Gênesis 3:15; Gênesis 12:1-3; 2 Samuel 7:12-16; Salmo 2; Salmo 16; Salmo 110; Isaías 2:2-4; Isaías 9:6-7; Isaías 11:1-9; Isaías 24-27; Isaías 25:6-8; Isaías 26:19; Isaías 53; Isaías 65:17-25; Jeremias 31:31-34; Ezequiel 36:26-27; Ezequiel 37; Daniel 7:13-14; Daniel 12:2; Joel 2:28-32; Amós 9:11-15; Miqueias 4:1-4; Zacarias 12-14"
        },
        {
            termo: "03. O Reino de Deus - Já e Ainda Não",
            definicao: "O reino de Deus é inaugurado por Cristo em seu primeiro advento, mas aguarda consumação em seu segundo advento. 'O reino de Deus está próximo; arrependei-vos e crede no evangelho' (Marcos 1:15). A tensão escatológica: já (inaugurado) e ainda não (consumado). Dimensões do reino: (1) Já: Cristo venceu o pecado, Satanás e a morte em sua morte e ressurreição (Colossenses 2:15). (2) Ainda não: os efeitos finais da vitória ainda não são plenamente manifestos (1 Coríntios 15:24-26). (3) Já: os crentes são trasladados do reino das trevas para o reino do Filho (Colossenses 1:13). (4) Ainda não: os crentes ainda sofrem, pecam e morrem (Romanos 8:23). (5) Já: o Espírito Santo é dado como arras (garantia) da herança (Efésios 1:13-14). (6) Ainda não: a herança plena ainda está por vir (1 Pedro 1:4-5). (7) Já: o julgamento do mundo foi decidido na cruz (João 12:31). (8) Ainda não: o julgamento final ainda será executado (Apocalipse 20:11-15). (9) Já: a nova criação começou em Cristo (2 Coríntios 5:17). (10) Ainda não: a criação inteira aguarda a redenção (Romanos 8:19-22). A teologia reformada (Ridderbos, Ladd, Hoekema, Vos) enfatiza que o reino é uma realidade presente em Cristo e futura na consumação. 'Ainda não vemos todas as coisas sujeitas a ele; vemos, porém, Jesus' (Hebreus 2:8-9).",
            referencias: "Mateus 4:17; Mateus 10:7; Mateus 12:28; Mateus 13; Mateus 24-25; Marcos 1:15; Lucas 4:16-21; Lucas 10:9; Lucas 11:20; Lucas 17:20-21; João 5:24; João 12:31; Romanos 8:18-25; 1 Coríntios 10:11; 1 Coríntios 15:20-28; Gálatas 1:4; Efésios 1:13-14; Colossenses 1:13; Colossenses 2:15; Colossenses 3:1-4; Hebreus 2:8-9; 1 Pedro 1:3-5; 1 João 3:2"
        },
        {
            termo: "04. A Parusia (Segunda Vinda) de Cristo - O Evento Central da Consumação",
            definicao: "A segunda vinda de Cristo (parusia) é o evento central da consumação, quando Cristo retorna visível, gloriosa e pessoalmente. 'Este Jesus, que dentre vós foi recebido acima no céu, há de vir assim como para o céu o vistes ir' (Atos 1:11). Características da parusia: (1) Visível: 'todo olho o verá' (Apocalipse 1:7). (2) Gloriosa: com poder e grande glória (Mateus 24:30). (3) Pessoal: o mesmo Jesus que subiu (Atos 1:11). (4) Repentina: como ladrão de noite (1 Tessalonicenses 5:2). (5) Audível: com voz de arcanjo e trombeta (1 Tessalonicenses 4:16). (6) Triunfante: com seus anjos (Mateus 25:31). (7) Inesperada: ninguém sabe o dia nem a hora (Mateus 24:36). (8) Consumadora: trará o fim da história (1 Coríntios 15:24). (9) Julgadora: separará justos e ímpios (Mateus 25:31-46). (10) Redentora: completará a salvação (Filipenses 3:20-21). Negando as heresias: (a) Não é apenas espiritual (refutação do pretérito). (b) Não é um evento gradual (refutação do pós-milenismo puro). (c) Não é meramente simbólico. (d) Não é um segundo evangelho (refutação de novas revelações). A teologia reformada (Calvino, Bavinck, Berkhof, Erickson) ensina a parusia como um evento literal, futuro, visível e glorioso. 'O Senhor mesmo descerá do céu' (1 Tessalonicenses 4:16).",
            referencias: "Mateus 24:30-31; Mateus 24:36; Mateus 25:31-46; Marcos 13:26-27; Lucas 21:27; João 14:3; Atos 1:11; Atos 3:20-21; Romanos 13:11; 1 Coríntios 1:7; 1 Coríntios 4:5; 1 Coríntios 15:23; Filipenses 3:20-21; Colossenses 3:4; 1 Tessalonicenses 1:10; 1 Tessalonicenses 2:19; 1 Tessalonicenses 3:13; 1 Tessalonicenses 4:15-17; 1 Tessalonicenses 5:2; 2 Tessalonicenses 1:7-10; 2 Tessalonicenses 2:1-8; 1 Timóteo 6:14; 2 Timóteo 4:1; 2 Timóteo 4:8; Tito 2:13; Hebreus 9:28; Tiago 5:7-8; 2 Pedro 1:16; 2 Pedro 3:3-13; 1 João 2:28; 1 João 3:2; Apocalipse 1:7; Apocalipse 22:12; Apocalipse 22:20"
        },
        {
            termo: "05. A Ressurreição dos Mortos - A Vitória sobre a Morte",
            definicao: "A ressurreição dos mortos é a esperança central do cristianismo, garantida pela ressurreição de Cristo. 'Cristo ressuscitou dos mortos, e foi feito as primícias dos que dormem' (1 Coríntios 15:20). Tipos de ressurreição: (1) Ressurreição de Cristo: primícias e garantia (1 Coríntios 15:20-23). (2) Ressurreição dos justos: para a vida eterna (João 5:29). (3) Ressurreição dos injustos: para o juízo e condenação (João 5:29; Atos 24:15). Características do corpo ressurreto dos justos: (a) Incorruptível (não mais sujeito à decadência). (b) Glorioso (cheio de glória). (c) Poderoso (cheio de poder). (d) Espiritual (governado pelo Espírito). (e) Imortal (não mais sujeito à morte) (1 Coríntios 15:42-49). (f) Semelhante ao corpo glorificado de Cristo (Filipenses 3:20-21). Negando heresias: (a) Não é apenas espiritual (refutação do gnosticismo). (b) Não é reencarnação (refutação do hinduísmo). (c) Não é aniquilação. (d) Não é sonho ou ilusão. (e) Não é apenas metafórica. A teologia reformada (Calvino, Bavinck, Berkhof, Hoekema) enfatiza a ressurreição corporal como essencial para a fé cristã. 'Se não há ressurreição de mortos, também Cristo não ressuscitou' (1 Coríntios 15:13).",
            referencias: "Jó 19:25-27; Salmo 16:9-10; Isaías 26:19; Ezequiel 37:1-14; Daniel 12:2; Mateus 22:23-33; Marcos 12:18-27; Lucas 20:27-38; João 5:28-29; João 6:39-40; João 11:23-26; Atos 23:6; Atos 24:15; Romanos 6:5; Romanos 8:11; 1 Coríntios 6:14; 1 Coríntios 15:1-58; 2 Coríntios 4:14; 2 Coríntios 5:1-5; Filipenses 3:20-21; 1 Tessalonicenses 4:13-18; Apocalipse 20:4-6; Apocalipse 20:12-13"
        },
        {
            termo: "06. O Juízo Final - O Trono Branco e a Separação Final",
            definicao: "O juízo final é o evento no qual Deus, por meio de Cristo, julgará toda a humanidade com justiça. 'Porque é necessário que todos nós compareçamos perante o tribunal de Cristo' (2 Coríntios 5:10). Aspectos do juízo final: (1) O Juiz: Jesus Cristo (João 5:22; Atos 17:31). (2) Os julgados: todos os seres humanos (justos e injustos) (Romanos 14:10; 2 Coríntios 5:10). (3) O critério: obras (Mateus 25:31-46; Apocalipse 20:12-13). (4) A base da salvação: fé em Cristo (João 3:18). (5) O destino dos justos: vida eterna (Mateus 25:46). (6) O destino dos ímpios: castigo eterno (Mateus 25:46). (7) O momento: após a ressurreição geral (Apocalipse 20:11-15). (8) O propósito: glória de Deus e manifestação de sua justiça. (9) A certeza: determinado por Deus (Atos 17:31). (10) O consolo para os crentes: justiça vindicada (2 Tessalonicenses 1:5-10). Negando heresias: (a) Não é aniquilação (refutação do aniquilacionismo). (b) Não é universalismo (todos salvos) (refutação do universalismo). (c) Não é purgatório (refutação do catolicismo romano). (d) Não é segundo chance após a morte (Hebreus 9:27). (e) Não é julgamento apenas das obras, mas da pessoa. A teologia reformada (Calvino, Turretin, Hodge, Berkhof) afirma o juízo final como real, justo, eterno e de acordo com as obras como evidência da fé. 'E estes irão para o tormento eterno, mas os justos para a vida eterna' (Mateus 25:46).",
            referencias: "Eclesiastes 12:14; Mateus 10:15; Mateus 11:22; Mateus 12:36-37; Mateus 25:31-46; Lucas 10:14; João 5:22-29; Atos 10:42; Atos 17:31; Romanos 2:5-16; Romanos 14:10-12; 1 Coríntios 3:10-15; 1 Coríntios 4:5; 2 Coríntios 5:10; 2 Tessalonicenses 1:5-10; 2 Timóteo 4:1; 2 Timóteo 4:8; Hebreus 6:2; Hebreus 9:27; Tiago 2:12-13; 2 Pedro 2:9; Judas 1:6; Judas 1:14-15; Apocalipse 20:11-15; Apocalipse 22:12"
        },
        {
            termo: "07. O Céu e a Nova Terra - A Habitação de Deus com os Homens",
            definicao: "O estado final dos redimidos não é o céu como um lugar etéreo e imaterial, mas o novo céu e a nova terra, onde Deus habita com seu povo. 'E vi um novo céu e uma nova terra' (Apocalipse 21:1). 'Eis aqui o tabernáculo de Deus com os homens' (Apocalipse 21:3). Características do estado final: (1) Novo céu e nova terra: a criação renovada, não aniquilada (2 Pedro 3:13). (2) A Nova Jerusalém: a cidade de Deus descendo do céu (Apocalipse 21:2). (3) Habitação de Deus com os homens: intimidade perfeita (Apocalipse 21:3). (4) Ausência de sofrimento: 'não haverá mais morte, nem pranto, nem clamor, nem dor' (Apocalipse 21:4). (5) Ausência de pecado: nada imundo entrará (Apocalipse 21:27). (6) Presença da glória de Deus: o Senhor Deus é o sol (Apocalipse 21:23). (7) Árvore da vida: cura e vida eterna (Apocalipse 22:2). (8) Rio da vida: águas vivas procedentes do trono (Apocalipse 22:1). (9) Serviço a Deus: serviremos ao Senhor (Apocalipse 22:3). (10) Visão beatífica: veremos a Deus face a face (Apocalipse 22:4). Negando heresias: (a) Não é mera vida espiritual sem corpo (refutação do platonismo). (b) Não é uma terra meramente reformada pelo homem. (c) Não é um reino milenar terrestre apenas (refutação do pré-milenismo dispensacionalista). (d) Não é um lugar de tédio ou inatividade. (e) Não é acesso universal (apenas os remidos entram). A teologia reformada (Calvino, Bavinck, Hoekema, Berkhof) enfatiza que o estado final é a restauração de toda a criação, não sua destruição. 'Criamos novos céus e nova terra; e as coisas passadas não serão lembradas' (Isaías 65:17).",
            referencias: "Isaías 60; Isaías 65:17-25; Isaías 66:22-23; Ezequiel 40-48; Mateus 5:3-12; Mateus 13:43; Lucas 12:32; Lucas 22:28-30; João 14:1-3; Romanos 8:18-25; 1 Coríntios 13:12; 2 Coríntios 5:1-8; 2 Pedro 3:13; Hebreus 11:10; Hebreus 11:16; Hebreus 12:22-24; Apocalipse 7:9-17; Apocalipse 21:1-22:5"
        },
        {
            termo: "08. O Inferno - A Realidade do Castigo Eterno",
            definicao: "O inferno é o lugar de castigo eterno para os ímpios, Satanás e seus demônios. 'E estes irão para o tormento eterno' (Mateus 25:46). Características bíblicas do inferno: (1) Eterno: fogo eterno preparado para o diabo e seus anjos (Mateus 25:41). (2) Consciência: os ímpios têm consciência de seu sofrimento (Lucas 16:23-24). (3) Escuridão: trevas exteriores (Mateus 8:12; 22:13). (4) Fogo: lago de fogo e enxofre (Apocalipse 20:10; 21:8). (5) Separação: separação eterna da presença de Deus (2 Tessalonicenses 1:9). (6) Choro e ranger de dentes: sofrimento intenso (Mateus 13:42). (7) Vergonha e desprezo: os ímpios serão desprezados (Daniel 12:2). (8) Verme que não morre: corrupção eterna (Marcos 9:48; Isaías 66:24). (9) Ira de Deus: a justa ira divina (Romanos 2:5-8). (10) Segunda morte: morte eterna (Apocalipse 20:14-15). Negando heresias: (a) Não é aniquilação (o castigo é eterno, não cessação da existência). (b) Não é purgatório (não há saída). (c) Não é universalismo (nem todos serão salvos). (d) Não é apenas metáfora sem realidade. (e) Não é injusto (é justo juízo de Deus). A teologia reformada (Calvino, Turretin, Shedd, Sproul) afirma a realidade do inferno como castigo eterno, consciente e justo, baseado na santidade de Deus e na gravidade do pecado. 'Horrível coisa é cair nas mãos do Deus vivo' (Hebreus 10:31).",
            referencias: "Daniel 12:2; Isaías 33:14; Isaías 66:24; Mateus 3:12; Mateus 5:22; Mateus 5:29-30; Mateus 8:12; Mateus 10:28; Mateus 13:41-42; Mateus 13:49-50; Mateus 18:8-9; Mateus 22:13; Mateus 23:33; Mateus 25:41; Mateus 25:46; Marcos 9:43-48; Lucas 12:5; Lucas 16:19-31; Romanos 2:5-9; 2 Tessalonicenses 1:8-9; 2 Pedro 2:4; Judas 1:6-7; Judas 1:13; Apocalipse 14:9-11; Apocalipse 19:20; Apocalipse 20:10; Apocalipse 20:14-15; Apocalipse 21:8; Apocalipse 22:15"
        },
        {
            termo: "09. As Visões Escatológicas - Pré-milenismo, Pós-milenismo, Amilenismo",
            definicao: "A teologia reformada apresenta diferentes visões sobre o milênio (Apocalipse 20:1-6). Principais posições: (1) Pré-milenismo histórico: Cristo retorna antes do milênio, que é um reinado literal de mil anos na terra. (2) Pré-milenismo dispensacionalista: distingue Israel e igreja, com um reino judaico terreno. (3) Pós-milenismo: Cristo retorna depois do milênio, que é uma era de vitória do evangelho antes da parusia. (4) Amilenismo: o milênio é simbólico, referindo-se à era presente da igreja entre a primeira e segunda vinda de Cristo. Posição reformada majoritária: amilenismo (Calvino, Bavinck, Berkhof, Hoekema, Vos, Ridderbos). Argumentos amilenistas: (a) Apocalipse 20 é altamente simbólico, não literal. (b) O milênio começa com a primeira vinda de Cristo e a amarração de Satanás (Mateus 12:29; Colossenses 2:15). (c) A primeira ressurreição é espiritual (regeneração), não física (João 5:24-25; Efésios 2:1,5-6; Colossenses 3:1). (d) Satanás já está amarrado para não enganar as nações (o que não significa inatividade total) (Apocalipse 20:3). (e) Os crentes já reinam com Cristo (Apocalipse 1:6; 5:10; 20:4-6). (f) A segunda vinda é um único evento, seguida pela ressurreição geral e juízo final. A teologia reformada (Calvino, Bavinck, Berkhof, Hoekema) adota o amilenismo, mas respeita o pós-milenismo e pré-milenismo histórico como posições possíveis dentro do evangelicalismo. 'O reino de Deus não vem com aparência exterior' (Lucas 17:20).",
            referencias: "Daniel 2:44; Daniel 7:13-14; Mateus 12:28-29; Mateus 28:18; Lucas 17:20-21; João 5:24-25; Atos 2:29-36; Romanos 6:4-5; 1 Coríntios 15:22-28; Efésios 1:20-23; Efésios 2:1-6; Colossenses 2:12-15; Colossenses 3:1; 2 Tessalonicenses 2:1-12; 2 Timóteo 2:18; Apocalipse 1:5-6; Apocalipse 1:18; Apocalipse 2:10-11; Apocalipse 5:9-10; Apocalipse 12:9-12; Apocalipse 20:1-6"
        },
        {
            termo: "10. A Esperança e a Vida Presente - Santificação e Missão",
            definicao: "A esperança escatológica não leva à fuga do mundo, mas ao engajamento missional e à santificação. 'Todo aquele que tem nele esta esperança purifica-se a si mesmo' (1 João 3:3). Implicações éticas da esperança: (1) Santificação: viver de maneira santa e piedosa (2 Pedro 3:11-12). (2) Missão: evangelizar as nações antes da parusia (Mateus 28:19-20; Atos 1:8). (3) Trabalho: o trabalho não é vão no Senhor (1 Coríntios 15:58). (4) Sofrimento: a esperança sustenta no sofrimento (Romanos 8:18-25). (5) Perseverança: permanecer firmes até o fim (Hebreus 10:36-39). (6) Amor fraternal: encorajar uns aos outros (1 Tessalonicenses 4:18; 5:11). (7) Vigilância: estar alerta para a vinda de Cristo (Mateus 24:42-44). (8) Desapego dos bens: não confiar nas riquezas terrenas (1 Timóteo 6:17-19). (9) Engajamento cultural: transformar a criação como ato de obediência (Gênesis 1:28; Mateus 5:13-16). (10) Oração: 'Maranata, vem, Senhor Jesus' (Apocalipse 22:20). A teologia reformada (Kuyper, Bavinck, Schaeffer, Wolters) enfatiza a esperança como motor da transformação cultural e missional. 'Se, porém, esperamos o que não vemos, com paciência o aguardamos' (Romanos 8:25).",
            referencias: "Mateus 5:13-16; Mateus 24:42-44; Mateus 25:14-30; Atos 1:8; Romanos 8:18-25; Romanos 13:11-14; 1 Coríntios 7:29-31; 1 Coríntios 15:58; 2 Coríntios 4:16-18; Filipenses 3:20-21; Colossenses 3:1-4; 1 Tessalonicenses 4:18; 1 Tessalonicenses 5:1-11; Tito 2:11-14; Hebreus 10:24-25; Hebreus 10:36-39; 1 Pedro 1:13-16; 2 Pedro 3:11-14; 1 João 3:2-3; Apocalipse 22:20"
        },
        {
            termo: "11. As Seitas e Falsas Escatologias - Testando os Espíritos",
            definicao: "Muitas seitas e falsos ensinos distorcem a esperança cristã. A teologia reformada deve discernir e refutar essas heresias. Principais falsas escatologias: (1) Ateísmo: negação da vida após a morte (Salmo 14:1). (2) Materialismo: esperança apenas nesta vida (1 Coríntios 15:19). (3) Hinduísmo: reencarnação e karma (Hebreus 9:27). (4) Espiritismo: contato com os mortos (Levítico 20:27; Deuteronômio 18:10-12). (5) Testemunhas de Jeová: negação da Trindade, da ressurreição física e do inferno (João 1:1; 1 Coríntios 15). (6) Mórmonismo: doutrinas de exaltação e pluralidade de deuses (Isaías 43:10-11). (7) Adventismo do Sétimo Dia: juízo investigativo (refutado por Hebreus 10:11-14). (8) Universalismo: todos salvos (refutado por Mateus 25:46). (9) Aniquilacionismo: ímpios deixam de existir (refutado por Apocalipse 20:10). (10) Pré-milenismo dispensacionalista: datação da volta de Cristo (Mateus 24:36). (11) Apocalípticos modernos: previsões falsas da volta de Cristo (Deuteronômio 18:22). (12) Teologia da Prosperidade: confusão entre bênçãos presentes e futuras (Mateus 6:19-21). A teologia reformada (Calvino, Turretin, Sproul, MacArthur) chama a igreja a discernir e rejeitar falsas escatologias, mantendo-se fiel à Escritura. 'Amados, não creiais em todo espírito, mas provai se os espíritos são de Deus' (1 João 4:1).",
            referencias: "Deuteronômio 18:10-12; Salmo 14:1; Isaías 43:10-11; Mateus 24:36; Lucas 16:19-31; João 1:1; João 14:6; Atos 4:12; Romanos 1:20-25; 1 Coríntios 15:12-19; 2 Coríntios 11:13-15; Gálatas 1:6-9; Efésios 4:14; Colossenses 2:8-10; 1 Tessalonicenses 5:21; 1 Timóteo 4:1-3; 2 Timóteo 4:3-4; Tito 1:10-11; 2 Pedro 2:1-3; 1 João 4:1; Judas 1:3-4; Apocalipse 20:10; Apocalipse 22:18-19"
        },
        {
            termo: "12. Síntese: Cristo é a Nossa Esperança - Vivendo entre o Já e o Ainda Não",
            definicao: "A teologia da esperança reformada é cristocêntrica, bíblica e transformadora. Resumo final: (1) Cristo é a garantia da nossa esperança, pois ressuscitou dos mortos (1 Coríntios 15:20). (2) O reino de Deus já foi inaugurado, mas ainda não foi consumado. (3) A parusia (segunda vinda) de Cristo é certa, visível e gloriosa. (4) Haverá ressurreição dos justos e dos injustos. (5) O juízo final separará os salvos dos perdidos. (6) O estado final é novo céu e nova terra, com Deus habitando conosco. (7) O inferno é a realidade do castigo eterno para os ímpios. (8) A visão escatológica reformada majoritária é o amilenismo (milênio como era presente da igreja). (9) A esperança produz santificação, missão, perseverança e alegria. (10) Devemos discernir e rejeitar falsas escatologias. (11) A igreja vive na tensão entre o já e o ainda não, com paciência e urgência. (12) A oração da igreja é: 'Maranata! Ora, vem, Senhor Jesus!' (Apocalipse 22:20). (13) Toda a história caminha para a glória de Deus em Cristo (Romanos 11:36). A teologia reformada (Calvino, Vos, Ridderbos, Hoekema, Berkouwer, Van Til) chama a igreja a viver com esperança certa, fé ativa e amor operante, aguardando a bem-aventurada esperança (Tito 2:13). 'Porque a nossa leve e momentânea tribulação produz para nós eterno peso de glória' (2 Coríntios 4:17). Soli Deo Gloria! Maranata!",
            referencias: "Isaías 40:31; Lamentações 3:24; Romanos 5:1-5; Romanos 8:18-39; Romanos 15:13; 1 Coríntios 13:13; 1 Coríntios 15:20-58; 2 Coríntios 4:16-18; 2 Coríntios 5:1-10; Gálatas 5:5; Efésios 1:18; Colossenses 1:5; Colossenses 1:27; 1 Tessalonicenses 1:3; 1 Tessalonicenses 5:8; Tito 1:2; Tito 2:13; Tito 3:7; Hebreus 6:11; Hebreus 6:18-20; 1 Pedro 1:3; 1 Pedro 1:13; 1 Pedro 3:15; 1 João 3:2-3; Apocalipse 22:20"
        }
    ]
};