// volume/volume-95.js
window.LIVRO_DATA = {
    nome: "Volume XCV",
    dados: [
        {
            termo: "01. Introdução: Cristo, a Palavra Viva e a Linguagem Humana",
            definicao: "A teologia da linguagem estuda como podemos falar sobre Deus (teologia) e como Deus se revelou em palavras. Cristo é a Palavra (Logos) de Deus, a revelação suprema. 'No princípio era o Verbo, e o Verbo estava com Deus, e o Verbo era Deus' (João 1:1). 'E o Verbo se fez carne, e habitou entre nós' (João 1:14). A teologia reformada (Calvino, Bavinck) enfatiza que a linguagem sobre Deus é possível porque Deus se revelou em palavras humanas (a Bíblia). Este volume explora: (1) A linguagem sobre Deus. (2) A analogia e a metáfora na teologia. (3) A linguagem bíblica. (4) A pregação e o testemunho. (5) O desafio do secularismo. (6) A comunicação do evangelho hoje. 'Toda a Escritura é inspirada por Deus e útil para o ensino' (2 Timóteo 3:16).",
            referencias: "João 1:1-14; Romanos 10:13-17; 1 Coríndios 2:6-16; 2 Coríndios 4:1-6; Efésios 4:29; Colossenses 3:16-17; 2 Timóteo 3:16-17; Hebreus 1:1-2"
        },
        {
            termo: "02. A Revelação de Deus em Palavras - A Bíblia como Palavra de Deus",
            definicao: "Deus se revelou em palavras na Bíblia. 'Toda a Escritura é inspirada por Deus e útil para o ensino, para a repreensão, para a correção, para a instrução na justiça' (2 Timóteo 3:16). 'Porque a profecia nunca foi produzida por vontade de homem algum, mas os homens santos de Deus falaram inspirados pelo Espírito Santo' (2 Pedro 1:21). A Bíblia é a Palavra de Deus em palavras humanas. Características: (1) Inspirada (Theopneustos): soprada por Deus. (2) Inerrante: sem erro nos originais. (3) Autoritativa: regra de fé e prática. (4) Clara: suficiente para a salvação. (5) Suficiente: completa para a fé e vida. (6) Progressiva: revelada em etapas. (7) Centrada em Cristo: Cristo é o centro (Lucas 24:27,44-45). (8) Viva e eficaz: poderosa para transformar (Hebreus 4:12). (9) Persuasiva: convence do pecado, da justiça e do juízo. (10) Eterna: permanece para sempre (1 Pedro 1:25). A teologia reformada (Calvino, Westminster) afirma que a Bíblia é a Palavra de Deus escrita, a única regra de fé e prática (Sola Scriptura). 'Examinais as Escrituras, porque vós cuidais ter nelas a vida eterna, e são elas que de mim testificam' (João 5:39).",
            referencias: "Salmo 19:7-11; Salmo 119:105; Isaías 55:10-11; Jeremias 23:29; Mateus 5:18; Lucas 16:17; João 10:35; Atos 17:11; Romanos 15:4; 1 Coríndios 2:13; Efésios 6:17; 1 Tessalonicenses 2:13; 2 Timóteo 3:16-17; Hebreus 4:12; 2 Pedro 1:19-21"
        },
        {
            termo: "03. A Linguagem sobre Deus - Possibilidade e Limites",
            definicao: "A linguagem sobre Deus é possível porque Deus se revelou. No entanto, a linguagem humana é limitada para descrever o Deus infinito. 'Ó profundidade das riquezas, tanto da sabedoria como da ciência de Deus! Quão insondáveis são os seus juízos, e quão inescrutáveis os seus caminhos!' (Romanos 11:33). Limites da linguagem: (1) Deus é transcendente (Isaías 55:8-9). (2) Deus é santo (Isaías 6:3). (3) Deus é incompreensível (Jó 11:7-9). (4) A linguagem humana é finita. (5) O pecado afeta a linguagem. (6) A analogia é necessária (falamos de Deus por analogia com a criação). (7) A metáfora é necessária (Deus como Pai, Rei, Pastor). (8) A linguagem apofática (negação) é útil (Deus não é limitado). (9) A linguagem catafática (afirmação) é possível (Deus é amor, justiça). (10) A linguagem revelada (Bíblia) é suficiente. A teologia reformada (Calvino, Barth) afirma que podemos falar verdadeiramente sobre Deus porque Ele se revelou em palavras humanas, mas nunca exaustivamente. 'As coisas encobertas são do Senhor nosso Deus, porém as reveladas são para nós e para nossos filhos para sempre' (Deuteronômio 29:29).",
            referencias: "Deuteronômio 29:29; Jó 11:7-9; Salmo 139:6; Isaías 55:8-9; Romanos 11:33-36; 1 Coríndios 13:12; 1 Timóteo 6:16; 1 João 3:2"
        },
        {
            termo: "04. Analogia e Metáfora na Teologia",
            definicao: "A teologia usa analogia (semelhança) e metáfora (imagem) para falar sobre Deus. Exemplos bíblicos: (1) Deus como Pai (Mateus 6:9). (2) Deus como Rei (Salmo 95:3). (3) Deus como Pastor (Salmo 23:1). (4) Deus como Rocha (Salmo 18:2). (5) Deus como Juiz (Salmo 7:11). (6) Deus como Salvador (Isaías 43:11). (7) Deus como Amigo (Tiago 2:23). (8) Deus como Leão (Oséias 11:10). (9) Deus como Águia (Deuteronômio 32:11). (10) Deus como Fogo (Hebreus 12:29). Analogia da fé (analogia fidei): a Escritura interpreta a si mesma. Analogia do ser (analogia entis): a criação reflete o Criador (Romanos 1:20). A teologia reformada (Calvino, Barth) aceita a analogia da fé, mas rejeita a analogia do ser (católica). 'Porque as suas coisas invisíveis, desde a criação do mundo, tanto o seu eterno poder como a sua divindade, se entendem e claramente se veem pelas coisas que estão criadas' (Romanos 1:20).",
            referencias: "Salmo 23:1; Salmo 95:3; Isaías 43:11; Mateus 6:9; Romanos 1:20; 1 Coríndios 10:11; 1 Coríndios 13:12; 2 Coríndios 3:18; Efésios 5:1; Hebreus 12:29"
        },
        {
            termo: "05. A Linguagem dos Evangelhos - Testemunho e Interpretação",
            definicao: "Os evangelhos são testemunho (martyria) da vida, morte e ressurreição de Jesus. 'Estes, porém, foram escritos para que creiais que Jesus é o Cristo, o Filho de Deus, e para que, crendo, tenhais vida em seu nome' (João 20:31). Características da linguagem dos evangelhos: (1) Testemunho ocular (Lucas 1:1-4). (2) Seletivo (João 20:30). (3) Interpretativo (João 1:14). (4) Teológico (Cristo é o centro). (5) Histórico (eventos reais). (6) Kerygmático (proclamação). (7) Doxológico (louvor). (8) Ético (imitação). (9) Pastoral (consolação). (10) Escatológico (esperança). A linguagem dos evangelhos não é mera reportagem neutra, mas testemunho apaixonado da fé. A teologia reformada (Calvino, Bavinck) afirma que os evangelhos são confiáveis historicamente e teologicamente. 'E, começando por Moisés e por todos os profetas, explicava-lhes o que dele se achava em todas as Escrituras' (Lucas 24:27).",
            referencias: "Lucas 1:1-4; João 1:14; João 20:30-31; Atos 1:1-3; 1 Coríndios 15:3-8; 2 Pedro 1:16-18; 1 João 1:1-4"
        },
        {
            termo: "06. A Pregação como Evento de Linguagem",
            definicao: "A pregação é o evento no qual a Palavra de Deus é proclamada em palavras humanas. 'Como, pois, invocarão aquele em quem não creram? e como crerão naquele de quem não ouviram? e como ouvirão, se não há quem pregue?' (Romanos 10:14). 'Pregai a palavra, instes a tempo e fora de tempo, redarguas, repreendas, exortes, com toda a longanimidade e doutrina' (2 Timóteo 4:2). Características da pregação: (1) Kerygma (proclamação). (2) Didachē (ensino). (3) Paraklēsis (exortação). (4) Homilia (explicação). (5) Martyria (testemunho). (6) Doxologia (louvor). (7) Profecia (aplicação). A pregação é um evento de linguagem no qual Deus fala através do pregador. A teologia reformada (Calvino, Lloyd-Jones) enfatiza que a pregação é o meio principal de graça. 'A fé é pelo ouvir, e o ouvir pela palavra de Deus' (Romanos 10:17).",
            referencias: "Neemias 8:1-8; Isaías 61:1-3; Mateus 5-7; Atos 2:14-41; Romanos 10:14-17; 1 Coríndios 1:18-25; 1 Coríndios 2:1-5; 2 Coríndios 5:18-20; Efésios 4:11-16; 2 Timóteo 4:2; Tito 1:3; Tiago 1:22-25"
        },
        {
            termo: "07. O Testemunho Pessoal - Contando a Nossa História com Cristo",
            definicao: "O testemunho pessoal é a narrativa da conversão e da vida com Cristo. 'Vinde, ouvi, todos os que temeis a Deus, e eu contarei o que ele tem feito à minha alma' (Salmo 66:16). 'Mas, em vossos corações, santificai a Cristo como Senhor; e estai sempre preparados para responder com mansidão e temor a qualquer que vos pedir a razão da esperança que há em vós' (1 Pedro 3:15). Estrutura do testemunho: (1) Antes (vida sem Cristo). (2) O encontro com Cristo (conversão). (3) Depois (mudança na vida). (4) Esperança (futuro). Características: (a) Honesto (não exagerar). (b) Humilde (glória a Deus, não a si). (c) Claro (foco em Cristo). (d) Relevante (para o ouvinte). (e) Amoroso. (f) Ousado. (g) Persuasivo. (h) Breve. (i) Verdadeiro. (j) Glorifica a Deus. A teologia reformada (Calvino, Bonhoeffer) incentiva o testemunho pessoal como forma de evangelismo. 'Vinde, e ouvi, todos os que temeis a Deus, e eu contarei o que ele tem feito à minha alma' (Salmo 66:16).",
            referencias: "Salmo 66:16; Isaías 43:10; Mateus 5:13-16; João 4:28-30; João 4:39-42; Atos 22:1-21; Atos 26:1-23; Romanos 10:9-10; 1 Pedro 3:15; Apocalipse 12:11"
        },
        {
            termo: "08. O Desafio do Secularismo - Falando de Deus em uma Cultura Secular",
            definicao: "O secularismo é a visão de mundo que exclui Deus da esfera pública e da vida cotidiana. Desafios: (1) A linguagem religiosa é marginalizada. (2) A ciência é vista como a única fonte de conhecimento. (3) O relativismo moral prevalece. (4) O ateísmo é a norma em muitos círculos. (5) O evangelho é visto como intolerante. Estratégias para falar de Deus em um mundo secular: (1) Apologética: defender a fé (1 Pedro 3:15). (2) Testemunho pessoal: compartilhar experiências reais. (3) Linguagem acessível: evitar jargões eclesiásticos. (4) Honestidade intelectual: reconhecer as dificuldades. (5) Humildade: não impor a fé. (6) Amor: demonstrar compaixão. (7) Paciência: respeitar o tempo do outro. (8) Criatividade: usar novas formas de comunicação. (9) Discernimento: saber quando falar e quando calar. (10) Oração: depender do Espírito Santo. A teologia reformada (Schaeffer, Keller) encoraja o engajamento com a cultura secular. 'Não vos conformeis com este mundo, mas transformai-vos pela renovação do vosso entendimento' (Romanos 12:2).",
            referencias: "Romanos 1:18-25; 1 Coríndios 1:18-25; 2 Coríndios 10:3-5; Efésios 4:17-19; Colossenses 2:8; 2 Timóteo 4:3-4; 1 Pedro 3:15-16; 2 Pedro 2:1-3; Judas 1:3-4"
        },
        {
            termo: "09. A Tradução da Bíblia - Comunicação Transcultural",
            definicao: "A tradução da Bíblia é essencial para a comunicação do evangelho em todas as línguas. 'E ouviram-nos falar nas nossas próprias línguas as grandezas de Deus' (Atos 2:11). Princípios da tradução: (1) Fidelidade ao texto original. (2) Clareza na língua alvo. (3) Legibilidade para os leitores. (4) Equivalência dinâmica (sentido) vs. equivalência formal (palavra por palavra). (5) Contextualização cultural (sem perda de verdade). (6) Tradução ecumênica (colaboração). (7) Revisão contínua. (8) Tradução para línguas não escritas. (9) Tradução em áudio (para analfabetos). (10) Tradução digital (aplicativos). Exemplos de traduções: (1) Almeida Corrigida Fiel (ACF) - equivalência formal. (2) Nova Almeida Atualizada (NAA). (3) Nova Versão Internacional (NVI) - equivalência dinâmica. (4) King James Version (KJV). (5) Revised Standard Version (RSV). (6) English Standard Version (ESV). (7) Nova Tradução na Linguagem de Hoje (NTLH). A teologia reformada (Calvino, Kuyper) valoriza a tradução da Bíblia para que todos possam ouvir a Palavra de Deus. 'Como, pois, invocarão aquele em quem não creram? e como crerão naquele de quem não ouviram? e como ouvirão, se não há quem pregue?' (Romanos 10:14).",
            referencias: "Atos 2:5-11; Atos 8:26-40; Atos 17:11; Romanos 15:4; 1 Coríndios 14:9; Neemias 8:8; Provérbios 25:11"
        },
        {
            termo: "10. A Linguagem Inclusiva na Bíblia e na Teologia",
            definicao: "A linguagem inclusiva busca evitar termos que possam excluir ou ofender grupos (gênero, raça, etc.). A Bíblia usa linguagem inclusiva e exclusiva. Exemplos de linguagem inclusiva na Bíblia: (1) 'Bem-aventurados os pobres de espírito' (Mateus 5:3) - dirigido a todos. (2) 'Todo aquele que nele crê' (João 3:16) - universal. (3) 'Não há judeu nem grego... macho nem fêmea' (Gálatas 3:28) - igualdade. (4) 'Toda língua confesse' (Filipenses 2:11) - universal. Exemplos de linguagem exclusiva: (1) 'Pai nosso' (Mateus 6:9) - linguagem masculina para Deus. (2) 'Filho do Homem' (Mateus 8:20) - linguagem masculina para Jesus. (3) 'Irmãos' (Atos 1:15) - pode incluir irmãs no contexto. Debate sobre linguagem inclusiva: (a) Deus é espírito (João 4:24), não tem gênero. (b) A Bíblia usa linguagem masculina para Deus (Pai, Rei, Senhor). (c) Jesus chamou Deus de 'Pai' (Mateus 6:9). (d) A linguagem inclusiva pode obscurecer a teologia. (e) A linguagem exclusiva pode ofender. A teologia reformada (Calvino, Bavinck) mantém a linguagem bíblica (Pai, Filho, Espírito), mas usa linguagem inclusiva para se referir à humanidade. 'Deus é Espírito, e importa que os que o adoram o adorem em espírito e em verdade' (João 4:24).",
            referencias: "Gênesis 1:27; Salmo 8:4; Isaías 66:13; Mateus 6:9; João 4:24; Atos 10:34-35; Romanos 10:12-13; Gálatas 3:28; Colossenses 3:11; 1 Pedro 1:17"
        },
        {
            termo: "11. A Linguagem da Apologética - Defendendo a Fé com Razão",
            definicao: "A apologética usa linguagem racional para defender a fé. 'Antes, santificai ao Senhor Deus em vossos corações; e estai sempre preparados para responder com mansidão e temor a qualquer que vos pedir a razão da esperança que há em vós' (1 Pedro 3:15). Tipos de apologética: (1) Clássica: argumentos filosóficos (cosmológico, teleológico, moral). (2) Evidencial: argumentos históricos (ressurreição, profecias). (3) Pressuposicional: parte da pressuposição da verdade da Escritura (Van Til). (4) Reformada: combinação de pressuposições e evidências. (5) Fideísta: apela à fé sem razão (rejeitado pela teologia reformada). Estratégias linguísticas: (a) Clareza: usar linguagem compreensível. (b) Honestidade: admitir limitações. (c) Humildade: não ser arrogante. (d) Amor: respeitar o interlocutor. (e) Persuasão: usar argumentos racionais. (f) Paciência: respeitar o tempo do outro. (g) Oração: depender do Espírito Santo. (h) Escritura: base bíblica. (i) Testemunho: experiência pessoal. (j) Razão: usar a mente que Deus deu. A teologia reformada (Calvino, Van Til) enfatiza que a razão é um dom de Deus, mas subordinada à revelação. 'Examinai as Escrituras, porque vós cuidais ter nelas a vida eterna, e são elas que de mim testificam' (João 5:39).",
            referencias: "Jó 12:12; Salmo 19:1-6; Isaías 1:18; Atos 17:2-4; Atos 17:22-31; 1 Coríndios 1:18-25; 1 Coríndios 2:14-16; 2 Coríndios 10:3-5; Colossenses 2:8; 1 Pedro 3:15; 2 Pedro 1:16-18"
        },
        {
            termo: "12. A Linguagem da Oração - Falando com Deus",
            definicao: "A oração é a linguagem da comunicação com Deus. 'Orai sem cessar' (1 Tessalonicenses 5:17). 'Perseverai na oração, vigiando com ações de graças' (Colossenses 4:2). Características da linguagem da oração: (1) Adoração: louvar a Deus. (2) Confissão: confessar pecados. (3) Ação de graças: agradecer. (4) Súplica: pedir por necessidades. (5) Intercessão: orar pelos outros. (6) Consagração: dedicar-se a Deus. (7) Lamento: expressar dor e tristeza (Salmo 13). (8) Silêncio: escutar a Deus. (9) Gritos: clamor a Deus (Salmo 22). (10) Sussurros: oração silenciosa (Neemias 2:4). Estilos de oração: (a) Oração formal (litúrgica). (b) Oração espontânea (pessoal). (c) Oração em línguas (carismática). (d) Oração mental (meditação). (e) Oração escrita (diário). (f) Oração em grupo. (g) Oração em família. (h) Oração no silêncio. (i) Oração em voz alta. (j) Oração com lágrimas. (k) Oração com gestos (mãos levantadas). (l) Oração com joelhos dobrados. A teologia reformada (Calvino, Edwards) enfatiza a oração como expressão de dependência de Deus. 'E tudo quanto pedirdes em meu nome, isso farei, para que o Pai seja glorificado no Filho' (João 14:13).",
            referencias: "Êxodo 14:15; 1 Samuel 1:10-20; 2 Crônicas 7:14; Salmo 5:1-3; Salmo 13:1-6; Mateus 6:5-15; Lucas 11:1-13; João 14:13-14; Romanos 8:26-27; Efésios 6:18; Filipenses 4:6-7; Colossenses 4:2; 1 Tessalonicenses 5:17; Tiago 5:13-18"
        },
        {
            termo: "13. Síntese: Falando de Cristo em um Mundo Secular",
            definicao: "Falar de Cristo em um mundo secular é desafiador, mas possível com a ajuda do Espírito Santo. 'Porque não me envergonho do evangelho de Cristo, pois é o poder de Deus para salvação de todo aquele que crê' (Romanos 1:16). Resumo da teologia da linguagem: (1) Deus se revelou em palavras (a Bíblia). (2) A linguagem sobre Deus é possível, mas limitada. (3) Usamos analogia e metáfora para falar de Deus. (4) Os evangelhos são testemunho interpretativo. (5) A pregação é um evento de linguagem. (6) O testemunho pessoal compartilha a história com Cristo. (7) O secularismo desafia a linguagem religiosa. (8) A tradução da Bíblia é essencial para missões. (9) A linguagem inclusiva deve ser usada com sabedoria. (10) A apologética usa a razão para defender a fé. (11) A oração é a linguagem da comunicação com Deus. (12) A linguagem da esperança anuncia a volta de Cristo. (13) Toda linguagem sobre Deus deve ser para a glória de Cristo (1 Coríndios 10:31). 'E tudo quanto fizerdes, por palavra ou por obra, fazei-o em nome do Senhor Jesus, dando por ele graças a Deus Pai' (Colossenses 3:17). Soli Deo Gloria!",
            referencias: "Romanos 1:16; Romanos 10:17; 1 Coríndios 10:31; 2 Coríndios 4:1-6; Efésios 4:29; Colossenses 3:16-17; 2 Timóteo 1:8; 1 Pedro 3:15; Apocalipse 1:9; Apocalipse 22:20-21"
        }
    ]
};