// volume/volume-13.js
window.LIVRO_DATA = {
    nome: "Volume XIII",
    dados: [
        {
            termo: "01. Introdução: A Encarnação e a Representação Artística",
            definicao: "A doutrina da encarnação (João 1:14: 'O Verbo se fez carne') tem profundas implicações para a arte. Se Deus se fez visível na carne de Jesus Cristo, então a matéria não é má (contra o gnosticismo), e a representação visual do divino é, em princípio, possível. No entanto, o Segundo Mandamento proíbe imagens de Deus para adoração (Êxodo 20:4-6; Deuteronômio 5:8-10). A igreja cristã tem oscilado entre: (a) Iconoclastia (rejeição total de imagens de Cristo) - defendida pelos iconoclastas bizantinos (século VIII) e pelos reformadores radicais (Zwinglio, Calvino? Calvino permitiu imagens de Cristo em Bíblias ilustradas, mas não para adoração). (b) Iconodulia (veneração de ícones) - defendida por João Damasceno e pelo Concílio de Nicéia II (787 d.C.), rejeitada pela Reforma. (c) Uso pedagógico e estético (não devocional) - a teologia reformada (Calvino, Lutero) permite imagens de Cristo como auxílio ao ensino (Bíblias ilustradas) e como expressão artística, mas proíbe sua veneração (adoração, genuflexão, incenso). Este volume explora as representações de Cristo na arte, literatura e música, dentro de uma perspectiva reformada que valoriza a criação (Cristo como Criador, Colossenses 1:16), mas rejeita a idolatria.",
            referencias: "Êxodo 20:4-6; Deuteronômio 5:8-10; João 1:14; Atos 17:29; Romanos 1:23; 1 João 5:21"
        },
        {
            termo: "02. A Arte Paleocristã: Cristo como Bom Pastor (séc. I-IV)",
            definicao: "A arte paleocristã (catacumbas, sarcófagos, igrejas primitivas) evitava representações diretas da divindade de Cristo, preferindo símbolos. Principais representações: (1) O Bom Pastor (Buen Pastor): imagem de um jovem pastor carregando uma ovelha nos ombros, baseada em João 10:11 ('Eu sou o bom pastor') e Lucas 15:1-7 (parábola da ovelha perdida). Exemplos: Catacumba de Domitila (Roma), Catacumba de Priscila (Roma). (2) O Peixe (Ichthys): acróstico grego: Iēsous Christos Theou Hyios Sōtēr ('Jesus Cristo, Filho de Deus, Salvador'). (3) O Crismão (Chi-Rho): as duas primeiras letras de Christos em grego (ΧΡ), frequentemente combinadas com Alfa e Ômega. (4) O Cordeiro (Agnus Dei): representação de Cristo como o Cordeiro de Deus (João 1:29). (5) O Orante: figura de Jesus em oração, ou os fiéis em oração. A arte paleocristã evitava representar a crucificação (considerada humilhante) preferindo a ressurreição e a glória de Cristo. A teologia reformada aprecia a simplicidade e o simbolismo da arte paleocristã, que evitava a idolatria.",
            referencias: "João 1:29; João 10:11-18; Lucas 15:1-7; Apocalipse 5:6-14; 1 Pedro 2:25"
        },
        {
            termo: "03. A Arte Bizantina: O Pantocrator (séc. V-XV)",
            definicao: "A arte bizantina (Império Bizantino, 330-1453 d.C.) desenvolveu a imagem de Cristo como Pantocrator ('Todo-poderoso, Soberano do universo'), geralmente representado no teto ou na abside das igrejas (ex.: Santa Sofia, Constantinopla; Mosteiro de Dafne, Grécia; Ravena, Itália). Características: (a) Rosto sério, barbudo, olhos grandes e penetrantes. (b) Mão direita abençoando (dedos formando IC XC - Jesus Cristo). (c) Mão esquerda segurando o Evangelho (geralmente aberto com João 14:6 ou Mateus 11:28). (d) Nimbo (auréola) com cruz. (e) Expressão entre a severidade (juiz) e a misericórdia (salvador). A arte bizantina também produziu ícones: (a) Ícone de Cristo Pantocrator (Sinai, século VI). (b) Ícone de Cristo o Justo (Mosteiro de Santa Catarina, Sinai). (c) Ícone da Transfiguração (Sinai). O Concílio de Nicéia II (787 d.C.) defendeu a veneração de ícones (proskynesis - beijar, reverenciar), distinta da adoração (latreia - devida só a Deus). A teologia reformada rejeita a veneração de ícones como violação do Segundo Mandamento, mas aprecia o valor histórico e teológico da arte bizantina (cristologia alta).",
            referencias: "Mateus 11:28; Mateus 28:18; João 14:6; Apocalipse 1:12-18; Êxodo 20:4-6"
        },
        {
            termo: "04. A Arte Românica e Gótica: Cristo em Majestade (séc. X-XV)",
            definicao: "A arte românica (séculos X-XII) e gótica (séculos XII-XV) na Europa ocidental desenvolveu a imagem de Cristo em Majestade (Christus triumphans). (1) Românico: Cristo como Rei e Juiz (tímpanos das catedrais, ex.: Autun, Moissac, Vézelay). Características: figura frontal, sentado em um trono, com a mão direita abençoando e a esquerda segurando o livro. Rosto severo (juiz). (2) Gótico: Cristo como o Homem sofredor (Christus patiens) - crucifixo com Jesus pendurado, coroado de espinhos, ensanguentado. Exemplos: Catedral de Chartres, Catedral de Notre-Dame de Paris, Catedral de Colônia. A escultura gótica também produziu o 'Cristo da Piedade' (Pietà) - Maria segurando o corpo morto de Jesus (ex.: Pietà de Michelangelo, 1498-1499). A arte gótica também incluiu vitrais com cenas da vida de Cristo (nascimento, milagres, paixão, ressurreição). A teologia reformada tem uma relação ambivalente: aprecia a arte gótica como expressão da fé (catedrais), mas rejeita a veneração de imagens (estátuas, crucifixos) e o culto de Maria (Pietà).",
            referencias: "Isaías 53:1-12; Mateus 25:31-46; João 19:1-37; Apocalipse 1:12-18; Apocalipse 19:11-16"
        },
        {
            termo: "05. O Renascimento: Cristo como Homem Perfeito (séc. XV-XVI)",
            definicao: "O Renascimento (séculos XV-XVI) foi um período de renovação das artes, baseado no humanismo (valorização do homem). A arte renascentista representou Cristo como o 'Homem perfeito' (Uomo universale), enfatizando sua humanidade, beleza e perfeição física. Principais obras: (1) Leonardo da Vinci (1452-1519): 'A Última Ceia' (1495-1498, Milão) - retrata o momento em que Jesus anuncia a traição de Judas. Inovação: expressões faciais, perspectiva, psicologia dos apóstolos. (2) Michelangelo Buonarroti (1475-1564): 'Pietà' (1498-1499, Vaticano) - Maria segurando Jesus morto. 'O Juízo Final' (1536-1541, Capela Sistina) - Cristo como juiz, musculoso, apolíneo. 'Crucifixo de Santo Espírito' (1492-1493). (3) Rafael Sanzio (1483-1520): 'A Transfiguração' (1516-1520, Vaticano) - Cristo transfigurado no monte. (4) Albrecht Dürer (1471-1528): 'Auto-Retrato como Cristo' (1500) - controverso; 'A Paixão' (série de gravuras). (5) Hans Holbein, o Jovem (1497-1543): 'O Corpo de Cristo Morto na Sepultura' (1521-1522) - realismo chocante. A teologia reformada tem uma relação ambivalente com o Renascimento: aprecia a arte (a beleza da criação de Cristo), mas critica o humanismo (centralidade do homem) e o naturalismo excessivo (Cristo como homem comum).",
            referencias: "Isaías 53:2-3; Mateus 17:1-8; Lucas 22:14-23; João 13:21-30"
        },
        {
            termo: "06. A Reforma Protestante e a Arte (séc. XVI)",
            definicao: "A Reforma Protestante (século XVI) teve atitudes variadas em relação à arte cristã. (1) Martinho Lutero (1483-1546): permitiu imagens de Cristo para fins pedagógicos (Bíblias ilustradas, crucifixos), mas proibiu a veneração. Lutero disse: 'Não sou iconoclasta... As imagens são úteis para o ensino, mas não devem ser adoradas'. O artista Lucas Cranach, o Velho (1472-1553) produziu gravuras para as Bíblias luteranas (ex.: 'Cristo abençoando as crianças', 'Cristo e a mulher adúltera'). (2) João Calvino (1509-1564): mais radical, rejeitou imagens de Cristo nas igrejas (exceto Bíblias ilustradas). Calvino argumentou que qualquer imagem de Cristo (humano) não pode representar sua divindade, e que as imagens levam à idolatria. As igrejas reformadas tornaram-se iconoclastas (paredes brancas, sem estátuas, crucifixos ou vitrais). (3) Ulrico Zwinglio (1484-1531): ainda mais radical, removeu todas as imagens das igrejas de Zurique (1523-1524). (4) Os anabatistas: iconoclastas radicais (removeram imagens, queimaram pinturas). A teologia reformada (calvinista) adotou a posição de Calvino: as igrejas reformadas (presbiterianas, congregacionais, batistas) são geralmente iconoclastas (sem imagens de Cristo), mas permitem arte religiosa fora do culto (Bíblias ilustradas, livros, música).",
            referencias: "Êxodo 20:4-6; Deuteronômio 5:8-10; Atos 17:29; Romanos 1:23; 1 João 5:21"
        },
        {
            termo: "07. A Arte Barroca e a Contrarreforma: Cristo Sofredor (séc. XVII)",
            definicao: "O período barroco (século XVII) foi marcado pela Contrarreforma (resposta católica à Reforma). A Igreja Católica usou a arte para evangelizar e emocionar os fiéis, enfatizando a humanidade sofredora de Cristo (Cristo como vítima, mártir). Principais artistas: (1) Caravaggio (1571-1610): realismo dramático, claro-escuro (tenebrismo). Obras: 'A Ceia em Emaús' (1601), 'A Flagelação de Cristo' (1607), 'A Crucificação de São Pedro' (1601). Cristo é representado como homem comum, sujo, ensanguentado. (2) Peter Paul Rubens (1577-1640): 'A Descida da Cruz' (1612-1614), 'A Elevação da Cruz' (1610-1611). (3) Rembrandt van Rijn (1606-1669): holandês, protestante, conhecido por suas representações íntimas de Cristo. Obras: 'A Lição de Anatomia do Dr. Tulp' (1632), 'A Ronda Noturna' (1642), 'Cristo na Tempestade' (1633), 'A Mulher Adúltera' (1644), 'Cristo Apresentado ao Povo' (1655). Rembrandt retratou Cristo como judeu (não europeu), humano, compassivo. (4) El Greco (1541-1614): 'A Crucificação' (1596-1600), 'A Ressurreição' (1596-1600). A teologia reformada aprecia a arte barroca (especialmente Rembrandt) como expressão da piedade cristã, mas rejeita o uso emocional e dramático que pode levar à idolatria.",
            referencias: "Isaías 53:3-5; Mateus 27:27-31; João 19:1-3; 1 Pedro 2:24"
        },
        {
            termo: "08. A Arte Moderna e Contemporânea: Cristo em Diálogo com a Secularização (séc. XIX-XXI)",
            definicao: "A arte moderna (século XIX-XX) e contemporânea (século XXI) refletem a secularização, o pluralismo e a crise da fé cristã. Representações de Cristo variam: (a) Salvador Dalí (1904-1989): 'A Última Ceia' (1955) - Cristo no centro, corpo translúcido, perspectiva dodecaedro. 'Cristo de São João da Cruz' (1951) - Cristo crucificado visto de cima, flutuando. (b) Marc Chagall (1887-1985): 'Cristo Branco' (1938) - Cristo crucificado envolto em um talhe judeu (talit), simbolizando o sofrimento dos judeus no Holocausto. 'A Crucificação' (1940). (c) Georges Rouault (1871-1958): 'O Cristo Padroeiro' (1940) - Cristo sofrido, expressionista. (d) Andy Warhol (1928-1987): 'Detalhe da Última Ceia' (1986) - pop art, repetição de imagens. (e) Arte pós-moderna (1980-2020): 'Piss Christ' (Andres Serrano, 1987) - crucifixo submerso em urina, controverso (ateísmo blasfemo). 'Myra' (Marcus Harvey, 1995) - não relacionado a Cristo. A teologia reformada critica a arte moderna que blasfema Cristo, mas aprecia as representações que o honram (Dalí, Chagall, Rouault).",
            referencias: "João 1:14; João 14:9; Apocalipse 1:12-18; 1 João 2:18-23"
        },
        {
            termo: "09. Cristo na Literatura: Dante, Dostoiévski, Tolkien, Lewis",
            definicao: "A literatura ocidental tem sido profundamente influenciada pela figura de Jesus Cristo. Principais obras: (1) Dante Alighieri (1265-1321): 'A Divina Comédia' (1308-1320) - poema épico sobre a jornada através do Inferno, Purgatório e Paraíso. Cristo é frequentemente mencionado (não aparece diretamente), mas sua obra (cruz, ressurreição) é central. (2) Fiódor Dostoiévski (1821-1881): 'Crime e Castigo' (1866) - Raskolnikov é redimido pelo amor de Sofia (Cristo). 'O Idiota' (1869) - Príncipe Mishkin como um 'Cristo' em um mundo corrupto. 'Os Irmãos Karamázov' (1880) - o 'Grande Inquisidor' (capítulo famoso sobre Cristo retornando à Espanha inquisitorial). (3) J. R. R. Tolkien (1892-1973): 'O Senhor dos Anéis' (1954-1955) - alegoria cristã: Gandalf como figura de Cristo (morre e ressuscita), Frodo carrega o 'fardo' (cruz). Tolkien rejeitava alegorias diretas, mas admitia a influência de sua fé. (4) C. S. Lewis (1898-1963): 'As Crônicas de Nárnia' (1950-1956) - Aslam, o leão, é uma figura de Cristo (morre por Edmundo na Mesa de Pedra e ressuscita). 'Cartas de um Diabo a seu Aprendiz' (1942) - teologia prática. 'Cristianismo Puro e Simples' (1952) - apologética. (5) John Milton (1608-1674): 'Paraíso Perdido' (1667) - poema épico sobre a queda de Adão e Eva, e a promessa de redenção por Cristo. (6) Herman Melville (1819-1891): 'Moby Dick' (1851) - Ahab como anti-Cristo; o navio Pequod como símbolo da humanidade. (7) Charles Williams (1886-1945): 'O Lugar do Leão' (1931) - romance de fantasia com temas cristológicos. A teologia reformada aprecia a literatura cristã como expressão da fé, mas critica a alegoria quando distorce a Escritura.",
            referencias: "Isaías 53:1-12; Mateus 27-28; Lucas 24:13-35; João 1:1-18; Romanos 5:12-21; 1 Coríntios 15:1-58"
        },
        {
            termo: "10. Cristo na Música Sacra: Bach, Händel, Hinos Gospel",
            definicao: "A música ocidental tem sido profundamente influenciada pela figura de Jesus Cristo. Principais obras: (1) Johann Sebastian Bach (1685-1750): luterano, compôs música sacra para a igreja. Obras: 'Paixão segundo São Mateus' (1727) - dramatização da crucificação de Cristo. 'Paixão segundo São João' (1724). 'Oratório de Natal' (1734). 'Cantatas' (mais de 200). A música de Bach é teológica: exprime a fé luterana na cruz e na ressurreição. (2) George Frideric Handel (1685-1759): 'Messias' (1741) - oratório sobre a vida de Cristo, baseado na Escritura. Famoso 'Aleluia' (Apocalipse 19:6). 'Ele foi ferido por nossas transgressões' (Isaías 53:5). 'Eu sei que o meu Redentor vive' (Jó 19:25). (3) Wolfgang Amadeus Mozart (1756-1791): 'Réquiem' (1791) - missa de réquiem católica, incluindo o 'Dies Irae' (juízo). (4) Ludwig van Beethoven (1770-1827): 'Cristo no Monte das Oliveiras' (1803) - oratório sobre a agonia de Jesus no Getsêmani. (5) Franz Joseph Haydn (1732-1809): 'A Criação' (1798) - baseada em Gênesis e Salmos. (6) Hinos gospel (século XIX-XX): 'Amazing Grace' (John Newton, 1779); 'How Great Thou Art' (Carl Boberg, 1885); 'In the Garden' (C. Austin Miles, 1912); 'Because He Lives' (Bill Gaither, 1971). (7) Música gospel contemporânea (século XX-XXI): 'Shout to the Lord' (Darlene Zschech, 1993); 'Reckless Love' (Cory Asbury, 2017). A teologia reformada aprecia a música sacra que exalta a Cristo (Bach, Händel), mas critica a música gospel que enfatiza a experiência humana em detrimento da doutrina.",
            referencias: "Isaías 53:5; Jó 19:25; Salmo 22; Apocalipse 19:6; Mateus 26:36-46; João 19:1-37"
        },
        {
            termo: "11. Cristo no Cinema (séc. XX-XXI)",
            definicao: "O cinema (século XX-XXI) tem produzido numerosos filmes sobre a vida de Cristo. Principais filmes: (1) 'Rei dos Reis' (Cecil B. DeMille, 1927) - épico mudo. (2) 'O Manto Sagrado' (Henry Koster, 1953) - sobre a crucificação. (3) 'Ben-Hur' (William Wyler, 1959) - Cristo aparece brevemente (rosto não mostrado). (4) 'A Maior História de Todos os Tempos' (George Stevens, 1965) - Max von Sydow como Jesus. (5) 'Jesus Cristo Superstar' (Norman Jewison, 1973) - rock ópera, baseado no musical de Andrew Lloyd Webber e Tim Rice. (6) 'A Última Tentação de Cristo' (Martin Scorsese, 1988) - controverso, baseado no romance de Nikos Kazantzakis (Jesus humano, com dúvidas, tentações). (7) 'A Paixão de Cristo' (Mel Gibson, 2004) - hiper-realista, foco no sofrimento físico de Jesus. (8) 'Ressurreição' (Kevin Reynolds, 2016) - sobre a ressurreição de Cristo. (9) 'O Caminho de Casa' (John Fusco, 2016) - sobre a infância de Jesus. (10) 'Jesus Revolution' (Jon Erwin, 2023) - sobre o movimento Jesus People (década 1970). A teologia reformada tem reservas sobre o cinema: (a) A representação visual de Cristo pode levar à idolatria (segundo mandamento). (b) A maioria dos filmes sobre Cristo é teologicamente imprecisa (ex.: 'A Última Tentação' é herética). (c) 'A Paixão de Cristo' (Mel Gibson) é mais fiel, mas foca na violência. (d) A Bíblia é a autoridade final, não o cinema.",
            referencias: "Mateus 27-28; Marcos 15-16; Lucas 23-24; João 18-21; Êxodo 20:4-6"
        },
        {
            termo: "12. Cristo na Poesia e Hinos (séc. I-XXI)",
            definicao: "A poesia cristã e os hinos têm louvado a Cristo desde os primeiros séculos. Principais exemplos: (1) Hino de Filipenses 2:5-11 (século I) - o mais antigo hino cristológico: 'Ele, subsistindo em forma de Deus... esvaziou-se a si mesmo...'. (2) Hino de Colossenses 1:15-20 (século I): 'Ele é a imagem do Deus invisível...'. (3) Hino de 1 Timóteo 3:16 (século I): 'E, sem dúvida, grande é o mistério da piedade: Deus se manifestou em carne...'. (4) Hinos de Efrém da Síria (c. 306-373 d.C.) - 'Hino sobre a Natividade', 'Hino sobre a Paixão'. (5) Hinos de Romanos, o Melodista (c. 490-556 d.C.) - 'Hino sobre a Natividade'. (6) Hinos de João Damasceno (c. 675-749 d.C.) - 'Hino sobre a Ressurreição'. (7) Hinos de Martinho Lutero (1483-1546): 'Castelo Forte é Nosso Deus' (1529) - sobre Cristo como defensor. (8) Hinos de Charles Wesley (1707-1788): 'Hino dos Desejos' ('Ó amor que não me deixará'), 'Cristo, o Senhor, ressurgiu hoje'. (9) Hinos de Isaac Watts (1674-1748): 'Quando eu contemplo a cruz' ('When I Survey the Wondrous Cross'). (10) Hinos de John Newton (1725-1807): 'Amazing Grace' ('Graça Maravilhosa'). (11) Hinos de Fanny Crosby (1820-1915): 'Blessed Assurance' ('Bendita Certeza'). (12) Poesia de John Donne (1572-1631): 'Morte, não te orgulhes'. (13) Poesia de George Herbert (1593-1633): 'O Colar', 'Amor'. (14) Poesia de Gerard Manley Hopkins (1844-1889): 'O Rei do Mundo'. (15) Poesia de T. S. Eliot (1888-1965): 'A Jornada dos Magos', 'Quatro Quartetos'. A teologia reformada aprecia a poesia e os hinos como expressão da fé, desde que teologicamente precisos.",
            referencias: "Filipenses 2:5-11; Colossenses 1:15-20; 1 Timóteo 3:16; Salmo 22; Salmo 110; Apocalipse 5:9-14; Apocalipse 15:3-4"
        },
        {
            termo: "13. Síntese: Cristo na Arte, Literatura e Música",
            definicao: "A arte, a literatura e a música ocidentais têm sido profundamente influenciadas pela figura de Jesus Cristo. A teologia reformada avalia estas representações com base em critérios: (1) Fidelidade à Escritura: a representação deve estar de acordo com a Bíblia (João 5:39; 2 Timóteo 3:16-17). (2) Cristologia ortodoxa: deve afirmar a divindade e humanidade de Cristo (Calcedônia). (3) Rejeição da idolatria: as imagens de Cristo não devem ser adoradas (Êxodo 20:4-6). (4) Valor pedagógico: a arte pode ensinar sobre Cristo, desde que não substitua a Escritura. (5) Valor estético: a beleza da criação reflete a glória de Cristo (Salmo 19:1; Romanos 1:20). (6) Música e poesia: devem exaltar a Cristo (Colossenses 3:16). A igreja reformada deve ser cuidadosa: (a) Não idolatrar imagens de Cristo. (b) Não depender da arte para o conhecimento de Deus (a Escritura é suficiente). (c) Apreciar a arte como expressão da fé. (d) Criticar a arte que blasfema Cristo (pós-moderna). (e) Usar a música sacra para louvar a Cristo. Conclusão: 'Tudo o que fizerdes, por palavra ou por obra, fazei-o em nome do Senhor Jesus, dando por ele graças a Deus Pai' (Colossenses 3:17).",
            referencias: "Êxodo 20:4-6; Salmo 19:1; João 5:39; Romanos 1:20; 2 Timóteo 3:16-17; Colossenses 3:16-17; 1 Pedro 2:21"
        }
    ]
};