// volume/volume-54.js
window.LIVRO_DATA = {
    nome: "Volume LIV",
    dados: [
        {
            termo: "01. Introdução: Cristo como o Médico das Almas e dos Corpos",
            definicao: "Jesus Cristo é chamado de 'Médico' (Mateus 9:12). Ele curou muitos enfermos durante seu ministério terreno e continua a curar hoje, seja diretamente (milagres), seja por meio da medicina, ou através da cura espiritual e emocional. 'Os sãos não precisam de médico, mas sim os enfermos' (Mateus 9:12). 'Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei' (Mateus 11:28). A teologia reformada afirma que a saúde é um dom de Deus, que o sofrimento é resultado da queda (Gênesis 3), e que a redenção final inclui a cura do corpo e da alma na ressurreição (1 Coríntios 15:35-58). Este volume explora a relação entre cristologia e saúde: cura divina, medicina, psicologia, cuidados paliativos, luto, e a esperança da ressurreição. 'Amado, desejo que te vá bem em todas as coisas, e que tenhas saúde, assim como bem vai a tua alma' (3 João 1:2).",
            referencias: "Gênesis 3:1-24; Mateus 9:12; Mateus 11:28; 1 Coríndios 15:35-58; 3 João 1:2; Apocalipse 21:1-4"
        },
        {
            termo: "02. Jesus, o Médico dos Médicos - Curas no Ministério de Cristo",
            definicao: "Jesus realizou muitas curas durante seu ministério, demonstrando sua compaixão e seu poder divino. Milagres de cura de Jesus: (1) Cura do leproso (Mateus 8:2-4; Marcos 1:40-45; Lucas 5:12-16). (2) Cura do paralítico (Mateus 9:1-8; Marcos 2:1-12; Lucas 5:17-26). (3) Cura da sogra de Pedro (Mateus 8:14-15; Marcos 1:29-31; Lucas 4:38-39). (4) Cura do servo do centurião (Mateus 8:5-13; Lucas 7:1-10). (5) Cura da mulher com hemorragia (Mateus 9:20-22; Marcos 5:25-34; Lucas 8:43-48). (6) Cura do cego Bartimeu (Mateus 20:29-34; Marcos 10:46-52; Lucas 18:35-43). (7) Cura do cego de nascença (João 9:1-12). (8) Cura do paralítico em Betesda (João 5:1-15). (9) Cura do endemoninhado gadareno (Mateus 8:28-34; Marcos 5:1-20; Lucas 8:26-39). (10) Cura da mulher encurvada (Lucas 13:10-17). Significados teológicos das curas: (1) Demonstram a divindade de Cristo (João 20:30-31). (2) Demonstram a compaixão de Cristo (Mateus 9:36). (3) Apontam para a redenção final (a ressurreição). (4) São sinais do Reino de Deus (Mateus 12:28). Aplicações para profissionais de saúde: (a) Vejam seu trabalho como imitação de Cristo, o Médico. (b) Tratem os pacientes com compaixão. (c) Reconheçam que a cura vem de Deus (mesmo por meio da medicina). (d) Orem pelos pacientes. (e) Reconheçam os limites da medicina (nem toda doença é curada). 'Jesus Cristo é o mesmo, ontem, hoje e eternamente' (Hebreus 13:8). 'E percorria Jesus toda a Galileia, ensinando... e curando... toda a enfermidade e toda a doença entre o povo' (Mateus 4:23).",
            referencias: "Mateus 4:23; Mateus 8-9; Marcos 1-5; Lucas 4-9; João 5; João 9; João 20:30-31; Hebreus 13:8"
        },
        {
            termo: "03. O Sofrimento na Perspectiva Cristã - A Queda e a Redenção",
            definicao: "O sofrimento (doença, dor, morte) entrou no mundo por causa da queda de Adão e Eva (Gênesis 3:1-24). 'Pelo que, como por um homem entrou o pecado no mundo, e pelo pecado a morte, assim também a morte passou a todos os homens, por isso que todos pecaram' (Romanos 5:12). O sofrimento não é um castigo individual (João 9:1-3), mas uma consequência do pecado original. Deus permite o sofrimento para: (1) Disciplinar e purificar seus filhos (Hebreus 12:5-11). (2) Demonstrar seu poder na fraqueza (2 Coríndios 12:9-10). (3) Aproximar-nos de si (Salmo 119:71). (4) Testemunhar aos outros (Jó 1-2). (5) Glorificar a Deus (João 9:3). A redenção em Cristo inclui a redenção do corpo (Romanos 8:23) e a promessa de um novo céu e nova terra sem sofrimento (Apocalipse 21:1-4). 'Porque a nossa leve e momentânea tribulação produz para nós um peso eterno de glória mui excelente' (2 Coríndios 4:17). 'E Deus limpará de seus olhos toda lágrima; e não haverá mais morte, nem pranto, nem clamor, nem dor' (Apocalipse 21:4).",
            referencias: "Gênesis 3:1-24; Jó 1-2; Salmo 119:71; João 9:1-3; Romanos 5:12; Romanos 8:23; 2 Coríndios 4:17; 2 Coríndios 12:9-10; Hebreus 12:5-11; Apocalipse 21:1-4"
        },
        {
            termo: "04. Cura Divina vs. Medicina - Complementaridade",
            definicao: "A relação entre cura divina (milagres) e medicina é de complementaridade, não de oposição. Deus cura por meio de milagres (diretamente), por meio da medicina (indiretamente, através de médicos, remédios), e por meio da cura interior (psicológica, espiritual). A Bíblia não condena a medicina: (1) O apóstolo Lucas era médico (Colossenses 4:14). (2) Isaías usou uma pasta de figos para curar Ezequias (Isaías 38:21). (3) Jesus usou saliva e barro para curar o cego (João 9:6). (4) Paulo aconselhou Timóteo a usar um pouco de vinho para suas enfermidades estomacais (1 Timóteo 5:23). (5) O bom samaritano usou azeite e vinho (Lucas 10:34). Extremos a evitar: (1) Rejeitar a medicina como 'falta de fé' (legalismo). (2) Confiar exclusivamente na medicina sem orar (naturalismo). (3) Buscar cura a qualquer custo (negando a morte). (4) Prometer cura garantida (teologia da prosperidade). A teologia reformada afirma: (a) Ore pela cura (Tiago 5:14-16). (b) Use os recursos médicos disponíveis. (c) Confie na soberania de Deus (Romanos 8:28). (d) Aceite a vontade de Deus, mesmo quando a cura não vem. 'A oração da fé salvará o doente, e o Senhor o levantará' (Tiago 5:15). 'Todas as coisas são puras para os puros' (Tito 1:15).",
            referencias: "Isaías 38:21; Lucas 10:34; João 9:6; Colossenses 4:14; 1 Timóteo 5:23; Tiago 5:14-16"
        },
        {
            termo: "05. Aconselhamento Pastoral para Enfermos - Cuidado Integral",
            definicao: "O aconselhamento pastoral para enfermos deve considerar o corpo, a alma e o espírito. Passos para o aconselhamento pastoral: (1) Visita: 'estive doente e me visitastes' (Mateus 25:36). (2) Escuta: ouça as queixas, medos, dúvidas. (3) Oração: ore com e pelo enfermo (Tiago 5:14). (4) Leitura bíblica: ofereça consolo das Escrituras (Salmo 23; Romanos 8; 2 Coríndios 4-5). (5) Unção: óleo como símbolo do Espírito Santo (Tiago 5:14). (6) Confissão: se o enfermo desejar, confesse pecados (Tiago 5:16). (7) Ação: ajude com necessidades práticas (comida, transporte, cuidados com crianças). (8) Acompanhamento: visite regularmente. (9) Encaminhamento: para médico, psicólogo, psiquiatra quando necessário. (10) Esperança: ofereça a esperança da ressurreição. Cuidados especiais: (a) Crianças: use linguagem simples. (b) Idosos: paciência, repetição. (c) Terminais: foco na esperança da vida eterna. (d) Depressão: não diga 'apenas tenha fé'; encaminhe para psicólogo/psiquiatra. (e) Transtornos mentais: não atribua apenas a demônios. 'Consolar os que estão em toda a tribulação' (2 Coríndios 1:4). 'Levai as cargas uns dos outros' (Gálatas 6:2).",
            referencias: "Salmo 23; Mateus 25:36; Romanos 8; 2 Coríndios 1:3-5; Gálatas 6:2; Tiago 5:14-16"
        },
        {
            termo: "06. Cuidados Paliativos - Morrendo com Dignidade em Cristo",
            definicao: "Cuidados paliativos são cuidados para pacientes com doenças terminais, focando no alívio da dor e na qualidade de vida, não na cura. A teologia cristã afirma: (1) A vida é sagrada (Gênesis 9:6). (2) A morte é inimiga (1 Coríndios 15:26), mas foi vencida por Cristo. (3) O sofrimento pode ter propósito (Romanos 5:3-5). (4) A eutanásia é proibida (não matarás, Êxodo 20:13). (5) O suicídio assistido é proibido. (6) Os cuidados paliativos são éticos (aliviar a dor, não matar). Princípios dos cuidados paliativos cristãos: (a) Alívio da dor (medicação, se necessário). (b) Suporte emocional e espiritual. (c) Preparação para a morte (arrependimento, perdão, reconciliação). (d) Esperança na ressurreição. (e) Presença da família e da igreja. (f) Não prolongar artificialmente a morte (distinção entre tratamento ordinário e extraordinário). (g) Dignidade: tratar o paciente como pessoa, não como caso. 'Bem-aventurados os mortos que desde agora morrem no Senhor' (Apocalipse 14:13). 'O Senhor é o meu pastor; nada me faltará' (Salmo 23:1). 'Ainda que eu andasse pelo vale da sombra da morte, não temeria mal algum, porque tu estás comigo' (Salmo 23:4).",
            referencias: "Gênesis 9:6; Êxodo 20:13; Salmo 23; Romanos 5:3-5; 1 Coríndios 15:26; Apocalipse 14:13"
        },
        {
            termo: "07. Saúde Mental - Depressão, Ansiedade e a Paz de Cristo",
            definicao: "A saúde mental (depressão, ansiedade, transtorno bipolar, esquizofrenia, etc.) é uma área importante do cuidado pastoral. A Bíblia reconhece a depressão (Salmo 42:5-6; 1 Reis 19:4). Causas: (1) Biológicas (desequilíbrio químico). (2) Psicológicas (traumas, estresse). (3) Espirituais (pecado não confessado, culpa). (4) Sociais (solidão, rejeição). (5) Existenciais (falta de propósito). Aconselhamento pastoral para saúde mental: (a) Não estigmatize (não diga 'é falta de fé'). (b) Escute sem julgamento. (c) Ofereça a paz de Cristo (João 14:27). (d) Encoraje a confissão de pecados (1 João 1:9). (e) Ensine a confiança na soberania de Deus (Romanos 8:28). (f) Incentive a meditação na Palavra (Salmo 1:2). (g) Promova o descanso e o autocuidado (Marcos 6:31). (h) Encaminhe para psicólogo/psiquiatra (não substitua profissionais). (i) Ore regularmente. (j) Acompanhe a medicação (se prescrita). (k) Não prometa cura instantânea. (l) Previna o suicídio (encaminhamento emergencial). 'Porque sou eu, ó minha alma, porque estás abatida? Porque te perturbas dentro de mim? Espera em Deus, pois ainda o louvarei' (Salmo 42:5). 'Lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós' (1 Pedro 5:7).",
            referencias: "1 Reis 19:4; Salmo 42:5-6; Salmo 1:2; João 14:27; Romanos 8:28; Filipenses 4:6-7; 1 Pedro 5:7"
        },
        {
            termo: "08. A Igreja como Comunidade de Cura - Ministério de Aconselhamento",
            definicao: "A igreja deve ser uma comunidade de cura, onde os enfermos encontram acolhimento, apoio e esperança. 'Levai as cargas uns dos outros, e assim cumprireis a lei de Cristo' (Gálatas 6:2). 'Consolai-vos, pois, uns aos outros com estas palavras' (1 Tessalonicenses 4:18). Estruturas de apoio na igreja: (1) Ministério de aconselhamento pastoral (pastores, presbíteros). (2) Grupos de apoio (câncer, luto, depressão). (3) Visitação aos enfermos. (4) Oração pelos enfermos (Tiago 5:14-16). (5) Diaconia (ajuda prática). (6) Pequenos grupos (comunidade terapêutica). (7) Encaminhamento para profissionais (psicólogos, psiquiatras cristãos). (8) Treinamento de líderes para aconselhamento básico. Cuidados: (a) Confidencialidade (não fofocar). (b) Limites (não fazer papel de terapeuta sem treinamento). (c) Encaminhamento (saber os limites). (d) Aconselhamento bíblico vs. aconselhamento psicológico (integração). (e) Supervisão (pastores devem ter mentores). 'Consolai-vos, pois, uns aos outros, e edificai-vos uns aos outros' (1 Tessalonicenses 5:11). 'Há amigos que despedaçam, mas há amigos mais chegados do que um irmão' (Provérbios 18:24).",
            referencias: "Provérbios 18:24; Gálatas 6:2; 1 Tessalonicenses 4:18; 1 Tessalonicenses 5:11; Tiago 5:14-16"
        },
        {
            termo: "09. Esperança na Ressurreição - A Vitória sobre a Morte",
            definicao: "A esperança cristã não é apenas a cura das doenças, mas a ressurreição do corpo. 'Porque, assim como a morte veio por um homem, também a ressurreição dos mortos veio por um homem. Porque, assim como todos morrem em Adão, assim também todos serão vivificados em Cristo' (1 Coríndios 15:21-22). 'O último inimigo que há de ser aniquilado é a morte' (1 Coríndios 15:26). 'Onde está, ó morte, o teu aguilhão? Onde está, ó inferno, a tua vitória?' (1 Coríndios 15:55). Características do corpo ressurreto: (1) Incorruptível (não perece). (2) Glorioso (não humilhado). (3) Poderoso (não fraco). (4) Espiritual (não natural) (1 Coríndios 15:42-44). (5) Semelhante ao corpo de Cristo (Filipenses 3:21). A esperança da ressurreição transforma a maneira como enfrentamos a doença e a morte: (a) Não tememos a morte (Hebreus 2:14-15). (b) Encaramos o sofrimento como temporário (2 Coríndios 4:17). (c) Cuidamos do corpo (templo do Espírito Santo - 1 Coríndios 6:19-20). (d) Consolamos os enlutados (1 Tessalonicenses 4:13-18). 'Bendito o Deus... que nos gerou de novo para uma viva esperança, pela ressurreição de Jesus Cristo dentre os mortos' (1 Pedro 1:3). 'E Deus limpará de seus olhos toda lágrima; e não haverá mais morte, nem pranto, nem clamor, nem dor' (Apocalipse 21:4).",
            referencias: "1 Coríndios 6:19-20; 1 Coríndios 15:1-58; Filipenses 3:21; 1 Tessalonicenses 4:13-18; Hebreus 2:14-15; 1 Pedro 1:3; Apocalipse 21:1-4"
        },
        {
            termo: "10. Luto e Consolação - Cristo, o Consolador",
            definicao: "O luto é o processo de lidar com a perda de um ente querido. Cristo oferece consolação: 'Bem-aventurados os que choram, porque eles serão consolados' (Mateus 5:4). 'Consolai, consolai o meu povo, diz o vosso Deus' (Isaías 40:1). O apóstolo Paulo escreve: 'Bendito seja o Deus... que nos consola em toda a nossa tribulação' (2 Coríndios 1:3-4). Estágios do luto (não lineares): (1) Negação. (2) Raiva. (3) Barganha. (4) Depressão. (5) Aceitação. Cuidado pastoral aos enlutados: (a) Presença: esteja presente (Romanos 12:15). (b) Escuta: ouça sem julgamento. (c) Permita o choro: 'chora com os que choram' (Romanos 12:15). (d) Ofereça a esperança da ressurreição (1 Tessalonicenses 4:13-18). (e) Ajuda prática: comida, cuidados com filhos. (f) Acompanhamento: visite regularmente nos meses seguintes. (g) Grupos de apoio ao luto. (h) Evite frases clichês: 'Deus sabia o que fazia', 'Foi para um lugar melhor' (embora verdadeiras, podem ser insensíveis no momento). (i) Celebre a vida do falecido (culto memorial focado na esperança). 'Chorai com os que choram' (Romanos 12:15). 'Não quero, porém, irmãos, que ignoreis acerca dos que já dormem, para que não vos entristeçais, como os demais que não têm esperança' (1 Tessalonicenses 4:13).",
            referencias: "Isaías 40:1; Mateus 5:4; Romanos 12:15; 2 Coríndios 1:3-5; 1 Tessalonicenses 4:13-18"
        },
        {
            termo: "11. A Relação entre Fé e Medicina - Perspectiva Histórica",
            definicao: "A relação entre fé cristã e medicina tem uma longa história. (1) Antigo Testamento: Deus como médico (Êxodo 15:26), leis de higiene (Levítico 13-14). (2) Novo Testamento: Jesus como médico, Lucas como médico. (3) Idade Média: hospitais cristãos (mosteiros). (4) Reforma: Lutero e Calvino apoiaram a medicina. (5) Ciência moderna: muitos cientistas cristãos (Pasteur, Lister, Fleming). (6) Movimento de cura pela fé (séc. XIX-XX): por vezes excessos. (7) Medicina contemporânea: bioética cristã (aborto, eutanásia, reprodução assistida). A teologia reformada afirma que a medicina é um dom de Deus, e que a cura divina e a medicina não são mutuamente exclusivas. 'Porque eu sou o Senhor que te sara' (Êxodo 15:26). 'Honra ao médico pelos seus serviços; porque o Senhor o criou' (Eclesiástico 38:1, apócrifo, mas ecoando o pensamento judaico-cristão). 'Toda a boa dádiva e todo o dom perfeito vêm do alto' (Tiago 1:17).",
            referencias: "Êxodo 15:26; Levítico 13-14; Lucas 10:34; Colossenses 4:14; Tiago 1:17"
        },
        {
            termo: "12. Bioética Cristã - Questões de Início e Fim da Vida",
            definicao: "A bioética cristã aborda questões morais relacionadas ao início e fim da vida à luz de Cristo. Princípios: (1) A vida humana é sagrada (imagem de Deus - Gênesis 1:26-27). (2) A vida começa na concepção (Salmo 139:13-16). (3) A morte é inimiga, mas foi vencida por Cristo (1 Coríndios 15:26). (4) O sofrimento pode ter propósito (Romanos 5:3-5). (5) A eutanásia é proibida (Êxodo 20:13). (6) O aborto é a morte de um ser humano inocente (Êxodo 21:22-25). Posições cristãs sobre questões bioéticas: (1) Aborto: oposto, exceto risco de vida da mãe (debate). (2) Eutanásia: oposta (cuidados paliativos são éticos). (3) Reprodução assistida (FIV): permitida apenas com espermatozoide e óvulo do casal, sem destruição de embriões. (4) Clonagem: oposta (viola a dignidade humana). (5) Engenharia genética (CRISPR): permitida para curar doenças, não para 'design de bebês'. (6) Transplante de órgãos: permitido (amor ao próximo). (7) Vacinas: permitidas (prevenção de doenças). A teologia reformada incentiva o debate bioético baseado na Escritura. 'Escolhei, pois, hoje a quem sirvais' (Josué 24:15). 'Tudo o que não é de fé é pecado' (Romanos 14:23).",
            referencias: "Gênesis 1:26-27; Êxodo 20:13; Êxodo 21:22-25; Salmo 139:13-16; Romanos 5:3-5; 1 Coríndios 15:26; 2 Coríndios 10:5"
        },
        {
            termo: "13. Síntese: Cristo, a Esperança para os Enfermos e Sofredores",
            definicao: "Cristo é a esperança para todos os enfermos e sofredores. 'Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei' (Mateus 11:28). Resumo da cristologia e saúde: (1) Jesus é o Médico dos médicos (modelo de compaixão). (2) O sofrimento entrou pela queda, mas Deus o usa para nosso bem (Romanos 8:28). (3) A cura divina e a medicina são complementares (dons de Deus). (4) O aconselhamento pastoral deve ser integral (corpo, alma, espírito). (5) Os cuidados paliativos oferecem dignidade na morte. (6) A saúde mental deve ser tratada com seriedade (depressão, ansiedade). (7) A igreja deve ser uma comunidade de cura. (8) A esperança na ressurreição transforma nossa perspectiva da morte. (9) O luto é um processo; Cristo é o Consolador. (10) A bioética cristã defende a vida desde a concepção até a morte natural. 'Toda a Escritura é inspirada por Deus e útil para o ensino, para a repreensão, para a correção, para a instrução na justiça' (2 Timóteo 3:16). 'Porque para mim o viver é Cristo, e o morrer é ganho' (Filipenses 1:21). 'E Deus limpará de seus olhos toda lágrima; e não haverá mais morte, nem pranto, nem clamor, nem dor' (Apocalipse 21:4). Soli Deo Gloria!",
            referencias: "Mateus 11:28; Romanos 8:28; Filipenses 1:21; 2 Timóteo 3:16; Apocalipse 21:4"
        }
    ]
};