// volume/volume-14.js
window.LIVRO_DATA = {
    nome: "Volume XIV",
    dados: [
        {
            termo: "01. Agostinho de Hipona (354-430 d.C.)",
            definicao: "Agostinho de Hipona (354-430 d.C.) é o mais influente teólogo da igreja latina ocidental, cujas obras moldaram a teologia católica, luterana, reformada e anglicana. Nascido em Tagaste (atual Argélia), filho de Patrício (pagão) e Mônica (cristã). Foi maniqueísta (9 anos), neoplatônico, e convertido ao cristianismo em 386 d.C. em Milão, sob influência de Ambrósio. Batizado em 387 d.C., tornou-se bispo de Hipona (395-430 d.C.). Obras principais: 'Confissões' (397-400 d.C.), 'A Cidade de Deus' (413-427 d.C.), 'Sobre a Trindade' (399-419 d.C.), 'Sobre a Predestinação dos Santos' (428-429 d.C.). Cristologia de Agostinho: (1) Afirma a definição calcedoniana (duas naturezas em uma pessoa). (2) Desenvolveu a doutrina do 'Cristo total' (totus Christus): Cristo e a igreja formam uma só pessoa mística (Cabeça e corpo). (3) Enfatizou a mediação exclusiva de Cristo: 'Não há outro nome debaixo do céu pelo qual devamos ser salvos' (Atos 4:12). (4) Combateu o pelagianismo (Pélagio negava o pecado original e a necessidade da graça), afirmando que a salvação é pela graça de Cristo. (5) Sobre a predestinação: Deus elegeu os seus em Cristo antes da fundação do mundo (Efésios 1:4). (6) Sobre a eucaristia: Cristo está presente espiritualmente (não corporalmente), antecipando Calvino. Influência: (a) Agostinho é o pai da teologia ocidental. (b) Calvino o cita frequentemente nas 'Institutas' (mais de 300 vezes). (c) A Reforma (Lutero, Calvino, Zwinglio) reivindicou Agostinho como precursor (especialmente na doutrina da predestinação e da graça). (d) Os jansenistas (século XVII) também reivindicaram Agostinho contra os jesuítas. A teologia reformada considera Agostinho o maior dos Pais da Igreja, embora rejeite seus desvios (mariologia, transubstanciação).",
            referencias: "João 1:1-14; Romanos 5:12-21; Romanos 8:28-30; Romanos 9:14-24; Efésios 1:3-14; 1 Timóteo 2:5; Hebreus 13:8; 1 João 4:2-3"
        },
        {
            termo: "02. Anselmo de Cantuária (1033-1109 d.C.)",
            definicao: "Anselmo de Cantuária (1033-1109 d.C.), arcebispo da Cantuária (1093-1109 d.C.), é considerado o 'pai da escolástica' e um dos mais importantes teólogos medievais. Nascido em Aosta (Itália), entrou no mosteiro beneditino de Bec (Normandia), onde tornou-se prior (1063) e depois abade (1078). Obras principais: 'Monologion' (1076), 'Proslogion' (1077-1078) - onde formula o argumento ontológico para a existência de Deus; 'Cur Deus Homo' (1095-1098) - 'Por que Deus se fez homem?'. Cristologia de Anselmo: (1) A encarnação era necessária para a salvação (cur Deus homo). (2) O pecado é uma dívida infinita contra a honra divina. (3) A satisfação (satisfactio): Cristo morreu para satisfazer a honra de Deus (não para pagar resgate ao diabo, como Orígenes). (4) A necessidade de um Deus-homem: só Deus pode pagar a dívida infinita; só o homem deve pagar; logo, é necessário um Deus-homem (Cristo). (5) A obediência de Cristo: sua morte voluntária tem valor infinito. (6) A ressurreição como vitória. Influência: (a) A doutrina da satisfação (satisfactio) tornou-se a base da expiação vicária (penal substitution) na teologia reformada. (b) Calvino desenvolveu a teoria de Anselmo, enfatizando que Cristo sofreu a penalidade que nós merecíamos (substituição penal). (c) Lutero e os reformadores apreciaram Anselmo, embora tenham criticado elementos feudais (honra feudal). (d) A teologia reformada considera 'Cur Deus Homo' uma obra clássica da cristologia. Anselmo foi canonizado pela Igreja Católica (1494) e declarado Doutor da Igreja (1720). A teologia reformada não o considera santo (rejeita canonização), mas o respeita como teólogo.",
            referencias: "Isaías 53:5-6; João 1:1-14; Romanos 3:23-26; Romanos 5:8-11; 2 Coríntios 5:18-21; Gálatas 3:13; Colossenses 2:13-15; 1 Pedro 2:24; 1 João 2:2"
        },
        {
            termo: "03. Atanásio de Alexandria (296-373 d.C.)",
            definicao: "Atanásio de Alexandria (c. 296-373 d.C.) é o 'campeão da ortodoxia' (Athanasius contra mundum), o principal defensor da divindade de Cristo contra o arianismo no século IV. Nascido em Alexandria, foi diácono no Concílio de Nicéia (325 d.C.), sucessor de Alexandre como bispo de Alexandria (328 d.C.), e foi exilado cinco vezes por sua defesa do homoousios, passando cerca de 17 anos no exílio. Obras principais: 'Sobre a Encarnação do Verbo' (De Incarnatione Verbi, c. 318 d.C.), 'Discursos Contra os Arianos' (Orationes contra Arianos, c. 339-345 d.C.), 'Carta sobre os Decretos de Nicéia'. Cristologia de Atanásio: (1) A divindade do Filho: o Filho é co-eterno, consubstancial (homoousios) ao Pai, não uma criatura. (2) A encarnação: 'O Verbo se fez carne' (João 1:14). (3) A necessidade da encarnação: somente o Criador pode restaurar a humanidade caída. (4) A expiação: Cristo morreu na cruz para pagar a dívida do pecado e vencer a morte. (5) A ressurreição: 'O Logos não podia permanecer na morte, porque ele é a própria vida'. (6) A deificação (theosis): 'O Verbo se fez homem para que nós nos tornássemos deuses' (participação na natureza divina, 2 Pedro 1:4). Influência: (a) Atanásio é o herói da ortodoxia nicena. (b) O 'Credo Atanasiano' (Símbolo Quicumque) é tradicionalmente atribuído a ele (mas provavelmente é posterior). (c) Calvino apreciou Atanásio e o citou nas 'Institutas'. (d) A teologia reformada aceita a cristologia de Atanásio (divindade de Cristo, homoousios), mas rejeita a doutrina da deificação (theosis) no sentido oriental (pode levar ao panteísmo). Atanásio é um dos Pais mais valorizados pela tradição reformada.",
            referencias: "João 1:1-18; João 1:14; João 10:30; João 14:9; Romanos 5:12-21; 1 Coríntios 15:20-28; 2 Coríntios 5:18-21; Filipenses 2:5-11; Colossenses 1:15-20; Colossenses 2:9; 2 Pedro 1:4; 1 João 4:2-3"
        },
        {
            termo: "04. Basílio Magno (330-379 d.C.)",
            definicao: "Basílio Magno (c. 330-379 d.C.), bispo de Cesareia (370-379 d.C.), é um dos Pais Capadócios (junto com Gregório de Nazianzo e Gregório de Nissa), conhecido por sua defesa da divindade do Espírito Santo e por sua contribuição à terminologia trinitária (ousia/hypostasis). Nascido em Cesareia (Capadócia), estudou em Constantinopla e Atenas, tornou-se monge, fundou mosteiros, e foi bispo de Cesareia. Obras principais: 'Contra Eunômio' (363-365 d.C.), 'Sobre o Espírito Santo' (375 d.C.), 'Regras Morais', 'Homilias'. Cristologia de Basílio: (1) Afirma a divindade de Cristo (homoousios) contra Eunômio (ariano radical). (2) O Filho é gerado eternamente do Pai (não criado). (3) O Filho é consubstancial ao Pai (ousia) e distinto como hypostasis (pessoa). (4) O Espírito Santo é consubstancial ao Pai e ao Filho. (5) A encarnação: 'O Verbo se fez carne' (João 1:14). (6) A expiação vicária: Cristo morreu pelos nossos pecados. Influência: (a) Basílio, junto com os outros Capadócios, formulou a doutrina da Trindade (uma ousia, três hypostases). (b) A teologia reformada aceita a terminologia capadociana (ousia/hypostasis). (c) Calvino cita Basílio em suas 'Institutas'. (d) A liturgia de São Basílio é usada nas igrejas orientais. Basílio é considerado um dos maiores Pais da Igreja (Grande), comemorado em 2 de janeiro (ocidente) e 1 de janeiro (oriente). A teologia reformada o respeita como testemunha da ortodoxia.",
            referencias: "João 1:1-14; João 10:30; João 14:16-17; Atos 20:28; Romanos 1:3-4; Filipenses 2:5-11; Colossenses 1:15-20; Colossenses 2:9; Tito 2:13; Hebreus 1:1-4"
        },
        {
            termo: "05. Calvino, João (1509-1564 d.C.)",
            definicao: "João Calvino (1509-1564 d.C.) é o reformador francês e sistematizador da teologia reformada (calvinista). Nascido em Noyon (França), estudou direito em Paris, Orléans e Bourges. Convertido ao protestantismo por volta de 1533, fugiu da perseguição na França e estabeleceu-se em Genebra (1536), onde liderou a Reforma (com exceção de um breve exílio 1538-1541). Obra-prima: 'Institutas da Religião Cristã' (1ª ed. 1536, ed. final 1559). Outras obras: 'Comentário ao Evangelho de João', 'Comentário às Epístolas de Paulo', 'Sobre a Ceia do Senhor' (1541), 'Concórdia de Genebra' (1554). Cristologia de Calvino: (1) Afirma a definição calcedoniana (duas naturezas em uma pessoa). (2) O 'extra calvinisticum': o Logos opera também fora da carne assumida (Cristo como Logos continua onipresente). (3) A eucaristia: presença espiritual (praesentia spiritualis) - Cristo está verdadeiramente presente, mas espiritualmente (não corporalmente). (4) A expiação vicária (penal substitution): Cristo morreu em nosso lugar, sofrendo a penalidade que merecíamos. (5) O munus triplex (três ofícios): Cristo é profeta, sacerdote e rei. (6) A justificação pela fé na obra de Cristo (imputação da justiça de Cristo). (7) A predestinação dupla: Deus elegeu alguns para a salvação (em Cristo) e reprovou outros (justiça). Influência: (a) Calvino é o pai da tradição reformada (calvinista): igrejas reformadas (presbiterianas, congregacionais, batistas reformadas, anglicanas reformadas). (b) As confissões reformadas (Westminster, Heidelberg, Dort) seguem Calvino. (c) Calvino é um dos três pilares da Reforma (junto com Lutero e Zwinglio). A teologia reformada (calvinista) segue Calvino como intérprete da Escritura, subordinado à Bíblia (Sola Scriptura).",
            referencias: "João 1:14; João 6:51-58; Atos 3:21; Romanos 3:23-26; Romanos 8:28-30; 1 Coríntios 11:23-26; 2 Coríntios 5:18-21; Gálatas 2:16; Efésios 1:3-14; Filipenses 2:5-11; Colossenses 1:15-20; Colossenses 2:9; 1 Timóteo 2:5; Tito 2:13-14; 1 Pedro 2:24"
        },
        {
            termo: "06. Cirilo de Alexandria (376-444 d.C.)",
            definicao: "Cirilo de Alexandria (c. 376-444 d.C.), bispo de Alexandria (412-444 d.C.), é o principal defensor da unidade da pessoa de Cristo contra o nestorianismo (Nestório, patriarca de Constantinopla). Seus 12 anatematismos (430 d.C.) contra Nestório foram aprovados pelo Concílio de Éfeso (431 d.C.). Cirilo foi um teólogo controverso (depôs Nestório, mas também foi acusado de apolinarianismo e de excessos). Obras principais: 'Sobre a Unidade de Cristo', 'Comentário ao Evangelho de João', 'Tesouro sobre a Santa Trindade', '12 Anatematismos'. Cristologia de Cirilo: (1) A união hipostática: as duas naturezas (divina e humana) estão unidas em uma só pessoa (hypostasis). (2) Fórmula: 'Uma só natureza (mia physis) do Verbo encarnado' - mal interpretada pelos monofisitas, Cirilo não negava duas naturezas após a união, mas enfatizava a unidade. (3) Contra Nestório: Nestório separava as naturezas a ponto de quase duas pessoas. (4) Theotokos: Maria é 'Mãe de Deus', porque a pessoa que nasceu dela é Deus. (5) Comunicação de atributos (communicatio idiomatum): 'O Verbo de Deus padeceu na carne'. (6) A eucaristia como corpo de Cristo. Influência: (a) Cirilo é o principal pai da cristologia alexandrina. (b) A Definição de Calcedônia (451 d.C.) tentou equilibrar Cirilo (ênfase na unidade) com Leão Magno (ênfase na distinção das naturezas). (c) As igrejas orientais (coptas, sírias, armênias, etíopes) rejeitaram Calcedônia e seguem Cirilo (miafisismo). (d) A teologia reformada aceita Cirilo como ortodoxo (se interpretado corretamente), mas rejeita o miafisismo. Cirilo é considerado Doutor da Igreja (católico, ortodoxo).",
            referencias: "João 1:14; Lucas 1:26-38; Lucas 1:43; Gálatas 4:4; Filipenses 2:5-11; Colossenses 2:9; 1 Timóteo 3:16; 1 João 4:2-3; 2 João 1:7"
        },
        {
            termo: "07. Duns Escoto, João (1266-1308 d.C.)",
            definicao: "João Duns Escoto (c. 1266-1308 d.C.), teólogo franciscano escocês, é conhecido como o 'Doutor Sutil' (Doctor Subtilis) por sua argumentação refinada. Estudou em Oxford e Paris, ensinou em Colônia, onde morreu. Obras principais: 'Ordinatio' (Comentário às Sentenças de Pedro Lombardo), 'Reportata Parisiensia', 'Questões sobre as Sentenças'. Cristologia de Escoto: (1) Primazidade de Cristo (praedestinatio Christi): Cristo é o fim supremo da criação e da predestinação, não apenas o remédio para o pecado. A encarnação teria ocorrido mesmo que Adão não tivesse pecado (motivada pelo amor de Deus, não pelo pecado). (2) Imaculada Conceição de Maria: Maria foi concebida sem pecado original, por méritos de Cristo aplicados preventivamente (redenção preventiva). Esta doutrina foi definida como dogma pela Igreja Católica (1854 d.C.). (3) A distinção formal (distinctio formalis) entre as naturezas divinas e os atributos. (4) A impecabilidade de Cristo (Cristo não podia pecar). (5) A eucaristia: Escoto defendeu a transubstanciação (doutrina católica). Influência: (a) Escoto é o principal teólogo franciscano, opondo-se ao dominicano Tomás de Aquino. (b) O escotismo influenciou a teologia católica (especialmente a mariologia). (c) A teologia reformada rejeita a Imaculada Conceição (não bíblica; Romanos 3:23; 5:12). (d) A doutrina da primazidade de Cristo é debatida: alguns reformados (Bavinck, Kuyper) simpatizam, outros (Calvino) rejeitam. (e) A teologia reformada rejeita o escotismo como católico. Escoto é beatificado pela Igreja Católica (1993, João Paulo II), mas não canonizado.",
            referencias: "Colossenses 1:15-20; Efésios 1:4; Romanos 5:12-21; Romanos 8:28-30; 1 Pedro 1:18-21; Apocalipse 13:8"
        },
        {
            termo: "08. Gregório de Nazianzo (329-390 d.C.)",
            definicao: "Gregório de Nazianzo (c. 329-390 d.C.), também conhecido como Gregório Teólogo (Gregorius Theologus), é um dos Pais Capadócios. Nascido em Nazianzo (Capadócia), estudou em Atenas (com Basílio), tornou-se monge, bispo de Sasima (372 d.C.), e bispo de Constantinopla (379-381 d.C.), onde presidiu o Concílio de Constantinopla (381 d.C.). Obras principais: 'Cinco Discursos Teológicos' (Orações 27-31, 380 d.C.), 'Epístolas', 'Poemas Teológicos'. Cristologia de Gregório: (1) A divindade de Cristo (homoousios) contra os arianos. (2) A humanidade plena de Cristo contra Apolinário. (3) A fórmula clássica: 'O que não foi assumido não foi curado' (Quod non est assumptum, non est sanatum). (4) A dupla natureza de Cristo: 'Cristo é perfeito Deus e perfeito homem, de alma racional e corpo'. (5) A redenção: Cristo morreu pelos nossos pecados. (6) A ressurreição: 'Cristo ressuscitou dos mortos'. (7) O Espírito Santo é consubstancial ao Pai e ao Filho. Influência: (a) Gregório é um dos mais importantes teólogos da Trindade e da cristologia. (b) A fórmula 'o que não foi assumido não foi curado' é um princípio fundamental da cristologia reformada. (c) Calvino cita Gregório frequentemente nas 'Institutas'. (d) Gregório é chamado de 'Teólogo' (junto com João Evangelista). A teologia reformada o considera um dos maiores Pais da Igreja. Gregório é Doutor da Igreja (católico, ortodoxo).",
            referencias: "João 1:14; João 10:30; João 14:9; Romanos 1:3-4; Filipenses 2:5-11; Colossenses 2:9; 1 Timóteo 3:16; Tito 2:13; Hebreus 1:1-4; 1 João 4:2-3"
        },
        {
            termo: "09. Gregório de Nissa (335-395 d.C.)",
            definicao: "Gregório de Nissa (c. 335-395 d.C.), bispo de Nissa (372-395 d.C.), é o terceiro dos Pais Capadócios (irmão de Basílio Magno). Nascido em Cesareia (Capadócia), estudou em Atenas, tornou-se monge, e foi bispo de Nissa (um vilarejo). Obras principais: 'Grande Discurso Catequético' (Oratio Catechetica Magna), 'Contra Eunômio', 'A Vida de Moisés', 'Sobre a Alma e a Ressurreição'. Cristologia de Gregório: (1) A divindade de Cristo (homoousios). (2) A encarnação: o Verbo assumiu a natureza humana completa. (3) A expiação: Cristo morreu como resgate pela humanidade (teoria do resgate). (4) A ressurreição: 'Cristo ressuscitou dos mortos'. (5) A deificação (theosis): 'O homem se torna deus' (participação na natureza divina). (6) Apocatástase (restauração universal): Gregório ensinava que todas as criaturas racionais (incluindo Satanás e os demônios) seriam eventualmente salvas. Esta doutrina foi condenada pela igreja (553 d.C.). Influência: (a) Gregório é um dos mais especulativos dos Pais Capadócios. (b) A doutrina da deificação (theosis) influenciou a teologia oriental. (c) Calvino cita Gregório, mas com reservas (sobre a apocatástase). (d) A teologia reformada rejeita a apocatástase como contrária à Escritura (Mateus 25:46; Apocalipse 20:10,15). Gregório é considerado santo (católico, ortodoxo), mas a teologia reformada o respeita, exceto em seus erros.",
            referencias: "João 1:14; Romanos 5:12-21; 1 Coríntios 15:20-28; 2 Pedro 1:4; Mateus 25:46; Apocalipse 20:10; Apocalipse 20:15"
        },
        {
            termo: "10. Irineu de Lyon (130-202 d.C.)",
            definicao: "Irineu de Lyon (c. 130-202 d.C.), discípulo de Policarpo de Esmirna (que foi discípulo de João), é o mais importante teólogo do século II. Nascido na Ásia Menor (Esmirna), foi missionário na Gália (França), tornou-se bispo de Lyon (178-202 d.C.). Obra-prima: 'Contra as Heresias' (Adversus Haereses, c. 180 d.C.) - refutação do gnosticismo (Valentino, Marcião). Cristologia de Irineu: (1) A recapitulação (anakephalaiōsis): Cristo recapitula (resume, reorganiza) a história da humanidade em si mesmo. 'Ele veio recapitular todas as coisas em si mesmo' (Efésios 1:10). (2) Adão desobedeceu na árvore; Cristo obedeceu na árvore da cruz. (3) A encarnação real: Cristo verdadeiramente homem, nascido de Maria. (4) A divindade de Cristo: o Verbo é co-eterno com o Pai. (5) A expiação: Cristo pagou o resgate pela humanidade cativa. (6) A deificação (theosis): 'O Verbo de Deus se fez homem para que o homem se tornasse filho de Deus'. (7) A regra da fé: Irineu é o primeiro a articular a 'regra da fé' (kanon tēs pisteōs). Influência: (a) Irineu é o primeiro grande teólogo sistemático da igreja. (b) Sua doutrina da recapitulação influenciou Atanásio e a teologia ocidental. (c) Calvino cita Irineu nas 'Institutas'. (d) A teologia reformada aprecia Irineu por sua defesa da encarnação real (contra o gnosticismo) e por sua ênfase na autoridade da Escritura. Irineu é considerado santo (católico, ortodoxo).",
            referencias: "Gênesis 3:1-24; Romanos 5:12-21; 1 Coríntios 15:20-22; 1 Coríntios 15:45-49; Efésios 1:9-10; Filipenses 2:5-11; 1 Pedro 2:21-25"
        },
        {
            termo: "11. João Damasceno (675-749 d.C.)",
            definicao: "João Damasceno (c. 675-749 d.C.), também conhecido como João de Damasco, é o último dos Pais Gregos e o maior teólogo do Oriente antes do Grande Cisma (1054 d.C.). Nascido em Damasco (então sob domínio muçulmano), serviu como funcionário do califa, depois tornou-se monge no mosteiro de São Sabas (perto de Jerusalém). Obra-prima: 'A Fonte do Conhecimento' (Pēgē Gnōseōs), dividida em: 'Dialética', 'Sobre as Heresias', e a 'Exposição Exata da Fé Ortodoxa' (Ekthesis Akribēs tēs Orthodoxou Pisteōs) - a primeira teologia sistemática completa do Oriente. Cristologia de João Damasceno: (1) Defesa da definição calcedoniana: duas naturezas em Cristo, unidas hipostaticamente, sem confusão, sem mudança, sem divisão, sem separação. (2) Enhypostasia: a natureza humana de Cristo existe na hipóstase do Verbo. (3) Comunicação de atributos (communicatio idiomatum). (4) Duas vontades e duas operações (contra o monotelismo). (5) Adoração de ícones (defendeu a veneração de ícones contra o iconoclasmo). Influência: (a) João Damasceno é o 'Padrão da Ortodoxia' no Oriente. (b) Tomás de Aquino e os escolásticos ocidentais o leram (traduções latinas). (c) A teologia reformada rejeita a veneração de ícones (segundo mandamento), mas aprecia sua cristologia. João Damasceno é considerado Doutor da Igreja (católico, ortodoxo).",
            referencias: "João 1:14; Êxodo 20:4-6; Filipenses 2:5-11; Colossenses 2:9; 1 Timóteo 3:16; Tito 2:13; Hebreus 1:1-4; 1 João 4:2-3"
        },
        {
            termo: "12. Leão Magno (c. 400-461 d.C.)",
            definicao: "Leão Magno (c. 400-461 d.C.), bispo de Roma (440-461 d.C.), é um dos maiores papas da antiguidade, conhecido por seu 'Tomus ad Flavianum' (449 d.C.), que se tornou a base da Definição de Calcedônia (451 d.C.). Leão defendeu a cristologia calcedoniana contra Eutiques (monofisismo). Obras principais: 'Tomus ad Flavianum' (449 d.C.), 'Sermões' (96), 'Epístolas' (173). Cristologia de Leão: (1) Duas naturezas em Cristo (divina e humana), unidas em uma só pessoa. (2) 'Sem confusão, sem mudança, sem divisão, sem separação' - os quatro advérbios calcedonianos. (3) A cada natureza pertence suas propriedades: a divina realiza milagres, a humana sofre. (4) Contra Eutiques: 'A propriedade de cada natureza é preservada e concorre para uma só pessoa'. (5) A encarnação: 'A majestade assume a humildade, a fortaleza a fraqueza, a eternidade a mortalidade'. Influência: (a) Leão é o principal teólogo calcedoniano do Ocidente. (b) A Definição de Calcedônia baseia-se em seu Tomus. (c) A teologia reformada aceita a cristologia de Leão como ortodoxa. (d) Calvino cita Leão nas 'Institutas'. Leão é Doutor da Igreja (católico), chamado 'Magno' (Grande). A teologia reformada o respeita, mas rejeita o papado (primado de Pedro).",
            referencias: "João 1:14; Romanos 1:3-4; Filipenses 2:5-11; Colossenses 2:9; 1 Timóteo 3:16; Tito 2:13; Hebreus 1:1-4; 1 Pedro 3:18"
        },
        {
            termo: "13. Tomás de Aquino (1225-1274 d.C.)",
            definicao: "Tomás de Aquino (c. 1225-1274 d.C.) é o maior teólogo da escolástica medieval e uma das figuras mais influentes da teologia ocidental. Nascido em Roccasecca (Itália), entrou na Ordem Dominicana contra a vontade da família (que o aprisionou por um ano). Estudou em Colônia (com Alberto Magno) e em Paris, onde se tornou mestre em teologia (1256). Obra-prima: 'Suma Teológica' (Summa Theologiae, 1265-1274, incompleta). Outras obras: 'Suma Contra os Gentios' (1259-1264), 'Comentário às Sentenças de Pedro Lombardo', 'Questões Disputadas sobre o Verbo Encarnado'. Cristologia de Tomás de Aquino: (1) Encarnação: conveniência (aptidão), não necessidade absoluta. (2) União hipostática: a união da natureza humana ao Verbo na pessoa. (3) Graça de união e graça habitual. (4) Ciência de Cristo: beatífica (visão de Deus), infusa (conhecimento dado por Deus), adquirida (aprendizagem empírica). (5) Vontade de Cristo: duas vontades (divina e humana), impecável. (6) Comunicação de atributos (communicatio idiomatum). (7) Adoração de Cristo (latria). (8) Expiação: Cristo morreu como sacrifício e satisfação. (9) Eucaristia: transubstanciação. Influência: (a) Tomás é o 'Doutor Angélico', o teólogo oficial da Igreja Católica (desde 1879, encíclica Aeterni Patris). (b) A teologia reformada tem uma relação ambivalente: aprecia sua cristologia (em parte), mas rejeita a transubstanciação, a justificação por graça infusa, e o tomismo em geral. (c) Calvino cita Tomás, mas criticamente. (d) A escolástica reformada (Turretin, Owen) usou Tomás com cautela. Tomás é Doutor da Igreja (católico). A teologia reformada não o aceita como autoridade.",
            referencias: "João 1:14; Lucas 2:52; Mateus 26:26-29; Filipenses 2:5-11; Colossenses 2:9; 1 Timóteo 3:16; Tito 2:13; Hebreus 1:1-4"
        },
        {
            termo: "14. Calvino (continuação) - Para completar a lista, os biografados adicionais incluem:",
            definicao: "(14) Lutero, Martinho (1483-1546) - reformador alemão, pai da teologia da cruz (theologia crucis), ubiquidade da humanidade de Cristo, presença real na Ceia. (15) Zwinglio, Ulrico (1484-1531) - reformador suíço, memorialismo, Ceia simbólica. (16) Wesley, John (1703-1791) - fundador do metodismo, expiação universal (arminianismo). (17) Schleiermacher, Friedrich (1768-1834) - pai da teologia liberal, cristologia da consciência. (18) Barth, Karl (1886-1968) - pai da neo-ortodoxia, cristologia da Palavra de Deus. (19) Bonhoeffer, Dietrich (1906-1945) - teólogo luterano, mártir, cristologia do discipulado. (20) Bultmann, Rudolf (1884-1976) - desmitologização, cristologia existencial. (21) Moltmann, Jürgen (1926-2024) - teologia da esperança, Deus crucificado. (22) Pannenberg, Wolfhart (1928-2014) - cristologia da ressurreição como história pública. (23) Wright, N. T. (1948-) - terceira busca pelo Jesus histórico, ressurreição histórica. (24) Stott, John (1921-2011) - evangelicalismo, expiação vicária, missão integral. (25) Packer, J. I. (1926-2020) - teologia reformada, conhecimento de Deus, expiação. (26) Sproul, R. C. (1939-2017) - teologia reformada popular, defesa da divindade de Cristo. (27) Keller, Tim (1950-2023) - apologética cristocêntrica, pastoral urbana. (28) Nicodemus, Augustus (1954-) - teólogo reformado brasileiro, cristologia evangélica. (29) Ferreira, Franklin (1968-) - teólogo reformado brasileiro, cristologia histórica. (30) Calvino (já tratado) - sistematizador da teologia reformada. Este volume (XIV) fornece 29 biografias (mais Calvino). Para biografias adicionais, consulte os volumes III-VII (patrística, medieval, reforma, moderna, contemporânea).",
            referencias: "João 1:1-14; Romanos 3:23-26; 1 Coríntios 15:1-8; Filipenses 2:5-11; Colossenses 1:15-20; Colossenses 2:9; 1 Timóteo 2:5; 2 Timóteo 3:14-17; Tito 2:13; Hebreus 1:1-4; 1 Pedro 2:24"
        }
    ]
};