// volume/volume-44.js
window.LIVRO_DATA = {
    nome: "Volume XLIV",
    dados: [
        {
            termo: "01. Introdução: As Festas do Senhor como Sombras de Cristo",
            definicao: "As festas judaicas (moedim) foram instituídas por Deus no Antigo Testamento como 'sombras das coisas futuras', cujo corpo (realidade) é Cristo (Colossenses 2:17). O apóstolo Paulo escreve: 'Portanto, ninguém vos julgue pelo comer, ou pelo beber, ou por causa dos dias de festa, ou da lua nova, ou dos sábados, que são sombras das coisas futuras, mas o corpo é de Cristo' (Colossenses 2:16-17). As sete festas do Senhor (Levítico 23) são: (1) Páscoa (Pessach) - 14 de Nisan. (2) Pães Asmos (Hag HaMatzot) - 15-21 de Nisan. (3) Primícias (Yom HaBikkurim) - 16 de Nisan. (4) Pentecostes (Shavuot) - 50 dias após a Páscoa. (5) Trombetas (Yom Teruah / Rosh Hashanah) - 1 de Tishrei. (6) Expiação (Yom Kippur) - 10 de Tishrei. (7) Tabernáculos (Sukkot) - 15-21 de Tishrei. A teologia reformada vê nestas festas o plano de redenção de Deus, cumprido em Jesus Cristo. 'Cristo, nossa Páscoa, foi sacrificado por nós' (1 Coríntios 5:7). Este volume explora cada uma das festas judaicas, seu significado original, e seu cumprimento em Cristo. 'Porque todas as promessas de Deus são nele sim, e por ele amém' (2 Coríntios 1:20).",
            referencias: "Êxodo 12:1-28; Levítico 23:1-44; Números 28-29; Deuteronômio 16:1-17; 2 Crônicas 8:12-13; Esdras 3:4-5; Neemias 8:13-18; Zacarias 14:16-19; João 5:1; João 7:2; Atos 2:1; 1 Coríntios 5:7; Colossenses 2:16-17; Hebreus 8:5; Hebreus 10:1"
        },
        {
            termo: "02. Páscoa (Pessach) - O Cordeiro Imolado (Êxodo 12; Levítico 23:5)",
            definicao: "A Páscoa (Pessach - 'passar por cima') é a primeira e mais importante festa judaica, instituída na noite do Êxodo do Egito (Êxodo 12). Data: 14 de Nisan (março/abril). Instituição: (1) Cada família devia tomar um cordeiro sem defeito (Êxodo 12:3-5). (2) O cordeiro era sacrificado ao entardecer (Êxodo 12:6). (3) O sangue era aspergido nos umbrais das portas (Êxodo 12:7,22-23). (4) A carne era assada no fogo e comida com pães asmos e ervas amargas (Êxodo 12:8). (5) O anjo da morte 'passou por cima' (pasach) das casas protegidas pelo sangue (Êxodo 12:13,23). Significado espiritual: (a) O cordeiro sem defeito - tipo de Cristo sem pecado (1 Pedro 1:19). (b) O sangue nos umbrais - tipo do sangue de Cristo que nos protege da ira de Deus (Romanos 5:9). (c) A libertação do Egito (escravidão) - tipo da libertação do pecado (Romanos 6:18). (d) Os pães asmos (sem fermento) - tipo da pureza e santidade (1 Coríntios 5:7-8). Cumprimento em Cristo: (1) Jesus é o Cordeiro de Deus que tira o pecado do mundo (João 1:29). (2) Jesus morreu na cruz exatamente na hora em que os cordeiros eram sacrificados (João 19:14-16,31). (3) 'Cristo, nossa Páscoa, foi sacrificado por nós' (1 Coríntios 5:7). (4) Nenhum osso de Jesus foi quebrado (Êxodo 12:46; João 19:33-36). (5) A Última Ceia de Jesus foi uma ceia pascal (Mateus 26:17-30). A teologia reformada vê na Páscoa o tipo mais claro da morte expiatória de Cristo.",
            referencias: "Êxodo 12:1-28; Levítico 23:5; Números 9:1-14; Números 28:16; Deuteronômio 16:1-8; Josué 5:10-11; 2 Reis 23:21-23; Esdras 6:19-22; Isaías 53:7; João 1:29; João 1:36; João 19:14-16; João 19:31-36; 1 Coríntios 5:7; 1 Pedro 1:18-19"
        },
        {
            termo: "03. Pães Asmos (Hag HaMatzot) - O Pão da Vida (Levítico 23:6-8)",
            definicao: "A Festa dos Pães Asmos (Hag HaMatzot - 'Festa dos Pães sem Fermento') durava sete dias (15-21 de Nisan), imediatamente após a Páscoa (Levítico 23:6-8). Durante este período, todo fermento (chametz) era removido das casas, e o pão asmo (matzah) era comido. Significado espiritual: (1) O fermento simboliza o pecado e a corrupção (1 Coríntios 5:6-8). (2) Remover o fermento simboliza a purificação do pecado. (3) Os pães asmos simbolizam a pureza e a santidade. (4) A pressa em sair do Egito (não houve tempo para o pão levedar) simboliza a urgência da salvação. Cumprimento em Cristo: (1) Jesus é o 'pão da vida' (João 6:35,48,51). (2) A vida de Jesus foi sem pecado ('sem fermento' - 1 Pedro 2:22; 1 João 3:5). (3) Paulo exorta: 'Alimpai-vos, pois, do fermento velho, para que sejais uma nova massa, assim como estais sem fermento. Porque Cristo, nossa Páscoa, foi sacrificado por nós. Por isso façamos festa, não com o fermento velho, nem com o fermento da maldade e da corrupção, mas com os asmos da sinceridade e da verdade' (1 Coríntios 5:7-8). (4) A remoção do fermento aponta para a santificação em Cristo. A teologia reformada vê nos Pães Asmos o chamado à pureza e santidade em Cristo.",
            referencias: "Êxodo 12:15-20; Êxodo 13:3-10; Levítico 23:6-8; Números 28:17-25; Deuteronômio 16:3-4; 1 Coríntios 5:6-8; João 6:35; João 6:51; 1 Pedro 2:22; 1 João 3:5"
        },
        {
            termo: "04. Primícias (Yom HaBikkurim) - A Ressurreição de Cristo (Levítico 23:9-14)",
            definicao: "A Festa das Primícias (Yom HaBikkurim) ocorria no dia seguinte ao sábado após a Páscoa (16 de Nisan). Um molho das primeiras espigas de cevada era oferecido ao Senhor como oferta de primícias (Levítico 23:9-14). Significado espiritual: (1) As primícias representam a primeira parte da colheita, dedicada a Deus. (2) As primícias são a garantia da colheita total. (3) A oferta de primícias reconhecia que toda a colheita pertencia a Deus. Cumprimento em Cristo: (1) Jesus ressuscitou dos mortos no dia das primícias (o dia seguinte ao sábado após a Páscoa - João 20:1). (2) Cristo é as 'primícias dos que dormem' (1 Coríntios 15:20,23). (3) A ressurreição de Cristo é a garantia da nossa ressurreição. 'Porque, assim como todos morrem em Adão, assim também todos serão vivificados em Cristo. Cada um, porém, na sua ordem: Cristo as primícias; depois os que são de Cristo, na sua vinda' (1 Coríntios 15:22-23). (4) Tiago escreve: 'De sua própria vontade nos gerou pela palavra da verdade, para que fôssemos como primícias das suas criaturas' (Tiago 1:18). A teologia reformada vê nas Primícias o tipo da ressurreição de Cristo e da nossa ressurreição.",
            referencias: "Levítico 23:9-14; Números 28:26-31; Deuteronômio 26:1-11; Rute 2:23; 1 Coríntios 15:20-23; Tiago 1:18; Apocalipse 14:4"
        },
        {
            termo: "05. Pentecostes (Shavuot) - O Derramamento do Espírito (Levítico 23:15-22)",
            definicao: "A Festa de Pentecostes (Shavuot - 'Semanas') ocorria 50 dias após a Páscoa (Levítico 23:15-22). Era também chamada Festa da Colheita (Êxodo 23:16) e Festa das Semanas (Êxodo 34:22). Características: (1) Dois pães levedados eram oferecidos como primícias da colheita do trigo (Levítico 23:17). (2) Sacrifícios de animais (Levítico 23:18-20). (3) Celebração da entrega da lei no Monte Sinai (Êxodo 19-20). Significado espiritual: (1) A colheita representa a igreja (João 4:35). (2) Os dois pães levedados (com fermento) representam a igreja (judeus e gentios) que ainda tem pecado (mas que é aceita por Deus). (3) A lei foi dada no Sinai, apontando para a necessidade de um Salvador. Cumprimento em Cristo: (1) O Espírito Santo foi derramado no dia de Pentecostes (Atos 2:1-4). (2) A igreja (judeus e gentios) foi formada. (3) Pedro pregou, e três mil almas foram salvas (Atos 2:41). (4) A lei foi escrita no coração dos crentes (Jeremias 31:33; Ezequiel 36:26-27). (5) O Pentecostes marca o início da colheita espiritual (a igreja). A teologia reformada vê no Pentecostes o cumprimento da promessa do Espírito Santo, e a formação da igreja como corpo de Cristo.",
            referencias: "Êxodo 19:1-20; Êxodo 23:16; Êxodo 34:22; Levítico 23:15-22; Números 28:26-31; Deuteronômio 16:9-12; Atos 2:1-41; 1 Coríntios 16:8; Jeremias 31:33; Ezequiel 36:26-27"
        },
        {
            termo: "06. Trombetas (Yom Teruah / Rosh Hashanah) - O Chamado ao Arrependimento (Levítico 23:23-25)",
            definicao: "A Festa das Trombetas (Yom Teruah - 'Dia do Toque da Trombeta') ocorria no primeiro dia do sétimo mês (1 de Tishrei, setembro/outubro) (Levítico 23:23-25). Mais tarde, esta festa tornou-se o Ano Novo judaico (Rosh Hashanah). Características: (1) Dia de descanso (shabbaton). (2) Toque de trombetas (shofar - chifre de carneiro). (3) Ofertas queimadas. Significado espiritual: (1) A trombeta anunciava a presença de Deus (Êxodo 19:16-19). (2) A trombeta convocava o povo para o arrependimento. (3) A trombeta anunciava o juízo vindouro. Cumprimento em Cristo: (1) Jesus anunciou o arrependimento: 'Arrependei-vos, porque é chegado o reino dos céus' (Mateus 4:17). (2) A trombeta de Deus anunciará a segunda vinda de Cristo: 'Porque o Senhor mesmo descerá do céu com alarido, e com voz de arcanjo, e com a trombeta de Deus' (1 Tessalonicenses 4:16). (3) A última trombeta anunciará a ressurreição dos mortos: 'Num momento, num abrir e fechar de olhos, ante a última trombeta; porque a trombeta soará, e os mortos ressuscitarão incorruptíveis' (1 Coríntios 15:52). (4) O toque da trombeta convida ao arrependimento antes do juízo. A teologia reformada vê na Festa das Trombetas o tipo do chamado ao arrependimento e da segunda vinda de Cristo.",
            referencias: "Levítico 23:23-25; Números 29:1-6; Neemias 8:1-12; Salmo 81:3-4; Mateus 4:17; 1 Coríntios 15:52; 1 Tessalonicenses 4:16; Apocalipse 8:2; Apocalipse 11:15"
        },
        {
            termo: "07. Expiação (Yom Kippur) - O Sacrifício Definitivo (Levítico 16; 23:26-32)",
            definicao: "O Dia da Expiação (Yom Kippur) é o dia mais sagrado do calendário judaico, ocorrendo no décimo dia do sétimo mês (10 de Tishrei) (Levítico 16; 23:26-32). Características: (1) Jejum e humilhação (afligir a alma). (2) O sumo sacerdote entrava no Santo dos Santos uma vez por ano (Levítico 16:2-3). (3) Dois bodes: um sacrificado ao Senhor, o outro (Azazel) enviado ao deserto (Levítico 16:7-10,20-22). (4) O sangue era aspergido sobre o propiciatório (Levítico 16:14-15). (5) Jejum e arrependimento (Levítico 23:27-32). Significado espiritual: (1) O pecado requer expiação (satisfação da justiça divina). (2) O sumo sacerdote (tipo de Cristo) intercedia pelo povo. (3) O bode sacrificado (tipo da morte de Cristo). (4) O bode emissário (Azazel) levava os pecados para longe (tipo da remoção dos pecados). (5) O sangue era levado ao Santo dos Santos (tipo do sangue de Cristo levado ao céu). Cumprimento em Cristo: (1) Cristo é o Sumo Sacerdote perfeito que entrou no céu com seu próprio sangue (Hebreus 4:14-16; 7:26-28; 9:11-12). (2) Cristo é o sacrifício definitivo pelos pecados (Hebreus 9:28; 10:10-14). (3) O sangue de Cristo remove os pecados (1 João 1:7). (4) O Dia da Expiação era anual; o sacrifício de Cristo foi único e definitivo (Hebreus 9:25-28). A teologia reformada vê em Yom Kippur o tipo mais completo da expiação vicária de Cristo.",
            referencias: "Levítico 16:1-34; Levítico 23:26-32; Números 29:7-11; Isaías 53:10-12; Romanos 3:25; Hebreus 4:14-16; Hebreus 7:26-28; Hebreus 9:1-28; Hebreus 10:1-18; 1 João 2:2; 1 João 4:10"
        },
        {
            termo: "08. Tabernáculos (Sukkot) - Deus Habita entre Nós (Levítico 23:33-44)",
            definicao: "A Festa dos Tabernáculos (Sukkot - 'Cabanas') ocorria do 15 ao 21 de Tishrei (setembro/outubro) (Levítico 23:33-44). Os israelitas habitavam em cabanas (sukkot) durante sete dias, lembrando a peregrinação no deserto (Levítico 23:42-43). O oitavo dia (Shemini Atzeret) era uma assembléia solene (Levítico 23:36). Significado espiritual: (1) A peregrinação no deserto (tipo da peregrinação cristã). (2) A dependência de Deus para provisão (maná, água). (3) A alegria da colheita (fim do ano agrícola). (4) A esperança da habitação de Deus com seu povo. Cumprimento em Cristo: (1) 'E o Verbo se fez carne, e habitou (tabernaculou) entre nós' (João 1:14). (2) Jesus proclamou durante a Festa dos Tabernáculos: 'Se alguém tem sede, venha a mim e beba. Quem crê em mim, como diz a Escritura, do seu interior fluirão rios de água viva' (João 7:37-38). (3) A água e a luz eram celebradas durante Sukkot; Jesus é a água viva (João 4:10) e a luz do mundo (João 8:12). (4) O descanso das cabanas aponta para o descanso eterno em Cristo (Hebreus 4:9-11). (5) O oitavo dia aponta para a nova criação (Apocalipse 21-22). A teologia reformada vê em Sukkot o tipo da encarnação ('Emanuel, Deus conosco') e da peregrinação cristã.",
            referencias: "Levítico 23:33-44; Números 29:12-38; Deuteronômio 16:13-15; Esdras 3:4; Neemias 8:13-18; Zacarias 14:16-19; João 1:14; João 7:2; João 7:37-39; João 8:12; Hebreus 4:9-11; Apocalipse 21:3"
        },
        {
            termo: "09. A Festa da Dedicação (Hanukkah) - A Luz do Mundo (João 10:22-39)",
            definicao: "A Festa da Dedicação (Hanukkah - 'Dedicação'), também chamada Festa das Luzes, não é uma das festas do Levítico, mas foi instituída por Judas Macabeu em 165 a.C. para comemorar a purificação do templo após a profanação por Antíoco Epifânio (1 Macabeus 4:36-59). Era celebrada no dia 25 de Quisleu (novembro/dezembro) durante oito dias. Significado espiritual: (1) A dedicação do templo a Deus. (2) O milagre do azeite que durou oito dias (tradição). (3) A luz como símbolo da presença de Deus. Cumprimento em Cristo: (1) Jesus estava em Jerusalém durante a Festa da Dedicação (João 10:22-23). (2) Durante esta festa, Jesus declarou: 'Eu e o Pai somos um' (João 10:30). (3) Jesus é o verdadeiro templo (João 2:19-21). (4) Jesus é a luz do mundo (João 8:12; 9:5). (5) A dedicação do templo aponta para a dedicação do nosso corpo como templo do Espírito Santo (1 Coríntios 6:19-20). A teologia reformada vê em Hanukkah o tipo da luz de Cristo e da dedicação a Deus.",
            referencias: "1 Macabeus 4:36-59; João 10:22-39; João 2:19-21; João 8:12; 1 Coríntios 6:19-20; 2 Coríntios 6:16"
        },
        {
            termo: "10. A Festa de Purim - A Intercessão de Ester e de Cristo (Ester 9:20-32)",
            definicao: "A Festa de Purim ('Sortes') foi instituída por Mordecai e Ester para comemorar a salvação dos judeus do plano de Hamã de exterminá-los (Ester 9:20-32). Era celebrada nos dias 14 e 15 de Adar (fevereiro/março). Significado espiritual: (1) A salvação do povo de Deus da destruição. (2) A intercessão de Ester (tipo de Cristo). (3) A inversão do destino: o que era para mal tornou-se bem. Cumprimento em Cristo: (1) Ester intercedeu pelo seu povo diante do rei Assuero (Ester 4:10-16; 5:1-8; 7:1-10). Cristo intercede por nós diante do Pai (Romanos 8:34; Hebreus 7:25). (2) Ester arriscou sua vida: 'Se eu perecer, pereci' (Ester 4:16). Cristo deu sua vida por nós (João 10:11). (3) Mardoqueu foi exaltado após a humilhação (Ester 6-10). Cristo foi exaltado após a humilhação (Filipenses 2:9-11). (4) Hamã foi enforcado (Ester 7:9-10). Satanás será derrotado (Apocalipse 20:10). (5) O povo foi salvo. Cristo salva seu povo (Mateus 1:21). A teologia reformada vê em Purim o tipo da intercessão de Cristo e da vitória sobre o mal.",
            referencias: "Ester 1-10; Ester 4:10-16; Ester 7:9-10; Ester 9:20-32; Mateus 1:21; João 10:11; Romanos 8:34; Hebreus 7:25; Filipenses 2:9-11; Apocalipse 20:10"
        },
        {
            termo: "11. O Sábado (Shabbat) - O Descanso em Cristo (Êxodo 20:8-11; Deuteronômio 5:12-15)",
            definicao: "O Sábado (Shabbat - 'descanso') é o dia sagrado semanal (sétimo dia) instituído por Deus na criação (Gênesis 2:2-3) e codificado no Decálogo (Êxodo 20:8-11; Deuteronômio 5:12-15). Significado espiritual: (1) Descanso da criação: Deus descansou no sétimo dia (Gênesis 2:2-3). (2) Descanso da redenção: Israel descansou da escravidão do Egito (Deuteronômio 5:15). (3) O sábado era um sinal da aliança (Êxodo 31:12-17). Cumprimento em Cristo: (1) Jesus é o Senhor do sábado (Mateus 12:8; Marcos 2:28; Lucas 6:5). (2) Jesus oferece descanso espiritual: 'Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei. Tomai sobre vós o meu jugo, e aprendei de mim... e encontrareis descanso para as vossas almas' (Mateus 11:28-30). (3) O descanso do sábado aponta para o descanso eterno em Cristo (Hebreus 4:1-11). (4) Os cristãos celebram o domingo (Dia do Senhor, Dies Domini) como o dia da ressurreição (Atos 20:7; 1 Coríntios 16:2; Apocalipse 1:10). (5) Paulo ensina que o sábado era uma 'sombra das coisas futuras, mas o corpo é de Cristo' (Colossenses 2:16-17). A teologia reformada (Calvino, Westminster) ensina que o sábado cerimonial foi abolido, mas o princípio do descanso (um dia em sete) permanece, aplicado ao domingo (o sábado cristão).",
            referencias: "Gênesis 2:2-3; Êxodo 20:8-11; Êxodo 31:12-17; Levítico 23:3; Deuteronômio 5:12-15; Neemias 13:15-22; Isaías 58:13-14; Mateus 11:28-30; Mateus 12:8; Atos 20:7; 1 Coríntios 16:2; Colossenses 2:16-17; Hebreus 4:1-11; Apocalipse 1:10"
        },
        {
            termo: "12. A Lua Nova (Rosh Chodesh) - A Nova Criação em Cristo",
            definicao: "A Lua Nova (Rosh Chodesh) era celebrada no primeiro dia de cada mês com ofertas especiais (Números 28:11-15) e toque de trombetas (Números 10:10). Significado espiritual: (1) O recomeço (novo ciclo lunar). (2) A dependência de Deus para o tempo (calendário). (3) A renovação da criação. Cumprimento em Cristo: (1) Cristo é o 'princípio da criação de Deus' (Apocalipse 3:14). (2) A nova criação em Cristo: 'Assim que, se alguém está em Cristo, nova criatura é; as coisas velhas já passaram; eis que tudo se fez novo' (2 Coríntios 5:17). (3) Paulo escreve: 'Portanto, ninguém vos julgue... por causa dos dias de festa, ou da lua nova, ou dos sábados' (Colossenses 2:16). (4) O mês começa com a lua nova; a vida cristã começa com Cristo. (5) No céu, haverá uma nova lua (?) - a nova Jerusalém (Apocalipse 21-22). A teologia reformada vê na Lua Nova o tipo da nova criação em Cristo.",
            referencias: "Números 10:10; Números 28:11-15; 1 Samuel 20:5; 2 Reis 4:23; Isaías 66:23; Ezequiel 46:1-3; Colossenses 2:16; 2 Coríntios 5:17; Apocalipse 3:14; Apocalipse 21-22"
        },
        {
            termo: "13. Síntese: Cristo é o Cumprimento de Todas as Festas",
            definicao: "As festas judaicas (Páscoa, Pães Asmos, Primícias, Pentecostes, Trombetas, Expiação, Tabernáculos, Hanukkah, Purim, Sábado, Lua Nova) eram 'sombras das coisas futuras, mas o corpo é de Cristo' (Colossenses 2:16-17). Jesus Cristo é o cumprimento de todas as festas: (1) Páscoa - O Cordeiro imolado (1 Coríntios 5:7). (2) Pães Asmos - O Pão da Vida (João 6:35). (3) Primícias - A Ressurreição (1 Coríntios 15:20-23). (4) Pentecostes - O Derramamento do Espírito (Atos 2:1-4). (5) Trombetas - O Chamado ao Arrependimento e a Segunda Vinda (Mateus 4:17; 1 Tessalonicenses 4:16). (6) Expiação - O Sacrifício Definitivo (Hebreus 9:11-14; 10:10-14). (7) Tabernáculos - Deus Habita entre Nós (João 1:14; Apocalipse 21:3). (8) Hanukkah - A Luz do Mundo (João 8:12). (9) Purim - A Intercessão de Cristo (Romanos 8:34; Hebreus 7:25). (10) Sábado - O Descanso em Cristo (Mateus 11:28-30; Hebreus 4:9-11). (11) Lua Nova - A Nova Criação (2 Coríntios 5:17). A teologia reformada celebra estas verdades em Cristo, não mais nas sombras. 'Porque todas as promessas de Deus são nele sim, e por ele amém, para glória de Deus por nós' (2 Coríntios 1:20). 'Porque dele e por ele, e para ele, são todas as coisas; glória, pois, a ele eternamente. Amém' (Romanos 11:36). Soli Deo Gloria!",
            referencias: "Romanos 11:36; 2 Coríntios 1:20; Colossenses 2:16-17; Hebreus 8:5; Hebreus 10:1; 1 Coríntios 5:7; João 1:14; João 6:35; João 8:12; Mateus 11:28-30; Atos 2:1-4; 1 Coríntios 15:20-23; 1 Tessalonicenses 4:16; Hebreus 4:9-11; Hebreus 9:11-14; Hebreus 10:10-14; Romanos 8:34; Hebreus 7:25; 2 Coríntios 5:17; Apocalipse 21-22"
        }
    ]
};