window.LIVRO_DATA = {
  nome: "2 João",
  id: "2joao",
  testament: "NT",

  dados: {
    1: [
        "<span style='font-size: 15px;'><strong>VERSÍCULO: 1</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> O ancião à senhora eleita e a seus filhos, aos quais amo na verdade, e não somente eu, mas também todos os que têm conhecido a verdade,<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> Ὁ πρεσβύτερος ἐκλεκτῇ κυρίᾳ καὶ τοῖς τέκνοις αὐτῆς, οὓς ἐγὼ ἀγαπῶ ἐν ἀληθείᾳ, καὶ οὐκ ἐγὼ μόνος, ἀλλὰ καὶ πάντες οἱ ἐγνωκότες τὴν ἀλήθειαν,<br>",
        "🔤 <strong>Transliteração:</strong> Ho presbyteros eklektē kyria kai tois teknois autēs, hous egō agapō en alētheia, kai ouk egō monos, alla kai pantes hoi egnōkotes tēn alētheian,<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) Ὁ πρεσβύτερος ἐκλεκτῇ κυρίᾳ καὶ τοῖς τέκνοις αὐτῆς, οὓς ἐγὼ ἀγαπῶ ἐν ἀληθείᾳ, καὶ οὐκ ἐγὼ μόνος, ἀλλὰ καὶ πάντες οἱ ἐγνωκότες τὴν ἀλήθειαν,<br>",
        "🇻🇦 <strong>Vulgata:</strong> Senior electae dominae et natis eius quos ego diligo in veritate et non ego solus sed et omnes qui cognoverunt veritatem<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>πρεσβύτερος</em> – 'ancião' – presbítero, líder da igreja. <em>ἐκλεκτῇ</em> – 'eleita' – escolhida, selecionada. <em>κυρίᾳ</em> – 'senhora' – senhora, dona (pode referir-se a uma igreja ou a uma mulher). <em>ἀγαπῶ</em> – 'amo' – tenho amor. <em>ἀληθείᾳ</em> – 'verdade' – verdade, realidade. <em>ἐγνωκότες</em> – 'conhecido' – tendo conhecido.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> João se identifica como ancião, enfatizando sua autoridade espiritual. A 'senhora eleita' pode ser uma igreja local ou uma irmã na fé. O amor na verdade é a marca da comunhão cristã. A verdade une todos os que a conhecem.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> João escreve como ancião, usando linguagem afetuosa. O amor é fundamentado na verdade, não em sentimentos vagos.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Amemos os irmãos na verdade. O amor cristão é baseado na verdade de Deus.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 2</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Por amor da verdade que está em nós, e para sempre estará conosco.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> διὰ τὴν ἀλήθειαν τὴν μένουσαν ἐν ἡμῖν, καὶ μεθ᾽ ἡμῶν ἔσται εἰς τὸν αἰῶνα.<br>",
        "🔤 <strong>Transliteração:</strong> dia tēn alētheian tēn menousan en hēmin, kai meth' hēmōn estai eis ton aiōna.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) διὰ τὴν ἀλήθειαν τὴν μένουσαν ἐν ἡμῖν, καὶ μεθ᾽ ἡμῶν ἔσται εἰς τὸν αἰῶνα.<br>",
        "🇻🇦 <strong>Vulgata:</strong> propter veritatem quae permanet in nobis et nobiscum erit in aeternum<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>μένουσαν</em> – 'está' – que permanece, que habita. <em>μεθ᾽ ἡμῶν</em> – 'conosco' – conosco. <em>εἰς τὸν αἰῶνα</em> – 'para sempre' – eternamente.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A verdade não é transitória; ela habita no crente e permanece para sempre. A verdade é eterna e estável.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> João explica que seu amor é motivado pela verdade que habita neles e permanecerá para sempre.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> A verdade de Deus é eterna. Que ela habite em nós e nos guie.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 3</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> A graça, a misericórdia e a paz, da parte de Deus Pai e da parte do Senhor Jesus Cristo, o Filho do Pai, seja convosco em verdade e amor.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> ἔσται μεθ᾽ ὑμῶν χάρις, ἔλεος, εἰρήνη παρὰ θεοῦ πατρός, καὶ παρὰ κυρίου Ἰησοῦ Χριστοῦ τοῦ υἱοῦ τοῦ πατρός, ἐν ἀληθείᾳ καὶ ἀγάπῃ.<br>",
        "🔤 <strong>Transliteração:</strong> estai meth' hymōn charis, eleos, eirēnē para theou patros, kai para kyriou Iēsou Christou tou huiou tou patros, en alētheia kai agapē.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) ἔσται μεθ᾽ ὑμῶν χάρις, ἔλεος, εἰρήνη παρὰ θεοῦ πατρός, καὶ παρὰ κυρίου Ἰησοῦ Χριστοῦ τοῦ υἱοῦ τοῦ πατρός, ἐν ἀληθείᾳ καὶ ἀγάπῃ.<br>",
        "🇻🇦 <strong>Vulgata:</strong> erit vobiscum gratia misericordia pax a Deo Patre et a Christo Iesu Filio Patris in veritate et caritate<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>χάρις</em> – 'graça' – favor imerecido. <em>ἔλεος</em> – 'misericórdia' – compaixão, piedade. <em>εἰρήνη</em> – 'paz' – paz, harmonia. <em>παρά</em> – 'da parte de' – de, procedente de. <em>υἱοῦ τοῦ πατρός</em> – 'Filho do Pai' – título que enfatiza a divindade de Cristo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A graça, misericórdia e paz são dons de Deus Pai e do Senhor Jesus Cristo. O Filho é o mediador dessas bênçãos. Elas são experimentadas em verdade e amor.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> João saúda com uma bênção tríplice, enfatizando a origem divina e o contexto da verdade e do amor.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Que a graça, misericórdia e paz de Deus estejam conosco em verdade e amor.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 4</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Muito me alegro por ter achado que alguns de teus filhos andam na verdade, assim como temos recebido o mandamento do Pai.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> Ἐχάρην λίαν ὅτι εὕρηκα ἐκ τῶν τέκνων σου περιπατοῦντας ἐν ἀληθείᾳ, καθὼς ἐντολὴν ἐλάβομεν παρὰ τοῦ πατρός.<br>",
        "🔤 <strong>Transliteração:</strong> Echarēn lian hoti heurēka ek tōn teknōn sou peripatountas en alētheia, kathōs entolēn elabomen para tou patros.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) Ἐχάρην λίαν ὅτι εὕρηκα ἐκ τῶν τέκνων σου περιπατοῦντας ἐν ἀληθείᾳ, καθὼς ἐντολὴν ἐλάβομεν παρὰ τοῦ πατρός.<br>",
        "🇻🇦 <strong>Vulgata:</strong> gavisus sum valde quoniam inveni de filiis tuis ambulantes in veritate sicut mandatum accepimus a Patre<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>Ἐχάρην</em> – 'alegro' – alegro-me, regozijo. <em>λίαν</em> – 'Muito' – grandemente, muito. <em>εὕρηκα</em> – 'achado' – encontrei, achei. <em>περιπατοῦντας</em> – 'andam' – que andam, que vivem. <em>ἐντολὴν</em> – 'mandamento' – ordem, preceito. <em>ἐλάβομεν</em> – 'recebido' – recebemos.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A alegria de João é ver os filhos andando na verdade. Andar na verdade é obedecer ao mandamento do Pai. A obediência é a fonte da alegria.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> João expressa sua alegria ao descobrir que alguns da comunidade estão vivendo na verdade.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Andemos na verdade. Isso traz alegria aos líderes espirituais.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 5</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> E agora, senhora, rogo-te, não como se te escrevesse um novo mandamento, mas o mesmo que tivemos desde o princípio: que nos amemos uns aos outros.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> Καὶ νῦν ἐρωτῶ σε, κυρία, οὐχ ὡς ἐντολὴν καινὴν γράφων σοι, ἀλλὰ ἣν εἴχομεν ἀπ᾽ ἀρχῆς, ἵνα ἀγαπῶμεν ἀλλήλους.<br>",
        "🔤 <strong>Transliteração:</strong> Kai nyn erōtō se, kyria, ouch hōs entolēn kainēn graphōn soi, all' hēn eichomen ap' archēs, hina agapōmen allēlous.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) Καὶ νῦν ἐρωτῶ σε, κυρία, οὐχ ὡς ἐντολὴν καινὴν γράφων σοι, ἀλλὰ ἣν εἴχομεν ἀπ᾽ ἀρχῆς, ἵνα ἀγαπῶμεν ἀλλήλους.<br>",
        "🇻🇦 <strong>Vulgata:</strong> et nunc rogo te domina non tamquam mandatum novum scribens tibi sed quod habuimus ab initio ut diligamus alterutrum<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>ἐρωτῶ</em> – 'rogo' – peço, suplico. <em>κυρία</em> – 'senhora' – senhora (termo de respeito). <em>ἀπ᾽ ἀρχῆς</em> – 'princípio' – desde o início. <em>ἀγαπῶμεν</em> – 'amemos' – tenhamos amor. <em>ἀλλήλους</em> – 'uns aos outros' – reciprocamente.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> O mandamento do amor não é novo, mas é fundamental e eterno. O amor é a essência da vida cristã.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> João exorta ao amor mútuo, lembrando que é um mandamento desde o princípio.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Amemo-nos uns aos outros. Este é o mandamento desde o princípio.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 6</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> E o amor é este: que andemos segundo os seus mandamentos. Este é o mandamento, como já desde o princípio ouvistes: que andeis nele.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> Καὶ αὕτη ἐστὶν ἡ ἀγάπη, ἵνα περιπατῶμεν κατὰ τὰς ἐντολὰς αὐτοῦ. αὕτη ἐστὶν ἡ ἐντολή, καθὼς ἠκούσατε ἀπ᾽ ἀρχῆς, ἵνα ἐν αὐτῇ περιπατῆτε.<br>",
        "🔤 <strong>Transliteração:</strong> Kai hautē estin hē agapē, hina peripatōmen kata tas entolas autou. hautē estin hē entolē, kathōs ēkousate ap' archēs, hina en autē peripatēte.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) Καὶ αὕτη ἐστὶν ἡ ἀγάπη, ἵνα περιπατῶμεν κατὰ τὰς ἐντολὰς αὐτοῦ. αὕτη ἐστὶν ἡ ἐντολή, καθὼς ἠκούσατε ἀπ᾽ ἀρχῆς, ἵνα ἐν αὐτῇ περιπατῆτε.<br>",
        "🇻🇦 <strong>Vulgata:</strong> et haec est caritas ut ambulemus secundum mandata eius hoc est mandatum sicut audistis ab initio ut in illo ambuletis<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>περιπατῶμεν</em> – 'andemos' – andemos, vivamos. <em>κατὰ</em> – 'segundo' – de acordo com. <em>ἐντολὰς</em> – 'mandamentos' – ordens, preceitos. <em>ἀπ᾽ ἀρχῆς</em> – 'princípio' – desde o início. <em>περιπατῆτε</em> – 'andeis' – andeis, viveis.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> O amor é definido como obediência aos mandamentos de Deus. Andar nos mandamentos é andar no amor. O amor não é sentimental, mas prático.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> João define o amor como obediência à vontade de Deus, expressa em mandamentos.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Andemos nos mandamentos de Deus. Isso é amor.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 7</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Porque já muitos enganadores entraram no mundo, os quais não confessam que Jesus Cristo veio em carne. Tal é o enganador e o anticristo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> Ὅτι πολλοὶ πλάνοι εἰσῆλθον εἰς τὸν κόσμον, οἱ μὴ ὁμολογοῦντες Ἰησοῦν Χριστὸν ἐρχόμενον ἐν σαρκί· οὗτός ἐστιν ὁ πλάνος καὶ ὁ ἀντίχριστος.<br>",
        "🔤 <strong>Transliteração:</strong> Hoti polloi planoi eisēlthon eis ton kosmon, hoi mē homologountes Iēsoun Christon erchomenon en sarki; houtos estin ho planos kai ho antichristos.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) Ὅτι πολλοὶ πλάνοι εἰσῆλθον εἰς τὸν κόσμον, οἱ μὴ ὁμολογοῦντες Ἰησοῦν Χριστὸν ἐρχόμενον ἐν σαρκί· οὗτός ἐστιν ὁ πλάνος καὶ ὁ ἀντίχριστος.<br>",
        "🇻🇦 <strong>Vulgata:</strong> quoniam multi seductores exierunt in mundum qui non confitentur Iesum Christum venientem in carne hic est seductor et antichristus<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>πλάνοι</em> – 'enganadores' – sedutores, enganadores. <em>εἰσῆλθον</em> – 'entraram' – entraram, vieram. <em>ὁμολογοῦντες</em> – 'confessam' – confessam, declaram. <em>ἐρχόμενον</em> – 'veio' – vindo (particípio presente). <em>πλάνος</em> – 'enganador' – sedutor, enganador. <em>ἀντίχριστος</em> – 'anticristo' – contra Cristo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A negação da encarnação é a marca dos enganadores e do anticristo. O engano doutrinário é uma realidade presente.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> João adverte que muitos enganadores negam a encarnação de Cristo, identificando-os como anticristos.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Estejamos alertas contra enganadores. A confissão da encarnação é essencial.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 8</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Olhai por vós mesmos, para que não percamos o que temos ganho, mas antes recebamos o inteiro galardão.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> Βλέπετε ἑαυτούς, ἵνα μὴ ἀπολέσωμεν ἃ εἰργασάμεθα, ἀλλὰ μισθὸν πλήρη ἀπολάβωμεν.<br>",
        "🔤 <strong>Transliteração:</strong> Blepete heautous, hina mē apolesōmen ha eirgasametha, alla misthon plērē apolabōmen.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) Βλέπετε ἑαυτούς, ἵνα μὴ ἀπολέσωμεν ἃ εἰργασάμεθα, ἀλλὰ μισθὸν πλήρη ἀπολάβωμεν.<br>",
        "🇻🇦 <strong>Vulgata:</strong> videte vosmet ipsos ne perdatis quae operati estis sed ut mercedem plenam accipiatis<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>Βλέπετε</em> – 'Olhai' – vede, cuidai. <em>ἀπολέσωμεν</em> – 'percam' – percamos, destruamos. <em>εἰργασάμεθα</em> – 'temos ganho' – trabalhamos, produzimos. <em>μισθὸν</em> – 'galardão' – recompensa, salário. <em>πλήρη</em> – 'inteiro' – completo, cheio. <em>ἀπολάβωμεν</em> – 'recebamos' – recebamos de volta.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Devemos vigiar para não perder o que já alcançamos. A recompensa plena é o objetivo. A perseverança é necessária para receber o galardão.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> João exorta à vigilância para não perder a recompensa.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Vigiemos para não perder o galardão. A perseverança traz a recompensa.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 9</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Todo aquele que prevarica, e não persevera na doutrina de Cristo, não tem a Deus. Quem persevera na doutrina de Cristo, esse tem tanto o Pai como o Filho.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> Πᾶς ὁ προάγων καὶ μὴ μένων ἐν τῇ διδαχῇ τοῦ Χριστοῦ, θεὸν οὐκ ἔχει· ὁ μένων ἐν τῇ διδαχῇ τοῦ Χριστοῦ, οὗτος καὶ τὸν πατέρα καὶ τὸν υἱὸν ἔχει.<br>",
        "🔤 <strong>Transliteração:</strong> Pas ho proagōn kai mē menōn en tē didachē tou Christou, theon ouk echei; ho menōn en tē didachē tou Christou, houtos kai ton patera kai ton huion echei.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) Πᾶς ὁ προάγων καὶ μὴ μένων ἐν τῇ διδαχῇ τοῦ Χριστοῦ, θεὸν οὐκ ἔχει· ὁ μένων ἐν τῇ διδαχῇ τοῦ Χριστοῦ, οὗτος καὶ τὸν πατέρα καὶ τὸν υἱὸν ἔχει.<br>",
        "🇻🇦 <strong>Vulgata:</strong> omnis qui praecedit et non manet in doctrina Christi Deum non habet qui manet in doctrina hic et Patrem et Filium habet<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>προάγων</em> – 'prevarica' – que vai além, que transgride. <em>μένων</em> – 'persevera' – que permanece. <em>διδαχῇ</em> – 'doutrina' – ensino, doutrina. <em>ἔχει</em> – 'tem' – possui. <em>πατέρα</em> – 'Pai' – Deus Pai. <em>υἱὸν</em> – 'Filho' – Jesus Cristo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A permanência na doutrina de Cristo é a condição para ter o Pai e o Filho. A doutrina correta é essencial para a comunhão com Deus.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> João afirma que aquele que não persevera na sã doutrina não tem Deus.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Permaneçamos na doutrina de Cristo. Isso nos dá comunhão com o Pai e o Filho.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 10</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Se alguém vem ter convosco e não traz esta doutrina, não o recebais em casa, nem tampouco o saudeis.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> Εἴ τις ἔρχεται πρὸς ὑμᾶς, καὶ ταύτην τὴν διδαχὴν οὐ φέρει, μὴ λαμβάνετε αὐτὸν εἰς οἰκίαν, καὶ χαίρειν αὐτῷ μὴ λέγετε·<br>",
        "🔤 <strong>Transliteração:</strong> Ei tis erchetai pros hymas, kai tautēn tēn didachēn ou pherei, mē lambanete auton eis oikian, kai chairein autō mē legete;<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) Εἴ τις ἔρχεται πρὸς ὑμᾶς, καὶ ταύτην τὴν διδαχὴν οὐ φέρει, μὴ λαμβάνετε αὐτὸν εἰς οἰκίαν, καὶ χαίρειν αὐτῷ μὴ λέγετε·<br>",
        "🇻🇦 <strong>Vulgata:</strong> si quis venit ad vos et hanc doctrinam non adfert nolite recipere eum in domum nec ave ei dixeritis<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>φέρει</em> – 'traz' – traz, apresenta. <em>λαμβάνετε</em> – 'recebais' – recebais, acolhais. <em>οἰκίαν</em> – 'casa' – casa, lar. <em>χαίρειν</em> – 'saudeis' – saudar, dar boas-vindas. <em>λέγετε</em> – 'diga' – digais, faleis.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A hospitalidade não deve ser estendida aos falsos mestres. Recebê-los ou saudá-los é endossar seu ensino.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> João instrui a não receber ou saudar aqueles que não trazem a sã doutrina.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Não recebamos nem saudemos falsos mestres. A separação é necessária.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 11</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Porque quem o saúda participa das suas más obras.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> ὁ γὰρ λέγων αὐτῷ χαίρειν, κοινωνεῖ τοῖς ἔργοις αὐτοῦ τοῖς πονηροῖς.<br>",
        "🔤 <strong>Transliteração:</strong> ho gar legōn autō chairein, koinōnei tois ergois autou tois ponērois.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) ὁ γὰρ λέγων αὐτῷ χαίρειν, κοινωνεῖ τοῖς ἔργοις αὐτοῦ τοῖς πονηροῖς.<br>",
        "🇻🇦 <strong>Vulgata:</strong> qui enim dicit illi ave communicat operibus eius malignis<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>λέγων</em> – 'saúda' – que diz, que fala. <em>χαίρειν</em> – 'saúde' – saudação. <em>κοινωνεῖ</em> – 'participa' – participa, compartilha. <em>ἔργοις</em> – 'obras' – ações, trabalhos. <em>πονηροῖς</em> – 'más' – más, perversas.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Saudar um falso mestre é participar de suas obras más. A cumplicidade é evitada pela separação.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> João explica que saudar um enganador é tornar-se cúmplice de suas más obras.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Não participemos das obras más dos enganadores. A separação é proteção.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 12</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Tendo muito que escrever-vos, não quis fazê-lo com papel e tinta; mas espero ir ter convosco e falar face a face, para que o nosso gozo seja completo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> Πολλὰ ἔχων ὑμῖν γράφειν, οὐκ ἐβουλήθην διὰ χάρτου καὶ μέλανος· ἀλλὰ ἐλπίζω ἐλθεῖν πρὸς ὑμᾶς, καὶ στόμα πρὸς στόμα λαλῆσαι, ἵνα ἡ χαρὰ ἡμῶν ᾖ πεπληρωμένη.<br>",
        "🔤 <strong>Transliteração:</strong> Polla echōn hymin graphein, ouk eboulēthēn dia chartou kai melanos; alla elpizō elthein pros hymas, kai stoma pros stoma lalēsai, hina hē chara hēmōn ē peplērōmenē.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) Πολλὰ ἔχων ὑμῖν γράφειν, οὐκ ἐβουλήθην διὰ χάρτου καὶ μέλανος· ἀλλὰ ἐλπίζω ἐλθεῖν πρὸς ὑμᾶς, καὶ στόμα πρὸς στόμα λαλῆσαι, ἵνα ἡ χαρὰ ἡμῶν ᾖ πεπληρωμένη.<br>",
        "🇻🇦 <strong>Vulgata:</strong> cum multa haberem vobis scribere nolui per cartam et atramentum spero enim me futurum apud vos et os ad os loqui ut gaudium vestrum plenum sit<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>ἐβουλήθην</em> – 'quis' – quis, desejei. <em>χάρτου</em> – 'papel' – papel, papiro. <em>μέλανος</em> – 'tinta' – tinta. <em>στόμα πρὸς στόμα</em> – 'face a face' – boca a boca. <em>πεπληρωμένη</em> – 'completo' – cheio, completo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> João prefere a comunhão pessoal à comunicação escrita. A presença física é mais completa. A alegria plena vem da comunhão face a face.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> João expressa seu desejo de visitar pessoalmente para uma comunhão mais plena.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Valorizemos a comunhão pessoal. Ela traz alegria completa.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 13</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Os filhos de tua irmã, a eleita, te saúdam. Amém.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> Ἀσπάζεταί σε τὰ τέκνα τῆς ἀδελφῆς σου τῆς ἐκλεκτῆς. Ἀμήν.<br>",
        "🔤 <strong>Transliteração:</strong> Aspazetai se ta tekna tēs adelphēs sou tēs eklektēs. Amēn.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) Ἀσπάζεταί σε τὰ τέκνα τῆς ἀδελφῆς σου τῆς ἐκλεκτῆς. Ἀμήν.<br>",
        "🇻🇦 <strong>Vulgata:</strong> salutant te filii sororis tuae electae amen<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>Ἀσπάζεταί</em> – 'saúdam' – saúdam, dão boas-vindas. <em>ἀδελφῆς</em> – 'irmã' – irmã (em Cristo). <em>ἐκλεκτῆς</em> – 'eleita' – escolhida. <em>Ἀμήν</em> – 'Amém' – assim seja.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A irmã eleita e seus filhos enviam saudações. A comunidade cristã é uma família espiritual. A saudação final reforça a unidade.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> João envia saudações da igreja irmã.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> A comunhão entre igrejas é importante. Saudações fortalecem os laços.<br>"
    ]
  }
};