window.LIVRO_DATA = {
  nome: "3 João",
  id: "3joao",
  testament: "NT",

  dados: {
    1: [
        "<span style='font-size: 15px;'><strong>VERSÍCULO: 1</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> O ancião ao amado Gaio, a quem amo na verdade.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> Ὁ πρεσβύτερος Γαΐῳ τῷ ἀγαπητῷ, ὃν ἐγὼ ἀγαπῶ ἐν ἀληθείᾳ.<br>",
        "🔤 <strong>Transliteração:</strong> Ho presbyteros Gaiō tō agapētō, hon egō agapō en alētheia.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) Ὁ πρεσβύτερος Γαΐῳ τῷ ἀγαπητῷ, ὃν ἐγὼ ἀγαπῶ ἐν ἀληθείᾳ.<br>",
        "🇻🇦 <strong>Vulgata:</strong> Senior Gaio carissimo quem ego diligo in veritate<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>πρεσβύτερος</em> – 'ancião' – presbítero, líder da igreja. <em>Γαΐῳ</em> – 'Gaio' – nome comum na época (Atos 19:29; 20:4; Romanos 16:23; 1 Coríntios 1:14). <em>ἀγαπητῷ</em> – 'amado' – querido, amado. <em>ἀγαπῶ</em> – 'amo' – tenho amor. <em>ἀληθείᾳ</em> – 'verdade' – verdade, realidade.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> João escreve a Gaio como ancião, usando o termo 'amado' que reflete afeição e estima. O amor na verdade é a base do relacionamento cristão. Gaio é um exemplo de fidelidade e amor.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> João se identifica como ancião e se dirige a Gaio com carinho, enfatizando o amor na verdade.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Amemos os irmãos na verdade. O amor cristão é sincero e fundamentado na verdade.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 2</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Amado, desejo que te vá bem em todas as coisas, e que tenhas saúde, assim como bem vai a tua alma.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> Ἀγαπητέ, περὶ πάντων εὔχομαί σε εὐοδοῦσθαι καὶ ὑγιαίνειν, καθὼς εὐοδοῦταί σου ἡ ψυχή.<br>",
        "🔤 <strong>Transliteração:</strong> Agapēte, peri pantōn euchomai se euodousthai kai hygiainein, kathōs euodoutai sou hē psychē.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) Ἀγαπητέ, περὶ πάντων εὔχομαί σε εὐοδοῦσθαι καὶ ὑγιαίνειν, καθὼς εὐοδοῦταί σου ἡ ψυχή.<br>",
        "🇻🇦 <strong>Vulgata:</strong> carissime de omnibus orationem facio te prosperari et valere sicut prosperatur anima tua<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>εὔχομαί</em> – 'desejo' – oro, desejo. <em>εὐοδοῦσθαι</em> – 'vá bem' – prosperar, ter sucesso. <em>ὑγιαίνειν</em> – 'tenhas saúde' – ser saudável. <em>ψυχή</em> – 'alma' – alma, vida interior.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> João ora pela prosperidade e saúde física de Gaio, assim como sua alma prospera. A saúde espiritual é a base para a saúde física. O desejo é de bem-estar integral.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> João expressa seu desejo de que Gaio seja próspero e saudável, refletindo a saúde de sua alma.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Oremos pela prosperidade e saúde dos irmãos. A saúde da alma deve se refletir em todas as áreas.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 3</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Porque muito me alegrei quando os irmãos vieram e testificaram da tua verdade, como tu andas na verdade.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> Ἐχάρην γὰρ λίαν, ἐρχομένων ἀδελφῶν καὶ μαρτυρούντων σου τῇ ἀληθείᾳ, καθὼς σὺ ἐν ἀληθείᾳ περιπατεῖς.<br>",
        "🔤 <strong>Transliteração:</strong> Echarēn gar lian, erchomenōn adelphōn kai martyrountōn sou tē alētheia, kathōs sy en alētheia peripateis.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) Ἐχάρην γὰρ λίαν, ἐρχομένων ἀδελφῶν καὶ μαρτυρούντων σου τῇ ἀληθείᾳ, καθὼς σὺ ἐν ἀληθείᾳ περιπατεῖς.<br>",
        "🇻🇦 <strong>Vulgata:</strong> gavisus sum valde venientibus fratribus et testimonium perhibentibus veritati tuae sicut tu in veritate ambulas<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>Ἐχάρην</em> – 'alegrei' – alegrei-me, regozijei. <em>λίαν</em> – 'muito' – grandemente. <em>μαρτυρούντων</em> – 'testificaram' – testemunhando. <em>περιπατεῖς</em> – 'andas' – vives, andas.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A alegria de João vem do testemunho da fidelidade de Gaio à verdade. Andar na verdade é viver de acordo com o evangelho. O testemunho dos irmãos confirma a caminhada de Gaio.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> João expressa grande alegria ao ouvir o testemunho sobre a fidelidade de Gaio à verdade.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Andemos na verdade para trazer alegria aos líderes e irmãos.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 4</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Não tenho maior gozo do que este: o ouvir que os meus filhos andam na verdade.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> μειζοτέραν τούτων οὐκ ἔχω χάριν, ἵνα ἀκούω τὰ ἐμὰ τέκνα ἐν ἀληθείᾳ περιπατοῦντα.<br>",
        "🔤 <strong>Transliteração:</strong> meizoteran toutōn ouk echō charin, hina akouō ta ema tekna en alētheia peripatounta.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) μειζοτέραν τούτων οὐκ ἔχω χάριν, ἵνα ἀκούω τὰ ἐμὰ τέκνα ἐν ἀληθείᾳ περιπατοῦντα.<br>",
        "🇻🇦 <strong>Vulgata:</strong> maiorem horum non habeo gratiam quam ut audiam filios meos in veritate ambulare<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>μειζοτέραν</em> – 'maior' – maior (comparativo). <em>χάριν</em> – 'gozo' – graça, alegria. <em>ἀκούω</em> – 'ouvir' – ouvir, escutar. <em>τέκνα</em> – 'filhos' – filhos (espirituais). <em>περιπατοῦντα</em> – 'andam' – que andam, que vivem.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A maior alegria de um líder espiritual é ver seus filhos espirituais andando na verdade. A caminhada na verdade é o maior testemunho.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> João declara que sua maior alegria é ouvir que seus filhos espirituais andam na verdade.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Busquemos andar na verdade para alegrar aqueles que nos guiam na fé.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 5</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Amado, procedes fielmente em tudo o que fazes para com os irmãos, e para com os estranhos,<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> Ἀγαπητέ, πιστὸν ποιεῖς ὃ ἐὰν ἐργάσῃ εἰς τοὺς ἀδελφοὺς καὶ εἰς τοὺς ξένους,<br>",
        "🔤 <strong>Transliteração:</strong> Agapēte, piston poieis ho ean ergasē eis tous adelphous kai eis tous xenous,<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) Ἀγαπητέ, πιστὸν ποιεῖς ὃ ἐὰν ἐργάσῃ εἰς τοὺς ἀδελφοὺς καὶ εἰς τοὺς ξένους,<br>",
        "🇻🇦 <strong>Vulgata:</strong> carissime fideliter facis quicquid operaris in fratres et in peregrinos<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>πιστὸν</em> – 'fielmente' – fielmente, de forma confiável. <em>ποιεῖς</em> – 'procedes' – fazes, ages. <em>ἐργάσῃ</em> – 'fazes' – fazes, trabalhas. <em>ξένους</em> – 'estranhos' – estrangeiros, viajantes.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Gaio age com fidelidade para com os irmãos e também para com os estranhos (missionários viajantes). A hospitalidade é uma obra fiel.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> João elogia a fidelidade de Gaio em suas obras para com os irmãos e estranhos.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Sejamos fiéis em nossas obras, especialmente na hospitalidade aos irmãos e missionários.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 6</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Os quais diante da igreja testificaram do teu amor; aos quais, se encaminhares como é digno para com Deus, bem farás.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> οἳ ἐμαρτύρησάν σου τῇ ἀγάπῃ ἐνώπιον ἐκκλησίας· οὓς καλῶς ποιήσεις προπέμψας ἀξίως τοῦ θεοῦ·<br>",
        "🔤 <strong>Transliteração:</strong> hoi emartyrēsan sou tē agapē enōpion ekklēsias; hous kalōs poiēseis propempsas axiōs tou theou;<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) οἳ ἐμαρτύρησάν σου τῇ ἀγάπῃ ἐνώπιον ἐκκλησίας· οὓς καλῶς ποιήσεις προπέμψας ἀξίως τοῦ θεοῦ·<br>",
        "🇻🇦 <strong>Vulgata:</strong> qui testimonium reddiderunt caritati tuae in conspectu ecclesiae quos bene facies deducens digne Deo<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>ἐμαρτύρησάν</em> – 'testificaram' – testemunharam. <em>ἐνώπιον</em> – 'diante' – diante, na presença de. <em>προπέμψας</em> – 'encaminhares' – tendo encaminhado, ajudado na viagem. <em>ἀξίως</em> – 'digno' – de maneira digna.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Os irmãos viajantes testemunharam o amor de Gaio diante da igreja. Gaio é encorajado a continuar apoiando-os de maneira digna de Deus.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> João recomenda que Gaio continue a apoiar os missionários de forma digna de Deus.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Apoiemos os obreiros de Deus de maneira digna. Isso é uma boa obra.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 7</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Porque pelo Seu Nome saíram, nada tomando dos gentios.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> ὑπὲρ γὰρ τοῦ ὀνόματος ἐξῆλθον, μηδὲν λαμβάνοντες ἀπὸ τῶν ἐθνικῶν.<br>",
        "🔤 <strong>Transliteração:</strong> hyper gar tou onomatos exēlthon, mēden lambanontes apo tōn ethnikōn.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) ὑπὲρ γὰρ τοῦ ὀνόματος ἐξῆλθον, μηδὲν λαμβάνοντες ἀπὸ τῶν ἐθνικῶν.<br>",
        "🇻🇦 <strong>Vulgata:</strong> pro nomine enim profecti sunt nihil accipientes a gentibus<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>ὑπὲρ</em> – 'por' – por causa de, em favor de. <em>ὀνόματος</em> – 'Nome' – Nome (de Cristo). <em>ἐξῆλθον</em> – 'saíram' – saíram, partiram. <em>λαμβάνοντες</em> – 'tomando' – recebendo. <em>ἐθνικῶν</em> – 'gentios' – pagãos, não-cristãos.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Os missionários saíram pelo Nome de Cristo, sem depender dos gentios (não-crentes). Sua motivação é o Nome, não o ganho material.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> João explica que os missionários saíram por amor ao Nome de Cristo, sem aceitar apoio dos incrédulos.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Apoiemos missionários que trabalham pelo Nome de Cristo. Eles não devem depender do mundo.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 8</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Portanto, aos tais devemos receber, para que sejamos cooperadores da verdade.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> ἡμεῖς οὖν ὀφείλομεν ὑπολαμβάνειν τοὺς τοιούτους, ἵνα συνεργοὶ γινώμεθα τῇ ἀληθείᾳ.<br>",
        "🔤 <strong>Transliteração:</strong> hēmeis oun opheilomen hypolambanein tous toioutous, hina synergoi ginōmetha tē alētheia.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) ἡμεῖς οὖν ὀφείλομεν ὑπολαμβάνειν τοὺς τοιούτους, ἵνα συνεργοὶ γινώμεθα τῇ ἀληθείᾳ.<br>",
        "🇻🇦 <strong>Vulgata:</strong> nos ergo debemus suscipere huiusmodi ut cooperatores simus veritatis<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>ὀφείλομεν</em> – 'devemos' – estamos em débito, devemos. <em>ὑπολαμβάνειν</em> – 'receber' – receber, acolher. <em>συνεργοὶ</em> – 'cooperadores' – colaboradores, cooperadores. <em>γινώμεθα</em> – 'sejamos' – tornemo-nos, sejamos.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Acolher os missionários é cooperar com a verdade. A hospitalidade é uma forma de parceria no evangelho.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> João ensina que devemos receber tais missionários, tornando-nos cooperadores da verdade.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Recebamos os obreiros de Deus. Isso nos torna cooperadores da verdade.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 9</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Tenho escrito à igreja; mas Diótrefes, que gosta de ter entre eles a primazia, não nos recebe.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> Ἔγραψα τῇ ἐκκλησίᾳ· ἀλλ᾽ ὁ φιλοπρωτεύων αὐτῶν Διοτρεφὴς οὐκ ἐπιδέχεται ἡμᾶς.<br>",
        "🔤 <strong>Transliteração:</strong> Egrapsa tē ekklēsia; all' ho philoprōteuōn autōn Diotrephēs ouk epidechetai hēmas.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) Ἔγραψα τῇ ἐκκλησίᾳ· ἀλλ᾽ ὁ φιλοπρωτεύων αὐτῶν Διοτρεφὴς οὐκ ἐπιδέχεται ἡμᾶς.<br>",
        "🇻🇦 <strong>Vulgata:</strong> scripsissem forsitan ecclesiae sed is qui amat primatum gerere in eis Diotrefes non recipit nos<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>φιλοπρωτεύων</em> – 'gosta de ter a primazia' – que ama a preeminência, que deseja ser o primeiro. <em>Διοτρεφὴς</em> – 'Diótrefes' – nome próprio, 'criado por Zeus'. <em>οὐκ ἐπιδέχεται</em> – 'não recebe' – não acolhe, não admite.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Diótrefes é um exemplo de orgulho e ambição na igreja. Ele rejeita a autoridade de João e não acolhe os missionários. O amor pela primazia é um obstáculo à comunhão.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> João menciona Diótrefes como um opositor que não o recebe, por amor à preeminência.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Evitemos o orgulho e a busca por primazia. A humildade é essencial na liderança.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 10</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Pelo que, se eu for, trarei à memória as obras que ele faz, proferindo contra nós palavras maliciosas; e, não contente com isto, não recebe os irmãos, e impede os que querem recebê-los, e os lança fora da igreja.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> διὰ τοῦτο, ἐὰν ἔλθω, ὑπομνήσω αὐτοῦ τὰ ἔργα ἃ ποιεῖ, λόγοις πονηροῖς φλυαρῶν ἡμᾶς· καὶ μὴ ἀρκούμενος ἐπὶ τούτοις, οὔτε αὐτὸς ἐπιδέχεται τοὺς ἀδελφούς, καὶ τοὺς βουλομένους κωλύει, καὶ ἐκ τῆς ἐκκλησίας ἐκβάλλει.<br>",
        "🔤 <strong>Transliteração:</strong> dia touto, ean elthō, hypomnēsō autou ta erga ha poiei, logois ponērois phlyarōn hēmas; kai mē arkoumenos epi toutois, oute autos epidechetai tous adelphous, kai tous boulomenous kōlyei, kai ek tēs ekklēsias ekballei.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) διὰ τοῦτο, ἐὰν ἔλθω, ὑπομνήσω αὐτοῦ τὰ ἔργα ἃ ποιεῖ, λόγοις πονηροῖς φλυαρῶν ἡμᾶς· καὶ μὴ ἀρκούμενος ἐπὶ τούτοις, οὔτε αὐτὸς ἐπιδέχεται τοὺς ἀδελφούς, καὶ τοὺς βουλομένους κωλύει, καὶ ἐκ τῆς ἐκκλησίας ἐκβάλλει.<br>",
        "🇻🇦 <strong>Vulgata:</strong> propter hoc si venero commonebo eius opera quae facit verbis malignis garriens in nos et quasi non ei sufficiunt ista nec ipse suscipit fratres et eos qui suscipiunt prohibet et de ecclesia eicit<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>ὑπομνήσω</em> – 'trarei à memória' – farei lembrar, recordarei. <em>φλυαρῶν</em> – 'proferindo' – falando tolices, difamando. <em>ἀρκούμενος</em> – 'contente' – satisfeito, contente. <em>κωλύει</em> – 'impede' – impede, proíbe. <em>ἐκβάλλει</em> – 'lança fora' – expulsa, joga fora.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Diótrefes não apenas recusa a hospitalidade, mas também difama e excomunga aqueles que a praticam. Suas obras são más e prejudicam a igreja.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> João descreve as más obras de Diótrefes: difamação, rejeição de irmãos e excomunhão.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Não imitemos as más obras de Diótrefes. A liderança deve servir, não dominar.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 11</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Amado, não sigas o mal, mas o bem. Quem faz o bem é de Deus; mas quem faz o mal não tem visto a Deus.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> Ἀγαπητέ, μὴ μιμοῦ τὸ κακόν, ἀλλὰ τὸ ἀγαθόν. ὁ ἀγαθοποιῶν ἐκ τοῦ θεοῦ ἐστιν· ὁ δὲ κακοποιῶν οὐχ ἑώρακεν τὸν θεόν.<br>",
        "🔤 <strong>Transliteração:</strong> Agapēte, mē mimou to kakon, alla to agathon. ho agathopoiōn ek tou theou estin; ho de kakopoiōn ouch heōraken ton theon.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) Ἀγαπητέ, μὴ μιμοῦ τὸ κακόν, ἀλλὰ τὸ ἀγαθόν. ὁ ἀγαθοποιῶν ἐκ τοῦ θεοῦ ἐστιν· ὁ δὲ κακοποιῶν οὐχ ἑώρακεν τὸν θεόν.<br>",
        "🇻🇦 <strong>Vulgata:</strong> carissime noli imitari malum sed quod bonum est qui benefacit ex Deo est qui autem malefacit non vidit Deum<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>μιμοῦ</em> – 'sigas' – imites, sigas o exemplo. <em>ἀγαθοποιῶν</em> – 'faz o bem' – que pratica o bem. <em>κακοποιῶν</em> – 'faz o mal' – que pratica o mal. <em>οὐχ ἑώρακεν</em> – 'não tem visto' – não viu, não conhece.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A exortação é clara: imitar o bem, não o mal. Quem faz o bem é de Deus; quem faz o mal não conhece a Deus. A prática do bem é a evidência do conhecimento de Deus.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> João exorta Gaio a não imitar o mal, mas o bem, baseado na natureza de Deus.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Sigamos o bem, não o mal. A prática do bem nos identifica como filhos de Deus.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 12</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Todos dão testemunho de Demétrio, até a mesma verdade; e também nós testemunhamos; e vós bem sabeis que o nosso testemunho é verdadeiro.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> Δημητρίῳ μεμαρτύρηται ὑπὸ πάντων, καὶ ὑπὸ αὐτῆς τῆς ἀληθείας· καὶ ἡμεῖς δὲ μαρτυροῦμεν, καὶ οἶδας ὅτι ἡ μαρτυρία ἡμῶν ἀληθής ἐστιν.<br>",
        "🔤 <strong>Transliteração:</strong> Dēmētriō memartyrētai hypo pantōn, kai hypo autēs tēs alētheias; kai hēmeis de martyroumen, kai oidas hoti hē martyria hēmōn alēthēs estin.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) Δημητρίῳ μεμαρτύρηται ὑπὸ πάντων, καὶ ὑπὸ αὐτῆς τῆς ἀληθείας· καὶ ἡμεῖς δὲ μαρτυροῦμεν, καὶ οἶδας ὅτι ἡ μαρτυρία ἡμῶν ἀληθής ἐστιν.<br>",
        "🇻🇦 <strong>Vulgata:</strong> Demetrio testimonium redditur ab omnibus et ab ipsa veritate et nos autem testimonium perhibemus et nosti quoniam testimonium nostrum verum est<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>Δημητρίῳ</em> – 'Demétrio' – nome próprio, 'pertencente a Deméter'. <em>μεμαρτύρηται</em> – 'dão testemunho' – tem sido testemunhado. <em>ὑπὸ</em> – 'por' – por, de parte de. <em>αὐτῆς</em> – 'mesma' – a própria (ênfase). <em>οἶδας</em> – 'sabes' – conheces, sabes.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Demétrio é um exemplo de boa reputação. Seu testemunho vem de todos e da própria verdade. João confirma esse testemunho.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> João recomenda Demétrio, cujo bom testemunho é confirmado por todos e pela verdade.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Busquemos ter um bom testemunho diante de todos. A verdade confirma o caráter.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 13</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Tinha muito que escrever, mas não quero escrever-te com tinta e pena.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> Πολλὰ εἶχον γράφειν, ἀλλ᾽ οὐ θέλω διὰ μέλανος καὶ καλάμου σοι γράφειν·<br>",
        "🔤 <strong>Transliteração:</strong> Polla eichon graphein, all' ou thelō dia melanos kai kalamou soi graphein;<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) Πολλὰ εἶχον γράφειν, ἀλλ᾽ οὐ θέλω διὰ μέλανος καὶ καλάμου σοι γράφειν·<br>",
        "🇻🇦 <strong>Vulgata:</strong> multa habui scribere sed nolui per atramentum et calamum scribere tibi<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>εἶχον</em> – 'Tinha' – tinha, possuía. <em>θέλω</em> – 'quero' – desejo, quero. <em>μέλανος</em> – 'tinta' – tinta. <em>καλάμου</em> – 'pena' – cálamo, caneta de junco.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> João prefere a comunicação pessoal à escrita. A comunhão face a face é mais valiosa que a correspondência.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> João expressa seu desejo de evitar a escrita prolongada, preferindo a visita pessoal.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Valorizemos a comunhão pessoal. A comunicação escrita tem limites.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 14</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Espero, porém, ver-te brevemente, e falaremos face a face. Paz seja contigo. Os amigos te saúdam. Saúda os amigos por nome.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> ἐλπίζω δὲ εὐθέως σε ἰδεῖν, καὶ στόμα πρὸς στόμα λαλήσομεν. εἰρήνη σοι. ἀσπάζονταί σε οἱ φίλοι. ἀσπάζου τοὺς φίλους κατ᾽ ὄνομα.<br>",
        "🔤 <strong>Transliteração:</strong> elpizō de eutheōs se idein, kai stoma pros stoma lalēsomen. eirēnē soi. aspazontai se hoi philoi. aspazou tous philous kat' onoma.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) ἐλπίζω δὲ εὐθέως σε ἰδεῖν, καὶ στόμα πρὸς στόμα λαλήσομεν. εἰρήνη σοι. ἀσπάζονταί σε οἱ φίλοι. ἀσπάζου τοὺς φίλους κατ᾽ ὄνομα.<br>",
        "🇻🇦 <strong>Vulgata:</strong> spero autem protinus te videre et os ad os loquemur pax tibi salutant te amici saluta amicos nominatim<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>ἐλπίζω</em> – 'Espero' – espero, confio. <em>εὐθέως</em> – 'brevemente' – imediatamente, em breve. <em>στόμα πρὸς στόμα</em> – 'face a face' – boca a boca. <em>εἰρήνη</em> – 'Paz' – paz, harmonia. <em>ἀσπάζονταί</em> – 'saúdam' – saúdam. <em>ἀσπάζου</em> – 'Saúda' – saúda, cumprimenta. <em>κατ᾽ ὄνομα</em> – 'por nome' – nominalmente.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> João espera uma visita em breve para uma comunhão face a face. A paz é a bênção final. As saudações são pessoais e individualizadas.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> João conclui com a expectativa da visita, a bênção da paz e as saudações.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Cultivemos a comunhão pessoal. A paz de Cristo seja conosco. Saudações pessoais fortalecem os laços.<br>"
    ]
  }
};