window.LIVRO_DATA = {
    nome: "Ageu",
    id: "ageu",
    testament: "AT",
    
    dados: {
        1: [
            
            "<span style='font-size: 15px;'><strong>VERSÍCULO: 1</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> No segundo ano do rei Dario, no sexto mês, no primeiro dia do mês, veio a palavra do Senhor, por intermédio do profeta Ageu, a Zorobabel, filho de Sealtiel, governador de Judá, e a Josué, filho de Jozadaque, o sumo sacerdote, dizendo:<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> בִּשְׁנַת שְׁתַּיִם לְדָרְיָוֶשׁ הַמֶּלֶךְ בַּחֹדֶשׁ הַשִּׁשִּׁי בְּיוֹם אֶחָד לַחֹדֶשׁ הָיָה דְבַר־יְהוָה בְּיַד־חַגַּי הַנָּבִיא אֶל־זְרֻבָּבֶל בֶּן־שַׁלְתִּיאֵל פַּחַת יְהוּדָה וְאֶל־יְהוֹשֻׁעַ בֶּן־יְהוֹצָדָק הַכֹּהֵן הַגָּדוֹל לֵאמֹר<br>",
            "🔤 <strong>Transliteração:</strong> Bishnat shtayim l'Daryavesh hamelech bachodesh hashishi b'yom echad lachodesh hayah d'var-YHWH b'yad-Chagai hanavi el-Z'rubavel ben-Shalti'el pachat Yehudah v'el-Yehoshua ben-Y'hotzadak hakohan hagadol lemor<br>",
            "🇬🇷 <strong>Septuaginta:</strong> Ἐν ἔτει δευτέρῳ ἐπὶ Δαρείου τοῦ βασιλέως, ἐν μηνὶ ἕκτῳ, μιᾷ τοῦ μηνός, ἐγένετο λόγος κυρίου ἐν χειρὶ Ἀγγαίου τοῦ προφήτου λέγων· εἶπον δὴ πρὸς Ζοροβάβελ τὸν τοῦ Σαλαθιὴλ ἐκ φυλῆς Ἰούδα, καὶ πρὸς Ἰησοῦν τὸν τοῦ Ἰωσεδὲκ τὸν ἱερέα τὸν μέγαν, λέγων<br>",
            "🇻🇦 <strong>Vulgata:</strong> In anno secundo Darii regis, in mense sexto, in die una mensis, factum est verbum Domini in manu Aggaei prophetae ad Zorobabel filium Salathiel ducem Iudae, et ad Iesum filium Iosedec sacerdotem magnum, dicens:<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>בִּשְׁנַת שְׁתַּיִם</em> – 'No segundo ano' – no segundo ano do reinado. <em>חַגַּי</em> – 'Ageu' – significa 'festivo' ou 'minha festa'. <em>זְרֻבָּבֶל</em> – 'Zorobabel' – significa 'semente de Babilônia'. <em>יְהוֹשֻׁעַ</em> – 'Josué' – significa 'o Senhor salva'.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Ageu profetiza no segundo ano de Dario, um período de restauração. Zorobabel, o governador, e Josué, o sumo sacerdote, representam a liderança civil e espiritual. Cristo, o Sumo Sacerdote e Rei, é a liderança perfeita que estabelece a Igreja (Hebreus 4:14-15).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: Ageu profetizou no segundo ano de Dario. Calvino: A liderança de Zorobabel e Josué é crucial. Crisóstomo: Cristo é o Rei e Sumo Sacerdote.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Deus levanta líderes para Sua obra. Cristo é o líder supremo.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 2</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Assim fala o Senhor dos Exércitos: Este povo diz: Não chegou ainda o tempo, o tempo de se edificar a casa do Senhor.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> כֹּה אָמַר יְהוָה צְבָאוֹת לֵאמֹר הָעָם הַזֶּה אָמְרוּ לֹא עֶת־בֹּא עֶת־בֵּית יְהוָה לְהִבָּנוֹת<br>",
            "🔤 <strong>Transliteração:</strong> Koh amar YHWH tz'va'ot lemor ha'am hazeh amru lo et-bo et-beit YHWH l'hibanot<br>",
            "🇬🇷 <strong>Septuaginta:</strong> τάδε λέγει κύριος παντοκράτωρ· ὁ λαὸς οὗτος λέγουσιν· οὐκ ἦλθεν ὁ καιρὸς τοῦ οἰκοδομῆσαι τὸν οἶκον κυρίου<br>",
            "🇻🇦 <strong>Vulgata:</strong> Haec ait Dominus exercituum, dicens: Populus iste dicit: Nondum venit tempus domus Domini aedificandae.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>צְבָאוֹת</em> – 'dos Exércitos' – Senhor dos Exércitos. <em>לֹא עֶת־בֹּא</em> – 'não chegou ainda o tempo' – ainda não é o tempo. <em>לְהִבָּנוֹת</em> – 'edificar' – para ser construída.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> O povo desculpava-se dizendo que o tempo não havia chegado para reconstruir o templo. A prioridade errada revela o coração indiferente. Cristo, o templo vivo (João 2:19-21), nos chama a priorizar o reino de Deus.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: O povo priorizou suas próprias casas. Calvino: A desculpa do povo revela negligência. Crisóstomo: Cristo é o templo verdadeiro.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Não procrastinemos a obra de Deus. Cristo deve ser a nossa prioridade.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 3</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Veio, pois, a palavra do Senhor, por intermédio do profeta Ageu, dizendo:<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> וַיְהִי דְּבַר־יְהוָה בְּיַד־חַגַּי הַנָּבִיא לֵאמֹר<br>",
            "🔤 <strong>Transliteração:</strong> Vayehi d'var-YHWH b'yad-Chagai hanavi lemor<br>",
            "🇬🇷 <strong>Septuaginta:</strong> καὶ ἐγένετο λόγος κυρίου ἐν χειρὶ Ἀγγαίου τοῦ προφήτου λέγων<br>",
            "🇻🇦 <strong>Vulgata:</strong> Et factum est verbum Domini in manu Aggaei prophetae, dicens:<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>וַיְהִי</em> – 'Veio' – aconteceu. <em>בְּיַד</em> – 'por intermédio' – pela mão, por meio de. <em>לֵאמֹר</em> – 'dizendo' – para dizer, dizendo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A palavra do Senhor veio novamente a Ageu. Deus não desiste de Seu povo. Cristo, a Palavra viva, é a mensagem de Deus para a humanidade (Hebreus 1:1-2).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: Deus repete a mensagem por meio de Ageu. Calvino: A palavra de Deus é persistente. Crisóstomo: Cristo é a Palavra viva.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Deus continua falando conosco. Estejamos atentos à Sua Palavra.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 4</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Acaso é tempo de habitardes nas vossas casas forradas, enquanto esta casa fica deserta?<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> הַעֵת לָכֶם אַתֶּם לָשֶׁבֶת בְּבָתֵּיכֶם סְפוּנִים וְהַבַּיִת הַזֶּה חָרֵב<br>",
            "🔤 <strong>Transliteração:</strong> Ha'et lachem atem lashevet b'vateichem s'funim v'habayit hazeh charev<br>",
            "🇬🇷 <strong>Septuaginta:</strong> μὴ καιρὸς ὑμῖν τοῦ οἰκεῖν ἐν οἴκοις ὑμῶν κοιλοστάθμοις, καὶ ὁ οἶκος οὗτος ἠρημώθη;<br>",
            "🇻🇦 <strong>Vulgata:</strong> Numquid tempus vobis est, ut habitetis in domibus laqueatis, et domus ista deserta?<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>הַעֵת</em> – 'Acaso é tempo' – é tempo? <em>בְּבָתֵּיכֶם סְפוּנִים</em> – 'vossas casas forradas' – casas revestidas, com teto. <em>חָרֵב</em> – 'deserta' – em ruínas, deserta.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A pergunta retórica de Deus expõe a hipocrisia do povo: eles vivem em conforto enquanto a casa de Deus está em ruínas. Cristo, o Rei, nos chama a priorizar a Sua casa (Mateus 6:33).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: O povo é repreendido por priorizar suas casas. Calvino: A negligência para com a casa de Deus é pecado. Crisóstomo: Cristo nos chama a priorizar o reino.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Não negligenciemos a obra de Deus. A prioridade deve ser o reino de Deus.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 5</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Ora, pois, assim diz o Senhor dos Exércitos: Considerai os vossos caminhos.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> וְעַתָּה כֹּה אָמַר יְהוָה צְבָאוֹת שִׂימוּ לְבַבְכֶם עַל־דַּרְכֵיכֶם<br>",
            "🔤 <strong>Transliteração:</strong> V'atah koh amar YHWH tz'va'ot simu l'vavchem al-darkeichem<br>",
            "🇬🇷 <strong>Septuaginta:</strong> καὶ νῦν τάδε λέγει κύριος παντοκράτωρ· τάξατε δὴ τὰς καρδίας ὑμῶν εἰς τὰς ὁδοὺς ὑμῶν<br>",
            "🇻🇦 <strong>Vulgata:</strong> Et nunc haec dicit Dominus exercituum: Ponite corda vestra super vias vestras.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>שִׂימוּ לְבַבְכֶם</em> – 'Considerai' – ponde o coração, considerai. <em>עַל־דַּרְכֵיכֶם</em> – 'vossos caminhos' – vossos caminhos, vossas ações.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> O chamado para considerar os caminhos é um convite ao exame de consciência e ao arrependimento. Cristo, o caminho, a verdade e a vida (João 14:6), é a direção que devemos seguir.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: Deus convida o povo a refletir. Calvino: O autoexame é necessário. Crisóstomo: Cristo é o caminho.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Examinemos nossos caminhos à luz de Cristo. Arrependamo-nos e sigamos a Ele.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 6</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Tendes semeado muito, e recolhido pouco; comeis, mas não vos fartais; bebeis, mas não vos saciais; vestis-vos, mas não vos aqueceis; e o que recebe salário, recebe-o para o pôr num saco roto.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> זְרַעְתֶּם הַרְבֵּה וְהָבֵא מְעָט אָכוֹל וְאֵין־לְשָׂבְעָה שָׁתוֹ וְאֵין־לְשָׁכְרָה לָבוֹשׁ וְאֵין־לְחֹם לוֹ וְהַמִּשְׂתַּכֵּר מִשְׂתַּכֵּר אֶל־צְרוֹר נָקוּב<br>",
            "🔤 <strong>Transliteração:</strong> Z'ra'tem harbeh v'have me'at achol v'ein-l'sov'ah shto v'ein-l'shoch'rah lavosh v'ein-l'chom lo v'hamistaker mistaker el-tz'ror nakuv<br>",
            "🇬🇷 <strong>Septuaginta:</strong> ἐσπείρατε πολλὰ καὶ εἰσηνέγκατε ὀλίγα· ἐφάγετε καὶ οὐκ εἰς πλησμονήν, ἐπίετε καὶ οὐκ εἰς μέθην, περιεβάλεσθε καὶ οὐκ ἐθερμάνθητε ἐν αὐτοῖς, καὶ ὁ ἐργαζόμενος ἐργάζεται εἰς κόλπον τετρημένον<br>",
            "🇻🇦 <strong>Vulgata:</strong> Seminastis multum, et intulistis parum; comedistis, et non estis saturati; bibistis, et non estis inebriati; operuistis vos, et non estis calefacti; et qui mercedes congregavit, misit eas in sacculum pertusum.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>זְרַעְתֶּם הַרְבֵּה</em> – 'Tendes semeado muito' – semearam muito. <em>וְהָבֵא מְעָט</em> – 'recolhido pouco' – trouxeram pouco. <em>צְרוֹר נָקוּב</em> – 'saco roto' – bolsa furada.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> O povo experimentava frustração em todas as áreas: colheita, comida, bebida, vestimenta e salário. As bênçãos de Deus são retidas quando a prioridade está errada. Cristo, que é a verdadeira provisão, nos ensina a buscar primeiro o reino de Deus (Mateus 6:33).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: A maldição de Deus sobre a colheita. Calvino: A negligência para com Deus traz frustração. Crisóstomo: Cristo é a provisão verdadeira.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Quando priorizamos o reino de Deus, Ele provê. Cristo é a nossa provisão.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 7</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Assim diz o Senhor dos Exércitos: Considerai os vossos caminhos.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> כֹּה אָמַר יְהוָה צְבָאוֹת שִׂימוּ לְבַבְכֶם עַל־דַּרְכֵיכֶם<br>",
            "🔤 <strong>Transliteração:</strong> Koh amar YHWH tz'va'ot simu l'vavchem al-darkeichem<br>",
            "🇬🇷 <strong>Septuaginta:</strong> τάδε λέγει κύριος παντοκράτωρ· τάξατε δὴ τὰς καρδίας ὑμῶν εἰς τὰς ὁδοὺς ὑμῶν<br>",
            "🇻🇦 <strong>Vulgata:</strong> Haec dicit Dominus exercituum: Ponite corda vestra super vias vestras.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>שִׂימוּ לְבַבְכֶם</em> – 'Considerai' – ponde o coração, considerai. <em>עַל־דַּרְכֵיכֶם</em> – 'vossos caminhos' – vossos caminhos.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A repetição do versículo 5 enfatiza a importância do exame de consciência. Deus deseja que Seu povo reflita e mude. Cristo nos chama ao arrependimento e à fé (Marcos 1:15).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: A repetição reforça a mensagem. Calvino: O autoexame é essencial. Crisóstomo: Cristo nos chama ao arrependimento.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Examinemos constantemente nossos caminhos. Cristo nos guia no caminho certo.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 8</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Subi ao monte, e trazei madeira, e edificai a casa; e dela me agradarei, e serei glorificado, diz o Senhor.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> עֲלוּ הָהָר וַהֲבֵאתֶם עֵץ וּבְנוּ הַבָּיִת וְאֶרְצֶה־בּוֹ וְאֶכָּבְדָה אָמַר יְהוָה<br>",
            "🔤 <strong>Transliteração:</strong> Alu hahar v'have'tem etz u'vnu habayit v'ertzeh-vo v'ekav'dah amar YHWH<br>",
            "🇬🇷 <strong>Septuaginta:</strong> ἀνάβητε εἰς τὸ ὄρος καὶ κόψατε ξύλα καὶ οἰκοδομήσατε τὸν οἶκον, καὶ εὐδοκήσω αὐτῷ καὶ δοξασθήσομαι, εἶπε κύριος<br>",
            "🇻🇦 <strong>Vulgata:</strong> Ascendite in montem, portate ligna, et aedificate domum, et acceptabilis mihi erit, et glorificabor, dicit Dominus.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>עֲלוּ</em> – 'Subi' – subi, subam. <em>וַהֲבֵאתֶם</em> – 'trazei' – trazei, tragam. <em>וְאֶרְצֶה</em> – 'me agradarei' – terei prazer, aceitarei.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Deus ordena a reconstrução do templo, prometendo agradar-se e glorificar-Se. O templo prefigura Cristo, o verdadeiro templo de Deus (João 2:19-21), no qual Deus se agrada e é glorificado.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: A obediência na construção do templo agrada a Deus. Calvino: Deus é glorificado na adoração. Crisóstomo: Cristo é o templo glorioso.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Construamos a casa de Deus (a Igreja) com dedicação. Cristo é glorificado em Sua Igreja.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 9</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Esperastes o muito, mas eis que veio a ser pouco; e quando o trouxestes para casa, eu o dissipei com um sopro. Por que causa? diz o Senhor dos Exércitos. Por causa da minha casa, que está deserta, enquanto cada um de vós corre à sua própria casa.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> פָּנֹה אֶל־הַרְבֵּה וְהִנֵּה לִמְעָט וַהֲבֵאתֶם הַבַּיִת וְנָפַחְתִּי בוֹ יַעַן מֶה נְאֻם יְהוָה צְבָאוֹת יַעַן בֵּיתִי אֲשֶׁר־הוּא חָרֵב וְאַתֶּם רָצִים אִישׁ לְבֵיתוֹ<br>",
            "🔤 <strong>Transliteração:</strong> Panoh el-harbeh v'hineh lim'at va've'tem habayit v'nafachti vo ya'an meh n'um YHWH tz'va'ot ya'an beiti asher-hu charev v'atem ratzim ish l'veito<br>",
            "🇬🇷 <strong>Septuaginta:</strong> εἰσβλέψαντες εἰς πολλὰ καὶ ἰδοὺ ὀλίγα· καὶ εἰσηνέχθη εἰς τὸν οἶκον, καὶ ἐξεφύσησα αὐτά· διὰ τοῦτο τάδε λέγει κύριος παντοκράτωρ, ἀνθ᾽ ὧν ὁ οἶκός μου ἐστὶν ἔρημος, ὑμεῖς δὲ τρέχετε ἕκαστος εἰς τὸν οἶκον ἑαυτοῦ<br>",
            "🇻🇦 <strong>Vulgata:</strong> Respexistis ad multum, et ecce factum est parum; et intulistis in domum, et exsufflavi illud. Quam ob causam? dicit Dominus exercituum: Quia domus mea deserta est, et vos festinatis unusquisque in domum suam.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>פָּנֹה</em> – 'Esperastes' – olhardes, voltardes. <em>וְנָפַחְתִּי</em> – 'dissipei' – soprei, assoprei. <em>רָצִים</em> – 'corre' – correis, apressais.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A razão da falta de bênção é a negligência para com a casa de Deus. Enquanto o povo corria para suas próprias casas, a casa de Deus estava deserta. Cristo, o Senhor da casa, nos chama a priorizar a Sua obra (Mateus 6:33).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: A falta de bênção é consequência da negligência. Calvino: A prioridade errada traz juízo. Crisóstomo: Cristo nos chama a priorizar o reino.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Não corramos apenas para nossas próprias casas. A casa de Deus deve ser nossa prioridade.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 10</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Portanto, por causa de vós os céus retêm o orvalho, e a terra retém os seus frutos.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> עַל־כֵּן עֲלֵיכֶם כָּלְאוּ שָׁמַיִם מִטָּל וְהָאָרֶץ כָּלְאָה יְבוּלָהּ<br>",
            "🔤 <strong>Transliteração:</strong> Al-ken aleichem kal'u shamayim mital v'ha'aretz kal'ah y'vulah<br>",
            "🇬🇷 <strong>Septuaginta:</strong> ἀντὶ τούτων ὑμᾶς συσχήσει ὁ οὐρανὸς ἀπὸ δρόσου, καὶ ἡ γῆ συσχήσει τὰ ἐκφόρια αὐτῆς<br>",
            "🇻🇦 <strong>Vulgata:</strong> Propter hoc super vos prohibiti sunt caeli a rore, et terra prohibita est germinibus suis.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>כָּלְאוּ</em> – 'retêm' – retêm, detêm. <em>מִטָּל</em> – 'orvalho' – do orvalho. <em>יְבוּלָהּ</em> – 'frutos' – produto, colheita.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Os céus e a terra retêm suas bênçãos por causa do pecado do povo. A seca espiritual e física é consequência da desobediência. Cristo, a chuva do Espírito, traz a bênção quando priorizamos a Deus (Atos 2:17-18).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: A seca é consequência da negligência. Calvino: A criação sofre com o pecado. Crisóstomo: Cristo traz a chuva do Espírito.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> O pecado retém as bênçãos. Em Cristo, recebemos a chuva do Espírito.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 11</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> E mandei vir a seca sobre a terra, e sobre os montes, e sobre o trigo, e sobre o vinho, e sobre o azeite, e sobre tudo o que a terra produz; como também sobre os homens e sobre os animais, e sobre todo o trabalho das mãos.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> וָאֶקְרָא חֹרֶב עַל־הָאָרֶץ וְעַל־הֶהָרִים וְעַל־הַדָּגָן וְעַל־הַתִּירוֹשׁ וְעַל־הַיִּצְהָר וְעַל אֲשֶׁר תּוֹצִיא הָאֲדָמָה וְעַל־הָאָדָם וְעַל־הַבְּהֵמָה וְעַל כָּל־יְגִיעַ כַּפָּיִם<br>",
            "🔤 <strong>Transliteração:</strong> Va'ekra chorev al-ha'aretz v'al-heharim v'al-hadagan v'al-hatirosh v'al-hayitzhar v'al asher totzi ha'adamah v'al-ha'adam v'al-habehemah v'al kol-y'gi'a kapayim<br>",
            "🇬🇷 <strong>Septuaginta:</strong> καὶ ἐπάξω ῥομφαίαν ἐπὶ τὴν γῆν καὶ ἐπὶ τὰ ὄρη καὶ ἐπὶ τὸν σῖτον καὶ ἐπὶ τὸν οἶνον καὶ ἐπὶ τὸ ἔλαιον, καὶ ὅσα ἐκφέρει ἡ γῆ, καὶ ἐπὶ τοὺς ἀνθρώπους καὶ ἐπὶ τὰ κτήνη, καὶ ἐπὶ πάντας τοὺς πόνους τῶν χειρῶν<br>",
            "🇻🇦 <strong>Vulgata:</strong> Et vocavi siccitatem super terram, et super montes, et super triticum, et super vinum, et super oleum, et quaecumque gignit humus, et super homines, et super iumenta, et super omnem laborem manuum.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>חֹרֶב</em> – 'seca' – seca, aridez. <em>הַדָּגָן</em> – 'trigo' – grão, cereal. <em>יְגִיעַ</em> – 'trabalho' – trabalho, labuta.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A seca atinge todas as áreas da vida: agricultura, produção e trabalho humano. O juízo de Deus é abrangente. Cristo, a água viva (João 4:14), sacia a sede da alma e restaura a criação.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: A seca é um juízo de Deus. Calvino: O trabalho humano é frustrado sem a bênção de Deus. Crisóstomo: Cristo é a água viva.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Sem Deus, nosso trabalho é vão. Cristo é a fonte de toda bênção.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 12</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Então Zorobabel, filho de Sealtiel, e Josué, filho de Jozadaque, o sumo sacerdote, com todo o resto do povo, obedeceram à voz do Senhor seu Deus, e às palavras do profeta Ageu, como o Senhor seu Deus o enviara; e o povo temeu diante do Senhor.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> וַיִּשְׁמַע זְרֻבָּבֶל בֶּן־שַׁלְתִּיאֵל וִיהוֹשֻׁעַ בֶּן־יְהוֹצָדָק הַכֹּהֵן הַגָּדוֹל וְכֹל שְׁאֵרִית הָעָם בְּקוֹל יְהוָה אֱלֹהֵיהֶם וְעַל־דִּבְרֵי חַגַּי הַנָּבִיא כַּאֲשֶׁר שְׁלָחוֹ יְהוָה אֱלֹהֵיהֶם וַיִּירְאוּ הָעָם מִפְּנֵי יְהוָה<br>",
            "🔤 <strong>Transliteração:</strong> Vayishma Z'rubavel ben-Shalti'el v'Yehoshua ben-Y'hotzadak hakohan hagadol v'chol sh'erit ha'am b'kol YHWH Eloheihem v'al-divrei Chagai hanavi ka'asher sh'lacho YHWH Eloheihem vayir'u ha'am mip'nei YHWH<br>",
            "🇬🇷 <strong>Septuaginta:</strong> Καὶ ἤκουσε Ζοροβάβελ ὁ τοῦ Σαλαθιὴλ ἐκ φυλῆς Ἰούδα, καὶ Ἰησοῦς ὁ τοῦ Ἰωσεδὲκ ὁ ἱερεὺς ὁ μέγας, καὶ πάντες οἱ κατάλοιποι τοῦ λαοῦ, τῆς φωνῆς κυρίου τοῦ θεοῦ αὐτῶν, καὶ τῶν λόγων Ἀγγαίου τοῦ προφήτου, καθότι ἀπέστειλεν αὐτὸν κύριος ὁ θεὸς αὐτῶν πρὸς αὐτούς, καὶ ἐφοβήθη ὁ λαὸς ἀπὸ προσώπου κυρίου<br>",
            "🇻🇦 <strong>Vulgata:</strong> Et audivit Zorobabel filius Salathiel, et Iesus filius Iosedec sacerdos magnus, et omnes reliquiae populi vocem Domini Dei sui, et verba Aggaei prophetae, sicut misit eum Dominus Deus eorum; et timuit populus a facie Domini.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>וַיִּשְׁמַע</em> – 'obedeceram' – ouviram, obedeceram. <em>שְׁאֵרִית</em> – 'resto' – remanescente. <em>וַיִּירְאוּ</em> – 'temeu' – temeram, reverenciaram.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A obediência e o temor do povo marcam o início da restauração. A liderança de Zorobabel e Josué é fundamental. Cristo, o Rei e Sumo Sacerdote, lidera a obediência da Igreja (Hebreus 5:8-9).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: O povo obedeceu e temeu a Deus. Calvino: A obediência é a resposta correta à Palavra. Crisóstomo: Cristo é o líder da obediência.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Obedeçamos à voz de Deus com temor. Cristo é o nosso exemplo.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 13</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Então Ageu, o mensageiro do Senhor, falou ao povo, segundo a mensagem do Senhor, dizendo: Eu sou convosco, diz o Senhor.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> וַיֹּאמֶר חַגַּי מַלְאַךְ יְהוָה בְּמַלְאֲכוּת יְהוָה לָעָם לֵאמֹר אֲנִי אִתְּכֶם נְאֻם־יְהוָה<br>",
            "🔤 <strong>Transliteração:</strong> Vayomer Chagai mal'ach YHWH b'mal'achut YHWH la'am lemor ani itchem n'um-YHWH<br>",
            "🇬🇷 <strong>Septuaginta:</strong> Καὶ εἶπεν Ἀγγαῖος ἄγγελος κυρίου ἐν ἀγγέλοις κυρίου τῷ λαῷ λέγων· ἐγώ εἰμι μεθ᾽ ὑμῶν, λέγει κύριος<br>",
            "🇻🇦 <strong>Vulgata:</strong> Et dixit Aggaeus nuntius Domini de nuntiis Domini populo, dicens: Ego vobiscum sum, dicit Dominus.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>מַלְאַךְ</em> – 'mensageiro' – anjo, mensageiro. <em>בְּמַלְאֲכוּת</em> – 'segundo a mensagem' – na mensagem, na comissão. <em>אֲנִי אִתְּכֶם</em> – 'Eu sou convosco' – Eu estou com vocês.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A promessa 'Eu sou convosco' é a garantia da presença divina para a obra. Esta promessa é cumprida plenamente em Cristo, o Emanuel, 'Deus conosco' (Mateus 1:23).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: Deus promete Sua presença. Calvino: A presença de Deus é a garantia do sucesso. Crisóstomo: Cristo é o Emanuel.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Deus está conosco em nossa missão. Cristo é a prova de Sua presença.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 14</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> E o Senhor despertou o espírito de Zorobabel, filho de Sealtiel, governador de Judá, e o espírito de Josué, filho de Jozadaque, o sumo sacerdote, e o espírito de todo o resto do povo; e eles vieram e começaram a trabalhar na casa do Senhor dos Exércitos, seu Deus,<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> וַיָּעַר יְהוָה אֶת־רוּחַ זְרֻבָּבֶל בֶּן־שַׁלְתִּיאֵל פַּחַת יְהוּדָה וְאֶת־רוּחַ יְהוֹשֻׁעַ בֶּן־יְהוֹצָדָק הַכֹּהֵן הַגָּדוֹל וְאֶת־רוּחַ כָּל־שְׁאֵרִית הָעָם וַיָּבֹאוּ וַיַּעֲשׂוּ מְלָאכָה בְּבֵית־יְהוָה צְבָאוֹת אֱלֹהֵיהֶם<br>",
            "🔤 <strong>Transliteração:</strong> Vaya'ar YHWH et-ruach Z'rubavel ben-Shalti'el pachat Yehudah v'et-ruach Yehoshua ben-Y'hotzadak hakohan hagadol v'et-ruach kol-sh'erit ha'am vayavo'u vaya'asu m'lachah b'veit-YHWH tz'va'ot Eloheihem<br>",
            "🇬🇷 <strong>Septuaginta:</strong> Καὶ ἐξήγειρε κύριος τὸ πνεῦμα Ζοροβάβελ τοῦ Σαλαθιὴλ ἐκ φυλῆς Ἰούδα, καὶ τὸ πνεῦμα Ἰησοῦ τοῦ Ἰωσεδὲκ τοῦ ἱερέως τοῦ μεγάλου, καὶ τὸ πνεῦμα τῶν καταλοίπων παντὸς τοῦ λαοῦ, καὶ εἰσῆλθον καὶ ἐποίουν ἔργα ἐν τῷ οἴκῳ κυρίου παντοκράτορος θεοῦ αὐτῶν<br>",
            "🇻🇦 <strong>Vulgata:</strong> Et suscitavit Dominus spiritum Zorobabel filii Salathiel ducis Iudae, et spiritum Iesu filii Iosedec sacerdotis magni, et spiritum reliquorum de omni populo; et ingressi sunt, et faciebant opus in domo Domini exercituum Dei sui.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>וַיָּעַר</em> – 'despertou' – despertou, estimulou. <em>רוּחַ</em> – 'espírito' – espírito, ânimo. <em>מְלָאכָה</em> – 'trabalhar' – trabalho, obra.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Deus desperta o espírito dos líderes e do povo para a obra. O Espírito Santo capacita a Igreja para a missão. Cristo, que derramou o Espírito no Pentecostes (Atos 2), é o capacitador da obra.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: Deus despertou o ânimo do povo. Calvino: O Espírito Santo capacita para a obra. Crisóstomo: Cristo derramou o Espírito.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> O Espírito Santo nos capacita para a obra. Busquemos a plenitude do Espírito.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 15</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> aos vinte e quatro dias do sexto mês, no segundo ano do rei Dario.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> בְּיוֹם עֶשְׂרִים וְאַרְבָּעָה לַחֹדֶשׁ בַּשִּׁשִּׁי בִּשְׁנַת שְׁתַּיִם לְדָרְיָוֶשׁ הַמֶּלֶךְ<br>",
            "🔤 <strong>Transliteração:</strong> B'yom esrim v'arba'ah lachodesh bashishi bishnat shtayim l'Daryavesh hamelech<br>",
            "🇬🇷 <strong>Septuaginta:</strong> τῇ τετράδι καὶ εἰκάδι τοῦ μηνὸς τοῦ ἕκτου, ἐν τῷ δευτέρῳ ἔτει ἐπὶ Δαρείου τοῦ βασιλέως<br>",
            "🇻🇦 <strong>Vulgata:</strong> Die viginti quarta mensis sexti, in anno secundo Darii regis.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>עֶשְׂרִים וְאַרְבָּעָה</em> – 'vinte e quatro' – vigésimo quarto dia. <em>בַּשִּׁשִּׁי</em> – 'sexto' – sexto mês. <em>בִּשְׁנַת שְׁתַּיִם</em> – 'segundo ano' – no segundo ano.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A data específica marca o início da obra de reconstrução. O tempo de Deus é perfeito. Cristo, que veio na plenitude do tempo (Gálatas 4:4), inaugurou a nova aliança.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: A obra começou no tempo designado. Calvino: O tempo de Deus é perfeito. Crisóstomo: Cristo veio na plenitude do tempo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Deus tem um tempo para cada obra. Confiemos em Seu timing perfeito.<br>"
        ],
        2: [
            
            "<span style='font-size: 15px;'><strong>VERSÍCULO: 1</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> No sétimo mês, aos vinte e um dias do mês, veio a palavra do Senhor, por intermédio do profeta Ageu, dizendo:<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> בַּשְּׁבִיעִי בְּעֶשְׂרִים וְאֶחָד לַחֹדֶשׁ הָיָה דְּבַר־יְהוָה בְּיַד־חַגַּי הַנָּבִיא לֵאמֹר<br>",
            "🔤 <strong>Transliteração:</strong> Bash'vi'i b'esrim v'echad lachodesh hayah d'var-YHWH b'yad-Chagai hanavi lemor<br>",
            "🇬🇷 <strong>Septuaginta:</strong> Ἐν τῷ ἑβδόμῳ μηνὶ μιᾷ καὶ εἰκάδι τοῦ μηνὸς ἐλάλησε κύριος ἐν χειρὶ Ἀγγαίου τοῦ προφήτου λέγων<br>",
            "🇻🇦 <strong>Vulgata:</strong> In mense septimo, die viginti et una mensis, factum est verbum Domini in manu Aggaei prophetae, dicens:<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>בַּשְּׁבִיעִי</em> – 'sétimo' – sétimo mês. <em>בְּעֶשְׂרִים וְאֶחָד</em> – 'vinte e um' – vigésimo primeiro dia. <em>לֵאמֹר</em> – 'dizendo' – dizendo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A segunda mensagem de Ageu vem no sétimo mês, durante a Festa dos Tabernáculos, um tempo de alegria e celebração. Cristo, que habitou entre nós (João 1:14), é a celebração da presença de Deus.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: A mensagem veio durante a Festa dos Tabernáculos. Calvino: Deus fala em tempos de celebração. Crisóstomo: Cristo é a presença de Deus.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Deus fala conosco em todos os tempos. Celebremos Sua presença em Cristo.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 2</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Fala agora a Zorobabel, filho de Sealtiel, governador de Judá, e a Josué, filho de Jozadaque, o sumo sacerdote, e ao resto do povo, dizendo:<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> אֱמָר־נָא אֶל־זְרֻבָּבֶל בֶּן־שַׁלְתִּיאֵל פַּחַת יְהוּדָה וְאֶל־יְהוֹשֻׁעַ בֶּן־יְהוֹצָדָק הַכֹּהֵן הַגָּדוֹל וְאֶל־שְׁאֵרִית הָעָם לֵאמֹר<br>",
            "🔤 <strong>Transliteração:</strong> Emar-na el-Z'rubavel ben-Shalti'el pachat Yehudah v'el-Yehoshua ben-Y'hotzadak hakohan hagadol v'el-sh'erit ha'am lemor<br>",
            "🇬🇷 <strong>Septuaginta:</strong> εἶπον δὴ πρὸς Ζοροβάβελ τὸν τοῦ Σαλαθιὴλ ἐκ φυλῆς Ἰούδα, καὶ πρὸς Ἰησοῦν τὸν τοῦ Ἰωσεδὲκ τὸν ἱερέα τὸν μέγαν, καὶ πρὸς πάντας τοὺς καταλοίπους τοῦ λαοῦ, λέγων<br>",
            "🇻🇦 <strong>Vulgata:</strong> Loquere ad Zorobabel filium Salathiel ducem Iudae, et ad Iesum filium Iosedec sacerdotem magnum, et ad reliquos populi, dicens:<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>אֱמָר</em> – 'Fala' – fala, dize. <em>פַּחַת</em> – 'governador' – governador, vice-rei. <em>שְׁאֵרִית</em> – 'resto' – remanescente.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A mensagem é dirigida aos líderes e ao povo, destacando a importância da liderança e da obediência coletiva. Cristo, o Cabeça da Igreja, fala à Sua Igreja (Efésios 5:23).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: A mensagem é para líderes e povo. Calvino: A liderança e a congregação devem ouvir. Crisóstomo: Cristo fala à Sua Igreja.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Toda a Igreja deve ouvir a voz de Cristo. Ele fala a todos.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 3</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Quem há entre vós que tenha visto esta casa na sua glória primitiva? E como a vedes agora? Não é ela como nada diante dos vossos olhos?<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> מִי בָכֶם הַנִּשְׁאָר אֲשֶׁר רָאָה אֶת־הַבַּיִת הַזֶּה בִּכְבוֹדוֹ הָרִאשׁוֹן וּמָה אַתֶּם רֹאִים אֹתוֹ עַתָּה הֲלוֹא כָמֹהוּ כְּאַיִן בְּעֵינֵיכֶם<br>",
            "🔤 <strong>Transliteração:</strong> Mi vachem hanish'ar asher ra'ah et-habayit hazeh bichvodo harishon u'mah atem ro'im oto atah halo chamohu k'ayin b'eineichem<br>",
            "🇬🇷 <strong>Septuaginta:</strong> τίς ἐξ ὑμῶν ὃς εἶδε τὸν οἶκον τοῦτον ἐν τῇ δόξῃ αὐτοῦ τῇ πρώτῃ; καὶ πῶς ὑμεῖς βλέπετε αὐτὸν νῦν, καθὼς οὐκ ἔστιν ἐν ὀφθαλμοῖς ὑμῶν;<br>",
            "🇻🇦 <strong>Vulgata:</strong> Quis in vobis est derelictus, qui vidit domum istam in gloria sua prima? Et quid vos videtis eam nunc? Numquid non ita est quasi non sit in oculis vestris?<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>הַנִּשְׁאָר</em> – 'que tenha visto' – o remanescente, que viu. <em>בִּכְבוֹדוֹ</em> – 'na sua glória' – em sua glória, esplendor. <em>כָּאַיִן</em> – 'como nada' – como nada.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> O novo templo parecia insignificante comparado ao de Salomão. Mas a glória de Deus não depende de aparências externas. Cristo, o verdadeiro templo, é a glória de Deus (João 1:14).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: O templo atual é menor que o de Salomão. Calvino: A glória de Deus não está em aparências. Crisóstomo: Cristo é a verdadeira glória.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Não desprezemos a obra de Deus por sua aparência. Cristo é a verdadeira glória.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 4</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Ora, pois, esforça-te, Zorobabel, diz o Senhor; esforça-te também, Josué, filho de Jozadaque, o sumo sacerdote; e esforçai-vos, todo o povo da terra, diz o Senhor, e trabalhai; porque eu sou convosco, diz o Senhor dos Exércitos.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> וְעַתָּה חֲזַק זְרֻבָּבֶל נְאֻם־יְהוָה וַחֲזַק יְהוֹשֻׁעַ בֶּן־יְהוֹצָדָק הַכֹּהֵן הַגָּדוֹל וַחֲזַק כָּל־עַם הָאָרֶץ נְאֻם־יְהוָה וַעֲשׂוּ כִּי־אֲנִי אִתְּכֶם נְאֻם יְהוָה צְבָאוֹת<br>",
            "🔤 <strong>Transliteração:</strong> V'atah chazak Z'rubavel n'um-YHWH v'chazak Yehoshua ben-Y'hotzadak hakohan hagadol v'chazak kol-am ha'aretz n'um-YHWH va'asu ki-ani itchem n'um YHWH tz'va'ot<br>",
            "🇬🇷 <strong>Septuaginta:</strong> καὶ νῦν ἰσχυέτω Ζοροβάβελ, λέγει κύριος, καὶ ἰσχυέτω Ἰησοῦς ὁ τοῦ Ἰωσεδὲκ ὁ ἱερεὺς ὁ μέγας, καὶ ἰσχυέτω πᾶς ὁ λαὸς τῆς γῆς, λέγει κύριος, καὶ ἐργάζεσθε, διότι ἐγὼ μεθ᾽ ὑμῶν, λέγει κύριος παντοκράτωρ<br>",
            "🇻🇦 <strong>Vulgata:</strong> Et nunc confortare, Zorobabel, dicit Dominus, et confortare, Iesu fili Iosedec sacerdos magne, et confortare, omnis popule terrae, dicit Dominus exercituum; et facite, quoniam ego vobiscum sum, dicit Dominus exercituum.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>חֲזַק</em> – 'esforça-te' – fortalece-te, encoraja-te. <em>וַעֲשׂוּ</em> – 'trabalhai' – fazei, trabalhai. <em>אֲנִי אִתְּכֶם</em> – 'eu sou convosco' – Eu estou com vocês.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> O chamado ao esforço e à obra é baseado na promessa da presença divina. Cristo, o Emanuel, está conosco e nos capacita (Mateus 28:20).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: O povo deve se esforçar porque Deus está com eles. Calvino: A presença de Deus é a fonte de força. Crisóstomo: Cristo está conosco.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Esforcemo-nos na obra de Deus, pois Ele está conosco. Cristo é a nossa força.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 5</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Segundo a palavra que comigo fiz aliança, quando saístes do Egito, assim o meu Espírito habita no meio de vós; não temais.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> אֶת־הַדָּבָר אֲשֶׁר־כָּרַתִּי אִתְּכֶם בְּצֵאתְכֶם מִמִּצְרָיִם וְרוּחִי עֹמֶדֶת בְּתוֹכְכֶם אַל־תִּירָאוּ<br>",
            "🔤 <strong>Transliteração:</strong> Et-hadavar asher-karati itchem b'tzeit'chem miMitzrayim v'ruchi omedet b'tochechem al-tira'u<br>",
            "🇬🇷 <strong>Septuaginta:</strong> καὶ τὸ πνεῦμά μου ἐφέστηκεν ἐν μέσῳ ὑμῶν· θαρσεῖτε<br>",
            "🇻🇦 <strong>Vulgata:</strong> Verbum quod pepigi vobiscum, cum egrederemini de Aegypto, et spiritus meus erit in medio vestri; nolite timere.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>כָּרַתִּי</em> – 'fiz aliança' – fiz aliança, cortei. <em>בְּתוֹכְכֶם</em> – 'no meio de vós' – no meio de vocês. <em>אַל־תִּירָאוּ</em> – 'não temais' – não temam.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A aliança de Deus e a presença do Espírito são a garantia da continuidade da obra. O Espírito Santo habita na Igreja (1 Coríntios 3:16). Cristo, que cumpriu a aliança, derramou o Espírito sobre nós.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: O Espírito de Deus está no meio do povo. Calvino: A presença do Espírito é a garantia da aliança. Crisóstomo: Cristo derramou o Espírito.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> O Espírito Santo habita em nós. Não temamos, pois Ele está conosco.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 6</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Porque assim diz o Senhor dos Exércitos: Ainda uma vez, dentro em pouco, farei tremer os céus e a terra, o mar e a terra seca.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> כִּי כֹה אָמַר יְהוָה צְבָאוֹת עוֹד אַחַת מְעַט הִיא וַאֲנִי מַרְעִישׁ אֶת־הַשָּׁמַיִם וְאֶת־הָאָרֶץ וְאֶת־הַיָּם וְאֶת־הֶחָרָבָה<br>",
            "🔤 <strong>Transliteração:</strong> Ki koh amar YHWH tz'va'ot od achat m'at hi va'ani mar'ish et-hashamayim v'et-ha'aretz v'et-hayam v'et-hecharavah<br>",
            "🇬🇷 <strong>Septuaginta:</strong> διότι τάδε λέγει κύριος παντοκράτωρ· ἔτι ἅπαξ ἐγὼ σείσω τὸν οὐρανὸν καὶ τὴν γῆν καὶ τὴν θάλασσαν καὶ τὴν ξηράν<br>",
            "🇻🇦 <strong>Vulgata:</strong> Quia haec dicit Dominus exercituum: Adhuc unum modicum est, et ego movebo caelum et terram, et mare et aridam;<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>עוֹד אַחַת</em> – 'Ainda uma vez' – uma vez mais. <em>מַרְעִישׁ</em> – 'farei tremer' – estremecerei, agitarei. <em>הֶחָרָבָה</em> – 'terra seca' – a terra seca.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> O tremor dos céus e da terra aponta para a manifestação final de Deus, o juízo e a restauração. Cristo, ao vir, fez tremer os céus (Mateus 27:51) e estabelecerá um novo céu e nova terra (Apocalipse 21:1).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: O tremor final virá com a vinda do Messias. Calvino: A manifestação final de Deus é iminente. Crisóstomo: Cristo trará um novo céu e terra.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> A vinda de Cristo abalará todas as coisas. Confiemos em Sua restauração final.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 7</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Farei tremer todas as nações; e virá o desejo de todas as nações; e encherei esta casa de glória, diz o Senhor dos Exércitos.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> וְהִרְעַשְׁתִּי אֶת־כָּל־הַגּוֹיִם וּבָאוּ חֶמְדַּת כָּל־הַגּוֹיִם וּמִלֵּאתִי אֶת־הַבַּיִת הַזֶּה כָּבוֹד אָמַר יְהוָה צְבָאוֹת<br>",
            "🔤 <strong>Transliteração:</strong> V'hir'ashti et-kol-hagoyim u'va'u chemdat kol-hagoyim umileti et-habayit hazeh kavod amar YHWH tz'va'ot<br>",
            "🇬🇷 <strong>Septuaginta:</strong> καὶ συσείσω πάντα τὰ ἔθνη, καὶ ἥξει τὰ ἐκλεκτὰ πάντων τῶν ἐθνῶν, καὶ πλήσω τὸν οἶκον τοῦτον δόξης, λέγει κύριος παντοκράτωρ<br>",
            "🇻🇦 <strong>Vulgata:</strong> et movebo omnes gentes, et veniet desideratus cunctis gentibus; et implebo domum istam gloria, dicit Dominus exercituum.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>חֶמְדַּת</em> – 'desejo' – desejo, objeto de desejo. <em>וּמִלֵּאתִי</em> – 'encherei' – encherei, completarei. <em>כָּבוֹד</em> – 'glória' – glória, honra.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> 'O desejo de todas as nações' é uma profecia messiânica, referindo-se a Cristo. Ele é o desejado de todas as nações, que enche o templo (a Igreja) com Sua glória. Cristo é a glória de Deus (Hebreus 1:3).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: O 'desejo' é o Messias. Calvino: Cristo é o desejado das nações. Crisóstomo: Cristo enche a Igreja com Sua glória.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Cristo é o desejado das nações. Ele enche a Igreja com Sua glória.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 8</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Minha é a prata, e meu é o ouro, diz o Senhor dos Exércitos.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> לִי הַכֶּסֶף וְלִי הַזָּהָב נְאֻם יְהוָה צְבָאוֹת<br>",
            "🔤 <strong>Transliteração:</strong> Li hakesef v'li hazahav n'um YHWH tz'va'ot<br>",
            "🇬🇷 <strong>Septuaginta:</strong> ἐμὸν τὸ ἀργύριον, καὶ ἐμὸν τὸ χρυσίον, λέγει κύριος παντοκράτωρ<br>",
            "🇻🇦 <strong>Vulgata:</strong> Meum est argentum, et meum est aurum, dicit Dominus exercituum.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>לִי</em> – 'Minha' – a Mim pertence. <em>הַכֶּסֶף</em> – 'prata' – prata. <em>הַזָּהָב</em> – 'ouro' – ouro.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Deus declara que toda riqueza Lhe pertence. Ele pode prover para a construção do Seu templo. Cristo, o Senhor de todas as riquezas, provê para Sua Igreja (Filipenses 4:19).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: Toda riqueza pertence a Deus. Calvino: Deus é o dono de todas as coisas. Crisóstomo: Cristo provê para Sua Igreja.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Toda riqueza pertence a Deus. Confiemos em Sua provisão.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 9</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> A glória desta última casa será maior do que a da primeira, diz o Senhor dos Exércitos; e neste lugar darei a paz, diz o Senhor dos Exércitos.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> גָּדוֹל יִהְיֶה כְּבוֹד הַבַּיִת הַזֶּה הָאַחֲרוֹן מִן־הָרִאשׁוֹן אָמַר יְהוָה צְבָאוֹת וּבַמָּקוֹם הַזֶּה אֶתֵּן שָׁלוֹם נְאֻם יְהוָה צְבָאוֹת<br>",
            "🔤 <strong>Transliteração:</strong> Gadol yih'yeh k'vod habayit hazeh ha'acharon min-harishon amar YHWH tz'va'ot uvamakom hazeh eten shalom n'um YHWH tz'va'ot<br>",
            "🇬🇷 <strong>Septuaginta:</strong> μεγάλη ἔσται ἡ δόξα τοῦ οἴκου τούτου ἡ ἐσχάτη ὑπὲρ τὴν πρώτην, λέγει κύριος παντοκράτωρ· καὶ ἐν τῷ τόπῳ τούτῳ δώσω εἰρήνην, λέγει κύριος παντοκράτωρ, καὶ εἰρήνην ψυχῆς εἰς περιποίησιν παντὶ τῷ κτίζοντι τοῦ ἀναστῆσαι τὸν ναὸν τοῦτον<br>",
            "🇻🇦 <strong>Vulgata:</strong> Magna erit gloria domus istius novissimae plus quam primae, dicit Dominus exercituum; et in loco isto dabo pacem, dicit Dominus exercituum.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>גָּדוֹל</em> – 'maior' – grande, maior. <em>כְּבוֹד</em> – 'glória' – glória. <em>שָׁלוֹם</em> – 'paz' – paz, prosperidade.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A glória do segundo templo superaria a do primeiro, não pela beleza material, mas pela presença de Cristo, o Príncipe da Paz, que visitou este templo. Cristo, o Príncipe da Paz (Isaías 9:6), trouxe paz através de Sua obra redentora.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: A glória do segundo templo será maior pela presença do Messias. Calvino: A paz de Cristo é a verdadeira glória. Crisóstomo: Cristo é a paz.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Cristo é a glória e a paz da Igreja. Ele nos dá Sua paz.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 10</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Aos vinte e quatro dias do nono mês, no segundo ano de Dario, veio a palavra do Senhor ao profeta Ageu, dizendo:<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> בְּעֶשְׂרִים וְאַרְבָּעָה לַתִּשְׁעִי בִּשְׁנַת שְׁתַּיִם לְדָרְיָוֶשׁ הָיָה דְּבַר־יְהוָה אֶל־חַגַּי הַנָּבִיא לֵאמֹר<br>",
            "🔤 <strong>Transliteração:</strong> B'esrim v'arba'ah latish'i bishnat shtayim l'Daryavesh hayah d'var-YHWH el-Chagai hanavi lemor<br>",
            "🇬🇷 <strong>Septuaginta:</strong> Τετράδι καὶ εἰκάδι τοῦ μηνὸς τοῦ ἐνάτου, ἐν ἔτει δευτέρῳ ἐπὶ Δαρείου, ἐγένετο λόγος κυρίου πρὸς Ἀγγαῖον τὸν προφήτην λέγων<br>",
            "🇻🇦 <strong>Vulgata:</strong> In die viginti quarta mensis noni, in anno secundo Darii, factum est verbum Domini ad Aggaeum prophetam, dicens:<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>בְּעֶשְׂרִים וְאַרְבָּעָה</em> – 'vinte e quatro' – vigésimo quarto dia. <em>לַתִּשְׁעִי</em> – 'nono' – nono mês. <em>אֶל־חַגַּי</em> – 'a Ageu' – ao profeta Ageu.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A terceira mensagem de Ageu vem em um novo tempo, após a reconstrução ter começado. Deus continua instruindo Seu povo. Cristo, a Palavra final, continua nos guiando.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: A terceira mensagem é para instrução. Calvino: Deus guia Seu povo continuamente. Crisóstomo: Cristo é a Palavra final.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Deus continua nos guiando através de Sua Palavra. Cristo é a nossa direção.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 11</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Assim diz o Senhor dos Exércitos: Pergunta agora aos sacerdotes acerca da lei, dizendo:<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> כֹּה אָמַר יְהוָה צְבָאוֹת שְׁאַל־נָא אֶת־הַכֹּהֲנִים תּוֹרָה לֵאמֹר<br>",
            "🔤 <strong>Transliteração:</strong> Koh amar YHWH tz'va'ot sha'al-na et-hakohanim torah lemor<br>",
            "🇬🇷 <strong>Septuaginta:</strong> τάδε λέγει κύριος παντοκράτωρ· ἐπερώτησον τοὺς ἱερεῖς νόμον λέγων<br>",
            "🇻🇦 <strong>Vulgata:</strong> Haec dicit Dominus exercituum: Interroga sacerdotes legem, dicens:<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>שְׁאַל</em> – 'Pergunta' – pergunta, consulta. <em>הַכֹּהֲנִים</em> – 'sacerdotes' – sacerdotes. <em>תּוֹרָה</em> – 'lei' – lei, instrução.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Deus ordena que os sacerdotes sejam consultados sobre a lei. A instrução sacerdotal era fundamental para a pureza do povo. Cristo, o Sumo Sacerdote, é a nossa instrução (Hebreus 5:1-5).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: A lei deve ser consultada para orientação. Calvino: A instrução sacerdotal é importante. Crisóstomo: Cristo é o Sumo Sacerdote.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Busquemos a instrução de Deus. Cristo é a nossa sabedoria.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 12</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Se alguém levar carne santa na aba do seu vestido, e com a sua aba tocar no pão, ou no caldo, ou no vinho, ou no azeite, ou em qualquer outro mantimento, ficará este santificado? Responderam os sacerdotes: Não.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> הֵן יִשָּׂא־אִישׁ בְּשַׂר־קֹדֶשׁ בִּכְנַף בִּגְדוֹ וְנָגַע בִּכְנָפוֹ אֶל־הַלֶּחֶם וְאֶל־הַנָּזִיד וְאֶל־הַיַּיִן וְאֶל־שֶׁמֶן וְאֶל־כָּל־מַאֲכָל הֲיִקְדָּשׁ וַיַּעֲנוּ הַכֹּהֲנִים וַיֹּאמְרוּ לֹא<br>",
            "🔤 <strong>Transliteração:</strong> Hen yisa-ish b'sar-kodesh bichnaf bigdo v'naga bichnafo el-halechem v'el-hanazid v'el-hayayin v'el-shemen v'el-kol-ma'achal hayikdash vaya'anu hakohanim vayomru lo<br>",
            "🇬🇷 <strong>Septuaginta:</strong> ἐὰν λάβῃ ἄνθρωπος κρέας ἅγιον ἐν τῷ ἄκρῳ τοῦ ἱματίου αὐτοῦ, καὶ ἅψηται τὸ ἄκρον αὐτοῦ ἄρτου ἢ ἑψήματος ἢ οἴνου ἢ ἐλαίου ἢ βρώσεως, ἁγιασθήσεται; καὶ ἀπεκρίθησαν οἱ ἱερεῖς καὶ εἶπαν· οὔ<br>",
            "🇻🇦 <strong>Vulgata:</strong> Si tulerit homo carnem sanctificatam in ora vestimenti sui, et tetigerit de ora eius panem, aut pulmentum, aut vinum, aut oleum, aut omnem cibum, numquid sanctificabitur? Respondentes autem sacerdotes, dixerunt: Non.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>בְּשַׂר־קֹדֶשׁ</em> – 'carne santa' – carne consagrada. <em>בִּכְנַף</em> – 'aba' – borda, extremidade. <em>הֲיִקְדָּשׁ</em> – 'ficará santificado' – será santificado.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A santidade não é transmitida por contato externo. A verdadeira santidade vem de Deus, não de rituais. Cristo, que santifica Seu povo (Hebreus 10:10), nos purifica internamente.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: A santidade não é transmitida por contato. Calvino: A santidade vem de Deus, não de rituais. Crisóstomo: Cristo santifica Seu povo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> A verdadeira santidade vem de Cristo. Busquemos a santidade em Sua obra.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 13</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Então disse Ageu: Se alguém, contaminado por um cadáver, tocar em alguma destas coisas, ficará ela contaminada? Responderam os sacerdotes: Ficará contaminada.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> וַיֹּאמֶר חַגַּי אִם־יִגַּע טְמֵא־נֶפֶשׁ בְּכָל־אֵלֶּה הֲיִטְמָא וַיַּעֲנוּ הַכֹּהֲנִים וַיֹּאמְרוּ יִטְמָא<br>",
            "🔤 <strong>Transliteração:</strong> Vayomer Chagai im-yiga tame-nefesh b'chol-eleh hayitma vaya'anu hakohanim vayomru yitma<br>",
            "🇬🇷 <strong>Septuaginta:</strong> καὶ εἶπεν Ἀγγαῖος· ἐὰν ἅψηται μεμιασμένος ἐν ψυχῇ ἐπὶ παντὸς τούτων, μιανθήσεται; καὶ ἀπεκρίθησαν οἱ ἱερεῖς καὶ εἶπαν· μιανθήσεται<br>",
            "🇻🇦 <strong>Vulgata:</strong> Et dixit Aggaeus: Si tetigerit pollutus anima de omnibus his, numquid contaminabitur? Et responderunt sacerdotes, et dixerunt: Contaminabitur.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>טְמֵא־נֶפֶשׁ</em> – 'contaminado por um cadáver' – impuro por um morto. <em>הֲיִטְמָא</em> – 'ficará contaminada' – será contaminada? <em>יִטְמָא</em> – 'ficará contaminada' – será contaminada.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A impureza é transmitida pelo contato, mostrando a necessidade de pureza. O pecado contamina tudo que toca. Cristo, que nos purifica do pecado (1 João 1:7), é a única fonte de pureza.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: A impureza é transmitida por contato. Calvino: O pecado contamina tudo. Crisóstomo: Cristo nos purifica.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> O pecado contamina, mas Cristo purifica. Busquemos a pureza em Cristo.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 14</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Respondeu então Ageu, e disse: Assim é este povo, e assim é esta nação diante de mim, diz o Senhor; e assim é toda obra das suas mãos; e tudo o que ali oferecem é imundo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> וַיַּעַן חַגַּי וַיֹּאמֶר כֵּן הָעָם הַזֶּה וְכֵן הַגּוֹי הַזֶּה לְפָנַי נְאֻם־יְהוָה וְכֵן כָּל־מַעֲשֵׂה יְדֵיהֶם וַאֲשֶׁר יַקְרִיבוּ שָׁם טָמֵא הוּא<br>",
            "🔤 <strong>Transliteração:</strong> Vaya'an Chagai vayomer ken ha'am hazeh v'chen hagoy hazeh l'fanai n'um-YHWH v'chen kol-ma'aseh y'deihem va'asher yakrivu sham tame hu<br>",
            "🇬🇷 <strong>Septuaginta:</strong> Καὶ ἀπεκρίθη Ἀγγαῖος καὶ εἶπεν· οὕτως ὁ λαὸς οὗτος, καὶ οὕτως τὸ ἔθνος τοῦτο ἐνώπιόν μου, λέγει κύριος, καὶ οὕτω πάντα τὰ ἔργα τῶν χειρῶν αὐτῶν, καὶ ὃ ἐὰν προσφέρωσιν ἐκεῖ, μεμίανταί ἐστι<br>",
            "🇻🇦 <strong>Vulgata:</strong> Et respondit Aggaeus, et dixit: Sic populus iste, et sic gens ista ante faciem meam, dicit Dominus, et sic omne opus manuum eorum; et omnia quae ibi offerunt, polluta sunt.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>כֵּן</em> – 'Assim' – assim, deste modo. <em>טָמֵא</em> – 'imundo' – impuro, contaminado.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> O povo, suas obras e ofertas são impuros por causa do pecado. A contaminação os separa de Deus. Cristo, que ofereceu o sacrifício perfeito, purifica o Seu povo (Hebreus 9:14).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: O povo e suas ofertas são impuros. Calvino: O pecado contamina tudo. Crisóstomo: Cristo purifica Seu povo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Sem Cristo, somos impuros. Ele nos purifica e santifica.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 15</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Agora, pois, considerai, desde este dia em diante, antes que se pusesse pedra sobre pedra no templo do Senhor,<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> וְעַתָּה שִׂימוּ־נָא לְבַבְכֶם מִן־הַיּוֹם הַזֶּה וָמַעְלָה מִטֶּרֶם שׂוּם־אֶבֶן אֶל־אֶבֶן בְּהֵיכַל יְהוָה<br>",
            "🔤 <strong>Transliteração:</strong> V'atah simu-na l'vavchem min-hayom hazeh vama'lah mit'rem sum-even el-even b'heichal YHWH<br>",
            "🇬🇷 <strong>Septuaginta:</strong> Καὶ νῦν θέσθε δὴ εἰς τὰς καρδίας ὑμῶν ἀπὸ τῆς ἡμέρας ταύτης καὶ ἄνω, πρὸ τοῦ θεῖναι λίθον ἐπὶ λίθον ἐν τῷ ναῷ κυρίου<br>",
            "🇻🇦 <strong>Vulgata:</strong> Et nunc ponite corda vestra a die hac et supra, antequam poneretur lapis super lapidem in templo Domini;<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>שִׂימוּ לְבַבְכֶם</em> – 'considerai' – ponde o coração, considerai. <em>מִטֶּרֶם</em> – 'antes que' – antes que. <em>בְּהֵיכַל</em> – 'no templo' – no palácio, templo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> O chamado para considerar as coisas passadas e o presente. A reflexão sobre a história ajuda a entender a graça de Deus. Cristo, o autor e consumador da fé (Hebreus 12:2), é o centro da história.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: O povo deve refletir sobre o passado. Calvino: A história ensina sobre a fidelidade de Deus. Crisóstomo: Cristo é o centro da história.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Reflitamos sobre a fidelidade de Deus. Cristo é a nossa história.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 16</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> antes que sucedessem estas coisas, quando alguém vinha a um montão de vinte medidas, havia só dez; quando vinha ao lagar para tirar cinquenta vasilhas, havia só vinte.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> מִהְיוֹתָם בָּא אֶל־עֲרֵמַת עֶשְׂרִים וְהָיְתָה עֲשָׂרָה בָּא אֶל־הַיֶּקֶב לַחְשֹׂף חֲמִשִּׁים פּוּרָה וְהָיְתָה עֶשְׂרִים<br>",
            "🔤 <strong>Transliteração:</strong> Mih'yotam ba el-ar'emat esrim v'hayetah asarah ba el-hayekev lach'sof chamishim purah v'hayetah esrim<br>",
            "🇬🇷 <strong>Septuaginta:</strong> τίνες ἐγένεσθε; ἐπεβλέψατε εἰς σωρὸν εἰκοσαετοῦς, καὶ ἐγενήθη ὁ σωρὸς δέκα, καὶ εἰσήλθετε εἰς ληνὸν ἀντλῆσαι πεντήκοντα, καὶ ἐγένετο εἴκοσι<br>",
            "🇻🇦 <strong>Vulgata:</strong> cum accederetis ad acervum viginti modiorum, et fierent decem; et intraretis ad torcular, ut hauriretis quinquaginta lagenas, et fiebant viginti.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>עֲרֵמַת</em> – 'montão' – monte, pilha. <em>הַיֶּקֶב</em> – 'lagar' – tanque de prensa. <em>חֲמִשִּׁים</em> – 'cinquenta' – cinquenta.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A falta de bênção antes da reconstrução é contrastada com a bênção futura. A obediência traz a bênção de Deus. Cristo, a bênção de Abraão (Gálatas 3:14), nos traz a plenitude da bênção.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: A colheita era escassa antes. Calvino: A obediência traz bênção. Crisóstomo: Cristo é a bênção plena.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> A obediência a Deus traz bênção. Cristo é a fonte de toda bênção.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 17</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Feri-vos com queimadura, com ferrugem e com saraiva, em toda a obra das vossas mãos; e não houve entre vós quem voltasse para mim, diz o Senhor.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> הִכֵּיתִי אֶתְכֶם בַּשִּׁדָּפוֹן וּבַיֵּרָקוֹן וּבַבָּרָד אֵת כָּל־מַעֲשֵׂה יְדֵיכֶם וְאֵין־אֶתְכֶם אֵלַי נְאֻם־יְהוָה<br>",
            "🔤 <strong>Transliteração:</strong> Hiketi etchem bashidafon u'vay'erakon u'vabarad et kol-ma'aseh y'deichem v'ein-etchem elai n'um-YHWH<br>",
            "🇬🇷 <strong>Septuaginta:</strong> ἐπάταξα ὑμᾶς ἐν ἀνεμοφθορία καὶ ἐν ἐρυσίβῃ καὶ ἐν χαλάζῃ πάντα τὰ ἔργα τῶν χειρῶν ὑμῶν, καὶ οὐκ ἐπεστρέψατε πρὸς με, λέγει κύριος<br>",
            "🇻🇦 <strong>Vulgata:</strong> Percussi vos vento urente, et aurugine, et grandine omnia opera manuum vestrarum; et non fuit in vobis qui reverteretur ad me, dicit Dominus.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>בַּשִּׁדָּפוֹן</em> – 'queimadura' – tísia, crestamento. <em>בַיֵּרָקוֹן</em> – 'ferrugem' – ferrugem, amarelão. <em>בַּבָּרָד</em> – 'saraiva' – granizo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> O juízo de Deus veio em pragas, mas o povo não se arrependeu. A persistência no pecado traz disciplina. Cristo, que suportou o juízo por nós (Isaías 53:4-5), nos chama ao arrependimento.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: Deus enviou pragas, mas o povo não se arrependeu. Calvino: O arrependimento é necessário. Crisóstomo: Cristo suportou o juízo por nós.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Não endureçamos o coração diante da disciplina de Deus. Cristo nos chama ao arrependimento.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 18</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Considerai, pois, desde este dia em diante, desde o vigésimo quarto dia do nono mês, desde o dia em que se fundou o templo do Senhor, considerai estas coisas.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> שִׂימוּ־נָא לְבַבְכֶם מִן־הַיּוֹם הַזֶּה וָמַעְלָה מִיּוֹם עֶשְׂרִים וְאַרְבָּעָה לַתְּשִׁיעִי לְמִן־הַיּוֹם אֲשֶׁר־יֻסַּד הֵיכַל־יְהוָה שִׂימוּ לְבַבְכֶם<br>",
            "🔤 <strong>Transliteração:</strong> Simu-na l'vavchem min-hayom hazeh vama'lah miyom esrim v'arba'ah lat'shi'i l'min-hayom asher-yusad heichal-YHWH simu l'vavchem<br>",
            "🇬🇷 <strong>Septuaginta:</strong> θέσθε δὴ εἰς τὰς καρδίας ὑμῶν ἀπὸ τῆς ἡμέρας ταύτης καὶ ἄνω, ἀπὸ τῆς τετράδος καὶ εἰκάδος τοῦ μηνὸς τοῦ ἐνάτου, καὶ ἀπὸ τῆς ἡμέρας ἧς ἐθεμελιώθη ὁ ναὸς κυρίου, θέσθε εἰς τὰς καρδίας ὑμῶν<br>",
            "🇻🇦 <strong>Vulgata:</strong> Ponite corda vestra a die hac et deinceps, a die viginti quarta mensis noni, a die qua fundata sunt templi fundamenta, et ponite super cor vestrum.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>יֻסַּד</em> – 'se fundou' – foi fundado, estabelecido. <em>הֵיכַל</em> – 'templo' – palácio, templo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> O dia em que os fundamentos do templo foram lançados é um marco. A partir desse dia, a bênção seria restaurada. Cristo, o fundamento da Igreja (1 Coríntios 3:11), é o marco da nova criação.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: O marco da fundação do templo é significativo. Calvino: A obediência traz bênção a partir do fundamento. Crisóstomo: Cristo é o fundamento da Igreja.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Cristo é o fundamento da nossa fé. A partir dEle, recebemos bênção.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 19</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Está ainda a semente no celeiro? A vide, a figueira, a romeira e a oliveira ainda não dão o seu fruto? Mas desde este dia vos abençoarei.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> הַעוֹד הַזֶּרַע בַּמְּגוּרָה וְעַד־הַגֶּפֶן וְהַתְּאֵנָה וְהָרִמּוֹן וְעֵץ הַזַּיִת לֹא נָשָׂא מִן־הַיּוֹם הַזֶּה אֲבָרֵךְ<br>",
            "🔤 <strong>Transliteração:</strong> Ha'od haze'ra bam'gurah v'ad-hagefen v'hate'enah v'harimon v'etz hazayit lo nasa min-hayom hazeh avarech<br>",
            "🇬🇷 <strong>Septuaginta:</strong> ἦ ἐπιγνωσθήσεται σπόρος; καὶ ἄμπελος καὶ συκῆ καὶ ῥόα καὶ ξύλον ἐλαίας, τὰ ξύλα ταῦτα οὐκ ἔνεγκε καρπόν; ἀπὸ τῆς ἡμέρας ταύτης εὐλογήσω<br>",
            "🇻🇦 <strong>Vulgata:</strong> Numquid iam semen in germine est? et vinea, et ficus, et malogranatum, et lignum olivae nondum floruit? Ex die hac benedicam.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>הַזֶּרַע</em> – 'semente' – semente. <em>בַּמְּגוּרָה</em> – 'celeiro' – celeiro, armazém. <em>אֲבָרֵךְ</em> – 'abençoarei' – abençoarei.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A promessa de bênção a partir daquele dia. A vide, a figueira, a romeira e a oliveira simbolizam a abundância. Cristo, a videira verdadeira (João 15:1), é a fonte da bênção.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: A bênção virá a partir daquele dia. Calvino: A obediência traz bênção. Crisóstomo: Cristo é a videira verdadeira.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Em Cristo, somos abençoados. Ele é a fonte de toda bênção.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 20</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Veio de novo a palavra do Senhor a Ageu, aos vinte e quatro dias do mês, dizendo:<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> וַיְהִי דְבַר־יְהוָה שֵׁנִית אֶל־חַגַּי בְּעֶשְׂרִים וְאַרְבָּעָה לַחֹדֶשׁ לֵאמֹר<br>",
            "🔤 <strong>Transliteração:</strong> Vayehi d'var-YHWH shenit el-Chagai b'esrim v'arba'ah lachodesh lemor<br>",
            "🇬🇷 <strong>Septuaginta:</strong> Καὶ ἐγένετο λόγος κυρίου ἐκ δευτέρου πρὸς Ἀγγαῖον τὸν προφήτην τῇ τετράδι καὶ εἰκάδι τοῦ μηνὸς λέγων<br>",
            "🇻🇦 <strong>Vulgata:</strong> Et factum est verbum Domini secundo ad Aggaeum, in die viginti quarta mensis, dicens:<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>שֵׁנִית</em> – 'de novo' – pela segunda vez, novamente. <em>לַחֹדֶשׁ</em> – 'do mês' – do mesmo mês.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A quarta mensagem de Ageu é uma palavra de encorajamento específica para Zorobabel. Deus confirma Sua escolha e promessa. Cristo, o servo escolhido, é a confirmação final da aliança de Deus (Isaías 42:1).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: A mensagem é para encorajar Zorobabel. Calvino: Deus confirma Sua escolha. Crisóstomo: Cristo é o servo escolhido.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Deus confirma Sua escolha em Cristo. Ele é o servo fiel.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 21</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Fala a Zorobabel, governador de Judá, dizendo: Farei tremer os céus e a terra;<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> אֱמֹר אֶל־זְרֻבָּבֶל פַּחַת־יְהוּדָה לֵאמֹר אֲנִי מַרְעִישׁ אֶת־הַשָּׁמַיִם וְאֶת־הָאָרֶץ<br>",
            "🔤 <strong>Transliteração:</strong> Emor el-Z'rubavel pachat-Yehudah lemor ani mar'ish et-hashamayim v'et-ha'aretz<br>",
            "🇬🇷 <strong>Septuaginta:</strong> εἶπον πρὸς Ζοροβάβελ τὸν τοῦ Σαλαθιὴλ ἐκ φυλῆς Ἰούδα λέγων· ἐγὼ σείσω τὸν οὐρανὸν καὶ τὴν γῆν<br>",
            "🇻🇦 <strong>Vulgata:</strong> Loquere ad Zorobabel ducem Iudae, dicens: Ego movebo caelum pariter et terram;<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>אֱמֹר</em> – 'Fala' – fala, dize. <em>פַּחַת</em> – 'governador' – governador. <em>מַרְעִישׁ</em> – 'farei tremer' – estremecerei.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Deus reafirma Seu poder sobre a criação, prometendo abalar os céus e a terra. Esta é uma profecia sobre o juízo e a restauração final. Cristo, o Rei que abalará todas as coisas, trará o reino eterno (Hebreus 12:26-28).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: Deus abalará a criação. Calvino: O poder de Deus é absoluto. Crisóstomo: Cristo estabelecerá o reino eterno.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Deus tem poder sobre toda a criação. Confiamos em Seu reino eterno.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 22</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> e derribarei o trono dos reinos, e destruirei a força dos reinos das nações; e derribarei os carros e os que neles andam; e os cavalos e os seus cavaleiros cairão, cada um pela espada do seu irmão.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> וְהָפַכְתִּי כִּסֵּא מַמְלָכוֹת וְהִשְׁמַדְתִּי חֹזֶק מַמְלְכוֹת הַגּוֹיִם וְהָפַכְתִּי מֶרְכָּבָה וְרֹכְבֶיהָ וְיָרְדוּ סוּסִים וְרֹכְבֵיהֶם אִישׁ בְּחֶרֶב אָחִיו<br>",
            "🔤 <strong>Transliteração:</strong> V'hafachti kise mam'lachot v'hishmad'ti chozek mam'l'chot hagoyim v'hafachti merkavah v'roch'veiha v'yardu susim v'roch'veihem ish b'cherev achiv<br>",
            "🇬🇷 <strong>Septuaginta:</strong> καὶ καταστρέψω θρόνους βασιλέων, καὶ διασκορπιῶ δύναμιν βασιλέων τῶν ἐθνῶν, καὶ καταστρέψω ἅρματα καὶ ἀναβάτας αὐτῶν, καὶ καταβήσονται ἵπποι καὶ ἀναβάται αὐτῶν, ἕκαστος ἐν ῥομφαίᾳ ἀδελφοῦ αὐτοῦ<br>",
            "🇻🇦 <strong>Vulgata:</strong> et subvertam solium regnorum, et conteram fortitudinem regni gentium; et subvertam currum et ascensorem eius; et descendent equi et ascensores eorum, vir in gladio fratris sui.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>וְהָפַכְתִּי</em> – 'derribarei' – derrubarei, virarei. <em>חֹזֶק</em> – 'força' – força, poder. <em>מֶרְכָּבָה</em> – 'carros' – carruagens.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Deus derribará os reinos das nações e destruirá seu poderio militar. A queda dos impérios é obra de Deus. Cristo, o Rei dos reis, derrubará todo poder inimigo (Apocalipse 19:11-21).<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: Deus derrubará os reinos das nações. Calvino: O poder humano é frágil. Crisóstomo: Cristo derrubará todo poder inimigo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> O poder humano é passageiro. Cristo é o Rei eterno.<br>",

            "<span style='font-size: 15px;'><strong>VERSÍCULO: 23</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Naquele dia, diz o Senhor dos Exércitos, te tomarei, ó Zorobabel, meu servo, filho de Sealtiel, diz o Senhor, e te farei como um anel de selar; porque te escolhi, diz o Senhor dos Exércitos.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
            "📜 <strong>Hebraico:</strong> בַּיּוֹם הַהוּא נְאֻם־יְהוָה צְבָאוֹת אֶקָּחֲךָ זְרֻבָּבֶל בֶּן־שַׁלְתִּיאֵל עַבְדִּי נְאֻם־יְהוָה וְשַׂמְתִּיךָ כַּחוֹתָם כִּי־בְךָ בָחַרְתִּי נְאֻם יְהוָה צְבָאוֹת<br>",
            "🔤 <strong>Transliteração:</strong> Bayom hahu n'um-YHWH tz'va'ot ekach'cha Z'rubavel ben-Shalti'el avdi n'um-YHWH v'samticha kachotam ki-v'cha vacharti n'um YHWH tz'va'ot<br>",
            "🇬🇷 <strong>Septuaginta:</strong> ἐν τῇ ἡμέρᾳ ἐκείνῃ, λέγει κύριος παντοκράτωρ, λήψομαί σε, Ζοροβάβελ τὸν τοῦ Σαλαθιὴλ, τὸν δοῦλόν μου, λέγει κύριος, καὶ θήσομαί σε ὡς σφραγῖδα, διότι σὲ ᾑρέτισα, λέγει κύριος παντοκράτωρ<br>",
            "🇻🇦 <strong>Vulgata:</strong> In die illa, dicit Dominus exercituum, assumam te, Zorobabel fili Salathiel, serve meus, dicit Dominus, et ponam te quasi signaculum, quia te elegi, dicit Dominus exercituum.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>אֶקָּחֲךָ</em> – 'te tomarei' – te tomarei, escolherei. <em>כַּחוֹתָם</em> – 'como um anel de selar' – como um anel-selo. <em>בָחַרְתִּי</em> – 'escolhi' – escolhi, elegi.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Zorobabel é escolhido e selado como um anel de selar, símbolo de autoridade e honra. Esta profecia messiânica aponta para Cristo, o Servo escolhido e selado por Deus (Isaías 42:1; Apocalipse 7:2-3). Cristo é o selo de Deus, a garantia da aliança eterna.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Rashi: Zorobabel é escolhido como um selo. Calvino: A escolha de Deus é certa. Crisóstomo: Cristo é o selo de Deus.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
            "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Em Cristo, somos selados pelo Espírito Santo (Efésios 1:13). Ele nos escolheu para sermos Seus.<br>"
        ]
    }
};