window.LIVRO_DATA = {
  nome: "Judas",
  id: "judas",
  testament: "NT",

  dados: {
    1: [
        "<span style='font-size: 15px;'><strong>VERSÍCULO: 1</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Judas, servo de Jesus Cristo, e irmão de Tiago, aos chamados, santificados por Deus Pai, e conservados por Jesus Cristo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> Ἰούδας Ἰησοῦ Χριστοῦ δοῦλος, ἀδελφὸς δὲ Ἰακώβου, τοῖς ἐν θεῷ πατρὶ ἠγαπημένοις καὶ Ἰησοῦ Χριστῷ τετηρημένοις κλητοῖς·<br>",
        "🔤 <strong>Transliteração:</strong> Ioudas Iēsou Christou doulos, adelphos de Iakōbou, tois en theō patri ēgapēmenois kai Iēsou Christō tetērēmenois klētois;<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) Ἰούδας Ἰησοῦ Χριστοῦ δοῦλος, ἀδελφὸς δὲ Ἰακώβου, τοῖς ἐν θεῷ πατρὶ ἠγαπημένοις καὶ Ἰησοῦ Χριστῷ τετηρημένοις κλητοῖς·<br>",
        "🇻🇦 <strong>Vulgata:</strong> Iudas Iesu Christi servus frater autem Iacobi his qui sunt in Deo Patre dilectis et Iesu Christo conservatis vocatis<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>Ἰούδας</em> – 'Judas' – nome hebraico (Yehudah), 'louvor'. <em>δοῦλος</em> – 'servo' – escravo, servo de Cristo. <em>ἀδελφὸς</em> – 'irmão' – irmão de Tiago (provavelmente o irmão do Senhor, Judas, mencionado em Mateus 13:55). <em>κλητοῖς</em> – 'chamados' – chamados, convocados. <em>ἠγαπημένοις</em> – 'santificados' – amados, santificados. <em>τετηρημένοις</em> – 'conservados' – guardados, preservados.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Judas se identifica como servo e irmão de Tiago. Os destinatários são chamados, amados por Deus Pai e guardados por Cristo. A tripla descrição enfatiza a segurança do crente.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Judas escreve como servo, enfatizando sua posição de humildade. A saudação é teológica: chamados, amados, guardados.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Somos chamados, amados e guardados por Deus. Isso nos dá segurança e identidade.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 2</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Misericórdia, e paz, e amor vos sejam multiplicados.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> ἔλεος ὑμῖν καὶ εἰρήνη καὶ ἀγάπη πληθυνθείη.<br>",
        "🔤 <strong>Transliteração:</strong> eleos hymin kai eirēnē kai agapē plēthyntheiē.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) ἔλεος ὑμῖν καὶ εἰρήνη καὶ ἀγάπη πληθυνθείη.<br>",
        "🇻🇦 <strong>Vulgata:</strong> misericordia vobis et pax et caritas adimpleatur<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>ἔλεος</em> – 'Misericórdia' – compaixão, piedade. <em>εἰρήνη</em> – 'paz' – paz, harmonia. <em>ἀγάπη</em> – 'amor' – amor divino. <em>πληθυνθείη</em> – 'multiplicados' – sejam multiplicados, aumentados.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A bênção tríplice: misericórdia, paz e amor. Essas são as marcas da vida cristã. A multiplicação dessas graças é o desejo de Judas.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Judas saúda com uma bênção que ecoa as epístolas pastorais, enfatizando as virtudes cristãs.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Busquemos misericórdia, paz e amor. Que elas sejam multiplicadas em nós.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 3</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Amados, procurando eu escrever-vos com toda a diligência acerca da salvação comum, tive por necessidade escrever-vos, e exortar-vos a batalhar pela fé que uma vez foi dada aos santos.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> Ἀγαπητοί, πᾶσαν σπουδὴν ποιούμενος γράφειν ὑμῖν περὶ τῆς κοινῆς σωτηρίας, ἀνάγκην ἔσχον γράψαι ὑμῖν παρακαλῶν ἐπαγωνίζεσθαι τῇ ἅπαξ παραδοθείσῃ τοῖς ἁγίοις πίστει.<br>",
        "🔤 <strong>Transliteração:</strong> Agapētoi, pasan spoudēn poioumenos graphein hymin peri tēs koinēs sōtērias, anankēn eschon grapsai hymin parakalōn epagōnizesthai tē hapax paradotheisē tois hagiois pistei.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) Ἀγαπητοί, πᾶσαν σπουδὴν ποιούμενος γράφειν ὑμῖν περὶ τῆς κοινῆς σωτηρίας, ἀνάγκην ἔσχον γράψαι ὑμῖν παρακαλῶν ἐπαγωνίζεσθαι τῇ ἅπαξ παραδοθείσῃ τοῖς ἁγίοις πίστει.<br>",
        "🇻🇦 <strong>Vulgata:</strong> carissimi omnem sollicitudinem faciens scribendi vobis de communi vestra salute necesse habui scribere vobis deprecans supercertari semel traditae sanctis fidei<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>σπουδὴν</em> – 'diligência' – zelo, esforço. <em>κοινῆς</em> – 'comum' – comum, compartilhada. <em>σωτηρίας</em> – 'salvação' – salvação. <em>ἀνάγκην</em> – 'necessidade' – necessidade, urgência. <em>παρακαλῶν</em> – 'exortar' – exortando, encorajando. <em>ἐπαγωνίζεσθαι</em> – 'batalhar' – lutar intensamente, contender. <em>ἅπαξ</em> – 'uma vez' – uma vez por todas. <em>παραδοθείσῃ</em> – 'dada' – entregue, transmitida.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A fé foi entregue de uma vez por todas. É uma batalha pela verdade. A salvação é comum a todos os crentes. A urgência é defender a fé.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Judas muda seu propósito: de escrever sobre a salvação comum para exortar à batalha pela fé.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Batalhemos pela fé. A defesa da verdade é uma responsabilidade urgente.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 4</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Porque se introduziram alguns, que já antes estavam escritos para este mesmo juízo, homens ímpios, que convertem em dissolução a graça de nosso Deus, e negam a Deus, único dominador e Senhor nosso, Jesus Cristo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> παρεισέδυσαν γάρ τινες ἄνθρωποι, οἱ πάλαι προγεγραμμένοι εἰς τοῦτο τὸ κρίμα, ἀσεβεῖς, τὴν τοῦ θεοῦ ἡμῶν χάριτα μετατιθέντες εἰς ἀσέλγειαν, καὶ τὸν μόνον δεσπότην θεὸν καὶ κύριον ἡμῶν Ἰησοῦν Χριστὸν ἀρνούμενοι.<br>",
        "🔤 <strong>Transliteração:</strong> pareisedysan gar tines anthrōpoi, hoi palai progegrammenoi eis touto to krima, asebeis, tēn tou theou hēmōn charita metatithentes eis aselgeian, kai ton monon despotēn theon kai kyrion hēmōn Iēsoun Christon arnoumenoi.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) παρεισέδυσαν γάρ τινες ἄνθρωποι, οἱ πάλαι προγεγραμμένοι εἰς τοῦτο τὸ κρίμα, ἀσεβεῖς, τὴν τοῦ θεοῦ ἡμῶν χάριτα μετατιθέντες εἰς ἀσέλγειαν, καὶ τὸν μόνον δεσπότην θεὸν καὶ κύριον ἡμῶν Ἰησοῦν Χριστὸν ἀρνούμενοι.<br>",
        "🇻🇦 <strong>Vulgata:</strong> subintroierunt enim quidam homines olim praescripti in hoc iudicium impii Dei nostri gratiam transferentes in luxuriam et solum Dominatorem et Dominum nostrum Iesum Christum negantes<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>παρεισέδυσαν</em> – 'introduziram' – entraram secretamente, infiltraram-se. <em>προγεγραμμένοι</em> – 'escritos' – escritos anteriormente, predestinados ao juízo. <em>κρίμα</em> – 'juízo' – julgamento, condenação. <em>ἀσεβεῖς</em> – 'ímpios' – sem Deus, ímpios. <em>μετατιθέντες</em> – 'convertem' – transformam, pervertem. <em>ἀσέλγειαν</em> – 'dissolução' – libertinagem, sensualidade. <em>ἀρνούμενοι</em> – 'negam' – renegam, negam.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Os falsos mestres se infiltram na igreja. Eles pervertem a graça em libertinagem e negam a Cristo. Seu juízo já está determinado.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Judas descreve a natureza e o destino dos falsos mestres: ímpios, pervertem a graça, negam a Cristo, e estão sob juízo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Estejamos alertas contra a infiltração de falsos mestres. A graça não é licença para pecar.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 5</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Portanto, quero lembrar-vos, a vós que já antes soubestes isto, que, havendo o Senhor salvo o povo da terra do Egito, destruiu depois os que não creram.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> Ὑπομνῆσαι δὲ ὑμᾶς βούλομαι, εἰδότας ὑμᾶς ἅπαξ τοῦτο, ὅτι κύριος λαὸν ἐκ γῆς Αἰγύπτου σώσας, τὸ δεύτερον τοὺς μὴ πιστεύσαντας ἀπώλεσε.<br>",
        "🔤 <strong>Transliteração:</strong> Hypomnēsai de hymas boulomai, eidotas hymas hapax touto, hoti kyrios laon ek gēs Aigyptou sōsas, to deuteron tous mē pisteusantas apōlese.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) Ὑπομνῆσαι δὲ ὑμᾶς βούλομαι, εἰδότας ὑμᾶς ἅπαξ τοῦτο, ὅτι κύριος λαὸν ἐκ γῆς Αἰγύπτου σώσας, τὸ δεύτερον τοὺς μὴ πιστεύσαντας ἀπώλεσε.<br>",
        "🇻🇦 <strong>Vulgata:</strong> commonere autem vos volo scientes semel omnia quoniam Iesus populum de terra Aegypti salvans secundo eos qui non crediderunt perdidit<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>Ὑπομνῆσαι</em> – 'lembrar' – recordar, fazer lembrar. <em>βούλομαι</em> – 'quero' – desejo, quero. <em>σώσας</em> – 'salvo' – tendo salvado. <em>ἀπώλεσε</em> – 'destruiu' – destruiu, perdeu. <em>μὴ πιστεύσαντας</em> – 'não creram' – que não creram.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> O exemplo de Israel no deserto: salvos do Egito, mas destruídos por incredulidade. A salvação não garante a perseverança sem fé.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Judas lembra o juízo sobre os incrédulos no deserto como advertência.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> A incredulidade leva ao juízo. Perseveremos na fé.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 6</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> E aos anjos que não guardaram o seu principado, mas deixaram a sua própria habitação, reservou na escuridão e em prisões eternas até ao juízo daquele grande dia.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> ἀγγέλους τε τοὺς μὴ τηρήσαντας τὴν ἑαυτῶν ἀρχήν, ἀλλὰ ἀπολιπόντας τὸ ἴδιον οἰκητήριον, εἰς κρίσιν μεγάλης ἡμέρας δεσμοῖς ἀϊδίοις ὑπὸ ζόφον τετήρηκε.<br>",
        "🔤 <strong>Transliteração:</strong> angelous te tous mē tērēsantas tēn heautōn archēn, alla apolipontas to idion oikētērion, eis krisin megalēs hēmeras desmois aidiois hypo zophon tetērēke.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) ἀγγέλους τε τοὺς μὴ τηρήσαντας τὴν ἑαυτῶν ἀρχήν, ἀλλὰ ἀπολιπόντας τὸ ἴδιον οἰκητήριον, εἰς κρίσιν μεγάλης ἡμέρας δεσμοῖς ἀϊδίοις ὑπὸ ζόφον τετήρηκε.<br>",
        "🇻🇦 <strong>Vulgata:</strong> angelos vero qui non servaverunt suum principatum sed dereliquerunt suum domicilium in iudicium magni diei vinculis aeternis sub caligine reservavit<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>ἀγγέλους</em> – 'anjos' – anjos, mensageiros. <em>τηρήσαντας</em> – 'guardaram' – guardaram, mantiveram. <em>ἀρχήν</em> – 'principado' – posição de autoridade, principado. <em>οἰκητήριον</em> – 'habitação' – morada, habitação. <em>δεσμοῖς</em> – 'prisões' – cadeias, grilhões. <em>ἀϊδίοις</em> – 'eternas' – eternas, perpétuas. <em>ζόφον</em> – 'escuridão' – escuridão, trevas. <em>τετήρηκε</em> – 'reservou' – guardou, reservou.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Os anjos caídos são um exemplo de juízo. Eles não guardaram sua posição e foram reservados para o juízo final. A desobediência angélica resulta em prisão eterna.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Judas cita anjos caídos como exemplo do juízo de Deus sobre a rebelião.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> A rebelião contra Deus leva ao juízo. Permaneçamos fiéis à nossa posição.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 7</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Assim como Sodoma e Gomorra, e as cidades circunvizinhas, que, havendo-se corrompido como eles, e ido após outra carne, foram postas por exemplo, sofrendo a pena do fogo eterno.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> ὡς Σόδομα καὶ Γόμορρα, καὶ αἱ περὶ αὐτὰς πόλεις, τὸν ὅμοιον τρόπον τούτοις ἐκπορνεύσασαι καὶ ἀπελθοῦσαι ὀπίσω σαρκὸς ἑτέρας, πρόκεινται δεῖγμα πυρὸς αἰωνίου δίκην ὑπέχουσαι.<br>",
        "🔤 <strong>Transliteração:</strong> hōs Sodoma kai Gomorra, kai hai peri autas poleis, ton homoion tropon toutois ekporneusasai kai apelthousai opisō sarkos heteras, prokeintai deigma pyros aiōniou dikēn hypechousai.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) ὡς Σόδομα καὶ Γόμορρα, καὶ αἱ περὶ αὐτὰς πόλεις, τὸν ὅμοιον τρόπον τούτοις ἐκπορνεύσασαι καὶ ἀπελθοῦσαι ὀπίσω σαρκὸς ἑτέρας, πρόκεινται δεῖγμα πυρὸς αἰωνίου δίκην ὑπέχουσαι.<br>",
        "🇻🇦 <strong>Vulgata:</strong> sicut Sodoma et Gomorrea et finitimae civitates simili modo exfornicatae et abeuntes post carnem alteram factae sunt exemplum ignis aeterni poenam sustinentes<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>Σόδομα</em> – 'Sodoma' – cidade de Sodoma. <em>Γόμορρα</em> – 'Gomorra' – cidade de Gomorra. <em>ἐκπορνεύσασαι</em> – 'corrompido' – tendo-se prostituído, corrompido. <em>σαρκὸς ἑτέρας</em> – 'outra carne' – outra carne (referência à imoralidade). <em>δεῖγμα</em> – 'exemplo' – exemplo, advertência. <em>δίκην</em> – 'pena' – punição, justiça. <em>ὑπέχουσαι</em> – 'sofrendo' – sofrendo, recebendo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Sodoma e Gomorra são exemplos do juízo de Deus sobre a imoralidade e a rebelião. O fogo eterno é a pena. A advertência é para todos os tempos.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Judas usa Sodoma e Gomorra como exemplo de juízo por imoralidade e perversão.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> A imoralidade leva ao juízo. Fujamos do pecado.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 8</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> E, todavia, semelhantemente também estes, sonhando, contaminam a sua carne, e rejeitam a dominação, e vituperam as dignidades.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> ὁμοίως μέντοι καὶ οὗτοι ἐνυπνιαζόμενοι, σάρκα μὲν μιαίνουσι, κυριότητα δὲ ἀθετοῦσι, δόξας δὲ βλασφημοῦσι.<br>",
        "🔤 <strong>Transliteração:</strong> homoiōs mentoi kai houtoi enypniazomenoi, sarka men miainousi, kyriotēta de athetousi, doxas de blasphēmousi.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) ὁμοίως μέντοι καὶ οὗτοι ἐνυπνιαζόμενοι, σάρκα μὲν μιαίνουσι, κυριότητα δὲ ἀθετοῦσι, δόξας δὲ βλασφημοῦσι.<br>",
        "🇻🇦 <strong>Vulgata:</strong> similiter et hii carnem coinquinant et dominationem spernunt et maiestates blasphemant<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>ἐνυπνιαζόμενοι</em> – 'sonhando' – sonhando, iludidos. <em>μιαίνουσι</em> – 'contaminam' – contaminam, mancham. <em>ἀθετοῦσι</em> – 'rejeitam' – rejeitam, desprezam. <em>κυριότητα</em> – 'dominação' – senhorio, domínio. <em>βλασφημοῦσι</em> – 'vituperam' – blasfemam, difamam. <em>δόξας</em> – 'dignidades' – glórias, seres celestiais.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Os falsos mestres contaminam a carne, rejeitam a autoridade e blasfemam contra seres celestiais. Seus sonhos são ilusões. O pecado é triplo: imoralidade, rebelião e blasfêmia.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Judas descreve a depravação dos falsos mestres: imorais, rebeldes e blasfemos.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Não nos contaminemos com imoralidade, rebelião ou blasfêmia. Honremos a Deus e Sua autoridade.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 9</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Mas Miguel, o arcanjo, quando contendia com o diabo, e disputava a respeito do corpo de Moisés, não ousou pronunciar juízo de maldição contra ele; mas disse: O Senhor te repreenda.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> ὁ δὲ Μιχαὴλ ὁ ἀρχάγγελος, ὅτε τῷ διαβόλῳ διακρινόμενος διελέγετο περὶ τοῦ Μωυσέως σώματος, οὐκ ἐτόλμησε κρίσιν ἐπενεγκεῖν βλασφημίας, ἀλλ᾽ εἶπεν, Ἐπιτιμήσαι σοι κύριος.<br>",
        "🔤 <strong>Transliteração:</strong> ho de Michaēl ho archangelos, hote tō diabolō diakrinomenos dielegeto peri tou Mōuseōs sōmatos, ouk etolmēse krisin epenegein blasphēmias, all' eipen, Epitimēsai soi kyrios.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) ὁ δὲ Μιχαὴλ ὁ ἀρχάγγελος, ὅτε τῷ διαβόλῳ διακρινόμενος διελέγετο περὶ τοῦ Μωυσέως σώματος, οὐκ ἐτόλμησε κρίσιν ἐπενεγκεῖν βλασφημίας, ἀλλ᾽ εἶπεν, Ἐπιτιμήσαι σοι κύριος.<br>",
        "🇻🇦 <strong>Vulgata:</strong> cum Michahel archangelus cum diabolo disputans altercaretur de Mosi corpore non est ausus iudicium inferre blasphemiae sed dixit imperet tibi Dominus<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>Μιχαὴλ</em> – 'Miguel' – arcanjo, 'quem é como Deus?'. <em>ἀρχάγγελος</em> – 'arcanjo' – arcanjo, chefe dos anjos. <em>διακρινόμενος</em> – 'contendia' – disputando, contendendo. <em>διελέγετο</em> – 'disputava' – discutia, argumentava. <em>ἐτόλμησε</em> – 'ousou' – atreveu-se. <em>ἐπενεγκεῖν</em> – 'pronunciar' – trazer, proferir. <em>βλασφημίας</em> – 'maldição' – blasfêmia, difamação. <em>Ἐπιτιμήσαι</em> – 'repreenda' – repreenda, censure.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Miguel, o arcanjo, mesmo tendo autoridade, não proferiu juízo contra o diabo, mas deixou a repreensão ao Senhor. Isso contrasta com os falsos mestres que blasfemam sem temor.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Judas usa o exemplo de Miguel para mostrar que até os anjos respeitam a autoridade divina.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Não blasfememos contra autoridades. Deixemos o juízo para Deus.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 10</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Estes, porém, blasfemam de tudo o que não sabem; e, naquilo que naturalmente conhecem, como animais irracionais, nisso se corrompem.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> οὗτοι δὲ ὅσα μὲν οὐκ οἴδασι, βλασφημοῦσι· ὅσα δὲ φυσικῶς ὡς τὰ ἄλογα ζῷα ἐπίστανται, ἐν τούτοις φθείρονται.<br>",
        "🔤 <strong>Transliteração:</strong> houtoi de hosa men ouk oidasi, blasphēmousi; hosa de physikōs hōs ta aloga zōa epistantai, en toutois phtheirontai.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) οὗτοι δὲ ὅσα μὲν οὐκ οἴδασι, βλασφημοῦσι· ὅσα δὲ φυσικῶς ὡς τὰ ἄλογα ζῷα ἐπίστανται, ἐν τούτοις φθείρονται.<br>",
        "🇻🇦 <strong>Vulgata:</strong> hi vero quaecumque ignorant blasphemant quaecumque autem naturaliter tamquam muta animalia norunt in his corrumpuntur<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>οἴδασι</em> – 'sabem' – conhecem, sabem. <em>βλασφημοῦσι</em> – 'blasfemam' – difamam, blasfemam. <em>φυσικῶς</em> – 'naturalmente' – naturalmente, instintivamente. <em>ἄλογα</em> – 'irracionais' – irracionais, sem razão. <em>ζῷα</em> – 'animais' – animais, seres vivos. <em>φθείρονται</em> – 'corrompem' – são corrompidos, perecem.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Os falsos mestres blasfemam do que não conhecem e se corrompem no que conhecem instintivamente, como animais. A ignorância e a corrupção andam juntas.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Judas descreve a irracionalidade dos falsos mestres: blasfemam do que ignoram e se corrompem no que sabem.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Busquemos o conhecimento de Deus. A ignorância leva à blasfêmia e à corrupção.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 11</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Ai deles! porque entraram pelo caminho de Caim, e foram levados pelo engano do prêmio de Balaão, e pereceram na contradição de Coré.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> οὐαὶ αὐτοῖς, ὅτι τῇ ὁδῷ τοῦ Κάϊν ἐπορεύθησαν, καὶ τῇ πλάνῃ τοῦ Βαλαὰμ μισθοῦ ἐξεχύθησαν, καὶ τῇ ἀντιλογίᾳ τοῦ Κορὲ ἀπώλοντο.<br>",
        "🔤 <strong>Transliteração:</strong> ouai autois, hoti tē hodō tou Kain eporeuthēsan, kai tē planē tou Balaam misthou exechythēsan, kai tē antilogia tou Kore apōlonto.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) οὐαὶ αὐτοῖς, ὅτι τῇ ὁδῷ τοῦ Κάϊν ἐπορεύθησαν, καὶ τῇ πλάνῃ τοῦ Βαλαὰμ μισθοῦ ἐξεχύθησαν, καὶ τῇ ἀντιλογίᾳ τοῦ Κορὲ ἀπώλοντο.<br>",
        "🇻🇦 <strong>Vulgata:</strong> vae illis quoniam via Cain abierunt et errore Balaam mercede effusi sunt et contradictione Core perierunt<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>οὐαὶ</em> – 'Ai' – ai, lamentação. <em>Κάϊν</em> – 'Caim' – Caim, assassino. <em>ἐπορεύθησαν</em> – 'entraram' – andaram, seguiram. <em>πλάνῃ</em> – 'engano' – erro, engano. <em>Βαλαὰμ</em> – 'Balaão' – profeta mercenário. <em>μισθοῦ</em> – 'prêmio' – recompensa, pagamento. <em>ἐξεχύθησαν</em> – 'foram levados' – derramaram-se, entregaram-se. <em>ἀντιλογίᾳ</em> – 'contradição' – contradição, rebelião. <em>Κορὲ</em> – 'Coré' – Coré, que se rebelou contra Moisés. <em>ἀπώλοντο</em> – 'pereceram' – pereceram, foram destruídos.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Três exemplos de rebelião: Caim (ódio e homicídio), Balaão (ganância e engano), Coré (rebelião contra autoridade). Esses são os caminhos dos falsos mestres.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Judas amaldiçoa os falsos mestres, comparando-os a três figuras bíblicas de rebelião.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Evitemos os caminhos de Caim, Balaão e Coré. A rebelião leva à perdição.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 12</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Estes são manchas em vossas festas de amor, banqueteando-se convosco, apascentando-se a si mesmos sem temor; são nuvens sem água, levadas pelos ventos de uma para outra parte; árvores murchas, infrutuosas, duas vezes mortas, desarraigadas;<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Greco (Textus Receptus):</strong> οὗτοί εἰσιν οἱ ἐν ταῖς ἀγάπαις ὑμῶν σπιλάδες, συνευωχούμενοι ὑμῖν ἀφόβως, ἑαυτοὺς ποιμαίνοντες· νεφέλαι ἄνυδροι, ὑπὸ ἀνέμων παραφερόμεναι· δένδρα φθινοπωρινά, ἄκαρπα, δὶς ἀποθανόντα, ἐκριζωθέντα·<br>",
        "🔤 <strong>Transliteração:</strong> houtoi eisin hoi en tais agapais hymōn spilades, syneuōchoumenoi hymin aphobōs, heautous poimainontes; nephelai anydroi, hypo anemōn parapheromenai; dendra phthinopōrina, akarpa, dis apothanonta, ekrizōthenta;<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) οὗτοί εἰσιν οἱ ἐν ταῖς ἀγάπαις ὑμῶν σπιλάδες, συνευωχούμενοι ὑμῖν ἀφόβως, ἑαυτοὺς ποιμαίνοντες· νεφέλαι ἄνυδροι, ὑπὸ ἀνέμων παραφερόμεναι· δένδρα φθινοπωρινά, ἄκαρπα, δὶς ἀποθανόντα, ἐκριζωθέντα·<br>",
        "🇻🇦 <strong>Vulgata:</strong> hii sunt in epulis suis maculae convivantes sine timore semet ipsos pascentes nubes sine aqua quae a ventis circumferuntur arbores autumnales infructuosae bis mortuae eradicatae<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>σπιλάδες</em> – 'manchas' – manchas, rochas submersas (perigo). <em>συνευωχούμενοι</em> – 'banqueteando-se' – banquetando-se juntos. <em>ἀφόβως</em> – 'sem temor' – sem medo. <em>ποιμαίνοντες</em> – 'apascentando' – pastoreando, alimentando. <em>ἄνυδροι</em> – 'sem água' – sem água, secas. <em>παραφερόμεναι</em> – 'levadas' – levadas, arrastadas. <em>φθινοπωρινά</em> – 'murchas' – outonais, murchas. <em>ἄκαρπα</em> – 'infrutuosas' – sem fruto. <em>δὶς</em> – 'duas vezes' – duas vezes. <em>ἐκριζωθέντα</em> – 'desarraigadas' – arrancadas pela raiz.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Os falsos mestres são perigosos e inúteis: manchas nas festas, nuvens sem água, árvores mortas e desarraigadas. Eles apascentam a si mesmos, não o rebanho.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Judas usa metáforas da natureza para descrever a inutilidade e o perigo dos falsos mestres.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Sejamos frutíferos e úteis no reino de Deus. Não sejamos manchas ou nuvens vazias.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 13</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Ondas impetuosas do mar, escumando as suas próprias abominações; estrelas errantes, para as quais está eternamente reservada a negrura das trevas.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> κύματα ἄγρια θαλάσσης, ἐπαφρίζοντα τὰς ἑαυτῶν αἰσχύνας· ἀστέρες πλανῆται, οἷς ὁ ζόφος τοῦ σκότους εἰς αἰῶνα τετήρηται.<br>",
        "🔤 <strong>Transliteração:</strong> kymata agria thalassēs, epaphrizonta tas heautōn aischynas; asteres planētai, hois ho zophos tou skotous eis aiōna tetērētai.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) κύματα ἄγρια θαλάσσης, ἐπαφρίζοντα τὰς ἑαυτῶν αἰσχύνας· ἀστέρες πλανῆται, οἷς ὁ ζόφος τοῦ σκότους εἰς αἰῶνα τετήρηται.<br>",
        "🇻🇦 <strong>Vulgata:</strong> fluctus feri maris despumantes suas confusiones sidera errantia quibus procella tenebrarum in aeternum servata est<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>κύματα</em> – 'Ondas' – ondas, vagas. <em>ἄγρια</em> – 'impetuosas' – selvagens, violentas. <em>ἐπαφρίζοντα</em> – 'escumando' – espumando, lançando espuma. <em>αἰσχύνας</em> – 'abominações' – vergonhas, obscenidades. <em>πλανῆται</em> – 'errantes' – errantes, vagantes. <em>ζόφος</em> – 'negrura' – escuridão, trevas. <em>τετήρηται</em> – 'reservada' – guardada, reservada.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Os falsos mestres são como ondas impetuosas que lançam sua vergonha, e como estrelas errantes que não têm curso fixo. Sua escuridão é eterna.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Judas continua a descrição metafórica dos falsos mestres, enfatizando sua instabilidade e destino.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Sejamos firmes na verdade, não como ondas instáveis ou estrelas errantes.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 14</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> E destes profetizou também Enoque, o sétimo depois de Adão, dizendo: Eis que é vindo o Senhor com milhares de seus santos;<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> Προεφήτευσε δὲ καὶ τούτοις ἕβδομος ἀπὸ Ἀδὰμ Ἐνώχ, λέγων, Ἰδοὺ ἦλθε κύριος ἐν ἁγίαις μυριάσιν αὐτοῦ,<br>",
        "🔤 <strong>Transliteração:</strong> Proephēteuse de kai toutois hebdomos apo Adam Enōch, legōn, Idou ēlthe kyrios en hagiais myriasin autou,<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) Προεφήτευσε δὲ καὶ τούτοις ἕβδομος ἀπὸ Ἀδὰμ Ἐνώχ, λέγων, Ἰδοὺ ἦλθε κύριος ἐν ἁγίαις μυριάσιν αὐτοῦ,<br>",
        "🇻🇦 <strong>Vulgata:</strong> prophetavit autem et his septimus ab Adam Enoch dicens ecce venit Dominus in sanctis milibus suis<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>Προεφήτευσε</em> – 'profetizou' – profetizou, falou profeticamente. <em>ἕβδομος</em> – 'sétimo' – sétimo (na linhagem de Adão). <em>Ἐνώχ</em> – 'Enoque' – Enoque, que andou com Deus (Gênesis 5:24). <em>ἦλθε</em> – 'é vindo' – veio, chegou. <em>μυριάσιν</em> – 'milhares' – miríades, dez milhares.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Enoque profetizou sobre a vinda do Senhor com seus santos para o juízo. A profecia de Enoque é citada para confirmar o julgamento dos ímpios.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Judas cita a profecia de Enoque (do livro apócrifo de Enoque) para reforçar a certeza do juízo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> O juízo é certo. O Senhor virá com Seus santos para julgar.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 15</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Para fazer juízo contra todos e condenar dentre eles todos os ímpios, por todas as suas obras de impiedade, que impiamente cometeram, e por todas as duras palavras que ímpios pecadores disseram contra ele.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> ποιῆσαι κρίσιν κατὰ πάντων, καὶ ἐλέγξαι πάντας τοὺς ἀσεβεῖς αὐτῶν περὶ πάντων τῶν ἔργων ἀσεβείας αὐτῶν, ὧν ἠσέβησαν, καὶ περὶ πάντων τῶν σκληρῶν ὧν ἐλάλησαν κατ᾽ αὐτοῦ ἁμαρτωλοὶ ἀσεβεῖς.<br>",
        "🔤 <strong>Transliteração:</strong> poiēsai krisin kata pantōn, kai elenxai pantas tous asebeis autōn peri pantōn tōn ergōn asebeias autōn, hōn ēsebēsan, kai peri pantōn tōn sklērōn hōn elalēsan kat' autou hamartōloi asebeis.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) ποιῆσαι κρίσιν κατὰ πάντων, καὶ ἐλέγξαι πάντας τοὺς ἀσεβεῖς αὐτῶν περὶ πάντων τῶν ἔργων ἀσεβείας αὐτῶν, ὧν ἠσέβησαν, καὶ περὶ πάντων τῶν σκληρῶν ὧν ἐλάλησαν κατ᾽ αὐτοῦ ἁμαρτωλοὶ ἀσεβεῖς.<br>",
        "🇻🇦 <strong>Vulgata:</strong> facere iudicium contra omnes et arguere omnes impios de omnibus operibus impietatis eorum quibus impie egerunt et de omnibus duris quae locuti sunt contra eum peccatores impii<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>κρίσιν</em> – 'juízo' – julgamento, condenação. <em>ἐλέγξαι</em> – 'condenar' – condenar, refutar. <em>ἀσεβεῖς</em> – 'ímpios' – ímpios, sem Deus. <em>ἠσέβησαν</em> – 'cometeram' – agiram impiamente. <em>σκληρῶν</em> – 'duras' – duras, severas. <em>ἁμαρτωλοὶ</em> – 'pecadores' – pecadores.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> O juízo será contra todos os ímpios por suas obras e palavras. A impiedade e as palavras duras são a base da condenação.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Judas descreve o propósito do juízo: condenar os ímpios por suas obras e palavras.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Nossas obras e palavras serão julgadas. Vivamos em piedade.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 16</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Estes são murmuradores, queixosos da sua sorte, andando segundo as suas concupiscências, e cuja boca diz coisas mui arrogantes, admirando as pessoas por causa do interesse.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> οὗτοί εἰσι γογγυσταί, μεμψίμοιροι, κατὰ τὰς ἐπιθυμίας αὐτῶν πορευόμενοι, καὶ τὸ στόμα αὐτῶν λαλεῖ ὑπέρογκα, θαυμάζοντες πρόσωπα ὠφελείας χάριν.<br>",
        "🔤 <strong>Transliteração:</strong> houtoi eisi gongystai, mempsimoiroi, kata tas epithymias autōn poreuomenoi, kai to stoma autōn lalei hyperogka, thaumazontes prosōpa ōpheleias charin.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) οὗτοί εἰσι γογγυσταί, μεμψίμοιροι, κατὰ τὰς ἐπιθυμίας αὐτῶν πορευόμενοι, καὶ τὸ στόμα αὐτῶν λαλεῖ ὑπέρογκα, θαυμάζοντες πρόσωπα ὠφελείας χάριν.<br>",
        "🇻🇦 <strong>Vulgata:</strong> hii sunt murmuratores querulosi secundum desideria sua ambulantes et os eorum loquitur superba mirantes personas quaestus causa<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>γογγυσταί</em> – 'murmuradores' – murmuradores, resmungões. <em>μεμψίμοιροι</em> – 'queixosos' – queixosos, insatisfeitos. <em>ἐπιθυμίας</em> – 'concupiscências' – desejos, paixões. <em>ὑπέρογκα</em> – 'arrogancias' – arrogantes, orgulhosas. <em>θαυμάζοντες</em> – 'admirando' – admirando, lisonjeando. <em>πρόσωπα</em> – 'pessoas' – faces, pessoas. <em>ὠφελείας</em> – 'interesse' – vantagem, lucro.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Os falsos mestres são murmuradores e insatisfeitos. Seguem seus desejos, falam com arrogância e lisonjeiam os outros para obter vantagem.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Judas descreve o caráter dos falsos mestres: insatisfeitos, desejosos, arrogantes e interesseiros.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Sejamos gratos e humildes. Evitemos a murmuração e a arrogância.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 17</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Mas vós, amados, lembrai-vos das palavras que vos foram preditas pelos apóstolos de nosso Senhor Jesus Cristo,<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> Ὑμεῖς δέ, ἀγαπητοί, μνήσθητε τῶν ῥημάτων τῶν προειρημένων ὑπὸ τῶν ἀποστόλων τοῦ κυρίου ἡμῶν Ἰησοῦ Χριστοῦ,<br>",
        "🔤 <strong>Transliteração:</strong> Hymeis de, agapētoi, mnēsthēte tōn rhēmatōn tōn proeirēmenōn hypo tōn apostolōn tou kyriou hēmōn Iēsou Christou,<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) Ὑμεῖς δέ, ἀγαπητοί, μνήσθητε τῶν ῥημάτων τῶν προειρημένων ὑπὸ τῶν ἀποστόλων τοῦ κυρίου ἡμῶν Ἰησοῦ Χριστοῦ,<br>",
        "🇻🇦 <strong>Vulgata:</strong> vos autem carissimi memores estote verborum quae praedicta sunt ab apostolis Domini nostri Iesu Christi<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>μνήσθητε</em> – 'lembrai-vos' – lembrai, recordai. <em>ῥημάτων</em> – 'palavras' – palavras, ditas. <em>προειρημένων</em> – 'preditas' – ditas anteriormente. <em>ἀποστόλων</em> – 'apóstolos' – enviados, apóstolos.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Os crentes devem lembrar das palavras dos apóstolos. A Palavra apostólica é a base da fé e da advertência.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Judas exorta os crentes a lembrar das profecias apostólicas sobre os falsos mestres.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Lembremo-nos das palavras dos apóstolos. Elas nos advertem e nos guiam.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 18</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Os quais vos diziam que nos últimos tempos haveria escarnecedores, andando segundo as suas ímpias concupiscências.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> ὅτι ἔλεγον ὑμῖν ὅτι ἐν ἐσχάτῳ χρόνῳ ἔσονται ἐμπαῖκται, κατὰ τὰς ἑαυτῶν ἐπιθυμίας πορευόμενοι τῶν ἀσεβειῶν.<br>",
        "🔤 <strong>Transliteração:</strong> hoti elegon hymin hoti en eschatō chronō esontai empaiktai, kata tas heautōn epithymias poreuomenoi tōn asebeiōn.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) ὅτι ἔλεγον ὑμῖν ὅτι ἐν ἐσχάτῳ χρόνῳ ἔσονται ἐμπαῖκται, κατὰ τὰς ἑαυτῶν ἐπιθυμίας πορευόμενοι τῶν ἀσεβειῶν.<br>",
        "🇻🇦 <strong>Vulgata:</strong> quia dicebant vobis quoniam in novissimo tempore venient inludentes secundum desideria sua ambulantes in impietatibus<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>ἐσχάτῳ χρόνῳ</em> – 'últimos tempos' – últimos tempos, fim dos dias. <em>ἐμπαῖκται</em> – 'escarnecedores' – zombadores, escarnecedores. <em>ἐπιθυμίας</em> – 'concupiscências' – desejos, paixões. <em>ἀσεβειῶν</em> – 'ímpias' – ímpias, sem Deus.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Os apóstolos profetizaram que nos últimos tempos surgiriam escarnecedores, seguindo seus próprios desejos ímpios.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Judas cita a profecia apostólica sobre a vinda de escarnecedores nos últimos dias.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Não sejamos escarnecedores. Andemos segundo o Espírito, não segundo a carne.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 19</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Estes são os que causam divisões; sensuais, que não têm o Espírito.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> οὗτοί εἰσιν οἱ ἀποδιορίζοντες, ψυχικοί, πνεῦμα μὴ ἔχοντες.<br>",
        "🔤 <strong>Transliteração:</strong> houtoi eisin hoi apodiorizontes, psychikoi, pneuma mē echontes.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) οὗτοί εἰσιν οἱ ἀποδιορίζοντες, ψυχικοί, πνεῦμα μὴ ἔχοντες.<br>",
        "🇻🇦 <strong>Vulgata:</strong> hii sunt qui se segregant animales Spiritum non habentes<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>ἀποδιορίζοντες</em> – 'causam divisões' – que se separam, causam divisões. <em>ψυχικοί</em> – 'sensuais' – naturais, carnais, sem o Espírito. <em>πνεῦμα</em> – 'Espírito' – Espírito Santo. <em>ἔχοντες</em> – 'têm' – possuem, têm.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Os falsos mestres causam divisões e são sensuais, não tendo o Espírito. A divisão e a carnalidade são marcas da ausência do Espírito.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Judas identifica os falsos mestres como divisivos e carnais, sem o Espírito Santo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Busquemos a unidade e a espiritualidade. O Espírito Santo nos une.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 20</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Mas vós, amados, edificando-vos sobre a vossa santíssima fé, orando no Espírito Santo,<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> Ὑμεῖς δέ, ἀγαπητοί, ἐποικοδομοῦντες ἑαυτοῖς τῇ ἁγιωτάτῃ ὑμῶν πίστει, ἐν πνεύματι ἁγίῳ προσευχόμενοι,<br>",
        "🔤 <strong>Transliteração:</strong> Hymeis de, agapētoi, epoikodomountes heautois tē hagiōtatē hymōn pistei, en pneumati hagiō proseuchomenoi,<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) Ὑμεῖς δέ, ἀγαπητοί, ἐποικοδομοῦντες ἑαυτοῖς τῇ ἁγιωτάτῃ ὑμῶν πίστει, ἐν πνεύματι ἁγίῳ προσευχόμενοι,<br>",
        "🇻🇦 <strong>Vulgata:</strong> vos autem carissimi superaedificantes vosmet ipsos sanctissimae vestrae fidei in Spiritu Sancto orantes<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>ἐποικοδομοῦντες</em> – 'edificando' – edificando sobre, construindo sobre. <em>ἁγιωτάτῃ</em> – 'santíssima' – santíssima, mais santa. <em>πίστει</em> – 'fé' – fé, confiança. <em>προσευχόμενοι</em> – 'orando' – orando, fazendo oração.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Os crentes devem se edificar na fé e orar no Espírito. A edificação e a oração são os meios de crescer espiritualmente.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Judas exorta os crentes a se edificarem na fé e a orarem no Espírito.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Edifiquemo-nos na fé e oremos no Espírito Santo. Isso nos fortalece.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 21</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Conservai-vos a vós mesmos no amor de Deus, esperando a misericórdia de nosso Senhor Jesus Cristo para a vida eterna.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> ἑαυτοὺς ἐν ἀγάπῃ θεοῦ τηρήσατε, προσδεχόμενοι τὸ ἔλεος τοῦ κυρίου ἡμῶν Ἰησοῦ Χριστοῦ εἰς ζωὴν αἰώνιον.<br>",
        "🔤 <strong>Transliteração:</strong> heautous en agapē theou tērēsate, prosdechomenoi to eleos tou kyriou hēmōn Iēsou Christou eis zōēn aiōnion.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) ἑαυτοὺς ἐν ἀγάπῃ θεοῦ τηρήσατε, προσδεχόμενοι τὸ ἔλεος τοῦ κυρίου ἡμῶν Ἰησοῦ Χριστοῦ εἰς ζωὴν αἰώνιον.<br>",
        "🇻🇦 <strong>Vulgata:</strong> ipsos vos in dilectione Dei servate expectantes misericordiam Domini nostri Iesu Christi in vitam aeternam<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>τηρήσατε</em> – 'Conservai' – guardai, preservai. <em>προσδεχόμενοι</em> – 'esperando' – aguardando, esperando. <em>ἔλεος</em> – 'misericórdia' – compaixão, piedade. <em>ζωὴν αἰώνιον</em> – 'vida eterna' – vida eterna.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Devemos nos guardar no amor de Deus e esperar a misericórdia de Cristo. A vida eterna é a esperança final.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Judas exorta a se manter no amor de Deus, aguardando a misericórdia de Cristo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Guardemo-nos no amor de Deus. Aguardemos a misericórdia de Cristo.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 22</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> E apiedai-vos de alguns, usando de discernimento.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> καὶ οὓς μὲν ἐλεεῖτε διακρινόμενοι,<br>",
        "🔤 <strong>Transliteração:</strong> kai hous men eleeite diakrinomenoi,<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) καὶ οὓς μὲν ἐλεεῖτε διακρινόμενοι,<br>",
        "🇻🇦 <strong>Vulgata:</strong> et hos quidem arguite iudicatos<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>ἐλεεῖτε</em> – 'apiedai-vos' – tende compaixão, mostrai misericórdia. <em>διακρινόμενοι</em> – 'usando de discernimento' – discernindo, distinguindo.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Devemos ter compaixão de alguns, mas com discernimento. A misericórdia deve ser exercida com sabedoria.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Judas instrui a ter compaixão com discernimento, distinguindo entre as situações.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Sejamos compassivos, mas com discernimento. A misericórdia deve ser guiada pela verdade.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 23</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> E salvai outros com temor, arrebatando-os do fogo, odiando até a veste manchada da carne.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> οὓς δὲ σώζετε ἐκ πυρὸς ἁρπάζοντες, οὓς δὲ ἐλεεῖτε ἐν φόβῳ, μισοῦντες καὶ τὸν ἀπὸ τῆς σαρκὸς ἐσπιλωμένον χιτῶνα.<br>",
        "🔤 <strong>Transliteração:</strong> hous de sōzete ek pyros harpazontes, hous de eleeite en phobō, misountes kai ton apo tēs sarkos espilōmenon chitōna.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) οὓς δὲ σώζετε ἐκ πυρὸς ἁρπάζοντες, οὓς δὲ ἐλεεῖτε ἐν φόβῳ, μισοῦντες καὶ τὸν ἀπὸ τῆς σαρκὸς ἐσπιλωμένον χιτῶνα.<br>",
        "🇻🇦 <strong>Vulgata:</strong> hos autem salvate de igne rapientes aliis autem miseremini in timore odientes et eam quae carnalis est maculatam tunicam<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>σώζετε</em> – 'salvai' – salvai, livrai. <em>ἁρπάζοντες</em> – 'arrebatando' – arrebatando, tirando com força. <em>φόβῳ</em> – 'temor' – temor, reverência. <em>μισοῦντες</em> – 'odiando' – odiando, detestando. <em>ἐσπιλωμένον</em> – 'manchada' – manchada, contaminada. <em>χιτῶνα</em> – 'veste' – túnica, vestimenta.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Devemos salvar alguns com temor, arrebatando-os do fogo. A veste manchada da carne deve ser odiada. A salvação é urgente e requer pureza.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Judas exorta a salvar com temor, mantendo-se puro da contaminação do pecado.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Salvemos outros com temor. Mantenhamo-nos puros da contaminação do mundo.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 24</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Ora, àquele que é poderoso para vos guardar de tropeçar, e apresentar-vos irrepreensíveis, com alegria, perante a sua glória,<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> Τῷ δὲ δυναμένῳ φυλάξαι ὑμᾶς ἀπταίστους καὶ στῆσαι κατενώπιον τῆς δόξης αὐτοῦ ἀμώμους ἐν ἀγαλλιάσει,<br>",
        "🔤 <strong>Transliteração:</strong> Tō de dynamenō phylaxai hymas aptaistous kai stēsai katenōpion tēs doxēs autou amōmous en agalliasei,<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) Τῷ δὲ δυναμένῳ φυλάξαι ὑμᾶς ἀπταίστους καὶ στῆσαι κατενώπιον τῆς δόξης αὐτοῦ ἀμώμους ἐν ἀγαλλιάσει,<br>",
        "🇻🇦 <strong>Vulgata:</strong> ei autem qui potest vos conservare sine peccato et constituere ante conspectum gloriae suae inmaculatos in exultatione<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>δυναμένῳ</em> – 'poderoso' – que pode, poderoso. <em>φυλάξαι</em> – 'guardar' – guardar, proteger. <em>ἀπταίστους</em> – 'de tropeçar' – sem tropeço, sem queda. <em>στῆσαι</em> – 'apresentar' – colocar, apresentar. <em>ἀμώμους</em> – 'irrepreensíveis' – sem mancha, irrepreensíveis. <em>ἀγαλλιάσει</em> – 'alegria' – alegria, exultação.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> Deus é poderoso para nos guardar de tropeçar e nos apresentar irrepreensíveis com alegria. A segurança do crente está no poder de Deus.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Judas conclui com uma doxologia, reconhecendo o poder de Deus para guardar e apresentar os crentes.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Confiemos no poder de Deus para nos guardar. Ele nos apresentará com alegria.<br>",

        "<span style='font-size: 15px;'><strong>VERSÍCULO: 25</strong></span><br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>TEXTO:</span></strong> Ao único Deus sábio, Salvador nosso, seja glória e majestade, domínio e poder, agora e para todo o sempre. Amém.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ORIGINAL:</span></strong><br>",
        "📜 <strong>Grego (Textus Receptus):</strong> μόνῳ σοφῷ θεῷ, σωτῆρι ἡμῶν, δόξα καὶ μεγαλωσύνη, κράτος καὶ ἐξουσία, καὶ νῦν καὶ εἰς πάντας τοὺς αἰῶνας. Ἀμήν.<br>",
        "🔤 <strong>Transliteração:</strong> monō sophō theō, sōtēri hēmōn, doxa kai megalōsynē, kratos kai exousia, kai nyn kai eis pantas tous aiōnas. Amēn.<br>",
        "🇬🇷 <strong>Septuaginta (LXX):</strong> (Forma grega do NT) μόνῳ σοφῷ θεῷ, σωτῆρι ἡμῶν, δόξα καὶ μεγαλωσύνη, κράτος καὶ ἐξουσία, καὶ νῦν καὶ εἰς πάντας τοὺς αἰῶνας. Ἀμήν.<br>",
        "🇻🇦 <strong>Vulgata:</strong> soli Deo salvatori nostro per Iesum Christum Dominum nostrum gloria magnificentia imperium et potestas ante omne saeculum et nunc et in omnia saecula amen<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>ESTUDO LEXICAL:</span></strong> <em>μόνῳ</em> – 'único' – único, somente. <em>σοφῷ</em> – 'sábio' – sábio, prudente. <em>θεῷ</em> – 'Deus' – Deus. <em>σωτῆρι</em> – 'Salvador' – Salvador, libertador. <em>δόξα</em> – 'glória' – glória, honra. <em>μεγαλωσύνη</em> – 'majestade' – grandeza, majestade. <em>κράτος</em> – 'domínio' – poder, domínio. <em>ἐξουσία</em> – 'poder' – autoridade, poder. <em>αἰῶνας</em> – 'sempre' – eras, eternidades. <em>Ἀμήν</em> – 'Amém' – assim seja.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>SIMBOLISMO:</span></strong> A doxologia final: glória, majestade, domínio e poder ao único Deus sábio, nosso Salvador. É um reconhecimento da soberania e majestade de Deus.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>COMENTÁRIOS EXEGÉTICOS:</span></strong> Judas termina com uma doxologia que exalta a Deus como sábio e Salvador.<br><hr style='border: 1px solid rgba(212, 175, 55, 0.2);'><br>",
        "<strong><span style='color: #d4af37;'>APLICAÇÃO:</span></strong> Glorifiquemos a Deus. Ele é sábio, Salvador, digno de toda glória.<br>"
    ]
  }
};